### ISSUE TITLE
最新版的比以前耗电，难道是我的错觉？

### ISSUE THREAD

**Issue by DarinJi** [shadowsocks/shadowsocks-android#1005]
之前在耗电排行里，ss基本是排在最后面，百分之1，2的电量消耗（Android7.0），最近刷机换了6.0.1的系统，耗电直升第二，比系统耗电都高。这是什么原因？
![wechatimg136](https://cloud.githubusercontent.com/assets/15549563/21138179/d75c04b6-c167-11e6-9e5a-debcbdc7ce64.jpeg)

**Comment by pexcn** [comment]
对，就是错觉

**Comment by sunsysjp** [comment]
Also i have this case,pls see the screen shot.

My phone is........
HUAWEI MATE8
Android 7.0
EMUI 5.0
Japanese language
SS Android V3.3.1
NO ROOT

But the old version dose not have this problem.

![img_20161216_003623](https://cloud.githubusercontent.com/assets/24353194/21233150/1b94dfc8-c329-11e6-89e6-bcaaafdf29ac.jpg)
