### ISSUE TITLE
Paid version without ads? 

### ISSUE THREAD

**Issue by zhovner** [shadowsocks/shadowsocks-android#1006]
Hello. Thank you for your great work.
I wan't to use client without advertisement but I can't find any paid option. 
I would be happy to buy premium ad free version for 3-7$.

**Comment by ervine** [comment]
Remove the default profile to remove ads;

**Comment by zhovner** [comment]
Thanks @ervine. But I still think this will be easy way to people who want to donate and support development.

**Comment by Mygod** [comment]
![image](https://cloud.githubusercontent.com/assets/3511321/21164713/d6492978-c1d5-11e6-8f04-1ee81114798f.png)

**Comment by pexcn** [comment]
也对，能不能提供无广告的捐赠版？（免费版依然可以移除默认配置以便去除广告

**Comment by pexcn** [comment]
@Mygod @madeye

**Comment by madeye** [comment]
No plan for this.

**Comment by Mygod** [comment]
@madeye How about adding an in app purchase option?

**Comment by madeye** [comment]
@Mygod I think in-app purchase is difficult for an open source app. It seems that there is no proper way to store the key.

**Comment by Mygod** [comment]
Have a look at how others do it: https://github.com/open-keychain/open-keychain/blob/c3c1568de1ca072f495bffc019499795f1b88332/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/HelpActivity.java#L93

**Comment by Mygod** [comment]
@madeye What do you think? Reopen this issue if you decide to integrate this feature.

**Comment by madeye** [comment]
I'm still busy with obfuscating feature, not sure if I have time to implement this.

Maybe we mark it long term feature or could you help to integrate?

**Comment by Mygod** [comment]
Sure. I'm currently working on new UI. Maybe after that.

**Comment by madeye** [comment]
Great! Thanks!

**Comment by nfjinjing** [comment]
@madeye @Mygod or you can simply forget about the checksum and public key and treat all response from iab as valid ...

**Comment by CzBiX** [comment]
As far as I know, user in some countries(such as China) can't download paid or IAP app in Google Play.
You can check the country list in [Google Help](https://support.google.com/googleplay/android-developer/table/3541286).

So, I vote for build another apk with different package name, just like [PPSSPP Gold](https://play.google.com/store/apps/details?id=org.ppsspp.ppssppgold).
Use [Product Flavors](https://developer.android.com/studio/build/build-variants.html#product-flavors) to implement this is so simple and easy.

**Comment by Mygod** [comment]
We aren't using Gradle to build the app. And I think it's not going to limit to Google Play IAP.

**Comment by Mygod** [comment]
@madeye Maybe it would be more convenient for you to implement this feature since it needs your payment info. Meanwhile I'm going to work on ACL (#1009).

**Comment by madeye** [comment]
Actually, with native AD in a cardview, users can easily remove ADs by just "removing" it. I'm wondering why we should let users spend money to remove it... It's really ridiculous.

**Comment by Mygod** [comment]
Perhaps the user wants to use the default configuration but doesn't want to see ads? Or we can just have a donate button.

**Comment by wongsyrone** [comment]
As long as I know, the default config is down for decades. Why not just replace it with dummy one.

**Comment by Mygod** [comment]
Just out of curiosity, is the default config supposed to work? @madeye

**Comment by madeye** [comment]
@wongsyrone Hehe. Actually not.

@Mygod For all the users outside China...

**Comment by Mygod** [comment]
In that case an IAP might actually be useful.

**Comment by madeye** [comment]
OK. I will try to do this. But it's still not on my top N.

**Comment by Mygod** [comment]
I wonder if N is sufficiently large though. :stuck_out_tongue:

**Comment by Yifei0727** [comment]
1 remove default config
2 remove ad
3 inapp purpose(donate) then get   your config ?
 
 还是打中文吧：
大部分人是不希望看到广告的 宁可买收费的。
这个app是靠 使用内置配置时广告的策略获取收益。而不少用户基本都是买收费的。

不排除有些人希望用免费广告版的，但我不得不说默认的服务基本不能用。
因此我认为
1. 移除内置配置和广告，起到软件无广告的作用（play商店不会显示 包含广告）
用户觉得更加“绿色”
2. 启用app内购或捐赠，然后提供配置 为开发者提供创收

**Comment by GeekerAndyLove** [comment]
In my opinion, "**removing**" is more elegant than other ways. Actually, it is the simplest way to save your time with just two clicks.

**Comment by yeweishuai** [comment]
Do not expose personal pay info on the app! We should protect the app authors!
The app is popular in China. If the GOV wants to depress the app, they can find any reason especially when the app exposes personal pay info about the author.
I suggest other ways to support authors to work on the project, like accept bit coin donate etc.

**Comment by yeweishuai** [comment]
@GeekerAndyLove  I agree with you.

**Comment by crazyyi** [comment]
@Yifei0727 默认的服务基本不能用? I don't thinks so. I have no problem using it.

**Comment by Mygod** [comment]
I think it's better not to implement this for now. As an alternative solution, keep the default configuration and click ads to help @madeye earn ad revenue.

**Comment by Mygod** [comment]
I think it's better not to implement this for now. As an alternative solution, keep the default configuration and click ads to help @madeye earn ad revenue.
