### ISSUE TITLE
Failure when long header is in HTTP request

### ISSUE THREAD

**Issue by xushichang0** [shadowsocks/shadowsocks-android#1007]
### Environment

* Android version: 5.1.1
* Device: Google Nexus 5
* Shadowsocks version: commit ID 139ea38

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 9000
* Encrypt method: TABLE
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

The NBC app fails to play any video when Shadowsocks is enabled.
To understand the reason, I capture network traces using tcpdump on the device. I find that Shadowsocks fails to forward a critical HTTP request to the server. This request has a large header.

To confirm this problem is caused by the large header, I write a simple Android app to send the HTTP request. 

The code is as follows.
```
HttpGet httpGet = new HttpGet("http://google.com/index.html");
String para = "";
for (int k = 0; k<1000;  k++) para += "a";
httppost.addHeader("Para", para);
HttpResponse response = tcpClient.execute(httppost);
```
I activate Shadownsocks. When the length of `para` is 1000, everything is fine. When the length of `para` is 2000, I get an exception.

I deactivate Shadowsocks, the program runs without exception even when the length of `para` is 2000.

### What did you expect to see?

I check the tcpdump trace when the length of `para` is 2000 (on the device I run `sudo tcpdump -i any -w /sdcard/tcpdump.pcap`).

I expect to see the following pattern.

26.26.26.1 --> google_ip
127.0.0.1:random --> 127.0.0.1:local_port
device_ip --> shadowsocks_server_ip
device_ip <-- shadowsocks_server_ip
127.0.0.1:random <-- 127.0.0.1:local_port
26.26.26.1 <-- google_ip

### What did you see instead?

In the trace I see

26.26.26.1 --> google_ip
127.0.0.1:random --> 127.0.0.1:local_port
127.0.0.1:random <-- 127.0.0.1:local_port  [RST]

The local port resets the connection without sending out the traffic to the server.

The proxy should work with any payload. I am not sure why a large HTTP header triggers such an error.

I appreciate your help to further diagnose this problem. Thanks!

**Comment by madeye** [comment]
It should be a bug of shadowsocks-libev. It's been fixed via https://github.com/shadowsocks/shadowsocks-libev/commit/31a88839d09d1ef0064706e8c0d38e4e4f21c4df.

**Comment by xushichang0** [comment]
Thanks! It is fixed now.
