### ISSUE TITLE
Duplicate acl files?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1008]
I just noticed that there's an [acl dir](https://github.com/shadowsocks/shadowsocks-libev/tree/master/acl) in shadowsocks-libev repo as well. Is it necessary to keep two copies of acls?

**Comment by madeye** [comment]
They are examples for different kind of usages, including server side ACLs.

**Comment by wongsyrone** [comment]
There are no docs for server side ACLs. You can only infer its usage based on code.

**Comment by Mygod** [comment]
Well I believe there's duplicates and inconsistencies. For example:

```
$ diff src/main/assets/acl/gfwlist.acl src/main/jni/shadowsocks-libev/acl/gfwlist.acl 
9d8
< 109.239.140.0/24
```

**Comment by wongsyrone** [comment]
It is https://github.com/shadowsocks/shadowsocks-android/commit/4400a6b81c47cc0fadd1fb54925ea0391052b2f7

**Comment by madeye** [comment]
Maybe I should remove duplicate ACLs.

**Comment by Mygod** [comment]
Maybe use a symlink to maintain backward compatibility?

Related:
https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/job/AclSyncJob.scala#L54
http://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links

**Comment by madeye** [comment]
What about sub git repo for all ACLs?

**Comment by Mygod** [comment]
And create symlink to that repo?

**Comment by madeye** [comment]
Nope. Just sub git modules for both shadowsocks-android and shadowsocks-libev like what we are doing for libraries.

**Comment by wongsyrone** [comment]
Looks better and ease to maintain

**Comment by Mygod** [comment]
But that would mean we would include unnecessary server side ACLs in the
app right?

**Comment by wongsyrone** [comment]
Why not tweak scripts to copy files needed.

**Comment by Mygod** [comment]
Why use scripts if it can be done automatically with symlink?

**Comment by wongsyrone** [comment]
My point is to make everything straightforward and clear. Others may not acknowledge they are under a symlink. Copy & paste looks more simple.

Just a suggestion.

**Comment by madeye** [comment]
@Mygod I'm not sure how to do the symbolic link. Could you open a pull request?

**Comment by Mygod** [comment]
Okay I'll get to it soon...
