### ISSUE TITLE
Add custom rules for policy route

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-android#1009]
As the support of hostname rules becomes stable, I think it's time to add custom rules feature. Any suggestion @Mygod ?

Also, I found this project is quite interesting (https://github.com/twiceyuan/SSRules). Maybe we can help to integrate it into our app.

Also open an issue in that project: https://github.com/twiceyuan/SSRules/issues/2

**Comment by AndlsH** [comment]
Wow, I've been looking forward to this feature for a loooooooooong time!

**Comment by Mygod** [comment]
Good idea but I think I need to fix #762 (2 and 3) first otherwise the user interface would become messy.

**Comment by Mygod** [comment]
Okay apparently this is much complicated that I originally thought. It's more than creating new ACL files and applying them.

So I also need to provide options to:

* Add bypass private route? (wait why is this necessary and why is it only in VPN service)
* Handle pdnsd configs?

Also, it seems remoteDns option is only used in NAT with UDP forward enabled and VPN with UDP forward disabled?

**Comment by madeye** [comment]
My suggestion is just let all the custom rules based on GFWList. In other word, this feature is only to modify GFWList to add the site you want to proxy. No need to provide too much flexibility.

**Comment by madeye** [comment]
So it's actually a customized GFWList.

**Comment by Mygod** [comment]
Okay. What about the other questions?

**Comment by madeye** [comment]
As it's based on GFWList, we don't need to touch any DNS code, all the custom rules share the same DNS config with GFWList mode.

**Comment by Mygod** [comment]
I meant

> wait why is this necessary and why is it only in VPN service

and

> Also, it seems remoteDns option is only used in NAT with UDP forward enabled and VPN with UDP forward disabled?

**Comment by madeye** [comment]
Remote DNS is also used in PDNSD? PDNSD forward DNS request to ss-tunnel, then forward to remote DNS?

If not, it should be my bug.

**Comment by madeye** [comment]
Because I cannot bypass UDP traffic in VPN mode. To support apps like airport, I have to bypass private IPs in IP level, instead of in TCP/UDP level. There is no limit in NAT mode, as shadowsocks works as a transparent proxy there.
