### ISSUE TITLE
tasker切换无kcptun的配置应用会挂

### ISSUE THREAD

**Issue by jim4ever** [shadowsocks/shadowsocks-android#1010]
我设置了两个配置，同样的服务器，一个开启了kcptun，一个没有。同时在tasker里设置了配置，连接到WiFi时启用开启kcptun的配置，连接到数据流量时使用没有kcptun的配置。现在出现一个问题，连接WiFi，正常切换，但是连接到数据流量时，就提示应用已关闭。，试着用不同服务器不开kcptun的配置，也是一样结果。
系统版本原生7.1.1,，手机Nexus6p，SS是play上下的最新版

**Comment by madeye** [comment]
I cannot reproduce your issue locally. Could you try uninstall and reinstall shadowsocks?

**Comment by jim4ever** [comment]
重新安装了以后好像好了，不太清楚之前是什么情况。多谢回复。
