### ISSUE TITLE
High battery usage （SS）

### ISSUE THREAD

**Issue by sunsysjp** [shadowsocks/shadowsocks-android#1013]
### Environment

My phone is........
HUAWEI MATE8
Android 7.0
EMUI 5.0
Japanese language
SS Android V3.3.1
NO ROOT

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:RC4-MD5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

I have this case that high battery usage when SS Android V3.3.1 is runnig.
Pls see the screen shot.
But the old version dose not have this problem.

![img_20161216_003623](https://cloud.githubusercontent.com/assets/24353194/21234270/03ce7d8c-c32d-11e6-9e37-8819eac57d5a.jpg)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#why-does-shadowsocks-consume-so-much-battery-on-android-50

**Comment by sunsysjp** [comment]
I've got it, tks @madeye
