### ISSUE TITLE
Play Store not loading on some Android device

### ISSUE THREAD

**Issue by fanthos** [shadowsocks/shadowsocks-android#1014]
Play Store on my device stopped working. After some research, I found that the app is trying to connect "services.googleapis.cn", that does not provide Google Play Service.

After adding this domain to my proxy list on my router, Play Store works great on my device.

I think it is better to add this domain to the gfwlist for now.

**Comment by madeye** [comment]
Thanks! This change would take days to take effect.

**Comment by shionphan** [comment]
hk node dose not work. switch to us node

**Comment by wzhb** [comment]
how to add it to SSR
