### ISSUE TITLE
请求将services.googleapis.cn域名添加到绕过大陆地址及大陆不可访问列表中。

### ISSUE THREAD

**Issue by fzhw88** [shadowsocks/shadowsocks-android#1016]
RT，华为的EMUI升级到5.0（Android 7.0）之后，除非全局代理，Google Play市场无法正常使用，提示“从服务器检索信息时出错[DF-DFERH-01]”

经过测试，是该ROM中的Google Play（or Google Play Service）会尝试连接services.googleapis.cn这个域名，这个域名会被解析到Google中国的ip（203.208.32+.x），而这些ip并不能正常返回数据（从抓包的情况来看是返回的空数据，不过怀疑我抓包有问题），总之是不能正常使用Play市场.

但是让这个域名走代理解析则会得到其它地区的Google IP（我用jp的代理，得到的是usa的），而且可以正常返回数据，正常使用。

我是在路由器ss条件下做的测试，我最终用hosts把services.googleapis.cn和我得到的ip绑定，从而确保自己能在路由器chnroute模式下正常使用Google Play，然而数据连接状态下，services.googleapis.cn在shadowsocks安卓端的绕开大陆和直连大陆无法访问这两种模式下都不走代理，因此只有全局能用，而全局实在不方便，因此提出如题请求。

PS：不知道是不是华为的ROM比较提别（恶心）还是以后国产自带Google框架的都会这么干……

**Comment by sunsysjp** [comment]
#1014

**Comment by fzhw88** [comment]
@sunsysjp Thanks~

**Comment by LanQ** [comment]
非常感谢 解决了我的问题

**Comment by tenhow** [comment]
感谢，确实是这个问题。华为好恶心，我用vivo自带的就没这样，oppo也没出现过

**Comment by wzhb** [comment]
我的oppo不行。。。该怎么解决？
