### ISSUE TITLE
仅代理中国无法访问的地址默认代理？

### ISSUE THREAD

**Issue by AoEiuV020** [shadowsocks/shadowsocks-android#1018]
### Environment

* Android version: 5.1.1
* Device: red mi 3
* Shadowsocks version: v3.3.1
* Last version that did not exhibit the issue (if applicable):

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
选择仅代理中国无法访问的地址，
然后通过自己买的域名访问自己的国内vps看自己ip,
http://aoeiuv020.cc/ip.php

### What did you expect to see?
通过了代理，

### What did you see instead?
不通过代理，

讲道理，仅代理中国无法访问的地址，那不就是默认不代理吗，
没记录的地址应该不代理才对，
不应该代理我的域名，

**Comment by AoEiuV020** [comment]
就算选择绕过中国地址，访问我的服务器也是一样默认代理，
讲道理，这个是怎么判定的？我的服务器是国内的，

**Comment by madeye** [comment]
Make sure you didn't enable traffic saver of Chrome.

**Comment by AoEiuV020** [comment]
OK，我的错，sorry,
