### ISSUE TITLE
复制url得到的base64少了等号=

### ISSUE THREAD

**Issue by AoEiuV020** [shadowsocks/shadowsocks-android#1020]
### Environment

* Android version: 5.1.1
* Device: red mi 3
* Shadowsocks version: v3.3.1
* Last version that did not exhibit the issue (if applicable):

### What did you do?
分享配置文件->复制url->粘贴

### What did you expect to see?
ss://cmM0LW1kNTozNzQzNTE1OEAxMzguNjguNjEuNDI6MjM0NTY=

### What did you see instead?
ss://cmM0LW1kNTozNzQzNTE1OEAxMzguNjguNjEuNDI6MjM0NTY#138.68.61.42

**Comment by AoEiuV020** [comment]
找到了，在/src/main/scala/com/github/shadowsocks/database/Profile.scala最后的Base64.NO_PADDING，
为什么要用这个标记呢？没有等号=解码到最后会出错，

**Comment by Mygod** [comment]
Decode with no padding and everything will work.

**Comment by AoEiuV020** [comment]
虽然说decode时也no padding应该就没问题，
但是命令行怎么no padding？
而且有必要nopadding吗？为了省一个字符？
shadowsocks-windows也没no padding，

**Comment by Mygod** [comment]
Perhaps we need consistency (or just say pad/no pad is both fine)? @madeye

**Comment by madeye** [comment]
The definition is without padding. However, base64 libraries can take care of both of the formats.

So, no need to worry, they are just the same.

**Comment by AoEiuV020** [comment]
嘛，我是觉得完全没必要no padding，
而且base64 -d命令会报错不知道怎么解决，

**Comment by AoEiuV020** [comment]
虽然确实可以解析，
但为什么要no padding呢？

**Comment by madeye** [comment]
`=` is not a valid character for URI. Also, it's a design choice.

**Comment by Mygod** [comment]
https://youtu.be/sasVW3debSc?t=15s
