### ISSUE TITLE
扫描二维码不支持从本地选择图片？

### ISSUE THREAD

**Issue by AoEiuV020** [shadowsocks/shadowsocks-android#1021]
### Environment

* Shadowsocks version: v3.3.1

### What did you do?
点扫描二维码，

### What did you expect to see?
一个从"相册选取二维码"的按钮，
![screenshot_2016-12-23-04-11-35-393_com tencent mm](https://cloud.githubusercontent.com/assets/11682198/21439320/fb41eed0-c852-11e6-9b23-09ca9ddb78b2.png)

### What did you see instead?
一个干净的扫描二维码界面，什么按钮都没有，

**Comment by madeye** [comment]
Use a third-party QR scanner for this purpose.

**Comment by AoEiuV020** [comment]
这我知道，我现在就是其他app扫描了复制过来，
我只是提一下这个功能可以有，，，

**Comment by madeye** [comment]
No plan for this.

**Comment by Mygod** [comment]
Actually we can implement this with new API in API 19 that doesn't require additional permissions.

**Comment by madeye** [comment]
@Mygod This one? https://developer.android.com/guide/topics/providers/document-provider.html

**Comment by Mygod** [comment]
Correct.

**Comment by madeye** [comment]
OK, we may have a try in the `drawer` branch. But I'm not sure if our current QR library can handle QR images correctly.

**Comment by Mygod** [comment]
Huh. Now we have so many stuff to do on the drawer branch. Maybe we can merge that branch after fixing more bugs and improvements and start implementing new features on new branches. :smile:

**Comment by Mygod** [comment]
On second thought why do we bother reinventing wheels like some stupid Chinese app does? We aren't developing a QR code scanner for ****'s sake.

@madeye What do you say if we go back to the good old days when we use third-party apps to scan QR codes?

**Comment by Mygod** [comment]
Yeah I'm closing this. I'm not implementing more features for this scanner like turning on/off flashlights, zooming, support for hand drawing QR codes, etc.

**Comment by madeye** [comment]
@Mygod What about use the internal QR scanner as a fallback? First, we call the external QR scanner. If failed, fallback to the internal one, which should only support basic feature.

**Comment by Mygod** [comment]
I still prefer the external-only design.

**Comment by madeye** [comment]
Hmm, I added this feature because so many Chinese users didn't have a external QR scanner installed... If I remove this feature, It would be very annoying with my inbox filled with "kindly" feedbacks...

**Comment by Mygod** [comment]
There are also a lot of users using an outdated OS (<6.0) asking what
camera permission is needed for. (btw they would have installed a more
up-to-date OS if they actually cared about security)

Just reply them with won't fix. Up till now I still don't think the
addition of this scanner feature was a good idea.

**Comment by Mygod** [comment]
Also having a general-purpose scanner app is much better than having one in
every app that does basically the same but is only willing to process one
or two types of information.

**Comment by madeye** [comment]
OK, let me remove this scanner and cross my fingers.
