### ISSUE TITLE
Question about GUI options in Shadowsocks Android

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#1022]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by KarlM256** [comment]
Android 6.0.1
Nexus 6
Current and recent versions of Shadowsocks Android.

My Questions are about the operation of the following GUI options. I will write what I believe to be answers and you only need to make corrections. Then this will be available for others.

Thanks.

Server Settings
  Profile Name:  A name string for the user identify and select profiles.
  Server:  DNS name or IP address of Shadowsocks server.
  Remote Port:  TCP/IP and UDP/IP Port number of Shadowsocks server.
  Local Port:  Shadowsocks Android listens on this port in addition to other methods (such as VPN).
                     (Is this still useful with VPN and per application settings?)
  Password:  Password (shared secret) for authentication must match the password for the
                    Shadowsocks server.
  Encrypt Method:  Encrypt method must match the method selected on the Shadowsocks server.
  One Time Authentication:  More secure method of encrypting TCP/IP and UDP/IP packets. Does
                                             not provide added DDoS protection for the server.
Feature Settings
  Route
    All:  All TCP/IP and UDP/IP traffic is routed through Shadowsocks (tunnel) to the server.
    Bypass LAN:  Local network traffic bypasses Shadowsocks and is sent directly to the local destination.
    Bypass China:  Traffic to China IP addresses is sent directly to the destination.
    Bypass LAN and China:  Both LAN and China IP addresses are sent directly to the destination.
    GFW List: IP addresses that are not blocked by the GFW are sent directly to the destination.
    China List:  Only addresses in China go through Shadowsocks. All other addresses are sent directly
                      to the destination.
    All of the above routes are defined by lists of IP addresses contained in the code. They can easily
    be inspected in the repository.
  Remote DNS:  This is the DNS server address used by the Shadowsocks server for resolving addresses.
  IPv6 Route:  If selected, IPv6 traffic is routed through the Shadowsocks (tunnel) to the server.
                     Otherwise IPv6 traffic is sent directly to the destination.
  Per-App Proxy:  Set the proxy for selected apps.
  UDP Forwarding:  If selected, UDP/IP traffic is encrypted and sent to the Shadowsocks server as UDP.
                              Otherwise, UDP traffic is sent to the Shadowsocks server wrapped in TCP.
KCP
  KCP:  Enable Shadowsocks TCP traffic transport over KCP. Otherwise KCP is not used. UDP traffic
           Always bypasses KCP.
  KCP Port:  IP port number on Shadowsocks server for KCP traffic.
  KCP Parameters (CLI):  Additional CLI parameters for KCPTUN configuration.
Misc:  All of the misc options are adequately described in the GUI.

**Comment by madeye** [comment]
Correct.

**Comment by KarlM256** [comment]
Is this still true...see above.

UDP Forwarding: If selected, UDP/IP traffic is encrypted and sent to the Shadowsocks server as UDP.
Otherwise, UDP traffic is sent to the Shadowsocks server wrapped in TCP.
