### ISSUE TITLE
Gcm connections get Fin errors on cell network after the device goes into standby

### ISSUE THREAD

**Issue by panzhitian** [shadowsocks/shadowsocks-android#1026]
### Environment

* Android version: *cm14.1*
* Device: *oneplus one*
* Shadowsocks version: *v3.3.1*

### Configuration
* [x] IPv4 server address
* [x] Client IPv4 availability
* Local port: 1080
* Encrypt method: chacha20
* Route
  * [x] All
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] Auto Connect

### What did you do?
https://github.com/shadowsocks/shadowsocks-libev/issues/1004

I have added the app to the battery optimization whitelist.

### What did you expect to see?
Gcm heartbeats keep alive after the device goes into standby.

### What did you see instead?
Gcm reconnects every 2 minutes.

![screenshot_20161224-105622](https://cloud.githubusercontent.com/assets/1327661/21464920/b857fb66-c9c7-11e6-9aac-0a647fc52218.png)

**Comment by madeye** [comment]
There are many possible reasons causing this ~120s timeout. e.g., Routers, NAT, VPS, ss-server settings. From Android client side, the timeout is 600s, which should be large enough.

Actually, don't worry about reconnection every 120s. It won't cause any problem.

**Comment by panzhitian** [comment]
The problem appears when the device uses cell network. I suspect the aggressive Doze on Android nougat limits the proxy but I have kicked it out of the battery optimization. The heartbeat alarm should have wakelock every 9 minutes when using cell network. Now it's 2 minutes there, it drains more battery, doesn't it?

**Comment by madeye** [comment]
> The heartbeat alarm should have wakelock *every 9 minutes* when using cell network.

Where is this number from?

> Now it's 2 minutes there, it drains more battery, doesn't it?

The difference should be negligible.

**Comment by panzhitian** [comment]
@madeye 
Here are some information from` /data/data/com.google.android.gsf/databases/gservices.db`.
```
gtalk_max_server_heartbeat_time|900000
gtalk_heartbeat_ping_interval_ms|1680000
gtalk_nosync_heartbeat_ping_interval_ms|540000
gtalk_active_heartbeat_ping_interval_ms|1680000
gtalk_sync_heartbeat_ping_interval_ms|1680000
```
I meet the reconnections with an occasion the heartbeat alarm counts down to zero.

![screenshot_20161224-151155](https://cloud.githubusercontent.com/assets/1327661/21465806/0d3b4816-c9ed-11e6-99c0-696642a76835.png)

**Comment by tianxingvpn** [comment]
[more](http://www.tianxingvpn.vip/software/download.html)

**Comment by fan123199** [comment]
what is the application to show net status of google play services in your screenshoot?  @panzhitian

**Comment by panzhitian** [comment]
@fan123199 dial *#*#426#*#*(426 means gcm)

**Comment by panzhitian** [comment]
close because there is no useful answer.

**Comment by immafrady** [comment]
I have the same issue. 
As a matter of fact, I think this problem actually have some effect to battery life.
When the GCM service connection is smooth (without Shadowsock in background), it should give us feedback like "Sent Client HB" every heartbeat. And then when I activate the phone after a long time, it should send something like "Doze mode is off".
But when I turn on Shadowsock, it appears the same problem as panzhitian's screenshot. And never show anything like "Doze mode is off". Therefore I suspect that timeout have a affect on Doze mode, makes Android system never enter Deep sleep.

**Comment by MichaelHu55** [comment]
same problem with me.

**Comment by gqbre** [comment]
same problem

**Comment by xydche** [comment]
same problem ,wifi too

**Comment by connectingfuture** [comment]
你们可以设置Shadowsocks(R)服务端的目录下的user config json配置文件把timeout的120改成600或者更大就不会反复唤醒耗电了。。

**Comment by JadeVane** [comment]
@connectingfuture 这个timeout改了好多遍，一直没作用，没想到原来还有一个`user-config.json`，之前一直改的是`config.json`，难怪不起作用，感谢！
