### ISSUE TITLE
选择性路由策略无法登陆 google play

### ISSUE THREAD

**Issue by wang20150419** [shadowsocks/shadowsocks-android#1028]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you see instead?

android 7.0，只有全局路由，才能使用 google play。
用其它路由策略则出现 “从服务器检索信息时出错。[DF-DFERH-01]”
使用国外VPN，用google play也无问题。

**Comment by fzhw88** [comment]
services.googleapis.cn的问题，已经反馈过
https://github.com/shadowsocks/shadowsocks-android/issues/1016#event-902603458

**Comment by wang20150419** [comment]
哦，现在用最新的3.4版本，已可以正常访问 Google play
