### ISSUE TITLE
[Tech Discussion] Add HAProxy to connect to ss-local in a different host.

### ISSUE THREAD

**Issue by dna2github** [shadowsocks/shadowsocks-android#1029]
### Environment

* Android version: *"6.0"*
* Device: *Huawei Honor 5A*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* Local port: 21080
* Encrypt method: aes-256-cfb
* Route
  * [x] All

### What did you do?
I would like to get proxy from a jump box instead of direct connect to socks server.
[internal network]: 10.0.0.2 -> socks server | ssserver
[internal network]: 10.0.0.3 -> proxy server | sslocal 0.0.0.0:21080 (two NICs, another 192.168.0.2)
[wifi network]: 192.168.0.3 -> haproxy | 192.168.0.2:21080

Then I copied haproxy repo and extract into src/main/jni folder. get haproxy compiled, copied from assets, chmod and run as haproxy -V -f haproxy.conf (do similarly as ss-local does, i.e. if password box is empty, then run haproxy instead of ss-local).

proxy server: sslocal -b 0.0.0.0 -l 21080 -s 10.0.0.2 -p 21080 -k 'xxx' -m aes-256-cfb

### What did you expect to see?

```java
// Constants.scala:
object Executable {
  ...
  val HAPROXY = "haproxy"
}
...
  val HAPROXY =
    """
      |listen socks_proxy
      |   bind 127.0.0.1:%d => 127.0.0.1:21080
      |   mode tcp
      |   server proxy %s:%d => server proxy 192.168.0.2:21080
      |   timeout connect 1m
      |   timeout client  1m
      |   timeout server  1m
    """.stripMargin

// ShadowsocksVpnService.scala:
  def startShadowsocksDaemon() {
    if (profile.password.length() == 0) {
      startShadowsocksProxy()
      return
    }
    ...

  def startShadowsocksProxy() {
    val conf = ConfigUtils
      .HAPROXY.formatLocal(Locale.ENGLISH, profile.localPort, profile.host, profile.remotePort)
    Utils.printToFile(new File(getApplicationInfo.dataDir + "/haproxy-vpn.conf"))(p => {
      p.println(conf)
    })

    val cmd = ArrayBuffer[String](getApplicationInfo.dataDir + "/haproxy"
      , "-V"
      , "-f", getApplicationInfo.dataDir + "/haproxy-vpn.conf")

    haproxyProcess = new GuardedProcess(cmd).start()
  }
```
if I run haproxy in shell directly: `haproxy -V -f haproxy.conf`

then `curl -k --socks5 localhost:21080 https://www.google.com` works (can see log from 192.168.0.2 `INFO     connecting google_ip:443 from 192.168.0.3:63870`);

### What did you see instead?

but click `start vpn`, and do the same `curl` on 192.168.0.3, 192.168.0.2 sslocal logger always says `ERROR    unknown command XX`

Just wondering how did the error occur? Any advices? :)

Thanks,
Seven

**Comment by dna2github** [comment]
in summary, so my idea is use haproxy to replace ss-local;
originally, ss-local runs saying at 127.0.0.1:21080; just replace it to haproxy runs at 127.0.0.1:21080 and the proxy will redirect tcp connection to another server. but does not work. maybe vpn mechanism stop it...

**Comment by madeye** [comment]
It won't work. `ss-local` is designed to bypass VPN Service.

**Comment by dna2github** [comment]
@madeye Thanks for your answer. Is there any way that can make this kind of sock proxy works without rooting Android? I see the droid proxy project but it requires rooted Android...

**Comment by madeye** [comment]
Why not setup haproxy on your gate server?

And nope, I don't know anything that can solve your problem.

**Comment by dna2github** [comment]
Not work either; so I have a try to modify the client app. Thanks all the same :)

**Comment by dna2github** [comment]
oh, just confirm: it is a simple problem...
haproxy is a tcp/http relay program;
to parse www.google.com, it sends udp packets...
then fails...
