### ISSUE TITLE
I have more history version of the program for everyone to download.

### ISSUE THREAD

**Issue by tianxingvpn** [shadowsocks/shadowsocks-android#1030]
I have more history version of the program for everyone to download.

Application number

* 30

Download address

* Please see the article:[vpn下载](http://www.tianxingvpn.vip/software/download.html)

**Comment by pexcn** [comment]
？？？

**Comment by tianxingvpn** [comment]
What's the problem?

**Comment by tianxingvpn** [comment]
I just want to share the resources, please do not think much!
