### ISSUE TITLE
ss手机版什么时候支持汝libev新特性obfs啊？

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-android#1031]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you expect to see?

可以在手机版使用汝的obfs

**Comment by madeye** [comment]
It's just an experimental feature. No plan to add this to Android client.

**Comment by Sherlock-Holo** [comment]
好吧，期待汝完善后添加到手机版，谢谢:)

**Comment by AmelieNet** [comment]
同期待
