### ISSUE TITLE
Shadowsocks asks me to save changes even though there aren't any

### ISSUE THREAD

**Issue by hrzhu** [shadowsocks/shadowsocks-android#1032]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*: CM14.1
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"* 3.4.4
* Last version that did not exhibit the issue (if applicable): 3.3.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [x NAT mode

Steps to reproduce:
Edit a profile, tick per-app settings and tick on and bypass mode.  Not sure if it's necessary to reproduce the bug but it's my current settings.

Now save the settings and go back to main interface. Edit a profile, tick per-app settings and then go back to main interface without changing any settings. Shadowsocks will prompt you that there're unsaved changes.

**Comment by hrzhu** [comment]
Turning some option on and off or off and on also triggers the bug, not sure if this is intended though.

**Comment by Mygod** [comment]
Yeah. Thanks for prompting me that. I was just going to fix that.

Turning an option on and off will trigger the dialog and that's the intended behavior.
