### ISSUE TITLE
新版本 drawer 背景问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1034]
新版本 drawer 背景左右两侧有一条白线，感觉怪怪的。
请问能不能换成 Google Plus 或者 Google Play android app 的默认 drawer 背景？(就是进入它的 app 未加载用户数据时候的默认背景)
![sc](https://cloud.githubusercontent.com/assets/4590439/21538948/f7a20e1a-cddc-11e6-9bc3-50ceeb2f5dfd.png)

**Comment by Mygod** [comment]
Please follow the template and add all the necessary information.

**Comment by madeye** [comment]
Which Android version?

**Comment by pexcn** [comment]
Android 5.1.1 (CyanogenMod 12.1)
Xiaomi M2S
:sweat_smile::sweat_smile:

**Comment by Mygod** [comment]
Tested on Android 5.1.1 simulator. Can't reproduce this issue. This should be a bug of Xiaomi's ROM.

Could you try [this sample app](https://play.google.com/store/apps/details?id=com.mikepenz.materialdrawer.app) and see if there are still white lines?

**Comment by pexcn** [comment]
@Mygod 这个不是 MIUI，这是 CyanogenMod --> https://github.com/cyanogenmod

**Comment by Mygod** [comment]
Hmm... Try that sample app then?

**Comment by pexcn** [comment]
额，这个 CM 自己编译的，源码在这里：https://github.com/aries-dev
刚刚试了那个 Demo, 没有问题。所以这个问题会不会是背景图片的问题？

**Comment by pexcn** [comment]
![screenshot_2016-12-29-17-11-40](https://cloud.githubusercontent.com/assets/4590439/21540383/91d28f28-cd74-11e6-9829-43b89d50a5bb.png)

补个图

**Comment by Mygod** [comment]
Try other demos. Does none of them exhibit this issue?

**Comment by pexcn** [comment]
那个 Demo 依然没有问题

**Comment by Mygod** [comment]
Could you try this commit https://github.com/shadowsocks/shadowsocks-android/commit/7e94e25d4954767cd0001f7be4ed9360e3ade33a? Or perhaps do you need me to get @madeye to build a test apk for you :stuck_out_tongue:?

**Comment by madeye** [comment]
Here it is: https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-7e94e25.apk

**Comment by pexcn** [comment]
谢谢，可惜遗憾的是依然有刚才的问题。

**Comment by Mygod** [comment]
In that case I have no idea what's wrong. Perhaps it's a ROM-specific issue. What do you think? @madeye

**Comment by pexcn** [comment]
![img_20161229_180944](https://cloud.githubusercontent.com/assets/4590439/21541519/b72575c6-cd7c-11e6-8ef0-45be6e0acbae.jpg)

**Comment by pexcn** [comment]
或许试试换个背景图片？@Mygod

**Comment by madeye** [comment]
It looks like a padding issue for low DPI devices. What's your DPI and screen resolution?

**Comment by pexcn** [comment]
1280 * 720, (320dpi)

**Comment by madeye** [comment]
Hmm, I tried on a emulator with that DPI and resolution, but failed to reproduce it...

**Comment by pexcn** [comment]
额，这就很奇怪了...

**Comment by pexcn** [comment]
会不会和这个有关：https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/layout/layout_header.xml#L9 ？

**Comment by madeye** [comment]
Could you try fir

**Comment by Mygod** [comment]
Or centerCrop?

**Comment by pexcn** [comment]
额，我没编译环境

**Comment by Mygod** [comment]
@madeye Make a test build? Or maybe try changing background image?

**Comment by madeye** [comment]
@pexcn Please try these builds:

https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-centerCrop.apk
https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-fitXY.apk

**Comment by madeye** [comment]
@pexcn Also try the solid color header background:

https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-solid.apk

**Comment by pexcn** [comment]
好的，现在手上没 320 dpi 的设备，所以今晚回去再测试～

**Comment by Kongloli** [comment]
新版本把通知的快捷操作去掉了吗？
![photo163139746169728687](https://cloud.githubusercontent.com/assets/9067951/21564152/04c79a22-cec5-11e6-82d9-9771128b64a9.jpg)

**Comment by simonsmh** [comment]
@Kongloli See #1037

**Comment by pexcn** [comment]
![screenshot_2016-12-30-20-37-58](https://cloud.githubusercontent.com/assets/4590439/21565192/89f9ecd8-ce5a-11e6-8024-350423ce1407.png)

3个新版本都测试了，都没有问题。

**Comment by Mygod** [comment]
Great! Let's use centerCrop!

**Comment by madeye** [comment]
Fixed via bc94ade
