### ISSUE TITLE
Toast Location in v3.4.0

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#1036]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: Oneplus 3 A3000
* Shadowsocks version: v3.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

Normal

### What did you do?

Normal

### What did you expect to see?

1. Toast显示位于底部信息栏上层，依次叠加（但是有可能会覆盖底部原有信息）
2. Toast显示于上部位置（bad idea）
3. Toast顶就顶吧，加个动画（Hard）
4. 预留Toast位置（Toast大小不固定）

### What did you see instead?

Toast显示有问题，点击测试时若无法链接网络，toast将底部信息栏顶出，期间没有动画过渡，感觉很突兀（粗糙）

**Comment by Mygod** [comment]
There was [an animation](https://github.com/shadowsocks/shadowsocks-android/commit/806f4e13bdef77b3f755976acdd5713f81a01b0a) for that. But it takes time to fix some bugs in that animation and I'm not planning to do that yet. Feel free to create a fork and try hunting that bug.

**Comment by Tornaco** [comment]
This is a SnackBar not a Toast I think.

**Comment by Mygod** [comment]
Fixed in beta branch. Happy anniversary issue.

**Comment by Mygod** [comment]
Fixed in beta branch. Happy anniversary issue.

**Comment by simonsmh** [comment]
Yummy! 😋 Thanks!
