### ISSUE TITLE
Quick function in Notification center in v3.4.0

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#1037]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: Oneplus 3 A3000
* Shadowsocks version: v3.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

Normal

### What did you do?

Normal

### What did you expect to see?

和3.3-一样，可以在通知栏进行停止/切换工作
即使7.x有快速磁贴可以使用，但是对于低系统版本的机子可能造成使用不变

### What did you see instead?

通知展开发现居然啥都没了。。

**Comment by Mygod** [comment]
Close button is still there for Android 6.0-. Switch is removed since you can switch profiles in the main activity now. So everything is intended.

**Comment by Sherlock-Holo** [comment]
可是这样的话，每次都要打开程序，以前那样的话不用打开程序呀，建议还是添加回去吧

Mygod <notifications@github.com>于2016年12月29日周四 18:09写道：

**Comment by Mygod** [comment]
Okay before:

1. Expand the notification. (unless you have some Xposed module to do that for you)
2. Press switch.
3. Pick a profile.

Now:

1. Tap the notification.
2. Pick a profile. (hey you can even test connection after switching!)
3. Press back.

See? The process didn't get any more complicated. Also the QuickSwitchActivity was put in the main process so everything including memory/battery cost should be as good if not better.

**Comment by simonsmh** [comment]
Yes. That's good.

Mygod <notifications@github.com>于2016年12月29日周四 18:20写道：

**Comment by whour** [comment]
@Mygod 或许应该在FAQ里面说明一下6.0+ 取消 `QuickSwitchActivity` 的原由，为更好的节省内存和电池消耗。

**Comment by Sherlock-Holo** [comment]
我也觉得这是个好主意，这样大家都能理解。而且加上这个对比：
> Okay before:

Expand the notification. (unless you have some Xposed module to do that for
you)
Press switch.
Pick a profile.
Now:

Tap the notification.
Pick a profile. (hey you can even test connection after switching!)
Press back.



bubbles <notifications@github.com>于2016年12月30日周五 09:36写道：

**Comment by ZeppLu** [comment]
@Mygod However things have changed in the latest Android 8.0 (at least on my Xperia XZ1 Compact):

![screenshot_20171021-141721](https://user-images.githubusercontent.com/17007549/31848823-e1dd9d38-b66b-11e7-91b4-3d1d0ff246c5.png)

As you can see, the notification is collapse to minimum, so now the process becomes:

1. Expand the notification.
2. Tap the notification.
3. Pick a profile.
4. Press back.
