### ISSUE TITLE
Is there a possibility to add public dns to Local DNS?

### ISSUE THREAD

**Issue by santaclausbaby** [shadowsocks/shadowsocks-android#1039]
Some local CHINA ISP make the DNS Cache Poisoning to promote Ads.  We can resolve  that by deploy a publice dns such as 114 and tencent to local dns.

**Comment by simonsmh** [comment]
Sure that's a great idea.
However most ISP have given up to this kind of DNS hijacking and use http hijacking instead. You should report it to Chinatcc.

**Comment by madeye** [comment]
Changing the local DNS won't help, as shadowsocks is already using 114 to do the local DNS resolving.

Actually the only way to avoid DNS poisoning is enabling UDP forwarding, forcing all DNS traffic forwarded to the Remote DNS you defined.
