### ISSUE TITLE
Why remove the built-in QR Code scanner?

### ISSUE THREAD

**Issue by kaneawk** [shadowsocks/shadowsocks-android#1047]
### Environment

* Android 7.1.1
* Device: Moto X Pure
* Shadowsocks version: *version code "v3.4.0"

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you expect to see?
I don't know why to remove it, I think it's a bad idea.

Use built-in QR Code scanner is very convenient when you in china, You do not need to open the play store to install "QuickMark" (Actually you can't open play store while you don't turn on the VPN, and you don't want to add profile by other ways then connect the VPN), this let me don't need to install a useless app.

### What did you see instead?
Built-in QR Code scanner has been removed.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1021

**Comment by kaneawk** [comment]
#1021 This will install tw.com.quickmark on Google Play Store.
Why not change to Barcode Scanner (ZXing Team's) like shadowsocks v2.x?

"QuickMark" uses ugly UI and have disgusting ads.
@Mygod

**Comment by Mygod** [comment]
Zxing's one doesn't support scanning image files. If you found a better one, we will be happy to change it.
