### ISSUE TITLE
Option to do DNS resolve by ssserver instead of hardcoded google dns

### ISSUE THREAD

**Issue by niulin** [shadowsocks/shadowsocks-android#1048]
While we deploy ssserver in China, the hardcoded DNS 8.8.8.8 is very unstable to use. Also using 8.8.8.8 causing failure to resolve internal hostnames within the network of ssserver. It's best to pass DNS requests directly to ssserver instead of hardcoded 8.8.8.8, just like other ss clients on windows and MacOS. If user really wants to use 8.8.8.8 to do DNS resolve, he will configure it at ssserver side.

**Comment by madeye** [comment]
1. Update to the latest version.
2. Configure the remote DNS.

**Comment by niulin** [comment]
Sorry about not following the templates.
