### ISSUE TITLE
Server information(password) protection/encryption

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-android#1049]
Now It is very easy to share the profile using qrcode. But it also means that it is also easy for other people to get all the information about the server. Thinking about the situation that you lose your phone and someone get it, your server information may be disclosed.
I think the information of the server should be protected. They should be encrypted(at lease "can be encrypted") and the client side. I think it is better to add a password protection for the profile settings and sharing.

**Comment by madeye** [comment]
My suggestion is using a phone with fingerprint sensor and full-disk encryption enabled.

If someone is already able to unlock your phone, it's almost impossible to protect your secret.
