### ISSUE TITLE
does not save/restore kcptun config

### ISSUE THREAD

**Issue by dawnfantasy** [shadowsocks/shadowsocks-android#1050]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment
Android 6
Le Max2
Shadowsocks v3.3.1
* Last version that did not exhibit the issue (if applicable): not quite sure.

### What did you do?
export to clipboard using the top-right icon and import from clipboard using right-bottom '+' button, import from clipboard. 

### What did you expect to see?
KCPTUN server configuration preserved.

### What did you see instead?
KCPTUN server configuration lost.

**Comment by madeye** [comment]
Currently kcptun is still not part of shadowsocks URI. As a result, the config of kcptun cannot be export and import.

The fix is being discussed in https://github.com/shadowsocks/shadowsocks-org/issues/27. Please wait for future updates.

**Comment by Mygod** [comment]
Closing this. Please go to that thread for further discussion.
