### ISSUE TITLE
Tmall app connetcion errors, slow...

### ISSUE THREAD

**Issue by sosmygirl** [shadowsocks/shadowsocks-android#1052]
Please read FAQ then answer these questions before submitting your issue. Thanks!

Environment

- Android version: e.g. "7.0.0_r14", more detailed description is preferred
- Device: e.g. Google Pixel XL
- Shadowsocks version: version code "v3.0.0" or commit ID "a073f85"
- Last version that did not exhibit the issue (if applicable):

Configuration

Put an x inside the [ ] that applies.

- [x ] IPv4 server address
- [ ] IPv6 server address
- [ x] Client IPv4 availability
- [ ] Client IPv6 availability

- Local port: 1080
- Encrypt method:
- [ ] One-time authentication
- Route
  - [ ] All
  - [ ] Bypass LAN
  - [ ] Bypass China
  - [x ] Bypass LAN & China
  - [ ] GFW List
  - [ ] China List
- [ ] IPv6 route
- [ ] Per-App Proxy
  - [ ] Bypass mode
- [ ] UDP Forwarding
- KCP Parameters: (leave blank if not enabled)
- [ ] Auto Connect
- [ ] TCP Fast Open
- [ ] NAT mode

What did you do?

What did you expect to see?

What did you see instead?

I have found some error in Bypass LAN & China. Tmall app have the network connection problems by ss. Usually a network delay happend , the connection speed is very slow. Turn off ss or use per-app  proxy mode just fine.

**Comment by madeye** [comment]
Please bypass these apps in the per-app mode. Taobao and Tmall have a mystery networking implementation, no one knows what happened there.

**Comment by pexcn** [comment]
@madeye @Mygod http://luojia.me/2015/07/14/114dns%E5%88%B0%E5%BA%95%E6%98%AF%E5%95%A5/ 114 DNS 似乎不太靠谱，是否能提供一个选项换成阿里 DNS: 223.5.5.5 ?
