### ISSUE TITLE
Per-App Proxy widget contains apps irrelevant to network usage

### ISSUE THREAD

**Issue by nfjinjing** [shadowsocks/shadowsocks-android#1053]
### Environment

Click the Per-App Proxy item, inside the Per-App Proxy widget.

### What did you expect to see?

Only network related apps.

### What did you see instead?

All apps.

This can probably be implemented by filtering the apps based on the condition of network permission.

**Comment by Mygod** [comment]
Be more specific and fill in all the other information.

**Comment by nfjinjing** [comment]
Details are not given because this is generally applied in all conditions. I'm closing this issue since it's actually quite trivial.

**Comment by Mygod** [comment]
You didn't include your version and FYI this feature was implemented long
ago.

**Comment by nfjinjing** [comment]
This issue is probably misunderstood. If I go into the per app proxy panel, what do I see? Well, calculator, clock, contact etc. Why would I care about setting a proxy for a calculator which doesn't use any internet at all? That's what I meant by "network related", which can probably be checked by querying the network permission field of the app package. So this issue is not about the absence of the app list, but to shorten it.

**Comment by nfjinjing** [comment]
OK, I might be wrong, sorry about that.

**Comment by nfjinjing** [comment]
Oh, it turned out I was completely wrong. Shadowsocks android really has been filtering all the network apps for a long time, sorry for the incorrect issue.
