### ISSUE TITLE
PAC可能需要更新

### ISSUE THREAD

**Issue by Pason2C** [shadowsocks/shadowsocks-android#1057]
当路由模式为非“全局”时，会导致Google Play Store出现无法连接及无法下载的问题。
主要原因是Google对新框架访问由android.clients.google.com转至services.googleapis.cn，导致googleapis.cn已GFWed，目前GFWlist已经将googleapis.cn加入至清单，PC端已经可以更新list，但SS移动貌似没有生效。不太清楚移动端的工作方式，请修复一下。

**Comment by Pason2C** [comment]
GFWList的issue 
https://github.com/gfwlist/gfwlist/issues/464#issuecomment-270840891

**Comment by zoujialing125** [comment]
从日志和网上搜索接过来看，play上不去的原因是这个打开play会被解析到这个地址services.googleapis.cn，所以上不去
