### ISSUE TITLE
请问现版本（3.3.1）是否支持android 4.4.4

### ISSUE THREAD

**Issue by angoen** [shadowsocks/shadowsocks-android#1058]
从Google play上下载的最新版本无法连接（点击小飞机没反应），并且在应用运行过程中多次提示：影梭已停止运行。

**Comment by 68a** [comment]
unsubscribe

**Comment by Mygod** [comment]
Yes since Google is still releasing security patches for 4.4 (not lower). But our customer support for Android 4.4 will probably be shit. You're welcome.

Please do submit crash reports to Google Play as we will check them when we are bored and don't have anything better to do.

**Comment by angoen** [comment]
@Mygod Open root privileges can be used after normal, and very grateful:)

**Comment by Pason2C** [comment]
Where to dowload the V.3.40 ? I could not found the link,and play store just can download the v3.31.
Thank you.
