### ISSUE TITLE
V3.4.1 自定义规则无法生效

### ISSUE THREAD

**Issue by whour** [shadowsocks/shadowsocks-android#1064]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *"7.0.0_r14"*
* Device: *Oneplus 3 A3000*
* Shadowsocks version: *version code "v3.4.1"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
* [x] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

1.  自定义一条域名规则，` (^|\.)ip\.cn$ `
2. 代理ConnectBot 终端软件， ` curl ip.cn` 返回ISP的地址。
3. 代理浏览器，访问ip.cn 返回ISP地址。

### What did you expect to see?
1. 添加一条域名，此域名应该从代理访问。

### What did you see instead?
1. 自定义规则和配置文件里面的路由选择是什么关系？
2. 自定义规则是否和路由模式有关系？

**Comment by Mygod** [comment]
You should pick custom rules as route.

**Comment by whour** [comment]
@Mygod Sorry，需要在配置文件里面选择自定义选项，就可以生效。自定义规则可以批量导入。
或许应该在FAQ里说明一下自定义规则的使用。

**Comment by whour** [comment]
@Mygod 能否在自定义规则里面增加一个搜索选项，当规则很多时删除某一条规则能够快速定位。

**Comment by Mygod** [comment]
It's ordered alphabetically.

**Comment by whour** [comment]
快速滚动条那里是有字母表排序，自定义规则有3K+的数据，通过字母表并不能快速定位域名，只能找到域名的首字母。
修改或者删除某条数据有些费时。

**Comment by whour** [comment]
在 `src/main/assets/acl/gfwlist.acl` 中有添加Telegram的地址段，但是在自定义规则中，导入规则里面并没有Telegram的地址段，手动添加正则匹配IP/CIDR
```
^((149\.154\.160\.0)(\/20))$
^((109\.239\.140\.0)(\/24))$
^((91\.108\.4\.0)(\/22))$
^((91\.108\.56\.0)(\/22))$
(^|\.)telegram\.org$
(^|\.)telegramdownload\.com$
```
Telegram依旧无法连接。

**Comment by Mygod** [comment]
You are using wrong format for subnets.

**Comment by madeye** [comment]
Try `149.154.160.0/20`.

**Comment by whour** [comment]
@madeye  `149.154.160.0/20`
这个格式添加进去会自动增加 `/`
实际生成的规则是这条 `/149.154.160.0/20` 
这样无法代理。

**Comment by Mygod** [comment]
Hmm. That should be a bug.

**Comment by Mygod** [comment]
Hmm. That should be a bug.

**Comment by whour** [comment]
在IP地址段前面新增一个空格，就不会自动增加 `/`  ，但无法代理。
