### ISSUE TITLE
新版取消了内建的二维码扫描仪吗？

### ISSUE THREAD

**Issue by yyxida** [shadowsocks/shadowsocks-android#1065]
新版取消了内建二维码扫描仪，很不方便啊，希望能不上来。
顺便问一下，新版的界面文本有没有修改的地方，有的话我会补上日语翻译，谢谢。

**Comment by whour** [comment]
有人提出前前面的版本无法扫描本地二维码图片，因为前面使用的Zxing组件不支持，就先取消了，后面会增加，详细见
#1021
#1047
可以先多关注已关闭的Issue。

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android#translate
