### ISSUE TITLE
自定义规则 当屏幕旋转时app崩溃

### ISSUE THREAD

**Issue by Yifei0727** [shadowsocks/shadowsocks-android#1066]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Nexus 5
* Shadowsocks version: v3.4.1

新版本UI 在 "自定义规则"页面，旋转屏幕时
应用程序崩溃并退出。
```很抱歉，"影梭"已停止运行```

**Comment by whour** [comment]
在横屏模式下，打开程序，切换到自定义规则可以进去，但是自动旋转时程序闪退，但是并没有退出，代理工作正常。
Android version: 7.0.0
Device: Oneplus 3 A3000
