### ISSUE TITLE
自定义规则能否添加导出和从网址导入，并兼容Surge规则

### ISSUE THREAD

**Issue by wilhexm** [shadowsocks/shadowsocks-android#1069]
终于加上自定义规则了，非常感谢！有两个建议：
1. 可否添加本地txt规则文件的导入导出，以及从网址导入规则？
2. 能否兼容surge类规则，并且像surge那样支持对自定义规则reject/direct/proxy？

### Environment

* Android version: 7.1.1
* Device: Google Pixel XL
* Shadowsocks version: 3.4.1

**Comment by Mygod** [comment]
@madeye You decide. (I don't use custom rules anyways.)

**Comment by madeye** [comment]
@Mygod Importing from URL looks useful. But I don't think importing from file is necessary, as you have to find a way to import that file to your phone first...

@wilhexm No plan to support surge rules.

**Comment by Mygod** [comment]
Example URL?

**Comment by whour** [comment]
除了没有reject的规则，direct和proxy在配置文件里面的路由规则里面都有详细的划分。
reject可以拒绝电信http劫持么？

**Comment by madeye** [comment]
For example: `https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/acl/gfwlist.acl`. Just ignore any comment line and section line.

**Comment by wilhexm** [comment]
作为一个刷机党，希望能导出规则到本地txt，刷完后再导入恢复

**Comment by Mygod** [comment]
Use Titanium backup or other similar softwares to back up this app's data.

**Comment by wilhexm** [comment]
@Mygod 部分机器root不能或者root影响保修，无法使用ti备份这样的app

**Comment by Mygod** [comment]
Who said you need root to backup app's data? Have you tried: https://play.google.com/store/apps/details?id=com.koushikdutta.backup

**Comment by wilhexm** [comment]
@Mygod sorry！我out了，我晚点试试这个，谢谢！

**Comment by Mygod** [comment]
You're welcome. AFAIK it's a wrapper of `adb backup`. Also since Android 6.0 IIRC app data can be restored automatically.

**Comment by wilhexm** [comment]
@whour 能支持reject的话，至少可以屏蔽部分广告，如果知道运营商的劫持指向服务器，应该可以部分解决劫持问题。

**Comment by Mygod** [comment]
Too lazy to implement. Just copy and import from clipboard.

**Comment by nameldk** [comment]
Does it support reject rule now?
