### ISSUE TITLE
v3.4.1 crush when using custom rules if it was connected

### ISSUE THREAD

**Issue by thune-xiaobai** [shadowsocks/shadowsocks-android#1071]
### Environment

* Android version: Mokee71.1 Android version:7.1.1_r13
* Device: Xiaomi 4C
* Shadowsocks version: V3.4.1

### What did you do?
Crush when using 'Custome rules' if the shadowsocks was connected

log:
![screenshot_2017-01-09_20-47-15](https://cloud.githubusercontent.com/assets/3123725/21767063/de158778-d6ac-11e6-8b43-09b276340f0c.png)

**Comment by Mygod** [comment]
Already fixed with 6d536a901b9bfce23f26efc6c09068cc710908bf.
