### ISSUE TITLE
无法进入自定义列表

### ISSUE THREAD

**Issue by iciness** [shadowsocks/shadowsocks-android#1074]
### Environment

* Android version: 7.1.1 NMF26V
* Device: Google Pixel XL
* Shadowsocks version: 3.4.1

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:AES-256-CFB
* [x] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: 
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
点击菜单中的自定义列表

### What did you see instead?
Shadowsocks has stopped

![screenshot_20170110-115805](https://cloud.githubusercontent.com/assets/4505686/21793969/0f0b4208-d731-11e6-9d34-101b5532f967.png)

**Comment by Mygod** [comment]
#1071.
