### ISSUE TITLE
编译报错，求解答

### ISSUE THREAD

**Issue by lnterface** [shadowsocks/shadowsocks-android#1078]
编译环境：
JDK 1.8
SBT 0.13.13
Go 1.7.4
Android SDK
       Build Tools 25.0.2
       Android Support Repository and Google Repository (see build.sbt for version)
Android NDK r13b
-----------
报错信息如下：
d# sbt native-build clean android:package-release
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[info] Loading project definition from /root/shadowsocks-android/project
[info] Updating {file:/root/shadowsocks-android/project/}shadowsocks-android-build...
[info] Resolving com.android.tools#annotations;25.2.0 ...
/root/sbt/bin/sbt-launch-lib.bash: line 41:  9456 Killed                  "$@"

**Comment by Mygod** [comment]
This issue probably doesn't relate to this project. You may have a damaged sbt, etc. Please try to resolve it yourself. 😓
