### ISSUE TITLE
终于加入自定义规则了，能够加入这个规则

### ISSUE THREAD

**Issue by heartacker** [shadowsocks/shadowsocks-android#1079]
能否加入对easylist 的支持
毕竟广告还是太讨人厌了，

我觉得 shadowsocks 要是支持easylist的话 就好了，手机就在也没有烦人的广告了，

谢谢 
万分感激。
https://easylist.to/

**Overview**

> The EasyList filter lists are sets of rules originally designed for Adblock that automatically remove unwanted content from the internet, including annoying adverts, bothersome banners and troublesome tracking. The filter lists are currently maintained by four authors, Fanboy, MonztA, Famlam and Khrin, who are ably assisted by an ample forum community.
> 
> The links listed below allow you to select filter lists for use in your browser provided that you are using a compatible ad blocker (tested with Adblock Plus, AdBlock, uBlock Origin and uBlock). Furthermore, EasyPrivacy Tracking Protection List is available for Internet Explorer 9 and higher.

**Comment by Mygod** [comment]
Easylist is meant to used by browsers. It's not possible to apply on Shadowsocks.
