### ISSUE TITLE
Connection test should connect to China LAN when using Chinalist

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1080]
The problem is which domain should we use?

Requirements: China IP, accepts HTTPS, returns HTTP 204 or 200 with no content.

* https://connect.rom.miui.com/generate_204
* https://www.v2ex.com/generate_204
* https://http204.sinaapp.com/generate_204 (unknown source)
* https://iwch.me/generate_204 (unstable)
* https://www.qualcomm.cn/generate_204

qualcomm.cn is the fastest one for me (smallest average ping).

**Comment by madeye** [comment]
Qualcomm.cn looks better.

**Comment by Mygod** [comment]
If anyone has a better domain, feel free to comment. I think we'll keep this issue open for at least 24h.

**Comment by simonsmh** [comment]
developers.google.cn is a better one IMO.
it's official and works well.

**Comment by Mygod** [comment]
I can't connect to *.google.cn despite it's located in China.

**Comment by simonsmh** [comment]
Which ISP are you using? It should be impossible.
Google.cn still works pretty well and providing services such as translations or maps.

**Comment by Mygod** [comment]
google.cn still works but you can't connect to it with HTTPS.

Some additional tests show that `www.v2ex.com` and `http204.sinaapp.com` are fastest.

```
$ time curl https://connect.rom.miui.com/generate_204; time curl https://www.v2ex.com/generate_204; time curl https://http204.sinaapp.com/generate_204; time curl https://www.qualcomm.cn/generate_204

real	0m0.431s
user	0m0.028s
sys	0m0.000s

real	0m0.316s
user	0m0.020s
sys	0m0.000s

real	0m0.314s
user	0m0.020s
sys	0m0.000s

real	0m0.489s
user	0m0.028s
sys	0m0.000s
```

**Comment by simonsmh** [comment]
```
$ curl https://developers.google.cn/generate_204 -vv
*   Trying 203.208.43.79...
* TCP_NODELAY set
* Connected to developers.google.cn (203.208.43.79) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /data/data/com.termux/files/usr/etc/tls/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.google.cn
*  start date: Jan  4 10:38:23 2017 GMT
*  expire date: Mar 29 10:18:00 2017 GMT
*  subjectAltName: host "developers.google.cn" matched cert's "*.google.cn"
*  issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f95293040)
> GET /generate_204 HTTP/1.1
> Host: developers.google.cn
> User-Agent: curl/7.52.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 204
< date: Fri, 13 Jan 2017 07:06:08 GMT
< alt-svc: quic=":443"; ma=2592000; v="35,34"
<
* Curl_http_done: called premature == 0
* Connection #0 to host developers.google.cn left intact
```
Using other service provider we may face other unpredictable problem. Last year captive.v2ex.co had met a SSL license problem which made it down for one day. It's never a good idea to choose unofficial provider instead the official one.
But it's up to you. 🤣

**Comment by Mygod** [comment]
Using developer.google.cn may also be unstable, at least for my case.

```
$ time curl https://developer.google.cn/generate_204
^C

real	1m21.303s
user	0m0.004s
sys	0m0.008s
```

So maybe use shadowsocks.org? @madeye

**Comment by madeye** [comment]
Using `shadowsocks.org` is definitely a bad idea... It could be one of the most unstable sites in China...

I suggest use `qualcomm.cn`, as their Chinese engineer need to run CTS. 😄

**Comment by kyze8439690** [comment]
what about ```curl --head http://www.google.cn/generate_204``` ?

**Comment by Mygod** [comment]
It's 2017 and WE NEED HTTPS!

**Comment by simonsmh** [comment]
BTW Google has changed the authentication method, now they're different between 6.x-, 7.0+ and 7.1.1. The 6.x- one did not use https method. So some of them may not work according to the users' report.
How would you support these platform at the same time?

**Comment by kyze8439690** [comment]
```curl --head https://www.google.cn/generate_204```

Also working

**Comment by Mygod** [comment]
@simonsmh This is platform independent. We do the connection test on our own.

@kyze8439690 On my end only HTTP works, so let's not use them for safety.

**Comment by him007** [comment]
> $ curl --head https://www.google.cn/generate_204
HTTP/1.1 204 No Content
Content-Length: 0
Date: Fri, 13 Jan 2017 13:48:01 GMT
Alt-Svc: quic=":443"; ma=2592000; v="35,34"

> $ curl --head https://www.gstatic.cn/generate_204
HTTP/1.1 204 No Content
Content-Length: 0
Date: Fri, 13 Jan 2017 13:48:11 GMT
Alt-Svc: quic=":443"; ma=2592000; v="35,34"

> $ curl --head https://developers.google.cn/generate_204
HTTP/1.1 204 No Content
Content-Length: 0
Date: Fri, 13 Jan 2017 13:49:03 GMT
Alt-Svc: quic=":443"; ma=2592000; v="35,34"

> $ curl  --head https://www.qualcomm.cn/generate_204
HTTP/1.1 204 No Content
Server: Apache
ETag: "d41d8cd98f00b204e9800998ecf8427e:1469502652"
Last-Modified: Tue, 26 Jul 2016 03:10:52 GMT
Accept-Ranges: bytes
Content-Length: 0
Content-Type: text/html
Date: Fri, 13 Jan 2017 13:52:07 GMT
Connection: keep-alive

> $ curl --head https://204.ustclug.org/generate_204
HTTP/1.1 204 No Content
Server: nginx
Date: Fri, 13 Jan 2017 13:49:26 GMT
Connection: keep-alive

**Comment by Mygod** [comment]
```
$ time curl https://204.ustclug.org/generate_204

real	0m10.192s
user	0m0.024s
sys	0m0.000s
```

And I can't connect to any domain of Google China via HTTPS.

**Comment by him007** [comment]
My ISP is Shenzhen Unicom and works well. Maybe your ISP had do something.

**Comment by Mygod** [comment]
Well I don't care if I can't access Google China. I'm just making a point that we can't use it.
