### ISSUE TITLE
Install failed on OPPO R9s

### ISSUE THREAD

**Issue by bt4wang** [shadowsocks/shadowsocks-android#1081]
### Environment

* Android version: 6.0.1(ColorOS V3.0)
* Device: OPPSR9s
* Shadowsocks version: v3.2.8~v3.4.1
* v3.2.7

### What did you do?

I was tried to install the latest version of SS on my R9s, my phone just told me the package was damaged(of course not). Tried to install via google play, reported error too. This issue occured with release v3.2.8~v3.4.1, the last installable version is 3.2.7.

**Comment by Mygod** [comment]
This is a bug of your ROM. Fortunately the next release will remove the use of that buggy feature.

@madeye Time for a new pre-release?

**Comment by madeye** [comment]
OK @Mygod

**Comment by Mygod** [comment]
@madeye Also maybe we should implement new features on a develop branch and make bug fixes on master branch? Fix for custom rule crash has been committed a long time ago but not been released.

**Comment by madeye** [comment]
@Mygod Yes, especially for SIP002 and SIP003 related changes.

**Comment by Mygod** [comment]
Try 3.4.2.

**Comment by bt4wang** [comment]
@Mygod Thanks a lot. Version 3.4.2 works fine.
