### ISSUE TITLE
列表项的 bug?

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1082]
![screenshot_2017-01-12-23-36-16](https://cloud.githubusercontent.com/assets/4590439/21896124/2e1fea72-d920-11e6-8e6f-c6cf233cc356.png)

新建多个配置文件，然后选中第二项，按返回键退出，再打开本应用程序，这时候第一项会显示成第三项这样，你再点击一下第一项，就会变成图片这样的。请问这是设计成这样还是 bug?

**Comment by Mygod** [comment]
@madeye I'm assigning you this since I'm busy with #1073 now. :P

**Comment by madeye** [comment]
Please follow the template to list your device details.

**Comment by pexcn** [comment]
Google Nexus 5, 480dpi, CyanogenMod 13.0, Android 6.0.1

**Comment by madeye** [comment]
I tried it on some Android 6.0 devices, but failed to reproduce it. Is it an issue of CyanogenMod?

**Comment by pexcn** [comment]
@madeye 我想应该不是，我在 CyanogenMod 13.0 和 CyanogenMod 12.1 上都试过，都能复现该问题。

**Comment by Mygod** [comment]
Unable to reproduce this on Lineage OS 14.1.

**Comment by pexcn** [comment]
@Mygod 但是之前的版本没有这个 bug 的，最近两个版本就这样了。

**Comment by madeye** [comment]
I guess I fixed it via 52286b9.

**Comment by Mygod** [comment]
A test build? @madeye

**Comment by madeye** [comment]
Please try https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-44b47e6.apk

**Comment by pexcn** [comment]
@madeye 链接 404 ...

**Comment by madeye** [comment]
@pexcn Try again?

**Comment by pexcn** [comment]
@madeye 可以了，测试后已经修复。
