### ISSUE TITLE
Small question and enhancement request

### ISSUE THREAD

**Issue by CaesarW** [shadowsocks/shadowsocks-android#1084]
### Environment

* Android version: 7.0
* Device: Sony Xperia X Performance
* Shadowsocks version: 3.4.2

Q: Does the latest version support shadowsocksr's protocol and mix method? If not, hope to add support for shadowsocksr. Thx!
Request: can you add a theme color adjust option in settings? People may prefer different colors and they can adjust it according to their personal preference. Thx a lot!

**Comment by Mygod** [comment]
A: No. Use a Shadowsocks R client instead.

Response: No unless you pay me. A lot.
