### ISSUE TITLE
新版本似乎耗电量有所增加

### ISSUE THREAD

**Issue by zxq1002** [shadowsocks/shadowsocks-android#1085]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: One Plus 3
* Shadowsocks version: 3.4.2
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
查看系统耗电统计。

### What did you expect to see?
原先版本耗电排名一般比较靠后（小于3%）。

### What did you see instead?
最近排名都在第一位（5%左右）

**Comment by whour** [comment]
Try 3.4.2
https://github.com/shadowsocks/shadowsocks-android/releases/tag/v3.4.2

**Comment by whour** [comment]
Oneplus 3
Android 7.0.0
Version V3.4.2
使用2小时26分，耗电429毫安时，耗电比率15%。

**Comment by Mygod** [comment]
See #893 and FAQ.

**Comment by Mygod** [comment]
See #893 and FAQ.
