### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 6ge** [shadowsocks/shadowsocks-android#1088]
### Environment

* Android version: 4.4.2
* Device: Samsung
* Shadowsocks version: v3.4.2
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
I connected a server

### What did you see instead?
![bandpix_2017-01-22_174531_190](https://cloud.githubusercontent.com/assets/25245796/22181635/a4a976b8-e055-11e6-9b86-140114d47b0f.jpg)
连接服务器后出现了如图所示的错误：Error running exec()。
安卓客户端是3.4.2版本，改用旧版本则正常。
图上的服务器信息已被图片处理软件抹去。

**Comment by madeye** [comment]
Could you try uninstalling and reinstalling the apk?

**Comment by Mygod** [comment]
Attach logcat if possible.

**Comment by 6ge** [comment]
@madeye
Of course!


@Mygod
安卓手机在哪找logcat？

**Comment by 6ge** [comment]
有一点很奇怪，在我的另一部手机上使用3.4.2版本影梭就没有任何问题，配置文件完全是一模一样的。

**Comment by llkkzz111** [comment]
之前也碰到过，好像是手机的问题，具体是忘记需要开启飞行模式 还是 重启 之后就解决了

**Comment by 6ge** [comment]
@llkkzz111
无用，依然如故。

**Comment by 6ge** [comment]
另外，我还遇到了这种情况。
![screenshot_2017-01-22-12-28-24-01](https://cloud.githubusercontent.com/assets/25245796/22180143/8d467282-e02d-11e6-9d2b-a03f167a176b.jpeg)

**Comment by llkkzz111** [comment]
最下面 有一个 重置   你可以试试

**Comment by 6ge** [comment]
@llkkzz111
没用
没用
没用
（重要的事情说三遍）

**Comment by 6ge** [comment]
@madeye @Mygod
没人鸟我？

**Comment by Mygod** [comment]
Did you install this app on external storage/SD card?

**Comment by 6ge** [comment]
@madeye @Mygod
哟呵！安装到内部就正常了。之前的旧版本安装到外部是正常的，为何新版本就改了呢？

**Comment by Mygod** [comment]
This app won't work with external storage which is already replaced by adoptable storage in Android 6.0. Please don't attempt to use some workaround and force moving this app.

**Comment by 6ge** [comment]
安装到外部是为了给内部空间腾地的，毕竟内部空间是有限的嘛～

**Comment by 6ge** [comment]
@Mygod
应该在Readme自述里面写上“不能安装到外部”之类的说明吧？

**Comment by Mygod** [comment]
This app doesn't support that feature. If you can, you or your ROM has applied some kind of hack to make it work.

**Comment by 6ge** [comment]
@Mygod
我不会hack。
