### ISSUE TITLE
UDP forwarding doesn't seem to work

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1090]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: bacon
* Shadowsocks version: b3bab982a87af87db1102d95d7194db94cc83f1b
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] UDP Forwarding
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

1. Connect with UDP forwarding on;
2. Connect with plugin KCP.

### What did you expect to see?

If 2 works (which implies that I have a working UDP connection), 1 should work as well.

### What did you see instead?

2 works while 1 fails.

**Comment by madeye** [comment]
It's quite tricky here. To make UDP and kcptun both work, you have to add additional parameters to `plugin_opts`. For example:

On the server

```
ss-server -c config.json --plugin kcp-server -s 443 --plugin-opts "listen=0.0.0.0:444" -u
```

On the client

```
ss-local -c config.json --plugin kcp-local --plugin-opts "remoteaddr=server_ip:444" -u
```

**Comment by madeye** [comment]
And we may add this to FAQ.

**Comment by Mygod** [comment]
I meant:

1. UDP on and KCP off;
2. UDP off and KCP on.

And I'm running kcptun at server side independently.

**Comment by madeye** [comment]
Hmm.. I tried UDP forwarding locally, and it works well... Any chance it's a network issue?

**Comment by Mygod** [comment]
Wait it turns out I have never set up UDP forwarding on my server side... Why do I remember it used to work? Never mind...

**Comment by Mygod** [comment]
Hmm and I don't think it's necessary to add that to FAQ since SIP003 doesn't support UDP for now.

**Comment by coolicer** [comment]
@madeye 先启动ss-server，再启动kcp行不行。

**Comment by madeye** [comment]
@coolicer Yes, it also works.

**Comment by coolicer** [comment]
@madeye 还是有问题的。
kcp我这样启动的
./kcp_server -l 0.0.0.0:444  -t MY_SERVER_IP:PORT  

然后android的configure是这样:
remoteaddr=server_ip:444;

**Comment by Kein** [comment]
After a numerous tests I came to the same conclusion and I think this issue needs to be reopened. Here is a quick example with the same proxy (ProxyMain) on desktop and on Android:

**Dekstop:**
Firefox is setup to use ProxyMain shadowsock proxy and "Send DNS over proxy" is enabled. Result at https://dnsleaktest.com/ - proy's local DNS is used:
![image](https://user-images.githubusercontent.com/623756/73288156-87e18a00-420b-11ea-8858-639ce5ebfa94.png)

**Android:**
* Global VPN mode, no per-app rules
* Send DNS over UDP enabled
* Remote DNS is 1dot1dot1dot1dot.cloudflare0dns.com
* No plugins

Result from DNSLeak - All dns' servers are Cloudflare for the EXACT same ProxyMain shadowsocks proxy.
