### ISSUE TITLE
DNS servers

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#1093]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Motorola G4 Plus
* Shadowsocks version: 3.3.1
* Last version that did not exhibit the issue (if applicable): unknown

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-128-CTR
* [x] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Disable DNS server on home network.
Try Check Connectivity from within the application.
### What did you expect to see?
Shadowsocks-Android use Google DNS (8.8.8.8) specified by default.

### What did you see instead?
Check Connectivity failed.

**Comment by KarlM256** [comment]
Hi...

It is my assumption that the remote DNS is forwarded to shadowsocks-libev in my case, and that IP address will be used for all DNS lookups. The DNS address for the connection/machine running shadowsocks-libev will not be used. Is this correct?

If so, then even if the DNS server address is set to 1.2.3.4, the address in shadowsocks-android (8.8.8.8) will be used.

My router acts as a DNS server for my home network. If I set the DNS server address on the router to 1.2.3.4, then shadowsocks-android cannot connect and fails the test function. I am referencing my shadowsocks-libev by a hard coded IP address in my local network.

If I set my router's DNS address back to normal it is fine again. (Expected)

If I set the remote DNS address in shadowsocks-android to 1.2.3.4, it connects and the test works fine. (Not expected)

I am using Cygwin. I know you object. But Cygwin will not set a resolve.conf automatically, but will use it if I create the resolve.conf. My resolve.conf points to my router. This has worked fine since you provide the DNS address on the shadowsocks-libev command line. That worked. After that, I set my resolve.conf and that worked fine too. So I have been running for a long time using the resolve.conf.

Thanks,

...Karl

**Comment by KarlM256** [comment]
I can consistently produce the following behavior.

If my phone is on the same local network as my shadowsocks-libev server (WiFi at home) and references the server by its local ip address on my home network, then I can put any address in the remote DNS field on the android client and my shadowsocks connection works fine.

Thanks

**Comment by madeye** [comment]
There is a failover feature for DNS resolver. If your DNS server is not available, it will fall back to default ones.
