### ISSUE TITLE
开启kcp插件的节点连接后无法关闭节点导致也无法切换节点～

### ISSUE THREAD

**Issue by NetRube** [shadowsocks/shadowsocks-android#1094]
必须强制停止ss后才能连接其他节点～

**Comment by whour** [comment]
操作系统环境也不说，我的Oneplus3 Android 7.0.0 
shadowsocks 4.0.0 kcptun 0.0.2 切换正常。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1092
