### ISSUE TITLE
Not compatible with Whaley Android TV

### ISSUE THREAD

**Issue by jacywy** [shadowsocks/shadowsocks-android#1095]
* Android version: Android L with WUI
* Device: WTV55K1J
* Shadowsocks version: 3.3.1
When click connect botton, nothing happened.

**Comment by Mygod** [comment]
Logcat please.

**Comment by jacywy** [comment]
Part of logcat related to ss (it seems the vpn fuction was removed by rom maker?)

I/HLSP2P  ( 3538): ## 2017-01-24 23:33:23.417 [3538,3630,:0] INFO ## [HLSP2P][DownloadManager.cpp:34][INFO][OnHeartBeatRsp][PeerServer] ps heartbeat rsp ok, localProxyPort: 25288
W/bt-btif ( 2672): bta_hh_co_data: UHID write, key code: 0x1, 0x0
W/WindowManager( 1657): >>> keyCode=23 down=false
D/WindowManager( 1657): <onkey up :keyCode:23 dname:寰哺閬ユ帶鍣?devid:10 scan:28 Source:769
I/BtGatt.btif( 2672): set_read_value unformat.len = 7
I/ActivityManager( 1657): START u0 {cmp=com.android.vpndialogs/.ConfirmDialog} from uid 10050 on display 0
W/System.err( 3817): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
W/System.err( 3817):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1761)
W/System.err( 3817):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
W/System.err( 3817):    at android.app.Activity.startActivityForResult(Activity.java:3737)
W/System.err( 3817):    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
W/System.err( 3817):    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
W/System.err( 3817):    at android.app.Activity.startActivityForResult(Activity.java:3698)
W/System.err( 3817):    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
W/System.err( 3817):    at com.github.shadowsocks.Shadowsocks$$anonfun$prepareStartService$1.apply(Shadowsocks.scala:221)
W/System.err( 3817):    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
W/System.err( 3817):    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
W/System.err( 3817):    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
W/System.err( 3817):    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
W/System.err( 3817):    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
W/System.err( 3817):    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
W/System.err( 3817):    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
E/Shadowsocks( 3817): Failed to start VpnService
W/GoogleTagManager( 3817): Excessive refreshing detected; call ignored.
D/BluetoothGatt( 1935): cancelOpen() - device: DC:2C:26:F5:18:C1
D/BluetoothGatt( 1935): onClientConnectionState() - status=0 clientIf=6 device=DC:2C:26:F5:18:C1
D/BluetoothGatt( 1935): close()
D/BluetoothGatt( 1935): unregisterApp() - mClientIf=6
I/HLSP2P  ( 3401): ## 2017-01-24 23:33:24.241 [3401,3493,:0] INFO ## [HLSP2P][DownloadManager.cpp:34][INFO][TryAdjustCacheSize]system memory total size: 1928M, free size: 1014M, cache add to 100MB, AppState: 14
I/tvos    ( 1207): [37m[INFO] Change to Voltage: 102 mv (0x23)[m
D/WifiNative-wlan0( 1657): doString: [SIGNAL_POLL]
E/WifiConfigStore( 1657): updateConfiguration freq=5180 BSSID=cc:81:da:ae:c7:80 RSSI=-51 "Netgear_5G"WPA_PSK
I/SLK: :[BroadcastManager$2.onSuccess(Line:197)]( 2539): send broadcast success : Bundle[{data=[]}]
E/LocalSocketTransmitVoice( 1990): [60] connect to server failed
E/WifiStateMachine( 1657): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=72.68 rxSuccessRate=55.76 targetRoamBSSID=cc:81:da:ae:c7:80 RSSI=-52
E/WifiStateMachine( 1657): WifiStateMachine CMD_START_SCAN with age=120000 interval=30000 maxinterval=300000
E/WifiStateMachine( 1657): WifiStateMachine CMD_START_SCAN try full band scan age=120000 interval=30000 maxinterval=300000
E/WifiStateMachine( 1657): WifiStateMachine CMD_START_SCAN prevent full band scan due to pkt rate
E/WifiStateMachine( 1657): WifiStateMachine CMD_START_SCAN source -2 ...and ignore scans tx=72.68 rx=55.76

**Comment by Mygod** [comment]
Your ROM doesn't support VPNs.
