### ISSUE TITLE
如果将app移至手机SD卡上，则会提示“后台服务启动失败”，移回则正常

### ISSUE THREAD

**Issue by Han9402** [shadowsocks/shadowsocks-android#1096]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Huawei honor 5X(KIW-UL00)
* Shadowsocks version: 4.0.0
* Last version that did not exhibit the issue (if applicable):4.0.0

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [X] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
将app移至SD卡

### What did you expect to see?
开启服务

### What did you see instead?
后台服务启动失败

**Comment by LNDDYL** [comment]
#1088

**Comment by Han9402** [comment]
thx
