### ISSUE TITLE
How can i modify the kcptune port in 4.0?

### ISSUE THREAD

**Issue by lyhiving** [shadowsocks/shadowsocks-android#1098]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
I can modify the port of KCPtun.
For example SS port is 3333, kcp port is 8888.
I can modify the 3333 in the server configure page.
But i can't input the 8888 when i enable kcptun plugin.

### What did you expect to see?
Some where can input the kcp port.

**Comment by madeye** [comment]
Add `remoteaddr=server_ip:444` to your plugin options.

**Comment by Mygod** [comment]
Using remote port.

**Comment by lyhiving** [comment]
Perfect
