### ISSUE TITLE
能否添加情景模式？根据网络状况自动连接相应的配置

### ISSUE THREAD

**Issue by wuhgit** [shadowsocks/shadowsocks-android#1100]
自从加入kcptun支持后，android版速度的确提速明显，但是会消耗大量的流量，在WiFi网络下倒是无所谓，但是移动数据网络下面就有点吓人了，并且在使用移动数据网络的时候，对于速度的需求其实也不是很急迫（当然这是对我个人而言），于是我设想了一下，能否添加一个类似情景模式的选项？可能有几种实现途径

一种是根据网络连接状态决定是否启用kcptun插件（当然也可能不仅仅只针对这一个插件）
另一种是根据网络连接状态自动切换配置文件（比如我建立两个配置文件，一个是开启kcp的，用于WiFi网络，另一个是普通的ss连接，用于移动数据网络，在手机切换到某一网络时，软件自动切换到设置的配置文件）

又或者，可以直接在磁贴上切换配置文件？
甚至更进一步，配置文件可以设置颜色，然后在状态栏显示状态的时候用这个颜色来强调当前使用的配置文件？

这些都是个人的一点建议，不管这些能否实现，还是很感谢开发者做出的贡献！顺祝春节快乐

**Environment**

Android version: 7.1.1
Device: Google Nexus 6
Shadowsocks version: 4.0.0

**Comment by Mygod** [comment]
Use Tasker integration.

Custom tiles in Android N doesn't support extended view. Long press tile/click notification for now.

**Comment by wuhgit** [comment]
……啊，谢谢，问题解决了，之前完全没想到可以用Tasker

**Comment by AoEiuV020** [comment]
这个Tasker integration指的是什么？为什么别人都知道就我不知道，
只搜到那个要钱的app,Tasker,net.dinglisch.android.taskerm
是这个吗？
@Mygod
