### ISSUE TITLE
在java中使用scala伴生对象 编译时候出现找不到程序包

### ISSUE THREAD

**Issue by lovean** [shadowsocks/shadowsocks-android#1104]

**Comment by Mygod** [comment]
You need to use `ObjectName$` from Java to refer to an object in Scala.

**Comment by lovean** [comment]
你好，我使用了这个：
ShadowsocksApplication$.MODULE$.app().isNatEnabled();
在编译过程中出现了下图情况
![5704c19c-2ade-4ce1-899c-792e3123dd26](https://cloud.githubusercontent.com/assets/16167147/22496873/6c57b42e-e888-11e6-8ad0-52866e5668aa.png)

**Comment by lovean** [comment]
@Mygod 你好，我使用了这个：
ShadowsocksApplication$.MODULE$.app().isNatEnabled();
在编译过程中出现了下图情况
![5704c19c-2ade-4ce1-899c-792e3123dd26](https://cloud.githubusercontent.com/assets/16167147/22497121/3d54a6ee-e88a-11e6-96c5-6e6577ca476f.png)

**Comment by lovean** [comment]
![46352a62-7437-4682-88e4-a63f7dfe7d95](https://cloud.githubusercontent.com/assets/16167147/22497471/dedff642-e88c-11e6-864f-f40d1d203311.png)

**Comment by lovean** [comment]
找到如下原因：
因为在编译Java代码时，需要用到Scala中定义的class，但是此时Scala的class还没有被编译

**Comment by Mygod** [comment]
Good point. Try CompileOrder := Mixed.

**Comment by lovean** [comment]
thank you ，解决了，刚刚在谷歌上也找到这个方法，万分感谢。嘻嘻。是你们的粉丝。
