### ISSUE TITLE
Twinkling float button

### ISSUE THREAD

**Issue by vexetron** [shadowsocks/shadowsocks-android#1105]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Xperia Z5 Premium
* Shadowsocks version: 4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Open the app.

### What did you expect to see?
A float button that dosen't twinkle and await me to toggle it.

### What did you see instead?
The float button twinkle twice, during which I can't touch it to toggle VPN on.

**Comment by Mygod** [comment]
Could you be more specific about the meaning of twinkling? A video perhaps?

**Comment by vexetron** [comment]
It is the reaction that happens when I tap the icon: an orange line go around the icon.

It happens automatically twice when I open the app.

**Comment by vexetron** [comment]
I mean 'goes'

**Comment by vexetron** [comment]
No, that's not right. When I tap the icon, the orange line goes around it. But this bug makes the icon surrounded by the orange line for twice. I may update a video later if I have leisure.

**Comment by Mygod** [comment]
Okay that's the normal behavior. Please wait while it's getting some initialization work done.
