### ISSUE TITLE
obfs插件随机性的不能启动

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-android#1106]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

华为mate8 安卓7.0
### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: rc4-md5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
使用obfs插件

### What did you see instead?

 现象是使用时网络不通，重连SS提示Unknown plugin obfs-local,关掉插件就可以正常使用，再打开插件就不能正常连接。

连接无插件的SS后，有时切换到有插件的节点又可以正常连接，无规律的出现这个问题。

[logcat正常连接.txt](https://github.com/shadowsocks/shadowsocks-android/files/747177/logcat.txt)
[logcat-obfs错误.txt](https://github.com/shadowsocks/shadowsocks-android/files/747178/logcat-obfs.txt)

**Comment by Mygod** [comment]
```
HwPFWLogger: AppAutoStartupPolicy:prevent start provider of package com.github.shadowsocks.plugin.obfs_local, auth: com.github.shadowsocks.plugin.obfs_local, name: com.github.shadowsocks.plugin.obfs_local.BinaryProvider by callerPid 11800, callerUid 10270
```

Your system is preventing obfs-local to start up. Please try to fix this yourself.
