### ISSUE TITLE
v4.0.1远程dns设置为内网地址时发生异常

### ISSUE THREAD

**Issue by eastmalon** [shadowsocks/shadowsocks-android#1110]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "7.1.1",
* Device: SAMSUNG Galaxy S5,
* Shadowsocks version: "v4.0.1",
* Last version that did not exhibit the issue (if applicable): "v4.0.0"

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20-ietf-poly1305, aes-128-gcm
* [ ] One-time authentication
* Route
  * [ x] All
  * [ x] Bypass LAN
  * [ x] Bypass China
  * [ x] Bypass LAN & China
  * [ x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ x] IPv6 route
* [ x] Per-App Proxy
  * [ x] Bypass mode
* [ x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
在ss应用内ping www.google.com, 访问www.google.com

### What did you expect to see?
ping通，能访问Google

### What did you see instead?
失败

当远程dns设置为169.254.169.254，路由选择Bypass LAN、Bypass LAN & China、GFW List，无法解析dns；
当运程dns设置为8.8.8.8或关闭udp转发，工作正常。

**Comment by madeye** [comment]
`Remote DNS` means the DNS your remote server can reach. So make sure your remote server can reach 169.254.169.254 first.

**Comment by eastmalon** [comment]
我肯定169.254.169.254是正确的dns地址，因为在v4.0.0正常工作。而更新后就发生问题了

**Comment by Mygod** [comment]
That's due to [remote DNS isn't handled correctly/used at all prior to 4.0.1](https://github.com/shadowsocks/shadowsocks-android/commit/ee08f02660cc1061f7b3e419cff4a59eecef1b4f) with UDP forwarding enabled. Your configuration is malformed.

**Comment by eastmalon** [comment]
我vps的dns就是169.254.169.254，它能正常工作。

**Comment by Mygod** [comment]
1. Verify that DNS works on your VPS;
2. Try disabling UDP forwarding;
3. Attach log from your ss-server.

**Comment by hellofwy** [comment]
根据 stackoverflow 这个帖子：
[What is this IP address: 169.254.169.254?](http://serverfault.com/questions/427018/what-is-this-ip-address-169-254-169-254)
169.254.169.254 这个地址属于 “IPv4 Link-Local Addresses”，看样子是像本地链路地址，只能在你 VPS 服务器的本地用。
所以换个地址吧。

**Comment by hellofwy** [comment]
根据 shadowsocks-android 的访问控制设置文件：[bypass-lan.acl](
https://github.com/shadowsocks/shadowsocks-android/blob/4b3eb44bc20f0652d144a76e8bdc2d107d203f0f/src/main/assets/acl/bypass-lan.acl)，169.254.0.0/24 这个网段不会发到远程服务器。

**Comment by eastmalon** [comment]
@Mygod 

客户端udp转发开启，远程dns169.254.169.254，路由All、Bypass China
```
ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http" －U-v
INFO: using tcp fast open
INFO: plugin "obfs-server" enabled
INFO: UDP relay enabled
INFO: initializing ciphers... chacha20-ietf-poly1305
INFO: tcp server listening at 127.0.0.1:59675
INFO: udp server listening at 0.0.0.0:13376
[simple-obfs] INFO: obfuscating enabled
[simple-obfs] INFO: tcp port reuse enabled
[simple-obfs] INFO: listening at 0.0.0.0:13376
INFO: [udp] server receive a packet
INFO: [udp] cache miss: 169.254.169.254:53 <-> 182.105.156.85:12037
INFO: [udp] remote receive a packet
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: successfully resolved www.google.com
INFO: remote connected
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: successfully resolved www.google.com
INFO: remote connected
INFO: [udp] server receive a packet
INFO: [udp] cache miss: 169.254.169.254:53 <-> 182.105.156.85:12050
INFO: [udp] remote receive a packet
INFO: accept a connection
INFO: connect to www.googleapis.com:443
INFO: successfully resolved www.googleapis.com
INFO: remote connected
```

客户端udp转发开启，远程dns169.254.169.254，路由Bypass LAN、Bypass LAN & China、GFW List，无法解析dns，服务端无log

客户端udp转发开启，远程dns8.8.8.8，路由All、Bypass LAN、Bypass China、Bypass LAN & China、GFW List
```
$ ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http" -u -v
INFO: using tcp fast open
INFO: plugin "obfs-server" enabled
INFO: UDP relay enabled
INFO: initializing ciphers... chacha20-ietf-poly1305
INFO: tcp server listening at 127.0.0.1:40399
INFO: udp server listening at 0.0.0.0:13376
[simple-obfs] INFO: obfuscating enabled
[simple-obfs] INFO: tcp port reuse enabled
[simple-obfs] INFO: listening at 0.0.0.0:13376
INFO: accept a connection
INFO: connect to 91.108.56.114:443
INFO: remote connected
INFO: [udp] server receive a packet
INFO: [udp] cache miss: 8.8.8.8:53 <-> 182.105.156.85:12773
INFO: [udp] server receive a packet
INFO: [udp] cache miss: 8.8.8.8:53 <-> 182.105.156.85:12774
INFO: [udp] remote receive a packet
INFO: [udp] remote receive a packet
INFO: [udp] server receive a packet
INFO: [udp] cache miss: 8.8.8.8:53 <-> 182.105.156.85:12775
INFO: [udp] remote receive a packet
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: successfully resolved www.google.com
INFO: remote connected
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: successfully resolved www.google.com
INFO: successfully resolved www.google.com
INFO: remote connected
INFO: remote connected
```

客户端udp转发关闭
```
$ ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http" -u -v
INFO: using tcp fast open
INFO: plugin "obfs-server" enabled
INFO: UDP relay enabled
INFO: initializing ciphers... chacha20-ietf-poly1305
INFO: tcp server listening at 127.0.0.1:15245
INFO: udp server listening at 0.0.0.0:13376
[simple-obfs] INFO: obfuscating enabled
[simple-obfs] INFO: tcp port reuse enabled
[simple-obfs] INFO: listening at 0.0.0.0:13376
INFO: accept a connection
INFO: connect to www.google.com:443
INFO: successfully resolved www.google.com
INFO: remote connected
INFO: accept a connection
INFO: connect to 91.108.56.114:443
INFO: remote connected
INFO: accept a connection
INFO: connect to 169.254.169.254:53
INFO: remote connected
```

只有路由选择Bypass LAN、Bypass LAN & China、GFW List时，无法正常解析dns。我认为新版本udp转发时这些路由会过滤远程dns的lan地址，导致了这个问题。

**Comment by Mygod** [comment]
I don't think UDP forwarding over plugins is supposed to work yet. @madeye?

**Comment by eastmalon** [comment]
@Mygod 客户端开/关插件，服务端开/关插件插件都会出现这个问题

**Comment by madeye** [comment]
UDP should work. All UDP traffic are bypassed.

The problem here is the user choose Bypass LAN & China, which means bypass any IP of LAN and China. And the DNS IP he set here is a LAN IP.

**Comment by madeye** [comment]
The behavior is expected. You cannot use a LAN IP for remote DNS while bypassing LAN IPs in the route setting.

**Comment by Mygod** [comment]
@madeye Call addRoute explicitly for remote DNS?

**Comment by eastmalon** [comment]
但是这个选项是`remote DNS`, 而不是`DNS`

**Comment by Mygod** [comment]
@eastmalon You can't configure your server from your client. These are all client settings.

**Comment by eastmalon** [comment]
我看不太懂你的回复，可能是你误会了我的上一条回复，它是回复给 @madeye 的。

**Comment by madeye** [comment]
@Mygod Yes, I think it's doable.

**Comment by eastmalon** [comment]
[24c6aca8](https://github.com/shadowsocks/shadowsocks-android/commit/24c6aca85cefe228a1b02a849d0639736da3ac74)
