### ISSUE TITLE
AEAD ciphers not compatible with ss-server 3.0.0

### ISSUE THREAD

**Issue by hexchain** [shadowsocks/shadowsocks-android#1115]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Sony Xperia Z5 Dual
* Shadowsocks version: client 4.0.2 (Google Play), server 3.0.0 (Arch Linux)
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20-ietf-poly1305, aes-128-gcm
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

#### Server-side `config.json`
```
{
    "server": "0.0.0.0",
    "server_port": "1234",
    "password": "password",
    "method": "aes-128-gcm"  // or "chacha20-ietf-poly1305"
}
```

### What did you do?
Fill in connection detail and try to connect.

### What did you expect to see?
Connection works.

### What did you see instead?
Client is not able to reach Internet and server logs show "authentication error":
```
 2017-02-10 05:33:57 ERROR: failed to handshake with xx.xx.xx.xx: authentication error
 2017-02-10 05:33:57 INFO: current server connection: 0
 2017-02-10 05:33:58 INFO: accept a connection
 2017-02-10 05:33:58 ERROR: failed to handshake with xx.xx.xx.xx: authentication error
 2017-02-10 05:33:58 INFO: current server connection: 0
```

**Comment by madeye** [comment]
Yes, it's expected. Try the latest version.

**Comment by hexchain** [comment]
OK, I'll try poking our package maintainer.
