### ISSUE TITLE
kcptun在4.0.2中怎么设置？

### ISSUE THREAD

**Issue by lingbaoboy** [shadowsocks/shadowsocks-android#1116]
请教kcptun在shadowsocks-android 4.02中怎么设置？
kcptun插件已经安装，在老版本中可以正常使用，新版本kcptun的服务器端口在哪里写？按照老版本的参数填写，服务器端口不管写ss还是kcp的端口都不能联上网！

**Comment by jaronliu** [comment]
是不是服务器客户端都得用（了）kcptun默认的端口？我也发现ss-android 4.01+没地方指定kcptun端口，参数r=端口也不行

**Comment by wujysh** [comment]
@lingbaoboy 
Android上的服务器端口写服务器的kcp端口。
不要勾选udp转发试试，似乎有bug。

**Comment by lingbaoboy** [comment]
@wujysh
试过了，不行。
另外我发现最新的SS貌似不支持加速，我在电脑上都没加入成功，换成老版本ss，电脑可以加速，手机依然不会。

**Comment by whour** [comment]
see #1101
启用kcptun插件，远程端口就是kcptun的端口。
不启用kcptun插件就是ss-server的端口

**Comment by lingbaoboy** [comment]
@whour 然而并不能连上……

**Comment by ljl024** [comment]
看一下kcptun插件的版本，应该要最新版才能兼容

**Comment by lingbaoboy** [comment]
@ljl024 kcptun是最新版，PC使用正常，手机怎么弄都不行

**Comment by whour** [comment]
@lingbaboy 我前面开启了远程UDP转发确实不能连接，关闭了远程UDP就可以连接了。

**Comment by lingbaoboy** [comment]
@whour 你的SS服务器版本是什么？kcptun是通过脚本安装的还是自己配置的？

**Comment by whour** [comment]
ss 2.9.0 kcptun最新releases ，脚本自己写的。

**Comment by lingbaoboy** [comment]
@whour 
ss-libev 没有2.9.0这个版本呢……

**Comment by whour** [comment]
@lingbaoboy 我用的shadowsocks ，不是shadowsocks-libev

**Comment by iamsad3508** [comment]
在之前的版本中，plugin的configure是“--nocomp --mode .....”，新的版本是“nocomp;mode=fast;....."，应该是不通用的，覆盖安装的时候会自己改过来，新安装可能就出问题了。然而新版本的参数说明“？”中依然改写着“--nocomp...."的形式。

**Comment by lingbaoboy** [comment]
我直接在服务器使用默认参数，仅设置端口，手机端只把远程端口设置为kcptun的端口，别的什么都不设置现在管用了。

**Comment by CuminLo** [comment]
@lingbaoboy 我的还是不行，具体是怎么设置的？

**Comment by lingbaoboy** [comment]
@cuminlo 我把kcptun全部使用默认参数，手机只启用，不设置任何参数，可以使用。

**Comment by whour** [comment]
see #1129

**Comment by oscarbat** [comment]
@lingbaoboy 请问怎么解决的，我和你一样，PC正常使用。手机怎么都不行

**Comment by 549982170** [comment]
@oscarbat 解决办法很简单，密码设置不能和ss密码一样就可以了

**Comment by ryanerwin** [comment]
@549982170

你有些tips吗？
我的arch linux笔记本ss>kcptun>服务器上的kcptun>ss链接可以。安卓ss可以链接服务器上的ss，但是安卓ss的kcptun插件就连不上。。。

```
mode=fast3;
remoteaddr=$VPS:$PORT;
dscp=46;
localaddr=127.0.0.1:40048;
crypt=none;
nocomp;
mtu=1200
```

我应该要怎么改这个配置？

**Comment by 549982170** [comment]
@ryanerwin 最新版的安卓ss的kcptun连接时候的配置用逗号连接，冒号隔开，如key=xxxxxxxx;crypt=aes;mode=fast3;mtu=1350;sndwnd=1024;rcvwnd=1024;datashard=10;parityshard=3;dscp=0  而且密码不能和ss的密码一样

**Comment by ryanerwin** [comment]
@549982170 谢谢🙏你的帮助。

我还没配置好。。。我的安卓SS配置是：

> 当然 "$VPS_ADDR, $VPS_PORT, $SS_KEY, $KCP_KEY 都是直接输入。。。就改成$NAME为了安全写在这里。。。

```
服务器：127.0.0.1
远程端口：40048
密码：$SS_KEY
加密方式：AES-256-CFB
路由：全局
远程 DNS： 8.8.8.8
IPv6 路由：关
分应用 VPN：关
DNS 转发： 开
插件：kcptun
配置：mode=fast3;remoteaddr=$VPS_ADDR:$VPS_PORT;dscp=46;localaddr=127.0.0.1:40048;crypt=none;key=$KCP_KEY;nocomp;mtu=1200
```

同时，我的arch笔记本链接上没问题：
```
kcptun-client -l 127.0.0.1:1081 -r $VPS_ADDR:$VPS_PORT --crypt none --mtu 1200 --nocomp --mode fast3 --dscp 46 --key "$KCP_KEY"

ss-local -s 127.0.0.1 -p 1081 -k '$SS_KEY' -m aes-256-cfb -l 1080
```

服务器上的配置是：
```
sudo ./server_linux_amd64 -l 0.0.0.0:$VPS_PORT -t 127.0.0.1:443 --crypt none --mtu 1200 --nocomp --mode fast3 --dscp 46 --key "$KCP_KEY"
sudo ./ssserver -p 443 -k '$SS_KEY' -maes-256-cfb
```

**Comment by bhz6344** [comment]
我只配置了：
remoteaddr=$VPS:$PORT;crypt=aes;key=XXX
连上了

**Comment by oscarbat** [comment]
我已經放棄不用了，直連SS

bhz6344 <notifications@github.com> 于2018年6月23日周六 下午1:15写道：

**Comment by ryanerwin** [comment]
@bhz6344 

谢谢bhz6344，我用了你的配置，终于配置成功！
终于可以用 `kcptun` 在我的手机上！

![shadowsocks](https://user-images.githubusercontent.com/2156415/42449785-8aad984e-83b4-11e8-9997-7742307779a6.jpg)
