### ISSUE TITLE
kcptun取消设置端口?

### ISSUE THREAD

**Issue by charshine** [shadowsocks/shadowsocks-android#1120]
kcptun为什么取消设置端口啊，难道shadowsocks-libev版本要添加插件进去了。现在在手机上设置的时候要直接设置kcp端口才行，本来想用kcp的时候打开就行，现在不想用还得改端口。

**Comment by ljl024** [comment]
libev已经有插件功能了。
你可以设置多个配置文件，需要的时候切换，配合automate/tasker更佳

**Comment by charshine** [comment]
libev有添加kcptun插件直接配置的打算吗

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1098

https://github.com/shadowsocks/shadowsocks-android/issues/1090#issuecomment-274404651

**Comment by svengong** [comment]
安装插件以后，app上的插件那里只能设置参数，没找到哪里可以设置端口

**Comment by Mygod** [comment]
Learn to use multiple profiles.
