### ISSUE TITLE
后台服务启动失败：无法连接远程服务器：Error running exec().Command:[/data/user/0/com.git...

### ISSUE THREAD

**Issue by zhouzhou3516** [shadowsocks/shadowsocks-android#1124]
Hi, is there any suggesstion for bellow issue?
后台服务启动失败：无法连接远程服务器：Error running exec().Command:[/data/user/0/com.git...

![image](https://cloud.githubusercontent.com/assets/3890536/22876300/03f06d9a-f20b-11e6-9899-27017c3a06b2.png)

**Comment by sunsysjp** [comment]
#1117 
Perhaps same problem？

**Comment by zhouzhou3516** [comment]
@sunsysjp I think it is not the same with #1117 , my issue reported Exception msg like: 
Error running exec(). COmmand:[data/user/0/com.git....

**Comment by sunsysjp** [comment]
@zhouzhou3516 
hmm....which model is ur phone? and the os version？

**Comment by zhouzhou3516** [comment]
@sunsysjp huawei mate 7 , android 6.0
![screenshot_2017-02-13-20-54-40](https://cloud.githubusercontent.com/assets/3890536/22887059/93767614-f23b-11e6-9417-670977b6c14a.png)

**Comment by Mygod** [comment]
Logcat needed.

**Comment by runapp** [comment]
Big chance for cannot connect to the server. Check your network and the server's network.

**Comment by ZhangRichey** [comment]
解决了吗老铁？

**Comment by hubme** [comment]
安装到系统空间试试。我的 vivo x5pro d就这样搞定的。

**Comment by MyJavaGithubs** [comment]
@hubme
帮了我大忙

**Comment by Andruola** [comment]
@hubme , thank you!
我将shadowsocks搬到手机存储后也好了. 我的手机是vivo V3MA, Android5.1

**Comment by inkylamb** [comment]
确实是将软件移动到手机储存就可以了。谢谢！
 it is move the software in to memery of phone nor sd card

**Comment by hylepo** [comment]
@inkylamb @Andruola @TomSirLiu @hubme 请问这个怎么迁移？

**Comment by XueTeng2** [comment]
我今天又遇到了这个问题，是在华为P8 EMUI4.0.2 Android5.0环境下，点击飞机连接时显示“后台服务启动失败：无法连接远程服务器：com.github.shadowsocks was not granted ei……”，而且早晨还可以用，中午就突然遇到了，我是把shadowsocks安装在手机存储里的。

**Comment by roachsinai** [comment]
@XueTeng2 同样的问题，解决了么？

**Comment by XueTeng2** [comment]
@roachsinai 是的，更新到4.5.3版本就可以。

**Comment by roachsinai** [comment]
嗯嗯，好的。谢谢！

**Comment by roachsinai** [comment]
@XueTeng2 嗯嗯，谢谢！
