### ISSUE TITLE
网页能打开facebook, facebook app不能连接到服务器

### ISSUE THREAD

**Issue by chrishaly** [shadowsocks/shadowsocks-android#1125]
网页能打开facebook, facebook app不能连接到服务器。

网页都能打开，app里面却不能正常连接，bacebook, youtube也这样。

是因为shadowsocks-android只支付http的代理吗？

**Comment by hellofwy** [comment]
不是。只要是 TCP 连接都可以。
请按照 issue 模板提供更多信息。

**Comment by chrishaly** [comment]
同样的配置我在一台旧手机上试了facebook app正常。

app不能正常访问网络的手机信息：

### Environment

* Android version: 6.0 MRA58K
* Device: 红米Note4
* Shadowsocks version: 3.3.1
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?


### What did you expect to see?


### What did you see instead?

**Comment by hellofwy** [comment]
分别尝试下 Route 选择为 All，关闭 TCP Fast Open。
看看会不会好。

**Comment by chrishaly** [comment]
是先了
* [x ] Per-App Proxy

的原因，大概当时把
  * [ ] Bypass mode
也选上了并且勾上了facebook

现在正常了。

谢谢！

下一个版本能不能增一个生成反馈的时候需要的环境及配置信息。直接粘贴到github上，这样就不会漏掉

**Comment by Mygod** [comment]
This is not a troubleshooting site.
