### ISSUE TITLE
add to f-droid

### ISSUE THREAD

**Issue by mahdiG** [shadowsocks/shadowsocks-android#1126]
f-droid is an app store for open source apps

**Comment by fiercebead** [comment]
You can also download apk from https://github.com/shadowsocks/shadowsocks-android/releases

**Comment by Mygod** [comment]
This app isn't FLOSS since it uses various components in Google Play services.

**Comment by IzzySoft** [comment]
And a bunch of trackers unfortunately, like Crashlytics, Firebase Analytics and some more – which is a pity. I had added it to [my repo](https://apt.izzysoft.de/fdroid) back in 8/2016, but will have to remove it now as it has too many trackers 😢

**Comment by muelli** [comment]
It'd be really valuable to have this privacy focused app being present in the privacy focused f-droid store.
Needless to say that it'd be quite valuable to have this privacy tool not use any trackers to monitor user behaviour.
