### ISSUE TITLE
What is the timeout when simple-obfs enabled?

### ISSUE THREAD

**Issue by fiercebead** [shadowsocks/shadowsocks-android#1128]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1 stock
* Device: Sony xperia z5 dual
* Shadowsocks version: 4.0.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 4431
* Encrypt method: chacha20-ietf-poly1305
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
`obfs=tls;obfs-host=lol.qq.com`
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Use simple-obfs

### What did you see instead?

I remember the timeout of shadowsocks-android is 600, it still is, right?
The default timeout of obfs-server and obfs-local on linux is 60, I can change it like this `--plugin-opts "obfs=tls;obfs-host=lol.qq.com;t=600;fast-open"`.
We can not change it on android, so I wonder what's the timeout of obfs-local on android.

**Comment by madeye** [comment]
Try add `t=600` to Android's plugin option.

The real time out is `min(ss-local, ss-server, obfs-local, obfs-server)`.

**Comment by fiercebead** [comment]
If i add `;t=600` to Obfuscation hostname, the result will be `obfs=tls;obfs-host=lol.qq.com\;t\=600`.
I didn't find other place to add more options.
Btw if I enable tcp fastopen in app's setting, will it enable tcp fastopen for obfs-local?
I didn't root my phone, just curious.

**Comment by madeye** [comment]
The option should be `obfs=tls;obfs-host=lol.qq.com;t=600`

**Comment by fiercebead** [comment]
![screenshot_20170215-120309](https://cloud.githubusercontent.com/assets/22412572/22960201/f27113c2-f376-11e6-8a0a-12fbcd7d4ec1.png)
![screenshot_20170215-120320](https://cloud.githubusercontent.com/assets/22412572/22960204/f7ff9e4e-f376-11e6-8fbf-45b8382422fc.png)

Can I do it in UI?

**Comment by madeye** [comment]
OK, you cannot modify this now. Wait for the next release of simple-obfs.

**Comment by madeye** [comment]
Try this: https://github.com/shadowsocks/simple-obfs-android/releases/tag/v0.0.5

**Comment by fiercebead** [comment]
OK, I read some code, I think the default timeout of obfs-local is 600 now, just like shadowsocks-android without simple-obfs. :smile:
