### ISSUE TITLE
How to set up kcp

### ISSUE THREAD

**Issue by oscarbat** [shadowsocks/shadowsocks-android#1129]
Kcp parameters will not write, give examples?

**Comment by whour** [comment]
Please read this.
[https://github.com/xtaci/kcptun/blob/master/README.md](https://github.com/xtaci/kcptun/blob/master/README.md)

**Comment by Pason2C** [comment]
Sorry, that's my  configure. but could not connect"SSL handshake timed out "，How to revisions? 

--remoteaddr "VPS_IP:kcp_port"  --crypt "salsa20"  --sndwnd "400" --rcvwnd "400" --key "itiskcptun" --mode "fast2"

**Comment by whour** [comment]
Shadowsocks-android with kcptun you should configure like this
```
dscp=46;autoexpire=60;parityshard=5;key=naive;mode=fast;mtu=1400;rcvwnd=256;datashard=5;keepalive=10;sndwnd=128;crypt=salsa20
```

**Comment by Pason2C** [comment]
Thank you. it's working now.

**Comment by lichaocc** [comment]
Shadowsocks-Android 4.1.3
Kcptun Plugin 4.0

必须在参数里设置 remoteaddr=VPS_IP:KCP_Port，否则就不能正确连接

**Comment by vincentruan** [comment]
@whour 

how to set a key if the value has contains ; and =

**Comment by vincentruan** [comment]
Already solved with \ as a escape character

**Comment by eromoe** [comment]
There is no keepalive parameter in kcptun native client,  kcptun android's extra settings ??
