### ISSUE TITLE
Importing multiple legacy profiles from clipboard failed

### ISSUE THREAD

**Issue by runapp** [shadowsocks/shadowsocks-android#1130]
Version: 4.0.3

Import A, B seperately is OK. Fail when importing the string "A\nB".
Seems the '$' in the regex pattern only match the ending of whole string instead of each linebreak?

Not familar with Java. Maybe caused by multiline mode set incorrect?

PS: Tried with new profile url scheme. Got failed too. Try first export all profiles, and then immediately import from the clipboard.

**Comment by madeye** [comment]
Thanks! It should be caused by `^` and `$` in the new pattern.
