### ISSUE TITLE
无法一次导入多个配置文件

### ISSUE THREAD

**Issue by sjdjfcu** [shadowsocks/shadowsocks-android#1131]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by sjdjfcu** [comment]
v4.0.1以后版本，从剪切板导入配置文件时，每次只能导入一条配置，多条配置同时导入会失败。

**Comment by iamsad3508** [comment]
nexus 6p N4F26O ss4.0.3  有几个配置文件，按下右上角的复制，再按从剪切板导入，会提示失败

**Comment by madeye** [comment]
#1130
