### ISSUE TITLE
Wish add ARM64 armv8 support 

### ISSUE THREAD

**Issue by GitHubUi** [shadowsocks/shadowsocks-android#1132]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0.0
* Device: SONY Xperia XZ
* Shadowsocks version: lastversion
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
wish Android version add ARMv8-64 compile, on 64bit processor devices have better experience.

**Comment by madeye** [comment]
No plan for this.

>  on 64bit processor devices have better experience.

Actually no difference for shadowsocks.
