### ISSUE TITLE
can‘t use in andriod 7.0

### ISSUE THREAD

**Issue by ron159** [shadowsocks/shadowsocks-android#1133]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0*
* Device: oneplus 3T*
* Shadowsocks version: *version code "v3.3.1" *

### Configuration

* IPv4 server address
* Local port: 1080
* Encrypt method:rc4-md5
   * One-time authentication
* Route
    * ALL

![qq 20170221122852](https://cloud.githubusercontent.com/assets/9960623/23150879/1bd430e0-f832-11e6-8f4a-521e2655ab0e.png)

**Comment by madeye** [comment]
Try uninstall and reinstall the app.

**Comment by ron159** [comment]
i have done that many times. 
and also install the old version (2.x)to see if it can work.but it didn’t show mistakes like this ,it just 
turn around again and again.
also checked the permission ,but it just required one permission:take photos.

**Comment by madeye** [comment]
If so, try this version: https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.0.3

**Comment by ron159** [comment]
thank you very much!
it works!
