### ISSUE TITLE
希望开启UDP转发之后国内域名能用国内的DNS解析，国外的域名用ss-tunnel

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1134]

**Comment by madeye** [comment]
No plan for this. and, actually it's not necessary.

So, just disable UDP forwarding if you don't want to resolve local domains remotely.

**Comment by pexcn** [comment]
@madeye 但是如果国内的网站在国外有服务器，dns也会解析到国外的服务器了

**Comment by pexcn** [comment]
比如开启udp转发访问 ip.cn  会显示你 vps 的地址

**Comment by pexcn** [comment]
@madeye 希望能加一个选项来支持仅代理国外域名的UDP流量😅

**Comment by madeye** [comment]
I don't think it's necessary and it's not a trivial task.

Of course, any pill request is welcome.

**Comment by pexcn** [comment]
@madeye 谢谢，以后试着折腾一下，如果成功就发个PR~
