### ISSUE TITLE
java.io.FileNotFoundException: bypass-lan-china.acl

### ISSUE THREAD

**Issue by ahxxm** [shadowsocks/shadowsocks-android#1135]
Request url in latest play store version(3.3.1): `https://raw.githubusercontent.com/shadowsocks/shadowsocks-android/master/src/main/assets/acl/bypass-lan-china.acl`

Actual url should be: `https://raw.githubusercontent.com/shadowsocks/shadowsocks-android/master/mobile/src/main/assets/acl/bypass-lan-china.acl`

**Comment by Mygod** [comment]
Update to latest version.

**Comment by ahxxm** [comment]
Can you help upload latest version to Play Store?

**Comment by Mygod** [comment]
Latest version is in beta channel for now... Please wait for a while...

**Comment by ahxxm** [comment]
thank you!
