### ISSUE TITLE
Extreme battery usage

### ISSUE THREAD

**Issue by tapir** [shadowsocks/shadowsocks-android#1137]
### Environment

* Android version: 6.0, cyanogen 13
* Device: LG G2
* Shadowsocks version: Beta 4.0.4

### What did you do?

Checked battery consumption

### What did you expect to see?

5-10%

### What did you see instead?

33% (consumtpion more than the screen) 

![screenshot_20170226-162527](https://cloud.githubusercontent.com/assets/223984/23340070/56f530ea-fbdc-11e6-9f0f-6a8cbcf2c7f3.png)

**Comment by Mygod** [comment]
#893
