### ISSUE TITLE
pixel xl 默认安装ss后fastopen是开的且不可关闭，请默认关闭。pixel xl 系统：没root，版本7.1.1，补丁到 2017年2月5日

### ISSUE THREAD

**Issue by dodcore** [shadowsocks/shadowsocks-android#1138]
* Android version: 7.1.1
* Device: Google Pixel XL
* Shadowsocks version: 4.0.4

pixel xl 默认安装ss和simple obsfucation插件后，fastopen是开的，且不可关闭。
请默认设置成关闭状态。
恶果：不能连接fastopen是关闭的ss服务。

pixel xl 系统：没root，版本7.1.1，补丁到 2017年2月5日

**Comment by Mygod** [comment]
@madeye Hmmm... Maybe add another per-app setting for tfo?

**Comment by madeye** [comment]
@Mygod Enabling TFO doesn't have any side effect. The connection always fall back to normal TCP if no TFO support on the client or the server. So, I don't think this bug report  is valid.

**Comment by dodcore** [comment]
@madeye 非Root Pixel XL默认安装SS后，设置选项里TFO是打开的。问题就在这里。系统没有Root过，想关TFO都不行。导致所点击连接节点，程序实际不工作，因为没Root权限（TFO是开的）。矛盾。和自动Fall Back回正常TCP模式貌似无关。

**Comment by madeye** [comment]
@dodcore TFO is enabled on the latest Android by default. Even with TFO enabled, you won't have any problem connecting to non-TFO servers.

**Comment by hellofwy** [comment]
If TCP fast open will fall back automatically, may be should remove the option, or just show as an indicator.

**Comment by dodcore** [comment]
thanks so muck for your promt reply.
fully understand what you mean. 
its not tfo problem. i should closed that issue, not bug. sorry for my mis-leading issue.
i have tried every previous version back to 3.3.1 whick used to work properly, but ss not
