### ISSUE TITLE
Client should enable redirection of IPv6 and UDP traffic by default

### ISSUE THREAD

**Issue by fortuna** [shadowsocks/shadowsocks-android#1139]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 3.3.1

### What did you do?

By default, the Android client seems to not enable ipv6 and udp forwarding. This can lead to unintended  and sensitive traffic to not be proxied.

### What did you expect to see?

All the traffic should be proxied by default, with the option to disable if needed.

**Comment by Mygod** [comment]
Not every server has IPv6 connection and not every client environment
supports UDP packets correctly.

**Comment by madeye** [comment]
Without IPv6 and UDP enabled, all the related traffic would be blocked (dropped in tun2socks). So, actually there is no traffic leak, unless you enabled the policy routing, i.e. GFWList.

**Comment by jab** [comment]
After establishing a TCP connection over IPv4, could a capable server advertise support for UDP and IPv6 to a capable client, allowing the client to opportunistically/adaptively enable UDP and IPv6 redirection? Or at least tell the user that the server has support and prompt to enable on the client?

**Comment by Mygod** [comment]
Server having UDP support doesn't mean client can rely on it (it may be dropped by firewalls). Perhaps we can enable IPv6 by default.

**Comment by fortuna** [comment]
So my understanding from what I read is:

- If the server doesn't support IPv6, all the IPv6 traffic is dropped, regardless of the option set on the client.
- If the server supports IPv6, the IPv6 traffic is dropped by default, unless explicitly enabled by the client.

The default setting is clearly a missed opportunity. Enabling IPv6 by default means the traffic will only be dropped if the server does not support it. Is there a downside?

**Comment by madeye** [comment]
Actually many "unusual" design decisions in shadowsocks are "localized" decisions. From the point of view of a engineer, they are really not elegant, but very necessary for this special product.

**Comment by Mygod** [comment]
Okay I guess it's settled then.

**Comment by fortuna** [comment]
On https://github.com/shadowsocks/shadowsocks-android/issues/1139#issuecomment-285223838, I had no idea about the broken AOSPs. Thanks for letting us know! Do you have an example of such breakage?

@Mygod , on point 2, could you clarify the performance issue so that we understand? I believe that servers will only have IPv6 addresses in the DNS if it supports IPv6. Which means that if the server doesn't support IPv6, it should only have IPv4 addresses, so the network stack on the clients will always try to connect via IPv4.

**Comment by Mygod** [comment]
@fortuna I don't think that's necessarily true.
