### ISSUE TITLE
可否兼容SSR的剪贴板

### ISSUE THREAD

**Issue by w153140** [shadowsocks/shadowsocks-android#1140]
比如ssr:dXMwMS5uZXRndW4ud2luOjIzMDE4Om9yaWdpbjpyYzQtbWQ1OnBsYWluOlJuUTJibEY1Lz9vYmZzcGFyYW09JnJlbWFya3M9VlZNd01lZS1qdVdidlNBdElGTm9ZV1J2ZDNOdlkydHomZ3JvdXA9NXAtUTU2ZVI1YTJtNTVx
就导不进去服务器

**Comment by Mygod** [comment]
No plan for this.
