### ISSUE TITLE
IPV6 Route not work in Chrome browser

### ISSUE THREAD

**Issue by Acris** [shadowsocks/shadowsocks-android#1141]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: OnePlus 3 (with Oxygen OS 4.0.3)
* Shadowsocks version: v4.0.4
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* Plugin configuration (if applicable): obfs-local
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
Open https://ipv6.google.com/ in Chrome.

### What did you expect to see?
Open Google normally.

### What did you see instead?
The Chrome give a error: ERR_NAME_NOT_RESOLVED

BTW, I can open https://ipv6.google.com/ on my Laptop with Shadowsocks-Windows.

**Comment by madeye** [comment]
Try Firefox.

**Comment by Acris** [comment]
@madeye I tested in other browser and it's worked like a charm!
Is it a Android Chrome bug?

**Comment by vkings1** [comment]
Yeah ipv6 route not working even if firefox. It is better to desable, but shadowsocks cannot browse to google chrome. But other browser like firefox it works.

**Comment by madeye** [comment]
It's a known bug of Chrome with Android 7. You may try the dev channel Chrome.

There are bugs reported before: https://github.com/shadowsocks/shadowsocks-android/issues?q=is%3Aissue+chrome+ipv6+is%3Aclosed+label%3A%22third-party+bug%22

According to https://github.com/shadowsocks/shadowsocks-android/issues/868#issuecomment-245278995, the dev channel Chrome fixed the bug.

**Comment by Acris** [comment]
@madeye Thank you very much.
