### ISSUE TITLE
POEditor translation related discussions

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1142]
This issue is reserved for discussing translation related things, mainly proofreaders.

Proofreaders' job is to approve translations. Proofreaders are needed only when there are at least 2 active contributors to the same language. And inactive proofreaders will probably get replaced. :sweat: In addition, access to other languages will be revoked for proofreaders to avoid unnecessary trouble.

Current proofreaders:

* @sunsysjp: Japanese

**Comment by Mygod** [comment]
Currently we need a proofreader for Japanese. @yyxida @sunsysjp What do you think?

**Comment by sunsysjp** [comment]
@Mygod 
You can make the decide, i have no problem, just do the translation well.

**Comment by Mygod** [comment]
@sunsysjp Okay I have added you to proofreaders. :)

**Comment by sunsysjp** [comment]
@Mygod Okay,I'll got it. :)

**Comment by yyxida** [comment]
enn，I have no opinion
It is up to you to decide @Mygod 
I have not been online for a long time (WeChat), have you ever sent me a message? @sunsysjp

**Comment by yyxida** [comment]
He is a Japanese, i am a Chinese, he priority @Mygod

**Comment by Mygod** [comment]
Good to know! Thanks!

**Comment by Mygod** [comment]
@sunsysjp Could you check the tick after proofreading? Thanks.

**Comment by sunsysjp** [comment]
@Mygod yes,i'll got it.

**Comment by Mygod** [comment]
@madeye I think it's better to leave a translation empty if it should use the same string as English (US).

**Comment by madeye** [comment]
@Mygod OK, I'm not familiar with POEditor, just want to make each language 100% translated. 😄

**Comment by Mygod** [comment]
@madeye It's just that we don't need to update other languages if we ever need to change a mostly untranslated string.

**Comment by initrider** [comment]
Hello everybody. I updated Russian translation just now from 90 to 99.2 percentage and fixed some translation mistakes. How can I publish it to the project?
![_2018-01-04_13-35-16](https://user-images.githubusercontent.com/35081987/34559762-291fbc44-f154-11e7-8844-c2fdc35be529.png)

**Comment by initrider** [comment]
@Mygod Hello!
I have few questions about translation:
1) You changed `stat_summary` string from my translation. Why?
Sent on Russian is "Отправить", Receive "Получать", so you simply reverted values.
2) Shoud I leave strings such as `service_mode_vpn` untranslated, if in Russian we haven't got 
abbreviation for that or string shouldn't be translated (for example: `speed`)
3) About transparent proxy... Well, I just will change `port_transproxy` to "Порт прозрачн**ого** прокси" OK?

**Comment by Mygod** [comment]
1. I didn't change the translation. I only did some padding. (the only difference is the number of `\t`s)
2. Yes. Leave it empty if you think it can use the same translation as English. It saves us some trouble that way it seems.
3. Feel free to do so.

**Comment by initrider** [comment]
@Mygod Hello again! Should I update `faq_url` now?
Also, don't be surprised, but we call "FAQ" as "ЧаВо", so I will change `faq` string.

**Comment by Mygod** [comment]
Yes certainly.

**Comment by initrider** [comment]
WTF? Some strings, for example `yes` and `no` are now empty, but they had translation!
![_2018-01-05_12-37-23](https://user-images.githubusercontent.com/35081987/34603512-48217828-f215-11e7-8b97-1a8e816341ba.png)

**Comment by madeye** [comment]
@initrider I think these strings have been removed in our latest versions.

**Comment by initrider** [comment]
@madeye Should I translate it again, or wait for next release to check existence of this strings?

**Comment by Mygod** [comment]
This seems to be a bug in POEditor. I'm not sure what's happening but we should probably add those back.

**Comment by Mygod** [comment]
Moved to: https://discourse.shadowsocks.org/t/poeditor-translation-related-discussions-1142/30
