### ISSUE TITLE
请问“一次验证”这个选项在哪里？

### ISSUE THREAD

**Issue by GongT** [shadowsocks/shadowsocks-android#1143]
Android: 7.1.1
shadowsocks: 4.0.4

where is the one-time authentication option?

找了半天没找到- -

谷歌了一下也没有人说如何设置，只有搜索代码发现issue template上面提到过。

最新版是否支持一次验证？如果支持的话，设置在哪里啊。。<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:65% 40%;background-size:4100%" title="joy"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:65% 40%;background-size:4100%" title="joy"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:65% 40%;background-size:4100%" title="joy"></span></span>

**Comment by madeye** [comment]
OTA has been deprecated via https://github.com/shadowsocks/shadowsocks-org/issues/30
