### ISSUE TITLE
KCP port not found in ss-andriod 4.0.4

### ISSUE THREAD

**Issue by shensven** [shadowsocks/shadowsocks-android#1145]
### Environment

* Android version: MIUI 8.2.1.0, based on 7.0 NRD90M
* Device: Xiaomi Mi5
* Shadowsocks version: v4.0.4
* Last version that did not exhibit the issue (if applicable): v3.4.2

I update ss-andriod from v3.4.2 to v4.0.4 on Play Store, I've Install kcptun plugin ,how do set KCP port?

**Comment by coolicer** [comment]
kcp不见了...好忧伤

**Comment by madeye** [comment]
Install the plugin instead: https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.kcptun

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1120#issuecomment-279218662

**Comment by Pason2C** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1129
