### ISSUE TITLE
The v4.1.0 makes dns server unreachable

### ISSUE THREAD

**Issue by leoshh** [shadowsocks/shadowsocks-android#1146]
* Android version:7.1.1
* Device: oneplus 3
* Shadowsocks version: v4.1.0
When test the connection, it shows "Fail: Unable to resolve host "www.google.com": No adress associated with hostname". And when try to open a website in chrome, it says some kind like "dns server unreachable".
And back to the v4.0.4,  evetything worked all well.

**Comment by marcus0930** [comment]
The same with you.

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.1.1

**Comment by leoshh** [comment]
@madeye This fixed it.
