### ISSUE TITLE
liboverture.so is draining battery immensely

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1148]
Currently it's using 22% battery compared to 3% screen usage. Details: 4.5h CPU, 0.5h mobile radio active.

Other disadvantages observed for using overture:

1. Connecting requires obtaining an IP which involves an additional DNS query and HTTP request. This isn't desirable when using in poor network condition (poor mobile signal).
2. Huge apk size.
3. External IP is subject to change on mobile devices.
4. No build script on Windows.

Also I'm not sure how primary/alternative DNS works. But anyways I think currently it's not usable for out project.

**Comment by madeye** [comment]
> Currently it's using 22% battery compared to 3% screen usage. Details: 4.5h CPU, 0.5h mobile radio active.

It's quite weird. Overture should not even send queries as we are using a very aggressive caching settings. (3600 TTL, 4096 entries)

**Comment by madeye** [comment]
Which mode are you using now, VPN or NAT mode? I haven't tested overture with NAT mode actually.

It looks caused by incorrect routing, which causes overture keep trying, which should be fixed via https://github.com/shadowsocks/shadowsocks-android/commit/54efe36ffc9994525b238e2bba4d32e0bc395ff2

**Comment by Mygod** [comment]
VPN mode. Let me try the new commit...

What about the external IP? Why does it need that?

**Comment by madeye** [comment]
@Mygod It's needed for `edns-client-subnet`. It will help to solve GEO-IP CDN issues.

But as overture already supports ChinaDNS, I think we can safely remove the external IP now.

**Comment by Mygod** [comment]
Looks good to me. Maybe we should add a build script for Windows one day so that this project can be built on Windows. (I don't plan to do that though :stuck_out_tongue:)
