### ISSUE TITLE
Build error. Invalid initial heap size: -Xms1g

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#1149]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Ubuntu desktop 16.04 LTS x64
* Oracle JDK 8.0
* sbt
* Android SDK/NDK installed
* GO lang

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
run build command:  `sbt clean android:package-release`

### What did you expect to see?
build seccess.

### What did you see instead?
```
sbt clean android:package-release
; support was removed in 8.0er VM warning: ignoring option MaxPermSize=512m
Invalid initial heap size: -Xms1g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by Mygod** [comment]
Attach full log and details about your build environment (versions of sbt, scala, etc.).

**Comment by ageback** [comment]
I solved it by modifying .jvmopts content. But I have another issue building overtrue. Maybe I should open a new issue. Close now.

**Comment by yxf0448** [comment]
@ageback  hello , I have the same problem, how did you solved it?
