### ISSUE TITLE
升级到4.0.4后 无法连接

### ISSUE THREAD

**Issue by leeaung** [shadowsocks/shadowsocks-android#1150]
抱歉 英文不好 没有使用
今天从3.4.2更新到4.0.4 安装了kcptun插件 但是不会配置参数
我以前自己设置kcptun一直不成 现在使用的是扩软博客的脚本 以下是脚本查看的参数
可使用的客户端配置文件为:
{
    "localaddr": ":12345",
    "remoteaddr": "123.123.123.123:29901",
    "key": "i6Qv3reP",
    "crypt": "aes-192",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 2048,
    "rcvwnd": 2048,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
手机端参数可以使用:
-autoexpire 60 -key "i6Qv3reP" -crypt "aes-192" -mode "fast2"

下面是我自己尝试修改的 但是无法连接 我是根据上面的旧版手机端参数改的
remoteaddr=123.123.123.123:29901;autoexpire=60;key=i6Qv3reP;crypt=aes-192;mode=fast2

请问是哪里错了? 我是不是需要把配置里面有的选项都添加到参数里面?

**Comment by Pason2C** [comment]
看看这个：https://github.com/shadowsocks/shadowsocks-android/issues/1129
哪个参数改动了就添加哪个，远程端口注意是KCP端口，不是SS端口

**Comment by mrivan168** [comment]
同样更新后不知道如何设置kcp参数，只有退回到3.4.2版本了

**Comment by siulee88** [comment]
剛測試了幾小時, 發覺4.0.4+kcptun插件只可這樣設定
1. UDP要disable
2. KCPTUN server 或 client 只可用aes, 其他encryption不能用

**Comment by Pason2C** [comment]
@siulee88 我使用的是salsa20，查看Kcptun_Server日志，正常运作。

**Comment by siulee88** [comment]
試過salsa20不能運作, kcptun client & server已經是最新版, 試過其他encryption也不行, 只有aes可以, 不知道甚麼原因

**Comment by leeaung** [comment]
已经解决了  是博客群里的一位朋友帮的忙  如果有和我一样情况的朋友 可以试试只保留key,crypt,mode这3个参数 其他都删掉

**Comment by siulee88** [comment]
剛試了只保留"key,crypt,mode", 不能運作

**Comment by leeaung** [comment]
我们情况可能不同  我是使用的某博客的脚本一键安装的 1楼有 博客群里的几个朋友都是不会配置新版参数 但都是这样修改后成功使用的

**Comment by Pason2C** [comment]
@leeaung 如果你不是100M宽带的话，sndwnd和rcwnd可以调小些，2048是以100M带宽为基准的，我测试调小之后，可以减少主机流量的消耗

**Comment by leeaung** [comment]
@Pason2C 感谢指导 我试过 1024的话下载不超过2MB 改了2048后 下载能上4MB 我流量不大 一个月才几十GB 用了一段时间了  应该不会被服务器商封掉
