### ISSUE TITLE
能否释出kcptun插件的apk下载呢？Could you please releases the apk of kcptun plugin?

### ISSUE THREAD

**Issue by CovMat** [shadowsocks/shadowsocks-android#1151]
Dear author:
I use Huawei EMUI and it is hard to use Google Play Store to get Kcptun plugin. So I have to download the apk to install it.

Could you please release the latest apk at:
https://github.com/shadowsocks/kcptun-android/releases

Thank you very much.

**Comment by whour** [comment]
m.apkpure.com
这里你可以下载kcptun-android和obfs 不需要Google Play Store

**Comment by Dreista** [comment]
https://github.com/shadowsocks/kcptun-android/releases
请善用搜索功能。

**Comment by whour** [comment]
@Dreista 他的意思是最新的版本没在releases发布，而是直接上架了google商店。
apkpure是一个墙内下载google paly商店应用的好地方，不过apkpure上了梯子下载才快。

**Comment by CovMat** [comment]
@whour  谢谢。
我下载了kcptun插件的apk并安装，发现会安装到/data/app下。然而如果要让这个插件正常工作，我必须有root权限把它移动到/system/app里。

可是如果我有root权限，就可以直接用play store正常安装了，又何必下载apk呢？

所以就陷入了这个奇怪的循坏中。总之没root的国产手机是用不上kcptun的。

**Comment by whour** [comment]
@CovMat kcptun-android  并不需要ROOT权限就可以运行啊！ 为什么要ROOT，直接在Shadowsocks-android里面调用插件就行了，插件不要被系统误杀。,华为的必须要root才能安装Play Store么？ http://coolapk.com/apk/com.goplaycn.googleinstall

**Comment by Dreista** [comment]
@CovMat 有没有在设置里禁止了 Shadowsocks 启动 kcptun？我这边只要不禁止，应该是不会出现类似问题的。

**Comment by CovMat** [comment]
@whour @Dreista 

谢谢回复，但我安装完kcptun的apk后，只在Shadowsocks-android里面看到一个kcptun的插件图标，不知道在哪里设置kcptun的端口，始终没找到相关的选项。在kcptun的issue那里有人说华为的EMUI要root移动到/system/app才行。

另外华为要安装Play Store确实不需要root，但这样安装出来的Play Store是不能用的，同样也要root权限移动到/system/app

**Comment by whour** [comment]
新版本kcptun的端口就在远程端口配置kcptun server监听的端口就行了。至于华为的EMUI没法帮忙，没用华为设备。
