### ISSUE TITLE
Scan QR Code, but did not respond

### ISSUE THREAD

**Issue by Mine-MuYan** [shadowsocks/shadowsocks-android#1153]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: oneplus 3T
* Shadowsocks version: 4.1.1

### What did you do?
I was download just now ,after downloading the scaner app :QuickMark , I  scan QR Code, but did not respond,the QR Code is from [http://free.shadowsocks8.cc/#free](http://free.shadowsocks8.cc/#free)

### What did you expect to see?
It can be  used normally.

### What did you see instead?
Nothing to happen.

**Comment by Mygod** [comment]
This website is using a non standard format. Don't expect this app to work.
