### ISSUE TITLE
关于udp转发问题

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/shadowsocks-android#1156]
勾选“udp转发”后udp包会按照路由设置项“选择绕过局域网及中国大陆地址”进行“分流”吗？

**Comment by pexcn** [comment]
不会，所有 UDP 包都会经过服务器

**Comment by suikatomoki** [comment]
@pexcn
谢谢 
之前我还以为和路由器的透明代理一样

**Comment by Mygod** [comment]
@madeye Maybe add UDP forwarding for non-DNS packets even if it's disabled?

**Comment by KarlM256** [comment]
I don't understand what that would mean. DNS is handled as a special case. So this would simply override the forward DNS setting?

**Comment by madeye** [comment]
@Mygod Good idea!

**Comment by Mygod** [comment]
@madeye Maybe we should rename "UDP forwarding" to something like "remote DNS resolving"?

**Comment by madeye** [comment]
OK. Could you help to update the string? I need to AFK for a while.

**Comment by Mygod** [comment]
I'm not going to do that immediately. And also what do you think would be a better name for this?

**Comment by madeye** [comment]
DNS forwarding? Force to forward all DNS packets to remote.

**Comment by Mygod** [comment]
Okay sounds good.

**Comment by suikatomoki** [comment]
@pexcn 
https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L168

这里只能控制tcp包？有啥wiki吗？

**Comment by pexcn** [comment]
@suikatomoki 不清楚唉…

**Comment by suikatomoki** [comment]
@pexcn  那就是会进行分流了？

**Comment by pexcn** [comment]
@suikatomoki 上面这个commit看来会强制udp转发，但是除了dns…

**Comment by KarlM256** [comment]
So we now have the following settings from the user's view:
1) Route
2) Remote DNS
3) DNS Forwarding

I wish to understand how the settings are intended to interact. Suppose Route is set to Bypass LAN, Remote DNS is set to 8.8.8.8 and DNS Forwarding is set to On. What will be used for the LAN?

Will the LAN DNS server be used? Will 8.8.8.8 be used? Or will the DNS from the ss-server be used?
Will UDP to an address within the LAN be handled locally? Or will it always be forwarded?

**Comment by Mygod** [comment]
Routing for IP addresses is always controlled by "route".

It's more complicated for domain names. If DNS forwarding is enabled, all DNS queries are forwarded via Shadowsocks (UDP) to remote where "remote DNS" is used. Otherwise first it will look up the rules to decide whether to resolve it locally or remotely. If resolving locally, it will query DNSPod's server via UDP ([details](https://github.com/shadowsocks/shadowsocks-android/blob/a494f56/mobile/src/main/scala/com/github/shadowsocks/BaseService.scala#L352)). If resolving remotely, it will query your "remote DNS" via Shadowsocks (TCP).

> I wish to understand how the settings are intended to interact. Suppose Route is set to Bypass LAN, Remote DNS is set to 8.8.8.8 and DNS Forwarding is set to On. What will be used for the LAN?

Only packets to LAN are bypassed. Every domain name is resolved remotely with 8.8.8.8 via Shadowsocks (UDP).

> Will the LAN DNS server be used? Will 8.8.8.8 be used? Or will the DNS from the ss-server be used?
Will UDP to an address within the LAN be handled locally? Or will it always be forwarded?

No. Not any more. Only used when you connect to ss-local port via socks proxy (which should never happen under normal circumstances). It depends on your "route" settings. In short, the same as TCP.

**Comment by KarlM256** [comment]
So what is the advantage of DNS forwarding via TCP over UDP through Shadowsocks? What is the use case for the DNS Forwarding option?

**Comment by Mygod** [comment]
@KarlM256 There's no TCP over UDP. It's DNS over TCP. The advantage is that UDP is unreliable in some network (for my case my mobile data).

Use case? Not sure. Perhaps faster DNS resolving? @madeye

**Comment by suikatomoki** [comment]
@KarlM256 第一：远端服务器没有开启udp  第二：运营商境外udp丢包严重

**Comment by KarlM256** [comment]
Sorry. Language issue. 

So what are the advantages/disadvantages of (1) DNS forwarding via TCP through Shadowsocks, compared to (2) DNS forwarding via UDP through Shadowsocks? What is the use case for the DNS Forwarding option?

**Comment by KarlM256** [comment]
第一：远端服务器没有开启udp 第二：运营商境外udp丢包严重

So is it worth having the DNS Forwarding option in the Android client?

**Comment by suikatomoki** [comment]
@KarlM256 
1)We need to convert udp dns queries to tcp queries, in case the server doesn't support UDP forwarding. 
2)In some environment UDP packets are not allowed.

**Comment by suikatomoki** [comment]
@KarlM256  I think turn off the DNS forwarding option is better.

**Comment by KarlM256** [comment]
What about and option to select UDP or TCP for DNS forwarding?

**DNS Forwarding** select TCP or UDP, default TCP.
When forwarding DNS to remote Shadowsocks server use TCP or UDP

Then the selection of TCP or UDP can be independent of the rules for when to forward to the remote.

**Comment by suikatomoki** [comment]
TCP for DNS forwarding need overture,so you suggest maybe no easy to achieve when turn on the DNS forwarding option.Do not worry query slow with TCP,the overture have cache.

**Comment by KarlM256** [comment]
The point of my Pecos comment was to simplify the controls from the user perspective. Any thoughts?

**Comment by suikatomoki** [comment]
@KarlM256 You can open a new issue, this issue has been closed.
