### ISSUE TITLE
Relay dns failed, and if I switch the DNS forward to OFF, all the other UDP packages can not be relay.

### ISSUE THREAD

**Issue by junolym** [shadowsocks/shadowsocks-android#1160]
### Environment

* Android version: *7.1.1*
* Device: *One plus 3T*
* Shadowsocks version: *v4.1.3*

### Configuration
* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] DNS Forwarding

### What did you expect to see?
UDP relay.

### What did you do?
Turn on the DNS forwarding.

### What did you see instead?
DNS failed, time out.

### What did you do?
Turn off the DNS forwarding.

### What did you see instead?
UDP packages can not be relay.

### What did you think of the problem?
The dns relay packages are blocked by some reason.

# How can I relay the udp packages without dns query packages

**Comment by madeye** [comment]
By default, UDP relay is enabled now. The only difference between enabling and disabling DNS forwarding is if the DNS packet is also forwarded.

**Comment by madeye** [comment]
> UDP packages can not be relay.

Any step to reproduce this?

**Comment by vkings1** [comment]
Try to change the dns remote. I gues

**Comment by junolym** [comment]
> Any step to reproduce this?

Thank you for your help. I am playing the game Asphalt 8, it use udp when i play online with others. If I turn on the DNS relay, it works sometime (The DNS works sometime, but usually fails). If I turn off the DNS relay, it can never work. 

To reproduce? I think just try turn off the DNS relay and then test udp.

**Comment by madeye** [comment]
> To reproduce? I think just try turn off the DNS relay and then test udp.

My local test shows UDP works well. A better way to test UDP is using QUIC in Chrome. You may enter `chrome://net-internals/#quic` to see if there is connections to Google servers.

>  I am playing the game Asphalt 8, it use udp when i play online with others.

AFAIK, very few mobile games would use UDP for multi-player play. Could you double check it first?

**Comment by Mygod** [comment]
@madeye Just gave v4.1.3 a go. Confirms that QUIC works when DNS forwarding is disabled and it doesn't for v4.1.2 when UDP forwarding is disabled. :+1:

**Comment by junolym** [comment]
Thanks for telling me how to test udp. I will try to test QUIC.

**Comment by vkings1** [comment]
Me i ask some qiestion about nat? What is the defference betwen nat in vpn, when i turn the nat mode it's work but unable to browse this new version of shadowsocks did not work for low memory.  Me i suggest instead of remote dns, change to auto detect dns  it is better..

**Comment by junolym** [comment]
Sorry, I find that the problem isn't caused by shadowsocks. Because I tried another network, and they work well. Thank you for your answers.
