### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by conanconan** [shadowsocks/shadowsocks-android#1161]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
commit id: 64c85297055a0471e18ed151c365792e3c1c7d0e
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
command build on win7 64bit 

### What did you expect to see?
build successfully

### What did you see instead?
It will cause error which error message is 
"java.io.IOException: Cannot run program "mobile/src/overture/make.bash": CreateProcess error=193, %1 不是正確的 Win32 應用程式 。".
make.bash is not a valid Win32 application.

**Comment by AndlsH** [comment]
Do not build this app on Windows.
