### ISSUE TITLE
新版如何设置kcptun，求详细教学

### ISSUE THREAD

**Issue by qwe1q2w** [shadowsocks/shadowsocks-android#1163]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by suikatomoki** [comment]
remoteaddr=VPS_IP:KCP_Port;key=kcppassword;mode=fast2;mtu=1350;snwnd=400;rcvwnd=400;crypt=salsa20

**Comment by zixia** [comment]
@suikatomoki Thanks. 

This should be put to the config dialog by default.
