### ISSUE TITLE
UDP forwarding on by default is causing issues

### ISSUE THREAD

**Issue by shounak-de** [shadowsocks/shadowsocks-android#1165]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Nexus 6
* Shadowsocks version: Latest from google play store
* Last version that did not exhibit the issue (if applicable): Prior version has no issues

### Configuration

_Put an `x` inside the [ ] that applies._

* [X] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [X] One-time authentication
* Route
  * [X] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
updated to the latest google play version of shadowsocks

### What did you expect to see?
usual behavior as before versions

### What did you see instead?
udp packets are not being forwarded to the server. No internet on the phone at all when using shadowsocks (It is probably being blocked on the network firewall, and not a bug in the android application) Earlier this was not an issue as I could disable udp forwarding.

But with the latest version, there is no option in the latest application to disable UDP forwarding. It means I cannot use shadowsocks on android anymore.

**Comment by madeye** [comment]
When you disable DNS forwarding, it works like disabling UDP forwarding in the previous version. The only difference is the previous version would drop UDP traffic locally, while the current version does such remotely.

**Comment by shounak-de** [comment]
When I disable DNS forwarding, I see a whole lot of these on the ss-server log:
```
Mar 16 17:35:07 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:07 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:07 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:07 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:07 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:07 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:07 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:07 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: failed to handshake with 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: authentication error from 64.170.21.252
Mar 16 17:35:08 ss-server[937]: failed to handshake with 64.170.21.252
```

There is no traffic coming back from the server

**Comment by shounak-de** [comment]
As a workaround, I reinstalled Shadowsocks from Titanium Backup to the prior version, to get it to work again. I've had to disable automatic updates.

**Comment by madeye** [comment]
Make sure you have disabled one time with, which is deprecated.

**Comment by madeye** [comment]
Your problem is not caused by UDP forwarding, but mismatch cipher and authentication between client and server.

**Comment by shounak-de** [comment]
Oh... ok, This is my current server config:
```
{
    "server"       : "0.0.0.0",
    "server_port"  : 8388,
    "password"     : "xxxxxxxxxx",
    "timeout"      : 300,
    "method"       : "aes-256-cfb",
    "fast_open"    : false,
    "auth"         : true,
    "dns"          : "192.168.1.1",
    "workers"      : 1
}
```
(password masked)
Would it be sufficient to drop the `"auth"         : true` line?

**Comment by madeye** [comment]
Right. OTA is deprecated.

**Comment by shounak-de** [comment]
Thank you very much! Much appreciated.
It is now working with the latest android version :+1:
