### ISSUE TITLE
TCP and UDP selection for DNS forwarding

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#1166]
### Environment

* Android version: 6.0.1
* Device: Moto G4 Plus
* Shadowsocks version: 4.1.3

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-128-GCM
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Ask in issue #1156 about how DNS now worked with the latest changes.

### What did you expect to see?
A simple explanation.

### What did you see instead?
A complex explanation.

### Comments

The description about how DNS now works seems like so many special cases. I understand that UDP is now forwarded by default. That seems fine to me. But now the DNS rules seem complex.

What if we eliminate the current **DNS Forwarding** option from Shadowsocks Android?

We could then replace it with a new **DNS Forwarding** option to select UDP or TCP for DNS forwarding?

**DNS Forwarding** Would accept either TCP or UDP, and default to TCP.
 With a description **When forwarding DNS to remote Shadowsocks server use TCP or UDP.**

Then the selection of TCP or UDP (for DNS) can be independent of the rules for when to forward to the remote.

I think this would be simpler and easier to use and understand.

Thanks,

...Karl

**Comment by madeye** [comment]
The best way to understand the mechanism behind this option is to read the code.

As normal user, you only need to know:

1. If you want to avoid GEO-IP related CDN issues, please don't forward DNS packets.
2. If you really care about the security, and want to make sure no DNS leak locally, make sure keep forwarding DNS enabled.

**Comment by KarlM256** [comment]
Would you consider changing the option description to

**Forward all DNS requests to remote**

for the English description?

**Comment by KarlM256** [comment]
Thanks.

Your "As a normal user..." description is great. Perhaps it would be helpful in the ReadMe or a FAQ.

**Comment by KarlM256** [comment]
For clarity, is this correct? If I select route all, without DNS Forwarding, all DNS requests are forwarded to the remote via TCP. If I then enable DNS Forwarding, all DNS requests are forwarded to the remote via TCP.

**Comment by KarlM256** [comment]
Because there are so many questions about TCP and UDP. Would you consider changing the option description to

**Forward all DNS requests to remote via UDP**

for the English description?

**Comment by KarlM256** [comment]
@madeye @Mygod do you think adding "via UDP" would make the action clearer?

**Comment by Mygod** [comment]
Imo there's no way to describe this feature in one sentence. In short, if you want to prevent DNS leakage turn it on; if you want to access China websites at the same time correctly turn it off.

**Comment by KarlM256** [comment]
If I use Route All, will that also prevent DNS leaks?

**Comment by Mygod** [comment]
Yes.

**Comment by KarlM256** [comment]
Hi @Mygod 

Ok, so Route All can prevent DNS leaks.

In that case, it still seams like it would be clearer to let the lists be the only way to control where DNS requests are sent for resolution.

Then the option in the Android app can select how DNS is forwarded to the remote (Shadowsocks) server (UDP or TCP) when the lists determine that the requests should be sent to the remote server. I think this would be much less confusing for users; considering how many questions there are, I think less confusing would be a big win.

Thanks,

...Karl

**Comment by Mygod** [comment]
No matter in what way you put it, it will still be confusing at some perspective. As I've said, there's just no simple way to describe it in one sentence. :upside_down_face:
