### ISSUE TITLE
can‘t use ipv6 in 4.1.3 with kcptun

### ISSUE THREAD

**Issue by hanson-l** [shadowsocks/shadowsocks-android#1167]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "6.0.1"
* Device: samsung s6*
* Shadowsocks version: "v4.1.3"
* Last version that did not exhibit the issue (if applicable): v4.1.2

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
upgrade to v4.1.3

### What did you see instead?
can not connected to the Internet

**Comment by Mygod** [comment]
@madeye Could it be f64014eb7b126e9240b948903c820eb376ae907c?

**Comment by Mygod** [comment]
I can't reproduce this on my side (IPv4). Did you upgrade kcptun?

**Comment by madeye** [comment]
I don't think so. All UDP traffic in kcptun would be bypassed to tun device.

**Comment by hanson-l** [comment]
IPv4 works fine.
The version of kcptun is v0.0.4.

**Comment by madeye** [comment]
It looks an issue of IPv6 address handling in plugin argument parsing. 

Could you try this one? https://www.dropbox.com/s/9xfma5gizomfl9z/kcptun-nightly-0.0.5.apk

**Comment by hanson-l** [comment]
It‘s fixed. Thank you.
