### ISSUE TITLE
无法连接，急！！！

### ISSUE THREAD

**Issue by x8888k** [shadowsocks/shadowsocks-android#1168]
### Environment

* Android version: "7.0.1"
* Device: Nexus6
* Shadowsocks version: *version code "v3.4.2" 
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
升级安卓3月安全补丁后就无法连接，系统VPN选项里删除shadowsocks后也无法再出现
![screenshot_20170319-024517](https://cloud.githubusercontent.com/assets/7923364/24075043/5eccef82-0c4f-11e7-8dbb-a06a5a0ce828.png)
连接按钮也没反应
![screenshot_20170319-024807](https://cloud.githubusercontent.com/assets/7923364/24075046/6e98f28a-0c4f-11e7-95c5-e90ae9956c98.png)

**Comment by Mygod** [comment]
Try a reboot.

**Comment by x8888k** [comment]
@Mygod 重启很多次了，我另一部手机红米安卓6.0.1，2月安全补丁，相同SS版本可以正常连上，我怀疑是不是升级3月安全补丁导致的，因为手机里的赛风也连不上

**Comment by Mygod** [comment]
This app works fine with March 5, 2017 update. It's a bug of your ROM.

**Comment by ljl024** [comment]
清除数据试试
不行的话再试试上一版应用
3月安全补丁没有给我带来这个问题(oneplus 3)

**Comment by hdp521** [comment]
问题解决了吗
