### ISSUE TITLE
可否考虑增加https,http协议支持？

### ISSUE THREAD

**Issue by iammecn** [shadowsocks/shadowsocks-android#1169]
如题

**Comment by junolym** [comment]
你说的东西跟shadowsocks好像没有关系。

是什么让你觉得它不支持http(s)？

**Comment by iammecn** [comment]
![img_1152](https://cloud.githubusercontent.com/assets/3390459/24082184/3b9fd012-0cfc-11e7-9340-1810de8f0a54.PNG)
我是说增加代理出去的协议类型，不是说ss不支持访问不了http

**Comment by chujian** [comment]
你这个是什么APP，我也要HTTP协议
