### ISSUE TITLE
"scan QR code" does not work

### ISSUE THREAD

**Issue by SoDa-GitHub** [shadowsocks/shadowsocks-android#1170]
### Environment
* Android Version 6.0.1
* Device: S6 edge+
* Shadowsocks version: version code v4.1.3  commit ID  c21bd74
* Last version that did not exhibit the issue (if applicable):sorry i  don't know

### What did you do?
i just want to use “scan QR code”

### What did you expect to see?
a camera to scan

### What did you see instead?
unfortunately,shadowsocks has stopped

**Comment by Mygod** [comment]
Attach logcat.

**Comment by SoDa-GitHub** [comment]
I don't have logcat. I tested just now,the last normal version is v3.3.1.And "scan QR code" doesn't work since v3.4.0 when you changed its UI. It is consistent with my inference: you forgot to ask for permission to use camera and keep the bug for a very long time. Another fact is, the new shadowsocks's permission list is empty when the old shadowssocks's permisson list has a "camera".

**Comment by Mygod** [comment]
We currently use third-party app to scan QR code.

**Comment by SoDa-GitHub** [comment]
So unfortunately...for me. Shadowsocks's very old versions do that like now,i even have forgot that app's name. And i remember that the very old versions will remind me to download a app to scan QR code ,but now...

**Comment by Mygod** [comment]
So attach logcat.

**Comment by SoDa-GitHub** [comment]
--------- beginning of main

--------- beginning of system

03-19 22:59:30.501  5990  5990 E AndroidRuntime: FATAL EXCEPTION: main

03-19 22:59:30.501  5990  5990 E AndroidRuntime: Process: com.github.shadowsocks, PID: 5990

03-19 22:59:30.501  5990  5990 E AndroidRuntime: java.lang.SecurityException: Permission Denial: starting Intent { act=com.google.zxing.client.android.SCAN cat=[android.intent.category.DEFAULT] flg=0x4080000 cmp=com.chinamworld.bocmbci/com.google.zxing.CaptureActivity } from ProcessRecord{ed596b2 5990:com.github.shadowsocks/u0a544} (pid=5990, uid=10544) not exported from uid 10244

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3131)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4915)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Activity.startActivityFromFragment(Activity.java:4902)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7319)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Fragment.startActivityForResult(Fragment.java:1126)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.Fragment.startActivityForResult(Fragment.java:1115)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at com.github.shadowsocks.ProfilesFragment.onMenuItemClick(ProfilesFragment.scala:355)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:88)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:345)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1547)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3821)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:5841)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7237)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

03-19 22:59:30.501  5990  5990 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Animenz7** [comment]
what is the third-party app?

**Comment by SoDa-GitHub** [comment]
i want to know,too.

**Comment by Animenz7** [comment]
I have already back to v3.3.1
