### ISSUE TITLE
Can I use TCP to query DNS?

### ISSUE THREAD

**Issue by junolym** [shadowsocks/shadowsocks-android#1171]
### Environment

* Android version: *7.1.1*
* Device: *one plus 3T*
* Shadowsocks version: *4.1.3*

### Configuration

* [x ] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
Turn on the DNS relay.

### What did you expect to see?
It works.

### What did you see instead?
It dose not work. DNS failed.

**The issue may be caused by my ISP.**
**Can I use TCP to query DNS?**
**If I can, what should I do in my Android device and the VPS.**

In Chinease:
由于ISP干扰之类的原因，到VPS的UDP包干扰很大。shadowsocks能否使用TCP解析DNS？

**Comment by Mygod** [comment]
Disable UDP/DNS forwarding.

**Comment by junolym** [comment]
Must be ? I want to use DNS forwarding, or I will get the wrong DNS record.

**Comment by Mygod** [comment]
Read the description.

**Comment by junolym** [comment]
Thanks anyway

**Comment by suikatomoki** [comment]
新版关掉DNS转发选项可在国内达到最佳使用效果😁

**Comment by suikatomoki** [comment]
关掉DNS转发选项后就是用tcp请求自定义dns服务器了😁

**Comment by junolym** [comment]
谢谢@suikatomoki 的回答，我后来查看文档知道了。我发现我这里的问题跟ss没关系。只是这个问题影响到udp，和ss打开dns转发又失败的问题总是同时出现同时消失，害我以为是ss的问题。
