### ISSUE TITLE
Pull down quick operation function missed in 4.1.3

### ISSUE THREAD

**Issue by zhouyang123** [shadowsocks/shadowsocks-android#1172]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment
Android 7.1.1
Device: Nexus 6 , Nexus 5x
Shadowsocks version 4.1.3
* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Check Shadowsocks pull down quick operation menu when Shadowsocks is running

### What did you expect to see?
In previous Shadowsocks version, there are two quick operations buttons(STOP  and Switch)avaiblabe to stop Shadowsocks service  or switch my profiles in the pull down quick operation menu.

### What did you see instead?
After updated to 4.1.3 version, there is no any quick operations in Shadowsock pull down menu

**Comment by zhouyang123** [comment]
@Mygod May I know why you close this issue directly?

**Comment by simonsmh** [comment]
FYI 
https://github.com/shadowsocks/shadowsocks-android/issues/1037
