### ISSUE TITLE
配置kcptun参数时，远程地址的值不能为域名？

### ISSUE THREAD

**Issue by shensven** [shadowsocks/shadowsocks-android#1173]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0 NRD90M
* Device: Xiaomi Mi5
* Shadowsocks version: v4.1.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: <code>1080</code>
* Encrypt method: <code>aes-256-cfb</code>
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable): <code>remoteaddr=a.com:10000;autoexpire=60;key=helloworld;mode=fast2;crypt=aes-192</code>
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
使用的影梭安卓客户端版本为 v4.1.3，安装的kcptun插件版本为 v0.0.4，在配置kcptun插件参数时，如果remoteaddr的值为 <code>ip:port</code> ，可以正常使用，如果为 <code>domain:port</code> ，就会连接失败

当remoteaddr的值为 <code>domain:port</code> 时，启动连接后提示 <code>失败：Unable to resolve host “www.google.com”:No address associated with hostname</code>

**Comment by madeye** [comment]
Unfortunately, it's expected. Use `ip:port` in plugin option or enter the domain name and port in shadowsocks profile.

**Comment by shensven** [comment]
@madeye okay, thank u

**Comment by weyou** [comment]
I came across the same issue. So why not support the domain name in kcptun plugin?
