### ISSUE TITLE
Auto connect not working on BlackBerry PRIV 

### ISSUE THREAD

**Issue by Explorare** [shadowsocks/shadowsocks-android#1175]
Device : BlackBerry PRIV 
System : Android 6.0.1
Shadowsocks 4.1.3

Auto connect won't work on boot.

**Comment by Mygod** [comment]
I assume this is a third-party bug. We can't fix that unless you provide more useful info.

**Comment by Explorare** [comment]
I tried a reboot and wait for about 2 mins and the Shadowsocks connected automatically. Just a small delay.
