### ISSUE TITLE
4.1.3版本无法直接在通知栏中切换服务器或关闭

### ISSUE THREAD

**Issue by kawnnor** [shadowsocks/shadowsocks-android#1176]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: OnePlus 3
* Shadowsocks version: 4.1.3

4.1.3以前的版本可以通知栏下滑后，直接关闭或切换服务器。但是4.1.3版本去掉了这个功能，希望能在后续的版本中回归此功能。谢谢！

**Comment by madeye** [comment]
http://www.tomsguide.com/us/customize-android-nougat-quick-settings,review-3991.html

**Comment by madeye** [comment]
https://developer.android.com/guide/topics/ui/shortcuts.html

**Comment by whour** [comment]
see
#1037

**Comment by kawnnor** [comment]
明白了，新版的开关、切换服务器的效率比以前更高。谢谢！
