### ISSUE TITLE
自定义 ACL 不能使用 [bypass_list] ？

### ISSUE THREAD

**Issue by hyxxsfwy** [shadowsocks/shadowsocks-android#1177]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *6.0*
* Device: *H60-L01*
* Shadowsocks version: *version code "v4.1.3"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: rc4-md5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Import custom ACL from clipboard with both [proxy_list] rules and [bypass_list] rules.

### What did you expect to see?
All rules in custom ACL take effect.

### What did you see instead?
Only rules in [proxy_list] take effect.

**Comment by Mygod** [comment]
It's expected. @madeye decided to make it simple.

Related source: https://github.com/shadowsocks/shadowsocks-android/blob/b397ab2/mobile/src/main/scala/com/github/shadowsocks/acl/CustomRulesFragment.scala#L306

**Comment by AndlsH** [comment]
You can host acl files on your own server. 
You will need to modify the url in `./mobile/src/main/scala/com/github/shadowsocks/acl/AclSyncJob.scala` and generate apk by yourself.
