### ISSUE TITLE
导出服务器配置 有问题

### ISSUE THREAD

**Issue by abc45628** [shadowsocks/shadowsocks-android#1179]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 5.1.1 LMY47V , miui 8.2.2.0
* Device: 红米3
* Shadowsocks version: 413
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open
* [ ] NAT mode

### What did you do?
导出服务器配置

### What did you expect to see?
ss://YWVzLTI1Ni1jZmI6NjQ0NzY4NTg@139.162.75.52:443
这个地址我用的是Android版SS导出的，不能导入到win版ss
### What did you see instead?
ss://YWVzLTI1Ni1jZmI6NjQ0NzY4NThAMTM5LjE2Mi43NS41Mjo0NDM=
这个地址我用的是win 版SS导出的，导入到Android版ss正常

**Comment by wongsyrone** [comment]
这种ZZ的格式，如果我是GFW，直接封掉你这个IP以及所在的VPS服务商了：139.162.75.52

**Comment by madeye** [comment]
It's expected. Android version is using a new URL schema.
