### ISSUE TITLE
手机自动重启

### ISSUE THREAD

**Issue by xzxz520cs** [shadowsocks/shadowsocks-android#1180]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 4.4.4
* Device: nexus 5
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable):4.0.4

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [x ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:AES-256-CFB
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* [x ] NAT mode

### What did you do?
我最近将服务器的ipv6打开了，但是这是和最近更新新版本的时间很近所以我不确定。

### What did you expect to see?
正常

### What did you see instead?
手机开机过一段时间后重启（当时我正在googleplay下东西）。将正在下载的东西停止后（我把下载管理程序停用了）手机没有重启，但是网络连接全部失效，放了一段时间后手机发热严重发现ss耗电高达60%才发现是ss的问题（我还以为我的Nexus5终于坏了）于是把ss卸载后手机恢复正常。然后去下APK重装发现最新版本无法安装，情况是一直在安装中，换了旧的4.0.4后安装成功，用googleplay升级到最新版本正常使用。但是几天之后又出现同样的问题。

**Comment by Mygod** [comment]
Try obtaining a logcat while you observe this bug.

**Comment by xzxz520cs** [comment]
[Log_2017-03-23_22-18-44.txt](https://github.com/shadowsocks/shadowsocks-android/files/865000/Log_2017-03-23_22-18-44.txt)

还需要别的吗？给我关键字，安卓实在不懂。

**Comment by Mygod** [comment]
Is this the log obtained when using 4.1.3?

**Comment by xzxz520cs** [comment]
这应该是刚刚从出问题（有过重启）、卸载、安装旧版本、用googleplay再升到新版本、正常使用，这段时间的日志。

**Comment by Mygod** [comment]
I think it's a bug of Android 4.4. Could you try fully uninstalling the app, restarting device before installing new version?

**Comment by xzxz520cs** [comment]
你说的我有做过，不过几天后就又出问题了。但是无所谓了，我把系统升成6.0了，应该不会出问题了。

**Comment by Mygod** [comment]
Okay. If you see the problem occurring again, try grabbing another logcat.

**Comment by xzxz520cs** [comment]
没问题
