### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ryanz91** [shadowsocks/shadowsocks-android#1181]
java.io.IOException: Cannot run program "mobile/src/overture/make.bash": CreateProcess error=193, %1 不是有效的 Win32 应用程序。

**Comment by madeye** [comment]
You need to build this project on Linux/macOS platforms.

**Comment by gejian311** [comment]
请问这是只能在Linux/macOS平台上吗？ windows下是不能编译的？

**Comment by xqgithub** [comment]
I have also encountered the same problem。I compiled the code in windows。Really can not compile on windows above?
