### ISSUE TITLE
Enabling UDP by default is causing my server to get blocked more often

### ISSUE THREAD

**Issue by m13253** [shadowsocks/shadowsocks-android#1183]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Motorola XT1072
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable): 4.1.2

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] UDP Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### Description

In the latest release, the toggle to enable/disable UDP is removed, with the default to enable UDP.

But I have found that, enabling UDP will get my server to get blocked more often, usually once for ~5 min per hour. (No matter on phone or on PC)

I have found no evidence of relationship between using UDP and getting blocked. But I believe it is better to leave the choice open.

### My suggestion

Please add back the toggle to enable/disable UDP.

In addition, I hope we can add the third option, besides enable and disable: "drop", which means dropping (or rejecting with icmp-port-unreachable) all UDP packets, that may allow Chrome to give up using QUIC protocol, speeding up browsing.

### 描述

在最近一次更新中，开启/关闭 UDP 的选项被移除了。取而代之的是默认打开 UDP。

但是我发现，开启 UDP 会导致我的服务器更经常被墙。（无论在手机端还是 PC 端，）开启 UDP 会导致每小时约 5 分钟的断线时间。

我没有发现确凿证据来证明打开 UDP 与服务器被墙有什么关联，但是我希望能保留这个选项。

### 我的建议

烦请加回开关 UDP 的选项。

更进一步，我希望我们能在开启和关闭之外增加第三个选项：“丢弃”，即丢掉（或用 icmp-port-unreachable 包来拒绝）所有 UDP 包。这样或许可以在 UDP 无法使用的情况下让 Chrome 不使用 QUIC 协议，从而加速网页浏览。

**Comment by madeye** [comment]
You can just disable UDP on your server. Then all the UDP traffic would be dropped

**Comment by suikatomoki** [comment]
我估计你动手能力也强，自己对照着改改加几个view编译个自己用吧
https://github.com/shadowsocks/shadowsocks-android/commit/f64014eb7b126e9240b948903c820eb376ae907c

**Comment by lostsnow** [comment]
China Mobile(beijing) block the udp package

**Comment by lostsnow** [comment]
@madeye 北京移动确实是封了 udp 的,,,包到不了server 端 
连接状态显示的只有send 没有receive,,这种情况server端去掉udp也是没用的吧?

**Comment by madeye** [comment]
@lostsnow if UDP packets are dropped, it just equals to disabling UDP forwarding.

**Comment by lostsnow** [comment]
@madeye 但是实际情况是 只要客户端UDP forwarding, 请求就出不去..

**Comment by lostsnow** [comment]
![default](https://cloud.githubusercontent.com/assets/220461/24439975/fe44e60a-1483-11e7-85a5-aa770e436309.png)

**Comment by suikatomoki** [comment]
@lostsnow 不要开启DNS转发 这个选项几乎没人会开 用的很少

**Comment by lostsnow** [comment]
@suikatomoki dns转发没开启的 但是现在新版udp 默认全转发了

**Comment by lostsnow** [comment]
![default](https://cloud.githubusercontent.com/assets/220461/24440062/8c6045ba-1484-11e7-9b60-18eabc1ec05c.png)

同样的配置 旧版关闭 UDP forwarding 就是没问题的

**Comment by suikatomoki** [comment]
@lostsnow 远程dns解析走的是tcp请求

**Comment by lostsnow** [comment]
这个在之前这个问题 #957 的时候也详细测试过 其他配置不动 disable UDP forwarding 就能正常访问, enable的话就不行

**Comment by madeye** [comment]
@lostsnow Make sure you've disabled `One Time Auth`.

**Comment by lostsnow** [comment]
@madeye 可以了, thx
原来是这个, 没注意 OTA 新版移除了?
