### ISSUE TITLE
多用户配置下分应用代理失效

### ISSUE THREAD

**Issue by AntSYau** [shadowsocks/shadowsocks-android#1184]
### Environment

Android version: 7.1.1 LineageOS 20170323
Device: OnePlus 3 A3000
Shadowsocks version: 4.1.3

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

我的手机上有两个用户。我想在我的主用户帐号上开启分应用代理

### What did you expect to see?

执行分应用代理

### What did you see instead?

显示错误：无法连接至服务器：Failed to connect remote server: get package uid: neither user 10102 nor current process has Android.permission.INTERACT_ACROSS_USERS

**Comment by madeye** [comment]
Is there any error when opening the per-app proxy list?

**Comment by madeye** [comment]
It looks a bug of your ROM's VPNService. Could you try other ROMs first? e.g. the official ROM from Oneplus.

**Comment by AntSYau** [comment]
Well, I think that the problem seems to be linked with multiple users on one  single device, when the app simply don't have the permissions to get the list of apps that is installed by other users and 'interact' with them.
So, creating a second user on any Android device may lead to this problem too. If not, then it is just a system bug:)

**Comment by AntSYau** [comment]
Oh, there isn't any error shown when opening the Per-App Proxy list

**Comment by AntSYau** [comment]
I will convert to the official ROM this weekend and see if it can fix this.

**Comment by ljl024** [comment]
Oneplus A3000，使用OxygenOS openbeta12
在主用户正常使用的情况下，添加一个用户
进入新用户初始化设置，不在新用户中安装shadowsocks
在主用户中开关代理（已开启分应用代理-绕过模式）没有遇到问题

**Comment by Mygod** [comment]
Similar issue at Adguard: https://github.com/AdguardTeam/AdguardForAndroid/issues/173

**Comment by Mygod** [comment]
I'm unable to reproduce this error. However I noted that other users don't have access to VPN section in System Settings.

**Comment by AntSYau** [comment]
OK, it seems to be a system bug. I'll ask Linage OS developers for futher suggestions.
