### ISSUE TITLE
流量显示有问题

### ISSUE THREAD

**Issue by sjdjfcu** [shadowsocks/shadowsocks-android#1186]
v4.1.3 使用youtube app 播放视频时，底部的灰色缓冲条一直在移动，但是通知栏的"接收:"一直显示0 Bytes/s，持续几秒钟后就瞬间升到10 MB/s 左右，然后立刻恢复到0 Bytes/s ，显然无法实时显示当前速度。使用浏览器在线播放视频时也是如此。

**Comment by Mygod** [comment]
Try a reboot.

**Comment by sjdjfcu** [comment]
I have tried it on redmi note 3 (lineage 7.1.1) and xperia z2(6.0.1) ,but it doesn't take effect.I think it's v4.1.3's problem, because It's normal for v4.1.2.

**Comment by Mygod** [comment]
Attach more information and/or logcat and we'll see what we can do about that.

**Comment by sjdjfcu** [comment]
Look at this screen record:https://youtu.be/sPigFCAMftU
The speed on notificaiton was staying 0 Bytes/s while the gray bar at the bottom of the player was moving.

**Comment by sjdjfcu** [comment]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: redmi note 3 (kenzo)
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable):4.1.2

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?


### What did you expect to see?


### What did you see instead?

**Comment by Mygod** [comment]
Still unsure what the issue is. Probably a device bug. Could you please grab a logcat if convenient? Anyway it's still just a minor issue.

**Comment by sjdjfcu** [comment]
logcat:https://drive.google.com/file/d/0B_dxZgQMmUx1QlJtVU1mVzNCU0k/view?usp=drivesdk

I don't think it's a device bug:
①;v4.1.2 did not exhibit the issue on my devices.
②;Both redmi note 3 and xperia z2 exists the issue according to my use.

Maybe you can try it on your own devices:
①;Open YouTube app and choose a relatively long video to watch
②; Slide the seek bar so that it will load.
③; Slide down notification and notice the speed.
It will prove to be a general issue on v4.1.3

What's more, the issue only exists in online viedos as far as I am concerned.The speed displays in real time when downloading file or browsing the web.

**Comment by Mygod** [comment]
Just double checked. Still cannot reproduce. @madeye Any thoughts?

**Comment by madeye** [comment]
I cannot reproduce this either.

One possible reason is related to Youtube app's buffering strategy, which only buffers a small part of video ahead, say 60s. As a result, it your connection is good, you would see traffic stats dropped to zero as Youtube has got enough data buffered and stop buffering to save traffic/battery.

I suggest to enable the nerd stat feature in your Youtube app and post the bandwidth lines here.

**Comment by sjdjfcu** [comment]
@madeye ![screenshot_20170415-093508](https://cloud.githubusercontent.com/assets/25857422/25059768/4801cb16-2152-11e7-8961-93dbad8368b1.png)

{"csdk":"25","cbrand":"Xiaomi","c":"android","cbrver":"12.13.53","cmodel":"Redmi Note 3","cplatform":"mobile","cver":"12.13.53","cbr":"com.google.android.youtube","cosver":"7.1.1","cos":"Android","videoid":"Fq0xEpRDL9Q","cpn":"3YpoMBs7b626NjII","fmt":"137","afmt":"140","bh":0,"bwe":14879713,"conn":3,"bat":"0.750:0","df":"1\/5288","timestamp":"2017-04-15T01:34:54.535Z","glrenderingmode":"RECTANGULAR_2D"}

**Comment by madeye** [comment]
According to the screenshot, the bandwidth line looks normal. It'd be better you can post a screen cast of your traffic numbers during watching a Youtube video.

**Comment by sjdjfcu** [comment]
@madeye https://youtu.be/sPigFCAMftU

**Comment by madeye** [comment]
I cannot reproduce your issue locally. It looks like the interprocess communication on your system is throttled which causes the traffic stat update is not that smooth.

Have you enabled any battery saving feature of your ROM , or any background service throttling tools, or xposed based tools?

**Comment by madeye** [comment]
BTW, are you using kcptun?

**Comment by sjdjfcu** [comment]
@Mygod None.

**Comment by sjdjfcu** [comment]
@madeye I think you can test it on your own devices.

**Comment by madeye** [comment]
As I said, we cannot reproduce your issue locally. I tested on three devices including Pixel, Nexus 9 and OnePlus 2. None of them have this issue.

Since it's a device related issue and no similar reports from other users, I don't think we can help you further.

**Comment by madeye** [comment]
It turns out a bug related to the traffic update of UDP relay.

Since 4.1.3, we enabled UDP relay by default. And Youtube actually are using QUIC (UDP) to transfer the data. However, `ss-local` didn't trigger the state change callback when there is only UDP traffic. It then causes the traffic numbers not that smooth.

**Comment by madeye** [comment]
@sjdjfcu Could you try this APK? https://www.dropbox.com/s/ks6xk0l18p4or67/shadowsocks-nightly-4.1.7.apk

**Comment by sjdjfcu** [comment]
@madeye 4.1.7 is OK.

**Comment by Mygod** [comment]
@madeye Great!
