### ISSUE TITLE
Invalid server name

### ISSUE THREAD

**Issue by gongzelong** [shadowsocks/shadowsocks-android#1188]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:6.0.1 MXB48T
* Device: XIAOMI 5
* Shadowsocks version: 
 4.1.3
![image](https://cloud.githubusercontent.com/assets/21305437/24585471/c4061dbe-17bd-11e7-9cdf-61c46785066d.png)
* Last version that did not exhibit the issue (if applicable):
None.

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Click the button to connect.

### What did you expect to see?
Invalid server name toast.

### What did you see instead?

![image](https://cloud.githubusercontent.com/assets/21305437/24585484/252379ac-17be-11e7-8b0b-79409749c6db.png)
![image](https://cloud.githubusercontent.com/assets/21305437/24585490/36149822-17be-11e7-934f-8cf46f4c3d44.png)

**Comment by gongzelong** [comment]
I cannot download the latest app version though I can browser the app in my Ubuntu.
The server is okay because I can use it in my Ubunbu and OS X.

**Comment by Mygod** [comment]
Look closely at your "-" symbol.

**Comment by gongzelong** [comment]
Oh, I used it wrongly.
You are awesome.
I had tried many times.
Thanks for your immediate reply. :+1:
