### ISSUE TITLE
One-time authentication does not work for me since Shadowsocks-android version v3.4.0

### ISSUE THREAD

**Issue by BurnySnek** [shadowsocks/shadowsocks-android#1189]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 5 AOSP-based Russian ROM
* Device: Xiaomi-redmi note 2
* Shadowsocks version: starting from version v3.4.0 (tested every single one from current to v3.3.0, issue starts from v3.4.0, currently sitting on v3.3.1 where One-time auth still works

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method: SALSA
* [ ] One-time authentication < this is precisely the problem :(
* Route < tested all all options here
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Tried to update my old shadowsocks which I didn't update in a long while

### What did you expect to see?
Everything working 

### What did you see instead?
I could not connect to a shadowsocks server that has one-time auth enabled.

Upon trying downgrading shadowsocks to different versions, discovered that problem starts at version v3.4.0

last version that works for me is 
v3.3.1 
 
Also, when manually creating profiles, I can't seem to find the one-time auth option

**Comment by coderfox** [comment]
One-time-auth is deprecated, use AEAD ciphers instead, e.g. `chacha20-ietf-poly1305`.
