### ISSUE TITLE
从play store更新到2.2.3后rc4-md5不能用了

### ISSUE THREAD

**Issue by hueyless** [shadowsocks/shadowsocks-android#119]
应该是无法解析域名，但是不确定。也有人反映改回aes-256-cfb后就好了。

**Comment by YcdYng** [comment]
rc4-md5 not working

**Comment by Sherlock-Holo** [comment]
不建议使用rc4-md5，据说深度检测已经可以识别他，据说！

EastWood <notifications@github.com>于2017年1月4日周三 20:09写道：
