### ISSUE TITLE
ipv6 bad address

### ISSUE THREAD

**Issue by huiselilun** [shadowsocks/shadowsocks-android#1190]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Nexus 9
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
try to connect my server with ipv6. 

### What did you expect to see?
connected successfully

### What did you see instead?
fialed to connetc the remote server: bad address

**Comment by Mygod** [comment]
Check again your address.

**Comment by huiselilun** [comment]
My address just like below.
2001:19f2:7001:cb2:5400:00ff:fe34:d658
Is there something wrong with "cb2" ? But it's OK in Shadowsocks  Windows version.

**Comment by Mygod** [comment]
Could you specify the version you're using?

**Comment by huiselilun** [comment]
4.1.3

**Comment by Mygod** [comment]
What about remote DNS?

**Comment by Mygod** [comment]
What about remote DNS?

**Comment by huiselilun** [comment]
Remote DNS is blank.

**Comment by Mygod** [comment]
It won't work then. Fill in `8.8.8.8`.

**Comment by huiselilun** [comment]
It works. thank you.
