### ISSUE TITLE
how to use a ipv6 DNS? just like "2001:4860:4860::8888".

### ISSUE THREAD

**Issue by zhcong** [shadowsocks/shadowsocks-android#1197]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
It seemd that this app can only use ipv4 DNS like "8.8.8.8", how use a ipv6 DNS? I have a ipv6 environment. And my shadowsocks server version is 2.8.2, it works on a ubuntu machine.

### What did you see instead?

I can't find a option useful.

**Comment by Mygod** [comment]
You should be able to resolve IPv6 records if your server is running on dual stack even with an IPv4 DNS address.

**Comment by zhcong** [comment]
there has a option "远程DNS", defaults value is "8.8.8.8:53", if I fill in it a ipv6 address, App can't connect to my server.
And see from my server, it show client allways want to connect to 8.8.8.8:53.

**Comment by whour** [comment]
8.8.8.8 可以解析IPv6的地址呀
`dig google.com @8.8.8.8 aaaa`
vps上要有IPv6的地址呀

**Comment by zhcong** [comment]
抱歉说错了，服务器不能访问ipv4的内容，也就是无法连接8.8.8.8

**Comment by whour** [comment]
那你可以在json文件里面添加
 `"nameserver":"8.8.8.8,4.2.2.1"`
 8.8.8.8不稳定可以换其他DNS服务。

**Comment by zhcong** [comment]
谢谢，我试试添加ipv6的DNS
