### ISSUE TITLE
UDP relay doesn't work when kcptun enabled

### ISSUE THREAD

**Issue by 1997cui** [shadowsocks/shadowsocks-android#1201]
UDP relay is not working when kcptun enabled. I guess the reason is that when kcptun enabled, all the traffic (include UDP) is forwarding to kcptun process by shadowsocks, however, kcptun could not handle UDP packet yet.

This could be solved by add a separated "remote port" and "remote address" option, and when kcptun plugin is enabled, create a dedicated shadowsocks process to only deal with UDP relay.
   
### Environment

* Android version: "7.0.0"
* Device: Nexus 6
* Shadowsocks version: "v4.1.3 google play"

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable): kcptun
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by madeye** [comment]
Try this: https://github.com/shadowsocks/shadowsocks-android/issues/1090#issuecomment-274404651

**Comment by 1997cui** [comment]
解决了，方法是在Android客户端把前面的远程端口号换成shadowsocks的端口号，最后在kcp的配置里把remoteaddr配置成kcp的端口号。不过这个解法真tricky，希望能改改Android版的界面

**Comment by Mygod** [comment]
It's an unofficial workaround since UDP isn't officially supported by the plugins.

**Comment by ryanerwin** [comment]
@1997cui 这个kcptun插件的remoteaddr配置你可以多解释吗？

我设置的UDP remoteaddr在电脑上能使用，但是在安卓上就用不了kcptun。。。

我认为关键问题是怎么配置本地SS来链接到本地的KCPTUN？我试试把SS服务器为127.0.0.1，端口：12948 （kcptun的默认 localaddr端口）但是SS失败反应那么快。。。感觉根本没有启动kcptun的代理。。。

我查到两年前的截图，当时SS有KCP端口可以直接设置，但是现在没有。。。

**Comment by eebssk1** [comment]
@ryanerwin
相同的问题，在安卓kcp插件配置里写remoteaddr根本连不上

**Comment by ryanerwin** [comment]
@eebssk1 

这个是我的详细配置。。。

![ss](https://h4u-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/3/3fd7443f70f0325ab14e4de5c0174c8ef67b91c8.jpg)
