### ISSUE TITLE
后台服务启动失败，无法连接远程服务器

### ISSUE THREAD

**Issue by williamking** [shadowsocks/shadowsocks-android#1202]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 5.0.2
* Device: unknown
* Shadowsocks version: v3.4.2 && v4.1.3

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: RC4-MD5
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
我在PC端上能成功连接的SS代理，在最新版本(v4.1.3)的安卓客户端上连接却显示下图的错误：
![image](https://cloud.githubusercontent.com/assets/7439138/24868329/4927cb52-1e42-11e7-817d-7742759836fb.png)
后面我又换用了(v3.4.2)版本，还是出现同样的错误，我怀疑是代理只能单点连接，但是断开PC端代理连接后，手机依然还是一样的错误结果。

**Comment by Mygod** [comment]
I can tell a ROM is bugged with my naked eyes.
