### ISSUE TITLE
影梭在Android 7.0开机无法自启动自连接

### ISSUE THREAD

**Issue by kn007** [shadowsocks/shadowsocks-android#1206]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: Oneplus 3T
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: CHACHA20
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
设置了“自动连接”

### What did you expect to see?
影梭跟随系统启动并连接

### What did you see instead?
没有随系统启动

**Comment by Mygod** [comment]
Check again settings in Shadowsocks and your system settings.

**Comment by kn007** [comment]
@Mygod New System(oxygen OS), Shadowsocks had already setting "auto connect".
I don't know why.

**Comment by kn007** [comment]
After upgrade to 7.1.1, it's work fine.
