### ISSUE TITLE
Tap the "test connection" always get failure

### ISSUE THREAD

**Issue by weyou** [shadowsocks/shadowsocks-android#1208]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Oneplus3T
* Shadowsocks version: 4.1.3/4.1.4
* Last version that did not exhibit the issue (if applicable): 

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [X] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [X] Auto Connect
* [X] TCP Fast Open
* [ ] NAT mode

### What did you do?
Tap the "test connection", I always get the failure report "failed to connect to www.google.com/xx.xx.xx.xx".  But actually, google is accessible with web browser.  Please note that I have put the web browser to the Per-App proxy rule. Do I need put ss itself into the Per-App list?  But I think ss should take care of this by itself.

**Comment by Mygod** [comment]
Check Shadowsocks in Per-App Proxy.
