### ISSUE TITLE
can connect but no Internet connect 

### ISSUE THREAD

**Issue by Kelyvon** [shadowsocks/shadowsocks-android#1209]
I can connect to my server ,but when I did the connection test, it went wrong.
And the result shows below:
失败：Unable to resolve host"www.google.com":No address associated with hostname

my telephone information:
nubia z11
Android 6.0.1

Please help me, thank you!

**Comment by Mygod** [comment]
Duplicate.

**Comment by huangri212** [comment]
I`m facing the same issue,have you resolve it currently?and how? 
really appreciate it !
