### ISSUE TITLE
Battery Drain in mobile network(I've seen FAQ about the other background service eg. Google)

### ISSUE THREAD

**Issue by Cirooo** [shadowsocks/shadowsocks-android#1210]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1 LineageOS 14 mako-nightly-20170406
* Device: Google Nexus 4
* Shadowsocks version: 3.3.5
* Last version that did not exhibit the issue (if applicable): Unknown

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* [x ] NAT mode(Since today)

### What did you do?
I noticed that the battery drain fast under mobile network. So I just turn off ssr when I go outside.

I'm using Unicom 3G network, and the battery drain fast. **I've seen FAQ**, maybe it's the issue of battery stat by Android itself. But if it's wifi, anything normal, including ssr. Anyway, I can turn ssr off when I use 3G network.
Today, I found that the NAT mode(deprecated) could remove the exclamation mark, maybe it's less useful than vpn mode, but it's a good manner for me. And could you just keep this feature while not recommend to other users to avoid advanced requests. And I want to try this mode to star whether it still has the battery issue.

**Comment by madeye** [comment]
> I noticed that the battery drain fast under mobile network. So I just turn off ssr when I go outside.

I suggest to open an issue here instead. https://github.com/shadowsocksr/shadowsocksr-android

> I'm using Unicom 3G network, and the battery drain fast. I've seen FAQ, maybe it's the issue of battery stat by Android itself. But if it's wifi, anything normal, including ssr. Anyway, I can turn ssr off when I use 3G network.

It's just a battery stat issue. 3G is expected to consume much more battery than Wi-Fi.
