### ISSUE TITLE
I cannot use shadowsocks app.

### ISSUE THREAD

**Issue by muweigg** [shadowsocks/shadowsocks-android#1211]
![image](https://cloud.githubusercontent.com/assets/5467869/24999247/6aed30fe-206f-11e7-86c6-e4f0d397ca1c.png)

Android emulator koplayer 1.4.1055.
confirmed server configuration is ok. but can not start vpn mode. 
prompt an error.

**Comment by Mygod** [comment]
Your ROM is bugged.
