### ISSUE TITLE
工程编译问题

### ISSUE THREAD

**Issue by tangxu0717** [shadowsocks/shadowsocks-android#1212]
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Timed out

编译的时修报这个错，不知道怎么解决的

**Comment by muweigg** [comment]
一看就是被墙了，翻墙吧~

**Comment by tangxu0717** [comment]
已经翻墙了啊，还是不行

**Comment by tangxu0717** [comment]
求助，我google了好久，还是没找到解决方案

**Comment by muweigg** [comment]
开启全局模式。
或者，如果在cmd命令里，执行命令 set http_proxy=http://127.0.0.1:1080，设置cmd的代理

**Comment by tangxu0717** [comment]
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Proxy CONNECT aborted due to timeout
fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path 'mobile/src/main/jni/pcre' failed

还是不行呀

**Comment by pexcn** [comment]
用路由器翻墙吧

**Comment by whour** [comment]
proxychins 使用socks5代理
privoxy转换shadowsocks成http代理

**Comment by gejian311** [comment]
请问这个问题怎么解决的？

**Comment by brainweiyi** [comment]
git config --global http.proxy "localhost:1080" 设置git的代理

**Comment by auv1107** [comment]
备注一个坑：
习惯性地使用 --local 配置代理，但是 clone 操作时并不会应用父 module 的 config。
所以切记：
一定要使用 --global 配置代理。
