### ISSUE TITLE
Display IP address on connection when server is specified by a domain name.

### ISSUE THREAD

**Issue by zeptoTantalum** [shadowsocks/shadowsocks-android#1214]
It seems that in the latest 4.1.4 version, IP address will no longer be displayed when connected to a server specified by domain name. However sometimes displaying the IP address can be helpful - e.g. CERNET2 IPv6 is an free experimental network, while using CERNET IPv4 will be charged. The IP address of the server allows the user to know whether or not they are using free network connection in this condition. Is it possible to recover the IP address display?

**Comment by Mygod** [comment]
Yes. Revert this commit and build it yourself: https://github.com/shadowsocks/shadowsocks-android/commit/1268376b683937d770365030b7caaffebd309ef1

It was removed to improve consistency.

**Comment by zeptoTantalum** [comment]
Then, is it OK to add a IPv4/v6 indicator? this would keep the consistency and show user the network environment.
(Sorry about this question, for I would prefer to upgrade from google play.)

**Comment by Mygod** [comment]
No. I don't plan to add that "feature" (p.s. it was a bug) back.

Regarding your use case, I'd recommend you to use IP addresses directly which is faster (saves a DNS query).
