### ISSUE TITLE
Client ShadowsSocks for Android has a terrible disadvantage!

### ISSUE THREAD

**Issue by Tamila-2017** [shadowsocks/shadowsocks-android#1218]
Attention!

Client ShadowsSocks for Android has a terrible disadvantage - **leak DNS**!

Check using the site **http://dnsleaktest.com**: 

```
Test complete
Query round Progress... Servers found
1            ......            4

IP              Hostname    ISP       Country
173.194.98.4     none       Google    Finland
173.194.98.9     none       Google    Finland
74.125.74.6      none       Google    Finland
173.194.98.7     none       Google    Finland
```

But I have on a remote ShadowsSocks-server  **absolutely other DNS address**, not from Google!

**DNS leaks expose me and pose a huge danger!**
Fix this immediately, please!

PS. This error in the client ShadowsSocks for Linux is missing :-)
Linux-client is working correctly. It does not used the DNS from Google.

### Environment

* Android version: 4.4.4 and 5.1.1
* Device: SGT P1000 and Xiaomi Redmi Note 3
* Shadowsocks Client version: v3.1.0

### Configuration

* Local port: 1080
* Encrypt method: AES-256-CFB
* [ no ] One-time authentication
* Route
  * [ yes] All
* [ no ] IPv6 route
* Remote DNS: my_private_server
* [ yes ] DNS Forwarding
* Plugin configuration (if applicable):
* [ yes ] Auto Connect  (- however, this does not work)
* [ no ] TCP Fast Open
* [ no ] NAT mode

### What did you see instead?

Fix this immediately, please! it's - dangerous!!!

**Comment by madeye** [comment]
What's your remote DNS settings in shadowsocks-android?

**Comment by madeye** [comment]
And the DNS settings for your server?

**Comment by madeye** [comment]
If you're using shadowsocks-libev as your server, make sure add `-d your_private_server` to your command line.

**Comment by Tamila-2017** [comment]
> What's your remote DNS settings in shadowsocks-android?

The DNS settings in the shadowsocks-android do not exist.

> And the DNS settings for your server?

```
resolv.conf:
search ispsystem.net
nameserver 188.120.247.2
nameserver 188.120.247.8
nameserver 82.146.59.250
```

> If you're using shadowsocks-libev as your server, make sure add -d your_private_server to your command line.

No. I use on server a regular ShadowSocks  3.0.0
https://shadowsocks.org/en/download/servers.html
There -d option is not suitable

**Comment by madeye** [comment]
If so, try `dns_server` in your config file. The default server is `8.8.8.8`.

**Comment by Tamila-2017** [comment]
Which config (server or client)?

**Comment by Tamila-2017** [comment]
(again):  **Which config (server or client)?**

**Comment by madeye** [comment]
Your server's config.
