### ISSUE TITLE
自定义ACL疑似存在DNS解析BUG

### ISSUE THREAD

**Issue by BROBIRD** [shadowsocks/shadowsocks-android#1219]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0
* Device: PLK-TL01H
* Shadowsocks version: 
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
使用自定义ACL（~~自定义更新URL~~从剪贴板导入）

### What did you expect to see?
DNS解析按照规则分别交由ChinaDNS和国外DNS解析

### What did you see instead?
所有地址疑似都由Remote DNS解析，导致部分国内网站无法正常访问。SSR版也有同样的问题。

**Comment by madeye** [comment]
Try the latest version of shadowsocks.

**Comment by madeye** [comment]
> 使用自定义ACL（自定义更新URL）

I don't think we support a customized ACL from URL.

**Comment by BROBIRD** [comment]
感谢回复，我确认了一下，原版是因为默认打开了DNS转发，关掉之后好像就正常了，SSR版的自定义ACL确实是有BUG，无法按照本地设置分流DNS解析。
