### ISSUE TITLE
在4G/2G网络直接切换后，无法继续上网

### ISSUE THREAD

**Issue by greensea** [shadowsocks/shadowsocks-android#1230]
### Environment

我知道官方不支持 MIUI，但我觉得此问题有可能在非 MIUI 上也能重现，希望有人能够在非 MIUI 上尝试重现此问题。另外，作为一个比较容易重现，但不容易找到重现步骤的问题，我觉得把它记录下来供后人参考也是好的。

* Android version: Android 7.0 (MIUI 8 7.4.13 国际版)
* Device: 红米 Note4X
* Shadowsocks version: 4.1.3
* Last version that did not exhibit the issue (if applicable): 不确定，以前也遇到过类似的断网的情况，但不确定是否与本问题有关。

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x ] IPv4 server address
* [ x ] IPv6 server address
* [ x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: CHACHA20-IETF-POLY1305
* [ ] One-time authentication
* Route
  * [ x ] All
（备注：平常我使用 Bypass LAN & China 模式，也会遇到此问题，但为了更容易调查此问题，我选择了 ALL 模式来进行测试，并重现了此问题。）
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ x ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### 简单的重现步骤
在 4G 网络下启动 ShadowSocks 并连接，然后到手机的网络设置中强制要求手机只使用 2G 网络，接着再要求手机优先使用 4G 网络，当网络从 4G 切换到 2G 再切换回 4G 后，就无法上网了。如果这时候断开 ShadowSocks 的连接，则可以继续正常上网。

### 详细的重现步骤

1. 打开 ShadowSocks，将代理模式设置位“全局”，并连接到服务器
1. 关闭手机的 WLAN，只使用数据流量上网。
1. 等待手机切换到 4G 网络
1. 手机连接到 4G 网络后，使用浏览器随意打开一个网站，确认此时可以正常上网
1. 进入手机的网络设置，将网络类型选择更改为“只使用 2G 网络”，强制手机切换到 2G 数据网络
1. 等待手机切换到 2G 数据网络后，再次进入网络设置，将网络类型选择修改为“4G 优先“
1. 等待手机连接到 4G 网络，然后用浏览器打开刚才的网站，这时会发现网站打不开了
1. 此时有两种办法可以恢复网络：
*  进入 ShadowSocks，断开连接，然后重新连接
* 打开 WLAN，并连接上一个可用的热点的热点

**Comment by madeye** [comment]
It looks a device or Android bug. You may report it to Xiaomi or AOSP issue tracker.

**Comment by Mygod** [comment]
Unable to reproduce this either on Lineage OS 14.1.

Try the following workaround:

1. Open phone info; (you can start it by entering `*#*#4636#*#*` in dialer)
2. Put "Set preferred network type" to "LTE only".

**Comment by madeye** [comment]
Closed due to inactivity.
