### ISSUE TITLE
Can not share the profiles with shadowsocks-windows

### ISSUE THREAD

**Issue by zongou** [shadowsocks/shadowsocks-android#1231]
I was using both shadowsocks-android and shadowsocks-windows at the same time, and I wanted to share the profiles that on my cellphone with my PC, I tried both creating QR code and SS links, nor did they work.

**Comment by madeye** [comment]
It's expected. Manually input your server info to your windows client.

**Comment by zongou** [comment]
Is there a plan to make it easy to share profiles between these programs?

**Comment by zongou** [comment]
Since shadowsocks-android and shadowsocks-windows both support add multiple profiles via shadowsocks URL, I wished I can manage my profiles  with only one profile text.

**Comment by madeye** [comment]
No, we don't have any plan to "update" shadowsocks-android. When shadowsocks-windows supports SIP002 and SIP003 in the future, you would get the new QR code and URL format supported on windows.

**Comment by ns0213** [comment]
Hey guys, I am having the same issue. Except that I'm connected to Shadowsocks on Android and I cannot remember my password to input into the Windows program. Is there a way to retrieve this password?

Thanks in advance!
