### ISSUE TITLE
kcptun转为插件形式后不可用

### ISSUE THREAD

**Issue by 10people** [shadowsocks/shadowsocks-android#1232]
kcptun转为插件形式后不可用，之前的版本3.4.2可用

### Environment

* Android version: 6.0.1
* Device: Xiaomi 5s
* Shadowsocks version: v4.0.0+
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [x] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable): kcptun
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
Update the latest version.

### What did you expect to see?
Kcptun works fine.

### What did you see instead?
Kcptun fail but original shadowsocks works fine.

ps.Ubuntu 17 最新内核，shadowsocks kcptun 服务器版本均为最新

**Comment by 10people** [comment]
由于开启了UDP转发但是没有添加remoteaddr参数

**Comment by foxundermoon** [comment]
最新版本  把远程dns转发打开可以用了
