### ISSUE TITLE
Custom rule 192.168.8.0/24 seems not working 

### ISSUE THREAD

**Issue by myfingerhurt** [shadowsocks/shadowsocks-android#1233]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: v5.1.1 kernel 3.4.67-g84ad5a4
* Device: Google Nexus 10
* Shadowsocks version: v4.1.5
* Last version that did not exhibit the issue (if applicable): Not sure

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
There is only one rule in my custom rules, I want to route all 192.168.8.0/24 traffic to remote server(go proxy), all the other traffic go direct. DNS requests phrase on the client end

### What did you expect to see?
See above.

### What did you see instead?
All traffic went to remote server, this ain't right, and completely went the opposite. And when accessing 192.168.8.6, no traffic was actually delivered to remote server. Inspecting the server log, I found nothing about 192.168.8.6 in the logs, and all DNS requests were also send to server end instead of phrasing on client end, despite the dns forward was off.

**Comment by madeye** [comment]
It's expected. Custom ACL only works for public IPs.

**Comment by myfingerhurt** [comment]
I really hope the custom rule would work on Class C IP address too, the PC version of shadowsocks client and all kinds of iOS clients are working flawlessly on Class C IPs. I hope you guys could fix this soon.
