### ISSUE TITLE
gfwlist.txt不需要base64编码

### ISSUE THREAD

**Issue by him007** [shadowsocks/shadowsocks-android#1235]
### Environment

* Shadowsocks version: *version code "v4.1.5"

### What did you do?

`shell>cat /data/data/com.github.shadowsocks/files/overture-vpn.conf`
`{"BindAddress":":1133","RedirectIPv6Record":true,"DomainBase64Decode":true,"HostsFile":"hosts","MinimumTTL":3600,"CacheSize":4096,"PrimaryDNS":[{"Name":"Primary-1","Address":"119.29.29.29:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"udp"},{"Name":"Primary-2","Address":"114.114.114.114:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"udp"}],"AlternativeDNS":[{"Name":"8.8.8.8","Address":"8.8.8.8:53","Timeout":6,"EDNSClientSubnet":{"Policy":"disable"},"Protocol":"tcp","Socks5Address":"127.0.0.1:1080"}],"IPNetworkFile":"china_ip_list.txt","DomainFile":"gfwlist.txt"}`

### What did you expect to see?
使用解码后的gfwlist.txt

### What did you see instead?
使用的是base64编码的gfwlist.txt

**Comment by madeye** [comment]
It's expected and by design.
