### ISSUE TITLE
shadowsocks-android包括4.1.0及以上版本在android5.0以下手机可以连接但无网络

### ISSUE THREAD

**Issue by SuperMan42** [shadowsocks/shadowsocks-android#1242]

**Comment by madeye** [comment]
You'd better upgrade your phone to Android 5.0 or above. If not, please keep using 3.x version.

**Comment by madeye** [comment]
Could you try this APK? https://www.dropbox.com/s/au3gavr8jadjhxh/shadowsocks-nightly-4.1.7-experiment-2.apk
