### ISSUE TITLE
please provide apk ! 

### ISSUE THREAD

**Issue by Kyson** [shadowsocks/shadowsocks-android#1244]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
i am installing shadowsocks

### What did you expect to see?
it must be installed through googleplay! while i am in china and can not open google play

### What did you see instead?
please give me an apk file ,thx

**Comment by hellofwy** [comment]
https://github.com/shadowsocks/shadowsocks-android/releases

Search first please.

**Comment by dqwyy** [comment]
In my opinion, it would be better if a link to *releases/apk file* could be provided on [README.md](https://github.com/shadowsocks/shadowsocks-android/blob/master/README.md), beside the *GET IT ON Google Play* button. That will help those who are not familiar with GitHub.
