### ISSUE TITLE
Where to turn on the kcptun?

### ISSUE THREAD

**Issue by ACGunion** [shadowsocks/shadowsocks-android#1245]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1 LineageOS
* Device: One Plus One
* Shadowsocks version: 4.1.6
* Last version that did not exhibit the issue (if applicable):N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:CHACHA20
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Add new server and i want turn on KCP
### What did you expect to see?
A way to set KCP client configuration
### What did you see instead?
nothing... The plugin was disabled and i can't turn it on

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/plugin/README.md#official-plugins
