### ISSUE TITLE
Connection issue on Flyme 6, android 5.1

### ISSUE THREAD

**Issue by chaoqunq** [shadowsocks/shadowsocks-android#1247]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *5.1, build number: Flyme 6.0.2.0A*
* Device: *MEIZU m3 note*
* Shadowsocks version: *v4.1.6*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-256-CFB
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
SS server is running on VPS.
SS is working on PC client.
Install and configure on Android phone, successfully connected.

### What did you expect to see?
Pass connection test, could open YouTube, etc.

### What did you see instead?
Check connection failed, unable to resolve host. Tried reset, re-connect, restart, not working.

**Comment by Harmoc** [comment]
I have encountered this situation, do not know whether it has been resolved?

**Comment by madeye** [comment]
Could you try this APK? https://www.dropbox.com/s/au3gavr8jadjhxh/shadowsocks-nightly-4.1.7-experiment-2.apk

**Comment by chaoqunq** [comment]
Tried but still not working. Attached one screenshot about the default route, not sure if it will help.

![s70510-140634](https://cloud.githubusercontent.com/assets/26832767/25885353/88b1f126-358a-11e7-9df3-e9a1b6a4d252.jpg)

**Comment by mrseaman** [comment]
Same issue with MX4 running same system.

**Comment by Mygod** [comment]
1. Try enabling DNS forwarding;
2. Is there a version that works for you?

**Comment by chaoqunq** [comment]
Update:

I tried the new version of 4.1.7, and it worked.

Not sure if it is related to the SS update or Flyme OS update(6.1.0.0 A), or just me being stupid when configuring SS.

Thanks for the help guys!
