### ISSUE TITLE
Can not android studio compile it?

### ISSUE THREAD

**Issue by jinshakx** [shadowsocks/shadowsocks-android#1248]
Can not android studio compile it?

Information:Module "plugin" was fully rebuilt due to project configuration/dependencies changes
Information:Some files were changed during the build. Additional compilation may be required.
Information:2017/5/10 15:16 - Compilation completed with 18 errors and 0 warnings in 1m 2s 192ms
F:\test\shadowsocks-android\plugin\src\main\java\com\github\shadowsocks\plugin\PluginContract.java
Error:(10, 20) PluginContract is already defined as object PluginContract
public final class PluginContract {
                   ^
Error:(10, 20) PluginContract is already defined as class PluginContract
public final class PluginContract {
                   ^
F:\test\shadowsocks-android\plugin\src\main\java\com\github\shadowsocks\plugin\PluginOptions.java
Error:(16, 20) PluginOptions is already defined as object PluginOptions
public final class PluginOptions extends HashMap<String, String> {
                   ^
Error:(16, 20) PluginOptions is already defined as class PluginOptions
public final class PluginOptions extends HashMap<String, String> {
                   ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\DialogPreferencePlus.scala
Error:(26, 7) DialogPreferencePlus is already defined as trait DialogPreferencePlus
trait DialogPreferencePlus extends DialogPreference {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\EditTextPreference.scala
Error:(36, 7) EditTextPreference is already defined as class EditTextPreference
class EditTextPreference(context: Context, attrs: AttributeSet = null) extends Parent(context, attrs)
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\EditTextPreferenceDialogFragment.scala
Error:(27, 7) EditTextPreferenceDialogFragment is already defined as class EditTextPreferenceDialogFragment
class EditTextPreferenceDialogFragment extends PreferenceDialogFragment {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\NumberPickerPreference.scala
Error:(31, 7) NumberPickerPreference is already defined as class NumberPickerPreference
class NumberPickerPreference(private val context: Context, attrs: AttributeSet = null)
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\NumberPickerPreferenceDialogFragment.scala
Error:(28, 7) NumberPickerPreferenceDialogFragment is already defined as class NumberPickerPreferenceDialogFragment
class NumberPickerPreferenceDialogFragment extends PreferenceDialogFragment {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\PreferenceCategory.scala
Error:(33, 7) PreferenceCategory is already defined as class PreferenceCategory
class PreferenceCategory(context: Context, attrs: AttributeSet = null) extends Base(context, attrs) {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\PreferenceFragment.scala
Error:(29, 16) PreferenceFragment is already defined as class PreferenceFragment
abstract class PreferenceFragment extends Base {
               ^
F:\test\shadowsocks-android\plugin\src\main\scala\be\mygod\preference\SummaryPreference.scala
Error:(32, 7) SummaryPreference is already defined as trait SummaryPreference
trait SummaryPreference extends Preference {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\ConfigurationActivity.scala
Error:(30, 7) ConfigurationActivity is already defined as trait ConfigurationActivity
trait ConfigurationActivity extends OptionsCapableActivity {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\HelpActivity.scala
Error:(26, 7) HelpActivity is already defined as trait HelpActivity
trait HelpActivity extends OptionsCapableActivity {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\HelpCallback.scala
Error:(13, 7) HelpCallback is already defined as trait HelpCallback
trait HelpCallback extends HelpActivity {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\NativePluginProvider.scala
Error:(29, 16) NativePluginProvider is already defined as class NativePluginProvider
abstract class NativePluginProvider extends ContentProvider {
               ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\OptionsCapableActivity.scala
Error:(13, 7) OptionsCapableActivity is already defined as trait OptionsCapableActivity
trait OptionsCapableActivity extends Activity {
      ^
F:\test\shadowsocks-android\plugin\src\main\scala\com\github\shadowsocks\plugin\PathProvider.scala
Error:(13, 13) PathProvider is already defined as class PathProvider
final class PathProvider private[plugin](baseUri: Uri, cursor: MatrixCursor) {
            ^

**Comment by Mygod** [comment]
No.

**Comment by jinshakx** [comment]
But I can ubuntu  not compile successfully

**Comment by jinshakx** [comment]
Can you help me?

root@p:~/android/shadowsocks-android# sbt clean go-build android:package-release 
[info] Loading project definition from /root/android/shadowsocks-android/project
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] Set current project to shadowsocks-android (in build file:/root/android/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] Set current project to shadowsocks-android (in build file:/root/android/shadowsocks-android/)
[success] Total time: 0 s, completed 2017-5-10 15:38:17
[info] Make standalone toolchain for ARM arch
[error] mobile/src/overture/make.bash: 行 31: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Make standalone toolchain for ARM64 arch
[error] mobile/src/overture/make.bash: 行 37: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Make standalone toolchain for X86 arch
[error] mobile/src/overture/make.bash: 行 43: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Build the custom go
[info] ~/android/shadowsocks-android/mobile/src/overture/go/src ~/android/shadowsocks-android
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] ERROR: Cannot find /root/go1.4/bin/go.
[error] Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:45)
	at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 0 s, completed 2017-5-10 15:38:18
root@p:~/android/shadowsocks-android# 
root@p:~/android/shadowsocks-android#
