### ISSUE TITLE
编译成功后的apk，无法安装

### ISSUE THREAD

**Issue by minenlink** [shadowsocks/shadowsocks-android#1252]
我在尝试编译了几次后，终于成功了，但是生成的apk，无法安装进手机，提示：“解析程序包时出现问题”。

在编译的过程中有看到error log，但是并没有导致编译中止。

一直感觉是 编译环境的问题，但是定位不到具体的原因。

请问，我该怎么做才能编译出可用的apk？

build log

first build log ==>>

[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[info] 
[info] ##### Building Go toolchain using /usr/lib/go.
[error] bootstrap/cmd/internal/dwarf
[error] bootstrap/cmd/internal/sys
[error] bootstrap/cmd/asm/internal/flags
[error] bootstrap/cmd/internal/obj
[error] bootstrap/cmd/internal/bio
[error] bootstrap/cmd/compile/internal/syntax
[error] bootstrap/cmd/internal/obj/arm
[error] bootstrap/cmd/internal/obj/arm64
[error] bootstrap/cmd/internal/obj/mips
[error] bootstrap/cmd/internal/obj/ppc64
[error] bootstrap/cmd/internal/obj/s390x
[error] bootstrap/cmd/internal/obj/x86
[error] bootstrap/cmd/asm/internal/lex
[error] bootstrap/cmd/internal/gcprog
[error] bootstrap/math/big
[error] bootstrap/cmd/asm/internal/arch
[error] bootstrap/cmd/asm/internal/asm
[error] bootstrap/cmd/asm
[error] bootstrap/cmd/compile/internal/ssa
[error] bootstrap/debug/pe
[error] bootstrap/cmd/link/internal/ld
[error] bootstrap/cmd/link/internal/amd64
[error] bootstrap/cmd/link/internal/arm
[error] bootstrap/cmd/link/internal/arm64
[error] bootstrap/cmd/link/internal/mips
[error] bootstrap/cmd/link/internal/mips64
[error] bootstrap/cmd/link/internal/ppc64
[error] bootstrap/cmd/link/internal/s390x
[error] bootstrap/cmd/link/internal/x86
[error] bootstrap/cmd/link
[error] bootstrap/cmd/compile/internal/gc
[error] bootstrap/cmd/compile/internal/amd64
[error] bootstrap/cmd/compile/internal/arm
[error] bootstrap/cmd/compile/internal/arm64
[error] bootstrap/cmd/compile/internal/mips
[error] bootstrap/cmd/compile/internal/mips64
[error] bootstrap/cmd/compile/internal/ppc64
[error] bootstrap/cmd/compile/internal/s390x
[error] bootstrap/cmd/compile/internal/x86
[error] bootstrap/cmd/compile
[info] 
[info] ##### Building go_bootstrap for host, linux/amd64.
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] encoding
[error] unicode/utf16
[error] internal/syscall/windows/sysdll
[error] internal/race
[error] unicode
[error] unicode/utf8
[error] sync/atomic
[error] math
[error] errors
[error] sync
[error] internal/singleflight
[error] io
[error] syscall
[error] bytes
[error] hash
[error] strings
[error] hash/adler32
[error] strconv
[error] path
[error] bufio
[error] internal/syscall/windows
[error] internal/syscall/windows/registry
[error] time
[error] crypto
[error] reflect
[error] encoding/base64
[error] crypto/sha1
[error] os
[error] os/signal
[error] encoding/binary
[error] fmt
[error] sort
[error] regexp/syntax
[error] container/heap
[error] path/filepath
[error] io/ioutil
[error] log
[error] debug/dwarf
[error] encoding/json
[error] net/url
[error] compress/flate
[error] text/template/parse
[error] context
[error] flag
[error] go/token
[error] os/exec
[error] go/scanner
[error] regexp
[error] go/ast
[error] compress/zlib
[error] text/template
[error] debug/macho
[error] debug/elf
[error] go/parser
[error] go/doc
[error] go/build
[error] cmd/go
[info] 
[info] ##### Building packages and commands for linux/amd64.
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] errors
[error] internal/race
[error] sync/atomic
[error] unicode
[error] sync
[error] io
[error] unicode/utf8
[error] math
[error] bytes
[error] bufio
[error] syscall
[error] strconv
[error] reflect
[error] time
[error] os
[error] strings
[error] fmt
[error] encoding/binary
[error] cmd/internal/sys
[error] sort
[error] path/filepath
[error] cmd/internal/dwarf
[error] flag
[error] log
[error] path
[error] debug/dwarf
[error] cmd/internal/obj
[error] compress/flate
[error] cmd/internal/goobj
[error] hash
[error] hash/adler32
[error] debug/gosym
[error] compress/zlib
[error] debug/macho
[error] debug/elf
[error] debug/pe
[error] debug/plan9obj
[error] cmd/vendor/golang.org/x/arch/arm/armasm
[error] cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
[error] cmd/vendor/golang.org/x/arch/x86/x86asm
[error] regexp/syntax
[error] regexp
[error] text/tabwriter
[error] io/ioutil
[error] archive/tar
[error] cmd/internal/objfile
[error] hash/crc32
[error] archive/zip
[error] cmd/addr2line
[error] compress/bzip2
[error] compress/gzip
[error] compress/lzw
[error] container/heap
[error] container/list
[error] container/ring
[error] context
[error] crypto
[error] crypto/subtle
[error] crypto/cipher
[error] crypto/internal/cipherhw
[error] math/rand
[error] crypto/aes
[error] crypto/des
[error] math/big
[error] crypto/sha512
[error] crypto/hmac
[error] crypto/md5
[error] internal/syscall/unix
[error] crypto/rc4
[error] crypto/sha1
[error] crypto/sha256
[error] encoding/hex
[error] encoding/base64
[error] encoding/pem
[error] internal/nettrace
[error] internal/singleflight
[error] go/token
[error] go/scanner
[error] crypto/dsa
[error] crypto/elliptic
[error] encoding/asn1
[error] crypto/rand
[error] crypto/ecdsa
[error] crypto/rsa
[error] crypto/x509/pkix
[error] go/ast
[error] os/exec
[error] vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
[error] vendor/golang_org/x/crypto/poly1305
[error] vendor/golang_org/x/crypto/chacha20poly1305
[error] go/parser
[error] go/printer
[error] vendor/golang_org/x/crypto/curve25519
[error] database/sql/driver
[error] cmd/cgo
[error] database/sql
[error] encoding
[error] encoding/ascii85
[error] encoding/base32
[error] encoding/csv
[error] encoding/gob
[error] unicode/utf16
[error] encoding/json
[error] runtime/cgo
[error] encoding/xml
[error] vendor/golang_org/x/net/http2/hpack
[error] vendor/golang_org/x/net/idna
[error] vendor/golang_org/x/text/transform
[error] vendor/golang_org/x/text/unicode/norm
[error] net
[error] vendor/golang_org/x/text/width
[error] mime
[error] mime/quotedprintable
[error] net/http/internal
[error] net/url
[error] text/template/parse
[error] text/template
[error] go/doc
[error] go/build
[error] go/constant
[error] crypto/x509
[error] vendor/golang_org/x/net/lex/httplex
[error] net/textproto
[error] mime/multipart
[error] go/format
[error] crypto/tls
[error] go/types
[error] net/http/httptrace
[error] net/http
[error] text/scanner
[error] go/internal/gccgoimporter
[error] go/internal/gcimporter
[error] go/importer
[error] hash/crc64
[error] hash/fnv
[error] html
[error] html/template
[error] image/color
[error] image
[error] expvar
[error] image/color/palette
[error] image/internal/imageutil
[error] image/draw
[error] image/jpeg
[error] image/gif
[error] image/png
[error] index/suffixarray
[error] internal/pprof/profile
[error] internal/syscall/windows
[error] internal/syscall/windows/registry
[error] internal/syscall/windows/sysdll
[error] runtime/debug
[error] runtime/trace
[error] testing
[error] internal/trace
[error] internal/testenv
[error] log/syslog
[error] math/cmplx
[error] net/http/cgi
[error] net/http/cookiejar
[error] net/http/httptest
[error] net/http/fcgi
[error] net/http/httputil
[error] runtime/pprof/internal/protopprof
[error] runtime/pprof
[error] net/internal/socktest
[error] net/http/pprof
[error] net/mail
[error] net/rpc
[error] net/smtp
[error] os/signal
[error] net/rpc/jsonrpc
[error] os/user
[error] plugin
[error] runtime/race
[error] testing/internal/testdeps
[error] testing/iotest
[error] testing/quick
[error] cmd/api
[error] cmd/internal/obj/arm
[error] cmd/internal/obj/arm64
[error] cmd/internal/obj/mips
[error] cmd/internal/obj/ppc64
[error] cmd/internal/obj/s390x
[error] cmd/internal/obj/x86
[error] cmd/asm/internal/flags
[error] cmd/asm/internal/lex
[error] cmd/internal/bio
[error] cmd/compile/internal/syntax
[error] cmd/asm/internal/arch
[error] cmd/asm/internal/asm
[error] cmd/asm
[error] cmd/compile/internal/ssa
[error] cmd/internal/gcprog
[error] cmd/compile/internal/test
[error] cmd/internal/browser
[error] cmd/cover
[error] cmd/dist
[error] cmd/doc
[error] cmd/fix
[error] cmd/go
[error] cmd/gofmt
[error] cmd/link/internal/ld
[error] cmd/link/internal/amd64
[error] cmd/link/internal/arm
[error] cmd/link/internal/arm64
[error] cmd/link/internal/mips
[error] cmd/link/internal/mips64
[error] cmd/link/internal/ppc64
[error] cmd/link/internal/s390x
[error] cmd/compile/internal/gc
[error] cmd/link/internal/x86
[error] cmd/link
[error] cmd/nm
[error] cmd/objdump
[error] cmd/pack
[error] cmd/pprof/internal/plugin
[error] cmd/pprof/internal/report
[error] cmd/pprof/internal/svg
[error] cmd/pprof/internal/tempfile
[error] cmd/pprof/internal/commands
[error] cmd/pprof/internal/driver
[error] cmd/pprof/internal/fetch
[error] cmd/pprof/internal/symbolizer
[error] cmd/pprof/internal/symbolz
[error] cmd/pprof
[error] cmd/trace
[error] cmd/vet/internal/cfg
[error] cmd/vet/internal/whitelist
[error] cmd/vet
[error] cmd/compile/internal/amd64
[error] cmd/compile/internal/arm
[error] cmd/compile/internal/arm64
[error] cmd/compile/internal/mips
[error] cmd/compile/internal/mips64
[error] cmd/compile/internal/ppc64
[error] cmd/compile/internal/s390x
[error] cmd/compile/internal/x86
[error] cmd/compile

...
more log

contain other error log
...

obile/target/android/intermediates/ndk/jni/x86/libredsocks.so
[x86] Install        : libss-local.so => /home/mzx/Desktop/shadowsocks-android/mobile/target/android/intermediates/ndk/jni/x86/libss-local.so
[x86] Install        : libss-tunnel.so => /home/mzx/Desktop/shadowsocks-android/mobile/target/android/intermediates/ndk/jni/x86/libss-tunnel.so
[info] Packaged: shadowsocks-release-unsigned.apk (8.54MB)
[warn] Package needs signing: shadowsocks-release-unsigned.apk
[warn] Package needs signing and zipaligning: shadowsocks-release-unsigned.apk
[success] Total time: 219 s, completed May 10, 2017 11:50:01 PM

**Comment by ageback** [comment]
Your apk file is not signed.

**Comment by minenlink** [comment]
@ageback 
thanks very much.

i modify like this:

![image](https://cloud.githubusercontent.com/assets/25025688/25938037/8072cd10-3660-11e7-9476-a4e249c33dab.png)

mobile/local.properties info:

key.alias: demo
key.store: /home/mzx/Desktop/shadowsocks-android/mobile/demo.jks
key.store.password: 123456

but the same ,anything is wrong ?

**Comment by Mygod** [comment]
You should learn the basics yourself. Stop spamming this issue tracker.
