### ISSUE TITLE
一次性认证选项会自动打开

### ISSUE THREAD

**Issue by jinliming2** [shadowsocks/shadowsocks-android#1253]
将一次性认证选项关闭后，如果将界面滚动到底部（不一定非要滚到底，大概是在一次性认证选项被滚出界面之后），再滚回去，选项会被自动打开。
上面这个步骤在我手机上复现100%

打开与关闭NAT模式都一样

软件已重装：问题依旧
手机前几天刷机：问题依旧

软件是从Play商店下载的，应该没有问题（电脑上ss允许局域网连接）
#516 #531 #779

**Comment by Mygod** [comment]
Update to latest version.
