### ISSUE TITLE
how to fix the error of compile event

### ISSUE THREAD

**Issue by wooi** [shadowsocks/shadowsocks-android#1256]
This error show up for build the app 

[x86] Compile        : event <= listener.c
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.APLRecord$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.Compression$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[x86] Compile        : event <= log.c
[x86] Compile        : event <= poll.c
[x86] Compile        : event <= select.c
[x86] Compile        : event <= signal.c
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.UDPClient$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.ZoneTransferIn$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[x86] Compile        : event <= strlcpy.c
[x86] Compile        : ss-local <= local.c
[x86] Compile        : ss-local <= cache.c
[x86] Compile        : ss-local <= udprelay.c
[x86] Compile        : ss-local <= utils.c
[x86] Compile        : ss-local <= netutils.c

**Comment by Mygod** [comment]
You don't.
