### ISSUE TITLE
关于 DNS 流程的重新设计

### ISSUE THREAD

**Issue by a8l1vy** [shadowsocks/shadowsocks-android#1259]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *"7.1.2_N2G47O", more detailed description is preferred* N2G47O
* Android version: *"7.0_不知道", more detailed description is preferred* LON-AL00××××xxxx
* Device: *Google Pixel XL* *Huawei mate 9 pro*
* Shadowsocks version: *version code "v4.1.7" or commit ID "不知道"*
* Last version that did not exhibit the issue (if applicable): 一直存在的问题想建议改进。

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address 有
* [x ] IPv6 server address 有
* [x ] Client IPv4 availability 是的
* [ ] Client IPv6 availability 不是
* Local port: 1080 是的
* Encrypt method: 用的是md5-rc
* [ ] One-time authentication 不用这个
* Route
  * [ ] All 有时候用这个
  * [ ] Bypass LAN 基本不用
  * [ ] Bypass China 基本不用
  * [ ] Bypass LAN & China 有时候用这个
  * [ ] GFW List 大部分时间用这个
  * [ ] China List 不用
  * [ ] Custom rules 不用
* [ ] IPv6 route 有时候选，有时候不选
* [ ] Per-App Proxy 不用这个
  * [ ] Bypass mode 用的是 VPN
* Remote DNS: 8.8.8.8 就用这个
* [ ] DNS Forwarding 很多时候选择通过代理用DNS
* Plugin configuration (if applicable): kcptun 插件，这个很好用。
* [ ] Auto Connect 是的
* [ ] TCP Fast Open 是的
* [ ] NAT mode 不是

### What did you do?
　　对于一直存在的 DNS 问题。我想提建议改进一下。这个 DNS 流程目前难以接受。

### What did you expect to see?
　　希望下面提出来的改进可以尽快上线。这样就可以一劳永逸。

### What did you see instead?
　　我看到 windows 桌面应用的绝佳搭配方法。

平时使用最方便的就是：
1. 　我在 windows 桌面使用 unbound 和 dnscrypt-proxy 结合的方式来进行 DNS 解析。配置是根据需要修改了默认的执行方式。
　　项目1 地址 
　　https://github.com/CNMan/unbound.conf

2. 　代理使用 Shadowsocks , kcptun 和 kcptun_gclient 结合的解决方式。
　　项目2 地址 
　　https://github.com/shadowsocks/shadowsocks-windows/releases
　　https://github.com/xtaci/kcptun/releases
　　https://github.com/dfdragon/kcptun_gclient

关于 DNS 流程的重新设计（主要是向外翻的情况）：

1. 　有软件当前缓存使用缓存查询 IP 地址。查询对应列表的域名，按照步骤 2，3 和 4 选择通道。

2. 　软件自带 hosts 优先
　　（可自己修改，后添加的文件用这些文件名字 hosts1,hosts2 等，多 hosts 文件依次查询）
　　（用户可以自定义的 “hosts direct” 与 “hosts proxy” 等）
　　出现 hosts direct 文件中的（ IP与域名 ）选择（直接连接）连接 IP 地址。（用户可以自定义）
　　出现 hosts proxy 文件中的（ IP与域名 ）选择（通过代理）连接 IP 地址。（用户可以自定义）
　　出现 hosts gfwlist 文件中的（ IP与域名 ）选择（通过代理）连接 IP 地址。
　　出现 hosts1 等其他名字，省略解析 IP 地址，按照步骤 3 选择是否通过代理通道。

3. 　软件自带 domains list 
　　list 文件中的只有域名，没有对应IP，支持泛域名匹配。
　　（用户可自定义的 “domains list china” 与 “domains list proxy” 等）

3.1---------------------------------------------
　　出现 domains list china 文件中的（域名）直接解析国内多地址（DNS 国内解析直接连接） ， （IP 使用直接连接）。
　　（配置三个选框，联通、电信、移动，我手机上双卡切换网络，开关wifi，在配置中就把国内解析选框改到相应的选框名字下就可以了。如果每次换网络去修改 DNS 列表还是太麻烦了）

　　国内域名列表在项目 1 中可以提取。
　　https://raw.githubusercontent.com/CNMan/unbound.conf/master/unbound/unbound.forward-zone.China.conf
　　看内容也是使用了另一个项目的连接：
　　https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf

3.2---------------------------------------------
　　 出现在 domains list proxy 中的域名，使用国际 DNS 地址解析。
　　（DNS可选通过代理或者不通过代理）
　　IP 连接通过代理。

3.3---------------------------------------------
 　　出现在 domains list gfwlist 中的域名，使用国际 DNS 地址解析。
　　（DNS可选通过代理或者不通过代理）
　　IP 连接通过代理。

4. 　以上所有列表中未出现的域名，就解析到 国际 DNS 地址。
　　（DNS可选通过代理或者不通过代理）
　　IP 连接按照路由选择，国内 IP 走直连，国外 IP 走代理。

这样就可以一劳永逸的解决所有麻烦。有问题自己或者大家都来修改一下列表就好了。

**Comment by madeye** [comment]
Make sure DNS forwarding is not enabled if you want geo-IP based DNS resolving.

For the details how shadowsocks handles DNS, please refer to this project: https://github.com/shawn1m/overture

**Comment by a8l1vy** [comment]
国内的域名直接解析，直接连接。
国外的域名代理解析，代理连接。
自定义的域名，按照想要的方法解析。
我想要谷歌地图的卫星图和道路图重合，必须让 clients4.google.com 直连，dns解析的域名一般连不上。只能使用 Hosts 的对应可以连接的 IP 直接连接。
https://github.com/GhostFlying/LocationReportEnabler/issues/32

**Comment by madeye** [comment]
Modify this file https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/assets/overture/hosts to define your hosts.

If you have rooted your device, you can modify /data/data/com.github.shadowaocks/files/hosts as well.

**Comment by a8l1vy** [comment]
明白了，只能在 root 的机子上改了。非常感谢耐心解答。谢谢。

**Comment by Mygod** [comment]
You can modify that file and compile a new apk if you don't have root.

**Comment by Platway** [comment]
From Version 4.7.1 onward, the file "hosts" does not exists any longer. Is there any way to achieve the same goal?

> Modify this file https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/assets/overture/hosts to define your hosts.
> 
> If you have rooted your device, you can modify /data/data/com.github.shadowaocks/files/hosts as well.

**Comment by Mygod** [comment]
Contributions are welcome.
