### ISSUE TITLE
Is there any way to detect shadowsocks running?

### ISSUE THREAD

**Issue by kyze8439690** [shadowsocks/shadowsocks-android#1261]
I am a developer of another app. I found that shadowsocks will cause my app not to work properly(because all application's udp packet will be dropped).
Is there any way to detect shadowsocks is running? I can prompt user to close shadowsocks if they really want to do so.

**Comment by Mygod** [comment]
In the new version, UDP packets are forwarded by default. (actually there's
no way to turn it off)

**Comment by kyze8439690** [comment]
My application is a VpnService application，so I think I can turn it off :)
