### ISSUE TITLE
Failed  to clone pcre

### ISSUE THREAD

**Issue by lvzhengxu1987** [shadowsocks/shadowsocks-android#1265]
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Timed out

### Environment

Ubuntu

### What did you do?
git submodule update --init --recursive

### What did you see instead?

when clone pcre,always has failed!

**Comment by madeye** [comment]
Make sure you can access https://android.googlesource.com/platform/external/pcre/ in your console.

**Comment by openproject** [comment]
config the git proxy:

git config --global https.proxy http://127.0.0.1:1080
git config --global https.proxy https://127.0.0.1:1080

unset them after you done:

git config --global --unset http.proxy
git config --global --unset https.proxy

NOTICE: 1080 is ss windows default local proxy port but mac 1087 ...
