### ISSUE TITLE
play store无法下载

### ISSUE THREAD

**Issue by bankshb** [shadowsocks/shadowsocks-android#1266]
绕过局域网及中国大陆地址的时候可以下载，但浏览很多国内网站依然会走代理；
仅代理中国大陆无法访问地址的时候，play store只能浏览不能下载

**Comment by lionchen336** [comment]
这个选项我理解是将服务端部署在大陆境内，用于访问那些不允许境外直接访问的地址的吧？

**Comment by coolypf** [comment]
去系统的下载管理器里把加速选项关掉。

**Comment by netroby** [comment]
Another solution: using shadowsocks-libev, and enable udp relay dns . Then you may download app from play store
