### ISSUE TITLE
Please  Can you answer a question for me? Please 

### ISSUE THREAD

**Issue by leejing2012** [shadowsocks/shadowsocks-android#1267]
Author，your  ss-android is very good, I'm a Android developers, I want to use Android language to Instead of scala ,   So I want to ask you :Is my idea feasible? please.  Can you solve this question please.

**Comment by madeye** [comment]
You can use any programming language you like to develop this Android application.

**Comment by pexcn** [comment]
This project use vim + scala plugin to develop it?
