### ISSUE TITLE
Can you write a tutorial on how to use it?

### ISSUE THREAD

**Issue by endolith** [shadowsocks/shadowsocks-android#1268]
### Environment

* Android 4.4.4 (client), Ubuntu 16.04 (server)
* Samsung Galaxy S Relay
* App is 4.1.7.  Server is 3.0.0

I've tried following instructions like https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File but the connection does not work.  

Shadowsocks app always says "Connected" when I push the button, even when the server is not running!  o_O

It says "Connected, tap to check connection", but clicking it says "Testing..." and then "Internet Unavailable", and when I run the server in foreground mode on the Linux machine, it does not show any connection or activity.

Can you write a tutorial of how to set up a server and the Android client so that they can talk to each other? We just need a configuration that works, and then we can modify it to suit our needs once we get _something_ working.

**Comment by madeye** [comment]
Please follow the issue template and post your detailed configuration here.

**Comment by endolith** [comment]
Well this isn't really a bug report; it's a request for a simple tutorial of a working configuration.  But here's what I tried:

### Configuration

#### Server:

Installed using 

    sudo apt install python-m2crypto
    sudo pip install git+https://github.com/shadowsocks/shadowsocks.git@master

Created configuration file using

     sudo nano /etc/shadowsocks.json

Contents of file are:

```
{
    "server":"computers_hostname",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"secret_password",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}
```

Added a port forward in home router for both TCP and UDP from 8388 external to server's IP address and 8388 internal port.

Started server from user account:

```
~> ssserver -v -c /etc/shadowsocks.json
INFO: loading config from /etc/shadowsocks.json
2017-05-28 10:03:35 INFO     loading libcrypto from libcrypto.so.1.0.0
2017-05-28 10:03:35 INFO     starting server at shuttle:8388
2017-05-28 10:03:35 DEBUG    using event model: epoll
```


#### Client:

Installed Shadowsocks from [Google Play store](https://play.google.com/store/apps/details?id=com.github.shadowsocks&hl=en)

Created a new profile

- Server: mycomputer.dyndns.net
- Remote port: 8388
- Local port: 1080
- Password: secret_password
- Encrypt method: AES-256-CFB
- Route: All
- Remote DNS: 8.8.8.8
- IPv6 Route: Off
- Per-App Proxy: Off
- DNS Forwarding: Off
- Plugin: Disabled

Then if I enable the profile, it says:

- Connecting...
- Connected, tap to check connection

If I tap, it says:

- Testing...
- Internet Unavailable

But it says "Connected" even if the server isn't running, so it's obviously not actually connecting to anything.  The server doesn't show any activity, it just stays at:

    2017-05-28 10:03:35 DEBUG    using event model: epoll

**Comment by madeye** [comment]
Since your server is behind a NAT device, you should change your server config to:

```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"secret_password",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}
```

**Comment by endolith** [comment]
Oh, that's a listening address.  It works now!  So I guess this can be the tutorial

**Comment by endolith** [comment]
Does the port forward need to be UDP, TCP or both?

**Comment by madeye** [comment]
@endolith It depends. Unless you'd like to forward UDP traffic like DNS queries, you may just forward TCP.
