### ISSUE TITLE
Better solution for QR Code scanning

### ISSUE THREAD

**Issue by pjrobertson** [shadowsocks/shadowsocks-android#1273]
### Environment

* Android version: 6.0 MRA58K
* Device: Xiaomi Redmi Note 4
* Shadowsocks version: 4.1.7
* Last version that did not exhibit the issue (if applicable): 3.4.1

### What did you do?

Tried to scan a Shadowsocks QR code

### What did you expect to see?

Built-in scanner scanning the QR code

### What did you see instead?

Error message saying I must install an external QR code scanner.

I understand the point that you want to keep the app lightweight and reduce the maintenance for the developers, and the limitations of the built in scanner, but removing it entirely is a real fallback.
For people who cannot access Google Play, but have managed to install Shadowsocks, it makes it very difficult for them to add a server via QR Code.

I suggest the following be done:

1. Re-instate the QR code scanner removed in d78e823ce2013bffc29079a0465a88f74de42ece
2. In the code, check for an external QR code scanner. If it exists, use it.
3. If no external QR code scanner exists, drop back to the built in one.

**Comment by madeye** [comment]
@Mygod What do you think?

**Comment by Mygod** [comment]
I'm OK with it.

**Comment by pjrobertson** [comment]
Wow you guys are quick! Thanks for adding this back in, and for all your hard work on SS (both here and `-libev`)
