### ISSUE TITLE
Bug report about resetting the client

### ISSUE THREAD

**Issue by 476210180** [shadowsocks/shadowsocks-android#1275]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 5.1.1 CyanogenMod 12.1
* Device: ZTE U9180
* Shadowsocks version: 4.1.7 from github release page
* Last version that did not exhibit the issue (if applicable): 3.3.0 (upgraded to 4.1.7 from that version)

### Configuration
N/A

### What did you do?
Click "Reset" while not connected to any server.

### What did you expect to see?
Just reset all connections. (If the client closed unexpectedly.)

### What did you see instead?
The connection status bar below kept showing "Shutting down..." and not able to start a new connection, the "paper plane"(connect) button is un-clickable.

**Comment by madeye** [comment]
I cannot reproduce it locally. Try uninstall and reinstall the package.

**Comment by 476210180** [comment]
This only occur when NAT mode is enabled.

2017年6月15日 17:23，"Max Lv" <notifications@github.com>写道：

**Comment by madeye** [comment]
NAT mode is already deprecated. Try VPN mode instead.
