### ISSUE TITLE
建议在自定义规则里面加入'基于某项规则'

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-android#1276]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.1.2", more detailed description is preferred*
* Device: Nexus 6p
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ x] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes 256 gcm
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you expect to see?
在自定义规则里面，建议加入继续'某项规则'，例如基于GFW List，然后在这上面再添加自定义。现在的自定义是直接导入了GFW List吧，这样的话要是GFW List更新了，但是导入的规则很难对比出修改了什么，这样就不太好了

**Comment by simonsmh** [comment]
感觉纯粹基于某规则也并不是完全适合。
1. 选择基础模式
让用户选择[proxy_all]或者[bypass_all]，以适应不同需求
2. 调整[bypass_list]
这里可以加入lan，China ip这种预留类型，用户自行修改
3. 调整[proxy_list]
这里可以加入gfwlist，China ip这种预留类型，用户自行修改
4. custom acl backup
导出到本地或者导出到Google drive

现有acl导入只能bypass，功能实在太弱了。

**Comment by madeye** [comment]
The best way to propose new features is opening a pull request.

**Comment by Sherlock-Holo** [comment]
看起来在咱的建议上添加可以基于现有所有规则就可以满足汝的要求了，而想调整gfwlist的人就直接导入就好了，想使用最新gfwlist的同时又想添加自己规则的就使用'基于gfwlist'这样就好了

Simon Shi <notifications@github.com>于2017年6月6日周二 10:41写道：

**Comment by 521xueweihan** [comment]
@Sherlock-Holo Android 客户端是否可以加上对**云平台**搭建的 shadowsocks 支持？

**Comment by madeye** [comment]
Implemented in 4.2.0. Will be released soon.

**Comment by simonsmh** [comment]
I tried this one.
https://github.com/shadowsocks/shadowsocks-libev/raw/master/acl/chn.acl
But there is no response after I clicked the button. Nothing is on my screen.
Although I known the acl has been imported by finding files in data partition under the help of superuser, I am still confused with it for its "different but looks same" …

**Comment by triaqu** [comment]
试了下，直接把https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl 链接地址放到规则里就行了。
好用。

**Comment by huaxianyan** [comment]
acl规则怎么使用？在自定义规则那里直接添加然后写acl地址吗？

**Comment by simonsmh** [comment]
对的 自定义规则-手动设置-URL/blahblah

huaxianyan <notifications@github.com>于2017年8月7日周一 23:08写道：

**Comment by huaxianyan** [comment]
@simonsmh 添加完就是本身的URL吗？我以为会把里面的内容读取出来写进规则

**Comment by windscolorme** [comment]
It seems that the part of '[outbound_block_list]' doesn't work.
I create a simple ACL file as below to test.
-------------------------
[proxy_all]
[outbound_block_list]
(^|\.)cnzz\.com$
-------------------------
And after add this url to the custom rules,I can still visit *.cnzz.com,such as s92.cnzz.com.
And I found this in src/main/jni/shadowsocks-libev/src/acl.c
---------------------------
       case index => if (!in_urls) line else ""
    }).trim match {
      case "[outbound_block_list]" =>
        hostnames = null
        subnets = null
---------------------------------
So I want to find out that if there are something syntax errors in the acl file with the part of '[outbound_block_list]'.
Thank you!
