### ISSUE TITLE
Unable to connect to Internet through shadowsocks on Lineage OS 14.1

### ISSUE THREAD

**Issue by entalent** [shadowsocks/shadowsocks-android#1277]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Lineage OS 14.1, Android 7.1.2
* Device: MI 5
* Shadowsocks version: 4.1.8, 4.1.3
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

* [ x ] IPv4 server address
* [ ] IPv6 server address
* [ x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ x ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Added a server configuration file, and click connect button, Then clicked the bottom bar to test connection

### What did you expect to see?
Client shows connected and test success

### What did you see instead?
Client shows connected, but test fails(no address associated with hostname)
The same version of shadowsocks client and configuration works fine on MIUI 8, but fails on Lineage OS 14.1. Both v4.1.3 and v4.1.8 behaves exactly the same.

**Comment by madeye** [comment]
1. Try the latest APK.
2. Follow the template to provide all the information.

**Comment by JKSec** [comment]
Same issue. (Mi MIX w/ LineageOS 14.1)
