### ISSUE TITLE
4.0.4以后的版本国内网站打开很慢

### ISSUE THREAD

**Issue by joh2254717** [shadowsocks/shadowsocks-android#1281]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.1.1*
* Device: *Oneplus 3*
* Shadowsocks version: *version code > "v4.0.4"*
* Last version that did not exhibit the issue (if applicable): *4.0.4*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
vpn模式下，浏览网页。

### What did you expect to see?
正常速度打开。

### What did you see instead?
国内网站速度很慢，等很久之后才会慢慢加载。
而4.0.4版本不存在这个问题。
现在一直在用4.0.4版本。

是我不会用么？求解答

**Comment by madeye** [comment]
Try uninstall and reinstall the app.

**Comment by joh2254717** [comment]
试过，没有效果

**Comment by madeye** [comment]
Enable DNS forwarding and try again.

**Comment by madeye** [comment]
BTW, which ISP are you with?

**Comment by joh2254717** [comment]
WiFi  电信
4G     联通/电信

**Comment by madeye** [comment]
I cannot reproduce your issue locally with same device, system and ISP.

You may install the latest 4.1.8, record a screencast, and post the video here.

**Comment by joh2254717** [comment]
[https://youtu.be/xxub3cbkOug](url)
![screenshot_20170617-134538](https://user-images.githubusercontent.com/23419458/27250485-d3f5d1a6-5363-11e7-9ac9-e02fa2b29be3.png)

**Comment by madeye** [comment]
1. What happens if you enable DNS forwarding?
2. Have you enabled the data saver of Chrome browser?

**Comment by madeye** [comment]
Please also try:

1. ping 199.29.29.29 from your shell with this https://play.google.com/store/apps/details?id=jackpal.androidterm
2. ping 114.114.114.114 from the same shell.

It looks to me that your phone cannot visit 199.29.29.29/114.114.114.114 directly. Then overture waited for 6 seconds (our current setting) and falled back to remote DNS. That's why you saw about 6 seconds before the page title appears.

To verify this, please try:

1. Visit ip.cn. Is the IP address your local address or shadowsocks' address.
2. Visit www.baidu.com and search "ip". Is the IP address your local address or shadowsocks' address.

**Comment by joh2254717** [comment]
开启转发，会打不开网页，如图。


![screenshot_20170617-145059](https://user-images.githubusercontent.com/23419458/27250885-d6cd275e-536c-11e7-8995-845f06d646a0.png)

![screenshot_20170617-144603](https://user-images.githubusercontent.com/23419458/27250884-d2566b5e-536c-11e7-9798-91d1fb05fc2c.png)

但是服务端有收到数据，
![55555](https://user-images.githubusercontent.com/23419458/27250890-eaf74ec6-536c-11e7-89ed-97b9a216bf71.jpg)

**Comment by madeye** [comment]
It makes sense now. Your firewall seems to have dropped all income UDP packets, including those from DNS server and shadowsocks server.

**Comment by madeye** [comment]
I built a "special" version for you. Could you try it again? 

https://www.dropbox.com/s/vg54vgoadfmhkje/shadowsocks-local-dns-4.1.8.apk

**Comment by joh2254717** [comment]
不连接ss，ping都正常。ip.cn和百度搜ip都是本地电信的ip，正常。
连接ss，不开启dns转发，能ping通114.114.114.114，其他ping不通。ip.cn显示本地电信ip，百度搜显示ss服务器地址。
连接ss，开启dns转发，能ping通114.114.114.114（114有黑魔法？），其他ping不通。网页打不开。

**Comment by joh2254717** [comment]
是我服务器的防火墙还是本地的路由器拒绝了dns数据包呢？
好的，我试试。

**Comment by joh2254717** [comment]
非常感谢，这个特别版本，很好用。不开启udp转发，连接ss后，打开国内网站速度也比之前快很多。

刚更新新了一加氧os 4.1.6，连接ss，信号就叹号，不连ss就没叹号，视频里面不知道您注意到没。
