### ISSUE TITLE
DNS over TCP not working

### ISSUE THREAD

**Issue by wilsonwen** [shadowsocks/shadowsocks-android#1284]
### Environment

* Android version: 7.0
* Device: Huawei P9
* Shadowsocks version: 4.1.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:RC4-MD5
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Dns tcp resolver is not OK. 
I try to use linux command to test tcp dns server.
`dig +tcp @114.114.114.114  google.com`
It shows "connection timeout". 

But dns over udp is ok.
`dig @114.114.114.114 google.com` will show the resolved result.

It seems like it's the problem of my network but I cannot figure it out.
Any advice would be appreciate!

### What did you expect to see?
None

### What did you see instead?
None

**Comment by madeye** [comment]
I don't think there is anything to do with shadowsocks-android.
