### ISSUE TITLE
三星note4 N9100, 无法开机自启动。

### ISSUE THREAD

**Issue by 6656i** [shadowsocks/shadowsocks-android#1286]
问题描述：在影梭中设置“随系统启动”，并在三星“智能管理器”中，授予“自动启动”权限，以及其他全部权限之后，影梭仍不能开机启动。系统后台进程中也无“影梭”进程。 影梭重置服务之后，仍无效。

系统版本：NOTE4官方 6.0.1

影梭版本：4.1.8，    SSR  3.4.0.5也是无法开机启动。

补充：在另外一台联想手机中，系统版本也是6.0.1，却没有这个问题。猜测可能跟三星ROM有关。

**Comment by madeye** [comment]
I don't think it's related to shadowsocks itself.

Double check your system's settings. Or report this issue to Samsung.

**Comment by 6656i** [comment]
因为手机属于旧款机型，三星已放弃系统维护，所以是没有办法找三星修复了。
如果可能，希望测试一下三星其他6.0的机型是否有此问题。
如果能复现问题，希望修复该问题或者提供指导设置方案。
复现不了，那也就算了。

**Comment by kimw** [comment]
Samsung S6 & S6 edge with Android 6.0.1 works fine.

**Comment by CooperLuo** [comment]
Check the system setting where "start at boot" is. You definitely didn't give access. I don't really know your phone is rooted or not. If so, I think your phone is controlled by some kind of root management software or doesn't give the right access. 

Best,

Cooper

**Comment by 6656i** [comment]
官方 6.0.1， 未root。应该是三星权限管理的bug。
