### ISSUE TITLE
Cannot use Miracast when Pre-App Proxy Bypass Mode is enabled

### ISSUE THREAD

**Issue by kenvix** [shadowsocks/shadowsocks-android#1288]
I guess that ignore "Android System"(android) and "System UI"(com.android.systemui) can solve this problem,but I can't find these app in Pre-App Proxy option

### Environment

* Android version: 7.1.2; Resurrection Remix Nougat 7.1.2_r17
* Device: oneplus3
* Shadowsocks version: v4.1.8 (google play)

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-256-CFB
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
1. Enable Pre-App Proxy
2. Enable Bypass Mode
3. Open "Cast"
4. Find my computer and connect it.

### What did you expect to see?
Do what miracast should do.
(When bypass mode is disabled, miracast works well)

### What did you see instead?
ANDROID: "Connected" -- a few seconds later -- "Cannot Connect"
WINDOWS: Noticed the android device but keep waiting the device

**Comment by Mygod** [comment]
Try bypassing settings app.

**Comment by kenvix** [comment]
bypassing settings app makes no effect

**Comment by madeye** [comment]
Change the route to 'bypass Lan and China'.

**Comment by madeye** [comment]
No response from the requester. Closed due to inactivity.
