### ISSUE TITLE
Application auto shutdown issue in HTC D10w

### ISSUE THREAD

**Issue by tamashii** [shadowsocks/shadowsocks-android#1293]
### Environment

* Android version: 6.0
* Device: HTC Desire 10 Pro (HTC D10w)
* Shadowsocks version: 398db4f
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?

Lock the screen and unlock the screen

### What did you expect to see?

VPN connection should still connecting and the application progress should still running.

### What did you see instead?

Application progress exited, and the VPN connection disconnected.

Maybe this is a issue of HTC operating system ? idk. just post an issue here.

**Comment by madeye** [comment]
You need to allow shadowsocks running in background.

http://www.htc.com/us/support/htc-bolt/howto/managing-apps-running-in-the-background.html

**Comment by tamashii** [comment]
Unfortunately, there have no such thing like that. Perhaps this article is too old for HTC new type phones.
I will literally contact HTC after service personal for answer, hope that will helpful.

**Comment by tamashii** [comment]
Okay,I solved this problem by my self. For anyone got this trouble like me, here is the solution:

1. Tap `HTC Secure Helper`()

**Comment by tamashii** [comment]
Niiiiiice user experience of GitHub web for mobile

I'll post that again.
1. Tap `HTC Secure Helper`(IDK what it exactly called in English version, but for Chinese version, it called *HTC 安全助手*).
2. Tap `Power optimization`(again, *省电优化* for Chinese)
3. Tap `Cloud power saving`(again, *云端省电* for Chinese)
4. Tap `Check power saving settings`(again, *查看省电配置* for Chinese), tap `shadow socks`

**Comment by tamashii** [comment]
No. I will not type that again. You win, github. You win.
Congratulations and gg.
