### ISSUE TITLE
Android版无法勾选“信任此应用”

### ISSUE THREAD

**Issue by codingbubble** [shadowsocks/shadowsocks-android#1296]
下载的最新版，没有开任何护眼APP，但是“信任此应用”怎么都勾选不了

**Comment by madeye** [comment]
You have some overlays apps running in the background. Try to uninstall the apps that requires "draw on other app"

**Comment by vickyleu** [comment]
我的大麦盒子用鼠标也这样,用遥控器可以勾选,估计是作者的checkBox点击事件没写

**Comment by madeye** [comment]
No response from the requester.

Closing the bug.

**Comment by codingbubble** [comment]
@madeye I  have no overlays apps running, ,and uninstall didn't work.
I have no idea, my phone is Meizu m2
