### ISSUE TITLE
最新版在Android tv上无法连接,Snackbar弹出后字体模糊,无法定位错误原因

### ISSUE THREAD

**Issue by vickyleu** [shadowsocks/shadowsocks-android#1297]
更新,发现将snackbar侧滑可以显示出来错误原因,command '96 inferface fwmark rule add tun0' failed with '400 96 Failed fwmark rule

**Comment by madeye** [comment]
> command '96 inferface fwmark rule add tun0' failed with '400 96 Failed fwmark rule

It means your Android TV doesn't support adding VPN interface.
