### ISSUE TITLE
shadowsocks被屏蔽了？

### ISSUE THREAD

**Issue by IceAmber** [shadowsocks/shadowsocks-android#1298]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Android 6.0，安装Shadowsocks后，配置完成，链接成功，但是不能翻墙，前几天都还能用，现在却不行了（不是服务器的问题，PC端用是正常的）

**Comment by Daniel-scx** [comment]
既然PC正常說明你網路沒問題
你手機使用的是PC的WIFI還是移動 電信？

**Comment by IceAmber** [comment]
解决了，手机上设置有点问题，后面改好了，不是app的问题

**Comment by YinboWu** [comment]
能告诉我发生了什么？我也出现了一样的问题。
能提供下设置方法吗？ 
0.0

**Comment by IceAmber** [comment]
我是通过直接扫描PC端上ss的二维码来解决的
