### ISSUE TITLE
Cannot add system VPN connection on Android 7

### ISSUE THREAD

**Issue by myhnet** [shadowsocks/shadowsocks-android#1304]
Cannot add system VPN connection on Android 7, and cannot establish any Shadowsocks connection.

### Environment

* Android version: 7.0
* Device:  Samsung s8
* Shadowsocks version: 4.1.8
* Last version that did not exhibit the issue (if applicable):4.1.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 10808
* Encrypt method:AES-256-CFB
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [x ] TCP Fast Open
* [ ] NAT mode

### What did you do?
I deleted the system VPN connection "Shadowsocks", and I MIGHT changed some system security settings.

### What did you expect to see?
Just accident, I didn't mean to see anything

### What did you see instead?
Shadowsocks cannot add the system VPN connection back any more and all the Shadowsocks connections cannot be established.

**Comment by myhnet** [comment]
I also tried deleting that system VPN on my Nexus 5 with Android 6.0.1,  it will pop-up a connection request dialog which I don't see from Android 7

**Comment by madeye** [comment]
Try reboot your phone.

**Comment by myhnet** [comment]
it works after a reboot!~~ thank you very much.
my phone has been online for more than 900 hours...

**Comment by madeye** [comment]
It's a know bug of Android 6.0.
