### ISSUE TITLE
能否将不需要翻墙的域名采用国内默认的DNS查询，需要翻墙的采用国外DNS

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-android#1305]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
6.0.1
* Device: *e.g. Google Pixel XL*
三星
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
V4.1.8
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [* ] IPv4 server address

* [* ] Client IPv4 availability

* Local port: 1080
* Encrypt method:

* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [* ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
ping www.alibaba.com

### What did you expect to see?
显示国内的IP地址

### What did you see instead?
显示国外的地址

设置了绕过局域网及中国大陆地址，或者设置仅代理中国访问不了的地址。但是在手机上ping 一些如www.alibaba.com 或www.qq.com，显示的是国外的IP。我觉得是DNS查询了国外DNS的缘故。那么岂不是应用要绕很远，导致应用缓慢？能否设置除了封锁的域名，其他的域名查询均采用默认的DNS？

**Comment by madeye** [comment]
1. Make sure DNS forwarding is not enabled.
2. Post the result of `ping www.alibaba.com` here.

**Comment by tianlichunhong** [comment]
sorry, I select forward all DNS by UDP.
