### ISSUE TITLE
I can't install this application on my android device

### ISSUE THREAD

**Issue by Qianai** [shadowsocks/shadowsocks-android#1306]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment
* Android version: 4.2.2
* Device: H8S
* Shadowsocks version: None installed
* I'm in China,there no googleplay,so I can't have correct version for my device.The newest version when I want to install it said can't unpack to install.
So,Could someone tell me what version is available for my device.

**Comment by jiyongjie** [comment]
可能是您的系统安卓版本比较低！

**Comment by Qianai** [comment]
没有解决办法么

**Comment by madeye** [comment]
Try old versions.

**Comment by pexcn** [comment]
升级系统吧。
