### ISSUE TITLE
kcptun plugin config help is incorrect

### ISSUE THREAD

**Issue by FerryOPT** [shadowsocks/shadowsocks-android#1307]
The correct format seems to be:

crypt=none;datashard=10;parityshard=3;mtu=1400;sndwnd=128;rcvwnd=512;dscp=46=;mode=fast2;remoteaddr=xxxx:xxxx

But help message indicates format like this:
--crypt none --datashard 10 --parityshard 3 --mtu 1400 --sndwnd 128 --rcvwnd 512 --dscp 46 --mode fast2

Really misleading .
kcptun plugin version 0.0.5
ss version 4.1.5

**Comment by Mygod** [comment]
Fixed via https://github.com/shadowsocks/kcptun-android/commit/9e43ffc512ccf27266a364063f89b84d1033a016.
