### ISSUE TITLE
QR scanner not work

### ISSUE THREAD

**Issue by kinosang** [shadowsocks/shadowsocks-android#1308]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: Galaxy S6 G9200
* Shadowsocks version: v4.1.8
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: ChaCha20
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [X] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [X] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

1. Use QR scanner to add profile
1. The scanner did nothing

### What did you expect to see?

1. Profile added by the scanner

### What did you see instead?

1. Nothing

**Comment by Mygod** [comment]
Check if the QR code is valid.

**Comment by Great-Li-Xin** [comment]
Valid QR code. QR code scanner never worked.

**Comment by kinosang** [comment]
Both of the QR code generated by ShadowSocksX-NG and generated manually are tested.

Still not work.

**Comment by madeye** [comment]
Post your generated QR code here.

**Comment by madeye** [comment]
BTW, you can generate and test your QR code here: https://shadowsocks.org/en/config/quick-guide.html

**Comment by Great-Li-Xin** [comment]
<img width="402" alt="2017-07-30 7 12 23" src="https://user-images.githubusercontent.com/17794470/28752836-3f8aec6c-755b-11e7-965d-a026b76bbee1.png">

``` javascript
{
    "configs":[
        {
            "remarks":"testService",
            "server":"test.service.com",
            "server_port":"65535",
            "password":"testService",
            "method":"rc4-md5",
            "obfs":"plain",
            "obfsparam":"",
            "remarks_base64":"576O5Zu957q/6LevMw==",
            "group":"",
            "tcp_over_udp":false,
            "udp_over_tcp":false,
            "protocol":"origin",
            "obfs_udp":false,
            "enable":true
        },
    ],
    "index":"0",
    "random":false,
    "global":false,
    "enabled":false,
    "shareOverLan":false,
    "isDefault":false,
    "localPort":"1080",
    "pacUrl":null,
    "useOnlinePac":false,
    "reconnectTimes":"0",
    "randomAlgorithm":"0",
    "TTL":"0",
    "proxyEnable":false,
    "proxyType":"0",
    "proxyHost":null,
    "proxyPort":"0",
    "proxyAuthUser":null,
    "proxyAuthPass":null,
    "authUser":null,
    "authPass":null,
    "autoban":false
}
```

@madeye POSTED, BUG REPRODUCED.
