### ISSUE TITLE
是否可以考虑增加fqrouter2中的无线中继功能

### ISSUE THREAD

**Issue by wsgzao** [shadowsocks/shadowsocks-android#1309]
庖丁解牛 - 整体构成
http://fqrouter.tumblr.com/post/51779503116/%E5%BA%96%E4%B8%81%E8%A7%A3%E7%89%9B-%E6%95%B4%E4%BD%93%E6%9E%84%E6%88%90

**Comment by madeye** [comment]
No plan for this.
