### ISSUE TITLE
二维码扫描无法工作

### ISSUE THREAD

**Issue by Great-Li-Xin** [shadowsocks/shadowsocks-android#1314]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *"4.4.4 KTU84P"*
* Device: *Xiaomi HM1S CDMA*
* Shadowsocks version: *version code "v4.1.8" or commit ID "398db4f"*
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration
* Normal
### What did you do?
* Normal
### What did you expect to see?
* 希望可以成功导入二维码
* 希望可以直接导入配置文件
### What did you see instead?
* 二维码无法扫描，并且扫描框是扁的

**Comment by pexcn** [comment]
广告哪里来的很多了？就 1 个而已

**Comment by pexcn** [comment]
我想这个 issue 可以标记为 cannot reproduce, 并且 close 了。

**Comment by zhanlan123** [comment]
二维码确实扫描有问题

**Comment by Great-Li-Xin** [comment]
首先，我想说的是，我是希望这个项目朝着一个好的方向发展的。很多国产软件的流氓嘴脸大家也是知道的，不是很希望SS-Android变成这个样子。之后的话，二维码扫描的确是不能用的，很多人也证实了这个issue的reproducibility，所以我认为这不是一个个例。记得自从4.0的主版本更新后SS-Android的质量就一直在下降，真的很痛心。希望能有一个正反馈吧。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1308#issuecomment-318520311

**Comment by pexcn** [comment]
@Great-Li-Xin 你用什么文本生成的二维码？举个例子？

**Comment by Great-Li-Xin** [comment]
@pexcn 直接使用ShadowsocksX-NG生成的服务器信息二维码

**Comment by pexcn** [comment]
@Great-Li-Xin 二维码的文本形式是？

**Comment by madeye** [comment]
Please follow https://github.com/shadowsocks/shadowsocks-android/issues/1308#issuecomment-318520311 to post your QR code here.

You can generate a QR code with https://shadowsocks.org/en/config/quick-guide.html

**Comment by Great-Li-Xin** [comment]
<img width="402" alt="2017-07-30 6 38 45" src="https://user-images.githubusercontent.com/17794470/28752609-54089554-7556-11e7-824d-532a7007c9c1.png">

    {
      "enable" : true,
      "password" : "testService",
      "method" : "rc4-md5",
      "remarks" : "testService",
      "server" : "127.0.0.1",
      "kcptun" : {
        "nocomp" : false,
        "key" : "it's a secrect",
        "crypt" : "aes",
        "datashard" : 10,
        "mtu" : 1350,
        "mode" : "fast",
        "parityshard" : 3,
        "arguments" : ""
      },
      "enabled_kcptun" : false,
      "server_port" : 65535,
      "remarks_base64" : "dGVzdFNlcnZpY2U="
    }

我觉得我应该说明一下，这事情根本不是二维码的问题，而是二维码扫描器的问题，请不要怀疑二维码的准确性来甩锅好吗

**Comment by pexcn** [comment]
已测试，无法重视。

**Comment by Great-Li-Xin** [comment]
@pexcn @madeye comment 已更新，可以试着扫描以上二维码，你会发现内置二维码扫描器不工作

**Comment by pexcn** [comment]
你的二维码 decode 出来的格式是：
```
ss://[BASE64]
```
现在应该是用 #27 这种格式。

**Comment by madeye** [comment]
The generated QR code doesn't follow neither old version nor SIP002.

```
rc4-md5:testService@test.service.com:65535?Remark=testService&OTA=false
```

Please ask the maintainer to remove `Remark` and `OTA` args.
