### ISSUE TITLE
Jni crash at libss-local.so when startShadowsocksDaemon

### ISSUE THREAD

**Issue by litch1983** [shadowsocks/shadowsocks-android#1315]
### Environment

Android version:  7.1.1
Device: Alcatel A7 XL
commit ID :  "5633ae7b2164172880fde21918751090bf33eeef"

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] AES-256-CFB
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
I pull code at commit ID :  "5633ae7b2164172880fde21918751090bf33eeef",  compile and install on my device.  

When Route set to All, the connection is fine. 
But when  Route set to GFW List , all the connect to Internet  failed . 

I have add debug information,  and found that crash occurd at  ip-address.c  cork_ipv4_parse when parse "(^|\.)4tern\.com$" at gfwlist.acl

But if I replace libss-local.so with the same file uncompressed from shadowsocks-4.1.6.apk, the connection is fine .

Here attach the log:

3025:07-27 03:51:57.846  6557  6978 D BaseService: connect
3026:07-27 03:51:57.848  6557  6978 D ShadowsocksVpnService: connect
3029:07-27 03:51:57.850  6557  7281 D ShadowsocksVpnService: run,  localSocket.bind
3030:07-27 03:51:57.851  6557  7281 D ShadowsocksVpnService: protect.getAbsolutePath : /data/user/0/com.github.shadowsocks/files/protect_path
3032:07-27 03:51:57.852  6557  7281 D ShadowsocksVpnService: localSocket.bind success
3033:07-27 03:51:57.853  6557  6978 D ShadowsocksVpnService: handleConnection
3034:07-27 03:51:57.854  6557  6978 D ShadowsocksVpnService: startShadowsocksDaemon, buildShadowsocksConfig
3035:07-27 03:51:57.854   329   350 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=55.76 dur=1004.22 max=40.81 min=7.34
3041:07-27 03:51:57.859  6557  6978 D BaseService: buildShadowsocksConfig,  profile.method: aes-256-cfb
3043:07-27 03:51:57.865  6557  6978 D ShadowsocksVpnService: cmd is : ArrayBuffer(/data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so, -V, -u, -b, 127.0.0.1, -l, 1080, -t, 600, -c, ss-local-vpn.conf, --acl, /data/user/0/com.github.shadowsocks/files/gfwlist.acl, --fast-open)
3045:07-27 03:51:57.873  6557  6978 D BaseService: makeDns,  profile.host: 1080
3048:07-27 03:51:57.875  6557  6978 D BaseService: makeDns,  profile.host: 1080
3051:07-27 03:51:57.878  6557  6978 D BaseService: makeDns,  profile.host: 1080
3057:07-27 03:51:57.894  6557  6978 D ShadowsocksVpnService: startVpn 
3080:07-27 03:51:57.908  7283  7283 D shadowsocks: initializing acl...
3081:07-27 03:51:57.908  7283  7283 E shadowsocks: init_acl, path : /data/user/0/com.github.shadowsocks/files/gfwlist.acl
3091:07-27 03:51:57.912  7283  7283 E shadowsocks: line : [bypass_all]
3092:07-27 03:51:57.912  7283  7283 E shadowsocks: [bypass_all] ,  line : [bypass_all]
3093:07-27 03:51:57.912  7283  7283 E shadowsocks: line : [proxy_list]
3094:07-27 03:51:57.913  7283  7283 E shadowsocks: [proxy_list] ,  line : [proxy_list]
3095:07-27 03:51:57.913  7283  7283 E shadowsocks: line : 91.108.4.0/22
3096:07-27 03:51:57.913  7283  7283 E shadowsocks: start parse_addr_cidr
3097:07-27 03:51:57.913  7283  7283 E shadowsocks: finish parse_addr_cidr,  cidr: 22
3100:07-27 03:51:57.913  7283  7283 E shadowsocks: cork_ip_init, err==0
3101:07-27 03:51:57.913  7283  7283 E shadowsocks: ipset_ipv4_add_network complete
3102:07-27 03:51:57.913  7283  7283 E shadowsocks: line : 91.108.56.0/22
3103:07-27 03:51:57.913  7283  7283 E shadowsocks: start parse_addr_cidr
3104:07-27 03:51:57.913  7283  7283 E shadowsocks: finish parse_addr_cidr,  cidr: 22
3105:07-27 03:51:57.914  6557  7284 I GuardedProcess:  0: 9	digit = 9
3106:07-27 03:51:57.914  6557  7284 I GuardedProcess:  1: 1	digit = 91
3107:07-27 03:51:57.914  6557  7284 I GuardedProcess:  2: .	octet 0 = 91
3108:07-27 03:51:57.914  7283  7283 E shadowsocks: cork_ip_init, err==0
3109:07-27 03:51:57.914  7283  7283 E shadowsocks: ipset_ipv4_add_network complete
3110:07-27 03:51:57.914  6557  7284 I GuardedProcess:  3: 1	digit = 1
3111:07-27 03:51:57.914  7283  7283 E shadowsocks: line : 109.239.140.0/24
3112:07-27 03:51:57.914  7283  7283 E shadowsocks: start parse_addr_cidr
3113:07-27 03:51:57.914  7283  7283 E shadowsocks: finish parse_addr_cidr,  cidr: 24
3114:07-27 03:51:57.915  7283  7283 E shadowsocks: cork_ip_init, err==0
3115:07-27 03:51:57.915  7283  7283 E shadowsocks: ipset_ipv4_add_network complete
3116:07-27 03:51:57.915  6557  7284 I GuardedProcess:  4: 0	digit = 10
3118:07-27 03:51:57.915  7283  7283 E shadowsocks: line : 149.154.160.0/20
3120:07-27 03:51:57.915  6557  7284 I GuardedProcess:  5: 8	digit = 108
3121:07-27 03:51:57.916  6557  7284 I GuardedProcess:  6: .	octet 1 = 108
3124:07-27 03:51:57.917  6557  7284 I GuardedProcess:  7: 4	digit = 4
3125:07-27 03:51:57.917  7283  7283 E shadowsocks: start parse_addr_cidr
3126:07-27 03:51:57.917  7283  7283 E shadowsocks: finish parse_addr_cidr,  cidr: 20
3127:07-27 03:51:57.917  6557  7284 I GuardedProcess:  8: .	octet 2 = 4
3128:07-27 03:51:57.917  7283  7283 E shadowsocks: cork_ip_init, err==0
3130:07-27 03:51:57.918  7283  7283 E shadowsocks: ipset_ipv4_add_network complete
3131:07-27 03:51:57.918  7283  7283 E shadowsocks: line : (^|\.)4tern\.com$
3132:07-27 03:51:57.918  7283  7283 E shadowsocks: start parse_addr_cidr
3133:07-27 03:51:57.918  7283  7283 E shadowsocks: finish parse_addr_cidr,  cidr: -1
3134:07-27 03:51:57.918  6557  7284 I GuardedProcess:  9: 0	digit = 0
3136:07-27 03:51:57.918  6557  7284 I GuardedProcess: 10:	octet 3 = 0
3137:07-27 03:51:57.918  6557  7284 I GuardedProcess: 	Parsed address: 91.108.4.0
3139:07-27 03:51:57.919  6557  7284 I GuardedProcess:  0: 9	digit = 9
3141:07-27 03:51:57.919  6557  7284 I GuardedProcess:  1: 1	digit = 91
3142:07-27 03:51:57.919  6557  7284 I GuardedProcess:  2: .	octet 0 = 91
3143:07-27 03:51:57.919  6557  7284 I GuardedProcess:  3: 1	digit = 1
3145:07-27 03:51:57.919  6557  7284 I GuardedProcess:  4: 0	digit = 10
3146:07-27 03:51:57.919  6557  7284 I GuardedProcess:  5: 8	digit = 108
3148:07-27 03:51:57.919  6557  7284 I GuardedProcess:  6: .	octet 1 = 108
3149:07-27 03:51:57.919  6557  7284 I GuardedProcess:  7: 5	digit = 5
3150:07-27 03:51:57.920  6557  7284 I GuardedProcess:  8: 6	digit = 56
3151:07-27 03:51:57.920  6557  7284 I GuardedProcess:  9: .	octet 2 = 56
3153:07-27 03:51:57.920  6557  7284 I GuardedProcess: 10: 0	digit = 0
3155:07-27 03:51:57.920  6557  7284 I GuardedProcess: 11:	octet 3 = 0
3156:07-27 03:51:57.920  6557  7284 I GuardedProcess: 	Parsed address: 91.108.56.0
3157:07-27 03:51:57.920  6557  7284 I GuardedProcess:  0: 1	digit = 1
3158:07-27 03:51:57.920  6557  7284 I GuardedProcess:  1: 0	digit = 10
3160:07-27 03:51:57.921  6557  7284 I GuardedProcess:  2: 9	digit = 109
3162:07-27 03:51:57.921  6557  7284 I GuardedProcess:  3: .	octet 0 = 109
3163:07-27 03:51:57.921  6557  7284 I GuardedProcess:  4: 2	digit = 2
3164:07-27 03:51:57.921  6557  7284 I GuardedProcess:  5: 3	digit = 23
3165:07-27 03:51:57.921  6557  7284 I GuardedProcess:  6: 9	digit = 239
3167:07-27 03:51:57.921  6557  7284 I GuardedProcess:  7: .	octet 1 = 239
3168:07-27 03:51:57.921  6557  7284 I GuardedProcess:  8: 1	digit = 1
3170:07-27 03:51:57.921  6557  7284 I GuardedProcess:  9: 4	digit = 14
3171:07-27 03:51:57.921  6557  7284 I GuardedProcess: 10: 0	digit = 140
3172:07-27 03:51:57.922  6557  7284 I GuardedProcess: 11: .	octet 2 = 140
3173:07-27 03:51:57.922  6557  7284 I GuardedProcess: 12: 0	digit = 0
3175:07-27 03:51:57.922  6557  7284 I GuardedProcess: 13:	octet 3 = 0
3176:07-27 03:51:57.922  6557  7284 I GuardedProcess: 	Parsed address: 109.239.140.0
3178:07-27 03:51:57.922  6557  7284 I GuardedProcess:  0: 1	digit = 1
3179:07-27 03:51:57.922  6557  7284 I GuardedProcess:  1: 4	digit = 14
3180:07-27 03:51:57.922  6557  7284 I GuardedProcess:  2: 9	digit = 149
3182:07-27 03:51:57.922  6557  7284 I GuardedProcess:  3: .	octet 0 = 149
3183:07-27 03:51:57.922  6557  7284 I GuardedProcess:  4: 1	digit = 1
3185:07-27 03:51:57.923  6557  7284 I GuardedProcess:  5: 5	digit = 15
3186:07-27 03:51:57.923  6557  7284 I GuardedProcess:  6: 4	digit = 154
3187:07-27 03:51:57.923  6557  7284 I GuardedProcess:  7: .	octet 1 = 154
3189:07-27 03:51:57.923  6557  7284 I GuardedProcess:  8: 1	digit = 1
3190:07-27 03:51:57.923  6557  7284 I GuardedProcess:  9: 6	digit = 16
3192:07-27 03:51:57.923  6557  7284 I GuardedProcess: 10: 0	digit = 160
3193:07-27 03:51:57.923  6557  7284 I GuardedProcess: 11: .	octet 2 = 160
3194:07-27 03:51:57.923  6557  7284 I GuardedProcess: 12: 0	digit = 0
3195:07-27 03:51:57.923  6557  7284 I GuardedProcess: 13:	octet 3 = 0
3197:07-27 03:51:57.924  6557  7284 I GuardedProcess: 	Parsed address: 149.154.160.0
3200:07-27 03:51:57.924  6557  7284 I GuardedProcess:  0: (	cork_ipv4_parse parse error
3254:07-27 03:51:57.941  7288  7288 I AEE_AED : handle_request(12)
3257:07-27 03:51:57.942  7288  7288 I AEE_AED : check process 7283 name:libss-local.so
3258:07-27 03:51:57.942  7288  7288 I AEE_AED : tid 7283 abort msg address:0x0000000000000000 si_code:1 (request from 7283:10157)
3260:07-27 03:51:57.943  7288  7288 W AEE_AED : debuggerd: handling request: pid=7283 uid=10157 gid=10157 tid=7283
3274:07-27 03:51:57.950  7288  7288 I AEE_AED : [preset_info] pid: 7283, tid: 7283, name: libss-local.so  >>> /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so <<<
3283:07-27 03:51:57.953  7288  7288 D AEE_AED : ptrace_siblings
3314:07-27 03:51:57.965  7288  7288 D AEE_AED : debuggerd: drop privileges
3641:07-27 03:51:58.017  7288  7288 I AEE_AED : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
3643:07-27 03:51:58.018  7288  7288 I AEE_AED : Build fingerprint: 'TCL/7071A/POP5-6_4G:7.1.1/N4F26M/vG2E-0:user/release-keys'
3644:07-27 03:51:58.018  7288  7288 I AEE_AED : Revision: '0'
3646:07-27 03:51:58.018  7288  7288 I AEE_AED : ABI: 'arm64'
3648:07-27 03:51:58.019  7288  7288 I AEE_AED : pid: 7283, tid: 7283, name: libss-local.so  >>> /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so <<<
3649:07-27 03:51:58.019  7288  7288 I AEE_AED : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x6fe7ded278
3652:07-27 03:51:58.019  7288  7288 I AEE_AED :     x0   0000000095dfd3c8  x1   0000006fe7e08904  x2   0000007fee517aa6  x3   ffffffffffffffff
3653:07-27 03:51:58.019  7288  7288 I AEE_AED :     x4   0000000000000058  x5   0000000000000080  x6   0000007fee51731d  x7   0000000000000000
3654:07-27 03:51:58.019  7288  7288 I AEE_AED :     x8   0000000000000000  x9   0000000000000001  x10  0000000000004001  x11  0000000000000000
3656:07-27 03:51:58.020  7288  7288 I AEE_AED :     x12  0000000000001c73  x13  000000000ccccccc  x14  000000008000002f  x15  0000006fe7c37548
3657:07-27 03:51:58.020  7288  7288 I AEE_AED :     x16  0000006fe7c53448  x17  0000006fe7bf9f8c  x18  0000000000000000  x19  0000007fee517aa6
3658:07-27 03:51:58.020  7288  7288 I AEE_AED :     x20  0000007fee517aa6  x21  0000006fe7c557c8  x22  0000006fe7e26b40  x23  0000000000000000
3659:07-27 03:51:58.020  7288  7288 I AEE_AED :     x24  0000000000000000  x25  0000006fe7e087cb  x26  0000007fee517994  x27  0000006fe7e088cc
3661:07-27 03:51:58.020  7288  7288 I AEE_AED :     x28  000000000000000a  x29  0000007fee517a00  x30  0000006fe7ded450
3662:07-27 03:51:58.020  7288  7288 I AEE_AED :     sp   0000007fee5178d0  pc   0000006fe7ded278  pstate 0000000080000000
3688:07-27 03:51:58.031  7288  7288 I AEE_AED : 
3689:07-27 03:51:58.031  7288  7288 I AEE_AED : backtrace:
3691:07-27 03:51:58.032  7288  7288 I AEE_AED :     #00 pc 0000000000022278  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so
3692:07-27 03:51:58.032  7288  7288 I AEE_AED :     #01 pc 000000000002244c  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so
3694:07-27 03:51:58.032  7288  7288 I AEE_AED :     #02 pc 0000000000022cbc  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so
3695:07-27 03:51:58.032  7288  7288 I AEE_AED :     #03 pc 000000000000e1d4  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so
3696:07-27 03:51:58.032  7288  7288 I AEE_AED :     #04 pc 0000000000005f2c  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so (main+532)
3698:07-27 03:51:58.033  7288  7288 I AEE_AED :     #05 pc 000000000001a5d4  /system/lib64/libc.so (__libc_init+88)
3699:07-27 03:51:58.033  7288  7288 I AEE_AED :     #06 pc 0000000000005cfc  /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so
4003:07-27 03:51:58.134  7288  7288 I AEE_AED : request.action: 0
4004:07-27 03:51:58.134  7288  7288 V AEE_AED : dashboard_record_update() : rec->module = /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so 
4005:07-27 03:51:58.135  7288  7288 D AEE_AED : Duplicated exception, cnt = 5 
4007:07-27 03:51:58.135  7288  7288 D AEE_AED : Last exception time: 1501125689 
4008:07-27 03:51:58.135  7288  7288 D AEE_AED : cur time: 1501145518 
4009:07-27 03:51:58.135  7288  7288 D AEE_AED : Skip for Exp level'0'
4026:07-27 03:51:58.141  2750  2750 E evan    : com.github.shadowsocks
4029:07-27 03:51:58.142  6557  6978 D ShadowsocksVpnService: builder.establish
4032:07-27 03:51:58.148  6557  7282 W GuardedProcess: process exit too fast, stop guard: /data/app/com.github.shadowsocks-1/lib/arm64/libss-local.so -V -u -b 127.0.0.1 -l 1080 -t 600 -c ss-local-vpn.conf --acl /data/user/0/com.github.shadowsocks/files/gfwlist.acl --fast-open
4088:07-27 03:51:58.218   861  2089 I Vpn     : Established by com.github.shadowsocks on tun0
4256:07-27 03:51:58.432  2750  2750 E evan    : com.github.shadowsocks
4748:07-27 03:51:58.739  2750  2750 E evan    : com.github.shadowsocks
4930:07-27 03:51:58.862   329  1456 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=50.58 dur=1008.35 max=59.60 min=7.95
5269:07-27 03:51:59.043  2750  2750 E evan    : com.github.shadowsocks
5663:07-27 03:51:59.242  6557  6978 D ShadowsocksVpnService: sendFd,  getFilesDir  is /data/user/0/com.github.shadowsocks/files
5664:07-27 03:51:59.242  6557  6978 E JniHelper: [Shadowsocks], Java_com_tct_vpn_jnihelper_sendfd 
5809:07-27 03:51:59.348  2750  2750 E evan    : com.github.shadowsocks
5858:07-27 03:51:59.372   861   902 V NotificationService: enqueueNotificationInternal: pkg=com.github.shadowsocks id=1 notification=Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0xff607d8b vis=PRIVATE)
5860:07-27 03:51:59.373   861   861 D NotificationService: EnqueueNotificationRunnable.run for: 0|com.github.shadowsocks|1|null|10157
5868:07-27 03:51:59.379   861   861 V NotificationService: pkg=com.github.shadowsocks canInterrupt=false intercept=false
5870:07-27 03:51:59.388   861   902 V NotificationService: enqueueNotificationInternal: pkg=com.github.shadowsocks id=1 notification=Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0xff607d8b vis=PRIVATE)
5872:07-27 03:51:59.392   861   861 D NotificationService: EnqueueNotificationRunnable.run for: 0|com.github.shadowsocks|1|null|10157
5874:07-27 03:51:59.393  1473  1473 D StatusBar: onNotificationPosted: StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10157: Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b vis=PRIVATE))
5875:07-27 03:51:59.393  1473  1473 D PhoneStatusBar: addNotification key=0|com.github.shadowsocks|1|null|10157
5876:07-27 03:51:59.395   861   861 V NotificationService: pkg=com.github.shadowsocks canInterrupt=false intercept=false
6174:07-27 03:51:59.507  1473  1473 D StatusBar: No peeking: unimportant notification: 0|com.github.shadowsocks|1|null|10157
6184:07-27 03:51:59.513  1473  1473 D StatusBar: onNotificationPosted: StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10157: Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b vis=PRIVATE))
6228:07-27 03:51:59.544  1473  1473 D StatusBar: updateNotification(StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10157: Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b vis=PRIVATE)))
6251:07-27 03:51:59.560  1473  1473 D StatusBar: No peeking: unimportant notification: 0|com.github.shadowsocks|1|null|10157
6348:07-27 03:51:59.657  2750  2750 E evan    : com.github.shadowsocks
6395:07-27 03:51:59.874   329   350 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=55.35 dur=1011.75 max=32.59 min=7.40
6396:07-27 03:51:59.949  2750  2750 E evan    : com.github.shadowsocks
6434:07-27 03:52:00.248  2750  2750 E evan    : com.github.shadowsocks
6457:07-27 03:52:00.553  2750  2750 E evan    : com.github.shadowsocks
6483:07-27 03:52:00.882   329   350 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=55.52 dur=1008.67 max=34.05 min=10.98
6487:07-27 03:52:00.904  2750  2750 E evan    : com.github.shadowsocks
6539:07-27 03:52:01.199  2750  2750 E evan    : com.github.shadowsocks
6560:07-27 03:52:01.480  2750  2750 E evan    : com.github.shadowsocks
6568:07-27 03:52:01.759  2750  2750 E evan    : com.github.shadowsocks
6570:07-27 03:52:01.887   329  1824 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=55.72 dur=1005.01 max=29.10 min=7.57
6571:07-27 03:52:02.066  2750  2750 E evan    : com.github.shadowsocks
6572:07-27 03:52:02.392  2750  2750 E evan    : com.github.shadowsocks
6573:07-27 03:52:02.680  2750  2750 E evan    : com.github.shadowsocks
6582:07-27 03:52:02.902   329  1456 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=56.20 dur=1014.28 max=26.76 min=9.27
6583:07-27 03:52:02.983  2750  2750 E evan    : com.github.shadowsocks
6588:07-27 03:52:03.271  2750  2750 E evan    : com.github.shadowsocks
6593:07-27 03:52:03.581  2750  2750 E evan    : com.github.shadowsocks
6619:07-27 03:52:03.872  2750  2750 E evan    : com.github.shadowsocks
6620:07-27 03:52:03.913   329   353 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=56.38 dur=1011.03 max=33.70 min=8.22
6623:07-27 03:52:04.175  2750  2750 E evan    : com.github.shadowsocks
6671:07-27 03:52:04.494  2750  2750 E evan    : com.github.shadowsocks
6679:07-27 03:52:04.811  2750  2750 E evan    : com.github.shadowsocks
6681:07-27 03:52:04.928   329  1456 I BufferQueueProducer: [com.github.shadowsocks/com.github.shadowsocks.MainActivity](this:0x765c415800,id:532,api:1,p:6538,c:329) queueBuffer: fps=55.14 dur=1015.59 max=31.98 min=9.34
6682:07-27 03:52:05.090  2750  2750 E evan    : com.github.shadowsocks
6716:07-27 03:52:05.394  2750  2750 E evan    : com.github.shadowsocks
6717:07-27 03:52:05.691  2750  2750 E evan    : com.github.shadowsocks

**Comment by Mygod** [comment]
Try official APKs and see if you can reproduce the same crash.

**Comment by litch1983** [comment]
This crash can be reproduce on official APKs.

**Comment by litch1983** [comment]
The crash can not be reproduced on official APKs

**Comment by madeye** [comment]
To me, it looks you're using an incorrect toolchain. Make sure your NDK is up to date.

**Comment by pexcn** [comment]
Try other ROMs.

**Comment by litch1983** [comment]
Problem resolved when NDK up to date
Thanks!
