### ISSUE TITLE
QQ/Wechat voice calls is hard to connect.

### ISSUE THREAD

**Issue by andyliu24** [shadowsocks/shadowsocks-android#1318]
### Environment

* Android version: 7.1.1
* Device: OnePlus 3
* Shadowsocks version: v4.1.8
* Last version that did not exhibit the issue (if applicable): none.

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method:chacha20
* [ ] One-time authentication（It's unknown to me.）
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
I accepted voice calls (QQ/Wechat), it lasts to prompt "Connecting..." about 30s to 1m.
If I close shadowsocks, it would be quickly.

![wechat](https://user-images.githubusercontent.com/24978668/28751490-91ea0fda-753b-11e7-8d03-54f4c0b3899f.jpg)
![qq](https://user-images.githubusercontent.com/24978668/28751491-92b07382-753b-11e7-8c76-e2007964c694.jpg)

**Comment by madeye** [comment]
Bypass QQ/Wechat in the per-app proxy setting.

**Comment by andyliu24** [comment]
Thanks, settled.
