### ISSUE TITLE
ver 4.20 开启分应用代理绕行模式时，测试连接失败，但实际好像是连上了。

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#1319]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *ResurrectionRemixOS "7.1.2_r24"*
* Device: *Oneplus 3T*
* Shadowsocks version: *version code "v4.2.0", commit ID "a3f57d2"*
* Last version that did not exhibit the issue (if applicable):4.1.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:AES-128-CFB
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
开启分应用代理绕行模式

### What did you expect to see?
点击测试连接，显示测试成功

### What did you see instead?
无互联网连接，失败: connect timed out. 但是实际上是连上了，因为其它app能连网。

**Comment by madeye** [comment]
1. 4.2.0 is still not released.
2. Make sure shadowsocks itself is not bypassed.
3. I cannot reproduce your issue locally.

**Comment by ageback** [comment]
关闭shadowsocks绕行就没问题了。谢谢。
