### ISSUE TITLE
版本4.2.0更新完成后丢失配置文件

### ISSUE THREAD

**Issue by Han9402** [shadowsocks/shadowsocks-android#1325]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2（lineage 14.1）
* Device: 华为荣耀5X（KIW-UL00）
* Shadowsocks version: v4.2.0
* Last version that did not exhibit the issue (if applicable):上个版本（有参与beta计划并保证app更新）

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
从google play更新版本至4.2.0

### What did you expect to see?
更新完成后，之前配置信息完好无损

### What did you see instead?
更新完成后，配置文件及相关设定全部丢失，但自定义规则完好无损

**Comment by turtleqiu** [comment]
Nexus 6P 运行Android O DP4，升级到4.2.0配置丢失。

**Comment by whour** [comment]
Oneplus 3 Android 7.1.1 升级到4.2.0 服务器配置信息丢失 +1

**Comment by pexcn** [comment]
我也遇到了这样的情况。

**Comment by Love4Taylor** [comment]
而且默认的 profile 中有奇奇怪怪的字符

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by whour** [comment]
@Love4Taylor 
GIF89这里是 Google的ads 图片。

**Comment by madeye** [comment]
@Mygod It looks we've switched to database for preferences. Is it expected that we would lost all the profiles after upgrading?

**Comment by madeye** [comment]
It turns out a bug in data upgrading.

**Comment by madeye** [comment]
Please try 4.2.1. Thanks for the bug report.

**Comment by tweet** [comment]
I updated the version to 4.2.1 just before, all of the configurations lost, can these be recovered later?
