### ISSUE TITLE
分应用代理的应用到所有配置文件无法应用分应用代理开关和绕行模式开关

### ISSUE THREAD

**Issue by wch930** [shadowsocks/shadowsocks-android#1327]
### Environment

* Android version: *7.1.1*
* Device: *htc u11*
* Shadowsocks version: *4.x*

its a general problem

**Comment by simonsmh** [comment]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Oneplus 3
* Shadowsocks version: v4.x
* Last version that did not exhibit the issue (if applicable): none

### Configuration

* [x] Per-App Proxy
  * [x] Bypass mode
*Other not affected*

### What did you do?

0. 应用分应用代理，绕行模式
1. 新建配置
2. 新配置开启分应用代理

### What did you expect to see?

Bypass mode on.

### What did you see instead?

Bypass mode off in new config file.

**Comment by madeye** [comment]
It's expected. Only per-app list would be applied.
