### ISSUE TITLE
当关闭电视屏幕再打开，会引起Sony电视重启

### ISSUE THREAD

**Issue by kuun** [shadowsocks/shadowsocks-android#1328]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android tv 6.0.1
* Device: Sony Tv KD-49X7000D
* Shadowsocks version: "v4.1.8"
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [x] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
在Sony电视Android TV上安装Shadowsocks，开启Shadowsocks进行代理，然后去使用其它App如Youtube。

### What did you expect to see?
能正常使用，不会引起电视重启。

### What did you see instead?
关闭电视屏幕会出现以下问题：
1. 如果把电视屏幕关掉，然后再打开，过几秒，电视会重启。
2. 如果关闭电视屏幕，过几分钟后再尝试使用摇控器打开，电视没有响应，按多次（4~5次）摇控器电源键，依然没有响应，过会再按摇控器，电视开启，发现电视已重启完毕

**Comment by madeye** [comment]
It looks a bug of your Android TV. Please report it to Sony instead.

**Comment by kuun** [comment]
我的电视上安装了各种程序都没这个问题，一开始我觉得可能是youtube的问题，因为电视上没有google play service，所以换其它版本，还是有这个问题；所有就将youtube卸载了，发现还是有这个问题；最后就shadowsocks的代理关掉，系统不会再因关闭屏幕而重启。我还分别测试了是不是跟kcptun插件是否有关，发现该插件是否启用都会导致该问题，应该跟kcptun无关。所以提了这个issue。
目前临时的解决办法是：看youtube时将shadowsocks打开，看完后就将shadowsocks关闭，再去关电视屏幕。
shadowsocks引起该问题的可能性应该非常大。

**Comment by Mygod** [comment]
Your system probably has buggy VPN service support. Try NAT mode and/or other VPN apps.

**Comment by kuun** [comment]
Maybe, i have tried openvpn, the TV also restarted. BTW, the NAT mode needs root privilege, i can try it.

**Comment by cgrk** [comment]
Same here!

There is a post on Sony Community that describes this problem: [BUG: Android 6.0.1 reboots after enabling VPN apps](https://community.sony.ie/t5/android-tv/bug-android-6-0-1-reboots-after-enabling-vpn-apps/td-p/2284371)

In addition, you can contact Sony here: [SONY China Service](http://service.sony.com.cn). I have emailed them to report the problem and I am waiting for their reply.

**Comment by koijan** [comment]
目前的解决办法 我是装了个类似tasker的app 设定关屏自动关shadowsocks 开屏自动打开 如此就可以避免开机重启了

**Comment by ipiger** [comment]
同样有这个问题. 准备换楼上的办法试试看, 用tasker.

**Comment by koijan** [comment]
天朝SonyTV没法登录play store，于是没法用付费tasker，只能试用七天。有法子能用完整版tasker么

> 同样有这个问题. 准备换楼上的办法试试看, 用tasker.

**Comment by sikaote222** [comment]
> 目前的解决办法 我是装了个类似tasker的app 设定关屏自动关shadowsocks 开屏自动打开 如此就可以避免开机重启了

能否请教后续如何呢，可以共享如何 设置tasker么? 谢谢或者类似tasker的app是。。
