### ISSUE TITLE
Android client connection failed

### ISSUE THREAD

**Issue by S3cuRiTy-Er1C** [shadowsocks/shadowsocks-android#1329]
Andrid客户端每当有流量包时日志(Error)打印如下:
`shadowsocks: [android] connect() failed for protect_path: No such file or directory (socket fd = 15)
shadowsocks: protect_socket: No such file or directory`
这条日志来自libss-local.so
请问是什么问题?难道是我libss-local.so启动时的配置问题?还是ShadowsocksVpnThread线程里处理有额外难题
* Note:
Seems libss-local.so can't find /data/data/pkg/files/protect_path file. so what can i do for correcting sun_path?

**Comment by S3cuRiTy-Er1C** [comment]
problem resolved. I forgot set ProcessBuild's working directory when i start libss-local.so

**Comment by hujiana** [comment]
E shadowsocks: [android] connect() failed for stat_path: No such file or directory (socket fd = 7) 我有流量包的时候也会提示出这个问题，请问是什么情况

**Comment by S3cuRiTy-Er1C** [comment]
@hujiana 除了真的找不到这个stat_path文件,还有另一种情况就是这个文件虽然在但是fd被释放了
