### ISSUE TITLE
二维码扫描功能报错无法开启

### ISSUE THREAD

**Issue by coofo** [shadowsocks/shadowsocks-android#1330]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: 华为 荣耀 8
* Shadowsocks version: v4.2.1
* Last version that did not exhibit the issue: v3.0.4之后没更新过

### What did you do?
使用 扫描二维码功能

### What did you expect to see?
此功能正常使用

### What did you see instead?
弹出了一个dialog 
res/anim/abc_fade_in.xml
Sorry,the Android camera encountered a problem

![screenshot_20170805-010656](https://user-images.githubusercontent.com/23547947/28978914-77e0a084-797a-11e7-9b9f-36bee61bb5dd.png)

**Comment by madeye** [comment]
Please install the scanner first: https://play.google.com/store/apps/details?id=com.google.zxing.client.android

**Comment by madeye** [comment]
Closed due to inactivity.
