### ISSUE TITLE
通过acl规则可否实现屏蔽广告

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-android#1335]
新版本支持remote acl规则了，这使得自定义代理方式变得很灵活。
不过貌似目前的acl只是匹配到两种结果中：走/不走代理，
不知道能否实现第三种结果：屏蔽，
这样就可以实现广告屏蔽了，实现成本也不高

**Comment by Sherlock-Holo** [comment]
shadowsocks is a proxy tool not like adblock plus.

Cokebar Chi <notifications@github.com>于2017年8月9日周三 上午10:44写道：

**Comment by cokebar** [comment]
@Sherlock-Holo 不少代理工具，诸如Privoxy，也是支持广告屏蔽的。代理软件的acl就是为了控制流量，很多代理软件也都有屏蔽流量的功能。我只是问一下这种想法可信性如何？如果实现起来比较容易，那么能加上这个功能是最好。

**Comment by madeye** [comment]
No plan for this.

**Comment by liaobin** [comment]
https://github.com/ACL4SSR/ACL4SSR
