### ISSUE TITLE
confused by SIP002 URI Scheme

### ISSUE THREAD

**Issue by icymind** [shadowsocks/shadowsocks-android#1336]
At page [SIP002 URI Scheme](https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html), it says:

> The last / should be appended if plugin or tag is present. 

But at the same page:

> Examples:
    - ss://YWVzLTEyOC1nY206dGVzdA==@192.168.100.1:8888#Example1
    - ss://cmM0LW1kNTpwYXNzd2Q=@192.168.100.1:8888/?plugin=obfs-local%3Bobfs%3Dhttp#Example2

The example1 doesn't contains "/". And the shadowsocks-android acts like example1.

so, should the last /  be appended if plugin or tag is present? Or just be appended if plugin present?

**Comment by madeye** [comment]
Good question.

What do you think? @Mygod

**Comment by Mygod** [comment]
I think / is optional but recommended.

**Comment by madeye** [comment]
Let me refine the description and implementation.

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-org/commit/a682aaa97652464a2e67f99f11b8f56ef081d2fb.
