### ISSUE TITLE
battery draining fast after latest beta update

### ISSUE THREAD

**Issue by liuminzhi** [shadowsocks/shadowsocks-android#1337]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
Android 8.0.0 DP4
* Device: *e.g. Google Pixel XL*
Google Pixel XL
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
version code "v4.2.2“

* Last version that did not exhibit the issue (if applicable):
v4.1.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:RC4-MD5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Per-App Proxy
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you expect to see?
待机两小时不会消耗10+的电量。

### What did you see instead?
刚才观察了下，后台待机2:30min，少了11%的电量。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-does-shadowsocks-consume-so-much-battery-on-android-50
