### ISSUE TITLE
No response when clicking the paper plane

### ISSUE THREAD

**Issue by RZloli** [shadowsocks/shadowsocks-android#1338]
* Android version: 7.0
* Device: LG H860
* Shadowsocks version: v4.18 and v4.22(Lastest)

![screenshot_2017-08-12-00-08-44](https://user-images.githubusercontent.com/19405916/29239604-2fbd062e-7f85-11e7-840d-77b78b065f4c.png)
it doesnt have any response after clicking the paper plane
![screenshot_2017-08-12-17-34-47](https://user-images.githubusercontent.com/19405916/29239606-32aa68c2-7f85-11e7-8bbd-a53802deca2d.png)
it shows this when i press the button and hold it for a second
But still there is no response. how can i solve it

**Comment by madeye** [comment]
1. Try reboot your phone first.
2. What happen if you select the default profile instead?
3. Post the details of your own profile.

**Comment by RZloli** [comment]
1. & 2. Tried and still the same
3. I am using the same profile on my PC and it works

**Comment by dodcore** [comment]
same thing happened to me several months ago.
pixel xl user, latest updated.
ss server profile 101% correct.
but just no response.

**Comment by madeye** [comment]
Have you got any version of shadowsocks working on your phone before?

It looks an issue of VPN support of your Android system.

**Comment by RZloli** [comment]
Haven't succeeded yet

**Comment by madeye** [comment]
Report it to LG, or try some other ROMs.
