### ISSUE TITLE
NAT模式为什么相当缓慢

### ISSUE THREAD

**Issue by Shadowhack0419** [shadowsocks/shadowsocks-android#1339]
NAT模式貌似只有TCP模式，但是服务端只开tcp模式使用VPN模式连依旧有2MB/S速度，但是使用NAT模式只有20KB/S。(XIAOMI MI5，Andirod 7.0) 

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment]
NAT mode is already deprecated (for years).
