### ISSUE TITLE
ToolbarFragment 的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1342]
请问这里的 Fragment 为什么不用 support v4 包里的 Fragment 呢？
https://github.com/shadowsocks/shadowsocks-android/blob/0acfaa1/mobile/src/main/scala/com/github/shadowsocks/ToolbarFragment.scala#L23

**Comment by madeye** [comment]
Since the minimal Android API we support is API 19, I think it'd be OK here.

**Comment by pexcn** [comment]
Thanks.
