### ISSUE TITLE
执行sbt clean go-build android:package-release时报错

### ISSUE THREAD

**Issue by wangfy517** [shadowsocks/shadowsocks-android#1343]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* win7 64bit
* Git-2.14.1-64-bit
* sbt-1.0.0
* scala-2.12.3

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
想编译一下源代码

### What did you expect to see?
能够编译成功

### What did you see instead?
[info] Updated file D:\androidworkspace\shadowsocks-android\project\build.properties: set sbt.version to 1.0.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from D:\androidworkspace\shadowsocks-android\project
[info] Updating {file:/D:/androidworkspace/shadowsocks-android/project/}shadowsocks-android-build...
[warn]  module not found: org.scala-android#sbt-android;1.7.8
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0//1.7.8/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-android/sbt-android/scala_2.12/sbt_1.0//1.7.8/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\org.scala-android\sbt-android\scala_2.12\sbt_1.0\\1.7.8\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-android/sbt-android_2.12_1.0/1.7.8/sbt-android-1.7.8.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\org.scala-android\sbt-android\1.7.8\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/org/scala-android/sbt-android_2.12_1.0/1.7.8/sbt-android-1.7.8.pom
[warn]  module not found: com.timushev.sbt#sbt-updates;0.1.10
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0//0.1.10/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0//0.1.10/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\com.timushev.sbt\sbt-updates\scala_2.12\sbt_1.0\\0.1.10\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\com.timushev.sbt\sbt-updates\0.1.10\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/com/timushev/sbt/sbt-updates_2.12_1.0/0.1.10/sbt-updates-0.1.10.pom
[warn]  module not found: net.virtual-void#sbt-dependency-graph;0.8.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0//0.8.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0//0.8.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\net.virtual-void\sbt-dependency-graph\scala_2.12\sbt_1.0\\0.8.2\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\net.virtual-void\sbt-dependency-graph\0.8.2\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.2/sbt-dependency-graph-0.8.2.pom
[warn]  module not found: org.xerial.sbt#sbt-sonatype;1.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.xerial.sbt/sbt-sonatype/scala_2.12/sbt_1.0//1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.xerial.sbt/sbt-sonatype/scala_2.12/sbt_1.0//1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\org.xerial.sbt\sbt-sonatype\scala_2.12\sbt_1.0\\1.1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/xerial/sbt/sbt-sonatype_2.12_1.0/1.1/sbt-sonatype-1.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\org.xerial.sbt\sbt-sonatype\1.1\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/org/xerial/sbt/sbt-sonatype_2.12_1.0/1.1/sbt-sonatype-1.1.pom
[warn]  module not found: com.jsuereth#sbt-pgp;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0//1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0//1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\com.jsuereth\sbt-pgp\scala_2.12\sbt_1.0\\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.12_1.0/1.0.0/sbt-pgp-1.0.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\com.jsuereth\sbt-pgp\1.0.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/com/jsuereth/sbt-pgp_2.12_1.0/1.0.0/sbt-pgp-1.0.0.pom
[warn]  module not found: org.scala-android#sbt-android-gms;0.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-android/sbt-android-gms/scala_2.12/sbt_1.0//0.4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-android/sbt-android-gms/scala_2.12/sbt_1.0//0.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Administrator\.ivy2\local\org.scala-android\sbt-android-gms\scala_2.12\sbt_1.0\\0.4\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-android/sbt-android-gms_2.12_1.0/0.4/sbt-android-gms-0.4.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\Administrator\.sbt\preloaded\org.scala-android\sbt-android-gms\0.4\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/Administrator/.sbt/preloaded/org/scala-android/sbt-android-gms_2.12_1.0/0.4/sbt-android-gms-0.4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-android#sbt-android;1.7.8: not found
[warn]  :: com.timushev.sbt#sbt-updates;0.1.10: not found
[warn]  :: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn]  :: org.xerial.sbt#sbt-sonatype;1.1: not found
[warn]  :: com.jsuereth#sbt-pgp;1.0.0: not found
[warn]  :: org.scala-android#sbt-android-gms;0.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.xerial.sbt:sbt-sonatype:1.1 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-android:sbt-android-gms:0.4 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-android:sbt-android:1.7.8 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.xerial.sbt:sbt-sonatype:1.1 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L7-8)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L5-6)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-android:sbt-android-gms:0.4 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L11-12)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.timushev.sbt:sbt-updates:0.1.10 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L3-4)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.jsuereth:sbt-pgp:1.0.0 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L9-10)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-android:sbt-android:1.7.8 (scalaVersion=2.12, sbtVersion=1.0) (D:\androidworkspace\shadowsocks-android\project\plugins.sbt#L1-2)
[warn]            +- default:shadowsocks-android-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.8: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[error] unresolved dependency: org.xerial.sbt#sbt-sonatype;1.1: not found
[error] unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
[error] unresolved dependency: org.scala-android#sbt-android-gms;0.4: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:64)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:141)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2313)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-android#sbt-android;1.7.8: not found
[error] unresolved dependency: com.timushev.sbt#sbt-updates;0.1.10: not found
[error] unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[error] unresolved dependency: org.xerial.sbt#sbt-sonatype;1.1: not found
[error] unresolved dependency: com.jsuereth#sbt-pgp;1.0.0: not found
[error] unresolved dependency: org.scala-android#sbt-android-gms;0.4: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by madeye** [comment]
Make sure you have a "good" connection to internet.

**Comment by yxf0448** [comment]
请问这个问题解决了吗？缺少的这几个包，有什么其他的办法引入么？

**Comment by yxf0448** [comment]
https://repo1.maven.org/maven2/org/scala-android/sbt-android_2.12_1.0/1.7.8/sbt-android-1.7.8.pom

**Comment by wangfy517** [comment]
@madeye 
网络是没问题的，这几个依赖包需要配置别的什么地方吗？

**Comment by wangfy517** [comment]
@yxf0448 
还没解决呢，一直报这个错，你是用什么环境编译的？

**Comment by yxf0448** [comment]
我用macos编译的，貌似需要把这几个包的工程下载下载，全都编译成jar包，然后放到这个项目里面吗？
@wangfy517

**Comment by wangfy517** [comment]
@yxf0448 
看到是有这么做的，不过不知道行不行。。

**Comment by huabeiyipilang** [comment]
编不过，求解

**Comment by wangfy517** [comment]
@huabeiyipilang 报什么错？

**Comment by huabeiyipilang** [comment]
@wangfy517 跟你的问题一样~

**Comment by wangfy517** [comment]
@huabeiyipilang 
问题解决了，是sbt版本的问题，你换个版本试试。

**Comment by huabeiyipilang** [comment]
@wangfy517 请问在哪设置环境变量？ 我在.bash_profile里设置了，不起作用

ANDROID_HOME="/Users/xxx/Library/Android/sdk"
GOROOT_BOOTSTRAP="/usr/local/go"

**Comment by wangfy517** [comment]
@huabeiyipilang 
我是修改了shadowsocks-android\project\build.properties里的sbt的版本号，修改为sbt.version=0.13.5

**Comment by madeye** [comment]
Fixed via 390cb522d5903f3124e73b5e67a8eff9553d9c66
