### ISSUE TITLE
分应用代理当开启`bypass mode`时不能使用

### ISSUE THREAD

**Issue by JayceCao** [shadowsocks/shadowsocks-android#1344]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 7.1.2, Lineags OS 14.1-20170808-NIGHTLY-gemini
* Device: MI 5
* Shadowsocks version: v4.2.3 from GithHub Releases
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
* Enable Per-App Proxy
* Enable Bypass Mode 

### What did you see instead?
当开启`Bypass Mode`的时候不能打开Google，当关闭`Bypass Mode`时能打开Google等，但这样的话时全局代理，访问国内网站时非常慢

**Comment by madeye** [comment]
Which apps are selected in bypass mode?

**Comment by JayceCao** [comment]
Chrome

**Comment by JayceCao** [comment]
And these:

On Aug 16, 2017 13:28, "Max Lv" <notifications@github.com> wrote:

Which apps are selected in bypass mode?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/shadowsocks-android/issues/1344#issuecomment-322670020>,
or mute the thread

**Comment by madeye** [comment]
Then, it' s expected.

When you select Chrome in per-app proxy and enable the "bypass mode", Chrome will not be proxied, which means you cannot access Google in Chrome.
