### ISSUE TITLE
必须更新 google play 才给用，非root机器

### ISSUE THREAD

**Issue by yyx007** [shadowsocks/shadowsocks-android#1347]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2 (N2G48C, Aug 2017),
* Device: Google Nexus5x
* Shadowsocks version: *version code "v4.2.3" 
* Last version that did not exhibit the issue (if applicable): 4.17（其余没试验）

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
重装系统安装 v4.2.3 ss

### What did you expect to see?
点击连接没反应，设备截图必须更新google play

### What did you see instead?
安装 4.1.7版本使用，好像依旧要求更新 google play，但是可以连接

**Comment by madeye** [comment]
1. Reboot your phone and try again.
2. Any VPN permission request dialog shows up when clicking the button?

**Comment by yyx007** [comment]
1、已经用老版本更新完google play，无法重现
2、当初 有显示启动vpn什么的，但是软件里面点连接根本没反应
![771358834008664268](https://user-images.githubusercontent.com/4769801/29700353-60704130-8996-11e7-8612-1b997390e457.jpg)

请关闭


’

**Comment by ykla** [comment]
遇到同样的问题，安卓8.0

**Comment by keenlovelife** [comment]
我也是

**Comment by Martinho0330** [comment]
I've come across this issue too, but I know the answer since I'm using the QRCode importer, and the camera QR Code importer need to open up Google Play for a proper QR Code scanner.
