### ISSUE TITLE
China List routing not fully working

### ISSUE THREAD

**Issue by invisiblearts** [shadowsocks/shadowsocks-android#1348]
### Environment

* Android version: *7.1.1*
* Device: *Sony Xperia XZ Premium*
* Shadowsocks version: *4.1.8*

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: *omitted*
* Encrypt method: *omitted*
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [x] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: *tried `8.8.8.8`, `223.5.5.5`, `server's assigned LAN DNS`*
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
visit https://google.com

### What did you expect to see?
😃 

### What did you see instead?
ERR_CONNECTION_CLOSED

### Relevant information
server shadowsocks version: go-shadowsocks2

`dig google.com` on server:
```
; <<>> DiG 9.10.4-P5 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14025
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		184	IN	A	216.58.200.46

;; Query time: 0 msec
;; SERVER: *LAN DNS*#53(*LAN DNS*)
;; WHEN: Sun Aug 20 00:33:34 CST 2017
;; MSG SIZE  rcvd: 55
```
`dig google.com @223.5.5.5` on server: 
```
; <<>> DiG 9.10.4-P5 <<>> google.com @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5468
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		54	IN	A	216.58.200.46

;; Query time: 28 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Sun Aug 20 00:54:17 CST 2017
;; MSG SIZE  rcvd: 44

```
`dig google.com @8.8.8.8` on server:
```
; <<>> DiG 9.10.4-P5 <<>> google.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17118
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		198	IN	A	172.217.27.142

;; Query time: 42 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Aug 20 00:56:03 CST 2017
;; MSG SIZE  rcvd: 55
```

server log:
```
proxy *my public ip (ctc.biz)*:44312 <-> 223.5.5.5:53
failed to connect to target: dial tcp 223.5.5.5:53: getsockopt: connection timed out
```

**Comment by invisiblearts** [comment]
note: it seems that `dig +tcp google.com` is not working on remote server, but `dig +tcp google.com @8.8.8.8` works. After setting remote DNS to 8.8.8.8, the problem still exists.

**Comment by madeye** [comment]
China List means only China IPs are routed. Could you make sure your local network can access `google.com` directly?

**Comment by invisiblearts** [comment]
I am in the US so for sure.

**Comment by Mygod** [comment]
Cannot reproduce on Android 7.1.2, client 4.2.4, Comcast. Please verify if this bug still persists.

**Comment by invisiblearts** [comment]
Tested on 4.2.4. Working fine now (despite a rather low speed).
