### ISSUE TITLE
深夜报 bug

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1349]
![screenshot_20170820-012102](https://user-images.githubusercontent.com/4590439/29488861-0224a5e2-84d9-11e7-98ee-2d6dd3383c6f.png)

这样横屏的时候，打开 drawer, 点击背景图片，程序会crash.

**Comment by Choutouketsu** [comment]
好像是真的哎，横屏以后那个shadowsocks背景不能点，崩溃率100%

**Comment by Choutouketsu** [comment]
@madeye

**Comment by Mygod** [comment]
This seems like upstream bug to me. Reported to mikepenz/MaterialDrawer.
