### ISSUE TITLE
开启ss后，wifi下无法打开WEB登陆页面

### ISSUE THREAD

**Issue by fevenor** [shadowsocks/shadowsocks-android#135]
我连上校园网wifi后，在未开启ss的情况下，用浏览器打开任意页面，都能自动跳转到WEB登陆页面http://web.auto.configed.certificate/aaa/wba_form.html 进行登陆操作。
在开启ss后，无法打开http://web.auto.configed.certificate/aaa/wba_form.html 页面进行登陆。

**Comment by Smallthing** [comment]
有关的。开启SS后，第一下访问不能被劫持到登陆页面。。。。。。希望能做个判断，自己设定 在，特定WIFI下可以允许直通到登录页

**Comment by Mygod** [comment]
Use per-app proxy and route.
