### ISSUE TITLE
Bugs with custom list

### ISSUE THREAD

**Issue by zzj0311** [shadowsocks/shadowsocks-android#1351]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *6.0.1*
* Device: *Nexus 6p*
* Shadowsocks version: *latest gp beta version*

### What did you do?
Tried to use default gfwlist as the basis of the custom rule, however, telegram failed to connect. Then I switch to "gfwlist" and it worked, which confused me since the top four rules are exactly for telegram

**Comment by madeye** [comment]
Which base ACL file are you using?

I cannot reproduce your issue with https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/acl/gfwlist.acl

**Comment by zzj0311** [comment]
i checked the custom_rules.acl file and found the reason. Seems that the inline import gfwlist method returns a wrong file. 
https://www.dropbox.com/s/6ju115yre4abyn1/Screenshot_20170821-151142.png?dl=0

**Comment by zzj0311** [comment]
Seems it's the import method that went wrong. I tried to import part of the gfwlist using "import from clipboard", rules are listed :
[proxy_list]
# manhuaren
mangaapi.manhuaren.com
# Telegram IPs$
91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20
 However , the file still went wrong like this
https://www.dropbox.com/s/ypll6av157ls3sc/Screenshot_20170821-153430.png?dl=0

**Comment by madeye** [comment]
1. Which version are you using? (the exact version number).
2. Could you clean up all the existed rules and import again?

**Comment by zzj0311** [comment]
v 4.3.2
like I said, I deleted the /data/data/com.github.shadowsocks/files/custom-rules.acl and import again, the problem still exists, and because of the permission, I can't edit it by my own....

**Comment by madeye** [comment]
Could you remove `[proxy_list]` from your rules in the clipboard and try again?

**Comment by zzj0311** [comment]
looks the same
result for import following
````
91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20
````
https://www.dropbox.com/s/k03qx6ie696ncbi/Screenshot_20170822-132746.png?dl=0
by the way, is there any log files in Android version so I can check out for any further details?

**Comment by Mygod** [comment]
@madeye Could you explain to me what in the world is going on with all those custom ACL urls now? It seems like we use `proxy_all` in custom rules mode now? Also this `#NETWORK_ACL_BEGIN, #NETWORK_ACL_END` looks extremely weird. Why don't we just use a new section for all the URLs?
