### ISSUE TITLE
路由选择自定义规则，自定义规则使用acl链接，在自行添加代理网址后，变成绕过局域网效果

### ISSUE THREAD

**Issue by shadowxr** [shadowsocks/shadowsocks-android#1354]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Android version: 6.0.1
Device: redmi 4 pro
Shadowsocks version: 4.3.2

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
.新的ss支持了通过acl链接进行支持，而不用导入里面的内容
正常使用
但是当我使用acl链接是，一旦我自行添加网址，
acl链接后多出个[]proxy_list]
路由选择自定义规则会变成类似绕过局域网代理的效果
打开任意网站都是通过代理

### What did you expect to see?

自己添加代理不会变成绕过局域网效果

手机反馈，无法上图
未自行添加代理，自定义规则页面为

https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/acl/gfwlist.acl

查ip为自己地址

添加网址，页面如下
https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/acl/gfwlist.acl[proxy_list]
(^|\.)name\.name$

查ip为节点地址

复制出acl内容，导入
在自行添加代理网址，使用正常

**Comment by madeye** [comment]
Duplicate with #1351
