### ISSUE TITLE
Foreground service in Android O

### ISSUE THREAD

**Issue by LvWind** [shadowsocks/shadowsocks-android#1355]
After update to Android O, it always shows a notification "shadowsocks is running in the background"
What i know is before API 26, A foreground service without a notification shows the "running". But Shadowsocks has a notification with status and usages. So why it start appearing in O, i'm totally no idea.
What do you think about it? @madeye 
![device-2017-08-23-140128](https://user-images.githubusercontent.com/280190/29601207-d8f86cc6-880c-11e7-958a-53d864e2ccc5.png)

### Environment

* Android version: 8.0
* Device: Nexux 5X
* Shadowsocks version: 4.1.8

**Comment by madeye** [comment]
I also noticed it months ago. Currently, I assume it's a bug of Android OS. 😃

**Comment by madeye** [comment]
It looks a low priority notification of foreground service would still cause this "status and usage" notification shows up.

**Comment by madeye** [comment]
Another example can be found in the same screenshot, where ADB is listed in the "status and usage" notification.

**Comment by LvWind** [comment]
Once [startForeground()](https://github.com/shadowsocks/shadowsocks-android/blob/f5247d627db2d41a73e5b8ca69b3147687d3b556/mobile/src/main/scala/com/github/shadowsocks/ShadowsocksNotification.scala#L102) method is called in Android O, the "running" notification will show if your app is not in foreground.
A VpnService has already promotes itself to the foreground. So stop using this method may fix this issue.


refer: https://developer.android.com/about/versions/oreo/background.html#services   chapter"Background Service Limitations"

**Comment by madeye** [comment]
Interesting.

@Mygod What do you think?

**Comment by LvWind** [comment]
I mean, showing notifications just with NotificationManager.notify() and setOngoing = true

**Comment by madeye** [comment]
Weird, After removing startForeground(), I got ANR in the VPN service after starting the service.

**Comment by LvWind** [comment]
oops, i found in that link:
 "If the app does not call startForeground() within the time limit, the system stops the service and declares the app to be ANR."
Maybe the "running" notification can not be removed in O

**Comment by Mygod** [comment]
I have implemented everything accordingly. I have no idea what caused that behavior. IIRC it didn't show up on emulators and I don't have a Oreo device to test it.

Maybe try calling stopService before startForeground? Just a guess.

**Comment by Mygod** [comment]
Wait I already have replaced startService with startForegroundService haven't I? :/

In that case maybe it's because of priority.

**Comment by madeye** [comment]
@Mygod Yes, we're using `startForegroundService` for API >= 26.

**Comment by LvWind** [comment]
<img width="376" alt="screenshot 2017-08-24 11 49 21" src="https://user-images.githubusercontent.com/280190/29648739-552f511e-88c2-11e7-8acb-cdde4eca85b7.png">
My emulator also has this notify.
And i tried to set NotificationChannel's importance to IMPORTANCE_MAX, nothing different.

**Comment by LvWind** [comment]
But IMPORTANCE_MAX worked. (I tested in my own project, not this one)

**Comment by madeye** [comment]
Hmm. as a trade-off, I suggest keep our current priority. `IMPORTANCE_MAX` would show an icon on the status bar.

**Comment by Mygod** [comment]
Since Android system will only show one notification for all the background
services, I don't consider this a major flaw for the moment. It'd be great
if someone could find related source code for that notification.

**Comment by WordlessEcho** [comment]
Is it concerned about [this issue](https://issuetracker.google.com/issues/62480012)?

**Comment by LvWind** [comment]
This Notification in AOSP
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/am/ActiveServices.java#790

https://github.com/android/platform_frameworks_base/blob/b056324630b8adfeb38393bcab49f3b9c720f4fd/services/core/java/com/android/server/am/ActiveServices.java

**Comment by Mygod** [comment]
Thanks @LvWind!

So I did some reading and the answer is no. As long as the app [is not on top](https://github.com/android/platform_frameworks_base/blob/b056324630b8adfeb38393bcab49f3b9c720f4fd/services/core/java/com/android/server/am/ActiveServices.java#L813) and [is not a system app](https://github.com/android/platform_frameworks_base/blob/b056324630b8adfeb38393bcab49f3b9c720f4fd/services/core/java/com/android/server/am/ActiveServices.java#L1001) ([source](https://github.com/android/platform_frameworks_base/blob/d86b8fe/core/java/android/app/ActivityManager.java#L460)) this notification will be shown. Therefore the only solution for AOSP may be moving this app to system, unless somebody can think of a smart hack.

**Comment by Mygod** [comment]
A tasker script that snoozes this notification as a workaround: https://www.xda-developers.com/hide-app-running-background-notification-android-oreo/

**Comment by LvWind** [comment]
wow
I think it is using [NotificationListenerService.snoozeNotification()](https://developer.android.com/reference/android/service/notification/NotificationListenerService.html#snoozeNotification(java.lang.String, long)) to
snooze this notification for a looooong time.

**Comment by LvWind** [comment]
Tried to make a standalone tool to snooze it.
Need someone's help to test.
https://github.com/LvWind/NotRunningInBg/releases/tag/v0.1

**Comment by Mygod** [comment]
Interestingly I just tried Adguard and it somehow managed to dodge this bullet.

**Comment by WordlessEcho** [comment]
Other way:
Change notification importance to medium+

**Comment by Mygod** [comment]
It seems like this notification has been removed in Android 9: https://github.com/aosp-mirror/platform_frameworks_base/commit/070d142993403cc2c42eca808ff3fafcee220ac4

@madeye Thoughts?

**Comment by madeye** [comment]
If so, I think we can put back our notification to lowest priority on Android 9+.
