### ISSUE TITLE
Power consumption.

### ISSUE THREAD

**Issue by libook** [shadowsocks/shadowsocks-android#1358]
### Environment

* Android version: *8.0.0*
* Device: *Google Pixel*
* Shadowsocks version: *4.2.3 from Google Play*
* Last version that did not exhibit the issue (if applicable): Not clear. After I upgrade my Android to 8.0.0.

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-128-CFB
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### Problem description

26%(about 680 mAh) power usage in 5 hours. This data is from Android settings.
It seems not normal.
Please let me know if you need more information.
Thanks.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-does-shadowsocks-consume-so-much-battery-on-android-50

**Comment by libook** [comment]
@madeye Thanks for your answer.

I used shadowsocks-android for many years with Android 5, 6 and 7. It was fine before.
This time, I obviously felt difference. So I said "It seems not normal.".

I remembered that this has been happening on several previous versions on Android 7.

Of course I hope I ware wrong.
It may be the issue of my Apps. Although I haven't found out.

Well, I'll keep watching it.

**Comment by Hbzzw** [comment]
The same one 7.1.2

**Comment by Mygod** [comment]
Battery usage shown in battery stats will increase significantly when you're using this app on mobile network. Reasons are not known.

**Comment by kyze8439690** [comment]
@Mygod because all baseband battery consumption will be counted on ss.
