### ISSUE TITLE
Shadowsocks-android can not automatically start with the system, the phone is not root(os:meizu flyme)

### ISSUE THREAD

**Issue by augustblizzard** [shadowsocks/shadowsocks-android#1360]
### Environment

* Android version:  5.1 flyme 6.1.0.0A
* Device: Meizu Pro 5
* Shadowsocks version: 2.10.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: Default
* [  ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Set the auto Connect in shadowsocks

### What did you expect to see?
automatically start with the system

### What did you see instead?
no automatically start with the system

**Comment by Mygod** [comment]
Check your app settings & system settings.

**Comment by rainbowhat** [comment]
What settings? Specifically?

**Comment by augustblizzard** [comment]
sorry, I had changed my device and "fixed" this problem.
