### ISSUE TITLE
can connect to server but cannot connect to internet

### ISSUE THREAD

**Issue by myhmz** [shadowsocks/shadowsocks-android#1362]
### Environment

* Android version: 7.0
* Device: Samsung S7 edge
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ x] TCP Fast Open
* [ ] NAT mode

tried all methods but didn't work
neither ShadowsocksR
other VPN app was ok to use

there is some connection report

--- 2017年9月1日 00:25:15

Network interfaces and IPs
    lo - 127.0.0.1
    lo - ::1
    dummy0 - fe80::………%dummy0
    p2p0 – f……….%p2p0
    wlan0 - 192.168.1.6
    wlan0 - ………..%wlan0
    tun0 - 26.26.26.1
    tun0 – f……..

MAC address is not available

Current connection type: WIFI
    WLAN: ChinaNet-………
    DNS #1: 192.168.1.1
    Gateway: 192.168.1.1
    Mask: 255.255.255.0
    IP: 192.168.1.6
    Lease: 86400 s
    DHCP: 192.168.1.1

IP routes
26.26.26.0/24 dev tun0  proto kernel
        scope link  src 26.26.26.1 
192.168.1.0/24 dev wlan0  proto kernel
        scope link  src 192.168.1.6 

IP neighbors
fe80::1 dev wlan0
        lladdr MAC router STALE
fe80::…….. dev wlan0
        lladdr MAC STALE
192.168.1.3 dev wlan0
        lladdr MAC STALE
192.168.1.1 dev wlan0
        lladdr MAC REACHABLE
192.168.1.43 dev wlan0
        lladdr MAC STALE

Netstat
    Proto    Recv   Send    State
    Local Address        Foreign Address
    tcp        0        0        ESTABLISHED
192.168.1.6:53966    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53963    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41578
    tcp        0        0        ESTABLISHED
192.168.1.6:54003    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:41578    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41593
    tcp        0        0        ESTABLISHED
localhost:41593    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:41575    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41583
    tcp        0        0        ESTABLISHED
localhost:41596    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:41615    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:41589    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41596
    tcp        0        0        ESTABLISHED
localhost:41609    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:41568    localhost:socks
    tcp        0        0        ESTABLISHED
192.168.1.6:54000    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53981    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41568
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41589
    tcp        0        0        ESTABLISHED
localhost:41581    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41572
    tcp        0        0        ESTABLISHED
localhost:41612    localhost:socks
    tcp        0        0        ESTABLISHED
192.168.1.6:53978    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53990    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53971    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53997    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:41572    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41575
    tcp        0        0        ESTABLISHED
localhost:41588    localhost:socks
    tcp        0        0        ESTABLISHED
192.168.1.6:53956    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53957    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41566
    tcp        0        0        ESTABLISHED
192.168.1.6:53984    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
192.168.1.6:53960    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:41583    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41588
    tcp        0        0        ESTABLISHED
192.168.1.6:53977    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
localhost:41566    localhost:socks
    tcp        0        0        ESTABLISHED
localhost:socks    localhost:41581
    tcp        0        0        ESTABLISHED
localhost:41602    localhost:socks
    tcp        0        0        ESTABLISHED
192.168.1.6:53972    103.1.206.62:16843
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:37556    syd15s03-in-f10.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5292    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:50041    syd15s01-in-f10.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5292    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5287    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5286    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:37008    syd09s14-in-f10.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5287    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5290    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:40158    syd09s15-in-f3.1e100.ne
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5292    nrt12s12-in-f192.1e100.
    tcp        0        0        TIME_WAIT
::ffff:192.168.1.6:4399    resolver2.opendns.com:h
    tcp        0        0        TIME_WAIT
::ffff:192.168.1.6:4873    ::ffff:124.239.227.241:
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:45454    syd15s03-in-f4.1e100.ne
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5287    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5290    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5290    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5287    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5292    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:45339    ::ffff:183.232.125.162:
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:37566    syd15s03-in-f10.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:46975    ::ffff:14.17.43.118:htt
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5290    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:45426    syd15s03-in-f4.1e100.ne
    tcp        0        1        FIN_WAIT1
::ffff:192.168.1.6:5659    ::ffff:220.181.112.244:
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5291    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:55536    syd15s04-in-f8.1e100.ne
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:48115    syd15s03-in-f14.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:37550    syd15s03-in-f10.1e100.n
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:38920    ::ffff:203.205.151.193:
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:60018    ec2-52-68-183-20.ap-nor
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5289    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5292    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5290    nrt12s12-in-f192.1e100.
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:3968    ::ffff:42.202.154.22:ht
    tcp        1        0        CLOSE_WAIT
::ffff:192.168.1.6:5288    nrt12s12-in-f192.1e100.
    tcp        0        0        ESTABLISHED
::ffff:26.26.26.1:41661    ::ffff:123.151.137.103:
    udp        2816        0        ESTABLISHED
192.168.1.6:bootpc    192.168.1.1:bootps

Traffic since device boot
    Total Bytes sent: 112,838,267
    Total Bytes rcvd: 504,141,313

    Total Packets sent: 449,931
    Total Packets rcvd: 541,025

and some ping report

ping 192.168.1.1
from 26.26.26.1: icmp_seq=1
destination port unreachable
from 26.26.26.1: icmp_seq=1
destination port unreachable
from 26.26.26.1: icmp_seq=1
destination port unreachable

**Comment by myhmz** [comment]
I think it must be something wrong with my phone
reset the app, reboot the phone, reinstall the app, all of them didn't work
maybe I should throw away this phone(this phone is new, the elder one(meizu mx4)'s ss&ssr worked)

**Comment by madeye** [comment]
1. Double check your config
2. Disable "DNS forwarding"

**Comment by XC3N** [comment]
I have similar issues, but I think I know why.

Are you using a non-chinese Android OS in China?

For my Lineage OS operating phone to work in china, I need to change the global setting for captive_portal_http_url to use a server different than googles, since those are blocked.

It seems the new version of shadowsocks reverts those settings to default, so I end up with the VPN thinking it's not working because it cannot reach google's server? I am not sure

everything was working fine before the last update, I now have the same symptoms as you (can connect to server but cannot reach internet and app claims internet is unreachable)

**Comment by myhmz** [comment]
I will try these methods later. It seems the app goes normal now by using the mobile network.
BUT it's a hard thing to recover the phone and system because my phone has some important data&photos, and my phone has not root yet.
So I'll review later when get home.

**Comment by myhmz** [comment]
They are all working properly. It is puzzling ...

**Comment by myhmz** [comment]
First of all, i'm appreciate for your reply.
And I'm a total Chinese.
There seems no problem about the ss&ssr, I also feel confused, but no idea.
Sometimes it appear the message "portal cannot reachable", sometime seems normal but other apps cannot connect internet.
Well, i have changed the isp provider, every problem has gone, I cannot go back that enviorement to test the ss either.
Just so-so. It's too hated. lol
That's all.  星期五, 01 九月 2017, 10:02下午 +08:00 发件人 XC3N  notifications@github.com :
