### ISSUE TITLE
build faild(memory allocation (mmap)faild)

### ISSUE THREAD

**Issue by tangyuanfu** [shadowsocks/shadowsocks-android#1363]
机器配置
CPU:
1 vCore
RAM:
2048 MB
Storage:
40 GB SSD
OS:
CentOS 7 x64
编译目标v4.2.4
问题
机器从1G RAM升级到2G RAM都显示“memory allocation (mmap)faild”不清楚究竟是不是内存不够。希望得到帮助。
下面是日志
[hs_err_pid8111.log.txt](https://github.com/shadowsocks/shadowsocks-android/files/1269215/hs_err_pid8111.log.txt)
[log.txt](https://github.com/shadowsocks/shadowsocks-android/files/1269216/log.txt)
log.txt在centos下是正常的，Windows下可能会有编码问题（log太长，截取了error部分）

[root@vultr shadowsocks-android]# cat log | grep error
[error] bootstrap/cmd/internal/dwarf
[error] bootstrap/cmd/internal/sys
[error] bootstrap/cmd/internal/obj
[error] bootstrap/cmd/internal/obj/arm
[error] bootstrap/cmd/internal/obj/arm64
[error] bootstrap/cmd/internal/obj/mips
[error] bootstrap/cmd/internal/obj/ppc64
[error] bootstrap/cmd/internal/obj/s390x
[error] bootstrap/cmd/internal/obj/x86
[error] bootstrap/cmd/asm/internal/arch
[error] bootstrap/cmd/asm/internal/flags
[error] bootstrap/cmd/asm/internal/lex
[error] bootstrap/cmd/asm/internal/asm
[error] bootstrap/cmd/internal/bio
[error] bootstrap/cmd/asm
[error] bootstrap/cmd/compile/internal/ssa
[error] bootstrap/cmd/compile/internal/syntax
[error] bootstrap/cmd/internal/gcprog
[error] bootstrap/math/big
[error] bootstrap/cmd/compile/internal/gc
[error] bootstrap/cmd/compile/internal/amd64
[error] bootstrap/cmd/compile/internal/arm
[error] bootstrap/cmd/compile/internal/arm64
[error] bootstrap/cmd/compile/internal/mips
[error] bootstrap/cmd/compile/internal/mips64
[error] bootstrap/cmd/compile/internal/ppc64
[error] bootstrap/cmd/compile/internal/s390x
[error] bootstrap/cmd/compile/internal/x86
[error] bootstrap/cmd/compile
[error] bootstrap/debug/pe
[error] bootstrap/cmd/link/internal/ld
[error] bootstrap/cmd/link/internal/amd64
[error] bootstrap/cmd/link/internal/arm
[error] bootstrap/cmd/link/internal/arm64
[error] bootstrap/cmd/link/internal/mips
[error] bootstrap/cmd/link/internal/mips64
[error] bootstrap/cmd/link/internal/ppc64
[error] bootstrap/cmd/link/internal/s390x
[error] bootstrap/cmd/link/internal/x86
[error] bootstrap/cmd/link
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] encoding
[error] errors
[error] internal/race
[error] internal/syscall/windows/sysdll
[error] math
[error] sync/atomic
[error] unicode
[error] unicode/utf16
[error] unicode/utf8
[error] sync
[error] internal/singleflight
[error] io
[error] syscall
[error] bytes
[error] hash
[error] strings
[error] hash/adler32
[error] bufio
[error] path
[error] strconv
[error] internal/syscall/windows
[error] internal/syscall/windows/registry
[error] reflect
[error] encoding/base64
[error] crypto
[error] time
[error] crypto/sha1
[error] os
[error] sort
[error] encoding/binary
[error] fmt
[error] os/signal
[error] container/heap
[error] regexp/syntax
[error] path/filepath
[error] io/ioutil
[error] context
[error] flag
[error] go/token
[error] log
[error] net/url
[error] text/template/parse
[error] compress/flate
[error] encoding/json
[error] debug/dwarf
[error] regexp
[error] os/exec
[error] go/scanner
[error] go/ast
[error] compress/zlib
[error] text/template
[error] debug/macho
[error] debug/elf
[error] go/parser
[error] go/doc
[error] go/build
[error] cmd/go
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] errors
[error] internal/race
[error] sync/atomic
[error] sync
[error] io
[error] unicode
[error] unicode/utf8
[error] bytes
[error] bufio
[error] math
[error] syscall
[error] time
[error] os
[error] strconv
[error] reflect
[error] fmt
[error] strings
[error] cmd/internal/dwarf
[error] encoding/binary
[error] cmd/internal/sys
[error] sort
[error] flag
[error] log
[error] path/filepath
[error] cmd/internal/obj
[error] cmd/internal/goobj
[error] path
[error] debug/dwarf
[error] compress/flate
[error] hash
[error] hash/adler32
[error] compress/zlib
[error] debug/elf
[error] debug/gosym
[error] debug/macho
[error] debug/pe
[error] debug/plan9obj
[error] cmd/vendor/golang.org/x/arch/arm/armasm
[error] cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
[error] cmd/vendor/golang.org/x/arch/x86/x86asm
[error] regexp/syntax
[error] regexp
[error] text/tabwriter
[error] cmd/internal/objfile
[error] cmd/addr2line
[error] io/ioutil
[error] archive/tar
[error] hash/crc32
[error] archive/zip
[error] compress/bzip2
[error] compress/gzip
[error] compress/lzw
[error] container/heap
[error] container/list
[error] container/ring
[error] context
[error] crypto
[error] crypto/subtle
[error] crypto/cipher
[error] crypto/internal/cipherhw
[error] crypto/aes
[error] crypto/des
[error] math/rand
[error] math/big
[error] crypto/dsa
[error] crypto/elliptic
[error] crypto/sha512
[error] encoding/asn1
[error] crypto/ecdsa
[error] crypto/hmac
[error] crypto/md5
[error] internal/syscall/unix
[error] crypto/rand
[error] crypto/rc4
[error] crypto/rsa
[error] crypto/sha1
[error] crypto/sha256
[error] crypto/x509/pkix
[error] encoding/hex
[error] encoding/base64
[error] encoding/pem
[error] internal/nettrace
[error] internal/singleflight
[error] go/token
[error] go/scanner
[error] go/ast
[error] go/parser
[error] go/printer
[error] os/exec
[error] cmd/cgo
[error] runtime/cgo
[error] net
[error] crypto/x509
[error] vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
[error] vendor/golang_org/x/crypto/poly1305
[error] vendor/golang_org/x/crypto/chacha20poly1305
[error] vendor/golang_org/x/crypto/curve25519
[error] crypto/tls
[error] database/sql/driver
[error] database/sql
[error] encoding
[error] encoding/ascii85
[error] encoding/base32
[error] encoding/csv
[error] encoding/gob
[error] unicode/utf16
[error] encoding/json
[error] encoding/xml
[error] vendor/golang_org/x/net/http2/hpack
[error] vendor/golang_org/x/net/idna
[error] vendor/golang_org/x/net/lex/httplex
[error] vendor/golang_org/x/text/transform
[error] vendor/golang_org/x/text/unicode/norm
[error] vendor/golang_org/x/text/width
[error] mime
[error] mime/quotedprintable
[error] net/textproto
[error] mime/multipart
[error] net/http/httptrace
[error] net/http/internal
[error] net/url
[error] net/http
[error] expvar
[error] text/template/parse
[error] text/template
[error] go/doc
[error] go/build
[error] go/constant
[error] go/format
[error] go/types
[error] text/scanner
[error] go/internal/gccgoimporter
[error] go/internal/gcimporter
[error] go/importer
[error] hash/crc64
[error] hash/fnv
[error] html
[error] html/template
[error] image/color
[error] image
[error] image/color/palette
[error] image/internal/imageutil
[error] image/draw
[error] image/gif
[error] image/jpeg
[error] image/png
[error] index/suffixarray
[error] internal/pprof/profile
[error] internal/syscall/windows
[error] internal/syscall/windows/registry
[error] internal/syscall/windows/sysdll
[error] runtime/debug
[error] runtime/trace
[error] testing
[error] internal/testenv
[error] internal/trace
[error] log/syslog
[error] math/cmplx
[error] net/http/cgi
[error] net/http/cookiejar
[error] net/http/fcgi
[error] net/http/httptest
[error] net/http/httputil
[error] runtime/pprof/internal/protopprof
[error] runtime/pprof
[error] net/http/pprof
[error] net/internal/socktest
[error] net/mail
[error] net/rpc
[error] net/rpc/jsonrpc
[error] net/smtp
[error] os/signal
[error] os/user
[error] plugin
[error] runtime/race
[error] testing/internal/testdeps
[error] testing/iotest
[error] testing/quick
[error] cmd/api
[error] cmd/internal/obj/arm
[error] cmd/internal/obj/arm64
[error] cmd/internal/obj/mips
[error] cmd/internal/obj/ppc64
[error] cmd/internal/obj/s390x
[error] cmd/internal/obj/x86
[error] cmd/asm/internal/arch
[error] cmd/asm/internal/flags
[error] cmd/asm/internal/lex
[error] cmd/asm/internal/asm
[error] cmd/internal/bio
[error] cmd/asm
[error] cmd/compile/internal/ssa
[error] cmd/compile/internal/syntax
[error] cmd/internal/gcprog
[error] cmd/compile/internal/gc
[error] cmd/compile/internal/amd64
[error] cmd/compile/internal/arm
[error] cmd/compile/internal/arm64
[error] cmd/compile/internal/mips
[error] cmd/compile/internal/mips64
[error] cmd/compile/internal/ppc64
[error] cmd/compile/internal/s390x
[error] cmd/compile/internal/x86
[error] cmd/compile
[error] cmd/compile/internal/test
[error] cmd/internal/browser
[error] cmd/cover
[error] cmd/dist
[error] cmd/doc
[error] cmd/fix
[error] cmd/go
[error] cmd/gofmt
[error] cmd/link/internal/ld
[error] cmd/link/internal/amd64
[error] cmd/link/internal/arm
[error] cmd/link/internal/arm64
[error] cmd/link/internal/mips
[error] cmd/link/internal/mips64
[error] cmd/link/internal/ppc64
[error] cmd/link/internal/s390x
[error] cmd/link/internal/x86
[error] cmd/link
[error] cmd/nm
[error] cmd/objdump
[error] cmd/pack
[error] cmd/pprof/internal/plugin
[error] cmd/pprof/internal/report
[error] cmd/pprof/internal/svg
[error] cmd/pprof/internal/tempfile
[error] cmd/pprof/internal/commands
[error] cmd/pprof/internal/driver
[error] cmd/pprof/internal/fetch
[error] cmd/pprof/internal/symbolizer
[error] cmd/pprof/internal/symbolz
[error] cmd/pprof
[error] cmd/trace
[error] cmd/vet/internal/cfg
[error] cmd/vet/internal/whitelist
[error] cmd/vet
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/QuickToggleShortcut.class:Class requires API level 25 (current min is 19): android.content.pm.ShortcutManager
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ScannerActivity.class:Class requires API level 25 (current min is 19): android.content.pm.ShortcutManager
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksApplication.class:Call requires API level 21 (current min is 19): java.util.Locale#getScript
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksApplication.class:Call requires API level 21 (current min is 19): java.util.Locale#toLanguageTag
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19): android.net.VpnService.Builder#addAllowedApplication
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19): android.net.VpnService.Builder#addDisallowedApplication
[error] lint found 6 errors, 9 warnings
[armeabi-v7a] Compile thumb  : mbedtls <= error.c
[armeabi-v7a] Compile thumb  : cork <= error.c
[arm64-v8a] Compile        : mbedtls <= error.c
[arm64-v8a] Compile        : cork <= error.c
[x86] Compile        : mbedtls <= error.c
[x86] Compile        : cork <= error.c
[error] Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000072968a000, 224464896, 0) failed; error='Cannot allocate memory' (errno=12)
[info] # An error report file with more information is saved as:
[error] (mobile/android:dex) com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(LoggedOutput(sbt.MultiLogger@756012e)),List(),None,Buffer(-Xmx4g, -cp, /usr/local/android/android-sdk-linux/build-tools/26.0.1/lib/dx.jar),false,Map())
[error] com.android.dx.command.Main --dex --num-threads=1 --output /root/project/shadowsocks-android/mobile/target/android/intermediates/dex /root/project/shadowsocks-android/mobile/target/android/intermediates/proguard/classes.proguard.jar
[error] Android SDK command failed (1); see prior messages for details
[error]              
[error] Total time: 251 s, completed Sep 1, 2017 4:40:33 AM

**Comment by Mygod** [comment]
Travis build is passing and therefore you are asking at the wrong place.
