### ISSUE TITLE
server turn on TFO will make my phone reboot when the phone try to start ss android

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-android#1365]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "7.1.2" LineageOS
* Device: Nexus 6P
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
turn on TFO on my server

### What did you expect to see?
my phone works well

### What did you see instead?
when I turn on TFO on my server through sysctl, I saw my phone is in reboot loop.
I noticed when it reboots, it is trying to start ss android

**Comment by Mygod** [comment]
Report to ROM developer instead.
