### ISSUE TITLE
4.2.4 with kcptun(any ver) not working

### ISSUE THREAD

**Issue by dingjibang** [shadowsocks/shadowsocks-android#1366]
### Environment

* Android version: 7.1.2
* Device: xiaomi mix (lineage rom)
* Shadowsocks version: 4.2.4
* Last version that did not exhibit the issue (if applicable): **4.2.3 works**

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by madeye** [comment]
It's almost impossible that there are only 3 changes to the custom list feature between 4.2.3 and 4.2.4.

https://github.com/shadowsocks/shadowsocks-android/commit/b6adeda924cf581793435d33a10f0133572b0b5a
https://github.com/shadowsocks/shadowsocks-android/commit/b14fdcaed9e7cc177abfb68dfa9ac00d37c49596
https://github.com/shadowsocks/shadowsocks-android/commit/390cb522d5903f3124e73b5e67a8eff9553d9c66

**Comment by madeye** [comment]
Please double check your config and try uninstall and reinstall the APKs.

**Comment by dingjibang** [comment]
i try to reinstall 4.2.4 and copy the config from clipeboard from 4.2.3, works...
sorry to disturb you

**Comment by dingjibang** [comment]
i try to reinstall 4.2.4 and copy the config from clipeboard from 4.2.3, works...
sorry to disturb you
