### ISSUE TITLE
Constant "app(s) running in background notification" notification when running on Android 8.0

### ISSUE THREAD

**Issue by zhangcx93** [shadowsocks/shadowsocks-android#1367]
### Environment

* Android version: "8.0.0"
* Device: Google Pixel XL
* Shadowsocks version: 4.2.4

### Issue
Constant notification from Android System - app(s) running in background notification

As shadowsocks should run on background, like Google music or google maps, there is a way to hide the notification based on this [stackoverflow](https://stackoverflow.com/questions/45840782/android-system-apps-running-in-background-notification), by setting notification importance be higher than the minimum.

Please fix this, the extra notification from the system is really annoying, it can only be snoozed for 2 hours if no extra hack applied like Tasker.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1355

**Comment by Mygod** [comment]
Set importance higher than minimum and congratulations you now have one extra annoying notification to deal with.

**Comment by unknownzerx** [comment]
After long time away from Android, I didn't even realize that this area is clickable and there are more settings.

![screenshot_20180716-173617](https://user-images.githubusercontent.com/1313044/42752029-3ab9f4ca-891f-11e8-8624-e16b84ee143e.png)

Note it down here for someone like me.
