### ISSUE TITLE
TCP Fast Open focibly open by default without asking for root permission

### ISSUE THREAD

**Issue by CKrome** [shadowsocks/shadowsocks-android#1369]
### Environment

* Android version: *6.0.1 MMB29M, MIUI 8.5.6.0 Stable*
* Device: *e.g. Xiaomi Redmi Note 4X (Snapdragon variant, mido)*
* Shadowsocks version: *4.2.5*
* Last version that did not exhibit the issue (if applicable):

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:All
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Installed Shadowsocks-android and check settings, found that TCP Fast Open was open( My device has no root permission), and I cannot turn off this setting. 

### What did you expect to see?
TCP Fast Open setting off by default because of no root permission.

### What did you see instead?
It is open and cannot turn off.

PS: I want to say that on my another phone,(Xiaomi Redmi Note 4 (Mediatek variant, AOSP 6.0,),the phenomenon also exists, the only difference is that phone is rooted, so when I tapped that setting, it prompted a message in order to asked for root permission, and after I permitted it turned off. I tried several roms on that phone (including MIUI), they all have the same issue.

**Comment by Mygod** [comment]
Your kernel has tfo enabled by default.

**Comment by CKrome** [comment]
@Mygod So it also can work properly without root?

**Comment by madeye** [comment]
@CKrome Yes.
