### ISSUE TITLE
Why not ChinaDNS?

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-android#137]
While I am visiting certain Mainland China websites with Shadowsocks on Android, I will connect to the overseas mirrors or CDN nodes of those Chinese sites sometimes. And I think it's due to ALL DNS request had been sent to overseas server, it allowed them mistakenly thought I visit from overseas. 
AFAIK, there is the project named ChinaDNS, that has perfect solution of this problem. So, clould you please integrate it into Shadowsocks-Android (and make it work with pdnsd, or just replace pdnsd)?

**Comment by pexcn** [comment]
不是可以把 ChinaDNS 的 国内 DNS 参数设置为 WiFi 优先分配下来的？请问为什么这是不可能的？@madeye 

> Many types of network block outgoing DNS queries, like enterprise Wi-FI, public Wi-FI, small ISPs etc. It makes impossible to solve DNS pollution in ChinaDNS's way.

**Comment by pexcn** [comment]
国外 DNS 参数或许可以用 UDP 转发回来的
