### ISSUE TITLE
推动golang官方提供接口

### ISSUE THREAD

**Issue by ayanamist** [shadowsocks/shadowsocks-android#1370]
我看到ss-android用了overture后，为了protect socket，修改了go的源代码暴露接口。

是否可以共同推动golang官方提供这样的接口，避免后续的fork

https://github.com/golang/go/issues/21820

**Comment by wongsyrone** [comment]
> inserting hooks that can run arbitrary code

人家说了，这种做法提高任意代码执行的风险。

**Comment by ayanamist** [comment]
不一定是我提议的方案，你们有别的更好方案也可以去回复，而不是默默的fork。
我的方案只是改动最小而已。

**Comment by madeye** [comment]
As a very special use case for shadowsocks android, I don't think golang would accept these changes.

Actually, the right way to implement the "protected connections" feature in golang is following Lantern's approach: https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/protected/protected.go

In other words, if we want to have an elegant solution in golang, the best way is patching kcptun and overture instead.

**Comment by ayanamist** [comment]
Lantern的方法就是golang哪个开发者的说法，我觉得很不好，后续net标准库的优化得跟进，自己全部撸一遍，扩展性也很差。

另外overture现在的用法，还要重新编译官方库有点太小题大做了，可以考虑只重新编译用到的net标准库，这样go二进制和其它标准库还是可以用官方的。

**Comment by Mygod** [comment]
If there isn't a better solution, I suggest not fixing what ain't broken.

https://github.com/shadowsocks/go/pull/1

**Comment by a86913179** [comment]
为什么不用unbound而用overture？

**Comment by Mygod** [comment]
As https://github.com/shadowsocks/go/pull/1 is already merged, I assume this has been resolved.
