### ISSUE TITLE
开启后耗电量排行第一，一会功夫就开始发热

### ISSUE THREAD

**Issue by s949492225** [shadowsocks/shadowsocks-android#1371]
### Environment

* Android version: 7.1 google原版系统非第三方
* Device: nexus9
* Shadowsocks version: 4.2.5

### Configuration
* [ ] IPv4 server address hk-ty-a.fqjsq.pw
* Local port: 1080
* Encrypt method: aes-256-cfb
* Route
  * [ ] Bypass LAN & China
* [ ] IPv6 route no
* [ ] Per-App Proxy no
  * [ ] Bypass mode no
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding no
* Plugin configuration (if applicable):
* [ ] Auto Connect yes 
* [ ] TCP Fast Open yes
* [ ] NAT mode no

### What did you do?
开启后耗电量排行第一，一会功夫就开始发热

### What did you expect to see?
耗电少一些，不要发热

### What did you see instead?
请排查性能问题，尽快修复，谢谢

**Comment by pexcn** [comment]
不看 FAQ 也好意思来发 issue？

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md

**Comment by s949492225** [comment]
Why does Shadowsocks consume so much battery on Android 5.0+?

这个我知道，但是实际使用中确实有发热现象，发热的话肯定会耗更多的电

**Comment by s949492225** [comment]
这个耗电排行第一确实是我描述有问题，5.0之后的机制我也明白，但是确实有发热，如果能检查下那就拜托了

**Comment by madeye** [comment]
Double check if there is any app keep connecting to the internet, especially the apps that need to go through shadowsocks.

BTW, apps like Google Service and Facebook are expected to sync data in the background.
