### ISSUE TITLE
手机上shadowdocks-android正常访问国外网站，但连到此手机热点的PC无法正常访问国外网站？

### ISSUE THREAD

**Issue by ivan8099** [shadowsocks/shadowsocks-android#1374]
手机为华为MATE9，系统为ANDROID 7.0，手机上SS已经成功连接服务器，本地端口为10086，并且手机上的APP都可以正常访问国外网站。接下来在手机上开启WIFI热点，此时手机IP为192.168.43.1，使用PC连接此热点。

实验如下：
(1)PC不通过任何代理直接上网，可以上国内网站，但无法上国外网站。
(2)PC通过<192.168.43.1:10086>代理来上网，结果所有网站无法访问。
(3)在手上安装"Proxy Server" APK，设置代理服务器端口为10087，启动代理服务器。PC通过<192.168.43.1:10087>代理来上网，可以正常访问所有国内国外网站。

补充实验如下：
将手机和PC连到同一个WIFI，手机IP为192.168.1.76，手机运行shadowdocks-android可以正常访问国外网站之后，PC通过<192.168.1.76:10086>代理来上网，结果所有网站无法访问。

通过以上的实验，个人结论如下：
(1)shadowsocks-android本身不具备局域网代理功能。
(2)通过热点连到手机的设备，无法利用手机上shadowsocks-android已经建立的连接来访问国外网站。
(3)如果需要分享手机的SS连接，则必须利用第三方的代理软件，比如"Proxy Server"。

我的提问如下：
(1)不知道上面描述的情况，开发者能从设计的层面给出解释和确认吗？
(2)有没可能给shadowdocks-android增加局域网代理功能？这样就不必要额外安装一个"Proxy Server"。
(3)有没可能让其它设备通过热点的方式就能共享手机上的SS连接？

**Comment by ivan8099** [comment]
APK版本为v4.2.5

**Comment by madeye** [comment]
It's expected. Search the issue tracker for more details.

**Comment by ivan8099** [comment]
"Search the issue tracker"是啥意思，我看到这里只有9个issues呢
翻了一遍，没看到相关的说明，所以才来发贴。
可以说得明白些吗？谢谢

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/639

https://github.com/shadowsocks/shadowsocks-android/issues/778

**Comment by creasylau** [comment]
按照你的方法解决了问题，非常感谢你的分享。

**Comment by bulubula** [comment]
https://steemit.com/shadowsocks/@neonatom/root-shadowsocks

**Comment by KeithChang** [comment]
因为SS的手机客户端是VPN模式，也就是说它是个本地VPN服务器，你让它提供proxy服务当然会失败，而且开发者也没有提供其它设备连接这个VPN服务器的接口，所以SS手机客户端无法为其它设备代理。而这个需求不是一个普遍的或者说大众的需求，那么要求开发者添加这个功能会浪费大部分用户的系统资源，所以估计不会添加这项功能。既然有方案能够解决，就这样吧，忍忍吧～

**Comment by Xiaotouming** [comment]
> 问题解决了，按照以下步骤操作即可，其他设置你们可以看着改 （Kcptun插件可以正常工作）
> 
> 需要额外安装一个安卓App：Proxy Server
> 
> 需要注意的是，
> 转发的协议是Socks5，所以普通的http/https方式没法正常访问在手机上的这个代理
> 所以要么你装个FireFox要么装个Proxifier或者别的什么方法走Socks5.
> 大概试了试，只改系统的代理，Edge和Chrome都没法正常访问网络。
> 
> **手机在提供这种方式的代理的时候，手机本身是无法翻墙的**

题主的方法

(3)在手上安装"Proxy Server" APK，设置代理服务器端口为10087，启动代理服务器。PC通过<192.168.43.1:10087>代理来上网，可以正常访问所有国内国外网站。

简单可行还好用（PC手机都能代理），不用你这么复杂弄多一个proxifier手机还不能用了。

**Comment by Xiaotouming** [comment]
> 问题解决了，按照以下步骤操作即可，其他设置你们可以看着改 （Kcptun插件可以正常工作）
> 
> 需要额外安装一个安卓App：Proxy Server
> 
> 需要注意的是，
> 转发的协议是Socks5，所以普通的http/https方式没法正常访问在手机上的这个代理
> 所以要么你装个FireFox要么装个Proxifier或者别的什么方法走Socks5.
> 大概试了试，只改系统的代理，Edge和Chrome都没法正常访问网络。
> 
> **手机在提供这种方式的代理的时候，手机本身是无法翻墙的**

1. 题主问题就不是这个
2. 题主的方法简单好用

**Comment by Yangerle** [comment]
非常感谢，我使用proxy server设置手动代理后，老是提示：已连接，但无法上网。看了你的帖子，改了端口号后成功了。看来端口号也不是随便设置的。
