### ISSUE TITLE
Telegram messenger cannot connect the server in Custom rules mode. 

### ISSUE THREAD

**Issue by csho** [shadowsocks/shadowsocks-android#1376]
### Environment

* Android version: 8.0.0
* Device: Google Nexus 6P
* Shadowsocks version: 4.2.3

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-gcm
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
telegram messenger cannot connect to the server. 
The configuration in Custom rules is the default configuration. 

### What did you expect to see?
telegram connect successfully. 

### What did you see instead?
Connecting...
Work properly in other modes.

**Comment by csho** [comment]
Telegram Android version: 4.3.1

**Comment by madeye** [comment]
It's an known issue of 4.2.3 and fixed in 4.2.5: https://github.com/shadowsocks/shadowsocks-android/issues/1351

Try the latest version instead.

**Comment by csho** [comment]
Thanks
