### ISSUE TITLE
Shadowsocks shuts down automatically

### ISSUE THREAD

**Issue by ClickListener** [shadowsocks/shadowsocks-android#1377]
I download the release V4.2.5, and I run it in HUAWEI P10 with android 7.0.
My problem is when I turn it on, I can search google, but it will shuts down automatically a few min later.

**Comment by madeye** [comment]
It's an issue of EMUI. Check out the issue below for details.

https://github.com/shadowsocks/shadowsocks-android/issues/1091#issuecomment-288420797
