### ISSUE TITLE
[bug] per-app proxy bypass mode not working on Oreo

### ISSUE THREAD

**Issue by gregist** [shadowsocks/shadowsocks-android#1378]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0.0
* Device: Nexus 6
* Shadowsocks version: 4.2.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable): simple-obfs w/ tls
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
put my maps app in the bypass list

### What did you expect to see?
maps app not routed throgh VPN

### What did you see instead?
routed

**Comment by madeye** [comment]
I tried your config locally but cannot reproduce your issue.

Double check your configs.

**Comment by gregist** [comment]
Double checked and reinstalled, same problem.

It might be a bug in my rom since it's currently in beta. I do not have another oreo device with me so I suggest that we keep this issue open for a few days and see if someone else can/cannot reproduce.

**Comment by gregist** [comment]
confirmed rom side issue. close.
