### ISSUE TITLE
Android.mk: tun2socks missing optimization level

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-android#1379]
There is no `-Ox` in tun2socks section, according to gcc manual, it's equivalent to -O0.
Just wondering if it's intended.

**Comment by wongsyrone** [comment]
The same situation applies to mbedtls and pcre

**Comment by wongsyrone** [comment]
Other tweaks: change from -DBADVPN_USE_SELFPIPE to -DBADVPN_USE_SIGNALFD

**Comment by wongsyrone** [comment]
Just some hints. Closing.

**Comment by madeye** [comment]
https://developer.android.google.cn/ndk/guides/ndk-build.html?hl=zh-cn#int

**Comment by wongsyrone** [comment]
I would prefer to -Os instead of -O2, anyway, thanks for the link.

**Comment by Mygod** [comment]
@wongsyrone Less CPU time = less battery consumption. Storage is no longer a big problem on modern phones imo.

**Comment by wongsyrone** [comment]
It doesn't mean only consider storage.

clang

-Os Like -O2 with extra optimizations to reduce code size.

gcc

-Os
Optimize for size. -Os enables all -O2 optimizations that do not typically increase code size. It also performs further optimizations designed to reduce code size.

**Comment by wongsyrone** [comment]
Someone says Os performs like O2.5

**Comment by wongsyrone** [comment]
While madeye would say it's IO bound, it's somewhat meaningless to talk about optimization flags. If you have interest, you can play with latest lwip integrated in badvpn, as I posted in https://github.com/ambrop72/badvpn/issues/45.

The author is not going to maintain the code regularly anymore, I will not submit them as pull requests and will keep them as the personal fork. Based on my tests, it's working well on my phone.

**Comment by pexcn** [comment]
`-O3` 不更好吗？
