### ISSUE TITLE
android shadowsocksR network speed slower than pc

### ISSUE THREAD

**Issue by m1yoki** [shadowsocks/shadowsocks-android#1380]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:Android 7.0 Nougat 
* Device: *LG G5 VS987 unroot
* Shadowsocks version: shadowsocksR v3.4.0.1
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:rc4-md5
* [ ] One-time authentication
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ x] TCP Fast Open
* [ ] NAT mode

well,I build a shadowsocksR from my vps.(vps bandwidth 100Mbps,my network is 8Mbps)
when I use shadowsocksR in my pc,the download speed can be 8 or 9 Mbps.
but I use LTE in my phone with shadowsocksR ,the download speed just 200 or 300 kb/s.(speedtest without shadowsocksR : DL 11.12Mbps,UL 13.44Mbps)
what's wrong with that?
thanks.

**Comment by madeye** [comment]
Sorry, but I think you post the issue in the wrong place.
