### ISSUE TITLE
将 shadowsocks-android 作为透明代理以提供给其它VPN使用?

### ISSUE THREAD

**Issue by sagan** [shadowsocks/shadowsocks-android#1381]
Hi,

我想将 shadowsocks 作为跳板代理使用，即让手机上其他 VPN App 通过 ss 连接服务器

手机 -> ss server -> VPN server -> Target

这样做的原因是：ss 是我自己的cn2 vps假设的，速度很快，但无法使用Netflix等服务（这些视频网站几乎把所有IDC的IP段都封了），所以我想用 vpngate 作为最终代理（vpngate的节点都是家用宽带）, ss作为中转。在 Windows下可以直接设置 vpngate 使用 shadowsocks 的 socks5/http 代理，但是在 Android下很麻烦。

我试了下，在 Android 手机上可以这样做：

1. （手机需要 root) shadowsocks 运行于 NAT 模式; Vpn app 使用 Android 系统的 VPN 接口运行。

2. 由于 VPN app 启动后会修改路由，所以必须将到 ss 服务器 IP 的路由设为直连,  在 adb shell 里 以 root 用户执行命令修改路由: 

ip rule add to <SS_IP>/32 lookup wlan0
ip rule add to <SS_IP>/32 lookup rmnet_data0

这样添加的rule规则优先级高于系统自己管理的规则。

3. 由于 ss nat 会拦截 所有 OUTPUT 流量，所以必须保证从 vpn 虚拟网卡发出的流量不会被拦截

iptables -t nat -I OUTPUT 1 -s 10.0.0.0/8  -j RETURN

问题是，这里的 “10.0.0.0/8” 必须匹配 vpn 虚拟网卡(tun+)的IP，但是不能匹配 wlan / rmnet_data0 的IP，而 vpngate 节点 以及运营商分配的本地 IP 段都是未知且经常变动的，无法提前知道。

所以我想能不能通过 Android 的 VPN Serivice，在 VPN 连接时获取到 tun 网卡的本地IP，然后动态添加规则？

shadowsocks-android 里能否加入这种“ss作为二级代理使用”的功能呢？

**Comment by madeye** [comment]
No plan for this.

If you'd like to DIY, two possible solutions:

1. Setup VPN gate on your VPS server.
2. Turn on NAT mode, enable per-app mode, not selecting any app in the list. Setup your VPN app to use the local SOCKS5 proxy: `127.0.0.1:1080`

**Comment by sagan** [comment]
谢谢

试了下第二种方法好像解决了，开启 ss NAT, per-app mode, 去掉 "bypass mode" 选项，app list 里只选中 VPN App。
