### ISSUE TITLE
When enable TFO but server not support TFO will case kernel panic

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-android#1382]
Sorry for my English.

Phone: Google Nexus 5X
Android Version: 7.1.2
Operating System: LineageOS 14.1 20170828
Kernel Version: 3.10.73

I Enabled TFO ,When I try switch server from support TFO to not support TFO server,And not disable TFO on Phone, The Phone will reboot.

After check last_kmsg,This look's kernel panic:
https://gist.github.com/chenshaoju/c65d4cde61e6fd2dcb6272e8920859e7

I'm not sure this is kernel issue or libss-local.so case kernel panic.

If this not case by libss-local.so or this is a kernel issue,Please let me know,I will post to LineageOS Jira.

Thank you. :)

**Comment by Mygod** [comment]
Do report to your ROM developer. Custom kernel is very common in custom ROMs. I suspect that your kernel version may not be telling the truth.

**Comment by chenshaoju** [comment]
Thanks!
