### ISSUE TITLE
`--no-delay` 参数以后会加上吗？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1383]

**Comment by madeye** [comment]
Nope. It's just a very special option for advanced users.

**Comment by pexcn** [comment]
emmm... 我想在自己的 fork hardcode 上 `--no-delay` 这个参数，想问一下，如果客户端开这个参数，服务端没开，会不会有什么异常？@madeye

**Comment by madeye** [comment]
Nope. No side effect.

**Comment by pexcn** [comment]
感谢~

**Comment by pexcn** [comment]
想请教一下，`--no-delay` 这个参数，我这样 hardcode 正确吗？https://github.com/pexcn/shadowsocks-android/commit/8d845568606ad600706ce2fd4ebb12e786148538 @madeye

**Comment by madeye** [comment]
Yes, it should work.

**Comment by pexcn** [comment]
Thanks a lot~
