### ISSUE TITLE
双行常驻通知使用频率不高且占用通知栏位，建议优化为单行

### ISSUE THREAD

**Issue by voq** [shadowsocks/shadowsocks-android#1384]
### Environment

* Android version: v4.2.5
* Device: xiaomi mix with miui8
* Shadowsocks version: v3.0.8
* Last version that did not exhibit the issue (if applicable): not applicable

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
从屏幕顶端下划，查看通知栏

### What did you expect to see?
显示单行SS通知

### What did you see instead?
显示双行SS通知

**Comment by CKrome** [comment]
@voq This issue was NOT caused by shadowsocks-android, actually its the feature of MIUI, MIUI will show a notification when apps wants to use VPN service.
Since your phone is Xiaomi mix, my advice is not to use MIUI, use 3rd party roms instead ( e.g. Lineage OS)
