### ISSUE TITLE
你想过65535个接口，从默认的8388接口调到160号端口要多久吗？

### ISSUE THREAD

**Issue by Edelwiess** [shadowsocks/shadowsocks-android#1385]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
I want to set port to port 161

### What did you expect to see?

I want to input "161" by keyboard.
### What did you see instead?

I roll screen for 5 minutes

**Comment by madeye** [comment]
Touch the port number and enter the number directly.

**Comment by pexcn** [comment]
（笑。。

**Comment by DizzyPPP** [comment]
I want to input "161" by keyboard.

**Comment by medifle** [comment]
Maybe the author needs to consider adding a UI prompt for smartphone beginners...

**Comment by livc** [comment]
lol

**Comment by iVeego** [comment]
hhhhhh
