### ISSUE TITLE
Android8.0中，Wifi环境下，延迟高？

### ISSUE THREAD

**Issue by linnnger** [shadowsocks/shadowsocks-android#1388]
新换了手机(xz1 compact, Android 8.0)，发现ss（最新版）在wifi环境下，延迟很高（而且不稳定），而同样版本的ss客户端、同样的wifi下，在老手机（Android 5.0）上，延迟就低很多了。下载30mb的GP应用，8.0上需要10分钟甚至更久，而5.0上只要1-2分钟。

另外，关掉wifi，使用4g网络，就正常了，只有wlan环境下才如此（公司的和家里的都是如此）。

**Comment by Mygod** [comment]
Does this problem still persist? I seem to have similar experience where the connection is usually slow on new devices but it disappears after using it for a while.
