### ISSUE TITLE
Automatic Language ?

### ISSUE THREAD

**Issue by CorentinJacob** [shadowsocks/shadowsocks-android#1391]
### Environment

Android Version 7.0 
Moto G5 Plus
Shadowsocks 4.2.5 for Android

###

I have my language system in french so when I installed the apk, it was in english and when i restart the application after i have setup my vpn connection, the language in the app was in Chinese (I'm in China).

**Comment by Mygod** [comment]
Look at your Android language preferences in settings. I think Android picks whatever matches your highest preference and falls back to English by default but I'm not sure.
