### ISSUE TITLE
突然无法连接了

### ISSUE THREAD

**Issue by coolmoya** [shadowsocks/shadowsocks-android#1393]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "8.0.0", more detailed description is preferred*
* Device: *Google Pixel*
* Shadowsocks version: *version code "4.2.5"
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
点击shadowsocks的test

### What did you expect to see?
正常

### What did you see instead?
Failed to detect internet connection:

**Comment by coolmoya** [comment]
可能是账号问题？。通过app中“手动设置”得到的默认配置文件可以连接。

**Comment by arvinpan** [comment]
不知道是不是最近变严了，我这几天也不行，今天Server端换了个端口就好了，可以试试

**Comment by joure** [comment]
portal.shadowsocks.la  主机地址变了，得重新配置一下，目前只有部分节点可用

**Comment by joure** [comment]
https://portal.shadowsocks.la/

**Comment by JJJeffery** [comment]
我的手机端（安卓）也没网了，PC端（windows）也是一样。
