### ISSUE TITLE
全局代理并没有完全做到全局代理

### ISSUE THREAD

**Issue by tiwa-7er** [shadowsocks/shadowsocks-android#1395]
example: pixiv.net在全局代理下无法正常访问，但在仅代理中国地址和代理中国无法访问地址时可以访问

**Comment by eastmalon** [comment]
你的代理服务器的ip被该网站封禁，并且中国大陆pixiv.net被dns污染。与shadowsocks无关

**Comment by tiwa-7er** [comment]
谢谢！

2017年10月6日星期五，Via Liberty <notifications@github.com> 写道：
