### ISSUE TITLE
suddenly can not connect in China

### ISSUE THREAD

**Issue by zengnan2218** [shadowsocks/shadowsocks-android#1396]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. 7.1.1 NMF26F
* Device: Xiaomi Max2
* Shadowsocks version: 4.0.0
* Last version that did not exhibit the issue (if applicable): 4.0.0 (i haven't received any update since i installed the app actually)

### Configuration

_Put an `x` inside the [ ] that applies._

* [X ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [X ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ X] TCP Fast Open
* [ ] NAT mode

### What did you do?
connet the app like i used to do

### What did you expect to see?
connect successfully

### What did you see instead?
SSL handshake timed out

**Comment by zengnan2218** [comment]
in fact, the shadowsock fuctions properly for the past year, but suddenly cannot use today, i want to know if there is a bug happening or I cannot use VPN anymore due to the internal firewall upgrade.

**Comment by JAYQIWAN** [comment]
I cannot either. looking for the way to figure it out.

**Comment by kingda** [comment]
i dont know why when connecting to a sever, it shows SSL wrong.

**Comment by totopamimi** [comment]
can't connect either. show 'TCP connection timeout'

**Comment by elephachang** [comment]
It shows connected, but 0 in upload and download speed.
This happened few days ago. Trying to figure out.
Don't know whether it's the problem of my account or the  internal firewall ...

**Comment by Acc0rdeur** [comment]
Standard server lockdown due to the 19th national congress.

**Comment by zengnan2218** [comment]
@Acc0rdeur
So, you mean there will be no solution at all?

**Comment by zengnan2218** [comment]
I found that the shadowsocks updated its server address to deal with this problem, by updating the corresponding server setting it can connet properly, so, the issue can close now.
