### ISSUE TITLE
Dns Leak problem

### ISSUE THREAD

**Issue by AnguisCaptor** [shadowsocks/shadowsocks-android#1397]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2
* Device: Oneplus5
* Shadowsocks version: 4.2.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:AES-256-CTR
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
I was connecting to my Shadowsocks server (which is running DnsCrypt) and when I connected and went to dnsleaktest.com it showed me 6 google servers, so this is clearly a dns leak

### What did you expect to see?
1 Dns Server in the dnsleaktest.com website

### What did you see instead?
6 google dns servers

**Comment by AnguisCaptor** [comment]
Extra info: if "DNS Forwarding" is enabled or disabled they still go to the target shadowsocks server
Dnsleak fix: if you run DnsCrypt or any other dns server yourself run this
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to 127.0.0.1:53
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to 127.0.0.1:53

it will now showup only 1 server in dnsleaktest.com

**Comment by madeye** [comment]
What's the remote DNS setting in your Shadowsocks-android?

**Comment by AnguisCaptor** [comment]
I can leave the DNS option empty or OpenDNS (208.67.222.222) but it will still show google's dns

**Comment by Mygod** [comment]
Might be related: https://github.com/shadowsocks/shadowsocks-android/blob/e8b5953701830e17c135e7050dd103ef7af45c51/mobile/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L189

**Comment by pexcn** [comment]
@Mygod 测试这个要开启 DNS 转发吗？

**Comment by Mygod** [comment]
Make sure you have `all' selected in `route'.
