### ISSUE TITLE
shadowsocks not work while shadowsockR works.

### ISSUE THREAD

**Issue by myrshfrs** [shadowsocks/shadowsocks-android#1398]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):
android version: 7.1.2 Lineageos14.1
device: mi 5s
shadowsocks version: v4.2.5

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x ] IPv6 route
* [ ] Per-App Proxy
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
i connect to a server that works well on my windows pc. 
ps: i try shadowsockR android in my phone with the same server and i can use google play.

### What did you expect to see?
i can use google play

### What did you see instead?
i can't, it says no internet connection. make sure wifi or cellular data is turned on, then try again.
[log.txt](https://github.com/shadowsocks/shadowsocks-android/files/1364689/log.txt)

**Comment by madeye** [comment]
Disable IPv6 and try again.

**Comment by myrshfrs** [comment]
I tried but it still doesn't work..

**Comment by myrshfrs** [comment]
i found out why. shadowsocks doesn't work well when i enable dns forwarding, i disable it and now shadowsocks works well. it is weird because i have checked my sever and i am sure i have enabled udp relay in my server...
