### ISSUE TITLE
请问安卓Shadowsocks有obfsproxy插件吗?

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-android#1400]
今天GFW封了我的一个VPS
后来新开了一个VPS,加上了obfsproxy混淆
请问安卓端有什么插件或者软件可以做obfsproxy混淆通道?

**Comment by CKrome** [comment]
Here:
https://github.com/shadowsocks/simple-obfs-android

**Comment by AmelieNet** [comment]
@CKrome 不会配置那个,有没有更简单点呢?

**Comment by CKrome** [comment]
There are no other Android obfuscation tools that are easier implemented than simple-obfs, you just need to download and set up your profiles in shadowsocks-android.

**Comment by AmelieNet** [comment]
@CKrome Thank you. I'm already using it
