### ISSUE TITLE
shadowsocks-android里的"插件"选项为什么是禁用的?

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-android#1401]
都有什么插件可以安装?

**Comment by Love4Taylor** [comment]
Repo 里 找找就能找到.......
https://github.com/shadowsocks/simple-obfs-android/releases
https://github.com/shadowsocks/kcptun-android/releases

**Comment by AmelieNet** [comment]
@Love4Taylor 谢谢,那个KCPtun 是干什么用的?
