### ISSUE TITLE
扫描二维码添加配置时，没有对密码进行 URL 解码

### ISSUE THREAD

**Issue by YukariHinata** [shadowsocks/shadowsocks-android#1402]
### Environment

* Android version: 8.0.0
* Device: Google Pixel XL
* Shadowsocks version: v4.2.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20-ietf-poly1305
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

通过扫描二维码添加配置。

由于密码中有特殊字符，在生成二维码时对密码进行了 URL 编码。

假设密码为 `!@#$%^`，服务器地址 `123.45.67.89:9999`，生成的 URL 为
```
ss://chacha20-ietf-poly1305:%21%40%23%24%25%5E@123.45.67.89:9999
```
base64 编码后为
```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTolMjElNDAlMjMlMjQlMjUlNUVAMTIzLjQ1LjY3Ljg5Ojk5OTk
```

以上 URL 生成二维码并使用 shadowsocks-android 扫描添加配置

### What did you expect to see?

客户端解析 URL 时，对密码进行 URL 解码

### What did you see instead?

客户端没有对密码进行 URL 解码，导致生成的配置中密码不正确，无法连接。

**Comment by madeye** [comment]
Please follow https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html

**Comment by YukariHinata** [comment]
没注意到这个新的页面… 已解决，感谢提醒～
