### ISSUE TITLE
failed to connect to www.google.com/2404:6800:4008:802::2004(port443)after...

### ISSUE THREAD

**Issue by Yuki-Chen** [shadowsocks/shadowsocks-android#1406]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 5.1.1(BlissPop3.7)
* Device: MI3TD
* Shadowsocks version: version code 4.2.5
* Last version that did not exhibit the issue (if applicable):第一次用

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

用家人的同款小米3TD刷了安卓5.1.1(BlissPop3.7)  用电脑版SS的来自局域网的连接的方式从goole play
下载并安装安卓版SS 结果出现失败:failed to connect to www.google.com/2404:6800:4008:802::2004(port443)after...的提示 我自己的小米3TD用的MIUI系统是能用SS的 相同的服务器

### What did you expect to see?
我希望能用得到SS 谢谢

**Comment by madeye** [comment]
Make sure you didn't enable IPv6 option.

**Comment by Yuki-Chen** [comment]
Yes, I am. I use the same config in two same MI3 TD phone, the other one works fine. @madeye

**Comment by yuwuchaio** [comment]
@Yuki-Chen oppo遇到同样的问题也是Android 5.1.1 ..大佬最后解决了嘛？求方法！

**Comment by Yuki-Chen** [comment]
@yuwuchaio 对不起 我刷了两次机都不行 最后选择放弃了 现在用iOS版的shadowrocket
