### ISSUE TITLE
建议默认使用内建QR扫描器

### ISSUE THREAD

**Issue by zhlicen** [shadowsocks/shadowsocks-android#1407]
https://github.com/shadowsocks/shadowsocks-android/blob/918eec43944128685264ab5a02a1962d32bcea9a/mobile/src/main/scala/com/github/shadowsocks/ProfilesFragment.scala#L346
SS在选择扫码时，会先尝试启动外部扫描器（"com.google.zxing.client.android.SCAN"），失败之后再启动内建扫描器

发现一些国产app中包含修改版的（"com.google.zxing.client.android.SCAN"）扫描器，如果默认调用会引起扫描失败，例如 [享家社区](http://www.wandoujia.com/apps/com.gemdale.client)，除非卸载该app

建议改为默认使用内建的ScannerActivity

**Comment by CzBiX** [comment]
看来还要限定外部扫描器的范围。

不标准的实现真是麻烦。
