### ISSUE TITLE
启动 shadowsocks 客户端后，局域网就不能访问了

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-android#141]
启动shadowsocks后，从手机上无法ping通WIFI路由器网关，停掉shadowsocks后马上就通。但是手机上外网都正常的。而且在局域网内电脑可以ping通手机的IP，但手机ping不通电脑。

不知道是否ss路由的问题。
andriod 5.0，2.3.3

**Comment by 429463267** [comment]
![image](https://user-images.githubusercontent.com/12899262/38617410-8ba8aa44-3dc9-11e8-903b-b4cf424822c5.png)

![image](https://user-images.githubusercontent.com/12899262/38617435-a43561ce-3dc9-11e8-857a-3c795dfab642.png)

我也遇到这个问题。开启之后企业局域网无法访问。
