### ISSUE TITLE
1M/s is the higest  downloading speed on my android device?

### ISSUE THREAD

**Issue by johnlii** [shadowsocks/shadowsocks-android#1411]
### Environment
* Android version: 7.1.1 
* Shadowsocks version:4.2.4

I am using the ipv6 service, and the same net environment speed and the same config in my PC
can reach about 6-8M/s.

but it seems the highest speeding is always limited around 1M/s in my android phone. 
where is the problem?

**Comment by madeye** [comment]
What's your device?

**Comment by johnlii** [comment]
xiaomi6
