### ISSUE TITLE
Network failed with" block connections without VPN"

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1413]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:android o opr5.170623.007
* Device: Nexus 6p
* Shadowsocks version: v4.2.5 and previous version
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Use mobile data not WiFi, Connect shadowsocks, apply option "block connections without VPN"in network -> VPN settings, turn on and off airplane mode.

### What did you expect to see?
As usual

### What did you see instead?
Cannot connect to internet.

**Comment by madeye** [comment]
I don't think this feature is supported. Just disable the option.

**Comment by Mygod** [comment]
This seems to be an upstream bug. Please wait for Google to release a fix.

Source: https://github.com/copperhead/bugtracker/issues/744#issuecomment-332084760

**Comment by iamsad3508** [comment]
bug fixed in android 8.1.0

**Comment by Mygod** [comment]
It still doesn't seem to work in Android Emulators though.

**Comment by rmazajev** [comment]
Yap, don't work on Emulators.
