### ISSUE TITLE
Found the works of copying this software

### ISSUE THREAD

**Issue by kot4ri** [shadowsocks/shadowsocks-android#1417]
![photo_2017-10-18_16-05-42](https://user-images.githubusercontent.com/20045613/31707979-5f5a6b36-b420-11e7-9736-94dec178f2a4.jpg)
![photo_2017-10-18_16-05-43](https://user-images.githubusercontent.com/20045613/31707980-5f972288-b420-11e7-833a-51e6ed25849e.jpg)
![photo_2017-10-18_16-06-48](https://user-images.githubusercontent.com/20045613/31707981-5ffb6b4e-b420-11e7-9a5d-a6e33d699fbb.jpg)
![photo_2017-10-18_16-06-49](https://user-images.githubusercontent.com/20045613/31707983-60500596-b420-11e7-9778-dbef18b611dd.jpg)

https://play.google.com/store/apps/details?id=com.multiselect
https://play.google.com/store/apps/details?id=com.vpnpro51

**Comment by madeye** [comment]
It's a shame to Copy & Paste without following GPL.

But we never want to waste  time on this kind of nonsense. So, closing the bug.
