### ISSUE TITLE
"Can not run program"无法连接远程服务

### ISSUE THREAD

**Issue by Yukiteno** [shadowsocks/shadowsocks-android#1418]
After I set it as system application, it can no longer connect to remote services.
BTW, my system is MIUI 9, XIAOMI 6.

**Comment by Yukiteno** [comment]
OK i solved it, i use Root explorer deleted it, and install it again, done.

**Comment by biodog** [comment]
I did follow your mention, but it's doesn't work with my MIUI 9eu, MI6.

**Comment by biodog** [comment]
How to set 55RR as a system application?

**Comment by studentmain** [comment]
55RR? Ask their developer, or learning how to make your own ROM.

DJ Yang <notifications@github.com> 于 2018年4月3日周二 10:27写道：

**Comment by biodog** [comment]
SSRR, I try to install the SSRR on my MIUI9.5 (EU) system. Consequently, it always shows the "cnanot run program", headache issue.
