### ISSUE TITLE
Help wanted with pre-loading  some config files before building the app

### ISSUE THREAD

**Issue by ss-socks** [shadowsocks/shadowsocks-android#1419]
Hello,

I recently came to china. I have to stay here for 6 months. I found shadowsocks to be only effective tool against GFW. Thanks to shadowsocks I can still be on the real internet. 

Many of my classmates now want access. I am thinking of giving them the ss android app with some preloaded servers. That way, I don't have to deal with their technical problems. 

I am a self taught linux guy. Don't have android dev experience. But I'm learning the basics and I think this will be a fun projects before academic pressure kicks in. Some pointers(eg. where to put config files/or where they are stored etc.) on how can I achieve this will be greatly helpful. 

Thanks.

**Comment by madeye** [comment]
No plan for this. You can always share your config with QR code.
