### ISSUE TITLE
开启shadowsocks无法使用ICMP的问题

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-android#142]
我持续ping我的vps正常，但开启ss后ping就断了，关闭后又恢复正常。但是Ping断时候（也就是开启SS）我能够使用SSH登录VPS，其他上网功能也正常，不知道是否处理ICMP包出现了问题。

**Comment by Macinberry** [comment]
ping 是 icmp 协议， ss 只能代理 UDP/TCP
