### ISSUE TITLE
如何自定义“直连”规则

### ISSUE THREAD

**Issue by hujiamin** [shadowsocks/shadowsocks-android#1423]
### Environment

* Android version:7.0
* Device: *samsung s8*
* Shadowsocks version: "v4.2.5" 

路由方式为“绕过局域网及中国大陆地址”
开启代理后，工商银行的融e联软件无法连接网络，请问这种情况应该如何解决，谢谢。

**Comment by whour** [comment]
使用分程序代理，把要代理侧程序勾选，其他程序则是直连。

**Comment by Sky891028** [comment]
如何设置直连域名呢？ 比如开全局模式  我要指定baidu.com不走代理

**Comment by Mygod** [comment]
It's not supported.
