### ISSUE TITLE
In the 7.1.1 system can not start, the configuration file in other equipment to confirm the normal, orange progress bar flash

### ISSUE THREAD

**Issue by kid101x** [shadowsocks/shadowsocks-android#1424]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* 7.1.1
* HTC U11( International Edition)
* Shadowsocks version: *version code "v4.2.5"
* Last version that did not exhibit the issue (if applicable):4.2.4 the same

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:AES-128-GCM
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Can not start, always.

### What did you expect to see?
This configuration is no problem with other devices

### What did you see instead?
Click to start, the orange progress bar flashed

**Comment by madeye** [comment]
I cannot reproduce the issue with the information you provided.

**Comment by kid101x** [comment]
Yes, I can not reopen the problem on other devices……
Pressing Reset is also invalid……

**Comment by madeye** [comment]
I don't think we can help if it's a device specific problem.

My suggestion is trying other ROMs or report the issue to HTC instead.

**Comment by Mygod** [comment]
Try to get a logcat.

**Comment by kid101x** [comment]
How to get logcat？

**Comment by FlamelightX** [comment]
I believe I have the same issue with you: 
https://file.snode.space/?5086080b1817ae49e54b8f8fc5b9a671
(video shoot within telegram app and the download link extracted with telegram bot)

Samsung Galaxy Note 8 (China Version) Android 7.1.1

**Comment by kid101x** [comment]
Yes, that's it.
PS: Your link ads are too much.
https://imgur.com/a/UcOOi

**Comment by cnsilvan** [comment]
I have the same issue with you.
Meizu Pro5 Flyme6(Android 7.0)

**Comment by gilbertli0409** [comment]
I have the same issue. Here below is the error log:


10638 11431 W FetchTask: exception on config fetch: java.net.UnknownHostException: Unable to resolve host "cloudconfig.googleapis.com": No address associated with hostname
 1583  5884 I ActivityManager: START u0 {cmp=com.android.vpndialogs/.ConfirmDialog} from uid 10211 on display 0
10606 10606 D cr_Ime(Factory): [ThreadedInputConnectionFactory.java:230] onWindowFocusChanged: false
 1583  5908 I ActivityManager: dispatchActivityResumed for activity com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog uid 1000
 7732  7732 I System  : Daemon delayGCRequest, sDelayGCRequest=true, delay=true, sPendingGCRequest=false
10606 10606 D cr_Ime(Factory): [ThreadedInputConnectionFactory.java:230] onWindowFocusChanged: true
 1583  9327 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@7d6f1d5 attribute=null, token = android.os.BinderProxy@f631069
 1583  9329 I ActivityManager: dispatchActivityResumed for activity com.github.shadowsocks/com.github.shadowsocks.MainActivity uid 10211
10606 10606 E ShadowsocksMainActivity: Failed to start VpnService
10638 11433 I CheckinUtil: Classify the device as Phone.

**Comment by Mygod** [comment]
It seems to me that your device has broken VpnService support. I think I will add a more helpful error message.

**Comment by gilbertli0409** [comment]
What about the hostname "cloudconfig.googleapis.com" ?  The hostname never exists.

BTW, I tested another client (SSRR) and it works on my device. Not sure if it is a VpnService broken issue.

Hope all above helps ! Thank you.

**Comment by Mygod** [comment]
That's irrelevant. In that case, try reinstalling this app.

**Comment by gilbertli0409** [comment]
I've reinstalled several times. Unfortunately not work.

**Comment by Mygod** [comment]
Please fill out the issue template to help us investigate the issue.

**Comment by gilbertli0409** [comment]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.1.1*
* Device: *Smartisan Nut Pro2*
* Shadowsocks version: *4.2.5*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Click the connect button.

### What did you expect to see?
Can start and connect successfully

### What did you see instead?
Click start, the orange progress bar flashed  without any messages.

**Comment by Mygod** [comment]
Maybe there's some permission manager on your phone that's preventing this app to create a VPN connection. Check your VPN settings in system settings.

**Comment by gilbertli0409** [comment]
I figured it out ! My google play service is too old.

It works if follow below steps:

1. uninstall the app
2. clean your device's vpn configuration
3. **upgrade your google play service to the latest version.**
4. reinstall the app.

**Comment by Mygod** [comment]
I'm not sure why that would help but I guess it's a bug of Google Play services then.

**Comment by kid101x** [comment]
An update. My HTC U11 can be used normally after updating Android 8.0 ... However I do not know the principle.
