### ISSUE TITLE
为什么不用unbound加国内域名白名单的方式呢？

### ISSUE THREAD

**Issue by a86913179** [shadowsocks/shadowsocks-android#1425]
不论是chinadns还是overture，当遇到一个被污染成国内ip的域名，同时gfwlist未更新(overture的域名列表)，即无法访问。如果这时用的是国内白名单(dnsmasq-china-list)就不会受到影响，而且白名单就算未更新，通过国外dns解析也依然可以访问，unbound能以白名单及黑名单的方式工作，国内域名指定国内dns，特殊域名走特殊dns，其余走国外无污染通道(指定ss-tunnel或opendns:443)。我觉得dns处理的应该是域名而不是ip。

**Comment by wongsyrone** [comment]
因为他们喜欢golang

**Comment by madeye** [comment]
1. Unbound doesn't support SOCKS5 proxy, but overture does: https://github.com/shawn1m/overture/issues/14
2. Unbound can only do TCP or UDP query globally, not mixed. But overture does.

**Comment by a86913179** [comment]
@wongsyrone 好吧，有人弄了个GO的unbound不过也超过一年没有维护了。

**Comment by a86913179** [comment]
@madeye Got it, thanks for your reply :)
