### ISSUE TITLE
org.xbill.DNS.APLRecord that doesn't come with an  associated EnclosingMethod attribute...

### ISSUE THREAD

**Issue by wenewzhang** [shadowsocks/shadowsocks-android#1427]
I try execute sbt clean go-build android:package-release and got error message above
edit the build.sbt add proguard options 
...
  "-keepattributes EnclosingMethod" ::
  "-keep class org.xbill.DNS.APLRecord" ::
  "-keep class org.xbill.DNS.Compression" ::
  "-keep class org.xbill.DNS.Tokenizer" ::
  "-keep class org.xbill.DNS.ZoneTransferIn" ::
  "-keep class org.xbill.DNS.UDPClient" ::
  "-keep class org.xbill.DNS.ResolverConfig" ::
  "-keep class org.xbill.DNS.spi.DNSJavaNameServiceDescriptor" ::
  "-keep class org.xbill.DNS.spi.DNSJavaNameServiceDescriptor" ::
  Nil
but the error message still exists,the dynamic referenced need copy the jar,dnsjava.jar include the org.xbill.DNS and already add to the library dependencies,What should i do?
btw:overture-go need go1.4-bootstrap,the README "go1.4+" make me confused!

Best Regards
Message:
make: *** No rule to make target `/Users/wenewzhang/Documents/goSeasNG/shadowsocks-android/mobile/src/main/jni/../jni/libancillary/fd_recv.c', needed by `/Users/wenewzhang/Documents/goSeasNG/shadowsocks-android/mobile/target/android/intermediates/ndk/obj/local/armeabi-v7a/objs/ancillary/libancillary/fd_recv.o'.  Stop.
make: *** Waiting for unfinished jobs....
Note: com.evernote.android.job.JobManager calls '(com.evernote.android.job.JobCreator$AddJobCreatorReceiver)Class.forName(variable).newInstance()'
Note: com.google.android.gms.internal.zzdim: can't find dynamically referenced class com.google.android.gms.measurement.AppMeasurement$ConditionalUserProperty
...
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.APLRecord$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.Compression$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.UDPClient$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[error] warning: Ignoring InnerClasses attribute for an anonymous inner class
[error] (org.xbill.DNS.ZoneTransferIn$1) that doesn't come with an
[error] associated EnclosingMethod attribute. This class was probably produced by a
[error] compiler that did not target the modern .class file format. The recommended
[error] solution is to recompile the class from source, using an up-to-date compiler
[error] and without specifying any "-target" type options. The consequence of ignoring
[error] this warning is that reflective operations on this class will incorrectly
[error] indicate that it is *not* an inner class.
[info] dex method count: 41464
[error] ndk-build failed!
[error] (mobile/android:ndkBuild) ndk-build failed!
[error] Total time: 114 s, completed Oct 24, 2017 4:25:19 PM

**Comment by madeye** [comment]
```
make: *** No rule to make target /Users/wenewzhang/Documents/goSeasNG/shadowsocks-android/mobile/src/main/jni/../jni/libancillary/fd_recv.c', needed by/Users/wenewzhang/Documents/goSeasNG/shadowsocks-android/mobile/target/android/intermediates/ndk/obj/local/armeabi-v7a/objs/ancillary/libancillary/fd_recv.o'. Stop.
```

This file is missing.

**Comment by wenewzhang** [comment]
yes,the submodules is empty,delete the jni/libancillary directory then execute git to fix it
thank you!
