### ISSUE TITLE
"bypass" apps get blocked by "block connections without VPN"

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1430]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android 8.1.0 OPP5.170921.005
* Device: nexus 6p
* Shadowsocks version: v4.2.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Per-App Proxy
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8
* [ x] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
enable"block connections without vpn"in network settings,set Chrome(for example) bypassed in shadowsocks.

### What did you expect to see?
as usual

### What did you see instead?
Chrome get blocked.

**Comment by madeye** [comment]
I think it's expected.

Since you choose to block connections without VPN, any bypassed application will not go through VPN and get blocked as expected.

**Comment by Mygod** [comment]
Confirmed. When this option is on, only the VPN app itself will be able to use connections outside of VPN. Please report to Google if you want them to change this behavior. ([source](https://android.googlesource.com/platform/frameworks/base/+/19bb1a0/services/core/java/com/android/server/connectivity/Vpn.java#1168))
