### ISSUE TITLE
Notification channel importance being ignored in Android 8.1

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1431]
### Environment

* Android version: 8.1
* Device: Emulator
* Shadowsocks version: 6fa1c822ef7a700ccafc2777b78ac5b670feec11
* Last version that did not exhibit the issue (if applicable): n/a

In Android 8.1, there seems to be only 4 levels of notification importance now but I can't seem to find documentations about this anywhere. Both `IMPORTANCE_MIN` and `IMPORTANCE_LOW` show up as Importance "Medium".

**Comment by aifennng** [comment]
既然提到8.1，顺便提一个不知道算不算bug的bug。一旦开启了VPN，系统便不能识别是否连接了wifi，导致photos无法备份照片。Pixel XL，8.1 Preview。试过一款其他的VPN工具，同样的问题，也许需要Google来修正。

**Comment by Mygod** [comment]
I think Android isn't allowing foreground service notifications to be invisible anymore. Maybe we should just make VPN notification visible for Android 8.x.

**Comment by XC-Zhang** [comment]
@Mygod I found some documentations in material design website which is possibly related to notification issues in Android 8.x:

[https://material.io/guidelines/patterns/notifications.html#notifications-settings]()

> In Android O, a channel’s default importance level for foreground service notifications must be at least `IMPORTANCE_LOW` so that it shows an icon in the status bar.
Channels using the less-prominent `IMPORTANCE_MIN` level will trigger an extra notification from Android at `IMPORTANCE_LOW`, stating that the app is using battery.
