### ISSUE TITLE
android支持负载均衡吗？

### ISSUE THREAD

**Issue by Ltre** [shadowsocks/shadowsocks-android#1436]
* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: Nexus 6p
* Shadowsocks version: v4

目前看到是只能连一个机器，没发现像PC那样均衡切换机器的功能

**Comment by madeye** [comment]
Nope.

**Comment by Mygod** [comment]
Load balancing should be done on server side.

**Comment by moralrebuild** [comment]
@Mygod Could you please give a hint about how to aviod single point failure when load balancing on server side? Thanks in advance.
