### ISSUE TITLE
关于ACM IMC 2017上新工具INTANG的应用

### ISSUE THREAD

**Issue by 7senchen** [shadowsocks/shadowsocks-android#1437]
今天看到消息说，会议上有研究人员发布了新的规避GFW策略，并发布了新的工具 INTANG，希望大神们能研究下，要是能综合运用起来就好啊。
新闻链接：http://www.solidot.org/story?sid=54363
项目地址：https://github.com/seclab-ucr/INTANG

**Comment by Mygod** [comment]
Generally you can use kcptun for now if your area is subject to massive TCP resets.

**Comment by lijun0326** [comment]
Actually if this work, we won't need SS anymore lol

**Comment by Mygod** [comment]
Locking this conversation. Anyone that wish to have more words about this should go to https://github.com/shadowsocks/shadowsocks-org/issues/91.
