### ISSUE TITLE
V4.25版通过访问映射到本地的VPS端口时，不能区分国内、外流量，全部走VPS映射端口

### ISSUE THREAD

**Issue by wansen** [shadowsocks/shadowsocks-android#1438]
你好：
      因为现在在手机（nexus6p 8.1）上除了obfs可以访问外，其它模式在我所在的地区均不能正常连接。正好最近在学习搭建v2ray,发现v2ray有个端口映射功能，其又有编译好的手机客户端，正好可以一试，搭设过程如下：
## 服务器端：
正常搭设最新的shadowsocks-libev 3.1.0版并加入obfs混淆，保证手机客户端可以正常访问。
并在同VPS上搭设v2ray的http、tls两种连接模式，并分别应用了HTTP 伪装和TLS伪装；

上述VPS配置在使用对应客户端时，可同时或分别访问网络。

## 手机端进行端口映射：
v2ray手机客户端进行端口映射，配置如下：
    {
    "protocol": "dokodemo-door",// 一个额外的 dokodemo-door 入口协议
    "port": 12345,// 本地端口
    "listen": "127.0.0.10",
    "settings": {
      "address": "xx.xx.xx.xx",// 远程主机的 IP
      "port": 23456,// 远程主机被影射的端口, 就是VPS 上未经混淆的ss监听端口
      "network": "tcp",// 网络协议，支持"tcp"、"udp"和"tcp,udp"
      "timeout": 15 // 传输超时（秒），0 表示不检测超时
      }
    }
然后在shadowsocks手机端配置：
Server:127.0.0.10  Remote Port:12345，不使用任何plugin，其它配置不变。

## 结果：
原配置国内、外分流，通过obfs访问时分流正常。
通过映射端口，其它配置不变访问时分流就不正常。

因为我不是很懂，只是喜欢折腾一下，如果有什么描述不专业或不太清楚的请批评指正。
以上问题，请懂的热心专业人士如果有空可指点一、二，如何解决映射端口的分流问题，非常感谢！

**Comment by madeye** [comment]
I don't think you can enable both v2ray and Shadowsocks in the same time. Both of them require VPN service.

**Comment by wansen** [comment]
在服务器端：
![server](https://user-images.githubusercontent.com/15998863/32410726-de4ad5a8-c202-11e7-822d-24b4df6b7875.PNG)
手机客户端：Shadowsocks我用的NAT模式，SS开机自启动，V2ray通过一个“Boot Shell”app开机启动，从我看它们申请root权限的提示顺序来看，SS先启动，在本机上，V2要滞后5~10s启动。
![client-1](https://user-images.githubusercontent.com/15998863/32410827-05c54ca6-c205-11e7-956d-169ba0822eb9.PNG)
![client-2](https://user-images.githubusercontent.com/15998863/32410828-075446f8-c205-11e7-8d30-42f72a38a13e.PNG)
![client-3](https://user-images.githubusercontent.com/15998863/32410839-2cce4dde-c205-11e7-9331-642b180ecaea.PNG)
第三张图上图我将V2 kill后，通过终端再次启动，下图可见共存运行。

**Comment by wansen** [comment]
如果需要，我可以将个人信息屏蔽后，贴出我的VPS、手机客户端V2和SS的配置截图，以供你参考。

**Comment by wansen** [comment]
正好看到是你Max Lv的回复，我还有关于ProxyDroid在手机6P8.1上测试的情况一并反馈一下：
之前、现在手机客户端的V2配置均是如下
----------------------------------------------------------------------------------
{
  "inbound": {
    "port": 1080, // 监听端口
    "domainOverride": ["http", "tls"],
    "listen": "127.0.0.10",
    "protocol": "socks", // 入口协议为 SOCKS 5
    "settings": {
      "auth": "noauth" //socks的认证设置,noauth 代表不认证,由于 socks 通常在客户端使用,所以这里不认证
    }
  },
  "inboundDetour": [
    {
    "port": 1088,// 备用监听端口
    "domainOverride": ["http", "tls"],
    "listen": "127.0.0.10",
    "protocol": "http",// 备用入口协议为 http
    "settings": {
      "timeout": 30
      }
    },
    {
    "protocol": "dokodemo-door",// 一个额外的 dokodemo-door 入口协议
    "port": 55555,// 本地端口
    "listen": "127.0.0.10",
    "settings": {
      "address": "xx.xx.xx.xx",// 远程主机的 IP
      "port": 2356,// 远程主机被影射的端口，SS服务端在VPS上的监听端口
      "network": "tcp",// 网络协议，支持"tcp"、"udp"和"tcp,udp"
      "timeout": 15 // 传输超时（秒），0 表示不检测超时
      }
    }
  ],
  "outbound": {
    "protocol": "vmess", // 出口协议
    "tag": "http80",
    "settings": {
      "vnext": [
        {
          "address": "xx.xx.xx.xx", // 
          "port": 8080,  // 服务器端口
          "users": [
            {
              "id": "VPSID",  // 用户 ID,必须与服务器端配置相同
              "alterId": 64, // 此处的值也应当与服务器相同
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "header": {  //这里的 header 要与服务器保持一致
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
	      "Host": ["www.baidu.com"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    },
    "mux": {"enabled": true}
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": null,
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
         "response": {
            "type": "http"  //自动回复 HTTP 403
         }
      },
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs", //"AsIs": 只使用域名进行路由选择。默认值;"IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录）再次进行匹配；
      "rules": [
        {
          "type": "field",
          "domain": [// 要代理的域名
              "dropbox.com",
              "feedly.com",
              "ggpht.com",
              "github.com",
              "rawgithub.com", 
              "google.com",
              "google.com.hk",
              "googleadservices.com",
              "googleapis.com",
              "googlecode.com",
              "googlesyndication.com",
              "googletagmanager.com",
              "googleusercontent.com",
              "googlevideo.com",
              "googlezip.net",
              "gstatic.com",
              "inkstream.org",
              "paypal.com",
              "twimg.com",
              "twitter.com",
              "wikimedia.org",
              "wikipedia.org",
              "youtube.com",
              "ytimg.com"
            ],
          "outboundTag": "http80"
        }
      ]
    }
  }
}
----------------------------------------------------------------------------------
win10上配置也基本相同，都可正常使用。

通过以上配置，我在手机端开了一个sock1080、http1088端口（V2的sock端口很多软件都好像不能使用，所在得再开一个http端口）、映射了VPS上SS的监听端口2356到手机55555端口。

设置ProxyDroid通过127.0.0.10:1088访问网络，本来如果ProxyDroid正常在6p8.1上运行，就不用使用SS客房端通过映射的55555端口来联网，可是ProxyDroid运行不正常：

首先，对本地PAC文件支持不行，可以正常设置，但会导致DNS解析失败，也谈不上内、外分流。
其次，只有上述配置内“// 要代理的域名”可以联网，其它的均失败，开始我以为是V2的问题，向V2提出了反馈（https://github.com/v2ray/v2ray-core/issues/674），经过多次测试，发现还是ProxyDroid的问题。
第三，ProxyDroid支持的直连IP个数好像为不超过2000个，我测试了3000个，结果导入失败，2000个以内没问题。

我的思路是：如果ProxyDroid可以正常使用上述功能，断网也像shadowsocks客户端一样不断开，则完全没必要通过V2映射端口来给SS做代理，这样岂不是更完美些。

知道跑题了，请Max Lv你见谅！非常感谢你的回复！

**Comment by wansen** [comment]
**正好看到是你Max Lv的回复，我还有关于ProxyDroid在手机6P8.1上测试的情况一并反馈一下：
之前、现在手机客户端的V2配置均是如下
----------------------------------------------------------------------------------
{
  "inbound": {
    "port": 1080, // 监听端口
    "domainOverride": ["http", "tls"],
    "listen": "127.0.0.10",
    "protocol": "socks", // 入口协议为 SOCKS 5
    "settings": {
      "auth": "noauth" //socks的认证设置,noauth 代表不认证,由于 socks 通常在客户端使用,所以这里不认证
    }
  },
  "inboundDetour": [
    {
    "port": 1088,// 备用监听端口
    "domainOverride": ["http", "tls"],
    "listen": "127.0.0.10",
    "protocol": "http",// 备用入口协议为 http
    "settings": {
      "timeout": 30
      }
    },
    {
    "protocol": "dokodemo-door",// 一个额外的 dokodemo-door 入口协议
    "port": 55555,// 本地端口
    "listen": "127.0.0.10",
    "settings": {
      "address": "xx.xx.xx.xx",// 远程主机的 IP
      "port": 2356,// 远程主机被影射的端口，SS服务端在VPS上的监听端口
      "network": "tcp",// 网络协议，支持"tcp"、"udp"和"tcp,udp"
      "timeout": 15 // 传输超时（秒），0 表示不检测超时
      }
    }
  ],
  "outbound": {
    "protocol": "vmess", // 出口协议
    "tag": "http80",
    "settings": {
      "vnext": [
        {
          "address": "xx.xx.xx.xx", // 
          "port": 8080,  // 服务器端口
          "users": [
            {
              "id": "VPSID",  // 用户 ID,必须与服务器端配置相同
              "alterId": 64, // 此处的值也应当与服务器相同
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "header": {  //这里的 header 要与服务器保持一致
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
	      "Host": ["www.baidu.com"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    },
    "mux": {"enabled": true}
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": null,
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
         "response": {
            "type": "http"  //自动回复 HTTP 403
         }
      },
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs", //"AsIs": 只使用域名进行路由选择。默认值;"IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录）再次进行匹配；
      "rules": [
        {
          "type": "field",
          "domain": [// 要代理的域名
              "dropbox.com",
              "feedly.com",
              "ggpht.com",
              "github.com",
              "rawgithub.com", 
              "google.com",
              "google.com.hk",
              "googleadservices.com",
              "googleapis.com",
              "googlecode.com",
              "googlesyndication.com",
              "googletagmanager.com",
              "googleusercontent.com",
              "googlevideo.com",
              "googlezip.net",
              "gstatic.com",
              "inkstream.org",
              "paypal.com",
              "twimg.com",
              "twitter.com",
              "wikimedia.org",
              "wikipedia.org",
              "youtube.com",
              "ytimg.com"
            ],
          "outboundTag": "http80"
        }
      ]
    }
  }
}
----------------------------------------------------------------------------------**
win10上配置也基本相同，都可正常使用。

通过以上配置，我在手机端开了一个sock1080、http1088端口（V2的sock端口很多软件都好像不能使用，所在得再开一个http端口）、映射了VPS上SS的监听端口2356到手机55555端口。

设置ProxyDroid通过127.0.0.10:1088访问网络，本来如果ProxyDroid正常在6p8.1上运行，就不用使用SS客房端通过映射的55555端口来联网，可是ProxyDroid运行不正常：

首先，对本地PAC文件支持不行，可以正常设置，但会导致DNS解析失败，也谈不上内、外分流。
其次，只有上述配置内“// 要代理的域名”可以联网，其它的均失败，开始我以为是V2的问题，向V2提出了反馈（https://github.com/v2ray/v2ray-core/issues/674），经过多次测试，发现还是ProxyDroid的问题。
第三，ProxyDroid支持的直连IP个数好像为不超过2000个，我测试了3000个，结果导入失败，2000个以内没问题。

我的思路是：如果ProxyDroid可以正常使用上述功能，断网也像shadowsocks客户端一样不断开，则完全没必要通过V2映射端口来给SS做代理，这样岂不是更完美些。

知道跑题了，请Max Lv你见谅！非常感谢你的回复！

**Comment by madeye** [comment]
NAT mode has been deprecated for years. Mix NAT mode with VPN service should be problematic.

**Comment by wansen** [comment]
你是指的shadowsocks客户端自身的问题，是吗？谢谢！

**Comment by madeye** [comment]
Not sure. We don't provide any support for NAT mode actually.
