### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by Rabbit1623** [shadowsocks/shadowsocks-android#1439]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [X] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [X] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [X] TCP Fast Open
* [ ] NAT mode

### What did you do?
My phone is galaxy note 8. I can't start service on my device. Everytime when I tap the connection bottom, it's automatically switched off and disconnected. It seems like something block the connection. I have allowed all permissions, and have already turn off battery saver. Wiped app datas several times. But useless. I tried other vpns, they show same issue.
Is it something wrong in my settings? On something settings needs to change on note 8? 
Please help.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1410#issuecomment-336786972

**Comment by madeye** [comment]
> I tried other vpns, they show same issue.

So, I don't think your issue is related to shadowsocks.

**Comment by Rabbit1623** [comment]
> So, I don't think your issue is related to shadowsocks.
 @Mygod Mygod closed this 27 days ago

yes, it seems like not the SS issue. And I found why on my new update of SS, it shows permission denied to create a VPN service. I allow all permission with my SS. Maybe something wrong with my phone.

**Comment by evenardo** [comment]
I also got this problem today , but I have a solution seems PRECISE :

SETTINGS -> GENERAL MANAGEMENT -> Reset -> Reset network settings

Take a deep breath , this is very important . Hands together , or be fail !

The Free World come back !!!

**Comment by Rabbit1623** [comment]
I solved it. my mobile phone have two notifications on the state bar. one from SS, another from system. when I disconnected with system's, the vpn will never be reconnected. But, if I tap SS toggles from state bar, all the things going well.

**Comment by z279** [comment]
Editar
Point-to-point
Peer-to-peer
