### ISSUE TITLE
GWF 截断SS之后，SS何时能升级？建议捐赠或者众筹模式，分担开发费用。开启新一代翻墙模式。

### ISSUE THREAD

**Issue by wulongji2016** [shadowsocks/shadowsocks-android#1443]
GFW升级可以识别SS之后，SS何时能升级？魔高一丈道高一丈。
从以前的封IP，到DNS污染，到流量特征识别，防火墙不断进步。
翻墙方式也不断变化，现在该是再次升级的时候了。

建议大家捐赠或者众筹模式，分担开发费用。开启新一代翻墙模式。
新版软件，依然开源，个人用户免费使用。开启官方捐赠通道。
针对企业用户（支持多用户登录和管理），可以考虑按月收费模式，给开发者以适当回报，带来良性循环。（收费账号可以使用国外账号，或者比特币，国内账号不行。）
开发者，个人使用者，企业使用者，各个方面做得利益均衡。促进翻墙技术随时升级和改进。

**Comment by wulongji2016** [comment]
一面是有资金，有技术，有政策支持的。
一面是无资金，无技术，无政策支持的散沙大众。
这个局，怎么破？

**Comment by wulongji2016** [comment]
很多企业，需要联系国外客户，各种软件无法使用，都影响正常外贸了。防火墙防止政治目的的翻墙，但是不应该禁止外贸正常使用吧？ 一刀切。不分青红皂白。
VPN还是需要白名单才能用。和大清朝禁止与外界来往一样开倒车。
不搞政治的学术研究和外贸应该有区别对待。

**Comment by Mygod** [comment]
Keep the default configuration and click ads to help @madeye earn ad revenue.
