### ISSUE TITLE
Remove option to disable IPv6 route?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1447]
Is it time yet to be future-proof and enable IPv6 route for all cases? Currently it's only used in VPN mode and IPv6 traffic is dropped if it's disabled.

**Comment by madeye** [comment]
My concern is some ROM may have issues with IPv6 enabled, e.g. Chinese AOSP forks.

**Comment by Mygod** [comment]
How about moving it to a global option?

**Comment by madeye** [comment]
@Mygod Yes, it's doable.

**Comment by Mygod** [comment]
Oh it seems like a more serious issue is #275. Maybe we should do an IPv6 connection check first via socks5?
