### ISSUE TITLE
Sometimes no speed.

### ISSUE THREAD

**Issue by MPaperPlane** [shadowsocks/shadowsocks-android#1448]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.1.1", 
* Device: *samsung note8*
* Shadowsocks version: *version code "v4.2.5" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration
设置好以后，大部分时间使用正常。有时会出现连接以后上下行都没有速度，测速失败，但我的线路和网络都是正常的。把进程杀掉等一会又会好。

Most of time SS runs properly. But it will happen sometimes there is no speed up or down. While my network and VPN profile are all accessible.

**Comment by madeye** [comment]
It's a known issue of Samsung Galaxy Note 8.

Report it to Samsung or try any AOSP ROM.

**Comment by Mygod** [comment]
Please read FAQ. #1410
