### ISSUE TITLE
By QRCode scanning, new created profile's name was truncated with only the first part left.

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-android#1449]
### Environment

* Android version: 6 & 7
* Device: Samsung S6 edge, S8/+
* Shadowsocks version: 4.2.5

### What did you do?

Try to add profile, see below, by scanning QR.

1. **profile details**
  ```json
  {
    "remarks":       "part1 & part2",
    "server":        "127.0.0.1",
    "server_port":   8388,
    "local_address": "::",
    "local_port":    1080,
    "password":      "UvjXG_4gcedRbDyBxTM82g==",
    "method":        "rc4-md5"
  }
  ```

2. **URI translated from profile upper**

  * uri 1

    `ss://cmM0LW1kNTpVdmpYR180Z2NlZFJiRHlCeFRNODJnPT0@127.0.0.1:8388#part1 & part2`

  * uri 2

    `ss://cmM0LW1kNTpVdmpYR180Z2NlZFJiRHlCeFRNODJnPT0@127.0.0.1:8388#part1`

3. **QR codes translated from URI upper**

  * QR code 1

    ![screenshot from 2017-11-11 18 15 52](https://user-images.githubusercontent.com/658250/32688512-fb32f6e6-c70c-11e7-9da7-ed11ad0ca7e6.png)

  * QR code 2

    ![screenshot from 2017-11-11 18 16 09](https://user-images.githubusercontent.com/658250/32688516-0f56c49a-c70d-11e7-8292-876a169759ca.png)

***

Whichever the qrcode I scan, the **shadowsocks-android** only create a profile with name `part1`. The `& part2` is **always truncated**.

I've tried the qr codes with ZXing teams' **Barcode Scanner** from *Google Play*, it **works fine**.

**Comment by madeye** [comment]
I don't think white space is legal in a URI.

**Comment by kimw** [comment]
Yes, you're right. White spaces is not legal in URI, but  legal in profile name.

> SIP002 purposed a new URL schema, following RFC3986:
>
> ```
> SS-URI = "ss://" userinfo "@" hostname ":" port [ "/" ] [ "?" query ] [ "#" fragment ]
> userinfo = websafe-base64-encode-utf8(method  ":" password)
> ```

Currently, the **fragment** is separated by plus `+`, like `Dummy+profile+name`. But it's really weired for a profile name, right?

> The last `/` should be appended if query or fragment is present. Example: `ss://YmYtY2ZiOnRlc3Q@192.168.100.1:8888/?plugin=url-encoded-plugin-argument-value&unsupported-arguments=should-be-ignored#Dummy+profile+name`. This kind of URIs can be parsed by standard libraries provided by most languages.

So, how's about encode the **fragment part** into base64 too? Or ... SIP002 improve is needed?

**Comment by kimw** [comment]
Or, we just support this kind of illegal URI?

**Comment by kimw** [comment]
Or, maybe we can define the plus mark as a translated-white-space?

I mean, the white spaces are translated into `+` in URI. And then, translate back into white space by shadowsocks-android.

**Comment by Mygod** [comment]
Use standard URL encoding schemes for special characters.

**Comment by madeye** [comment]
More specifically, it'd be `%20`
