### ISSUE TITLE
启动后台服务失败:服务名无效

### ISSUE THREAD

**Issue by defare** [shadowsocks/shadowsocks-android#1450]
我用这个提示服务名无效,启动后台服务失败是什么情况,配置里面配置名我没设置

**Comment by Mygod** [comment]
Check your hostname.

**Comment by abcfy2** [comment]
@Mygod 我也是这个问题，使用ipv6的域名就出现“服务名无效”，但是偶尔有非常低的概率又能连接成功，不知道怎么回事。

我本机ipv6域名解析没问题，用浏览器打开`mirrors6.tuna.tsinghua.edu.cn`都没有问题，但是运行ss使用ipv6的域名就报错服务名无效
