### ISSUE TITLE
流量速度计显示的速度始终为 0

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1452]
基于 master 分支的最新代码的 bug：https://github.com/shadowsocks/shadowsocks-android/tree/265ecc04066092665b27e1779b77b1bf404d965f

VPN 模式，连接上去了点测试速度，显示始终为 0.

![rep](https://user-images.githubusercontent.com/4590439/32760741-a5f544fc-c92a-11e7-9b4e-1c1d90200131.png)

EDIT: 忘记把 IP 打码了...

**Comment by pexcn** [comment]
奇怪，现在又可以了...

**Comment by Mygod** [comment]
It seems like a race condition somewhere in `ServiceBoundContext`.

**Comment by pexcn** [comment]
原来真是 bug...

**Comment by madeye** [comment]
I cannot reproduce it locally. Any related change recently? @Mygod

**Comment by Mygod** [comment]
It's very hard to reproduce. I've only seen it like 4 times so far. I might be wrong but it seems to only happen immediately after an update.

**Comment by pexcn** [comment]
@Mygod @madeye 我从旧版本升级上去，Service mode 选择 Proxy only，尝试连接，断开，再选择 Transproxy，尝试连接，断开，最后选择 VPN，连接，测延迟，就能出现这种情况。只出现过一次，后来就没再尝试了

**Comment by Mygod** [comment]
This bug actually has been around longer than I'd like to admit but since it only happens very occasionally I can't fix it.

**Comment by madeye** [comment]
OK, I followed the way described in https://github.com/shadowsocks/shadowsocks-android/issues/1452#issuecomment-345138613 and get it reproduced.

Change to proxy mode -> Connect -> Disconnect -> Change to VPN mode -> Connect -> Reproduced.

**Comment by madeye** [comment]
It looks related to the newly added proxy only mode.

**Comment by pexcn** [comment]
Change to proxy mode -> Connect -> Disconnect -> Change to VPN mode -> Connect -> Reproduced.
然后显示始终 0 kb 的时候，退出应用界面之后重新进入 或 关闭再打开屏幕，就正常显示速度了

**Comment by madeye** [comment]
@pexcn It's because the background service is forced to reconnected again.

**Comment by madeye** [comment]
It'd be a misbehavior of the bandwidth listener's state:

https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/scala/com/github/shadowsocks/ServiceBoundContext.scala#L42

I'll look into it and try some fixes.

**Comment by pexcn** [comment]
谢谢~
