### ISSUE TITLE
Is it possible to share the SS connection in LAN? 

### ISSUE THREAD

**Issue by 2ndMessiah** [shadowsocks/shadowsocks-android#1453]
Does the SS android client support ss connection sharing ? I have an iOS8 device on which the latest version client isn't integrated with some newest cypher patterns to match with my ss service provider's. So I'm thinking about setting one of my obsolete android phones as a proxy forwarding server. 

Is that feasible? Or is there any recommendation that you could share to me to make it? Much obliged.

**Comment by Mygod** [comment]
#639. It's also possible to install a port forwarder if you just want SOCKS5 proxy.
