### ISSUE TITLE
Support for automatic switch according to the network status?

### ISSUE THREAD

**Issue by 2ndMessiah** [shadowsocks/shadowsocks-android#1454]
Idea: Automatically switch the SS connection on when the network is up ( or a specified type of network, e.g, cellular data). And Switch it off when the network is down.

Reason: The RAM management is way too radical in Android 7.0. The ss connection can't receive/send any data after several hours' usage/idle. So if the shadowsocks program or daemon(I don't really know about its background activity) wakes up every time the network is up, the possibilities of such matters would be effectively impaired to a low rate.

Thanks.

**Comment by Mygod** [comment]
#1390. Also I'm not sure what you mean. If there is connectivity changes, your device is already awake anyways.
