### ISSUE TITLE
Don't display installed apps in Per-app Proxy list

### ISSUE THREAD

**Issue by cykai** [shadowsocks/shadowsocks-android#1456]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: Xiaomi Mi 5
* Shadowsocks version: v4.2.5
* Last version that did not exhibit the issue (if applicable): happened after update to MIUI 9 (from Android 6.0 - 7.0)

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Update MIUI 9 (from Android 6.0 - 7.0)

### What did you expect to see?
See all apps in Per-app Proxy list

### What did you see instead?
Only pre-installed apps displayed in Per-app Proxy list, can't see any apps i installed.

**Comment by Mygod** [comment]
This is almost definitely your ROM's fault. Report to your ROM dev instead.
