### ISSUE TITLE
minor improvements

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-android#1458]
Since NDK r16, there are several changes.

1. switch to c++_static

libc++ is out of beta and is now the preferred STL in the NDK. Starting in r17, libc++ is the default STL for CMake and standalone toolchains. If you manually selected a different STL, we strongly encourage you to move to libc++. For more details, see https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html.

2. remove all `-O?` optimization level

Clang now defaults to -Oz instead of -Os. This should reduce generated code size increases compared to GCC.

It means ndk-build already defines the optimization level, no need to override that.

**Comment by wongsyrone** [comment]
Just a hint. It's working well on my side.

**Comment by Mygod** [comment]
> Clang now defaults to -Oz instead of -Os.

Source?

**Comment by wongsyrone** [comment]
https://android.googlesource.com/platform/ndk/+/ndk-release-r16/CHANGELOG.md

**Comment by Mygod** [comment]
These sound good to me.

@madeye What do you think?

**Comment by madeye** [comment]
Please feel free to submit a pull request for these changes.
