### ISSUE TITLE
issue on Android TV

### ISSUE THREAD

**Issue by cgrk** [shadowsocks/shadowsocks-android#1459]
### Environment

* Android version: *7.0.0*
* Device: *Sony BRAVIA X90E*
* Shadowsocks version: *v4.2.5*
* Last version that did not exhibit the issue (if applicable):

### What did you do?

I cannot slide out Shadowsocks' drawer while using remote control on my Android TV so that I can only configure servers.  In addition, Shadowsocks' user interface is unfriendly to TVs.

**Comment by Mygod** [comment]
#762.

Yes we haven't tested this app on Android TV for a while. Meanwhile please use one of the older versions for Android TV. I'm actually planning to migrate this project to kotlin and do Android TV redesign there.

**Comment by cgrk** [comment]
Finally I configured Shadowsocks with Sony's SideView app. There is a mouse emulator inside.
