### ISSUE TITLE
Could you please provide a direct link for downloading apk files on README?

### ISSUE THREAD

**Issue by dqwyy** [shadowsocks/shadowsocks-android#1460]
Hi.

After reading the closed issues such as #1244, #743, #718, #680,  #242 and #13, I found that some people don't know how to download the apk files directly. They are not familiar with GitHub so they don't know where the releases are. Besides, when viewing GitHub repos in mobile version, releases aren't shown.

Therefoer, I recommend to add a direct download link for apk files on README, that will help thoes who doesn't have a Google Play Service or cannot circumvent the GFW. Besides, with the direct link for apk on README, issues like "How can I download the apk" will less show up.

I've made that for you. Here are the codes and preview.

----

```
## Shadowsocks for Android

A [shadowsocks](http://shadowsocks.org) client for Android, written in Scala.

<a href="https://play.google.com/store/apps/details?id=com.github.shadowsocks"><img src="https://play.google.com/intl/en_us/badges/images/generic/en-play-badge.png" height="48"></a><a href="https://github.com/shadowsocks/shadowsocks-android/releases"><img src="https://i.loli.net/2017/11/19/5a111c3ed6e40.png" height="48"></a>
```

----

## Shadowsocks for Android

A [shadowsocks](http://shadowsocks.org) client for Android, written in Scala.

<a href="https://play.google.com/store/apps/details?id=com.github.shadowsocks"><img src="https://play.google.com/intl/en_us/badges/images/generic/en-play-badge.png" height="48"></a><a href="https://github.com/shadowsocks/shadowsocks-android/releases"><img src="https://i.loli.net/2017/11/19/5a111c3ed6e40.png" height="48"></a>

**Comment by Mygod** [comment]
A pull request?

**Comment by dqwyy** [comment]
@Mygod I saw your commit, thanks for your contributions. I think that will help a lot of people.
