### ISSUE TITLE
Permission bugs on MIUI9

### ISSUE THREAD

**Issue by Reformatsky** [shadowsocks/shadowsocks-android#1463]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0 [MIUI 9.7.10.26 | Beta]
* Device: MI 5
* Shadowsocks version: 4.1.8 from Google play
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [*] Client IPv4 availability
* [*] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [*] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route

***** Problem *****
The problem came after miui update, it seems that miui has update the permission access method. Since that update, both old version and new version of software could not work any more (neither ipv4 nor ipv6 works).
Phenomenon: Each time I press start button, there is a notation below the screen written "Fail to connect the remote server: get package uid: Neither user *** nor current process has android permission.INTERACT_ACROSS_USERS."

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1184

**Comment by biodog** [comment]
Seem issue after I rooted and outdated to MIUI 9 eu.
