### ISSUE TITLE
Profile URI doesn't conform to the spec on the official website 

### ISSUE THREAD

**Issue by icodesign** [shadowsocks/shadowsocks-android#1467]
### What did you do?
SS URI is generated on Android client as a format of `ss://BASE64(encryption:password)@host:port`, while per the spec on the official website, the format should be  `ss://BASE64(method:password@hostname:port)` (https://shadowsocks.org/en/config/quick-guide.html)

### What did you expect to see?
The exported URI format should be `ss://BASE64(method:password@hostname:port)` 

### What did you see instead?
The exported URI format is `ss://BASE64(encryption:password)@host:port`

> I don't have proper Android environment ready now. Hope someone can fix it.

**Comment by madeye** [comment]
It's a SIP002 URL scheme: https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html

Currently, shadowsocks-android supports to import both old URI and SIP002 URI, but only export SIP002 URI.

My suggestion is implement SIP002 in your client to keep compatibility and prepare for the further SIP003 plugins.

**Comment by icodesign** [comment]
LGTM. Thanks.
