### ISSUE TITLE
Is it possible to load KCP and OBFS plug-ins at the same time?

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/shadowsocks-android#1468]
I have my own server running shadowsocks-libev with OBFS plugin and KCPTUN stand-alone.
I setup my server running like
shadowsocks -->OBFS: providing SS port
SS port --> KCPTUN: providing KCP port

In my Linux desktop, I setup my client as
KCPTUN-CLIENT --> KCPTUN server port: providing KCP-CLIENT local port
shadowsocks-->OBFS --> KCPTUN-CLIENT local port: providing SS-local port

In my case, I can use OBFS and KCP at the same time.

I'm wondering if shadowsocks-android can run KCP and OBFS plugin at the same time.
Just make KCP connect to server's KCP port, and make OBFS connect to KCP's local port, and SS connects to OBFS's local port.

**Comment by Mygod** [comment]
No point in doing that. If you really want to do that, nobody's stopping you writing a new plugin.
