### ISSUE TITLE
Display Error 

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-android#1469]
### Environment

* Android version: 7.1.1 , O2OS_171031
* Device: OnePlus 5
* Shadowsocks version: v4.3.0
* Last version that did not exhibit the issue (if applicable): v4.2.5

### What did you do?
Upgrade shadowsocks-android from v4.2.5 to v4.3.0 using Google Play Store

### What did you expect to see?
Everything works fine.

### What did you see instead?
Upload transfer data amount display as "1$s":
![screenshot_20171130-192450](https://user-images.githubusercontent.com/9136591/33429077-4b8b773c-d606-11e7-97f8-4e99e173f77e.jpg)

**Comment by Loukky** [comment]
同样的问题
