### ISSUE TITLE
Apply custom rules based on another selected mode

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-android#1470]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2, LineageOS 14.1-20171127-NIGHTLY-bacon
* Device: OnePlus One
* Shadowsocks version: 4.3.0 (Beta)
* Last version that did not exhibit the issue (if applicable): n/a

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:RC4-MD5 
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Some IPs are mistaken as overseas therefore traffic is directed by proxy server when it doesn't have to be. It leads to specific apps reporting 'unstable connection' or 'no connection' at all, thanks to the proxy server unable to access China IPs.
Current implementation of custom rules doesn't provide China IP importing, let alone allowing dynamically updating China IPs. Such outlier IP cannot be forced to be connected directly.
IP in question: 203.208.43.120 (it connects to Google Beijing BGP node when user tries to use Google Translate on Android, **provided DNS forwarding is off**).
### What did you expect to see?
User may manually add custom rules on the basis of a selected mode, with options to exclude (`NOT`) some specific IPs when the list is out-dated.
A way to update China IP list is also appreciated.
### What did you see instead?
N/A

**Comment by HankAviator** [comment]
A workaround is to enable per app proxy, yet I'd like to correct the IP error so this issue may be resolved for good.

**Comment by madeye** [comment]
Try add a remote custom ACL. The app doesn't support any excluding rules.

**Comment by Mygod** [comment]
Actually remote ACL rules are also filtered so that wouldn't work either.
