### ISSUE TITLE
Need more detail configration about transproxy mode

### ISSUE THREAD

**Issue by coolicer** [shadowsocks/shadowsocks-android#1472]
### Environment

* Android version:  "7.0.0"
* Device: *. MEIZU PRO6 PLUS*
* Shadowsocks version:  "v4.3.0" 

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

All apps are blocked by custom script set in AFwall+.

![s71201-124829](https://user-images.githubusercontent.com/811078/33468267-0afaff22-d696-11e7-9201-0f84f113936d.jpg)
![s71201-124835](https://user-images.githubusercontent.com/811078/33468269-0f0bfa76-d696-11e7-83e9-e344b7428ba5.jpg)

**Comment by Mygod** [comment]
It's expected. The default behavior of AFWall+ blocks filtered connections.

**Comment by coolicer** [comment]
@Mygod 
I do know how to set next.

**Comment by Mygod** [comment]
Any route should work.

**Comment by coolicer** [comment]
@Mygod all ?

**Comment by coolicer** [comment]
@Mygod AFwall+设置了custom script，那些应用还要全部勾上吗？

**Comment by coolicer** [comment]
选上之后好像可以 了

**Comment by coolicer** [comment]
开王者荣耀的时候，进不到对战。iptables要怎么设置？

**Comment by daizq** [comment]
@coolicer 进不到王者后来解决了么？

**Comment by coolicer** [comment]
@daizq 把那个游戏的东西加进去就好了
WZRY_UID=`dumpsys package com.tencent.tmgp.sgame | grep userId | cut -d= -f2 - | cut -d' ' -f1 -`
$IPTABLES -t nat -A OUTPUT -m owner --uid-owner $WZRY_UID -j RETURN
