### ISSUE TITLE
4.3.0's traffic usage display error

### ISSUE THREAD

**Issue by GOGOsu** [shadowsocks/shadowsocks-android#1475]
### Environment

* Android version: 7.1.2
* Device: MI 6, custom rom
* Shadowsocks version: v4.3.0
* Last version that did not exhibit the issue (if applicable): v4.2.5

### Configuration
not applicable for this issue.

### What did you do?
update to 4.3.0

### What did you expect to see?
123 KB↑456 KB↓ in server list

### What did you see instead?
1$s↑456 KB↓

**Comment by GOGOsu** [comment]
![screenshot_20171202-151818](https://user-images.githubusercontent.com/8972942/33513072-9b638b02-d776-11e7-834d-854d6fef33f1.png)
partial screenshot attached.

**Comment by Mygod** [comment]
#1469
