### ISSUE TITLE
常驻通知栏网速显示在中文语言环境下有bug.

### ISSUE THREAD

**Issue by iVeego** [shadowsocks/shadowsocks-android#1477]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* OS: H2OS
* Device: Oneplus 3T
* Shadowsocks version: 4.3.0

### Issue
![_20171202220350](https://user-images.githubusercontent.com/15966723/33516417-6632a864-d7ad-11e7-89e1-69048c32bf9f.jpg)

**Comment by summer19940609** [comment]
I have the same problem, oneplus A5000

**Comment by coolicer** [comment]
same too

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/commit/0ae15f61d96add5b8239c868ba091981ee0a6873 这个 commit 应该 fix 了吧？

**Comment by iVeego** [comment]
bug fixed on V4.3.1
