### ISSUE TITLE
Socks5 Proxy Mode Not Working

### ISSUE THREAD

**Issue by aeroxy** [shadowsocks/shadowsocks-android#1480]
I have a local socks5 server running at 127.0.0.1:1080 and I set the password to empty, encryption to whatever (tried all of them), ss local port at 1085, remote 127.0.0.1:1080. Mode set to app specific (chrome), failed to connect (SSL handshake failed or connection closed by peer).

Android 7.0
Samsung S6
Shadowsocks 4.3.0

**Comment by aeroxy** [comment]
oh also tried socks5 mode transparent proxy mode and vpn mode none of which is working

**Comment by Mygod** [comment]
Proxy mode is meant to be used as upstream proxy instead of the opposite. This app can't connect to a SOCKS5 server.
