### ISSUE TITLE
The problem of toggle

### ISSUE THREAD

**Issue by looogy** [shadowsocks/shadowsocks-android#1483]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:  "6.0"
* Device: HUAWEI VNS-AL00
* Shadowsocks version: version code "v4.3.1" 
* Last version that did not exhibit the issue (if applicable):Sorry I do not make sure about it. I get the app from  Google Play Store and I can not see the last version.

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I click the widget named toggle.

### What did you expect to see?
I want to open the shadowsocks service.

### What did you see instead?
It does not respond.
But I can close the shadowsocks service with the widget named toggle.

**Comment by whour** [comment]
see #1481

**Comment by looogy** [comment]
Thank you!And I get
