### ISSUE TITLE
Can't not use VPN mode.

### ISSUE THREAD

**Issue by JJcdomat** [shadowsocks/shadowsocks-android#1484]
在代理模式透明代理都可以ping，但是VPN模式就不可以ping通。很奇怪。

**Comment by Love4Taylor** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/142

**Comment by Mygod** [comment]
Make sure you give Shadowsocks access to VPN in the list of Apps VPN mode.

**Comment by JJcdomat** [comment]
@Love4Taylor  并不只是无法ping。主要是开启VPN后无法上外网。而一些自带proxy的应用如telegram就可以正常使用。应该也是给了VPN权限的。因为有🔑的图标。

**Comment by Mygod** [comment]
Fixed in beta branch.
