### ISSUE TITLE
DNS resolve slowly

### ISSUE THREAD

**Issue by tony1016** [shadowsocks/shadowsocks-android#1485]
### Environment
Android Version:OxygenOs OP3_O2_Open_28 on Android 8.0.0
Deivice:OnePlus 3
Shadowsocks Version: Shadowsocks-libev 3.1.1
### Configuration

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ x] TCP Fast Open
* [ x] Simple Obfs
* If you're not using VPN mode, please supply more details here:

### What did you do?
Normal scene

### What did you expect to see?
Whatever I ss speed is，it should not effect the website in China Mainland.

### What did you see instead?
DNS resolve slow.sometimes even can't resolve the domain in China Mainland.The chrome display "NX_DOMAIN".Sometimes I can open the page when I refresh,sometimes it remains.I lookup the code,and notice that it use 114.114.114.114 to resolve domain in China Mainland,so I don't think "NX DOMAIN" could happen in China Mainland Website.

**Comment by madeye** [comment]
Which ISP are you using?

**Comment by madeye** [comment]
Try the following things:

1. Uninstall and reinstall the APK.
2. When switching to a new network, switching off and on the service.

**Comment by madeye** [comment]
> it use 114.114.114.114 to resolve domain in China Mainland

Not actually, we're using 119.29.29.29, 114.114.114.114 and your local DNS as primary DNS. It's hard to believe you have connection issue to all the three DNS servers.

**Comment by tony1016** [comment]
Really strange.are there some overture log for debug??

**Comment by whour** [comment]
119.29.29.29 do not supprot tcp resolve?
```
dig @119.29.29.29 github.com +tcp
;; Connection to 119.29.29.29#53(119.29.29.29) for github.com failed: connection refused.
$ dig @119.29.29.29 github.com
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.1-P3 <<>> @119.29.29.29 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42157
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             3600    IN      A       203.208.39.99

;; Query time: 1734 msec
;; SERVER: 119.29.29.29#53(119.29.29.29)
;; WHEN: Thu Dec 07 10:06:58 CST 2017
;; MSG SIZE  rcvd: 44

$ dig @114.114.114.114 github.com +tcp

; <<>> DiG 9.11.1-P3 <<>> @114.114.114.114 github.com +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35796
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 0143b5a1f41f9029 (echoed)
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             37      IN      A       192.30.255.112
github.com.             37      IN      A       192.30.255.113

;; Query time: 121 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Thu Dec 07 10:07:26 CST 2017
;; MSG SIZE  rcvd: 83

```

**Comment by tony1016** [comment]
Interesting,I change another ss vps provider，then everything is fine.So I wonder why vps speed can effect local domain resolve??some process  hung up??

**Comment by whour** [comment]
> Not actually, we're using 119.29.29.29, 114.114.114.114 and your local DNS as primary DNS. It's hard to believe you have connection issue to all the three DNS servers.

@madeye 
My ISP is very annoying.  I have problem with visit github.com ,I think maybe on dns side.
```
$ dig @127.0.0.1 -p5450 github.com

; <<>> DiG 9.11.1-P3 <<>> @127.0.0.1 -p5450 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52576
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 8, ADDITIONAL: 8

;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             3600    IN      A       203.208.39.99

;; AUTHORITY SECTION:
github.com.             169117  IN      NS      ns-1707.awsdns-21.co.uk.
github.com.             169117  IN      NS      ns-520.awsdns-01.net.
github.com.             169117  IN      NS      ns3.p16.dynect.net.
github.com.             169117  IN      NS      ns-421.awsdns-52.com.
github.com.             169117  IN      NS      ns-1283.awsdns-32.org.
github.com.             169117  IN      NS      ns4.p16.dynect.net.
github.com.             169117  IN      NS      ns2.p16.dynect.net.
github.com.             169117  IN      NS      ns1.p16.dynect.net.

;; ADDITIONAL SECTION:
ns1.p16.dynect.net.     81009   IN      A       208.78.70.16
ns2.p16.dynect.net.     3144    IN      A       204.13.250.16
ns3.p16.dynect.net.     66491   IN      A       208.78.7
ns4.p16.dynect.net.     85971   IN      A       204.13.251.16
ns-421.awsdns-52.com.   3941    IN      A       205.251.193.165
ns-520.awsdns-01.net.   80413   IN      A       205.251.194.8
ns-1283.awsdns-32.org.  77133   IN      A       205.251.197.3
ns-1707.awsdns-21.co.uk. 76565  IN      A       205.251.198.171

;; Query time: 5 msec
;; SERVER: 127.0.0.1#5450(127.0.0.1)
;; WHEN: Fri Dec 08 16:58:39 CST 2017
;; MSG SIZE  rcvd: 392
```
This is releases 4.3.2 resolve result ,onle thie version  return error ip.
V4.3.1 and V4.3.0 resolve correct.
You can try this 
```
dig @61.128.114.133 github.com

; <<>> DiG 9.11.2 <<>> @61.128.114.133 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17824
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		3332	IN	A	203.208.39.104

;; Query time: 3 msec
;; SERVER: 61.128.114.133#53(61.128.114.133)
;; WHEN: 五 12月 08 17:16:26 CST 2017
;; MSG SIZE  rcvd: 55
```
Maybe wo should check overture configuration.

**Comment by madeye** [comment]
If It's a ISP specific issue, i suggest enabling DNS forwarding instead.

**Comment by whour** [comment]
remove ISP dns,define dns  119.29.29.29 and  enable edns configure ExternalIP ?

**Comment by madeye** [comment]
There is a DNS forwarding option in your profile. Just enable it.

**Comment by whour** [comment]
Thanks for you time. I just enable DNS forwarding option. F**King ISP.
