### ISSUE TITLE
Notification importance shows 'medium' And appears in Notification bar

### ISSUE THREAD

**Issue by LvWind** [shadowsocks/shadowsocks-android#1486]
<img width="328" alt="1" src="https://user-images.githubusercontent.com/280190/33641062-f8ba423c-da6e-11e7-99f0-3aaaf242e79d.png">
I updated my 5X to 8.1.0 release version today, the 'VPN Service' Notification channel importance is 'Medium'. 
Changing it to 'Low', the notification is as invisible as before.

### Environment

* Android version: "8.1.0 opm1.171019.011"
* Device: Nexus 5X
* Shadowsocks version: 4.2.5

**Comment by madeye** [comment]
Tried it locally. It works well.

**Comment by Mygod** [comment]
This is the new default behavior to avoid showing the background notification by Android system in Android 8.0. Please change it manually if you don't like this behavior.

**Comment by LvWind** [comment]
Well, at least we can change it manually :）
