### ISSUE TITLE
Google Translate app cannot connect to the internet with Bypass LAN & China route

### ISSUE THREAD

**Issue by iKirby** [shadowsocks/shadowsocks-android#1488]
### Environment

* Android version: 8.1.0 Developer Preview 2 (OPP6.171019.012)
* Device: Google Pixel
* Shadowsocks version: v4.3.2
* Last version that did not exhibit the issue (if applicable): forgot, may be 4.3.0 or 4.2.5

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Setup shadowsocks and use Google services. For this issue, the Google Translate app.

### What did you expect to see?
Google Translate app shows translate result correctly.

### What did you see instead?
Google Translate app can't connect to the internet with Bypass LAN & China route.
It shows a progress bar infinitely, or fallback to offline translate if a offline language package is installed.

Also tried GFW List route, the same as above. But with Bypass LAN route, Translate app works flawlessly.
The web version `translate.google.com` is not affected.

**Comment by whour** [comment]
Maybe you can try custom rules .
-  https://raw.githubusercontent.com/shadowsocks/shadowsocks-android/master/mobile/src/main/assets/acl/bypass-lan-china.acl
- https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl


or add a line  translate.google.com

**Comment by iKirby** [comment]
@whour `translate.google.com` is not affected by this issue, only the app.

**Comment by whour** [comment]
@iKirby  I have installed the Google Translate App,working fine.
BTW,I'm using the Apps vpn mode,selected the Translate App,using custom rules.

**Comment by iKirby** [comment]
After lots of testing I finally found the problem.
Google translate app connects to `translate.google.cn` even when proxy is on. Shadowsocks-android uses local DNS so it gets IPs of Google servers located in China. But my server can't connect to those IPs, causing no internet for Google Translate app. When DNS forwarding is on, it works without problem.
