### ISSUE TITLE
重置按钮没有了

### ISSUE THREAD

**Issue by ayanamist** [shadowsocks/shadowsocks-android#1490]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Xiaomi 6
* Shadowsocks version: 4.3.2
* Last version that did not exhibit the issue (if applicable):

左侧边的“重置”按钮没了，不小心在root环境把acl文件全部删除后，无法恢复了

![image](https://user-images.githubusercontent.com/406779/33751198-4dbf1f72-dc14-11e7-9026-ea7ea0a0b4b2.png)

**Comment by Mygod** [comment]
Don't mess with this apps data if you don't know how to fix it.

**Comment by ayanamist** [comment]
FAQ里第二条还提到了这个Reset，应该不是刻意去掉的吧？

**Comment by Mygod** [comment]
It's fully intentional. It's been removed along with NAT mode. Thanks for pointing that out.

**Comment by Mygod** [comment]
And also for your problem, you can reinstall the apk.
