### ISSUE TITLE
LineageOS 14.1 lost all connections after using for a while

### ISSUE THREAD

**Issue by Tevic** [shadowsocks/shadowsocks-android#1492]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: LineageOS 14.1-20171204 Android 7.1.2
* Device: Xiaomi Mi4W
* Shadowsocks version: 4.3.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you see?
Connect via shadowsocks,all work fine,after using for a while(maybe several miniutes or hours),all connection lost,can't connect any website include websites in China. I should restart shadowsocks to revive internet connection.

Logcat:
12-10 19:52:58.241 23730 23730 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 9 lines
12-10 19:53:05.099 23749 23749 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/libtun2socks.so expire 8 lines
12-10 19:53:09.851 23730 23779 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 18 lines
12-10 19:53:12.357 23730 23782 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 17 lines
12-10 19:53:18.538 23730 23785 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 8 lines
12-10 19:53:18.878 23730 23788 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 4 lines
12-10 19:53:22.366 23730 23784 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 16 lines
12-10 19:53:26.300 23730 23790 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 4 lines
12-10 19:53:26.940 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 23 lines
12-10 19:53:26.941 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 18 lines
12-10 19:53:38.896 23730 28000 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 13 lines
12-10 19:53:43.260 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 4 lines
12-10 19:53:45.180 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 5 lines
12-10 19:53:46.380 23730 23782 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 14 lines
12-10 19:53:46.380 23730 28000 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 1 line
12-10 19:53:47.020 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 7 lines
12-10 19:53:47.020 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 10 lines
12-10 19:53:47.609 23730 23784 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 12 lines
12-10 19:53:56.380 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 18 lines
12-10 19:53:56.380 23730 23782 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 23 lines
12-10 19:53:57.020 23730 28000 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 9 lines
12-10 19:54:00.221 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 14 lines
12-10 19:54:05.100 23730 23784 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 12 lines
12-10 19:54:05.181 23749 23749 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/libtun2socks.so expire 4 lines
12-10 19:54:15.100 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 15 lines
12-10 19:54:20.220 23730 23790 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 15 lines
12-10 19:54:28.220 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 6 lines
12-10 19:54:30.540 23730 23790 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 6 lines
12-10 19:54:32.060 23730 23771 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 9 lines
12-10 19:54:35.740 23730 23786 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 2 lines
12-10 19:54:36.460 23730 23782 I chatty  : uid=10077(com.github.shadowsocks) /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so expire 5 lines
12-10 19:57:19.220  5455 29296 W System.err: java.net.UnknownHostException: Unable to resolve host "shadowsocks.org": No address associated with hostname
12-10 19:57:19.222  5455 29296 W System.err:    at com.github.shadowsocks.acl.AclSyncJob.onRunJob(AclSyncJob.scala:53)
12-10 19:58:31.445  5455 29296 W System.err: java.net.UnknownHostException: Unable to resolve host "shadowsocks.org": No address associated with hostname
12-10 19:58:31.446  5455 29296 W System.err:    at com.github.shadowsocks.acl.AclSyncJob.onRunJob(AclSyncJob.scala:53)
12-10 20:00:23.590  5455 30327 W System.err: java.net.UnknownHostException: Unable to resolve host "shadowsocks.org": No address associated with hostname
12-10 20:00:23.592  5455 30327 W System.err:    at com.github.shadowsocks.acl.AclSyncJob.onRunJob(AclSyncJob.scala:53)
12-10 20:04:06.464  5455 31162 W System.err: java.net.UnknownHostException: Unable to resolve host "shadowsocks.org": No address associated with hostname
12-10 20:04:06.471  5455 31162 W System.err:    at com.github.shadowsocks.acl.AclSyncJob.onRunJob(AclSyncJob.scala:53)

ProcessInfo:
./adb shell ps | grep shadowsocks
u0_a77    5455  478   1070712 62136 sys_epoll_ 00000000 S com.github.shadowsocks:bg
u0_a77    23724 5455  5496   2568  sys_epoll_ 00000000 S /data/app/com.github.shadowsocks-2/lib/arm/libss-local.so
u0_a77    23730 5455  855460 16140 futex_wait 00000000 S /data/app/com.github.shadowsocks-2/lib/arm/liboverture.so
u0_a77    23749 5455  5900   3076  sys_epoll_ 00000000 S /data/app/com.github.shadowsocks-2/lib/arm/libtun2socks.so

**Comment by madeye** [comment]
Try this APK: https://www.dropbox.com/s/yalz5oo0sdtp7v8/shadowsocks-nightly-4.4.0.apk

**Comment by Tevic** [comment]
Thanks, i'll test it and feedback.

**Comment by Tevic** [comment]
Problem still exists in new APK.

**Comment by madeye** [comment]
It looks a socket system corruption like what we are observing on Galaxy Note 8.

Post the output of `adb logcat -s overture ShadowsocksVpnThread` when the connection is lost.

**Comment by Tevic** [comment]
Lots of logs like:
12-11 12:44:35.766 29467 29494 I overture: time="2017-12-11T04:44:35Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:45:23.765 29467 29494 I overture: time="2017-12-11T04:45:23Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:45:28.725 29467 29494 I overture: time="2017-12-11T04:45:28Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:45:33.765 29467 29494 I overture: time="2017-12-11T04:45:33Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:45:43.765 29467 29494 I overture: time="2017-12-11T04:45:43Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:47:04.797 29467 29467 I overture: time="2017-12-11T04:47:04Z" level=warning msg="Dial DNS upstream failed: dial udp 119.29.29.29:53: connect: network is unreachable"
12-11 12:47:04.797 29467  8901 I overture: time="2017-12-11T04:47:04Z" level=warning msg="Dial DNS upstream failed: dial udp 114.114.114.114:53: connect: network is unreachable"
12-11 12:47:04.797 29467  8901 I overture: time="2017-12-11T04:47:04Z" level=warning msg="Dial DNS upstream failed: dial udp 114.114.114.114:53: connect: network is unreachable"
12-11 12:47:18.890 29467 29561 I overture: time="2017-12-11T04:47:18Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:47:23.931 29467 29507 I overture: time="2017-12-11T04:47:23Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:47:27.770 29467 29507 I overture: time="2017-12-11T04:47:27Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"
12-11 12:47:27.771 29467 29493 I overture: time="2017-12-11T04:47:27Z" level=warning msg="Dial DNS upstream with SOCKS5 proxy failed: dial tcp 127.0.0.1:1080: getsockopt: connection timed out"

**Comment by madeye** [comment]
```
12-11 12:47:04.797 29467 29467 I overture: time="2017-12-11T04:47:04Z" level=warning msg="Dial DNS upstream failed: dial udp 119.29.29.29:53: connect: network is unreachable"
```

It looks your ROM disabled the background traffic from shadowsocks, causing networking issue. So, double check your ROM's configs or report it your ROM's maintainer.

**Comment by Tevic** [comment]
Could take a look if this problem is related to these two commits, so i can post a issue t them or you can figure out some methods for this situation.
https://review.lineageos.org/#/c/196562/
https://review.lineageos.org/#/c/196563/

**Comment by madeye** [comment]
Could you confirm that your problem only happens when switching from 4G to WiFi or Wifi to 4G?

**Comment by Tevic** [comment]
No,it will happen even if i'm browsering,connection suddenly lost.

**Comment by lanxianhui** [comment]
I also encountered the same problem.When auto switching from 4G to WiFi or Wifi to 4G，or 4G signal recovery,the probability of this problem occurring is high.
Environmentwhen 
Android version: MK71.2-cherry-201712120429-NIGHTLY.zip Android 7.1.2
Device: Huawei Honor 4X
Shadowsocks version: 4.3.3

**Comment by madeye** [comment]
It looks LineageOS's fault. Please submit an issue to them.
