### ISSUE TITLE
No longer works with island

### ISSUE THREAD

**Issue by zzj0311** [shadowsocks/shadowsocks-android#1494]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *6.0.1*
* Device: *Google Nexis 6p*
* Shadowsocks version: *version code 4.3.2*
* Last version that did not exhibit the issue (if applicable):
Before the Nat mode removed I think
### Configuration

_Put an `x` inside the [ ] that applies._

* [X] IPv4 server address
* [X] IPv6 server address
* [X] Client IPv4 availability
* [X] Client IPv6 availability
* Encrypt method:aes256cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [X] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Shadowsocks works well in the mainland but can't pass the connection test when it connected in island

### What did you expect to see?
Traffic goes through ss in island 

### What did you see instead?
Can not get access to blocked sites

**Comment by madeye** [comment]
Tried locally. everything works well.
