### ISSUE TITLE
求教怎么才能像lantern那样只代理墙外流量？

### ISSUE THREAD

**Issue by kinoph** [shadowsocks/shadowsocks-android#1498]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
默认代理全局流量的，打开大陆网站比较慢。
尝试绕过”中国大陆网址“或者”分应用代理"都连接失败了！
### What did you expect to see?

那位大神告诉我只代理墙外流量的办法

**Comment by joviqiao** [comment]
绕过大陆啊  这应该没有问题吧、、

**Comment by Mygod** [comment]
Need more info.

**Comment by pexcn** [comment]
关闭 DNS 转发试试
