### ISSUE TITLE
按 app short cut 会卡住，不会断开或重连vpn

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1499]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android 8.1.0 ""OPM1.171019.011"
* Device: nexus 6p
* Shadowsocks version: 4.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Apps VPN mode
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
长按图标，按“开关”

### What did you expect to see?
成功开关

### What did you see instead?
桌面定住了，不会断开或者重连vpn。

**Comment by madeye** [comment]
Fixed via 956443ef
