### ISSUE TITLE
Facebook/Messenger Cannot Login

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/shadowsocks-android#1504]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
8.0.0
* Device: *e.g. Google Pixel XL*
Huawei Mate 9/10
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
v4.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Open Facebook/Messenger

### What did you expect to see?
Facebook/Messenger login

### What did you see instead?
Both apps report "Cannot connect, check your network"

**Comment by madeye** [comment]
Try disable IPv6.
