### ISSUE TITLE
connection closed by peer

### ISSUE THREAD

**Issue by pongfcnkl** [shadowsocks/shadowsocks-android#1509]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*4.4.4
* Device: *e.g. Google Pixel XL*酷派8712
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*4.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):obfs
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
ss账号没问题，windows版C#都能翻，就是安卓版无法翻，同个网络下。
这两个是测速截图
![d](https://user-images.githubusercontent.com/24273319/34069815-c81e7f12-e293-11e7-891f-c7814c2e4f06.png)

![qq 20171216190147](https://user-images.githubusercontent.com/24273319/34069816-d5242108-e293-11e7-9c41-6595c1008439.png)

**Comment by coolguy001tv** [comment]
Same question. Besides, Mac's wrong too.
