### ISSUE TITLE
Google Photos and Google Play store not recognizing WiFi connections anymore

### ISSUE THREAD

**Issue by frankxu2004** [shadowsocks/shadowsocks-android#1510]
### Environment

* Android version:  8.1.0
* Device: Google Pixel 2
* Shadowsocks version: v4.2.5 from Google Play Store

### Configuration

* [ x ] IPv4 server address
* [ ] IPv6 server address
* [ x ] Client IPv4 availability
* [ x ] Client IPv6 availability
* Encrypt method: chacha20-ietf
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Connected to shadowsocks, everything works fine, except that the Google Photos app says it needs to wait for WiFi connection to auto backup the photos. When disconnected from Shadowsocks app, it works perfectly. 

### What did you expect to see?
Shadowsocks shouldn't hinder the ability of WiFi connection detection.

### What did you see instead?
 Google Photos app says it needs to wait for WiFi connection to auto backup the photos, while I am connected to WiFi

**Comment by Love4Taylor** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1501

**Comment by BH1ENO** [comment]
Duplicate
