### ISSUE TITLE
Cannot auto connect

### ISSUE THREAD

**Issue by zfk513** [shadowsocks/shadowsocks-android#1513]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:  "5.1", more detailed description is preferred*
* Device: 大神note3
* Shadowsocks version: *version code "v4.2.5 V4.3.3 v4.4.1
* Last version that did not exhibit the issue (if applicable): still exist

### Configuration

_normal

### What did you do?
set auto connect 

### What did you expect to see?
when it start ,it can be auto connect

### What did you see instead?

it struggle to show some orange line around the circle,but fail to connect

**Comment by Mygod** [comment]
Try grabbing a logcat, preferably for 4.4.1.
