### ISSUE TITLE
手机版无法连接ipv6地址的服务器，电脑却可以

### ISSUE THREAD

**Issue by techstay** [shadowsocks/shadowsocks-android#1514]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android 7.0 (miui 9)
* Device: xiaomi 5
* Shadowsocks version: v4.2.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [x] IPv6 server address
* [ ] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:AES-256-CFB
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
原来我用的好好的，ss和kcptun都没问题，后来十九大那几天我的搬瓦工就不能用了，我还以为例行公事，结果ip从此封到现在。今天突然想起来搬瓦工不是还有ipv6的地址么，于是我试了试发现ipv6的还能用，但是手机版ss就无法连接了，电脑端.NET版的ss倒是完全正常。手机端中那几个选项我来回都试了试，结果发现好像没啥用，手机端始终无法连接。手机端配置应该是没问题的，因为是从电脑端二维码上扫来的，所以来求教一下如何解决……如果开发者有需要的话我还可以私信发一下我的二维码，不过我不确定是否有用

**Comment by henryhwang** [comment]
我也遇到一模一样的问题！哪位大师帮忙

**Comment by madeye** [comment]
There is a known issue of shadowsocks-windows' IPv6 URL generator: https://github.com/shadowsocks/shadowsocks-android/issues/1519.
