### ISSUE TITLE
无法添加 ipv6 带 plugin 的 SS URL

### ISSUE THREAD

**Issue by zmz125000** [shadowsocks/shadowsocks-android#1519]
### Environment
*Android version: 8.1
*Shadowsocks version: 4.4.1
*Shadowsocks version: 4.3.3

### Configuration
* [x] IPv6 server address

### What did you do?
用扫码（稳定版调用扫码 app、beta 版自带扫码）和粘贴板添加 ipv6 带 plugin (obfs-local) 的 SS URL
如：
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTphc2RmYXNkZmFzZGY@53d3%3a72da%3a72a0%3ac77d%3afa3%3a80b2%3a96c4%3aa7db:443/?plugin=obfs-local%3bobfs%3dtls%3bobfs-host%3dwww.baidu.com#aaaaa

不带 plugin 成功
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTphc2RmYXNkZmFzZGZANTNkMzo3MmRhOjcyYTA6Yzc3ZDpmYTM6ODBiMjo5NmM0OmE3ZGI6NDQz#aaaaa

### What did you expect to see?
添加成功

### What did you see instead?
用粘贴板添加显示 failed to import
扫码添加后应用崩溃
把 ip 换成 ipv4 后添加成功（带的 plugin 信息也添加了）

**Comment by madeye** [comment]
Please don't encode your IP. A valid IPv6 URL looks like

ss://YWVzLTI1Ni1jZmI6dTFyUldUc3NOdjBw@[2001:4860:0:2001::68]:8388?plugin=obfs-local%3Bobfs%3Dhttp

**Comment by zmz125000** [comment]
看来是 shadowsocks-windows 转出来的 url 有问题
