### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by 967018** [shadowsocks/shadowsocks-android#1520]
These suggestions are based on @Mygod 's [last comment](https://github.com/shadowsocks/shadowsocks-android/issues/762) which mostly depended on Android Support Library or third-party design libraries.

In order to make it easier, some improvements were divided into levels with different difficulty.
**If you would like to participate in this issue, please comment here. I'll interact with you for further specifications of the design.**

_Of course shadowsocks has a [redesign](https://github.com/shadowsocks/shadowsocks-android/issues/762). Hoping someone could implement that._

---

### 0. Navigation bar (!important)
**Problems: Wrong usage of colouring navigation bar.** 
The goal of colouring is to make the visual experience more immersive. Beyond all doubt, the whole interface was smothered without exaggeration.

**Solution: Reset to the default state. Black is just perfect.**

---
### 1. Navigation drawer
**Now:** 

![nav-o](https://user-images.githubusercontent.com/8299251/34301218-9cf4e326-e766-11e7-88d5-c2045282af50.png)

**Problems:** 

1.  Unnecessary image. The guideline doesn't say that it has to be an image there. About 277KB can be saved by removing the hero image.
2.  Unnecessary shadow, having too much complicates the interface and lacks focus. 

**Improved:** 

![nav-u](https://user-images.githubusercontent.com/8299251/34304209-adb9c71e-e773-11e7-9822-bccf9bc30172.png)

---
### 2. Product icon (Legacy & Play Store only)
**Problems: Doesn't follow the guideline completely (Lighting, Shadows, Edge tint and shade).** 

**Solution: I remade a correct one. Here's the [download link](https://drive.google.com/open?id=1KQZz5s3BUlfiDj1Sd2VeDq6Ja3LoWQKy).**

---
### 3. Status panel
In progress.

---
### 4. Floating Action Button
**Now:**
![FAB-o](https://user-images.githubusercontent.com/8299251/34317016-e58077ee-e7df-11e7-8bef-1393b42deace.jpg)

**Problems:** 
1. Floating **ACTION** Button. Now the fab shows the connection state, not the action of our users can do. 
2. The deactivated icon has a too complicated path.

**Improved:** 
![FAB-u](https://user-images.githubusercontent.com/8299251/34317021-f3a0e71e-e7df-11e7-803f-b1a47acef369.jpg)

---

To be continued.

**Comment by Mygod** [comment]
I'm not convinced that these are improvements.

1. Having a secondary toolbar in drawer looks weird. Banner in beta branch uses webp instead which only costs ~100kB in apk size.
2. Yours may be correct but there are at least 2 ways yours is inferior:
  a. No adaptive icon support; (see https://github.com/shadowsocks/shadowsocks-android/pull/1258#issuecomment-315590616)
  b. No vector drawable/svg support.
3. Status panel is helpful in Global Settings fragment so it's more convenient and consistent to just put one everywhere.

**Comment by 967018** [comment]
@Mygod 

1. That is not a toolbar, it's just a coloured block. 
2. Those are only applicable to the legacy icon.
3. Why?

**Comment by Mygod** [comment]
1. It looks like exactly like a Toolbar therefore I will call it a Toolbar;
2. In that case, blame Android studio for not generating good enough legacy icon;
3. You could change settings (including for custom rules) and reapply changes with the status panel.

**Comment by 967018** [comment]
@Mygod 

1. There's no action at all... The block is simple enough to express consistency and well-organized structure.
3. That makes sense.

**Comment by Mygod** [comment]
Oh and about "Wrong usage of colouring navigation bar", source?

**Comment by 967018** [comment]
@Mygod 

The guideline doesn't have a specific description. But the problem here is very clear and reasonable.
Coloured navigation bar doesn't fit the present structure of shadowsocks. It makes navigation bar more conspicuous, as an opposite consequence of "The goal of colouring is to make the visual experience more immersive."

**Comment by Mygod** [comment]
0. In this case, we have a persistent bottom bar that justifies this decision (it's technically a [translucent navigation bar](https://material.io/guidelines/layout/structure.html#structure-system-bars)). And I personally prefer colorful interfaces to boring black navigation bars. Considering Google itself is pretty inconsistent about material design, there are no rights and wrongs on this.
4. The complex path is for the middle state (busy) between connected and disconnected. See the animation in the latest version.

**Comment by Mygod** [comment]
Also may I suggest you open separate issues instead of keeping updating this thread?

**Comment by Mygod** [comment]
I don't see anything needs fixing for now. Please open new issues (separate ones) if you want to keep the conversation going.
