### ISSUE TITLE
从wifi网络转到移动网络时，偶尔会出现所有应用不能访问网络的情况

### ISSUE THREAD

**Issue by adasqg** [shadowsocks/shadowsocks-android#1522]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment
MIUI 9 Global 7.12.14 | android 7.0 | mi 5s | shadowsocks@4.25

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
从wifi转换到移动网络

### What did you expect to see?
所有应用能使用网络，并自动代理

### What did you see instead?
偶尔会出现所有应用不能联网，需要手动断开shadowsocks然后在连接shadowsocks才会恢复正常。

**Comment by madeye** [comment]
I think there are some settings in MIUI that restricts shadowsocks' background data usage.

Search the issue tracker for more details.

**Comment by adasqg** [comment]
恩，我试试在智能省电中设置不限制后台，也设置允许后台自启
