### ISSUE TITLE
手机端访问网页正常，但是账号同步有问题

### ISSUE THREAD

**Issue by dc3671** [shadowsocks/shadowsocks-android#1524]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "7.0"
* Device: Samsung S7
* Shadowsocks version: "v4.2.5"

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-CFB
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

谷歌账号同步一直报错（Sync里红叹号），但是只有Calendar和Gmail、Chrome这些有问题，像Contact就没有问题，浏览网页是正常的，gmail、Google都能正常访问。

尝试过各种Route方式，是否开TCP、是否Forward DNS都试过，没有区别。电脑上由于基本也只有Chrome用到ss所以也都是正常的。

其实在刚刷好系统后短暂的一段时间内Calendar和Gmail可以同步，但是后来因为Task同步一直有问题，Gmail同步也有bug（primary和update两个标签能同步，all mails没法同步），所以有尝试切换配置开开关关ss，今天尝试了一下别人说的方法比如升级新版、清缓存，后来gmail就显示no connection了，之后还清了gmail的缓存，还是没效果

另外Route的其他选项似乎有问题，比如GFW List就并不能过滤国内的请求，我在Chrome里开sogou输入ip还是显示ss-Server的IP，在微信里打开sogou输入ip也一样

**Comment by madeye** [comment]
1. Try the latest 4.4.2 version.
2. It could be an issue of your server's IP. It's a known issue that some VPS' IP would get blocked by Google.
