### ISSUE TITLE
Direct boot support

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-android#1525]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2 
* Device: Xiaomi Mi 6 _[sagit]_
* Shadowsocks version: 4.4.2
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: N/A
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Since Nougat, new phones are shipped with ROMs with File-based encryption, which works along with Direct boot. In this boot mode, only apps which are registered with Direct boot is possible to run before user unlocks the screen after boot. Considering shadowsocks is a major app for networking (esp for Gmail and etc.), the proxy has to be running before other apps can gain access to limited network, it might be a good idea to make shadowsocks compatible with direct boot.
Some docs for reference: https://developer.android.com/training/articles/direct-boot.html
### What did you expect to see?
shadowsocks will be compatible with direct boot.
### What did you see instead?
shadowsocks won't run before device boots, even 'Always on VPN' is enabled in VPN system settings.

**Comment by Mygod** [comment]
Did you check direct boot awareness in settings (requires shadowsocks 4.4.2+)? If you can't find it, that means your phone doesn't use FBE.

As for always-on VPN, blame AOSP.

**Comment by HankAviator** [comment]
OMG when did you implement this?! Didn't notice in changelog. 
Works like charm ❤️ 👍

**Comment by Mygod** [comment]
#1457 Always search issue tracker.
