### ISSUE TITLE
v4.4.2 后台服务启动失败：请选择配置文件

### ISSUE THREAD

**Issue by luffyke** [shadowsocks/shadowsocks-android#1526]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: 锤子坚果pro 2
* Shadowsocks version: 4.4.2
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Just install v4.4.2 and import my server config.

### What did you expect to see?
Connect successfully.

### What did you see instead?
后台服务启动失败：请选择配置文件

**Comment by luffyke** [comment]
it's normal for 4.3.3 version.

**Comment by madeye** [comment]
Post a screenshot if possible.

**Comment by Mygod** [comment]
It could be caused by database corruption. Post a logcat if possible.

**Comment by luffyke** [comment]
@madeye @Mygod sorry, i have uninstalled v4.4.2, and install 4.3.3, it's expected now.

**Comment by luffyke** [comment]
And i do the same action for 4.3.3 and 4.4.2

**Comment by whour** [comment]
## Just click you profile.
![screenshot_20171225-170748__01](https://user-images.githubusercontent.com/4928187/34337109-c064668c-e997-11e7-95c0-1e56df0d22ba.jpg)
![screenshot_20171225-170908__01](https://user-images.githubusercontent.com/4928187/34337115-cba31124-e997-11e7-9bc9-d25683d3489e.jpg)

**Comment by luffyke** [comment]
@whour i have clicked

**Comment by iKirby** [comment]
After updating from 4.4.1, the profile selected before was unselected, so you need to select it again manually before connecting.

**Comment by luffyke** [comment]
@iKirby i'm confirm that i have selected profile.

**Comment by airycanon** [comment]
Same issue here.

Android version: 7.0.0
Device: Mezu Pro6 plus
Shadowsocks version: 4.4.3

**Comment by Windsmild** [comment]
4.4.4 小米
同样的问题
发现是直接升级的安装会有问题,把原来已安装的ss删掉,再重新安装就好了

**Comment by airycanon** [comment]
@Windsmild 我删除旧版重新安装仍然是同样的问题。

**Comment by isxiao** [comment]
Same issue here.

Android version: 7.0.0
Device: Meizu Pro6 plus
Shadowsocks version: 4.4.5

**Comment by luffyke** [comment]
我昨天拿了一台原来装了shadowsocks-android旧版的手机，然后下载4.4.5的apk安装（系统会替换掉原来的app），这样的安装方式导致上述错误，没有调用系统提示会打开VPN的提示框。
然后我把4.4.5卸载，重装（这时候的安装是原来手机没有存在shadowsocks-android旧包），又回归正常（系统提示会打开VPN的提示框）

**Comment by airycanon** [comment]
@luffyke 我的情况跟你类似：
* 存在旧版，覆盖安装，没有弹出 VPN 的提示框，会出现“请选择配置文件“的错误。
* 不存在旧版，直接安装，会弹出 VPN 的提示框，点击确定后仍然会出现“请选择配置文件“的错误。

**Comment by luffyke** [comment]
@airycanon 嗯，我的后面卸载掉重装就正常了。

**Comment by Lemon-le** [comment]
meizu手机 一样的问题  试了很多版本  还是不行

**Comment by airycanon** [comment]
@Lemon-le 看这里 #1589

**Comment by Lemon-le** [comment]
刚刚我找到了另一个版本  可以使用了  是软件本身的问题

**Comment by lczxxx123** [comment]
MZnote5+flyeme6.3.0.0A(Android 7.0)+google play版本也会出现这个后台服务无法启动的问题。
另外在android7上会出现更新安装时报异常的情况。
（显示为安装包损坏，实际应该是覆盖安装的权限问题，卸后重装即可）

**Comment by qiuyukuhe** [comment]
@lczxxx123 一样的设备， 只有4.3.1可以用？

**Comment by lczxxx123** [comment]
@qiuyukuhe 试了4.4.6和4.4.5不行就直接跳回到4.3.1了，其他的没有尝试

**Comment by coolicer** [comment]
装了4.4.1，要求更新google play服务。之前的版本也会要求更新的，安装完就可以了

**Comment by LenKiMo** [comment]
flyme 6.3 固件与 Play 服务等套件对接存在问题。更新至 6.3 以后会导致此问题发生。

**Comment by coolicer** [comment]
@LenKiMo 我也是flyme6.3，我用的是GO那个安装套件

**Comment by vanejiang** [comment]
flyme6.3影梭最新版不能用，必须安装旧版本才行。

**Comment by tannx** [comment]
shadowsocks 4.4.6 在android 7.1.1 ，本来是用旧版3.0.4没问题，自动省级更新了版本，不连接了。

**Comment by reyesyang** [comment]
Nexus7 2013，Android 6.0.1和 @tannx 一样，清楚应用缓存之后再打开应用连接就好了

**Comment by huster1446** [comment]
flyme7，找了好久，4.2.0能用

**Comment by coolicer** [comment]
@huster1446 其实我已经提了给flyme管第三方的开发...不知道有没有空搞

**Comment by NWRH** [comment]
小米6手机  SS从旧版升级出现同样的错误，清除软件的所有数据后就可以正常使用了，不知道是不是更新造成的BUG

**Comment by yobdc** [comment]
meizu pro5，装v4.3.3可破

**Comment by ReeceNee** [comment]
Same issue here.

Android version: 7.0.0
Device: Meizu Pro5 
Shadowsocks version: 4.5.7

**Comment by xudaile** [comment]
Device: Meizu pro6
shadowsocks version :4.2.5
try to many shadowsocks version , i discovery 4.2.5 version that it is useful to my mobile

**Comment by TaoistMo** [comment]
same issue here.

Flyme version: 7.0.1.0A
Device: Meizu Pro6 s
shadowsocks version :4.6.1

**Comment by ssrpanel** [comment]
same issue here.
Flyme version: 7.0.1.0A
Device: Meizu 魅蓝 E1
shadowsocks version :4.6.1

**Comment by opticalix** [comment]
小米手机同样问题，怀疑是直接升级所致。
MIUI same issue.
尝试清除全部数据可以解决。
Clear all the data may resolve this problem

**Comment by wudan3551** [comment]
我用的4.2.4没啥问题

**Comment by zhangzhuoming** [comment]
Export the problematic settings to the sticker, remove the problematic settings, and import from the sticker.problem solved.

**Comment by zhangzhuoming** [comment]
把出现问题的设置导出到黏贴板,删除出现问题的设置,然后从黏贴板导入.

**Comment by liubao** [comment]
mx3最新版是有问题，下了4.2.4就可以了。
