### ISSUE TITLE
[question]Do I have to stay at v4.2.5 if my android version is 4.4 and per-app proxy is needed?

### ISSUE THREAD

**Issue by catscarlet** [shadowsocks/shadowsocks-android#1527]
This is just a question.

I saw that the NAT mode is retired in v4.3.0, and I know the NAT mode was no longer suggested a long time ago.

But I have a old android pad, mipad, and its latest version is still android 4.4. I need per-app proxy. 

Does that mean I have to stay in v4.2.5 ?

### Environment

* Android version: *4.4.x*
* Device: *MIPAD*
* Shadowsocks version: *newer than v4.2.5?*
* Last version that did not exhibit the issue (if applicable): *v4.2.5*

**Comment by Mygod** [comment]
You can use transproxy mode and take the trouble to set up bypass rules as
an alternative.

**Comment by catscarlet** [comment]
@Mygod Thank you for your answer.
There isn't urgent feature in the new version so I think I will stay at v4.2.5 for a while.
Not the same as v3-v4, I had to change my phone from android 4.2, to enjoy AEAD ciphers that time.
There are still too many phone and tablet using Android 4.4 or 5 although the latest version of Android is 8.
Anyway, Thanks for your help.
