### ISSUE TITLE
v 4.4.2无法刷新instagram/google play

### ISSUE THREAD

**Issue by yibin001** [shadowsocks/shadowsocks-android#1529]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *Android 8.0*
* Device: *三星 S8+*
* Shadowsocks version: *4.4.2*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Just install v4.4.2 and import my server config.

### What did you expect to see?

Connect successfully.

### What did you see instead?

1. 能打开twitter client
2. 能打开www.instgram.com
3. 开启instagram app不能刷新timeline
4. 打开google play提示：从服务器检索信息是出错[DF-DFERH-01]

![wechatimg17](https://user-images.githubusercontent.com/973490/34369248-36c1cc6c-eaf5-11e7-9b90-be3e1cd1b282.jpeg)
![wechatimg19](https://user-images.githubusercontent.com/973490/34369249-3702f0b6-eaf5-11e7-95fb-7c95ff1c079b.jpeg)
![wechatimg20](https://user-images.githubusercontent.com/973490/34369250-37320450-eaf5-11e7-9ed0-19dff05863b9.jpeg)

**Comment by madeye** [comment]
Post the full logcat if possible.

**Comment by yibin001** [comment]
我怎么样才能找到日志文件？

**Comment by Mygod** [comment]
https://play.google.com/store/apps/details?id=com.pluscubed.matlog

Or adb logcat if you don't have root.

**Comment by UranusCEO** [comment]
如何解决？

**Comment by selayoo** [comment]
分应用VPN里面勾选了相应app么？还有框架底层等

**Comment by loulijun** [comment]
分应用也开启了，包括dns转发也试过勾选，都不行

selayoo <notifications@github.com> 于 2018年4月10日周二 21:47写道：
