### ISSUE TITLE
Is it possible to set my android as a LAN proxy server?

### ISSUE THREAD

**Issue by Lovefish** [shadowsocks/shadowsocks-android#1530]
I mean I can get to SSR via my phone local IP 192.168.1.3:1080.

**Comment by madeye** [comment]
Nope, it's not supported.

**Comment by Mygod** [comment]
Afaic we are not going to officially support listening socks5 server on devices other than lo. There are several workarounds. As mentioned in #1446, one way to do this is to set up adb forward. A much less troublesome way (without risking trusting unknown devices) is to use a [port forwarder](https://play.google.com/store/apps/details?id=com.elixsr.portforwarder). Here's an example configuration.

![demo](https://user-images.githubusercontent.com/3511321/34370653-b097bd3e-eb00-11e7-951d-e06de560d1c0.png)

**Comment by Lovefish** [comment]
@Mygod thx, it works great!
