### ISSUE TITLE
v4.2.2 服务模式中"仅代理""VPN""透明代理"都是什么意思?

### ISSUE THREAD

**Issue by AmelieNet** [shadowsocks/shadowsocks-android#1531]
希望大神回答一下,"仅代理"和"透明代理"有什么区别?

**Comment by Mygod** [comment]
Just use VPN.

**Comment by Mygod** [comment]
Just use VPN.

**Comment by BigBIgMouse** [comment]
为什么我选择“仅代理”和“透明代理”都无法连接呢？

**Comment by howard11** [comment]
透明代理 的用法
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#how-to-use-transproxy-mode
