### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by wyun96711256** [shadowsocks/shadowsocks-android#1532]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 8.0
* Device: nexus 6P
* Shadowsocks version: 4.4.2
* Last version that did not exhibit the issue (if applicable): 4.1.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
正常google play上升级

### What did you expect to see?
连接成功,正常上网
### What did you see instead?
无法连接上网
![screenshot_20171228-085638](https://user-images.githubusercontent.com/14844926/34397209-08df276c-ebaf-11e7-8fe3-07a5d497f91c.png)
![qq 20171228091040](https://user-images.githubusercontent.com/14844926/34397456-2f59e5e2-ebb1-11e7-882f-e92dec5cdf7a.png)
![screenshot_20171228-085700](https://user-images.githubusercontent.com/14844926/34397457-2f939f94-ebb1-11e7-948b-814702b32f9e.png)

**Comment by madeye** [comment]
Shadowsocks-android is well tested on Nexus / Pixel devices. So, first of all, make sure your configs are correct.

**Comment by madeye** [comment]
You may also try a clean install. Or just clear the data of shadowsocks.

**Comment by wyun96711256** [comment]
我重新安装了一遍然后删除了所有数据,重新正确扫描二维码配置.选择
使用VPN模式
绕行局域网和中国大陆,
VPN分应用代理
结果仍然无法连接上.
卸载当前版本(4.4.2),安装使用4.1.8版本,扫描二维码配置,使用root NAT模式,分应用代理,正常连接上网

**Comment by madeye** [comment]
With 4.1.8, could you confirm that VPN mode also works?

**Comment by wyun96711256** [comment]
谢谢,我找到原因了, 因为一直没有消除信号的X,导致无法连接.现在更新后可以连接了

**Comment by hdp521** [comment]
我也无法连接 点连接就没反应
没有 授权VPN窗口

**Comment by darklx** [comment]
我也是这样 电脑上扫码的，配置都也有，android 不行。mac 可以。
手动添加的也是一样

Android 5.1.1 的手机不行 Android 7.1 的可以 这可咋整

**Comment by piggymorning** [comment]
如何解决的能说的详细些吗

**Comment by wyun96711256** [comment]
你要先排除感叹号，然后就连上了

piggymorning <notifications@github.com> 于 2018年6月15日周五 10:33写道：
