### ISSUE TITLE
What's the build command for "beta" branch?

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#1533]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Ubuntu 14 which can build master branch.

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
```
git checkout beta
sbt go-build android:package-release
```

### What did you expect to see?
Build successfully.

### What did you see instead?
```
[info] Loading project definition from /root/shadowsocks-android/project
[info] Updating {file:/root/shadowsocks-android/project/}shadowsocks-android-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to shadowsocks-android (in build file:/root/shadowsocks-android/)
[error] Not a valid command: go-build
[error] Not a valid key: go-build (similar: loaded-build, on-unload, loadedBuild)
[error] go-build
[error]         ^
```

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/beta/.travis.yml#L33

Search how to build signed release apk using Gradle.

**Comment by Mygod** [comment]
Read README.
