### ISSUE TITLE
在切换网络连接方式/热点之后必须重启SS，这个是不是没法解决？

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#154]
在SS已经运行的情况下，从WIFI切换到移动数据，或者反过来，或者从一个WIFI切换到另外一个WIFI，每次都得重启SS（reset），才能联网，仅仅flash DNS cache无法解决此问题。请问这个问题是android必然导致而无法解决吗？

系统 android 5 OTA 升级，没有root，选项开启了 bypass LAN/CHN UDP 转发以及auto connect
目前用的是 2.4.1，如果2.4.2已经解决此问题，请忽略。

谢谢！

**Comment by cooltech-bs** [comment]
我用的是2.7.7版本，原来没问题，最近一周出现了与这个issue相同的问题。

**Comment by YCYUNCNB** [comment]
@madeye 我也出现了这个问题，安卓4.2.2

**Comment by GitatHub** [comment]
@madeye this problem cames out again in ANDROID 6.0.1 on NEXUS 5 at its version 2.10.4
