### ISSUE TITLE
[3rd party] per app proxy doesn't work as intended

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-android#1540]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.2, LOS 14.1, `lineage-14.1-20171130_090058-UNOFFICIAL-sagit` 
* Device: Xiaomi Mi 6
* Shadowsocks version: v4.2.5 - v4.4.2 (all versions should be able to replicate this)
* Last version that did not exhibit the issue (if applicable): irrelevant with app version, see below

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: RC4-MD5
* Route [see below description]
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode  [see below]
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
On all the other LOS, shadowsocks works as intended. Due to #1488 and #1470 , Google Translate app has to be excluded when proxy is on to access Google.cn. I enabled the ticked items above.

### What did you expect to see?
Per app proxy + bypass mode will prevent the app from directing its data to proxy server when selected to be bypassed, or per app proxy + normal mode will not prevent an app from being proxied, when deselected in per app proxy.

### What did you see instead?
The combination of [per app proxy + bypass mode / normal mode] and [global proxy / bypass LAN & China] will fail to prevent Google Translate, or any app selected in bypass mode from being excluded.
* per app proxy + bypass mode + [global proxy / bypass LAN & China] with the objective app selected for bypass, or per app proxy + normal mode + [global proxy / bypass LAN & China] with the objective app *deselected* to be proxied: ![](https://i.imgur.com/KNR54Xj.png)
* turn off shadowsocks (`192.168.1.3` is my phone's IP in my home wifi): ![](https://i.imgur.com/b10Y0Nd.png)

### Purpose
I would kindly ask you some details about the implementation of per app proxy, so I can create an issue on my device system maintainer's Github.

**Comment by madeye** [comment]
It's probably an issue of your ROM.

You can open an issue with your ROM maintainer to check any VPNService related changes.

**Comment by HankAviator** [comment]
Confirmed as 3rd-part bug, closed.
