### ISSUE TITLE
三星NOTE8使用SS客户端总是会一会儿就断线需要重新连

### ISSUE THREAD

**Issue by ericyyyy** [shadowsocks/shadowsocks-android#1541]
三星NOTE8
版本国行非ROOT
使用SS客户端（github最新版本或者Google Play 版）都会出现一会儿就断了，点测试就会显示无法连接物联网，提示 SSL handshake Timeout

已经在NOTE8中设置允许后台运行了，也设置了不监视SS运行（防止休眠）

电脑上和iPhone上使用毫无问题。

请问这是三星ROM 问题吗？或者说有什么办法可以解决

**Comment by madeye** [comment]
It's a known issue of Galaxy Note8. Search the issue tracker for more info.

**Comment by zhangqithu11** [comment]
我也有这个问题，请问你解决了吗？

**Comment by yencn** [comment]
还没有解决哦   好烦心哦

**Comment by ntyitian** [comment]
一样，我的note8也是这个问题，一直没解决。以后不买三星的机器了

**Comment by gumptie** [comment]
我的Note8之前也是遇到同样的问题，后来按照指引设置，基本没有遇到断网问题。连着开几天都不会断网。

**Comment by ntyitian** [comment]
@gumptie 你是怎么设置的，有教程么？我的一直被困扰中。

**Comment by gumptie** [comment]
@ntyitian https://github.com/shadowsocks/shadowsocks-android/issues/1410
我是按照下面这个操作。
我有个朋友也是NOTE8，通过这个设置也解决了同样的问题。
不过好像不是每部机子都可以，可以试试。

Anyway, if you didn't installed Brevent, maybe it is your misconfiguration.
There are several items of setting you should config:

Smart Manager-->Battery-->Unmonitored apps;
Smart Manager-->App management-->Manage Autorun;
Besides, if you add ss into Security Folder/MyKnox, you need add the ss-secured(the ss in Security Folder) into white list as well.
