### ISSUE TITLE
4G 下连接后无法访问互联网

### ISSUE THREAD

**Issue by ctlee61** [shadowsocks/shadowsocks-android#1544]
### Environment

* Android version: *5.0.2*
* Device: *LG isai FL LGL24*
* Shadowsocks version: *4.4.2*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I had configured correctly.
### What did you expect to see?
Link to the internet.
### What did you see instead?
I couldn't visit any servers when I am in 4G environment but I could do it in WLAN environment.

**Comment by madeye** [comment]
Make sure the background data of shadowsocks is allowed.

**Comment by ctlee61** [comment]
Unluckily it wasn't be limited under 4G, the server wasn't been blocked either.

**Comment by ctlee61** [comment]
Also, it wasn't work when I'm using shadowsocks-rr for Android, yet another shadowsocks client. I thought the problem is about 4G and VPN, but I didn't know why.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#it-works-fine-under-wi-fi-but-cant-connect-through-cellular-data
