### ISSUE TITLE
Routing's not working on pixel2 xl

### ISSUE THREAD

**Issue by xin1092134** [shadowsocks/shadowsocks-android#1547]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1
* Device: Google Pixel2 XL
* Shadowsocks version: 4.2.5 4.3.3 4.4.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you expect to see?
routing's not working. when I using apps does not need to route to proxy server, it still routed and it's opening too slow.

**Comment by JunnanZ** [comment]
I have the same issue, also on pixel 2 xl. No matter which one I choose (bypass China, gfw list, China list), visiting Chinese websites, say baidu, still goes through shadowsocks. I didn't select data saver in chrome.

**Comment by madeye** [comment]
I cannot reproduce your issue locally.

Please provide detailed steps to reproduce your issue.

**Comment by JunnanZ** [comment]
I was using Google play version. For future reference, updating to 4.4.4 fixed the issue.
