### ISSUE TITLE
shadowsocks works on windows but not on android

### ISSUE THREAD

**Issue by madl-ash** [shadowsocks/shadowsocks-android#1549]
### Environment

* Android version: 6.0.1
* Device: *Samsung Galaxy S5*
* Shadowsocks version: *version code "v4.4.3" or commit ID " a40f87f"(Pre-release - nightly build)*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:AES-256-CFB
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules : None
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here: i'm using VPN Mode

### What did you do?
I used the version on googleplay(4.2.5 i think) and it didn't work so i upgraded to latest build and the problem still exists as i said below.

### What did you expect to see?
QT client on windows works correctly but android client doesn't works

### What did you see instead?
shadowsocks doesn't work,either it stuck at "testing" or apps use my normal IP instead of my proxy server's IP

1.if i turn on DNS forwarding,i suppose it doesn't connect to server because when i tap the "test connection",it stucks on "testing..."

2.if DNS forwarding is off,client connects successfully and i can test my latency,but no app is using the VPN and all of them are using my normal ip

**Comment by Mygod** [comment]
Try using other routes.

**Comment by zk5580752** [comment]
The same with you... Please help...

**Comment by madeye** [comment]
It's expected when you're using a invalid custom rules.

**Comment by zk5580752** [comment]
No, not the problem about my rules. The same rules works well in my mac and windows and I check double when using in the android.
So, just now I downgrade the version into 4.2.5. Its work again... Maybe some problem in latest version (4.4.4 or earlier)
Hope this can help you.

**Comment by madeye** [comment]
@zk5580752 Please don't post your issue in other one's issue, since you are facing different problems.
