### ISSUE TITLE
How to publish my translation to the project?

### ISSUE THREAD

**Issue by initrider** [shadowsocks/shadowsocks-android#1551]
Hello everybody. I updated Russian translation just now from 90 to 99.2 percentage and fixed some translation mistakes. How can I publish it to the project?
![_2018-01-04_13-35-16](https://user-images.githubusercontent.com/35081987/34559762-291fbc44-f154-11e7-8844-c2fdc35be529.png)

**Comment by Mygod** [comment]
Hi @initrider! Thanks for contributing! We will periodically merge translations from poeditor, for example see [here](https://github.com/shadowsocks/shadowsocks-android/commits/master/mobile/src/main/res/values-zh-rCN).

Note: Transproxy is short for transparent proxy. If you feel like keeping Transproxy in Russian, please feel free to go back there and revert my changes. :)

By the way we do have a separate issue #1142 open specifically for translations. Feel free to continue the conversation here or there.

**Comment by Mygod** [comment]
Hi @initrider! Thanks for contributing! We will periodically merge translations from poeditor, for example see [here](https://github.com/shadowsocks/shadowsocks-android/commits/master/mobile/src/main/res/values-zh-rCN).

Note: Transproxy is short for transparent proxy. If you feel like keeping Transproxy in Russian, please feel free to go back there and revert my changes. :)

By the way we do have a separate issue #1142 open specifically for translations. Feel free to continue the conversation here or there.
