### ISSUE TITLE
v4.4.3 最后一个配置文件被buttom bar（?）遮住了

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1553]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android O (OPM1.171019.011)
* Device: Nexus 6P
* Shadowsocks version: v 4.4.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
添加多个配置文件

### What did you expect to see?
配置文件能全部展现

### What did you see instead?
最后一个配置文件被buttom bar(还是navigation bar ?)遮住。向上拉也不能完全展示

**Comment by madeye** [comment]
It's a known bug and has been fixed via db74988190e3f29d6b32f9610158f91fed75c76d

**Comment by madeye** [comment]
Try v4.4.4

**Comment by iamsad3508** [comment]
v 4.4.4没问题

**Comment by Mygod** [comment]
I wonder if animation still works in 4.4.4... I'll look into it sometime. 👽

**Comment by madeye** [comment]
@Mygod Just tried on 4.4.4 emulator, everything works well.

**Comment by Mygod** [comment]
@madeye Hmmm yeah but it's a different animation now. :sweat:
