### ISSUE TITLE
Connection failure on version 4.4.x

### ISSUE THREAD

**Issue by gavinweixin** [shadowsocks/shadowsocks-android#1557]
### Environment

* Android version: *7.1.1 PureNexus-20170317*
* Device: *Google Nexus 6*
* Shadowsocks version: *4.4.1/4.4.2/4.4.4*
* Last version that did not exhibit the issue (if applicable): *4.2.5*

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: *CHACHA20*
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Update to new versions 4.4.1/4.4.2/4.4.4 on Google Play Store from version 4.2.5.

### What did you expect to see?
Connection success.

### What did you see instead?
I have tried version 4.4.1/4.4.2/4.4.4, and they all came into the error 'Failed to detect internet connection: SSL handshake timed out'.
Version 4.2.5 works well on my phone with the same configuration, so do Windows & Mac clients.

**Comment by madeye** [comment]
Could you disable TCP fast open and try again?

**Comment by madeye** [comment]
Also try a clean install.

**Comment by gavinweixin** [comment]
Just tried a clean install and got TCP Fast Open disabled, but it reported with the same error.

**Comment by madeye** [comment]
Please post the logcat here if possible.

**Comment by gavinweixin** [comment]
It hit me that I have changed the hosts file, and after setting it back to default Shadowsocks can work now! Thx a lot!

**Comment by madeye** [comment]
Hmm... Just tried latest release on Android 4.4, 7.0 and 7.1 emulator. Everything works well.

**Comment by gavinweixin** [comment]
Actually, I used Go Hosts to change hosts file before, and maybe some its rules conflict with new versions of Shadowsocks.

**Comment by wenhelinlu** [comment]
very thanks, finally got the solution.
