### ISSUE TITLE
How to prevent it from being killed when cleaning background apps?

### ISSUE THREAD

**Issue by HankelBao** [shadowsocks/shadowsocks-android#1562]
### Environment

* Android version: 6.0
* Device: HUAWEI G9 Lite
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I pressed the clean background apps button in the multi-apps interface.

### What did you expect to see?
Shadowsocks could still stay alive just like spotify or QQ, etc.

### What did you see instead?
Shadowsocks is killed.

It there any way to keep it alive?
Or how can i keep it running in background?

**Comment by Mygod** [comment]
Read FAQ.
