### ISSUE TITLE
gradle failed 

### ISSUE THREAD

**Issue by quan-xie** [shadowsocks/shadowsocks-android#1563]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Mac os 10.13.2

### What did you do?
 gradle assemble -x lint

### What did you expect to see?
> Task :core:goBuild
Make standalone toolchain for ARM arch
src/overture/make.bash: line 31: :/Users/xxx/Library/Android/sdk/ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Make standalone toolchain for ARM64 arch
src/overture/make.bash: line 37: :/Users/xxx/Library/Android/sdk/ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Make standalone toolchain for X86 arch
src/overture/make.bash: line 43: :/Users/xxx/Library/Android/sdk/ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Get dependences for overture
~/androidstudio/shadowsocks-android/core/src/overture/src/github.com/shadowsocks/overture/main ~/androidstudio/shadowsocks-android/core
Cross compile overture for arm
# runtime/cgo
fork/exec /Users/xiequan/androidstudio/shadowsocks-android/core/src/overture/.deps/android-toolchain-19-arm/bin/arm-linux-androideabi-clang: no such file or directory

### What did you see instead?

sudo chomd -R 777 /Users/xxx/Library/Android/sdk/ndk-bundle/build/tools

**Comment by sugood** [comment]
兄弟～你这问题怎么解决的？
