### ISSUE TITLE
Cannot connect through cellurar network

### ISSUE THREAD

**Issue by initrider** [shadowsocks/shadowsocks-android#1565]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1
* Device: Google Nexus 9
* Shadowsocks version: 4.3.3
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I and my friend live in diffenent countries. But we have the same problem. No matter, what server we select - it is the same behavior all time. If I connect by wi-fi, it works normally, but if we use cellurar network, it not working. Speed test shows !10kb/s download and normal speed at upload. On wifi download and upload speed are normal. Tried to follo the FAQ, it doesn't help. Dont know, what it could be. 

### What did you expect to see?
Shadowsocks working

### What did you see instead?
It doesn't

Update: Telegram + socks5 only mode works! VPN mode not.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#it-works-fine-under-wi-fi-but-cant-connect-through-cellular-data

**Comment by initrider** [comment]
I was already enabled. But it doesnt work.
![screenshot_20180108-105100 2](https://user-images.githubusercontent.com/35081987/34662484-15f6bbde-f462-11e7-92cd-d96ee8b31057.png)

**Comment by initrider** [comment]
Shadowsocks show 6 kb/sec for downloading. On server side there are some "Connection reset by peer" errors (SS 3.1.1).
Update! Something strange. Well, I fixed the problem, maybe only temporally or not. I simply open Telegram Messenger and started download videos. After some tryings, it started works fast. Now speedtest shows normal speed.

**Comment by initrider** [comment]
Update! Here is my test. Youtube Full HD works really fast, Speedtest reached normal speed on both download and upload. But google search works slow.

**Comment by madeye** [comment]
If you're using Chrome,

- In the URL type "chrome://flags"
- Search for "QUIC protocol" and disable it

**Comment by madeye** [comment]
Please disable data saver in Chrome as well.

**Comment by initrider** [comment]
It start working a bit faster. Howeever Youtube, Telegram and Speedtest working slow againg... It seems, I must to get something work, I must to use it for some time. Then speed become normal.
By the way, I found new problem. It seems, your fix - https://github.com/shadowsocks/shadowsocks-android/issues/1233 - doesn't work. I unable to connect to local subnets, even I use Route - All.

**Comment by initrider** [comment]
Just theory. Maybe something wrong with mtu on client side?

**Comment by initrider** [comment]
So I don`t know, how Telegram depends on whole network, but yes, if nothing work, I run Telegram, than try to download video. After 3 minutes, evrything except for google search start works perfectly. After 5 minutes of inactivity - it not work again.
