### ISSUE TITLE
Not all apps are listed in the per-app proxy list

### ISSUE THREAD

**Issue by dbw9580** [shadowsocks/shadowsocks-android#1567]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: device 1: 8.0.0, Sony Xperia stock; device 2: 7.1.2, LineageOS 14.1 20171228
* Device: device 1: Sony Xperia XZ1 Compact; device 2: Xiaomi Mi 4c
* Shadowsocks version: 4.2.5
* Last version that did not exhibit the issue (if applicable): n/a

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Install Automate from Google Play, an automation app like Tasker.
Try to include Automate in the per-app proxy list.

### What did you expect to see?
Automate gets listed in the app list, so it can be selected.

### What did you see instead?
Automate is not listed. Instead, one of the Automate permission plugins does get listed.

**Comment by Mygod** [comment]
Search issue tracker before posting new issues. Apps that don't declare INTERNET permission can't access INTERNET.
