### ISSUE TITLE
代理google play services，gcm会不断断开重连

### ISSUE THREAD

**Issue by buguniaogu** [shadowsocks/shadowsocks-android#1572]
### Environment

* Android version: 8.1
* Device: Nexus 5X
* Shadowsocks version: 4.4.4

/etc/shadowsocks-libev/config.json  

    "server":"",  
    "server_port":443,  
    "local_port":1080,  
    "password":"",  
    "timeout":60,  
    "method":"aes-128-gcm"
代理google play services（wifi或数据网络），查看gcm详情（拨号盘\*#\*#426#\*#\*）。
发现gcm不断重连。
不代理google play services，不会出现重连状况。（但造成其他问题，例如同步）
不确定是否会是android8.1的bug。[issue:68657525](https://issuetracker.google.com/issues/68657525)
![image](https://user-images.githubusercontent.com/4465719/34903216-c00df5de-f867-11e7-87ec-d2c95fc9f057.png)

**Comment by buguniaogu** [comment]
找到了之前的issue，先看一下，sorry to bother。

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，ss默认设置gcm走proxy。是否可以默认设置不走proxy？或者怎样设置自定义规则？

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，ss默认设置gcm走proxy。是否可以默认设置不走proxy？或者怎样设置自定义规则？

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，ss默认设置gcm走proxy。是否可以默认设置不走proxy？或者怎样设置自定义规则？

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，shadowsocks默认设置代理了gcm。这能够更新一下规则么？不代理gcm。

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，shadowsocks默认设置代理了gcm。这能够更新一下规则么？不代理gcm。

**Comment by buguniaogu** [comment]
gcm在中国没有屏蔽，shadowsocks默认设置代理了gcm。这能够更新一下规则么？不代理gcm。

**Comment by madeye** [comment]
GCM requires timeout larger than 600s.
