### ISSUE TITLE
git submodule update --init --recursive

### ISSUE THREAD

**Issue by hejie** [shadowsocks/shadowsocks-android#1576]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

hejiedeMacBook-Pro:shadowsocks-android hejie$ git submodule update --init --recursive
Cloning into '/Users/hejie/projects/shadowsocks-android/core/src/main/jni/pcre'...
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Operation timed out
fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path '/Users/hejie/projects/shadowsocks-android/core/src/main/jni/pcre' failed
Failed to clone 'core/src/main/jni/pcre'. Retry scheduled
Cloning into '/Users/hejie/projects/shadowsocks-android/core/src/main/jni/pcre'...
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Operation timed out
fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path '/Users/hejie/projects/shadowsocks-android/core/src/main/jni/pcre' failed
Failed to clone 'core/src/main/jni/pcre' a second time, aborting

### What did you expect to see?
能正常执行

**Comment by madeye** [comment]
As said in the log, your network cannot access https://android.googlesource.com/platform/external/pcre/
