### ISSUE TITLE
4.4.5版本 4g下无法连接

### ISSUE THREAD

**Issue by zhengwenk** [shadowsocks/shadowsocks-android#1577]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
4.4.5版本
在4g网络下无法连接。wifi可以连接

```
D/Cal:D:MiPushManager( 1105): shouldInit(): 32358:1105, com.android.calendar:com.github.shadowsocks
I/dalvikvm(32358): Could not find method java.net.URLConnection.getContentLengthLong, referenced from method com.github.shadowsocks.utils.UtilsKt.getResponseLength
I/dalvikvm(32379): Could not find method android.os.PowerManager.isInteractive, referenced from method com.github.shadowsocks.bg.ServiceNotification.<init>
D/PhoneStatusBar( 1184): addNotification pkg=com.github.shadowsocks;basepkg=com.github.shadowsocks;id=1
E/dalvikvm(32379): Could not find class 'android.system.ErrnoException', referenced from method com.github.shadowsocks.JniHelper.sigtermCompat
W/dalvikvm(32379): VFY: unable to resolve new-instance 1568 (Landroid/system/ErrnoException;) in Lcom/github/shadowsocks/JniHelper;
D/dalvikvm(32379): DexOpt: unable to opt direct call 0x32ae at 0x1e in Lcom/github/shadowsocks/JniHelper;.sigtermCompat
D/dalvikvm(32379): Trying to load lib /data/app-lib/com.github.shadowsocks-1/libjni-helper.so 0x429c1548
D/dalvikvm(32379): Added shared lib /data/app-lib/com.github.shadowsocks-1/libjni-helper.so 0x429c1548
D/shadowsocks( 1384): initializing acl...
I/dalvikvm(32379): Could not find method android.net.LinkProperties.getDnsServers, referenced from method com.github.shadowsocks.bg.Dns.getDnsResolvers
I/overture( 1403): time="2018-01-16T03:23:58Z" level=info msg="If you need any help, please visit the project repository: https://github.com/shadowsocks/overture"
D/shadowsocks( 1384): initializing ciphers... aes-256-cfb
D/shadowsocks( 1384): listening at 127.0.0.1:1080
D/shadowsocks( 1384): udprelay enabled
I/Vpn     ( 1126): Established by com.github.shadowsocks on tun0
```

**Comment by sssshadowsocks** [comment]
预订服务地址 https://portal.shadowsocks.la/aff.php?aff=12091
• Windows  客戶端下載 https://portal.shadowsocks.la/files/Shadowsocks-4.0.6.zip 注：需要安裝 .NET FrameWork 4.6.2 以上版本
• iOS  相關客戶端與使用方法請參考下述鏈接： https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md
• MAC OS  請更新到 ShadowsocksX-NG 使用 下載地址： https://portal.shadowsocks.la/files/ShadowsocksX-NG.1.6.1.zip
• Android下載地址  下載地址： https://portal.shadowsocks.la/files/shadowsocks-nightly-4.2.5.zip
• Linux用戶  請使用最新的 Shadowsocks-libev 命令行版本 安裝與使用請參考：https://github.com/shadowsocks/shadowsocks-libev

**Comment by Mygod** [comment]
Android 4.4 is no longer supported.
