### ISSUE TITLE
This app doesn't support Android 4.3.

### ISSUE THREAD

**Issue by brokpen** [shadowsocks/shadowsocks-android#1579]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by Mygod** [comment]
Maybe we should drop support for 4.4 and 5.0 as well. Android security patches [dropped support for 4.4 in Nov](https://source.android.com/security/bulletin/2017-11-01) and [5.0 in Dec](https://source.android.com/security/bulletin/2017-12-01).

**Comment by brokpen** [comment]
是的，但是仍然有少部分用户使用，我在测试某项目需要在4.3手机上面。 幸运的是， 我找到了这个软件的旧版本解决了

**Comment by madeye** [comment]
@Mygod Good idea!

@brokpen We dropped the support of 4.3 about two years ago. So it's expected.

**Comment by Mygod** [comment]
We could still keep 5.0 support though since there's virtually no difference between 5.0 and 5.1.

**Comment by catscarlet** [comment]
Maybe we can update Readme.md and show about the latest version of supported android, or some key feature or key change.
I used 2.10.4 on an Android 4.2 phone for a long time. I think that was the last stable version still supported Android 4.2, without AEAD (A great key feature)
And I'm also using 4.2.5 on another Android 4.4 phone. Supports AEAD and NAT mode for pre-app using.
