### ISSUE TITLE
System laggy

### ISSUE THREAD

**Issue by HanYL-coder** [shadowsocks/shadowsocks-android#1580]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *8.1*
* Device: *Google Pixel 2 XL*
* Shadowsocks version: 4.4.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ x] IPv6 server address
* [x ] Client IPv4 availability
* [ x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
There might be some problems causing system laggy.
I think the problem might be occuring when maching the routing rules. And the rules still not working fine, most of the network accesses should not mathing the rules still NOT connect to the server directly.
The situation happens when TOO MANY accesses mathing the rules and go throught the proxy.
Maybe the multi-processing ability need to be optimized.
Plz let me know if anything I can do to help, including test and do coding works.

Wish we can access networks without this amazing tool some day.

**Comment by madeye** [comment]
I cannot reproduce the lag you mentioned on the same device.

**Comment by madeye** [comment]
> most of the network accesses should not mathing the rules still NOT connect to the server directly.

Any example?

**Comment by HanYL-coder** [comment]
It's not always feeling laggy.
When it happens, just shutdown the shadowsocks, then the app you are using will be not responsable, restart the app, and the lag is gone.

For the proxy rules.
Like wechat(including pages opened in it), baidu map, almost every app is going through the proxy.
But one thing I'm certainly sure that the proxy rules are still working. Cuz once I opened us.battle.net, it wasn't going through the proxy(this was the only one I found not matched in the rules), and I added it into the rules list, it can be accessed.

Is there any tools that I can test the rules on PC?
I wanna locate the problem from the rules or the code's logical.

**Comment by madeye** [comment]
> Like wechat(including pages opened in it), baidu map, almost every app is going through the proxy.

First of all, you should exclude these "Chinese apps" through per-app proxy settings, as most of slowness issues come from their internal DNS implementation.

With our default GFWList, I don't think any host name in these apps would be matched.

> When it happens, just shutdown the shadowsocks, then the app you are using will be not responsable, restart the app, and the lag is gone.

List the apps here.

**Comment by HanYL-coder** [comment]
> First of all, you should exclude these "Chinese apps" through per-app proxy settings, as most of slowness issues come from their internal DNS implementation.

May be that's the problem why it's lagging my system and always going through the proxy server.
Could you tell my where the "per-app proxy settings" is, I can not find it.
Is it a system setting or an app setting?

**Comment by madeye** [comment]
In a profile, select "Apps VPN mode".

**Comment by HanYL-coder** [comment]
Do I need to root my phone?
There just three selections, Proxy only, VPN and Transproxy.

**Comment by madeye** [comment]
It's in the proxy config view, where you configures the password.

**Comment by HanYL-coder** [comment]
I get it.
I always using scanQR code to add profiles, never noticed the selections.
thx very much, appreciate it.
