### ISSUE TITLE
"Proxy only" mode: can't check connection

### ISSUE THREAD

**Issue by l5h5t7** [shadowsocks/shadowsocks-android#1583]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *Android 6.0.1*
* Device: *Google Nexus 6*
* Shadowsocks version: *version code "v4.3.0"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
switch to "Proxy only" mode, connect to a available server, and touch the bottom bar.

### What did you expect to see?
The bottom bar shows: "Success: ____ latency". (If I use "VPN" mode, all is well.)

### What did you see instead?
The bottom bar shows: "Internet Unavailable", and at the bottom of the screen shows: "Fail to detect internet connection: Malformed reply from SOCKS server".

**Comment by madeye** [comment]
Please update to the latest version and try again.

**Comment by l5h5t7** [comment]
Updated shadowsocks-android to 4.4.5, but the issue still exists.

**Comment by fanthos** [comment]
I am using miui  android 8.0 and has the same issue. Tested with 4.4.5 and 4.3.3.

**Comment by sniperhalo** [comment]
me too

**Comment by doegeenon** [comment]
same here. with 8.1 pixel phone

**Comment by madeye** [comment]
@Mygod Could you reproduce this issue on your devices? I cannot reproduce it locally.

**Comment by Mygod** [comment]
As I've already mentioned in #1595 connection tests under proxy only mode works even better than that under VPN modes for me. :)

**Comment by Mygod** [comment]
Also can't reproduce this on emulator.

**Comment by balthild** [comment]
On my device, the bug only occurs in Android 6.0 ROMs, and disappears on Android 8.1

**Comment by AnyoeDove** [comment]
same here, Android 6.0.1 @madeye
