### ISSUE TITLE
为什么要由安卓app层面先dns查询连接的ss远程服务器地址呢？

### ISSUE THREAD

**Issue by snower** [shadowsocks/shadowsocks-android#1584]
看代码BaseService中，如果配置远程服务器地址写的是域名而不是ip地址的时候，会先做dns解析，然后再用ip启动local-ss，为什么不让local-ss自行解析域名呢？

```
if (!profile.host.isNumericAddress())
    profile.host = Dns.resolve(profile.host, true) ?: throw UnknownHostException()

startNativeProcesses()
```

这样在用动态dns更新ip地址的时候问题很大啊，ip一变，local-ss并不能更新，很容易卡死

**Comment by madeye** [comment]
It's expected. For any DDNS hostname, please try to reconnect after IP address changes.

**Comment by snower** [comment]
为什么要这么设计呢？很不方便诶

**Comment by madeye** [comment]
Avoid local DNS queries. Since there always exists DNS cache, I don't think DDNS problem would be solved by doing DNS query in ss-local.

**Comment by snower** [comment]
Well, read the local-ss inside is indeed the first analysis of ip, and then started to initiate the connection, follow-up ip change does not take effect, thank you!
