### ISSUE TITLE
为何我连上上海”花生地铁”公共wifi后，有时无法翻墙？

### ISSUE THREAD

**Issue by yelosheng** [shadowsocks/shadowsocks-android#1588]
奇怪的现象：
本人华为P8的手机，在移动数据和其他Wifi环境下，打开shadowsocks后可流畅翻墙，可是连上地铁提供的公共Wifi后（“花生地铁Wifi”），某些时候无法翻墙。但也不是每次都不行，成功和失败大概各占一半吧。
请大神给分析下，这是怎么回事？

**Comment by pexcn** [comment]
这种网络需要它的客户端认证，可能是验证的地址走了代理，所以要关掉 ss 验证完之后重新开 ss 才能用

**Comment by yelosheng** [comment]
您说的没错，的确是要先关掉ss，然后用它的客户端认证，再打开ss翻墙。
问题是同样经过上述操作，有时候能够翻墙，有时候无法翻墙。而且，无论能否翻墙，我的vps的ip都是可以ping通的。而且如果切换的4G网络，也是可以翻墙的。

**Comment by Mygod** [comment]
I don't think it has anything to do with this app.
