### ISSUE TITLE
Please select a profile

### ISSUE THREAD

**Issue by jw587** [shadowsocks/shadowsocks-android#1589]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1 with Flyme 6.2.5.0A
* Device: Meizu MX6
* Shadowsocks version: 4.4.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
有时候打开ShadowSocks的时候，它会闪退，然后再点一下就能打开了。
但选择一个配置后，点击右下角的小飞机图标连接，老是提示“Please select a profile”。
我尝试过将所有配置删除，然后手工添加了一个新配置，还是同样的问题。
手机重启之后再试，第一次打开的时候没有闪退，但还是提示“Please select a profile”
最近3、4个版本都有这个问题。

### What did you expect to see?
应该能连接上

### What did you see instead?
总是提示“Please select a profile”，但实际上我已经选择了一个配置。

**Comment by jw587** [comment]
之前都是安装新版本apk来直接替换掉手机上的旧版本，刚才试了一下把软件卸载、清理缓存、重启手机、重新安装，还是有同样的问题。我现在重新安装了4.2.3就可以了。

**Comment by madeye** [comment]
It looks a Flyme only issue according to reports. @Mygod.

**Comment by Mygod** [comment]
I don't have a flyme device though. Could you try wiping data?

**Comment by liangpure** [comment]
I meet the same problem in MEIZU PRO 6. Android version 7.1.1

**Comment by Cople** [comment]
PRO 6s 系统版本和楼主一样，一直提示「后台服务启动失败：请选择配置文件」，清除数据也没用。

**Comment by Mygod** [comment]
Please post a logcat if possible (although it's most likely database corruption).

**Comment by Flammulinavelutipes** [comment]
我meizu pro6 也遇到同样问题，哪里可以下载SS旧版本？

**Comment by jw587** [comment]
这个项目的Code标签里，有个Releases，里面有各个版本的下载

**Comment by jw587** [comment]
不知道怎么生成logcat

**Comment by Cople** [comment]
java.lang.RuntimeException: Unable to create application com.github.shadowsocks.App: java.sql.SQLException: Unable to run insert stmt on object com.github.shadowsocks.database.KeyValuePair@bbbc516: INSERT INTO `keyvaluepair` (`key` ,`value` ,`valueType` ) VALUES (?,?,?)

好像问题出在这里？

[logcat.zip](https://github.com/shadowsocks/shadowsocks-android/files/1649761/logcat.zip)

**Comment by BurgerTown** [comment]
用Kotlin重写后才出现

**Comment by Mygod** [comment]
OK I suspect this problem is caused by messed up permissions of `/data/user_de` folder.

Could somebody run this on a **rooted** terminal and paste output: `ls -al /data/user_de/0/com.github.shadowsocks/databases`.

**Comment by BurgerTown** [comment]
Result
![default](https://user-images.githubusercontent.com/19660419/35331583-da4ee53c-0142-11e8-9868-b783f7b2368c.png)

**Comment by Mygod** [comment]
profile.db shouldn't exist under that folder. Maybe Flyme ROMs are doing a symlink for `user_de` folder?

Could you also run `ls -al /data/user/0/com.github.shadowsocks/databases`?

**Comment by Mygod** [comment]
Also I thought Flyme ROMs are not officially supported. Wtf @madeye?

**Comment by BurgerTown** [comment]
Here is the result
![default](https://user-images.githubusercontent.com/19660419/35367636-5cf5a0b2-01ba-11e8-8bb0-39044e10a153.png)

**Comment by BurgerTown** [comment]
I think of Xposed Installer when u mentioned  `user_de` folder
The App it self seems cannot creat file or folder in `user_de` folder even it has the root perrmission
so i have to creat folders and files manually so that i can run Xposed modules LOL

**Comment by Mygod** [comment]
Yeah Flyme is so terrible at making ROMs that they should just quit already. Report this bug to Flyme instead. Tell them they can't just symlink user_de to user. They can't make this Android 7.x/6.x hybrid. Wtf do they expect us to do?

I can't fix this unless somebody mails me a rooted flyme phone. The last version that will work on this buggy system is 4.4.1. One can also build custom builds that reverts #1525 so that it will work on these buggy ROMs.

**Comment by BurgerTown** [comment]
I reported this to Flyme but i dont thihk it will make any changes beacuse there is still some devices runs a Flyme bases on Android 6.x and others are running at 7.x

**Comment by Mygod** [comment]
Avoid Flyme devices in the future.

**Comment by BurgerTown** [comment]
haaaa

**Comment by madeye** [comment]
I'm curious how Flyme passed Android CTS?

**Comment by BurgerTown** [comment]
I think the answer is no

**Comment by jw587** [comment]
多谢各位大佬的热心支持，只要有能用的版本就知足了，再次感谢！

**Comment by BurgerTown** [comment]
>Yeah Flyme is so terrible at making ROMs that they should just quit already. Report this bug to Flyme instead. Tell them they can't just symlink user_de to user. They can't make this Android 7.x/6.x hybrid. Wtf do they expect us to do?
I can't fix this unless somebody mails me a rooted flyme phone. The last version that will work on this buggy system is 4.4.1. One can also build custom builds that reverts #1525 so that it will work on these buggy ROMs.

用441或以下的就行

**Comment by Mygod** [comment]
Added to FAQ via https://github.com/shadowsocks/shadowsocks-android/commit/bff2615599285588eb06823d59951ebfb7f10a09.

**Comment by liuwei0514** [comment]
系统设置 应用管理 找到应用 选择存储 删除数据 重新进入应用就ok了

**Comment by jw587** [comment]
刚刚试过，4.4.1以上版本不行 @liuwei0514

**Comment by thekingofcity** [comment]
Thanks to this discussion. I have just decided to change my next phone to OnePlus or Pixel 2.
A Pro 6 Plus user who encountered this problem.

**Comment by lendo** [comment]
坑，我也是Flyme.

**Comment by stephenix** [comment]
meizu pro 6 plus encounters the same problem.

**Comment by shishenwozuile** [comment]
Thank you  very much

**Comment by BurgerTown** [comment]
为大家提供版本
Pro6Plus 即7.0.0 用4.3.3
Pro6 即7.1.1 用4.6.6
这应该是最高支持的版本了

**Comment by EriCZZZZ** [comment]
exm, any version can pro7 use? thanks

**Comment by hmgqzx** [comment]
@BurgerTown 
4.6.6？😂现在最高版本不是 4.6.1 吗？

**Comment by Lsnsh** [comment]
### use version`4.4.1`, it work!

Environment
* Android version: 7.0.0 with Flyme 7.8.7.24 beta
* Device: Meizu Pro 6 Plus
* Shadowsocks version: 4.4.1

**Comment by jw587** [comment]
Meizu 16上可以正常运行最新的4.6.1
下面是Meizu 16的系统版本信息：
Android Version: 8.1.0
Flyme 7.1.1.2A

**Comment by BurgerTown** [comment]
It works now. @Mygod 
I think Flyme fix that problem
devices:Meizu Pro 6 Plus
Android Version: 7.0.0
Flyme 7.2.0.0A

**Comment by Se7enPanda** [comment]
device :MeiLan Note 5
Android Version: 7.0
Flyme: 7.1.5.0A

SS version: 4.7.0 , still show "Please select a profile" when start SS.
ONLY 4.4.1 , CAN WORK!!!
魅蓝note5，当前最新flyme版本号7.1.5.0A（稳定版）情况下。4.7.0版本还是会出现“后台启动错误，请选择配置文件”的错误
换回4.4.1之后就能连接了，应该是Flyme 版本的问题！（Buggy Flyme!!!)
