### ISSUE TITLE
play新版更新后无法使用

### ISSUE THREAD

**Issue by alickglyn** [shadowsocks/shadowsocks-android#1590]
* Android version: 8.1.0 OPM3.171019.013
* Device: Nexus 6P
* Shadowsocks version: 4.4.5
* Last version that did not exhibit the issue (if applicable):4.1.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

问题：4.4.5更新后，显示已连接，但是实际无法连接。退回4.1.8正常。

**Comment by alickglyn** [comment]
找到问题了，原来一直用nat模式（讨厌那个钥匙），而开启nat模式后，更新4.4.5就会导致无法联网。

**Comment by Mygod** [comment]
There's no NAT mode in 4.4.5.

**Comment by madeye** [comment]
It's expected. Read the FAQ for more details.
