### ISSUE TITLE
透明代理模式下无法穿墙

### ISSUE THREAD

**Issue by ccc1924** [shadowsocks/shadowsocks-android#1591]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android 8.0 Huawei Mate9
* Huawei Mate9
* Shadowsocks version: 4.4.5
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [*] IPv4 server address
* [ ] IPv6 server address
* [*] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-cfb
* Route
  * [*] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:：使用透明代理模式

### What did you do?
使用透明代理模式，透明端口8200

### What did you expect to see?
正常访问Google

### What did you see instead?
无法访问Google（chrome浏览器）

**Comment by Mygod** [comment]
Stop using advanced options if you don't know what they are.

**Comment by callzhang** [comment]
Three is no document about this and I cannot find answers on Google. So stop blaming others when you don't provide useful information. @Mygod
