### ISSUE TITLE
Idea: DNS resolving for socks2tun the "fast way"

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#1595]
Inspired by #1594 and terrible network conditions like EDGE or satellite networks (extremely high round-trip time and/or package drop rate), here's one possible way to make this app works better under extremely bad conditions.

1. Set up local DNS server, use a bi-map (a one-to-one map function, implementation could be e.g. 2 hashmaps) to map domain names to "fake"/local IPv6 (it's very hard if not impossible to do this for IPv4 addresses) addresses and return those addresses on query;
2. In ss-local, map "fake" addresses back to domain and open connections with the original domain names.

Pro:
* Theoretically this will work better under extremely bad connectivity conditions;
* Reduced handshake time even for normal conditions;

Possible cons:
* Increased memory usage; (grows over time, is swapping possible?)
* Client doesn't support IPv6? (hopefully that's extremely unlikely nowadays)

Note: IPv6 address pool must be large enough to store all the queries (and avoid collisions).

This mode is arguably better than what we have now. Possible alternatives to this is to allow user to switch to UDP DNS (not exactly the same as the unconditional DNS forwarding option) or simply use apps that support SOCKS proxy.

**Comment by madeye** [comment]
> In ss-local, map "fake" addresses back to domain and open connections with the original domain names.

It's hard to get the original domain name, given shadowsocks works as a transparent proxy.

**Comment by Mygod** [comment]
The point here is that those are fake addresses that the dns server (or ss-local) generated and we will keep them in our bi-maps.

Currently the cheapest way to improve this is to change unconditional DNS forwarding functionality to UDP DNS in overture. Maybe we will keep the unconditional (overture-less) way for debugging purposes? (should it be a global switch?)

**Comment by Mygod** [comment]
For example, here's a figure to hopefully clear things up.

1. DNS Request (example.com) -> ss-local DNS respond with `abcd::[something random]` using the bimap
2. Connect (`abcd::[something random]`) -> ss-local connects to example.com using the bimap (fails if no entry found)

**Comment by madeye** [comment]
What about multiple hostnames on one IP? It's very common with CDNs.

**Comment by madeye** [comment]
OK, I think you mean fake IPs generated by local server.

**Comment by Mygod** [comment]
Yes. Hostnames are bijected onto fake IPs and the real resolving happens remotely.

**Comment by madeye** [comment]
Some limitations:

1. IP based rules wouldn't work anymore.
2. Direct IP accesses would be hard to handle, e.g. telegram.

**Comment by madeye** [comment]
Actually, one of my projects https://github.com/madeye/baoliandeng is using the approach for NAT.

**Comment by madeye** [comment]
> Currently the cheapest way to improve this is to change unconditional DNS forwarding functionality to UDP DNS in overture

I think we already use UDP for default DNS upstreams?

**Comment by Mygod** [comment]
1. Correct. I'm afraid we'll have to use A LOT OF hostname rules;
2. Incorrect. If IP doesn't match fake IP pattern we can just forward it without changing it. The point of fake IPs is that it's not used in real networks (there are plenty of these in IPv6 realm afaic).

I didn't know that but I suspect that it would probably be very hard and/or complicated to do this stuff for IPv4.

> I think we already use UDP for default DNS upstreams?

*reading source code and documentations*

https://github.com/shadowsocks/overture#features says:

> * Via SOCKS5 proxy (TCP only)

I'm not sure. We should verify it sometime.

**Comment by Mygod** [comment]
We can replace DNS forwarding option with DNS forwarding modes:

* TCP
* UDP
* Unconditional (overture-less)
* Extreme (beta) 😛

**Comment by madeye** [comment]
> Incorrect. If IP doesn't match fake IP pattern we can just forward it without changing it. The point of fake IPs is that it's not used in real networks (there are plenty of these in IPv6 realm afaic).

I mean some clients would connect to an IP directly without DNS resolving. For example, Telegram will connect to a random IP in its pre-defined IP pools.

**Comment by Mygod** [comment]
I don't see how this app will be affected by this change. Here's some pseudocode:

```
ss-local-connect(ip)
  if ip matches fake-ip-range
    hostname = bimap-reverse-lookup(ip)
    if not found
      return not routable # this is safe because we are using unused IP addresses
    else
      return hostname
  else
    return ip  # this is where resolving for apps like telegram will exit
```

**Comment by madeye** [comment]
OK, I know what you mean now. So, let me summary the purposed change:

1. Modify overture to return fake IPs for any hostname in the GFW list.
2. Modify ss-local to connect with hostname for any fake IP.

**Comment by Mygod** [comment]
That's basically it. Bimaps have to be shared between DNS server and ss-local so implementing those all in one executable (like ss-local) might be preferable. (or you could use mapped process memory)

**Comment by madeye** [comment]
I think we can use local socket to do the "reverse DNS lookup".

Another problem is this change would cause DNS leak as we let ss-server resolving the hostname remotely.

**Comment by Mygod** [comment]
Honestly I don't think the current overture codebase would be useful for this but I'm not familiar with overture. Implementing the whole thing in ss-local (using ANDROID preprocessor macro) sounds more reasonable to me. It's possible to implement this such that lookups are lockless (which means no inter-process/thread/kernel-userspace communication = ridiculously cheap + energy efficient + fast!).

I also don't see how this would cause any more DNS leak than the existing DNS resolution scheme. DNS leak is caused by resolving DNS locally. It seems to me that this change would only reduce the amount of DNS leakage.

Remark: we are basically doing DNS pollution therefore this should only be used under extreme connectivity conditions like mentioned in the main thread.

**Comment by madeye** [comment]
Implementing a DNS resolver in C would be very painful.

Let's add it to our wish list for now. Maybe someone else would have a better idea.

**Comment by Mygod** [comment]
Well it's just a dummy DNS resolver I don't think it would be that hard. I just had a look at rfc1035 and it seems we just need to return an AAAA record if type matches and return a not found for other record types (this could also be problematic).

**Comment by madeye** [comment]
After rethinking the whole problem, imo, the motivation seems not strong enough.

Given we have a very aggressive cache policy in overture, most of DNS queries would be fetched from local cache, rather than from remote server. Is it a real problem that slow connection would cause problems of DNS resolving?

**Comment by Mygod** [comment]
Yes I once tested it on a plane and somehow connection tests under proxy mode goes through perfectly but VPN mode is almost unusable. I'm suspecting that it's caused by TCP DNS.

**Comment by madeye** [comment]
It's hard to tell if it's caused by DNS.

If only the first connection test in VPN mode is slow, it should be related to DNS, If not, it would be related to the unstable connection itself.

There is a fix from upstream that would improve overture's performance a lot, which is already in v4.4.6. Let's see further reports to decide what's the next step.

**Comment by Mygod** [comment]
Sounds good. I'll try to do some testing on the emulator...

**Comment by Mygod** [comment]
Huh this is very interesting... I turn network mode to GSM and master branch works very well. At least when I was testing it, proxy mode works iff VPN mode works. 4.4.2 seems to perform noticeably worse but I still need to do some extra tests to make sure. For now I suspect that 982845e877c28f28e48f89add8af9c08c8be3e7f has fixed the issue.

I will close this issue for now.

**Comment by madeye** [comment]
@Mygod In my test, this upstream fix improved the performance a lot: https://github.com/shadowsocks/overture/commit/d6b1c6d1082e53b790a9f6045489551cfe88996a

Previously, I observed many "missing DNS queries" in overture, where the main loop of overture is blocked due to some reason.

**Comment by Mygod** [comment]
After doing some further test, I can't tell the difference any more.

However I noticed one pattern that's consistent throughout 4.4.2-4.4.6+.

```
43.492418 IP 26.26.26.1.62658 > 8.8.8.8.53: 53885+ AAAA? www.google.com. (32)
44.281168 IP 8.8.8.8.53 > 26.26.26.1.62658: 53885 1/0/0 AAAA [google-ipv6] (74)
44.281304 IP 26.26.26.1.54732 > 8.8.8.8.53: 45313+ A? www.google.com. (32)
44.886580 IP 8.8.8.8.53 > 26.26.26.1.54732: 45313 1/0/0 A [google-ipv4] (62)
44.903938 IP 26.26.26.1.56471 > [google-ipv4].443: Flags [S], seq 4090527169, win 4380, options [mss 1460,sackOK,TS val 432433 ecr 0,nop,wscale 3], length 0
...more communication between 26.26.26.1 and google-ipv4...
```

It seems like overture is requesting AAAA and A in serial (bad?) and IPv6 address isn't used even though it's requested first. Is this the intended behavior? @madeye

**Comment by madeye** [comment]
@Mygod It should be an issue of overture. Let me find a way to improve it.

**Comment by Mygod** [comment]
@madeye Any update on this?

**Comment by Mygod** [comment]
Okay so apparently it is caused by `ChooseActiveClientBundle`. I think I will implement a DNS server from scratch in pure Kotlin instead. Coming soon to #2092.
