### ISSUE TITLE
SS在oneplus 5 安桌8.0下不能自动启动

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-android#1596]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0.0 版本：OP5_H2_Open_3 内核：4.478-perf+OnePlus@ubuntu-152#1Sat Jan 1300：18：10 CST2018
* Device: Oneplus 5
* Shadowsocks version: 4.46
* Last version that did not exhibit the issue (if applicable): 在使用安卓7.1时，SS能开机自动启动

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:  aes-128-gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ x] GFW List
  * [ ] China List
  * [  x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [x ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
设置里打开 自动连接 和 直接启动 （手机没有root,TCP Fast Open自动打开的）

### What did you expect to see?
开机后SS能自动启动

### What did you see instead?
开机后SS没有自动启动

**Comment by triaqu** [comment]
补充一下，SS使用simple-obfs 0.0.5插件，在系统应用设置里，SS权限管理只有相机一项，系统的权限管理里没有自启动管理。已关闭了SS的电池优化。

**Comment by heiybb** [comment]
Auto startup works well in **Oneplus5**(OxygenOS 5.01 Android Version:8.0.0 Shadowcsocks 4.4.6)
You should wait about 20s for system to wake up the shadowsocks service  
or it might be the problem of  **Hydrogen** system

**Comment by triaqu** [comment]
重启试了下，等了1分钟以上没启动。
另外，直接点状态栏SS图标也无不能启动，要长按打开SS后，才能启动。
用的氢8.0.

**Comment by triaqu** [comment]
@heiybb 谢谢提醒。是我设置问题，打开VPN图标，在影梭设置里把始终开启VPN打开就行了。
