### ISSUE TITLE
SSL handshakes times out  (version 4.4.5 )

### ISSUE THREAD

**Issue by HuiCukmen** [shadowsocks/shadowsocks-android#1598]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0
* Device: Oneplus 3
* Shadowsocks version: v4.4.5
* Last version that did not exhibit the issue (if applicable):
4.4.4
### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by wenhelinlu** [comment]
Same question，one plus 5T，Android7.1.1

**Comment by findlayfeng** [comment]
Same question，Galaxy S6 edge +，Android7.0

**Comment by hadeschan1985** [comment]
Same question，LE MAX2 Android 6.01
