### ISSUE TITLE
fd_recv.c fd_send.c 这两个文件在目录下面找不到

### ISSUE THREAD

**Issue by HarryPotter528** [shadowsocks/shadowsocks-android#1599]
########################################################
########################################################

include $(CLEAR_VARS)

ANCILLARY_SOURCE := fd_recv.c fd_send.c

LOCAL_MODULE := libancillary
LOCAL_CFLAGS += -I$(LOCAL_PATH)/libancillary

LOCAL_SRC_FILES := $(addprefix libancillary/, $(ANCILLARY_SOURCE))

include $(BUILD_STATIC_LIBRARY)

**Comment by Mygod** [comment]
Read README.md.
