### ISSUE TITLE
更新过shadowsocks之后，我的手机facebook客户端和messenger不能登录了，一直提示检查网络设置

### ISSUE THREAD

**Issue by lublues** [shadowsocks/shadowsocks-android#1601]
更新过shadowsocks之后，我的手机facebook客户端和messenger不能登录了，一直提示检查网络设置，但是我在浏览器里面可以登录网页版的facebook。并且其他应用 google play 也可以正常登录

facebook的存储权限也打开了。

PS:我更改路由规则为   绕过局域网和大陆地址，facebook客户端可以登录，但是，图片加载不出来
改为全局模式，facebook客户端可以正常登陆以及加载图片

但是全局模式使用，还有很多不需要fq的。
手机应用80%不需要fq，但是fq应用我基本是全天开启的。
不知道应该怎么调整。。。

**Comment by lublues** [comment]
啊啊啊啊啊，突然发现全局模式也失效了。。。图片加载不进来了。

**Comment by lublues** [comment]
试了一个小时，问题解决了。。我估计应该是ipv6的转发开关的问题。我关闭ipv6之后，貌似一切正常了。
![screenshot_20180125-101842](https://user-images.githubusercontent.com/18481641/35367497-89ab1e1c-01b9-11e8-9b76-36b8fb339ddd.png)

**Comment by Tlfebook** [comment]
对于vpn能用但连接facebook或ins失败的状况，解决真实有效，感谢！

**Comment by Yichengxuan** [comment]
感谢大佬的指点，已经解决！

**Comment by kwrong** [comment]
我试过啦，开着ipv6也能正常打开啊

**Comment by hdrafyy** [comment]
直的是ipv6的问题，我关了就正常了。

**Comment by hdrafyy** [comment]
真的是ipv6的问题，我关了就正常了。

**Comment by joedyyoung** [comment]
感谢大佬，已经解决
