### ISSUE TITLE
Can't set localhost for dnscrypt address in remote dns.

### ISSUE THREAD

**Issue by odkrys** [shadowsocks/shadowsocks-android#1605]
I set the remote dns 127.0.2.1 to use dnscrypt-proxy in my vps.
But with the latest update, it doesn't work anymore and showing bad address.
Any change to fix this error ?

**Comment by madeye** [comment]
Don't use private IP for remote DNS. Try your VPS' IP instead.

**Comment by odkrys** [comment]
I am getting following server error log if I set vps ip for remote dns.

ERROR: getpeername: Transport endpoint is not connected

Here is the server config.
```
{
    "server":"VPS IP",
    "server_port":PORT,
    "local_port":1080,
    "password":"PASSWORD",
    "timeout":60,
    "nameserver":"127.0.2.1",
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls"
}
```
To use dnscrypt-proxy, I set name server as 127.0.2.1.
It is working with ss-local + kcptun on my router, but not the latest android client. (It worked before)

**Comment by Mygod** [comment]
I'd suspect that `tun2socks` isn't picking up DNS requests sent there. But I agree that you should probably not use local address as server addr.
