### ISSUE TITLE
May you add "customize china dns"?

### ISSUE THREAD

**Issue by santaclausbaby** [shadowsocks/shadowsocks-android#1607]
You know that lots of china isp making a dns hijacking to insert some advertisement or to monitar users. So default dns distributed by isp is unsafe.

**Comment by Mygod** [comment]
Just specify your local DNS in your system settings.

**Comment by santaclausbaby** [comment]
Well, it's impossible for non-root devices. I think it is good to users for a VPN-like app just like SS Android.
