### ISSUE TITLE
缺少pcre相关项目库，其他的相关的都可以下载下来

### ISSUE THREAD

**Issue by juwusheng** [shadowsocks/shadowsocks-android#1608]
楼主可以排查下，没有pcre相关库地址
![qq 20180127113929](https://user-images.githubusercontent.com/18287999/35468340-c59821b0-0356-11e8-8db6-0b1b94bcf09f.png)

**Comment by juwusheng** [comment]
其他相关链接库使用git submodules可以下载下来，只要这个无法下载，注意下看下跟其他公共库链接颜色不一样
![image](https://user-images.githubusercontent.com/18287999/35468381-534cca60-0357-11e8-8c76-33751f6252d3.png)

**Comment by pexcn** [comment]
`git submodule update --init --recursive`

**Comment by juwusheng** [comment]
![image](https://user-images.githubusercontent.com/18287999/35482509-8f41e364-0471-11e8-9875-2e4ce956ed72.png)
使用git submodule update --init --recursive，已经尝试很多次，无法获取pcre库

**Comment by Einsteinford** [comment]
@juwusheng 由于 https://android.googlesource.com/platform/external/pcre [是墙内难以访问的地址(感谢你提供这个地址，我也卡住了)，所以需要自己想聪明的方法去clone，我下载好了，打包给你地址](https://pan.baidu.com/s/1htdvgqC)

**Comment by juwusheng** [comment]
多谢，已解决此问题，我直接从网上下载了prce的库

**Comment by juwusheng** [comment]
@Einsteinford 谢谢已解决此问题

**Comment by amokGithub** [comment]
git 要设置代理

**Comment by SmileToMe** [comment]
@juwusheng  问题是什么解决的啊 ? 我卡着好几天了 实在不知道怎么解决了？能不能发一份能编译的源码给我吗？563241845@qq.com

**Comment by SmileToMe** [comment]
@Einsteinford   问题是什么解决的啊 ? 我卡着好几天了 实在不知道怎么解决了？能不能发一份能编译的源码给我吗？563241845@qq.com

**Comment by juwusheng** [comment]
pcre是一个c++正则库，自己可以网上下载一份，放进去就行了。github无法直接代码下载是因为国内防火墙的原因。下载参考地址https://ftp.pcre.org/pub/pcre/

**Comment by imkobedroid** [comment]
> @Einsteinford 谢谢已解决此问题

大神 怎么解决的呢 我这边也遇到了 很急  你可以发一份编译好的源代码到我邮箱嘛？379760818@qq.com 谢谢
