### ISSUE TITLE
Android TV can not navigate to some menu using controller

### ISSUE THREAD

**Issue by tony1016** [shadowsocks/shadowsocks-android#1609]
### Environment

Android version: 7.0
Device: Nvidia Shield TV
Shadowsocks version: 4.4.6

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Normal navigate to ENCRYPT METHOD SELECTION or ROUTE SELECTIONG

### What did you expect to see?

Focus on it and Popup the selection items

### What did you see instead?

Can't focus on the menu,no selection shadow appearance

**Comment by Mygod** [comment]
Can't reproduce on Android 8.1. Could you show us a screenshot/capture?

Also there's this upstream bug blocked by upstream: https://github.com/mikepenz/MaterialDrawer/issues/2173

Please just wait for a TV version to come out hopefully sometime this year. Meanwhile use a USB/Bluetooth mouse as a workaround.

**Comment by tony1016** [comment]
just like this

https://drive.google.com/file/d/1507z69oTClGwAKUJkMwljyY3g0ryc5lX/view?usp=sharing

**Comment by williamjoy** [comment]
+1 same here

**Comment by Mygod** [comment]
Please wait for https://github.com/Gericop/Android-Support-Preference-V7-Fix/pull/142 to be merged.
