### ISSUE TITLE
Whether to support AES hardware acceleration?

### ISSUE THREAD

**Issue by giftzn** [shadowsocks/shadowsocks-android#1613]
Some CPUs on the mobile platform have AES instructions (such as Snapdragon 835).
 If I use AES encryption, does the client speed up using the CPU's AES instructions?

**Comment by wongsyrone** [comment]
Nope.

**Comment by madeye** [comment]
On mobile devices, chacha20 is always preferred.

**Comment by giftzn** [comment]
Thanks Reply.
