### ISSUE TITLE
Not work at EMUI8.0

### ISSUE THREAD

**Issue by caodianlong** [shadowsocks/shadowsocks-android#1614]
I ugrade system from EMUI5.1 to EMUI8.0， shadowsocks-android do not work again. It can connetc successfully, and test well,  but all the other apps can't connect any website。
my shadowsocks server work healthly.

### Environment
* sSystem: HUAWEI EMUI8.0（Android 8.0.0）
* Device: HUAWEI Honor V9
* Shadowsocks-android version: V4.4.6
* Last version that did not exhibit the issue (if applicable):

**Comment by TessChan** [comment]
Is this problem going to fix?I am using HUAWEI EMUI8.0 too....

**Comment by madeye** [comment]
Report to Huawei, as it's a bug of EMUI.

**Comment by caodianlong** [comment]
uninstall and reinstall the app，it is OK now.
this problem seemingly occur after  upgrade  system,  the same as #888
