### ISSUE TITLE
compatibility issue with ss-libev ipv6_fist mode

### ISSUE THREAD

**Issue by wrlssqi** [shadowsocks/shadowsocks-android#1616]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android 8.1
* Device: Pixel 2
* Shadowsocks version: V4.4.6
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
server ss is ss-libev, and ipv6_first mode turned on. Because the ipv4 address of my vps has been banned by google scholar, so I set ipv6 address of scholar domain in vps hosts file. 

### What did you expect to see?
On my phone, when I search "ip" by google.com, the ipv6 address of my vps should be shown in search result(cause i turn on ipv6_first mode on vps server), and I can access google scholar. 

### What did you see instead?
On my phone, when I search "ip" by google.com, the ipv4 address of my vps is shown in search result, and I can't access google scholar. On my windows PC, ss csharp client is used and works well with server's ipv6_first mode(when i search "ip" in google.com, the result displays the ipv6 address of my vps, and I can access google scholar). Both my pc and phone are in the same network situation. I tried to turn on the "IPv6 route" config in ss android, but it still doesn't work  as I expect.

Sorry for my poor english.

**Comment by madeye** [comment]
First of all, enable IPv6 route in your Android app.

**Comment by wrlssqi** [comment]
With IPv6 route disabled: I can't access ipv6.google.com; When I search "ip" by www.google.com, the result displays the ipv4 address of my vps; I can't access google scholar. 
With IPv6 route enabled: I can access ipv6.google.com; When I search "ip" by www.google.com, the result displays the ipv4 address of my vps; I can't access google scholar. 

The only difference is that i can access ipv6 resources when IPv6 route is enabled. But when I access dual-stack resources, ipv4 network is used first, so  ipv6_first mode on ss server side failed.  With windows csharp client,  ipv6_first mode works as expected.

**Comment by madeye** [comment]
1. As shadowsocks-android works as a transparent proxy and all the DNS queries happen locally, the "ipv6_first" option in your server won't work.
2. Since you can access IPv6 web sites correctly, IPv6 routing should work correctly on your device.
3. If your browser prefer IPv4 address to IPv6, it's not an issue related to shadowsocks.
