### ISSUE TITLE
What is the functionality of the  default_configs.xml file in mobile/src/main/res/xml directory?

### ISSUE THREAD

**Issue by chinmoyden** [shadowsocks/shadowsocks-android#1618]
This file makes a request to another server https://socks123.azureedge.net/get.php . What is the functionality of this get.php file? Is this for delivering the default config that comes with the default installation from google play or serving ads?

**Comment by whour** [comment]
This is Default profile when you first install the app.

**Comment by chinmoyden** [comment]
Hello,

Why close the question without the ability of further discussion? I would like to know how this is implemented
