### ISSUE TITLE
"Proxy Only" mode: trying to connect to OpenVPN TCP server but it resets upon connection and repeats

### ISSUE THREAD

**Issue by privatevpnsupportguy** [shadowsocks/shadowsocks-android#1620]
### Environment

* Android version: Android 8.0.0
* Device: Oneplus 5 (128GB)
* Shadowsocks version on Android: *version code "v4.4.6"
* Shadowsocks on Ubuntu Server 16.04: Shadowsocks-libev

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

I put 'socks-proxy 127.0.0.1 1080' in client.ovpn to connect to a OpenVPN TCP server via SS running in Proxy Only mode on my Android using OpenVPN for Android App. 

I even tried putting 'route <SS's server IP> 255.255.255.255 GATEWAY_IP' in client.ovpn in addition to above like I do when I connect using Tor socks proxy. 

### What did you expect to see?

I expected it to connect using SS's proxy just fine like it does on GNU/Linux or Windows. It works perfectly fine there just like with Tor's socks proxy. No issues at all. 

### What did you see instead?

In OpenVPN error logs, what I see is it connects fine and then resets with the log entry:

Connection reset, restarting[0]

What I assume is that it is because OpenVPN is forcing SS's proxy via its default route too, hence I tried adding the following route in client.ovpn to create an expection:

route <SS's server IP> 255.255.255.255 GATEWAY_IP

So that this IP is excluded from OpenVPN routing, but nothing. It still resets and does not work.

Please help me. I have also tried 'Route Bypass LAN'.

Is it a shadowsocks error? Can you reproduce it? Or is it just fine?

**Comment by madeye** [comment]
If your OpenVPN client supports per-app VPN, try to exclude shadowsocks from the list.

**Comment by privatevpnsupportguy** [comment]
Did the trick. You are an amazing personality. You rock! It works now.
