### ISSUE TITLE
shadowsocks4.4.6不能使用Google play

### ISSUE THREAD

**Issue by qvjp** [shadowsocks/shadowsocks-android#1623]
如题，打开代理后其他应用（Gmail、Chrome等）均可正常使用，可就是打不开Google play，关闭shadowsocks后，用蓝灯就可以用Google play了，求解，到底是shadowsocks的bug，还是我哪里需要为Google play特殊配置。

手机是Nokia7 Android8.0

**Comment by Mygod** [comment]
Use bypass mode.

**Comment by qvjp** [comment]
@Mygod I use bypass mode but still can not access Google play. error code DF-DFERH-01

**Comment by Mygod** [comment]
Read labels.

**Comment by junbujianwpl** [comment]
哪个版本不需要google play service来着  天朝特殊情况真烦人

**Comment by mumuxizzz** [comment]
@junbujianwpl 同求

**Comment by jp1017** [comment]
@junbujianwpl @mumuxizzz 4.4.6 :smile:
