### ISSUE TITLE
Select the configuration file but can not start

### ISSUE THREAD

**Issue by jinkun2014** [shadowsocks/shadowsocks-android#1624]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: MEIZU PRO 5
* Shadowsocks version: v4.4.2 v4.4.3 v4.4.4 v4.4.5 v4.4.6 
* Last version that did not exhibit the issue (if applicable): v4.4.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Uninstall the old version, install the new version, 

卸载旧版本，安装新版本

### What did you expect to see?
Like the previous version, the connection is successful and the service is started

像以前版本一样，连接成功，并启动服务

### What did you see instead?
when the installation is complete, the first entry appears flashback, the second into the selected default configuration, click on the button, the bottom of the "please select the configuration file" prompt, I enter your own configuration Use, has been prompted to choose the configuration, I think it is not a bug in the choice of configuration files

当安装完成时，第一次进入出现闪退，第二次进入选中默认配置，点击按钮，底部出现"请选择配置文件"的提示，我输入自己的配置也没有用，一直提示让我选择配置，我想是不是在选择配置文件时出现bug

**E.g (v4.4.2 v4.4.3 v4.4.4 v4.4.5 v4.4.6):**

![v4.4.2](https://user-images.githubusercontent.com/11567175/35716363-7dcbf8e0-0813-11e8-8cc6-912f4d0a4538.png)

**E.g (v4.4.1):**

![image](https://user-images.githubusercontent.com/11567175/35716484-35596f7e-0814-11e8-81ba-40597644dd02.png)

**Comment by Mygod** [comment]
Read FAQ or gtfo.
