### ISSUE TITLE
Can't access Google play app

### ISSUE THREAD

**Issue by qvjp** [shadowsocks/shadowsocks-android#1625]
### Environment

* Android version: *"8.0.0"*
* Device: *Nokia 7*
* Shadowsocks version: *version code "v4.4.6"*

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: CHACHA20
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable): Disabled
* [x] Auto Connect
* [x] TCP Fast Open

### What did you do?
I connected shadowsocks, and I can access Google play website, but can't access the Google play app.

### What did you expect to see?
I expect I can access the Google play app.

### What did you see instead?
I can not access the Google play store.
Google play app:
![screenshot_2018-02-02-13-56-06](https://user-images.githubusercontent.com/17522949/35719163-085617d4-0823-11e8-99d3-e6b8a16eee4f.png)

Google play website:
![screenshot_2018-02-02-14-10-55](https://user-images.githubusercontent.com/17522949/35719172-13669b1c-0823-11e8-97e2-938234e2dad5.png)

**Comment by Mygod** [comment]
Try using Bypass LAN & China or custom rules.

**Comment by qvjp** [comment]
@MygodStill not available:cry:

**Comment by lihsai0** [comment]
@qvjp The same problem. Have you solved it?

**Comment by qvjp** [comment]
@lihsai0 有两种解决方法
1 换服务器，我当初就是腾讯云香港地区服务器，不行，换了个新加坡的，可以了。 
2 手机root后删除删除/etc/permissi*/services.cn.google.xml
