### ISSUE TITLE
vpn successfully connected and then immediately test the connection is found to be very slow

### ISSUE THREAD

**Issue by pzl237** [shadowsocks/shadowsocks-android#1628]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1
* Device: Google Nexus 6p
* Shadowsocks version:  commit ID "daea4b5f6cd350fe473f6ea22594da2f8c3b487e"
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Use your own profile, vpn successfully connected, immediately call MainActivity.testConnection test vpn is really available.

### What did you expect to see?
Expect: Using your own profile, vpn connects successfully and immediately calls MainActivity.testConnection to test that vpn is truly available, rather than having to wait for more than 5 seconds or longer.

### What did you see instead?
vpn successful connection, immediately test whether the connection is available, it takes 5 seconds or longer, test again soon, almost a few hundred milliseconds.

**Comment by madeye** [comment]
It's expected, as DNS cache is flushed at that point.
