### ISSUE TITLE
unable to build the source

### ISSUE THREAD

**Issue by wekky43** [shadowsocks/shadowsocks-android#1629]
I have installed all the prerequisite and tried to build the project. Got this error. if anyone could help please.

External Native Build Issues
Build command failed.
Error while executing process C:\Users\Waqas\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Android_projects\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\Android_projects\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -ID:/Android_projects/shadowsocks-android-master/core/src/main/jni/libancillary -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/Android_projects/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/Android_projects/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o
md "D:\Android_projects\shadowsocks-android-master\core\buiprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_projects/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
ld\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
Build command failed.
Error while executing process C:\Users\Waqas\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\Android_projects\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\Android_projects\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"
copy /b/y "C:\Users\Waqas\AppData\Local\Android\sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86" > D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot D:/Android_projects/shadowsocks-android-master/core/src/main/jni C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/support C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/support/include C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures D:/Android_projects/shadowsocks-android-master/core/src/main/jni/libancillary C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include D:/Android_projects/shadowsocks-android-master/core/src/main/jni/mbedtls/include D:/Android_projects/shadowsocks-android-master/core/src/main/jni/pcre/dist D:/Android_projects/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv4 D:/Android_projects/shadowsocks-android-master/corep/rocess_begin: CreateProcess(NULL, "", ...) failed.
src/main/jni/ba
make: *** No rule to make target `D:/Android_projects/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.
dvpn/lw
ip/src/include/ipv6 D:/Android_projects/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custom" >> D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -ID:/Android_projects/shadowsocks-android-master/core/src/main/jni/libancillary -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/Android_projects/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/Android_projects/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem
md "D:\Android_projects\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -IC:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
C:/Users/Waqas/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a D:/Android_projects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

**Comment by Mygod** [comment]
Read your error log.

**Comment by tidatida** [comment]
@wekky43  Hello, have you passed compiling successfully?  I failed too, but I known one more git command to do, in ShadowSocks-android/  , EXECUTE:  # git submodule  update --init  ,    fetch out third-party  sources. 

But I stilled failed. The first line looks the same to that you posted above.  I am new on android, I feel sad this issue closed , but not give out any useful info.

**Comment by jackrow** [comment]
@wekky43 I have the same problem. Have you solved it?

**Comment by jackrow** [comment]
git submodule update --init --recursive？
