### ISSUE TITLE
锤子坚果Pro2 创建VPN服务权限不足

### ISSUE THREAD

**Issue by Thiece** [shadowsocks/shadowsocks-android#1630]
坚果Pro2
Smartisan 4.1.5 （Android 7.1.1）
shadowsocks 4.4.6

点击连接，创建VPN服务权限不足，系统设置中没有对于VPN权限相关的选项。

shadowsocksR 3.4.0.6 可以正常使用

**Comment by moleen** [comment]
设置->更多无线和网络设置->VPN->开启始终此VPN

**Comment by noqnakhier** [comment]
@moleen VPN里没有影梭的选项。把影梭删除后再重新安装，VPN里的影梭没了

**Comment by Mygod** [comment]
Ranting will never solve your issue.

**Comment by neworcer** [comment]
二楼正解，要是vpn设置清空了，重启下就可以了。

**Comment by arshcaria** [comment]
如果你同时安装并使用过SSR，尝试删除SSR与SS并重启（如果需要，记得备份SSR），重启后只安装SS，这样应该就可以看到SS申请VPN权限的弹窗了。

**Comment by coolearn** [comment]
大神们问下，坚果Pro2s下载哪个版本的zpk

**Comment by Thiece** [comment]
> 大神们问下，坚果Pro2s下载哪个版本的zpk

v8a

**Comment by Quasimo** [comment]
重启。

**Comment by jackwang1993** [comment]
我是 pro 2s ，

1. （设置->更多无线和网络设置->VPN->开启始终此VPN ）设置好以后还是没有。
2. 卸载了  ss 和 ssr   
3. 重启手机
4. 下载 ss 并配置好
5.搞定啦

**Comment by jiangen1016** [comment]
锤友你好

**Comment by yuyistar** [comment]
@Thiece 你最后成功了吗
