### ISSUE TITLE
启动后台服务失败:请选择配置文件

### ISSUE THREAD

**Issue by backav** [shadowsocks/shadowsocks-android#1631]
* Android version: 7.1.1 (Meizu Flyme 6.3.0.1A)
* Device: Meizu Pro 6
* Shadowsocks version: 4.4.6
* Last version that did not exhibit the issue (if applicable):

选中配置,点击连接按钮,提示"启动后台服务失败:请选择配置文件"。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1589

**Comment by ykla** [comment]
emui 8.0复现
