### ISSUE TITLE
无法刷新 Instagram，其它 App 正常

### ISSUE THREAD

**Issue by kid1412621** [shadowsocks/shadowsocks-android#1632]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0
* Device: Oneplus 5T
* Shadowsocks version: 4.4.6
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:rc4-md5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you expect to see?
无法连接 Instagram（App），无法刷新，其它 App 没事。
然而使用 ssr-android，同一服务器同一配置就能连接。
Btw，如何查看 log？

**Comment by madeye** [comment]
Disable IPv6 and try again.

**Comment by madeye** [comment]
Your server's IPv6 address is blocked by Instagram.

**Comment by kid1412621** [comment]
@madeye OMG! It works ! Is there any workaround to solve this issue on the server side except turing off ipV6 on the client side ?
Thanks anyway.

**Comment by madeye** [comment]
Instagram won't fall back to IPv4, if the IPv6 link doesn't really work. That's the root cause.

**Comment by zhaijiayu12345** [comment]
牛逼

**Comment by YanHuiLi** [comment]
没有ipv6的选项啊？

**Comment by yangjingce** [comment]
请问如何禁用ipv6？

**Comment by yumengsong** [comment]
Yes! Solved my problem! Thank you.
If you are using a shadowsocks app on your phone, just disabled the IPv6 in that app.
You will find the option in the settings.

**Comment by zhongqin0820** [comment]
close ipv6 option in the app configuration settings

**Comment by BaLaLaLs** [comment]
thanks!

**Comment by tempofan** [comment]
my version is 4.7.4,  IPV6 already been turned off，but still cant refreshing APP (facebook& Instagram)， need helps

**Comment by wudan3551** [comment]
it works

**Comment by qiuqiran** [comment]
666
