### ISSUE TITLE
EMUI 8.0 cannot use ss

### ISSUE THREAD

**Issue by hrzhao76** [shadowsocks/shadowsocks-android#1633]
下载最新版之后线路不能用。 换了其他的版本也是如此。应该是EMUI8.0的问题

**Comment by Zhwt** [comment]
TCP Fast Open 选项默认保持开启状态无法关闭, 清除数据或重新安装无法解决, EMUI5.0(Android 7.0)可用, 机型荣耀V9(DUK-AL20)
