### ISSUE TITLE
Can't connect to server when using VPN mode

### ISSUE THREAD

**Issue by wegood9** [shadowsocks/shadowsocks-android#1643]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 5.0.1 *Flyme OS 4.5.7.1A*
* Device: Meizu MX2
* Shadowsocks version: v4.4.6
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:
Can't connect to server on (might be) any shadowsocks-android version using vpn mode.

### What did you do?
Upgraded shadowsocks-android and found that nat mode is deprecated.

### What did you expect to see?
Connect to server successfully.

### What did you see instead?
`No Internet connection:Failed to connect to www.google.com/173.252.110.21(port 443) after 10000ms`
The network situation do not change after launching shadowsocks.

Transproxy and Proxy only mode also don't work.Testing connection prompted `Malformed reply from SOCKS server`

[logcat.log](https://github.com/shadowsocks/shadowsocks-android/files/1756100/logcat.log) including switching to 3 different modes

**Comment by madeye** [comment]
Flyme OS is known to not work with shadowsocks. Read the FAQ for more details.
