### ISSUE TITLE
Get wrong DNS result. How local DNS server is decided？

### ISSUE THREAD

**Issue by eastpiger** [shadowsocks/shadowsocks-android#1644]
Type of changes
Put an x inside the [ ] that applies.

[x] Bugfix
[ ] New feature
[ ] Translation
[ ] General refinement

Other:

[When not use shadowsocks]
In my campus, when using WiFi, I will get a dns server (10.xx.xx.xx) from DHCP. Some internal used domains have different ip (eg. For www.xxxx.com, get 10.xx.xx.xx in campus network dns, but 119.xx.xx.xx outside dns). It works as we expected.

[when using shadowsocks]
I select route GFWList. But cannot visit these internal used domains, because all of the dns to shadowsocks dns ports return 119.xx.xx.xx(ip which should be used outside campus network). It seems that this result doesn't come from the dns given by DHCP. 

DNSforwarding is not checked, this domain isn't listed in GFWList. So it's supposed to be transport to local dns server, right？so how shadowsocks.android decide the local dns server？ Can I change it？

**Comment by madeye** [comment]
It's expected.

A workaround is using Apps VPN mode, and excluding the browser that you want to use with internal web sites.

**Comment by Mygod** [comment]
If we change this behavior to fix the issue described, we will have the issue of DNS pollution instead.
