### ISSUE TITLE
Testing Delay Shows Much More Increase After Upgrading To 4.5.0

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/shadowsocks-android#1645]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: xchacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Upgrade from 4.4.6 to 4.5.0

### What did you expect to see?
Delay test shows the same delay time or similar delay time in both 4.4.6 and 4.5.0

### What did you see instead?
Delay test on 4.4.6 shows 200 ~ 300 ms, but on 4.5.0, delay test increases to 1000 ~ 2000 ms

**Comment by Mygod** [comment]
It's expected. Since 4.5.0 this test result will correctly represent the time it takes to perform a TLS handshake.
