### ISSUE TITLE
[4.5.0] The delay shown is significantly increased after tested successful

### ISSUE THREAD

**Issue by eastmalon** [shadowsocks/shadowsocks-android#1648]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1.0, LineageOS 15.1
* Device: Xiaomi mi 5
* Shadowsocks version: 4.5.0
* Last version that did not exhibit the issue (if applicable):4.4.6

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: aes-128-gcm
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
In different versions, I tested delay of the same configuration

### What did you expect to see?
The delay displayed in 4.5.0 should consistent with the previous version

### What did you see instead?
4.4.6: 65 - 80ms
4.5.0: 320 - 480ms

**Comment by madeye** [comment]
It's expected. https://github.com/shadowsocks/shadowsocks-android/issues/1645
