### ISSUE TITLE
不能用ss android来代理碧蓝航线日服客户端

### ISSUE THREAD

**Issue by OceanEyeFF** [shadowsocks/shadowsocks-android#1650]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
希望能够正常用ss代理日服碧蓝航线

### What did you expect to see?
成功代理

### What did you see instead?
不能代理？

据说是ss的协议问题。具体我不是很懂……所以来问一下大佬qwq

**Comment by madeye** [comment]
If it's a UDP based app, make sure you have enabled UDP forwarding in the server.

**Comment by OceanEyeFF** [comment]
thanks. but the udp connection is fine
