### ISSUE TITLE
自带浏览器翻不了墙，instagram也不行，其它基本可以什么原因

### ISSUE THREAD

**Issue by jackallam** [shadowsocks/shadowsocks-android#1651]
如题，之前用过不知什么版本的shadowsocks完全没问题，就是老是打不开shadowsock，每次用都要重新安装，退出就不能再用了。

于是才换了这个4.4.6版本，手机自带的浏览器翻不了墙，用chrome就可以。instagram也返不了，但是youtube可以，twitter和facebook没下载不知道，不过有2个香港的新闻软件也可以返。

究竟问题出在哪？设置问题吗？

**Comment by jackallam** [comment]
我用了一个3.3.1版本的就没问题了，应该是软件有bug

**Comment by jackallam** [comment]
现在发现3.3.1google play 上不了~~~~晕~

**Comment by zhengwuji** [comment]
你们真是的，没搞错的话！作者看不懂中文！应该写英文给作者看，如果可以的话，提供一下工作日志！
