### ISSUE TITLE
没有一种模式适合，不知道你们用哪个模式

### ISSUE THREAD

**Issue by coolicer** [shadowsocks/shadowsocks-android#1656]
用全局模式，正常。但是并不想全部流量走全局，如果走全局+APP分应用，google更新AP不能下载，一直速度为0。

其他模式
会影响其他APP，要不就是不能代理。

现在如果要更新play store的app，只能切换全局模式，更新完成再暂停加上分应用VPN。

**Comment by madeye** [comment]
Try bypass mode.

**Comment by coolicer** [comment]
@madeye 大佬，这个模式google 服务有时候不行，是不是DNS的问题？
