### ISSUE TITLE
Scan QR code and get unrecognized URI

### ISSUE THREAD

**Issue by 914802951** [shadowsocks/shadowsocks-android#1657]
* Android version: 7.1.2
* Device: RedMi 5
* Shadowsocks version: v4.4.6 & v4.5.0

03-03 17:26:59.794  3088  3088 I Timeline: Timeline: Activity_launch_request time:308398722
03-03 17:26:59.831  2603  2793 I WtProcessController: FOREGROUND INFO: name=com.github.shadowsocks uid=10140 pid=3088 TaskId:1178
03-03 17:26:59.861  3088  3088 W DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
03-03 17:26:59.866  3088  3088 I DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1402
03-03 17:26:59.866  3088  3088 I DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1402
03-03 17:26:59.871  3088  3088 I Vision  : Loading library libbarhopper.so
03-03 17:26:59.872  3088  3088 I Vision  : libbarhopper.so library load status: true
03-03 17:27:00.158  3088  3167 D OpenGLRenderer: endAllActiveAnimators on 0x7f7e669400 (MenuPopupWindow$MenuDropDownListView) with handle 0x7f7db4d620
03-03 17:27:01.000  3088  3088 E ShadowParser: Unrecognized URI: ss://YWVzLTI1Ni1jZmI6MjIwNTI3NTRAYi5pc3hiLmJpZDoxNTQ3OQo=
03-03 17:27:01.044  3088  3088 D Camera  : app passed NULL surface
03-03 17:27:01.424   725  1564 I CameraService: disconnect: Disconnected client for camera 0 for PID 3088
03-03 17:27:01.433  2603  2793 I WtProcessController: FOREGROUND INFO: name=com.github.shadowsocks uid=10140 pid=3088 TaskId:1178

**Comment by madeye** [comment]
The URL is not valid. Read the documents on shadowsocks.org for more details.
