### ISSUE TITLE
4.5.0启动服务后，在SS主界面测试连接延时高

### ISSUE THREAD

**Issue by hkfires** [shadowsocks/shadowsocks-android#1658]
4.5.0启动服务后，在SS主界面测试连接延时高，从300+ms到800+ms不等。
装回4.4.6后，测试连接延时稳定在160ms左右

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1645 (这个写到 FAQ 里面比较好吧？)

**Comment by ddzzhen** [comment]
the same question.
