### ISSUE TITLE
 "App not installed. The package appears to be corrupt." on samsung galaxy Note8

### ISSUE THREAD

**Issue by darkness71** [shadowsocks/shadowsocks-android#1660]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
i tried to install the latest version 4.5.0, and the issue  "App not installed. The package appears to be corrupt." occured.
and then i tried the previous version 4.4.6, the same issue happened. but this version worked well before.
the android version is 7.1.1

**Comment by madeye** [comment]
Try universe apks.

**Comment by darkness71** [comment]
yes, i had firstly installed this version, and also tried all the others. the same result i got.
i found an video on youtube, it used "APK editor" to change the install location to internal only to resolve the issue. but i found the shadowsocks was this setting already.
