### ISSUE TITLE
Instagram app network error

### ISSUE THREAD

**Issue by to2false** [shadowsocks/shadowsocks-android#1661]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1.1
* Device: Xiaomi6
* Shadowsocks version: 4.5.1
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Login instagram app
### What did you expect to see?
Login succeed

### What did you see instead?
Get a network error, can access instagram through chrome works.

**Comment by madeye** [comment]
Make sure IPv6 route is disabled.

**Comment by to2false** [comment]
Thanks, my mistake, it works now.
