### ISSUE TITLE
用Android studio编译报错，具体该如何修改？

### ISSUE THREAD

**Issue by MasterLing** [shadowsocks/shadowsocks-android#1662]
Error:src/overture/make.bash: line 31: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 37: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 43: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
# runtime/cgo
fork/exec /Users/masterling/Desktop/androidssr/shadowsocks-android/core/src/overture/.deps/android-toolchain-21-arm/bin/arm-linux-androideabi-clang: no such file or directory
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:goBuild'.
> Process 'command 'sh'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 9s

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/README.md#prerequisites

**Comment by imfinethanks** [comment]
Error:FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> executing external native build for ndkBuild C:\Users\long\shadowsocks-android\core\src\main\jni\Android.mk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s


请问 我这个呢

**Comment by onlymash** [comment]
我已经设置了环境变量 仍然出现这个错误
```
echo $ANDROID_HOME 
/home/user/.android/android-sdk-linux
echo $ANDROID_NDK_HOME
/home/user/.android/android-sdk-linux/ndk-bundle
```

**Comment by jaronliu** [comment]
try 
export $ANDROID_HOME=/home/user/.android/android-sdk-linux
export $ANDROID_NDK_HOME=/home/user/.android/android-sdk-linux/ndk-bundle

**Comment by onlymash** [comment]
这不一样吗，你没看明白，第一行执行后第二行当然是输出结果，说明配置正确

**Comment by onlymash** [comment]
问题不在编译环境。方便解决办法好像是手动执行一个命令编译生成一些中间文件，缺少这些文件就会报这个错误，具体忘记了
