### ISSUE TITLE
编译的时候出错

### ISSUE THREAD

**Issue by PsjJourney** [shadowsocks/shadowsocks-android#1665]
D:\android-demo\shadowsocks-android\core\src\main\jni>ndk-build
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in D:/android-d
emo/shadowsocks-android/core/src/main/AndroidManifest.xml. NDK binaries will *not* be comptible with
 devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user
/common_problems.md for more information.
[armeabi-v7a] Compile++ thumb: jni-helper <= jni-helper.cpp
D:/android-demo/shadowsocks-android/core/src/main/jni/jni-helper.cpp:20:10: fatal error:
      'ancillary.h' file not found
#include <ancillary.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [D:/android-demo/shadowsocks-android/core/src/main/obj/local/armeabi-v7a/objs/jni-helper/j
ni-helper.o] Error 1

**Comment by PsjJourney** [comment]
提示这个文件找不到ancillary.h

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/README.md#prerequisites
