### ISSUE TITLE
从剪切板导入有问题

### ISSUE THREAD

**Issue by IgarashiInaba** [shadowsocks/shadowsocks-android#1668]
全程手机操作
在ishadow和freess这两个地方识别二维码然后用ss打开会提示“未找到有效的配置文件”，或者先把二维码保存然后识别之后把链接复制，选“从剪切板导入”则会显示导入失败。
其他地方的ss却没这个问题，而且ssr通吃，一点问题都没有。
难不成ss还挑食？

**Comment by Mygod** [comment]
shadowsocks-android only supports importing from 2 kind of URLs specified by shadowsocks.org. We are not going to include support for alternative schemes nor faulty URLs. Feel free to create a fork.

**Comment by IgarashiInaba** [comment]
ah...I find the problem..i discovered a option called '自定义规则文件(in my cell phone,lauguage is chinese)' then i open and copy the url in it(从剪切板导入), and connect,is working!
thank you for your reply

**Comment by IgarashiInaba** [comment]
@Mygod  ah...I find the problem..i discovered a option called '自定义规则文件(in my cell phone,lauguage is chinese)' then i open and copy the url in it(从剪切板导入), and connect,is working!
thank you for your reply

**Comment by IgarashiInaba** [comment]
nope,i got a mistake  again.forget about it
