### ISSUE TITLE
无法启动后台服务，请选择配置文件

### ISSUE THREAD

**Issue by tramchamploo** [shadowsocks/shadowsocks-android#1669]
已经选择配置文件

* Android version: *7.1.1 Flyme 6.3.0.0A*
* Device: *Meizu Pro 6*
* Shadowsocks version: *version code "v4.5.1"

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

**Comment by ddzzhen** [comment]
delete it and readd.

**Comment by tramchamploo** [comment]
Where is the readded one?

**Comment by ddzzhen** [comment]
delete and add the new one of the same config. i met the problem ever

**Comment by tramchamploo** [comment]
I've tried this, export config to clipboard and import. Doesn't work for me.
