### ISSUE TITLE
局域网不走 HTTPS 流量

### ISSUE THREAD

**Issue by yourshell** [shadowsocks/shadowsocks-android#1670]
系统环境：安卓5.1 ， 影梭4.5.1
用 privoxy 转发影梭的 SOCKS5(1080) 到 8118 端口，用 dnsmasq 转发影梭的 DNS(5450) 到 53，iptables 的设置
iptables -t nat -A PREROUTING -p tcp -s 192.168.0.0/16 -j REDIRECT --to-ports 8118

内网用代理 192.168.43.1:8118 访问正常，不用代理时，只能访问被墙的 HTTP ，不能访问 HTTPS

http://31.220.14.46/ip.php

**Comment by Mygod** [comment]
Your issue makes no sense. But you might want to use this: https://github.com/Mygod/VPNHotspot
