### ISSUE TITLE
华为手机突然变成可以连接，但线路不通

### ISSUE THREAD

**Issue by solohsi** [shadowsocks/shadowsocks-android#1671]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0.0 EMUI 5.01
* Device: Honer8
* Shadowsocks version: all version from 2.95
* Last version that did not exhibit the issue (if applicable): I Think all versions of ss-android can't work well

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
之前一直可以正常使用，版本4.23，大概在春节后有一天突然不能fq，显示状态为正常连接到服务器，但除了连同的第一下又一点点流量在走，之后上传下行全部为零，之后我试用了从2.9x开始的每个大版本，一直到4.51，全部不能使用，另外发现个别时候点击开启按钮以后，下拉菜单的状态栏只有shaodowsocks一行而没有提示，到很久以后才有提示，服务器为自有服务器，电脑连接正常，ios连接正常，服务器信息确定完全正确，查看正在运行的应用中，影梭包含2进程1服务，服务名称为影梭，进程名称分别为影梭(com.github.shadowsocks:bg)，google play 服务(com.google.android.gms)，后来我也有尝试重新刷机，以及EMUI小版本号降级刷机（大概试了降三四个小版本号的情况），有时候可以在刷机结束刚安装好google play以及影梭的情况下正常使用一会儿，然后就又变回原状，正常使用时间从三五分钟到一个半小时不等，手机电量充满无用，所有关于省电的设置均已关闭，很头疼，请教如何解决

### What did you expect to see?
让ss-android正常工作

### What did you see instead?
只有到服务器的连接，但实际数据不能连通

最后，shadowsocks是个非常好的项目，谢谢大家的辛苦付出！

**Comment by yourshell** [comment]
个人建议：
1. 删除手机自带的华为APP 及相关的库文件；
2. 更换 shadowsocks 服务器；
2. 更换 ISP ，

**Comment by ddzzhen** [comment]
my honor8 is ok，you should add the playstore and upgrade all apps.

**Comment by rigious** [comment]
My honor8(android 7.0) is OK. But my honor 9(android 8.0) has the same problem with @solohsi  said.

**Comment by rigious** [comment]
My honor8(android 7.0) is OK. But my honor 9(android 8.0) has the same problem with @solohsi  said.

**Comment by rigious** [comment]
My honor8(android 7.0) is OK. But my honor 9(android 8.0) has the same problem with @solohsi  said.

**Comment by solohsi** [comment]
play store已经更新为最新了，而且我认为并不是环境问题，包括硬件环境，网络环境，毕竟有能用的时候，而且同环境下的其他手机和电脑都可以用，我把他恢复到和以前能用的一样的环境，也能用一下然后就不行了，看上去更像是emui在运行了一小段时间之后，把ss-andoird加入了类似黑名单一样的东西里，禁止了后台的某个服务或者是干脆直接禁止了他的网络连接，总之很费解。。。。。

**Comment by solohsi** [comment]
> 华为手机禁用华为智障的省电精灵后ss使用完全正常，不会被杀，做法自己百度 “adb 省电精灵"

貌似不是这个问题，我禁用了省电精灵，重新装了ss的几个版本，还是一样的现象，是可以建立连接的，但是不能发出包，从ss安卓的导航栏小控件来看，如果没有出现速度栏，是后台服务没启动，但我的问题是出现速度栏之后，只显示一下速度，然后就一直是零了，电脑，IOS，包括在家里主路由上做的透明代理都可以正常工作，就是安卓版无论如何也不行，实在是很费解。。。。。。。

**Comment by jackrow** [comment]
我现在也是同样的症状

**Comment by xgdgsc** [comment]
好像是好久之前的某次升级后我遇到过

**Comment by solohsi** [comment]
> 好像是好久之前的某次升级后我遇到过

嗯，谢谢

**Comment by vqintian** [comment]
我这个也是这种问题，但是我的DNS转发没有开啊。。还有大神帮忙研究研究吗？
![_20180614135658](https://user-images.githubusercontent.com/18448915/41394004-d85cd5b6-6fda-11e8-90ad-76fa608c1f51.jpg)

**Comment by solohsi** [comment]
> 我这个也是这种问题，但是我的DNS转发没有开啊。。还有大神帮忙研究研究吗？
你要看任务栏的小控件，有没有上传下载数据显示

**Comment by vqintian** [comment]
我刚刚自己莫名其妙的成功的解决了这个问题。。我什么也没改。。。
我只是先用PC登陆ss连接成功后。。然后用手机扫pc的服务器配置的二维码
然后就莫名其妙的好了。。你可以试试

**Comment by vqintian** [comment]
服务器/分享服务器配置.手机扫二维码...然后就可以了..什么原理,为什么我都不清楚,但是我手机现在有了上传下载数据,成功科学上网了
![_20180614145341](https://user-images.githubusercontent.com/18448915/41396222-c48880b4-6fe2-11e8-887a-eaf27c7979ed.jpg)

**Comment by solohsi** [comment]
如果没有上传下载显示，说明后台服务没有启动，那么应该是省电精灵的问题，如果有，那应该是到服务器连接的问题，各种情况就不好说了

**Comment by vqintian** [comment]
![_20180614145702](https://user-images.githubusercontent.com/18448915/41396345-35a5f6be-6fe3-11e8-9127-ea7755d075b2.jpg)

**Comment by jjwong1991** [comment]
我也有同样的问题，华为p20手机之前可以正常上网，2月开始出现可以连接成功但是没有发送接收的问题，尝试了一下添加任何ip配置，包括在关闭wifi和移动数据的情况下，客户端都会显示连接成功，但是实际都没有网速

**Comment by limchen233** [comment]
> 我这个也是这种问题，但是我的DNS转发没有开啊。。还有大神帮忙研究研究吗？
> ![_20180614135658](https://user-images.githubusercontent.com/18448915/41394004-d85cd5b6-6fda-11e8-90ad-76fa608c1f51.jpg)

你有问题解决了吗

**Comment by Michael-Xiu** [comment]
已解决这个问题，华为自动杀后台，导致shadowsocks连接完后切换其他应用其实已经断开了连接，解决方法如下：
![4](https://user-images.githubusercontent.com/35869384/54802560-cda5fb80-4ca6-11e9-8767-0847e9936ec2.jpg)
![3](https://user-images.githubusercontent.com/35869384/54802562-d0a0ec00-4ca6-11e9-8940-ffb8a7d66ac5.jpg)

**Comment by bobli1128** [comment]
EMUI9.1中在应用->应用启动管理中将shadowsocks设置为自动管理，这样解决了我的问题。

**Comment by kukudemajia** [comment]
以上各位的方法都试过了还是不行

**Comment by chaochao-zhang** [comment]
If you had many configuration,The first is generated by default(with ip and port 8388),change sequence by drag this item to the last
如果你通过扫码二维码或者其他方式配置了多个项目，有一个8388的是自动生成的，把这个拖到最后。

**Comment by luo-chuan** [comment]
如果系统是EMUI 10的话。设置—更多连接—加密DNS—默认关闭，勾选自动。就可以用了。  
参考： https://club.huawei.com/thread-21446964-1-1.html  
![EMUI10_SS](https://clubimg.club.vmall.com/data/attachment/forum/201909/29/084537fjrs2tvgllixn7gj.jpg)
