### ISSUE TITLE
陷入了死循环

### ISSUE THREAD

**Issue by sunmd01** [shadowsocks/shadowsocks-android#1672]
使用SS科学上网，需要更新Google服务。
更新Google服务，需要SS科学上网。
尴尬...

**Comment by pexcn** [comment]
不能忽略吗？

**Comment by p506738532** [comment]
哭死，谷歌商店这个不能电脑上下载吗，然后我把apk传输到手机上。。。

**Comment by zomco** [comment]
解压缩软件需要解压缩

**Comment by studentmain** [comment]
找个x灯x风xx门或者干脆安个v2ray，问题解决（

**Comment by yourshell** [comment]
https://apkpure.com/ 
http://apk-dl.com/
https://apps.evozi.com/apk-downloader/

这些是在线下载apk的。github上有相关的程序，用过python的

**Comment by Mygod** [comment]
Use import via URL instead.
