### ISSUE TITLE
Seems some Google Play traffic goes without proxy

### ISSUE THREAD

**Issue by aLMonotonous** [shadowsocks/shadowsocks-android#1674]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 7.0
* Device: Sumsang S8+(China version)
* Shadowsocks version: 4.5.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: ras-256
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

### What did you do?
a bandwagon SS-VPS set myself, I successfully open Google.com/GooglePlay in explorer like Chrome. But I can not open Google Account Setting in system settings.

Firstly I cannot even add Google Account in Settings even I can open google.com in explore.

I used a VPN(vyprVPN) then I set all things normally. But when back to SS, I can only use google play for only free items(A version for China only), and I still cannot set Google account in system setting.

BTW, I saw the issue of fb #1601, so I turn off the IPV6, then FB/INS work normally but GooglePlay not

#1435 I tried clean the caching of APP, not work

It seems some traffic for GooglePlay Service do not go though SS-Proxy.
But I'm sure some VPN-Provider's App can achieve this purpose, I wonder it is an issue of Socket5 or my VPS IP is blocked by google

Thanks for your time

aL

**Comment by madeye** [comment]
I don't think it's related to shadowsocks.

If you don't enable any policy routing and app proxy option, all of your traffic would be redirected to Google Play.
