### ISSUE TITLE
每次开机TCP Fast Open恢复默认

### ISSUE THREAD

**Issue by sjdhome** [shadowsocks/shadowsocks-android#1675]
Android version: Lineage OS 14.1-20180220-UNOFFICIAL-Sultan-oneplus3
Device: OnePlus 3T
Shadowsocks version: v4.5.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open

### What did you do?
打开TCP Fast Open开关

### What did you expect to see?
/proc/sys/net/ipv4/tcp_fastopen 的值是3

### What did you see instead?
系统默认值1

**Comment by madeye** [comment]
It's expected. Your system will reset TCP options when booting.

**Comment by sjdhome** [comment]
但能不能开机时自动应用Shadowsocks的设置？

**Comment by Mygod** [comment]
Make sure you have started Shadowsocks (you don't need to start service) before checking tcp_fastopen after reboot.
