### ISSUE TITLE
建议shadowsocks客户端重新支持NAT模式

### ISSUE THREAD

**Issue by DevinStever** [shadowsocks/shadowsocks-android#1677]
需求设备：任何使用Android8.0以上的手机
问题描述：
因Android8.0以上系统存在wifi下连接vpn之后，会把vpn识别为数据连接的问题。因此导致好多同步功能无法使用。
对于中国大陆用户而言，唯一最方便解决这个问题的办法就是使用需要root的NAT模式来解决这个问题。
所以想请开发者是否可以考虑重新支持NAT模式。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#how-to-use-transproxy-mode
