### ISSUE TITLE
cannot access 192.168.*.* when open ss

### ISSUE THREAD

**Issue by zyf0330** [shadowsocks/shadowsocks-android#1681]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 8.1.0
* Device: Google Pixel 2 XL
* Shadowsocks version: newest Google Play version
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I use custom rule and import from gfw list. When start ss-android, I cannot access 192.168.*.*, if close it, I can.

**Comment by studentmain** [comment]
manually bypass 192.168.*.* in custom rule, or just use bypass lan&china

**Comment by zyf0330** [comment]
How to bybass mannually?

**Comment by zyf0330** [comment]
@studentmain in custom rules, first is [bypass all], so 192 subnet should be bybassed default. I have tried @@ prefix but useless.
