### ISSUE TITLE
External Native Build Issues:Build command failed.

### ISSUE THREAD

**Issue by longforus** [shadowsocks/shadowsocks-android#1682]
### Environment

* Android buildToolsVersion = '27.0.3'
* jdk: 1.8.0_151
* go version go1.10 windows/amd64
* ndk: 16.1.4479499
* Gradle 4.6
* Groovy:       2.4.12
* Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
* JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
* OS:           Windows 10 10.0 amd64

### What did you do?
build

### What did you expect to see?

build success

### What did you see instead?
`External Native Build Issues
Build command failed.
Error while executing process C:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\release\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -ID:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/libancillary -IC:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/jni-helper.cpp -o D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || remprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -IC:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot C:/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
Build command failed.
Error while executing process C:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"
copy /b/y "C:\Android\sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86" > D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Android/sdk/ndk-bundle/build//../sysroot D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni C:/Android/sdk/ndk-bundle/build//../sources/android/support C:/Android/sdk/ndk-bundle/build//../sources/android/support/include C:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi C:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/libancillary C:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include C:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/mbedtls/include D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/pcre/dist D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/maprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.
in/jni/badvpn/lwip/src/include/ipv4 D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/badvpn/lwip/src/include/ipv6 D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/badvpn/lwip/custom" >> D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -ID:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/libancillary -IC:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/AndroidStudioProjects/Demo/shadowsocks-android/core/src/main/jni/jni-helper.cpp -o D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem
md "D:\AndroidStudioProjects\Demo\shadowsocks-android\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -IC:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot C:/Android/sdk/ndk-bundle/build//../sysroot -isystem C:/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o
C:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
C:/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a D:/AndroidStudioProjects/Demo/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o`

please help me? I'm not familiar with the NDK.

**Comment by CreaterXu** [comment]
same error，please help
