### ISSUE TITLE
Node switch bug

### ISSUE THREAD

**Issue by Choutouketsu** [shadowsocks/shadowsocks-android#1685]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *6.0.1 MMB29M", MIUI 9 version 9.2.4.0*
* Device: *Redmi Note 3 Snapdragon*
* Shadowsocks version: *version code "v4.5.1" *
* Last version that did not exhibit the issue (if applicable):
N/A
### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES 256 CFB
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I was planning to switch from one node address to another

### What did you expect to see?
the number address switch should be as fast as that of letter or domain name address, isn't it?

### What did you see instead?
The address composed of numbers switch fast, but addresses of letters or domain names, they will take very long to switch

**Comment by madeye** [comment]
It's expected. Any domain name address should be resolved to an IP address first.

**Comment by Mygod** [comment]
Maybe we should intentionally slow down setting up VPN for IP addresses so that it will feel right to you.
