### ISSUE TITLE
Plugin binaries aren't executed

### ISSUE THREAD

**Issue by cbeuw** [shadowsocks/shadowsocks-android#1686]
### Environment

* Android version: 8.0.0
* Device: Emulated Google Pixel
* Shadowsocks version: 4.5.1. Plugin Library 0.1.0

### What did you do?

This is my BinaryProvider.kt:

```kotlin
package com.github.shadowsocks.plugin.gq_client

import android.net.Uri
import android.os.ParcelFileDescriptor
import java.io.File
import java.io.FileNotFoundException
import android.util.Log

import com.github.shadowsocks.plugin.NativePluginProvider
import com.github.shadowsocks.plugin.PathProvider

class BinaryProvider:NativePluginProvider() {
    override fun populateFiles(provider: PathProvider) {
        Log.d("popFiles","populating files")
        provider.addPath("gq-client", "755")
    }

    override fun getExecutable(): String {
        val exec = context.applicationInfo.nativeLibraryDir + "/libgq-client.so"
        Log.d("execPath",exec)
        Log.d("exists",File(exec).exists().toString())
        return exec
    }

    override fun openFile(uri: Uri?): ParcelFileDescriptor {
        if (uri==null){
            Log.d("URI","null")
            throw FileNotFoundException()
        }
        Log.d("URI",uri.path)
        when (uri.path) {
            "/gq-client" -> return ParcelFileDescriptor.open(File(getExecutable()), ParcelFileDescriptor.MODE_READ_ONLY)
            else -> throw FileNotFoundException()
        }

    }
}
```

This is my AndroidManifest.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.github.shadowsocks.plugin.gq_client">

    <application
        tools:replace="android:theme"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >
        <provider android:name=".BinaryProvider"
            android:exported="true"
            android:authorities="com.github.shadowsocks.plugin.gq_client.BinaryProvider">
            <intent-filter>
                <action android:name="com.github.shadowsocks.plugin.ACTION_NATIVE_PLUGIN"/>
            </intent-filter>
            <intent-filter>
                <action android:name="com.github.shadowsocks.plugin.ACTION_NATIVE_PLUGIN"/>
                <data android:scheme="plugin"
                    android:host="com.github.shadowsocks"
                    android:pathPrefix="/gq-client"/>
            </intent-filter>
            <meta-data android:name="com.github.shadowsocks.plugin.id"
                android:value="gq-client"/>
            <meta-data android:name="com.github.shadowsocks.plugin.default_config"
                android:value=""/>
        </provider>
        <activity android:name=".ConfigActivity" >
            <intent-filter>
                <action android:name="com.github.shadowsocks.plugin.ACTION_CONFIGURE"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:scheme="plugin"
                    android:host="com.github.shadowsocks"
                    android:path="/gq-client"/>
            </intent-filter>
        </activity>
    </application>

</manifest>
```

This is my project binary paths:

```
app
   |
   src
      |
     main
        |
        jniLibs
            |
            armeabi
            |   |
            |   libgq-client.so
            |
            armeabi-v7a
            |   |
            |   libgq-client.so
            |
            x86
            |   |
            |   libgq-client.so
```

### What did you expect to see?

`populateFiles`, `getExecutable` and `openFile` should all be called.

### What did you see instead?

Only `getExecutable` is called. The debug output:

```
D/execPath: /data/app/com.github.shadowsocks.plugin.gq_client-h5qyHCNa31TYJS_GZJDayg==/lib/x86/libgq-client.so
D/exists: true
```

Some answers on Stackoverflow suggest that the binary paths should be under `/data/data/`. Maybe accessing  `/data/app/` requires root privilige? But I couldn't find anywhere else to put native libraries.

**Comment by Mygod** [comment]
How do you know it's not executed? Shadowsocks will only invoke `getExecutable` if it can directly invoke that file:

https://github.com/shadowsocks/shadowsocks-android/blob/f63842f7736e356efe41db9db3e588562d38331e/mobile/src/main/java/com/github/shadowsocks/plugin/PluginManager.kt#L152-L159

The other methods are for fallback mode.

**Comment by cbeuw** [comment]
@Mygod 
adb shell `ps` does not show libgq-client.so when I press connect, neither does libss-local.so appear. I could see libkcptun.so and libss-local.so when I'm using kcptun.
Maybe my app crashes on startup?

I actually managed to get my app running by executing libgq-client.so directly in adb shell:
`$ SS_LOCAL_HOST=127.0.0.1 SS_LOCAL_PORT=1080 SS_REMOTE_HOST=192.168.1.70 SS_REMOTE_PORT=443 SS_PLUGIN_OPTIONS="ServerName=bing.com;TicketTimeHint=3600;Key=exampleconftest;Browser=chrome" ./data/app/com.github.shadowsocks.plugin.gq_client-PvEJzstm3kX0yldpMOWmhw==/lib/arm64/libgq-client.so`

And then when I press connect in shadowsocks app, the terminal gets flooded with
`2018/03/18 16:30:21 accept tcp 127.0.0.1:1080: accept4: too many open files`

I tried to run gq-client on standalone mode, with server set as 127.0.0.1:1080 and plugin disabled in shadowsocks app, the same thing appears.

Speculation: this has to do with [this](https://github.com/cbeuw/GoQuiet/issues/11#issuecomment-373862287). Shadowsocks-android uses TCP fast-open by default and cannot be turned off without root privilige. My app compiled with Android NDK GC (it works fine with the native GC cross compiler) is not compatible with SYN with TFO cookie (maybe it doesn't send SYN-ACK), causing ss-local to reconnect infinitely to gq-client and nothing works.

**Comment by cbeuw** [comment]
I ran gq-client on standalone mode and ss-local on my computer with server set to my phone's ip. The proxy works. I'm now pretty sure this is a fast-open issue.

**Comment by madeye** [comment]
Have you implemented "Network Callback" in your plugin? It's required in Android plugin for bypass local VPN connection.

https://github.com/shadowsocks/kcptun/blob/shadowsocks/client/main.go#L537

It's also required a modified golang build, which is already handled in the example kcptun-android plugin project.

**Comment by madeye** [comment]
There is another known approach to implement "protected connection" in golang without hacking in golang runtime.

https://github.com/getlantern/lantern/blob/331729195468dc9cc3fad2a667488624f36c7e91/src/github.com/getlantern/protected/protected.go

**Comment by cbeuw** [comment]
@madeye 
My understanding is: once a VpnService is started, all outbound connections will be routed to the VpnService unless an `fwmark` is set. In this case, the connection made by gq-client to gq-server is looped back into ss-local which creates a positive feedback loop. Is that correct?

I read lantern's code you linked and it seems that a function reference is stored in the field  `protect` in struct `Protector`. But I couldn't find the implementation of the `protect` function. It could be a JNICALL like [this](https://stackoverflow.com/questions/44479021/android-vpnservice-protect-socket-thats-stored-in-native-code) or a syscall.

In [this](https://stackoverflow.com/questions/38606036/how-does-android-vpnservice-protect-fd-work) StackOverflow answer, it gives the underlying implementation of VpnService.protect() as:

```cpp
// android/system/netd/server/FwmarkServer.cpp

    fwmark.permission = permission;

    if (setsockopt(*socketFd, SOL_SOCKET, SO_MARK, &fwmark.intValue,
                   sizeof(fwmark.intValue)) == -1) {
        return -errno;
    }
```

and

```c
// android/system/netd/include/Fwmark.h 

union Fwmark {
    uint32_t intValue;
    struct {
        unsigned netId          : 16;
        bool explicitlySelected :  1;
        bool protectedFromVpn   :  1;
        Permission permission   :  2;
    };
    Fwmark() : intValue(0) {}
};
```

So I guess I need to get the unexported file descriptor from net.Conn using [pointer hack](https://github.com/coyove/gotfo/blob/master/util.go#L56), and then syscall `setsockopt`.

**Comment by cbeuw** [comment]
In [android.c](https://github.com/shadowsocks/simple-obfs/blob/master/src/android.c#L66) in simple-obfs, this seems to be the code that does the work
```c
    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, "protect_path", sizeof(addr.sun_path) - 1);

    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) == -1) {
        LOGE("[android] connect() failed for protect_path: %s (socket fd = %d)\n",
             strerror(errno), sock);
        close(sock);
        return -1;
    }
```
The socket to obfs_server is connected to 0.0.0.0:0. It then gets connected to the actual remote address in local.c. But how does this work?

**Comment by madeye** [comment]
We're using IPC (local socket) to pass FD from plugin to Android application.

You can find an example here:

https://github.com/shadowsocks/kcptun/blob/shadowsocks/client/main.go#L62

**Comment by kimw** [comment]
@cbeuw How's it going?

**Comment by cbeuw** [comment]
@kimw 
There are some interesting [progress](https://github.com/linusyang92/GoQuiet) made by @linusyang92 . He used the same approach as the one in kcptun, which requires modification to the Go code. I really don't want to do this.

But, looking at madeye's [fork](https://github.com/shadowsocks/go/commit/9498b10a66b741fd00a52cddbd61271e8c37c333), the only thing he did is to export the socket's file descriptor. Since I need a third-party `net` package to implement TCP fast-open anyway, I may just modify [that](https://github.com/coyove/gotfo) to achieve the same thing.

**Comment by Mygod** [comment]
I want to point out that the underlying implementation of `VpnService.protect` is actually sending a `FwmarkCommand::PROTECT_FROM_VPN` command to `netd` where some complicated logic (finding default network) happens. If you try to reimplement this, you will very likely end up writing lots of code opting for every version of Android (and possibly worse, every OEM variant). Also in the end your fwmark will probably be overwritten by `netd` so that would probably not work.

@madeye Are you hijacking go runtime just that we can merge upstream changes more easily?

**Comment by madeye** [comment]
@Mygod I think this one looks useful: https://github.com/coyove/gotfo. But it requires additional changes to our existing golang components.

**Comment by cbeuw** [comment]
[It](https://github.com/cbeuw/GoQuiet-android) works on my emulator now but weirdly not on my phone (the handshake sequence is normal and there are application data being sent, but Shadowsocks complains about protocol error)

**Comment by Mygod** [comment]
I'm not sure what you mean by protocol error. You could try if proxy mode works. If it does, there's something wrong with your protect code.

**Comment by Mygod** [comment]
@cbeuw I just wrote another example in Kotlin that's pretty related to your project. You might want to take a lot: https://github.com/shadowsocks/kcptun-android/pull/32
