### ISSUE TITLE
Always"Please select a profile"

### ISSUE THREAD

**Issue by LawrenceGK** [shadowsocks/shadowsocks-android#1687]
### Environment

* Android version: 7.1.1, more detailed description is preferred*
* Device: MEIZU MX6
* Shadowsocks version: v4.5.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Just select one of Profiles, which turned green and run it.

### What did you expect to see?
Successfully connected.

### What did you see instead?
"Please select a profile."

**Comment by pythonnewlearning** [comment]
same problem, meizu note3.
Always"Please select a profile"

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-is-my-rom-not-supported

**Comment by LawrenceGK** [comment]
@madeye Oh thank you. Sorry for missed it.

**Comment by LawrenceGK** [comment]
@madeye Oh thank you. Very sorry for missing it.
