### ISSUE TITLE
开启DNS转发后无法连上服务器

### ISSUE THREAD

**Issue by whka** [shadowsocks/shadowsocks-android#1694]
### Environment

* Android version: 8.1 (Mokee 81.0)
* Device: xiaomi 6
* Shadowsocks version: v4.5.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-128-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):mode=fast3;dscp=46;crypt=aes-128;parityshard=30;rcvwnd=2900;key=key23333;sndwnd=128;nocomp;mtu=1400;datashard=70
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:
Socks5 port: 1081
Local DNS port: 5450
### What did you do?
配合kcptun插件使用，在开启DNS转发后无法连上服务器，而关掉DNS转发后则连接正常

### What did you expect to see?
连上服务器

### What did you see instead?
服务器连接失败

**Comment by Mygod** [comment]
Plugins don't work very well with UDP forwarding. Check issue trackers for workarounds.
