### ISSUE TITLE
4.2.5后无法使用

### ISSUE THREAD

**Issue by verity886** [shadowsocks/shadowsocks-android#1699]
### Environment

* Android version: 7.12 魔趣
* Device: 乐视max2
* Shadowsocks version: 4.2.5以上
* Last version that did not exhibit the issue (if applicable):4.2.5

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

连接线路后点击“测试连接”，一直显示“测试中”。GFW内网站可以打开，其他不行

**Comment by Mygod** [comment]
Turn off Apps VPN mode.

**Comment by verity886** [comment]
不好意思搞错了，apps vpn mode没有打开

**Comment by yyh1102** [comment]
@verity886 这在哪里打开

**Comment by entropysnow** [comment]
have you solve this????
