### ISSUE TITLE
Unknown plugin obfs-simple unknown  plugin kcptun

### ISSUE THREAD

**Issue by Coel0728** [shadowsocks/shadowsocks-android#1701]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

chose the kcptun plugin
### What did you expect to see?
connect successfully

### What did you see instead?

failed to connect the remote server:unknown plugin xxx

**Comment by john564** [comment]
See solutions
https://github.com/shadowsocks/simple-obfs/issues/206
https://github.com/shadowsocks/kcptun-android/issues/33

But, need solution expanded to other versions of android.

**> android 8.0**
> 
> Got error
> Failed to connect to remote server: Unknown plugin obfs-local
> 
> fix
> 
> goto
> Settings/Battery/Launch
> press Simple obfuscation
> un-select automatic management.
> 
> Then within Manage Manually,
> select
> Secondary launch
> Can be launched by other apps
> 
> press ok



**android 6.0**

Got error "Unknown plugin kcptun", checking notifications showed shadowsocks needed the permission to run secondary app kcptun. Once allowed, working again.

Reproduce.
uninstall and install kcptun. First time shadowsocks+kcptun connection works,
second time, gives error
"Unknown plugin kcptun"

Check Notifications shows
"Stopped Shadowsocks from launching secondary app kcptun"
when you click kcptun, its asks permission for kcptun to be launched by shadowsocks.
Click allow, and all working again.

**android 8.0**

Got error "Unknown plugin kcptun", no notifications, no clues.
fix

goto
Settings/Battery/Launch

press kcptun (or simple-obfs), un-select automatic management.
Then within Manage Manually, select

Secondary launch
Can be launched by other apps
