### ISSUE TITLE
A bug occured accidentally

### ISSUE THREAD

**Issue by XueTeng2** [shadowsocks/shadowsocks-android#1706]
Android version：6.0
Device：Huawei P8
Shadowsocks version：4.5.2
ERROR：无法连接远程服务器：com.github.shadowsocks was not granted ei……
![screenshot_2018-03-28-12-38-04](https://user-images.githubusercontent.com/26952232/38010392-6bad29d4-328b-11e8-80d2-3d36564a4e70.png)

**Comment by Google-Android** [comment]
same problem

**Comment by Novite5** [comment]
same problem always with Moto X Style Android 6.0

**Comment by Mygod** [comment]
Update your Android system to 6.0.1 or higher or wait for next release.

**Comment by madeye** [comment]
Please try https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.5.3

**Comment by bobstone007** [comment]
same problem

**Comment by XueTeng2** [comment]
The version 4.5.3 running normally，thank you for your  efforts！ @madeye
