### ISSUE TITLE
make_standalone_toolchain.py: No such file or directory

### ISSUE THREAD

**Issue by imkobedroid** [shadowsocks/shadowsocks-android#1707]
### Environment

* Android version: *7.0"
* Device: *xiaomi*
* Shadowsocks version: *version code "v3.0.0"
* Last version that did not exhibit the issue (if applicable):

### Configuration

go 1.4

android studio 3.0

ndk R16

### What did you do?
My NDK configuration is good I use ndk-build is no problem, I can see in the make_standalone_toolchain.py folder, I modify the executable for read and write all.
After configuring the environment, it is compiled in Android studio.

### What did you expect to see?

Normal compilation and installation on the phone

### What did you see instead?
Error:src/overture/make.bash: line 31: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 37: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 43: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
godep: error downloading dep (golang.org/x/net/proxy): unrecognized import path "golang.org/x/net/proxy"
godep: error downloading dep (golang.org/x/sys/unix): unrecognized import path "golang.org/x/sys/unix"
godep: Error downloading some deps. Aborting restore and check.
# runtime/cgo
fork/exec /Users/toushihiroshi/Desktop/ssh/shadowsocks-android/core/src/overture/.deps/android-toolchain-21-arm/bin/arm-linux-androideabi-clang: no such file or directory
FAILURE: Build failed with an exception.
Error:src/overture/make.bash: line 31: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 37: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
src/overture/make.bash: line 43: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
godep: error downloading dep (golang.org/x/net/proxy): unrecognized import path "golang.org/x/net/proxy"
godep: error downloading dep (golang.org/x/sys/unix): unrecognized import path "golang.org/x/sys/unix"
godep: Error downloading some deps. Aborting restore and check.
# runtime/cgo
fork/exec /Users/toushihiroshi/Desktop/ssh/shadowsocks-android/core/src/overture/.deps/android-toolchain-21-arm/bin/arm-linux-androideabi-clang: no such file or directory
FAILURE: Build failed with an exception.

**Comment by madeye** [comment]
Make sure you have set `ANDROID_NDK_HOME` correctly if you're using a separate NDK install.
