### ISSUE TITLE
ndk issues.

### ISSUE THREAD

**Issue by ravi-nimavat128** [shadowsocks/shadowsocks-android#1710]
Error:FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> executing external native build for ndkBuild C:\Users\Sys2\Desktop\ravi\shadowsocks-android\core\src\main\jni\Android.mk

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by Chirag2310** [comment]
Same problem occur me. can you help to solve this error? @ravi-nimavat128
