### ISSUE TITLE
How to build from the zip soure?

### ISSUE THREAD

**Issue by wansj** [shadowsocks/shadowsocks-android#1711]
The build steps list on the [https://github.com/shadowsocks/shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android) page is based on the [shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android.git) git repositoty. Can someone provide a complete build steps for the zip source??Thanks in advance. 
### Environment
* java version:       "1.8.0_161"
* Groovy:       2.4.12*
* Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
* JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
* OS:           Mac OS X 10.13.3 x86_64:

### What did you do?
1. I failed to git clone the repository, so I downloaded the zip source version instead.
2. I've setted the ANDROID_HOME, ANDROID_NDK_HOME, GOROOT_BOOTSTRAP environment variable.
3.I can't execute `git submodule update --init --recursive` because the source I downloaded is not a git repository, so I opened the project in the Android Studio
### What did you expect to see?
Build  successfully

### What did you see instead?
I saw `Gradle sync failed `

**Comment by wansj** [comment]
@Mygod Could you give me some clues? I just can't clone this repository from git, but I can download the zip. How to build the project from the zip?

**Comment by pexcn** [comment]
Use git clone instead.

**Comment by wansj** [comment]
@pexcn I tried it just now and encountered with `fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Operation timed out`. It seems that some dependencies are unavailable from my network.

**Comment by studentmain** [comment]
Maybe you need across gfw first before clone.
NOTE: some software doesn't use proxy by default.

wansj <notifications@github.com> 于 2018年4月1日周日 16:17写道：

**Comment by pexcn** [comment]
make sure your network can be access android.googlesource.com

**Comment by wansj** [comment]
Thanks for your reply.
