### ISSUE TITLE
No send/recv traffic after a while on Samsung S9+

### ISSUE THREAD

**Issue by Coxxs** [shadowsocks/shadowsocks-android#1712]
**This issue is similar with another issue (#1410), but the symptom seems to be different. So I decided to open a new issue.**

### Environment

* Android version: 8.0.0
* Device: Samsung S9+ (SM-G9650/DS) [Dual-Sim (Qualcomm)]
* Shadowsocks version: 4.5.2
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### Samsung Related Configuration
* **Unmonitored** shadowsocks in "Settings -> Device maintenance"
* **Locked** shadowsocks in recent apps
* No optimization apps installed (Greenify, brevent, etc.. )

### What did you do?
1. Boot up the device, the ss service auto connected.
2. Enjoy the internet (1hrs ~ 2days)
3. Unable to access the internet via ss. (ss shows: Connect success / send 0KB 0 Bytes/s | recv 0KB 0 Bytes/s )
5. Try to connect to different servers via ss -> no send/recv traffic
4. Try to connect to the servers mentioned above (on other devices, under same network) -> the server seems ok.

Methods I tried but still **no send/recv traffic**:
* Disable / Enable service in shadowsocks
* Kill / Start shadowsocks app (mentioned in #1410)
* Change socks5 proxy port (mentioned in #1410)
* Settings -> General Management -> Reset -> Reset network settings (mentioned in #1410)

**Other attempts:**
* Use [outline](https://play.google.com/store/apps/details?id=org.outline.android.client) or other VPN apps unrelated to ss protocol (still no send/recv traffic)
* Connect to baidu without VPN services -> success

It seems that the only method to solve this problem temporarily is **reboot**. 

I thought it's a bug related to VPN services in the Samsung OS, ~~but I can hardly find similar issues on google~~ (https://github.com/shadowsocks/shadowsocks-android/issues/1712#issuecomment-377424988) , so I wonder if some specific usage in ss triggered this bug in Samsung OS.

**Comment by Coxxs** [comment]
When the "no traffic" issue occurs, there is also some errors related to "addRoute" in logcat when I enabled service in shadowsocks (no such errors when shadowsocks is ok):

https://gist.github.com/Coxxs/d5074d68607687750fc098880eb8a8ff

**Comment by Mygod** [comment]
Thanks for the very helpful logcat. Unfortunately `Netd` and `ConnectivityService` are both system components. So I think this might be a bug of your ROM.

Does this issue also occur for 4.5.1? Does other VPN app works with your device?

**Comment by liujian1987** [comment]
my s8 has a problem, when you touch the circle button  which  start to connect, it doesn't work, you can't get any responses

**Comment by liujian1987** [comment]
but last version works well

**Comment by Coxxs** [comment]
Thanks for the quick reply. 

The problem already existed for a period of time (before I upgrade my ss 22hr. ago), so I guess the same issue existed in other versions. I will downgrade to 4.5.1 now and test it for a while.

As mentioned in the issue, when the "no traffic" problem occurs, other VPN apps also won't work.

**Comment by Mygod** [comment]
I meant do you observe the similar behavior for other VPN apps before everything breaks down?

**Comment by madeye** [comment]
@Mygod I think maybe no one can keep a VPN connected for days? 😃

**Comment by Coxxs** [comment]
抱歉.. 英文实在吃力..
1. 关于其他 VPN 应用是否会触发系统的 VPN 断流：目前很少使用其他 VPN 应用（很难长期稳定连接），我会尽量尝试一下，看是否能引起这个问题。
2. logcat 中 addRoute 相关的错误是在断流后，每次启用 ss 时出现的。
3. 在出现问题后，其他 VPN 启用时，logcat 中不会有 addRoute 相关的错误，但是这些 VPN 应用也无法使用。

**Comment by Mygod** [comment]
@madeye Maybe but unlike real VPNs, Shadowsocks is stateless.

@Coxxs Try switching to Wi-Fi and cellular networks frequently and see if that makes it happen more often. I'm suspecting some race condition somewhere.

**Comment by Mygod** [comment]
It would probably be most helpful if you could get a logcat just after when connectivity is lost.

**Comment by Coxxs** [comment]
Just found a way to reproduce this issue in 10 seconds:
1. Add 2 servers
2. Enable shadowsocks service
3. switch between 2 service repeatedly and quickly
4. "no traffic" until net reboot

I guess this is the method I triggered this bug because I have multiple server config before.
I will post the logcat and `adb shell ip addr` result later.

**Comment by Coxxs** [comment]
[logcat](https://gist.github.com/Coxxs/4dc015a1c9869d4a3f8f178e3715fc98) [ip addr](https://gist.github.com/Coxxs/7ba49d59bc031f06c17684a0ffb8aa5d)

**Comment by Mygod** [comment]
Thanks. That's very helpful. I also tried your way on my Lineage OS for ~20 seconds and nothing happened.

Looking at your logcat, the most relevant lines are:

```
03-30 15:19:19.185   948  1229 E Netd    : Error deleting IPv4 rule: No such file or directory
03-30 15:19:19.185   948  1229 E Netd    : failed to remove interface tun0 from VPN netId 506
03-30 15:19:19.185   948  1229 E Netd    : deleting network with netId 506 without clearing its interfaces
03-30 15:19:19.186  1523  1778 E ConnectivityService: Exception removing network: java.lang.IllegalStateException: command '120 network destroy 506' failed with '400 120 destroyNetwork() failed (No such file or directory)'
```

This is almost certainly a race condition. Unfortunately it's impossible to debug it because we don't have access to Samsung's source code.

Also good job finding that related issue. Now I'm certain there's nothing to do here since you can reproduce it also with airplane mode. Please wait for Samsung to release a fix. (you could also contact their support staff)

**Comment by Coxxs** [comment]
Thanks, I will try to switch the servers slowly before samsung fixes the bug ;)
By the way, enable & disable airplane mode can't trigger the issue for me in shadowsocks (maybe shadowsocks didn't touch the route when switching the airplane mode..)

**Comment by Mygod** [comment]
Tip on switching slowly: Shut down VPN, switch profile then start again.

It's a race condition. It doesn't happen every time. If you try it for an hour it will probably happen.

Shadowsocks does change the route. It tells `netd` which route to add to VPN tunnel otherwise no traffic will go through VPN.

**Comment by AlynxZhou** [comment]
Seems 9.0 Beta fixed this issue.
