### ISSUE TITLE
DNS issue on v4.5.3

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#1713]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Android version: 8.1.0
Device: *e.g. Google Pixel 2 XL
Shadowsocks version: v4.5.3
Last version that did not exhibit the issue (if applicable): 4.5.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x ] Apps VPN mode
  * [ x ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ x ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
visit some sites which are dns poisoned by GFW, like https://www.binance.com

### What did you expect to see?
site opens normally, which happens on v4.5.1

### What did you see instead?
sites won't open, or chrome warns the site is using a wrong cert (which is caused by GFW's spoofed IPs)

**Comment by madeye** [comment]
Let's wait GFWList adding all these domains.

**Comment by baraja** [comment]
but it works great on v4.5.2, does that mean v4.5.3 has some changes on the DNS resolver part?

**Comment by madeye** [comment]
The website you mentioned is GFWed vert recently, It's nothing to do with shadowsocks. https://github.com/gfwlist/gfwlist/issues/947

**Comment by madeye** [comment]
You can try the custom rules if you need to visit some specific sites that is not in GFWList. All you can try the global routing.

**Comment by baraja** [comment]
thanks, but I wouldn't try the global routing, I'll go with "bypass China & LAN". 
What I don't understand is:
1. on v4.5.3, only with DNS Forwarding option enabled, these sites open normally
2. on v4.5.2, with/without the option enabled, these sites open normally as always

and looks like the gfwlist.acl hasn't been changed since v4.5.2

**Comment by zmz125000** [comment]
Exactly the same problem on v4.5.3
'on v4.5.3, only with DNS Forwarding option enabled, these sites open normally'

**Comment by zmz125000** [comment]
"bypass China & LAN" = bad
"All" = good

**Comment by dawnchen** [comment]
Same problem, return to 4.5.1, works like a charm.

**Comment by Mygod** [comment]
@madeye This is very interesting... When routing is set to all, the server spits `invalid host name` and eventually blocks. It seems like ss-local is malfunctioning only when it's not passed `--acl <file>`.

**Comment by Mygod** [comment]
It seems like b0d0be1f9da4333cc5052b65dc361ca87b612d13 broke all routing.

**Comment by Red54** [comment]
[All]
$ nslookup gist.github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   gist.github.com
Address: 192.30.253.118
Name:   gist.github.com
Address: 192.30.253.119

[Bypass LAN]
$ nslookup gist.github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   gist.github.com
Address: 192.30.253.119
Name:   gist.github.com
Address: 192.30.253.118

[Bypass mainland China]
$ nslookup gist.github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   gist.github.com
Address: 192.30.253.118
Name:   gist.github.com
Address: 192.30.253.119

[Bypass LAN & mainland China]
$ nslookup gist.github.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   gist.github.com
Address: 59.24.3.173

**Comment by andrew0x0** [comment]
Hi all, now my situation is dns reslove google.com is poisoned. Oreo with SS-android 4.5.3 with gfw list opntion only web access google is not ok ,but google player and web access twitter is both ok. So i want to enable dns forward,but ss-android seems cant's dns reslove when server site enable -u option. So any one meet my situation ? Any soluation ? thanks.

**Comment by madeye** [comment]
Closed as off-topic now.
