### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [shadowsocks/shadowsocks-android#1714]
Hello, sir. I want to offer you something, do you need a new logo for your application? if you want i can make it.

**Comment by Mygod** [comment]
Show me. You're not going to get paid however.

**Comment by redmusic27** [comment]
Yes sir. I will start to make a logo for you. if it is ready I will be back. I do not ask for payment. I'm happy if later my logo you directly use

**Comment by redmusic27** [comment]
Hello sir, I came back with some logo options that you like.

![1](https://user-images.githubusercontent.com/37577374/38382597-8a0efdda-3934-11e8-9ea6-0a488f6f7cca.jpg)
![2](https://user-images.githubusercontent.com/37577374/38382598-8a47a1c6-3934-11e8-881f-69f9e6d57dcc.jpg)
![3](https://user-images.githubusercontent.com/37577374/38382599-8a8818be-3934-11e8-8033-555f9e9b4a4a.jpg)
![4](https://user-images.githubusercontent.com/37577374/38382600-8ace532e-3934-11e8-9681-693f21e80bd0.jpg)
![5](https://user-images.githubusercontent.com/37577374/38382602-8b0a64d6-3934-11e8-8fdb-cb674d1fac04.jpg)

Which one do you like? if I personally prefer the last one. if you have determined it, i immediately make all its file for you. regards
