### ISSUE TITLE
Does not work with Mi Box Remoter

### ISSUE THREAD

**Issue by ZhaoXiangXML** [shadowsocks/shadowsocks-android#1716]
### Environment

* Android version: *Not Sure*
* Device: *Mi Box 3 小米盒子3增强版*
* Shadowsocks version: *v4.5.3*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I tried to select a Encrypt method but the drop down does not change when I press the "Down" button on remoter.

I think this link could be helpful: [电视/盒子应用开发指南](https://dev.mi.com/doc/p=2212/index.html)

小米盒子的遥控器不能切换加密方式

**Comment by Mygod** [comment]
> *Not Sure*

Go find out. This app works perfectly fine with Android d-pad navigation on Android 8.1.

**Comment by ZhaoXiangXML** [comment]
The TV About section says "MIUI TV 1.5.63", and this [link](http://www.mi.com/en/mibox/) says "Android TV 6.0"

**Comment by Mygod** [comment]
Please wait for upstream to merge the fix. Thanks for the report.

**Comment by ZhaoXiangXML** [comment]
Thanks, I'll try a new version a few days later
