### ISSUE TITLE
Battery drain with China Unicom 4G network

### ISSUE THREAD

**Issue by Platway** [shadowsocks/shadowsocks-android#1719]
### Environment

* Android version: 8.1.0, stock, non-rooted
* Device: Nokia 8 (TA-1052)
* Shadowsocks version: 4.5.3 arm64-v8a
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

Daily use with Shadowsocks on, connected to home WiFi network or China Unicom 4G SIM card.

### What did you expect to see?

Normal battery consumption.

### What did you see instead?

Shadowsocks consumes way much more battery on China Unicom 4G network than on WiFi network. While it's with 4G network all day, battery drains fast and Shadowsocks is on the top of the battery statistics; while it's with WiFi all day, Shadowsocks consumes much less battery and is near the bottom of the battery statistics.

**Comment by madeye** [comment]
Please read the FAQ first.
