### ISSUE TITLE
China Unicom 4G network issue

### ISSUE THREAD

**Issue by Platway** [shadowsocks/shadowsocks-android#1722]
I HAVE ALREADY READ THE FAQ, AND THIS IS NOT THE CASE IN THE FAQ! PLEASE DO READ IT THROUGH! THANK YOU SO MUCH!

### Environment

* Android version: 8.1.0, stock, non-rooted
* Device: Nokia 8 (TA-1052)
* Shadowsocks version: 4.5.3 arm64-v8a
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: xchacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable): 
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

Daily use with Shadowsocks on, connected to home WiFi network or China Unicom 4G SIM card.

### What did you expect to see?

Battery consumption similar when using WiFi or cellular network.

### What did you see instead?

Shadowsocks consumes way much more battery on China Unicom 4G network than on WiFi network. While it's with 4G network all day, battery drains fast and Shadowsocks is on the top of the battery statistics; while it's with WiFi all day, Shadowsocks consumes much less battery and is near the bottom of the battery statistics.

I HAVE ALREADY READ THE FAQ, AND THIS IS NOT THE CASE IN THE FAQ! PLEASE DO READ IT THROUGH! THANK YOU SO MUCH!

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-does-shadowsocks-consume-so-much-battery-on-android-50

**Comment by madeye** [comment]
Make sure you understand that battery consumption of 4G network is much larger than WiFi

**Comment by studentmain** [comment]
4G network is unstable, when connection lost (or nearly lost), high battery
consume is expected. If you installed Google Service, it will also try
reconnect (and use battery) when connection lost.

Platway <notifications@github.com> 于 2018年4月2日周一 10:17写道：
