### ISSUE TITLE
External Native Build Issues

### ISSUE THREAD

**Issue by KevinDestinydoor** [shadowsocks/shadowsocks-android#1723]
**I  download  the  project  but gradle failed  and  got  this  message:**

External Native Build Issues
Build command failed.
Error while executing process D:\asAnother\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -ID:/shadowsocks-android-master/core/src/main/jni/libancillary -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_6process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
4/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
Build command failed.
Error while executing process D:\asAnother\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"
copy /b/y "D:\asAnother\Android\sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86" > D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot D:/shadowsocks-android-master/core/src/main/jni D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures D:/shadowsocks-android-master/core/src/main/jni/libancillary D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include D:/shadowsocks-android-master/core/src/main/jni/mbedtls/include D:/shadowsocks-android-master/core/src/main/jni/pcre/dist D:/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv4 D:/shadowsocks-android-master/core/src/main/jni/badvpnprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.
/lwip/src/include/ipv6 D:/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custom" >> D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -ID:/shadowsocks-android-master/core/src/main/jni/libancillary -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem
md "D:\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a D:/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

**Comment by KevinDestinydoor** [comment]
好纠结啊 跑不起来

**Comment by KevinDestinydoor** [comment]
External Native Build Issues
Build command failed.
Error while executing process D:\asAnother\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\vpn0402\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\vpn0402\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"
copy /b/y "D:\asAnother\Android\sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86" > D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot D:/vpn0402/shadowsocks-android-master/core/src/main/jni D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures D:/vpn0402/shadowsocks-android-master/core/src/main/jni/libancillary D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include D:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include D:/vpn0402/shadowsocks-android-master/core/src/main/jni/mbedtls/include D:/vpn0402/shadowsocks-android-master/core/src/main/jni/pcre/dist D:/vpn0402/shadowsocks-android-master/core/src/mainprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/vpn0402/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.
/jni/badvpn/lwip/src/include/ipv4 D:/vpn0402/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv6 D:/vpn0402/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custom" >> D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -ID:/vpn0402/shadowsocks-android-master/core/src/main/jni/libancillary -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/vpn0402/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/vpn0402/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o
Build command failed.
Error while executing process D:\asAnother\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\vpn0402\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\vpn0402\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -ID:/vpn0402/shadowsocks-android-master/core/src/main/jni/libancillary -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/support/include -ID:/vpn0402/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/vpn0402/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem
md "D:\vpn0402\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem
D:/aprocess_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/vpn0402/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
sAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -ID:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/asAnother/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/asAnother/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
D:/asAnother/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"
D:/asAnother/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a D:/vpn0402/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

**Comment by whiyc** [comment]
I I have the same problem

**Comment by madeye** [comment]
Building on Windows is not supported.

**Comment by KevinDestinydoor** [comment]
where should  I building on? Linux  or Mac?

**Comment by madeye** [comment]
Both should work.
