### ISSUE TITLE
4.5.4这个版本报错：connection closed by peer

### ISSUE THREAD

**Issue by LongTaiJun** [shadowsocks/shadowsocks-android#1730]
最新的shadowsocks-arm64-v8a-4.5.4这个版本在我的oneplus 5t手机上测试ping值会显示：失败connection closed by peer。。。代理也没法正常使用。

**Comment by GitatHub** [comment]
我的手机跟你一模一样，我这里一切正常。由于没有使用插件，暂时没遇到 #1727 这个问题，不过似乎已经看到被修复了。
建议你按模板报告问题，或许开发者能帮你定位问题。

**Comment by akzhangweiyi** [comment]
我用universal版也遇到相同問題。三星S8.

**Comment by Mygod** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-android/commit/a338395030d0874648a9e6eb21d2aa7652adc610.
