### ISSUE TITLE
Is there any way to log destination IPs for all connections through ss?

### ISSUE THREAD

**Issue by oasisfeng** [shadowsocks/shadowsocks-android#1732]
I'm hoping to use shadowsocks to better understand the underlying connections, to fine tune my partial proxy setup on my home router.

It will be more helpful if connection can be tagged by app.

**Comment by madeye** [comment]
It's possible to log connections on routers with ss-redir.

To enable connection log on Android, you have to modify the code, adding '-v' option to the command line in BaseService.kt.

**Comment by oasisfeng** [comment]
@madeye Thanks for the tip.
