### ISSUE TITLE
4.5.4使用simple-obfs插件不能正常链接/4.5.4 when useing simple-obfs plugin does not connect

### ISSUE THREAD

**Issue by neweva** [shadowsocks/shadowsocks-android#1734]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
8.0
* Device: *e.g. Google Pixel XL*
mix2
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
shadowsocks--universal-4.5.4
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
使用simple-obfs插件不能正常链接 关闭后能正常连接 
降级使用4.5.3没有这个问题
v4.5.4 useing simple-obfs plugin does not connect when turn off the plugin can be connect
There is no such issue before

**Comment by Mygod** [comment]
Use 4.5.5.

**Comment by Love4Taylor** [comment]
同样的问题
