### ISSUE TITLE
为什么更新到新版本后，延时成倍增加？

### ISSUE THREAD

**Issue by joesufe** [shadowsocks/shadowsocks-android#1737]
为什么更新到新版本后，延时成倍增加？如题。以前都是200左右，现在至少700-800，甚至1000以上。

**Comment by Yubyf** [comment]
我也有点疑惑，可能是检测方法更改了

**Comment by Mygod** [comment]
Since daea4b5f6cd350fe473f6ea22594da2f8c3b487e/v4.5.0, the measured time is correctly represented as a full TLS handshake.
