### ISSUE TITLE
哪个版本开始需要谷歌框架？

### ISSUE THREAD

**Issue by realpg** [shadowsocks/shadowsocks-android#1739]
如题
今天哥们的新MIX2S下载了最新版 提示需要谷歌框架支持

我机器里的4.2.x并不需要谷歌框架支持

翻了一下更新说明 没发现哪里写自哪个版本开始需要框架

另外，问下用了框架的啥功能导致后面的版本需要框架

**Comment by Mygod** [comment]
GMS is required for scanning QR codes since 4.5.0. You can still use third party scanners if you don't have GMS.
