### ISSUE TITLE
CANNOT connect to my services after updated to 4.5.4

### ISSUE THREAD

**Issue by HanYL-coder** [shadowsocks/shadowsocks-android#1741]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: latest 8.1
* Device: Google Pixel2 XL
* Shadowsocks version: 4.5.4 4.5.5
* Last version that did not exhibit the issue (if applicable): 4.5.3

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Updated to 4.5.4 and 4.5.5

### What did you expect to see?
Connect to the servers my SP provided

### What did you see instead?
connection test says server unavailable

I uninstalled the 4.5.5 and installed back to 4.5.3, it's working perfectly fine.
Maybe "Refine the local DNS resolver." got something wrong.
My SP provided domain, not ip adresses. So there must be something wrong with the DNS resolver.

**Comment by HanYL-coder** [comment]
btw, could u tell me which package should I choose for my device? I've always using universal, but the play wants me to update it.

**Comment by Mygod** [comment]
That's fine.
