### ISSUE TITLE
Mixed address server domain cannot connect

### ISSUE THREAD

**Issue by giftzn** [shadowsocks/shadowsocks-android#1743]
### Environment

* Android version: *8.0.0 (OPR1.170623.027)*
* Device: *Xiaomi MIX*
* Shadowsocks version: *4.5.5*
* Last version that did not exhibit the issue (if applicable): No

### Configuration

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* [x] Auto Connect
* [x] TCP Fast Open

### What did you do?
Server Address Domain Name Contains IPV4 and IPV6 Addresses, Direct use of IPV4 connection is normal.

### What did you expect to see?
This is a recent sudden problem. It is unclear whether it is related to cloudflare domain name resolution or operator DNS resolution. Pinging a server on a mobile phone is to return a normal V4 address.

### What did you see instead?
Domain name containing IPV6 server address cannot be linked.

**Comment by Mygod** [comment]
Your device might have a valid IPv6 address that's causing this app to use IPv6 address. I just reproduced this issue by connecting my device to an IPv4-only Wi-Fi (which became the default network) but with a valid cellular IPv6 address.

I think the best way to fix this is https://github.com/shadowsocks/shadowsocks-libev/issues/942. @madeye What do you think?

**Comment by madeye** [comment]
It's not trivial to support dual-stack-address hostname in ss-local. My suggestion is not using this hostname at all.

**Comment by giftzn** [comment]
The problem is solved, but I'm not sure if it's a bug:
If my main card is **ChinaMobile** (_4G VoLTE_), this problem will occur. 
After the primary card is switched to **ChinaUnicom** (_4G_), the problem disappears.

**Comment by Mygod** [comment]
It's working as intended. As @madeye pointed out, currently there's no plan to fix https://github.com/shadowsocks/shadowsocks-libev/issues/942 so until that is fixed, you should make explicit whether you want to connect to IPv4 or IPv6 address.
