### ISSUE TITLE
通知栏快捷菜单消失

### ISSUE THREAD

**Issue by fyzs999** [shadowsocks/shadowsocks-android#1745]
### Environment

* Android version: *7.1.1  (vivo funtouch os 3.2)*
* Device: *vivo x20*
* Shadowsocks version: *“v4.5.5"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
shadowsocks通知栏快捷菜单使用起来非常方便.可以一键vpn

### What did you expect to see?
通知栏快捷方式能够维持拖拽后的固定位置，自行安装任意其他apk软件，重启手机后，快捷菜单不消失
![screenshot_20180409_222724](https://user-images.githubusercontent.com/378109/38504109-6f521864-3c46-11e8-8a16-2ea53fc19520.jpg)

### What did you see instead?
通知栏快捷方式能够维持拖拽后的固定位置，自行安装任意其他apk软件，重启手机后，快捷菜单消失。
菜单图标会变到不显示的地方，需要重新拖动通知栏菜单到我想要的位置才行。（此种方法不一定100%重现，但是高概率重现）
![screenshot_20180409_223228](https://user-images.githubusercontent.com/378109/38504133-7ac06d04-3c46-11e8-8a49-70beae3e6491.jpg)

微信和支付宝的扫一扫和付款码的通知栏快捷菜单都没有这个问题。

恳请优化适配vivo，谢谢

**Comment by Mygod** [comment]
We are not going to provide support for third-party ROM features as it would be impossible to maintain. Feel free to create a fork and provides additional features there.
