### ISSUE TITLE
Failed to connect to android.googlesource.com port 443: Connection refused

### ISSUE THREAD

**Issue by tangxu0717** [shadowsocks/shadowsocks-android#1746]
Cloning into 'D:/github/shadowsocks-android/core/src/main/jni/pcre'...
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Connection refused
fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path 'D:/github/shadowsocks-android/core/src/main/jni/pcre' failed
Failed to clone 'core/src/main/jni/pcre' a second time, aborting

请问这个编译报错如何解决？

**Comment by imkobedroid** [comment]
请问一下这个是怎么解决的呢 我现在也遇到了相同的情况！
