### ISSUE TITLE
[Feature request] Custom rules sources

### ISSUE THREAD

**Issue by abbradar** [shadowsocks/shadowsocks-android#1752]
### Environment

* Shadowsocks version: 4.5.5

It'd be great to have an option to specify a URL for a list for blocked domains which should be routed through shadowsocks. The list could be synced periodically but one-time load from an URL would be good too (a user can then manually reload rules from time to time). Usecase: I'd like to use Russian censored websites [list](https://github.com/zapret-info/z-i) -- I could convert its format to one used by Shadowsocks and publish automatically.

Side notice: this list is most useful when IP addresses from it are used, not hostnames. I'm not sure if Shadowsocks would interpret IP addresses in rules list correctly now.

**Comment by abbradar** [comment]
Ouch, I didn't notice an arrow in "Edit rule" where you can select this! Sorry for this, is there some kind of documentation where this is mentioned? I'd be glad to contribute an entry to FAQ if there isn't anything else.

What about IP addresses -- can you use them and/or subnets in this list?

**Comment by abbradar** [comment]
It seems IP addresses do work -- thank you again. I'm still glad to contribute documentation, just point me where should I add it.

**Comment by Mygod** [comment]
Let's just hope people will find this issue through search.
