### ISSUE TITLE
Poisoned DNS response for foreign domains under Bypass LAN & China route mode

### ISSUE THREAD

**Issue by hexchain** [shadowsocks/shadowsocks-android#1754]
### Environment

* Android version: 8.1.0
* Device: Pixel 2 XL
* Shadowsocks version: 4.5.5
* Last version that did not exhibit the issue (if applicable): Not sure

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encryption method: Not relevant I believe
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 1.1.1.1
* [ ] DNS Forwarding
* Plugin configuration (if applicable): simple-obfs
* [ ] Auto Connect
* [x] TCP Fast Open (force enabled)
* If you're not using VPN mode, please supply more details here:

### What did you do?
Start Shadowsocks and let it run for a while, and:

- try to open `www.instagram.com` in Chrome

or

- install Termux (and make sure it's not whitelisted in Shadowsocks) and execute `host www.instagram.com`.

### What did you expect to see?
Chrome successfully opens `www.instagram.com`.
The `host` command returns an IP that belongs to Instagram.

### What did you see instead?
Chrome cannot navigate to `www.instagram.com` with error code `ERR_FAILED`.
The `host` command returns an IP starting with `243`, which is "reserved for future use" according to RFC, indicating that the result may be poisoned.

Toggling Shadowsocks may fix this issue temporarily.

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.5.6

**Comment by madeye** [comment]
In fact, it's almost impossible to get any IP starting with 243, as it should be detected by our china DNS module: https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/assets/overture/china_ip_list.txt#L14

**Comment by vovoa17** [comment]
I have a same question.
version:4.5.6
fake dns result:243.185.187.39

**Comment by madeye** [comment]
Could you uninstall and reinstall the APK?
