### ISSUE TITLE
transfer udp packet as tcp packet

### ISSUE THREAD

**Issue by prashantvidja** [shadowsocks/shadowsocks-android#1755]
Hello,

can we transfer udp packet shadowsocks-client to shadowsocks-server as tcp packet?

Thanks

**Comment by prashantvidja** [comment]
hello @madeye 

sorry, i mean we want to transfer VoIP data over tcp by shadowsocks. Is this possible?

Thanks @madeye  for your precious replay

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1756#issuecomment-381868727
