### ISSUE TITLE
Manual configuration via file?

### ISSUE THREAD

**Issue by feidaman** [shadowsocks/shadowsocks-android#1761]
Hi, quick question, where does shadowsocks-android store its settings? Is the file human-friendly? I use Shadowsocks on Windows and automatically generate the _gui-config.json_ config file using a script. I would like to be able to deploy this file to my android devices without having to scan QR codes or worse yet manually entering the configuration (e.g. Android-based TV). Thanks!

**Comment by madeye** [comment]
Try URL based config instead: https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html

**Comment by feidaman** [comment]
That would be very nice!
