### ISSUE TITLE
CLEARTEXT communication to host not permitted by network security policy

### ISSUE THREAD

**Issue by imkobedroid** [shadowsocks/shadowsocks-android#1765]
Loading the whole project, running on a mobile phone is a manual configuration of several servers that can be used, but today I added a new page with a page own okhttp3 and retrofit for data requests, but I have been reporting not permitted by network security policy, but I am in my other items. It's no problem with this address in the eye.

**Comment by V-E-O** [comment]
HTTPS enforced

**Comment by shellhub** [comment]
[Solution on YouTube](https://www.youtube.com/watch?v=nADShH87zVg)
add `android:usesCleartextTraffic="true"` to `application` tag in `AndroidManifest.xml` 
``` xml
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">
```
