### ISSUE TITLE
Local Forwarding DNS issue in *new* rooted Devices

### ISSUE THREAD

**Issue by HAMIDx9** [shadowsocks/shadowsocks-android#177]
Hi,

Sorry for interrupting, there might be an issue on side of me but i think it's so valuable to discuss.

As of my experiments there is an issue in using pdns and iptables in order to avoiding DNS leakage.
After rooting device i noticed that shadowsocks no longer works, I checked several things, but ss-tunnel, pdns , ... all worked fine. by diging into iptables rules i noticed when i remove OUTPUT DNAT rule for forwarding dns (--line-number = 4), browser and all gui apps works fine. but there was no secure dns resolving. 
I also used dnscrypt and write 'nameserver 127.0.0.1' on top of resolv.conf but again this issue occurs. also with setting ndc for if.

As i can see in my adb shell resolver just works fine (dnscrypt, shadowsocks, and ...) but in this way on gui apps there's still problem, which non-censored sites also are not reachable (but after removing that rule, non-censored sites fixes).

As we know ui apps are using **ndc** in order to resolving domains. so resolv.conf and setprop does not work anymore. but it seems there is an issue in new phones maybe udp in local, since when i use my PC as DNS server it works fine (just what you did by using DNAT rule). 

```
iptables -t nat -D OUTPUT 5
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 192.168.1.53:53
```

I've tested this situation on two devices : LG G3 (rooted), LG G PRO Lite (rooted). 
It's worth to mention that non-rooted device works fine.

I'm courius if anyone has experience in this issue. 

Thank you

**Comment by firemeteorxx** [comment]
Question: by 'no ROOT mode' do you mean denying the su request from shadowsocks or to unroot the device entirely? I tried with former choice and shadowsocks go back to VPN mode. But the DNS issue is NOT fixed. I don't want to try unroot the device.

PS: In my case, adb shell also don't resolve DNS request even HAMIDx9 reported the other way.

**Comment by HAMIDx9** [comment]
No, As you may know in root mode shadowsocks-android use iptables to route the traffic, but in VPN mode (like what fqrouter does) it uses VPNService. In case you don't need to unroot your device. 

In Fqrouter, make sure you are using VPN( via vpnservice api) in Setting -> Launch Mode

DNS resolving in Shell just happend when i forward the DNS traffic to my own DNS server in my local network.

**Comment by HAMIDx9** [comment]
Also please use `ndc` to set DNS to 127.0.0.1 as below : 
`# ndc resolver flushif wlan0`
`# ndc resolver flushdefaultif`
`# ndc resolver setifdns wlan0 127.0.0.1`
`# ndc resolver setdefaultif wlan0`

or any if, or other DNS.
