### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by get233** [shadowsocks/shadowsocks-android#1772]
###  Environment
Android version: 8.1.0
Device: Google Pixel
Shadowsocks version: “v4.5.6"

### Configuration

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 208.67.222.222
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open

### What did you do?
从4.5.0版本开始，无论用什么服务器，在shadowsocks主界面测试延迟都不准确，即便使用距离我最近的香港线路，测试延迟波动都很大，屡屡超过300ms，起初我认为是我自身的原因，检查了服务端和线路，发现没有问题，而且用speedtest测速，延迟也是正常的，后来我尝试换到了4.4.6版本发现客户端主界面的延迟测试就正常了，测试稳定23ms，也没有波动，换回4.5.0以上的版本，依然如故

### What did you expect to see?
求解，另，开发者接受PayPal捐赠吗？

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1737#issuecomment-379598379
