### ISSUE TITLE
obfs-host can't be blank

### ISSUE THREAD

**Issue by Platway** [shadowsocks/shadowsocks-android#1774]
### Environment

* Android version: 8.1.0, stock, non-rooted
* Device: Nokia 8 (TA-1052)
* Shadowsocks version: 4.5.7 arm64-v8a
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

Setting obfs-host to blank.

### What did you expect to see?

SS works normally with no obfs-host.

### What did you see instead?

SS does not work after connected because of the ";obfs-host=" in obfs parameter string.

My suggestion:

1. When obfs-host is blank, eliminate ";obfs-host=" from the obfs parameter string; OR

2. Allow user to edit the entire parameter string for obfs.

**Comment by madeye** [comment]
It's expected. `obfs-host` should never be blank.

**Comment by Platway** [comment]
In Windows version, and in Simple Obfuscation plugin itself, obfs-host is optional. When it's not set (i.e. "obfs-host=" parameter not specified), it means no dest host obfuscation, only disguising as tls/http. This is useful for some carrier (for instance, China Unicom in some cities) to beat sniffer and QoS. Thank you and enjoy your day!

**Comment by Platway** [comment]
And if it's impossible to leave obfs-host blank in Android version, i think it's better to show an error msg when user sets the option to blank. Thanks!

**Comment by madeye** [comment]
> it means no dest host obfuscation, only disguising as tls/http. This is useful for some carrier (for instance, China Unicom in some cities) to beat sniffer and QoS.

Actually not, without specify obfs-host, it will use the default one, e.g. www.baidu.com
