### ISSUE TITLE
自己重新新建的项目，实现自动获取ss账号密码以及acl，出现在5.1.1的机器上都能成功，在7.0以上的机器上时好时不好的情况，请问这个是什么原因导致的？

### ISSUE THREAD

**Issue by liwux** [shadowsocks/shadowsocks-android#1775]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

自己重新新建的项目，实现自动获取ss账号密码以及acl，出现在5.1.1的机器上都能成功，在7.0以上的机器上时好时不好的情况，请问这个是什么原因导致的？
是不是高版本的android 我忽略了没什么没配置？有遇到吗

**Comment by studentmain** [comment]
自己的项目自己调嘛……
要请别人调你也把代码和logcat什么的发出来嘛……
不过你说的"自动获取"是指从哪获取，突然有点好奇

Xinxin.HAN <notifications@github.com> 于 2018年4月26日周四 12:25写道：

**Comment by liwux** [comment]
也没有任何报错提醒。

    override fun onServiceDisconnected(name: ComponentName?) {
        unregisterCallback()
        instance.onServiceDisconnected()
        service = null
        binder = null
    }

每次触发这个 之后 成功率会很大

**Comment by liwux** [comment]
这个报错有用吗？

04-26 12:37:15.174 4827-6607/? E/PushLog2847: [SocketRead_12:37:14-9579]connect occurs :com.huawei.android.pushagent.datatype.PushException: java.net.SocketException: Software caused connection abort(android/null:-1)
    com.huawei.android.pushagent.datatype.PushException: java.net.SocketException: Software caused connection abort
        at z.bp(Unknown Source)
        at com.huawei.android.pushagent.model.channel.entity.SocketReadThread.run(Unknown Source)
     Caused by: java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at java.net.SocketInputStream.read(SocketInputStream.java:206)
        at ab.read(Unknown Source)
        at z.bp(Unknown Source) 
        at com.huawei.android.pushagent.model.channel.entity.SocketReadThread.run(Unknown Source)
