### ISSUE TITLE
No Connection if mobile using WiFi's SSID with space character

### ISSUE THREAD

**Issue by hctt00** [shadowsocks/shadowsocks-android#1777]
I found something strange.

If my mobile connects SSID with space character, e.g. SSID: Free WiFi , the APP can connect my ss server around 20 minutes. After that, it said it can connect my ss server but has no data transmission.

At the same time, I test my server using iPhone and Windows laptop. They can use my ss server successfully.

When I change my WiFi SSID without any space characters, no more problem appears.

**Comment by madeye** [comment]
I don't think it's related to shadowsocks.

When connecting to a Free WiFi, try disconnect the client and login in your browser first.
