### ISSUE TITLE
"Buy SS account" button/link idea

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-android#1779]
1) need an SS server(s) to provide a safe tunnel to "buy service" (all other sites may be blocked)
2) need some SS account sellers (maybe some infrastructure for third-party SS providers so they can place offers).

**Comment by studentmain** [comment]
So, who will be the seller? Is the seller reliable? Will the developers (
who "provide VPN service in China") safe?
SS is just a simple socks5 proxy tool, you shouldn't have too high
expection of it. It just a tool, not a service. It haven't any AAA ability,
it just a proxy which accept all inbound connection, password is just for
encryption, not for accounting.
If you want buy an account, you just need buy a VPS and **apt install
shadowsocks-libev** then enjoy your private tunnel.

Dmitry <notifications@github.com> 于 2018年4月30日周一 11:23写道：

**Comment by dimzon** [comment]
I realize evrything you wrote. But
1) is the seller reliable - must deside a user - you just provide a link or button to seller and sellers can sponsor your work with a bit of money just for placing link/button  inside your app (or maybe some kind of refferal program) - a win-win state isn't it?

2) it's possible to automate process buy cheap vps onto linode/digitalOcean/vultur+deploy SS server onto it (I saw somewhere same for OpenVPN-related solution, they got +2$ fee per installation). 

This will be usefull for non-geek users so they can get SS account easy. This can be usefull for 3-rd party SS providers. This can be usefull for you (referal programs, sponsorship etc)

**Comment by trulyliu** [comment]
Why do you use ss?
there are many commercial VPN service providers.

Max Lv <notifications@github.com> 于 2018年4月30日周一 13:21写道：

**Comment by dimzon** [comment]
I am geek. I just think about other users

пн, 30 апр. 2018 г., 8:34 trulyliu <notifications@github.com>:

**Comment by trulyliu** [comment]
Non-geek users should use commercial VPN service.

Dmitry <notifications@github.com> 于 2018年4月30日周一 13:36写道：

**Comment by trulyliu** [comment]
Full commercial service are not the goal of ss-android, neither other ss
variants .
Some VPN sevice provider from China eg. 天梯 are in jail now.

SS devs are not living in Shangrila, they live in realy countries.



Dmitry <notifications@github.com> 于 2018年4月30日周一 13:36写道：
