### ISSUE TITLE
Problem for Apps VPN mode

### ISSUE THREAD

**Issue by wordlesswind** [shadowsocks/shadowsocks-android#1781]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: * "8.0.0", HydrogenOS*
* Device: * OnePlus 3T*
* Shadowsocks version: *version code "v4.5.7"*

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
  * [ ] IPv6 route
  * [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable): obfs=tls;obfs-host=cloudflare.com
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you see instead?
![2018-05-01-21-54-14](https://user-images.githubusercontent.com/9050713/39475743-089162c2-4d8c-11e8-81d7-6f86c1161fc7.gif)

**Comment by wordlesswind** [comment]
MP4: [2018-05-01-21-54-14.zip](https://github.com/shadowsocks/shadowsocks-android/files/1963988/2018-05-01-21-54-14.zip)
I can't slide the list.

**Comment by madeye** [comment]
Report it to OnePlus or try Oxygen OS instead.

**Comment by Mygod** [comment]
Is there an old version that works for you?

**Comment by wordlesswind** [comment]
@Mygod 
Yes, I don't know when the bug appears.

**Comment by wordlesswind** [comment]
Reinstall is be fine.
