### ISSUE TITLE
need compatible Android O

### ISSUE THREAD

**Issue by conncui** [shadowsocks/shadowsocks-android#1782]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "8.0.0", more detailed description is preferred*
* Device: HuaWei Honor V9
* Shadowsocks version: *version code "v4.5.7" 
* Last version that did not exhibit the issue (if applicable):

In Android  O , background Execution is be Limited, and i don't see the Notification from SS,
it cause the VPN can't connect .

**Comment by madeye** [comment]
Uninstall and reinstall shadowsocks.

It'd be a known bug of Huawei that you need to reinstall shadowsocks after upgrading the system.

**Comment by Mygod** [comment]
Sorry we only support Android P, no love for Oreo.

**Comment by conncui** [comment]
@madeye Yes, it's work . Thanks
