### ISSUE TITLE
Cannot connect to server by name, only by numeric IP address

### ISSUE THREAD

**Issue by ralphrmartin** [shadowsocks/shadowsocks-android#1786]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1
* Device: OnePlus 5
* Shadowsocks version: 4.5.7
* Last version that did not exhibit the issue (if applicable): Unknown

### Configuration

_Put an `x` inside the [ ] that applies._

* [*IPv4 server address
* [ ] IPv6 server address
* [*] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [* All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [*] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [*] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
(1)  Tried to open a server by name, e.g. ss-server.example.com
(2) Tried to open the same server by numeric address, e.g. 1.2.3.4

### What did you expect to see?
server connected in both cases

### What did you see instead?
Server does not connect in case (1), but does connect in case (2).

It would be useful in profiles to allow servers to be specified by name, as well as by numeric address: my server has a dynamic DNS address. It's name never changes, but its numerica address frequently does.

**Comment by madeye** [comment]
It looks the client got an old IP of your DDNS enabled hostname.

Double check your DNS records and make sure the TTL is small enough.

**Comment by ralphrmartin** [comment]
OK, thanks. My DDNS updater may be at fault. Sorry to waste your time.
