### ISSUE TITLE
4.5 版本不能扫描二维码

### ISSUE THREAD

**Issue by osdu** [shadowsocks/shadowsocks-android#1788]
4.5 版本不能扫描二维码

![screenshot_2018-05-05-21-34-01-448_com github sha_](https://user-images.githubusercontent.com/2067880/39663822-8c5cec16-50ac-11e8-93a7-64880cd5caa8.jpg)

**Comment by madeye** [comment]
It's expected.

Two choices:

1. Install Google Play on your phone.
2. Use a third-party QR scanner.

**Comment by osdu** [comment]
@madeye 
1. 为了扫个码安装GG全家桶，没必要
2. MIUI 相机和自带的扫一扫都可以扫码，然而没蛋用

shadowsocks-android 和 shadowsocks-libev 均已经换回旧版了，不知道最近的更改出于何种考虑，原先用好好的更新后都出问题了

**Comment by XiangShao333** [comment]
> @madeye
> 
> 1. 为了扫个码安装GG全家桶，没必要
> 2. MIUI 相机和自带的扫一扫都可以扫码，然而没蛋用
> 
> shadowsocks-android 和 shadowsocks-libev 均已经换回旧版了，不知道最近的更改出于何种考虑，原先用好好的更新后都出问题了

我也是这个问题，然后安装Google play 商店后，打开就闪退，说是少GMS服务，真的是一环套一环，不知道谷歌想干嘛，太麻烦了，而且即使是为了推销，能不能集成在一起啊，别一个套一个啊，心累o(╥﹏╥)o
