### ISSUE TITLE
NFC share is not work on configuratins with plugin

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-android#1789]
### Environment

* Android version: **7.0**
* Device: **Samsung S6 edge * 2**
* Shadowsocks version: **4.5.7**
* Last version that did not exhibit the issue (if applicable): **N/A**

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: **1.1.1.1**
* [ ] DNS Forwarding
* Plugin configuration (if applicable): **go-quiet**
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Sharing config between mobiles by NFC.

### What did you expect to see?
The target mobile is get configured by NFC.

### What did you see instead?
Nothing happens here. No config item appears. (It seems like the target dropped NFC message)

**BUT**, if I choose to share the config by copy out (from source mobile) -> send to the target -> paste in (to target mobile), it works.

EDIT: NFC is work on config without plugin.

**Comment by Mygod** [comment]
Does NFC work with configs without plugins?

**Comment by kimw** [comment]
> Does NFC work with configs without plugins?
Yes

**Comment by Mygod** [comment]
Unfortunately I was unable to reproduce this issue.

**Comment by kimw** [comment]
Cannot reproduce in v4.6.0 (maybe fixed). Close this issue.
