### ISSUE TITLE
LoadBalancer

### ISSUE THREAD

**Issue by hoseinit** [shadowsocks/shadowsocks-android#1791]
Hey guys,
Thanks for making such a great App,
I would like to suggest making an embedded load balancer. If the user has two or more servers to connect, the load balancer should decides to choose with which server should the app routes the traffic through.
It can be a simple ping to servers each 10 seconds or so ...
Thanks

**Comment by madeye** [comment]
No plan for this.

**Comment by madeye** [comment]
Also search the issue tracker for previous discussions on it.
