### ISSUE TITLE
后台服务启动失败：请选择配置文件

### ISSUE THREAD

**Issue by microsoftBoy** [shadowsocks/shadowsocks-android#1792]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.0.0*
* Device: *meizu PRO 6 Plus*
* Shadowsocks version: *v4.5.7"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [Y ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [Y ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ Y] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you see instead?
我已经配置了新的配置文件并选中，但是启动的时候，会提示：“后台服务启动失败：请选择配置文件”

**Comment by madeye** [comment]
It's a duplicate issue. Please read the FAQ for more details.

**Comment by MagicalPhantom** [comment]
v4.6.0版本已经成功修复了这个错误。
：）

**Comment by airycanon** [comment]
@MagicalPhantom 魅族 Pro 6 Plus 并没有解决……

**Comment by MagicalPhantom** [comment]
我的个人经验就是在升级之前，备份当前最新可用的版本。遇到升级到最新版本不可用时滚回之前的版本。

**Comment by MagicalPhantom** [comment]
@airycanon 我的个人经验就是在升级之前，要有备份当前最新可用的版本。遇到升级到最新版本不可用时滚回之前版本。

**Comment by lingshow** [comment]
是的，魅族pro5，用了ss4.6.1也没解决

**Comment by kamileaf** [comment]
我也是魅族Pro 6 Plus，最新的用不了，用4.2.5的版本可以
