### ISSUE TITLE
Feature Request - add port mapping feature

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-android#1795]
It's easy and possible to make in pure java|kotlin - listen on socket NN, forward recieved data to remote:YY using shadowsocks sock5 (client) port, forward reply back to sender.

use case (in my example) - I'm running http proxy at vps  - privoxy + special rules to transparent access to i2p|onion sites + ad-blocking + some geo-based rules (some sites re-routed via another vps|proxies to bypass some geo-restrictions).

I'm using ss-tunnel on all my PC to access privoxy port. I want to access it onto android too.

**Comment by madeye** [comment]
No plan for this.

Since it's a very "technical" feature request, I suggest modifying the code and build your own app.

**Comment by Mygod** [comment]
If you have this app installed, you can simply write a script to invoke libss-tunnel.so which is bundled in this app. No permissions required.
