### ISSUE TITLE
Feature request: tunnel to custom DNS server

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-android#1796]
There are 2 tasks where DNS is used
1) to resolve Shadowsocks server IP
2) to resolve while connected

I really think 1) is enough to use "default" DNS (anyway can use IP instead hostname)
2) custom DNS server can run on Shadowsocks VPS (127.0.2.1:53) for example - need to map it

**Comment by madeye** [comment]
There is a remote DNS option which works as you mentioned.

**Comment by dimzon** [comment]
Try 127.0.0.1 as remote DNS - you will get error
