### ISSUE TITLE
A problem occurred configuring project ':core'.

### ISSUE THREAD

**Issue by kivenC** [shadowsocks/shadowsocks-android#1798]
Please read FAQ then answer these questions before submitting your issue. Thanks!

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> executing external native build for ndkBuild E:\GitHub\shadowsocks-android\core\src\main\jni\Android.mk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by chenwenxiang** [comment]
You have to enough these conditions:
JDK 1.8
Go 1.4+
Android SDK
Build Tools 27+
Android NDK r16+
