### ISSUE TITLE
The connection fails

### ISSUE THREAD

**Issue by jackrow** [shadowsocks/shadowsocks-android#1800]
I compiled and installed the success, clicked the connection, displayed the connection, clicked the test link, returned the failure, and did not connect.

能看到的信息
java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname

and logcat print
 E/Parcel: Reading a NULL string not supported here.

**Comment by jackrow** [comment]
帮助

**Comment by itacajsj** [comment]
<code>No address associated with hostname</code> may means something wrong with your DNS config.

**Comment by jackrow** [comment]
Reading a NULL string not supported here.
Reading a NULL string not supported here.
Reading a NULL string not supported here.
Reading a NULL string not supported here.
Reading a NULL string not supported here.

**Comment by jackrow** [comment]
我没有开启dns转发啊 能定位问题吗

**Comment by jackrow** [comment]
@itacajsj 我没有开启nds转发啊 能定位问题吗？我感觉这个log就是没有连上ss
