### ISSUE TITLE
Add "always use proxy" mode in app VPN mode

### ISSUE THREAD

**Issue by Hzbeta** [shadowsocks/shadowsocks-android#1807]
In app VPN mode, I can choose some apps in baypass mode, so they won't use VPN, but in some situation, I need some apps always use VPN.
  So can you add a new function called blacklist and whitelist.
  Some apps in blacklist will always use VPN, some apps in whitelist won't use VPN forever, other apps which are not included in the black and white list will follow the global route.
  Thank you so much!

**Comment by madeye** [comment]
Just disable `bypass mode`.

**Comment by Hzbeta** [comment]
I want to have both blacklist and whitelist, if I disable bypass mode, I only have blacklist.
I hope that every app has 3 option, VPN mode, direct connection and follow global route.
In VPN mode app will use VPN for all URL, in direct mode app will not use VPN at all and in global mode, app will follow the global route to decide what URLs use VPN and what URLs not.

**Comment by madeye** [comment]
It's impossible. You can only have blacklist or whitelist, which is a limitation of Android system.

**Comment by Hzbeta** [comment]
Oh, it is so sad, thank you at all.
