### ISSUE TITLE
Failed to find target with hash string 'android-27'

### ISSUE THREAD

**Issue by vovoa17** [shadowsocks/shadowsocks-android#1810]
I compile with the latest version (daa9d9f) but there is an error
looks like gradle can't find android 27 sdk
I use:
`export ANDROID_HOME=/root/sdk`
`export ANDROID_NDK_HOME=/root/ndk`
`export GOROOT_BOOTSTRAP=/root/go`
`yes|sdkmanager --licenses`

when i excute the command:
`./gradlew`

![55](https://user-images.githubusercontent.com/29777681/40402224-fe15d218-5e7c-11e8-8b79-0be5b3f4c31a.JPG)

what should i do ?

**Comment by temoto** [comment]
How did you fix it?

**Comment by vovoa17** [comment]
I think this is a mistake that can be avoided.
command:
mkdir sdk
unzip sdk.zip -d sdk
cd sdk/tools/bin/
yes|./sdkmanager --licenses

the key is to extract 'sdk.zip' to a folder named 'sdk', instead of renaming the 'tools' folder to 'sdk'
hope this helps :)
