### ISSUE TITLE
Your app for Fdroid

### ISSUE THREAD

**Issue by theScrabi** [shadowsocks/shadowsocks-android#1811]
Have you thought about putting your app on [fdroid](https://fdroid.org) it's a repositorry for opensource applications.

However in order to support fdroid you might have to remove gsm lib. This could be done by a different build flavour/build type :)

**Comment by madeye** [comment]
No plan for it.

Please search the issue tracker for previous discussions.

**Comment by madeye** [comment]
Nope, we don't have any plan for it.

Old discussions:
https://github.com/shadowsocks/shadowsocks-android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+F-Droid

**Comment by theScrabi** [comment]
Ok if you don't want to receive help from outside. It's your decision.

**Comment by Kein** [comment]
Cant do that when using libs to spy and track/gather phone data :P
