### ISSUE TITLE
Frequent connection problem in Android 8

### ISSUE THREAD

**Issue by liujunhui74** [shadowsocks/shadowsocks-android#1813]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0.0
* Device: Samsung Galaxy S9
* Shadowsocks version: 4.5.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

[x] IPv4 server address
[x] Client IPv4 availability
Encrypt method: rc4-md5
Route
  [x] GFW List

#####
Frequent connection problem. It seems that when switching network (e.g. WiFi to 4G or vice versa), there is a chance of breaking shadowsocks connection. When shadowsocks is broken, it will not provide connection for a very long period of time, including VPN and non-VPN connection. Disconnecting ss will resume the non-VPN connection, but reconnecting ss will not resume the VPN connection. Killing ss and restart it usually doesn't solve the problem. Sometimes ss is not responding to the disconnection button, it can only be disconnected by the system VPN notification bar.

**Comment by madeye** [comment]
It's a know bug of Samsung system. Read the FAQ for more details.
