### ISSUE TITLE
延迟比较高是怎么回事

### ISSUE THREAD

**Issue by wangxiao1995** [shadowsocks/shadowsocks-android#1814]
手机型号OnePlusA5010  一加5T
android8.1  
已root
手机和电脑在同一个wifi 下,电脑ping是100 左右  手机就是500以上,(测试好多次了)
发布的那么多版本应该选择哪一个?
之前用的时候延迟还比较正常,那个版本我找不到了.

**Comment by madeye** [comment]
It's expected. Search the issue tracker for more details.
