### ISSUE TITLE
camera can't scan code。

### ISSUE THREAD

**Issue by Kila2** [shadowsocks/shadowsocks-android#1818]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0?
* Device: Red Mi Note 5
* Shadowsocks version: the last
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
use camera scan code to add rule on Red Mi Note 5. It's screen is 18:9. I think Camera not support this pixel.

### What did you expect to see?
no response

**Comment by madeye** [comment]
Also tried the internal QR code scanner in MIUI, it works as well.

**Comment by Kila2** [comment]
OK. Internal QR code scanner work as well.
But why QR code scanner need Google Play service? I

**Comment by Mygod** [comment]
Because we are using Google Play's vision library and Google decided that it's a good idea to put those into Google Play Service. If you know a better alternative we'd happy to use that instead.
