### ISSUE TITLE
Can't switch it by button on status bar

### ISSUE THREAD

**Issue by huiyifyj** [shadowsocks/shadowsocks-android#1819]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1.0  (OxygenOS 5.1.2)
* Device: OnePlus 5T
* Shadowsocks version: v4.5.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

At present, the switch in the pull-down of the status bar is not available for most of the time. More to see attached picture.
I used to switch ss by the status bar before, but now I have to turn on app to turn it on.
This has not happened in my phone before.
![5b134ddecbafe](https://user-images.githubusercontent.com/32027253/40882512-fe4d4408-6716-11e8-823b-45a6857bd840.jpg)

**Comment by kalonelee** [comment]
Set [Battery optimization] to [Don't optimize] may fix this.

**Comment by madeye** [comment]
It looks your system killed the background service of shadowsocks, try https://github.com/shadowsocks/shadowsocks-android/issues/1819#issuecomment-394132425

**Comment by huiyifyj** [comment]
Thanks.
@kalonelee 
it work it.
