### ISSUE TITLE
联想P780+Android 4.4.2无法使用

### ISSUE THREAD

**Issue by zhaibin18** [shadowsocks/shadowsocks-android#182]
启动后会建立很多链接，然后马上就报打开文件数过多了，
尝试了2.2.0-2.5.3的所有版本都不行。

H:\adb>adb logcat -s shadowsocks
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/shadowsocks(31032): initialize ciphers... rc4-md5
D/shadowsocks(31032): server listening at port 1080.
D/shadowsocks(31032): udprelay enabled.
E/shadowsocks(31032): socket: Too many open files
E/shadowsocks(31032): invalid remote addr.
E/shadowsocks(31032): server_recv_cb_send: Connection reset by peer
E/shadowsocks(31032): socket: Too many open files
E/shadowsocks(31032): invalid remote addr.
E/shadowsocks(31032): remote_recv_cb_recv: Connection reset by peer
E/shadowsocks(31032): server_recv_cb_send: Connection reset by peer
E/shadowsocks(31032): accept: Too many open files
E/shadowsocks(31032): accept: Too many open files
E/shadowsocks(31032): accept: Too many open files
E/shadowsocks(31032): socket: Too many open files
E/shadowsocks(31032): invalid remote addr.
E/shadowsocks(31032): remote_recv_cb_recv: Connection reset by peer
E/shadowsocks(31032): socket: Too many open files
E/shadowsocks(31032): invalid remote addr.
E/shadowsocks(31032): remote_recv_cb_recv: Connection reset by peer
E/shadowsocks(31032): accept: Too many open files
E/shadowsocks(31032): accept: Too many open files
E/shadowsocks(31032): socket: Too many open files

H:\adb>adb logcat -s tun2socks
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
D/tun2socks(31026): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.127
D/tun2socks(31026): NOTICE(tun2socks): entering event loop
D/tun2socks(31026): ERROR(BConnection): send failed
D/tun2socks(31026): ERROR(BConnection): send failed
D/tun2socks(31026): ERROR(BConnection): send failed
D/tun2socks(31026): ERROR(BConnection): recv failed

**Comment by bestoa** [comment]
碰见同样的问题，我已经把android里面的 ulimit -n 和 /proc/sys/fs/file-max 都设置为1024000了，依然同样错误还有什么方法debug吗？

**Comment by lixiuna0908** [comment]
我也遇到了同样的问题，是在红米1+Android4.4.2系统上，这个在VPN 客户端侧能否解决？
