### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by kkyflying** [shadowsocks/shadowsocks-android#1820]
### Environment
1. Android version: *8.0"
2. onoplus 6

### Configuration
ubuntu 16.04
android studio 3.1.2
go 1.7
ndk 17
(curl ip.cn  is a usa ip)

### What did you do?
./gradlew build 

### What did you expect to see?
Normal compilation and installation on the phone

### What did you see instead?
godep: error downloading dep (golang.org/x/net/proxy): unrecognized import path "golang.org/x/net/proxy"
godep: error downloading dep (golang.org/x/sys/unix): unrecognized import path "golang.org/x/sys/unix"
godep: Error downloading some deps. Aborting restore and check.

../core/outbound/client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
        /home/kky/professional/libs/shadowsocks-android/core/src/overture/go/src/golang.org/x/net/proxy (from $GOROOT)
        /home/kky/professional/libs/shadowsocks-android/core/src/overture/src/golang.org/x/net/proxy (from $GOPATH)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:goBuild'.
> Process 'command 'sh'' finished with non-zero exit value 255

My  internet is ok, in terminator can visit https://golang.org/

**Comment by kkyflying** [comment]
@yihongyuelan 
thank for you anwser , but , l have set a function in .zshrc
```
 function switch_proxy()
  {   
      if [ -z $all_proxy ]; then
          export all_proxy=socks5://127.0.0.1:1080
         curl ip.cn
     else
         unset all_proxy
        curl ip.cn
     fi
 }
```
Before I build . l will use this switch_proxy() ,check to socks5://127.0.0.1:1080,howerver , l build again is failed

**Comment by kkyflying** [comment]
@yihongyuelan 
thank for you anwser !!!
because l set all_proxy=socks5://localhost:1080 , is not http_proxy,but l try and find https_proxy is ok

**Comment by SuperBeagleDog** [comment]
> @yihongyuelan
> thank for you anwser !!!
> because l set all_proxy=socks5://localhost:1080 , is not http_proxy,but l try and find https_proxy is ok

**I did as you did, I set all_proxy too... ... So now How to reslove it, friend . I wasted half day on it, still can't find a way to solve.  Thank you**

**Comment by kkyflying** [comment]
if you use ubuntu 16.04 too,you can try
```
1. sudo apt-get install privoxy
2. sudo vim /etc/privoxy/config 
add    " forward-socks5t / 127.0.0.1:1080 .  "   in config  
```
l think ss can not proxy http and https ,so , l have to use  privoxy  to proxy ss , next , you should privoxy address for gradle
