### ISSUE TITLE
Error to start VPN service: 无法连接远程服务器: Cannot run program "/data/app/com.github.shadowsocks-2/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory

### ISSUE THREAD

**Issue by goodluckforme** [shadowsocks/shadowsocks-android#1822]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0.1
* Device: *VIVO*
* Shadowsocks version:  version code "v4.6.0" 
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

可以编译并运行 加入配置文件后连接出现如下问题：

Error to start VPN service: 无法连接远程服务器: Cannot run program "/data/app/com.github.shadowsocks-2/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory

堆栈：

package github.com/tools/godep
	imports github.com/kr/fs
	imports github.com/kr/pretty
	imports github.com/kr/text
	imports github.com/pmezard/go-difflib/difflib
	imports golang.org/x/tools/go/vcs: unrecognized import path "golang.org/x/tools/go/vcs"
godep: error downloading dep (golang.org/x/net/proxy): unrecognized import path "golang.org/x/net/proxy"
godep: error downloading dep (golang.org/x/sys/unix): unrecognized import path "golang.org/x/sys/unix"
godep: Error downloading some deps. Aborting restore and check.

"Cross compile overture for arm"

..\core\outbound\client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang.org\x\net\proxy (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang.org\x\net\proxy (from $GOPATH)
..\..\..\..\..\go\src\crypto\tls\cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\chacha20poly1305 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\chacha20poly1305 (from $GOPATH)
..\..\..\..\..\go\src\crypto\x509\x509.go:36:2: cannot find package "golang_org/x/crypto/cryptobyte" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte (from $GOPATH)
..\..\..\..\..\go\src\crypto\x509\x509.go:37:2: cannot find package "golang_org/x/crypto/cryptobyte/asn1" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOPATH)
..\..\..\..\..\go\src\crypto\tls\key_agreement.go:20:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\curve25519 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\curve25519 (from $GOPATH)
import cycle not allowed
package github.com/shadowsocks/overture/main
	imports bufio
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime/internal/sys
	imports runtime
D:\androidSpace\ShadowSocks\core\src\overture\\.deps\android-toolchain-21-arm\bin\arm-linux-androideabi-strip: 'main': No such file

"Cross compile overture for arm64"

2018/06/05 17:49:20 unsupported GOARCH arm64
D:\androidSpace\ShadowSocks\core\src\overture\\.deps\android-toolchain-21-arm64\bin\aarch64-linux-android-strip: 'main': No such file

"Cross compile overture for x86"

..\core\outbound\client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang.org\x\net\proxy (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang.org\x\net\proxy (from $GOPATH)
..\..\..\..\..\go\src\crypto\tls\cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\chacha20poly1305 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\chacha20poly1305 (from $GOPATH)
..\..\..\..\..\go\src\crypto\x509\x509.go:36:2: cannot find package "golang_org/x/crypto/cryptobyte" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte (from $GOPATH)
..\..\..\..\..\go\src\crypto\x509\x509.go:37:2: cannot find package "golang_org/x/crypto/cryptobyte/asn1" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOPATH)
..\..\..\..\..\go\src\crypto\tls\key_agreement.go:20:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
	D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\curve25519 (from $GOROOT)
	D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\curve25519 (from $GOPATH)
import cycle not allowed
package github.com/shadowsocks/overture/main
	imports bufio
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
D:\androidSpace\ShadowSocks\core\src\overture\\.deps\android-toolchain-21-x86\bin\i686-linux-android-strip: 'main': No such file

"Successfully build overture"

**Comment by Crafsman** [comment]
![wechatimg56](https://user-images.githubusercontent.com/15353430/45252302-6faf6780-b397-11e8-8d97-a5ddf89456ee.jpeg)
This is my problem, any ideas?

**Comment by h1138289016** [comment]
Have you soved this problem? I need youre help, Thank u.

**Comment by h1138289016** [comment]
#

> Please read FAQ then answer these questions before submitting your issue. Thanks!
> 
> ### Environment
> * Android version: 7.0.1
> * Device: _VIVO_
> * Shadowsocks version:  version code "v4.6.0"
> * Last version that did not exhibit the issue (if applicable):
> 
> ### Configuration
> _Put an `x` inside the [ ] that applies._
> 
> * [ ]  IPv4 server address
> * [ ]  IPv6 server address
> * [ ]  Client IPv4 availability
> * [ ]  Client IPv6 availability
> * Encrypt method:
> * Route
>   
>   * [ ]  All
>   * [ ]  Bypass LAN
>   * [ ]  Bypass China
>   * [ ]  Bypass LAN & China
>   * [ ]  GFW List
>   * [ ]  China List
>   * [ ]  Custom rules
> * [ ]  IPv6 route
> * [ ]  Apps VPN mode
>   
>   * [ ]  Bypass mode
> * Remote DNS: 8.8.8.8
> * [ ]  DNS Forwarding
> * Plugin configuration (if applicable):
> * [ ]  Auto Connect
> * [ ]  TCP Fast Open
> * If you're not using VPN mode, please supply more details here:
> 
> 可以编译并运行 加入配置文件后连接出现如下问题：
> 
> Error to start VPN service: 无法连接远程服务器: Cannot run program "/data/app/com.github.shadowsocks-2/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory
> 
> 堆栈：
> 
> package github.com/tools/godep
> imports github.com/kr/fs
> imports github.com/kr/pretty
> imports github.com/kr/text
> imports github.com/pmezard/go-difflib/difflib
> imports golang.org/x/tools/go/vcs: unrecognized import path "golang.org/x/tools/go/vcs"
> godep: error downloading dep (golang.org/x/net/proxy): unrecognized import path "golang.org/x/net/proxy"
> godep: error downloading dep (golang.org/x/sys/unix): unrecognized import path "golang.org/x/sys/unix"
> godep: Error downloading some deps. Aborting restore and check.
> 
> "Cross compile overture for arm"
> 
> ..\core\outbound\client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang.org\x\net\proxy (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang.org\x\net\proxy (from $GOPATH)
> ..........\go\src\crypto\tls\cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\chacha20poly1305 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\chacha20poly1305 (from $GOPATH)
> ..........\go\src\crypto\x509\x509.go:36:2: cannot find package "golang_org/x/crypto/cryptobyte" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte (from $GOPATH)
> ..........\go\src\crypto\x509\x509.go:37:2: cannot find package "golang_org/x/crypto/cryptobyte/asn1" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOPATH)
> ..........\go\src\crypto\tls\key_agreement.go:20:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\curve25519 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\curve25519 (from $GOPATH)
> import cycle not allowed
> package github.com/shadowsocks/overture/main
> imports bufio
> imports bytes
> imports errors
> imports runtime
> imports runtime/internal/atomic
> imports runtime/internal/sys
> imports runtime
> D:\androidSpace\ShadowSocks\core\src\overture\.deps\android-toolchain-21-arm\bin\arm-linux-androideabi-strip: 'main': No such file
> 
> "Cross compile overture for arm64"
> 
> 2018/06/05 17:49:20 unsupported GOARCH arm64
> D:\androidSpace\ShadowSocks\core\src\overture\.deps\android-toolchain-21-arm64\bin\aarch64-linux-android-strip: 'main': No such file
> 
> "Cross compile overture for x86"
> 
> ..\core\outbound\client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang.org\x\net\proxy (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang.org\x\net\proxy (from $GOPATH)
> ..........\go\src\crypto\tls\cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\chacha20poly1305 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\chacha20poly1305 (from $GOPATH)
> ..........\go\src\crypto\x509\x509.go:36:2: cannot find package "golang_org/x/crypto/cryptobyte" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte (from $GOPATH)
> ..........\go\src\crypto\x509\x509.go:37:2: cannot find package "golang_org/x/crypto/cryptobyte/asn1" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\cryptobyte\asn1 (from $GOPATH)
> ..........\go\src\crypto\tls\key_agreement.go:20:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
> D:\androidSpace\ShadowSocks\core\src\overture\go\src\golang_org\x\crypto\curve25519 (from $GOROOT)
> D:\androidSpace\ShadowSocks\core\src\overture\src\golang_org\x\crypto\curve25519 (from $GOPATH)
> import cycle not allowed
> package github.com/shadowsocks/overture/main
> imports bufio
> imports bytes
> imports errors
> imports runtime
> imports runtime/internal/atomic
> imports runtime
> D:\androidSpace\ShadowSocks\core\src\overture\.deps\android-toolchain-21-x86\bin\i686-linux-android-strip: 'main': No such file
> 
> "Successfully build overture"

Have you soved this problem? I need youre help, Thank u.

**Comment by h1138289016** [comment]
@goodluckforme Have you soved this problem? I need youre help, Thank u.
