### ISSUE TITLE
TCP Fast Open not work

### ISSUE THREAD

**Issue by Frogger01** [shadowsocks/shadowsocks-android#1825]
### Environment

* Android version: 8.1.0
* Device: Nokia 7 Plus
* Shadowsocks version: v4.6.0

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open

### What did you do?
我想尽量把情况阐述清楚，请原谅我使用中文。

手机系统默认启用TCP Fast Open，配置如下：
```
$ cat /proc/sys/net/ipv4/tcp_fastopen                                                                                        
1
```
同时在服务端(Debian9 | shadowsocks-libev 3.1.3)启用TCP Fast Open，配置如下：
```
~# cat /proc/sys/net/ipv4/tcp_fastopen
3

~# cat /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "server_port":8080,
    "local_port":1080,
    "password":"passwd",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true
}
```

### What did you expect to see?
正常使用

### What did you see instead?
当服务端启用TCP Fast Open，在连接WIFI的情况下客户端能够正常工作，但是在连接LTE移动网络的情况下客户端完全不工作或者只是工作一小段时间，检查服务端发现大量TCP握手错误，直到自动封锁我的IP地址。当服务端禁用TCP Fast Open `"fast_open":false`客户端在WIFI和LTE下均能正常工作。
为此我尝试过共享LTE网络给我的Linux PC使用，在使用相同配置的情况下ss-local也能够正常工作，服务端无错误日志，我不知道问题究竟出现在哪里...

我刚刚测试了不同的服务器，在两个不同地区的服务器上重现了此情况...我哪里做错了嘛？

```
ERROR: failed to handshake with My IP address: authentication error
ERROR: failed to handshake with My IP address: authentication error
ERROR: failed to handshake with My IP address: authentication error
ERROR: failed to handshake with My IP address: authentication error
ERROR: failed to handshake with My IP address: authentication error
...
ERROR: block all requests from My IP address
ERROR: block all requests from My IP address
ERROR: block all requests from My IP address
ERROR: block all requests from My IP address
ERROR: block all requests from My IP address
...
```

**Comment by madeye** [comment]
It's expected. https://github.com/shadowsocks/shadowsocks-libev/issues/1669

**Comment by Frogger01** [comment]
Thanks.
