### ISSUE TITLE
Shadowsocks stopped working after running in proxy mode for 1-2 days

### ISSUE THREAD

**Issue by AJIh** [shadowsocks/shadowsocks-android#1828]
### Environment

* Android version: MIUI 9.5 (Android 8.0)
* Device: Xiaomi MIX 2S
* Shadowsocks version: 4.5.7

### Configuration

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* Using `Proxy` mode

### What did you do?

I'm using Adguard in VPN mode and set Shadowsocks as its local proxy.  

### What did you expect to see?

I want to keep Shadowsocks running normally for a long time. 

### What did you see instead?

After a long time running(1-2 days), Shadowsocks usually stops working and I can not connect to any server in the GFW ban list. Servers not in GFW list are not affected(like baidu, zhihu, etc.).

I tried these methods to solve it:

* Clear Shadowsocks cache and restart it. (Not working)
* Remove all Shadowsocks' data and restart it. (Working, but I have to add my servers again after removing data)
* Reboot my device. (Working)

**Comment by madeye** [comment]
Check your battery settings for shadowsocks in MIUI. Make sure it's set as "no restrictions"

**Comment by AJIh** [comment]
I've confirmed that the battery settings is set as "no restrictions". In fact, I wouldn't be able to visit any websites (including GFW whitelist websites) if it's killed by the battery manager. Currently my net packages are firstly passed to Adguard (VPN mode) to determine whether to block it, then it's passed to Shadowsocks (Proxy mode) to determine whether to use my server to bypass GFW. I think it should be Shadowsocks' issue because it works normally after I wipe its data and restart it.

 

发件人: Max Lv <notifications@github.com>
答复: shadowsocks/shadowsocks-android <reply@reply.github.com>
日期: 2018年6月12日 星期二 17:42
收件人: shadowsocks/shadowsocks-android <shadowsocks-android@noreply.github.com>
抄送: Youfeng Hao <ajihyf@gmail.com>, Author <author@noreply.github.com>
主题: Re: [shadowsocks/shadowsocks-android] Shadowsocks stopped working after running in proxy mode for 1-2 days (#1828)

 

Check your battery settings for shadowsocks in MIUI. Make sure it's set as "no restrictions"

**Comment by DonClaud** [comment]
can u tell me what is the current domin of shadowsicks ? cuz i can not find it through search engine and the old links

**Comment by chaozhao** [comment]
I have this problem too, When I run app, the ss app runs one second then stoped. The notification shows data download and upload then it stoped. I try to reinstall app, it never happen.

**Comment by samuelthapa** [comment]
Any one found the solution for this issue as i am having same exact isuue, if anyone has solution pls, can you share here.
