### ISSUE TITLE
sendFD failed in Chromebook

### ISSUE THREAD

**Issue by lzchen1998** [shadowsocks/shadowsocks-android#1829]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1 in Chrome OS
* Device: Samsung Chromebook Plus
* Shadowsocks version: 4.5.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Tried reinstall the App.
Tested the connection of remote server by using other Android devices and the server worked well

### What did you expect to see?
Successful connection

### What did you see instead?
Connecting to remote server failed: sendFd failed

**Comment by madeye** [comment]
Shadowsocks-android is designed for Android, not for chrome OS.

Try https://github.com/shadowsocks/shadowsocks-chromeapp instead.

**Comment by Mygod** [comment]
`sendFd` failed means that your device doesn't implement VPN service properly. Try proxy only mode.

**Comment by lzchen1998** [comment]
Chromebook has support Android apps and the problem has solved after I updated the Chrome OS. Thanks for your answers.

**Comment by Mygod** [comment]
@madeye I just tested with [Chrome OS emulator](https://developer.android.com/topic/arc/emulator) and this app (including kcptun plugin) works flawlessly.
