### ISSUE TITLE
Timeout is too short for GCM

### ISSUE THREAD

**Issue by ZASXCDFVA** [shadowsocks/shadowsocks-android#1833]
ss-local cmdline "timeout"
600 seconds is too short for GCM.

**Comment by ZASXCDFVA** [comment]
But with mobile data, the GCM heartbeat may be longer.

**Comment by madeye** [comment]
Any source?

**Comment by ZASXCDFVA** [comment]
Timeout ,wake up and reconnect.
This may increase power consumption.
But ten minutes does not seem to be frequent.

I will close this issue.
Thank you for your reply.
