### ISSUE TITLE
shadowsocks 4.5.7 is not user friendly 

### ISSUE THREAD

**Issue by AshZh** [shadowsocks/shadowsocks-android#1837]
### Environment

* Android version:  "7.0.0"
* Device: *samsung s7 edge*
* Shadowsocks version: *version code "v4.5.7" 
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
i've selected the profile ,then i click the connect bottom,but it didn't work and the app notice me to choose a profile.

**Comment by Mygod** [comment]
How about "choose a profile, *please?*"

Try the latest release 4.6.0, *please?*

**Comment by AshZh** [comment]
I've downloaded the shadowsocks on the google store. and after I set the profile, I just click the profile to make the label to turn green, then I click plane icon to connect. but it just notice me to choose a profile.
The latest release 4.6.0 work well on my phone, thx.
