### ISSUE TITLE
android build issue

### ISSUE THREAD

**Issue by shiwuning** [shadowsocks/shadowsocks-android#1838]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* win7, Android studio3.1.3

### What did you do?
when i sync project in android studio, i got follow errors:

Build command failed.

Error while executing process D:\soft_green\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\work\ss\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\work\ss\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=D:/work/ss/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=D:\work\ss\core\build\intermediates\ndkBuild\release\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

md "D:\work\ss\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -ID:/work/ss/core/src/main/jni/libancillary -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/work/ss/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/work/ss/core/src/main/jni/jni-helper.cpp -o D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o

md "D:\work\ss\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem

md "D:\work\ss\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/work/ss/core/build/intermediates/process_begin: CreateProcess(NULL, "", ...) failed.

make: *** No rule to make target `D:/work/ss/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
ndkB

uild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a D:/work/ss/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

Build command failed.

Error while executing process D:\soft_green\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\work\ss\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\work\ss\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/work/ss/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\work\ss\core\build\intermediates\ndkBuild\debug\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

md "D:\work\ss\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] D:\work\ss\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"

copy /b/y "D:\soft_green\Android\sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "D:\work\ss\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "D:\work\ss\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86" > D:\work\ss\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot D:/work/ss/core/src/main/jni D:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/support D:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ D:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include D:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures D:/work/ss/core/src/main/jni/libancillary D:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include D:/work/ss/core/src/main/jni/mbedtls/include D:/work/ss/core/src/main/jni/pcre/dist D:/work/ss/core/src/main/jni/badvpn/lwip/src/include/ipv4 D:/work/ss/core/src/main/jni/badvpn/lwip/src/include/ipv6 D:/work/ss/core/src/main/jni/badvpn/lwip/custom" >> D:\work\ss\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup

md "D:\work\ss\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-heprocess_begin: CreateProcess(NULL, "", ...) failed.

make: *** No rule to make target `D:/work/ss/core/src/main/jni/libancillary/fd_recv.c', needed by `D:/work/ss/core/build/intermediates/ndkBuild/debulg/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.
per 

<= jni-helper.cpp"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -ID:/work/ss/core/src/main/jni/libancillary -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -ID:/work/ss/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/work/ss/core/src/main/jni/jni-helper.cpp -o D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o

md "D:\work\ss\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem

md "D:\work\ss\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -ID:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot -isystem D:/soft_green/Android/sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  D:/soft_green/Android/sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

D:/soft_green/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"

D:/soft_green/Android/sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a D:/work/ss/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

Folder D:\work\ss\mobile\build\generated\source\kaptKotlin\debug

Folder D:\work\ss\mobile\build\generated\source\kaptKotlin\release

3rd-party Gradle plug-ins may be the cause

**Comment by CyrusCeasar** [comment]
https://stackoverflow.com/questions/42739916/aarch64-linux-android-strip-file-missing    you may find the proper answer in this link.

**Comment by x2031** [comment]
我也遇到了这个问题但是不知道是链接中得 那个解决方案

**Comment by shiwuning** [comment]
非常感谢解答，我切换了一次代码版本之后，这个问题就自己好了，有点莫名其妙的。。。
