### ISSUE TITLE
Plugin: VPN starts before plugin establishes the connection with the server

### ISSUE THREAD

**Issue by liberal-boy** [shadowsocks/shadowsocks-android#1839]
### Environment

* Android version: 8.1.0
* Device: Redmi Note 3
* Shadowsocks version: v4.5.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I am developing a plugin to establish a connection with the server via websocket using [chisel](https://github.com/jpillora/chisel). It works well with "Proxy only" and "Transproxy" mode. And I had implemented and set callback with reference to [kcptun](https://github.com/shadowsocks/kcptun/blob/shadowsocks/client/main.go#L537), but when I test it with "VPN" mode, it does not work.

### What did you expect to see?
Chisel takes a few seconds to establish a connection with the server. VPN starts before the plugin establishes the connection. So the plugin cannot establish the connection, of course the callback was never called.

### What did you see instead?
VPN starts after the ancillary message received

**Comment by madeye** [comment]
It's expected.

You need to follow our examples to "protect" the socket in your plugin:

https://github.com/shadowsocks/simple-obfs/blob/master/src/android.c#L49

Then all the traffic from/to plugin would bypass Android VPN connection.

**Comment by madeye** [comment]
Another example for golang: 

https://github.com/shadowsocks/kcptun/blob/shadowsocks/client/main.go#L537
