### ISSUE TITLE
后台服务启动失败：无法连接远程服务器：Error running exec().Command:[/data/app/com.githu...

### ISSUE THREAD

**Issue by tangxu0717** [shadowsocks/shadowsocks-android#1840]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you see instead?
![shadowsocks_error](https://user-images.githubusercontent.com/8011122/41764946-2b177f4e-7635-11e8-89d6-61f3775e1468.png)

请问我拉取源码编绎扣的apk大小怎么比你们release的apk小很多，并且报“后台服务启动失败：无法连接远程服务器：”，如果用你们release的apk就没问题

**Comment by madeye** [comment]
Make sure you have followed all the steps listed in README.

**Comment by tangxu0717** [comment]
。。。I followed all the steps

**Comment by pexcn** [comment]
可能你是用 windows 编译的，而且没有安装 golang?

**Comment by tangxu0717** [comment]
是直接在windows下用android studio编译的，但是windows上装了golang，不行吗？

**Comment by tangxu0717** [comment]
是在windows下用android studio编译的，但是windows上装了golang，不行吗？

**Comment by pexcn** [comment]
对比一下本项目 release 的 apk, 就知道了，应该是缺少了某个 `.so`.
