### ISSUE TITLE
not work on samsung s9 stock rom

### ISSUE THREAD

**Issue by fayeharuna** [shadowsocks/shadowsocks-android#1841]
it will stop working on samsung s9 rom until restart telephone

**Comment by fayeharuna** [comment]
lineage or some aosp build rom is fine, only have this issue on stock rom

**Comment by madeye** [comment]
It's a know bug of Samsung,

Please refer to https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md for more detail.

**Comment by fayeharuna** [comment]
谢谢，目前使用全局代理加分应用发现没事了
