### ISSUE TITLE
java.io.IOException: Cannot run program "/data/app/com.github.shadowsocks-yaVdy9Fo4K_xpdHYs_U05Q==/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory

### ISSUE THREAD

**Issue by CyrusCeasar** [shadowsocks/shadowsocks-android#1843]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
 I build project successfuly , but  i got this error when i run application and connect VPN service .

06-27 14:51:20.352 8327-8486/com.github.shadowsocks:bg W/System.err: java.io.IOException: Cannot run program "/data/app/com.github.shadowsocks-yaVdy9Fo4K_xpdHYs_U05Q==/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory
06-27 14:51:20.353 8327-8486/com.github.shadowsocks:bg W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.github.shadowsocks.bg.GuardedProcessPool$Guard.looper(GuardedProcessPool.kt:71)
        at com.github.shadowsocks.bg.GuardedProcessPool$start$$inlined$synchronized$lambda$1.invoke(GuardedProcessPool.kt:114)
        at com.github.shadowsocks.bg.GuardedProcessPool$start$$inlined$synchronized$lambda$1.invoke(GuardedProcessPool.kt:37)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
    Caused by: java.io.IOException: error=2, No such file or directory
06-27 14:51:20.354 8327-8486/com.github.shadowsocks:bg W/System.err:     at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
06-27 14:51:20.355 8327-8486/com.github.shadowsocks:bg W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    	... 4 more

I have  no idea why  this happen and Google this problem  but only get a same question without answers  and closed.   Thanks for any  help !
### What did you expect to see?
Successfully  connect to My VPN server .

### What did you see instead?
 Error to start VPN service: 无法连接远程服务器: Cannot run program "/data/app/com.github.shadowsocks-yaVdy9Fo4K_xpdHYs_U05Q==/lib/arm64/liboverture.so" (in directory "/data/user_de/0/com.github.shadowsocks/files"): error=2, No such file or directory

**Comment by madeye** [comment]
Building on Windows is not officially supported.

**Comment by h1138289016** [comment]
@CyrusCeasar Have you soved this proble，I need your help, Thank u.
