### ISSUE TITLE
Call to setUnderlyingNetworks doesn't take effect

### ISSUE THREAD

**Issue by 7nights** [shadowsocks/shadowsocks-android#1844]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android P developer preview 3
* Device: Google Pixel & Google Pixel 2
* Shadowsocks version: 4.5.7 & 4.6.0

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Please see https://issuetracker.google.com/issues/110060022 for details.
Engineering team response in #6: 

> The code in Shadowsocks/master appears to be working correctly, but the official API/version bump renders the setUnderlyingNetwork code in Shadowsocks 4.6.0 inactive.

Just wondering if this code already landed in v4.5.7 & v4.6.0 ?

**Comment by Mygod** [comment]
I guess they're saying `BuildCompat.isAtLeastP` doesn't work for DP3 which is pretty ironical. This should already be fixed via https://github.com/shadowsocks/shadowsocks-android/commit/1d49b2ff591dca1f4a8806c2f1d2ce64b9a3c4da#diff-5de104e13c252a2e4c1876ebe9e409d1R232.

@madeye Next release?

**Comment by Mygod** [comment]
Please try 4.6.1.
