### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by CyrusCeasar** [shadowsocks/shadowsocks-android#1845]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
   I  change my build system to Ubuntu 18.04  , but now  I got  another problem in My build process . 

Build command failed.

Error while executing process /home/cyrus/Android/Sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/cyrus/project/shadowsocks-android/core/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/cyrus/project/shadowsocks-android/core/src/main/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/*

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdbserver

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdb.setup

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86

echo [x86] "Gdbserver      ": "[i686-linux-android] /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdbserver"

install -p /home/cyrus/Android/Sdk/ndk-bundle/prebuilt/android-x86/gdbserver/gdbserver /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdbserver

echo [x86] "Gdbsetup       ": "/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdb.setup"

echo "set solib-search-path /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86" > /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdb.setup

echo "directory /home/cyrus/Android/Sdk/ndk-bundle/sysroot /home/cyrus/project/shadowsocks-android/core/src/main/jni /home/cyrus/Android/Sdk/ndk-bundle/sources/android/support /home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++ /home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include /home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures /home/cyrus/project/shadowsocks-android/core/src/main/jni/libancillary /home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include /home/cyrus/project/shadowsocks-android/core/src/main/jni/mbedtls/include /home/cyrus/project/shadowsocks-android/core/src/main/jni/pcre/dist /home/cyrus/project/shadowsocks-android/core/src/main/jni/badvpn/lwip/src/include/ipv4 /home/cyrus/project/shadowsocks-android/core/src/main/jni/badvpn/lwip/src/include/ipv6 /home/cyrus/project/shadowsocks-android/core/src/main/jni/badvpn/lwip/custom" >> /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdb.setup

mkdir -p /home/cyrumakse: */** No rule to make target `/home/cyrpus/rojproject/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c', needed by `/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.

ect/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper

echo [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"

/home/cyrus/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain /home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -I/home/cyrus/project/shadowsocks-android/core/src/main/jni/libancillary -I/home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures -I/home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -I/home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -I/home/cyrus/project/shadowsocks-android/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot /home/cyrus/Android/Sdk/ndk-bundle/sysroot -isystem /home/cyrus/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /home/cyrus/project/shadowsocks-android/core/src/main/jni/jni-helper.cpp -o /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures

echo [x86] "Compile        ": "cpufeatures <= cpu-features.c"

/home/cyrus/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MP -MF /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain /home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -I/home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot /home/cyrus/Android/Sdk/ndk-bundle/sysroot -isystem /home/cyrus/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures/cpu-features.c -o /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

echo [x86] "StaticLibrary  ": "libcpufeatures.a"

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a

/home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-ar crsD  /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

Build command failed.

Error while executing process /home/cyrus/Android/Sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/cyrus/project/shadowsocks-android/core/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/cyrus/project/shadowsocks-android/core/src/main/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/*

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/gdbserver

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/gdb.setup

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper

echo [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"

/home/cyrus/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain /home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -I/home/cyrus/project/shadowsocks-android/core/src/main/jni/libancillary -I/home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures -I/home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -I/home/cyrus/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -I/home/cyrus/project/shadowsocks-android/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot /home/cyrus/Android/Sdk/ndk-bundle/sysroot -isystem /home/cyrus/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /home/cyrus/project/shadowsocks-android/core/src/main/jni/jni-helper.cpp -o /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86

mkdir -p /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures

echo [x86] "Compile        ": "cpufeatures <= cpu-featumake: *** No rule to make target `/home/cyrus/project/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c', needed by `/hromes.c"

/home/cyre/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.

us/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MP -MF /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain /home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -I/home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot /home/cyrus/Android/Sdk/ndk-bundle/sysroot -isystem /home/cyrus/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /home/cyrus/Android/Sdk/ndk-bundle/sources/android/cpufeatures/cpu-features.c -o /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

echo [x86] "StaticLibrary  ": "libcpufeatures.a"

rm -f /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a

/home/cyrus/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-ar crsD  /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a /home/cyrus/project/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

Folder /home/cyrus/project/shadowsocks-android/mobile/build/generated/source/kaptKotlin/debug

Folder /home/cyrus/project/shadowsocks-android/mobile/build/generated/source/kaptKotlin/release

3rd-party Gradle plug-ins may be the cause

I have no ideas  why  this happen  though I check whole process almost three times . 

This is part of  My  .bashrc file about environment variable .
 export JAVA_HOME=~/sdk/java/jdk1.8
  export  CLASSPATH=$CLASSPATH:$JAVA_HOME/lib
 export  PATH=$PATH:$JAVA_HOME/bin
export GOROOT=~/sdk/go/go1.10
 export PATH=$PATH:$GOROOT/bin
 export GOROOT_BOOTSTRAP=~/sdk/go/go1.10
 export ANDROID_HOME=~/Android/Sdk
 export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

This is My  java version 
cyrus@ubuntu:~$ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

This is My Go version 
cyrus@ubuntu:~$ go version
go version go1.10.3 linux/amd64

of course , I clone code as readme guide .
cyrus@ubuntu:~/project/shadowsocks-android$ git submodule update --init --recursive
cyrus@ubuntu:~/project/shadowsocks-android$ git submodule update --init --recursive
cyrus@ubuntu:~/project/shadowsocks-android$ 
as we can see , this is nothing to update for whole project .

Who has ideas for this problem ? Thanks  for Any help .

### What did you expect to see?
Build successfully !

### What did you see instead?
 Build failed .

**Comment by madeye** [comment]
There is no `/home/cyrpus/rojproject/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c`

Make sure you have cloned all files locally.

**Comment by YueminJi** [comment]
maybe you need change branch to `beta`

**Comment by CyrusCeasar** [comment]
@SnehilChouhan   yes, i  download all code as doc guide  and change my build environment  to Ubuntu

**Comment by SnehilChouhan** [comment]
@CyrusCeasar Thanks for your response, I am still not able to solve it.  
Q. By Doc guide you mean README.md?
Q. I am already using Ubuntu, would that be ok, or we need to do something to change build environment. 
I am also downloading all code

**Comment by CyrusCeasar** [comment]
@SnehilChouhan   Q. By Doc guide you mean README.md?  
 yes,pls follow the README.md steps
Q. I am already using Ubuntu, would that be ok, or we need to do something to change build environment.
 Ubuntu is ok , but some dependency library  you need to install before building your download code .

**Comment by SnehilChouhan** [comment]
@CyrusCeasar Thanks, I am already following doc, exactly as given.  
Q.  Which dependency library we need to install before building downloaded code?  Please let me know

**Comment by CyrusCeasar** [comment]
@SnehilChouhan   JDK 1.8
Go 1.11+
Android SDK
Android NDK r16+ 
those tools have you installed?    if you meet the same question as me ,  i suggest you delete code downloaded before and download those code again as doc guide .  This problem is made by file missing

**Comment by SnehilChouhan** [comment]
@CyrusCeasar Yes, I have all these tools installed.  And I did try downloading code again, I will try deleting and doing all setup form start .
The files that are missing are: for eg.(  core/.externalNativeBuild/ndkBuild/debug/armeabi-v7a) these folder are empty.  I think it can be the problem.
Because In my other NDK project, these folder have files and some code.

**Comment by CyrusCeasar** [comment]
@SnehilChouhan no ,All files in directory of .externalNativeBuild is result of building .  you'd better download all code recursive . pls be careful about you download command  .

**Comment by SnehilChouhan** [comment]
@CyrusCeasar ok, I was downloading zip directly, now doing clone in Android Studio directly

**Comment by CyrusCeasar** [comment]
@SnehilChouhan  you'd better do this in terminal ,create a dir and run this command (git clone --recurse-submodules https://github.com/shadowsocks/shadowsocks-android.git) in this dir.

**Comment by xiaoxiang626** [comment]
I also encountered this problem, what reason is this?
error code ：
Build command failed.
Error while executing process /Users/skyween/develop/soft/adt-bundle-mac-x86_64-20140702/sdk/ndk/20.0.5594570/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/skyween/develop/git/shadowsocks-android-master/core/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/skyween/develop/git/shadowsocks-android-master/core/src/main/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/skyween/develop/git/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/skyween/develop/git/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
