### ISSUE TITLE
client stuck during boot when no internet connection and server name needs resolution

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-android#1846]
### Environment

* Android version: 8.1.0 
* Device: Xiaomi MI 6 
* Shadowsocks version: 4.6.0
* Last version that did not exhibit the issue (if applicable): N/A

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
My phone doesn't enable data switch during boot, shadowsocks is stuck with the description below.
The server name is an address and has to be resolved first to use, since no data during boot, some logical lines may be missing.
Connectivity change, in this case, **DOESN'T** trigger a reconnection.
Correct behavior observed when app killed: data off and attempts to connect to a domain will prompt a snack bar "server name invalid".

### What did you expect to see?
Status: disconnected / connected and switching profiles and on/off available

### What did you see instead?
Status: Closing; not possible to tap on plane icon to toggle status, nor reset the app itself. The workaround is kill the app and restart it.

**Comment by madeye** [comment]
When data is off, `InetAddress.getByName()` should return and throw an exception immediately. If not, it'd be a bug of MIUI and Android itself.

To ensure the data connection is ready, you may try Tasker integration instead.

I also added a workaround to avoid the "connecting forever" problem you observed.
