### ISSUE TITLE
下载后使用Android studio 编译不了

### ISSUE THREAD

**Issue by huanyuan** [shadowsocks/shadowsocks-android#1848]
![qq 20180628155424](https://user-images.githubusercontent.com/12406954/42020821-9422a134-7aeb-11e8-904d-2f76831c1424.png)

看下面好像是ndk出错 怎么解决啊

Build command failed.
Error while executing process H:\Software\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\Demon\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=F:\Demon\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -IF:/Demon/shadowsocks-android-master/core/src/main/jni/libancillary -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IF:/Demon/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot H:/Software/Android/Sdk/ndk-bundle/build//../sysroot -isystem H:/Software/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  F:/Demon/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "process_begin: CreateProcess(NULL, "", ...) failed.

make: *** No rule to make target `F:/Demon/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.

cpufeatures <= cpu-features.c"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot H:/Software/Android/Sdk/ndk-bundle/build//../sysroot -isystem H:/Software/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  H:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

Build command failed.

Error while executing process H:\Software\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\Demon\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=F:\Demon\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"

copy /b/y "H:\Software\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86" > F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory H:/Software/Android/Sdk/ndk-bundle/build//../sysroot F:/Demon/shadowsocks-android-master/core/src/main/jni H:/Software/Android/Sdk/ndk-bundle/build//../sources/android/support H:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ H:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include H:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures F:/Demon/shadowsocks-android-master/core/src/main/jni/libancillary H:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include F:/Demon/shadowsocks-android-master/core/src/main/jni/mbedtls/include F:/Demon/shadowsocks-android-master/core/src/main/jni/pcre/dist F:/Demon/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv4 F:/Demon/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv6 F:/Demon/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custoprocess_begin: CreateProcess(NULL, "", ...) failed.

make: *** No rule to make target `F:/Demon/shadowsocks-android-master/core/src/main/jni/libancillary/fd_recv.c', needed by `F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.

m" >> F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -IF:/Demon/shadowsocks-android-master/core/src/main/jni/libancillary -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IF:/Demon/shadowsocks-android-master/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot H:/Software/Android/Sdk/ndk-bundle/build//../sysroot -isystem H:/Software/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  F:/Demon/shadowsocks-android-master/core/src/main/jni/jni-helper.cpp -o F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem

md "F:\Demon\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -IH:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot H:/Software/Android/Sdk/ndk-bundle/build//../sysroot -isystem H:/Software/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  H:/Software/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

H:/Software/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"

H:/Software/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a F:/Demon/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o

Folder F:\Demon\shadowsocks-android-master\mobile\build\generated\source\kaptKotlin\debug

Folder F:\Demon\shadowsocks-android-master\mobile\build\generated\source\kaptKotlin\release

3rd-party Gradle plug-ins may be the cause

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1787
https://github.com/shadowsocks/shadowsocks-android/issues/1608
https://github.com/shadowsocks/shadowsocks-android/issues/974
