### ISSUE TITLE
Add GCM/FCM ACL

### ISSUE THREAD

**Issue by dream-mind** [shadowsocks/shadowsocks-android#1850]
GCM/FCM is available in china ，Suggested to add a list  like “bypass GCM/FCM"
google 推送在国内可以正常使用，建议添加一个 类似绕过 GCM/FCM的选项

### What did you expect to see?
add acl file extends `bypass-china.acl` and `bypass-lan-china.acl`
添加一个新的acl文件，继承  `bypass-china.acl` 和 `bypass-lan-china.acl`

append this code
添加以下内容

```
(^|alt[0-9]{1}-)mtalk.google.com$
```

### What did you see instead?
GCM/FCM use native network，not ss server，Improve the use efficiency of GCM and battery performance
GCM/FCM  可以走本地网络，而不是ss服务器，提高GCM的使用率和电池性能

**Comment by madeye** [comment]
Use custom rules instead.

**Comment by YueminJi** [comment]
Custom rules cannot using acl

**Comment by madeye** [comment]
You can add any ACL into your custom rules, including IP range, regex and domain names.

**Comment by YueminJi** [comment]
I use an URL to my own ACL file,BUT I did not succeed
我用了自己域名的acl 文件地址，但是一直没有成功
http://docs.tongji.jwwblockchain.com/gcm.acl

maybe I need your help
或者您可以指导下

**Comment by madeye** [comment]
Bypass rules are not supported. Use GFW list base rules instead.

**Comment by YueminJi** [comment]
Maybe this project needs to add this feature.
User can write ACL rule in custom rules.

**Comment by Mygod** [comment]
Contributions are welcome.
