### ISSUE TITLE
Vivo NEX  prompt “failed to connect to www.google.com“

### ISSUE THREAD

**Issue by look0089** [shadowsocks/shadowsocks-android#1851]
### Environment

Android version: 8.1（Funtouch OS_4.0）
Device: vivo NEX S
Shadowsocks version: v4.6.0
Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
I use vivo NEX to connect to ss, but the prompt "failed to connect to www.google.com/31.13.75.18:443".
My other phone Redmi Note 4X SS is work。

### What did you expect to see?
SS is work in vivo NEX

### What did you see instead?
![img](https://github.com/look0089/scan/raw/master/jpg/IMG_20180703_093405.JPG "img")

**Comment by look0089** [comment]
OK..i reboot my phone，is work..

**Comment by chengqiang1992** [comment]
> OK..i reboot my phone，is work..

您好，我也出现了 failed to connect to www.google.com 这个问题。重启也没用有。
