### ISSUE TITLE
Hi , ins app cannot load feed 

### ISSUE THREAD

**Issue by zfk513** [shadowsocks/shadowsocks-android#1855]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "8.1", more detailed description is preferred*
* Device:Cool1dual
* Shadowsocks version: *version code "v4.6"
* Last version that did not exhibit the issue (if applicable):don't know ,sorry

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
HI,i can use google and others ,i can sign in to Ins via facebook
but ins cannot load feed

**Comment by madeye** [comment]
Try "Route All" first. If still not working, it means Instagram blocked your server's IP.
