### ISSUE TITLE
4.6.1 版新增的夜间模式有点小问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1856]
OS: LineageOS 14.1, 系统默认是日间模式

复现过程：
1. 打开默认是：`跟随系统`，界面风格是日间模式。
2. 切换到 `开启`，界面变为夜间模式，这时候再切换到 `跟随系统` 仍然显示成夜间模式。

**Comment by Sherlock-Holo** [comment]
pixel 2xl Android o 复现

Max yv <notifications@github.com> 于 2018年7月4日周三 17:09写道：

**Comment by Mygod** [comment]
@onlymash Thoughts?

**Comment by onlymash** [comment]
如果非要立即显现，就要先检测一下系统的主题状态，再决定开启还是关闭 app 的夜间主题，最后才设置为跟随系统

**Comment by onlymash** [comment]
由于系统版本众多，并不是所有系统都支持修改主题，不支持的系统就只能是日间模式。谷歌在设计 DayNight 主题的时候想必也考虑到了这一点，如果 app 主题是跟随系统，app 本身并不会去读书系统主题状态，因为每个系统都不一样，有的支持有的不支持，不好处理。所以是由系统告诉 App 主题改变了。还有一个选项是 Auto ，这个就简单了，这个选项是根据时间来设置的，所以修改后立即就生效了。

**Comment by Mygod** [comment]
I, on the other hand, think everything is just fine. 😅

**Comment by Mygod** [comment]
Opened an issue at support library: https://issuetracker.google.com/issues/111345020
