### ISSUE TITLE
请教下，如何查看自己手机是什么架构呢？

### ISSUE THREAD

**Issue by iseeyo** [shadowsocks/shadowsocks-android#1860]
现在Releases提供4种不同cpu架构的版本下载，我们怎么才能知道自己手机cpu是下面哪个架构呢universal、arm64-v8a、armeabi-v7a、x86。universal是通用版的意思吗？

**Comment by marlboro3420** [comment]
一般都是arm

**Comment by MoonBegonia** [comment]
下载个AIDA64，在中央处理器的指令集里自己看，是哪个就选哪个啰，不想看就下载通用的。
