### ISSUE TITLE
I need to download shadowsocks-android ,it's need google appstore , but to download google appstore , I need shadowsocks-android!

### ISSUE THREAD

**Issue by duotai** [shadowsocks/shadowsocks-android#1861]
I need to download shadowsocks-android ,it's need google appstore , but to download google appstore , I need shadowsocks-android !

how can I download shadowsocks-android from a no gfw env.

thank you

**Comment by PetitDevil** [comment]
Download lantern for free 500m, then you can download whatever you want.

On Jul 10, 2018, at 11:29 AM, 多态 <notifications@github.com<mailto:notifications@github.com>> wrote:


I need to download shadowsocks-android ,it's need google appstore , but to download google appstore , I need shadowsocks-android !

how can I download shadowsocks-android from a no gfw env.

thank you

**Comment by lixshnew** [comment]
https://github.com/shadowsocks/shadowsocks-android/releases
