### ISSUE TITLE
Could you provide APK for X86_64? 

### ISSUE THREAD

**Issue by lixshnew** [shadowsocks/shadowsocks-android#1862]
Thank you for providing such excellent app. I use v4.5.7, it works on my ARM based devices. I have a MIPAD2 which kernel is based on X86_64, it seems the APK libs only support X86.   I can see the GUI (java) after installation, but no functional  on data transfer(native libs).  
Could you provide one APK for X86_64 on v4.5.7 ? I  don't have the knowledge on app development...
Thanks a lot.

**Comment by madeye** [comment]
Try ARM apk instead.

**Comment by Mygod** [comment]
x86_64 Android devices support x86 just as x86_64 PCs do. Never assume your problem was caused by arch.

**Comment by lixshnew** [comment]
The ARM apk is not working . The error msg is 
"后台服务器启动失败：无法连接远程服务器：sendFd failed“.   
Any other idea about it? Thanks.

My MIPAD info:
kernel : 3.14.37-x86_64-g172c52b
MIUI : 9.6.1.0 
Android: 5.1 LMY471

**Comment by lixshnew** [comment]
@madeye @Mygod  You are right, the issue is not related to arch. I installed Outline instead. It works.
I believe there should be some slight differences of internal configuration which make it failed.
I hope you can fix it.  Shadowsocks-android seems much professional than Outline. :) 

Outline : 
http://shadowsocks.org/en/download/clients.html   (Android)

**Comment by Mygod** [comment]
When your issue is tagged "not following template", you should supplement all necessary information. Please open another issue.
