### ISSUE TITLE
 fatal error: 'ancillary.h' file not found

### ISSUE THREAD

**Issue by kigkrazy** [shadowsocks/shadowsocks-android#1864]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

JDK 8.0
GO 1.10.3 darwin/amd64
Platform-tools: r26.0.2-darwin
system: linux-manjaro
Build-tools: 28
Platforms: android-23, android-25, android-27 (tried all of them)
m2repository: v11_3_rc05_wear_2_0_5
NDK: 17.1

### What did you do?

```
cd core/src/main/jni
ndk-build
```
### What did you expect to see?
build success.
### What did you see instead?

```
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in /home/kigkrazy/work/projects/shadowsocks-android/core/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
[armeabi-v7a] Compile++ thumb: jni-helper <= jni-helper.cpp
/home/kigkrazy/work/projects/shadowsocks-android/core/src/main/jni/jni-helper.cpp:20:10: fatal error: 'ancillary.h' file not found
#include <ancillary.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [/home/kigkrazy/work/projects/shadowsocks-android/core/src/main/obj/local/armeabi-v7a/objs/jni-helper/jni-helper.o] Error 1
```

**Comment by madeye** [comment]
Make sure you've pulled all the sub modules.

**Comment by saeedhooshmand** [comment]
@kigkrazy did you fix this problem?
I have the same problem compiling shadowsocks badvpn

**Comment by mohsensaremi** [comment]
@kigkrazy same issue
@madeye can you tell me what should I do exactly?
I have to fix this problem as soon as posible
