### ISSUE TITLE
"后台服务器启动失败：无法连接远程服务器：sendFd failed“.

### ISSUE THREAD

**Issue by lixshnew** [shadowsocks/shadowsocks-android#1872]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *5.1 LMY471*
* Device: *XIAOMI MIPAD2*
* Shadowsocks version: *version code "v4.5.7" *
* Last version that did not exhibit the issue (if applicable): No

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
AES-256-GCM

* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):  No
* [ ] Auto Connect
* [x] TCP Fast Open  (by default, I cannot change because without rooted)
* If you're not using VPN mode, please supply more details here:

### What did you do?
Configurate  ip, port, password and encrypt method and connect.

### What did you expect to see?
socks proxy get working.

### What did you see instead?
"后台服务器启动失败：无法连接远程服务器：sendFd failed“.

**Comment by Mygod** [comment]
Use x86.

**Comment by lixshnew** [comment]
@madeye  any solution available? I can have a try if you have a test build. thanks.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1872#issuecomment-404526444

**Comment by qgtxqj** [comment]
这个问题似乎和导入分应用列表有关系，如果你导入了一个含有已删除应用的列表（比如你删除了U2B，但是原来的分应用列表里有它），可能会导致这个问题出现。请确认一下你是否也是这样导入列表的。@lixshnew
