### ISSUE TITLE
失败：Failed to connect to www.google.com/64.13.192.74:443

### ISSUE THREAD

**Issue by HaloWang** [shadowsocks/shadowsocks-android#1875]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *8.0.0*
* Device: *MIX 2S*
* Shadowsocks version: *4.5.0/4.6.0*
* MIUI version: *9.5.18.0*

### Configuration

所有配置均为 App 默认

### What did you do?

我使用熊猫翻滚的官方教程来配置 VPN 服务器

### What did you expect to see?

手机可以正常连接 VPN

### What did you see instead?

1. 一个星期前突然就开始无法连接服务器了，当时使用的是 Shadowsocks 4.5.0
2. 我更新至 4.6.0，且多次重装后，仍然无法解决问题
3. 每次失败过程如下：
打开 4.5.0/4.6.0 -> 点击右下角的飞机 -> `已连接，点击测试` -> `测试中`（经过大概30s的等待） -> `失败：Failed to connect to www.google.com/64.13.192.74:443` -> `无互联网连接` -> 打开 chrome -> google.com 无法连接
4. 我的 Mac/iPad 都可以使用对应的线路
5. 我已经问过熊猫翻滚的客服，他们叫我来这里提 issue

**Comment by HaloWang** [comment]
重启后正常了😅

**Comment by xuliugen** [comment]
同样的问题，小米Mix2s，重启收集后就ok了

**Comment by xuliugen** [comment]
@oxoxoxox Thanks！

**Comment by 838340139** [comment]
我的8se重启后也可以了

**Comment by 5920ooxx** [comment]
谢谢我也好了
