### ISSUE TITLE
When run task <core:goBuild>,build failed

### ISSUE THREAD

**Issue by JZXiang** [shadowsocks/shadowsocks-android#1876]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

OS:MAC OS ,
IDE:Android studio 3.0.1
go environment : go(branch-release-branch.go1.4)
shadowsocks-android/core/src/overture/go: go(branch-486515fc98)
NDK:17.1.4828580

When I run the goBuild task,build failed.
Is the go environment variable correct?

LOG
Error:# runtime/internal/sys
src/overture/go/src/runtime/internal/sys/zversion.go:5:23: DefaultGoroot redeclared in this block
	previous declaration at src/overture/go/src/runtime/internal/sys/stubs.go:13:5
# runtime/internal/sys
../../../../../go/src/runtime/internal/sys/zversion.go:5:23: DefaultGoroot redeclared in this block
	previous declaration at ../../../../../go/src/runtime/internal/sys/stubs.go:13:5
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:goBuild'.
> Process 'command 'sh'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s

**Comment by JZXiang** [comment]
![image](https://user-images.githubusercontent.com/15622668/42719715-160d9448-874d-11e8-97e5-99fffa6b395b.png)

**Comment by JZXiang** [comment]
go/src/runtime/internal/sys/stubs.go
````
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sys

// Declarations for runtime services implemented in C or assembly.

const PtrSize = 4 << (^uintptr(0) >> 63) // unsafe.Sizeof(uintptr(0)) but an ideal const
const RegSize = 4 << (^Uintreg(0) >> 63) // unsafe.Sizeof(uintreg(0)) but an ideal const
const SpAlign = 1*(1-GoarchArm64) + 16*GoarchArm64 `//` SP alignment: 1 normally, 16 for ARM64

var DefaultGoroot string // set at link time
```
`

**Comment by JZXiang** [comment]
go/src/runtime/internal/sys/zversion.go:5:23
```
// auto generated by go tool dist

package sys

const DefaultGoroot = /Users/jzxiang/code/shadowsocks-android/core/src/overture/go
const TheVersion = go1.9rc2
const Goexperiment = ``
const StackGuardMultiplier = 1
```

**Comment by madeye** [comment]
Update your local go to 1.9 and above.

**Comment by caocheng029** [comment]
the same issues,  and I'm go 1.10,  but

**Comment by JZXiang** [comment]
@madeye @caocheng029 Thanks.Now build successfully.I'm go 1.4.

**Comment by SuperBeagleDog** [comment]
> Update your local go to 1.9 and above.

I got the same issue, my go is 1.9+... ...but i set all_proxy once... I don't know whether it's affected it.
