### ISSUE TITLE
v4.6.1 crashed running on Alibaba Tmall TV Box 4S

### ISSUE THREAD

**Issue by ibus11** [shadowsocks/shadowsocks-android#1877]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.0 
* Device: Alibaba Tmall TV Box 4S 
* Shadowsocks version: universal-4.6.1
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ X] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Setup google ssl config, clicked the connection button on the bottom right.

### What did you expect to see?
Connected

### What did you see instead?
Crashed

**Comment by madeye** [comment]
Report it to Xiaomi instead.
