### ISSUE TITLE
Android's Global is fake global.

### ISSUE THREAD

**Issue by shindoge** [shadowsocks/shadowsocks-android#1879]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0 MPES24.49-18-7 
* Device: MOTOROLA XT1095
* Shadowsocks version: v4.6.0
* Last version that did not exhibit the issue (if applicable): v2.10.8

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:CHACHA20-IETF-POLY1305
* Route
  * [x] All
  * [ ] Bypass LAN (Tried)
  * [ ] Bypass China (Tried)
  * [ ] Bypass LAN & China (Tried)
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules (Tried)
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
Android's Global is fake global.
like inst's pic it's domain is not in pac's list. even you set global proxy it's not gonna do proxy.
and Play Store can open, but can't do update. mostly says it's bout the Download app is not in proxy.(But it's Global ???).
Concise a little bit: open the instagram app. the app frame can shows. no pic can be shows.
or open google play app. settings and frame and site can be shows. all the update will appending forever. 

### What did you expect to see?

expect the VPN mode or proxy can be used on any sites and apps.
if a Accurate config can't apply. Hope the Global setting can work for a while. But even a inst's pic(cdninstagram.com) can not be loaded. 
The same situation on Android Download apps. I know there's a Divide mode that doesn't change anything even you open or close or add all app in the list.
It's like the setting is fake. the proxy is locked on default mode like pac runs everything.

### What did you see instead?
sorry. not gonna work. not gonna work.
doing well on chrome app.

so it's not real Global set. cuz it's android we can't run another proxy Exes.
so there's a Divided application set we can choose all the apps and set bypass lan works etc... none of these gonna work.
BTW. All the same server doing well on PC.
it happens on regular version and Beta version include all version in 2018 releases.
and this situation last bout half years.
and It happened before I remember it since the version 3.0 PC's proxy is not working.

**Comment by madeye** [comment]
When you enabled "Apps VPN mode", it's definitely not a "global mode".

**Comment by madeye** [comment]
We cannot reproduce your issue locally.

Try the following things:

1. Disable IPv6 on your server.
2. Disable UDP forwarding on your server.

**Comment by shindoge** [comment]
ty I'll check

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android).
