### ISSUE TITLE
分应用代理不生效，所有应用流量都走了代理

### ISSUE THREAD

**Issue by catscarlet** [shadowsocks/shadowsocks-android#1880]
### Environment

* Android version: *Android 7.1.2", LineageOS 14.1
* Device: Mipad
* Shadowsocks version: v4.5.7

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

1. 安装了 Chrome 和 Firefox
2. Chrome 配置分应用代理开，Firefox配置分应用代理关
3. 未开启绕行模式
4. 开启代理
5. Chrome 访问国内查看本地地址的网站（如ipip.net）和国外查看本地地址的网站（如www.whatismyip.com）
6. 使用 Firefox 重复第5步

### What did you expect to see?
5. Chrome 访问国内查看本地地址的网站，显示本地地址；国外查看本地地址的网站，显示代理服务器地址
6. Firefox 访问国内查看本地地址的网站，显示本地地址；国外查看本地地址的网站，显示本地地址

### What did you see instead?
5. Chrome 访问国内查看本地地址的网站，显示本地地址；国外查看本地地址的网站，显示代理服务器地址
6. Firefox 访问国内查看本地地址的网站，显示本地地址；国外查看本地地址的网站，**显示代理服务器地址**

Firefox 并未加入到分应用代理，但是流量仍然被代理了。

**Comment by catscarlet** [comment]
尝试不勾选任何 APP ， 国外流量仍然走代理。
尝试绕行模式，只勾选 Firefox 和 Chrome，Firefox 和 Chrome 流量仍然走代理。

Chrome 流量节省程序 是关闭状态。

**Comment by madeye** [comment]
It's a typical issue of your ROM. Report it to LineageOS instead.

**Comment by catscarlet** [comment]
Checked on my new device and it's working. Consider it as a  issue of the ROM.

Recommend that add this situation to FAQs.
