### ISSUE TITLE
Connection lost after a period of idle time.

### ISSUE THREAD

**Issue by zzhhbyt1** [shadowsocks/shadowsocks-android#1885]
### Environment

* Android version: 7.1.2 LineageOS 14.1-20180701
* Device: Moto X 2014 / XT1095 / victara
* Shadowsocks version: v4.5.7

### Configuration

* [X] IPv4 server address
* [ ] IPv6 server address
* [X] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: CHACHA20-IETF-POLY1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [X] GFW List
  * [ ] China List
  * [ ] Custom rules
* [X] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [X] Auto Connect
* [ ] TCP Fast Open

### What did you do?

* Set Battery optimization to not optimize shadowsocks-android.
* Turn on Always-On VPN.
* Normally use the phone with shadowsocks connected.
* Maybe then lock the screen and put it away for a while and then continue to use.

### What did you expect to see?

* Connection is still good after resume using.

### What did you see instead?

* No app can connect to internet with either WiFi or cell-network, even apps bypassed in Per-App VPN mode, even bypass by GFWList.
* Shadowsocks' built-in connection test says: "shadowsocks android fail to detect internet connection: unable to resolve host"...
* Turn-off and then turn-on the proxy fix this for a while.

### Additional Info:

* Didn't installed Brevent and similar apps and will happen when installed Brevent, too. 
* LineageOS Privacy Guard is ON and remains default settings.
* Logcat attached. Any instruction about how to provide further information is welcomed.
* [logcat.txt](https://github.com/shadowsocks/shadowsocks-android/files/2201895/logcat.txt)

**Comment by madeye** [comment]
It means the background service is killed by your system.

Please report it to LineageOS instead.

**Comment by zzhhbyt1** [comment]
Thank you for your reply and effort to make such a helpful software.
I'll consult LineageOS team for further inspection about this problem and close this issue for now.
