### ISSUE TITLE
shadowsocks 4.6.1不支持android 5.1版本吗

### ISSUE THREAD

**Issue by qaz350623** [shadowsocks/shadowsocks-android#1887]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 5.1
* Device: vivo V3M A
* Shadowsocks version: shadowsocks 4.6.1
* Last version that did not exhibit the issue (if applicable):shadowsocks 4.6.0

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by benben233** [comment]
哥们，安卓9.0都要出了，该换啦

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/build.gradle#L8
