### ISSUE TITLE
What server should i setup for android client 2.6.8

### ISSUE THREAD

**Issue by max4444** [shadowsocks/shadowsocks-android#1888]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 4.3
* Device: Sony xperia
* Shadowsocks version: I need to know what version should i setup?
* Last version that did not exhibit the issue (if applicable): Not sure

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?

I've been using android client 2.6.8 since 2015 without any issues, i lost my shadowsocks server last night (due to a hard disk crash) and i cannot find a compatible server version to work with my client.

### What did you expect to see?
I tried a few different server versions but none of them worked with my android client. the problem is that i can't update my client.

**Comment by studentmain** [comment]
Maybe you just need use some old cipher.

max4444 <notifications@github.com> 于 2018年7月23日周一 00:26写道：

**Comment by max4444** [comment]
The client supports aes-256-cfb, so can i setup any server which supports this cipher or i need to try versions built in 2015?

**Comment by max4444** [comment]
@madeye 
@studentmain 

Thank you guys, got it working 👍
