### ISSUE TITLE
[功能请求] 通过 travis-ci crontab 自动更新规则列表

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#1891]
希望能通过 travis-ci 的 crontab 每日（或者每周）自动更新 ACL 列表 / GFWList 列表的数据。
这种日常更新的数据可以单独新建一个 repo 或者新建一条 branch 放置，而不是放到 [mobile/src/main/assets/acl](https://github.com/shadowsocks/shadowsocks-android/tree/master/mobile/src/main/assets/acl).

**Comment by pexcn** [comment]
Relational PR: https://github.com/shadowsocks/shadowsocks-android/pull/1890

**Comment by madeye** [comment]
Given we move on to circleci now, closing this.

**Comment by pexcn** [comment]
emmm... 我希望能够在每个 release 之前能更新一下~
