### ISSUE TITLE
Application occupies memory exception

### ISSUE THREAD

**Issue by 821938089** [shadowsocks/shadowsocks-android#1893]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *Android 7.0*
* Device: *HUAWEI honor 5c*
* Shadowsocks version: *4.5.7*
* Last version that did not exhibit the issue (if applicable):

The Screenshot:https://s1.ax1x.com/2018/07/27/PUFIUI.png

What is the role of the gms service?
It takes up too much memory on my device.

**Comment by ghuiii** [comment]
GMS is `Google Message Service` , it's a system service which provide message push ability. And all apps in your phone share the same process, you can ignore it.
