### ISSUE TITLE
android手机可以做代理并走ss吗？

### ISSUE THREAD

**Issue by stonyz** [shadowsocks/shadowsocks-android#1897]
1. android手机成功连上ss server, 并设置全局模式
2. 该手机科学上网是没有问题的
3. 如果我把该手机设置为热点， 其他手机连上
4. 但是其他手机不能科学上网。。

求解决方案； （排除在所有手机上装ss的方案）

**Comment by studentmain** [comment]
看看fqrouter能不能，如果不能，你可能得再买个路由器刷openwrt

Stony Zhang <notifications@github.com> 于 2018年8月1日周三 09:53写道：

**Comment by oxoxoxox** [comment]
如果手机已经root  可以借助这个app实现 https://play.google.com/store/apps/details?id=com.evozi.injector
如果没有root  那就没有任何办法

**Comment by pexcn** [comment]
这个？https://github.com/Mygod/VPNHotspot

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android).
