### ISSUE TITLE
启用DNS转发之后，手机无法上网，提示无法解析域名

### ISSUE THREAD

**Issue by yanggis** [shadowsocks/shadowsocks-android#1904]
Please read contributing guidelines. Thanks.

**Describe the bug**
安装SS的android版，Android 8.0, 默认情况下设置DNS转发为false的时候，后台可以看到所有DNS请求仍然经过SS服务器转发给8.8.8.8；但是当设置DNS转发为true的时候,手机全部都上不了网，提示无法解析DNS域名。SS Android 4.6.1版本。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: [8.0]
 - Device: [S7 Edge]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [V ] IPv4 server address
* [ ] IPv6 server address
* [V ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfb
* Route
  * [V ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [V ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [V ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [V ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Your server has to support UDP forwarding.

**Comment by yanggis** [comment]
补充一下，确认是DNS转发的问题，外部链接用IP可以直接访问，用域名解析不了。请开发者检查。

**Comment by madeye** [comment]
As mentioned above, double check you have UDP forwarding enabled on your server.

**Comment by yanggis** [comment]
I see now, thx.
