### ISSUE TITLE
Can't startup when set the Route Bypass LAN & China

### ISSUE THREAD

**Issue by cclover** [shadowsocks/shadowsocks-android#1910]
**Describe the bug**
Can't startup when set the Route Bypass LAN & China and other mode,  only startup when set to ALL or Custom rules.  Version 4.5.7

**To Reproduce**
1. Click start button
2. Show error:  "后台服务启动失败，无法连接远程服务器。You need to call create() at least once to create the si..."

**Expected behavior**
Can startup when set Route to Bypass LAN & China 

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: 8.0.0
 - Device: HTC  U Ultra
 - Version: 2.24.1405.2

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-CFB
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
Looks a third party issue. Please report it to HTC instead.

**Comment by Mygod** [comment]
Please try out the 4.6.1.

**Comment by cclover** [comment]
I had updated to 4.6.1 from 4.5.7.  It still show the error.   The i uninstall and install it again.  It works fine.

I thought it may caused by upgrade from old version.  I  had installed an old version about 3.x from local then update form google play.
