### ISSUE TITLE
In the app of phone ,how to set to the mode of PAC like the computer

### ISSUE THREAD

**Issue by wdw753951** [shadowsocks/shadowsocks-android#1911]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mygod** [comment]
Use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
