### ISSUE TITLE
No internet after turning DNS Forwarding on.

### ISSUE THREAD

**Issue by CHLLHC** [shadowsocks/shadowsocks-android#1914]
Please read contributing guidelines. Thanks.

**Describe the bug**
No internet after turning DNS Forwarding on. App said Internet Unavailable.

**To Reproduce**
1. Turn on the DNS Forwarding,
2. Tap connect

**Expected behavior**
I can browse anything.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: [8.1.0]
 - Device: [Oneplus 6]
 - Version: [4.5.7]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
XCHACHA20-IETF-POLY1305
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by CHLLHC** [comment]
duplicate? which one? @Mygod

**Comment by samm81** [comment]
wanted to leave a note for any other English speakers that stumble into this
I was having this problem and it was because I had not configured my server to accept udp connections
for me, the fix was to add this to the confic file (`/etc/shadowsocks/shadowsocks.json`):
```json
"mode": "tcp_and_udp"
```
