### ISSUE TITLE
Application killed by trashbin from recently apps

### ISSUE THREAD

**Issue by dva-re** [shadowsocks/shadowsocks-android#1920]
**Describe the bug**
The application is stops if you click on the trash bin in recently apps.

**To Reproduce**
1. Go to Recently Apps
2. Click on Trash Bin
3. Application stops

**Expected behavior**
Application must continue work.

**Smartphone (please complete the following information):**
 - Android version: EMUI 8.0.0 Android 8.0.0
 - Device: Huawei P20 Lite
 - Version: 4.5.7

**Configuration**
VPN Mode

**Additional context**
All battery optimizations are disabled (all that the system manages to control). 
Found somewhere (https://forum.xda-developers.com/showpost.php?p=71201384&postcount=4) the information that the system will not kill the application, if it will be a system application. It may be worth adding such a function to shadowsocks client for those who have a root? Or any other instructions how we may do it manually?

**Comment by Mygod** [comment]
Please use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
