### ISSUE TITLE
 app crash you need to call create() at least once to create

### ISSUE THREAD

**Issue by DR-YangLong** [shadowsocks/shadowsocks-android#1922]
open app,config options,click connect button.but can't connect to server.the same options on windows client  are working fine.
the tips:" you need to call create() at least once to create ..."
i think something is different between my os and others。

phone information:
brand: HTC U11 U3W
android version:8.0.0

the phone without Google service and google play but i installed with HTC's GMS app.
I confirmed through VPN the Google services can working well.

**Comment by Mygod** [comment]
This might be fixed in the next version.

**Comment by SnowOnion** [comment]
Maybe https://firebase.google.com/docs/test-lab/ helps testing?
If https://www.testin.cn is in the GFW, it's even better :) ;(

**Comment by lu-xu** [comment]
The same situation with you . My problem was solved after uninstall the old version, and install v4.6.1

**Comment by Mygod** [comment]
This should be fixed in 4.6.2.
