### ISSUE TITLE
instgrams image load so slow and custom rules is GFW List

### ISSUE THREAD

**Issue by fangasvsass** [shadowsocks/shadowsocks-android#1925]
* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

youtube and twiter google is ok

**Comment by madeye** [comment]
Double check you have added all Instagram URLs to your custom rules.

**Comment by Mygod** [comment]
Please post questions at the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
