### ISSUE TITLE
Please remove Google Play Service dependency (causes crash with old version of Google Play Service)

### ISSUE THREAD

**Issue by S-Tsunemori** [shadowsocks/shadowsocks-android#1926]
Recently I got an old phone (HTC, Android 6.0.1) which don't have GSM installed by default.

**First I installed Shadowsocks-android (with the apk provided on Github)**

It works fine. I got a notification nagging about Google Play Service but the app would start and I can use the proxy without any problem

**Then I installed GSM**

Using official install toolkit, after reboot I got GSM installed - which is a fairly old version. Now Shadowsocks-Android won't start. It just keeps crashing and crashing and I got a notification saying basically I must upgrade Google Play Service in order to use the app.

**So I'm stuck.**

1. I can't upgrade Google Play Service because I need a proxy to do so.
2. I can't use the proxy because Shadowsocks-Android isn't running.
3. I can't run Shadowsocks-Android because it requires me to upgrade Google Play Service.
4. I can't upgrade Google Play Service because I need a proxy to do so.
5. ......

See the problem here? If there's no Google Play Service, Shadowsocks-Android would run. If there's an old version of Google Play Service (could happen if someone factory resets their phone) Shadowsocks-Android would just flat-out crashes.

I had to manually find a updated version of Google Play Service from opengapps (which isn't really that easy for someone not familiar with it)

Please remove this dependency, as far as I can see it's only used for QR code scanning, what's wrong with installing another app to get the scanning ability? Or if you can fix the crash when there's an old version of Google Play Service, that would be ok too.

**Comment by studentmain** [comment]
My Mi 5X with Mi A1 ROM works well... Can you paste log here?

**Comment by Mygod** [comment]
> what's wrong with installing another app to get the scanning ability?

Search past issues for people whining about this approach.

Also FYI there's no "official" install toolkit (meaning from Google). Gapps is meant to be installed by vendors. If you take the risk to install an old unsupported gapps version, it's up to yourself to make this app work with your phone.

**Comment by S-Tsunemori** [comment]
@studentmain 

> My Mi 5X with Mi A1 ROM works well... Can you paste log here?

I believe you're not having this problem because you have a newer phone that comes with a later version of GMS pre-installed, I can't say for sure about the exact version number but it's likely something very old, something from 2015 judging by the install toolkit release date.

I can't provide any log because I don't have root, and I don't think I would get any because it just crashes before anything even starts, I see no interface flashes by, just a android system dialog saying it has stopped working. 

@Mygod 

> Search past issues for people whining about this approach.

I think it's better to have some people whining than have the app don't work for some people, right?

> Also FYI there's no "official" install toolkit (meaning from Google).

There is official install toolkit, at least for HTC phones afaik. The toolkit is developed by HTC, provided in HTC app store, and basically it download vendor GMS (which comes from Google) and install it using a backdoor without unlocking/rooting the phone. If that's an old version, nothing I can do about it.

>  it's up to yourself to make this app work with your phone.

Surely I can download an newer version of Google Play Service apk from some source like opengapps, or I can just install an old version of Shadowsocks that doesn't depend on Google Play Service. But it's very un-userfriendly to have an app crash just because the user has an old phone don't you think?

**Comment by ipcjs** [comment]
扫码功能依赖Google Play Service真的很坑("▔□▔)/

**Comment by gongzelong0718** [comment]
@S-Tsunemori 
Hi, which old version of Shadowsocks you are using is not needing the newer version of Google Service?

Hi, I encountered the same issue. I agree with you removing the dependency

But I came up with a workaround.
I guess QR code scanning needs the newer version of Google Service.
So I tried to manually set the shadowsocks and it works.
After we can use shadowsocks, we can update the Google Service.

Shadowsocks-Android: v4.6.1 (latest for now)
Nexus 6P/Androd 8.1.0 (reset to factory setting)
Google Play service version: 11.5.80


```
admindeMacBook-Pro-3:~ gongzelong$ adb shell
angler:/ $ pm dump com.google.android.gms|grep version
          6838926 com.google.android.gms/.ads.measurement.GmpConversionTrackingBrokerService filter 79ce6a
      versionCode=11580448 minSdk=23 targetSdk=23
      versionName=11.5.80 (448-175107017)
```

By the way, which old version of Shadowsocks are you using?

**Comment by XiangShao333** [comment]
都是中国人，何必用英文啊o(╥﹏╥)o，因为也就中国需要这个软件，连香港都不需要

**Comment by FirstLoveLife** [comment]
Maybe North Korean also need shadowsocks.
> 都是中国人，何必用英文啊o(╥﹏╥)o，因为也就中国需要这个软件，连香港都不需要


I would argue that not every Chinese like Hanzi.

**Comment by XiangShao333** [comment]
> Maybe North Korean also need shadowsocks.
> 
> > 都是中国人，何必用英文啊o(╥﹏╥)o，因为也就中国需要这个软件，连香港都不需要
> 
> I would argue that not every Chinese like Hanzi.

还用古老的繁体字，原来你不是大陆的，难怪你这么说

**Comment by FirstLoveLife** [comment]
> 原来你不是大陆的
Nope. https://segmentfault.com/q/1010000014442622?_ea=3639859
