### ISSUE TITLE
Huawei Mate7 install shadowsocks 4.6.X crash on app startup.

### ISSUE THREAD

**Issue by takeseem** [shadowsocks/shadowsocks-android#1928]
Please help me, Tanks.

**Describe the bug**
phone: Huawei Mate7
os: EMUI 3.1
cpu: Hisilicon Kirin 925
Android OS: 5.1.1

1. since upgrade to 4.6.x, crash on app startup. (try install shadowsocks--universal-4.6.1.apk same crash)
2. install 4.5.7, it is run ok.

**Comment by Mygod** [comment]
Logcat.
