### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by PsjJourney** [shadowsocks/shadowsocks-android#1929]
> Task :core:goBuild FAILED
Task ':core:goBuild' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'sh''. Working directory: /Users/sjp/Development/Android/Github/shadowsocks-android/core Command: sh -c src/overture/make.bash 21
Successfully started process 'command 'sh''
Make standalone toolchain for ARM arch
src/overture/make.bash: line 31: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Make standalone toolchain for ARM64 arch
src/overture/make.bash: line 37: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Make standalone toolchain for X86 arch
src/overture/make.bash: line 43: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
~/Development/Android/Github/shadowsocks-android/core/src/overture/src/github.com/shadowsocks/overture/main ~/Development/Android/Github/shadowsocks-android/core
Get dependences for overture
Cross compile overture for arm
# runtime/cgo
fork/exec /Users/sjp/Development/Android/Github/shadowsocks-android/core/src/overture/.deps/android-toolchain-21-arm/bin/arm-linux-androideabi-clang: no such file or directory
:core:goBuild (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.458 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:goBuild'.
> Process 'command 'sh'' finished with non-zero exit value 255

**Comment by PsjJourney** [comment]
I have this file of make_standalone_toolchain.py

**Comment by sugood** [comment]
我也遇到这个问题，能说下是怎么解决的吗？谢谢！

**Comment by PsjJourney** [comment]
环境变量的问题，注意你的NDK_HOME的路径

**Comment by sugood** [comment]
我最新的配置是怎样的。原来NDK_HOME 是安卓默认的路径。反正两个路劲都有这个问题
export ANDROID_NDK_HOME=/Users/sugood/Programs/android-ndk-r17-beta2
export PATH=$PATH:$ANDROID_NDK_HOME

帮忙看看这个配置是不是有什么问题~谢谢

**Comment by sugood** [comment]
我的开发环境
mac 10.13.6
android 3.1.4
java 1.8.0_161
go 1.11

环境变量
xport ANDROID_HOME=/Users/sugood/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

export ANDROID_NDK_HOME=/Users/sugood/Programs/android-ndk-r17-beta2
export PATH=$PATH:$ANDROID_NDK_HOME

**Comment by PsjJourney** [comment]
/ndk-bundle/build/tools/make_standalone_toolchain.py，这个路径不对，log上列出来的，所以你的环境配置有问题

**Comment by PsjJourney** [comment]
src/overture/make.bash: line 31，去这个对应文件里看看吧

**Comment by sugood** [comment]
奇怪了！不管我路劲怎么修改，都还是有这个报错。android-ndk-r17-beta2我确保下面是有build/tools/make_standalone_toolchain.py这个文件的

**Comment by sugood** [comment]
大兄弟~谢谢你，果然是环境变量的问题。我在make.bash把环境变量的路径打印出来，再修改环境变量再试最后终于可以了。也怪自己不熟悉mac环境变量的配置。总之一句话，太感谢你了~
