### ISSUE TITLE
可以成功“generate signed apk”，但是点击运行project，报错“Cause: java.lang.NullPointerException”。找了很久没找到原因。

### ISSUE THREAD

**Issue by Vector-SMG** [shadowsocks/shadowsocks-android#1930]
可以成功“generate signed apk”，但是点击运行project，报错“Cause: java.lang.NullPointerException”。找了很久没找到原因。

**Comment by Mygod** [comment]
Please post questions at the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
