### ISSUE TITLE
Android P 系统下在4G网络下ss耗电耗出新高度

### ISSUE THREAD

**Issue by GuJay** [shadowsocks/shadowsocks-android#1931]
一次用电下来，ss耗电会在60%以上，电池信息里面可以看到ss一直在运行。记得在8.1系统的时候，无论是前台运行时间还是后台运行时间，ss都是0min的，请问这算是ss在Android P下的bug吗？

**Comment by Mygod** [comment]
Please post questions at the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
