### ISSUE TITLE
Question about custom list

### ISSUE THREAD

**Issue by yanggis** [shadowsocks/shadowsocks-android#1933]
Just wanna check with you great guys:
does ss-android support filter a domain with different paths?
For example, I have two links, namely:
1. http://www.6park.com/news/12345.cn.html
2. http://www.6park.com/img/12x45.cn.gif
If I set a rule:      www\\.6park\\.com$ 
both links will pass through the proxy. 
Can I consider the path, create a rule, just like  www\\.6park\\.com\\/news$        to just allow the first link to pass through the proxy?

**Comment by Mygod** [comment]
Please post questions at the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.
