### ISSUE TITLE
Feature request: Password protection for configuration page

### ISSUE THREAD

**Issue by huguzahis** [shadowsocks/shadowsocks-android#1936]
**Is your feature request related to a problem? Please describe.**
I installed a shadow socks server on my VPS for my private use. Now, I want to install shadow socks on my mom tablet and add my server configuration there. But I don't want another one that has access to my mom tablet copy my server configuration.
 
**Describe the solution you'd like**
`Simple solution:` When accessing configuration page (or at least share actions) client ask a password, if user enabled the password protection feature. 

`Some more advanced features:` If password protection feature is enabled, client should encrypt its configuration using AES256 and there should be an auto-lock mechanism. 

**Additional context**
As my mom's tablet is using kit kat so I need that this feature also be available on those old device.

**Comment by madeye** [comment]
No plan for this. Try any AppLock apps to lock shadowsocks.

The configuration is encrypted by default on latest Android file system.

**Comment by Mygod** [comment]
I agree. Your profile information is stored securely given that:

* You have enabled device encryption;
* You have set up a strong passphrase for your lock-screen and it is active.

This app does not protect profile information from the device owner.
