### ISSUE TITLE
安卓5.0下面耗电过大

### ISSUE THREAD

**Issue by xuan880** [shadowsocks/shadowsocks-android#195]
手机升级到了5.0之后影梭的耗电量就变得特别大，不管用是是nat模式还是vpn模式，耗电显示上面永远都是第一，比屏幕还高，希望解决或说明原因。

**Comment by qiansen1386** [comment]
@madeye  Hi bro, the source you referenced is no longer accessible, do you still remember the original reply?

**Comment by zxq1002** [comment]
上面链接无法打开了，谁能再发一下吗？
