### ISSUE TITLE
Connection error due to Certificate Issues after upgraded MIUI ROM

### ISSUE THREAD

**Issue by samuelchen** [shadowsocks/shadowsocks-android#1955]
**Describe the bug**

After upgraded **MIUI to 9.6.10**, my SS Android can not work. **But the desktop SS client worked well** (I mean server works)

version: [**shadowsocks-arm64-v8a-4.6.1.apk**](https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.6.1/shadowsocks-arm64-v8a-4.6.1.apk) (installed today)

When click "test connection" button, it shows (similar messages):

* peer reset connect

* www.google.com can not resolve.

* google cert error

  ![](https://github.com/samuelchen/temp/blob/master/ss/1.jpg?raw=true)

Even I set to "global" or "transparent proxy" what ever, no options can make it works.

If I visit "google.com" or "twitter.com" in browser, it can not connect or show error message from "facebook" … 

![](https://github.com/samuelchen/temp/blob/master/ss/4.png?raw=true)

Or, it shows certificates not mached.

![](https://github.com/samuelchen/temp/blob/master/ss/2.png?raw=true)

![](https://github.com/samuelchen/temp/blob/master/ss/3.png?raw=true)

**To Reproduce**
1. Open SS Android
2. Connect
3. Click "test connection" or open browser to visit "twiiter.com"
4. Try change options and again.

**Expected behavior**
Connect "twitter.com" or "google.com"

**Screenshots**
As in description.

**Smartphone (please complete the following information):**
 - Android version: 7.1.1
 - Patch: 2018-05-01
 - Device: Mi Note 3
 - Version: 4.6.1
 - Last version that did not exhibit the issue: < 4.5.7

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: RC4-MD5 / AES-256-CFB
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:
Neither "VPN" or "Transparent Proxy" works.

**Additional context**

**Comment by lelelemonade** [comment]
yes,same here.but sometimes it work,i do not know what is the key.

**Comment by iBug** [comment]
Recommend close. This is a known issue that under certain Chinese network the SSL certificates get replaced randomly (there was a large wave of this SSL MITM attack) and it's not related/specific to SS-Android.

**Comment by samuelchen** [comment]
Thanks for replies. Is there any solution to solve this issue ? @iBug

**Comment by iBug** [comment]
@samuelchen Unfortunately I don't have any effective solution, because this is primarily a network issue and is unrelated to your hardware/software, etc.

**Comment by samuelchen** [comment]
Thanks @iBug . I guess I maybe have to try re-image my device :(

**Comment by Mygod** [comment]
Try using route = all and per-app VPN = off. If this still occurs, there might be something fishy going on in your SW/HW.

**Comment by samuelchen** [comment]
@Mygod thanks

**Comment by samuelchen** [comment]
still can not work ... close it as it may be device/system/china network issues
