### ISSUE TITLE
新版本（4.6.1）的用不了 kcptun插件

### ISSUE THREAD

**Issue by foxundermoon** [shadowsocks/shadowsocks-android#1957]
我之前的是s8  kcptun用的是`0.0.2`版本    shadowsocks-android 忘记了是什么版本了  可以正常使用。
后面买了 note9  正常装好`kcptun` 0.1 版本 ,   shadowsocks-android   4.6.1   然后通过扫描二维码的方式同步了配置过去，发现只要有kcp插件的配置都连不上 。
然后我回去试了一下旧手机  发现依然可以正常使用。
然后我特意记了一下旧手机的版本，后面发现只记住了kcptun的版本  ，太健忘 shadowsocks-android 版本忘记了。朱版本是4  次版本貌似是2.

然后我把旧手机也安装了新版本 发现旧手机也连不上带插件的了。 然后就开始各种回退 kcp版本  shadowsocks-android  版本，发现最后两台手机都连不上带插件的了 。  
  有人能正常使用   `kcptun 0.1`  + ` shadowsocks-android   4.6.1 `  吗   或者告诉我一个能用的版本组合。

**Comment by foxundermoon** [comment]
回退到了  3.1.0  内置kcp 可以连上，还是内置的比较好使😄

**Comment by foxundermoon** [comment]
3.1.0在s8  安卓8.0上正常使用，但是在note9   android 8.1上无法使用。

**Comment by catdog** [comment]
遇到同样的问题

**Comment by veigrent** [comment]
开启kcptun插件之后关掉dns转发试试。

**Comment by guojindai** [comment]
需要单独安装 kcptun 的 apk
https://github.com/shadowsocks/shadowsocks-android/tree/master/plugin

**Comment by foxundermoon** [comment]
最新版本  开启dns转发 然后就可以使用
