### ISSUE TITLE
application icon for TV version not showing up

### ISSUE THREAD

**Issue by yanggis** [shadowsocks/shadowsocks-android#1961]
Please read contributing guidelines. Thanks.

**Describe the bug**
I just downloaded the latest version and compiled for TV version. After installation on my tvbox, no application icon appeared on the desktop; I thus could not launch the app. Please check and fix it.
Thanks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: [e.g. "7.0.0_r14", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
Which TV?

**Comment by yanggis** [comment]
Hi Mygod.  I didn't say this this app is working or not for a Chinese TV box. Even it is not working for a Chinese TV box, at least It should have an app icon, right?

**Comment by Mygod** [comment]
> I didn't say this this app is working or not for a Chinese TV box.

And I suppose we haven't asked you the model? How can we make it more obvious to you that you should fill in the template?
