### ISSUE TITLE
View, Edit, and Default existing routes, maybe logs

### ISSUE THREAD

**Issue by addohm** [shadowsocks/shadowsocks-android#1962]
I apologize in advance if the formatting of this issue does not match the requirements.  Currently the FAQ is blank and I'm forced to write this from my phone.

Android version 8.0.0 on a Galaxy S9+ in Shanghai. 

Currently the all the routes work well for me but only one works for the Google play store. The same one that works for the Google play store is blocking Google itself. So to update I'm goi g to have to flip back and fourth between route lists.  I wonder why there is a need for several GFW lists.  I'd like to be able to view, modify, and/or merge the lists. 

This may also be a good lead into the need for log viewing as well.  Because I have no idea which rules are actually allowing Google play through, and haven't been able to find a resource that tells me.

**Comment by Mygod** [comment]
> I apologize in advance if the formatting of this issue does not match the requirements. Currently the FAQ is blank and I'm forced to write this from my phone.

I don't see how this is our fault.
