### ISSUE TITLE
Apps VPN mode is not functional on Android Pie.

### ISSUE THREAD

**Issue by Roller44** [shadowsocks/shadowsocks-android#1963]
**Describe the bug**
It seems like the Apps VPN mode is not functional on Android Pie. For example, even if I select the Wechat and then turn on the bypass mode, the WeChat still need to go through the VPN when it loads figures.

**To Reproduce**
1. Go to 'Profile config' -> 'Apps VPN mode' -> turn on 'On' -> turn on 'Bypass Mode' -> select 'WeChat'
2. Click on 'back'
3. Click links or figures on Wechat.
4. Present web pages or figures slow and the notification bar of Shadowsocks indicates that there are some download link traffics via VPN.

**Expected behavior**
Present web pages or figures fast and the notification bar of Shadowsocks indicates that there is no download link traffic via VPN at all.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: 9
 - Device: Oneplus 2 (ONE A2001).
 - Version: Lineage0S 16.0-20180907-UNOFFICIAL-oneplus2

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [x ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
No.

Thank you for reading this.

**Comment by madeye** [comment]
Report it to your ROM developer. It should be a third-party problem.

**Comment by shun1249844726** [comment]
pixel xl   android 9 .

Failed to connect the remote server:Failed to connect to socks123.azureedge.net/31.13.83.16:443

**Comment by madeye** [comment]
@shun1249844726 Setup your own server.

**Comment by Roller44** [comment]
> Report it to your ROM developer. It should be a third-party problem.

It seems like that. I switch to another ROM and the problem is gone. Thanks!
