### ISSUE TITLE
Could we bring back using external barcode scanner application for adding connections?

### ISSUE THREAD

**Issue by KenOokamiHoro** [shadowsocks/shadowsocks-android#1970]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
When Google Play Service is not available (such as the device doesn't have it) or it is configured incorrectly (such as microG users as me), it will prompt user "Google Play Services Error" simplely when they are trying to add connections via scanning barcodes.

**Describe the solution you'd like**
Provide an option of using external barcode scanning applicaton or using that automaticlly when they are detected.

**Additional context**
In my memories, previous version of shadowsocks-android is using an external barcode scanner (typically Zxing's one) and it dosen't require Google Play Services to work. Is there some reason of using a integrated scanner instead?

**Comment by madeye** [comment]
You can still use an external barcode scanner. It's always supported.
