### ISSUE TITLE
"googleapis.cn"有时无法走代理 / googleapis.cn sometimes won't go through the proxy

### ISSUE THREAD

**Issue by Villivateur** [shadowsocks/shadowsocks-android#1974]
Please read contributing guidelines. Thanks.

**Describe the bug**
由于我的Google框架使用的是"googleapis.cn"这一域名，直接解析是指向北京的一台无效的服务器上。使用本客户端后，有的时候会使用远端DNS将"googleapis.cn"解析到洛杉矶的服务器上（有效服务器），有的时候则不会使用远端服务器解析，导致改域名无法正确解析，进而无法使用Google Play。
但实际上，GFW list里已经包含"googleapis.cn"。
同时，若开启“DNS转发”，会好一点，但仍然会有一定几率无法正确解析"googleapis.cn"。

My Google Framework use googleapis.cn as its default API domain, which cannot be modified. And in mainland China it will be resolved to a invalid server in Beijing. When using this Android client, googleapis.cn will sometimes be resolved to the valid server in Los Angeles by remote DNS. However, sometime it will still not use remote DNS and resolve googleapis.cn to the invalid server, which will cause Google Play to work improperly.
However, the GFW list has already include the domain.
Moreover, if I open DNS forwarding, the resolving will be better. But gooleapis.cn will still not be resolved correctly from time to time.

**Smartphone (please complete the following information):**
 - Android version: 9
 - Device: Xiaomi MIX 2S
 - Version: latest

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-256-cfg
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1.1.1.1
* [sometimes checked] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by madeye** [comment]
It's probably a DNS cache poisoning issue.

When it happens, try switching on / off airplane mode to flash the DNS cache.

**Comment by Villivateur** [comment]
@madeye Thank you.
But what confuses me is that, googleapis.cn has already been in the GFW list. So when I use shadowsocks-android, googleapis.cn should be resolved by remote DNS, which is away from DNS cache poisoning.
It is just strange for me.

**Comment by madeye** [comment]
The DNS cache would be poisoned before turning on shadowsocks.

**Comment by Mygod** [comment]
```
> server 1.1.1.1
Default server: 1.1.1.1
Address: 1.1.1.1#53
> services.googleapis.cn
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	services.googleapis.cn
Address: 216.58.207.67
Name:	services.googleapis.cn
Address: 2a00:1450:4001:825::2003
> googleapis.cn
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
*** Can't find googleapis.cn: No answer
```

I don't think there is such domain.

**Comment by Villivateur** [comment]
@madeye Thank you. I will try your suggestion the next time the bug occurs.
@Mygod Sorry. But I mean that, googleapis.cn has multiple subdomains such as services.googleapis.cn. I use the top-level domain to cover all of them.

**Comment by Mygod** [comment]
What exact version are you using? Also please make sure your VPS resolves *.googleapis.cn correctly.

**Comment by jiangfengming** [comment]
@madeye switching on / off airplane mode worked for me, thank you!
