### ISSUE TITLE
启动后台服务失败：请选择配置文件

### ISSUE THREAD

**Issue by huangtiangang** [shadowsocks/shadowsocks-android#1975]
Please read contributing guidelines. Thanks.

**Describe the bug**

**To Reproduce**
1. 配置好服务器后
2. 选择配置文件
3. 点击连接，出现错误

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: 7.0
 - Device: M1 E
 - Version: v4.6.1
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by AI0TSec** [comment]
![image](https://user-images.githubusercontent.com/48520137/61581854-6ca80a80-ab56-11e9-8922-553220197b6c.png)

How can I solve this problem?THANKS
HUAWEI  麦芒8
