### ISSUE TITLE
Disconnected after running well for a while 

### ISSUE THREAD

**Issue by BH1ENO** [shadowsocks/shadowsocks-android#1981]
**Describe the bug**
Disconnected after running well for a while, and cannot connect again.

**Screenshots**
This is the message when trying to re-connect.
![image](https://user-images.githubusercontent.com/17289895/47443164-5ac35200-d7e6-11e8-8333-7f13caa3f55c.png)

Background service failed to start: cannot connect to remote server. command 1852(this number changes every time) interface fwmark .....

**Smartphone (please complete the following information):**
 - Android version: 4.4.2
 - Device: Android Set-Top-Box

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability

* Encrypt method:
"chacha20-ietf-poly1305"

* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by Mygod** [comment]
This is caused by buggy third-party Linux kernel. Please report to your ROM developer instead.
