### ISSUE TITLE
可以兼容surge或者ssr的规则吗？

### ISSUE THREAD

**Issue by frankpen** [shadowsocks/shadowsocks-android#1983]
这些规则有人维护，能保证翻墙和去广告。导入了acl4ssr发现不能正常工作，不知道您这个客户端规则是什么样的？

**Comment by madeye** [comment]
No plan for this.

**Comment by qgtxqj** [comment]
是支持acl4ssr的fullgfwlist.acl的，全选复制粘贴到SS里面就可以了。
