### ISSUE TITLE
点小飞机连接时出现异常，Error running exec() Command:[ /mnt/asec

### ISSUE THREAD

**Issue by gaotong2055** [shadowsocks/shadowsocks-android#1984]
安装的4.5.5 版本，安装了外置存储卡。点击小飞机时出现下图的异常

**Screenshots**

![image](https://user-images.githubusercontent.com/4126479/47577102-aad21e00-d978-11e8-8a77-c08b7c760b3a.png)

**Smartphone (please complete the following information):**
 - Android version:5.02
 - Version:  4.5.5
 - Last version that did not exhibit the issue: [not applicable]

**Comment by madeye** [comment]
Make sure the app is installed in internal memory. Otherwise it won't work.
