### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wzfxue** [shadowsocks/shadowsocks-android#1987]
1.建议增加全部清空功能（目前如果导入太多每次都要手工挨个删除）
2.目前仅有从粘贴板导入，建议增加从网址url导入（支持ss和ssr link，及config文件配置内容等方式的解析）

**Comment by madeye** [comment]
1. You can clear the data in Android's app settings.
2. No plan for this.

**Comment by GH-JY** [comment]
你是安卓的吧 不习惯可以用SSR，SS不支持你说的那些功能，估计作者也没计划增加你说的第二点，第一点已经有这样的功能了。
