### ISSUE TITLE
The Apps VPN mode is not working after I updated my Samsung Note 9 Firmware to V9.5

### ISSUE THREAD

**Issue by antiwinter** [shadowsocks/shadowsocks-android#1988]
I am sorry if this kind of question is not to be posted here, just close it.

**Problem**

Apps VPN mode is not working. Things like *Play Store*, *Youtube* cannot connect to server anymore. They all worked well before this firmware update.

**My configuration**

|Item| State|
|-|-|
|`Route`|Bypass LAN & mainland China|
|`Remote DNS`| 8.8.8.8|
|`IPv6 Route`| Off |
|`Apps VPN mode`| On|
|`DNS Forwarding`| Off|

This worked well before my firmware update.

**My Question**

Does anybody suffering the same problem?
I would be appreciate if somebody tell me what this fail may relate to or tell me how to debug/solve this fail.

**Comment by madeye** [comment]
Try uninstall and reinstall the app.

**Comment by zcq100** [comment]
I have the same problem.

**Comment by antiwinter** [comment]
> Try uninstall and reinstall the app.

This do the trick, thank you so much. @acq100 you've got to have a try, my configuration is still as above, and the *Chrome* app is in VPN list too.
