### ISSUE TITLE
为何ACL文件没有被自动下载？

### ISSUE THREAD

**Issue by monkey000** [shadowsocks/shadowsocks-android#1994]
LineageOS
Android 8.1.0 
Shadowsocks 4.6.1

在自定义规则设置处填入了ACL的链接
发现并没有下载ACL文件，期间也连接过节点
只能手动将ACL文件重命名为custom-rules.acl复制到files目录下使用
为什么填入链接后没有下载ACL文件？？？
![screenshot_20181108-141303_](https://user-images.githubusercontent.com/36021889/48181568-ef8b8b00-e362-11e8-9178-9b8211ee2d9d.png)
![screenshot_20181108-141306_shadowsocks](https://user-images.githubusercontent.com/36021889/48181569-f0242180-e362-11e8-9f87-81a120fbfa4b.png)

**Comment by monkey000** [comment]
> Obviously, you're using a non-compatible ACL files.

This is the ACL url I am using：
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/gfwlist-banAD.acl

If it is not compatible, why will it work after I copy the downloaded ACL file to the files directory?

**Comment by madeye** [comment]
Even you download it to local, it cannot work as expected.

To verify this, you can just visit any banned site in that list, like 58.com.

**Comment by madeye** [comment]
Actually, even you download it to local, it cannot work as expected.

To verify this, you can just visit any banned site in that list, like 58.com.

**Comment by Mygod** [comment]
You're looking at the wrong folder.
