### ISSUE TITLE
Wear OS can't connect banned website using the network of the phone.

### ISSUE THREAD

**Issue by tony1016** [shadowsocks/shadowsocks-android#1997]
Please read contributing guidelines. Thanks.

**Describe the bug**
I have a fossil Q Android Watch which use Bluetooth to connect with my phone, but the watch can't connect to banned website like google etc.

**Expected behavior**
My phone and the watch both can using the vpn 

**Smartphone (please complete the following information):**
 - Android version: 9
 - Device: OnePlus 6
 - Version:9.0.2

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by ngstgl** [comment]
It should be no, only your mobile phone can be VPN, but it is not possible to transfer through the mobile phone network.

**Comment by tony1016** [comment]
### So sad...

**Comment by madeye** [comment]
It’s expected.
