### ISSUE TITLE
GFW list seems to be outdated, can we manually update it?

### ISSUE THREAD

**Issue by ouyangde** [shadowsocks/shadowsocks-android#1999]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
There is a option called "URL to online config", I set it to "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt", but without any effect.

**Describe the solution you'd like**
Provide a feature to set URL to GFWlist, and user can updated it when nessesary.

**Comment by Mygod** [comment]
Use custom rules.

**Comment by ouyangde** [comment]
> Use custom rules.

But mostly we didn't know which URLs are blocked when we use Apps. Then how can we use custom rules?
