### ISSUE TITLE
Build command failed.(build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=)

### ISSUE THREAD

**Issue by zdf01082413** [shadowsocks/shadowsocks-android#2001]
Build command failed
Error while executing process C:\Users\Mycomputer\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib -j2 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

**Comment by oreuuz** [comment]
user git clone --recurse to get this project and you must out of the wall.

**Comment by DonZheng** [comment]
Hi @oreuuz @madeye ,

I encountered exactly same issue after following @oreuuz 's advise. Here is what I did:
1. git clone --recouse https://github.com/shadowsocks/shadowsocks-android.git
2. open Android Studio 3.3 
(Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0)

3. Import existing Android Studio project and wait till it finished
4. Click Run (mobile)

**Error message as below. Any guidance will be greatly appreciated.**

`Build command failed.
Error while executing process C:\Users\don\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\don\Documents\VPN\shadowsocks\shadowsocks-android-master-git-clone\shadowsocks-android\core\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\don\Documents\VPN\shadowsocks\shadowsocks-android-master-git-clone\shadowsocks-android\core\src\main\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\don\Documents\VPN\shadowsocks\shadowsocks-android-master-git-clone\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib -j8 C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86_64/libss-local.so}
[x86_64] Compile        : ss-local <= local.c
[x86_64] Compile        : ss-local <= cache.c
[x86_64] Compile        : ss-local <= udprelay.c
[x86_64] Compile        : ss-local <= utils.c
[x86_64] Compile        : ss-local <= netutils.c
[x86_64] Compile        : ss-local <= json.c
[x86_64] Compile        : ss-local <= jconf.c
[x86_64] Compile        : ss-local <= acl.c
[x86_64] Compile        : ss-local <= http.c
[x86_64] Compile        : ss-local <= tls.c
[x86_64] Compile        : ss-local <= rule.c
[x86_64] Compile        : ss-local <= crypto.c
[x86_64] Compile        : ss-local <= stream.c
[x86_64] Compile        : ss-local <= aead.c
[x86_64] Compile        : ss-local <= base64.c
[x86_64] Compile        : ss-local <= plugin.c
[x86_64] Compile        : ss-local <= ppbloom.c
[x86_64] Compile        : ss-local <= android.c
[x86_64] Compile        : ev <= ev.c
[x86_64] Compile        : ev <= event.c
[x86_64] Compile        : mbedtls <= aes.c
[x86_64] Compile        : mbedtls <= aesni.c
[x86_64] Compile        : mbedtls <= arc4.c
[x86_64] Compile        : mbedtls <= asn1write.c
[x86_64] Compile        : mbedtls <= asn1parse.c
[x86_64] Compile        : mbedtls <= base64.c
[x86_64] Compile        : mbedtls <= bignum.c
[x86_64] Compile        : mbedtls <= blowfish.c
[x86_64] Compile        : mbedtls <= camellia.c
[x86_64] Compile        : mbedtls <= ccm.c
[x86_64] Compile        : mbedtls <= certs.c
[x86_64] Compile        : mbedtls <= cipher.c
[x86_64] Compile        : mbedtls <= cipher_wrap.c
[x86_64] Compile        : mbedtls <= cmac.c
[x86_64] Compile        : mbedtls <= ctr_drbg.c
[x86_64] Compile        : mbedtls <= debug.c
[x86_64] Compile        : mbedtls <= des.c
[x86_64] Compile        : mbedtls <= dhm.c
[x86_64] Compile        : mbedtls <= ecdh.c
[x86_64] Compile        : mbedtls <= ecdsa.c
[x86_64] Compile        : mbedtls <= ecjpake.c
[x86_64] Compile        : mbedtls <= ecp.c
[x86_64] Compile        : mbedtls <= ecp_curves.c
[x86_64] Compile        : mbedtls <= entropy.c
[x86_64] Compile        : mbedtls <= entropy_poll.c
[x86_64] Compile        : mbedtls <= error.c
[x86_64] Compile        : mbedtls <= gcm.c
[x86_64] Compile        : mbedtls <= havege.c
[x86_64] Compile        : mbedtls <= hmac_drbg.c
[x86_64] Compile        : mbedtls <= md.c
[x86_64] Compile        : mbedtls <= md2.c
[x86_64] Compile        : mbedtls <= md4.c
[x86_64] Compile        : mbedtls <= md5.c
[x86_64] Compile        : mbedtls <= md_wrap.c
[x86_64] Compile        : mbedtls <= memory_buffer_alloc.c
[x86_64] Compile        : mbedtls <= net_sockets.c
[x86_64] Compile        : mbedtls <= oid.c
[x86_64] Compile        : mbedtls <= padlock.c
[x86_64] Compile        : mbedtls <= pem.c
[x86_64] Compile        : mbedtls <= pk.c
[x86_64] Compile        : mbedtls <= pk_wrap.c
[x86_64] Compile        : mbedtls <= pkcs11.c
[x86_64] Compile        : mbedtls <= pkcs12.c
[x86_64] Compile        : mbedtls <= pkcs5.c
[x86_64] Compile        : mbedtls <= pkparse.c
[x86_64] Compile        : mbedtls <= ripemd160.c
[x86_64] Compile        : mbedtls <= platform.c
[x86_64] Compile        : mbedtls <= pkwrite.c
[x86_64] Compile        : mbedtls <= rsa.c
[x86_64] Compile        : mbedtls <= sha1.c
[x86_64] Compile        : mbedtls <= sha256.c
[x86_64] Compile        : mbedtls <= sha512.c
[x86_64] Compile        : mbedtls <= ssl_cache.c
[x86_64] Compile        : mbedtls <= ssl_ciphersuites.c
[x86_64] Compile        : mbedtls <= ssl_cli.c
[x86_64] Compile        : mbedtls <= ssl_cookie.c
[x86_64] Compile        : mbedtls <= ssl_srv.c
[x86_64] Compile        : mbedtls <= ssl_tls.c
[x86_64] Compile        : mbedtls <= ssl_ticket.c
[x86_64] Compile        : mbedtls <= threading.c
[x86_64] Compile        : mbedtls <= timing.c
[x86_64] Compile        : mbedtls <= version.c
[x86_64] Compile        : mbedtls <= version_features.c
[x86_64] Compile        : mbedtls <= x509.c
[x86_64] Compile        : mbedtls <= x509_create.c
[x86_64] Compile        : mbedtls <= x509_crl.c
[x86_64] Compile        : mbedtls <= x509_crt.c
[x86_64] Compile        : mbedtls <= x509_csr.c
[x86_64] Compile        : mbedtls <= x509write_crt.c
[x86_64] Compile        : mbedtls <= xtea.c
[x86_64] Compile        : mbedtls <= x509write_csr.c
[x86_64] Compile        : ipset <= general.c
[x86_64] Compile        : ipset <= assignments.c
[x86_64] Compile        : ipset <= basics.c
[x86_64] Compile        : ipset <= bdd-iterator.c
[x86_64] Compile        : ipset <= expanded.c
[x86_64] Compile        : ipset <= reachable.c
[x86_64] Compile        : ipset <= read.c
[x86_64] Compile        : ipset <= write.c
[x86_64] Compile        : ipset <= allocation.c
[x86_64] Compile        : ipset <= inspection.c
[x86_64] Compile        : ipset <= ipv4_map.c
[x86_64] Compile        : ipset <= ipv6_map.c
[x86_64] Compile        : ipset <= allocation.c
[x86_64] Compile        : ipset <= storage.c
[x86_64] Compile        : ipset <= inspection.c
[x86_64] Compile        : ipset <= ipv4_set.c
[x86_64] Compile        : ipset <= ipv6_set.c
[x86_64] Compile        : ipset <= iterator.c
[x86_64] Compile        : ipset <= storage.c
[x86_64] Compile        : cork <= commands.c
[x86_64] Compile        : cork <= allocator.c
[x86_64] Compile        : cork <= error.c
[x86_64] Compile        : cork <= gc.c
[x86_64] Compile        : cork <= hash.c
[x86_64] Compile        : cork <= ip-address.c
[x86_64] Compile        : cork <= mempool.c
[x86_64] Compile        : cork <= timestamp.c
[x86_64] Compile        : cork <= u128.c
[x86_64] Compile        : cork <= array.c
[x86_64] Compile        : cork <= bitset.c
[x86_64] Compile        : cork <= buffer.c
[x86_64] Compile        : cork <= dllist.c
[x86_64] Compile        : cork <= file-stream.c
[x86_64] Compile        : cork <= hash-table.c
[x86_64] Compile        : cork <= managed-buffer.c
[x86_64] Compile        : cork <= ring-buffer.c
[x86_64] Compile        : cork <= slice.c
[x86_64] Compile        : cork <= directory-walker.c
[x86_64] Compile        : cork <= env.c
[x86_64] Compile        : cork <= exec.c
[x86_64] Compile        : cork <= files.c
[x86_64] Compile        : cork <= process.c
[x86_64] Compile        : cork <= subprocess.c
[x86_64] Compile        : cork <= thread.c
[x86_64] Compile        : bloom <= bloom.c
[x86_64] Compile        : bloom <= MurmurHash2.c
[x86_64] Compile        : sodium <= aead_aes256gcm_aesni.c
[x86_64] Compile        : sodium <= aead_chacha20poly1305.c
[x86_64] Compile        : sodium <= aead_xchacha20poly1305.c
[x86_64] Compile        : sodium <= ed25519_ref10.c
[x86_64] Compile        : sodium <= core_hchacha20.c
[x86_64] Compile        : sodium <= core_salsa_ref.c
[x86_64] Compile        : sodium <= blake2b-compress-ref.c
[x86_64] Compile        : sodium <= blake2b-ref.c
[x86_64] Compile        : sodium <= generichash_blake2b.c
[x86_64] Compile        : sodium <= onetimeauth_poly1305.c
[x86_64] Compile        : sodium <= poly1305_donna.c
[x86_64] Compile        : sodium <= crypto_pwhash.c
[x86_64] Compile        : sodium <= argon2-core.c
[x86_64] Compile        : sodium <= argon2.c
[x86_64] Compile        : sodium <= argon2-encoding.c
[x86_64] Compile        : sodium <= blake2b-long.c
[x86_64] Compile        : sodium <= pwhash_argon2i.c
[x86_64] Compile        : sodium <= argon2-fill-block-ref.c
[x86_64] Compile        : sodium <= scalarmult_curve25519.c
[x86_64] Compile        : sodium <= x25519_ref10.c
[x86_64] Compile        : sodium <= stream_chacha20.c
[x86_64] Compile        : sodium <= chacha20_ref.c
[x86_64] Compile        : sodium <= stream_salsa20.c
[x86_64] Compile        : sodium <= salsa20_ref.c
[x86_64] Compile        : sodium <= verify.c
[x86_64] Compile        : sodium <= randombytes.c
[x86_64] Compile        : sodium <= randombytes_sysrandom.c
[x86_64] Compile        : sodium <= core.c
[x86_64] Compile        : sodium <= runtime.c
[x86_64] Compile        : sodium <= utils.c
[x86_64] Compile        : sodium <= version.c
[x86_64] Compile        : ancillary <= fd_recv.c
[x86_64] Compile        : ancillary <= fd_send.c
[x86_64] Compile        : pcre <= pcre_byte_order.c
[x86_64] Compile        : pcre <= pcre_compile.c
[x86_64] Compile        : pcre <= pcre_config.c
[x86_64] Compile        : pcre <= pcre_dfa_exec.c
[x86_64] Compile        : pcre <= pcre_exec.c
[x86_64] Compile        : pcre <= pcre_fullinfo.c
[x86_64] Compile        : pcre <= pcre_globals.c
[x86_64] Compile        : pcre <= pcre_jit_compile.c
[x86_64] Compile        : pcre <= pcre_get.c
[x86_64] Compile        : pcre <= pcre_maketables.c
[x86_64] Compile        : pcre <= pcre_newline.c
[x86_64] Compile        : pcre <= pcre_ord2utf8.c
[x86_64] Compile        : pcre <= pcre_refcount.c
[x86_64] Compile        : pcre <= pcre_string_utils.c
[x86_64] Compile        : pcre <= pcre_tables.c
[x86_64] Compile        : pcre <= pcre_study.c
[x86_64] Compile        : pcre <= pcre_ucd.c
[x86_64] Compile        : pcre <= pcre_valid_utf8.c
[x86_64] Compile        : pcre <= pcre_xclass.c
[x86_64] Compile        : pcre <= pcre_version.c
[x86_64] Compile        : pcre <= pcre_chartables.c
[x86_64] StaticLibrary  : libev.a
[x86_64] StaticLibrary  : libmbedtls.a
[x86_64] StaticLibrary  : libipset.a

C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/libev/ev.c:483:48: warning: '/*' within block comment [-Wcomment]
/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                               ^
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/libev/ev.c:1831:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                              ^
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/libev/ev.c:3878:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                       ~~~~~~~~~~^~~~~~~~~~~~~ ~
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/libev/ev.c:3878:34: note: place parentheses around the '&' expression to silence this warning
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                 ^
                       (                      )
3 warnings generated.
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/mbedtls/library/net_sockets.c:316:37: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                    (void *) &type, &type_len ) != 0 ||
                                    ^~~~~~~~~
C:/Users/joe/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\sys/socket.h:310:92: note: passing argument to parameter '__value_length' here
__socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                           ^
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/mbedtls/library/net_sockets.c:326:80: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                                             (struct sockaddr *) &client_addr, &n );
                                                                               ^~
C:/Users/joe/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\sys/socket.h:300:71: note: passing argument to parameter '__addr_length' here
__socketcall int accept(int __fd, struct sockaddr* __addr, socklen_t* __addr_length);
                                                                      ^
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/mbedtls/library/net_sockets.c:334:59: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                        (struct sockaddr *) &client_addr, &n );
                                                          ^~
C:/Users/joe/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\sys/socket.h:334:119: note: passing argument to parameter '__src_addr_length' here
__socketcall ssize_t recvfrom(int __fd, void* __buf, size_t __n, int __flags, struct sockaddr* __src_addr, socklen_t* __src_addr_length);
                                                                                                                      ^
C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/mbedtls/library/net_sockets.c:369:59: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                         (struct sockaddr *) &local_addr, &n ) != 0 ||
                                                          ^~
C:/Users/joe/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\sys/socket.h:309:76: note: passing argument to parameter '__addr_length' here
__socketcall int getsockname(int __fd, struct sockaddr* __addr, socklen_t* __addr_length);
                                                                           ^
4 warnings generated.
error: unable to open output file 'C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/pcre/C_/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/patch/pcre/pcre_chartables.o': 'No such file or directory'
1 error generated.
make: *** [C:/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/pcre/C_/Users/joe/Documents/VPN/shadowsocks/shadowsocks-android-master-git-clone/shadowsocks-android/core/src/main/jni/patch/pcre/pcre_chartables.o] Error 1
make: *** Waiting for unfinished jobs....

`
