### ISSUE TITLE
Exporting profile does not URL-encode apostrophe in profile name

### ISSUE THREAD

**Issue by premiumrich** [shadowsocks/shadowsocks-android#2004]
**Describe the bug**
When exporting a profile to a QR code or to clipboard within the app, any apostrophes (') contained within the remark/tag/profile name are not URL-encoded to %27. This causes Shadowsocks Android to truncate the profile name after the first apostrophe.

**To Reproduce**
1. Create a profile with an apostrophe in the profile name.
2. Press share and export to clipboard.
3. Import from clipboard on the same device or another.
4. The profile name will be truncated after the first occurrence of an apostrophe.

**Problem only happens on import.** The exported URI is perfect.

For example, the app exports one of my profiles to:
```
ss://<BASE64>@<SERVER:PORT>#Richard's%20Server
```
(placeholders were added). **The profile name should be "Richard's Server"**.

After importing from clipboard, **the profile name shows "Richard" instead**, because the apostrophe is not handled properly. Please see screenshots as well.

**Expected behavior**
Exporting URI should URL-encode apostrophes (') to %27. This will allow profile names to be exported properly because an apostrophe is a special character.

**Screenshots**
Before importing:
![screenshot_20181116-102217](https://user-images.githubusercontent.com/7052890/48638411-c9cb3b00-e98d-11e8-93e1-2358d1c7a519.jpg)

After importing from clipboard:
![screenshot_20181116-102227](https://user-images.githubusercontent.com/7052890/48638418-cdf75880-e98d-11e8-9c15-231feabe8359.jpg)

**Device:**
 - Android version: 8.0.0
 - Device: OnePlus 3T A3000
 - Version: v4.5.7 (latest stable from Play Store)

**Configuration**
Not applicable. This bug is only relevant to the profile name.

**Additional context**
It seems that the apostrophe is the only character not properly handled. I have not tested other characters extensively, but "@" is URL-encoded properly.

**Comment by madeye** [comment]
It looks `'` should not be encoded. The problem here we dropped the character when importing.

https://stackoverflow.com/questions/31511922/is-uri-encode-in-android-equivalent-to-encodeuricomponent-in-javascript
