### ISSUE TITLE
与zerotier结合会不会更加安全

### ISSUE THREAD

**Issue by haohowey** [shadowsocks/shadowsocks-android#2005]
如题，先用zerotier将本地和vps之间建立一个局域网，然后再用ss连接代理，在客户端的ss填写入局域网ip，我在mac上测试完全没问题，理论上应该更加安全。

**Comment by madeye** [comment]
Within zerotier, a plain socks5 proxy should be enough.

**Comment by linanwx** [comment]
Typically, the communication protocol used by the zerotier has a handshake feature that is easily identifiable. If the communication between the zerotiers can be done using shadowsocks, then I think this is safe.
