### ISSUE TITLE
重新在vps安装了SSR就没法在android上使用了

### ISSUE THREAD

**Issue by githubhao0705** [shadowsocks/shadowsocks-android#2006]
请问这是为什么呢？试过了安装最新版app，卸载了再安装。
用的是这个命令安装的SSR
`wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh
chmod +x shadowsocksR.sh
./shadowsocksR.sh 2>&1 | tee shadowsocksR.log`
毫无头绪啊

**Comment by madeye** [comment]
I don't think this app supports "SSR".

**Comment by githubhao0705** [comment]
> I don't think this app supports "SSR".

oh？is true？

**Comment by githubhao0705** [comment]
> I don't think this app supports "SSR".

Thank you for your reminder, I found another app and it was successful!   
----for translate.google.com
