### ISSUE TITLE
自定义规则里面可以加上绕过局域网大陆地址的快速设置吗?

### ISSUE THREAD

**Issue by fcying** [shadowsocks/shadowsocks-android#2007]
现在只有一个GFW的. 

能加一个快速加入绕过局域网和大陆地址吗? 方便在这基础上加点需要直连的地址.

**Comment by madeye** [comment]
Bypassing is not supported in custom rules.

**Comment by fcying** [comment]
那只能在gfw基础上多加很多地址了...感谢回复
