### ISSUE TITLE
shadowsocks aes-128-gcm 加解密问题

### ISSUE THREAD

**Issue by rc452860** [shadowsocks/shadowsocks-android#2012]
根据shadowoskcs aead公式解密的时候应该由
AE_decrypt(key, nonce, ciphertext, tag) => message

加密的时候收到的流应该是
[iv][encrypted payload length][length tag][encrypted payload][payload tag]...
并没有对应的nonce在java中解密一直提示
javax.crypto.AEADBadTagException: Tag mismatch!

nonce是随机生成的吗？加密和解密可以使用不同的nonce？iv 和 nonce有什么区别？

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-org/wiki/AEAD-Ciphers#key-derivation

**Comment by rc452860** [comment]
@madeye 我看到这个了，在https://shadowsocks.org/en/spec/AEAD-Ciphers
我不能理解的是nonce并没有包含在tcp stream里边，解密是不需要nonce吗？

**Comment by madeye** [comment]
> The first AEAD encrypt/decrypt operation uses a counting nonce starting from 0. After each encrypt/decrypt operation, the nonce is incremented by one as if it were an unsigned little-endian integer. Note that each TCP chunk involves two AEAD encrypt/decrypt operation: one for the payload length, and one for the payload. Therefore each chunk increases the nonce twice.

**Comment by rc452860** [comment]
@madeye thank you. I also got it just now.
