### ISSUE TITLE
about local-dns global config

### ISSUE THREAD

**Issue by qyb** [shadowsocks/shadowsocks-android#2016]
We have had a global config named 'Local DNS port'. So, the new config name will be 'Customize Local DNS upstream'? If user enable it, then he/she need input a string such as 'udp:114.114.114.114,udp:119.29.29.29:53,tcp-tls:cloudflare-dns.com,tcp-tls:dnsovertls.sinodun.com:443@145.100.185.15'??

**Comment by madeye** [comment]
Add a new section called "DNS upstreams", which would include "DNS over TLS", "DNS over plain UDP" and "DNS over plain TCP" options.

**Comment by sqwwqw5** [comment]
> Add a new section called "Local DNS upstreams", which would include "DNS over TLS", "DNS over plain UDP" and "DNS over plain TCP" options.

I support the idea to make local DNS configurable but do we really need DNS over TLS&TCP for locals?.. I say just make it simple...
