### ISSUE TITLE
是否有日志调试请求失败的域名

### ISSUE THREAD

**Issue by ykswang** [shadowsocks/shadowsocks-android#2017]
自己写规则最大的问题是我不知道某个APP的哪个域名不通了，目前好像没有地方可以查看正在请求的地址的结果，通还是不通，方便用户来完善自己的规则

**Comment by madeye** [comment]
You can easily debug this with the log on your server.

**Comment by ykswang** [comment]
因为是走规则转发，也就是我需要检查有哪些应该走转发但是我没有配置，这个时候我自己的SS服务器是不会有这个域名的日志的吧

**Comment by madeye** [comment]
if no log for that domain, it exactly means that domain name is not in your list.

**Comment by ykswang** [comment]
I mean, if andorid-shadowsocks doesn't provide logs, how can I know that an app uses a blocked domain name?

To put it another way, an app uses a blocked domain name, but I don't know what the domain name is.

**Comment by Mygod** [comment]
This seems to be a feature request rather than a question.

I think this is reasonable as DNS resolving is done by overture on shadowsocks-android. And to some extent this certainly can be done. A major problem is that I don't see a clean way of presenting logs in Android UI.

**Comment by madeye** [comment]
Overture has a 'debug' option to enable debug mode and output the logs to logcat.

If you can build the app in debug mode, please just try it first.

**Comment by wuya1111** [comment]
能请教下  win10  编译shadowsocks 项目吗  ，遇到难点了， 方便的化 加qq  ：897268140 ，指导下

**Comment by williamxxy** [comment]
没办法，只有一条一条查日志，用一个好一点儿的文本编辑器，分类那种
