### ISSUE TITLE
可以修改协议增加协议字段吗？

### ISSUE THREAD

**Issue by imkobedroid** [shadowsocks/shadowsocks-android#2018]
可以修改协议增加协议字段吗？客户端的代码是不是没发达到效果！如果能达到，我该怎样进行修改呢

**Comment by madeye** [comment]
Yeah, it's required to modify both client and server, if you'd like to change anything related to protocols.

**Comment by imkobedroid** [comment]
> Yeah, it's required to modify both client and server, if you'd like to change anything related to protocols.

因为我对sockt5不是很了解  我需要增加字段的具体操作是在哪个文件里面呢？谢谢
