### ISSUE TITLE
salsa20 failed

### ISSUE THREAD

**Issue by pfitseng** [shadowsocks/shadowsocks-android#202]
I reported at https://github.com/shadowsocks/shadowsocks/issues/238 first.
Then upgrade the client last night, but not any luck.

Server: shadowsocks (2.6.1) + salsa20
Client: Android shadowsocks 2.6.2 + salsa20
log:
WARNING unsupported addrtype 178, maybe wrong password
ERROR can not parse header

Under debian jessie libsodium13:amd64 1.0.0-1
loading libsodium from libsodium.so.13

**Comment by madeye** [comment]
I cannot reproduce your issue with 2.6.1 server and 2.6.2 client. Double check your configs.

**Comment by pfitseng** [comment]
我用windows的客户端相同配置没有问题，是不是和我的ROM有关？我用的是Omni ROM。客户端能打日志吗？

**Comment by pfitseng** [comment]
我重做了chacha20验证的服务端，最简单的密码，也不行
用其他人提供的chacha20的服务端也不行，在windows客户端下都是正常的

**Comment by dutonttie** [comment]
salsa20我不知道，但是chacha20是可以的，我就是用一直在用。

**Comment by dantewang** [comment]
服务端

shadowsocks-libev：2.1.1-1.fc21（安装自copr库）

客户端

shadowsocks-c#：服务端使用chacha20和salsa20的时候，客户端设置对应的加密方式，在Windows上可以正常工作；
shadowsocks-android 2.6.2：使用chacha20和salsa20时，无法通过代理访问任何网站，使用aes-256-cfb则没问题。
