### ISSUE TITLE
为什么不能下载了

### ISSUE THREAD

**Issue by joesufe** [shadowsocks/shadowsocks-android#2023]
如题，只剩版本号了。

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-android/releases
https://play.google.com/store/apps/details?id=com.github.shadowsocks

**Comment by joesufe** [comment]
真的下载不了，不信试试

**Comment by pexcn** [comment]
可以，是你不行

**Comment by AnyWAT** [comment]
github 上图、下载需代理😂

**Comment by joesufe** [comment]
一直都用代理的，以前一直可以，就是现在不行

**Comment by AnyWAT** [comment]
检查代理设置内有关 github 的切换规则？
