### ISSUE TITLE
魅族note6手机，无法识别二维码

### ISSUE THREAD

**Issue by qian-jiahong** [shadowsocks/shadowsocks-android#2027]
添加节点时，扫描框都变形了。识别不到任何二维码。

**Comment by madeye** [comment]
Please report this issue to Meizu.

**Comment by Mygod** [comment]
This could happen when Google play services is still downloading models for QR code. Try again later.

**Comment by qian-jiahong** [comment]
> 
> 
> Please report this issue to Meizu.

The scanning QR code function of other applications is normal.

**Comment by qian-jiahong** [comment]
The scan box is normal and the preview QR code image is flat.
