### ISSUE TITLE
在使用speedtest软件时候出现“网络通讯问题”

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-android#203]
使用speedtest应用时候，在“上载阶段”就会出现“网络通讯问题”，而“下载阶段”是正常的。
关闭shadowsocks后，使用此应用就没有问题。

“nat模式”和“vpn模式”都有相同的问题。
![screenshot_2015-01-02-21-07-03](https://cloud.githubusercontent.com/assets/9409003/5596251/55e92446-92c4-11e4-9d16-d01ab1774ed1.png)

**Comment by madeye** [comment]
试了一下，无法重现。

![screenshot_2015-01-02-21-25-42](https://cloud.githubusercontent.com/assets/627917/5596336/67438e00-92c6-11e4-9450-1bee83725393.png)

**Comment by myliyifei** [comment]
我也是哦  测试在手机网络的情况下。比如我联通4g  测试连接国内服务器  下载测速正常
上传测速前面测速正常，总是在最后一瞬间降到0然后一直没有速度。看起来像是链接无法正常关闭。这个问题我两个月前就发现了，因为影响不大，所以一直没有报告。
2015年1月2日 下午9:29于 "Max Lv" <notifications@github.com>写道：

**Comment by dutonttie** [comment]
我用adb logcat -s "UploadTestTask"两种情况的日志,
正常情况(未开启ss)
![normal](https://cloud.githubusercontent.com/assets/9409003/5602769/4b3ad2fc-939f-11e4-9282-cff4fbec4805.png)
出错情况(开启ss)
![error](https://cloud.githubusercontent.com/assets/9409003/5602772/6d6f0618-939f-11e4-9e8c-09ed1b792a2a.png)

我使用的speedtest 版本是3.2.7
shadowsocks 是最新版本.
我不知道这个能不能帮你定位到问题所在，如果还需要我做什么请告诉我。
我看到log里面有recvform错误。

**Comment by JohnnySun** [comment]
Yep, Sometimes the shadowsocks Android will no traffic until you restart.

**Comment by dutonttie** [comment]
Ok,I restarted my phone,but no help.
2015年1月4日 下午4:15 於 "JohnnySun" <notifications@github.com> 寫道：

> Yep, Sometimes the shadowsocks Android will no traffic until you restart.
>
