### ISSUE TITLE
4.6.2 crash when starting service

### ISSUE THREAD

**Issue by iKirby** [shadowsocks/shadowsocks-android#2030]
**Describe the bug**
Shadowsocks crashes sometimes when starting service, especially when stopping and restarting service manually.

**To Reproduce**
When service is running, open Shadowsocks and stop service, then start service.

**Expected behavior**
Service stop and start successfully.

**Smartphone (please complete the following information):**
 - Android version: 7.1.2
 - Device: Nexus 9 Wi-Fi
 - Version: 4.6.2 (9af85af, the latest pre-release version)
 - Last version that did not exhibit the issue: 4.6.1

**Configuration**
* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open

**Additional context**
Crash log: 
[2018-12-16-23-56-47.txt](https://github.com/shadowsocks/shadowsocks-android/files/2683700/2018-12-16-23-56-47.txt)

**Comment by Mygod** [comment]
Probably caused by `throwErrnoException`. Thanks for reporting, will check later.

**Comment by madeye** [comment]
@Mygod I think we already catch that exception correctly?

https://github.com/shadowsocks/shadowsocks-android/blob/7f4624f31eb20f05e537b2d0d464f43b0446dbaf/core/src/main/java/com/github/shadowsocks/bg/VpnService.kt#L252

**Comment by madeye** [comment]
Please try this APK: https://www.dropbox.com/s/9asq5gvypvrk1w9/mobile-universal-release.apk

**Comment by iKirby** [comment]
@madeye This APK works well. I tried stopping and restarting service multiple times and there was no crash.
