### ISSUE TITLE
如何触发更新 ACL 规则？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#2039]
请问怎么才能让它更新 [AclSyncer.kt#L46](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/acl/AclSyncer.kt#L46) 里的 acl?

**Comment by Mygod** [comment]
1. Update the app;
2. Connect to a profile with the route you wish to update.

**Comment by pexcn** [comment]
@Mygod 尝试过了，然后检查了 /data/data/user_de/0/com.github.shadowsocks/... 里面，也没发现有更新

**Comment by Mygod** [comment]
Is this a bug report?

**Comment by Mygod** [comment]
I just checked and I believe everything is working as intended. Only the route you picked would be updated from the server.

**Comment by pexcn** [comment]
我今晚再测一次吧... 😅

**Comment by pexcn** [comment]
@Mygod 请问 ACL 文件将会下载到哪里的？我删了 /data/data/user_de/0/com.github.shadowsocks/...  下面的 5 个 ACL 文件，再启动，没有看到有 ACL 文件被重新下载下来…

**Comment by Mygod** [comment]
no_backup

**Comment by pexcn** [comment]
@Mygod /data/data/user_de/0/com.github.shadowsocks/ 这个路径下面搜过了，`no_backup` 也没有被重新下载。

**Comment by pexcn** [comment]
嗯嗯，今晚再试试 :smile::smile:
