### ISSUE TITLE
Support batch remove for servers

### ISSUE THREAD

**Issue by exotfboy** [shadowsocks/shadowsocks-android#2051]
It is rather simple to import servers like copying from clipboard, while it is difficult to remove all of them at once. You have to remove them one by one by swiping on the item.

It would be better if  batch remove is supported.

**Comment by Mygod** [comment]
And I thought swiping is easy enough.

**Comment by exotfboy** [comment]
It's true for a single profile/server remove, not enough if you have 50+ profiles to be removed.

And generally we may purchase servers which can be used out of box rather than deploying by ourselves. And most of the server provider may provide almost  50+ different servers for its clients.

Hope you can consider that more.

**Comment by Mygod** [comment]
Batch update is currently only supported for Android TV clients. I don't think this would be a good addition as it is too time consuming to manage 50+ clients any way.

**Comment by exotfboy** [comment]
Glad to see that the 'replace from file' feature is added, how about the 'replace from clipboard' ?

**Comment by Mygod** [comment]
Replace from clipboard does not make a lot of sense because ss urls does not contain feature settings.

**Comment by exotfboy** [comment]
😒  Like API, operations should have sufficient orthogonality.  If batch remove is supported, the menus in the action bar does not need any change. Since `replace`  = `remove` + `import`.

Appreciate if you can consider this feature again.
