### ISSUE TITLE
google play

### ISSUE THREAD

**Issue by MARRYTA** [shadowsocks/shadowsocks-android#2056]
三星s8用4.6.5版本，使用GFW规则以及别的规则谷歌商店会出现DF-DFERH-01，使用bifrostV不会出现这样的情况，相同的节点。我不知道log在哪？所以无法提交

**Comment by madeye** [comment]
Enable DNS forwarding and try again.

**Comment by MARRYTA** [comment]
这样子的话谷歌商店能够打开了，但是所有地址都放在远程服务器去解析的话解析中国的地址速度会变慢，有个v2ray客户端v2rayNg也是这种情况这种情况应该是dns污染吧
，谢谢了麻烦你了


发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： Max Lv <notifications@github.com>
日期: 2019/1/2 10:49 (GMT+08:00)
收件人： shadowsocks/shadowsocks-android <shadowsocks-android@noreply.github.com>
抄送： MARRYTA <peng296912214@hotmail.com>, Author <author@noreply.github.com>
主题： Re: [shadowsocks/shadowsocks-android] google play (#2056)


Enable DNS forwarding and try again.

―

**Comment by madeye** [comment]
It's because your device is using `services.googleapis.cn` as the Google Play API, which should be resolved to a China IP. However, Google's China data center didn't provide Google Play Appstore service.

**Comment by madeye** [comment]
Try this APK: https://www.dropbox.com/s/ekzlpuhv01yxsvv/mobile-universal-release-overture-acl.apk

**Comment by MARRYTA** [comment]
你好，用了你发过来的版本没有出现错误了，麻烦你了，谢谢



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： Max Lv <notifications@github.com>
日期: 2019/1/2 12:43 (GMT+08:00)
收件人： shadowsocks/shadowsocks-android <shadowsocks-android@noreply.github.com>
抄送： MARRYTA <peng296912214@hotmail.com>, Author <author@noreply.github.com>
主题： Re: [shadowsocks/shadowsocks-android] google play (#2056)


Try this APK: https://www.dropbox.com/s/ekzlpuhv01yxsvv/mobile-universal-release-overture-acl.apk

―
