### ISSUE TITLE
something about submodule 'mobile/src/main/jni/libevent'

### ISSUE THREAD

**Issue by kinghhp** [shadowsocks/shadowsocks-android#2058]
branch:develop
command:git submodule update --init --recursive
error: no such remote ref 359ca847a649b9c318f9217c0755484d98ecb779
Fetched in submodule path 'mobile/src/main/jni/libevent', but it did not contain 359ca847a649b9c318f9217c0755484d98ecb779. Direct fetching of that commit failed.

**Comment by Mygod** [comment]
develop branch is outdated. Do not use.

**Comment by kinghhp** [comment]
what about beta branch ?






On 01/4/2019 14:41，Mygod<notifications@github.com> wrote：

develop branch is outdated. Do not use.
