### ISSUE TITLE
Proposal: UDP fallback profile for plugins

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2064]
**Is your feature request related to a problem? Please describe.**

Currently SIP003 plugins do not support UDP forwarding. However, some games (and QUIC) need to use UDP.

**Describe the solution you'd like**

A new setting called "UDP fallback profile" will be added, where all UDP traffic will be forwarded to that profile instead.

Implementation wise, we will start two `ss-local` servers at the "same" port, the main one only listening for TCP and the fallback one for UDP.

**Describe alternatives you've considered**

I remember there was a hacky way to achieve this by manually setting `remoteaddr` in `kcptun`. However, the same doesn't apply to other plugins like `simple-obfs`.

**Additional context**

This should be a client-only change. If this sounds good, should we also promote it to other implementations?

**Comment by madeye** [comment]
I think it's doable. But maybe bypassing the UDP traffic would be more useful.

**Comment by Mygod** [comment]
For security and compatibility concerns, I prefer this approach. I'll try to implement this sometime.

**Comment by Mygod** [comment]
Surprisingly, I just found a second use case for UDP fallback while playing with Google Cloud Platform (GCP), i.e. for using it in combination with TCP relay/load balancer. Basically, you can achieve similar performance as CDN accelerated solutions like [v2ray](https://github.com/shadowsocks/v2ray-plugin) with raw shadowsocks protocol.

First, to motivate the problem a bit, it's well known that RTT (Round-Trip Time) has a big impact on TCP performance (throughput). (see also: Bandwidth-delay product on Wikipedia) However, if we were able to set up a relay that works on a per-stream (that means cache involved) basis instead of per-IP packet (like routers), RTT decreases dramatically and we would get an improvement in throughput.

To do this TCP relay trick, I used [Load balancing feature in GCP](https://cloud.google.com/load-balancing/) (note to others trying to replicate this: use Global Scope addresses, not Regional; and Premium Network Tier, not Standard). If I'm not mistaken, this feature should incur no extra cost, but I'll update this post if I am wrong.

Observed: According to ping, RTT decreased from ~220ms to ~94ms. A (single connection) throughput increase from ~5Mbps (QUIC over Shadowsocks UDP) to ~15Mbps (HTTPS over Shadowsocks TCP) during especially busy (a.k.a. congested) time like right now in China. This makes streaming UHD somewhat less laggy (sometimes even entirely possible, like I just streamed for ~10 minutes non-stop between two buffering).

On the other hand, this sort of trick would have no impact on UDP (not in a black-box way) since UDP is not a reliable transport. This makes UDP fallback option desirable if one wish to have UDP connectivity. (but for the test above, I actually disabled UDP fallback to prevent YouTube app from using QUIC)

I might write a post describing my configuration in more details for enable TCP load balancing on Google Cloud Platform if anyone is interested. Not sure where would be appropriate though.

**Comment by madeye** [comment]
@Mygod Cool! What about the pricing?

**Comment by Mygod** [comment]
Hmmm... Actually [load balancing is quite expensive](https://cloud.google.com/products/calculator/#id=0924576c-2d49-4569-961a-2a31427b9333).

I'll try to use this on a daily basis and see how much it actually charges.

**Comment by Mygod** [comment]
(some more off-topic remarks) Here's some benchmark with speedtest.net (single thread, i.e. no cheating mode). This is fun. It's probably profitable to make a business out of this as Google seems to charge per hour in addition to ingress bandwidth, but so far they only charged me 1 cent.

Direct:
![image](https://user-images.githubusercontent.com/3511321/52990738-8a0c6780-3444-11e9-8c15-9f9457713033.png)

Load balanced IPv4:
![image](https://user-images.githubusercontent.com/3511321/52990667-487bbc80-3444-11e9-8350-89c6ae0e4ae7.png)
