### ISSUE TITLE
shadowsocks Android连接成功，全局代理无法正常访问国外网站

### ISSUE THREAD

**Issue by code871** [shadowsocks/shadowsocks-android#2076]
红米note4x ，shadowsocks版本4.7.0，路由选全局代理后，连接成功后能访问中国国内网站，但打不开google facebook twitter之类的国外网站，点击“测试链接”时候也一直是“测试中...”。换成“绕过局域网和大陆地址”后打开国内和国外网站正常。PC端用相同服务器，正常使用，排除了服务器的问题。

这个问题是从我昨天将4.5.0版本升级到4.7.0后才发生的，请问这是更新后的bug吗？

**Comment by Mygod** [comment]
Try clearing app data.

**Comment by code871** [comment]
> Try clearing app data.

I've tried many times,reboot system,but it still doesn't works

**Comment by Mygod** [comment]
Android version? Logcat?

**Comment by code871** [comment]
NO

**Comment by Mygod** [comment]
Can you locate the [last working version](https://github.com/shadowsocks/shadowsocks-android/releases) for you?

**Comment by code871** [comment]
I use shadowsocks-Android4.7.0 on android emulator，it works.
I think it's a bug on my phone,but it's difficult to find what happened on my android system.
Thanks for your help,it's time to give up looking for the answer.
It isn't a big trouble for me ,  I just need to switch from "all" to "Bypass LAN & China" .

**Comment by Zhang21** [comment]
same problem.

<br>

```
我的问题是能够连接上，但是测试连接失败。无法正常访问。
但是在PC上没有问题。
```

**Comment by issingle** [comment]
我的荣耀v10升级到安卓9.0也无法使用ss了. 应用启动管理中允许SS后台运行也无法解决该问题.
表现就是,可以连接上,但点击测试连接一直处于测试中....

**Comment by Mygod** [comment]
Closing this issue due to off-topic comments. Try the next update maybe.
