### ISSUE TITLE
Why is the project <source root> changed to the user <HOME> directory?

### ISSUE THREAD

**Issue by IdioticMadman** [shadowsocks/shadowsocks-android#2077]
![image](https://user-images.githubusercontent.com/16788980/51296571-b739b480-1a57-11e9-9790-d3ad68097ef9.png)
The AS version is 
![image](https://user-images.githubusercontent.com/16788980/51296589-c7ea2a80-1a57-11e9-9adf-cd4968265129.png)
By the following step
1. clone the code
2. sync the submodule
3. open it By Android Studio

**Comment by Mygod** [comment]
Try https://github.com/shadowsocks/shadowsocks-android/commit/3d2d485a57dcc4c39ff27af3268d5396c5306847.

**Comment by IdioticMadman** [comment]
Thanks! I had never seen this before. What happen? 
Refine ndk-build fix this?

**Comment by Mygod** [comment]
IDK. `cpufeatures` is acting weird.

**Comment by IdioticMadman** [comment]
I am sorry to hear that. Anyway, It's fine now.
