### ISSUE TITLE
UDP traffic is blocked

### ISSUE THREAD

**Issue by IdioticMadman** [shadowsocks/shadowsocks-android#2080]
**Describe the bug**
While using Whatsapp, everything is fine.But WhatsApp calls can not connect. 

**To Reproduce**
1. import profile 
2. Click on connect button
3. Test connection successfully
4. Using WhatsApp Voice call cannot connect

**Expected behavior**
UDP traffic successfull

**Screenshots**
![image](https://user-images.githubusercontent.com/16788980/51363438-e2350e80-1b12-11e9-998d-a914b0d9bddf.png)

**Smartphone (please complete the following information):**
 - Android version: 8.1.0
 - Device: OPPO find x
 - Version: v4.7.0

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by Mygod** [comment]
Is this present on 4.6.5? Are you using UDP fallback?

**Comment by Mygod** [comment]
Ensure UDP forwarding is enabled on server side and your local network has UDP connection.

**Comment by madeye** [comment]
Double check your serer settings. Also, it'd be related to your ISP.

**Comment by IdioticMadman** [comment]
Thanks, the problem should be on the server side. When I try to use another server, the problem disappears.

**Comment by edsburke** [comment]
> Ensure UDP forwarding is enabled on server side and your local network has UDP connection.

With UDP fallback, Whatsapp call still does not work.

The UDP is enabled as the screenshot, btw, the ss-server and UDP-enabled ss-server look like:
```
ss-server -l1080 -t60 -n31200 -u --reuse-port -mchacha20-ietf-poly1305 -s172.26.4.96 -p10005 -kSome_pwd
```

```
ss-server -l1080 -t60 -n31200 -u --reuse-port -mchacha20-ietf-poly1305 -s192.104.3.123 -p10005 -kSome_pwd
```

![image](https://user-images.githubusercontent.com/43584298/93537189-baa5d300-f8ff-11ea-8afb-f4b6d26c388b.png)
