### ISSUE TITLE
GFWlist可能过期

### ISSUE THREAD

**Issue by liuzhiyi0315** [shadowsocks/shadowsocks-android#2085]
Please read contributing guidelines. Thanks.

**Describe the bug**
访问playstore出现从服务器检索信息出错

**To Reproduce**
1. 设置使用GFW列表，出现从服务器检索信息出错
2. 改为全局，问题不再出现

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 9.0
 - Device: [huawei mate 20]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by sqwwqw5** [comment]
升级4.7.0。

**Comment by liuzhiyi0315** [comment]
playstore没更新，手动升级问题解决

**Comment by Mygod** [comment]
Opt-in to beta program on Google Play or (optionally watch for releases only and) download latest pre-releases from GitHub manually to receive the latest updates.
