### ISSUE TITLE
Why can't the server use ipv4+ipv6

### ISSUE THREAD

**Issue by de-conf** [shadowsocks/shadowsocks-android#2086]
Please read contributing guidelines. Thanks.

**Describe the bug**

I hope to use ipv6+ipv4 like json.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

all

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ x] IPv6 server address
* [ x] Client IPv4 availability
* [ x] Client IPv6 availability

**Additional context**

When I fill in the server address
"128.199.89.246","2400:6180:0:d0::e78:d001"
He told me that this is the wrong address, why can't I use ipv4+ipv at the same time as on PC?...

**Comment by Mygod** [comment]
I think this duplicates https://github.com/shadowsocks/shadowsocks-libev/issues/942. For now I prefer to having two different profiles for two addresses as their performances might differ due to different routes.
