### ISSUE TITLE
路由功能不能绕过大陆地址？

### ISSUE THREAD

**Issue by xavierskip** [shadowsocks/shadowsocks-android#209]
设备：mx2
Rom：Flyme 4.1.3.4A

shadowsocks-android 2.6.2

打开 ip.cn 页面显示的是代理服务器的地址。网易云音乐和豆瓣FM都巨慢，无法正常使用，一定是走代理了。

可能是什么原因，怎么解决？

**Comment by madeye** [comment]
ROOT
