### ISSUE TITLE
Disconnects after about half hour in OnePlus 5T Android™ 9.0 Pie™.

### ISSUE THREAD

**Issue by Sh1noka** [shadowsocks/shadowsocks-android#2098]
**Describe the bug**
It worked normally before. After [a recent OS update (9.0.3)](https://www.oneplus.com/support/softwareupgrade/details?code=7), It will disconnect after some time. I had turned off optimazing battery for ShadowSocks. I also tried disable adaptive battery but with no luck.

**To Reproduce**
1. Click to connect. It connects normmaly and I can visit websites via the proxy.
2. Wait some time. (Not entering sleep mode)
3. Suddenly, It disconnects, and I can't access twitter (in China).

**Expected behavior**
Always connected until I manually disconnect it.

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 9
 - Device: ONEPLUS A5010 (OnePlus 5T)
 - Version: 4.6.5

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: XCHACHA20-IETF-POLY1305
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by triaqu** [comment]
试试在应用管理里，在SS的存储里，清除缓存和存储空间，再重新设置配置。我是这样解决的。

**Comment by Sh1noka** [comment]
I have cleared storage. It still disconnects. Also tried restarting my phone, but still the same.

**Comment by naiij** [comment]
我的A5000 9.0.1也是同样的问题。不过之前装一个比较远古的版本就不会自动断开。

**Comment by Mygod** [comment]
Oxygen OS is not supported. Install custom ROMs.

https://dontkillmyapp.com/oneplus

**Comment by Sh1noka** [comment]
Locked ss app. It didn't disconnect for 1 day. Then I enabled battery
optimization again. Still working normally now.

2019年2月2日(土) 20:41、Mygod さん（notifications@github.com）のメッセージ:
