### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ted-dev-42** [shadowsocks/shadowsocks-android#21]
hi,
I followed the instructions step by step, but end up with the following build error:
make: **\* No rule to make target `jni/shadowsocks/src/local.c', needed by`obj/local/armeabi/objs/shadowsocks/shadowsocks/src/local.o'.  Stop.

I also noticed my jni/shadowsocks/ directory is empty. I am not very familiar with git, so please forgive me if I made some stupid mistakes.

any help will be appreciated.

**Comment by Linger50** [comment]
I have the same issue, after having "git submodule update --init"
