### ISSUE TITLE
Change "DNS forwarding" yet again

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2100]
"DNS forwarding" has been a confusing option since the day its predecessor "UDP forwarding" has been associated with change in DNS behavior. Furthermore, currently this option also changes how DNS packets are routed.

UDP forwarding is active unconditionally (basically) in `libss-local.so` since quite a while ago. In this issue, I propose to replace (or rename) DNS forwarding with the following:

> *Send DNS over UDP*
> (default: off)
> Requires UDP forwarding on server side

Its behavior will be simplified to basically changing this flag in #2096: https://github.com/shadowsocks/shadowsocks-android/blob/1def9e69cee528e91f51a3fdb48d6b3dff81c455/core/src/main/java/com/github/shadowsocks/net/LocalDnsServer.kt#L52

So that also means we are getting rid of `libss-tunnel.so` and always use `LocalDnsServer`. Thoughts? @madeye

**Comment by madeye** [comment]
Not really, there are multiple ways to do DNS for shadowsocks-android:

1. Local DNS server -> (UDP) -> system DNS
2. Local DNS server -> (TCP) -> local socks5 proxy -> remote DNS
3. Local DNS server -> (UDP) -> local socks5 proxy -> remote DNS
4. -> (UDP) -> local socks5 proxy -> remote DNS

When enabling DNS forwarding, we will force all DNS queries going to local socks5 proxy, which is the case 4. It helps to avoid any DNS leak.

So maybe we can call it "Global DNS forwarding"?

**Comment by Mygod** [comment]
Well there is actually no way to use 3 right now without changing code. All DNS packets sent from local DNS server (or overture) is TCP. Also local DNS service can do unconditional DNS forwarding.
