### ISSUE TITLE
“仅代理中国大陆地址”模式无效，翻回国内失败

### ISSUE THREAD

**Issue by jbxiaoyu** [shadowsocks/shadowsocks-android#2102]
人在国外，想翻回国内。

搭建了国内SS服务器，使用安卓客户端（已更新到最新）的全局模式可以正常使用（特征为使用百度搜索IP 为国内IP）。

但现在由于想同时使用google和国内的一些app，所以我调到了“仅代理中国大陆地址”模式。但这个模式下，根本就没用（特征为使用百度搜索IP 为国外IP）。

所以想问一下这个模式什么时候修复，以及我现在想翻回国该怎么操作。

有人推荐我用自定义规则，但是我不大清楚该怎么操作，有谁能帮我一下吗

**Comment by alinusking** [comment]
尝试分应用加上全部流量。

**Comment by Windelight** [comment]
欢迎关注我的SuperACL项目，当然还很不成熟

**Comment by Windelight** [comment]
> 尝试分应用加上全部流量。

浏览器怎么破😂😂😂

**Comment by onlymash** [comment]
> > 尝试分应用加上全部流量。
> 
> 浏览器怎么破

用两个浏览器不就可以了
