### ISSUE TITLE
Tethering won't work in transproxy mode with AFWall+

### ISSUE THREAD

**Issue by Menci** [shadowsocks/shadowsocks-android#2104]
Please read contributing guidelines. Thanks.

**Describe the bug**
Follow https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#how-to-use-transproxy-mode to use transproxy mode. Works well on the phone itself, but USB/WiFi tethering won't work.

**To Reproduce**
1. Follow https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#how-to-use-transproxy-mode
2. Start USB or WiFi thther.
3. Your PC won't get a IPv4 address, and IPv6 is unable to use too.

**Expected behavior**
At least, your PC should able to suf the Internet, no matter proxied or non-proxied.

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 9.0 Pie
 - Device: Sony Xperia XZ1 Compact
 - Version: v4.7.0
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

Maybe we should add some `RETURN` rule to `PREROUTING` or `POSTROUTING` chain?

**Comment by Mygod** [comment]
Transproxy mode is only intended for very advanced usage. The script in FAQ is just a starting point for customization. For tethering [this](https://github.com/Mygod/VPNHotspot/blob/master/mobile/src/main/java/be/mygod/vpnhotspot/net/Routing.kt) might help you.
