### ISSUE TITLE
Failed resolution of: Lorg/apache/http/ProtocolVersion

### ISSUE THREAD

**Issue by rachitmishra** [shadowsocks/shadowsocks-android#2106]
Please read contributing guidelines. Thanks.

**Describe the bug**
App crashed on launch

**To Reproduce**
1. Start app
2. Click on `start` (fab button)
3. App crashes

**Expected behavior**
App shouldn't crash in any case

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [Android 9 - Jan Patch]
 - Device: Google Pixel 2 XL
 - Version: 4.6.5
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Crash log 
```
02-06 12:54:29.706 17341 17549 E AndroidRuntime: Process: com.github.shadowsocks, PID: 17341
02-06 12:54:29.706 17341 17549 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at jq.b(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at jp.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):3)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at jr.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):19)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at com.google.android.gms.ads.internal.util.ar.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):15)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at iu.a(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):20)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at iu.run(:com.google.android.gms.dynamite_adsdynamite@15090081@15.0.90 (100400-231259764):8)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/000000bd/AdsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/000000bd/AdsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090081@15.0.90 (100400-231259764):4)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-06 12:54:29.706 17341 17549 E AndroidRuntime: 	... 6 more
02-06 12:54:29.803  1170  2231 W ActivityManager:   Force finishing activity com.github.shadowsocks/.MainActivity

```

**Comment by Mygod** [comment]
Official ROM?

**Comment by rachitmishra** [comment]
Yup. official.

**Comment by madeye** [comment]
Looks related to an old Google play service installed on the device.

https://github.com/google/iosched/issues/291

**Comment by Mygod** [comment]
Can you try 4.7.0?

Also #2096 should have the latest Google play dependencies.

**Comment by rachitmishra** [comment]
> Looks related to an old Google play service installed on the device.
> 
> [google/iosched#291](https://github.com/google/iosched/issues/291)

Most probably related to this.

> Can you try 4.7.0?
> 
> Also #2096 should have the latest Google play dependencies.

I was on Playstore build. Works fine now.

The crash is no longer reproducible. 

Thank you.
