### ISSUE TITLE
Domains through proxy are also resolved via local dns？（DNS Forwarding turned off）

### ISSUE THREAD

**Issue by buguniaogu** [shadowsocks/shadowsocks-android#2107]
* Route
  [√] Bypass China
or
  [√] Bypass LAN & China
or
  [√] Gfwlist
* Remote DNS: 8.8.8.8
  [×] DNS Forwarding

For example, www.bing.com would result in a redirect to cn.bing.com.(DNS Forwarding turned off）

Can it make domains in gfwlist resolved via remote dns only(  [√] Bypass China or
  [√] Bypass LAN & China or  [√] Gfwlist)? 
This also prevents carriers sniffing you are browsing websites in gfwlist.

**Comment by Mygod** [comment]
Private DNS will be used since #2096.
