### ISSUE TITLE
通过二维码扫描添加 服务器 密码含有特殊字符 无法添加

### ISSUE THREAD

**Issue by Septembers** [shadowsocks/shadowsocks-android#211]
````
ss://rc4-md5:test!@#@100.100.100.100:1080
ss://cmM0LW1kNTp0ZXN0IUAjQDEwMC4xMDAuMTAwLjEwMDoxMDgw
注意密码是:"test!@#"
````

### 测试样本
![测试样本](https://chart.googleapis.com/chart?cht=qr&chs=300x300&choe=UTF-8&chld=L|2&chl=ss://cmM0LW1kNTp0ZXN0IUAjQDEwMC4xMDAuMTAwLjEwMDoxMDgw)

**Comment by madeye** [comment]
这种密码是不支持的，去掉@即可
