### ISSUE TITLE
是否可以做到手动更新 GFW 规则

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-android#2113]
现有的规则貌似是集成在安装包内，这样似乎看起来非常不友好。

有没有一种办法可以手动更新 GFW 列表规则。又或者以后某个新版本增加一个手动更新的按钮。

**Comment by DearTanker** [comment]
如果无法做成功能，是不是只能自己替换gfwlist.acl文件？最新4.7.0版本内置的gfwlist是2018年3月份的。。

**Comment by madeye** [comment]
Updating the GFWList, submitting a pull request, then all android client's list will be updated.

**Comment by DearTanker** [comment]
Any GFWlist.txt to gfwlist.acl tools?

**Comment by pexcn** [comment]
曾经模仿里面的脚本做了个每日更新 gfwlist 的: https://github.com/pexcn/shadowsocks-android/tree/acl
