### ISSUE TITLE
Error:No such property: GradleVersion for class: JetGradlePlugin  Consult IDE log for more details (Help | Show Log)

### ISSUE THREAD

**Issue by 1170762202** [shadowsocks/shadowsocks-android#2117]
first import and run this error,help me

**Comment by JerryCui** [comment]
Hi, did you fix it ?  Could you share any resolution?

**Comment by Jaypatelbond** [comment]
@JerryCui You just updated the gradle version to 5.0+ so it is rising the conflict.
Try Changing the build.gradle version to **3.0.1** in  Build.gradle (Project) and update the **DistributionUrl** verion accordingly in the gradle wrapper properties.
Hope it helps. 👍

**Comment by pallavbohara** [comment]
Same problem. Posted question on SO 
https://stackoverflow.com/questions/61156986/react-native-android-studio-errorno-such-property-gradleversion-for-class-je
