### ISSUE TITLE
Several variant outputs are configured to use the same file name "resources-debug.ir.ap_", filters : FULL_SPLIT:FilterData{type=ABI, value=x86_64}:FilterData{type=ABI, value=x86}:FilterData{type=ABI, value=armeabi-v7a}:FilterData{type=ABI, value=arm64-v8a}

### ISSUE THREAD

**Issue by 1170762202** [shadowsocks/shadowsocks-android#2119]
android studio version:3.3.1

**Comment by TravelerLq** [comment]
app下的build.gradle里这个**    defaultConfig {
        splits {
            abi {
                enable true
                reset()
                include 'armeabi-v7a'//, 'armeabi', 'x86', 'x86_64', 'arm64-v8a'
                universalApk false
            }
        }
    }
把 'armeabi', 'x86', 'x86_64', 'arm64-v8a'加上“//“,这样就只生产一个apk file ,就不会有这种问题了

**Comment by saurabhzibal** [comment]
It worked on my device. Thanks!

**Comment by saurabhzibal** [comment]
It worked on Android Studio version 4.1.2 on macOS BigSur. Thanks!
