### ISSUE TITLE
最新版4.7.0 如何开启全局模式

### ISSUE THREAD

**Issue by Sunbvert** [shadowsocks/shadowsocks-android#2121]
如题，为什么越来越不好用了，找不到全局模式的入口，ins现在都上不去

**Comment by Alexkun** [comment]
以及新版的没看到“分应用代理”选项？
系统：EMUI 9.0 / Android 9
软件版本：4.7.0

**Comment by mokapsing** [comment]
编辑自己的配置，里面可以选
