### ISSUE TITLE
这条通道被封了 还有别的方法吗

### ISSUE THREAD

**Issue by fancker1992** [shadowsocks/shadowsocks-android#2122]
近期突然发现ss连接远程服务器失败  大部分vpn都被封了   还有别的办法吗

**Comment by Windelight** [comment]
自己动手丰衣足食，如果就是你自己的服务器，尝试换端口或者改加密协议吧

**Comment by zhaoxinjie** [comment]
是只有安卓被封了吗，我用浏览器可以用，但是安卓一直连不上，你们有相同的情况吗

**Comment by fancker1992** [comment]
浏览器是通过什么连接？    我win上的客户端也连不上了

**Comment by zhaoxinjie** [comment]
就是win上的客户端，然后用pac代理，浏览器用switchomega插件，只代理浏览器，不代理全局；
但是手机安卓客户端好像自从过年，就一直没法用了，不知道咋回事
