### ISSUE TITLE
可以使用电脑端fq，安卓端不可用

### ISSUE THREAD

**Issue by zhaoxinjie** [shadowsocks/shadowsocks-android#2124]
我的ss服务器，在电脑端可以使用，但是使用安卓一直连不上，有遇到类似问题的伙伴吗

**Comment by datianjiao** [comment]
今早我的也发现不能用了，电脑端能用

**Comment by Windelight** [comment]
如果是几千端口号用不了的话，那么调到五万六万可以，我之前的服务器端口几千也都有被限速问题

**Comment by Windelight** [comment]
(我还每天换)

**Comment by zhaoxinjie** [comment]
我觉得应该不是端口限速的问题，因为电脑端访问还是正常，只有安卓端不可以，会不会跟手机型号或者手机系统有关系

**Comment by Windelight** [comment]
我之前一直611端口用了很久突然有一天不行了，然后我就改一下ss每天加一个端口，从3306到3389，目前稳定的一狗

**Comment by zhaoxinjie** [comment]
好的，我试试，

**Comment by zhaoxinjie** [comment]
兄弟们我终于知道原因了。。。我的ssserver端口没开，因为用的kcptun，pc端可以连，但是手机端连不了，自己真是太笨了。。忘开端口了
