### ISSUE TITLE
4.7.1 版本无法使用基于 ACL 的路由规则（报错 后台服务启动失败：无法连接远程服务器：null）

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-android#2127]
**Describe the bug**
通过 Google Play 将 Shadowsocks 由 4.7.0 更新为 4.7.1（已参加 Beta Program），完成后打开应用连接节点失败，报错「后台服务启动失败：无法连接远程服务器：null」。
尝试更换远程 DNS、尝试域名和 IP 两种形式的服务器名、尝试更换路由方案。最终发现问题仅在使用自定义配置的路由时出现：更改为其他诸如「GFW 列表」、「绕过局域网与中国大陆」、「全局」，保持另外所有配置项不变，均可正常连接。
此问题已在两台不同的设备上复现，且均在重新安装 4.7.0 版本后恢复正常。
**关键词：ACL, DNS, 自定义路由规则, 解析异常, 连接失败**

**To Reproduce**
1. 自定义规则内添加 gfwlist 的 acl 规则（fullgfwlist provided by ACL4SSR project）
2. 创建连接配置，选择路由为「自定义规则」
3. 尝试连接，报错

**Expected behavior**
如之前版本般正常使用（由于 Shadowsocks-Android 许久未更新集成的 gfwlist，一直使用 acl 在线规则的方式使用较新的 gfwlist 路由）。

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 魔趣 Android 9.0 / 一加氢 Android 9.0
 - Device: 小米平板4 / 一加手机5
 - Version: 4.7.1
 - Last version that did not exhibit the issue: 4.7.0

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1.1.1.1
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
我只是普通用户，能力有限，还请开发者百忙之中关注此问题，感谢。

**Comment by Mygod** [comment]
It should be already fixed via https://github.com/shadowsocks/shadowsocks-android/commit/8c50461e1c6949791299551b4dbf719a6d1ae425.

**Comment by Mirr0ch1** [comment]
@Mygod thanks, may I ask when this patch will be submitted to the Play Store?

**Comment by Mygod** [comment]
You can build latest commit yourself or download debug apk from circle CI.

**Comment by whour** [comment]
I have the same problem when I update 4.7.1.
First clear the application data, and then I can start with a custom rule mode, but I can't connect to the service.
gfwlist mode can connect to the service.

**Comment by whour** [comment]
Great,Thanks.

**Comment by handleft** [comment]
原生系统 nexus5 也遇到这个问题

**Comment by liyu272173673** [comment]
同小米平板4, 请问问题解决了么?
