### ISSUE TITLE
Can I set "Local DNS" on v4.7.1 by my will?

### ISSUE THREAD

**Issue by santaclausbaby** [shadowsocks/shadowsocks-android#2131]
Android 8.0.0 with v4.7.1

1.What's the hardcoded DNS previously? 114 or Dnspod?
2.I can't change the DNS of mobile network for the non-ROOT devices. So if v4.7.1 read DNS form interface configration, I guess it is very non-friendly to privacy coz the Carrier owned DNS, like CU/CM, has making the DNS cache poisoning and DNS hijacking for a long time. I don't have Android 9.0 device so maybe the "private DNS" available but not on Android 8.0.
3.So May you add "Customize Local DNS" function for Android 8.0?

Thanks.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/v4.7.0/core/src/main/java/com/github/shadowsocks/bg/LocalDnsService.kt#L65-L67

I don't think you quite understand how DNS server in this app works. This app resolves every domain twice (once locally and once remotely) and picks the more appropriate response based on your route settings. This should already take care of DNS poisoning.

Private DNS is designed for privacy purposes. Custom local DNS does not solve the concern of privacy either. Either use a global route (which disable local resolving) or upgrade to Android 9.
