### ISSUE TITLE
4.7.1不能在mumu和电视盒子上正常运行，4.7.0无法正常导入配置文件

### ISSUE THREAD

**Issue by sumirecccp** [shadowsocks/shadowsocks-android#2133]
Please read contributing guidelines. Thanks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

实测4.7.1在mumu模拟器最新版和fire tv stick上不能正常运行，一连接就会提示“后台服务运行失败：无法连接到远程服务器 null”。

4.7.0可以在以上两平台正常运行，但无法从文件导入配置，文件图标显示为灰色

麻烦尽早修复了

**Comment by ankino17** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/2127#issuecomment-466115183
