### ISSUE TITLE
比较好奇，为啥4.7.1版本以后，Universal版本的安装包只有4.7.0之前的一半左右？

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-android#2134]
看了更新日志，没发现什么说明啊。

**Comment by Love4Taylor** [comment]
扔掉了 overture 的缘故吧

**Comment by DearTanker** [comment]
@Love4Taylor overture是个啥玩意。

**Comment by Love4Taylor** [comment]
> Overture is a DNS server/forwarder/dispatcher written in Go.

https://github.com/shawn1m/overture

**Comment by DearTanker** [comment]
> > Overture is a DNS server/forwarder/dispatcher written in Go.
> 
> https://github.com/shawn1m/overture

感谢，去掉这个估计没有什么影响吧。

**Comment by Love4Taylor** [comment]
什么影响? 功能性? Changelog 里已经写了 DNS 部分更新幅度很大. 体积的话一个 arm64 的 overture lib 就得 6M 了

![Screenshot_20190225-124340_Solid_Explorer.png](https://i.loli.net/2019/02/25/5c7372e6b422d.png)

**Comment by yuger** [comment]
@DearTanker @Love4Taylor 4.7.1确实是少了overture.so，为了追求更小的apk包，我又编译了新版本，然后经过众人测试，发现4.7.1版的速度总体不如以前编译的4.6.0版本，服务端线路是一样的，只会是客户端导致速度的差异，不确定是不是因为少了overturn.so的原因，你们怎么看？另外你们有没有类似问题？
