### ISSUE TITLE
DNS设置多个时，提示dns.host must not be null

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#2137]
Please read contributing guidelines. Thanks.

**Describe the bug**
点击连接时，提示后台服务启动失败：无法连接远程服务器：dns.host must not be null

**To Reproduce**
编辑一个配置文件，在“远程DNS”处填写“8.8.8.8，1.1.1.1”
保存，连接

**Expected behavior**
能正常连接

**Screenshots**

**Smartphone (please complete the following information):**

* Android 8.1
* Device: nexus 6p
* Version:  4.7.2
* Last version that did not exhibit the issue: 4.7.0

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ]  IPv6 server address
* [x]  Client IPv4 availability
* [ ]  Client IPv6 availability
* Encrypt method:
  aes-256-cfb
* Route
  
  * [x ]  All
  * [ ]  Bypass LAN
  * [ ]  Bypass China
  * [ ] Bypass LAN & China
  * [ ]  GFW List
  * [ ]  China List
  * [ ]  Custom rules
* [x ]  IPv6 route
* [x ] Apps VPN mode
  
  * [x ] Bypass mode
* Remote DNS: 8.8.8.8,1.1.1.1
* [ ]  DNS Forwarding
* Plugin configuration (if applicable):
* [x ]  Auto Connect
* [ ]  TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
It's expected.

No need to provide multiple remote DNS servers in the latest version.

**Comment by iamsad3508** [comment]
OKay~
