### ISSUE TITLE
三星国行 GMS 限制

### ISSUE THREAD

**Issue by CzBiX** [shadowsocks/shadowsocks-android#2138]
**Is your feature request related to a problem? Please describe.**
三星国行 ROM 中有一段叫 `com.android.server.GmsAlarmManager` 的代码（港行也有，但是通过开关禁用了），会检查 www.google.com 的连通性。在无法连接的情况下，会对 GMS 实施 3 个限制，包括只允许访问解析 `checkin.gstatic.com` 得到的 IP，推迟 alarm，限制 wakelock。可以在 adb shell 中执行 `dumpsys alarm` 输出的内容的尾部看到相关信息。

![image](https://user-images.githubusercontent.com/760097/53617643-0102e680-3c23-11e9-8386-9cf28e706d09.png)

因此，在使用分应用代理的情况下，如果没有勾选 Android System，将会导致 Google 全系软件无法正常使用。而 Per-app VPN 在系统底层是 iptables 按 uid 转向流量，所以如果使用 bypass 模式时，也可能在排除其他 app 时无意将 Android System 排除掉。

**Describe the solution you'd like**
在分应用代理的设置界面，显式显示 Android System，并按 uid 同步选择状态。

**Additional context**
我稍后附上 PR。

**Comment by bobbychan** [comment]
我的三星S9，谷歌商店和Youtube都无法联网了，Twitter都是可以正常访问，请问有办法解决吗？

**Comment by ayd13swb** [comment]
怪不得S24分应用代理了GMS和GSF，GOOGLE服务还是会连接失败。请问代理了安卓系统之后，除了这个Ping，还会有其他功能或者说流量通过这个安卓系统来走代理么，会不会影响其他不需要走代理的东西也走了代理？

另外，有别的办法比如host解决这个问题么？
