### ISSUE TITLE
2.6.2 G+ 客户端无法使用

### ISSUE THREAD

**Issue by neverzyw** [shadowsocks/shadowsocks-android#214]
最新版的2.6.2  开启了UDP转发
无论是VPN模式还是NAT模式 G+ 客户端都会报Can't load data. Check your connection.
这是为什么呢？

但是 如果我使用了hosts 例如imouto.host G+ 就会正常了 这是为什么呢？
PS： 我使用了hosts 在开启SS 国外的流量是按hosts上面的ip走SS 还是走本身的WIFI呢？

**Comment by madeye** [comment]
无法重现

**Comment by neverzyw** [comment]
ok 等下 我把视频录下来 发给你 你看下

**Comment by neverzyw** [comment]
sorry…… 我突然发现好像是adaway里面某一条有问题导致的……
