### ISSUE TITLE
Android client udp problem

### ISSUE THREAD

**Issue by NotRealMe** [shadowsocks/shadowsocks-android#2140]
**Describe the bug**
android client must get a correct udp reply to work.

**To Reproduce**
### case 1
1. A server which has 2 ip address
2. Server listening at 0.0.0.0
3. Set Android client connect it with second address list with command `ip a`
4. capture network package on server,
5. Server receive udp package, and will reply it use udp with first address
6. Android client can't functional, but Windows client can use second address to connect to server.

### case 2
1. Set a port forwarder to relay traffic between server and client
2. Set relay server's firewall to only accept tcp incoming package
3. Start Android client, capture package in server, 
4. No package received
5. Android client failed, but Windows client works fine.

**Expected behavior**
Android client can work without udp connection.

**Smartphone (please complete the following information):**
 - Android 6, 
 - Device: Honor 7
 - Version: android shadowsocks 4.6.5
 - Last version that did not exhibit the issue: not sure

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: xchacha20-ietf-poly1305
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 1.1.1.1
* [ ] DNS over UDP(not sure, but dns forwarding enabled)
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open

#### Extra
- udp relay are enabled on server side in both case.

**Comment by madeye** [comment]
Disable DNS forwarding.

**Comment by NotRealMe** [comment]
> Disable DNS forwarding.

Thanks, I thought it was forwarding DNS request over tcp....
