### ISSUE TITLE
怎么把这个软件添加到设置里面的vpn权限里面去

### ISSUE THREAD

**Issue by yuyistar** [shadowsocks/shadowsocks-android#2144]
我之前用一个别的软件，安装后自动添加到里面。但是这个软件不能自动添加。手动那个选项也不成功。现在没有权限运行ss。要怎么办。手机是三星s7
![_20190303201156](https://user-images.githubusercontent.com/14964575/53694978-a0290900-3df0-11e9-8205-e380cec5a1b8.jpg)

**Comment by Mygod** [comment]
Disable always-on VPN.
