### ISSUE TITLE
有成功clone源码的吗？

### ISSUE THREAD

**Issue by bangbing** [shadowsocks/shadowsocks-android#2148]
Execution failed for task ':plugin:dokka'.
> Guice provision errors:
  
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://developer.android.com/reference/, packageListUrl=https://developer.android.com/reference/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:28)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:28)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:13)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:13)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:12)
    while locating org.jetbrains.dokka.PackageDocs
——————————————————————————
好不容易把没clone到的jni文件补了一些，又提示这个错误，我在根gradle添加了classpath 'org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17'
又在plugin的gradle中加了apply plugin: 'org.jetbrains.dokka-android'还是没能解决

**Comment by OceanSnape** [comment]
请问能成功克隆了吗？

**Comment by OceanSnape** [comment]
> 任务'：plugin：dokka'的执行失败。
> 
> > Guice供应错误：
> 
> 1. 注入构造函数时出错，java.lang.RuntimeException：从ExternalDocumentationLinkImpl加载package-list时出现异常（url = [https://developer.android.com/reference/,packageListUrl](https://developer.android.com/reference/) = [https://developer.android.com/reference/package-列表](https://developer.android.com/reference/package-list)）
>    org.jetbrains.dokka.ExternalDocumentationLinkResolver。（ExternalDocumentationLinkResolver.kt：28）
>    org.jetbrains.dokka.ExternalDocumentationLinkResolver.class（ExternalDocumentationLinkResolver.kt：28），
>    同时
>    在org中找到参数4的org.jetbrains.dokka.ExternalDocumentationLinkResolver 。 jetbrains.dokka.DeclarationLinkResolver。（DeclarationLinkResolver.kt：13）
>    在定位org.jetbrains.dokka.DeclarationLinkResolver时
>    对于org.jetbrains.dokka.PackageDocs。（PackageDocs.kt：13）
>    中的参数0，org.jetbrains.dokka.PackageDocs.class （PackageDocs.kt：12），
>    同时找到org.jetbrains.dokka.PackageDocs 
>    ----- --------------------- 
>    好不容易把没克隆到的jni文件补了一些，又提示这个错误，我在根gradle添加了classpath'org.jetbrains .dokka：dokka-android-gradle-plugin：0.9.17' 
>    又在插件的gradle中加了apply plugin：'org.jetbrains.dokka-android'还是没能解决

Can you clone successfully?
