### ISSUE TITLE
Why there are so many releases?

### ISSUE THREAD

**Issue by liuweilhy** [shadowsocks/shadowsocks-android#2149]
Please use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead. Your issue will probably be closed.
I don't know why the developer show so many releases. Do you think every user know which one he should download?

**Comment by liuweilhy** [comment]
shadowsocks--universal-4.7.2.apk
5.32 MB
shadowsocks-arm64-v8a-4.7.2.apk
4.54 MB
shadowsocks-armeabi-v7a-4.7.2.apk
4.5 MB
shadowsocks-tv--universal-4.7.2.apk
4.17 MB
shadowsocks-tv-arm64-v8a-4.7.2.apk
3.38 MB
shadowsocks-tv-armeabi-v7a-4.7.2.apk
3.35 MB
shadowsocks-tv-x86-4.7.2.apk
3.39 MB
shadowsocks-tv-x86_64-4.7.2.apk
3.4 MB
shadowsocks-x86-4.7.2.apk
4.54 MB
shadowsocks-x86_64-4.7.2.apk
Who can tell me which one is suited for me?

**Comment by Villardhzq** [comment]
according to your device, most of phones released after 2015 or 2016 supports arm64. if you don't know, choose universal one
