### ISSUE TITLE
notification icon disappears sometimes

### ISSUE THREAD

**Issue by ericjding** [shadowsocks/shadowsocks-android#215]
I'm using shadowsocks 2.6.2 on AOSP 4.4.2 (KTU84P) in rooted (NAT) mode.  Since the last time I updated shadowsocks, I've noticed that the notification icon sometimes is not visible -- if I pull down the notification drawer, then it still appears that shadowsocks is running, but the icon isn't visible in the status bar when I close the drawer.  Eventually, the icon becomes visible again in the status bar for no obvious reason, and then it can disappear again for no obvious reason.

My suspicion is that this change in behavior is somehow related to commit dec098fbc5e9bf864e4bc85fdf44ac51f5c64884, but I am not familiar with enough with Android's API to guess whether (1) this is intentional behavior, or (2) how to fix this issue if it's not intended. 

Please fix if it's unintentional behavior, or document/explain it if it is intentional. :-) Thanks!

**Comment by madeye** [comment]
It's a feature, not a bug

**Comment by ericjding** [comment]
Wow, that was fast. Thanks. Can you explain in what situations the notification icon disappears and when it is visible? In the past, it was a nice, quick way for me to see when Shadowsocks was running and when it was not. That doesn't appear to be an option anymore.

**Comment by ericjding** [comment]
After looking at #166 and reading over the most recent version of ShadowsocksNatService.scala, I'm still confused. It looks like the intended behavior is that the notification should be hidden when the screen is turned off, and then made visible again when the device is unlocked from the lock screen or if the screen is turned on with no lock screen. Is this correct, or am I misreading the code?

If I am correct, then the program is not working on my device -- the notification icon doesn't always turn on after unlock.

If I am incorrect, then when is the icon actually supposed to be visible (if ever)? When is it supposed to be invisible (other than on the lock screen)?
