### ISSUE TITLE
批量修改配置内容。

### ISSUE THREAD

**Issue by gongjianhui** [shadowsocks/shadowsocks-android#2153]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
一次性导入多个代理服务器时（如 20+ 个），需要逐个修改路由 (Route) 为「绕过局域网及中国大陆地址」(Bypass LAN & China)，浪费时间和精力。

**Describe the solution you'd like**
三种可能的解决方案：
1. 允许批量修改「路由」等设置项。
2. 将配置文件中的「路由」设置项移至 App 的「设置选项」(Settings) 中，避免逐个修改配置。
3. 修订 SIP002，在 QR 中添加「路由」设置参数（会出现兼容性问题）

**Additional context**
我认可「全局」路由较其它路由安全性更高，但这与很多 Shadowsocks Android 用户的需求不符。

**Comment by Mygod** [comment]
Use v4.7.2+.
