### ISSUE TITLE
关于服务器hosts的解析

### ISSUE THREAD

**Issue by roadwide** [shadowsocks/shadowsocks-android#2154]
我在部署ss的服务器上设置了hosts以保证我访问某些域名时能访问特定的ip，在windows上的ss客户端代理能用服务器的hosts(在我的windows上没有设置hosts，但还是通过服务器访问到了期望的ip)。但手机上的ss客户端却无法使用服务器的hosts解析。使用远程dns解析也是公共的dns服务器，没法解析到我想要的ip地址。请问有什么办法吗？不知道我的问题和这个是不是一样https://github.com/shadowsocks/shadowsocks-android/issues/2150
我在更改了手机的hosts后也能访问到正确的ip

**Comment by madeye** [comment]
Please follow the template and post your detailed settings here.

**Comment by Mygod** [comment]
Use global routes.

**Comment by roadwide** [comment]
> Use global routes.

没有用。我是想访问谷歌学术，但是ipv4地址被谷歌封掉了，只能用ipv6访问。但是谷歌学术没有解析到ipv6的地址，也没有dns能将它解析到ipv6，只有改hosts才能访问ipv6地址。

服务器设置hosts到ipv6的谷歌学术地址，服务器能访问谷歌学术，电脑使用代理也能访问 ，手机使用ss代理不能访问。
手机更改本地的hosts再使用ss代理后能访问谷歌学术。

手机设置全局代理也不会使用服务器端设置好的hosts
