### ISSUE TITLE
parseNumericAddress no longer usable in Android Q

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2155]
```
Accessing hidden method Ljava/net/InetAddress;->parseNumericAddress(Ljava/lang/String;)Ljava/net/InetAddress; (greylist-max-p,core-platform-api, reflection)
```

See also:

* https://github.com/shadowsocks/shadowsocks-android/commit/cabe12e8be1d91cebffc940dff27c3b58763e988
* https://issuetracker.google.com/issues/123456213

This method is forbidden only if target API is Q+.

**Comment by madeye** [comment]
What about InetAddress.getByName?

**Comment by Mygod** [comment]
Hmm good point!

**Comment by ayanamist** [comment]
我在支持hosts实现了一个，要不我先推上来吧

**Comment by Mygod** [comment]
Never mind. There is actually a new API: https://developer.android.com/reference/android/net/InetAddresses.html#parseNumericAddress(java.lang.String)
