### ISSUE TITLE
加了一层Cloudflare CDN，DNS就不能解析

### ISSUE THREAD

**Issue by wowpaladin111** [shadowsocks/shadowsocks-android#2158]
服务器（libev版本）
"method":"chacha20-ietf-poly1305",
"fast_open":true,
"nameserver":"8.8.8.8",
"mode":"tcp_and_udp",
"plugin":"obfs-server",
"plugin_opts":"obfs=http"

客户端：v4.7.3
无论如何设置（路由、远程DNS、DNS转发），都不能解析任何域名

同一局域网内，用windows版客户端，工作正常。

谢谢！

**Comment by smilinger** [comment]
新版本确实有问题，我使用v2ray-plugin tls模式，总是过一会就断流，怀疑是dns无法解析，有时候会提示无法解析www.google.com的域名。装回4.6.5版本一切正常。

**Comment by smilinger** [comment]
改回4.7.3了，用4.6.5也有同样的问题。好像v2ray-plugin+tls很容易被检测识别，用几分钟就被封，换ip也撑不了多久，用http反而没事，不知道什么鬼。

**Comment by xhqpp** [comment]
> 改回4.7.3了，用4.6.5也有同样的问题。好像v2ray-plugin+tls很容易被检测识别，用几分钟就被封，换ip也撑不了多久，用http反而没事，不知道什么鬼。

你这是被墙了 干扰你

**Comment by wowpaladin111** [comment]
是UDP的原因吗？按说不把DNS请求转发到远端，就应该在本地域名解析了吧？连国内的域名都解析不了。

**Comment by smilinger** [comment]
好像又不是dns的原因，可能是cloudflare的某些ip段都被封了，我昨天把IP换了一个ip段，暂时没发现问题。

**Comment by wowpaladin111** [comment]
> 
> 
> 好像又不是dns的原因，可能是cloudflare的某些ip段都被封了，我昨天把IP换了一个ip段，暂时没发现问题。

不不不，同一个wifi lan下的windows PC一点问题都没有。

**Comment by williamxxy** [comment]
Cloudflare现在的ip被墙得很严重，要想DNS最好使用secure certificate

**Comment by ednew2018** [comment]
我可能也是这个问题，我在墙外。加上cloudflare就无法解析，过了六分钟又可以解析了。如果用http就可以解析，但是https无法解析。去掉cloudflare，就都正常解析。

**Comment by forever8938** [comment]
> 好像又不是dns的原因，可能是cloudflare的某些ip段都被封了，我昨天把IP换了一个ip段，暂时没发现问题。

cloudflare的CDN怎么换IP段？

**Comment by wowpaladin111** [comment]
同一局域网内，用windows版客户端，工作正常。所以不是封IP的问题。
