### ISSUE TITLE
Start on boot is not working

### ISSUE THREAD

**Issue by yanggis** [shadowsocks/shadowsocks-android#2159]
Please read contributing guidelines. Thanks.

**Describe the bug**
On Android P, we make "start on boot" checked, then restart my phone, after rebooting, the vpn service not start automatically.
Another issue, the acl file cannot sync after I modify my online acl file. I remember, some months ago, the feature worked fine. after  the version of 4.7.1, the feature didn't work any more.

**To Reproduce**
1. Go to 'global setting'
2. Click on 'start on boot'
3. reboot the phone
4. the vpn service did not run automatically. 

**Expected behavior**
 Start vpn on boot;
acl synchronization work again;

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android P
 - Device: [Oneplus 5T]
 - Version: [N/A]
 - Last version that did not exhibit the issue: [shadowsocks 4.6.5]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Update to latest release 4.7.3.

**Comment by yanggis** [comment]
@Mygod Have you tested the issues on the version of 4.7.3? I just compiled the app with your mentioned version, the issues are persistent. Please check again.

**Comment by yanggis** [comment]
here the error: WM-WorkerWrapper: Worker result RETRY for Work [ id=fb7be0eb-3dab-4566-bdfe-3aa063442179

**Comment by Mygod** [comment]
We are not responsible for your changes.
