### ISSUE TITLE
Feature request: keep notification icon visible always

### ISSUE THREAD

**Issue by ericjding** [shadowsocks/shadowsocks-android#216]
I hope this isn't a misuse of the issues tracking system. I just reported #215, which @madeye closed immediately and said was an intended feature, not a bug. But I actually would like to request:

1) an explanation for when this icon is visible and when it's invisible by default, and
2) an additional feature: can we have an option for this icon to be consistently visible so that's it's easy to see at a glance whether shadowsocks is running?

Thanks!

**Comment by madeye** [comment]
Sorry, no plan for this.

**Comment by madeye** [comment]
See #166 for more details.
