### ISSUE TITLE
Connection Issue with Netflix on Android TV

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-android#2163]
Very poor connection while using Netflix on Android TV.

**What I oberved:**
Netflix in-app speedtest was cool (average 44 Mbps), but when I tried to play a video, it was extremely unusable. Videos took minutes to load with very low video quality.

I submit this issue beacuse YouTube for android TY was completely fine, the video qualities were great and loaded fast.

**Other Comments:**
I don't believe it's a server issue, other devices like PC iPhone are working fine.

The device is not at-hand, it servers my parents way back home, some info can be hard to provide. If you guys need the device to test, I can ask them to mail out.

The server can use Netflix with no problem. It's in my relative's house in Hongkong. If you need my server to test, please let me know.

**Device Info:**
 - Android TV version: Latest (to be determined)
 - Device: MI BOX (not the "s" version)
 - Shadowsocks for Android TV Version: 4.7.2
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open

**Comment by Mygod** [comment]
Netflix is known for screwing users over with poor quality. Usually the quality problem would go away after a few minutes. I'm not sure why it's doing this.

**Comment by RebelliousWhiz** [comment]
Thank you for replying Mygod.

I think Netflix wishes you to have a quicker start with video by lowering video quality in the beginning, I can observe this behavier in many platforms (Browser, xBox, iPhone). But that wasn't the problem.

What I experienced was a NOTICIABLE OVER-ALL POOR QUALITY. Plus, it stopped the video sometimes to load, and the load speed was VERY SLOW.
