### ISSUE TITLE
Using dnscrypt-proxy instead of NeatDNS

### ISSUE THREAD

**Issue by tony1016** [shadowsocks/shadowsocks-android#2167]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
YES.If all the backend dns is poisoned,how can we connect to the world??

**Describe the solution you'd like**
I want a dns with encrypted

**Describe alternatives you've considered**
The dnscrypt-proxy project is the best way to do that.Even,these is a project [dnscrypt-proxy-config](https://github.com/CNMan/dnscrypt-proxy-config) using the **forwarded** feather to accelerate the dns in China

**Comment by Mygod** [comment]
Wrong repo.

**Comment by tony1016** [comment]
> Wrong repo.

why close it??
