### ISSUE TITLE
Problem in Huawei System (connected but no data) / 华为手机的问题 (连接但无数据)

### ISSUE THREAD

**Issue by Michael-Xiu** [shadowsocks/shadowsocks-android#2169]
**Describe the bug**
New Huawei phone or systems encounter the problem that although shadowsocks is opened and VPN is connected, even if the function of testing latency is sound, when change to other apps such as Youtube, Instagram, Google play store, there is only a short period of time, about 1 to 2 seconds, that data flow exists. Problem: Huawei kills the shadowsocks process behind in order to save battery.
新华为手机和系统会遇到这样的问题：尽管shadowsocks和VPN已经开启，测试延迟功能也没有问题，但当把shadowsocks放到后台切换到其他应用时(Youtube, Instagram, Google play store)，只存在1到2秒正常的工作时间，之后将没有数据传输。问题：华为后台杀掉了应用进程为了省电

**Solution**
Setting- APP setting - shadowsocks - Power usage details - turn on all the manual settings
![1](https://user-images.githubusercontent.com/35869384/54804382-2e850200-4cae-11e9-8102-d680a9ccb40a.jpg)
![2](https://user-images.githubusercontent.com/35869384/54804386-304ec580-4cae-11e9-9e13-03ab3e870bca.jpg)

**解决方法**
设置 - 应用 - 找到shadowsocks - 耗电详情 - 打开所有手动管理
![4](https://user-images.githubusercontent.com/35869384/54804426-55433880-4cae-11e9-8ed8-d541776a78b7.jpg)
![3](https://user-images.githubusercontent.com/35869384/54804429-583e2900-4cae-11e9-9c78-a0cb6a3a586a.jpg)

**Comment by luo-chuan** [comment]
如果系统是EMUI 10的话。设置—更多连接—加密DNS—默认关闭，勾选自动。就可以用了。
参考： https://club.huawei.com/thread-21446964-1-1.html
