### ISSUE TITLE
MeiZu MX6 , can not open in chrome when connecting

### ISSUE THREAD

**Issue by narutojxl** [shadowsocks/shadowsocks-android#2170]
Installed  ss_android  version is 4.3.3,  android version is 7.1.1,  system version is Flyme 7.2.0.1A. Connecting WIFI, When launching ss_android it can connect my server, but loss some bags,  and the result is 

>Unable to resolve host "www.google.com":No address associated with hostname. 

 here is the result picture [link is here](https://www.dropbox.com/s/bhevrah1ypyfs2q/No%20address%20associted%20with%20hostname.jpg?dl=0) and [ss_android_config](https://www.dropbox.com/s/2wwgjk1uoihc3zu/ss_android_config.jpg?dl=0).  My phone is not root, and when i tried ss_android version >=4.4.2,  when runing ss_android it let me load config file, but i have already loaded.  I have given ss_android all right. And i have tried the same things on HUAWEI Honor V9(Android 7.0, EMUI version 5.1, not root), also outputs `Unable to resolve host "www.google.com":No address associated with hostname. `,   what something i missed, thank you very much!
PS: On desktop PC(windows and linux), i can use ss client to normally open www.google.com.

**Comment by Mygod** [comment]
Update to latest version.

**Comment by narutojxl** [comment]
when removed ss_android version is 4.3.3,  intsall lasted version, such as  v4.7.3, it always let me load config file, which i already have loaded. In fact,  i tried eighteen versions, from v4.4.2 to v4.7.3, they all let me load config file, Honor V9 also did the same.
