### ISSUE TITLE
设备不支持Google Play服务，无法运行

### ISSUE THREAD

**Issue by alin0906** [shadowsocks/shadowsocks-android#2171]
设备不支持Google Play服务，无法运行。我记得以前没有这个问题的，有人知道原因吗？是谷歌特别要求的，还是因为什么原因有意加的？

**Comment by sveinjoe** [comment]
不要使用扫码功能，手动设置完美解决这个问题

**Comment by williamxxy** [comment]
安卓需要破解了才能用，破解后安装补丁
