### ISSUE TITLE
分应用代理VPN无法连接google play

### ISSUE THREAD

**Issue by h254234211** [shadowsocks/shadowsocks-android#2172]
设备是三星s10+，当分应用代理VPN时无法连接google play，无论是否开启绕行模式都不行，也没有选择不代理google play

**Comment by NeowuqiLee** [comment]
同样遇到，知道怎么设置么，求截图

**Comment by whour** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-is-my-rom-not-supported

Samsung with GMS: #2138
