### ISSUE TITLE
 Shadowsocks service killed by system in android 7 and higher version

### ISSUE THREAD

**Issue by luckymanreal** [shadowsocks/shadowsocks-android#2174]
**Smartphone (please complete the following information):**
 - Android version: 7.0, 8.1
 - Device: TECNO
Shadowsocks version: 4.7.2

**Configuration**

* [ *] IPv4 server address
* [ ] IPv6 server address
* [* ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-128-gcm
* Route
  * [ *] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [* ] Auto Connect
* [ *] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

I have found a bug in using shadowsocks android app.
I am sure that this is not related to shadowsocks setting.
When I run the app in android 7 and higer version, I realized that vpn service was killed in doze mode.
So vpn service is stopped 10-15 minutes after I lock phone screen off.
But other vpn apps(not using shadowsocks library) still kept alive.
I want to know why this happens.
I think vpn should work in doze mode.

**Comment by Mygod** [comment]
https://dontkillmyapp.com/
