### ISSUE TITLE
分应用VPN无法访问google

### ISSUE THREAD

**Issue by h254234211** [shadowsocks/shadowsocks-android#2175]
**Describe the bug**
开启分应用VPN模式时无法连接google类应用（google play和地图等），分应用VPN绕行模式只选择国内应用也不行，其他应用都可以正常使用。关闭分应用VPN模式就可以连接。
使用了以下组合都不能正常访问：
1. 全局代理+分应用VPN
2. 全局代理+分应用VPN(绕行模式)
3. 绕过局域网和中国+分应用VPN
4. 绕过局域网和中国+分应用VPN(绕行模式)

**To Reproduce**
1. 开启分应用VPN模式
2. 访问google play下载应用
3. 无法加载
4. 关闭分应用VPN，可以下载

**Expected behavior**
可以使用分应用VPN模式

**Smartphone (please complete the following information):**
 - Android P
 - Device: Samsung s10+
 - Last version that did not exhibit the issue: Oneplus5(Oos)+shadowsocks4.7.0

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by williamxxy** [comment]
大概是因为谷歌框架在中国被阉割的缘故，root之后安装，全套市场就好了
