### ISSUE TITLE
Profile disappears from UDP fallback list

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/shadowsocks-android#2178]
**Describe the bug**

Once a plugin (in my case, v2ray-plugin) has been enabled for a profile, that particular profile can no longer be selected as a UDP fallback profile. It does not even show up in the list. Even if you disable plugin for that profile, it will not show up again. 

**To Reproduce**

Just create a new profile without editing anything, it shows up in other profiles' UDP fallback list. Once you've enabled a plugin for the new profile, it disappears from other profiles' UDP fallback list.

**Smartphone (please complete the following information):**

One plus 5T with Android P. APP version 4.7.3

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

I'm not sure if it is intentional.

**Comment by Mygod** [comment]
Indeed. Thanks for reporting.
