### ISSUE TITLE
Is the release version built with the latest libs?

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-android#2179]
The third-parties libraries are not linked to the latest code, on page https://github.com/shadowsocks/shadowsocks-android/tree/master/core/src/main/jni

e.g. mbedtls is 2017's, https://github.com/ARMmbed/mbedtls/tree/4f0929189ab43e020b0d441919abf6bab02baf11

Is the release binaries built with the old code?

**Comment by Mygod** [comment]
Contributions are welcome.

**Comment by yzou** [comment]
I'm thinking it has some reason to use old libs, for stable for example. I'm working on some improvements in c libraries.
