### ISSUE TITLE
Add availability to manually set local bypass IPs

### ISSUE THREAD

**Issue by LukeXuan** [shadowsocks/shadowsocks-android#218]
Since I'm in a campus environment, local IPs doesn't necessarily mean they are in the same network segment as mine, for example: 
```
    192.255.240.0/24
    192.255.255.0/24
```
Both are IPs in local network, while the IP address given to me is `172.19.247.151`.

As a result, I've to switch off the shadowsocks when I have to visit local websites in browser such as chrome.

So I'd like to know if there is any possibility to enable me to manually set bypass IPs?

**Comment by madeye** [comment]
Sorry, no plan for this.
