### ISSUE TITLE
DNS failed to forward after network switch

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-android#2180]
**Describe the bug**
DNS packet is not forward to configured DNS server after network switch.

**To Reproduce**
1. Connetc a server under wifi or mobile data/4G
2. Switch network to mobile data/4G or wifi
3. Some site maybe failed to resolve and open such as Twitter, baidu.com
4. On ss-server, we can see DNS packet sent to new Network's DNS server such as 192.168.1.1 or China Mobile's 221.179.155.193
5. You can switch to different wifi with different DNS config, and see DNS packets sent to the new network's DNS server on ss-server

**Expected behavior**
DNS packets should be forwarded to my configured DNS server 8.8.8.8

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: EMUI 9.0.0, Android 9
 - Device: Huawei P20 Pro
 - Version: shadowsocks v4.7.3
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP, this option doesn't matter
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Switch to wifi from 4G network
![image](https://user-images.githubusercontent.com/1464693/55157772-38b86c00-5198-11e9-8f66-06ef5ea75455.png)

Switch back to 4G from wifi
![image](https://user-images.githubusercontent.com/1464693/55157824-5ab1ee80-5198-11e9-8540-b2d3b9697a44.png)

wlan0 interface's dns:
![image](https://user-images.githubusercontent.com/1464693/55157874-7ddc9e00-5198-11e9-909a-edf50d640665.png)

tun0's dns:
![image](https://user-images.githubusercontent.com/1464693/55157899-9056d780-5198-11e9-908c-21b3e41e8492.png)

rmnet0's dns:
![image](https://user-images.githubusercontent.com/1464693/55157918-9baa0300-5198-11e9-952c-4749f3a48341.png)

**Comment by Mygod** [comment]
Welp. This is definitely a vendor bug. I don't think other VPN will work properly on your phone either.

**Comment by yzou** [comment]
I'll test on nexus again.

**Comment by madeye** [comment]
Could you confirm that VoIP is enabled?

**Comment by madeye** [comment]
I cannot reproduce this problem with EMUI 9.0 onChina Union network.

Since only CMNET has this issue, I guess it maybe related to VoIP. 

So please help to confirm if VoIP enabled. If enabled, please disable it and try again.

**Comment by yzou** [comment]
Yes, the VoLTE is enabled, I have both China Mobile and China Unicom card on my Phone.

**Comment by Mygod** [comment]
@madeye I think #2143 and #2180 are two different issues. #2143 does not involve network switch.

**Comment by madeye** [comment]
@Mygod Okay.

@yzou could you confirm that if not switching the network, your connection is still fine?

If so, please try to enable autostart mode for shadowsocks in EMUI.

**Comment by yzou** [comment]
I also encountered this issue without a network switch.

If mobile data using my second China Unicom sim card, I didn't see this issue, the HD voice is on the first China Mobile sim card.

**Comment by yzou** [comment]
VoLTE HD calls is enable on SIM 1, China Mobile

**Comment by Mygod** [comment]
Please also supply: steps to reproduce without network switch, expected and actual results, over at #2143.

**Comment by yzou** [comment]
Switch mobile data from SIM 2 to SIM 1, the DNS is sending to China Mobile's DNS server again.
![image](https://user-images.githubusercontent.com/1464693/55225039-b2aa2d00-524c-11e9-982e-e054a86829c7.png)

**Comment by madeye** [comment]
Please confirm this issue already fixed in the latest release.

**Comment by yzou** [comment]
This issue is fixed in 4.7.4.

**Comment by wxysystem32** [comment]
i have same issue. i download the ver.4.7.4, but it not working...

**Comment by shiliushao** [comment]
i download the ver.4.7.4, but it not working too
