### ISSUE TITLE
夜间主题下高级设置选项的图标颜色问题

### ISSUE THREAD

**Issue by onlymash** [shadowsocks/shadowsocks-android#2182]
RT
![IMG_20190330_173836](https://user-images.githubusercontent.com/5838634/55274411-ed769880-5312-11e9-966d-15ace6f32bdd.jpg)

**Comment by Mygod** [comment]
This is an upstream bug. Contributions are welcome.

**Comment by williamxxy** [comment]
？？？？这个是因为没有root权限，只需要root就行

**Comment by Mygod** [comment]
This is fixed in preference lib 1.1.0-alpha05.
