### ISSUE TITLE
Shadowsocks 4.7.3 cannot connect

### ISSUE THREAD

**Issue by AntonKosov** [shadowsocks/shadowsocks-android#2184]
When the app was updated from Google Play Store a few days ago, it stopped work. Testing of a connection writes "Internet Unavailable" after a while. All applications that are in bypass mode had access to the Internet. I tried to reinstall the app, but it didn't help. Version 4.6.5, which I installed from GitHub, works perfectly (I transferred all settings through a JSON file).

Here are some details:
 - Android version: 9
 - Device: Xiaomi Mi A1
 - Version: 4.7.3
 - Last version that did not exhibit the issue: 4.7.0

Configuration:

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-CFB
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

**Comment by madeye** [comment]
Can you visit 1.1.1.1 when connected?

**Comment by AntonKosov** [comment]
4.6.5: everything works perfectly.
4.7.0: everything works perfectly.
4.7.1: `1.1.1.1` works, but others don't (`google.com`, for example).
4.7.3: `1.1.1.1` works, but others don't (`google.com`, for example).

**Comment by Mygod** [comment]
Grab a logcat.

**Comment by AntonKosov** [comment]
1. Installed 4.7.3
1. Imported my settings.
1. Ran `logcat`.
1. Pressed the connect button.
1. Pressed the test panel.

[shadowsocks.txt](https://github.com/shadowsocks/shadowsocks-android/files/3051256/shadowsocks.txt)

**Comment by madeye** [comment]
Can you try this APK: https://www.dropbox.com/s/xdjv1j4sj42sgtz/shadowsocks-nightly-19-04-07.apk?

**Comment by AntonKosov** [comment]
This version works!

**Comment by madeye** [comment]
Thanks!

So, it's the same problem found here: https://github.com/shadowsocks/shadowsocks-android/issues/2143#issuecomment-477233065

It looks it's possible that system will ignore the VPN interface's default DNS.

It's still not clear that why we cannot reproduce it on same MIUI and EMUI system.

**Comment by AntonKosov** [comment]
I've got Xiaomi Mi A1 Global Version (Android One)

**Comment by madeye** [comment]
@Mygod let's revert that commit for now. Otherwise, many users would be affected.

We can keep investing this issue further, until the root cause is found.

**Comment by AntonKosov** [comment]
Thanks! Let me know if you need to test the bugfix on my device.

**Comment by madeye** [comment]
Looks duplicate to #2143.

**Comment by Mygod** [comment]
@madeye Can you reproduce this issue?

**Comment by madeye** [comment]
Nope, I can't.

**Comment by Mygod** [comment]
I would still argue that this hack/workaround would break non-DNS traffic through port 53 (e.g. QUIC on UDP 53). I think their ROM is fundamentally broken for VPN.

**Comment by madeye** [comment]
A better way is identifying DNS packet in tun2socks.

Let me try it later.

**Comment by ProfessorX** [comment]
Same issue found on Oneplus 3t 

system version A3010_28_190527

**Comment by ProfessorX** [comment]
[https://i.imgur.com/QfhE6lu.jpg](url)

[https://i.imgur.com/3fMHAPq.jpg](url)


Forgive me for being lazy.

**Comment by ProfessorX** [comment]
@madeye 

I have updated some screenshots. If you need the complete log let me know. 

Glad to help with 4.7.1 test.
