### ISSUE TITLE
4.7.4新版本udp转发问题

### ISSUE THREAD

**Issue by bobohuang1985** [shadowsocks/shadowsocks-android#2186]
我发现一个很神奇的问题。
默认情况下，使用line无法进行语音通话，但是udp转发不是默认开启的吗？
然后UDP配置里面随便选一个配置，即使是一个假的ip，设置完后，line竟然能通话了。
这个是否是一个bug？还是其中有什么处理逻辑？
谢谢

**Comment by yzou** [comment]
我的没有你说的问题呢
