### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by ChangedenCZD** [shadowsocks/shadowsocks-android#2188]
Build command failed.
Error while executing process D:\Android\sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\Project\Changeden\Android\shadowsocks-android\core\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\Project\Changeden\Android\shadowsocks-android\core\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:/Project/Changeden/Android/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib\armeabi-v7a" >NUL 2>NUL || rem
D:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdbserver"
copy /b/y "D:\Android\sdk\ndk-bundle\build\\..\prebuilt\android-arm\gdbserver\gdbserver" "E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib\armeabi-v7a\gdbserver" > NUL
D:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbsetup       ": "E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup"
D:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path E:/Project/Changeden/Android/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a" > E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup
D:/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory D:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/mbedtls/include E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/pcre/dist D:/Android/sdk/ndk-bundle/build//../sources/cxx-stl/system E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/libancillary E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/badvpn/lwip/src/include/ipv4 E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/badvpn/lwip/src/include/ipv6 E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/badvpn/lwip/custom" >> E:\Project\Changeden\Android\shadowsocks-android\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup

process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `E:/Project/Changeden/Android/shadowsocks-android/core/src/main/jni/redsocks/base.c', needed by `E:/Project/Changeden/Android/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/redsocks/redsocks/base.o'.  Stop.

**Comment by ICLXL** [comment]
我也遇到这种情况了(I also encountered this situation.)

**Comment by lisongting** [comment]
I also encountered this situation.

**Comment by lisongting** [comment]
@ChangedenCZD 大兄弟你是怎样解决的

**Comment by ChangedenCZD** [comment]
```
Clone the repo using git clone --recurse-submodules <repo> or update submodules using git submodule update --init --recursive
```

clone 后再 update，有些依赖没有clone到造成的

**Comment by cyq7on** [comment]
如果还没解决，可以用我clone好的这个https://github.com/cyq7on/shadowsocks-android-patch

**Comment by moz1q1** [comment]
??

**Comment by cs8** [comment]
clone的时候没有选递归子模块

**Comment by cs8** [comment]
clone的时候要递归子模块，不然库引不进来

**Comment by yefangqingchen** [comment]
这个问题弄好了吗，我也是这个问题。
