### ISSUE TITLE
启用“UDP DNS”后国内流量不走远程DNS

### ISSUE THREAD

**Issue by JhonHuGit** [shadowsocks/shadowsocks-android#2189]
Please read contributing guidelines. Thanks.

**Describe the bug**
我设置了一个自己的用于去广告的DNS服务器，shadowsocks 4.7.1及其之后版本，在“绕过局域网及中国大陆地址”并启用“使用UDP DNS”后，国内网站不能去广告，国外网站没问题，且可以正常访问Google。并且在使用全局路由之后均可达到去广告的目的。另外4.7.1之前版本不存在此问题。我认为问题出在即使设置了远程DNS，在“绕过局域网及中国大陆地址”模式下解析国内网站的时候仍然使用了本地DNS而不是设置的远程DNS，请问这是个feature还是个bug？

**To Reproduce**
1. 设置绕过局域网及中国大陆地址模式
2. 设置远程DNS，启用UDP DNS
3. chrome浏览器访问国内网站不能达到预期目的

**Expected behavior**
设置远程DNS后，所有流量均使用远程DNS解析

**Screenshots**
绕过局域网及中国大陆地址
![1](https://user-images.githubusercontent.com/44264634/56332789-563f8b00-61c4-11e9-8632-948ce149fbe8.jpg)

![2](https://user-images.githubusercontent.com/44264634/56332797-5b043f00-61c4-11e9-90b3-d4801dfaa61c.jpg)

全局
![3](https://user-images.githubusercontent.com/44264634/56332835-78d1a400-61c4-11e9-8a08-c323f8ccc1e4.jpg)

![4](https://user-images.githubusercontent.com/44264634/56332843-7bcc9480-61c4-11e9-85c0-6db8c6536683.jpg)

**Smartphone (please complete the following information):**
 - Android version: 8.1.0
 - Device: samsung note 9
 - Version: shadowsocks 4.7.1及以上
 - Last version that did not exhibit the issue: shadowsocks 4.7.0

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 自己设置
* [x ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
It's expected. In the latest release, unless you route all traffic to the remote, local DNS queries won't use remote results any more.

On Android 9.0, you can use private DNS to forward your local DNS queries to a AD block DNS server.

**Comment by JhonHuGit** [comment]
I am using android 8, is there another solution? I do not want to route all traffic because I cannot open intranet websites and it can also cause problems with domestic websites.
Maybe like you said before, we can have a function called "Global dns"?

**Comment by Mygod** [comment]
Your proposed functionality is problematic. Use hosts functionality in #2162.
