### ISSUE TITLE
the apk files do not install on Android 4.2.2

### ISSUE THREAD

**Issue by LeoK987** [shadowsocks/shadowsocks-android#219]
downloaded and copied them to my Android device.  From file manager, I opened the apk file, then the normal Android install confirmation window popped up.  At the bottom of the window, there are two choices: Cancel or Install.  Selecting Install causes nothing to happen, as if the button is disabled.  I could only select Cancel. 

Wonder what is wrong.

**Comment by madeye** [comment]
Turn on Airplane mode and try again.

**Comment by LeoK987** [comment]
I tried with Airplane mode both on and off.  Same.  BTW, this is my first time trying to install shadowsocks

**Comment by madeye** [comment]
Two possible reasons:
1. Some apps on your device have compatibility issue with shadowsocks.
2. Your ROM / phone has compatibility issue with shadowsocks.

My suggestions:
1. Uninstall / disable any firewall apps.
2. Try some other ROMs.

**Comment by LeoK987** [comment]
It was not due to these reasons.  I just found it was BlueLight Filter
app.  With the screen filter on, Android disabled the install button.
