### ISSUE TITLE
wifi 和3G出现感叹号

### ISSUE THREAD

**Issue by deepller** [shadowsocks/shadowsocks-android#220]
是有vpn模式右上角的wifi信号一直有感叹号，切换成NAT模式就可以消失，不知可否在vpn模式里面修复。 网上说是一条检测google服务的函数没有返回。

**Comment by madeye** [comment]
http://xn--yet824cpd.xn--fiqs8s

**Comment by JohnnySun** [comment]
使用nat模式即可
