### ISSUE TITLE
Customer List导入GWF List后效果与GWFList不同

### ISSUE THREAD

**Issue by zhoujun2** [shadowsocks/shadowsocks-android#2205]
Please read contributing guidelines. Thanks.

**Describe the bug**
我在Customer List中导入了GWF列表，profile 配置里也选择Custmoer了，但是这样不能使用Telegram。而profile 配置里选择GFW就能访问Telegram。我认为在自定义列表里面导入GFW和直接使用GWF效果是一样的。该问题只出现在电报上，请问怎么办
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android 9 
 - Device: [e.g. Google Pixel XL]
 - Shadowsocks Version: v4.7.4

**Configuration**
Put an `x` inside the [ ] that applies.

* [X] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [X] Client IPv6 availability
* Encrypt method: aes256
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [x] Custom rules
* [X] IPv6 route
* [X] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):none
* [X] Auto Connect
* [X] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
如描述不清，请开发者见谅，我补全

**Comment by madeye** [comment]
Double check you have these IPs in your custom rules:

```
# Telegram IPs
91.108.4.0/22   
91.108.8.0/21   
91.108.16.0/21  
91.108.36.0/22  
91.108.56.0/22  
109.239.140.0/24
149.154.160.0/20
```

**Comment by zhoujun2** [comment]
自定义规则中有telegram.dog .me .org .co.uk等域名规则，没有任何IP信息。
我是通过右上角导入GWF List功能生成的自定义规则，这样有问题吗

**Comment by zhfreal** [comment]
我以前抓过电报Android端的包，发现其没有用域名而是直接用的IP，所以你需要检查是否有电报的IP段。
