### ISSUE TITLE
4.7.4版“分应用VPN”中的“启用”、“绕行”不起作用？分别点亮这两个开关，看不出变化

### ISSUE THREAD

**Issue by 3xpert** [shadowsocks/shadowsocks-android#2207]
Please read contributing guidelines. Thanks.

**Describe the bug**
4.7.4版“分应用VPN”中的“启用”、“绕行”不起作用，
![photo_2019-05-15_22-40-50](https://user-images.githubusercontent.com/8335065/57784497-957cdf80-7762-11e9-8643-845825884aff.jpg)
![photo_2019-05-15_22-40-56](https://user-images.githubusercontent.com/8335065/57784498-957cdf80-7762-11e9-9092-eb06eb46742c.jpg)
![photo_2019-05-15_22-41-03](https://user-images.githubusercontent.com/8335065/57784500-96157600-7762-11e9-8bb0-70fd44dadc6e.jpg)
![photo_2019-05-15_22-41-09](https://user-images.githubusercontent.com/8335065/57784501-96ae0c80-7762-11e9-9fc2-ee1fcd620da3.jpg)

分别点亮这两个开关，看不出变化
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Probably ROM bug.
