### ISSUE TITLE
手动设置配置信息时 换屏信息将不会保留

### ISSUE THREAD

**Issue by jzlnice** [shadowsocks/shadowsocks-android#2209]
手动设置配置信息时 会一下子记不住配置信息，需要返回只别的界面复制剩余信息，但重新返回APP时 原先设置了一半的界面消失了，app自动返回至首页。
原来记得3.xx的版本 返回APP时仍是原先的界面，但升级至4.7.4之后，就有这个问题了

**Comment by Mygod** [comment]
Post video.

**Comment by iamsad3508** [comment]
nexus 6P  
android O 8.1.0
ss:4.7.4
点击“手动设置”，修改服务器为1.1.1.1，按下home键（不是切换窗口键），点击桌面的影梭。
app返回首页，刚才编辑的内容会消失，剩下一个没有配置过的“配置文件”在最下面。
