### ISSUE TITLE
北京联通3G环境下无法使用

### ISSUE THREAD

**Issue by dustookk** [shadowsocks/shadowsocks-android#221]
设备: 三星Galaxy S5联通版
系统: 官方4.4.2已root
软件版本: 2.6.2 ( google play )

现象: wifi下使用正常. 3G环境下墙内外网络都无法访问.

**Comment by madeye** [comment]
取消对 shadowsocks 的 ROOT 授权。

**Comment by dustookk** [comment]
可以解释一下原因吗?  谢谢了.

**Comment by madeye** [comment]
https://groups.google.com/forum/#!topic/shadowsocks/wdC0cjrTpGM

**Comment by madeye** [comment]
Duplicate with https://github.com/shadowsocks/shadowsocks-android/issues/177
