### ISSUE TITLE
导入二维码功能，建议不要使用google play的组件

### ISSUE THREAD

**Issue by jzlnice** [shadowsocks/shadowsocks-android#2210]
使用该软件的用户基本时国内，而国内android系统都是不预装google play 服务，而且基本不愿意再安装。
所以二维码功能需要支持Google Play的话，大部分用户将无法使用该功能。
感谢！

**Comment by Mygod** [comment]
Contributions are welcome.

**Comment by jhoneybee** [comment]
我尝试的使用开源的解决方案替换掉 google play的服务. 如果你急需要这个功能尝试的捐助一下这个项目

**Comment by Mygod** [comment]
I personally prefer machine learning based solutions over traditional CV based solutions (e.g. Zxing) due to their versatility and futureproofness. Feel free to replace Google/Firebase vision with another library if you managed to find any.

**Comment by madeye** [comment]
@Mygod If we use MLKit directly, can we make Google service optional?

**Comment by madeye** [comment]
Hmm, it looks MLKit is just a wrapper of Google service...

**Comment by Mygod** [comment]
Firebase vision depends on Google play services quite heavily unfortunately (I think Google services is responsible for maintaining an up-to-date copy of their trained model).

**Comment by Mygod** [comment]
As a reminder, for devices without Google play, you can still scan QR codes using third party apps and import it into shadowsocks however.

**Comment by Mygod** [comment]
Yeah, we have already addressed this in https://github.com/shadowsocks/shadowsocks-android/commit/8335a5809adb455d3aa873bc1dd0eba462bd0ad4.
