### ISSUE TITLE
[enhancement] use aes-ni for armv8

### ISSUE THREAD

**Issue by liudongmiao** [shadowsocks/shadowsocks-android#2212]
In issue #1613, @madeye said:

> On mobile devices, chacha20 is always preferred.

Actually, if aes-ni are supported,  aes-gcm should be much fast than chacha20.
One evidence is that Chrome android use choose aes or chacha20 dynamically.
You can use ssllabs.com to check, and visit on your mobile phones, and low-end phones.
You can check google.cn/.com for boringssl, and brevent.sh for openssl.

Openssl or Boringssl has the implementation for ARMv8-A.
- https://github.com/openssl/openssl/blob/master/crypto/aes/asm/aesv8-armx.pl
- https://github.com/google/boringssl/blob/master/crypto/fipsmodule/aes/asm/aesv8-armx.pl

The core instructions are`aesd`, `aese`, `aesimc` and `aesmc`.

Current aes-gcm implementation in  shadowsocks-libev are mbedtls.
mbedtls is mainly for arm32, and only implement aes-ni for x86_64.
It would take long time to add aes-ni for armv8a into mbedtls.
(I have pr for another asm enhancement, and use in product, they don't accept yet.)
And libsodium use non-asm implementation for aes-ni on x86.

So, can we switch the implementation of aes-128-gcm and aes-256-gcm to openssl/boringssl?

In tls 1.3, there are 3 ciphers:
- TLS_AES_128_GCM_SHA256
- TLS_AES_256_GCM_SHA384
- TLS_CHACHA20_POLY1305_SHA256

I don't check them yet, however, it should be similar with AEAD in shadowsocks-libev:
- aes-128-gcm
- aes-256-gcm
- chacha20-ietf-poly1305

If you need the benchmark on Android devices, I'll try to build and run.

**Comment by liudongmiao** [comment]
We can dlsysm aes related function from `libssl.so`.

Even Android N restrict private symbol. We can just `dlopen(NULL)` to indicate  `libssl.so`, as it's loaded by `app_process`.

Actually, I just don't know why shadowsocks-libev don't use openssl, but use libsodium and/or mbedtls.

**Comment by liudongmiao** [comment]
```
AES_encrypt: 0x73054af1f0
AES_decrypt: 0x73054af580
AES_set_encrypt_key: 0x73054aec74
AES_set_decrypt_key: 0x73054aefb0
```

dlopen(NULL) + dlsym on Pixel, Android P, 2019-05.

**Comment by madeye** [comment]
> So, can we switch the implementation of aes-128-gcm and aes-256-gcm to openssl/boringssl?

No, we don't have any plan to do that.

**Comment by liudongmiao** [comment]
It should be simple to use a wrapper of `libssl.so` in Android, as Android ships `libssl.so`.

Actually most devices including desktop and mobile are shipped with aes-ni or other aes hardware encryption.

I have look into the api of mbedtls and libsodium, I still don't understand why choose mbedtls + libsodium instead of a single openssl or its fork like libressl and boringssl (in old time, there was no libressl, nor boringssl of course).

Actually, ever for chacha20, there is a asm implementation.
I have checked on my devices, c version took 150% time than asm version.

If you have no plan to support aes hardware encryption, please close this issue.

**Comment by madeye** [comment]
1. chacha20-poly1305 is the recommended and default cipher of shadowsocks, which has good performance across platforms.
2. shadowsocks-libev/android are published under GPLv3, which have a potential conflict with OpenSSL's license.
3. We prefer lightweight libraries like libsodium and mbedtls.

**Comment by liudongmiao** [comment]
1. For chacha20-poly1305, the implementation in boringssl is by Google, from public domain and in ISC license, same as libsodium. Normally, asm implementation has better performance than pure c.

2. The idea won't ship openssl binary at all, but try to dlopen / dlsym libssl.so in system.
I'm not familiar with license, use dlopen/dlsym to call api shouldn't have any problem.
Since Android 5.X, it can use dlopen(NULL) to omit library name.

3. Again, I'm not familiar with license.
However, GnuTLS is under LGPL, however, it still ship some file from openssl.

Thanks. And I will terminate the discussion.
However, I'd like to say again, aes-ni is faster than chacha20...
