### ISSUE TITLE
Suggestions: Add UDP forwarding and Set DNS feature in the application Shadowsocks: socks5 proxy safe  

### ISSUE THREAD

**Issue by ammarraisafti** [shadowsocks/shadowsocks-android#2217]
# Components
The following are the feature components that I want to recommend:

- UDP forwarding
- Set DNS

# Proposal description
Propose and suggest the 'UDP forwarding feature' in the shadowsocks application, preferably the developer adds the feature in the Settings section and modify the section to give the user information about the benefits of the "UDP forwarding" feature if the user enables the feature. function of the feature.
![Screenshot_20180301-105137-picsayjs.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716262/aybgymqwt9l8ljyuhycb.png)

Propose and recommend the "Set DNS" feature in the profile section. We recommend that developers add those features in the toolbar section of the profile menu, and modify those sections to give users a choice of DNS, such as DNS Default, Google DNS, and Custom DNS. And gives users information about each DNS, as well as permission to activate it.
![Screenshot_20180301-105137-picsayvb.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716459/aeko0eajek23mhalcsmq.png)

# Mockups / Examples
An example image before the developer adds a "UDP forwarding" feature in the Settings section, and gives the user complete information about the feature.
![Screenshot_20180301-105137-picsayjsje.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716665/nee2pkek67fagfw8r4mu.png)

An example image after the developer adds a "UDP forwarding" feature in the Settings section, and gives the user complete information about the feature.
![Screenshot_20180301-105137-picsayjsjs.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716741/sk7qloijkzfkvpxocdln.png)

An example image before the developer adds the "DNS Set" feature in the profile menu section, ie in the top toolbar section.
![Screenshot_20180301-105137-picsayuj.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716797/n4yk100e7fuqzatnv3ze.png)

An example image after the developer adds the "DNS Set" feature in the profile menu section, ie in the top toolbar section.
![Screenshot_20180301-105137-picsayhh.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716873/ivah8zm7qcjoi77o7sa4.png)

An example image after the developer modifies the "DNS Set" section to give users a usable DNS option, such as the Default DNS option, Google DNS, and Custom DNS.
![Screenshot_20180301-133023-picsayf.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716894/doiy0taklkwfvcwebpwo.png)

![Screenshot_20180301-105137-picsayg.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521716919/n2ozih3qu0gerhua5fml.png)

# Benefits
With the "UDP forwarding" feature in the shadowsocks app, the app is more attractive to use, as users can use external servers to forward UDP, if streaming video or voice calls are not working, while surfing the internet / playing videos using the internet network, via the shadowsocks app . So users can surf the internet in a private and secure way, using shadowsocks apps, without finding problems, and obstacles. And that's a big advantage.

And with the "DNS Set" feature in the shadowsocks application profile menu section, users can set DNS, according to their needs when surfing the internet, choosing to use the DNS address provided by the network operator, or choose to use the DNS address provided by Google, and choose to use Custom DNS, which allows users to set the DNS address as desired. So Shadowsocks applications are more optimal to use, and faster surfing the internet. So users will give the best rating for this app. And boast against other users, because the app they use, has great features, which is not owned by other apps. I hope, my suggestion can be an additional idea for developers to make this application more interesting.

Thanks.

**Comment by madeye** [comment]
Both features you mentioned are already there from the very beginning.

**Comment by ammarraisafti** [comment]
Thank you for responding to my suggestion.  I don't see that my first suggestion was in the previous application.  And regarding the second suggestion, it's true if you mention that it was there before, but it is a "Local DNS" feature, not a feature for managing DNS.  I think, it will look better and more interesting, if the DNS can be set as desired by the user.  They can choose DNS provided by the network, or provided by Google, and use Special DNS, which allows users to set DNS addresses as desired.  It will look cooler.

**Comment by madeye** [comment]
1. UDP forwarding is always enabled.
2. Find the remote DNS setting in the server profile.
3. Local DNS is handled automatically following system's setting.

**Comment by Mygod** [comment]
Please stop spamming [these](https://busy.org/@ammarraisafti/suggestions-add-udp-forwarding-and-set-dns-feature-in-the-application-shadowsocks-socks5-proxy-safe) and waste everyone's time.
