### ISSUE TITLE
在ipv4和ipv6之间切换网络时ss服务器不会自动切换

### ISSUE THREAD

**Issue by cnsdtest** [shadowsocks/shadowsocks-android#222]
假设我的域名是name.tk为双栈，我在ipv4下正在使用ss上网，现在切换到ipv6的wifi了，ss就断网了，假设wifi是需要登陆才能使用ipv4的，我不想登陆。能否做到当网络环境切换时重新解析ip地址的功能？

**Comment by madeye** [comment]
不可以的，域名解析只发生在连接时。

**Comment by cnsdtest** [comment]
那有没有可能实现呢，比如动态DNS的支持。
