### ISSUE TITLE
请问当我一个链接导入多个节点时，我应如何把这些节点的路由全部设置为“绕过局域网和中国大陆地址”？

### ISSUE THREAD

**Issue by ubui** [shadowsocks/shadowsocks-android#2223]
请问当我一个链接导入多个节点时，我应如何把这些节点的路由全部设置为“绕过局域网和中国大陆地址”？

**Comment by madeye** [comment]
1. Export profiles to file.
2. Modify the `route` to `bypass-lan-china`.
3. Import the file back.
