### ISSUE TITLE
当我用v2ray-plugin套上cdn之后发现大概率出现Cannot resolve hostname "www.google.com"...的错误提示

### ISSUE THREAD

**Issue by lxsjgzs** [shadowsocks/shadowsocks-android#2224]
Please read contributing guidelines. Thanks.

**Describe the bug**
当我用v2ray-plugin套上cdn之后发现大概率出现Cannot resolve hostname "www.google.com"...的错误提示
**Expected behavior**
在手机释放资源重新链接之后大概率出现，多次重连可以解决
**Smartphone (please complete the following information):**
 - Device: [Xiaomi MIX 3]
 - Version: [Android 9]
**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ x] All
* Remote DNS: 8.8.4.4
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Shadowsocks verson 4.7.4

**Comment by madeye** [comment]
It means the background service is killed by your system.

**Comment by lxsjgzs** [comment]
THANKS!

发件人: Max Lv<mailto:notifications@github.com>
发送时间: 2019年5月31日 9:33
收件人: shadowsocks/shadowsocks-android<mailto:shadowsocks-android@noreply.github.com>
抄送: lxsjgzs<mailto:mzx9685@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [shadowsocks/shadowsocks-android] 当我用v2ray-plugin套上cdn之后发现大概率出现Cannot resolve hostname "www.google.com"...的错误提示 (#2224)


It means the background service is killed by your system.

―
