### ISSUE TITLE
希望加入一键测试所有链接延迟的功能

### ISSUE THREAD

**Issue by StudyForMe** [shadowsocks/shadowsocks-android#2230]
希望加入一键测试所有链接延迟的功能，有很多公益链接已经失效但是只要连接上才能测试，很不方便

**Comment by sumpeter** [comment]
有吧，点左上角进入配置文件页面，右边icon有一个闪电A的就是全部测试。

**Comment by StudyForMe** [comment]
那个是ssr的功能啊

sumpeter <notifications@github.com> 于 2019年6月4日周二 11:34写道：

**Comment by Mygod** [comment]
#2215
