### ISSUE TITLE
Can't download app from Google Play

### ISSUE THREAD

**Issue by bluesky139** [shadowsocks/shadowsocks-android#2231]
Please read contributing guidelines. Thanks.

**Describe the bug**
When downloading app from Google Play, it will stuck at "download pending", app will never be downloaded.

**To Reproduce**
1. Go to Google Play.
2. Click on one app whatever you want.
3. Press install.
4. It shows "download pending", app will never be downloaded.

**Expected behavior**
Download app successfully.

**Screenshots**
![Screenshot_20190607-011133](https://user-images.githubusercontent.com/1788897/59075662-79550400-8904-11e9-893d-eb56d8ce5cfd.png)

**Smartphone (please complete the following information):**
 - Android 8.1/9.0.
 - Device: Nexus 5, Pixel 3 XL
 - Version: v4.8.0, v4.6.5
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x ] IPv4 server address
* [ ] IPv6 server address
* [ x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I traced this problem for a while, it's caused by ss-local acl, maybe some bug in ss-local acl.

The `bypass-lan-china.acl` file has `bypass_list` and `proxy_list`, if I remove `proxy_list`, this problem is solved.

One the other hand, I think `proxy_list` is unnecessary in VPN mode, domain will be solved by dns server first, then go to ss-local with solved IP, ss-local has bypass acl, so it know how to route.

**Comment by madeye** [comment]
First of all, I cannot reproduce your issue locally.

I don't think the workaround mentioned here is the root cause of your problem. It looks your server cannot resolve and reach Google's file server correctly.

BTW, `[proxy_list]` is required for corner cases that the polluted DNS record is in China IP range.

**Comment by madeye** [comment]
One common misunderstanding of shadowsocks-android is that it's pure routing based and support IP only ACL.

Actually, the latest shadowsocks-android supports domain name based rules for any HTTP/TLS connections.

**Comment by bluesky139** [comment]
I'm sure my server is OK, because if I set route to all, I also can download app from Google play.

**Comment by bluesky139** [comment]
So, do you have any other way to let me trace this problem?

**Comment by madeye** [comment]
Try some other servers first, make sure it's not a server specific issue.

Then look into the log on your server, trace the server domain name when downloading from Google play.
