### ISSUE TITLE
A blacklist may guarantee security during network communication

### ISSUE THREAD

**Issue by twz007** [shadowsocks/shadowsocks-android#2232]
**Is your feature request related to a problem? Please describe.**
Not a problem, a new optimization feature.

**Describe the solution you'd like**
I hope that the new version of shadowsocks-android can be added to the blacklist function. You can use keywords or regular expressions to block unwanted addresses. I hope you can adopt this idea.
**Describe alternatives you've considered**
When you use shadowsocks-android to access external websites, you will often encounter pop-up ads and viruses, which makes your phone unsafe. The historical version of shadowsocks only prohibits the configuration of ip, and the emergence of cdn at this stage makes the function lose its last value. I once modified the source code of shadowsocks and added the function of domain name blocking. I used it a few days ago. Until yesterday, my vps was banned. I tried to change ip, but ip was still banned. I had to use Just My Socks which couldn't modify the shadowsocks configuration.
**Additional context**
Add a blacklist button to the settings option, just like the custom rule.

**Comment by Mygod** [comment]
Use hosts in v4.8.0.

**Comment by twz007** [comment]
I installed the beta version of v4.8.0, but I don't know what the hosts are for? How should I configure it?

**Comment by madeye** [comment]
https://en.wikipedia.org/wiki/Hosts_(file)
