### ISSUE TITLE
Add the IP Hunter, Host Checker, and Others Settings feature in the Shadowsocks app

### ISSUE THREAD

**Issue by ammarraisafti** [shadowsocks/shadowsocks-android#2235]
# Components
The following are the feature components that I want to recommend:

- IP Hunter. 
- Host Checker. 
- Others Settings. 

# Proposal
Propose three important features in the shadowsocks app for surfing the internet in a private and secure way, and optimizing app performance.

- Add the IP Hunter feature in the shadowsocks application, in the options menu section.And give the user access using the feature.A developer must modify the section, to give users access to enter the local IP, and give users access to locate the local IP address.

- Add the Host Checker feature in the options menu section, and grant the user access using the feature. The developer must grant the user access to check host header information. And developers need to modify the section to give users access to enter the URL, and give users multiple options, such as Get, Post, Head, Options, Put, Delete, Trash, and Patch. The developer must also grant the user access entering the Proxy (IP: port) in that section. And grant the user access to enable Direct Request. And provides Check feature in that section.

- Add the Advanced Settings feature in the Settings section of the app. And modify that section to give users the features of Wakelock CPU, Battery Saver, and Clear log on connect feature. And give the user access using the feature.

# Mockups / Examples
Examples of images seen in the Shadowsocks app after the developer added three features I proposed.

- An example image after the developer adds the IP Hunter and Host Checker features in the options menu section.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521037276/h2pei6eixi3zdj6qrmqq.png)

- An example image after the developer modifies the IP Hunter section, to provide the user access entering the local IP address and giving the user access to locate the local IP address.
![Screenshot_20180301-105137-picsayrt.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521037772/fhzf5p7rhwgz2mphhdbl.png)

- An example image after the developer modifies the Host Checker section, to give the user access entering the URL and gives the user multiple options, and provides access to enter Proxy (IP: port). And gives the user access to check host header information.
![Screenshot_20180301-105137-picsayysus.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521037916/i0ekdy7a6rzjsfwe9jaa.png)

![Screenshot_20180301-105137-picsaybsjz.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521038330/zn3lwnqgykmkmv65kvcb.png)

- An example image after the developer adds the Advanced Settings feature in the Settings section of the shadowsocks application.

- An example image after the developer modifies the Advanced Settings section, to give the user the Wakelock CPU features and Clear log on connect feature when the user accesses the feature. San gives the user access to enable the feature.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521042843/irhz4yqj1t54qw3cswqa.png)

![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521043635/b7qu6iayn7es6gim3h1d.png)

An example of a picture after the user activates all the features contained in the Other Settings section.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521044095/cqsagzokbqjwbdncdocb.png)

# Benefits
- The benefits of the IP Hunter feature I propose in the Shadowsocks app are. Users of Shadowsocks applications can surf the internet by locating local IP addresses using the shadowsocks app, allowing users to surf the internet by pointing to network locations, and searching for IPs with few users, increasing Internet speed. And that's a big advantage for users. 

- And with the presence of the Host Checker feature in the shadowsocks app, users can check the host used while surfing the internet in a private and secure way using the shadowsocks app. So users can find out some information about Host on their device. If Host is in trouble.

- And the user can set the option to use the Wakelock CPU feature to connect with android system mechanisms using the shadowsocks app, to get Power from CPU processing, to run its task. So the Shadowsocks application is more interesting to use. Users can also enable Battery Saver feature while surfing the internet, so do not consume excessive battery usage. And users can also enable Clear log on connect feature, to delete all previous logs, when connecting connections to surf the internet in a private and secure way using the shadowsocks app.

**Comment by madeye** [comment]
None of these proposed features make sense to me.

**Comment by Mygod** [comment]
@madeye No need to respond to spam. 😄
