### ISSUE TITLE
让服务端解析IP

### ISSUE THREAD

**Issue by coiby** [shadowsocks/shadowsocks-android#224]
你好！

因为VPS的IP被Google Scholar block了，但是通过IPv6访问scholar是没问题的。

但是据我的测试结果，本客户端似乎先向服务器请求DNS解析，然后再把IP发给ss-server让抓回网页内容。有没有方法直接发送域名给ss-server，让ss-server自己去处理？

P.S. 标题有误，是“让服务端解析域名”。

谢谢！

**Comment by madeye** [comment]
Android 端的实现是一个透明代理，无法实现所谓的“发送域名给ss-server”。
