### ISSUE TITLE
Invalid Server Name for cnode.xyz domain

### ISSUE THREAD

**Issue by maye9999** [shadowsocks/shadowsocks-android#2240]
Invalid server name when using hkvi.cnode.xyz server. Server and QR code have been verified both on PC and Mac OS. After I manually look up the IP address of that server and use that for server address, everything works fine. So maybe the DNS seems broken?

**Screenshots**
![image](https://user-images.githubusercontent.com/10060525/59196058-2d35e800-8bc0-11e9-9371-133c5f0fa128.png)

**Smartphone (please complete the following information):**
 - Android version: 9
 - Device: Xiaomi MIX2S
 - Version: v4.7.4

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by Mygod** [comment]
Make sure there is no hidden characters in your server name.

**Comment by maye9999** [comment]
@Mygod 
I've tried clearing and retyping the server name, but still problem exists.

**Comment by maye9999** [comment]
Sorry but I've tried scanning the QR code again. It works. So I cannot reproduce this issue. Thanks for your time.
