### ISSUE TITLE
"VPN Set Up and Manage Virtual Private Networks" feature in application Shadowsocks 

### ISSUE THREAD

**Issue by ammarraisafti** [shadowsocks/shadowsocks-android#2243]
# Components
The following are the feature components that I want to recommend:

- VPN Set Up and Manage Virtual Private Networks

# Proposal description
Propose the "VPN Set Up and Manage Virtual Private Networks (VPNs)" feature in the settings section of the shadowsocks app, and grant the user access using the feature. And modify the "Set Up Virtual Private Networks (VPNs)" feature feature to add the "Always-on VPN" feature, and enable it. And add the feature "Delete VPN Profile", as well as permission to delete it.

# Mockups / Examples
Examples of images seen in the Shadowsocks app after the developers added the "VPN Set Up and Manage Virtual Private Networks (VPNs)" feature in the Settings section of the shadowsocks app and gave users the "Always-on VPN" feature and the "Delete VPN Profile" feature in that section.

![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520350139/pimremdls1f1qrzcdw7s.png)

![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520350674/q5r5wik7i91smgxdp1bz.png)

![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520351144/qop8zr7bqsxqcddivau2.png)

![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520351330/benpwbwfja4cjabz1bzt.png)

# Benefits
Users of the Shadowsocks app will benefit greatly after the developers added the "VPN Set Up and Manage Virtual Private Networks (VPNs)" feature in the shadowsocks app, as users can use the feature to choose to use and assign the "Always-on VPN" shadowsocks app on their android device , while surfing the internet in a private and secure way. Users can also manage to delete the VPN profile used by the shadowsocks application. And that's a big advantage. So users feel very happy with the presence of these features and invite other users to download and install Shadowsocks applications.

**Comment by madeye** [comment]
Why we keep receiving this kind of spams?

@Mygod Do you know?

**Comment by Mygod** [comment]
I think this dude is an automated bot that copies from utopian-io where people get paid to spam nonsensical feature requests. This one is from: https://steemit.com/utopian-io/@tikaraisaika/vpn-set-up-and-manage-virtual-private-networks-feature-in-application-shadowsocks
