### ISSUE TITLE
"分应用VPN" not working in 4.8.0

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-android#2244]
Please read contributing guidelines. Thanks.

**Describe the bug**
(sorry for my English)
After install 4.8.0 in Android simulator, The "分应用VPN" no longer working.
Rollback to 4.7.4, everything is woking fine.

**To Reproduce**
1. Click Edit server settings. (pen button)
2. Enable "分应用VPN"
3. Add any app in the list.
4. Click OK (√)
5.Back to server settings.
6."分应用VPN" is disabled.

**Expected behavior**
"分应用VPN" is enabled

**Screenshots**
Demo:
![4 8 0](https://user-images.githubusercontent.com/515763/59770300-6108c000-92da-11e9-9ef8-6e280eaf9332.gif)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 6.0.1 (x86)
 - Device: Netease MuMu simulator ( http://mumu.163.com )
 - Version: 4.8.0 (Pre-release)
 - Last version that did not exhibit the issue: 4.7.4

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
N/A

**Comment by Mygod** [comment]
Does this only occur on this emulator only? I tried official emulator 6.0 and failed to reproduce this.

**Comment by chenshaoju** [comment]
I tested on the real phone (Google Nexus 5X + Android 8.1.0 (LineageOS 15.1), It's crashed.

Demo:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/515763/59776830-0f663280-92e6-11e9-9f1b-0ccd814285d9.gif)

Here is log (Not the same time with screen record):
[ss.log](https://github.com/shadowsocks/shadowsocks-android/files/3306672/ss.log)

**Comment by Mygod** [comment]
Oh I just realized #2236 isn't in v4.8.0 yet. Please use OS back button for now, OP: https://github.com/shadowsocks/shadowsocks-android/issues/2234#issuecomment-500195454.

**Comment by chenshaoju** [comment]
Thanks! Wating next release. :100:

**Comment by chenshaoju** [comment]
Note: This issue has been fixed at 4.8.1.
