### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by yanlianglai** [shadowsocks/shadowsocks-android#2246]
Build command failed.
Error while executing process C:\Users\yan\AppData\Local\Android\Sdk\ndk\20.0.5594570\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\yan\Desktop\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\yan\Desktop\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/yan/Desktop/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j4 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\armeabi-v7a" >NUL 2>NUL || rem
C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdbserver"
copy /b/y "C:\Users\yan\AppData\Local\Android\Sdk\ndk\20.0.5594570\build\\..\prebuilt\android-arm\gdbserver\gdbserver" "C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\armeabi-v7a\gdbserver" > NUL
C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi-v7a] "Gdbsetup       ": "C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup"
C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path C:/Users/yan/Desktop/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a" > C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup
C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/mbedtls/include C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/pcre/dist C:/Users/yan/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../sources/cxx-stl/system C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/libancillary C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv4 C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv6 C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custom" >> C:\Users\yan\Desktop\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/armeabi-v7a/gdb.setup

process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/yan/Desktop/shadowsocks-android-master/core/src/main/jni/redsocks/base.c', needed by `C:/Users/yan/Desktop/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/redsocks/redsocks/base.o'.  Stop.
please help...

**Comment by yanlianglai** [comment]
BUILD
You can check whether the latest commit builds under UNIX environment by checking Travis status.

Clone the repo using **git clone --recurse-submodules <repo>** or update **submodules using git submodule update --init --recursive**
Build it using Android Studio or gradle script

**Comment by Bodertownpas** [comment]
我也遇到了，是怎么解决

**Comment by AliBadar** [comment]
Hi @yanlianglai @Mygod 
Have you fixed this issue? I am also facing this issue, can you please guide me
