### ISSUE TITLE
使用4G出现错误，WiFi没有问题

### ISSUE THREAD

**Issue by aylitan** [shadowsocks/shadowsocks-android#2249]
![Screenshot_20190625103059](https://user-images.githubusercontent.com/46384604/60065243-d12da080-9735-11e9-936b-407130099fc8.jpg)

**Comment by FlameYagami** [comment]
Wifi is no problem，but when I use 4g and test connect，it will be error，the toast is【Read error:ssl=0x75f2524e40:Failure in SSL library,usually a protocaol error...】
PS：My Sim card is China Mobile

**Comment by Mygod** [comment]
Hey everyone facing this issue, you are wasting everyone's time by not filling out the template.

Complaining will not get it fixed. Fill out the damn form.
