### ISSUE TITLE
Hunan China Mobile Connection issue (With specific ss server)

### ISSUE THREAD

**Issue by ProfessorX** [shadowsocks/shadowsocks-android#2250]
Please read contributing guidelines. Thanks.

开始用英文写了一大堆，然后点了个no thanks 跳到新页面没了，forgive me for being more concise.
**Describe the bug**

Cannot connect to my own private ss server (****.yxiao.org) under Hunan China Mobile network, it says SSL=**** something and cannot connect.

However, it works perfectly in my windows system and 4.2.5 with my friend's oneplus7 pro.

**To Reproduce**

1. go to manual settings to add my private ss server (email me if you need it to reproduce)
2. click save and start the connection.
3. click testing to test https handshake
4. it will take ages then show connection failed. (Today with 4.7.4 it says Internet Unavailable

**Expected behavior**

It should connect. The APP and connection are OK with another commercial ss server provider with RC4-MD5 encryption.

**Screenshots**

It was on another closed issue(hosted on imgur, but my server IP seems to be temporarily blocked ???. Check here 链接：https://share.weiyun.com/5WNtv68 

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

Check the screenshot above.

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

Sometimes my server IP is blocked. But the time for the phone screenshot it was OK.

**Comment by ProfessorX** [comment]
![1](https://camo.githubusercontent.com/1328c28db2b54fc6bdc0a010738f1e7b20ba10bd/68747470733a2f2f692e696d6775722e636f6d2f51666845366c752e6a7067)

![2](https://camo.githubusercontent.com/2c9ee1ccd378bc261faa24aa35a4e6ed022d1916/68747470733a2f2f692e696d6775722e636f6d2f33664d484150712e6a7067)

**Comment by ProfessorX** [comment]
![20190626](https://i.imgur.com/yYEndA4.jpg)

Add a new image today.

Note: it is ok to ping the server on my desktop under China Telecomm and ssh is fine.

Update: the first fuck.yxiao.org pings ok at times. Randomly.

**Comment by Mygod** [comment]
Make sure your server is reachable from your mobile network by setting up a
hotspot.

**Comment by ProfessorX** [comment]
Update: My ss private ss server works fine on my friend's phone oneplus 7pro with ss nightly build 4.2.5 (China Unicomm Hunan)

And it works great at least on company desktop China Telecomm.

I guess it's most likely the problem of China Mobile here at Hunan?

**Or anyone else can help test outside/inside Hunan connection to my server?**

**Comment by ProfessorX** [comment]
@Mygod H Hey amigo it is not polite to close issue like this. Hope you can reopen it since this problem is not solved yet.

For Hunan China Mobile 4g network connectivity test please refer to the following s-shot.

![ping](https://i.imgur.com/mMvxOPB.jpg)

-------
As I have mentioned I have been using 4.7.4 version for quite a long time and it is OK with the other commercial ss server.

I tried to set up my own and it works fine with my company desktop ss-windows, ss-mac on my friend's laptop and ss android 4.2.5 with his Oneplus 7pro.

Mine is oneplus 3t and it does not work on either 4.2.5, 4.5.x or 4.7.4 (Some connectivity issue, which was reported here: [https://github.com/shadowsocks/shadowsocks-android/issues/2184](url)

BTW I have changed the encryption method from chacha20-poly to rc-md5 to stay the same with the **commercial ss server** so it is most likely something wrong with android APP.

If you need the full logcat, let me know. I have android studio in my desktop.

Regards,
Yanan

**Comment by ProfessorX** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/344

The clearing cache and storage method works.

But cannot figure out why.

**Comment by KRReuben** [comment]
我也遇到了同样的问题。
1通过湖南移动的移动数据上网，无论是手机，还是连接了手机的热点，连接非常不稳定，很难得通过ss浏览YouTube一次。清除缓存等方式无法解决问题。
2更换成wifi或中国联通后，手机和电脑上网一切正常。

**Comment by wangfeng35** [comment]
> 我也遇到了同样的问题。
> 1通过湖南移动的移动数据上网，无论是手机，还是连接了手机的热点，连接非常不稳定，很难得通过ss浏览YouTube一次。清除缓存等方式无法解决问题。
> 2更换成wifi或中国联通后，手机和电脑上网一切正常。

北京移动也是
