### ISSUE TITLE
Mistranslation of Russian labels for DNS over UDP

### ISSUE THREAD

**Issue by georgh-** [shadowsocks/shadowsocks-android#2251]
Russian labels for DNS over UDP are incorrect, they were set up on commit 9ab92309600719dc71bf3e34702cd9058c40ce0f

Incorrect (mobile/src/main/res/values-ru/strings.xml):
```
<string name="udp_dns">"Перенаправление DNS"</string>
<string name="udp_dns_summary">"Перенаправлять все DNS-запросы на удалённый сервер"</string>

```
It should translate exactly the English test:
```
<string name="udp_dns">Send DNS over UDP</string>
<string name="udp_dns_summary">Requires UDP forwarding on server side</string>
```

I am not native speaker to fix this issue.

**Comment by madeye** [comment]
https://discourse.shadowsocks.org/t/poeditor-translation-main-thread/30

**Comment by Mygod** [comment]
The original text was updated and this resulted in a fuzzy translation. Feel free to fix it.

**Comment by georgh-** [comment]
Thanks!
