### ISSUE TITLE
Feature Request: Round-robin DNS Cloaking Rules

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-android#2255]
The hosts feature introduced in #2162 seem only to support mapping domains to single IPs. Adding round-robin DNS Cloaking support may make this feature much more flexible. An existing example of round-robin DNS Cloaking can be found [here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_cloak.go) ([source](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_cloak.go))([documentation](https://github.com/jedisct1/dnscrypt-proxy/wiki/Cloaking)).

**Comment by Mygod** [comment]
I don't see the practical benefits of this. Contributions are welcome.

**Comment by ShrdBB** [comment]
> I don't see the practical benefits of this. Contributions are welcome.

I've created another feature request #2256, see #2256 for a possible benefit.

**Comment by ShrdBB** [comment]
It seems hosts are already shuffled:
```kotlin
fun resolve(hostname: String) = map[hostname]?.shuffled() ?: emptyList()
```
So this issue can be closed. @Mygod 
(I created this issue, but later deleted my account. )
