### ISSUE TITLE
Feature Request: Apply hosts (or cloaking rules if #2255 is implemented) to plugins for resolving remote server host

### ISSUE THREAD

**Issue by ShrdBB** [shadowsocks/shadowsocks-android#2256]
A possible benefit when using the v2ray-plugin+WebSocket+TLS+Cloudflare method:

When the IP addresses returned by Cloudflare authoritative DNS servers are blocked, one just needs to map the remote server host to another Cloudflare-enabled domain or a set of IP addresses in the Cloudflare Anycast network instead of registering a new Cloudflare account to circumvent the block, while round-robin cloaking (#2255) may make the traffic look even more legitimate because it is sent to several different IP addresses.

On the PC side this may be achieved using dnscrypt-proxy, but not on an unrooted Android phone because it seems that Go has to use Android system DNS settings for TLS connections, which AFAIK may only be modified by a VPN created by another app.

A possible solution:

1. Establish a VPN service which only modifies DNS by applying cloaking rules before initiating the shadowsocks connection.
2. Establish a connection to the remote server.
3. Route network traffic to remote server.

Since I speak neither Kotlin nor Go, I am probably unable to contribute.

**Comment by ShrdBB** [comment]
I don't think this is the wrong repo because it seems impossible to implement this within the plugins.

**Comment by ShrdBB** [comment]
It seems go lib can be patched? IDK which repo is responsible for go lib patching though.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/942
