### ISSUE TITLE
安卓版客户端，选择端口的时候，能不能不要设置为滑动

### ISSUE THREAD

**Issue by autumnft** [shadowsocks/shadowsocks-android#2257]
安卓版，选择端口的时候，能不能考虑一下不要滑动，而是像电脑版的直接输入配置，不然服务端如果设置了一个23456类的端口，手机端设置端口手指都要残废了--
安卓版：
![1](https://user-images.githubusercontent.com/45935917/60867750-243b4380-a25e-11e9-8997-ce2d3b12c642.jpg)

win版：
![image](https://user-images.githubusercontent.com/45935917/60867465-7c257a80-a25d-11e9-9c7b-bda9e12e142f.png)

**Comment by kzwr** [comment]
you use version is old

**Comment by autumnft** [comment]
> 你使用的版本是旧的

非常感谢
