### ISSUE TITLE
Please add two plugins that are enabled at the same time.

### ISSUE THREAD

**Issue by Webb-Hua-Walker** [shadowsocks/shadowsocks-android#2259]
**Describe the solution you'd like**
Please add two plugins that are enabled at the same time.

**Comment by huanght1997** [comment]
I'm afraid that the developers won't implement this feature because the spec for Shadowsocks Plugin says "Only one plugin can be enabled when a shadowsocks service is started." See the spec [here].(http://shadowsocks.org/en/spec/Plugin.html)
