### ISSUE TITLE
谷歌play无法下载安全信息更新

### ISSUE THREAD

**Issue by Loukky** [shadowsocks/shadowsocks-android#2260]
Please read contributing guidelines. Thanks.

**Describe the bug**
使用shadowsocks android连接以后且连接wifi，play store 似乎误认为处于移动流量环境下面，导致play security information  update 无法更新，此时关闭ss以后通知栏会显示“下载管理器”正在下载"安全信息更新"。例：https://www.reddit.com/r/cngooglers/comments/b5xmb6/%E6%9C%89%E6%97%B6%E5%80%99google_play_%E6%97%A0%E6%B3%95%E5%9C%A8vpn%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%9B%B4%E6%96%B0%E5%85%B3%E6%8E%89%E6%A2%AF%E5%AD%90%E8%B7%B3%E5%87%BAplay_security/
同时偶尔也会有大型app无法下载，卡在正在下载...（偶然）
如果使用BifrostV连接代理的话就能正常下载play安全信息更新。
**To Reproduce**
似乎某个旧版本没有这个问题，但是已经忘记具体版本号了。

**Expected behavior**
希望解决

**Screenshots**
暂无

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: android 9.0
 - Device: sony xz premuim G8142 HK version
 - Version: 
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [X] IPv4 server address
* [ ] IPv6 server address
* [X] Client IPv4 availability
* [X] Client IPv6 availability
* Encrypt method:AES-128-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [X] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [X] IPv6 route
* [ ] Apps VPN mode
  * [X] Bypass mode
* Remote DNS: DNS.GOOGLE
* [ ] DNS over UDP
* Plugin configuration (if applicable):SIMPLE-OBFS
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Which version are you using?

**Comment by Loukky** [comment]
4.8.1

**Comment by Mygod** [comment]
Make sure the metered option is not checked in your profile config.

**Comment by Loukky** [comment]
该选项有何作用？我的确有选中。

**Comment by Mygod** [comment]
Untick "Metered Hint" so that your system will treat VPN as unmetered network when connected to unmetered Wi-Fi.

**Comment by Loukky** [comment]
关闭之后似乎无变化…下载大型app任然卡在“正在下载”，通知栏不显示下载app，另测试一60MB左右app能下载。

**Comment by Loukky** [comment]
update：app下载无问题了。
继续观察 “play安全信息更新”能否正常下载…

**Comment by ykla** [comment]
仍然存在该问题

**Comment by ykla** [comment]
4.8.7仍然存在该问题
