### ISSUE TITLE
Increase the robustness of DNS resolve

### ISSUE THREAD

**Issue by 8x8-64** [shadowsocks/shadowsocks-android#2265]
What version of ss are you using?
4.7.4

What operating system are you using?
android 9

What did you do?
用aes-128-gcm加密做dns查询，客户端会向服务器端发起连接，典型的是发送一个130左右字节的包，又收到1个130左右字节的包就断开连接，特征太明显。对于连接53端口，我在服务器端（非libev版）返回的加密数据后面直接增加了一定长度随机数据。libev、android版客户端不能正常工作，但是c#版的可以。

What did you expect to see?
这个类似发生了tcp粘包，第1个包是正确的，后面的包是错误的，我希望客户端收到这样的数据能正常工作。本来客户端就是读完第1个包结果后要主动断开连接的，后面的多余数据不应该产生影响。

**Comment by Mygod** [comment]
dup #2093?

**Comment by Mygod** [comment]
Either way, if you are looking for heavier protections against censors, you should look into plugins instead of running the plain Shadowsocks.

**Comment by 8x8-64** [comment]
我在libev那边提了同样的问题https://github.com/shadowsocks/shadowsocks-libev/issues/2436，我找到libev版问题原因了，就是一个tcp数据块里解密出多个加密块时，后面的块出错就丢弃前面刚解密的数据导致。安卓版的不知道代码在哪。

我的服务器端只接收tcp连接，客户端DNS查询自己走tcp，我也不懂为什么。另外，服务器一个端口还能接收udp，字节数就那么点，不是太明显了

**Comment by 8x8-64** [comment]
目前解决办法是，服务器在后面发加密的随机数据就行，反正客户端收到第1个解密数据块后就会断开连接
