### ISSUE TITLE
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Timed out fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path 'D:/vps/shadowsocks-android/core/src/main/jni/pcre' failed

### ISSUE THREAD

**Issue by northwolf521** [shadowsocks/shadowsocks-android#2267]
fatal: unable to access 'https://android.googlesource.com/platform/external/pcre/': Failed to connect to android.googlesource.com port 443: Timed out
fatal: clone of 'https://android.googlesource.com/platform/external/pcre' into submodule path 'D:/vps/shadowsocks-android/core/src/main/jni/pcre' failed

**Comment by mayukirin** [comment]
+1 
https://android.googlesource.com/platform/external/pcre/ can be accessed by browser
