### ISSUE TITLE
Causing Now E Launcher App List crashes

### ISSUE THREAD

**Issue by Liqianyu** [shadowsocks/shadowsocks-android#2272]
When installing Shadowsocks or Shadowsocks Android TV, try to trigger a crash when the launcher opens the app

Reproduce
Select backward in the application bar after installing the app

 - Android/Chrome OS version: 7.1.2
 - Device: Now E Android TV Box（hk101）
 - Version: hk001a-r31

**Comment by Mygod** [comment]
Report to vendor instead.
