### ISSUE TITLE
Couldn't scan the QR core

### ISSUE THREAD

**Issue by AppJ-GS** [shadowsocks/shadowsocks-android#2274]
**Describe the bug**
I scan the QR code,and nothing happened.
**To Reproduce**
1. Go to '扫描二维码'
2. See error

**Expected behavior**
Want you to fix the problem as soon as possible
**Screenshots**

**Smartphone (please complete the following information):**
 - Android 9
 - Device: Xiaomi Mi 8
 - Version: v4.8.3

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by madeye** [comment]
Try
https://play.google.com/store/apps/details?id=com.google.zxing.client.android

**Comment by AppJ-GS** [comment]
> Try
> https://play.google.com/store/apps/details?id=com.google.zxing.client.android

Are you sure?Is it useful for this app?
