### ISSUE TITLE
QR code scanning function does not work under microG/Non-GMS enabled devices

### ISSUE THREAD

**Issue by CaKrome** [shadowsocks/shadowsocks-android#2275]
**Describe the bug**
QR code scan function will be interrupted by "Google Play services error" even if the Awesome QR application is installed.

**To Reproduce**
1. Go to 'Go to 'the "add" button on the top right corner of the screen'
2. Click on 'Scan QR code'
3. See error

**Expected behavior**
Either the built-in QR code scanner pops up or use the Awesome QR code scanner.

**Smartphone (please complete the following information):**
 - Android 8.1 (LineageOS for microG)
 - Device: Xiaomi Redmi Note 4
 - Version: 4.8.3

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by madeye** [comment]
Try https://play.google.com/store/apps/details?id=com.google.zxing.client.android

**Comment by madeye** [comment]
Use the third party scanner to scan the qr code instead.

**Comment by Mygod** [comment]
Shadowsocks should prompt you to install a scanner app.

**Comment by CaKrome** [comment]
> 
> 
> Use the third party scanner to scan the qr code instead.

Sure but does that mean the QR code scanning function require Google services? Will there be a fix?

> 
> Shadowsocks should prompt you to install a scanner app.

Yes I installed the prompt Awesome QR code scanner but it cannot be recognized by Shadowsocks.

**Comment by Mygod** [comment]
You should use the app to scan the code directly.
