### ISSUE TITLE
Does not work on China Mobile

### ISSUE THREAD

**Issue by hg2581** [shadowsocks/shadowsocks-android#2276]
Please read contributing guidelines. Thanks.

**Describe the bug**
Shadowsocks client does not work when run on stock Google Android Pixel 3A phone using China Mobile SIM. The setup uses a IPv4 address outside China which is otherwise reachable on the phone, thus this IPv4 address is not blocked.
Most likely this may be because not only domain names but also IP addresses are resolved using Google servers which are blocked in China.

**To Reproduce**
Connect to either of two private shadowsocks servers outside China while in China, one in Europe, one in the US. The connection fails with the error message "Fail to detect internet connection: Unable to resolve host "www.google.com": No address associated with..." and the rest is off the screen. The default shadowsocks server, 198.199.101.152, also fails to connect.

**Expected behavior**
Should connect as other phones with exact same software but using non-China SIM cards connect fine to the same two shadowsocks servers over cellular connection while used in China. Thus no problem with the servers.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
Android 9 Pie stock
 - Device: [e.g. Google Pixel XL]
Pixel 3a XL
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
4.7.4
 - Last version that did not exhibit the issue: [not applicable]
Not known.
**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
AES-256-CFB
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
Redirect IPv6 traffic to remote
* [ ] Apps VPN mode
  * [ x] Bypass mode
* Remote DNS: 8.8.8.8
8.8.8.8 as well as 1.0.0.1
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by hg2581** [comment]
Today I tried shadowsocks on two other identical phones but with local cellular carriers in the US and have the same problem, both on WiFi and connecting over the cellular networks. What could generate this error message? Could the real issue be something else?

**Comment by hg2581** [comment]
Found an earlier entry that suggested that this could be solved by adding
"name_server":"1.1.1.1" to the shadowsocks.json file and that it is a DNS problem. So far, it seems to work.

**Comment by hg2581** [comment]
I can add that another source of this error is having the incorrect server IP address on the network in the shadowsocks.json file.

**Comment by wonderpai** [comment]
> Found an earlier entry that suggested that this could be solved by adding
> "name_server":"1.1.1.1" to the shadowsocks.json file and that it is a DNS problem. So far, it seems to work.

I met similar issue. Did you solve the problem and how??

**Comment by hg2581** [comment]
On October 24, 2019 12:17:53 PM GMT+08:00, wonderpai <notifications@github.com> wrote:
>> Found an earlier entry that suggested that this could be solved by
>adding
>> "name_server":"1.1.1.1" to the shadowsocks.json file and that it is a
>DNS problem. So far, it seems to work.
>
>I met similar issue. Did you solve the problem and how??
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/shadowsocks/shadowsocks-android/issues/2276#issuecomment-545736158

Yes, it was resolved the way described in my statement.
