### ISSUE TITLE
SS NAT模式 通知显示的优先级

### ISSUE THREAD

**Issue by neverzyw** [shadowsocks/shadowsocks-android#228]
嗯 大大 能否把SS NAT模式在通知栏的优先级调低一点呢……
我现在是5.0  开了SS之后总是跳到通知栏的第一个 但是我的第一个通知位置想放别的东西（只有第一个通知位置才能显示更多东西）
能否把SS的通知优先级调低一点呢？ 或者像某些软件一样 可以自行设置优先级
![screenshot_2015-01-25-12-03-43](https://cloud.githubusercontent.com/assets/9364796/5890179/675df864-a48a-11e4-96b0-229783c00041.png)
![screenshot_2015-01-25-12-03-53](https://cloud.githubusercontent.com/assets/9364796/5890180/6761e532-a48a-11e4-8a55-3734a03d303b.png)
![screenshot_2015-01-25-12-04-06](https://cloud.githubusercontent.com/assets/9364796/5890181/6767d29e-a48a-11e4-832c-60553f3c96e5.png)

**Comment by neverzyw** [comment]
大大什么时候能放一下新的包呢~
十分感谢~~~~

**Comment by ageback** [comment]
@neverzyw I built with the latest source code. You can try it.
https://userscloud.com/yv6h6nco7qh3

**Comment by neverzyw** [comment]
好了 谢谢大大
