### ISSUE TITLE
use shadowsocks in two app on same device

### ISSUE THREAD

**Issue by rexi1r** [shadowsocks/shadowsocks-android#2281]
Please use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead. Your issue will probably be closed.
@vmlinz @jlund @athurg @ayanamist 
hi, I want two use shadowsocks and v2ray plugin inside two different application and both of theme are installed on user device .so I create two separate app and import modules (core, plugin, v2ray). 
when just one of them is on user device everything goes ok, but If both of them are installed,onServiceConnected method fire but proxy does not work.

I think when both of theme is installed we have conflict in something, but I don't know where is it and what happened.
do you know anything about that?

**Comment by rexi1r** [comment]
@Mygod no one doesn't know any things about this problem?

**Comment by huang-ju** [comment]
Modify package name
