### ISSUE TITLE
How to build with android app bundle

### ISSUE THREAD

**Issue by Joy-Whale** [shadowsocks/shadowsocks-android#2289]
I want to build app with google android app bundle use the command "gradlew bundleRelease", but when I install with bundle apks and try to connect, It always told "Cannot run program "/data/app/packageName/lib/arm64/libss-local.so" (in directory "/data/user_de/0/packageName/no_backup"): error=2, No such file or directory"

**Comment by Mygod** [comment]
Android app bundle is not supported. Contributions are welcome.

**Comment by ALi-Moslehi** [comment]
hi, i have this problem....

please help me.
