### ISSUE TITLE
无法连接服务器，libss-local exits too fast (exit code:255)

### ISSUE THREAD

**Issue by didi-droid** [shadowsocks/shadowsocks-android#2292]
Please read contributing guidelines. Thanks.

**Describe the bug**
无法连接服务器

**To Reproduce**
1. 选择服务器配置
2. 点击【连接】
3. 看到不能连接服务器异常

**Expected behavior**
正常连接服务器

**Screenshots**

**Smartphone (please complete the following information):**
 - Android 10
 - Device: xiaomi 9
 - Version: master version

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x ] IPv4 server address
* [ ] IPv6 server address
* [ x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-128-gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ x ] DNS over UDP
* Plugin configuration (if applicable):
* [ x ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

抓取到日志：
```
error: "/data/app/com.github.shadowsocks.plugin.v2ray-n4J1iJa1RLMutq1cBcyaTw
==/lib/arm64/libv2ray.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64
Bionic
```

**Comment by Mygod** [comment]
Post full logcat.

**Comment by didi-droid** [comment]
抱歉，搞错了。我在v2ray-plug-android找到解决方法。
shadowsocks/v2ray-plugin-android#6
用go1.13重新编译。

**Comment by iamaguoke** [comment]
你好，我想问一下，用影梭shadowsocks - universal-4.8.4.apk，当启用kcptun的时候就出现libss-local exits too fast (exit code:255)，如果不启用kcputun插件就能正常使用，这是怎么回事？

**Comment by 43350860** [comment]
> 你好，我想问一下，用影梭shadowsocks - universal-4.8.4.apk，当启用kcptun的时候就出现libss-local exits too fast (exit code:255)，如果不启用kcputun插件就能正常使用，这是怎么回事？

我也遇到了同样的问题，求回答。

**Comment by dao3300** [comment]
> 。

我也是，华为手机。已经排除了关联启动的原因。
