### ISSUE TITLE
Please add an Amazon Kindle Fire App

### ISSUE THREAD

**Issue by hermosabeach** [shadowsocks/shadowsocks-android#2293]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**

I'd love to use this app on my Amazon Kindle Fire. 

**Describe the solution you'd like**

Add the latest version to the Amazon App store or add some documentation on how to install one of the builds on the Kindle Fire.

**Describe alternatives you've considered**

An older version of the Shadowsocks App is on the Amazon App store, but I'm not sure if it's legitimate.  It works, but doesn't support V2ray or any of the latest features.

**Additional context**

Thanks for supporting this project!

**Comment by madeye** [comment]
Just install the apk through ADB.

https://github.com/shadowsocks/shadowsocks-android/releases

**Comment by gs666** [comment]
the apk can't be installed to Kindle Fire?

**Comment by hermosabeach** [comment]
I found it's even easier, just enable installing “Apps from Unknown Sources“.  You can download the APK from the release page.  Same for the V2ray plugin.  

For my kindle fire hd 8, I needed to use the armeabi-v7a apk version.  The QR code scan doesn't work, it requests additional libraries be installed.  Everything else seems fine.

There is a shadowsocks app already in the Amazon App store, but it's an older version.  Not sure if it's by the same authors.
