### ISSUE TITLE
Feature Request: DDNS option

### ISSUE THREAD

**Issue by miaomi** [shadowsocks/shadowsocks-android#2301]
**Is your feature request related to a problem? Please describe.**
I'm using tunnel for selected apps on phone to connect home private cloud servers with lan address. The ss server is installed on a router with DDNS setup. The WAN connection on router was with dynamic IP.
The tunnel was inaccessible every time WAN IP changes.

**Describe the solution you'd like**
Would be nice if there's an option optimized for connect ss servers with DDNS.

**Describe alternatives you've considered**
Force DNS resolve every n seconds.
Kill and restart the android client app with some task manager while DNS change detected. Need an option to start selected profile on app start.

**Comment by miaomi** [comment]
Refresh resolve on connection fail without adding new option.

**Comment by max2max** [comment]
What about update server by tasker?
DDNS will performs best with the nameserver, or it will spend more time on waiting for ddns cache updated.

**Comment by madeye** [comment]
Due to the DNS cache, I don't think you can switch servers with DDNS dynamically.

One workaround is using Tasker to restart the shadowsocks service when a webhook is triggered, say your server's IP is updated.

**Comment by miaomi** [comment]
Switch IP with some delay is acceptable. The issue is the IP only updated on profile restart. Would you share more details how to restart it with Tasker? Profile not restart with app restart.

**Comment by madeye** [comment]
Can we bypass any DNS queries for the shadowsocks server's hostname to the local resolver? @zonyitoo 

It should help solve this issue.

**Comment by zonyitoo** [comment]
Hmmm... That's the thing I want to avoid, which will eventually have no DNS resolve cache for server's hostnames.

**Comment by zonyitoo** [comment]
Reverted back to old logic.

**Comment by madeye** [comment]
@zonyitoo If China route based ACL is enabled, it's possible that DNS resolver always take the remote response for shadowsocks server's hostname, even the remote response is invalid.

```
 [shadowsocks_service::local::dns::server] pick remote response (response): Err(Custom { kind: Other, error: ProtoError { kind: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) } })
```

**Comment by madeye** [comment]
It looks the server hostname resolver is actually not bypassed.

**Comment by madeye** [comment]
On Android, I cannot see any traces from DNS resolver, which is quite weird. What I expect is something like this:

```
DNS resolved test.com:8038 with customized 0.0010579s
```

**Comment by madeye** [comment]
Okay, I know the root cause. It's a problem of the plugin, nothing wrong with shadowsocks-rust.
