### ISSUE TITLE
华为Mate20X链接VPN后，无法发送数据

### ISSUE THREAD

**Issue by lcc47uk49** [shadowsocks/shadowsocks-android#2305]
同一个VPS，华为手机连上后，无法发送数据。其他手机就可以，为什么呢？
报错失败：Read error: ssl=0xc6e32dc8:Failure in SSL library, usually a protocal error...

**Comment by Mygod** [comment]
Unless some more helpful information is provided, I will regard this as a vendor bug for now.

**Comment by luo-chuan** [comment]
如果系统是EMUI 10的话。设置—更多连接—加密DNS—默认关闭，勾选自动。就可以用了。
参考： https://club.huawei.com/thread-21446964-1-1.html
