### ISSUE TITLE
仅代理局域网地址

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-android#2311]
可以加一个"仅代理局域网地址"的路由选项吗？比如在公司里开了一个ss-server，通过这个选项可以很方便的访问公司的内网资源

**Comment by edison0354** [comment]
规则选成custom rules，然后把本地IP都丢进去即可……
你可以先看一下公司网段在多少
> 
1.0.0.0/24
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.0.0.0/24
192.0.2.0/24
192.88.99.0/24
192.168.0.0/16
198.18.0.0/15
198.51.100.0/24
203.0.113.0/24
224.0.0.0/4
240.0.0.0/4
255.255.255.255

**Comment by 0x112** [comment]
好的👌
