### ISSUE TITLE
android can't connect to local domain via shadowsocks

### ISSUE THREAD

**Issue by petrikoz** [shadowsocks/shadowsocks-android#2314]
**Describe the bug**
I have a server with `shadowsocks-libev`, `dnsmasq` and `nginx`.

Dnsmasq configured with `address=/my.domain/127.0.0.1` and available only for requests from localhost. Nginx configured with `server_name .my.domain`. This allows me to connect to my private web-page through shadowsocks.

On my Linux machines, all work well: I have local socks5-proxy and can use it in any software (ex. Firefox).

But it doesn't work on Android: mobile Firefox can't connect to my secret page.

I enabled `--log-queries` in Dnsmasq's config and saw DNS requests go to it. And Dnsmasq's answers are correct (for Linux-connections it looks similar):

```
query[AAAA] my.domain from 127.0.0.1
config my.domain is ::1
query[A] my.domain from 127.0.0.1
config my.domain is 127.0.0.1
```
Also, I tried [IP Tools](https://play.google.com/store/apps/details?id=com.ddm.iptools). And its "Lookup" tool gets the correct answer.

**Expected behavior**

**Smartphone**
 - Resurrection Remix LP v5.5.9 (Android 5.1.1)
 - Device: Oukitel K4000
 - Version: 4.8.4

**Configuration**
* [x] IPv4 server address
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [x] All
* [x] IPv6 route
* [x] Apps VPN mode
* Remote DNS: 127.0.0.1
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect

**Comment by Mygod** [comment]
Check remote acl.

**Comment by petrikoz** [comment]
Acl to what?

**Comment by Mygod** [comment]
Okay this is fundamentally impossible. You need to connect to the local socks5 port to access remote localhost.

**Comment by petrikoz** [comment]
I thinked if Shadowsocks enabled for concrete app (ex. Firefox) all requests from it will sent through tunnel. Or I did mistake?

Is Shadowsocks enough for send all requests of selected app from my phone to my remote server through tunnel? Or I need more software / configuration for this?
