### ISSUE TITLE
Android10 报错libss- local exits too fast

### ISSUE THREAD

**Issue by ddgweb** [shadowsocks/shadowsocks-android#2315]
![er.jpg](https://i.loli.net/2019/09/27/FDvji34tTBRmxPe.jpg)
Android10 报错libss- local exits too fast

**Comment by fadedHYC** [comment]
你好，请问你导入工程运行调试时候出现这个错误吗？
Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\20.0.5594570\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\projectTest\shadowsocks-android-master\core\src\main\jni\Android.mk NDK_APPLICATION_MK=D:\projectTest\shadowsocks-android-master\core\src\main\jni\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=D:/projectTest/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib -j6 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\arm64-v8a" >NUL 2>NUL || rem
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe [arm64-v8a] "Gdbserver      ": "[aarch64-linux-android] D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdbserver"
copy /b/y "C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\20.0.5594570\build\\..\prebuilt\android-arm64\gdbserver\gdbserver" "D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib\arm64-v8a\gdbserver" > NUL
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe [arm64-v8a] "Gdbsetup       ": "D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup"
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path D:/projectTest/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a" > D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../toolchains/llvm/prebuilt/windows-x86_64/sysroot D:/projectTest/shadowsocks-android-master/core/src/main/jni D:/projectTest/shadowsocks-android-master/core/src/main/jni/mbedtls/include D:/projectTest/shadowsocks-android-master/core/src/main/jni/pcre/dist C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/20.0.5594570/build//../sources/cxx-stl/system D:/projectTest/shadowsocks-android-master/core/src/main/jni/libancillary D:/projectTest/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv4 D:/projectTest/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/src/include/ipv6 D:/projectTest/shadowsocks-android-master/core/src/main/jni/badvpn/lwip/custom" >> D:\projectTest\shadowsocks-android-master\core\build\intermediates\ndkBuild\debug\lib/arm64-v8a/gdb.setup

process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/projectTest/shadowsocks-android-master/core/src/main/jni/redsocks/base.c', needed by `D:/projectTest/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/redsocks/redsocks/base.o'.  Stop.

**Comment by pjy612** [comment]
华为 mate30 同样提示 libss- local exits too fast
只有 4.6.5 能进行连接，但是连接后。并不能正常使用。
SSRR倒是能用，但是SSRR停用后不会自动关闭，需要到VPN连接里手动关闭。

**Comment by 212858854** [comment]
> 
> 
> 华为 mate30 同样提示 libss- local exits too fast
> 只有 4.6.5 能进行连接，但是连接后。并不能正常使用。
> SSRR倒是能用，但是SSRR停用后不会自动关闭，需要到VPN连接里手动关闭。

那你现在可以用了吗？

**Comment by pjy612** [comment]
> > 华为 mate30 同样提示 libss- local exits too fast
> > 只有 4.6.5 能进行连接，但是连接后。并不能正常使用。
> > SSRR倒是能用，但是SSRR停用后不会自动关闭，需要到VPN连接里手动关闭。
> 
> 那你现在可以用了吗？

之前一直用SSRR，现在刚试了下最新版v5.1.1 连接正常
