### ISSUE TITLE
希望能不要求GMS

### ISSUE THREAD

**Issue by unl89** [shadowsocks/shadowsocks-android#2318]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**

我喜欢用没有装GMS的lineageos

**Comment by luo-chuan** [comment]
附议，华为Mate 30已经没法安装GMS了

**Comment by madeye** [comment]
GMS is optional. Read the FAQ for more details.

**Comment by yobdc** [comment]
+1
