### ISSUE TITLE
2.6.4打不开g+和 play store

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#232]
2.6.3没问题，退回去了。配置文件是同样的。

**Comment by myliyifei** [comment]
我这里升级都是正常的
2015年1月27日 下午8:34于 "Michael Lu" <notifications@github.com>写道：

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-android/commit/6c1ae6893148cf504506d7d37838f3bd86fd5a4d
