### ISSUE TITLE
Seems VPN mode doesn't work on multi-user of Android Q

### ISSUE THREAD

**Issue by edison0354** [shadowsocks/shadowsocks-android#2320]
Please read contributing guidelines. Thanks.

**Describe the bug**
Everything works well in the primary user, but when switching to the second user, VPN mode is connected, but by pressing test, it always shows failed to connect to google, nor does anything works through VPN.

I copy paste the APP data folder from primary user to second user, so all the settings are exactly the same.

After changed to transproxy mode, it can pass the connection test again, so I guess maybe it's only about the VPN mode.

It worked well in Android Pie, maybe something changed? (Or is there something wrong with my phone? Can anyone help to test it? Thanks.)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android 10
 - Device: Google Pixel XL
 - Version: v4.8.4
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Sounds like a Google issue. Try different VPNs. If it does not work, report to Google.

**Comment by edison0354** [comment]
Actually it's very strange...
It can work with 'bypass LAN'
But will not work with 'bypass LAN & Chinalist'
So I assume it's not a Google issue, but something related to bypass all the China IP.

**Comment by Mygod** [comment]
Cannot reproduce on emulator. Report to Google's issue tracker instead.

**Comment by saspol** [comment]
Same problem on Samsung Galaxy S9+, VPN mode 1) Cannot catch any particular application traffic. All applications together proxyfying through VPN works.
2) Cannot see in settings any of applications of working profile.
![Screenshot_20201002-093704_Settings](https://user-images.githubusercontent.com/16889941/94879467-dd54f180-0492-11eb-81b0-04d2d24ded38.jpg)
