### ISSUE TITLE
能不能对服务器名称自动清理多余的空格

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-android#2321]
一个小小的提升用户体验的优化。
经常遇到朋友设置的时候不小心输入空格还看不出来问题，提示服务器名无效。

**Comment by Mygod** [comment]
I guess a sanity check can be added.

**Comment by DearTanker** [comment]
@Mygod Very looking forward, thank you.

**Comment by Buffer2Disk** [comment]
@madeye trim() only having leading and trailing whitespace removed , maybe replace() function will be better
