### ISSUE TITLE
cannot open router's page 192.168.*.* when using bypass LAN

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#2322]
Please read contributing guidelines. Thanks.

**Describe the bug**
cannot open router's page when using bypass LAN / bypass LAN&China.
router's page is 192.168.1.1
however smb is accessible, which is weird to me
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 10
 - Device: Pixel 3 XL
 - Version: 4.8.4
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-128-gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by glu2000** [comment]
用google vm实例链接不上网络了，求指教
