### ISSUE TITLE
process_begin: CreateProcess(NULL, "", ...) failed.

### ISSUE THREAD

**Issue by Jeela13** [shadowsocks/shadowsocks-android#2325]
I just clone this code and open in android studio but its not work. and give this error:
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Sajeel/AndroidStudioProjects/Pojects/shadowsocks-android-master/core/src/main/jni/redsocks/base.c', needed by `C:/Users/Sajeel/AndroidStudioProjects/Pojects/shadowsocks-android-master/core/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/redsocks/redsocks/base.o'.  Stop.

**Comment by whatisforever** [comment]
使用Android Studio克隆代码时，许多依赖文件（第三方库）并没有下载，使用以下命令下载全部代码 git clone --recurse-submodules <repo>
