### ISSUE TITLE
使用分应用VPN之后，YouTube不能使用

### ISSUE THREAD

**Issue by decentone** [shadowsocks/shadowsocks-android#2326]
使用分应用VPN之后，YouTube无法使用。不使用分应用代理，youtube可以使用。

系统版本：Android 10.0
shadowsocks版本：4.8.5

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [] Auto Connect
* [ ] TCP Fast Open

**Comment by dyxushuai** [comment]
@decentone 问题修复了嘛

**Comment by wupeng1211** [comment]
没问题啊，你DNS的问题吧
