### ISSUE TITLE
希望能加入订阅功能

### ISSUE THREAD

**Issue by noir1216** [shadowsocks/shadowsocks-android#2328]
一个一个加入节点还是挺麻烦的，希望能加入订阅功能

**Comment by yogaskung** [comment]
#1610

**Comment by yogaskung** [comment]
用户:订阅？
madeye:No plan for this,
用户:去广告？
madeye:No plan for this,
用户:滋瓷ssr？
madeye:No plan for this,
用户:服务器批量测速+ping值？
madeye:No plan for this,
用户:翻墙路由器？
madeye:No plan for this,
