### ISSUE TITLE
Failed to detect internet connection

### ISSUE THREAD

**Issue by wonderpai** [shadowsocks/shadowsocks-android#2331]
Please read contributing guidelines. Thanks.

**Describe the bug**
Cannot get connected. It shows connected but if you run the test it reports error. It says: Fail to detect internet connection: read error: ssl=0x740ebd5008: Failure in SSL library, usu... (it didn't show the rest words... Also the number after ssl= always changing)

I tested the port and the server from China mainland and they are save (not blocked). 

Everything was fine before the National days of Oct. After that, cannot get connected quite often. Or connected but breakdown during the using.

**To Reproduce**
1. Open the android app
2. Click on the icon of air plane
3. Click "connected, tap to check connection"

**Expected behavior**
Get connected and won't (or less) break the link during my usage.

**Screenshots**
![28a0a63e5c25c5d5286d0614a347d99](https://user-images.githubusercontent.com/56945784/67452602-4fec0900-f656-11e9-9306-112d2fb65f4c.jpg)

**Smartphone (please complete the following information):**
 - Android 9
 - Device: Vivo Z3 V1813BT
 - Version: V4.8.5
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [X ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-CFB / AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [X ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Looking forward to your reply!

**Comment by wonderpai** [comment]
Hi developer, I searched the answer of the other issues and found one issue has quite similar issue with mine. It mentioned that China Mobile cannot get connected but China Unicom could do. So I just switched to China Unicom and this issue has not been showing up for the whole afternoon.

I am still testing now.

**Comment by rcz0315** [comment]
Try filling in the server's ipv6 address and then connecting.

**Comment by XiaoXiaoLui** [comment]
My Huawei phone has the same problem today. 
I didn't change any configure recently and it had been working without any problem for more than a year.  
Also, the shadowsock connection on my computer works well.
My card is China Telecom but ss connection on WIFI still fails, so I think maybe Huawei phone bans shadowsocks....

**Comment by rcz0315** [comment]
Recently upgraded ROM?

**Comment by wonderpai** [comment]
Continue to report my test result. After I switched to China Unicom, I never met similar issues. My current app version is 4.8.5. I now believe very likely the issues I met is caused by the telecom operators. And based the fact that this issue only show up after the national days, maybe is some new method to block the connection. Now I wish similar problem won't show up on my new tele-card.
