### ISSUE TITLE
DNS resolve very slow in transproxy mode

### ISSUE THREAD

**Issue by bluesky139** [shadowsocks/shadowsocks-android#2333]
**Describe the bug**
Enable shadowsocks in transproxy mode, redirect 53 port to 5450 to let all dns resolve requests are handled by shadowsocks, dns resolve become very slow.

**To Reproduce**
1. Enable shadowsocks in transproxy mode.
2. Add iptable rules:

> iptables -w -t nat -N Shadowsocks
iptables -w -t nat -A Shadowsocks -o lo -j RETURN
iptables -w -t nat -A Shadowsocks -d 127.0.0.1 -j RETURN
iptables -w -t nat -A Shadowsocks -m owner --uid-owner $ShadowsocksUid -j RETURN
iptables -w -t nat -A Shadowsocks -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5450
iptables -w -t nat -A Shadowsocks -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5450
iptables -w -t nat -A Shadowsocks -p tcp -j DNAT --to-destination 127.0.0.1:8200
iptables -w -t nat -A OUTPUT -j Shadowsocks

3. Resolve any domain by browser or dig like `dig @127.0.0.1 -p 5450 qq.com`
4. Resolve response is very slow.

**Expected behavior**
DNS resolve fastly.

**Smartphone (please complete the following information):**
 - Android 9.0
 - Device: Google Nexus 5
 - Version: v4.8.5
 - Last version that did not exhibit the issue: v4.6.5

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

**Additional context**
If use dig to test on 5450 port, by removing `iptables -w -t nat -A Shadowsocks -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5450` will let resolve become fast.

I know overture is replaced by a simple dns resolver after v4.6.5, maybe something related to this.

**Comment by madeye** [comment]
> iptables -w -t nat -A Shadowsocks -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5450
> iptables -w -t nat -A Shadowsocks -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5450

You should not redirect all the DNS requests to local, which also redirects the internal resolver's traffic to itself.

**Comment by bluesky139** [comment]
Ok, by adding `iptables -w -t nat -A Shadowsocks -m owner --uid-owner 0 -j RETURN` to pass system internal resolver, problem is resolved.

I think the point is the old overture dns resolver resolve all domains by itself, not system internal resolver, so the old version has no problem.
