### ISSUE TITLE
同一个节点shadowrocket可以使用，安卓上shadowsocket连不上？

### ISSUE THREAD

**Issue by Xnqi** [shadowsocks/shadowsocks-android#2337]
烦死了

**Comment by Xnqi** [comment]
打错了，安卓上shadowsocks死活连不上

**Comment by Zhangdelu** [comment]
可能是因为服务器上安装的是shadowsocksR, 安卓或者PC端就只能用相应的shadowsocksR.

**Comment by Xnqi** [comment]
> 可能是因为服务器上安装的是shadowsocksR, 安卓或者PC端就只能用相应的shadowsocksR.

不是的，小火箭上也是ss模式。节点是购买于https://portal.shadowsocks.center的节点

**Comment by hczhch** [comment]
最近也出现了连不上的问题
