### ISSUE TITLE
server config got easily removed by mistake by gesture

### ISSUE THREAD

**Issue by skywalkerytx** [shadowsocks/shadowsocks-android#2339]
**Describe the bug**
server config could be removed by swipe left, on certain phone model which do not have button/soft button, 

**To Reproduce**
quit the program(or using return to home gesture)

on nex S, QUIT is a gesture that swipe up from the right bottom of the screen.
sometimes it is both recognized as quit by system and delete config by program. cancel is not helping by this case.
hope there would be a way to disable this feature.

**Expected behavior**
server config should not be removed.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 9
 - Device: vivo nex S
 - Version: from google play latest version
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
undo
