### ISSUE TITLE
Can't select config file on Amazon FireTV Stick 

### ISSUE THREAD

**Issue by wangyongcong** [shadowsocks/shadowsocks-android#2340]
Release version: shadowsocks-armeavi-v7a-4.8.5
Device: Amazon FireTV Stick

1. Go to 'Import config from file...'
2. Then the sidebar show up without focus
3. With TV remote controller, I can't move focus to the sidebar to select config file

**Comment by Mygod** [comment]
Install 3rd party explorer.

**Comment by samirmh-dev** [comment]
Still same problem on `shadowsocks-tv-armeabi-v7a-5.1.4.apk`.

Steps:

1. Open Shadowsocks app
2. Select Choose from remote...
3. Can't select any source. Screen freezes

![102520154627](https://user-images.githubusercontent.com/54883542/97106176-7dd8b300-16d9-11eb-97cd-2bc0cdad52ea.png)
