### ISSUE TITLE
libss-local exits too fast （exit code 255）

### ISSUE THREAD

**Issue by hnsylzg** [shadowsocks/shadowsocks-android#2343]
**Describe the bug**
连接服务器 提示libss-local exits too fast （exit code 255）不能连接
更新android10后出现的

**Smartphone (please complete the following information):**
使用的是小米8 ，miui11 9.10.31 andorid 10

**Comment by hnsylzg** [comment]
更新kcptun到1.0解决

**Comment by sunqb** [comment]
你好，请问kcptun是更新服务端吗？
