### ISSUE TITLE
MIUI11.0.2 上 创建 VPN 服务权限不足

### ISSUE THREAD

**Issue by darrennong** [shadowsocks/shadowsocks-android#2352]
在Mi9 升级到MIUI11.0.2以后编译或者下载安装出现 创建 VPN 服务权限不足 的问题，系统VPN设置里面没有SS。

**Comment by darrennong** [comment]
当蓝灯设置为保持连接时出现的问题

**Comment by muyexi** [comment]
@darrennong 你是不是安装了SSR，在设置中先取消SSR的VPN
