### ISSUE TITLE
Instagram image can not load on Huawei mate 30 pro

### ISSUE THREAD

**Issue by Buffer2Disk** [shadowsocks/shadowsocks-android#2354]
**Describe the bug**
Instagram image can not load on Huawei mate 30 pro when use Bypass lan and China mode, but when i switch to Global mode , it works fine.
 
Another strange phenomenon is that it doesn't work(it means that instagram image can not load) when i use Gfwlist mode directly  while it works fine when i change mode from Global to Gfwlist

**Smartphone (please complete the following information):**
Android/Chrome OS version: 10
Device: Huawei mate 30 pro
Version: 4.8.3 , 4.8.5
Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: RC4-MD5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Comment by madeye** [comment]
Disable IPv6 on your VPS server.

This problems happens when your server's IPv6 address is blocked by Instagram.

**Comment by Buffer2Disk** [comment]
> Disable IPv6 on your VPS server.
> 
> This problems happens when your server's IPv6 address is blocked by Instagram.
> 
> Search the issue tracker for more details.

Thanks for your reply , i have not enable IPV6 on my server , and iphone works fine

**Comment by madeye** [comment]
If so, enable "send DNS over UDP" and try again.

**Comment by muyoucun** [comment]
直接写中文好了
我的Huawei上的配置和你一样。在ins上能加载图片阅览，但是不能上传图片
请问你有什么解决办法了吗？
