### ISSUE TITLE
Read error: ssl=0×7c17a6f908: Failure in SSL library, usually a protocol error...

### ISSUE THREAD

**Issue by SeiFujibayashi** [shadowsocks/shadowsocks-android#2357]
启动以后，当你测试网络连接的时候，软件有时候可以返回响应时间，但有时候则会提示“Read error: ssl=0×7c17a6f908: Failure in SSL library, usually a protocol error...”。

After startup, when you test the network connection, the software can sometimes return the response time, but sometimes it will prompt "Read error: ssl=0×7c17a6f908: Failure in SSL library, usually a protocol error...".

**Comment by wangfeng35** [comment]
移动4G网络？

**Comment by oneone1995** [comment]
@wangfeng35 联通4G有这个问题

**Comment by Ngwind** [comment]
为什么close了？
