### ISSUE TITLE
[新功能]建议UDP转发的时候，可以自定义远程DNS，或者调用VPS自身设置的DNS解析。

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-android#236]
因为我发现 VPS自己的DNS解析出来的IP 有时候更合适一些。

比如我的一个VPS,解析youtube.com出来的IP， 从VPS ping过去延迟才1.x MS, 而用8.8.8.8解析出来的IP，延迟有50.x ms。

**Comment by madeye** [comment]
不会提供自定义 DNS 的。

**Comment by madeye** [comment]
此类定制化需求（#235 和 #236）建议自行修改代码，并编译 APK。
