### ISSUE TITLE
电脑使用基本无问题，手机使用流量连接经常连接不上

### ISSUE THREAD

**Issue by TzyyJye** [shadowsocks/shadowsocks-android#2365]
MAC电脑使用基本无问题，手机使用流量连接经常连接不上，很奇怪

**Comment by AlexMao9527** [comment]
ss现在是有问题的，应该是中国移动限制了流量。用ssr吧，我用ssr没有问题。

**Comment by wangfeng35** [comment]
> ss现在是有问题的，应该是中国移动限制了流量。用ssr吧，我用ssr没有问题。

搞不懂为啥移动才有这个问题 而且改用ssr没问题

**Comment by v7lin** [comment]
同问，自己搭了个ss，电脑可以正常使用，手机链接同一个WI-FI却不能用

**Comment by richardplas** [comment]
+1

**Comment by richardplas** [comment]
> ss现在是有问题的，应该是中国移动限制了流量。用ssr吧，我用ssr没有问题。

ssr是啥？

**Comment by v7lin** [comment]
同一手机，统一WI-FI，用12vpn上的Shadowsocks账号却能正常使用，求解
