### ISSUE TITLE
扫码功能应该有bug，相片是糊的扫不出二维码

### ISSUE THREAD

**Issue by 4fm** [shadowsocks/shadowsocks-android#2366]
**Describe the bug**
扫码不清晰扫不出二维码，像是预览的相片。
直接使用自带相机或者用微信扫码相片正常，应该不是手机固件的问题。

**Smartphone (please complete the following information):**
 - Android/ Pixelexperience 10 official ROM
 - Device: Redmi Note 7 Pro
 - Version: Lastest from Google Store

**Comment by Mygod** [comment]
Use third party scanners.
