### ISSUE TITLE
Optimization about application in Multi-Process

### ISSUE THREAD

**Issue by giswangsj** [shadowsocks/shadowsocks-android#2367]
When using Multi-Process，onCreate() in Application will process twice

`class App : Application() {
    override fun onCreate() {
        super.onCreate()
        Core.init(this, MainActivity::class)
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
    }
}`

so the Core.init() will process twice which is redundant.

I think you can compare the main process name with current process name to avoid it, like this:

`class App : Application() {
    override fun onCreate() {
        super.onCreate()
	var processName = getProcessName()
        processName?.let{
              if(it == this.packageName){
                   Core.init(this, MainActivity::class)
		   AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
              }
         }
    }
}

/**
     * get the name of process
     * @return
     */
    public static String getProcessName() {
        try {
            File file = new File("/proc/" + android.os.Process.myPid() + "/" + "cmdline");
            BufferedReader mBufferedReader = new BufferedReader(new FileReader(file));
            String processName = mBufferedReader.readLine().trim();
            mBufferedReader.close();
            return processName;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
`

**Comment by Mygod** [comment]
Expected behavior.

**Comment by giswangsj** [comment]
I am sorry , I tried it and found that 'Core.init(this, MainActivity::class)' must process twice，or it will crash in :bg process , because :bg process use Core class
