### ISSUE TITLE
为什么我的shadowsocks经常连不上

### ISSUE THREAD

**Issue by joeaki1983** [shadowsocks/shadowsocks-android#237]
nexus5手机，4.4.4系统，联通3g 经常用着用着就突然打不开网页 国内外都不行，需要重新断开再连接才恢复，这是什么状况？如何解决

**Comment by joeaki1983** [comment]
shadowsocks 2.6.4版本

**Comment by madeye** [comment]
无法复现。检查你是否限制了后台服务数量，或安装了进程清理软件。

**Comment by joeaki1983** [comment]
大神回复了!打不开网页的状况通常是，chrome的上蓝色进度条卡在中间不动了！好像无法完成域名解析的样子，再刷新也是一样，只有重新连接，我没有限制过后台服务数量，这在哪里看。只装了一个百度手机助手但是从来没有进行过进程清理，另外我用的是nat模式，vpn模式速度明显慢一些，instagram很多图片打不开，不知道为什么。

**Comment by madeye** [comment]
另外建议升级到 5.0 系统后再试试。

**Comment by joeaki1983** [comment]
刚才回复的时候又卡住了导致回复发不出去，卡住的同时我去刷了下QQ  QQ 和微博是可以通的，但是chrome就是无法打开网页，本地翻墙都不行，卡住一段时间以后，但是翻墙就是打不开，只有重新连接

**Comment by joeaki1983** [comment]
卡住一段时间以后 本地突然可以打开，翻墙就是不行 只有重新连接
