### ISSUE TITLE
Custom Rules issue

### ISSUE THREAD

**Issue by yuzhu** [shadowsocks/shadowsocks-android#2372]
Please read contributing guidelines. Thanks.

**Describe the bug**
I want to customize the china list using custom rules, so I import from a china-list url. The behavior is not identical to using china list. 
For example, google.com is not accessible, seems like it is being routed though the ss-server. 

**To Reproduce**
1. set up a route using custom rules
2. add `https://raw.githubusercontent.com/shadowsocks/shadowsocks-android/master/core/src/main/assets/acl/china-list.acl` to the custom rules as a URL to online config.
3. connection test fails

**Expected behavior**
Identical behavior to selecting china list

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred] 9
 - Device: [e.g. Google Pixel XL] Oneplus 5 T
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"] 4.8.5
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [x] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by yuzhu** [comment]
I think it is actually combining what is in gfwlist with my custom rules??

**Comment by madeye** [comment]
I think what you want is GFWList rather than ChinaList: 

https://raw.githubusercontent.com/shadowsocks/shadowsocks-android/master/core/src/main/assets/acl/gfwlist.acl

**Comment by yuzhu** [comment]
i am outside of the wall. I want to use a customized list, I want to bypass the list for Google, so that's why I am using the ChinaList. In any case, when my customized list is empty, I can not access google, indicating the traffic is being routed through the ss-server. My ss-server is inside the wall.

**Comment by madeye** [comment]
If the custom list is empty, no traffic will be redirected to the remote.

The only reason you cannot access google should be related to DNS poisoning.

Change the remote DNS to `208.67.222.222:443` in your server profile then try again.

**Comment by yuzhu** [comment]
thanks! that was indeed the problem

**Comment by yuzhu** [comment]
actually i find myself unable to cast to chromecast, i assume local addresses are bypassed because my custom list is empty? do i need to edit hosts file or something like that?

**Comment by madeye** [comment]
Use app VPN to bypass specific apps for Chromecast.

Chromecast on LAN is not supported in China List mode or customized ACL mode.
