### ISSUE TITLE
ss-tunnel function in Android version

### ISSUE THREAD

**Issue by zhangjint5** [shadowsocks/shadowsocks-android#2373]
It is recommended to implement ss-tunnel function in Android version

Ask for help. Is there a suitable alternative now. I have an OpenVPN server that needs to be brought to the mobile phone through ss-stunnel to provide services for the LAN.

**Comment by madeye** [comment]
I don't think your problem is related to this project.

**Comment by Mygod** [comment]
Feel free to fork.

**Comment by lockywolf** [comment]
Yes, I was also very surprised to see ss-tunnel missing from the Android version.
