### ISSUE TITLE
建议APP启动后自动连上

### ISSUE THREAD

**Issue by redstoneleo** [shadowsocks/shadowsocks-android#2374]
电脑版软件启动后就会自动连上，手机版启动后每次都要点一下才能连上，麻烦了点，建议APP启动后自动连上

**Comment by pingL** [comment]
android Q 后台管理权限应该不允许这种自启动吧。

**Comment by redstoneleo** [comment]
不是软件开机启动，而是手动打开软件后软件自动连接上VPN

**Comment by Mygod** [comment]
Feel free to fork and make the modifications, or use auto start.

**Comment by redstoneleo** [comment]
auto start是开机启动的意思吗？

**Comment by Mygod** [comment]
Yes.

**Comment by redstoneleo** [comment]
奇怪了，这个建议就这么一文不值吗？

**Comment by tianjx98** [comment]
> 奇怪了，这个建议可以减少一步操作，难道就这么无足轻重吗？

可以直接把这个设置为像数据网络开关那样的按钮加到下拉栏，点一下就能开启。

**Comment by redstoneleo** [comment]
@tianjx98 你的安卓是什么版本？我的6.0找不到去哪里设置

**Comment by tianjx98** [comment]
> @tianjx98 你的安卓是什么版本？我的6.0找不到去哪里设置

我是安卓9，小米系统，直接在编辑开关里面最下面就有应用自带的开关。

**Comment by redstoneleo** [comment]
这让我想起了桌面快捷小组件，我找了一下还确实有shadowsocks的桌面快捷小组件，但是有个问题就是点击了虽然开上VPN了，但是小组件图标不会变色响应操作成功，所以（1）建议修正这个问题；（2）如果安装成功shadowsocks后自动创建shadowsocks的桌面快捷小组件，那会方便很多人，希望考虑这个建议。谢谢！
