### ISSUE TITLE
FC when trying to scan QR code since v4.8.6

### ISSUE THREAD

**Issue by hrzhu** [shadowsocks/shadowsocks-android#2375]
The title is self-explanatory.

1 Click Scan QR code from menu, shadowsocks crashes immediately.

 - Android/Chrome OS version: [lineage-16.0-20191204]
 - Device: [Oneplus 5t/Mi 6X]
 - Version: [v4.8.6]
 - Last version that did not exhibit the issue: [v4.8.5]

**Comment by Mygod** [comment]
Yeah let's use that fix for now until Google releases a new artifact with
that bug fixed.

**Comment by Mygod** [comment]
Also I see I missed the latest 2 releases... I will try to catch up with stuff in this repo over the next few days.
