### ISSUE TITLE
内嵌DNS服务器 建议增加 本地DNS域名 列表，或者 局域网IP 额外处理

### ISSUE THREAD

**Issue by kkHAIKE** [shadowsocks/shadowsocks-android#2376]
因为公司使用 chromeos 系统，使用 此app 最为稳定，但遇到了如下问题：

公司有内网域名，使用了 内部DNS。之前都是要上 g网 才开启$$，发现此时会访问不了内网，关闭$$才能访问，一直这样开关会造成使用的程序总是在重连。

后面拜读了源码后。梳理了现有的 本地DNS 逻辑(kotlin不熟,有错误请指正)。
*远程DNS* 就是远程 $$srv 访问的 DNS

1. HOSTS 文件写死的最优先(chromeos 无法改写hosts, chrome插件?)
2. ALL | BYPASS_LAN 强制使用 远程DNS
3. BYPASS_C | BYPASS_LAN_C | FKLIST | CUSTOM_RULES 使用如下

逻辑：

1. googleapis 域名直接使用 远程DNS
2. 原始DNS 解析的 结果IP 若不在 c_ip_list 也是使用 远程DNS

从上面看来。。当前方案对 LAN 不合理。。可以作出如下改进(按优先级排序)
1. 原始DNS 最后 ip范围确认 使用 c_ip_list+lan
2. 远程DNS 解析超时(10s)，信任 原始DNS 结果
3. 增加 DNS bypass 域名列表 功能

🙏
-
突然发现，如果DNS被污染到了 LAN IP 也没辙

**Comment by Mygod** [comment]
This app uses a configurable hosts (not `/etc/hosts`) in the settings.

**Comment by kkHAIKE** [comment]
@Mygod thx,got it

**Comment by moralrebuild** [comment]
@Mygod 能具体说明一下格式吗？逐行给按照标准的hosts文件： ip<whitespace>hostname ， 导入后仅认为是一行；加入分号后识别为多行但仍然解析错误。目前我只能配置一行。
