### ISSUE TITLE
分应用VPN多个APP相同的ID

### ISSUE THREAD

**Issue by dcty** [shadowsocks/shadowsocks-android#2380]
![c1aa590647837a0297b6841e1b2a4dd](https://user-images.githubusercontent.com/792929/70516680-6270c200-1b72-11ea-9bed-dd66c4d3ccf3.jpg)
com.android.settings是1000，华为的一些APP也是1000，只要开关setting会联通开关其他的。

**Comment by Mygod** [comment]
Expected behavior.

**Comment by alexlee728** [comment]
> Expected behavior.

why？
