### ISSUE TITLE
After connect to SS server , local network working abnormally

### ISSUE THREAD

**Issue by wuhgit** [shadowsocks/shadowsocks-android#2387]
**Describe the bug**
After connect to SS server , local network working abnormally.

**To Reproduce**
Connect to SS server with "Bypass LAN & mainland China".
VLC Player can not found Dlna server on local network.
AirDroid can not connect with phone's local IP on PC.
but add these APP to 'Apps VPN mode' with Bypass mode , everything work fine.

**Expected behavior**
Because the profile is already ‘Bypass LAN’ , so make these APPs work fine on local network, not need to set in 'Apps VPN mode'  again.

**Screenshots**
Sorry for No Screenshots

**Smartphone (please complete the following information):**
 - Android version: Android 10 with December 5,2019 security patch
 - Device: Redmi K20 Pro
 - Version: v4.8.7

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1.1.1.1
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
None

**Comment by Geekerzz** [comment]
My Google photos, Youtube cannot connect to google when "GFW" mode is on, but my chrome still can at the same time. "ALL" mode has no such situation :(

**Comment by madeye** [comment]
#2361 

@Mygod It looks Google broke something in their recent security patches.
