### ISSUE TITLE
Plugin: onInitializePluginOptions(): first key with null value will disappear

### ISSUE THREAD

**Issue by IrineSistiana** [shadowsocks/shadowsocks-android#2391]
**Describe the bug**
after plugin call `saveChanges(options)` , everything looks fine, config stored successfully, it's string can be seen in shadowscosk-android UI. For example, `option1;option2;option3;arg4=value`

but when loading saved config using `onInitializePluginOptions(options: PluginOptions)`, key `option1` disappeard. Only got `option2;option3;arg4=value`

first key with null value will always disappear.

`option1;option2;option3;arg4=value` -> `option2;option3;arg4=value`

first key has a string value won't disappear. 

`arg1=value;option2;option3;arg4=value` -> `arg1=value;option2;option3;arg4=value`

**Pluging version**
1.3.1

**shadowsocks-android version**
4.8.7

**Comment by IrineSistiana** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/858a7f1dde8f7b2cd9dd829202449e217fa0ab24/plugin/src/main/java/com/github/shadowsocks/plugin/OptionsCapableActivity.kt#L33

https://github.com/shadowsocks/shadowsocks-android/blob/3f25eace082bcdbbcd41c0c705c79695ffd505f1/plugin/src/main/java/com/github/shadowsocks/plugin/PluginOptions.kt#L56

Seems that first key with null value will be parsed as `id` rather than put into Map, when constructing PluginOptions for `onInitializePluginOptions(options: PluginOptions)`

**Comment by Mygod** [comment]
Yeah this seems problematic (sorry about the delay). Feel free to submit a PR (or wait for me to get around to it). :)

**Comment by IrineSistiana** [comment]
Hi @Mygod 

I'm not quite sure what the var `id` does.  

It seems that the simplest fix is changing

https://github.com/shadowsocks/shadowsocks-android/blob/3f25eace082bcdbbcd41c0c705c79695ffd505f1/plugin/src/main/java/com/github/shadowsocks/plugin/PluginOptions.kt#L64

to `constructor(options: String?) : this(options, false)`

Submitting a PR is quite hard for me right now. I'm still struggling to set up a working development  environment. So I can't test it =[

**Comment by Mygod** [comment]
See #2398. You can also try to take this fix in your plugin app locally and see if it works. :)
