### ISSUE TITLE
小米手机上无法安装咋办呀？有大佬给支个招吗？

### ISSUE THREAD

**Issue by wutongskype** [shadowsocks/shadowsocks-android#2393]
如图，应该是被识别了，有啥办法给装上吗？
![IMG_20191231_014050](https://user-images.githubusercontent.com/40192806/71593970-f978da80-2b70-11ea-887c-420ce6b62bda.jpg)

**Comment by siwuxiesss** [comment]
试试从Google play 安装

**Comment by pexcn** [comment]
换系统啊

**Comment by RtYkk** [comment]
刷Los，或者换个修改版

**Comment by pongfcnkl** [comment]
右上角齿轮，把安全应用推荐给关了

**Comment by wutongskype** [comment]
已解决，发现是处理器的问题，这破币红米8A是arm7的处理器，装后缀是arm7那个universal的版本就装上去了。
