### ISSUE TITLE
Android Studio can not build，，

### ISSUE THREAD

**Issue by Wudelin** [shadowsocks/shadowsocks-android#2396]
Build command failed.
Error while executing process C:\Users\14588\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\AndroidStudioProjects\shadowsocks-android-4.8.7\core\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\AndroidStudioProjects\shadowsocks-android-4.8.7\core\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:/AndroidStudioProjects/shadowsocks-android-4.8.7/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\AndroidStudioProjects\shadowsocks-android-4.8.7\core\build\intermediates\ndkBuild\debug\lib -j6 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
md "E:\AndroidStudioProjects\shadowsocks-android-4.8.7\core\build\intermediates\ndkBuild\debug\lib\armeabi-v7a" >NUL 2>NUL || rem

**Comment by Wudelin** [comment]
I now set up a server manually. After the manual configuration file is saved, click to connect successfully. The speed measurement prompts no internet. What is the reason?

**Comment by northMingFish** [comment]
我也是构建不成功  相同的报错

**Comment by Wudelin** [comment]
https://github.com/cyq7on/shadowsocks-android-patch  解决方案！
