### ISSUE TITLE
Bypass LAN still doesn't work.

### ISSUE THREAD

**Issue by sanzo-mlgb** [shadowsocks/shadowsocks-android#2399]
**Describe the bug**
Bypass LAN still doesn't work, apk in #2361 can not  solve too

**To Reproduce**
ss version 4.8.7，and everything just like #2361 

**Expected behavior**
Bypass LAN still doesn't work.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Android version: 10 QKQ1.190825.002
 -MIUI version : 11.0.4.0
 - Security Patch : 2019-10-01
 - kernel : 4.14.117-perf-g834e8250
 - Device: Redmi k20 pro PE
 - Shadowsocks Version: 4.8.7
 - Last version that did not exhibit the issue: None

**Configuration**
* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open

**Comment by madeye** [comment]
Probably a third-party issue. Refer to previous issues for more details.

**Comment by Mygod** [comment]
Thanks for filling out the template. Please redirect all discussions towards this issue to #2361 instead.
