### ISSUE TITLE
the app consumed nearly 800M  traffic while my phone is locked

### ISSUE THREAD

**Issue by dolaham** [shadowsocks/shadowsocks-android#2401]
Please read contributing guidelines. Thanks.

**Describe the bug**
i started work at 13:30. so since then, i wasn't using my phone until 17:14 i picked up my phone and waked it up. the phone told me nearly 800MB traffic was consumed.

**To Reproduce**
1. use a redmi phone
2. install shadowsock and connect to a server
3. lock the phone and wait for hours

**Expected behavior**
fix the problem. i think my cellular data traffic was wasted while my phone wasn't in using.

**Screenshots**
https://user-images.githubusercontent.com/76417/72141282-828fdd00-33cd-11ea-8b8b-43981921ccb9.png

**Smartphone (please complete the following information):**
 - Android 8.1.0, miui 9.5
 - Device: redmi note 5
 - Version: shadowsock 4.8.5
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
please.

**Comment by dolaham** [comment]
![Screenshot_2020-01-10-17-14-44-202_com miui securitycenter](https://user-images.githubusercontent.com/76417/72141867-97b93b80-33ce-11ea-813b-33ef9ae904c8.png)
try to upload the screenshot

**Comment by dolaham** [comment]
i edited my report so that it now following the template. please help.

**Comment by madeye** [comment]
You need to check which app is transferring data in background.

Shadowsocks is just a proxy, it won't cost any traffic by itself.

**Comment by dolaham** [comment]
> You need to check which app is transferring data in background.
> 
> Shadowsocks is just a proxy, it won't cost any traffic by itself.

in my phone, only a few apps are allowed using shadowsocks as proxy and i always kill these apps when i dont use. When I look at the traffic statistics for this month, I can see the current traffic consumption of these apps, but none of them consumed 800M.
if there was some other apps, they should also be listed separately on the watch list of the screenshot.
i have been using ss for years, this is the first time i met such problem.
really weird.

**Comment by madeye** [comment]
Probably the MIUI system itself or Google Play service. Double check if you have OTA update or Google Play service update recently.

**Comment by Mygod** [comment]
Infeasible to investigate for now.
