### ISSUE TITLE
Support SIP002 URI scheme for subscription might be better

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#2404]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
Current subscription use json and it might be hard to generate and maintain. Also it couldn't be used on other platform easily.

**Describe the solution you'd like**
Take SIP002 into consideration. Each line contains a full SIP002 URI. File format like this.
```
ss://abc
ss://def
ss://ghi
```
Then, use base64 tool to encode the file and make it public.
This kind of subscription is used for a while for many clients. It might be better comparing to json file format.

**Describe alternatives you've considered**

**Additional context**

**Comment by madeye** [comment]
No plan for this.

SIP002 URL should be only used in QR code and context intent (Android and IOS).

**Comment by Mygod** [comment]
I think JSON is the standard format as described at shadowsocks.org. This repo supports some additional fields that are not required to be supported by other implementations.

**Comment by madeye** [comment]
Right, it also enables other client like windows client to specify its own fields.
