### ISSUE TITLE
5.0.0 不兼容 v2ray-plugin-android 1.3.0 ?

### ISSUE THREAD

**Issue by bigbighill** [shadowsocks/shadowsocks-android#2405]
Please read contributing guidelines. Thanks.

**Describe the bug**
显示错误：
  后台 服务 启动失败：无法连接远程服务器
android.os.NetworkOnMainThreadException

**Comment by xianren78** [comment]
把服务器域名改成IP暂时可以解决这个问题。

**Comment by Mygod** [comment]
https://android.googlesource.com/platform/libcore/+/04f57c8f9fddbf81e5375b071e3e246889a9fe01%5E%21/luni/src/main/java/libcore/io/BlockGuardOs.java

Hmm... It looks like `connect` a UDP socket will throw this exception on Android 5-9.
