### ISSUE TITLE
添加“在线规则文件URL”似乎没用

### ISSUE THREAD

**Issue by windstander** [shadowsocks/shadowsocks-android#2406]
Please read contributing guidelines. Thanks.

**Describe the bug**
如题，添加GFW LIST的文件地址上去，并不能应用规则。

**To Reproduce**
1. Go to '自定义规则'
2. Click on '右上角三条杠'
3. Scroll down to '手动设置'
4. 编辑规则，在线规则文件URL，添加GFW List的地址: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Expected behavior**
更改路由为“GFW列表”，但是不能翻墙。

**Smartphone (please complete the following information):**
 - Android 9
 - Device: 小米MIX2
 - Version: MIUI 11.0.2.0

**Comment by Mygod** [comment]
ACL file is expected. Try https://github.com/shadowsocks/shadowsocks-android/raw/master/core/src/main/assets/acl/gfwlist.acl
