### ISSUE TITLE
希望增加混和翻墙规则

### ISSUE THREAD

**Issue by windstander** [shadowsocks/shadowsocks-android#2407]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
是的，有的app我想指定让它翻墙，比如谷歌app；有的app我想让它服从全局规则。但是现在要么指定app翻墙行为，要么采用全局规则。

**Describe the solution you'd like**
增加一个混合模式，比如谷歌app我全部指定翻墙，而浏览器程序如firefox，则根据访问的网页是否匹配自定义规则来决定是否翻墙。.

**Describe alternatives you've considered**
没有

**Additional context**

**Comment by adfnkjasd** [comment]
对手机来说的话功能太复杂了，电脑上的话可以试试switchyomega

**Comment by madeye** [comment]
App proxy and policy routing can work together.

For your case, I didn't see anything useful to not use policy routing for Google App.

The best practice is bypass Chinese Apps and enable CHN route.
