### ISSUE TITLE
free improvement without binary size increase

### ISSUE THREAD

**Issue by babarosaM33** [shadowsocks/shadowsocks-android#2410]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
ndk release compile flags is just "-O2" with nothing else. most android phone processor is  compatible with cortex-a53. let's set another cflag "-mcpu=cortex-a53"

I have build the official benchmark of mbedtls with ndk-r20 and tested several cflags combination on my mobile phone.
Here is the result table.
|                        |   aes-128-gcm | aes-192-gcm | aes-256-gcm |  chachapoly    |  binary_size|
|----------------|---------------|---------------|-------------|-------------|------------|
|default(O2)      |   69398 KiB/s   | 68241 KiB/s   | 64930 KiB/s    | 180535 KiB/s  |    100%|
|O2+a53           |   71145 KiB/s   | 69702 KiB/s   | 66283 KiB/s    | 181584 KiB/s  |    100%|
|O2+a55           |   71422 KiB/s   | 69611 KiB/s   | 66230 KiB/s    | 179028 KiB/s  |    100%|
|O3                   |  70269 KiB/s    | 68852 KiB/s   | 65445 KiB/s    | 185508 KiB/s  |    119%|

**Comment by Mygod** [comment]
I don't know about "free". If it's free, why not report to android/ndk?
