### ISSUE TITLE
Remote no longer resolved using hosts after v5.0.1 update

### ISSUE THREAD

**Issue by ShrdBB** [shadowsocks/shadowsocks-android#2412]
Please read contributing guidelines. Thanks.

**Describe the bug**
Previous issue #2256 was fixed in v4.8.2, but it no longer works after v5.0.1 update.
When using the v2ray-plugin+WebSocket+TLS+Cloudflare method, sometimes an error message 'Invalid server name' shows up, otherwise the client connects to IP addresses returned by normal DNS resolvers rather than those specified in the 'hosts' option. (Viewed using [PingTools](https://www.pingtools.org/))

**Expected behavior**
The clients connects to IP addresses specified in the 'hosts' option.

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 9.1.0
 - Device: Huawei
 - Version: v5.0.1
 - Last version that did not exhibit the issue: v4.8.7

**Comment by DearTanker** [comment]
华为EMUI最新版似乎在WiFi那里加了个DNS加密的特性会导致域名识别出问题。不知道这个有没有办法通过App来规避，还是说必须去WiFi那边手动关闭这个DNS加密。

**Comment by shikkoku** [comment]
> 华为EMUI最新版似乎在WiFi那里加了个DNS加密的特性会导致域名识别出问题。不知道这个有没有办法通过App来规避，还是说必须去WiFi那边手动关闭这个DNS加密。

你指的是私人DNS？那个又不是华为独有的。

**Comment by Mygod** [comment]
@ghost Can you verify that this issue has been fixed in v5.0.2?

**Comment by DearTanker** [comment]
@shikkoku 貌似和私人DNS没有什么关系。

![微信图片_20200122030814](https://user-images.githubusercontent.com/1122669/72834836-93d9c300-3cc4-11ea-8275-d92b4ba3c5ef.jpg)

**Comment by shikkoku** [comment]
> @shikkoku 貌似和私人DNS没有什么关系。
> 
> ![微信图片_20200122030814](https://user-images.githubusercontent.com/1122669/72834836-93d9c300-3cc4-11ea-8275-d92b4ba3c5ef.jpg)

你这个就是在别的系统（MIUI 10 类原生安卓等）称为私人dns的功能。Private DNS（DNS over TLS）也就是DoT。我在用EMUI 10。
