### ISSUE TITLE
GreatFire诚招渴望互联网自由的软件工程师

### ISSUE THREAD

**Issue by gfsupport** [shadowsocks/shadowsocks-android#2415]
我们(GreatFire.org)的使命是终结中国的互联网审查。现在我们正在招聘几名开发者。匿名远程工作。工资根据您的经验而定。

目前的项目将使用机器学习进行数据分析，优化各种翻墙软件的速度和质量，包括Shadowsocks等。项目需要Android开发、翻墙软件开发、机器学习方面的技能。

如果您有意象，欢迎发送邮件到 support@greatfire.org 与我们详谈。为了安全起见，请使用非国内邮箱联系。

**Comment by yzou** [comment]
不会是钓鱼吧

**Comment by gfsupport** [comment]
> 不会是钓鱼吧

不是的，我们的邮箱域是 greatfire.org 你可以搜索一下看看政府是否允许这样的网站存在
