### ISSUE TITLE
在中国移动4G下看不了YouTube App，但可以打开YouTube网页。

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-android#2418]
Please read contributing guidelines. Thanks.

**Describe the bug**
在中国移动4G下看不了YouTube App，可以看YouTube网页版。就算用obfs混淆插件也看不了YouTube App。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [Android 9]
 - Device: [Samsung]
 - Version: [Shadowsocks 4.8.7]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:AES-256-GCM
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Try disabling DNS over UDP.

**Comment by okudayukiko** [comment]
> Try disabling DNS over UDP.

也不行

**Comment by onlyJinx** [comment]
中国移动内网中的内网，有点悬啊，你先试试联通电信可不可以正常用

**Comment by DeviesVi** [comment]
The same in China Telecom 200M, routing as GFW list. Bypass LAN & China has no problem.

**Comment by rampageX** [comment]
Youtube Android App 视频貌似走的是 QUIC 而且改不了，要确认你的服务器是不是支持 UDP。

**Comment by Mygod** [comment]
Please search related issue and upload requested information.
