### ISSUE TITLE
Subscription issue with specifically git.io shortened URL

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#2419]
Please read contributing guidelines. Thanks.

**Describe the bug**
Seems like a bad url detection while fetching Subscription.

**To Reproduce**
1. Subscribe this URL in ss-android.
https://git.io/JvtMw
2. Update the subscription
3. Recieve error: `Failed to connect to git.io/127.0.5.17:443`

For a reference, Use this link doesn't have similar problem.
https://fars.ee/vW2E

**Expected behavior**
Subscribe without problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 10
 - Device: MI MIX 2S
 - Version: v5.0.1

**Configuration**
NaN

**Additional context**
NaN

**Comment by madeye** [comment]
You're visiting a blocked domain name .

Double check you have a valid SS connection first.

**Comment by simonsmh** [comment]
Why I need a valid SS connection to fetch subscription?
Also I have access to git.io without ss and DNS is working. There is no internet issue.

**Comment by madeye** [comment]
If so, double check that your system browser can visit that URL first. 

We follow the system DNS settings to resolve any domain names.

**Comment by simonsmh** [comment]
Double checked on my side, it seems like the DNS is polluted on my network.
