### ISSUE TITLE
DNS forwarding is broken since 5.0.1

### ISSUE THREAD

**Issue by danialbehzadi** [shadowsocks/shadowsocks-android#2420]
**Describe the bug*
After update to 5.0.1, DNS forwarding doesn't work. I had to downgrade to 4.8.7 in order to connect to banned websites.

**Screenshots**
![Screenshot_۲۰۲۰۰۱۲۴-۲۱۳۳۰۵_](https://user-images.githubusercontent.com/3658678/73092688-f0abc800-3ed4-11ea-9014-a464c4dc16bf.png)
![Screenshot_۲۰۲۰۰۱۲۴-۲۱۳۳۱۱_](https://user-images.githubusercontent.com/3658678/73092702-f7d2d600-3ed4-11ea-97e4-a554fc9b53bc.png)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: LineageOS 16 (AOSP 9.0.0_r46)
 - Device: Pocophone F1
 - Version: v5.0.1 and v5.0.2
 - Last version that did not exhibit the issue: 4.8.7

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20 + v2ray
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] Bypass LAN & Iran
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open

**Comment by Mygod** [comment]
What's bypass LAN & Iran?

Hostname matching is currently buggy from v5.0.0 to v5.0.2 which should be fixed (see also #2411). On the other hand, since 10.10.34.35 is a LAN address, it is incorrectly bypassed. If you configured the bypass Iran acl correctly, this issue should be fixed in the next version.

**Comment by danialbehzadi** [comment]
10.10.0.0 is not a LAN network. It's the censorship network in Iran. If DNS resolving work correctly over shadowsocks, it should return the actual IP of twitter, but since it's not going to be resolved over shadowsocks, the Iran firewall spoofs the DNS request and returns the censored IP (10.10.34.35) instead.

**Comment by Mygod** [comment]
Please try v5.0.3.

**Comment by danialbehzadi** [comment]
Fix in 5.0.3 confirmed.
