### ISSUE TITLE
how usr the subscription?

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/shadowsocks-android#2421]
Please use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead. Your issue will probably be closed.

The shadowsocks has been support subscription, how use it?

![Screenshot_20200128-123211_Google Play Store](https://user-images.githubusercontent.com/21324835/73235803-e1759480-41ca-11ea-9870-72d3d9925c2b.jpg)

**Comment by Love4Taylor** [comment]
https://gist.github.com/madeye/8451355b1baba312dae78a6c8ca4d1a1

**Comment by onlyJinx** [comment]
> https://gist.github.com/madeye/8451355b1baba312dae78a6c8ca4d1a1

I'm sorry, I can't understand example.json in this link, Can you help me change my profile, thanks.

{
    "server":"0.0.0.0",
    "server_port":4333,
    "local_port":1080,
    "password":"nPB4dhhBg.*.",
    "timeout":60,
    "method":"xchacha20-ietf-poly1305",
    "fast_open": true,
    "nameserver": "8.8.8.8",
    "mode": "tcp_and_udp"
}

**Comment by onlyJinx** [comment]
I think I know how to do it, thank you very much
