### ISSUE TITLE
feature request: app vpn mode enabled for all profiles

### ISSUE THREAD

**Issue by Mystery00** [shadowsocks/shadowsocks-android#2425]
请求添加 app vpn mode批量操作的功能，因为节点太多，批量导入之后默认的分应用代理是关闭，并且代理方式是全局，因为节点太多不方便手动修改，希望提供一个批量操作的功能。

**Comment by Mystery00** [comment]
app vpn mode enabled for all profiles after import multiple profiles from file or clipboard

**Comment by Mygod** [comment]
batch edit via json import/export
