### ISSUE TITLE
5.0.3 can't connect ip server consists of words and numbers

### ISSUE THREAD

**Issue by AppJ-GS** [shadowsocks/shadowsocks-android#2429]
**Describe the bug**
5.0.3 can't connect ip server consists of words and numbers.But it could connect ip consists of only numbers.
**To Reproduce**
1. Select ip consists of words
2. Click on 'connect'
3. No respond

**Expected behavior**
Plz check and fix this issue as fast as possible.
**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: Android 10,MIUI 11 beta(20.1.21).
 - Device: Xiaomi Mi 8
 - Version: v5.0.3
 - Last version that did not exhibit the issue: This issue always exists

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:AES-256-CTR
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
> can't connect

yeah right
