### ISSUE TITLE
APP中，路由选择gfw列表 部分APP打不开 如play商店和YouTube之类的

### ISSUE THREAD

**Issue by xidcn** [shadowsocks/shadowsocks-android#2432]
路由模式中的 gfw列表一直好用，就在上个月好像就出问题了，打不开YouTube和play商店 网页可以正常打开，就是APP不行了，怎么回事？

**Comment by AppJ-GS** [comment]
这是gfw升级所致，部分ip间歇性失效

**Comment by xidcn** [comment]
> 这是gfw升级所致，部分ip间歇性中断
有办法抢救下吗

**Comment by yechnlin** [comment]
两天前突然连不上了，服务器在香港，什么情况？
