### ISSUE TITLE
Supscriptions refresh breaks profiles with `udp_fallback`

### ISSUE THREAD

**Issue by rocka** [shadowsocks/shadowsocks-android#2437]
**Describe the bug**
When refreshing subscription contains `udp_fallback` profiles, there would always be a toast shows "Check failed", and profiles with `udp_fallback` download previously would lose their `udp_fallback`.

**To Reproduce**
1. Go to 'Subscriptions'.
2. Click on 'Add a subscription', add any subscription url contains `upd_fallback` enabled profiles, [this gist](https://gist.githubusercontent.com/rocka/b0c1c58a524a2ce87a46dfbe41336ac5/raw/19975d205c71dcf1d038741018e0f34b6c9937e4/servers.json) for example.
3. Click on 'Refresh servers from subscription'.
4. Go to 'Profiles', should see 2 profiles, the second one's `udp_fallback` set to the first one.
5. Go to 'Subscriptions', click on 'Refresh servers from subscription', **Again**.
6. Toast shows "Check failed", and profiles with `udp_fallback` lose their `udp_fallback`.

**Expected behavior**
Profiles should be updated without losing their `udp_fallback`.

**Smartphone (please complete the following information):**
 - Android version: Android 9, LineageOS 16.0-20200208-NIGHTLY-bacon
 - Device: OnePlus One
 - Version: v5.0.4
 - Last version that did not exhibit the issue: [not applicable]

**Additional context**

**Comment by Mygod** [comment]
Thank you for your detailed bug report. This will be fixed in the next release.
