### ISSUE TITLE
Feature Request: Apps Filter Toggle.

### ISSUE THREAD

**Issue by alpineboi20** [shadowsocks/shadowsocks-android#2438]
Please would you consider adding an option to filter apps, in  Profile Config/Apps VPN Mode. For example. A toggle to Show Only System Apps or Show Only Installed Apps. It would be a great improvement to quickly find just the installed Apps you want to go through the tunnel. 

Thanks

**Comment by Mygod** [comment]
You are looking for an app manager.

**Comment by alpineboi20** [comment]
Lol. How am I? Its no fun scrolling through dozens of system apps, just to find the apps you want to allow or block. Seemed like a genuine QOL request. No problem though.
