### ISSUE TITLE
3G网络下有问题

### ISSUE THREAD

**Issue by lixuy** [shadowsocks/shadowsocks-android#244]
联通3G，使用Shadowsock无法访问被墙网址，但是先用wifi连上访问被墙网址的话，断开wifi再用3G网络就可以访问，在wifi下未访问过的就不行。比如用3G连接shadowsock访问google不行，用wifi连接shadowsock访问google成功，断开wifi，使用3G即可访问，但是未访问过的G+就不行了。
难道跟dns解析有关？如果是这样，最好出个pac自定义模式。
MIUI V5 Andriod 4.4.2 三星Galaxy Note3

**Comment by kalsangphuntsok** [comment]
我出现的问题是使用联通3G时跟本无法连接Shadowsocks，而是用Wifi则是顺畅连接，没有任何问题。不知道原因在哪里？
