### ISSUE TITLE
Hope that the Android version will add the Trojan protocol as soon as possible

### ISSUE THREAD

**Issue by zllafgafg** [shadowsocks/shadowsocks-android#2469]
Hello, I hope that the Android client can support the "Trojan" proxy protocol as soon as possible.  Because the current effect of using traditional protocols in mainland China is not very good, traditional protocols have been blocked by gfw.  Now using the new Trojan protocol, it is necessary to download another Trojan-exclusive software, which is very inconvenient and Trojan software is unstable.  So I hope that the Android version can support the Trojan protocol as soon as possible.  Thank you

**Comment by Mygod** [comment]
Implement it as plugins: https://github.com/shadowsocks/shadowsocks-android/blob/master/plugin/README.md

If you are just looking for a TLS tun, also consider v2ray-plugin which is already supported by this client.
