### ISSUE TITLE
Nvidia Shield 2019, Beta 5.0.5, SSR单端口 用不了。只有普通端口可以上网

### ISSUE THREAD

**Issue by liliass** [shadowsocks/shadowsocks-android#2470]
Android TV version,
SSR单端口 用不了。
只有普通端口可以上网

 - Device: NVIDIA SHIELD 2019
 - Version: 8.1.1
 -

**Configuration**
Put an `x` inside the [ ] that applies.

* [* ] IPv4 server address
* [ ] IPv6 server address
* [ *] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: SSR
* Route
  * [* ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ *] Auto Connect
* [* ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
Make sure you're using shadowsocks, not SSR.
