### ISSUE TITLE
google play无法访问

### ISSUE THREAD

**Issue by zhl111** [shadowsocks/shadowsocks-android#2472]
如题，这两天都是这样

**Comment by AppJ-GS** [comment]
估计你用的是小米内测吧，只要把google全部框架（play store除外）全部设置为自启动即可

**Comment by xiaobu1994** [comment]
5.0.5版本的小米和华为都不能安装的吗

**Comment by AppJ-GS** [comment]
华为不行，小米的只要把google所有框架服务设置为自启动即可，设置之后重启

xiaobu1994 <notifications@github.com> 于2020年3月17日周二 上午11:00写道：

**Comment by xiaobu1994** [comment]
OK 感谢

发至小布的iphone

**Comment by xiaobu1994** [comment]
哦哦好的感谢

发至小布的iphone
