### ISSUE TITLE
Improve tun2socks performance and memory usage

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-android#2474]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
The tun2socks UDP sessions are not timeout, after some time of heavy usage, the udp sessions reach 256 and about 5MB memory.

**Describe the solution you'd like**
Timeout UDP sessions and free memory to improve poll performance and memory usage.

**Describe alternatives you've considered**
Add a timer to free UDP sessions.

**Additional context**
The timeout should be the same as ss-local.

**Comment by madeye** [comment]
It's expected. 5MB memory is almost nothing for even 10 years old Android phones.

Given it's a LRU cache, the memory won't increase after reaching 5MB.

**Comment by yzou** [comment]
No, it won't increase. I got thread killed on iOS 13 because of reaching 15MB of memory.

Memory is not an issue, polling hundreds of fds may impact performance.

**Comment by madeye** [comment]
I don't think epoll or kqueue has a performance issue on 256 file descriptors.

BTW, this project is for Android platform. Any iOS problem is not what we'd like to resolve.

**Comment by yzou** [comment]
This is for tun2socks, the badvpn repo is closed for issues, so I posted here. the tun2socks is also used on iOS projects.

**Comment by madeye** [comment]
I didn't see any open source iOS application using our tun2socks implementation.

Given it's an issue for your proprietary software, you have to solve it by yourself.

**Comment by yzou** [comment]
Google's outline and protaso are using this.

**Comment by madeye** [comment]
Nope, they forked badvpn directly and implemented their own UDP forwarder. I suggest you do the same thing as well.
