### ISSUE TITLE
Adopt SS-Windows' [gui-config.json] format as an available subscription format

### ISSUE THREAD

**Issue by iBug** [shadowsocks/shadowsocks-android#2475]
**Is your feature request related to a problem? Please describe.**

Many existing Shadowsocks service providers have "Shadowsocks configuration file" as one of the available subscription formats (generates a `gui-config.json` file). Such configuration files are designed for SS-Windows and are unfortunately not directly usable in SS-Android 5.0.

**Describe the solution you'd like**

[The expected][1] SS-Android configuration file, in the meantime, has exactly the same format as the `"configs"` key in a typical SS-Windows file. It would be simple and easy to check the received JSON from the subscription endpoint to see whether the root object is an Object, and when so, extract the `"configs"` key and proceed as before.

Being able to utilize existing solutions makes SS-Android more convenient to use.

**Describe alternatives you've considered**

For the time being, I have written a small app that "proxies" and does the conversion. It's a simple Ruby Sinatra app:

```ruby
require 'sinatra'
require 'net/http'
require 'json'

get '/mysecretpath' do
  JSON.generate JSON.parse(Net::HTTP.get URI 'https://example.com/gui-config.json')['configs']
end

not_found do
  "Hello world!\n"
end
```

I must say this 10-line Ruby app is a perfect "middleware" and it's coordiating smoothly with SS-Android 5.0.5 on my phone. I am currently using `https://mysecretdomain.example.com/mysecretpath` as my subscription URL, but a patch as described above would eliminate the need for this extra job.

  [1]: https://gist.github.com/madeye/8451355b1baba312dae78a6c8ca4d1a1

**Comment by Mygod** [comment]
What makes you think it's not supported? Have you tried?

**Comment by iBug** [comment]
@Mygod Can this be added to relevant documentations? I only read the release notes of v5.0.0 and checked that GitHub Gist item. I generally don't depend on or even expect undocumented features.

**Comment by Mygod** [comment]
That's a reasonable request. Let me write a quick documentation.

**Comment by Mygod** [comment]
Well that was not quick at all.

**Comment by iBug** [comment]
Thanks a lot for that. It's definitely worth it.
