### ISSUE TITLE
更新/重新订阅节点列表排序错乱

### ISSUE THREAD

**Issue by cjiasu** [shadowsocks/shadowsocks-android#2477]
SS订阅功能希望可以优化下,目前添加订阅后无法更新订阅,点击重新订阅后节点会在基础上叠加重复节点,感觉这个订阅功能有点像下载？

**Comment by iBug** [comment]
我这相反，重复的订阅会消失，很奇怪，必须把名字改掉（5.0.5），感觉应该是同一个问题
