### ISSUE TITLE
Failed to connect the remote server:Unknow plugin obfs-local 

### ISSUE THREAD

**Issue by jw587** [shadowsocks/shadowsocks-android#2480]
I get the error 'Failed to connect the remote server:Unknow plugin obfs-local' when trying to connect to the Shadowsocks servers using obfs plugin.

**Screenshots**
![Unknown plugin](https://user-images.githubusercontent.com/31643883/77746498-f732f900-7057-11ea-82b3-1d5c5bc9a96c.jpg)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 8.1.0
 - Device: Meizu 16th
 - Version: Shadowsocks 5.0.5

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable): Simple obfuscation | obfs=tls
* [ ] Auto Connect
* [x] TCP Fast Open

**Additional context**
I get the unknow plugin error if I connect to the server directly. But I can connect to it when I disable the plugin first and then enable it again in the client app. 
This issue also occurs in Huawei phones.

**Comment by shikkoku** [comment]
把你的插件APP自启动设置为手动管理，然后把自启动关联启动和后台运行三个选项全部打开。

**Comment by jw587** [comment]
> 把你的插件APP自启动设置为手动管理，然后把自启动关联启动和后台运行三个选项全部打开。

我用的插件是Simple Obfuscation，没有找到你说的那些启动和运行的相关设置。
如果您也是用的OBFS，可能麻烦截图示意一下。

**Comment by shikkoku** [comment]
请务必打开显示系统进程。Sent from my Huawei phone-------- Original message --------From: WHQ <notifications@github.com>Date: Tue, Apr 7, 2020, 3:59 PMTo: shadowsocks/shadowsocks-android <shadowsocks-android@noreply.github.com>Cc: Felix <fchioa@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [shadowsocks/shadowsocks-android] Failed to connect the remote server:Unknow plugin obfs-local  (#2480)

把你的插件APP自启动设置为手动管理，然后把自启动关联启动和后台运行三个选项全部打开。

我用的插件是Simple Obfuscation，没有找到你说的那些启动和运行的相关设置。
如果您也是用的OBFS，可能麻烦截图示意一下。

**Comment by shikkoku** [comment]
华为比较新的系统请务必打开显示系统进程。
![Screenshot_20200407_161950_com huawei systemmanager](https://user-images.githubusercontent.com/4697177/78647022-8eb40980-78ec-11ea-8b7d-05f2f671623d.jpg)
![Screenshot_20200407_161923_com huawei systemmanager](https://user-images.githubusercontent.com/4697177/78647033-94a9ea80-78ec-11ea-923e-2ec2fea4ed3a.jpg)

**Comment by jw587** [comment]
不同手机的差异还真是挺大的，魅族手机的后台运行设置和自动启动设置不在一个地方，而且没法手工修改自动启动方式。
![Simple OBFS](https://user-images.githubusercontent.com/31643883/78649574-37179d00-78f0-11ea-92f8-de613d727113.png)
![Auto launch app](https://user-images.githubusercontent.com/31643883/78649592-3c74e780-78f0-11ea-97d1-3001a2e419e0.png)

**Comment by shikkoku** [comment]
> 不同手机的差异还真是挺大的，魅族手机的后台运行设置和自动启动设置不在一个地方，而且没法手工修改自动启动方式。
> ![Simple OBFS](https://user-images.githubusercontent.com/31643883/78649574-37179d00-78f0-11ea-92f8-de613d727113.png)
> 
> ![Auto launch app](https://user-images.githubusercontent.com/31643883/78649592-3c74e780-78f0-11ea-97d1-3001a2e419e0.png)
> 
> ![Allow running in background](https://user-images.githubusercontent.com/31643883/78650018-e9e7fb00-78f0-11ea-94ec-e26909c82f11.jpg)

论坛说开了这个就能自启动了。

**Comment by jw587** [comment]
启用后台运行后，可以正常用了。非常感谢!
