### ISSUE TITLE
Profiles that was once present in a subscription will not re-appear for a second time

### ISSUE THREAD

**Issue by iBug** [shadowsocks/shadowsocks-android#2481]
## Description

If a profile (server, port, remarks) appears in a subscription and later disappears, then it won't ever appear again.

## Reproduce

1. Add a subscription and refresh. There should be at least one valid profile
2. Remove the subscription and refresh. The profile should disappear
3. Add that subscription back and refresh. No profiles appear

## Expected behavior

The same profiles re-appear in the list

## Smartphone (please complete the following information):

 - Android 8.1
 - Device: Not relevant
 - Version: Google Play v5.0.5
 - Last version that did not exhibit the issue: \[not applicable\]

## Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS over UDP
* Plugin configuration (if applicable): obfs-local
* [ ] Auto Connect
* [ ] TCP Fast Open

**Comment by Mygod** [comment]
Thanks for reporting. While I have not tested it, this bug sounds likely. A proposed fix is in #2483.
