### ISSUE TITLE
订阅功能bug！

### ISSUE THREAD

**Issue by zhangjint5** [shadowsocks/shadowsocks-android#2485]
新安装的 shadowsocks-android ，并安装有 v2ray 和 kcptun 插件！

在删掉了软件内置的198.199.*.*那个节点，只使用订阅节点的情况下

第一次新建订阅，订阅成功！

在订阅成功后！如果编辑订阅地址，之后在按订阅，则出现故障，所有订阅节点消失！

即使恢复最初的订阅地址也无法订阅到内容！

只能卸载APP重装，或者在Android软件管理里面对此APP“清除数据”，让APP恢复成刚刚安装的状态，才能重新订阅成功！

################################################################

另外，对订阅的节点设置“分应用VPN”，进行“应用设置到所有配置文件”不起作用，所有的节点还得一个一个设置！“路由”设置也得一个一个设置

麻烦看下

谢谢

**Comment by cjiasu** [comment]
目前有点麻烦 1.删除订阅地址不会删除订阅的节点  如果节点几十个要一个个手动删   2.更新订阅更新节点是从节点列表底部加会造成节点排序混乱

**Comment by Mygod** [comment]
Should be fixed via v5.0.6.

**Comment by triaqu** [comment]
@Mygod  v5.06, oneplus7 安桌10系统，获取订阅时报 com.google.gson.stream.MalformedJsonException:Expected value at line 1column 211 path $ 错误， 在PC上能正常获取。

**Comment by imkyleshing** [comment]
> ## 明白了，订阅文件是json格式，不是base64加密文件
> @Mygod v5.06, oneplus7 安桌10系统，获取订阅时报 com.google.gson.stream.MalformedJsonException:Expected value at line 1column 211 path $ 错误， 在PC上能正常获取。

那是要怎么处理，我不太懂

**Comment by trulyliu** [comment]
能举个例子吗？

**Comment by triaqu** [comment]
手机版选导出到文件，放到服务器上就可以在订阅中导入

**Comment by Gao-sy** [comment]
获取订阅时报 com.google.gson.stream.MalformedJsonException:Expected value at line 1column 211 path $ 错误
可以转换一下订阅链接，可以在这个佬的网站https://acl4ssr-sub.github.io/进行转换，客户端选择ss或者ssAndroid，转换完自己再访问一下转换后的链接试试，看看能不能浏览器能不能返回JSON数据，确定可以用再用新链接订阅就可以了。
