### ISSUE TITLE
Please support UDP2RAW because QUIC traffics are being QoS-ed or polluted.

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-android#2486]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
> Please support UDP2RAW.

**Describe the solution you'd like**
> Please support UDP2RAW or any obscuration against UDP, because QUIC traffics are being QoS-ed or polluted.

**Describe alternatives you've considered**
> Of course we can switch to TCP, but this protocol is not mobile friendly.

**Additional context**

**Comment by Mygod** [comment]
Wrong repo.
