### ISSUE TITLE
请问斐讯n1应该用哪个安卓tv版本?装了却看不到app

### ISSUE THREAD

**Issue by isblue01** [shadowsocks/shadowsocks-android#2488]
我试过了universal，安装成功了，却没有看到app，看了cpu，应该是装arm64，也是一样成功却看不到app，请问该怎么解决

**Comment by onlymash** [comment]
斐逊n1的系统不是ATV

**Comment by isblue01** [comment]
yyf固件 咋不是安卓tv呢

**Comment by onlymash** [comment]
你怕是对ATV有什么误解

**Comment by onlymash** [comment]
ATV 长这样
[Screenshot](https://user-images.githubusercontent.com/5838634/79332751-f521d300-7f4f-11ea-87db-ffc011482e31.jpg)

**Comment by onlymash** [comment]
N1窝也有，目前各种Android系统无非是加了个TV启动器。所以刷了个Linux当网关使用了。

**Comment by onlymash** [comment]
![Screenshot from 2020-04-15 19-40-11](https://user-images.githubusercontent.com/5838634/79333457-251da600-7f51-11ea-97a2-f72c99b708af.png)
