### ISSUE TITLE
在电脑上已知可用的订阅链接在此软件上无法更新

### ISSUE THREAD

**Issue by beibao233** [shadowsocks/shadowsocks-android#2493]
rt
系统MEUI 和 Android 都是 8.0

**Comment by beibao233** [comment]
com.googke.gson.stream.MalformedJsoneException:Expected value at line 1 column 57628 path $

**Comment by Meilinhost** [comment]
该怎么写，我也遇到报错

**Comment by Meilinhost** [comment]
@madeye @Mygod 
请问有规范说明怎么写订阅规则吗
