### ISSUE TITLE
how about use ss-local as a lib with JNI interface instead of executable binary

### ISSUE THREAD

**Issue by dna2github** [shadowsocks/shadowsocks-android#2499]
**Is your feature request related to a problem? Please describe.**
Currently, I tried to use shadowsocks-android and kcp-android to connect to my kcptun-server and ssserver; however, it failed since the kcp plugin version is not the latest kcptun but my kcptun-server is in the latest version. thus i would like to try upgrade kcp-android; the tricky thing is that there is a forked kcptun in shadowsocks group which is customized some code in the old verion of kcptun; it is hard to rebase the changes on kcptun master ... (although we can migrate old version chagne to new version, it is a little bit hack way).

As we know, shadowsocks-android uses Android VPNService, which create local unix socket to pass socket fd (it is used for VPNService.protect to make sure the connection does not loop itself; i.e. use direct connection to external).

In this case, we need to fork the original project and add code for unix socket operations ... it is not friendly for developer (when some project upgrade a version; how can we do rebase for the hack changes) ... i wonder if there is better way to do socket protect ...

**Describe the solution you'd like**
just some brainstorm to discuss here; what do you think about:
- use a non-modified version of 3rd code
- use glue to connect them; i mean, for example, for shadowsocks: import shadowsocks-libev, use it as library instead of executable binary: create JNI interface to create connection directly via Kotlin/Java code; then we can keep 3rd code clean, we just create adapter instead of hacking ... ; similarly, for kcp-android, we may build kcptun into a so library and invoke from JNI interface ...

**Describe alternatives you've considered**
I know it is better to send a merge request; frankly, I am not an expert in Android; i think maybe you do much faster than me. therefore, i put this idea here first; and maybe one day i will send a merge request when I have time ...

**Comment by madeye** [comment]
Actually what you suggest is not possible.

The "protect socket" logic requires modification to any SIP003 plugin, to make sure VPNService can get the socket file descriptor before the plugin connecting. 

For your case, a better way is open a PR to the upstream (KCPTUN) to add the SIP003 support. 

BTW, I think your proposal is only for plugin. Whether using shadowsocks-libev as library won't help to solve your problem.
