### ISSUE TITLE
中国大陆路由表更新了

### ISSUE THREAD

**Issue by luxin88** [shadowsocks/shadowsocks-android#250]
实际上apnic的路由表几乎每个月更新，每次都要把这些编译到软件里面不是很麻烦？

是不是可以保存到手机内存，用户可以手动更新呢？

**Comment by myliyifei** [comment]
看作者怎么想的，我其实很想提，但是估计会被关，所以就没有提，哈哈。

BTW， 这里有个被合并网段的表
http://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone
大概比apnic的少2000行。

在 2015年2月25日 上午11:09，luxin <notifications@github.com>写道：

**Comment by PeterCxy** [comment]
其实可以初始化到/data/data里面……

**Comment by madeye** [comment]
Duplicate to #40
