### ISSUE TITLE
Shadowsocks-Android没使用AES指令集？

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-android#2503]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
Shadowsocks-Android似乎没有使用AES指令集，使用AES明显比CHACHA20慢。比如用Shadowsocks看视频会卡顿。但将加密算法改为CHACHA20后，用Shadowsocks看视频明显变快。
不使用AES指令集会明显减慢AES加解密的速度。
![屏幕截图(112)](https://user-images.githubusercontent.com/17502357/79841520-2421c400-83ea-11ea-9d79-37266301e582.png)
![屏幕截图(113)](https://user-images.githubusercontent.com/17502357/79841528-25eb8780-83ea-11ea-9b23-ecfe5132e58b.png)
![屏幕截图(114)](https://user-images.githubusercontent.com/17502357/79841533-284de180-83ea-11ea-9108-f540758723d1.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liudongmiao** [comment]
I don't think so.

```
shell> aarch64-linux-android-objdump -d libss-local.so | grep -i aes
```

no output. And if aes-ni is used, it should be at least aesd and aese.

And @madeye said wont fix for aesni in #2212

**Comment by Timat12345** [comment]
I have an issue with shadowsocks vpn. It says it is connected but no data is showing or being transferred

Thanks 

Tim

**Comment by Timat12345** [comment]
When I  test it says no internet, but my internet is connected as other programs are working

**Comment by Timat12345** [comment]
When I have it on no programs will connect to the Internet

**Comment by Mygod** [comment]
@zonyitoo Curious to hear your thoughts on supporting AES-NI/Neon.

**Comment by madeye** [comment]
Given we have switched back to OpenSSL in shadowsocks-rust, I guess we already have AES-NI support.

**Comment by Mygod** [comment]
Have we enabled it though? Also Neon is probably going to be more useful on armv8 architecture. I found some traces that libsodium is using it but again I am not sure if it is enabled.

**Comment by zonyitoo** [comment]
`aes-*-gcm` algorithms are provided by [`ring`](https://github.com/briansmith/ring). It should support AES-NI by default.

**Comment by madeye** [comment]
Yes, aes-ni is already enabled:

```
mlv@mlv-ubuntu /w/s/c/s/m/r/s/t/a/release> aarch64-linux-android-objdump -d libsslocal.so | grep -i aese | head
  16a12c:       4e284806        aese    v6.16b, v0.16b
  16a168:       4e284806        aese    v6.16b, v0.16b
  16a198:       4e284806        aese    v6.16b, v0.16b
  16a1ec:       4e284806        aese    v6.16b, v0.16b
  16a224:       4e284806        aese    v6.16b, v0.16b
  16a274:       4e284802        aese    v2.16b, v0.16b
  16a284:       4e284822        aese    v2.16b, v1.16b
  16a294:       4e284802        aese    v2.16b, v0.16b
  16a2a0:       4e284822        aese    v2.16b, v1.16b
  16a3a0:       4e284a00        aese    v0.16b, v16.16b
```

**Comment by Mygod** [comment]
What about NEON? SIMD instructions can probably be helpful for chacha20 and variants as well?

**Comment by Mygod** [comment]
It seems like libsodium only has [Neon support for aegis256](https://github.com/jedisct1/libsodium/blob/066150a94dd8599f818a403dc4011396a374091f/src/libsodium/crypto_aead/aegis256/armcrypto/aead_aegis256_armcrypto.c). Moved to https://github.com/jedisct1/libsodium/issues/949.

**Comment by liudongmiao** [comment]
@madeye Did you release it yet?

As I checked the `arm64-v8a` of `5.0.6`, no output for `aes`.
And in the apk, the filename is `libss-local.so`, not `libsslocal.so` as you mentioned.

However, for `x86_64`, there is `aesenc` and `aesdec`.

```
shell> x86_64-linux-android-objdump -d lib/x86_64/libss-local.so |grep -i aes
   21631:	66 0f 38 dc c1       	aesenc %xmm1,%xmm0
   21643:	66 0f 38 dd c1       	aesenclast %xmm1,%xmm0
   2164e:	66 0f 38 de c1       	aesdec %xmm1,%xmm0
   21660:	66 0f 38 df c1       	aesdeclast %xmm1,%xmm0
   2181d:	66 0f 38 db c0       	aesimc %xmm0,%xmm0
   218a3:	66 0f 3a df c8 01    	aeskeygenassist $0x1,%xmm0,%xmm1
   ......
```

**Comment by liudongmiao** [comment]
@Mygod Please note, on arm64-v8a, noen for chacha20 is not the same as `aesd` / `aese` for aes-*-gcm.

**Comment by okudayukiko** [comment]
没调用AES的结果，要么是速度慢，要么是在手机上很耗电。

**Comment by zonyitoo** [comment]
AES acceleration on ARM platform is with NEON instructions. AES-NI is only for x86 CPUs.

**Comment by zonyitoo** [comment]
```bash
RUSTFLAGS="-C target-feature=+aes"
```

Maybe this `target-feature` specification is required in build process

https://github.com/shadowsocks/shadowsocks-android/blob/adb0807f96efccc0b0d6a5976fcc13de5642e70d/core/build.gradle.kts#L37-L56

**Comment by zonyitoo** [comment]
`ring`'s AES implementation detects CPU's feature dynamically:

https://github.com/briansmith/ring/blob/dbd606f1420b3374292f0adb8f06bb514d3a814c/src/aead/aes.rs#L364-L375

Should be enabled by default. Hmm..

**Comment by zonyitoo** [comment]
I tried to build with those `RUSTFLAGS` on Docker. Output binaries doesn't contain any NEON and ARM AES instructions. So .. I don't know how to make it work. Help wanted.

**Comment by okudayukiko** [comment]
很多VPN应用（如V2RayNG、Trojan、AnyConnect）没有使用AES指令集？

**Comment by okudayukiko** [comment]
很多VPN应用（如V2RayNG、Trojan、AnyConnect）没有使用AES指令集？

**Comment by zonyitoo** [comment]
@okudayukiko Do not confused AES-NI (x86) with ARM's AES instructions.

**Comment by okudayukiko** [comment]
> @okudayukiko Do not confuse AES-NI (x86, the Intel Advanced Encryption Standard New Instructions) with ARM's AES instructions.
> 
> Oh the other hand, only AnyConnect is a VPN application. The others are not VPN. (Off-topic). VPN runs on Layer-2 or Layer-3, but all the others, including SS, running on Layer-5.
> 
> There is no doubt that the current version of shadowsocks-android on x86_64 platform supports AES-NI.

My Phone use Samsung Exynos ARM64 CPU.

**Comment by zonyitoo** [comment]
I suppose you are more concern about hardware accelation on ARM platform. AES-NI can't help you. :)

OpenSSL can support NEON instructions with `-mfpu=neon`, but not all ARM CPUs has this coprocessor. `aes-*-gcm` is now supported by [ring](https://github.com/briansmith/ring), I am checking if it is actually uses AES or NEON instructions on aarch64.

**Comment by okudayukiko** [comment]
> I suppose you are more concern about hardware accelation on ARM platform. AES-NI can't help you. :)
> 
> OpenSSL can support NEON instructions with `-mfpu=neon`, but not all ARM CPUs has this coprocessor. `aes-*-gcm` is now supported by [ring](https://github.com/briansmith/ring), I am checking if it is actually uses AES or NEON instructions on aarch64

只知道这几个VPN App很耗电。
执行`cat /proc/cpuinfo`显示
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

**Comment by zonyitoo** [comment]
https://docs.rs/crate/ring/0.16.14/source/pregenerated/aesv8-armx-linux64.S

AES instructions should be supported already.

**Comment by okudayukiko** [comment]
> https://docs.rs/crate/ring/0.16.14/source/pregenerated/aesv8-armx-linux64.S
> 
> AES instructions should be supported already.

为什么我用Google Play最新版SS，AES还是比CHACHA20耗电得多？

**Comment by zonyitoo** [comment]
Can't tell. Could be investigated deeper.

**Comment by zonyitoo** [comment]
> @madeye Did you release it yet?
> 
> As I checked the `arm64-v8a` of `5.0.6`, no output for `aes`.
> And in the apk, the filename is `libss-local.so`, not `libsslocal.so` as you mentioned.
> 
> However, for `x86_64`, there is `aesenc` and `aesdec`.
> 
> ```
> shell> x86_64-linux-android-objdump -d lib/x86_64/libss-local.so |grep -i aes
>    21631:	66 0f 38 dc c1       	aesenc %xmm1,%xmm0
>    21643:	66 0f 38 dd c1       	aesenclast %xmm1,%xmm0
>    2164e:	66 0f 38 de c1       	aesdec %xmm1,%xmm0
>    21660:	66 0f 38 df c1       	aesdeclast %xmm1,%xmm0
>    2181d:	66 0f 38 db c0       	aesimc %xmm0,%xmm0
>    218a3:	66 0f 3a df c8 01    	aeskeygenassist $0x1,%xmm0,%xmm1
>    ......
> ```

https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.1.1

Not released yet.

**Comment by Mygod** [comment]
Yeah I think AES instructions are already enabled.

Speaking of which, in appendix A of [this paper](https://eprint.iacr.org/2020/572.pdf), there is a benchmark of popular crypto libraries with hardware acceleration.

**Comment by okudayukiko** [comment]
> > @madeye Did you release it yet?
> > As I checked the `arm64-v8a` of `5.0.6`, no output for `aes`.
> > And in the apk, the filename is `libss-local.so`, not `libsslocal.so` as you mentioned.
> > However, for `x86_64`, there is `aesenc` and `aesdec`.
> > ```
> > shell> x86_64-linux-android-objdump -d lib/x86_64/libss-local.so |grep -i aes
> >    21631:	66 0f 38 dc c1       	aesenc %xmm1,%xmm0
> >    21643:	66 0f 38 dd c1       	aesenclast %xmm1,%xmm0
> >    2164e:	66 0f 38 de c1       	aesdec %xmm1,%xmm0
> >    21660:	66 0f 38 df c1       	aesdeclast %xmm1,%xmm0
> >    2181d:	66 0f 38 db c0       	aesimc %xmm0,%xmm0
> >    218a3:	66 0f 3a df c8 01    	aeskeygenassist $0x1,%xmm0,%xmm1
> >    ......
> > ```
> 
> https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.1.1
> 
> Not released yet.
> 
> In this `v5.1.1` version:
> 
> ```shell
> $ aarch64-linux-gnu-objdump -d lib/arm64-v8a/libsslocal.so |grep aese
>   24460c:	4e284806 	aese	v6.16b, v0.16b
>   244648:	4e284806 	aese	v6.16b, v0.16b
>   244678:	4e284806 	aese	v6.16b, v0.16b
>   2446cc:	4e284806 	aese	v6.16b, v0.16b
>   244704:	4e284806 	aese	v6.16b, v0.16b
>   244754:	4e284802 	aese	v2.16b, v0.16b
>   244764:	4e284822 	aese	v2.16b, v1.16b
>   244774:	4e284802 	aese	v2.16b, v0.16b
>   244780:	4e284822 	aese	v2.16b, v1.16b
>   244880:	4e284a00 	aese	v0.16b, v16.16b
>   244888:	4e284a01 	aese	v1.16b, v16.16b
> ...
> ```
> 
> Or may be @okudayukiko could try this prerelease version. **NOTE**: Prerelease is not stable.

我的三星手机用的Exynos处理器，`cat /proc/cpuinfo`没有neon。

**Comment by Mygod** [comment]
`asimd` is an acronym of `neon` for `/proc/cpuinfo`.

Also locking this as off-topic.
