### ISSUE TITLE
Search "IP", Baidu returns server IP

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#2508]
Please read contributing guidelines. Thanks.

**Describe the bug**
A dns bypass bug

**To Reproduce**
In bypass China and lan mode,
Search "ip", Baidu returns server IP
So.com returns real IP
Soso.com returns real IP as well

**Expected behavior**
Chinese search engines should return my real IP

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 10
 - Device: [Google Pixel 3 XL]
 - Version: [5.0.5 play]
 - Last version that did not exhibit the issue: [4.8.7]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes128gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Will be fixed in next update.
