### ISSUE TITLE
Task :buildSrc:compileKotlin FAILED.  happend in new version 

### ISSUE THREAD

**Issue by kunlunhundun** [shadowsocks/shadowsocks-android#2511]
> Task :buildSrc:compileKotlin FAILED
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.3/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

buildSrc/src/main/kotlin/Helpers.kt: (3, 33): Unresolved reference: AbstractAppExtension
shadowsocks-android/buildSrc/src/main/kotlin/Helpers.kt: (88, 49): Unresolved reference: AbstractAppExtension

android studio 4.1 canary 7     gradle 6.3.    tools.build:gradle:4.1.0-alpha07

**Comment by liuyaxi** [comment]
Has this problem been solved
