### ISSUE TITLE
Please add an option to globally override some settings

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [shadowsocks/shadowsocks-android#2513]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**

Hello
First, thank you for this project.
I had a suggestion:
Please add an option so we can globally override some settings specially

- dns setting (dns provider),
- metered hint button,
- send dns over udp button,
- and app vpn mode setting.

This is really adds a great ease of use to app because when adding several servers and removing them frequently, it is really annoying to changing all those options again and again.
Thank you very much.

**Describe the solution you'd like**

Please add those global setting to change default behavior of these options described above.

Alternative options:

An option to apply all these settings to all servers in list like the option "apply to all" that is in app vpn mode select three dot menu.

**Additional context**

-

**Comment by IceCodeNew** [comment]
Agreed.
---
Why is this proposal been labeled `wontfix`? @Mygod
