### ISSUE TITLE
Android TV (Nvidia shield) no permission to read sd card

### ISSUE THREAD

**Issue by peterDijk** [shadowsocks/shadowsocks-android#2514]
On my nvidia shield android tv, when I click 'Replace from file' I come into a sort of explorer screen (see screenshots) where I can only click on the top-left hamburger menu.
A sidebar opens, but I can't navigate or click on anything.
I want to do this to select a json file I've uploaded to the shield with server info.

When I use FX Explorer to see the contents of the app, go to Permissions, I notice these two are strike-through: android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE

This might be the reason I can't navigate to my file when I click 'Replace from file' ? 

**To Reproduce**
1. Go to 'Replace from file'
2. Click on 'hamburger-menu-icon top left of screen'
3. You can't move a 'selected' bar on anything, left right top left or OK button on remote doesn't do anything. Only 'Back' works to go to previous screen

**Expected behavior**
Being able to browse through my file system to select a json-file with server settings.

**Screenshots**
![IMG_7035](https://user-images.githubusercontent.com/39601927/80569047-60f84700-89f8-11ea-93cf-7643cb77d18c.jpg)

Android TV on latest NVidia Shield TV 2019 (cilinder)

**Comment by Mygod** [comment]
Update to latest version.

**Comment by peterDijk** [comment]
Hi,
I am using version 5.0.6, that is the latest I believe ? 
https://www.apkmirror.com/apk/max-lv/shadowsocks-for-android-tv-android-tv/shadowsocks-for-android-tv-android-tv-5-0-6-release/shadowsocks-for-android-tv-5-0-6-android-apk-download/download/

**Comment by Mygod** [comment]
Grant storage permission via system settings.

**Comment by peterDijk** [comment]
Thats not possible I’m afraid.

Does it mean the app can’t be used on a Nvidia Shield TV or am I
missing something?
