### ISSUE TITLE
libsslocal exits too fast (exit code: 134)

### ISSUE THREAD

**Issue by marierose147** [shadowsocks/shadowsocks-android#2516]
**Describe the bug**
libsslocal exits too fast (exit code: 134)

**To Reproduce**
1. Set the configuration file to use custom rules
2. Adding an online rule file to a custom rule [https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl](url)
3. initiate a connection
4. Prompt error, connection disconnected

**Expected behavior**
Connection established successfully

**Screenshots**
![Screenshot_20200506-093310_Shadowsocks](https://user-images.githubusercontent.com/13193378/81132272-661d3f00-8f80-11ea-88a5-fa3487602ef8.jpg)

**Smartphone (please complete the following information):**
 - Android version: Android 10 with OneUI 2.1
 - Device: Samsung Galaxy S10
 - Version: "v5.1.0"
 - Last version that did not exhibit the issue: "v5.0.6"

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: xchacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1dot1dot1dot1.cloudflare-dns.com
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
Looks related to https://github.com/shadowsocks/shadowsocks-rust/issues/237

**Comment by madeye** [comment]
Try this APK: https://www.dropbox.com/s/mv0dc4v1d1ru8pq/shadowsocks--universal-5.1.1.apk

**Comment by marierose147** [comment]
I tried the new apk file.
With all settings intact, the new version no longer prompts for errors, but configuration files using custom rules and online rule files still don't connect properly.

**Comment by madeye** [comment]
That ACL file is already blocked, so make sure you can access that URL directly.

**Comment by marierose147** [comment]
I'm sure I have access to that ACL file because I used cdn.jsdelivr.net.

**Comment by madeye** [comment]
Try this APK: https://www.dropbox.com/s/9ay19596vfgo9pu/shadowsocks--universal-5.1.1-nightly.apk

**Comment by marierose147** [comment]
I tried the new file and it worked correctly.

**Comment by madeye** [comment]
Thanks! Closing the issue.

**Comment by bill363yang** [comment]
> Try this APK: https://www.dropbox.com/s/9ay19596vfgo9pu/shadowsocks--universal-5.1.1-nightly.apk

I tried this apk,but the error still exists. My device is Honor V30 Pro , running Android 10, Magic UI 3.0.1. Route option is set to 'All'
