### ISSUE TITLE
UDP fallback and dns works different in play market version

### ISSUE THREAD

**Issue by Link184** [shadowsocks/shadowsocks-android#2517]
Please read contributing guidelines. Thanks.

**Describe the bug**
Github and market versions works different with the same configs. Seems like my udp configurations work different in these apps. I checked the configs with https://whoer.net/ in browser. On playmarket version I saw expected dns configs from mine config, with github there was local and internet provider dns. I tried different versions from github, nothing changes. 

**To Reproduce**
Install play market version and github version. Install v2ray plugin
Import the same config from file with udp fallback and v2ray plugin in both apps.
Connect.
Take a look https://whoer.net/ The dns configs will differ.

**Expected behavior**
when visit https://whoer.net/ with github version we should see the same configs as with playmarket app.

**Screenshots**

**Smartphone (please complete the following information):**
Samsung s9+, s10, j7

**Configuration**
Put an `x` inside the [ ] that applies.

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
* [x ] All
* [ ] Bypass LAN
* [ ] Bypass China
* [ ] Bypass LAN & China
* [ ] GFW List
* [ ] China List
* [ ] Custom rules
* [ ] IPv6 route
* [ x] Apps VPN mode
* [ ] Bypass mode
* Remote DNS: My DNS
* [ x] DNS over UDP (tried both (true and false))
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I tried with latest sources from this repository, debug build type with small changes (android gradle plugin 3.6.2, gradle 5.6.4, compiled with openjdk 1.8.0)

**Comment by Mygod** [comment]
The app uses both local DNS and remote DNS to determine the best server to connect to. To hide your local DNS, use Route = all. This is the only relevant setting.

**Comment by Mygod** [comment]
P.S. This might not be the case for v5.1.0 but it has been addressed via https://github.com/shadowsocks/shadowsocks-rust/pull/235 and will be fixed in next release.
