### ISSUE TITLE
UDP DNS setting is not respected in v5.1.0

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2518]
Forgot to implement this oops. Opening this to track the issue.

**Comment by Mygod** [comment]
@madeye Want to fix this?

**Comment by madeye** [comment]
Not sure, actually I keep that option disabled for years...

**Comment by Mygod** [comment]
Should we remove it then?

**Comment by madeye** [comment]
yeah, let's remove this.

**Comment by Mygod** [comment]
Maybe we should fix #2093 to accommodate for the performance? https://github.com/shadowsocks/shadowsocks-rust/pull/242 might help but I am done fighting with rust compiler (and tokio) for the day (and possibly longer).
