### ISSUE TITLE
Can't build project sucessful in AndroidStudio,Help me ,please

### ISSUE THREAD

**Issue by amColinzzz** [shadowsocks/shadowsocks-android#2519]
My build environment:

- AndroidStudio version:3.6.3

When I user the default settings, build failed,the error message is :

```shell
* What went wrong:
This version of Android Studio cannot open this project, please retry with Android Studio 4.1 or newer.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

The error pic :

![2020-05-09_131112](https://user-images.githubusercontent.com/43057595/81464823-89055880-91f7-11ea-894c-0680faf054f2.jpg)

So i think the error reason is the gradle version is too large.so I use the gradle 5.5,but after a change the gradle version ,it's show new error message:

```shell
ERROR: Minimum supported Gradle version is 6.3. Current version is 5.5.
```

The error pic:

![2020-05-09_131749](https://user-images.githubusercontent.com/43057595/81464827-8f93d000-91f7-11ea-9625-c03bb7ab214c.jpg)

 So I think, it is because the android Plugin version do not adapt the gradle version ,but I don't know how to change the Plugin version.I can find the code on 'repository.gradle.kts':

```
rootProject.extra.apply {
    set("androidPlugin", "com.android.tools.build:gradle:4.1.0-alpha08")
    set("kotlinVersion", "1.3.72")
}
```

And I try to change the version ,It will also error when i change the '4.1.0-alpha08'  .

**Comment by dev4u** [comment]
upgrade gradle to 6.3 or above, and upgrade AS 4 or above.
