### ISSUE TITLE
MIUI12闪退

### ISSUE THREAD

**Issue by git10135405** [shadowsocks/shadowsocks-android#2526]
小米6 安卓9 MIUI12内测/公测版
shadowsocks版本:5.0.6/5.1.0
编辑服务器信息或手动设置均闪退，无法使用

**Comment by Mygod** [comment]
Wipe data.

**Comment by git10135405** [comment]
> Wipe data.

一样的，我已经卸载再重装也是一样

**Comment by Mygod** [comment]
Uninstall all plugins.

**Comment by git10135405** [comment]
> Uninstall all plugins.

一样，还是不行，刚卸载了唯一一个v2ray-plugin

> Uninstall all plugins.

嗯，目前可以确定跟v2ray-plugin有关，不装插件就没问题，谷歌商店和git的发布分支安装这个插件都一样会导致闪退，甚至导致其他vp也用不了，有什么解决方案吗？

**Comment by git10135405** [comment]
shadowsocks最新发布版已集成v2ray-plugin插件了？我火星了吗？😂

**Comment by Mygod** [comment]
You might have another app installed that also provides v2ray-plugin. The app considers this as a security risk and crashes. In next version the app will show you which apps are providing conflicting plugin.

**Comment by Mygod** [comment]
For now, as you have installed the official v2ray, you can long press on the v2ray plugin to see which app is providing the other v2ray.

**Comment by git10135405** [comment]
> Uninstall all plugins.

一样，还是不行，刚卸载了唯一一个v2ray-plugin

> For now, as you have installed the official v2ray, you can long press on the v2ray plugin (in the profile configuration page) to see which app is providing the other v2ray.

嗯，看到了，确实是别的vp软件内置冲突了，辛苦作者新版本看能否增加提示而不是闪退😃
