### ISSUE TITLE
微信语音聊天功能不能用

### ISSUE THREAD

**Issue by dawnbrave** [shadowsocks/shadowsocks-android#2529]
Please read contributing guidelines. Thanks.

**Describe the bug**
启动软件，路由模式为：绕过局域网及中国大陆地址，部分软件的语音聊天功能不可用。
版本是5.0.6，以前是只有腾讯会议等软件，现在微信语音也不能使用了（表现为一直连接中）。
关闭软件后，上述软件又能正常使用。

**Expected behavior**
希望在该路由模式下，能正常使用上述语音聊天功能。

**Smartphone (please complete the following information):**
 - Android version: 10
 - Device: Honnor V10
 - Version: v5.0.6
 - EMUI version: 10.0.0

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment]
Double check your server supports UDP relay.
