### ISSUE TITLE
关于xposed状态栏网速统计模块的网速异常问题

### ISSUE THREAD

**Issue by codexss** [shadowsocks/shadowsocks-android#253]
我跟模块开发者交流了一下，他解决了影梭NAT网速统计的问题现在已经可以正确显示，但是影梭的VPN模式下依旧有统计问题，希望Madeye能够可以和模块开发者解说一下影梭VPN模式的细节，以下是模块的issue
https://github.com/chiehmin/Xposed-NetworkSpeedIndicator/issues/86#issuecomment-76593295

**Comment by madeye** [comment]
It's neither a bug of shadowsocks nor xposed, but a bug of Android system.

**Comment by codexss** [comment]
那么这个app修复了系统的虫子？(
https://play.google.com/store/apps/details?id=com.internet.speed.meter.lite

**Comment by ADTC** [comment]
I only understood that proxy apps route the data through loopback (localhost, `lo`) interface and this gets counted in the total data transmission counts. Hence my fix was to exclude the counts for `lo` interface to give a more accurate result.

But as per codexss, this only works for the NAT mode, and not the VPN mode. Does the VPN mode create an additional network interface that routes the data through it? If so, how do I best approach the exclusion?

I don't know how the app mentioned by codexss does it.

**Comment by madeye** [comment]
A TUN device is created when VPNService started.

**Comment by ADTC** [comment]
That could explain the problem. I may have to change the approach to only counting a limited set of valid interfaces (such as ethernet and wifi) instead of excluding a non-exhaustive set of invalid interfaces (such as proxy loopback and tunnel devices).

Thanks.
