### ISSUE TITLE
[FR] Bring back table cypher support for connecting to internal servers

### ISSUE THREAD

**Issue by rayfoss** [shadowsocks/shadowsocks-android#2532]
**Is your feature request related to a problem? Please describe.**
I use a phone as a hotspot. To improve speeds and get around carrier controls, I need a VPN server installed on the phone. Shadowsocks is easy, fast and full featured compared to SSH tunneling and OpenVPN. On ShadowSocks, most ciphers rely on libcrypto, which has some bugs. I managed to get chacha20 working... But "tables" would be faster, easier on the hotspot battery, more portable to other phones and easier to install.

**Describe the solution you'd like**
Add a no encryption option. If we must, we can limit it to only servers on private IP addresses... Like 127.0.0.1 or 10.0.0.119

**Describe alternatives you've considered**
chacha20 is okay, but it still adds tons of overhead that will kill the hotspot hours earlier than otherwise. I tried installing OpenVPN server... but it's a nightmare on ARM+Android. SSH doesn't do UDP, has high overhead, and the VPN converter apps aren't robust.

**Additional Context:**
While I could install ShadowSocks client apps on all the hotspot network clients, I instead have a hotspot VPN app that routes all wlan traffic to the Android VPN client app, which subsequently sends the traffic to the app running the VPN server, baremetal or Termux.

**Comment by studentmain** [comment]
table cipher is slower than other method, due to it's encrypt table generation function...
