### ISSUE TITLE
手机端如何开启mptcp

### ISSUE THREAD

**Issue by liuyaxi** [shadowsocks/shadowsocks-android#2533]
手机端通过什么方法开启mptcp  双通道加速    服务端已支持

**Comment by Mygod** [comment]
I think mptcp should probably be implemented at plugin's side. @madeye Thoughts?

**Comment by madeye** [comment]
MPTCP requires a patched Linux kernel, I don't think we can do that on Android.

**Comment by liuyaxi** [comment]
> MPTCP requires a patched Linux kernel, I don't think we can do that on Android.

谢谢

**Comment by liuyaxi** [comment]
> MPTCP requires a patched Linux kernel, I don't think we can do that on Android.

如果您说的方式都满足，通过何种方法开启双通道加速呢？求解惑！！！谢谢。
