### ISSUE TITLE
Shadowsocks-Android builts on windows 10 failed.

### ISSUE THREAD

**Issue by voltwu** [shadowsocks/shadowsocks-android#2536]
I am using windows10 build this project. I have problems with shadowsocks-rust.

if I built from `cargo` in *shadowsocks-rust* directory. it's can go through successfully.
![QQ截图20200525150808](https://user-images.githubusercontent.com/45677662/82787720-9ed27900-9e99-11ea-80c0-43daf3dd4022.png)

However, if I built it under `shadowsocks-android` directory with `.\gradlew -p core clean build`.  an exception will be thrown out.
I use the following command to build:
```
.\gradlew -p core clean build
```
![QQ截图20200525155002](https://user-images.githubusercontent.com/45677662/82790893-69c92500-9e9f-11ea-83a6-e8348103144c.png)

The exception shows that I didn't have `openssl-sys`. But I have it, and already put it in the system environment. 
```
OPENSSL_DIR = C:\OpenSSL-Win64
```

![QQ截图20200525151439](https://user-images.githubusercontent.com/45677662/82789031-2de09080-9e9c-11ea-9e9f-1a1f2b152a74.png)

The exception is:
```
   Compiling pest v2.1.3
   Compiling block-padding v0.1.5
   Compiling foreign-types v0.3.2
   Compiling heck v0.3.1
   Compiling ring v0.16.13
   Compiling textwrap v0.11.0
error: failed to run custom build command for `openssl-sys v0.9.56`

Caused by:
  process didn't exit successfully: `D:\job\13.shadowsocks\shadowsocks-android\core\src\main\rust\shadowsocks-rust\target\debug\build\openssl-sys-c563c5c2392b1b4c\build-script-main` (exit code: 101)
--- stdoutng aho-corasick v0.7.10
cargo:rustc-cfg=const_fn6TING [1m 45s]
cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR
ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
CC_armv7-linux-androideabi = Some("D:\\softwares\\android\\sdk\\ndk\\21.1.6352462\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi21-clang.cmd")
CFLAGS_armv7-linux-androideabi = None
CFLAGS_armv7_linux_androideabi = None
TARGET_CFLAGS = None6.22
CFLAGS = None
CRATE_CC_NO_DEFAULTS = Nonev0.12.3
DEBUG = Some("true")1.1
running "perl" "./Configure" "--prefix=D:\\shadowsocks-android\\core\\src\\main\\rust\\shadowsocks-rust\\target\\armv7-linux-androideabi\\debug\\build\\openssl-sys-52f3e7afe9723601\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-engine" "no-async" "no-stdio" "no-shared" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=armv7-linux-androideabi"
```

**Comment by diamanat** [comment]
I also tried on Windows 10, and can't find version of perl that can built it - best choise is docker.

**Comment by voltwu** [comment]
@diamanat what's the version you were using. I mean that android studio, docker, shadowsocks-android, and other related components version.

**Comment by diamanat** [comment]
@voltwu you don't need anything else just docker and code

**Comment by voltwu** [comment]
@diamanat  Thank you. I use the Ubuntu system instead, and it's successful.  It is inconvenient for Windows.
