### ISSUE TITLE
能否增加DNS over TLS或DNS over HTTPS功能？

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-android#2537]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
使用DNS over TLS或DNS over HTTPS後，看視頻明顯加快。
原因可能是因為，GFW的深度包檢測，或日本梯子訪問8.8.8.8（8.8.8.8伺服器在美國）導致的UDP丟包？
Android 9內建DNS over TLS功能。Firefox PC版內建DNS over HTTPS功能。
**Describe alternatives you've considered**

**Additional context**

**Comment by Mygod** [comment]
Duplicate #2524
