### ISSUE TITLE
When import settings from url, some characters are neglected

### ISSUE THREAD

**Issue by yku12cn** [shadowsocks/shadowsocks-android#2546]
Please read contributing guidelines. Thanks.

**Describe the bug**
"\_" character in plug-in section is not handled correctly.
A URI generated by shadowsocks-android can not be import back to shadowsocks-android without information loss:
`ss://YWVzLTI1Ni1jZmI6cGFzc3dvcmQ@v2ray.demo.com:443?plugin=v2ray%3Bpath%3D%2Fs2_server%3Bloglevel%3Dnone%3Bhost%3Ddemo.com`

**To Reproduce**
Detailed description can be found here:
https://github.com/shadowsocks/v2ray-plugin-android/issues/28

**Expected behavior**
As comparison, the windows client can handle this perfectly

**Screenshots**
Detailed description can be found here:
https://github.com/shadowsocks/v2ray-plugin-android/issues/28

**Smartphone (please complete the following information):**
 - Android 10
 - Pixel 3a
 - Version: 5.0.5

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] v2ray
* [x] tls
* Hostname = demo.com
* Path = /ss_user

**Additional context**
@madeye @Mygod    either of you, please help me to figure out where I should post this bug...Thx

**Comment by madeye** [comment]
@Mygod looks the path is not correctly encoded.

**Comment by yku12cn** [comment]
> @Mygod looks the path is not correctly encoded.

Encoded or decoded? When import the same link to the windows-client, everything works fine.
And Percent-encoding should just pass through the "\_".

**Comment by madeye** [comment]
Found some related discussions here: https://stackoverflow.com/questions/18281593/uri-getqueryparameter-not-working-with-and-symbols

**Comment by madeye** [comment]
After some experiments, it looks that `getQueryParameter only returns the characters before `_`.

https://developer.android.com/reference/android/net/Uri#getQueryParameter(java.lang.String)

**Comment by yku12cn** [comment]
Good to know there is a fix. Thanks a lot.
But why missing "\_" in the first place. I mean, we use "\_" everywhere as a space holder.. Especially when naming something.....

**Comment by Mygod** [comment]
- > _
change my mind

**Comment by yku12cn** [comment]
> `- > _`
> change my mind
@Mygod 
Since you ask. '-' tends to have more functional meaning rather than '_'. E.g, most program takes '-' as an indicator of an option.  Aesthetically, '-' is more intrusive too.
As a perfect replacement of space, no one did a better job than '_'.
