### ISSUE TITLE
Sync error on Android

### ISSUE THREAD

**Issue by HiColinn** [shadowsocks/shadowsocks-android#2552]
My Dev Env Info:
---
OS:Windows10
AndroidStudio Ver:4.0
Gradle Ver:6.5
JDK:jdk8_x64
---
My Error :
  When I Sync this projrct,it will error,error msg:
`* What went wrong:
A problem occurred configuring root project 'shadowsocks-android'.
> Could not open cache directory 2mz7uuphgfawvpeuq4mci7gha (E:\DevelopTools\GradleRepo\caches\6.5-rc-1\gradle-kotlin-dsl\2mz7uuphgfawvpeuq4mci7gha).
   > Could not open cache directory eznv0t03hxedl0hykchm9lxgr (E:\DevelopTools\GradleRepo\caches\6.5-rc-1\gradle-kotlin-dsl-accessors\eznv0t03hxedl0hykchm9lxgr).
      > MALFORMED`

**Comment by chinachance** [comment]
How did it work

**Comment by alan1982** [comment]
I had same error,i try it ,not ok!

**Comment by janus-xiao** [comment]
这个问题有解决方案吗
