### ISSUE TITLE
Firestick shadowsocks 255 error (after having succeeded in connecting earlier)

### ISSUE THREAD

**Issue by shawnxy123** [shadowsocks/shadowsocks-android#2554]
I'm using shadowsocks (latest version) on my firestick, and I was having no problem connecting today. But all of a sudden, it won't connect and the error message is: libss-local exits too fast (255). I have tried uninstalling and reinstalling the app, clearing cache and data. None of them worked. Any idea what I could do? Thanks!

**Comment by Mygod** [comment]
logcat
