### ISSUE TITLE
Can't use with ADGUARD.

### ISSUE THREAD

**Issue by ExcellentHzj** [shadowsocks/shadowsocks-android#2555]
Device:Sony Xperia XZ1
OS: Android 9
Shadowsocks version:5.1.2
Shadowsocks Service Mode:Proxy Only
Route:Bypass LAN & mainland China
Remote DNS:dns.google

Adguard Filtering method:Local VPN
Proxy:Enable 
Proxy host:127.0.0.1
Type:socks5
Port:1080

DNS filters:
127.0.0.1:5450

Can't load some Gfw ban websites
for example:
Google.com
t66y.com
...

**Comment by terrytw** [comment]
You need to use transparent proxy mode. As proxy only does not provide DNS service. It's fairly obvious since "DNS port" is grayed out.
