### ISSUE TITLE
节点路由部分的配置建议放在设置选项里，作为全局配置

### ISSUE THREAD

**Issue by xixiri** [shadowsocks/shadowsocks-android#2556]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
我节点列表里有很多节点，但是默认都是全局路由，我想用绕过中国大陆地址这个模式就得一个个节点去改。因为微信你经常换ip的话腾讯会封你的号。所有要改绕过大陆地址

**Describe the solution you'd like**
希望把节点设置里路由部分的功能，拿出来作为公共配置，让所有节点使用，放在设置选项里就不错，我记得原来就是这样的呀，怎么现在改了

**Describe alternatives you've considered**
我没办法，只能一个个节点去改

**Additional context**
无

**Comment by cyber386** [comment]
基于单个配置文件的路由设置具有很高的灵活性，我认为不应该将路由作为全局设置，折中的方案是增加一个“应用路由设置到所有配置文件”的选项，就如同分应用代理那样。

**Comment by xixiri** [comment]
搞的有点复杂，灵活是灵活，但是你开发了别人用不上，没有使用场景就尴尬了，开发者麻烦，使用者也麻烦。我想不到有什么场景一部分节点需要走全局，一部分节点绕过中国。v2rayng的这个配置就是对所有节点设置的
