### ISSUE TITLE
v5.1.2不能转发udp了？

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#2559]
经测试，退回到v5.1.1是可以转发的
v5.1.2使用udp通讯的软件比如Google voice拨打电话会失败

**Comment by madeye** [comment]
Tried Google Voice locally, everything works well.

Also from the changelog, there's no change related to any network logic: https://github.com/shadowsocks/shadowsocks-android/compare/v5.1.1...v5.1.2

**Comment by baraja** [comment]
等稳定版出了我再测一下看看吧 
目前先用着511了
谢谢

**Comment by baraja** [comment]
换了台手机又测了一下，确认此bug存在
前提是我同时使用了v2ray-plugin（没有测试无插件的情况），5.1.1可以打通GV，5.1.2无声音过12秒挂断
是不是v2ray那边做了改动造成bug了？

**Comment by Mygod** [comment]
@madeye Presumably due to this: https://github.com/shadowsocks/shadowsocks-android/commit/fbffc9841fdcb586d6929af04d8302f490f52068

**Comment by madeye** [comment]
You need to setup a UDP fallback profile to enable UDP forwarding when SIP003 plugin is enabled.

**Comment by madeye** [comment]
We received a security report that the previous behavior has a potential flaw. So we change the default behavior here, avoiding UDP forwarding to same port of a SIP003 server.

**Comment by Mygod** [comment]
Makes sense. Thanks for the update.

**Comment by loyess** [comment]
Where is UDP fallback?  server? or client?

**Comment by windstander** [comment]
> Where is UDP fallback? server? or client?

我看到了这个帖子：
https://github.com/shadowsocks/shadowsocks-android/issues/2639

要启用UDP，就是复制一个一模一样的服务器信息，但是禁用插件。然后启用了插件的那个服务器信息里面的最下面就可以设置UDP配置了。
