### ISSUE TITLE
把ss切换到分屏下，再更改配置文件，上下传速率会互换

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#2561]
Please read contributing guidelines. Thanks.

**Describe the bug**
分屏时，更改配置文件，上下传速率互换

**To Reproduce**
1.打开youtube
2.把;youtube设定为分屏的上方
3.把SS设定为分屏的下方
4.切换配置文件

**Expected behavior**
下载大于上传

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: android 8.1.0
 - Device: nexus 6P
 - Version: 至少5.1.0
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-gcm
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
@madeye https://github.com/shadowsocks/shadowsocks-rust/commit/205eaa95addbb56fccc3d0d34705a92e79c8086b What is this

**Comment by madeye** [comment]
The previous order is wrong in the packet, causing a tx/rx order before.

**Comment by Mygod** [comment]
As far as I can tell it is in the wrong order on my side as well...

**Comment by madeye** [comment]
Okay, we may need to revert this in shadowsocks-rust.

**Comment by madeye** [comment]
I can reproduce the issue locally now.

**Comment by Mygod** [comment]
I have no idea what is happening now so I will leave it to your able hands.

Regarding https://github.com/shadowsocks/shadowsocks-rust/commit/205eaa95addbb56fccc3d0d34705a92e79c8086b, it is probably better to manually specify the order/endianness I think.

**Comment by madeye** [comment]
Should be fixed via https://github.com/shadowsocks/shadowsocks-rust/pull/279 now.

**Comment by Mygod** [comment]
Confirming fixed via 9b2095cc9eda26c256b1170befcfb8a6261b0195,
