### ISSUE TITLE
5.1.2 doesn't work with v2ray-plugin (with default plugin configuration)

### ISSUE THREAD

**Issue by iKirby** [shadowsocks/shadowsocks-android#2562]
**Describe the bug**
Version 5.1.2 doesn't work with v2ray-plugin. Same configuration works on 5.0.6, and also works on Windows version.

**To Reproduce**
1. Setup a profile with v2ray-plugin
2. Connect
3. Do the connectivity test
4. See error message "Unable to resolve host", and there is no internet connection
5. Check logcat, there are messages saying that libsslocal failed to connect to plugin

**Expected behavior**
Shadowsocks works well with v2ray-plugin.

**Smartphone (please complete the following information):**
 - Android version: 10 (QQ3A.200605.001, LineageOS 17.1-20200704-NIGHTLY-sailfish)
 - Device: Google Pixel
 - Version: Pre-release 5.1.2
 - Last version that did not exhibit the issue: Latest release 5.0.6

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

**Additional context**
"All" route mode doesn't work either.

Logcat

```
07-16 09:02:16.959 20300 20300 I GuardedProcessPool: start process: /data/app/com.github.shadowsocks-_m8azGdhDsWKnm9NXdEMuw==/lib/arm64/libtun2socks.so --netif-ipaddr 172.19.0.2 --socks-server-addr 127.0.0.1:1080 --tunmtu 1500 --sock-path sock_path --dnsgw 127.0.0.1:5450 --loglevel warning --enable-udprelay
...
07-16 09:02:17.136 20300 21113 E libsslocal: 2020-07-16T09:02:17.135+08:00 INFO  shadowsocks 1.8.12
07-16 09:02:17.137   648 18702 I netd    : networkAddRoute(129, "tun0", "198.64.0.0/10", "") <0.25ms>
07-16 09:02:17.138   648 18702 I netd    : networkAddRoute(129, "tun0", "198.128.0.0/9", "") <0.24ms>
07-16 09:02:17.139   648 18702 I netd    : networkAddRoute(129, "tun0", "199.0.0.0/8", "") <0.28ms>
07-16 09:02:17.140   648 18702 I netd    : networkAddRoute(129, "tun0", "200.0.0.0/7", "") <0.26ms>
07-16 09:02:17.141 20300 21113 E libsslocal: 2020-07-16T09:02:17.140+08:00 INFO  started plugin "/data/app/com.github.shadowsocks.plugin.v2ray-0SL8ulrtXDhPUZ3ebP6z9Q==/lib/arm64/libv2ray.so" on 127.0.0.1:37103 <-> 173.82.186.78:465 (21127)
...
07-16 09:02:17.347 21127 21127 I v2ray   : V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 android/arm64)
07-16 09:02:17.347 21127 21127 I v2ray   : A unified platform for anti-censorship.
07-16 09:02:17.350 21127 21127 W v2ray   : v2ray.com/core: V2Ray 4.23.2 started
...
07-16 09:02:22.808 20300 21113 E libsslocal: 2020-07-16T09:02:22.808+08:00 INFO  shadowsocks TCP listening on 127.0.0.1:1080
07-16 09:02:22.809 20300 21113 E libsslocal: 2020-07-16T09:02:22.809+08:00 INFO  shadowsocks DNS relay listening on tcp:127.0.0.1:5450
07-16 09:02:22.810 20300 21113 E libsslocal: 2020-07-16T09:02:22.809+08:00 INFO  shadowsocks DNS relay listening on udp:127.0.0.1:5450
07-16 09:02:24.984 20300 21113 E libsslocal: 2020-07-16T09:02:24.983+08:00 ERROR failed to connect 127.0.0.1:37103, retried 3 times, last_err: Connection refused (os error 111)
07-16 09:02:25.623   903  1216 E LightsService: Light requested not available on this device. 2
07-16 09:02:25.684   648 18702 I netd    : tetherGetStats() <4.90ms>
07-16 09:02:29.941 20300 21113 E libsslocal: 2020-07-16T09:02:29.940+08:00 ERROR failed to connect 127.0.0.1:37103, retried 3 times, last_err: Connection refused (os error 111)
07-16 09:02:34.947 20300 21113 E libsslocal: 2020-07-16T09:02:34.946+08:00 ERROR failed to connect 127.0.0.1:37103, retried 3 times, last_err: Connection refused (os error 111)
```

I thinks this should be the same as #2515 , but that has been closed due to inactivity. I'm sorry for my late reply on that issue. Logcat I captured before is at https://github.com/shadowsocks/shadowsocks-android/issues/2515#issuecomment-644718511 .

**Comment by madeye** [comment]
I cannot reproduce this locally.

From your log, v2ray looks killed at the very beginning. Have you installed any app that prevents background wake up?

**Comment by iKirby** [comment]
I'm really sorry. It's my fault. Just checked all the configurations, and found that plugin configurations are not imported when scanning QR code (generated from Windows version). In the previous logcat I remember that I tested using a server without special plugin configuration, may be I messed it up. Now it works well, thanks for your reply.

**Comment by iKirby** [comment]
@madeye  After more testing, I think I found the issue.

If I use v2ray-plugin without any configuration (with only one option "server"), and leave everything just default on v2ray-plugin for Android (plugin configuration "Not set"), it doesn't work on 5.1.2 but works on 5.0.6.

If I change the hostname to something other than "cloudfront.com", it works on 5.1.2.

**Comment by madeye** [comment]
@Mygod Looks like if the plugin options are not set, shadowsocks-rust will pass empty PLUGIN_OPTS to the plugin, which caused the issue here.
