### ISSUE TITLE
Android 5.0 移动网络耗电很厉害，再wifi情况下正常

### ISSUE THREAD

**Issue by afayge** [shadowsocks/shadowsocks-android#257]
shadowsocks 2.6.4再wifi下，正常，虽然其他网络的能耗全部算在shadowsocks下面。但是再移动通信4G网络下面，明显不正常，不使用，待机30-40分钟也有1% 的能耗。

shadowsocks 2.6.4, power consumption is OK with wifi, but at 4G shadowsocks need 1% each 30-40mins by standby.

**Comment by madeye** [comment]
Duplicate with #195
