### ISSUE TITLE
DNS leak issue

### ISSUE THREAD

**Issue by Coxxs** [shadowsocks/shadowsocks-android#2570]
**Is your feature request related to a problem? Please describe.**

When using `Route` option other than `All`, ~~all DNS requests~~ depending on the `Route` option user selected, all or some DNS requests will be sent to DNS resolver provided by ISP without proxy, which may causing privacy issue.

Here's my test result:
`Route` option | &nbsp;
------------ | -------------
All | No DNS leak
Bypass LAN | All DNS requests leaked to ISP provided DNS (!)
Bypass (LAN &) mainland China | non-blacklisted DNS requests sent to ISP provided DNS
GFW List | non-blacklisted DNS requests sent to ISP provided DNS
China List | All DNS requests leaked to ISP provided DNS (!)

For `Bypass LAN`, I think there shouldn't be any DNS leak.

For `China List`, all non-whitelisted domains should only use DNS resolver over proxy.

For `Bypass (LAN &) mainland China` and `GFW List`, consider when user visiting `por**ub.com`, ISP will see DNS request of a CDN domain "m1.nsimg.net" (not blocked), and now ISP knows what website user is visiting and knows user uses some method to bypass the block.

Here's a picture showing both the configuration and test result.

![image](https://user-images.githubusercontent.com/3007303/88775724-9fe49700-d1b7-11ea-8823-004ace708798.png)

**Describe the solution you'd like**
For `Route` option `Bypass LAN`, `China List`, send all DNS requests via proxy except known domains in whitelist.

Also, it would be nice to have a switch to allow user only use DNS resolver over proxy.

**Describe alternatives you've considered**
Add a warning to let user know the potential risk, when selecting "Route" option other than "All".

**Additional context**
https://twitter.com/AristineQT0I87/status/1288301512657997825

**Comment by madeye** [comment]
All your DNS queries are sent to the remote DNS that you set in the profile.

**Comment by Coxxs** [comment]
However I'm able to capture plain DNS requests using wireshark, when using Static IP (shown in the picture) **or** DHCP in Wifi Settings. The ss-android settings is also shown in the above picture.

**Comment by madeye** [comment]
And any domain name in the ACL are forced to be resolved with remote DNS.

**Comment by Coxxs** [comment]
Thanks for the speedy reply, I might misunderstand your first reply. I understand when using the "All" route policy, no DNS leak will happen (already mentioned in this issue). 

However, with the ss-android settings shown in the picture, I think there shouldn't be any DNS leak when I only "Bypass LAN".

**Comment by madeye** [comment]
Bypass LAN is a very special case. As there is no black-listed domains in [its ACL](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/assets/acl/bypass-lan.acl), all the DNS queries will goes to the local DNS.

For other ACL based routes like GFWList and China route, we expect no DNS leak for any black listed domains.

@Mygod what do you think.

**Comment by madeye** [comment]
Okay, the DNS leak is expected for any route other than `ALL`

https://github.com/shadowsocks/shadowsocks-rust/blob/7eac5416b303abd9cdc6fb9bdc0a27b53b749e39/src/relay/dnsrelay/mod.rs#L207

**Comment by Coxxs** [comment]
It seems `ss-android`(5.0.5) actually won't send DNS request of blacklisted domains to ISP resolver when using `Bypass (LAN &) mainland China` or `GFW List` route. I've update the issue to show the test result.

**Comment by Mygod** [comment]
> Okay, the DNS leak is expected for any route other than `ALL`
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/7eac5416b303abd9cdc6fb9bdc0a27b53b749e39/src/relay/dnsrelay/mod.rs#L207

I don't think that should be the case. The future was created but it should not be executed as it was not polled. In particular, if the hostname was matched (in ACL) then the other future will not be used. Let me know if this is not the case.

**Comment by Mygod** [comment]
Everything is working as expected here. For any domain that was not matched in ACL, two DNS probes will be sent, even in bypass LAN mode (this is so that local DNS would work, e.g. in case you want to connect to your computer under `my-windows-pc.home`).

If you worry about DNS leaking to local DNS provider, do either:

1. Enable Private DNS on Android 9. (however, it is incompatible with ACL on Android 10+, #2524)
2. Use ALL routing in app. This way all traffic and DNS probes will be only sent to remote. You can switch between two route options quickly by creating two identical profiles with different route options.

Currently if you are using bypass (LAN and) China or GFW list, and if a domain name is in GFW list, the probe will be sent to remote only. In the future, we hope to support more versatile ACL routes (#2525).

**Comment by Coxxs** [comment]
Thank you for the detailed explanation. Sending both local & remote DNS request do make the connectivity and performance  better, I can see the reason behind that. But it seems that compared to these conveniences, DNS leaks are too harmful. As stated in this issue, even with DNS leak of non-blocked CDN domains, ISP could still tell which blocked site user is visiting and may even able to guess the proxy ip (since both request are fired at the same time). 

I will use `all` routing form now on (thanks for the suggestions!), but I still think this should be an `enhancement` to carefully consider about. Let user judge if they need better privacy or performance at first place. Actually, with my old settings, I'm completely unaware of the DNS leak until someone [tweeted](https://twitter.com/AristineQT0I87/status/1288301512657997825) about this.

**Comment by Mygod** [comment]
@madeye Maybe we can add an option to disable the double DNS probe behavior (maybe call it "Advanced routing") and warn user about its risks?

**Comment by madeye** [comment]
@Mygod we can put that option in the global settings, and disable it by default.

**Comment by Mygod** [comment]
Actually that was a terrible idea. Never mind that. The best way to fix this is to use private DNS.

**Comment by Mygod** [comment]
Closing this as dup #2524.
