### ISSUE TITLE
从5.0.6升级以后，GostPlugin 不能正常使用了

### ISSUE THREAD

**Issue by ddgweb** [shadowsocks/shadowsocks-android#2572]
当然，我知道这不是shadowsocks-android的主要issue，但是有点好奇，是什么原因导致的呢？
我看了一下release的log，好像是更新了aes算法？

GostPlugin https://github.com/xausky/ShadowsocksGostPlugin

**Comment by Mygod** [comment]
Possibly duplicate of #2562
