### ISSUE TITLE
使用订阅链接的节点不能设置路由绕过大陆网址

### ISSUE THREAD

**Issue by xixiri** [shadowsocks/shadowsocks-android#2574]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
新版本的ss支持订阅链接了，但是订阅的节点不能编辑，无法调整路由设置，我想设置成绕过大陆局域网和大陆地址

**Describe the solution you'd like**
建议把路由设置放到菜单 设置选项里，作为软件的全局功能

**Describe alternatives you've considered**
无法做到

**Additional context**
无

**Comment by Mygod** [comment]
Feature settings are editable.

**Comment by xixiri** [comment]
确实点那个小云朵图标可以进去编辑，我看错了
