### ISSUE TITLE
[Feature Request] HTTP support and Option to remove status bar icon

### ISSUE THREAD

**Issue by chromer030** [shadowsocks/shadowsocks-android#2577]
Hi , Thanks for this great app.
If it's possible please add these features to this useful app :

1- Supports for HTTP protocol in proxy mode , useful for apps like twitter.
2- Option to remove app's icon in status bar.
3- Allow Connections form the LAN
Thanks again.

**Comment by Mygod** [comment]
For 2, edit it in your system app setting for Android 8.0+.

**Comment by chromer030** [comment]
But for android 7 and below , there is no such settings ☹️☹️☹️

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-rust/issues/349
