### ISSUE TITLE
No version of NDK matched the requested version 21.0.5935234. Versions available locally: 21.0.6113669, 21.3.6528147

### ISSUE THREAD

**Issue by shuhaoSCode** [shadowsocks/shadowsocks-android#2578]
mac os 10.15.6

No version of NDK matched the requested version 21.0.5935234. Versions available locally: 21.0.6113669, 21.3.6528147

Install NDK '21.0.5935234' and sync project

can not install NDK '21.0.5935234'

**Comment by waheedsabir** [comment]
I am also facing the same issue NDK
