### ISSUE TITLE
请考虑增加一个功能：使用kcptun插件的时候不用输入“服务器”和“远程端口”，只需要密码和加密方式，其他一切交给kcptun插件

### ISSUE THREAD

**Issue by wholenewx** [shadowsocks/shadowsocks-android#2580]
简单来说是希望能实现“手机上通过shadowsocks翻进内网”的功能，情景如下：

人在A地，国内C地有一台没有公网IP的电脑，需要连接上此电脑进行一些操作，以及在某些情况下让A地的一些程序和app走国内网络，电脑上好办，手机上根本没办法操作，折腾来折腾去最后利用kcptun整了一个链路：

**A地 kcptun client → → → VPS kcptun server → VPS kcptun client → VPS zerotier → → → C地 zerotier → C地 kcptun server → C地 shadowsocks server**      （这个链路还能精简吗？）

在A地的电脑端用shadowsocks-QT直连A地 kcptun client可以实现电脑上的程序直接用国内的网络处理事物，速度快又稳，在手机上就要运行arm版的kcptun client二进制文件：

./kcptunc -r "VPS:port" -l ":phoneport" -mode fast2  （就这么简单，电脑上也是这个配置）

然后shadowsocks-android新建一个连接，服务器127.0.0.1, 端口phoneport，密码和加密方式填服务端的设定就可以使用了，但是很多问题：

1,麻烦，每次使用前手机的selinux必须关闭，否则无法使用

2,慢，非常慢，A和C都是百兆网络，A端的电脑上这样连接下载文件速度可以达到1M～2M，但是在手机上只有几十KB，这个比较是电脑和手机都在同一个路由器下面的时候作的比较，如果是连接之前配置好的其他VPS，手机上最高可以有10M左右的速度

3,除了慢还不稳，表现为有时候完全没有数据流量，刷新好几次浏览器才又有了流量

（4, 4.x的版本还不能这么用，连不了，5.x的才可以这么用）

这么多年shadowsocks-android一直表现优异，上面这些问题大概率是手机上的二进制文件和apk的配合问题，我尝试直接让kcptun插件来代替二进制文件，"remoteaddr=VPS:PORT;mode=fast2"，但是“服务器设置”里的“远程端口”绕不过去，就算不填也会自动生成一个8388，结果就是完全连不上，一个字节的流量都不会有。我的理解，一般的使用情景下kcptun插件工作的时候shadowsocks-android里面只需要定义好SS server的密码和加密方式，其他的什么都不需要管只要把网络流量喂给kcptun插件就行了，所以也许稍微做一点修改就可以实现“手机上通过shadowsocks翻进内网”，这应该能帮到很多人，不单是我现在这个需求。

其他一些考虑：

1,手机上直接用zerotierOne不行吗？
还真不行，为此折腾了一个星期，本身zerotierOne能连接上内网但是除了zerotierOne之外的其他app一概用不上它的网络，去zerotier官方论坛提问也没解决问题，而且手机上的zerotier没几分钟就断了，电池管理里面设置它为“不优化”也没用，两个手机都这样，最新版1.4.6。（电脑上直接用zerotier是可以的，方便的很）

2,手机上能代替shadowsocks-android的其它app试过吗？
试过proxydroid、bifrostv什么的，表现更差，我用shadowsocks-android好几年了，能自己折腾解决一些小问题，而且自己搭建shadowsocks server也很熟了，所以其他的app简单试过觉得不上手就扔了

之前人在国内的时候用这个app翻出去，现在人到了国外却因为国内的业务需求又要翻回来，希望看在能折腾的份上开发者帮忙实现一下新功能吧！谢谢！

**Comment by dev4u** [comment]
我觉得你说的内容跑题了。

不填地址、端口，要怎么建立服务？
你是不是需要在内网里打洞？frp了解一下。

**Comment by wholenewx** [comment]
> 我觉得你说的内容跑题了。
> 
> 不填地址、端口，要怎么建立服务？

在使用kcptun插件的时候IP地址和端口是定义在kcptun插件里的，shadowsocks-android把流量喂给插件的

> 你是不是需要在内网里打洞？frp了解一下。

是要打洞，用的是zerotier

**Comment by dev4u** [comment]
> > 我觉得你说的内容跑题了。
> > 不填地址、端口，要怎么建立服务？
> 
> 在使用kcptun插件的时候IP地址和端口是定义在kcptun插件里的，shadowsocks-android把流量喂给插件的
> 
喔，你这么一说，我好像有印象了。其实你发个PR过来，我相信维护者很乐意合并进去的。

**Comment by wholenewx** [comment]
> 
> 喔，你这么一说，我好像有印象了。其实你发个PR过来，我相信维护者很乐意合并进去的。

PR是什么？不好意思我不是程序员
