### ISSUE TITLE
v5.1.3 not connectable on Android 11 beta with simple-obfs

### ISSUE THREAD

**Issue by gregist** [shadowsocks/shadowsocks-android#2582]
Please read contributing guidelines. Thanks.

**Describe the bug**
5.1.3 not connectable to remote server on Android 11 beta with simple-obfs, whereas 5.1.2 works fine with identical configuration.

**Screenshots**
![Screenshot_20200925-151422](https://user-images.githubusercontent.com/6292095/94237928-29a7ab00-ff42-11ea-8f87-14753a24f076.png)
![Screenshot_20200925-151336](https://user-images.githubusercontent.com/6292095/94237938-2ca29b80-ff42-11ea-935f-02ea9b342c3d.png)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [‎11.0.0_r3]
 - Device: [Google Pixel 3a XL]
 - Version: [5.1.3]
 - Last version that did not exhibit the issue: [5.1.2]

**Configuration**
client side: see screenshot
server side: libev v3.3.5
```
    "server":["[::0]","0.0.0.0"],
    "server_port":80,
    "password":"passwd",
    "timeout":86400,
    "method":"chacha20-ietf-poly1305",
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
```

**Comment by onlymash** [comment]
Same for Android 10

**Comment by madeye** [comment]
It's expected. simple-obfs has been deprecated for years, try the latest v2ray-plugin 1.3.3 instead.

**Comment by onlymash** [comment]
> It's expected. simple-obfs has been deprecated for years, try the latest v2ray-plugin 1.3.3 instead.

v2ray-plugin not work too

**Comment by madeye** [comment]
@onlymash https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.1.3

**Comment by onlymash** [comment]
Why not update it in the play store🤔

**Comment by madeye** [comment]
Double check you joined the beta tester of v2ray-plugin in the play store. @onlymash

**Comment by kn007** [comment]
> Double check you joined the beta tester of v2ray-plugin in the play store. @onlymash

v2ray-plugin has no beta channel in the play store

**Comment by gregist** [comment]
> @onlymash https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.1.3

Thanks. would simple-obfs get a hotfix too?
