### ISSUE TITLE
Suddenly not working under bypass lan and mainland china mode

### ISSUE THREAD

**Issue by zzj0311** [shadowsocks/shadowsocks-android#2583]
Please read contributing guidelines. Thanks.

**Describe the bug**

The 'same' profile works under GFW list mode but not bypass lan and mainland china mode, with toast
```
......unable to resolve host "cp.cloudflare.com"......
```
Just happened this morning and no app version update is done I thing

**To Reproduce**
Use 'bypass LAN and china mainland'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred] Android 10 oos 10.3.2
 - Device: [e.g. Google Pixel XL] Oneplus 7 pro
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"] 5.1.3
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
It's for now reproducible on my phone

**Comment by Omico** [comment]
I have the same issue before. The problem was solved after I followed the changelog.

> Make sure the plugin is also updated to the latest:
> v2ray-plugin: https://github.com/shadowsocks/v2ray-plugin-android/releases/tag/v1.3.3
> kcptun: https://github.com/shadowsocks/kcptun-android/releases/tag/v1.0.1

These latest plugins haven't been published in Play Store yet.

**Comment by zzj0311** [comment]
@Omico solved😂 thanks！

**Comment by lyancang-sh** [comment]
it means your ip has been banned by GW
