### ISSUE TITLE
The obfs connection has been under test

### ISSUE THREAD

**Issue by Roiyaru** [shadowsocks/shadowsocks-android#2586]
Please read contributing guidelines. Thanks.

**Describe the bug**
The connection using obfs cannot be established. It is normal on version 5.1.2, and problems occur after updating to 5.1.3

**To Reproduce**
The configuration imported through the subscription is normal on 5.1.2.  After updating to 5.1.3, the connection cannot be made successfully, and it has been in the "testing" state

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [MIUI12-Android11]
 - Device: [RedMi K30 Pro]
 - Version: [5.1.3]
 - Last version that did not exhibit the issue: [5.1.2]

**Configuration**
Put an `x` inside the [ ] that applies.

* [√ ] IPv4 server address
* [ ] IPv6 server address
* [√ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ √] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [ √] DNS over UDP
* Plugin configuration (The configuration uses obfs, but all plugins have been installed.):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by arbabseyfola** [comment]
> Please read contributing guidelines. Thanks.
> 
> **Describe the bug**
> The connection using obfs cannot be established. It is normal on version 5.1.2, and problems occur after updating to 5.1.3
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> The configuration imported through the subscription is normal on 5.1.2. After updating to 5.1.3, the connection cannot be made successfully, and it has been in the "testing" state
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Android/Chrome OS version: [MIUI12-Android11]
> * Device: [RedMi K30 Pro]
> * Version: [5.1.3]
> * Last version that did not exhibit the issue: [5.1.2]
> 
> **Configuration**
> Put an `x` inside the [ ] that applies.
> 
> * [√ ] IPv4 server address
> * [ ]  IPv6 server address
> * [√ ] Client IPv4 availability
> * [ ]  Client IPv6 availability
> * Encrypt method:
> * Route
>   
>   * [ √] All
>   * [ ]  Bypass LAN
>   * [ ]  Bypass China
>   * [ ]  Bypass LAN & China
>   * [ ]  GFW List
>   * [ ]  China List
>   * [ ]  Custom rules
> * [ ]  IPv6 route
> * [ ]  Apps VPN mode
>   
>   * [ ]  Bypass mode
> * Remote DNS: dns.google
> * [ √] DNS over UDP
> * Plugin configuration (The configuration uses obfs, but all plugins have been installed.):
> * [ ]  Auto Connect
> * [ ]  TCP Fast Open
> * If you're not using VPN mode, please supply more details here:
> 
> **Additional context**
> Add any other context about the problem here.

Update v2ray plugin to V1.3.3 problem will fixed.

**Comment by Roiyaru** [comment]
> > Please read contributing guidelines. Thanks.
> > **Describe the bug**
> > The connection using obfs cannot be established. It is normal on version 5.1.2, and problems occur after updating to 5.1.3
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > The configuration imported through the subscription is normal on 5.1.2. After updating to 5.1.3, the connection cannot be made successfully, and it has been in the "testing" state
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > **Smartphone (please complete the following information):**
> > 
> > * Android/Chrome OS version: [MIUI12-Android11]
> > * Device: [RedMi K30 Pro]
> > * Version: [5.1.3]
> > * Last version that did not exhibit the issue: [5.1.2]
> > 
> > **Configuration**
> > Put an `x` inside the [ ] that applies.
> > 
> > * [√ ] IPv4 server address
> > * [ ]   IPv6 server address
> > * [√ ] Client IPv4 availability
> > * [ ]   Client IPv6 availability
> > * Encrypt method:
> > * Route
> >   
> >   * [ √] All
> >   * [ ]   Bypass LAN
> >   * [ ]   Bypass China
> >   * [ ]   Bypass LAN & China
> >   * [ ]   GFW List
> >   * [ ]   China List
> >   * [ ]   Custom rules
> > * [ ]   IPv6 route
> > * [ ]   Apps VPN mode
> >   
> >   * [ ]   Bypass mode
> > * Remote DNS: dns.google
> > * [ √] DNS over UDP
> > * Plugin configuration (The configuration uses obfs, but all plugins have been installed.):
> > * [ ]   Auto Connect
> > * [ ]   TCP Fast Open
> > * If you're not using VPN mode, please supply more details here:
> > 
> > **Additional context**
> > Add any other context about the problem here.
> 
> Update v2ray plugin to V1.3.3 problem will fixed.
> https://github.com/shadowsocks/v2ray-plugin-android/releases

Did not solve the problem, I now fall back to version 5.1.2, everything is fine.

**Comment by eebssk1** [comment]
This happened on my friends' oneplus too,however I can't get logs from him.I'm using CrDroid and it's fine with me,which makes this look like MiUI(OEM Rom)'s problem.

**Comment by Roiyaru** [comment]
This bug has been fixed in version 5.1.4.
