### ISSUE TITLE
Add User Agent request for SIP008 Subscription

### ISSUE THREAD

**Issue by betaxab** [shadowsocks/shadowsocks-android#2589]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
Subscription API cound not recognize Client type.

**Describe the solution you'd like**
Set default User-Agent to `ShadowsocksAndroid/$version` (Example), instead of default `Dalvik/x.x.x`.

**Describe alternatives you've considered**
May add Add a custom User-Agent field, allow users specify it should be better?

**Additional context**

I feel this is an useful feature, I have a Subscription API, it uses User-Agent to determine the client type, e.g. ClashForAndroid, Surfboard, ShadowsocksWindows etc. It will return corresponding configuration file according UA type.
Since it does not use any parameters, this API URL can be general used on any supported Client, no need to remember which parameters is which Client, no need to change URL parameters.

Thanks.

**Comment by Mygod** [comment]
No.

**Comment by database64128** [comment]
`shadowsocks-windows` implemented this in shadowsocks/shadowsocks-windows#2978 with an added option to allow the user to override the default User-Agent. I think clients identifying themselves correctly and clearly can be helpful for small scale online configuration administrators, which in my opinion, is the primary target audience of SIP008.

**Comment by Mygod** [comment]
The point of SIP008 is to have the *same* config for every client implementation. If you want to track users just use query parameters.
