### ISSUE TITLE
GFW列表的路由方式比绕过大陆地址延迟高很多

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-android#2590]
Please read contributing guidelines. Thanks.

**Describe the bug**
我是配置是Caddy+TLS证书+v2ray-plugin+ss，在配置不变的情况下，路由方式选为绕过局域网及中国大陆地址以及全局等方式，软件HTTPS握手都在300毫秒以下，而使用GFW列表方式时，握手时间达到1800毫秒。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable): v2ray-plugin: tls;host=myhost;path=/mypath;
* [x ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by dev4u** [comment]
自己分析一下就能明白问题会是什么，cf不在gfw下。

**Comment by triaqu** [comment]
这个问题与CF没任何关系。任何方式连接SS服务，路由选GFW列表，测试连接HTTPS握手延时要比其它路由方式高2、3倍。

**Comment by dev4u** [comment]
> 这个问题与CF没任何关系。任何方式连接SS服务，路由选GFW列表，测试连接HTTPS握手延时要比其它路由方式高2、3倍。

请参阅这段代码的实现逻辑。
https://github.com/shadowsocks/shadowsocks-android/blob/36576a6113d69dc91875441dc115fb34da003313/core/src/main/java/com/github/shadowsocks/net/HttpsTest.kt#L82

**Comment by triaqu** [comment]
@dev4u 这逻辑是不是有问题呢，测试握手延时应该是测试经过代理后的连接速度，如测不过代理的速度没意义。个人意见。

**Comment by dev4u** [comment]
> @dev4u 这逻辑是不是有问题呢，测试握手延时应该是测试经过代理后的连接速度，如测不过代理的速度没意义。个人意见。

等你再了解多点整个工作逻辑后，再讨论这个吧。有更好的实现，也可以发PR。

**Comment by dev4u** [comment]
> @dev4u 这逻辑是不是有问题呢，测试握手延时应该是测试经过代理后的连接速度，如测不过代理的速度没意义。个人意见。

等你再了解多点整个工作逻辑后，再讨论这个吧。有更好的实现，也可以发PR。
