### ISSUE TITLE
Feature request: clarifying README/Contributing guideline

### ISSUE THREAD

**Issue by jamiemott** [shadowsocks/shadowsocks-android#2591]
**Is your feature request related to a problem? Please describe.**
As someone new to open source contributing, I found the README and CONTRIBUTING documents to be not quite enough to get me going on this project.

**Describe the solution you'd like**
README: Add short description of project below header, add gif of built project, link to prereqs, general format cleanup
CONTRIBUTING: clarify process

**Describe alternatives you've considered**
Leave as-is

**Additional context**
I am currently taking an open source software class and we are evaluating OSS project documentation.

**Comment by Mygod** [comment]
You are welcome to submit a PR.

**Comment by jamiemott** [comment]
It looks like I will need write access in order to publish a branch and make a PR.  Is there a process for requesting that access?  I can add that into the contributing document.

**Comment by studentmain** [comment]
> It looks like I will need write access in order to publish a branch and make a PR.  Is there a process for requesting that access?  I can add that into the contributing document.

Use fork to create your own copy, make change, there.
