### ISSUE TITLE
How to use Android phone as a server

### ISSUE THREAD

**Issue by jarno520** [shadowsocks/shadowsocks-android#2594]
I want to use Android phone as a server, and then use other mobile phones to connect this mobile phone to access the Internet. How should I use it? Does this open source code support this feature?

Other phones are far away from this Android phone

**Comment by madeye** [comment]
Nope, you cannot do that.

You need something else: https://play.google.com/store/apps/details?id=be.mygod.vpnhotspot&hl=en&gl=US
