### ISSUE TITLE
Huawei mobile phone unable to use after connection

### ISSUE THREAD

**Issue by SpaceCZ** [shadowsocks/shadowsocks-android#2595]
After the Huawei phone connected, the test HTTPS handshake connection existed, but the web page failed to open.Only upload without download

**Comment by 907597029** [comment]
mode=fast;dscp=0;crypt=aes;parityshard=3;rcvwnd=512;key=very fast;sndwnd=512;mtu=1350;datashard=10

记得配置一下kcptun里面的设置 没压缩传输的就删除nocomp这一条

**Comment by SpaceCZ** [comment]
好的，非常感谢，我试试
