### ISSUE TITLE
error[E0463]: can't find crate for `core`

### ISSUE THREAD

**Issue by janus-xiao** [shadowsocks/shadowsocks-android#2597]
> Task :core:cargoBuildArm
   Compiling libc v0.2.79
   Compiling proc-macro2 v1.0.24
   Compiling syn v1.0.44
   Compiling cfg-if v0.1.10
   Compiling typenum v1.12.0
   Compiling memchr v2.3.3
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-linux-androideabi` target may not be installed

error: aborting due to previous error

aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
could not compile `cfg-if`.

build failed, waiting for other jobs to finish...

error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-linux-androideabi` target may not be installed

error: aborting due to previous error
aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: build failed
build failed

**Comment by dev4u** [comment]
= note: the armv7-linux-androideabi target may not be installed
