### ISSUE TITLE
部分小米手机的微信无法接收观看聊天记录里发过来的视频

### ISSUE THREAD

**Issue by gyan850718** [shadowsocks/shadowsocks-android#2598]
部分小米手机的微信无法接收观看聊天记录里发过来的视频
发出去的可以看，不使用VP*也可以看，图片发送接收都可以看
就是好友发来的小视频都看不了，不管是1秒的还是1分钟的视频都看不了，也下载不了

**Comment by dev4u** [comment]
请检查配置

**Comment by snower** [comment]
似乎5.0以上版本在部分通过tcp发出的dns解析请求是不是有啥bug？很多tcp Reset然后访问国内网站都很慢了，而且最近ipv6的网站似乎开始增多，比如抖音啥的cdn似乎都开始走ipv6了，但是ipv6的支持似乎并不完整，会不会和这两有啥关系

**Comment by dev4u** [comment]
> 似乎5.0以上版本在部分通过tcp发出的dns解析请求是不是有啥bug？很多tcp Reset然后访问国内网站都很慢了，而且最近ipv6的网站似乎开始增多，比如抖音啥的cdn似乎都开始走ipv6了，但是ipv6的支持似乎并不完整，会不会和这两有啥关系

试试在代理列表中剔除掉抖音测试

**Comment by snower** [comment]
> > 似乎5.0以上版本在部分通过tcp发出的dns解析请求是不是有啥bug？很多tcp Reset然后访问国内网站都很慢了，而且最近ipv6的网站似乎开始增多，比如抖音啥的cdn似乎都开始走ipv6了，但是ipv6的支持似乎并不完整，会不会和这两有啥关系
> 
> 试试在代理列表中剔除掉抖音测试

抖音本来就不在代理列表里的，但是dns请求还是有部分会发到远程服务器，而且是通过tcp方式发送的，服务器在家里的路由上了，用来代理连家里网络了

似乎不开通过udp远程解析ip的情况下还是有部分dns会通过tcp方式发送到远程这个问题似乎一直存在的呐，然后如果不加入subnet选项的情况下，那么dns拿到的不是最近的地址，访问常常就会很慢了
