### ISSUE TITLE
如果在服务器地址中，填入域名并启用UDP转发，则ss服务会失效。

### ISSUE THREAD

**Issue by f1199252** [shadowsocks/shadowsocks-android#260]
问题重现：
1、我用一个公网可被解析的域名，映射了我的一台国外的主机；
2、用界面的服务器地址中，填入这个域名；
3、启用UDP转发；
4、路由选择全局；
5、勾选全局代理；
6、开启服务。

得到的结果：
可连接到我架设了ss服务的主机，但所有应用的网络都连接不了。

期望的结果：
所有应用的服务都能正常使用。

如果路由选择绕过局域网及大陆地址，则国内的应用仍可使用，国外的仍不正常。

异常分析：
略

**Comment by madeye** [comment]
Make sure your server supports UDP relay.
