### ISSUE TITLE
Is it possible to use addDisallowedApplication instead of protect in VpnService

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-android#2608]
Current implementation relies on a RPC call from the underlying `sslocal` to the Application to call `VpnService.protect`, which is for setting a `SO_MARK` on the socket file descriptor to bypass all outbound data.

But is it possible to make use of [VpnService.Builder.addDisallowedApplication](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String))?

**Comment by madeye** [comment]
It's possible but we want to avoid that.

Because we expect the shadowsocks app itself needs to be proxied, to help testing the connection, fetching remote ACL rules and etc.

**Comment by zonyitoo** [comment]
Sounds reasonable.

But with `addDisallowedApplication` will help simplfied the whole process. RPC calls still have extra overhead.

**Comment by madeye** [comment]
Actually Android system is full of IPC calls: https://developer.android.com/guide/components/aidl

So don't worry about that.

**Comment by Mygod** [comment]
#1742

**Comment by zonyitoo** [comment]
2018 ... So what's your plan? @Mygod

**Comment by Mygod** [comment]
It's abandoned and no plan to revive it. As detailed in the post, it could be used for debugging purposes.
