### ISSUE TITLE
java.lang.AbstractMethodError in v5.1.5

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2609]
Seems to be getting a lot of these...

```
abstract method "java.lang.Object androidx.camera.core.impl.CameraFactory.getCameraManager()"
androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9 (CameraX.java:566)
androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX
androidx.camera.core.-$$Lambda$CameraX$u-Xx2b6YXY5GXNXRh-mDiDnHdpQ.run (Unknown Source:10)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
```

**Comment by madeye** [comment]
It looks related to this change https://github.com/shadowsocks/shadowsocks-android/commit/8e17e4fb96386affb1d80d9e986d462d8cc3b65c#diff-42f7d174d818d9eae31131e23a20b10400ff59879ebbba231984485fb5ea2fb0R20

Revert back to alpha17.

**Comment by xizhang** [comment]
FYI CameraX's camera-view and camera-core have to be used in lock step. e.g. they both have to be upgraded to certain version. If they are out of sync, you will get the AbstractMethodError.
