### ISSUE TITLE
GFW or custom rule is not working with v5.1.6

### ISSUE THREAD

**Issue by cpstar** [shadowsocks/shadowsocks-android#2611]
Please read contributing guidelines. Thanks.

**Describe the bug**
[EN]Except GFW and ACL/items, other options for the route are effective, after I updated to 5.1.6 from Google Play a few moments earlier. With the same server, at ALL route, the connectivity-testing only went to 600-1000ms, but at Custom Rule (items or online ACL) the connectivity-testing would take about 30,000+ms. Even though, google youtube or other blocked site wouldn't be open.
[CN]从G商店升级了5.1.6之后，除了全局、绕开大陆等相关选项能够正常工作走数据以外，GFW和自定义规则（无论规则使用ACL或者逐条规则），均不能收发数据。连通性测试上，同样的服务器，全局或绕开大陆等，几百毫秒，GFW和自定义能有几十秒，且网站仍然打不开。

**To Reproduce**
Install v5.1.6
I'm not sure it's the problem of mine, or the problem of this version, as it mentioned Refined ACL support in the change list on Google Play.

**Smartphone (please complete the following information):**
Huawei P20Pro with EMUI10

**Comment by madeye** [comment]
Disable private DNS and try again.

**Comment by cpstar** [comment]
> Disable private DNS and try again.

Ugh, it worked as I turned off the DoH/DoT.
So, conflict? and no solution at all?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/2524
