### ISSUE TITLE
不知道哪里有问题，编译卡在了这里

### ISSUE THREAD

**Issue by hw1020** [shadowsocks/shadowsocks-android#2617]
Please use the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead. Your issue will probably be closed.
> Task :core:cargoBuildArm
   Compiling openssl-sys v0.9.58
   Compiling libsodium-sys v0.2.6
error: could not find native static library `sodium`, perhaps an -L flag is missing?

could not find native static library `sodium`, perhaps an -L flag is missing?

error: aborting due to previous error

aborting due to previous error

error: could not compile `libsodium-sys`
could not compile `libsodium-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
build failed, waiting for other jobs to finish...

error: build failed

> Task :core:cargoBuildArm FAILED
build failed

Execution failed for task ':core:cargoBuildArm'.
> Process 'command 'cargo'' finished with non-zero exit value 101

**Comment by dev4u** [comment]
编译时，确认机器处于科学上网，以免下载不了依赖。

**Comment by hw1020** [comment]
> 编译时，确认机器处于科学上网，以免下载不了依赖。

还是不行，不知道是不是我环境哪里不对，对安卓也不是特别熟悉，报错一直是这样的
> Task :core:cargoBuildArm
   Compiling ring v0.16.15
   Compiling openssl-sys v0.9.58
   Compiling libsodium-sys v0.2.6
error: failed to run custom build command for `ring v0.16.15`

failed to run custom build command for `ring v0.16.15`

Caused by:
  process didn't exit successfully: `E:\AndroidStudioProjects\shadowsocks-android-master\core\src\main\rust\shadowsocks-rust\target\debug\build\ring-7a4be1f4a61bb590\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("armv7-linux-androideabi")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_armv7-linux-androideabi = Some("D:\\AndroidStudioSdk\\ndk\\21.3.6528147\\toolchains\\llvm\\prebuilt\\windows\\bin\\armv7a-linux-androideabi23-clang.cmd")
  CFLAGS_armv7-linux-androideabi = None
  CFLAGS_armv7_linux_androideabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")

  --- stderr
  ENV ALLUSERSPROFILE=C:\ProgramData
  ENV ANDROID_HOME=D:\AndroidStudioSdk
  ENV APPDATA=C:\Users\Administrator\AppData\Roaming
  ENV AR_ARMV7-LINUX-ANDROIDEABI=D:\AndroidStudioSdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows\bin\arm-linux-androideabi-ar
  ENV CARGO=\\?\C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo.exe
  ENV CARGO_CFG_PANIC=unwind
  ENV CARGO_CFG_TARGET_ARCH=arm
  ENV CARGO_CFG_TARGET_ENDIAN=little
  ENV CARGO_CFG_TARGET_ENV=gnu
  ENV CARGO_CFG_TARGET_FAMILY=unix
  ENV CARGO_CFG_TARGET_FEATURE=aclass,dsp,thumb-mode,v5te,v6,v6k,v6t2,v7,vfp2
  ENV CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr
  ENV CARGO_CFG_TARGET_HAS_ATOMIC_EQUAL_ALIGNMENT=16,32,64,8,ptr
  ENV CARGO_CFG_TARGET_HAS_ATOMIC_LOAD_STORE=16,32,64,8,ptr
  ENV CARGO_CFG_TARGET_OS=android
  ENV CARGO_CFG_TARGET_POINTER_WIDTH=32
  ENV CARGO_CFG_TARGET_VENDOR=unknown
  ENV CARGO_CFG_UNIX=
  ENV CARGO_FEATURE_ALLOC=1
  ENV CARGO_FEATURE_DEFAULT=1
  ENV CARGO_FEATURE_DEV_URANDOM_FALLBACK=1
  ENV CARGO_FEATURE_ONCE_CELL=1
  ENV CARGO_HOME=C:\Users\Administrator\.cargo
  ENV CARGO_MAKEFLAGS=--jobserver-fds=__rust_jobserver_semaphore_2880934774 --jobserver-auth=__rust_jobserver_semaphore_2880934774
  ENV CARGO_MANIFEST_DIR=C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.15
  ENV CARGO_MANIFEST_LINKS=ring-asm
  ENV CARGO_PKG_AUTHORS=Brian Smith <brian@briansmith.org>
  ENV CARGO_PKG_DESCRIPTION=Safe, fast, small crypto using Rust.
  ENV CARGO_PKG_HOMEPAGE=
  ENV CARGO_PKG_LICENSE=
  ENV CARGO_PKG_LICENSE_FILE=LICENSE
  ENV CARGO_PKG_NAME=ring
  ENV CARGO_PKG_REPOSITORY=https://github.com/briansmith/ring
  ENV CARGO_PKG_VERSION=0.16.15
  ENV CARGO_PKG_VERSION_MAJOR=0
  ENV CARGO_PKG_VERSION_MINOR=16
  ENV CARGO_PKG_VERSION_PATCH=15
  ENV CARGO_PKG_VERSION_PRE=
  ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR=D:\AndroidStudioSdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows\bin\arm-linux-androideabi-ar
  ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_CC=D:\AndroidStudioSdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows\bin\armv7a-linux-androideabi23-clang.cmd
  ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=E:\AndroidStudioProjects\shadowsocks-android-master\build\linker-wrapper\linker-wrapper.bat
  ENV CC_ARMV7-LINUX-ANDROIDEABI=D:\AndroidStudioSdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows\bin\armv7a-linux-androideabi23-clang.cmd
  ENV COMMONPROGRAMFILES=C:\Program Files\Common Files
  ENV COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
  ENV COMMONPROGRAMW6432=C:\Program Files\Common Files
  ENV COMPUTERNAME=QQWW
  ENV COMSPEC=C:\WINDOWS\system32\cmd.exe
  ENV DEBUG=true
  ENV DRIVERDATA=C:\Windows\System32\Drivers\DriverData
Caused by:

  ENV FP_NO_HOST_CHECK=NO
  ENV GOROOT=E:\Go
  ENV HOMEDRIVE=C:
  ENV HOMEPATH=\Users\Administrator
  ENV HOST=x86_64-pc-windows-msvc
  ENV IDEA_INITIAL_DIRECTORY=D:\Program Files\Android\Android Studio\bin
  ENV JAVA_HOME=D:\JAVA_HOME
  ENV LD_LIBRARY_PATH=C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib
  ENV LOCALAPPDATA=C:\Users\Administrator\AppData\Local
  ENV LOGONSERVER=\\QQWW
  ENV MAVEN_HOME=D:\Program Files\apache-maven-3.6.3
  ENV NDK_HOME=D:\AndroidStudioSdk/ndk/21.3.6528147
  ENV NUMBER_OF_PROCESSORS=12
  ENV NUM_JOBS=12
  ENV ONEDRIVE=C:\Users\Administrator\OneDrive
  ENV OPENSSL_DIR=C:\OpenSSL-Win64
  ENV OPT_LEVEL=0
  ENV OS=Windows_NT
  ENV OUT_DIR=E:\AndroidStudioProjects\shadowsocks-android-master\core\src\main\rust\shadowsocks-rust\target\armv7-linux-androideabi\debug\build\ring-265355c1a8d37598\out
  ENV PATH=E:\AndroidStudioProjects\shadowsocks-android-master\core\src\main\rust\shadowsocks-rust\target\debug\deps;E:\AndroidStudioProjects\shadowsocks-android-master\core\src\main\rust\shadowsocks-rust\target\debug;C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Users\Administrator\.cargo\bin;C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\JAVA_HOME\bin;D:\JAVA_HOME\jre;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;d:\Program Files\nodejs\;d:\Program Files\TortoiseSVN\bin;d:\Program Files\VisualSVN Server\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files (x86)\NetSarang\Xftp 7\;D:\Program Files (x86)\NetSarang\Xshell 7\;D:\Program Files (x86)\NetSarang\Xmanager 7\;D:\AndroidStudioSdk\platform-tools;E:\Go\bin;E:\Program Files\Git\cmd;C:\Program Files (x86)\sbt\bin;%ANDROID_NDK_HOME%;C:\msys64\usr\bin;%OPENSSL_DIR%\bin;C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Users\Administrator\.cargo\bin;C:\Program Files\CMake\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Administrator\AppData\Roaming\npm;D:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;D:\Program Files\phantomjs-2.1.1-windows\bin;D:\anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Users\Administrator\go\bin;
  ENV PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  ENV PROCESSOR_ARCHITECTURE=AMD64
  ENV PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
  ENV PROCESSOR_LEVEL=6
  ENV PROCESSOR_REVISION=2c02
  ENV PROFILE=debug
  ENV PROGRAMDATA=C:\ProgramData
  ENV PROGRAMFILES=C:\Program Files
  ENV PROGRAMFILES(X86)=C:\Program Files (x86)
  ENV PROGRAMW6432=C:\Program Files
  ENV PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;d:\Program Files\VisualSVN Server\PowerShellModules
  ENV PUBLIC=C:\Users\Public
  ENV RUSTC=rustc
  ENV RUSTC_LINKER=E:\AndroidStudioProjects\shadowsocks-android-master\build\linker-wrapper\linker-wrapper.bat
  ENV RUSTDOC=rustdoc
  ENV RUSTUP_HOME=C:\Users\Administrator\.rustup
  ENV RUSTUP_TOOLCHAIN=nightly-x86_64-pc-windows-msvc
  ENV RUST_ANDROID_GRADLE_CC=D:\AndroidStudioSdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows\bin\armv7a-linux-androideabi23-clang.cmd
  ENV RUST_ANDROID_GRADLE_CC_LINK_ARG=-Wl,-soname,libsslocal.so
  ENV RUST_ANDROID_GRADLE_LINKER_WRAPPER_PY=E:\AndroidStudioProjects\shadowsocks-android-master\core/src/main/rust/shadowsocks-rust/../linker-wrapper.py
  ENV RUST_ANDROID_GRADLE_PYTHON_COMMAND=python
  ENV RUST_ANDROID_GRADLE_TARGET=target/armv7-linux-androideabi/debug/libsslocal.so
  ENV RUST_RECURSION_COUNT=1
  ENV SBT_HOME=C:\Program Files (x86)\sbt\
  ENV SESSIONNAME=Console
  ENV SYSTEMDRIVE=C:
  ENV SYSTEMROOT=C:\WINDOWS
  ENV TARGET=armv7-linux-androideabi
  ENV TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
  ENV TMP=C:\Users\ADMINI~1\AppData\Local\Temp
  ENV USERDOMAIN=QQWW
  ENV USERDOMAIN_ROAMINGPROFILE=QQWW
  ENV USERNAME=Administrator
  ENV USERPROFILE=C:\Users\Administrator
  ENV VISUALSVN_SERVER=d:\Program Files\VisualSVN Server\
  ENV WINDIR=C:\WINDOWS
  ENV WINDOWS_TRACING_FLAGS=3
  ENV WINDOWS_TRACING_LOGFILE=C:\BVTBin\Tests\installpackage\csilogfile.log
  running "D:\\AndroidStudioSdk\\ndk\\21.3.6528147\\toolchains\\llvm\\prebuilt\\windows\\bin\\armv7a-linux-androideabi23-clang.cmd" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-oE:\\AndroidStudioProjects\\shadowsocks-android-master\\core\\src\\main\\rust\\shadowsocks-rust\\target\\armv7-linux-androideabi\\debug\\build\\ring-265355c1a8d37598\\out\\aesv8-armx-linux32.o" "C:\\Users\\Administrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.15\\pregenerated\\aesv8-armx-linux32.S"
  thread 'main' panicked at 'failed to execute ["D:\\AndroidStudioSdk\\ndk\\21.3.6528147\\toolchains\\llvm\\prebuilt\\windows\\bin\\armv7a-linux-androideabi23-clang.cmd" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-oE:\\AndroidStudioProjects\\shadowsocks-android-master\\core\\src\\main\\rust\\shadowsocks-rust\\target\\armv7-linux-androideabi\\debug\\build\\ring-265355c1a8d37598\\out\\aesv8-armx-linux32.o" "C:\\Users\\Administrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ring-0.16.15\\pregenerated\\aesv8-armx-linux32.S"]: 系统找不到指定的文件。 (os error 2)', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.15\build.rs:661:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
build failed, waiting for other jobs to finish...

error: could not find native static library `sodium`, perhaps an -L flag is missing?

error: aborting due to previous error

could not find native static library `sodium`, perhaps an -L flag is missing?

aborting due to previous error

error: build failed
build failed


> Task :core:cargoBuildArm FAILED

Execution failed for task ':core:cargoBuildArm'.
> Process 'command 'cargo'' finished with non-zero exit value 101

**Comment by hw1020** [comment]
Ubuntu上尝试时报的是类似的错，同时网络都可以访问Google

> Task :core:cargoBuildArm
   Compiling libsodium-sys v0.2.6
   Compiling openssl-sys v0.9.58
   Compiling num-integer v0.1.43
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling crypto-mac v0.8.0
   Compiling crypto-mac v0.9.1
   Compiling regex v1.4.1
   Compiling rand_chacha v0.2.2
   Compiling clap v2.33.3
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/home/ubuntu-wch/StudioProjects/shadowsocks-android/core/src/main/rust/shadowsocks-rust/target/debug/build/openssl-sys-19b8013a11e50e4f/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_armv7-linux-androideabi = Some("/home/ubuntu-wch/Android/SDK/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi23-clang")
  CFLAGS_armv7-linux-androideabi = None
  CFLAGS_armv7_linux_androideabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running "perl" "./Configure" "--prefix=/home/ubuntu-wch/StudioProjects/shadowsocks-android/core/src/main/rust/shadowsocks-rust/target/armv7-linux-androideabi/debug/build/openssl-sys-b88f13b6a7324991/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "no-shared" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer"
  Configuring OpenSSL version 1.1.1h (0x1010108fL) for linux-armv4
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ubuntu-wch/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.12.0+1.1.1h/src/lib.rs:411:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.9.58`

Caused by:

build failed, waiting for other jobs to finish...

error: build failed

> Task :core:cargoBuildArm FAILED

build failed

Execution failed for task ':core:cargoBuildArm'.
> Process 'command 'cargo'' finished with non-zero exit value 101

**Comment by cai137800735** [comment]
I have the same problem. Have you found a solution?

**Comment by hw1020** [comment]
https://discourse.shadowsocks.org/c/implementations/shadowsocks-android/6

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
