### ISSUE TITLE
Android4.4，已经获取root权限，右上角关闭按钮一直无法点击怎么办

### ISSUE THREAD

**Issue by vicliu1990** [shadowsocks/shadowsocks-android#262]
右上角关闭按钮一直无法点击怎么办
IUNI U2，32GB手机
Android4.4系统
已经获取root权限

**Comment by vicliu1990** [comment]
安装的是shadowsocks-nightly-2.6.5.apk

**Comment by larryzhao83** [comment]
我也遇到了你同样的问题，应该是 nat service 和 shadowsocks 同时调用Console.runRootCommand 引起的。
