### ISSUE TITLE
AES-192-GCM not working (was working on release 5.0.6)

### ISSUE THREAD

**Issue by lm902** [shadowsocks/shadowsocks-android#2620]
Please read contributing guidelines. Thanks.

**Describe the bug**
AES-192-GCM won't work.

**To Reproduce**
1. Add a configuration with AES-192-GCM encryption
2. Start service
3. Crash immediately

**Expected behavior**
Start service correctly

**Screenshots**
![Screenshot_2020-12-10-19-51-43-291_com github shadowsocks](https://user-images.githubusercontent.com/4379070/101824261-ed5e1100-3b66-11eb-92a5-96e765e0e4bf.jpg)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: MIUI 12 20.12.2, Android 11
 - Device: Mi 10 Pro
 - Version: 5.1.6, 5.1.5, and 5.1.4
 - Last version that did not exhibit the issue: 5.0.6

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: AES-192-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS over UDP
* Plugin configuration (if applicable): Not applicable
* [x] Auto Connect
* [ ] TCP Fast Open

**Additional context**
Not applicable

**Comment by madeye** [comment]
Looks we forgot to remove that cipher.

From 5.1.x, aes-192-gcm is not supported. It's expected.

**Comment by madeye** [comment]
Fixed via f73d308b
