### ISSUE TITLE
Cannot use two plugins at the same time

### ISSUE THREAD

**Issue by PotZedd** [shadowsocks/shadowsocks-android#2624]
**Describe the question**
Cannot use two plugins at the same time.

**To Reproduce**
1. Go to 'shadowsocks-android'
2. Click on 'config setting'
3. Scroll down to 'plugin'
4. Cannot use two plugins

**Expected behavior**
Can use v2ray-plugin plugin and kcptun plugin at the same time.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: "MIUI 11.0.3.0(QDGCNXM)"，"Android 10"
 - Device: Xiaomi MIX2S
 - Version: v5.1.6"
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
  * [ ] IPv6 route
  * [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
  * [ ] DNS over UDP
* Plugin configuration (if applicable):
  * [ ] Auto Connect
  * [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Only one plugin can be used at the same time.  Only v2ray-plugin can be connected but there is no kcptun speed-up effect.  Only use kcptun only has weak upload traffic, and cannot access the Internet.

**Comment by madeye** [comment]
It's expected. BTW, it makes no sense to use these two plugins together.
