### ISSUE TITLE
exclude HK IP used by weibo

### ISSUE THREAD

**Issue by crackevil** [shadowsocks/shadowsocks-android#263]
weibo app's using weibo.cn as its API source, which resolved to 114.134.80.163 for overseas. pls exclude such IPs in the list.thx.

**Comment by myliyifei** [comment]
I  remember to use  tcp dns query which is bypass some cdn sites.

but   udp  mode  will  redirect  global  dns  request to  remote
2015年3月14日 下午9:10于 "crackevil" <notifications@github.com>写道：
