### ISSUE TITLE
There is no way to make WhatsApp voice calls on version 5.1.7...

### ISSUE THREAD

**Issue by ayton** [shadowsocks/shadowsocks-android#2639]
There is no way to make WhatsApp voice calls on version 5.1.7, but when using version "Shadowsocks client without AD" created by TrueNight, based on version 4.8.4 from Google Play, there are no such problems.

Shalowsocks is configured with v2ray with UDP support: https://github.com/Acris/docker-shadowsocks-libev
I would be glad of any information to solve this ...

**Comment by madeye** [comment]
Create a profile without plugin as the UDP fallback upstream.

**Comment by ayton** [comment]
I do not quite understand, do you suggest setting up a server without using v2ray?
Because if I just create a profile in the application without the v2ray plugin, I just don't have a connection to the server.

**Comment by ayton** [comment]
I also noticed that in version 5.0.6 everything works fine, there are no problems with voice calls ...

**Comment by madeye** [comment]
> I do not quite understand, do you suggest setting up a server without using v2ray?

Yes, and use that server as the UDP fallback profile of your v2ray enabled profile.
