### ISSUE TITLE
`5.1.8` cannot start a configuration file that uses `XCHACHA20_POLY1305`

### ISSUE THREAD

**Issue by Stzx** [shadowsocks/shadowsocks-android#2642]
**Describe the bug**

- Currently `shadowsocks-crypto` does not implement `XCHACHA20_POLY1305`, but user profiles may use `XCHACHA20_POLY1305`. this will cause `sslocal` to not start.

**To Reproduce**

1. _Select the profile that uses `XCHACHA20_POLY1305` and start it._

**Expected behavior**

- Normal start.
- Let's disable the start of this profile.

~~**Screenshots**~~

**Smartphone (please complete the following information):**

- I guess maybe all devices, since this is related to upstream.

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: `XCHACHA20_POLY1305`
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* ~~If you're not using VPN mode, please supply more details here:~~

~~**Additional context**~~

**Comment by dev4u** [comment]
使用chacha20-ietf-poly1305

**Comment by jerry-ch-issue** [comment]
Same problem.same encrypt method.

**Comment by zh-Spike** [comment]
same with the exit code134

**Comment by madeye** [comment]
This cipher is not part of our standard AEAD ciphers.

It will be removed in the next release.

**Comment by vp594** [comment]
Hi @madeye and thanks for your great work.

Can you explain more about your `standard AEAD ciphers` and why `XCHACHA20_POLY1305` is not included in that?

**Comment by madeye** [comment]
> Can you explain more about your `standard AEAD ciphers` and why `XCHACHA20_POLY1305` is not included in that?

Here are the AEAD ciphers officially supported by shadowsocks:
 
https://shadowsocks.org/en/wiki/AEAD-Ciphers.html
