### ISSUE TITLE
5.1.8用XCHACHA20-IETF-POLY1305不能启动

### ISSUE THREAD

**Issue by maskedeken** [shadowsocks/shadowsocks-android#2644]
提示exit code 134

**Comment by qwerttvv** [comment]
换翻墙软件可解决ss的一切问题

**Comment by madeye** [comment]
> 换翻墙软件可解决ss的一切问题

There're many alternatives to shadowsocks on Android. You'd like to try them out:

1. https://play.google.com/store/apps/details?id=com.v2ray.ang
2. https://play.google.com/store/apps/details?id=com.github.kr328.clash
3. https://play.google.com/store/apps/details?id=io.github.trojan_gfw.igniter
4. https://play.google.com/store/apps/details?id=org.outline.android.client

**Comment by qwerttvv** [comment]
手机和电脑都换trojan了，路由器上现在看起来性能不如ss+cloak，元旦这几天再折腾折腾看看

另外XCHACHA20-IETF-POLY1305过时了还是有别的问题啊？

https://doc.libsodium.org/secret-key_cryptography/aead#tl-dr-which-one-should-i-use

**Comment by wupeng1211** [comment]
XCHACHA20-IETF-POLY1305没有过时啊！

**Comment by qwerttvv** [comment]
> XCHACHA20-IETF-POLY1305没有过时啊！

我也不知道为什么去掉了，反而那些真正被认为已经跟不上时代的还留着

**Comment by zonyitoo** [comment]
1. `XCHACHA20-IETF-POLY1305` is not a part of the standard: https://shadowsocks.org/en/wiki/AEAD-Ciphers.html
2. `XCHACHA20-IETF-POLY1305` is not an IANA registered cipher
3. You are right, we are going to deprecate all stream ciphers.

**Comment by MedievalSteel** [comment]
废弃 xchacha20-ietf-poly1305 简直莫名其妙

**Comment by prowong** [comment]
竟然保留RC4-MD5却废弃 xchacha20-ietf-poly1305，真是神奇，然而Windows版本依然保留着xchacha20-ietf-poly1305。
