### ISSUE TITLE
v5.1.9不能用了【后台服务启动失败】，v5.1.8是好的

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-android#2645]
![1816378828](https://user-images.githubusercontent.com/56712217/103393312-ff771200-4b5c-11eb-9f22-747a82f2ee66.jpg)

5.1.8是可以用的

任何设置没有更改，直接升级后不可用

我用了一个sip003插件，系统安卓10

**Comment by dev4u** [comment]
logcat一下

**Comment by qwerttvv** [comment]
抓不了，换回去5.1.8了

总之5.0.6之后似乎bug不断

**Comment by madeye** [comment]
Please follow the template and provide all the details.

I cannot reproduce your issue locally.

**Comment by madeye** [comment]
Also double check your ck-client is updated to the latest: https://github.com/cbeuw/Cloak-android/releases

**Comment by qwerttvv** [comment]
cloak是最新版的，包括服务端和客户端

**Comment by qwerttvv** [comment]
算了
