### ISSUE TITLE
Not able to access intranet resource on v5.1.9

### ISSUE THREAD

**Issue by xygwfxu** [shadowsocks/shadowsocks-android#2646]
In profile option to 'bypass cn', all other options are default ones. Note, server(two network card) has an intranet ip like 10.20.30.x.

Now in client try to access the server's intranet resource. it cannot load it in chrome.

ps. 
1.the issue is also in window client version. I have to remove intranet ip from system proxy profile to make it works. but don't know how to set this for Android.
2. it works on v5.0.6.

**Comment by madeye** [comment]
Have you tried 5.1.9?

**Comment by xygwfxu** [comment]
let me. check.

**Comment by madeye** [comment]
I cannot reproduce this locally. Can you help verify those two things:

1. What's the specific IP range you are using for your intranet service?
2. Are you accessing thoses service using IPs and hostnames?

**Comment by madeye** [comment]
BTW, here is my local test setup:

1. Setup a HTTP service on the shadowsocks server, bound to a LAN IPs, e.g. 10.127.0.1:2051 or 172.31.0.1:2051.
2. Visit this HTTP server through shadowsocks.

All my local tests can pass.

To help reproduce your issue, please provide as many details as possible.

**Comment by xygwfxu** [comment]
I am so sorry, I forgot to upgrade server with gost go shadowsocks2 in that pc.

After replaced, everything is working now perfectly!!

Thanks all your efforts and appreciated very much.
