### ISSUE TITLE
"Unable to resolve host cp.cloudfire.com"

### ISSUE THREAD

**Issue by the4realpsych** [shadowsocks/shadowsocks-android#2647]
![Screenshot_20210102-111455_Shadowsocks](https://user-images.githubusercontent.com/76070767/103492845-2f940e80-4e04-11eb-92d6-8c2d5c5188ef.jpg)
On my phone, it gives me this error every time I try to connect; I have upload speeds, but I have 0mbs for downloads.

I know I have my connection settings in the app right; but, it still gives me the error.

Does anyone know how to fix this? Thank you. It's for my job.

**Comment by dev4u** [comment]
#2606
参考这个自查一下。如需更多帮助，请隐去敏感信息后，把你使用的配置发上来。
