### ISSUE TITLE
微信视频无法连接

### ISSUE THREAD

**Issue by lbp0200** [shadowsocks/shadowsocks-android#265]
已选择跳过中国大陆地址

**Comment by madeye** [comment]
分应用代理中排除微信。

**Comment by myliyifei** [comment]
为什么你的环境  微信视频解析到国外IP 。udp选择了全局 ?
2015年3月16日 下午12:35于 "Boping Liu" <notifications@github.com>写道：

**Comment by lbp0200** [comment]
按照您的方案已经解决

**Comment by wanglongbiao** [comment]
为啥会这样？
当选择为GFWList 的时候，钉钉有时候也不好用

**Comment by wanglongbiao** [comment]
哪位大佬能点拨点拨？和UDP有关系不？
