### ISSUE TITLE
Keep configuration while uninstall the app

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#2652]
Please read contributing guidelines. Thanks.

**Is your feature request related to a problem? Please describe.**
Sometimes an updated ss-android cannot work with previous configuration.
In this condition, we may need to down-grade the app to the previous version.

**Describe the solution you'd like**
Keep the configuration when uninstall the app, and then the configuration can be used by a re-installed older version app.
Just like mentioned here: https://www.ithome.com/0/455/560.htm

Thanks a lot.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Mygod** [comment]
Have you even checked

**Comment by madeye** [comment]
You cannot downgrade the app while keeping the configuration. It's expected.

**Comment by madeye** [comment]
If you just uninstall the app and reinstall the  same version or above, it's already supported.
