### ISSUE TITLE
建议重新支持xchacha20-ietf-poly1305

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-android#2653]
新版本不支持xchacha20-ietf-poly1305了.
个人认为xchacha20-ietf-poly1305并不过时,当然,以xchacha20-ietf-poly1305不是标准AHEAD大家也都同意
但是很多人都还在用,建议恢复支持

**Comment by loyess** [comment]
Android 一套加密方式，Windows 一套加密方式，rust 一套加密方式，go 一套加密方式，libev 一套加密方式。

**Comment by madeye** [comment]
Here are the standard ciphers defined in the spec: http://shadowsocks.org/en/wiki/AEAD-Ciphers.html
