### ISSUE TITLE
Dynamically update GFW list

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#2656]
Please read contributing guidelines. Thanks.

**Describe the bug**
The builtin gfw list is not updated. Many rules are different from the latest GFW list.
For example, ||inoreader.com has been added in the official gfw list,
but only blog.inoreader.com is written in the builtin gfw list.

**To Reproduce**
1. Go to '...' Configure
2. Click on '....' edit pen
3. Scroll down to '....' Set route to GFW list
4. Some websites are not accessible, for example www.inoreader.com.

**Expected behavior**

Update gfw list dynamically within the app or update the builtin gfw list when update the app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by dev4u** [comment]
你可以把你的版本PR给项目组，或者使用自定义规则，指定个你喜欢的规则URL地址。
这都是可以试试的。

**Comment by GitatHub** [comment]
> 你可以把你的版本PR给项目组，或者使用自定义规则，指定个你喜欢的规则URL地址。
> 这都是可以试试的。
GFW list 有官方更新链接，项目组也是从那边得到的，只是很久没更新了。如果能在应用内动态更新，或者至少在每次更新app的时候更新GFW list就好了。

**Comment by dev4u** [comment]
> > 你可以把你的版本PR给项目组，或者使用自定义规则，指定个你喜欢的规则URL地址。
> > 这都是可以试试的。
> 
> GFW list 有官方更新链接，项目组也是从那边得到的，只是很久没更新了。如果能在应用内动态更新，或者至少在每次更新app的时候更新GFW list就好了。

在应用里的自动更新，这个已经实现。
每次启动，app都会从shadowsocks.org上更新本地的规则数据。
你想用上gfwlist官网上的版本，要么耐心等待有人PR，要么自己PR一份过去。印象中，项目组很少见有主动做版本同步的，因为精力有限啊！

**Comment by madeye** [comment]
It's already supported.

Try some third-party rules like https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl

**Comment by GitatHub** [comment]
This is what the app showed after I chose the customized rules in one configure.
The service failed to start.
![345](https://user-images.githubusercontent.com/8266771/104142983-bba3c880-53f8-11eb-91b8-e80cfafe332b.jpg)
![123](https://user-images.githubusercontent.com/8266771/104142987-be9eb900-53f8-11eb-940a-3ccb0411e0f7.jpg)


> It's already supported.
> 
> Try some third-party rules like https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/fullgfwlist.acl
