### ISSUE TITLE
能否新增使用公共ss帐号的功能？

### ISSUE THREAD

**Issue by lbp0200** [shadowsocks/shadowsocks-android#266]
我买的vps每月流量用不完，但是发布出来一怕攻击、二怕被bt下载乱用，所以只想分享给android手机用户使用，方便别人使用play和gmail。
公共账号不显示ip、端口和密码。

**Comment by madeye** [comment]
Just share the QR code and make sure only share to your friends.

**Comment by lbp0200** [comment]
ok
