### ISSUE TITLE
fake UDP association broken since 5.1.9

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/shadowsocks-android#2665]
It's exactly what was discussed in https://github.com/shadowsocks/shadowsocks-android/issues/2571, which was fixed in 5.1.7 by https://github.com/shadowsocks/shadowsocks-android/commit/84ac0c449c5dab29498def990c54d231a4ac31b4.

After upgrading to 5.1.9, the same problem occurs again. It could possibly be broken in 5.1.8, but there is no way to know since proxy mode had that [critical bug](https://github.com/shadowsocks/shadowsocks-android/issues/2638) in 5.1.8. 

Update: I tried VPN mode in 5.1.8, and tested the connectivity, it was most likely broken already in 5.1.8. I have tried every version afterwards, the result is the same.

**Comment by madeye** [comment]
@zonyitoo It should be a regression of shadowsocks-rust.

With this patch, I can get `udp_bind_addr` working in tcp-only mode:

```diff
diff --git a/crates/shadowsocks-service/src/local/socks/server/mod.rs b/crates/shadowsocks-service/src/local/socks/server/mod.rs
index d3308fd..da5d676 100644
--- a/crates/shadowsocks-service/src/local/socks/server/mod.rs
+++ b/crates/shadowsocks-service/src/local/socks/server/mod.rs
@@ -113,14 +113,10 @@ impl Socks {

         info!("shadowsocks socks TCP listening on {}", listener.local_addr()?);

-        // If UDP is enabled, SOCK5 UDP_ASSOCIATE command will let client to send requests to this address
-        let udp_bind_addr = if self.mode.enable_udp() {
-            let udp_bind_addr = self.udp_bind_addr.as_ref().unwrap_or(client_config);
-            let udp_bind_addr = Arc::new(udp_bind_addr.clone());
-            Some(udp_bind_addr)
-        } else {
-            None
-        };
+        // If UDP bind addr is specified, SOCK5 UDP_ASSOCIATE command
+        // will let client to send requests to this address
+        let udp_bind_addr = self.udp_bind_addr.as_ref().unwrap_or(client_config);
+        let udp_bind_addr = Some(Arc::new(udp_bind_addr.clone()));

         loop {
             let (stream, peer_addr) = match listener.accept().await {
```

**Comment by zonyitoo** [comment]
Sincerely sorry for the mess.
