### ISSUE TITLE
Service is down intermittently

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2667]
**Describe the bug**

Sometimes the Internet fails entirely when Shadowsocks keeps running for a while. This is a new bug introduced around v5.1.7 until latest master.

**To Reproduce**
1. Start Shadowsocks
2. Wait until your Internet is dead
3. Restart service and verify that it is back working again

**Expected behavior**
Shadowsocks should work 24/7.

**Relevant logcat**
```
ERROR dns udp 127.0.0.1:38945 query message parse error: dns class value unknown: 2287
```

This message is repeated 6 times over 4 seconds, around when the DNS goes down. Not sure if it is related though.

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 11
 - Device: Pixel 3a XL
 - Version: Reproducible from v5.2.1 (9a1c677) to 1394ab3
 - Last version that did not exhibit the issue: around v5.1.7

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: n/a
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1.1.1.1

**Comment by madeye** [comment]
It looks related to

https://github.com/shadowsocks/shadowsocks-rust/blob/d41404cbf9241ae695f97d9b0a86bee479d9253f/crates/shadowsocks-service/src/local/dns/server.rs#L230

But I guess it's not the root cause.

Two questions:

1. Would DNS go back online after 6 seconds?
2. When the DNS is down, can we still visit https://1.1.1.1?

**Comment by Mygod** [comment]
Looping @zonyitoo in on this.

1. No.
2. I haven't tried it yet but will update when this eventually happen again.

**Comment by zonyitoo** [comment]
Couldn't reproduce because I don't possess an Android device. :(

Anything I can help? Maybe start `sslocal` with `-vvv` and see what it was doing at that time.

**Comment by madeye** [comment]
@zonyitoo You can try this on a router with local DNS feature enabled. I guess it's something related to socket leaks.

**Comment by madeye** [comment]
@Mygod please try change `256` to `64` here:

https://github.com/shadowsocks/shadowsocks-android/blob/1394ab32813d7c20071e95749b2ba775c7890c6e/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L85

**Comment by zonyitoo** [comment]
I tested with

```bash
while true; do dig @127.0.0.1 -p 5300 google.com; done
```

and runs `sslocal` with `--protocol dns --udp-max-associations 64` for half an hour. Everything seems to works fine.

**Comment by zonyitoo** [comment]
BTW, `--udp-max-associations` doesn't have any effects in dns relay.

**Comment by madeye** [comment]
After testing for hours, I still cannot reproduce the problem locally.

There's no socket leaks observed, even with intensive VoIP usage. I'm watching the open FDs through ADB:

```
adb exec-out run-as com.github.shadowsocks ls -l /proc/$libsslocal.pid/fd | wc -l
```

**Comment by Mygod** [comment]
For more context, I have been using it with [VPN hotspot](https://github.com/Mygod/VPNHotspot), which forwards other DNS packets via NAT. I will do more test later.

**Comment by Mygod** [comment]
Just got a different error: `ERROR received invalid UDP associate packet: b"G\x93\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x03ssl\x07gstatic\x03com\x00\x00\x01\x00\x01"`

**Comment by zonyitoo** [comment]
UDP packet doesn't have a SOCKS5 header: https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs#L110-L118

**Comment by Mygod** [comment]
Ok I ran libsslocal with `-v` (because `-vvv` logs every single UDP packets and makes the logger OOM) and sent the logs to @madeye. Some preliminary findings:

1. When it is not working, existing TCP connections still work but initiating new TCP connection does not.
2. Also seeing `[shadowsocks_service::local::socks::server::socks5::tcprelay] CONNECT xxx` and `[shadowsocks_service::local::dns::server] DNS lookup xxx` in log, despite nothing working.
3. Number of fds is well under 1000, where as the limit is 32768.

**Comment by madeye** [comment]
It looks we need to check the VPNService `protect()` routine.

Seems `sslocal` is still receiving new connections, but keep failing to connect the remote shadowsocks server.

**Comment by Mygod** [comment]
There is no significant network related logic change in Kotlin since my last update: https://github.com/shadowsocks/shadowsocks-android/compare/v5.1.7...1394ab3

I am pretty sure that I was on v5.1.7 before, and it was able to run completely fine for a long period of time.

**Comment by madeye** [comment]
Yes, I mean the protect logic in `sslocal`.

**Comment by zonyitoo** [comment]
1. Did you see any logs like `DNS resolved {}:{} with customized` ? If no, then the problem is in DNS resolver.
2. `protect()` opens a new connection everytime when creating new sockets. How can it be broken?

**Comment by madeye** [comment]
Just to confirm, you cannot visit https://1.1.1.1 after the `sslocal` is down?

**Comment by Mygod** [comment]
I have not tried 1.1.1.1 specifically but ssh into an IP directly does not work.

**Comment by Mygod** [comment]
> After testing for hours, I still cannot reproduce the problem locally.

Regarding this, it only happens randomly. Perhaps try to run it more?

**Comment by madeye** [comment]
@zonyitoo I'm reviewing `protect()` routine here: https://github.com/shadowsocks/shadowsocks-rust/blob/3e771f717e5239c141d5cea4d878ef468fddf35b/crates/shadowsocks/src/relay/sys/unix/mod.rs#L44

Do we have logic to handle timeout like this? https://github.com/shadowsocks/shadowsocks-libev/blob/cfe0c2cba08f25e5a70294b368490f66032ac882/src/android.c#L63

**Comment by madeye** [comment]
@Mygod I usually switch profiles from time to time, maybe that's why I didn't observe connection down before.

Also, unlike tethering, workload from one phone is typically lower, making me hard to reproduce the issue.

**Comment by madeye** [comment]
One more question for @Mygod, do you observe busy CPU usage when the connection down?

**Comment by madeye** [comment]
> Did you see any logs like DNS resolved {}:{} with customized ?

There are only CONNECT related items in @Mygod's logs, no DNS logs, as he is running in `-v` verbose mode.

**Comment by zonyitoo** [comment]
> @zonyitoo I'm reviewing `protect()` routine here: https://github.com/shadowsocks/shadowsocks-rust/blob/3e771f717e5239c141d5cea4d878ef468fddf35b/crates/shadowsocks/src/relay/sys/unix/mod.rs#L44
> 
> Do we have logic to handle timeout like this? https://github.com/shadowsocks/shadowsocks-libev/blob/cfe0c2cba08f25e5a70294b368490f66032ac882/src/android.c#L63

Async I/O doesn't have timeouts. We have to set timer manually.

**Comment by Mygod** [comment]
Ok I managed to reproduce it again and haven't restarted it yet. Let me know what you want to see asap. :)

> @Mygod I usually switch profiles from time to time, maybe that's why I didn't observe connection down before.
> 
> Also, unlike tethering, workload from one phone is typically lower, making me harder to reproduce the issue.

Yes. It is best to set up a profile that you can consistently connect to, in order to reproduce this bug.

> One more question for @Mygod, do you observe busy CPU usage when the connection down?

Yes.

```
   PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS
  2036 u0_a201      20   0  14G 214M  95M S 14.6   5.9 343:36.61 com.android.systemui
 21267 u0_a248      20   0  10G  63M 5.0M S 12.3   1.7 147:51.48 libsslocal.so -v --stat-path /data/user_de/0/com.github.shadowsocks/no_backup/stat_main -c /data/user/0/com.github.shadowsocks/no_backup/shadowso+
  1597 system       18  -2  16G 348M 258M S 11.0   9.6 640:55.15 system_server
 27107 u0_a248      20   0  14G  51M  21M S  9.3   1.4  16:40.26 com.github.shadowsocks:bg
  7605 u0_a248      10 -10  13G 207M 147M S  7.0   5.7   0:24.07 com.github.shadowsocks
```

> > Did you see any logs like DNS resolved {}:{} with customized ?
> 
> There are only CONNECT related items in @Mygod's logs, no DNS logs, as he is running in `-v` verbose mode.

I also get logs like `[shadowsocks_service::local::dns::server] DNS lookup A **`.

**Comment by madeye** [comment]
@Mygod Is the traffic stat still updating?

**Comment by Mygod** [comment]
Yes.

**Comment by madeye** [comment]
Okay, IMO, it'd be related to `protect()`, as libsslocal still receives new connection. Also the existing TCP connections are not done.

Maybe we can try @zonyitoo 's new commits.

**Comment by zonyitoo** [comment]
Is 3 seconds too long? Hmm..

**Comment by madeye** [comment]
Let's use a long timeout for now. 3 seconds look good to me.

**Comment by Mygod** [comment]
Hmm... remind me why do we need timeout there?

**Comment by zonyitoo** [comment]
@madeye I just realized that UDP sockets' `protect()` is forgotten.

**Comment by madeye** [comment]
Hmm, but I didn't see UDP relay issues before...

**Comment by madeye** [comment]
I guess you mean "bypassed" UDP sockets?

**Comment by zonyitoo** [comment]
Nope. I mean I just added timeouts for UDP sockets' `protect()` call.

**Comment by madeye** [comment]
After 72 hours testing, I still cannot reproduce this issue locally...

**Comment by Mygod** [comment]
[This commit](https://github.com/shadowsocks/shadowsocks-rust/commit/be6049f35bf32fa6e1e7df3e03a5b0bd9946fe9a) does not compile.

```
> Task :core:cargoBuildArm
   Compiling shadowsocks v1.9.0
error[E0433]: failed to resolve: use of undeclared crate or module `time`
   --> crates/shadowsocks/src/relay/sys/unix/mod.rs:177:19
    |
177 |             match time::timeout(Duration::from_secs(3), protect(path, socket.as_raw_fd())).await {
    |                   ^^^^ use of undeclared crate or module `time`

error[E0433]: failed to resolve: use of undeclared type `Duration`
   --> crates/shadowsocks/src/relay/sys/unix/mod.rs:177:33
    |
177 |             match time::timeout(Duration::from_secs(3), protect(path, socket.as_raw_fd())).await {
    |                                 ^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
2   | use core::time::Duration;
    |
2   | use crate::relay::udprelay::Duration;
    |
2   | use std::time::Duration;
    |
2   | use tokio::time::Duration;
    |

warning: unused imports: `EventKind`, `Event`, `RecommendedWatcher`, `RecursiveMode`, `Watcher`
  --> crates/shadowsocks/src/dns_resolver/resolver.rs:19:14
   |
19 | use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Result as NotifyResult, Watcher};
   |              ^^^^^  ^^^^^^^^^  ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^                          ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `error`
 --> crates/shadowsocks/src/dns_resolver/trust_dns_resolver.rs:4:11
  |
4 | use log::{error, trace};
  |           ^^^^^

error[E0698]: type inside `async fn` body must be known in this context
   --> crates/shadowsocks/src/relay/sys/unix/mod.rs:177:53
    |
177 |             match time::timeout(Duration::from_secs(3), protect(path, socket.as_raw_fd())).await {
    |                                                     ^ cannot infer type for type `{integer}`
    |
note: the type is part of the `async fn` body because of this `await`
   --> crates/shadowsocks/src/relay/sys/unix/mod.rs:177:19
    |
177 |             match time::timeout(Duration::from_secs(3), protect(path, socket.as_raw_fd())).await {
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

unused imports: `EventKind`, `Event`, `RecommendedWatcher`, `RecursiveMode`, `Watcher`

unused import: `error`

error: aborting due to 3 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0433, E0698.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `shadowsocks`

To learn more, run the command again with --verbose.

> Task :core:cargoBuildArm FAILED
aborting due to 3 previous errors; 2 warnings emitted

could not compile `shadowsocks`


Execution failed for task ':core:cargoBuildArm'.
> Process 'command 'cargo'' finished with non-zero exit value 101
```

**Comment by zonyitoo** [comment]
@Mygod You must have compiled the old commit. I have just force pushed a new commit this morning.

**Comment by Mygod** [comment]
From my testing, it seems the issue has improved somewhat. I will do some more extensive testing.

**Comment by Mygod** [comment]
P.S. We should fix the warnings as well. :)

**Comment by zonyitoo** [comment]
What warnings exactly? I couldn't build it locally.

**Comment by madeye** [comment]
```
warning: unused import: `error`
 --> crates/shadowsocks/src/dns_resolver/trust_dns_resolver.rs:4:11
  |
4 | use log::{error, trace};
  |           ^^^^^
```

@zonyitoo This one I think.

**Comment by zonyitoo** [comment]
![image](https://user-images.githubusercontent.com/1067951/106541988-f1425a00-653d-11eb-94b3-ea232b8b6693.png)

**Comment by madeye** [comment]
Here're all the warnings:

```
warning: unused imports: `EventKind`, `Event`, `RecommendedWatcher`, `RecursiveMode`, `Watcher`
  --> crates/shadowsocks/src/dns_resolver/resolver.rs:19:14
   |
19 | use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Result as NotifyResult, Watcher};
   |              ^^^^^  ^^^^^^^^^  ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^                          ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `resolver`
   --> crates/shadowsocks/src/dns_resolver/resolver.rs:167:38
    |
167 | async fn trust_dns_notify_update_dns(resolver: Arc<TrustDnsSystemResolver>) -> NotifyResult<()> {
    |                                      ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_resolver`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: field is never read: `ipv6_first`
  --> crates/shadowsocks/src/dns_resolver/resolver.rs:34:5
   |
34 |     ipv6_first: bool,
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

**Comment by madeye** [comment]
Actually it's possible to build Android target without Android environment:

1. Download NDK here: https://developer.android.com/ndk/downloads
2. Set the PATH like this `export PATH=$PATH:/path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin`
3. Build the Android target `cargo build  --target aarch64-linux-android`

**Comment by dev4u** [comment]
> What warnings exactly? I couldn't build it locally.

```log
warning: field is never read: `nodelay`
  --> crates/shadowsocks-service/src/manager/server.rs:60:5
   |
60 |     nodelay: bool,
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```
这里还有一个

**Comment by Mygod** [comment]
> After 72 hours testing, I still cannot reproduce this issue locally...

It seems the issue is gone after the timeout is added. So why exactly does adding a timeout fix this? 🤔

**Comment by madeye** [comment]
No idea, it looks the timeout is there from the very beginning...

**Comment by zonyitoo** [comment]
If the timeout actually works, then there must be error logs about connection errors.

**Comment by Mygod** [comment]
> If the timeout actually works, then there must be error logs about connection errors.

What kind of errors should I be looking for?

After a lot more testing, I think I am now seeing a different error:

```
D tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
D tun2socks: ERROR(SocksUdpGwClient): The current UDP connection is broken, recreating a new one
```

When this happens, it seems all UDP connections are broken, e.g. YouTube comments, using reddit sync (presumably they are using QUIC?). Normal TCP connections and DNS still work.

**Comment by zonyitoo** [comment]
Hmm, this was reported by `tun2sock`.

**Comment by madeye** [comment]
@Mygod It looks `tun2socks` has too many UDP packets in the queue, which prevents the UDP connection receiving more packets.

Currently, the max number of UDP packets for one UDP connection is `8`: https://github.com/shadowsocks/badvpn/blob/06f766354abe34c73ac34f137f39c48ff43f0b86/tun2socks/SocksUdpGwClient.c#L39

However, even we see the `out of UDP buffer` error, tun2socks should not drop all the UDP connections.

**Comment by madeye** [comment]
BTW, if the UDP socket `protect()` fails, we would see similar behaviors, as `sslocal` keep sending packets to itself. In that case, the UDP connection in `tun2socks` would be easily out of buffer.

**Comment by madeye** [comment]
I still cannot reproduce this issue locally, even after testing the same profile for one week without the `protect` timeout fixes.

Maybe it's also related to Android system or Linux kernel? I'm testing on a OnePlus 8 with Android 11 and Linux Kernel 4.19.

**Comment by madeye** [comment]
@Mygod Can you try this branch? https://github.com/shadowsocks/shadowsocks-android/tree/issue-2667

**Comment by Mygod** [comment]
Anything I should be looking out for to debug this? 🤔

**Comment by madeye** [comment]
Nope, just want to see if there's anything wrong with UDP connection handling in tun2socks.

**Comment by Mygod** [comment]
I am now getting the following error when trying to start service: `E/libsslocal: thread 'main' panicked at 'Non-unique argument name: OUTBOUND_BIND_INTERFACE is already in use', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:181:9`, presumably introduced in https://github.com/shadowsocks/shadowsocks-rust/commit/1bb86e47b04cc96b056619b5f5af84cd0a3480c9.

**Comment by zonyitoo** [comment]
Ah...!!!

**Comment by Mygod** [comment]
Also it might be unrelated, but I have been testing it under pretty bad network conditions: public Wi-Fi, frequent Wi-Fi channel switches. Maybe some packet drop triggered the bug? 🤔

**Comment by zonyitoo** [comment]
Yes, it is completely unrelated.

Maybe, maybe there is some bug in tun2socks, that it fails to manage TCP's status transition? Or maybe not.

**Comment by madeye** [comment]
Maybe we can restart the background service every time the network switched.

![203bc22442df63b3a82e7d4079f52403.jpg](https://user-images.githubusercontent.com/627917/107171299-6a89f300-69fd-11eb-9952-fa89304c909f.jpg)

**Comment by dev4u** [comment]
> Maybe we can restart the background service every time the network switched.
> 
> ![203bc22442df63b3a82e7d4079f52403.jpg](https://user-images.githubusercontent.com/627917/107171299-6a89f300-69fd-11eb-9952-fa89304c909f.jpg)

对于使用自定义规则的用户来说，这样的修改很糟糕吧？！

**Comment by Mygod** [comment]
Out of UDP buffer still happens on `issue-2667` branch. However, I'm thinking that maybe it might be because my network is dropping UDP packets instead.

Should I maybe try the old commit, the one without timeout at protect again?

**Comment by IceCodeNew** [comment]
Bump.

**Comment by zonyitoo** [comment]
If timeouts for `protect()` works, then you must could find ERROR logs about TCP sockets creation errors or UDP sockets' bind errors.

https://github.com/shadowsocks/shadowsocks-rust/blob/9927cf621b611ec14983721c7044c23e198753b6/crates/shadowsocks-service/src/local/socks/server/socks5/tcprelay.rs#L137-L161

https://github.com/shadowsocks/shadowsocks-rust/blob/9927cf621b611ec14983721c7044c23e198753b6/crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs#L135-L141

**Comment by madeye** [comment]
After testing for another 7 days, I didn't see any service down issues from my side. To reproduce the unstable network conditions, I even tested on CRH trains for hours...

**Comment by Mygod** [comment]
I just reproduced again earlier today. Maybe it is just my device? 😓

**Comment by madeye** [comment]
Let's keep this issue open. Maybe someone else can help reproduce and debug the issue later.

**Comment by Mygod** [comment]
I will do more testing and see what comes up.

**Comment by Mygod** [comment]
I am seeing errors like: `E libsslocal: ERROR udp relay 127.0.0.1:44187 -> *:443 (proxied) with 1350 bytes, error: Network is unreachable (os error 101)`

**Comment by zonyitoo** [comment]
Network is unreachable!! Why?

**Comment by Mygod** [comment]
Presumably due to network switch. Turning off Wi-Fi restores connection but turning it on kills it again. 🤔

**Comment by Mygod** [comment]
Let's see if 31cbe58 fixes it...

**Comment by Mygod** [comment]
Amazingly it looks like 31cbe58 fixed my issue, even after reverting https://github.com/shadowsocks/shadowsocks-rust/commit/621d4740e238daf6158cb2a4dd9a2dfafe731a63.

@madeye @zonyitoo Thoughts? 😆

**Comment by zonyitoo** [comment]
I have no idea. What's that `underlyingNetwork` means? Will that be overwritten by multi-threads?

**Comment by madeye** [comment]
A race condition?

**Comment by zonyitoo** [comment]
If `volatile` fixes the issue, then:

https://www.baeldung.com/kotlin/volatile-properties

> The @Volatile annotation will mark the JVM backing field of the annotated property as volatile. Thus, the writes to this field are immediately made visible to other threads. Moreover, the reads will always see the latest changes.

**Comment by Mygod** [comment]
> I have no idea. What's that `underlyingNetwork` means? Will that be overwritten by multi-threads?

That field determines which interface new connections should be routed to. It is written exclusively by `DefaultNetworkMonitor` (probably connectivity thread) and read by default pool coroutine workers (multiple threads).

**Comment by Mygod** [comment]
Anyway should we revert the timeout patch? It seems unrelated.

**Comment by madeye** [comment]
Yes, let's revert that commit.

If we got a timeout from Android side, we'd better handle it by ourselves.

**Comment by zonyitoo** [comment]
I would prefer keep it. It should report error instead of blocking the whole coroutine forever.

**Comment by Mygod** [comment]
Sounds good. Closing this issue at last.

**Comment by Mygod** [comment]
Ok it seems like I reproduced it again and found the way to reproduce it.

1. Turn off Wi-Fi and turn on data.
2. Start service.
3. Turn on Wi-Fi.

@madeye Could you try if you could reproduce it too?

**Comment by madeye** [comment]
Nope, I followed the same steps and everything works well.

**Comment by madeye** [comment]
BTW, any special on your WiFi? For example, does it block all the external DNS servers or require web authentication?

**Comment by Mygod** [comment]
No it is a normal home WiFi. Doing this in reverse order does not seem to trigger the issue (i.e. if it starts with Wi-Fi network, then turning on/off data/Wi-Fi does not seem to cut off the connection at all).

**Comment by madeye** [comment]
It looks a bug of the Android system on some specific devices.

Let's wait for more reports if anyone else can reproduce this issue.

**Comment by Mygod** [comment]
I am using latest Android 11 on Pixel 3A XL though. 😅

I've tried switching `bindSocket` to `protect`, and not calling `VpnService.setUnderlyingNetworks` but the issue persists. Another thing I've noticed is that once the service is started under data, turning data off and then on again does not cut off the connection (even though no packets can be sent to wlan0), even though the Network ID has changed.

**Comment by Mygod** [comment]
Too lazy to debug further... Maybe another day. 🤣

**Comment by Mygod** [comment]
Hmm just tried again and it seems working fine on Route on All but not working on Bypass LAN/Bypass LAN and China.

**Comment by Mygod** [comment]
@zonyitoo Any thoughts? Only proxied streams are getting errno 101, bypassed streams are working fine.

**Comment by Mygod** [comment]
I think it might be an issue with server name being a domain name, i.e. some bugs in `lookup_then`.

**Comment by zonyitoo** [comment]
Err.. I remember that @madeye said shadowsocks-android starts `sslocal` with resolved IPs.

DNS queries triggered by `lookup_then` will be looped back to the UDP port because the fd that created by trust-dns is not protected.

**Comment by Mygod** [comment]
Ok you are right.

**Comment by Mygod** [comment]
On the other hand, once I change my server to IP, the issue seems to go away. 🤔

**Comment by madeye** [comment]
It depends. In the latest shadowsocks-android, the hostname is passed to `libsslocal` if there's no plugin enabled:

https://github.com/shadowsocks/shadowsocks-android/blob/181ef5322c1a4a155b121beb672fcbfd6b89f12b/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L50

So, it would be related to the protect() logic in the DNS resolver of shadowsocks-rust. For example, when the network changed, the UDP socket of the local resolver should be released, otherwise we would see the issue.

BTW, even this is the root cause. I still cannot reproduce it following https://github.com/shadowsocks/shadowsocks-android/issues/2667#issuecomment-826384980 on my device.

**Comment by Mygod** [comment]
Wtf?

**Comment by madeye** [comment]
> DNS queries triggered by lookup_then will be looped back to the UDP port because the fd that created by trust-dns is not protected.

I remember you fixed it before, it should be protected now?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/2301

**Comment by zonyitoo** [comment]
> > DNS queries triggered by lookup_then will be looped back to the UDP port because the fd that created by trust-dns is not protected.
> 
> I remember you fixed it before, it should be protected now?

The `lookup_then` is fixed to call trust-dns. If I remembered correctly.

**Comment by Mygod** [comment]
I just added a log in `LocalDnsWorker` and my server domain name was never queried even once. I doubt if #2301 is implemented correctly.

**Comment by zonyitoo** [comment]
I was wrong. It was fixed already.

https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/local/mod.rs#L94-L96

https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/dns/mod.rs#L42-L56

**Comment by Mygod** [comment]
> I was wrong. It was fixed already.
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/local/mod.rs#L94-L96
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/dns/mod.rs#L42-L56

I saw this too but I am starting to think that this is not functional. See my previous comment.

**Comment by zonyitoo** [comment]
Does shadowsocks-android passed `dns` parameter with `unix://` prefix?

**Comment by madeye** [comment]
> Does shadowsocks-android passed dns parameter with unix:// prefix?

Yes.

https://github.com/shadowsocks/shadowsocks-android/blob/181ef5322c1a4a155b121beb672fcbfd6b89f12b/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L86

**Comment by zonyitoo** [comment]
Then it should work.

Please check if there are any logs like: `trace!("DNS resolved {}:{} with customized", self.addr, self.port);`

**Comment by Mygod** [comment]
I know what 39f784a fixes. I don't know why it fixed this but it fixed this.
