### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by max4444** [shadowsocks/shadowsocks-android#267]
Hi, 

I'm getting this error when i try ./build.sh : make: *** No rule to make target `jni/shadowsocks-libev/src/local.c', needed by `obj/local/armeabi-v7a/objs/ss-local/shadowsocks-libev/src/local.o'.  Stop.

And i get  "Initialized empty Git repository in /home/max/shadowsocks-android-master/.git/" when i try git submodule update --init

My build environment:

OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
javac 1.7.0_75
android-ndk-r10d
android-sdk-r23
sbt launcher version 0.13.7

Any helps would be appreciated.

Regards,
Max

**Comment by Mygod** [comment]
Use `git clone` instead of downloading the zip file.

**Comment by dosoos** [comment]
you requestion is close? i'm have this problem
