### ISSUE TITLE
Can’t connect without DNS forwarding

### ISSUE THREAD

**Issue by chinese-dude** [shadowsocks/shadowsocks-android#2674]
I use Shadowsocks as the transport protocol between my client and a V2Ray server.  The server makes additional routing decisions based on domain names, and for this reason, DNS forwarding must be turned off.  Blanking the **Remote DNS** field, however, prevents connecting with the server profile.

A look at the source suggests there might be a defect in “BaseService.kt”.  Specifically, while **ProxyInstance.start** does [provide a switch](https://github.com/shadowsocks/shadowsocks-android/blob/7112c49dada6f5a0cf24265b9231524cb29e2f4d/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L72) (**dnsRelay**) that controls DNS forwarding, the argument is not passed by [the code responsible for starting the proxy processes](https://github.com/shadowsocks/shadowsocks-android/blob/5352fae61345062b832498fde1371db48b4b4c51/core/src/main/java/com/github/shadowsocks/bg/BaseService.kt#L246) and, as a result, always defaults to **true**.

* * * 

**Describe the bug**
Connecting with a profile with a blank **Remote DNS** field isn’t possible.

**To Reproduce**
1. Go to the **Profile config** view.
2. Blank **Remote DNS**.
3. Save the profile.
4. Activate the profile and connect.
5. You will get the following message.
> Failed to connect the remote server: Authority expected at index 6: dns://

**Expected behavior**
A connection should be established if the profile is configured properly.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
n/a

**Configuration**
* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: (blank)
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
n/a

**Comment by Mygod** [comment]
Do not leave blank in remote DNS.

**Comment by chinese-dude** [comment]
Can you explain why it’s not supposed to be left blank?  Why does `ProxyInstance.start` has a `dnsRelay` parameter?

**Comment by wurenny** [comment]
there is no reason to force dns relaying !
users should be left to decide whether to relay or not !
