### ISSUE TITLE
chacha20-ietf-poly1305比xchacha20-ietf-poly1305更容易引来主动探测

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-android#2677]
同一个服务器端
Centos 7,SS-libev.no plugins
TCP only and disable TCP Fast Open
端口A,用chacha20-ietf-poly1305
端口B用xchacha20-ietf-poly1305

同一用户端:ss-libev local
在同一时间段的测试发现
端口B引来的主动探测IP更多.是端口A的四倍
端口B日志不产生Salt AHEAD detect报警
端口A产生一大堆的Salt AHEAD detect报警

建议还是把xchacha20-ietf-poly1305加回来吧
看不出只支持chacha20-ietf-poly1305有什么好处

**Comment by dev4u** [comment]
两个端口对调加密方式试试。

**Comment by sophauer** [comment]
> 两个端口对调加密方式试试。

结果一样,我在三个小鸡上测试过

**Comment by IceCodeNew** [comment]
我觉得这个你需要去 https://github.com/shadowsocks/shadowsocks-rust/ 那边提才有用。

**Comment by sophauer** [comment]
> 我觉得这个你需要去 https://github.com/shadowsocks/shadowsocks-rust/ 那边提才有用。
> 
> 此外这个建议和 Issue #2663 重复，我觉得几乎不太可能得到推进。

谢谢,刚去看了一下,原来是backend换了,那这个真玄了.也实在不懂为什么非得要拿掉xchacha20-ietf-poly1305

**Comment by jtan21at** [comment]
把加密部分独立出来用户自己选择更好
