### ISSUE TITLE
如何调试scala+sbt with android

### ISSUE THREAD

**Issue by i5ting** [shadowsocks/shadowsocks-android#269]
有点晕

每次都脚本，慢的哭了

**Comment by madeye** [comment]
http://developer.android.com/tools/debugging/index.html

**Comment by i5ting** [comment]
能写一个少简短的您的经验么？用java debug我很熟，scala刚接触

**Comment by i5ting** [comment]
https://github.com/jberkel/android-plugin/ 不能用

**Comment by i5ting** [comment]
https://github.com/pfn/android-sdk-plugin 也不能用

**Comment by Mygod** [comment]
+1
上一次尝试手贱把系统搞坏了。= =

**Comment by i5ting** [comment]
```
#! /bin/bash
adb shell am start -n com.github.shadowsocks/com.github.shadowsocks.Shadowsocks
```

这样么？

**Comment by vmlinz** [comment]
可以尝试使用https://github.com/mpeltonen/sbt-idea, 项目里面有这个plugin，可以生成idea的工程，导入到idea里面就可以调试了。

前提先把native的库build好。

**Comment by Hackeris** [comment]
参考这里http://scala-on-android.taig.io/editor/android-studio/，可以实现调试

**Comment by tkisme** [comment]
```
adb shell monkey -p com.github.shadowsocks -c android.intent.category.LAUNCHER 1
```
launch ss from shell
