### ISSUE TITLE
Why is xchacha20-ietf-poly1305 deprecated?

### ISSUE THREAD

**Issue by catscarlet** [shadowsocks/shadowsocks-android#2697]
I searched and got #2651 and 5352fae and #2655 , still have no idea why xchacha20-ietf-poly1305 is deprecated?

Security issue? or just some android-only dependencies gave up xchacha20-ietf-poly1305?

**Comment by sophauer** [comment]
cuz the backend,shadow-rust,removed it

**Comment by catscarlet** [comment]
Got it.

Well I searched in shadowsocks-rust and got something useful. I think I should leave these links here to help someone else has same question.

shadowsocks/shadowsocks-rust#317
shadowsocks/shadowsocks-rust#319
