### ISSUE TITLE
Per App VPN functionality in android below lollipop version

### ISSUE THREAD

**Issue by dkumar1987** [shadowsocks/shadowsocks-android#270]
I want to allow some specific applications(by default all) to pass through vpn.
It is a default API in lollipop version but I want to implement in below lollipop version.
How can i implement this?

**Comment by madeye** [comment]
Root your phone.

**Comment by dkumar1987** [comment]
But many app in market those have implemented firewall applications. Can i create firewall application without root phone?

**Comment by dkumar1987** [comment]
basically i want to allow specific app to use data.
