### ISSUE TITLE
[FR] _gateway ip support, like systemd-resolved dns resolver

### ISSUE THREAD

**Issue by rayfoss** [shadowsocks/shadowsocks-android#2716]
**Is your feature request related to a problem? Please describe.**
I have a 5mbps hotspot speed limit on my main phone. When I install an SS server on the phone and use the Shadowsocks for Android app on my Chromebook or Android tablet clients, I can bypass that speed limit and get 80mbps+ downloads. My main issue is, anytime I restart or toggle the hotspot, it's IP changes, Requiring me to manually update the hotspot IP in the Shadowsocks app for all clients.

**Describe the solution you'd like**
Systemd networking stack resolves _gateway to the gateway IP automatically. This is a really useful feature, as on Linux clients I can just set Shadowsocks to find the server hosted on _gateway and never have to change the config even when the hotspot restarts.

**Describe alternatives you've considered**
I've considered installing a DNS server on the Android hotspot, but that would need to be hosted on a non standard port without root access and it would not be published by the default hotspot DHCP either. Meaning clients would need custom DNS server settings, but not custom IP settings. Stock Android AOSP clients don't support that.

**Additional context**
I'm using stock Android 11 on all my hardware, I do have one rooted phone, but it doesn't support the fast wideband radio that the expensive unrooted phone does. Rooting can leave annoying warnings, break Safetynet/Widevine, get me blacklisted and/or reduce network stability from carrier services app tomfoolery.

**Comment by Mygod** [comment]
Too niche.
