### ISSUE TITLE
Extremely slow to start the service

### ISSUE THREAD

**Issue by smilinger** [shadowsocks/shadowsocks-android#272]
If I select "bypass LAN and mainland address" in the setting, it will take about 30 seconds to start, it is painful to wait.
Why is it so slow, without the setting mentioned above it takes only 8 seconds. And it is much faster      to start fqrouter, I believe fqrouter is using the same method (to setup a vpn connection).

**Comment by madeye** [comment]
https://code.google.com/p/android/issues/detail?id=62530&can=1&q=vpnservice%20max&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
