### ISSUE TITLE
DDNS support with plugins

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#2722]
Now that we have DDNS from #2301, we should support it when it is used along with a plugin as well. One thing to do is to start a second plugin when IP is changed, and release the first one when all existing connections have been closed.

CC @zonyitoo @madeye

**Comment by zonyitoo** [comment]
Currently `sslocal` passes the host name directly as `SS_REMOTE_HOST`.

**Comment by Mygod** [comment]
Yes but the plugins do not have the custom DNS passed to it. I think handling them in sslocal is the best option.

**Comment by zonyitoo** [comment]
Hmm. Is it possible to have a solution that could hooks all traffics sending to UDP port `53`?

**Comment by Mygod** [comment]
That is what shadowsocks-android used to do a few years ago and I fixed it. :rofl:

**Comment by zonyitoo** [comment]
It would be a lot nicer for plugins, which are hard to make modifications on DNS resolver.

**Comment by madeye** [comment]
> Hmm. Is it possible to have a solution that could hooks all traffics sending to UDP port 53?

Currently, we already hijack all the UDP DNS queries to the DNS gateway (local DNS resolver provided by shadowsocks-rust): 
https://github.com/shadowsocks/badvpn/blob/fb01eb983915c9a09a690ad44c6028dd87500ec7/tun2socks/SocksUdpGwClient.c#L286

So, if we can bypass any query of the server's hostname, it's possible to solve the plugin's issue as well: https://github.com/shadowsocks/shadowsocks-android/issues/2301#issuecomment-757596516

**Comment by Mygod** [comment]
First it's not hijacking since no other DNS is running at that address. Second you're right that would be a better solution lol.

**Comment by zonyitoo** [comment]
If I understand correctly, `sslocal` should try to parse UDP packets and guess if it is a DNS query, and then bypass it to the local DNS client.

**Comment by madeye** [comment]
`tun2socks` already did this for `sslocal`. It only bypass DNS packets to the local resolver of `sslocal`.

**Comment by zonyitoo** [comment]
Ah. Then it should be considered as **already solved**?

**Comment by madeye** [comment]
But in the current local resolver of `sslocal`, the queries will be forwarded to the remote server (through the plugin). That's the root cause...

We just need to add one logic into `sslocal` that it bypasses all the queries for `ss.example.com` to `unix://local_dns_path`
