### ISSUE TITLE
能否添加IPv6优先

### ISSUE THREAD

**Issue by toorich** [shadowsocks/shadowsocks-android#2740]
如题，实测即使打开IPv6路由的功能ss也会优先使用IPv4进行连接。

**Comment by sophauer** [comment]
ipv6普及率只有30%(貌似).而且墙国内ipv6路由乱成一团,用过几次就放弃了,退回到ipv4 only.
添加IPV6优先好像会添乱

**Comment by toorich** [comment]
> ipv6普及率只有30%(貌似).而且墙国内ipv6路由乱成一团,用过几次就放弃了,退回到ipv4 only.
> 添加IPV6优先好像会添乱

我使用ss后是使用的是墙外服务端上的IPv6，和国内的IPv6线路好坏无关

**Comment by Mygod** [comment]
Since this app works as a VPN, it does not get to decide whether to prioritize connecting to IPv6 or IPv4. Complain to the app you are using instead.
