### ISSUE TITLE
5.2.3版本的启动按钮有问题

### ISSUE THREAD

**Issue by gegehennb** [shadowsocks/shadowsocks-android#2744]
您好，我的系统是miui12.0.2.0。
今天安装了5.2.3版本，结果在设置选项这里，出现了图上的问题
![IMG_20210605_091553](https://user-images.githubusercontent.com/16933365/120875486-a82f0f00-c5de-11eb-9834-013de870d519.jpg)
整个启动按钮乱了，测试5.2.2版本是正常的。

**Comment by Mygod** [comment]
#2733
