### ISSUE TITLE
UDP相关

### ISSUE THREAD

**Issue by KeSaite** [shadowsocks/shadowsocks-android#2746]
**Describe the bug**
5.2.4版本，单个配置文件A，如何开启UDP？虽然可以通过克隆A配置文件或者全局模式开启UDP，但要为了绕过大陆IP除了前面克隆的方法其他不行了吗？首先我没有安装任何插件，配置文件都是原版SS，服务端也支持UDP。v2rayng、clash客户端开启绕过大陆IP模式UDP正常。
我尝试了单独创建一个UDP配置文件B，然后如截图所示，在A配置文件的UDP Fallback功能选择了配置文件B，但是似乎并不起作用，这是为什么？

**Screenshots**
![image](https://user-images.githubusercontent.com/13944595/121766695-91605d80-cb86-11eb-991f-e93f50e0e7c6.png)

![image](https://user-images.githubusercontent.com/13944595/121766701-97563e80-cb86-11eb-8e15-4d6d61e58f9d.png)

![image](https://user-images.githubusercontent.com/13944595/121766740-d6848f80-cb86-11eb-885f-da046c76e7f3.png)

![image](https://user-images.githubusercontent.com/13944595/121766714-a3da9700-cb86-11eb-9790-7cd39333a229.png)

**Expected behavior**
UDP正常

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 11
 - Device: Google Pixel 2 XL
 - Version: 5.2.4

**Comment by Mygod** [comment]
UDP is enabled by default if UDP fallback is empty.

**Comment by KeSaite** [comment]
> UDP is enabled by default if UDP fallback is empty.

按常理来说是这样的，但是如果UDP是禁用的，在我这边UDP不起作用，我也不知道哪里出了问题|

**Comment by KeSaite** [comment]
我刚才下了二款游戏(二之国交错世界和sky)实际弄了一下，发现了一个情况。shadowsocks在全局模式，UDP Fallback为空的情况下，UDP正常，但是(二之国)游戏会提示网络问题，而(sky)游戏虽然可以正常进入，但是联机状态似乎不太正常

v2ray，clash，surfboard在同一配置下，两款游戏均正常

如果开发者测试一下的话，情况是可以复现的，推荐(二之国)测试，快速明了

**Comment by madeye** [comment]
1. I just tested Ni no Kuni: Cross Worlds (Google Play Edition) locally. Everything works well.
2. UDP relay also works with STUN and Google Voice.

BTW, I don't think either Ni no Kuni or Sky is using UDP. In fact, very few mobile games would use UDP, since most mobile devices are behind NAT.

So, double check your shadowsocks server is up to date and supports full cone UDP. You'd better setup shadowsocks-rust or go-shadowsocks2 on your server, to ensure best compatibility.

**Comment by KeSaite** [comment]
> 1. 我刚刚在本地测试了 Ni no Kuni: Cross Worlds (Google Play Edition)。一切正常。
> 2. UDP 中继也适用于 STUN 和 Google Voice。
> 
> 顺便说一句，我认为 Ni no Kuni 或 Sky 都没有使用 UDP。事实上，很少有手机游戏会使用 UDP，因为大多数移动设备都在 NAT 之后。
> 
> 因此，请仔细检查您的 shadowsocks 服务器是否是最新的并支持全锥 UDP。您最好在服务器上设置 shadowsocks-rust 或 go-shadowsocks2，以确保最佳兼容性。

OK，我自己再试一试

**Comment by KeSaite** [comment]
尝试重新购买了一台新机子，全新Ubuntu21环境安装了go-shadowsocks2，情况似乎还是一样，俺放弃了_(´ཀ`」 ∠)__

**Comment by KeSaite** [comment]
> 1. I just tested Ni no Kuni: Cross Worlds (Google Play Edition) locally. Everything works well.
> 2. UDP relay also works with STUN and Google Voice.
> 
> BTW, I don't think either Ni no Kuni or Sky is using UDP. In fact, very few mobile games would use UDP, since most mobile devices are behind NAT.
> 
> So, double check your shadowsocks server is up to date and supports full cone UDP. You'd better setup shadowsocks-rust or go-shadowsocks2 on your server, to ensure best compatibility.

尝试重新购买了一台新机子，全新Ubuntu21环境安装了go-shadowsocks2，游戏情况似乎还是一样，俺放弃了_(´ཀ`」 ∠)__

**Comment by madeye** [comment]
The best way to verify UDP is using this app:
 https://play.google.com/store/apps/details?id=hu.uszeged.inf.wlab.stunner

The expected NAT type should be full cone.

**Comment by KeSaite** [comment]
> 验证 UDP 的最佳方法是使用此应用程序：[https](https://play.google.com/store/apps/details?id=hu.uszeged.inf.wlab.stunner) :
> [//play.google.com/store/apps/details?id=hu.uszeged.inf.wlab.stunner](https://play.google.com/store/apps/details?id=hu.uszeged.inf.wlab.stunner)
> 
> 预期的 NAT 类型应为全锥。
尝试重新购买了一台新机子，全新Ubuntu21环境安装了go-shadowsocks2，然后刚才试了一下发的那个应用，是显示通的，但是游戏情况似乎还是一样，换成v2，clash就正常，搞不定呀，俺想放弃了_(´ཀ`」 ∠)__
![image](https://user-images.githubusercontent.com/13944595/121774176-9c7db280-cbb3-11eb-896a-9dcff03d0f23.png)
![image](https://user-images.githubusercontent.com/13944595/121774180-a8697480-cbb3-11eb-8723-bd55ecea3ca3.png)

**Comment by madeye** [comment]
From your screenshot, the UDP relay didn't work.

**Comment by KeSaite** [comment]
> From your screenshot, the UDP relay didn't work.

我不明白的是同一个配置文件，v2rayng、clash是正常的
![image](https://user-images.githubusercontent.com/13944595/121774685-29297000-cbb6-11eb-9e08-baf47d8fca65.png)

**Comment by KeSaite** [comment]
不过辛苦开发者了，俺打算放弃了(oﾟvﾟ)ノ

**Comment by KeSaite** [comment]
> From your screenshot, the UDP relay didn't work.

忘记对比了，这是v2rayng和clash的截图
![image](https://user-images.githubusercontent.com/13944595/121775156-79093680-cbb8-11eb-845b-975cce667441.png)

**Comment by madeye** [comment]
Please post your server config here.

**Comment by KeSaite** [comment]
> Please post your server config here.

辛苦开发者了，不过还是不知道咋回事，要不要cmd补个log
  {
    "server": "x.x.x.x",
    "server_port": 11110,
    "password": "xxxx",
    "method": "aes-256-gcm",
    "remarks": "x",
    "route": "bypass-lan-china",
    "remote_dns": "8.8.8.8",
    "ipv6": false,
    "metered": false,
    "proxy_apps": {
      "enabled": false
    },
    "udpdns": false
  }

**Comment by madeye** [comment]
I cannot reproduce your issue with the same config.

Given other clients work for you, I suggest you keep use them on your device.

**Comment by KeSaite** [comment]
> I cannot reproduce your issue with the same config.
> 
> Given other clients work for you, I suggest you keep use them on your device.

啊，麻烦了，先用着吧

**Comment by larvata** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/1443833/124645778-6be51c00-dec6-11eb-86a3-00193dfffe45.png)
![image](https://user-images.githubusercontent.com/1443833/124645931-9cc55100-dec6-11eb-9d9f-d0b9d0b8d88f.png)

I noticed I can't hear anyone talking in any rooms in clubhouse.
This server supports UDP and it works on iOS with surge.

**Comment by Mygod** [comment]
Update to 5.2.5.

**Comment by larvata** [comment]
Just updated it to 5.2.5, but still doesn't work.
STUNner test has the same result.

**Comment by DaPoHou** [comment]
我也有同样的问题。在配置文件UPD配置如果是默认的禁用，使用telegram语音通话可以连接，但是效果很差。
如果克隆一个配置，在udp配置中选择克隆后的文件，效果会很好。

**Comment by windstander** [comment]
> The best way to verify UDP is using this app: https://play.google.com/store/apps/details?id=hu.uszeged.inf.wlab.stunner
> 
> The expected NAT type should be full cone.

测试出来是 Symmetric cone 能否正常工作？
