### ISSUE TITLE
Prefer IPv4 or disable IPv6

### ISSUE THREAD

**Issue by matttbe** [shadowsocks/shadowsocks-android#275]
Hello,

First, thank you for developing and maintaining this free, open-source and nice SOCKS proxy!

I have a problem with IPv6: When my smartphone has an IPv6 address, it will first try to connect to an IPv6 address if one is available. But the problem is that my proxy (shdowsocks-libev) is running on a server without IPv6 address and the DNS resolver can answer to AAAA requests. I'm able to block AAAA DNS requests on the proxy if they are made on top of UDP but it seems the proxy do all requests on top of TCP. If I block the port 53 for TCP protocol, each time I use `nslookup` on the smartphone, I have an error.

The result is that when my smartphone has an IPv6 address, the connections are "slow": it first tries to connect to an IPv6 address but because it will not be possible to do that, after a few seconds, the smartphone tries to connect to the IPv4 address.
It's not really a problem with the browsers because they have implemented Happy Eyeballs feature (RFC6555) but apps like the Play Store are "slow" because Google supports IPv6.

I could also disable IPv6 on the smartphone by setting this Sysctl but Android will re-enable IPv6 after any re-connection: `net.ipv6.conf.all.disable_ipv6 = 1`.

Do you have any idea how to solve this problem? :-)

Is it maybe possible to add an (hidden) option to disable IPv6 support / to not prefer IPv6? ~~When looking at the source code, I see this line:~~

    Utils.resolve(config.proxy, enableIPv6 = true)

**EDIT**: Sorry, I didn't see that this method is only called at the initialisation part to get the IP of the proxy server.

Best Regards,

Matt

**Comment by madeye** [comment]
1. shadowsocks-android cannot proxy IPv6 traffic.All IPv6 fraffic are just bypassed to the lower interface.
2. To avoid using IPv6, the best way I think is to disable it on your server. Filtering all AAAA queries should work.

**Comment by matttbe** [comment]
Hello Max,

Thank you for this quick answer!

> Shadowsocks-android cannot proxy IPv6 traffic.Actually, all IPv6 fraffic are just bypassed to the lower interface.

What do you mean when saying "*IPv6 fraffic are just bypassed to the lower interface*"? Do you mean that this IPv6 traffic is not redirected to the proxy?

> To avoid using IPv6, the best way I think is to disable it on your server. Filtering all AAAA queries should work.

My proxy doesn't have global IPv6 address, just a local one. I would like to filter all AAAA queries but I don't know how to simply do that when queries are made on top of TCP :-/
Or maybe I could redirect all traffic to `8.8.4.4` address to a custom DNS server which will not answer to AAAA queries.

When looking at the [documentation](http://members.home.nl/p.a.rombouts/pdnsd/doc.html#querymethodcommandlineoption) of `pdnsd`, I see a `reject` option. Maybe we could reject all IPv6 address by setting `::/0` (+ settings `reject_policy=negate` and `reject_recursively=on`.

**Comment by madeye** [comment]
1. Yes, IPv6 traffic is not redirected.
2. Try to redirect all TCP traffic to the dest port `53` on your server to your local DNS server. In your local DNS server, you can just disable AAAA queries as you like.
3. Of course, you can modify shadowsocks-android itself to reject all IPv6 results. Look at https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/utils/ConfigUtils.scala#L65 for more details.

**Comment by matttbe** [comment]
> Yes, IPv6 traffic is not redirected.

Ok, I didn't check that! Then is it not better to reject all IPv6 addresses received by `pdnsd`? Or having an option to drop/reject all IPv6 traffic by adding a new iptables rule?

> Try to redirect all TCP traffic to the dest port 53 on your server to your local DNS server. In your local DNS server, you can just disable AAAA queries as you like.

Thank you for this idea! I'll try to do that.

> Of course, you can modify shadowsocks-android itself to reject all IPv6 results.

Yes, I saw this file. I tried to directly play with `pdnsd` but it would be better if I recompile your app. Another problem is that we are doing that for academic researches and if I change your app, we'll have to reinstall it on all test devices but yes, it's another problem :-)

**Comment by madeye** [comment]
> Ok, I didn't check that! Then is it not better to reject all IPv6 addresses received by pdnsd? Or having > an option to drop/reject all IPv6 traffic by adding a new iptables rule?

We decided to bypass IPv6 traffic because they are not blocked in China. I've no plan to modify this behaviour or add an option for it, as it will confuse the major users of this App.

So, my suggestion is to modify and recompile the app yourself. :)

**Comment by matttbe** [comment]
> We decided to bypass IPv6 traffic because they are not blocked in China.

I didn't know that IPv6 could be seen as a kind of freedom :-)

> I've no plan to modify this behaviour or add an option for it, as it will confuse the major users of this App.

Yes, I totally understand! Is it maybe possible to add a note somewhere to precise that only IPv4 traffic is redirected? :-)

**Comment by matttbe** [comment]
> Maybe we could reject all IPv6 address by setting `::/0` (+ settings `reject_policy=negate` and `reject_recursively=on`).

It seems it's not a good idea. When trying with `google.com`, it will only display IPv4 adresses. But with other requests (e.g. `korben.info`), `nslookup` returns no address! It's maybe because `pdnsd` will reject all answers if it detect at least one IPv6...

Then, my idea is to disable IPv6 on the smartphones by dropping all IPv6 traffic with `ip6tables`... Not so good but if I only set this sysctl to `1`, Google will re-enable it later: `net/ipv6/conf/all/disable_ipv6`

**Comment by madeye** [comment]
Tried korben.info, it works well.

```
u0_a99@hammerhead:/ $ nslookup korben.info 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      korben.info
Address 1: 2400:cb00:2048:1::a29f:fbba
Address 2: 162.159.251.186
Address 3: 162.159.250.186


u0_a99@hammerhead:/ $ nslookup korben.info 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      korben.info
Address 1: 162.159.251.186
Address 2: 162.159.250.186
```

**Comment by matttbe** [comment]
You're lucky :-)

Is it possible that it's due to your DNS caches? But it shouldn't be... I also had problem with `ipv6.be` and `ipv6.nl`. And after removing the rules, I got both IPv4 and IPv6...

But note that I tried by launching `pdnsd` manually.

PS: is it maybe possible to get the APK build with your last commit? :-)

**Comment by matttbe** [comment]
I just retry on a network without IPv6 and after having added these 3 new options in `/data/data/com.github.shadowsocks/pdnsd-nat.conf` and relaunched `pdnsd -c pdnsd-nat.conf`, it works with `google.com`, `wikipedia.org`, `facebook.com`, `korben.info`, `ipv6.be`, etc. (I only have IPv4 addresses) but I still have a first IPv6 address with `ipv6.nl`:

````
root@hammerhead:/ # nslookup ipv6.nl 127.0.0.1:8163
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      ipv6.nl
Address 1: 2a02:2210:12:a:b820:fff:fea2:25d1
Address 2: 85.159.113.53

root@hammerhead:/ # nslookup korben.info 127.0.0.1:8163
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      korben.info
Address 1: 162.159.251.186
Address 2: 162.159.250.186

root@hammerhead:/ # nslookup ipv6.nl 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      ipv6.nl
Address 1: 2a02:2210:12:a:b820:fff:fea2:25d1
Address 2: 85.159.113.53
````

But I guess it's due to the caches...
