### ISSUE TITLE
Share Over Lan not available.

### ISSUE THREAD

**Issue by emmauss** [shadowsocks/shadowsocks-android#2750]
Please read contributing guidelines. Thanks.

**Describe the bug**
The Share Over Lan option is not visible on my client.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advance'
3. No Share Over Lan option

**Expected behavior**
A toggable option for Share over Lan should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/5307160/122961891-60490f80-d374-11eb-8582-b5b5412f09ec.png)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 10 Aarch64
 - Device: LG G7 ThinQ
 - Version: 5.2.4 Google Play
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Expected behavior.

**Comment by emmauss** [comment]
any reason why it's expected?
