### ISSUE TITLE
double click one profile and drag upwards, profiles would be displayed incorrectly

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#2752]
Please read contributing guidelines. Thanks.

**Describe the bug**
select one profile, and double click the profile and drag upwards, profiles would be displayed incorrectly

**To Reproduce**
1.select one profile
2.double click the profile fast
3.don't let go your finger and draw it upwards immediately

**Expected behavior**
normal

**Screenshots**
![20210628_162554](https://user-images.githubusercontent.com/3872185/123642789-43ba4500-d856-11eb-991d-b3b3e82d476f.gif)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: android 8.10
 - Device: [e.g. Google nexus 6P
 - Version:5.2.4
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Umm do not double click? 😭

**Comment by iamsad3508** [comment]
🤣 it's ok to me, if you won't fix it

**Comment by DescargarDixmax** [comment]
And what is the fault for that double click operation?

**Comment by yndue736** [comment]
If you are facing this similar problem then I suggest you to check some information about [Woodbridge dental center](https://www.woodbridgedentalcentre.com/woodbridge-dental-centre/vellore-village-dentist-family-cosmetic/) where they applied some same procedure that you also looking for.

**Comment by MSVhora** [comment]
Is anyone working on this issue?

**Comment by Mygod** [comment]
Not as far as I'm concerned. Feel free to submit a PR.

**Comment by MSVhora** [comment]
@Mygod There are a couple of optimizations we can do in the move function of ProfileAdapter.

1) I think instead of swapping each item in the [from, to] range, we can just swap [from, to] object's `userOrder` and [from, to] objects themselves in the array.
2) Instead of `updated` HashSet of Profile object, we can use HashMap of <profileId, Profile> to reduce the number of update operations on DB.
For example, I dragged the item at index `20` to index `0` and back to index `20`, which added 53 objects in the `updated` HashSet, where we only need to update at most 20.

**Comment by MSVhora** [comment]
> @Mygod There are a couple of optimizations we can do in the move function of ProfileAdapter.
> 
> 1. I think instead of swapping each item in the [from, to] range, we can just swap [from, to] object's `userOrder` and [from, to] objects themselves in the array.
> 2. Instead of `updated` HashSet of Profile object, we can use HashMap of <profileId, Profile> to reduce the number of update operations on DB.
>    For example, I dragged the item at index `20` to index `0` and back to index `20`, which added 53 objects in the `updated` HashSet, where we only need to update at most 20.

@Mygod Should I implement above optimization ?
