### ISSUE TITLE
断流问题

### ISSUE THREAD

**Issue by feixiaoyu1984** [shadowsocks/shadowsocks-android#2754]
5.2.3 和5.2.4有断流问题 并且按测试连接按钮 间歇性不通 经过一个一个测试发现 5.2.2  5.2.1是正常的
现在使用5.2.2

**Comment by Mygod** [comment]
fill out template

**Comment by lanyuue** [comment]
断流问题蛮严重的，像安卓检查更新，一下通一下网络不通

**Comment by Mygod** [comment]
Dup #2751
