### ISSUE TITLE
ERR_CONNECTION_RESET on first website visit

### ISSUE THREAD

**Issue by uragiristereo** [shadowsocks/shadowsocks-android#2757]
Please read contributing guidelines. Thanks.

**Describe the bug**
Everytime i visit a site it will be error connection reset on first time, then works normally after reloading several times. Also images sometimes could not loaded properly.

**To Reproduce**
1. Connect to any server with UDP Fallback
2. Visit any site
3. See error **ERR_CONNECTION_RESET** (see Screenshot 1)
4. Site works normally after reload once but images not loaded properly (see Screenshot 2)

**Expected behavior**
Site and images loaded properly.

**Screenshots**
(Screenshot 1)
![image](https://user-images.githubusercontent.com/52477630/124500194-84cbcf80-dde9-11eb-94ee-adfcba88cd36.png)

(Screenshot 2)
![image](https://user-images.githubusercontent.com/52477630/124500225-9319eb80-dde9-11eb-8c7a-00b2b956db2a.png)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 10 Q & Chrome v79
 - Device: Xiaomi Mi A2
 - Version: v5.2.4
 - Last version that did not exhibit the issue: 5.2.2

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha-ietf-poly1305
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I think it's because of the new DDNS feature. Downgrading to v5.2.2 works fine.
Sorry for my bad report this is my first time doing opening issue in GitHub.

**Comment by Mygod** [comment]
🤔 Android should have built-in DNS cache: https://android.googlesource.com/platform/bionic/+/android-5.0.0_r1/libc/dns/resolv/res_cache.c

I guess it is likely that custom ROM could improperly implement the cache.

**Comment by uragiristereo** [comment]
Thank you for the response. My friend also had the same issue. He use Samsung Galaxy S21 with OneUI 3.

**Comment by Mygod** [comment]
Dup #2751.
