### ISSUE TITLE
Random TCP connection establish failure: connection immediately closed on establish by server

### ISSUE THREAD

**Issue by recolic** [shadowsocks/shadowsocks-android#2759]
**Describe the bug**
I execute the `telnet` command to test opening TCP connections, but most tests fail randomly. The connection was immediately closed, after a successful establishment. 
I'm sure that, all tested port are accessible from Internet. Retry sometimes could resolve this issue, and sometimes not. 

I tried to execute these commands again with `outline-android` VPN, using exactly the same shadowsocks server. 
However, these commands succeeded 100%. 

**To Reproduce**
1. Enable shadowsocks-android and connect to any node. The route is `Bypass LAN`. 
2. Run `termux`. 
3. Execute `telnet smtp.gmail.com 587`, `telnet aliyun.com 80`, `telnet smtp-mail.outlook.com 587`, `telnet imap.recolic.cc 143`
4. Random failure spotted. Connection immediately closed, after the establishment. 

**Screenshots**

<details>
  <summary>Click to expand. </summary>

```
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
u0_a235@localhost ~> telnet recolic.cc 80
Trying 139.162.87.22...
Connected to recolic.cc.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet recolic.cc 80
Trying 139.162.87.22...
Connected to recolic.cc.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet aliyun.com 80
Trying 140.205.135.3...
Connected to aliyun.com.
Escape character is '^]'.
helo


^C^]
telnet> q
Connection closed.
u0_a235@localhost ~> telnet smtp-mail.outlook.com 587
Trying 52.96.26.162...
Connected to smtp-mail.outlook.com.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet smtp.gmail.com 587
Trying 142.251.2.108...
Connected to smtp.gmail.com.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet smtp-mail.outlook.com 587
Trying 52.96.188.162...
Connected to smtp-mail.outlook.com.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet smtp-mail.outlook.com 587
Trying 52.96.188.162...
Connected to smtp-mail.outlook.com.
Escape character is '^]'.
220 SJ0PR03CA0247.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 6 Jul 2021 07:55:38 +0000
^]
telnet> q
Connection closed.
u0_a235@localhost ~> telnet smtp-mail.outlook.com 587
Trying 52.96.69.66...
Connected to smtp-mail.outlook.com.
Escape character is '^]'.
220 BY5PR17CA0040.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 6 Jul 2021 07:55:57 +0000
^]
telnet> q
Connection closed.
u0_a235@localhost ~> telnet aliyun.com 80
Trying 140.205.135.3...
Connected to aliyun.com.
Escape character is '^]'.
Connection closed by foreign host.
u0_a235@localhost ~> telnet aliyun.com 80
Trying 140.205.135.3...
Connected to aliyun.com.
Escape character is '^]'.
helo
HTTP/1.1 302 Moved Temporarily
Server: Tengine
Date: Tue, 06 Jul 2021 07:56:19 GMT
Content-Type: text/html
Content-Length: 215
Connection: close
Location: http://err.taobao.com/error1.html
Via: tongyijieru-aliyun-com011227224177.et93[web,302]

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>
Connection closed by foreign host.
u0_a235@localhost ~>
```

</details>

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 11, kernel 4.9.248-ga11f008926d6 (build RQ3A.210605.005)
 - Device: Google Pixel 3 XL
 - Version: v5.2.4
 - Last version that did not exhibit the issue: N/A

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: dns.google
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

I also noticed that, the first connection trial would be 100% failure, the following connection trial would be 50% failure.

**Comment by recolic** [comment]
I'm doing some work to re-produce this issue on linux-desktop, with the same toolchain used by ss-android (tun2socks+ss-rust)

**Comment by Mygod** [comment]
Update to v5.2.5.
