### ISSUE TITLE
shadowsocks android的分应用代理无效，而ProxyDroid的分应用代理模式正常

### ISSUE THREAD

**Issue by ueinohakono** [shadowsocks/shadowsocks-android#277]
G3 ROM。给root权限开shadowsocks-android就全局无网，只能禁了root开VPN
然后我在路由器上建了个Shadowsocks的socks5代理，ProxyDroid配置好后给root权限分应用等功能都是正常的。
不知道算不算给作者提供了一个解决很多ROM无法分应用代理的方向

**Comment by madeye** [comment]
Duplicate with #177 

Try this http://forum.xda-developers.com/showthread.php?t=2524485
