### ISSUE TITLE
Google Pixel 5 升级到 android12 bate4 后变得无法代理系统流量

### ISSUE THREAD

**Issue by zhang-xzh** [shadowsocks/shadowsocks-android#2783]
可以连接到服务器, APP内测试连接正常, 但是其他程序无法连接网络

**Comment by zhang-xzh** [comment]
![Screenshot_20210812-173124](https://user-images.githubusercontent.com/10415368/129174953-dee70cfd-180e-4ff9-b322-3dd96d5cf503.png)

![Screenshot_20210812-173150](https://user-images.githubusercontent.com/10415368/129174970-1d180498-dc1a-40fb-a9e6-b01e07f24ce1.png)

![Screenshot_20210812-173428](https://user-images.githubusercontent.com/10415368/129174986-1ff665e1-84cf-4d15-9e21-de645286bd0f.png)

![Screenshot_20210812-173327](https://user-images.githubusercontent.com/10415368/129174994-b2e40963-539e-48b4-93b0-d200b639efd1.png)

**Comment by dev4u** [comment]
ref #2782
