### ISSUE TITLE
libsslocal exits too fast (exit code: 134)

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/shadowsocks-android#2785]
都是最新版apk，相同配置导入，全部手机（小米11 U、锤子手机、小米9）都正常。
在小米平板5上提示：libsslocal exits too fast (exit code: 134) bug

**Comment by Mygod** [comment]
logcat

**Comment by wyfang** [comment]
> logcat

what？check log？But  how to check log?

**Comment by Mygod** [comment]
You can use an app to export logcat from Google Play or others.

**Comment by Joohom** [comment]
我也遇到同样的问题在坚果pro2s 上，安卓8.1
