### ISSUE TITLE
本地端口1024以下的一律卡住

### ISSUE THREAD

**Issue by leozzyzheng** [shadowsocks/shadowsocks-android#279]
1024以上的本地端口都被Connection reset by peer
1024以下的本地端口点开启就无限停留在“连接中”的loading弹框那里。
查看Logcat没有任何输出。
请问这个是什么情况？

**Comment by leozzyzheng** [comment]
机器是android 5.0.2的，网络是公司的外网wifi，也是上不了google的那种

**Comment by mashiro94** [comment]
低于1024端口的ssserver需要以root身份运行才能监听端口。

**Comment by leozzyzheng** [comment]
@mashiro94 谢谢
