### ISSUE TITLE
插件不能完全关闭

### ISSUE THREAD

**Issue by elisaday** [shadowsocks/shadowsocks-android#2792]
Please read contributing guidelines. Thanks.

**Describe the bug**
Vivo X60手机，插件不能完全关闭

**To Reproduce**
1. 启动shadowsocks
2. 关闭shadowsocks
3. 等待几秒
4. 再次启动shadowsocks，报错：“无法连接到远程服务器：未知插件kcptun”

**Expected behavior**
可以正常启动

**Smartphone (please complete the following information):**
 - Android 11
 - Device: Vivo X60
 - Version: shadowsocks 5.2.5 kcptun 1.0.0

**Additional context**
如果在系统应用管理中，强制关闭kcptun。再次启动shadowsock可以成功。
猜测，关闭shadowsock的时候，kcptun插件并未完全退出。

**Comment by Mygod** [comment]
Fill out bug template.
