### ISSUE TITLE
Request for menu of REORDER BY DELAY and GROUP TAB

### ISSUE THREAD

**Issue by mmofaha** [shadowsocks/shadowsocks-android#2793]
I hope you can insert a new menu of REORDER BY DELAY for android version, so it can be easy for users to select the fastest server after speed test.
Bcoz currently we must scroll one by one which server is the fastest especially for android tv it not easy.

Second thing is can you added a GROUP MENU TAB for adding different configuration file so we can manage profile easly

TQ Sir your updates are greatly appreciated

from mmofaha

**Comment by Mygod** [comment]
dup #2215
