### ISSUE TITLE
红米1无法联网 日志显示too many open files

### ISSUE THREAD

**Issue by greatyao** [shadowsocks/shadowsocks-android#280]
--------- beginning of /dev/log/system
W/ADB_SERVICES(16322): create_local_service_socket() name=shell:am start -n com.github.shadowsocks/com.github.shadowsocks.Shadowsocks -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

W/ADB_SERVICES(16322): service_to_fd() name=shell:am start -n com.github.shadowsocks/com.github.shadowsocks.Shadowsocks -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

W/ADB_SERVICES(16322): LS(166): bound to 'shell:am start -n com.github.shadowsocks/com.github.shadowsocks.Shadowsocks -a android.intent.action.MAIN -c android.intent.category.LAUNCHER' via 21

I/ActivityManager(  669): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.github.shadowsocks/.Shadowsocks} from pid 30226

I/ActivityManager(  669): Start proc org.fuckgfw.ss for activity org.fuckgfw.ss/.Shadowsocks: pid=30317 uid=10125 gids={50125, 3003}

V/WindowManager(  669): Changing focus from null to Window{42236740 u0 org.fuckgfw.ss/org.fuckgfw.ss.Shadowsocks} Callers=com.android.server.wm.WindowManagerService.addWindow:2734 com.android.server.wm.Session.addToDisplay:163 android.view.IWindowSession$Stub.onTransact:111 com.android.server.wm.Session.onTransact:126 

I/WindowManager(  669): Gaining focus: Window{42236740 u0 org.fuckgfw.ss/org.fuckgfw.ss.Shadowsocks}

I/Shadowsocks(30317): reset

D/ActivityThread(30317): ACT-AM_ON_RESUME_CALLED ActivityRecord{420eaa68 token=android.os.BinderProxy@420ea2c8 {org.fuckgfw.ss/org.fuckgfw.ss.Shadowsocks}}

V/PhoneWindow(30317): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{4238cd28 org.fuckgfw.ss/org.fuckgfw.ss.Shadowsocks,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{42177a00 V.E..... R.....ID 0,0-0,0}

D/ActivityThread(30317): ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{420eaa68 token=android.os.BinderProxy@420ea2c8 {org.fuckgfw.ss/org.fuckgfw.ss.Shadowsocks}}

D/ActivityThread(30332): BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.github.shadowsocks flg=0x4000010 cmp=com.tencent.mobileqq/com.tencent.open.business.base.appreport.AppReportReceiver (has extras) } packageName=com.tencent.mobileqq resultCode=0 resultData=null resultExtras=null}

E/Shadowsocks(30317): unable to kill ss-local

E/Shadowsocks(30317): unable to kill ss-tunnel

E/Shadowsocks(30317): unable to kill pdnsd

E/Shadowsocks(30317): unable to kill tun2socks

E/Shadowsocks(30317): unable to kill redsocks

D/dalvikvm(30317): Trying to load lib /data/app-lib/com.github.shadowsocks-1/libsystem.so 0x420f04c0

D/dalvikvm(30317): Added shared lib /data/app-lib/com.github.shadowsocks-1/libsystem.so 0x420f04c0

I/Shadowsocks(30317): JNI_OnLoad

I/ActivityManager(  669): [AppLaunch] Displayed Displayed com.github.shadowsocks/.Shadowsocks: +2s330ms

D/ActivityManager(  669): AP_PROF:AppLaunch_LaunchTime:com.github.shadowsocks/.Shadowsocks:2330:11826431

D/ActivityManager(  669): ACT-windowsVisible(): ActivityRecord{4210eb28 u0 com.github.shadowsocks/.Shadowsocks t110}

V/ActivityManager(  669): ACT-Activity idle: Token{42dfba68 ActivityRecord{4210eb28 u0 com.github.shadowsocks/.Shadowsocks t110}}

V/WindowManager(  669): Changing focus from Window{42236740 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks EXITING} to Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:2839 com.android.server.wm.WindowManagerService.removeWindow:2778 com.android.server.wm.Session.remove:182 android.view.IWindowSession$Stub.onTransact:197 

I/WindowManager(  669): Gaining focus: Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}

I/WindowManager(  669): Losing focus: Window{42236740 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks EXITING}

I/Shadowsocks(30317): starting vpnservice now

V/WindowManager(  669): Changing focus from Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4411 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:2425 com.android.server.am.ActivityStackSupervisor.startActivityUncheckedLocked:2191 com.android.server.am.ActivityStackSupervisor.startActivityLocked:1510 

I/WindowManager(  669): Losing focus: Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}

D/ActivityThread(30317): ACT-AM_ON_PAUSE_CALLED ActivityRecord{420eaa68 token=android.os.BinderProxy@420ea2c8 {com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}}

V/WindowManager(  669): Changing focus from Window{42352f70 u0 com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog} to Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} Callers=com.android.server.wm.WindowManagerService.handleAppTransitionReadyLocked:9520 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10089 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:8981 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked:8923 

D/IPCThreadState(  669): [DN #5] BR_CLEAR_DEATH_NOTIFICATION_DONE cookie 0x651b8ad0

I/WindowManager(  669): Gaining focus: Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}

I/WindowManager(  669): Losing focus: Window{42352f70 u0 com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}

D/ActivityThread(30401): ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@420e1138

D/ActivityThread(30317): SEND_RESULT handled : 0 / ResultData{token=android.os.BinderProxy@420ea2c8 results[ResultInfo{who=null, request=1, result=-1, data=null}]}

D/ActivityThread(30317): ACT-AM_ON_RESUME_CALLED ActivityRecord{420eaa68 token=android.os.BinderProxy@420ea2c8 {com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}}

V/PhoneWindow(30317): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{4238cd28 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{42177a00 V.E..... R....... 0,0-720,1280}

D/ActivityThread(30317): ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@420ea2c8

D/ActivityManager(  669): ACT-windowsGone(): ActivityRecord{42e2f990 u0 com.android.vpndialogs/.ConfirmDialog t110 f}

D/ActivityThread(30317): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@42544a18 className=com.github.shadowsocks.ShadowVpnService packageName=com.github.shadowsocks intent=null}

I/ShadowVpnService(30317): onCreate()/data/data/com.github.shadowsocks/files

D/ActivityThread(30317): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@42544a18 className=com.github.shadowsocks.ShadowVpnService packageName=com.github.shadowsocks intent=null}

D/ActivityThread(30317): SVC-Calling onStartCommand: com.github.shadowsocks.ShadowVpnService@42548c08, flags=0, startId=1

I/ShadowVpnService(30317): onStartCommand()

D/ActivityThread(30317): SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@42544a18 startId=1 args=Intent { cmp=com.github.shadowsocks/.ShadowVpnService }}

I/GLConsumer(  144): [com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog](this:0xb728bf00,api:0) [void* android::GLConsumer::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&, const android::Rect&)]

V/WindowManager(  669): Changing focus from Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} to Window{4283aa78 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} Callers=com.android.server.wm.WindowManagerService.addWindow:2734 com.android.server.wm.Session.addToDisplay:163 android.view.IWindowSession$Stub.onTransact:111 com.android.server.wm.Session.onTransact:126 

I/WindowManager(  669): Gaining focus: Window{4283aa78 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}

I/GLConsumer(  144): [com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog](this:0xb728bf00,api:0) [void* android::GLConsumer::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&, const android::Rect&)]

V/ActivityManager(  669): ACT-Activity idle: Token{42dfba68 ActivityRecord{4210eb28 u0 com.github.shadowsocks/.Shadowsocks t110}}

D/ActivityThread(30401): ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@420e1138

I/GLConsumer(  144): [com.github.shadowsocks/com.github.shadowsocks.Shadowsocks](this:0xb72a9078,api:1) [void* android::GLConsumer::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&, const android::Rect&)]

I/GLConsumer(  144): [com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog](this:0xb728bf00,api:0) [void* android::GLConsumer::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&, const android::Rect&)]

D/libc    (  140): _resolv_cache_add: query:

D/libc    (  140): QUERY: RECURSIVE zjgnh.com (A)

D/libc    (  140): ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23859

D/libc    (  140): ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

D/libc    (  140): ;;	zjgnh.com, type = A, class = IN

D/libc    (  140): zjgnh.com.		29m59s IN A	103.37.84.60

D/libc    (  140): zjgnh.com.		29m59s IN A	121.133.252.136

D/libc    (  140): zjgnh.com.		29m59s IN A	121.133.252.153

D/libc    (  140): 

D/libc    (  140): answer:

D/libc    (  140): 5d 33 81 80 00 01 00 03 00 00 00 00 05 7a 6a 67  ]3...........zjg

D/libc    (  140): 6e 68 03 63 6f 6d 00 00 01 00 01 c0 0c 00 01 00  nh.com..........

D/libc    (  140): 01 00 00 07 07 00 04 67 25 54 3c c0 0c 00 01 00  .......g%T<.....

D/libc    (  140): 01 00 00 07 07 00 04 79 85 fc 88 c0 0c 00 01 00  .......y........

D/libc    (  140): 01 00 00 07 07 00 04 79 85 fc 99                 .......y...

D/libc    (  140): TTL = 1799

D/libc    (  140): _cache_add_p: entry 38 added (count=36)

D/libc    (  140): MRU LIST (36):  38 37 20 36 35 34 23 31 33 32 30 29 28 22 27 26 25 24 21 19 18 15 14 13 12 11 9 10 8 7 6 5 4 3 2 1

D/libc-netbsd(  140): res_queryN name = zjgnh.com succeed

I/ShadowVpnService(30317): ss-local=/data/data/com.github.shadowsocks/ss-local -u -b 127.0.0.1 -t 600 -c /data/data/com.github.shadowsocks/ss-local-vpn.conf -f /data/data/com.github.shadowsocks/ss-local-vpn.pid

D/shadowsocks(30426): listening at 127.0.0.1:1080

D/shadowsocks(30426): udprelay enabled

I/ShadowVpnService(30317): pdnsd=/data/data/com.github.shadowsocks/pdnsd -c /data/data/com.github.shadowsocks/pdnsd-vpn.conf

I/ShadowVpnService(30317): ss-tunnel=/data/data/com.github.shadowsocks/ss-tunnel -u -t 10 -b 127.0.0.1 -l 8163 -L 8.8.8.8:53 -c /data/data/com.github.shadowsocks/ss-tunnel-vpn.conf  -f /data/data/com.github.shadowsocks/ss-tunnel-vpn.pid

D/shadowsocks(30435): initialize ciphers... rc4

D/shadowsocks(30435): listening at 127.0.0.1:8163

D/shadowsocks(30435): udprelay enabled

I/Netd    (  140): Get netlink event, ifname: tun0 action: 1

D/SocketClient(  140): SocketClient msg = Iface added tun0

D/SocketClient(  140): SocketClient sendDatalocked done: 600 Iface added tun0

D/NetdConnector(  669): RCV <- {600 Iface added tun0}

D/NetworkManagementService(  669): onEvent:600 Iface added tun0:4

D/wpa_supplicant(18442): nl80211: Ignore event for foreign ifindex 17

I/Tethering(  669): interfaceAdded tun0

D/NetlinkEvent(  140): clear RA flag done

I/NetlinkEvent(  140): clear 0 IPv6 DNS for tun0

I/Netd    (  140): Get netlink event, ifname: tun0 action: 5

D/SocketClient(  140): SocketClient msg = Iface linkstate tun0 down

D/SocketClient(  140): SocketClient sendDatalocked done: 600 Iface linkstate tun0 down

D/Tethering(  669): tun0 is not a tetherable iface, ignoring

D/NetdConnector(  669): RCV <- {600 Iface linkstate tun0 down}

D/wpa_supplicant(18442): nl80211: Ignore event for foreign ifindex 17

D/NetworkManagementService(  669): onEvent:600 Iface linkstate tun0 down:5

I/Tethering(  669): interfaceLinkStateChanged tun0, false

I/Tethering(  669): interfaceStatusChanged tun0, false

I/Netd    (  140): Get netlink event, ifname: tun0 action: 4

D/SocketClient(  140): SocketClient msg = Iface linkstate tun0 up

D/SocketClient(  140): SocketClient sendDatalocked done: 600 Iface linkstate tun0 up

D/NetdConnector(  669): RCV <- {600 Iface linkstate tun0 up}

D/NetworkManagementService(  669): onEvent:600 Iface linkstate tun0 up:5

I/Tethering(  669): interfaceLinkStateChanged tun0, true

I/Tethering(  669): interfaceStatusChanged tun0, true

I/ANRManager(  669): updateProcessStats

D/Vpn     (  669): setting state=CONNECTING, reason=establish

I/Netd    (  140): Get netlink event, ifname: tun0 action: 6

D/SocketClient(  140): SocketClient msg = Address updated 26.26.26.1/32 tun0 128 0

D/SocketClient(  140): SocketClient sendDatalocked done: 614 Address updated 26.26.26.1/32 tun0 128 0

I/Netd    (  140): Get netlink event, ifname: tun0 action: 7

D/SocketClient(  140): SocketClient msg = Address removed 26.26.26.1/32 tun0 128 0

D/SocketClient(  140): SocketClient sendDatalocked done: 614 Address removed 26.26.26.1/32 tun0 128 0

D/NetdConnector(  669): RCV <- {614 Address updated 26.26.26.1/32 tun0 128 0}

D/NetdConnector(  669): RCV <- {614 Address removed 26.26.26.1/32 tun0 128 0}

D/NetworkManagementService(  669): onEvent:614 Address updated 26.26.26.1/32 tun0 128 0:7

D/NetworkManagementService(  669): onEvent:614 Address removed 26.26.26.1/32 tun0 128 0:7

I/Netd    (  140): Get netlink event, ifname: tun0 action: 6

D/SocketClient(  140): SocketClient msg = Address updated 26.26.26.1/24 tun0 128 0

D/SocketClient(  140): SocketClient sendDatalocked done: 614 Address updated 26.26.26.1/24 tun0 128 0

D/NetdConnector(  669): RCV <- {614 Address updated 26.26.26.1/24 tun0 128 0}

D/NetworkManagementService(  669): onEvent:614 Address updated 26.26.26.1/24 tun0 128 0:7

D/VpnJni  (  669): Address added on tun0: 26.26.26.1/24

D/IPCThreadState( 1014): [DN #5] BR_CLEAR_DEATH_NOTIFICATION_DONE cookie 0x61c16ca8

D/IPCThreadState(  669): [DN #5] BR_CLEAR_DEATH_NOTIFICATION_DONE cookie 0x654f2d28

D/NetdConnector(  669): SND -> {584 interface fwmark rule add tun0}

I/FrameworkListener(  140): onDataAvailable get 35 bytes 

D/FrameworkListener(  140): dispatchCommand data = (584 interface fwmark rule add tun0)

D/ActivityThread(30317): SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@42544a18 intent=Intent { act=android.net.VpnService cmp=com.github.shadowsocks/.ShadowVpnService }}

I/ShadowVpnService(30317): tun2socks=/data/data/com.github.shadowsocks/tun2socks --netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:1080 --tunfd 88 --tunmtu 1500 --loglevel 3 --pid /data/data/com.github.shadowsocks/tun2socks-vpn.pid --dnsgw 26.26.26.1:8153

V/WindowManager(  669): Changing focus from Window{4283aa78 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks EXITING} to Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} Callers=com.android.server.wm.WindowManagerService.removeWindowLocked:2839 com.android.server.wm.WindowManagerService.removeWindow:2778 com.android.server.wm.Session.remove:182 android.view.IWindowSession$Stub.onTransact:197 

D/ActivityThread(30317): ACT-AM_ON_PAUSE_CALLED ActivityRecord{420eaa68 token=android.os.BinderProxy@420ea2c8 {com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}}

V/WindowManager(  669): Changing focus from Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4411 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:2425 com.android.server.am.ActivityStack.completeResumeLocked:1040 com.android.server.am.ActivityStack.resumeTopActivityLocked:1816 

I/WindowManager(  669): Losing focus: Window{42271628 u0 com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}

E/shadowsocks(30426): accept: Too many open files

E/shadowsocks(30426): accept: Too many open files

D/OpenGLRenderer(  948): prepareDirty (0.00, 0.00, 156.00, 180.00) opaque 0 <0x61aaa5f0>

E/shadowsocks(30426): accept: Too many open files

E/shadowsocks(30426): accept: Too many open files

E/shadowsocks(30426): accept: Too many open files

**Comment by madeye** [comment]
It's a bug of Hongmi, not shadowsocks.
