### ISSUE TITLE
It's hard to share shadowsocks config from shadowsocks-android

### ISSUE THREAD

**Issue by vmlinz** [shadowsocks/shadowsocks-android#282]
Scenario: 

User A tries to share the shadowsocks account he is using to User B, but for now, shadowsocks-android provides no easy way to share the profile.

Suggestion: 

1.Using a barcode generator to generate a barcode which contains the config
2.Clip the config to clipboard and users can share via text.

**Comment by madeye** [comment]
No plan for this.
