### ISSUE TITLE
不支持ipv6格式的dns，不能优先选择使用ipv6

### ISSUE THREAD

**Issue by kckm** [shadowsocks/shadowsocks-android#2820]
**Describe the bug**
第一个问题：dns地址使用ipv6的dns，例如谷歌的公共dns：2001:4860:4860::8888，将无法解析域名。
第二个问题：无法优先选择使用ipv6，双栈网站依旧会选择使用ipv4。
服务端是shandowsocks-libev-3.3.5
ss-server -s ::0 -p xxxx -m rc4-md5 -k xxxx -6
在windows平台使用shadowsocks-windows是优先解析为ipv6的。

**To Reproduce**

**Expected behavior**
可以使用ipv6格式的dns，以及应当优先选择ipv6解析。

**Screenshots**

**Smartphone (please complete the following information):**
 - Android11

**Comment by triaqu** [comment]
一台纯IPv6的VPS，服务器端shadowsocks-rust，用电脑连接可以正常使用，手机端就无法使用，不知是不是同样问题造成的。

**Comment by dev4u** [comment]
dns服务器地址不一定要v6的才能返回对应的地址，只要发送AAAA过去，就可以得到v6地址的。同理，v6的dns也是可以返回v4的地址。
你需要的是开启ss客户端的ipv6选项。
至于没有优先返回v6地址，这个跟客户端关系不是太大。请自行确认远端的程序有支持ipv6 first参数，并正确传入程序中被处理。忘了libev有没支持这个参数，建议升级改用rust的版本试试。

**Comment by kckm** [comment]
> dns服务器地址不一定要v6的才能返回对应的地址，只要发送AAAA过去，就可以得到v6地址的。同理，v6的dns也是可以返回v4的地址。 你需要的是开启ss客户端的ipv6选项。 至于没有优先返回v6地址，这个跟客户端关系不是太大。请自行确认远端的程序有支持ipv6 first参数，并正确传入程序中被处理。忘了libev有没支持这个参数，建议升级改用rust的版本试试。

安卓客户端是vpn需要设定远程dns，填入ipv6地址的dns是无法解析的；服务端是优先解析为ipv6，在windows客户端上正常。

**Comment by kckm** [comment]
> 一台纯IPv6的VPS，服务器端shadowsocks-rust，用电脑连接可以正常使用，手机端就无法使用，不知是不是同样问题造成的。

因为它不支持设置ipv6格式的dns地址，所以单ipv6网络应该是没办法去解析dns地址的。
