### ISSUE TITLE
在手机上看油管2160P的视频，经常会死掉

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-android#2824]
Please read contributing guidelines. Thanks.

**Describe the bug**
我在油管上看2160p的视频，经常会ss自己死掉。重启ss后继续看，过不了多久，ss还是会退出。
看1080p以下是没问题的。
测试的链接：
https://youtu.be/28CAmnr3yUA

**To Reproduce**
1. 用youtube app浏览2160p的视频

**Expected behavior**
正常看完视频，app不会中途自己死掉。

**Screenshots**

**Smartphone (please complete the following information):**
![Screenshot_2021-11-04-02-53-15-697_com.android.settings.png](https://user-images.githubusercontent.com/1210047/140174494-8181cf32-cf5d-4a9b-9951-163e2012810c.png)

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 1.0.0.1
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
用1080p来看视频，是完全不会死掉。
使用的环境，网速不成问题，能达到6、7MB/s的速度。
分不分应用代理，结果是一样的。
使用的rust分支版本是master。
开启了rust的-vvv参数输出日志。

**Comment by dev4u** [comment]
当时看油管时，网络请求是udp协议。
![Screenshot_2021-11-04-03-07-05-290_com.vanced.android.youtube.png](https://user-images.githubusercontent.com/1210047/140176780-023ee72c-f662-4ef6-b574-8fa735badc16.png)

**Comment by Mygod** [comment]
🤔 If you enabled `-vvv`, it might overwhelm the logging. Try disabling that and see if it fixes the issue.

**Comment by dev4u** [comment]
> 🤔 If you enabled `-vvv`, it might overwhelm the logging. Try disabling that and see if it fixes the issue.

好的。但是我要过两天才能测试你的方法。

**Comment by dev4u** [comment]
@Mygod 果然如你估计得那样，把rust的日志输出关掉，ss不再无端退出。
