### ISSUE TITLE
Can't access 127.0.0.1 or 0.0.0.0 of remote server

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-android#2828]
Please read contributing guidelines. Thanks.

**Describe the bug**
I have several services running locally on a server where I'm running the proxy. If I connect to it from my Macbook, I can access all the services on 127.0.0.1, but I can not do the same if I run this client

**To Reproduce**
1. Run local services on remote server
2. Connect to it by this client
3. Try to access 0.0.0.0:$PORT, where $PORT is where a service is running
4. You can't connect to it

**Expected behavior**
I can connect to the service

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 11
 - Device: Pixel 5
 - Version: 5.1.4
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 0.0.0.0
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by Mygod** [comment]
Expected behavior.

**Comment by Mygod** [comment]
You can try to use the server's local IP address.

**Comment by DUOLabs333** [comment]
Why would that work? The service is running locally.
