### ISSUE TITLE
Question: proxifying other UDP-intensive applications (per-app proxy mode)

### ISSUE THREAD

**Issue by lepasserby** [shadowsocks/shadowsocks-android#283]
Hello!
Since shadowsocks for android already can handle UDP, would it be hard to implement a function to proxify other apps that make much use of UDP, specifically VoIP apps?

I've tried proxifying Callcentric VOIP client (forward UDP is checked), but it breaks completely (Signalling works fine, but RTP breaks)

**Comment by madeye** [comment]
For intensive UDP forwarding, I suggest to use VPN instead. ShadowVPN is recommend, if you are looking for a lightweight solution.

**Comment by lepasserby** [comment]
Well, there ain't no shadowVPN version for Android as far as I can see.

Also, on a flaky connection (where a "naked" VOIP is "bearable, but barely) VPN+VOIP perfomance is pretty damn horrible (at least for VPNs I've tested on my android)

Okay, one more question if you don't mind:
Does shadowsocks for android use socks2tun's UDP shtick ?
 (if it does, I could maybe use something like iptables to route all UDP destinated towards a particular port through Shadowsocks (since the TCP part of SIP seems to be handled by Shadowsocks just fine as it is)

**Comment by madeye** [comment]
1. It's possible to do static port forwarding in this case, like what we're doing for DNS.
2. https://play.google.com/store/apps/details?id=clowwindy.shadowvpn
3. I just tested Hangouts which is also using RTP. And it works pretty well when UDP forwarding enabled.

**Comment by lepasserby** [comment]
I'm probably just fubaring the port forward  
No cigar so far.
Looks like my US-phone calls will have to go naked for the time being (I am still getting pretty horrible perfomance of voice with the ShadowVPN)

Could it be a SELinux issue ?
Speaking of which, I notice that you do have a selinux/UDP/DNS related ticket here.

Is there a way to modify selinux policy settings (phone's rooted) to make Shadowsocks's life easier (ideally without turning Selinux to permissive mode) ?

P.S.:
Hangouts is indeed working (though I doubt that RTP is going through Shadowsocks)
