### ISSUE TITLE
Android 12上无法关闭vpn

### ISSUE THREAD

**Issue by cucxbd** [shadowsocks/shadowsocks-android#2835]
使用miui系统，android 12版本，打卡vpn之后无法关闭，系统上方的vpn图标还在。清除后台也无法关闭

**Comment by Mygod** [comment]
Seems like a MIUI issue. Report to them instead.

**Comment by gp-alex-chen** [comment]
并不是 miui 系统原因, 使用google pixel 的原生系统也有同样情况
真正原因是android12以后 java 的 process.destroy 方法无法触发 tun2socks 的信号
想关闭就直接找到 tun2socks 的pid, 调用系统的 OS.kill 方法就行
