### ISSUE TITLE
VPN occasionally disconnects

### ISSUE THREAD

**Issue by anyuta1166** [shadowsocks/shadowsocks-android#2846]
**Describe the bug**
VPN occasionally disconnects

**To Reproduce**
1. Just enable the VPN and after some time it occasionally disconnects

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 10, MIUI 12.0.6
 - Device: Xiaomi Redmi 9T
 - Version: 5.2.6
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I've recently bought a new phone and found that Shadowsocks doesn't work as expected on it. I enable the VPN but after some time it occasionally disconnects.

I've researched the logcat and found that MIUI occasionally kills all background services, usually during the night time, despite that background usage is set to unrestricted in application settings.

```
01-04 23:46:14.174 W/PK      ( 5714): AutoLockOffClean in night 
01-04 23:46:14.175 I/ProcessManager( 1699): Kill reason AutoLockOffClean from pid=5714
01-04 23:46:14.177 I/ProcessManager( 1699): AutoLockOffClean: kill com.github.shadowsocks:bg Adj=100 State=5
01-04 23:46:14.177 I/ActivityManager( 1699): Killing 27121:com.github.shadowsocks:bg/u0a272 (adj 100): AutoLockOffClean
01-04 23:46:14.570 I/Zygote  (  685): Process 27121 exited due to signal 9 (Killed)
01-04 23:46:14.599 D/ProcessManager( 1699): skip restart com.github.shadowsocks:bg
01-04 23:46:14.599 I/ProcessManager( 1699): remove no clear notification:StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10272: Notification(channel=service-vpn pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b category=service vis=PRIVATE))
01-04 23:46:14.600 W/ActivityManager( 1699): Scheduling restart of crashed service com.github.shadowsocks/.bg.VpnService in 90695ms
01-04 23:46:14.732 D/PowerKeeper.Vpn( 5714): removed vpn iface: tun0
01-04 23:46:14.732 D/PowerKeeper.Vpn( 5714): removed vpn: 10272
01-04 23:46:14.735 D/ConnectivityService( 1699): NetworkAgentInfo [VPN () - 112] EVENT_NETWORK_INFO_CHANGED, going from CONNECTED to DISCONNECTED
01-04 23:46:14.735 I/AppActiveChecker( 5714): uid:10272change to inactive
01-04 23:46:14.735 I/ActiveStateController( 5714): Vpn disconnect, uid is 10272
01-04 23:46:14.738 I/PowerKeeperConfigureManager( 5714): Vpn disconnect, uid is 10272
01-04 23:46:14.739 D/ConnectivityService( 1699): NetworkAgentInfo [VPN () - 112] got DISCONNECTED, was satisfying 1
```

It seems that this is a known MIUI feature and nothing can be done with this behavior. But another applications seems to survive through this. I guess that their workaround is to periodically check if the background service is alive and relaunch it if needed. Is it possible to add the same workaround to Shadowsocks? I guess it should be possible as there is already the auto-connect on boot feature.

**Comment by dev4u** [comment]
试试设置允许应用自启动。

**Comment by anyuta1166** [comment]
> 试试设置允许应用自启动。

I didn't mention it, but I already enabled Autostart in application settings too as well as setting the background usage to unrestricted and disabling battery optimization.
The difference is that without autostart, Shadowsocks is not automatically launched after reboot. But that setting doesn't affect periodic background service killing.

**Comment by anyuta1166** [comment]
It seems that I've found an undocumented workaround.

**Comment by foi** [comment]
@anyuta1166 how you solved this issue?

**Comment by foi** [comment]
@anyuta1166  thanks!
