### ISSUE TITLE
Material Design 风格化

### ISSUE THREAD

**Issue by fython** [shadowsocks/shadowsocks-android#285]
希望 Shadowsocks Android 版客户端能采用 Material Design 风格，
现在很多 Android 应用都已经采用了这个风格，而 Shadowsocks Android 版客户端还是 Android Design 的 Holo 主题。

（PS：之前想过贡献代码但是没接触过 Scala （感觉和 Java 不是很大）而且习惯了用 Android Studio IDE 环境，本人高中党水平不高时间有限，最后还是放弃了QAQ）

**Comment by madeye** [comment]
短期内不会跟进，有兴趣的话可以提交 Pull Request。

**Comment by madeye** [comment]
Fixed via ef2ff23cd01a5efa11f57378c77d259909ce3e2c
