### ISSUE TITLE
谷歌的Pixel 3 XL在android 12的系统上无法关闭vpnService

### ISSUE THREAD

**Issue by Jeremyzwc** [shadowsocks/shadowsocks-android#2859]
Pixel 3 XL更新到Android 12后，无法在应用中断开Vpn服务，只能再设置中的vpn中取消保存vpn

**Comment by frinck** [comment]
i have the same issue. whatever using 3.4 or the latested

**Comment by feiaiafang** [comment]
same issue,can't close vpn service,must kill process in setup config.
Samsung S20 Ultra,
android 12
shadowsocks 3.5.4

**Comment by frinck** [comment]
> same issue,can't close vpn service,must kill process in setup config.
> Samsung S20 Ultra,
> android 12
> shadowsocks 3.5.4

does it work normal if you use the latest version ?

**Comment by feiaiafang** [comment]
> 

Function is ok，just can't close it in top shortcut.

**Comment by Mygod** [comment]
What's the security patch?

**Comment by frinck** [comment]
MDF v3.2 Release 1 
WLAN v1.0 Release 2 
VPN Client v2.2 Release 1.0 
ASKS v4.5 Release 20211027 
ADP v3.0 Release 20191001 
FIPS BoringSSL v1.6 
FIPS SKC v2.2 FIPS SCrypto v2.5 
SMR Jan -2022 Release 1

se:
Enforcing SEPF _ SM - G9910_12_0001 Tue Jan 1115:57:162022
