### ISSUE TITLE
Importing SSR failed 导入SSR失败

### ISSUE THREAD

**Issue by githubnimabi** [shadowsocks/shadowsocks-android#2866]
Android system version：Android 7.1.1、Android 10    安卓系统版本：安卓7.1和安卓10
APK Version：shadowsocks-arm64-v8a-v5.2.6.apk

I installed shadowsocks-arm64-v8a-v5.2.6.apk on my Android 7.1.1 and Android 10 phone，I import SSR from clipboard but it says import failed，My SSR works fine on Windows(ShadowsocksR-win-4.8.0)What should I do to solve the problem? If you need to test, I can provide my SSR，Thank you！

我在Android7和Android10手机上安装了5.2.6版本的Apk，从剪贴板导入，都显示导入失败，我的SSR在电脑上是可以正常使用的，不知道为什么在手机不能导入，而且也不能使用。如果你需要测试，我可以提供我的SSR，烦请告知我如何解决这个问题。万分感谢
![Screenshot_20220314-134902](https://user-images.githubusercontent.com/12745231/158132114-14432d19-95b0-4755-9fc7-fa696459c399.jpg)

**Comment by AaronChen0** [comment]
This is a shadowsocks project, not for shadowsocksR. You can use other android apps like [ClashForAndroid](https://github.com/Kr328/ClashForAndroid) for your purpose.

**Comment by githubnimabi** [comment]
ok，thankyou，but clash for Android does not support the SSR protocol
