### ISSUE TITLE
Bug in interface

### ISSUE THREAD

**Issue by devmitrandir** [shadowsocks/shadowsocks-android#2870]
Bug in interface on screen "Apps VPN mode" in Russia language. I don't know if there is a problem in other languages

**To Reproduce**
1. Go to 'Profile config'
2. Click on 'Apps VPN mode'

**Expected behavior**
I was expecting a normal radio button layout

**Screenshots**
![image](https://user-images.githubusercontent.com/59085306/160249187-33e1f7bb-408f-4908-8e8e-b7dd3f160ace.png)

**Smartphone:**
 - Android version: 11, realme UI 2.0(RMX2155_11_C.16)
 - Device: realme 7(RMX2155)
 - App version: 5.2.6 (did not use other versions)

**Comment by VladWinner** [comment]
Possibly fixed in https://github.com/shadowsocks/shadowsocks-android/pull/2867#issuecomment-1079631929

**Comment by VladWinner** [comment]
Fixed in v5.3.0-preview
