### ISSUE TITLE
Odd behavior - all networking down if Shadowsocks is misconfigured (system proxy disabled)

### ISSUE THREAD

**Issue by lepasserby** [shadowsocks/shadowsocks-android#289]
What it says on the can.

Steps to reproduce:

Configure a working shadowsocks on android.

Disable system-wide proxy.
Disable UDP forwarding (for experimental clarity)

Test that system-wide proxy is not working and that per-app proxification is working (have 2 browsers installed, proxify only one of them, check IP on browser 1 and browser 2)

Now screw up the shadowsocks config (change server port number and IP, for instance)

Re-enable shadowsocks.

No networking works unless shadowsocks config is fixed or shadowsocks is stopped.

Expected behavior:
Only the proxified app should have its networking broken.

**Comment by madeye** [comment]
It's expected that shadowsocks forwards all DNS requests to the remote server all the time.

**Comment by lepasserby** [comment]
Okay, now I am moderately confused. 
What's the purpose of the "forward UDP traffic" option then (I assumed it was for DNS only)?
