### ISSUE TITLE
Personal hotspot isn't working when shadowsocks is on

### ISSUE THREAD

**Issue by dallascao** [shadowsocks/shadowsocks-android#29]
I can not open any sites on the computer when connecting to my phone, with my phone being the hotspot. 

Internet still works on the phone.

**Comment by hydrandt** [comment]
2018: Use "Apps VPN mode". Either you can select which apps' traffic will go through the vpn, or you can use the "Bypass Mode", where you select which apps' traffic will not go through the vpn. In both cases tethering will work.
