### ISSUE TITLE
Disconnect / Pause button in notification

### ISSUE THREAD

**Issue by anton0kurilov** [shadowsocks/shadowsocks-android#2903]
Some VPN applications have buttons to disable or pause an active connection directly in notifications (See screenshot). It would be great if you could add this to your app.

![nord](https://user-images.githubusercontent.com/8565767/175861974-edd5d6f6-95c3-445a-89d6-04de54ad1e3d.png)

**Comment by Mygod** [comment]
Use quick setting tile.
