### ISSUE TITLE
Unable to resolve host "cp.cloudflare.com": No address associated with hostname.

### ISSUE THREAD

**Issue by NightFlexer** [shadowsocks/shadowsocks-android#2908]
I successfully connect the client to the server, but I get an error in the browser: ERR_NAME_NOT _RESOLVED.
In the shadowsocks-android settings, I manually specified DNS: 8.8.8.8 and 1.1.1.1
This did not solve the problem with dns.
shadowsocks-android version: 5.2.6
Android version: 7.1.2

**Comment by NightFlexer** [comment]
If I click the button: "Connected, click to test the connection." I am getting an error: cp.cloudflare.com has no address

**Comment by NightFlexer** [comment]
My mistake, config problems

**Comment by m-ocean-it** [comment]
> My mistake, config problems

How did you fix it? What was the culprit?

**Comment by Crazywhat** [comment]
> My mistake, config problems

How did you fix it? I have the same problem.

**Comment by vrzdrb** [comment]
It worked for me to change the server address to 0.0.0.0 in the server config.  However, with the v2ray plugin the error is returned.

shadowsocks-libev Debian 11

**Comment by amirhs712** [comment]
Still the same problem on android 7, connection succeeded on other multiple devices (linux, mac, windows, android 11, android 10)

**Comment by m-ocean-it** [comment]
@Crazywhat:
> > My mistake, config problems
> 
> How did you fix it? I have the same problem.

changing the cipher did it for me

**Comment by teamclouday** [comment]
In my case the firewall isn't configured properly so the port isn't open. Need to use `ufw allow` to open the port

**Comment by dablelv** [comment]
I encountered the same problem. Suddenly, it ss on android report the error info.

So who can tell me how to fix this problem, thx first.

**Comment by gewalttat** [comment]
same, android tv client
