### ISSUE TITLE
Sorry to bother again, but I am still confused about port forwarding (and "modes" too, now)

### ISSUE THREAD

**Issue by lepasserby** [shadowsocks/shadowsocks-android#293]
Hello.
Sorry to bother, but google group seems to be fairly low-activity, and I seem to be... insufficiently smart to figure it out on my own.

Basically, I've set up my own TURN server (listens on port 3478), and narrowed-down UDP ports available to Groundwire (I use groundwire on my android) for establishing RTP connections (range 60005-65525).

Without Shadowsocks, everything works fine, TURN server is contacted and calls are established "as intended".

When groundwire is proxified (even when UDP-forwarding is on), something breaks and apparently the outgoing RTP streams still originate from the phone, not going through Shadowsocks's tunnel ("forward UDP option is ON)

It seems to me that given that  I
1) know the rather unique destination port of TURN ( 3478 )

2) know the port range Groundwire app is allowed to use for its RTP / RTCP business ( 60005-65525 )

I should be, theoretically, able to use iptables to force all traffic (UDP, TCP, anything) that is either *a)* directed towards a remote port 3478 or *b)* originates from range 60005-65525 to go through Shadowsocks.

However, I fail :( (Not smart enough, lol)

Google does not appear to be very helpful (all I managed to find was [this dialogue](https://twitter.com/linusyang/status/445111853744549888) you had on Twitter a year ago )

Would you kindly help me out ?

P.S.:
I am also confused as to what is "Nat-mode" and "VPN-mode" for Shadowsocks-android, since no such options are explicitly present  (I installed it from Play store)

**Comment by madeye** [comment]
Without ROOT permission, shadowsocks works in VPN mode. If ROOT granted, shadowsocks works in NAT mode.

To understand the details, please read the code.

**Comment by lepasserby** [comment]
I am afraid I am a simpleton user, not a programmer, so sorry if I am being bothersome.

Phone is rooted, and Shadowsocks has permission.

I suspect I'll have to figure out iptables part of the question myself...
