### ISSUE TITLE
Selective tunneling of programs

### ISSUE THREAD

**Issue by mickhaorex** [shadowsocks/shadowsocks-android#2940]
I use it on android tv. Please make it possible to selectively tunnel applications. Or vice versa, the choice of applications that will not tunnel. Since I use your application only for watching TV (for the Internet TV program), other programs that work with the local network (DLNA, Samba) cannot connect to the local network. I use it in VPN mode, since there is no way to configure work through a proxy in the TV viewing program. 
Thank you so much for this app, for AndroidTV it is the most convenient, with a small size!

**Comment by zyxmon** [comment]
I also do vote for this enhancement.

**Comment by Mygod** [comment]
Install mobile version of this app (which has partial TV support). You can export/import between two versions.

**Comment by zyxmon** [comment]
I do use mobile app on AndroidTV. The support is partial - virtual mouse is needed on FireOS (AndroidTV fork by Amazon)!

**Comment by Mygod** [comment]
You can configure in mobile version and export to TV version.

**Comment by zyxmon** [comment]
This solution does not work - export says that "No application supporting this function found". I have made reverse translation - to this is not the exact English message.

**Comment by zyxmon** [comment]
Installin MixPlorer help to solv the problem. No other file managers worked (((
