### ISSUE TITLE
The report you linked as a reference contradicts your point. Shadowsocks servers **need** protection against replay attacks. The current bloomfilter-based implementation might not be good enough (limited capacity, no persistency, etc). But removing the protection is not the solution. We need protocol changes to achieve full protection.

### ISSUE THREAD

**Issue by 0987cronaker** [shadowsocks/shadowsocks-android#2956]
The report you linked as a reference contradicts your point. Shadowsocks servers **need** protection against replay attacks. The current bloomfilter-based implementation might not be good enough (limited capacity, no persistency, etc). But removing the protection is not the solution. We need protocol changes to achieve full protection.

Since you have consistently given downvotes/objections to proposals of any change (shadowsocks/shadowsocks-org#177, shadowsocks/shadowsocks-org#178, shadowsocks/shadowsocks-org#183 (comments)), I'm giving your PR a 👎.

_Originally posted by @database64128 in https://github.com/shadowsocks/shadowsocks-rust/issues/556#issuecomment-864387619_

**Comment by database64128** [comment]
Why did you take my previous comment out of context and re-post it here? This contains outdated opinions/information and should be deleted.
