### ISSUE TITLE
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:cargoBuildArm64'

### ISSUE THREAD

**Issue by kothanzaw** [shadowsocks/shadowsocks-android#2963]
Please read contributing guidelines. Thanks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by kothanzaw** [comment]
I have downloaded the repo with --recurse-submodules
and i already update with rustup. 
when i try to build with android studio , it fails.
i am on ubuntu 22.04
what is the problem  some body help , please.
![Screenshot from 2022-12-08 09-55-37](https://user-images.githubusercontent.com/12668371/206349281-82c4d722-725e-4fd3-92f4-5a2af2fd9a6c.png)

**Comment by dev4u** [comment]
`rustup default nightly`
`rustup update`
