### ISSUE TITLE
服务端升级到shadowsocks-rust v1.15.0之后，客户端shadowsocks-android v5.3.1-preview不能使用

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-android#2966]
ss用的是chacha20-ietf-poly1305，sip003是cloak，没敢裸连测试。其他不变，之前服务端版本v1.14.3没有使用问题。

另外目前服务端v1.15.0，客户端shadowsocks-rust v1.15.0-alpha.9，其它不变，使用是正常的

**Comment by madeye** [comment]
It should be a bug in the latest shadowsocks-rust. I saw a segfault of ss-rust on the server after enabling plugin. @zonyitoo

**Comment by zonyitoo** [comment]
That was strange. How can I reproduce? Could you provide more detail about `sslocal`? @qwerttvv 

> I saw a segfault of ss-rust on the server after enabling plugin.

Hmm, please provide more detail about `ssserver`, too.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/actions/runs/3717954160/jobs/6305787076

It probably related to some bugs introduced from the latest nightly Rust. Please change toolchain to stable Rust. shadowsocks-rust is able to be compiled with stable Rust since 1.64.

**Comment by zonyitoo** [comment]
@dev4u Please remove features `armv8 neon` and use stable Rust toolchain.

**Comment by Mygod** [comment]
> It probably related to some bugs introduced from the latest nightly Rust. Please change toolchain to stable Rust. shadowsocks-rust is able to be compiled with stable Rust since 1.64.

It's about time. 👍

**Comment by Mygod** [comment]
@zonyitoo So `armv8 neon` is removed for now? Do you have a link to the rust stabilization timeline of these features? Not sure why they need to take such a long time to stabilize such a trivial feature.

**Comment by zonyitoo** [comment]
Tracking Issue: https://github.com/rust-lang/stdarch/pull/1266

Release Note: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1590-2022-02-24

**Comment by Mygod** [comment]
So they would be enabled already? And there had been no reason to build shadowsocks-rust on nightly since this February?

**Comment by Mygod** [comment]
Shouldn't the `neon` flag be kept/enabled then?

**Comment by zonyitoo** [comment]
> Shouldn't the `neon` flag be kept/enabled then?

Yes, I think we should. NEON is required for standard ARMv8 implementations: https://developer.arm.com/documentation/den0024/a/AArch64-Floating-point-and-NEON .

But why they still kept the `neon` feature? I should open an issue.

**Comment by zonyitoo** [comment]
Well, they know: https://github.com/RustCrypto/stream-ciphers/pull/310 . Maybe the only reason is for keeping MSRV unchanged in the current version.

**Comment by Mygod** [comment]
Great. So let's add it (back) to shadowsocks-crypto?

**Comment by zonyitoo** [comment]
`chacha20` with `neon` didn't released yet.

**Comment by Mygod** [comment]
Maybe we could send them a friendly reminder. :)
