### ISSUE TITLE
Poor performance on my tablet and smartphone

### ISSUE THREAD

**Issue by HyperBioGhost** [shadowsocks/shadowsocks-android#297]
Got it work on Nexus 9 and Sony Z1 compact.
Nexus 9: Android 5.1.1, running dirty unicorn official v9.3 with Elemental X kernel.
Sony Z1 compact: Android 4.4.4. Build number 14.4.A.0.157.
In same wifi environment, the computer is fine. However, Google play app downloading speed is 2 ~ 27 KB/s on Nexus 9 and Z1 compact.
Tried to change route to all/by pass lan/by pass lan and China, not effecting.
Any idea how to fix it?

**Comment by madeye** [comment]
Try to enable UDP forwarding.
