### ISSUE TITLE
libsslocal exits too fast (exit code : 134)

### ISSUE THREAD

**Issue by aquaman1984** [shadowsocks/shadowsocks-android#2995]
I am using version 5.3.2 and when I connect to shadowsocks 2022 I get the error I posted in the title.

**Comment by madeye** [comment]
Is there any known issue of aead-2022-cipher feature on ARM? @zonyitoo

**Comment by zonyitoo** [comment]
Nope. I run it everyday on my ARM router (aarch64) with various encryption methods, including aead, aead-2022, and didn't see any problems like this.

**Comment by madeye** [comment]
```
02-15 21:20:03.495 15385 15385 F DEBUG   : Abort message: '2022-blake3-chacha20-poly1305 password example is not base64 encoded, error: Encoded text cannot have a 6-bit remainder.
```

@Mygod it looks we need to output the error message in a better way. Or we can check if the key is base64 encoded for aead-2022-cipher first.

@iamsad3508 Make sure you provide a valid base64 encoded shared key for aead-2022-cipher

**Comment by iamsad3508** [comment]
@madeye  为什么会缺了两个  ”==“  ？ 补回去就好了，我不太确定之前5.3.2的时候等号是否在

**Comment by iamsad3508** [comment]
v5.3.2没有“==”也可以正常使用，应该是升到5.3.3就不可以了

**Comment by zonyitoo** [comment]
Maybe you have built with the latest master branch? The latest `base64` crate will validate the string and report error if it is not a valid standard base64 string.

> Or we can check if the key is base64 encoded for aead-2022-cipher first.

That would be better.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/commit/dfa0117530f8c9c10def654568245f39ecd955d6#commitcomment-99858064 🧠

**Comment by zonyitoo** [comment]
Well yes, it is a new "feature" from `base64`. :P
