### ISSUE TITLE
codeModle

### ISSUE THREAD

**Issue by MygithubTom** [shadowsocks/shadowsocks-android#3016]
1.Execution failed for task ':core:cargoBuildX86_64'
2.A problem occurred starting process 'command 'rustc'
3. Could not start 'rustc'
4. Cannot run program "rustc" (in directory "D:\AndroidStudioProjects\shadowsocks-android\core"): CreateProcess error=2, ϵͳ�Ҳ���ָ�����ļ���

**Comment by zhoujunliang94** [comment]
兄弟，麻烦的话一起讨论。Q:2868441586
