### ISSUE TITLE
3G模式下无法联网

### ISSUE THREAD

**Issue by weishiji** [shadowsocks/shadowsocks-android#302]
nexus5 系统 5.1.1 3G 模式下无法联网

**Comment by xcjiang** [comment]
是可以的，我一直用。

**Comment by weishiji** [comment]
难道是我的设置问题？最近一段时间就不可以了，不过也还好，毕竟WIFI的时间长，而且出门在外不翻墙也没关系~~

2015-05-25 16:58 GMT+08:00 tedjiang <notifications@github.com>:

> 是可以的，我一直用。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shadowsocks/shadowsocks-android/issues/302#issuecomment-105171825>
> .
>



-- 
姓名：刘小光
电话：18610078527

**Comment by Tobyskernel** [comment]
移动数据下无法联网，WiFi下正常
