### ISSUE TITLE
Extremely delayed startup, leak during delay

### ISSUE THREAD

**Issue by lepasserby** [shadowsocks/shadowsocks-android#303]
Hello!
Following behavior on android 4.4 (global proxy off, forward UDP off), start at boot on

After reboot, the Shadowsocks only starts if/when screen is unlocked, or else with a very long delay.
Installed from google apps.

Other apps that need to start at boot (Viber, for instance) autostart normally.

In the period of time between autostart of Shadowsocks and system startup some apps do manage to connect "unsocksified".

**Comment by madeye** [comment]
This behavior is expected, not a bug.

**Comment by lepasserby** [comment]
Okay, if possible, would you please explain why it is desirable to prevent Shadowsocks from starting up until the keyguard gets unlocked? 
In case of spontaneous phone reboot, that may lead to a fairly prolonged leak, no ?
