### ISSUE TITLE
UDP Forwarding + per-app proxy issue/question (two questions)

### ISSUE THREAD

**Issue by ironoob** [shadowsocks/shadowsocks-android#304]
Hello! 

I am a bit confused (sure thing) and I don't know where to ask.

I have shadowsocks android. I connect to a remote shadowsocks server which has udp-forward support.

I do not have system-wide proxy enabled on my android device (and don't wanna do this)

I have "per-app proxy" enabled  (relevant apps are selected)

I have "UDP Forwarding" enabled.

Phone is Android 4.2, rooted

**Now, question 1:**

Does shadowsocks honor the per-app settings for forwarding UDP?

Because I've ran "iptables -t -nat -v -L" in Android Terminal, and I'm not seeing any app-specific rules for UDP forwarding...

**Question 2:**
If shadowsocks-android doesn't do per-app UDP forwarding currently (which would be an awesome feature BTW!), would it be possible to do so via manual DNAT rules, or would I have to start tun2socks and do it [mark+route way](http://serverfault.com/questions/345111/iptables-target-to-route-packet-to-specific-interface)?

**Comment by madeye** [comment]
1. No.
2. You can't.

For full feature per-app proxy, upgrade your phone to Android 5.0 or above.

**Comment by ironoob** [comment]
Okay, that's... sad. This device doesn't have Android 5+ support.

Why wouldn't tun2socks+route shtick work though? 
I can run udpgw on the server if that's what needed....
