### ISSUE TITLE
Last question: udp features of tun2socks binary bundled with shadowsocks-android (if any)

### ISSUE THREAD

**Issue by ironoob** [shadowsocks/shadowsocks-android#305]
Hi! 

One last question (sorry if annoying, I'm not a programmer so can not just go and check myself)

Does tun2socks binary shipping with shadowsocks-android support udpgw-based UDP forwarding and would that work if I try to start a udpgw instance on the server (as detailed in their manual), then run a separate instance of tun2socks (with a separate tun-device) on android's side ? 

As in, 
1) would the tun2socks you have included successfully forward UDP packets (you mentioned it was patched on twitter, so I thought I'd better ask) 

and 

2) would shadowsocks-tun successfully forward those packets to udpgw on the server ?

**Comment by madeye** [comment]
1. Yes.
2. No. UDPGW is not required for shadowsocks.

**Comment by ironoob** [comment]
Okay, please pardon me if I am saying something magnanimously stupid, but wouldn't the following work to do per-app UDP forwarding for Android 4.4.:

1) 
Create a separate tun device
2) 
Run tun2socks instance configured to use this device and to forward packets to Shadowsocks 
3) 
Use iptables mark and route to redirect all UDP traffic from app of choice to tun2socks interface ?

**Comment by madeye** [comment]
No, you can't do per-app UDP forwarding below Android 5.0.

**Comment by ironoob** [comment]
Errrr... I can't do it with DNAT, that seems to be the case.

But as long as iptables mark is supported and route works as expected, policy-based routing should work more or less as expected.

What I want to know is, IF the udp packet arrives at tun2socks's interface and is then redirected to ss-tunnel's listening port, will shadowsocks (ss-tunnel) then successfully forward it to the server ?

Also, is UDPGW shtick completely disabled or simply unnecessary ?

**Comment by ironoob** [comment]
Also, if one were to try using tun2socks this way, one would need to use port 8163 (where according to netstat ss-tunnel is always listening for UDP)

Also, would appreciate very much if you were to let me know if udpgw-related functionality has been stripped out of your tun2socks binary (udpgw, like I said, had some features that might prove useful for the little humble project I'm doing)
