### ISSUE TITLE
Iptables gives me a faceful of protoent* getprotobynumber(int)(3)

### ISSUE THREAD

**Issue by lealex9999** [shadowsocks/shadowsocks-android#309]
Hello dear shadowsocks team!

I have an oldie android 4.2.2 phone and when I installed shadowsocks, per-app proxy does not seem to work allright.

When I checked out the NAT table in iptables, it is full of 

protoent* getprotobynumber(int)(3) is not implemented on Android 

errors 

What should I do now, how to fix ?

**Comment by madeye** [comment]
It'd be an issue of your ROM. Just try some other ROMs.
