### ISSUE TITLE
How can Shadowsocks configure a socks proxy that requires only user name and password authentication

### ISSUE THREAD

**Issue by XuanRanDev** [shadowsocks/shadowsocks-android#3121]
How can Shadowsocks configure a socks proxy that requires only user name and password authentication?
I've tried searching in issues but didn't find a proper answer and also asked chatgpt and google

**Comment by evsasha** [comment]
@XuanRanDev Have you found the answer to your question? I have the same question.

**Comment by yuanbaoyang** [comment]
> @XuanRanDev您找到问题的答案了吗？我也有同样的问题。

你找到方法了吗

**Comment by XuanRanDev** [comment]
我换成了socks，已解决，此应用谷歌商店就能搜到，很轻量




XuanRan
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadowsocks/shadowsocks-android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadowsocks/shadowsocks-android] How can Shadowsocks configure a socks proxy that requires only user name and password authentication (Issue #3121)





  
@XuanRanDev您找到问题的答案了吗？我也有同样的问题。
  
你找到方法了吗

**Comment by XuanRanDev** [comment]
> @XuanRanDev Have you found the answer to your question? I have the same question.

我换成了socks，已解决，此应用谷歌商店就能搜到，很轻量
