### ISSUE TITLE
not withing on rooted ASUS Zeonfone 2 stock rom

### ISSUE THREAD

**Issue by realdreams** [shadowsocks/shadowsocks-android#314]
rom: MR7-LRX21V.WW-ASUS_Z00A-2.18.40.12_20150529_9543_USER044030427_201501060109

server end not seeing incoming connections at all

any way to debug the android client? I checked logcat and didnt spot anything that might cause problems

shadowsocks android client works on other devices on the same network, Google play latest version

**Comment by madeye** [comment]
It'd be an issue of ASUS's ROM, not Shadowsocks's. You may try:

1. Disable SELinux: https://github.com/MrBIMC/SELinuxModeChanger
2. Report this bug to ASUS.

**Comment by madeye** [comment]
Try this APK：https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-2.7.0.apk
