### ISSUE TITLE
Mostly broken on mobile data

### ISSUE THREAD

**Issue by qwelias** [shadowsocks/shadowsocks-android#3151]
Please read contributing guidelines. Thanks.

**Describe the bug**

**To Reproduce**
1. Configure shadowsocks-rust 1.18.2-1 server as:
    ```json
    {
    "server": "::",
    "server_port": 443,
    "method": "aes-256-gcm",
    "password": "redacted",
    "plugin_opts": "mode=quic;host=github.com",
    "plugin_args": [
        "--verbose"
    ],
    "plugin_mode": "tcp_and_udp",
    "timeout": 7200
    }
    ```
1. Get Termux from F-Droid
1. Get Shadowsocks 5.3.3-nightly from F-Droid
1. Connect to shadowsocks-rust server
1. Allow Background data, Unrestricted usage
1. Turn on WiFi
1. Try `ping 8.8.8.8` in termux = no res
1. Try `curl ipinfo.io` in termux = ok 
1. Try `curl fast.com` in termux = ok 
1. Open `fast.com` in Chrome = ok 
1. Disconnect WiFi, use mobile data
1. Try `ping 8.8.8.8` in termux = no res
1. Try `curl ipinfo.io` in termux = ok
1. Try `curl fast.com` in termux = ok 
1. Open `fast.com` in Chrome/Brave = ERR_CONNECTION_CLOSED (but sometimes it works if you spam reload)

**Expected behavior**
Works on mobile data same as on WiFi

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 13, security/play update 1 April 2024, 5.4.254-moto-g1c96cdb0b01, build T1SUS33.1-124-6-8
 - Device: moto g82 5g
 - Version: 5.3.3-nightly, had it on 4.something as well
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-gcm
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8 or 9.9.9.9
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
- When using OpenVPN android client with a 3rd party VPN provider I do not experience any of these issues
- When using the device as a wifi hotspot and connecting via laptop with shadowsocks-rust client configured to use the same server everything works

**Comment by qwelias** [comment]
enabling v2ray fixed the issue, must be ISP doing things

**Comment by frozzway** [comment]
@qwelias Russia, isn't it?
