### ISSUE TITLE
UDP doesn't seem to be working

### ISSUE THREAD

**Issue by gudvinr** [shadowsocks/shadowsocks-android#3162]
**Describe the bug**

With server having `"mode":"tcp_and_udp"`, client doesn't forward UDP.

**To Reproduce**
1. Add server
2. Click on 'Connect'

**Expected behavior**

UDP should be forwarded along with TCP.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [Android 14 (LineageOS 21-20240729-NIGHTLY)]
 - Device: [OnePlus 7 Pro]
 - Version: [v5.3.3]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
* [ ] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 9.9.9.9
* [ ] DNS over UDP (__not seeing this setting__)
* Plugin configuration (if applicable):
* [ ] Auto Connect [not applicable]
* [ ] TCP Fast Open [not applicable]
* If you're not using VPN mode, please supply more details here:

**Additional context**

<details><summary>logcat output</summary>

```
libsslocal: 2024-08-06T08:02:40.564893627+00:00 INFO  shadowsocks local 1.15.2 build 2023-02-07T04:08:52.977279400+00:00
libsslocal: 2024-08-06T08:02:40.565782117+00:00 WARN  no valid UDP server serving for UDP clients, consider disable UDP with "mode": "tcp_only", currently chose [REDACTED]
libsslocal: 2024-08-06T08:02:40.566549252+00:00 INFO  shadowsocks socks TCP listening on 127.0.0.1:1080
libsslocal: 2024-08-06T08:02:40.567161856+00:00 INFO  shadowsocks socks5 UDP listening on 127.0.0.1:1080
libsslocal: 2024-08-06T08:02:40.567790815+00:00 INFO  shadowsocks dns TCP listening on 127.0.0.1:5450, local: local_dns_path, remote: 9.9.9.9:53
libsslocal: 2024-08-06T08:02:40.568730294+00:00 INFO  shadowsocks dns UDP listening on 127.0.0.1:5450, local: local_dns_path, remote: 9.9.9.9:53
```
</details>

Server version (shadowsocks-rust): `v1.20.3`

**Comment by AaronChen0** [comment]
If you use plugin, sslocal will be in mode `tcp-only`. You have to use udp fallback config to enable UDP proxy.

**Comment by AaronChen0** [comment]
Can not reproduce with v5.3.3 and the same config you described. TCP and UDP both works in my test.

From your logcat output, your udp server is not valid. Please ensure your udp server is reachable from your client with nmap or other tools.

Try disabling IPv6 route. Would this help?

Better post your redacted server config and shadowsocks-android config screenshots.

**Comment by Mygod** [comment]
Closing as per above.

**Comment by AaronChen0** [comment]
I can see the same logcat output too. But the udp is really working.

Try using `tshark -i eth0 udp` (replace eth0 with your interface) on your server to observer udp traffic.
Or
`ssserver -c config.json -v` to confirm if UDP is working.
