### ISSUE TITLE
Unknown plugin error with Cloak

### ISSUE THREAD

**Issue by Artyom-K** [shadowsocks/shadowsocks-android#3174]
I get the connection error stating that ck-client is unknown. Going into settings of the plugin, opening the config string and just reapplying it solves the problem for some time. If I immediately disconnect and connect again, everything still works. Then, after some time passes, it's not possible to connect again without going into plugin settings and just reapplying them.
 - Android 14, 6.1.57-android14-11-maybe-dirty, PD2324_A_14,0.24.3.W10.V000L1
 - Device: Vivo X100 Pro
- Current version of Shadowsocks app: 5.3.4
- Current version of Cloak plugin: 2.9.0

**Configuration**
    {
      "server": "xxx",
      "server_port": xxx,
      "password": "xxx",
      "method": "chacha20-ietf-poly1305",
      "plugin": "ck-client",
      "plugin_opts": "UID=xxx\\=\\=;PublicKey=xxx\\=;ServerName=bing.com;BrowserSig=chrome;NumConn=4;ProxyMethod=shadowsocks;EncryptionMethod=plain;StreamTimeout=300",
      "timeout": 300,
      "warnLegacyUrl": false
    }

**Comment by AaronChen0** [comment]
Probably related to your phone's battery management. Try checking your phone's app automatic management settings.

**Comment by Artyom-K** [comment]
> Probably related to your phone's battery management. Try checking your phone's app automatic management settings.

Thanks! It looks like cloak should have been allowed to be opened by Shadowsocks. Looks like now it's working.
