### ISSUE TITLE
Android 15 not work

### ISSUE THREAD

**Issue by yanickxia** [shadowsocks/shadowsocks-android#3188]
Please read contributing guidelines. Thanks.

**Describe the bug**
SS With KCPTUN not work, without kcptun will be ok

**To Reproduce**
- open shadowsocks
- connect

**Expected behavior**
Should be work

**Screenshots**
![info](https://github.com/user-attachments/assets/f1568bd7-2f32-4b6d-95e4-47e2856ee29a)

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: ["6.1.75-android14-11-0-gc6c9b99a89c8"]
 - Device: [Realme GT6]
 - Version: [v5.3.4]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x ] IPv4 server address
* [ ] IPv6 server address
* [ x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ x ] All
  * [ x] Bypass LAN
  * [ x] Bypass China
  * [ x] Bypass LAN & China
  * [ x] GFW List
  * [x ] China List
  * [x ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ x ] KCPTUN
* If you're not using VPN mode, please supply more details here:

**Additional context**

logs file: 
[log.log](https://github.com/user-attachments/files/17840686/log.log)

**Comment by yanickxia** [comment]
more logs:

2024-11-21 16:57:42.035 24310-24318 s.plugin.kcptun         com...hub.shadowsocks.plugin.kcptun  E  Failed to send jdwp-handshake response.: Broken pipe

**Comment by AaronChen0** [comment]
Are you using OnePlus? Maybe a device specific issus. https://github.com/termux/termux-app/issues/4219.
Check your phone's setting. Make sure the plugin process doesn't get killed by your phone's management system.

**Comment by yanickxia** [comment]
same with #2954 , i try run kcptun-client in termux + ss without kcptun, it's works

**Comment by yuliu** [comment]
> Are you using OnePlus? Maybe a device specific issuse. https://github.com/termux/termux-app/issues/4219.
> Check your phone's setting. Make sure the plugin process doesn't get killed by your phone's management system. 
> Or wait for OS update.

Seems so. I've upgraded my OnePlus 12 from ColorOS 14 to 15, and shadowsocks android with the v2ray plugin won't connect to the server which toasts `libsslocal exits too fast` with exit code `70`. Don't know what reason this number is for.

**Comment by yuliu** [comment]
> Are you using OnePlus? Maybe a device specific issuse. https://github.com/termux/termux-app/issues/4219.
> Check your phone's setting. Make sure the plugin process doesn't get killed by your phone's management system. 
> Or wait for OS update.

Termux installed from f droid has issues setting up bootstraps (script killed when opening termux), but the one from Google play store runs pretty fine. Maybe shadowsocks android is having the same issue?

**Comment by yuliu** [comment]
After upgrading shadowsocks android to 534 from GitHub repo release, it can connect but no connection would go through the VPN set up by it. Same environment and same message as in https://github.com/shadowsocks/shadowsocks-android/issues/3185

**Comment by yanickxia** [comment]
After last system upgrade, it's works again, seem OS bug

**Comment by yuliu** [comment]
> After upgrading shadowsocks android to 534 from GitHub repo release, it can connect but no connection would go through the VPN set up by it. Same environment and same message as in #3185

A newer OS version fixed the issue. The Google Play Store version works.
