### ISSUE TITLE
在客户端内置一个按应用流量统计功能是否可行？

### ISSUE THREAD

**Issue by m13253** [shadowsocks/shadowsocks-android#319]
连接上 Shadowsocks 之后，Android 自带的流量统计会把所有流量算在 Shadowsocks 头上。
这样就无法判断哪个应用在吃我的流量了。

如果在 Shadowsocks 客户端内置一个按应用流量统计功能，技术上是否可行？

谢谢。

**Comment by madeye** [comment]
1. 可行。
2. 没有加入此功能的计划。

**Comment by m13253** [comment]
> 没有加入此功能的计划。

如果我能实现，你会 pull 进来么？

**Comment by madeye** [comment]
可以的，欢迎提交 Pull Request。

**Comment by Mygod** [comment]
+1

**Comment by diligentpig** [comment]
+10086
早上不知道哪个应用把我一个月的流量跑完了，晚上google了一圈也没找到查找的办法

**Comment by Mygod** [comment]
I observed that on my device (Android 7.1), the system is actually able to count data usage correctly. So we will never implement this feature.
