### ISSUE TITLE
Problem with VPN mode on Android 5.0.2

### ISSUE THREAD

**Issue by morteza25** [shadowsocks/shadowsocks-android#320]
Hi,

I'm using latest SS version (2.6.8) on a non-rooted device with Android lollipop (5.0.2) in VPN mode. The client is connecting without any problem, but the network doesn't work at all. The VPN connection shows some data transfer (many upload, very low download), but when I've checked the server's log, the client doesn't connect to server at all. I've also tried previous versions (2.6.7, 2.6.6, 2.5.7), but they have same problem. I didn't see any shadowsocks related error in logcat.

I would really appreciate it if you kindly give me some hint to find out the problem.

Thank you so much for your great app.

**Comment by madeye** [comment]
1. Double check your configuration.
2. Uninstall / Disable any firewall or similar apps.
3. ROOT your phone and disable SE-Linux using this app: http://forum.xda-developers.com/showthread.php?t=2524485

**Comment by madeye** [comment]
Try this APK：https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-2.7.0.apk

**Comment by morteza25** [comment]
Thanks! It works now!
