### ISSUE TITLE
Nokia N1 root之后无法实现全局代理

### ISSUE THREAD

**Issue by aesean** [shadowsocks/shadowsocks-android#321]
Nokia N1使用X86的Intel CPU不知道是不是跟这个有关系。

**Comment by madeye** [comment]
Try http://forum.xda-developers.com/showthread.php?t=2524485

**Comment by aesean** [comment]
那个工具试了，然而并没有什么用。我的Nexus5也是Android 5.0操作系统，root后使用没任何问题，我的Nokia N1也是5.0操作系统不过是Intel的X86 CPU。
安装SS配置好账号地址后状态栏会有小钥匙图标，一切看似正常，也没任何报错之类的，但就是访问外网的时候不成功。
基本可以排除的问题，SS账号100%没问题（在其他平板手机测试正常），root正常，可以访问系统目录。

**Comment by madeye** [comment]
Try this one: https://drive.google.com/open?id=0B3YSrCJtFxYiQnViNTNzaHIwQnM&authuser=0

**Comment by madeye** [comment]
Try this apk: https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-2.7.0.apk

**Comment by aesean** [comment]
It doesn't work. shadowsocks-nightly-2.7.0.apk
