### ISSUE TITLE
Android 多用户模式其他用户无法访问

### ISSUE THREAD

**Issue by Jack-Works** [shadowsocks/shadowsocks-android#324]
Android 5.0.2, Shadowsocks 2.6.8
在主用户开启VPN之后，其他用户无法代理
但是其他用户的状态栏上仍有 VPN 连接标志。

其他用户无法连接 Shadowsocks

**Comment by madeye** [comment]
It's a limitation of Android, not a bug of shadowsocks.

**Comment by IhInspiration** [comment]
shadowsocks在android5.0兼容性貌似不是很好

**Comment by chriszeng87** [comment]
Samsung Galaxy S6 Edge 直接crash
