### ISSUE TITLE
dns look up failed

### ISSUE THREAD

**Issue by UzxMx** [shadowsocks/shadowsocks-android#325]
Hi, I just installed 2.6.7 in my android device. After configuration, I switched it on successfully. But when I open my browser and enter www.baidu.com, the browser said the dns look up failed. How can I resolve this problem? I installed 2.6.7 on Nexus 6(API 22), LG-LS970(API 16), Nexus 4(API 19), Huawei G750(API17), Xiaomi, but all failed because of such problem. Thank you!

**Comment by madeye** [comment]
Because your configuration is incorrect.
