### ISSUE TITLE
A Problem after Server IP Changed

### ISSUE THREAD

**Issue by LenKiMo** [shadowsocks/shadowsocks-android#326]
For some reason, I moved my ShadowSocks to a new server.
In fact all changing just in server. I kept all the setting still same with older VPS. 
So I think all the setting inside the ShadowSocks APP is not need to change.
But after I changed the domain‘s DNS record. And flush the DNS cache, click "reset" inside the ShadowSocks APP. I still can use it to browse web or APP which needs to use ShadowSocks.
And I haved clear data of Network Location, but it still doesn't work out.
The ShadowSocks APP seems like it is connect to server successfully. And it can work in background. But it still can't work.
The csharp in PC connect to same server are working sucessfully now. But my phone still can't link. How can I find what's problem with my phone.
My phone using Android 4.4.4. Before I changed my domain IP, it works without any problem.
My server config using "::". And my domain has A and AAAA record. 

出于某些原因，我将自己搭建的 ShadowSocks 迁移到了另一台服务器上。
实际上所有的改变都是在后台进行的，我将与老 VPS 同样的配置文件转移到了新 VPS 上。
所以我认为 ShadowSocks APP 内的设置是不用修改的。
但当我修改好域名的 DNS 记录，并在 ShadowSocks APP 内刷新 DNS 缓存与重置设置后，我依旧不能使用或浏览需要 ShadowSocks 代理的内容。
我也尝试过清除“网络位置”的数据，但是也同样不起作用。
至少 ShadowSocks APP 是启动成功的，没有弹出无法连接到服务器的通知。而且也成功启用了后台服务。但是就是没办法浏览需要它协助的网页或内容。
连接到同一服务器的电脑端已经在正常工作了，但手机依旧处于无法连接状态，应该如何排查这里面的错误？

**Comment by madeye** [comment]
1. Reboot your phone.
2. Uninstall and reinstall shadowsocks.

**Comment by LenKiMo** [comment]
I had reboot my phone for many times.
And I tried to reinstall ShadowSocks once.
But nothing changed.

**Comment by spencerwinston** [comment]
问题是shadowsocks server 不能同步更新！当wan ip 更改时，shadowsocks server 依然咬死原有旧wan ip，所以shadowsocks server 便失效！至今仍未有人能解决这问题。所以shadowsocks 只能用于fix ip 既wan。动态ip 是不行的。

**Comment by hellofwy** [comment]
Try to use server IP directly instead of domain name until ISP's DNS can pick up your new ip.

**Comment by spencerwinston** [comment]
@hellofwy,
I have tried your suggestion before, its not work. even i type the new ip on my client side, it wont allow me to use ss. The problem is surely occur in server side, ss server in (koolshare) merlin firmware fail to update itself.
