### ISSUE TITLE
android 5.1.1 dns error

### ISSUE THREAD

**Issue by nickleefly** [shadowsocks/shadowsocks-android#329]
when using the latest version. it connects well, but in chrome it says dns probe started, then few seconds later, it says dns probe finished no internet, You can't open any website. without shadowsocks turning on, everything is normal.

this scenario happens both on wifi and 3G, While downgrade to 2.6.8 doesnt have this issue.

**Comment by madeye** [comment]
Tested on Android 5.1.1, everything works well.

**Comment by zjx20** [comment]
I have the same problem too

**Comment by zjx20** [comment]
It's due to incorrect configuration, and it works now, sorry!
