### ISSUE TITLE
关于“绕过局域网和中国大陆地址”和“SS国内中转”之间的冲突

### ISSUE THREAD

**Issue by lucifersun** [shadowsocks/shadowsocks-android#331]
近日为了解决手机移动网络国际出口速度缓慢的问题，在国内服务器上用netsh建了一个SS中转服务。但发现只有将手机客户端上的路由模式设置成“全局”，才能正常通讯。如果使用“绕过局域网和中国大陆地址”，则无法连接境外网站。
是否ss客户端在绕行模式下对所有国内IP发回的数据包都不作处理，连带中转服务器发还的ss加密数据包也未经解密直接转发了？
因为在全局模式下，对国内网站的访问会经过中转服务器+日本VPS两次跳转，速度影响很大。
不知道对这个情况能否解决，比如在境内地址清单里，把中转服务器IP排除掉。

同时对您开发此软件表示万分感谢。

我的环境如下：
VPS：Debian 8.0，shadowsocks 2.6.11
中转：Win2012 R2，netsh转发
客户端：Android 5.0.2，未root，shadowsocks-android 2.6.9

**Comment by madeye** [comment]
试了一下国内中转，无此问题，建议你仔细排查设置。

从原理上讲，本地的路由策略与服务器所在网段无关。
