### ISSUE TITLE
网易云音乐走了代理

### ISSUE THREAD

**Issue by kkzhang** [shadowsocks/shadowsocks-android#332]
我的小米NOTE，安装了谷歌市场，路由选择绕过中国IP和局域网。但是云音乐会被误判，每次都走代理，导致很慢断断续续。希望有更灵活的绕过机制

**Comment by madeye** [comment]
ROOT 后启用分应用代理。

**Comment by kkzhang** [comment]
经过试验。分应用代理在MIUI上是存在问题的，症状是，所有的应用都走了代理。。

我把miui刷成5.1.1的AOSP版本，这个功能是正常的，在MIUI里面，无效，确定是root后的，因为没有ROOT权限根本无法选择该项。

重装，刷机过多次，从MIUI6到7，ss-andriod也经历了好几个版本，基本可以确认这个是个bug。

**Comment by madeye** [comment]
It's a bug of MIUI, not shadowsocks. Report this issue to MIUI, or stick to AOSP as recommended.

**Comment by myliyifei** [comment]
因为网易云音乐用国外的DNS解析，可以解析到国外的IP上面去，所以走了SS

2015-08-24 10:00 GMT+08:00 Max Lv <notifications@github.com>:

**Comment by jsoncode** [comment]
意思是说，网易云音乐他翻墙了？

**Comment by iahu** [comment]
公司路由封了网易云音乐，我开了ss代理，也在云音乐上设置了127.0.0.1:1080的代理，测试代理也通了。但是云音乐主页显示没有网。我该怎么设置才能让云音乐走ss代理？
