### ISSUE TITLE
com.github.shadowsocks.apk 连上了但不能用

### ISSUE THREAD

**Issue by uinux** [shadowsocks/shadowsocks-android#336]
下载的com.github.shadowsocks.apk
跟pc端设置的一样的参数，但不能用，com.github.shadowsocks.apk自动弄了vpn，但上不了google.全局代理了，也UDP转发了。服务端用shadowsocks-go架的。PC机可以连，安卓机连上不能上google，也不能上国内网站。安卓机测试用的火狐安卓版，直接从国外下的非和谐版。系统4.2.2

**Comment by madeye** [comment]
1.Download the latest version: https://github.com/shadowsocks/shadowsocks-android/releases/tag/v2.7.1
2. Disable UDP realy

**Comment by uinux** [comment]
感谢，我试下。
