### ISSUE TITLE
能否负载均衡和自动切换？

### ISSUE THREAD

**Issue by renyouguo** [shadowsocks/shadowsocks-android#338]
WIndows版刚刚实现了……

**Comment by polong** [comment]
为啥不实现，多么重要的功能。

**Comment by mashiro94** [comment]
其实我觉得自定义路由表之类的功能更重要一点，负载均衡倒是没那么重要。

**Comment by polong** [comment]
不的，主要是很多时候不知道是服务商线路的问题，还是GFW的问题，还是运营商的问题，很多线路不定期抽风，如果能自动切换或多条腿走路比较好，可是手机有时时本身自己网络不稳定，所以是不是其实不容易解决。

**Comment by fzhw88** [comment]
期待添加android版本的自动切换功能，主要的用途在，有服务器只能在wifi下使用，移动4G不能用，刚好有另一个服务器只能在4G用，wifi就不行了，非常无语，现在都是手动切换。

**Comment by Mygod** [comment]
@fzhw88 Use Tasker integration.
