### ISSUE TITLE
使用269,271,273版本时，连上指定有效SS服务器后。连接任何网站皆DNS解析失败，但DNS完全没问题。

### ISSUE THREAD

**Issue by mindcat** [shadowsocks/shadowsocks-android#339]
对此我已经快发疯了。

EDIT: 不好意思,不是275版本,而是273版本.

**Comment by mindcat** [comment]
再另外说一句，UDP转发选不选，全局或绕过局域网都一样。

**Comment by mindcat** [comment]
疯了疯了！ (╯°Д°)╯︵ ┻━┻

**Comment by madeye** [comment]
你需要提供更多信息。

**Comment by mindcat** [comment]
Android版本 4.4.4
内核版本 3.10.28-g984ade2 Thu Mar 26 14:46:06 CST 2015
版本号TCL_M2L_L_V1.92

在我安装shadowsocks-android之后,打开了这个APP. 出现服务器设置,配置文件,服务器,远程端口等等的东西. 我按照SS服务器上面的/etc/shadowsocks.json进行配置. 选定全局代理并且点击shadowsocks-android软件右上角的开关之后,我打开了我手机的Opera Classic浏览器,尝试访问google.com,显示"无法定位远程服务器". 再尝试访问ip138.com也是如此. 我关掉了shadowsocks-android的服务再使用Opera Classic浏览器访问ip138.com正常.
但是在我没开服务访问google.com的时候,去访问google.com一段时间的话再开shadowsocks-android的服务,那么google.com访问会正常,但是通过google.com搜素出来的任何链接点击之后还是会出现"无法定位远程服务器"的情况.
我手机另外还有Firefox浏览器,我还没测试过.

不知道我提供的信息是否详细.

**Comment by madeye** [comment]
应该是不支持你的手机型号吧，换个手机试试。

**Comment by mindcat** [comment]
我就只有这一台手机.

**Comment by myliyifei** [comment]
android下面有个软件 ping &dns 有助于你定位问题

在 2015年7月30日 下午12:06，☯neko <notifications@github.com>写道：

**Comment by mindcat** [comment]
我试试

**Comment by madeye** [comment]
换个浏览器试试

**Comment by mindcat** [comment]
没开shadowsocks-android的服务,打开了Firefox浏览器. 访问了ip138.com正常. 连续访问几次也正常.
然后开shadowsocks-android的服务之后,使用Firefox浏览器访问了ip138.com显示当前本地IP,如此几次也是一样. 之后关掉Firefox浏览器再开Firefox浏览器,访问ip138.com正常,但不显示IP. 再访问google.com,显示找不到服务器. 访问baidu.com也是如此.
关闭shadowsocks-android的服务之后,访问baidu.com正常.
再开shadowsocks-android的服务之后,访问baidu.com正常,搜索也没问题. 但是搜索出来的链接没法访问. 这时访问ip138.com也没问题. 然后我在shadowsocks-android的界面从左开始右滑,点击刷新DNS缓存, 访问ip138.com也没问题. 访问baidu.com显示找不到服务器.

**Comment by madeye** [comment]
目测是不支持你的手机吧，暂时没有解决方案。

**Comment by mindcat** [comment]
在已开启shadowsocks-android的服务的情况下,我打开了ping & dns. 输入了baidu.com 点击DNS, 勾选Use alternate NS. 结果:
```
--- 2015年7月30日 下午1:25:56
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for baidu.com

A   timed out

AAAA   timed out

(DNS server: 8.8.8.8, port 53, UDP)
```
勾选Use TCP之后:
```
--- 2015年7月30日 下午1:25:38
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for baidu.com

baidu.com.	
TTL=73
A    123.125.114.144

baidu.com.	
TTL=73
A    180.149.132.47

baidu.com.	
TTL=73
A    220.181.57.217

AAAA   timed out

(DNS server: 8.8.8.8, port 53, TCP)

```

**Comment by mindcat** [comment]
进入shadowsocks-android的界面, 停止shadowsocks-android的服务. 勾选UDP转发. 开启shadowsocks-android的服务
Use alternate NS 已勾选
Alternate NS    8.8.8.8
Port    53
Use TCP 未勾选
点击OK

```
--- 2015年7月30日 下午1:36:40
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for baidu.com

A   timed out

AAAA   type not found

(DNS server: 8.8.8.8, port 53, UDP)

```

**Comment by mindcat** [comment]
这次再勾选 Use TCP
```
--- 2015年7月30日 下午1:38:05
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for baidu.com

baidu.com.	
TTL=515
A    220.181.57.217

baidu.com.	
TTL=515
A    123.125.114.144

baidu.com.	
TTL=515
A    180.149.132.47

AAAA   type not found

(DNS server: 8.8.8.8, port 53, TCP)
```

**Comment by mindcat** [comment]
忘了说,从开启Firefox那时起,我DNS设置为192.168.1.9,即我家开着dnsmasq的OpenWRT路由器. 而shadowsocks-android的路由选项是绕过局域网地址.
转到shadowsocks-android的界面关闭服务之后,我勾选了UDP转发,然后打开服务.
关闭Ping & DNS再打开.
```
--- 2015年7月30日 下午1:50:50
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for google.com

A   timed out

AAAA   timed out

(DNS server: 192.168.1.9, port 53, UDP)
```
```
--- 2015年7月30日 下午1:52:49
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for google.com

google.com.	
TTL=0
A    173.194.38.215

google.com.	
TTL=300
AAAA    2404:6800:4005:808::200e

(DNS server: 192.168.1.9, port 53, TCP)
```
```
--- 2015年7月30日 下午1:54:45
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for google.com

google.com.	
TTL=299
A    216.58.221.142

google.com.	
TTL=299
AAAA    2404:6800:4005:80b::200e

(DNS server: 8.8.8.8, port 53, TCP)

```

```
--- 2015年7月30日 下午1:54:45
--- IP (wlan0) fe80::b2e0:3cff:fe66:886c%wlan0 
--- IP (wlan0) 192.168.1.30 
--- Connection: WIFI

DNS records for google.com

google.com.	
TTL=299
A    216.58.221.142

google.com.	
TTL=299
AAAA    2404:6800:4005:80b::200e

(DNS server: 8.8.8.8, port 53, TCP)

```

**Comment by mindcat** [comment]
由此推测,是不是自从shadowsocks-android的服务开启之后, UDP包没法发送出去?

**Comment by madeye** [comment]
手机ROOT了吗？没有的话，ROOT。如果ROOT了，在授权管理里取消对shadowsocks的授权。

**Comment by mindcat** [comment]
刚才我谷歌了下. 看到这里http://v2dn.com/t/183 开启了服务器端的udp转发.
我手机ROOT过了,现在也取消了

**Comment by mindcat** [comment]
不,取消shadowsocks-android的授权之后,shadowsocks-android的服务无法开启了.

**Comment by mindcat** [comment]
换句话说,shadowsocks-android是个必须ROOT才能使用的软件

**Comment by mindcat** [comment]
而关了shadowsocks-android的服务,DNS查询都能使用

**Comment by mindcat** [comment]
不知为何,自从开启服务器端的udp转发之后, shadowsocks-android的服务关了再开都还是使用本地IP而不是VPS那边的IP. 我重启手机之后,再开启shadowsocks-android的服务,怪事出现了. 打开ping&dns或者Firefox浏览器使用全都正常. google访问正常 baidu访问不能. bilibili正常. ip138访问正常. 在此关掉UDP转发之后,服务关掉再开. baidu访问正常. bilibili访问正常. ip138访问正常,而且显示VPS的IP. google访问正常.

**Comment by mindcat** [comment]
这竟然是手机重启就能好的事情!!! (╯°Д°)╯︵ ┻━┻ (╯°Д°)╯︵ ┻━┻ (╯°Д°)╯︵ ┻━┻

**Comment by madeye** [comment]
忘了跟你说了，先要试试重启手机。

**Comment by orvice** [comment]
重启如果解决不了问题，在重启一次。

**Comment by mindcat** [comment]
@orvice 你这说法就像是: 

> 世界上没有什么是一颗猴腮雷不能解决的，如果有，那就两颗
