### ISSUE TITLE
使用电信2/3G无法翻墙

### ISSUE THREAD

**Issue by SeavantUUz** [shadowsocks/shadowsocks-android#34]
如题。我在wifi下，shadownsocks运行得很好，但是如果使用移动数据，那么就没法正常工作。
网络是电信的cdma，手机是sony的m35c，原版系统，没有任何第三方应用管理工具。
请问可能的原因？
谢谢。

**Comment by lostgdi** [comment]
不明白，既然这个是sock5的，应该不存在污染的情况（假设会被污染的域名在未打开ss前未打开）。难道Android域名解释不走sock，另外的？
