### ISSUE TITLE
2.7.5 版本在小米 note 上无法正常运行

### ISSUE THREAD

**Issue by aenerv7** [shadowsocks/shadowsocks-android#340]
刚才发错项目了，抱歉...

不太清楚是 shadowsocks 的问题还是 MIUI 的问题，切换回 2.7.4 版本就可以正常运行了。手机是小米 note 的普通版本，Android 系统是 4.4.4，MIUI 版本是 6.6.5.0。

**Comment by madeye** [comment]
卸载，重装，重启手机

**Comment by rockstore** [comment]
execuse me,when I build the shadowsock-android , follow your steps ,when I execute ./build.sh ,it always tells me "./build.sh: line 4: /ndk-build no such file or directory".How can I solve this problem,thank you very much

**Comment by ShaolinZhang** [comment]
NDK is not installed in your computer. Refer to developer.android.com to
download NDK.

On Wed, Aug 5, 2015 at 1:15 AM rockstore <notifications@github.com> wrote:

> execuse me,when I build the shadowsock-android , follow your steps ,when I
> execute ./build.sh ,it always tells me "./build.sh: line 4: /ndk-build no
> such file or directory".How can I solve this problem,thank you very much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shadowsocks/shadowsocks-android/issues/340#issuecomment-127679499>
> .
>
-- 
SHAOLIN ZHANG
SHANGHAI WORLD FOREIGN LANGUAGE MIDDLE SCHOOL

**Comment by madeye** [comment]
@aenerv7 Try the latest version.

**Comment by aenerv7** [comment]
The latest version works just fine, thanks for fix!
