### ISSUE TITLE
手机端突然无法使用

### ISSUE THREAD

**Issue by akaneko252** [shadowsocks/shadowsocks-android#344]
您好。
同一网络下，电脑端正常使用。手机端突然无法使用。
手机端之前一直轻度使用偶尔看推，前一天新装国外游戏玩了一整天，睡一觉就不能用了。
表现为能连接，绕行模式下能上国内网，国外网和那类应用均无法使用，错误提示为dns解析错【dns_probe_finished_no_internet】。
无法上网可ss手机端发送接收包一直增长，查看vps端记录为无接收到手机端的连接请求，
已在wifi下手动指定ip并修改dns为8888，ss端无勾选udp转发，问题依旧。手机一直无root过，ss版本号为2.7.7，手机系统为4.4.2。
推测为数据包并没有成功发送出去，检查手机并没有装任何杀毒，拦截软件，系统自带程序内也并没有禁用SS，卸载重装ss应用无改善。因手机端无日志无法看出问题。
本人新手，求大大支招，在此谢过！

**Comment by madeye** [comment]
试着重启手机，重刷ROM。

**Comment by KylinDeci** [comment]
华为p7 4.4.2
手机遇到类似问题，不稳定。

手机代理的网站dns_probe_finished_no_internet，非代理链接都顺利。立即重启也不能解决。
有时手机又能够顺利连接所有网站。

**Comment by zzxwill** [comment]
虽然问题解决了，这里提供另外一种解决办法。
SS菜单"Flush DNS"和"Reset"可以解决。

**Comment by nikki70** [comment]
android 5.0.2 表示ss重装好几遍，dns也刷新了好几遍，连接上 但是无法使用。。求解

**Comment by GH-JY** [comment]
清理下DNS缓存

**Comment by chrisju** [comment]
我也遇到了 清理dns还是没用

**Comment by akaneko252** [comment]
上面介绍的清理DNS缓存，当时尝试没有效果。
之前提到的问题后来没有作任何改动隔两天又能正常使用，由于我wifi环境比较特殊，为单位内部的公共wifi，推测为管理员作了一些流量qos之类，或者单纯那几天网络抽风，结果不得而知。
最后上面留言的几位，包括我提问时用的手机，竟然全部都是华为，这真是一种巧合吗？

**Comment by nikki70** [comment]
我是索大法z3 ..

**Comment by chrisju** [comment]
手机双清估计能好 我是直接刷机后好了

**Comment by zarathuss** [comment]
我也遇到了同样的问题，同样配置下PC端科学上网没问题，手机端在SS软件内检查网络能连接但就是上不了网页。
我的解决方法是：
（andriod 4.4.4已root）刷新dns+重置后台+重启。

**Comment by cocobear** [comment]
我也遇到类似的问题，原来使用的是2.9.3，然后自动通过google play升级为2.9.10，就无法连接了，表现为DNS无法解析。然后FLASH DNS REST REBOOT都没有作用，重新装2.9.3也没有用。。。
然后从WIFI换了4G网络就好了……。

**Comment by kaid** [comment]
我是发现手机进入节能模式禁止了后台数据，关掉节能模式就ok了

**Comment by lwjcjmx123** [comment]
我现在出现的情况是能连外网，但是Google play打不开。所有Google应用除了chrome浏览器都用不了。。刷新重启都不行，难道真要重刷rom？。。。。

**Comment by xwhfcenter** [comment]
我也是忽然就不能用了，北京联通的网络，不知道什么原因

**Comment by GongXueYong** [comment]
不知道我的问题和你们是不是一样，我也是这两天用不了，打开 chrome 浏览器的时候显示 dns 错误。
由于我的手机没有root， 不能刷新dns。
所以我就在手机设置里面把ss 的缓存和数据清除里一遍，然后重新打开，然后就可以用啦0.0
没有 root 的可以试试...

**Comment by jccode** [comment]
正确姿势: 设置 -> 应用程序 -> 影梭 -> 清除数据/清除缓存.

**Comment by xwhfcenter** [comment]
发现清楚缓存没有作用，都是删掉重装一遍

**Comment by XatMassacrE** [comment]
清 缓存和数据应该就可以了。

**Comment by xiasummer** [comment]
不可以，不知道具体什么原因，上述说法都是错误的。确认输入密码正确，确认ip和端口正确，确认加密方式正确，但是安卓手机使用shadowsocks就是错误。清除数据、清除缓存也没用。同时，确认服务器配置正确，确认苹果手机可以正常使用——这到底是为什么呢？

**Comment by jasonwang3** [comment]
打开DNS转发就好了

**Comment by tangyongjin** [comment]
@xiasummer  我同样情况，路由器ok，iphoneok，andoid不可以。 ----电量低，进入了低电量模式。安卓充满惊喜。

**Comment by nmb2b** [comment]
我觉得应该是安卓电池优化的锅

**Comment by etrock99** [comment]
@kaid 还真的是“后台数据”的锅，不给后台，不管是重新安装还是清除ss数据，都无效。。。连接正常、点ss内测试也正常，必须电池优化，给ss后台数据

**Comment by why609729343** [comment]
绝对是电池的锅，充电的时候就不可以，拔下数据线就可以了

**Comment by wy-ei** [comment]
坚果Pro2s, 重启了一下手机就工作了。

**Comment by xiangrikui88200** [comment]
> 不知道我的问题和你们是不是一样，我也是这两天用不了，打开 chrome 浏览器的时候显示 dns 错误。
> 由于我的手机没有root， 不能刷新dns。
> 所以我就在手机设置里面把ss 的缓存和数据清除里一遍，然后重新打开，然后就可以用啦0.0
> 没有 root 的可以试试...

very nice

**Comment by xiangrikui88200** [comment]
> 正确姿势: 设置 -> 应用程序 -> 影梭 -> 清除数据/清除缓存.

very goog

**Comment by shidexiao** [comment]
> 正确姿势: 设置 -> 应用程序 -> 影梭 -> 清除数据/清除缓存.

再重启一下手机

**Comment by jacobin** [comment]
猪未鸡油，别废话那么多，卸载了重装就OK了。是华为手机的授权问题，而这个授权问题通过”设置“也折腾不出个明白，所以，最他妈逼爽快的做法就是卸了他妈个屄球的然后装回来。别瞎逼折腾了，浪费时间。

**Comment by jacobin** [comment]
猪位鸡油，别废话那么多，卸载了重装就OK了。就是华为手机的授权问题，而这个授权问题通过”设置“->...也折腾不出一个明白，所以，最他妈屄爽快的做法，就是卸了他妈个屄球的，然后装回来。别瞎逼折腾了，浪费时间。

**Comment by jacobin** [comment]
猪位鸡油，别废话那么多，卸载了重装就OK了。就是华为手机的授权问题，而这个授权问题通过”设置“->...也折腾不出一个明白，所以，最他妈屄爽快的做法，就是卸了他妈个屄球的，然后装回来。别瞎逼折腾了，浪费时间。
有关这个”授权“问题，之前一直无感，我点击启动SSR的时候，华为偶尔（/注意是偶尔，不是每次必现）会提示我”本手机要接受这个SSR程序的VPN的网络管控“，问我”你同意或者不同意“，我当然是每次必是同意了。这次弄到手足无措疑神疑鬼，估计是昨晚手机被我孩子猴玩乱点，结果把它弄瞎了。
别想讨巧去搞设置rollback，没门无用，浪费肏屄时间。
卸载重装，万事大吉！

**Comment by Demo-Liu** [comment]
> 设置

笑死啦 哈哈哈哈

**Comment by Demo-Liu** [comment]
> 猪位鸡油，别废话那么多，卸载了重装就OK了。就是华为手机的授权问题，而这个授权问题通过”设置“->...也折腾不出一个明白，所以，最他妈屄爽快的做法，就是卸了他妈个屄球的，然后装回来。别瞎逼折腾了，浪费时间。
> 有关这个”授权“问题，之前一直无感，我点击启动SSR的时候，华为偶尔（/注意是偶尔，不是每次必现）会提示我”本手机要接受这个SSR程序的VPN的网络管控“，问我”你同意或者不同意“，我当然是每次必是同意了。这次弄到手足无措疑神疑鬼，估计是昨晚手机被我孩子猴玩乱点，结果把它弄瞎了。
> 别想讨巧去搞设置rollback，没门无用，浪费肏屄时间。
> 卸载重装，万事大吉！

被楼上回复笑死  暴躁老哥
