### ISSUE TITLE
望作者加入本地扫描二维码功能

### ISSUE THREAD

**Issue by useeep1** [shadowsocks/shadowsocks-android#347]
作者你好，
关于二维码添加设置方式，我有一个建议。目前的添加方式是透过摄像头扫描二维码。但是，如果遇到只有手机，没有电脑之类的电子产品的时候，便无法使用这个简便快捷的功能。希望shadowsocks-android能加入扫描本地二维码链接的方式添加设置，也感谢作者您的无私贡献。

**Comment by madeye** [comment]
装一个支持本地图像的扫码app

**Comment by evshiron** [comment]
当本地没有安装“Barcode Scanner”时，使用“扫描二维码”功能会推荐安装“Barcode Scanner”，而“Barcode Scanner”并没有扫描本地二维码的功能。

MIUI里有“二维码扫描”应用，可以扫描本地二维码，但“影梭”不会调用它。直接用它扫描出内容后不会调用“影梭”，而是显示URI的文本内容，不管protocol使用的是ss还是shadow。另外测试了一下，直接使用“Barcode Scanner”也是显示URI的文本内容，“微信”的扫一扫更是直接当作URL访问了。~~我可能是MIUI的受害者~~

因此我觉得，添加一个“通过URI添加服务器配置”的功能也是有意义的。

**Comment by Mygod** [comment]
Shadowsocks 是支持打开 ss 协议的 URL 的。曾经从 Chrome 里成功调用过。

**Comment by evshiron** [comment]
我这里用“Google Chrome”和自带的“浏览器”都不行，系统是MIUI 6.4，影梭版本是2.7.7，权限和自启动都没对“影梭”做限制。

**Comment by Mygod** [comment]
直接输地址是没有用的，要超链接之类的才行。

**Comment by evshiron** [comment]
确认了，超链接是可用的。通过网页分享确实可以这样弄。但比如通过即时通讯应用分享，可能就没这么方便了。

**Comment by madeye** [comment]
用这个:
https://play.google.com/store/apps/details?id=tw.com.quickmark

**Comment by evshiron** [comment]
好吧。感谢。
