### ISSUE TITLE
经常出现无法访问任何网络的问题

### ISSUE THREAD

**Issue by falseen** [shadowsocks/shadowsocks-android#348]
安卓版本 : 4.4.4
系统OS : MIUI 5.8.13开发版

问题是这样的：

在没有root权限的情况下开着影梭，路由那里选最后一项“绕过局域网及中国大陆地址”或“绕过局域网”(应该跟这个选项无关)。一开始可以用，但一段时间过后(10分钟左右)所有网络都无法访问，关闭影梭之后问题解决。期间有比较频繁的网络环境变化(wifi、4g以及无网络)，可能跟这个有关。

在有root权限的情况下开着影梭，不管是选全局代理还是分应用代理，也不管路由那里是哪个选项，一段时间过后均出现无法访问任何网络的情况。有时候关闭影梭可以解决，有时候重启手机才能解决。勾选了“自动启动”选项话，app里的开关不起作用，必须把勾去掉并重启手机，或者卸载重装才能解决(我已重装了好几次了)。

这个问题困扰了我很长间，找不到解决办法，现在我只能不开root权限，出现问题就重启影梭。
我也试过换回之前的版本(2.7.6)，发现问题比2.7.7更严重。另外我有一个朋友跟我的情况一样，他用的是一加手机，安卓系统也是4.4.4。

以上这个问题，希望能够早日解决。虽然我也很想帮忙完善这个项目，但是我不会java。python我倒是会一点，可惜没什么经验。主页上提到的那几个工具我已经下载了，我有空研究一下看能不能搞得来。

**Comment by madeye** [comment]
这是 MIUI 的问题，关闭所谓 ”神隐模式“。

**Comment by falseen** [comment]
我之前有把影梭从神隐模式的列表中去除，发现没有用。我再试试关闭神隐模式吧。
