### ISSUE TITLE
Problem with Huawei phones

### ISSUE THREAD

**Issue by dci39384** [shadowsocks/shadowsocks-android#349]
Hi,

I just tried the application with Huawei honor 3C lite and Huawei y220, it gets connected but there's no data.

The statistics windows shows send/receive numbers growing fast but there's no send/receive actually.

Both devices are running android 4.4.2 and FYI i have 4.4.2 on my galaxy note8 as well and it works just fine on it !

Thank you

**Comment by madeye** [comment]
Devices of Huawei are not supported. Try other apps, like fqrouter or any VPN solutions.
