### ISSUE TITLE
能把服务器配置和本地配置独立开吗？

### ISSUE THREAD

**Issue by DCY2013** [shadowsocks/shadowsocks-android#353]
我的意思是不要把服务器配置(如服务器地址、端口和密码之类)和本地配置(全局代理/分应用代理之类)做成一对一关系，而是独立开。配置好本地配置，然后在服务器配置里指定本地配置(最好可以设置默认配置)。

我现在遇到的问题是，添加一个服务器(比如扫描一个二维码)就要更新一大堆本地配置，还要到原来的服务器配置导出分应用代理配置，然后导入过来，挺折腾人的，导入导出分应用代理配置时又要加载几秒钟，感觉整个配置体验很不好，希望作者能考虑一下本人的建议。

**Comment by falseen** [comment]
扫描二维码会更新本地配置（其实应该叫应用配置）？我没遇到过。一般二维码是只包含服务器配置的，只要别扫那些用手机导出的二维码应该就可以了吧？(也就是包含应用配置的二维码)（说实话我真的不清楚安卓版的二维码会不会导出应用配置）

**Comment by DCY2013** [comment]
@falseen  谢谢回复，不过我纠结的不是二维码的问题，而是配置独立的问题.即使不扫二维码，我在更新本地配置的时候也需要更新所有服务器节点的配置，不然我需要更换节点的时候导出导入配置(或者说同步配置).另外二维码一般不包含本地配置(我甚至不知道可以),而像分应用代理这种配置也是无发包含在二维码里的，一是数据量大(二维码包含数据有限，如果数据太多则二维码的像素点会变高，传播会有丢失的风险[如传播时二维码图片时被压缩])，二是这个配置是根据应用id(或许叫编号？)配置的，不同的手机无法同步,因为装的应用不一样，同一个id在不同的手机里会指定不同的应用.

**Comment by falseen** [comment]
我好像明白你的意思了，之前理解错了，抱歉。我以为你说的是你扫描二维码的时候会同时导入本地配置....

原来你说的是每次添加新服务器配置的时候本地配置（路由、分应用配置等等）会变成默认的，如果是这样的话那你这个提议还是挺不错的。这两个设置确实应该分开设置，建议@madeye采纳。

**Comment by DCY2013** [comment]
@falseen  是这样。多谢。

**Comment by madeye** [comment]
No plan for this.

**Comment by DCY2013** [comment]
太遗憾了，我要是会Android开发好了
