### ISSUE TITLE
简化切换服务器操作

### ISSUE THREAD

**Issue by forkburn** [shadowsocks/shadowsocks-android#355]
目前的用户界面，要切换服务器时，需要先断开连接，选择新的profile, 然后再点连接键。如果能像PC客户端一样，一次点击就切换到新的服务器，就更方便了。不知是否能实现。

**Comment by madeye** [comment]
No plan for this.

**Comment by falseen** [comment]
应该有难度，安卓上的实现跟pc不太一样。
