### ISSUE TITLE
能否自己编辑绕过或通过的ip(或域名)？

### ISSUE THREAD

**Issue by falseen** [shadowsocks/shadowsocks-android#356]
想问下这个功能实现起来困难不？

**Comment by madeye** [comment]
No, you can't.

**Comment by falseen** [comment]
好吧，那编辑 com.github.shadowsocks文件夹下的配置文件是否有效？我看里面有一些相关的配置文件。

**Comment by madeye** [comment]
Edit `/data/data/com.github.shadowsocks/acl.list` then `chmod 600 /data/data/com.github.shadowsocks/acl.list`. Of course, you need ROOT permission to do this.

The `acl.list` is well tuned for Android. Any manual modification would cause issues.

**Comment by codexss** [comment]
acl.list每次启动软件都会重新生成，如果去掉文件可写权限的话就无法启动，这个列表为什么不能修改呢？漏掉了一些ip了哦 比如119.29.29.29 和114.114.114.114都没有包括进去

**Comment by codexss** [comment]
应该是修改这个玩了重新编译吧。
https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/values/arrays.xml
