### ISSUE TITLE
Build reports "UNRESOLVED DEPENDENCIES"

### ISSUE THREAD

**Issue by eintr** [shadowsocks/shadowsocks-android#357]
sbt clean android:package-release
says:
```
......
[error] (*:update) sbt.ResolveException: unresolved dependency: com.hanhuy.sbt#sbt-idea;1.7.0-SNAPSHOT: not found
```

The URL "http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-snapshots" in project/plugins.sbt reports 404.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/project/plugins.sbt#L5

https://oss.sonatype.org/content/repositories/snapshots/com/github/mpeltonen/sbt-idea_2.10_0.13/1.7.0-SNAPSHOT/
