### ISSUE TITLE
error 105, net::err_name_not_resolved

### ISSUE THREAD

**Issue by xufooo** [shadowsocks/shadowsocks-android#358]
the latest 2.7.7 version recently encounter an issue that report an error about "net::ERR_NAME_NOT_RESOLVED", while does libev ss-local 2.3.1 version not.
my server version is libev 2.3.1 too.
may an update will solve?
thx

**Comment by madeye** [comment]
Double check your configuration.

**Comment by xufooo** [comment]
i haven't changed its configuration... it just broke since yesterday, maybe earlier...
both of my phones got this problem under either wifi or celluar networks.
i've tried dns flush and reset, no help

**Comment by xufooo** [comment]
work now...without any configuration change

**Comment by xufooo** [comment]
fixed by configurating dnsmasq on the server
