### ISSUE TITLE
SS Server seems to be blocked after connecting it in a while

### ISSUE THREAD

**Issue by babykiss4ever** [shadowsocks/shadowsocks-android#359]
* Device: Android 4.4.2
* Shadowsocks Client version: 2.7.7
* Client config: Bypass LAN and China, Per APP without turning on the last 2 options(UDP forwarding and auto connect)
* Server location: San Francisco
* Encryption method: RC4-MD5 and AES-256-CFB
* Location: Shanghai, China Telecom

After connecting the server for a while( maybe 10 minutes- or 1 hour+ ), it seems that the connection has been blocked by GFW and other devices via the same LAN can't even **ping** the server as well.

I have to resolve this problem by redial ISP via the router's manage page.

![image](https://cloud.githubusercontent.com/assets/4182346/9726253/1e0f8358-5623-11e5-90f0-554babeca53d.png)

**Comment by madeye** [comment]
It's an issue of your network, not shadowsocks.
