### ISSUE TITLE
Per-app on Lolipop 5.0 (VPN mode, non-root) and udp forwarding

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-android#360]
Hi!

First and foremost, I did google (and thus did read several other things people have asked about shadowsocks + udp here)

From reading previous "Shadowsocks+per-app udp" questions, I've got the impression that on Lolipop, UDP forwarding occurs per-app

I have a Lolipop 5.0 device (rooted, BUT launching Shadowsocks without root so it goes into VPN mode)

I select per-app proxy, bypass mode, select Chrome and Google Service things (Play, Play Services, Service Framework) for proxyfication

Now, if I DO NOT check "forward UDP", Chrome does not connect.

To make sure that no rules interfere, I did iptables -F, the outcome is the same.

This is weird.

It was my understanding from reading other stuff that on Lolipop+ UDP should be forwarded per-app, and thus apps whitelisted via "per app proxy bypass modes" would be doing fine without UDP forwarding.

If UDP forwarding is per-app, and google stuff is also whitelisted, UDP from Chrome should go through wlan0 without issue

So, my questions are:

Does Shadowsocks in VPN mode perform per-app UDP forwarding (on Lolipop and above)?

If yes, why does disabling UDP forwarding cause issues with apps that were whitelisted via per-app selection interface.

If no, is there a mode for Shadowsocks that would allow me to do per-app UDP forwarding on Lolipop ?

**Comment by madeye** [comment]
> Does Shadowsocks in VPN mode perform per-app UDP forwarding (on Lolipop and above)?

Yes.

> If yes, why does disabling UDP forwarding cause issues with apps that were whitelisted via per-app selection interface.

Android has a system-wide DNS resolver / cache for all the apps.

**Comment by DamienGrand** [comment]
Interesting.

I've installed dnscrypt, activated it, and added following iptables rules 

iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:53
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53
iptables -t nat -A OUTPUT -p udp m owner --uid-owner 0 --dport 53 -j DNAT --to-destination 
iptables -t nat -A OUTPUT -p tcp m owner --uid-owner 0 --dport 53 -j DNAT --to-destination 127.0.0.1:53

(I realize the last two are redundant, but you know, just to make sure)

Same behavior.

However, when I activate udp forwarding, the ipleak.net tester shows dnscrypt's dns servers instead of my home or google.

Since I'm no coder, could you please go into more detail on how android's dns resolver interacts with Shadowsocks's udp forward / per-app udp forward on Lolipop+ ?
