### ISSUE TITLE
Build problem: missing EnclosingMethod attribute?

### ISSUE THREAD

**Issue by epitron** [shadowsocks/shadowsocks-android#362]
I'm not sure what's causing this problem -- I managed to build all the NDK components, and got through most of the SBT build process, but it breaks when trying to prepare the `classes.proguard.jar`.

I've pasted the sbt build output into a text-file here: http://ix.io/kTo

I'm running Arch Linux, with Java 1.8.0, and the appropriate Android APIs.

This is my sbt about information:

```
$ sbt about
[info] Loading project definition from /home/epi/src/shadowsocks-android/project
[info] Set current project to shadowsocks (in build file:/home/epi/src/shadowsocks-android/)
[info] This is sbt 0.13.8
[info] The current project is {file:/home/epi/src/shadowsocks-android/}shadowsocks-android 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.4
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, android.AndroidPlugin, android.Plugin, org.sbtidea.SbtIdeaPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
```

Thanks!

**Comment by madeye** [comment]
Java 1.8.0 is not supported.

**Comment by madeye** [comment]
http://stackoverflow.com/questions/24662801/bad-class-file-magic-or-version

**Comment by epitron** [comment]
Thank you! :D
