### ISSUE TITLE
Cannot add profile by QRCode

### ISSUE THREAD

**Issue by xclimbing** [shadowsocks/shadowsocks-android#365]
This project is great. Thank you very much.

I'm from the China  called mainland and we cannot use google play here. so I cannot install QRCode Scanner. When I use shadowsocks-android for a QRcode new profile, it look for the QRcode Scanner.

In fact, We just need the "SS://.... " URI by the QRcode. Would you like to add a new function that just read a "ss://..." URI directly for a new profile? I can get the URI from other QRcode Scanner or sent from IM.

thank you.

**Comment by madeye** [comment]
Download any QR code scanner from 3rd party App store.

**Comment by xclimbing** [comment]
I really installed a QRcode scanner from 3rd party. But When I add a profile by QRcode in your APP, it still look for QRcode scanner from google play.

**Comment by madeye** [comment]
Scan the QR code in your app and click the recognized URI.

**Comment by xclimbing** [comment]
Repeat: **I CANNOT Scan the QR code in my APP**!!!

## 1. ShadowSocks-Android Version
![1](https://cloud.githubusercontent.com/assets/9360857/10085804/b8b5ee70-633d-11e5-8d43-8fa6a749d21c.png)
## 2. Add a Profile by Scan QR code
![2](https://cloud.githubusercontent.com/assets/9360857/10085846/e600fb4a-633d-11e5-876c-bc92107ec4fd.png)
## 3. Requires Barcode Scanner 
![3](https://cloud.githubusercontent.com/assets/9360857/10085880/fdcdf8d6-633d-11e5-81dc-d485c63bd66c.png)
## 4.Click Yes will lead to App Store(google play)
![4](https://cloud.githubusercontent.com/assets/9360857/10085934/3ff31dc2-633e-11e5-8cb6-837272a1e0d6.png)
## 5. Job failed.

## 6. There is no direct way for an URI to recognized in ShadowSocks-Android.

## 7. I need the function that Adding a profile by URI NOT by QR code in ShadowSocks-Android.

## 8. Have any idea?

**Comment by madeye** [comment]
Scan the QR code in any QR scanner app and click the recognized URI.

The recommended QR app is http://www.coolapk.com/apk/tw.com.quickmark

**Comment by xclimbing** [comment]
Thank you. but the QuickMark cannot work on my cell phone. finally I download a Barcode Sanner from the coolapk.com and it works fine. 

Thanks again!
