### ISSUE TITLE
Randomly disconnects after short time connected

### ISSUE THREAD

**Issue by CoolOppo** [shadowsocks/shadowsocks-android#367]
I am having issues with the app staying connected. I can connect to my server, and it works for about a minute. Without any message appearing, it disconnects. I have tried the `CHACHA20` and `aes-128-cfb` encryption methods, but both have the issue. My friend is able to connect and use my server just fine.

**Comment by madeye** [comment]
Your system or any 3rd party app killed shadowsocks' background service. Check this carefully.

**Comment by CoolOppo** [comment]
I don't have any apps that would do something like this, so how can I find out what's making Android itself shut down the app? Also, if Android itself is what's shutting down the service, shouldn't that be fixed?

**Comment by madeye** [comment]
If you're sure that no `app killer` like apps are installed on your system, it means the Android system on your phone is broken. To fix this, report this issue to your phone's manufacturer or try some AOSP based ROM, e.g. Cyanogenmod.

**Comment by CoolOppo** [comment]
I have a Nexus 5 running the stock ROM. I don't have any apps like that installed either, so are you completely sure that this isn't an issue with the app?

**Comment by madeye** [comment]
Shadowsocks works fine on Nexus 5 with stock ROM. Double check your config, make sure your client's configuration is consistent with the server's.

**Comment by CoolOppo** [comment]
It definitely is. Like I said, it connects and works just fine for around a
minute, but disconnects after that for seemingly no reason.

**Comment by CoolOppo** [comment]
Well, I completely wiped my phone and installed the latest Android M preview. Everything is working perfectly now.
