### ISSUE TITLE
新版的一次性验证有什么作用？有没有详细的说明呢。

### ISSUE THREAD

**Issue by falseen** [shadowsocks/shadowsocks-android#370]
rt，不懂c，想知道“一次性验证”具体是干什么的，不知能否说明一下。谢谢。

**Comment by madeye** [comment]
shadowsocks/shadowsocks#69
shadowsocks/shadowsocks#64
Long-live-shadowsocks/shadowsocks@ccd1c0b

**Comment by moerfutin** [comment]
请问服务端需要配置吗

**Comment by moerfutin** [comment]
最新ss封锁太厉害了，很多人用着360 ，还用ss，智商堪忧啊。
另外发现源码里更新了插件，请问这个有啥用？ 
https://oss.sonatype.org/content/repositories/snapshots/
这是截屏功能？》
