### ISSUE TITLE
滴滴出行无法显示腾讯地图

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-android#371]
由于ss常开，滴滴出行一直无法显示地图（只出现车辆），以为是滴滴问题，今天把ss关了，发现地图可以显示正常了。

起初以为是路由的问题，地图走代理了，我就把ss设置成全局（不绕过局域网和大陆地址），开关飞行模式清空dns缓存，启动ss后，发现地图能正常显示的，不存在问题。

1.只要设置成绕过局域网和大陆地址就不正常显示地图。
2.版本2.7.x和2.8问题一样，再早的版本我就没试过了。
3.每次测试时候我都清空了滴滴的缓存（好像地图缓存还是在的，不过移动到以前没显示过的地方可测试）。

4.nat和VPN模式都出现一样的问题。

**Comment by madeye** [comment]
Bypass this app in VPN mode.

**Comment by dutonttie** [comment]
我以前一直用全局模式+绕过局域网和大陆地址的。
唉！只为了它要用分应用代理吗？
2015年10月1日 06:35，"Max Lv" <notifications@github.com>写道：

**Comment by falseen** [comment]
影梭是基于ip判断的，所以可能的情况是你用的这个app需要同时连接国内和国外的ip，并且要求只能用一个ip连接，而你却用了两个ip。

**Comment by falseen** [comment]
另外听说国内的各大网站部署了一种脚本，用来检测当前访问者是否翻墙。而这种脚本的原理就是让访问者同时访问属于同一域内的不同地区的两个服务器（同一个会话），这两个服务器一个在境内，一个在境外。你的问题可能就是属于这种情况。

其实你用分代理也可以很好的解决这个问题，分代理中选择这个app，打开绕行模式。这样的话就可以绕过这个app。
