### ISSUE TITLE
Building in IntelliJ IDEA

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#377]
I can build in terminal now but I can't seem to get it work in IntelliJ IDEA. I have imported `build.sbt`, added `src/main/aidl` as source and configured paths in Modules - Android. But it seems the dependencies wasn't included. What am I missing?

Error log:

    Error:(38, -1) android-apt-compiler: [shadowsocks-android] /shadowsocks-android/src/main/res/values/styles.xml:38: error: Error: No resource found that matches the given name: attr 'menuDrawerStyle'.
    Error:(72, -1) android-apt-compiler: [shadowsocks-android] /shadowsocks-android/src/main/res/values/styles.xml:72: error: Error retrieving parent for item: No resource found that matches the given name 'Widget.MenuDrawer'.
    Error:(73, -1) android-apt-compiler: [shadowsocks-android] /shadowsocks-android/src/main/res/values/styles.xml:73: error: Error: No resource found that matches the given name: attr 'mdActiveIndicator'.
    Error:(74, -1) android-apt-compiler: [shadowsocks-android] /shadowsocks-android/src/main/res/values/styles.xml:74: error: Error: No resource found that matches the given name: attr 'mdMenuSize'.

**Comment by madeye** [comment]
`sbt gen-idea no-classifiers`

**Comment by Mygod** [comment]
I have switched to `sbt "gen-idea no-classifiers"`. Now dependencies are showing in SBT projects window, code analysis for scala code seems to work fine too but I still got the same errors when building.

**Comment by madeye** [comment]
Actually, I never build this project in IDE. So, I suggest to build it with sbt in the command line.

**Comment by yuiopt** [comment]
那这个项目不在ide里写，不太方便吧，试过这个sbt gen-idea了，需要在~/.sbt/0.13/下面添加个gen-idea.sbt 文件，要下载个依赖，但是scala的版本升到2.11了，所以那个 
resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.7.0-SNAPSHOT")  

好像也不管用了，https://oss.sonatype.org/content/repositories/snapshots/com/github/mpeltonen/sbt-idea_2.11_0.13/1.7.0-SNAPSHOT/sbt-idea-1.7.0-SNAPSHOT.pom  这个链接是不存在的，主要是sbt-idea_2.11_0.13这个目录没有，版本不对

**Comment by pexcn** [comment]
一直很好奇这个项目的开发流程是怎样的，难道仅 vim + scala 插件？请问有语法提示吗？@Mygod @madeye
