### ISSUE TITLE
Samsung S6(edge)  app closed by OS

### ISSUE THREAD

**Issue by octf** [shadowsocks/shadowsocks-android#378]
Samsung's flagship Galaxy S6 series have poor RAM management: RAM is overused and system frequently forces closing many background apps including shadowsocks. That makes shadowsocks unable to run continuously for 10 minutes in most cases before it's got closed and VPN connection got lost.
Some workaround for these phones is highly needed.

**Comment by madeye** [comment]
Try any other AOSP based ROM.

**Comment by octf** [comment]
I disagree. 
While Galaxy S6 does force closing background apps aggressively, some apps are not affected, like GSam Battery Monitor and Pixel Filter. Apps like shadowsocks should be designed to run as a permanent service, and flag itself not to be killed by OS. This is a design bug, Galaxy S6's memory problem merely amplifies this issue.

On the other hand, I tried shadowsocks in Cyanogen on an older phone. This problem persists; just not so easy to reproduce.
