### ISSUE TITLE
为何不支持华为设备？技术原因是？

### ISSUE THREAD

**Issue by hnbly** [shadowsocks/shadowsocks-android#383]
我想问一下为何很多华为设备使用都有问题，表现为进程没被杀但连不上网络。技术层面的具体原因是什么？海思的内核驱动方面的原因还是ROM方面的原因。

**Comment by madeye** [comment]
It's a bug of Huawei.

**Comment by hnbly** [comment]
能否稍微说具体一点？

**Comment by hatogit** [comment]
I can't add any technical information. But on my Huawei Phone, when the processes are NOT killed, shadowsocks works really fine. But for reasons unknown to me, com.github.shadowsocks, ss-local and  ss-local will be killed eventually (shadowsocks had already been whitelisted), only com.github.shadowsocks:vpn survives. So I think it's still an issue of Huawei's buggy rom.

**Comment by dequn** [comment]
It looks like it's Huawei's ROM bug.
