### ISSUE TITLE
如何去除下拉的Stop the service

### ISSUE THREAD

**Issue by heiybb** [shadowsocks/shadowsocks-android#384]
使用过程中很少用到这个按钮，想自己编译一个版本去除这个选项，需要怎么做？

**Comment by madeye** [comment]
去掉这两行：

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L121

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ShadowsocksNatService.scala#L327

**Comment by HooinKyoma** [comment]
其实直接长按点击详细信息，去掉显示通知的选项就可以了。
