### ISSUE TITLE
分应用代理列出的应用清单与系统 设置->应用->全部 中列出的不一致

### ISSUE THREAD

**Issue by karevos** [shadowsocks/shadowsocks-android#386]
Xperia Z3。
分应用代理列表中没有“USB连接”或"com.sonyericsson.usbux“这个应用，却列出了我曾用 pm disable 禁用过的应用，与系统 设置->应用->全部 中列出的应用不一致。

**Comment by madeye** [comment]
Only user's apps are listed, no system apps.

**Comment by karevos** [comment]
对于 com.sonyericsson.setupwiz、电话、What's New、Android System WebView 等应用，按你的说法，他们都是 user‘s apps 咯？你的说法明显解释不通。

**Comment by ShaolinZhang** [comment]
They are actually User's apps. System App is defined as apps under the
folder /system/priv-app

On Sun, Oct 11, 2015 at 10:47 AM karevos <notifications@github.com> wrote:

> 对于 com.sonyericsson.setupwiz、电话、What's New、Android System WebView
> 等应用，按你的说法，他们都是 user‘s apps 咯？你的说法明显解释不通。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shadowsocks/shadowsocks-android/issues/386#issuecomment-147149128>
> .
>
-- 
Shaolin Zhang
Shanghai World Foreign Language Academy

**Comment by karevos** [comment]
谢谢张君的说明，这样解释就清楚多了。
