### ISSUE TITLE
创建连接之后无法访问网络

### ISSUE THREAD

**Issue by UISAHF** [shadowsocks/shadowsocks-android#387]
下拉VPN菜单之后只有几百个数据包 完全无法访问网络 同一局域网下的PC则正常使用 更换服务器也如此 手机无法使用 PC正常
2.8.1 2.7.7等几个版本都尝试过了 表现一致
手机系统MIUI7 5.8.13(Android 5.0.2) MIUI7 5.10.9(Android 5.1.1)表现皆一致 已关闭省电模式&神隐模式

**Comment by madeye** [comment]
MIUI is not supported.

**Comment by falseen** [comment]
重置和刷新dns缓存都试一下，我这里miui开发版可以用。
