### ISSUE TITLE
A possible reason for shadowsocks not work properly on HUAWEI devices?

### ISSUE THREAD

**Issue by hatogit** [shadowsocks/shadowsocks-android#388]
As I just commented in #383, not like what was said by the op in that issue, when the processes are not killed (all related process, not just com.github.shadowsocks:vpn), shadowsocks actually works well on my Huawei Phone (both android 4.4.2 and 5.1.1 were tried). But the ss-local and tun2socks will be killed (or crash, no information available in logcat) eventually for unknown reasons.
But I just observed another interest thing, the tun device used by shadowsocks (actually tun2socks I think?) has an MTU of 1500, but as I know, some (maybe all, I'm not sure. I checked Honor6 plus and mate 7, all the same) HUAWEI phones set the MTU for wlan0 and rmnet0 as 1400.
If I understand it correctly. the MTU of the tun device should at least not greater than 1400 in this case, am I right?

**Comment by madeye** [comment]
Nope, it's not related to MTU. Misconfigured MTU would cause slow link, not crash.

As you mentioned, HUAWEI has a very aggressive background service killing strategy, which kills shadowsocks' service regardless of that they are forked by a VPNService.

**Comment by hatogit** [comment]
Yes, you were right. I just caught the killing in progress:
I/AppsCleanUp( 4870): Clean Apps Num:4, clean type is 1

**Comment by hzhr** [comment]
目前，ss启动后的进程布局为（举例）：
进程名                                           PID           父PID
com.github.shadowsocks              1234         xxx
com.github.shadowsocks:vpn       1235         1234
ss-local                                          1236         1
tun2socks                                      1237         1

后面几个native进程，由于其父PID为1，即成为了所谓的daemon进程，反而容易被系统误认为是垃圾进程而清理掉，因为Android下其实很少app会这样启daemon进程。
对比之下，fqrouter没有启动父PID为1的native的daemon进程，所以它的进程不会被清理，反而可以比较稳定运行。

实验了一下，将ss的几个native进程改为非daemon进程，改完后运行时布局如下：
进程名                                           PID           父PID
com.github.shadowsocks              1234         xxx
com.github.shadowsocks:vpn       1235         1234
ss-local                                          1236         1235
tun2socks                                      1237         1235

运行了好几天，几个native进程都没有被清理掉，比较稳定了，问题解决。

所以建议一下ss也做下workround，不要启动daemon进程，规避一下问题。
说实话，无法去指责或期望厂商去改正问题，或者让用户去换ROM什么的，但ss可以做最好的自己，让更多的人受益。

胡乱改的，代码比较烂，就不提交了patch了，有人有同样的问题可以自己试着去解决，也希望正式版能解决一下问题  ;-)

**Comment by madeye** [comment]
@hzhr Thanks, very helpful.

**Comment by hyxxsfwy** [comment]
华为荣耀6，EMUI3.1最新稳定版，Android5.1.1，v2.94已经可以完美运行，特来报告。

**Comment by chinalu** [comment]
华为mate7，目前升级到Android6了，还是存在这个问题，shadowsocks版本是2.10.8，是华为策略变了，还是。。。

**Comment by swors** [comment]
emui5 也存在这个问题
是否有解决的想法 或者 建议?  @madeye

**Comment by dequn** [comment]
I encount this problem in Emui 5.0 B397 recently.

**Comment by baoming** [comment]
华为note v8
emui 5.0.1 
android 7.0
B356
不能用

**Comment by dyj2012** [comment]
华为v10 可以使用,但是需要手动输入账号,无法通过freess扫描二维码的形式添加免费账户

**Comment by dequn** [comment]
@xgdgsc 有效。
