### ISSUE TITLE
从通知栏里断开连接后，主程序界面仍然显示连接连接状态为On

### ISSUE THREAD

**Issue by forkburn** [shadowsocks/shadowsocks-android#389]
在通知栏里选择Stop the service后，打开SS主程序，连接状态却仍显示为on。如需重新连接，用户要先把连接状态切换为off，然后再切换到on，比较不方便。

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-android/commit/bb81fe13394c6f71f46642361edcafd36da491c9
