### ISSUE TITLE
GCM push misbehavior when using shadowsocks to proxify GCM

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-android#392]
Hello!

Caught GCM misbehavior.

System is as follows:
Android 5.0, shadowsocks-android v2.8.1

Not rooted. Running in VPN mode

Per-app proxification on (with Bypass mode on), but Google Play and Google Play Services not chosen (are not bypassing VPN)

Route: All

UDP on

IPv6 on

*Misbehavior:*
GCM coonection often breaks with "err:FIN" message and has to reconnect (about every 20-25 seconds)

GCM Debug log looks like:

![screenshot_2015-10-13-02-49-02](https://cloud.githubusercontent.com/assets/14230915/10448132/49dcc5e6-7193-11e5-95ca-177d3df3769e.png)

I suspect that it is due to connection timeout in Shadowsocks-android defaulting to 10 seconds.

Is there a way to manually change it to, say. 600 seconds (I run my own shadowsocks server so "stale" connections do not concern me much) ? If no, could you add such an ability to the UI ?

Thank you very much!

**Comment by madeye** [comment]
The default timeout is 600s: https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L329

Also I cannot reproduce your issue on both WiFi and LTE. My suggestions are:
1. Check your server's connection.
2. Disable IPv6 in the app.

**Comment by DamienGrand** [comment]
I've just navigated to shadowsocks data folder (/data/data/com.github.shadowsocks) and when VPN service is running, the ss-local-vpn.conf file clearly states

"timeout" : 10

(which is weird)

Tried disabling ipv6, nothng changed, still err:FIN every 15-20 seconds.

Checked the server, seems to be fine

**Comment by madeye** [comment]
The default timeout in the config file is 10s, but overridden by the command line arg `-t`. It looks quite confusing, and I will fix it soon.

BTW, according to your log, the close error is FIN, not RST. Shadowsocks sends RST when closing TCP connection after timeout (not graceful but working well).

**Comment by DamienGrand** [comment]
Okay, thanks for explaining, will try to poke around my server's hosting company, maybe it's something on their end

**Comment by madeye** [comment]
It seems an issue of tun2socks. If your phone is rooted, try to long press `shadowsocks` in the app to enable NAT mode.

**Comment by DamienGrand** [comment]
Interesting, the issue disappeared after rebooting the vps that hosts my shadowsocks server (restarting shadowsocks itself didn't help)


Anyway, it would be nice to have a UI way of configuring timeout, just in case :)
