### ISSUE TITLE
one time authentication doesn't work with shadowsocks-libev

### ISSUE THREAD

**Issue by andronoob** [shadowsocks/shadowsocks-android#393]
Log at server side:
 2015-10-16 14:56:07 ERROR: failed to handshake with [client_ip]
 2015-10-16 14:56:08 ERROR: authentication error 1

**Comment by madeye** [comment]
shadowsocks-libev > 2.4.0

**Comment by andronoob** [comment]
I'm using shadowsocks-libev 2.4.0 and shadowsocks-android 2.8.2 now.
If one time authentication is disabled at server side, shadowsocks-android will work properly, no matter whether auth is enabled at client side, but ss-local doesn't work with one time authentication enabled, ss-local works if auth is disabled.
If auth is turned on at server side, only ss-local works, if auth is enabled at client side, too. shadowsocks-android doesn't work, no matter whether auth is enabled.

**Comment by andronoob** [comment]
Sorry...I rebooted my phone, then shadowsocks-android seems to work properly now.
