### ISSUE TITLE
A curious issue with a particular website in Google Chrome with shadowsocks android 

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-android#394]
System is as follows:
Android 5.0, shadowsocks-android v2.8.1

Not rooted. Running in VPN mode

Shadowsocks in global proxy mode (easier to reproduce this way)

Route: All

UDP on

IPv6 on

Iptables flushed completely to ensure nothing messes with shadowsocks's normal operation

*Problem*

When I browse to certain pages, .css and many other assets appear not to load via shadowsocks

Example page:
[http://m.geektimes.ru/post/264102/comments/](http://m.geektimes.ru/post/264102/comments/)

When Shadowsocks is enabled, page ends up like this (Chrome, latest version):

(https://cloud.githubusercontent.com/assets/14230915/10560423/a36ec630-7513-11e5-8989-dc0ca2a1d2a1.png)

When Shadowsocks is disabled, the page finally loads okay

(https://cloud.githubusercontent.com/assets/14230915/10560428/034fb938-7514-11e5-983f-9310b431a93b.png)

Clearing browser cache, rebooting, changing DNS behavior (iptables redirect to dnscrypt vs normal google way) do not affect the behavior.

Disabling IPv6 does not affect this behavior.

Issue does not reproduce in Firefox.

Issue reproduces in Opera too.

**Comment by madeye** [comment]
It looks like a server specific issue, related to DNS and CDN. With my servers located in Hong Kong and Singapore, I cannot reproduce this issue.

I suggest to try a Russia based VPS, to see if this page can be loaded correctly.

**Comment by DamienGrand** [comment]
After fiddling about with different servers and settings for a while, I've figured it out.
It was an MTU thing

As long as MTU > 1450 for tun0 interface, the problem persists. 
Lowering MTU for tun0 to 1450 or lower via adb or terminal solves the issue.

Reporting just in case someone else runs into similar behavior.
