### ISSUE TITLE
IPv6 shadowsocks server can't connect in version 2.8.2

### ISSUE THREAD

**Issue by heyeshuang** [shadowsocks/shadowsocks-android#395]
When I try to connect to some server like [xxxx:yyyy::aaaa:bbbb] or some  domain name to this IP ,it tells "已连接" but chrome says "DNS_PROBE_FINISHED_NO_INTERNET", trying to connect the IPV4 address of the same server works well. Both 4.4 and 5.1 (NAT or VPN mode) have this issue. 

log says "failed to resolve server name, wait xx seconds"

It works correctly in previous version in google play.

By the way, the tests of the server and the IPV6 environment seem fine.

**Comment by madeye** [comment]
> log says "failed to resolve server name, wait xx seconds"

It means the server address typed is incorrect, shadowsocks is unable to bind to that address.

Try:
1. Remove `[` and `]` in your address.
2. Remove any white space in your address.

**Comment by heyeshuang** [comment]
Removing [] solves the problem. Thanks.
