### ISSUE TITLE
IPv6路由功能的问题

### ISSUE THREAD

**Issue by liangrx** [shadowsocks/shadowsocks-android#398]
我的情况如下：服务器同时接入v4v6，监听v4v6地址。本地v4v6双栈，使用Windows客户端时，连接服务器的v4或者v6地址均能同时访问v4和v6站点，test-ipv6.com测试我的v4v6地址均为代理服务器ip，运营商均为代理服务器ISP。
Android版本4.4.4，客户端版本2.8.2，非root环境使用VPN模式：
关闭IPv6路由功能的情况下，连接服务器v4地址或v6地址，v4v6站点均能访问，v4流量走ss代理，v6依旧直连。test-ipv6.com显示我的ipv4地址为代理服务器的ip，ipv6地址为本地ISP提供的本机地址。
开启IPv6路由功能的情况下，无论连接服务器的ipv4或ipv6地址，均只能访问ipv4站点而无法访问ipv6站点，test-ipv6.com显示我没有ipv6地址，无法接入ipv6网络，纯ipv6站点对我来说就像ban掉了。
貌似IPv6路由功能没有起到预期作用。请问这是bug还是我设置上有问题？

**Comment by madeye** [comment]
IPv6 route on devices below Android 5.0 cannot work properly due to the buggy IPv6 VPN support of Android.

Try to upgrade your device to Android 5.0 or above.

**Comment by liangrx** [comment]
明白了，谢谢解答
