### ISSUE TITLE
A small feature request (would be useful for testing) - expose VPN's DNS, MTU and shadowsock's timeout for modification

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-android#399]
Hello!

Would it be possible to expose 
1) DNS used by VPN (currently hardcoded to goog's dns)
2) MTU for tun interface (right now I'm tuning it manually after every shadowsocks connect)
3) timeout setting of shadowsocks

as options, either in GUI (maybe a hidden menu for power users) or in "advanced config" file in app's folder ?

**Comment by madeye** [comment]
Sorry, I've no plan to expose these options. I suggest to modify the source code yourself and compile your own App.
