### ISSUE TITLE
Maybe remove the status in status bar

### ISSUE THREAD

**Issue by Kai-Zhang** [shadowsocks/shadowsocks-android#400]
Latest version puts a status in status bar which cannot be canceled.
In some way I'd like to have this run silently. I keep it running background and not really want to know it has running perfectly since the VPN icon will always tell me that.
Would you mind at least adding an option for that?
Thanks a lot.

**Comment by CoolOppo** [comment]
I completely agree. It's very annoying having a notification taking up space.

**Comment by madeye** [comment]
Unfortunately, you cannot do that. It's a requirement for keeping the service running in the background.

**Comment by Kai-Zhang** [comment]
But it happens only in the latest version...
Before this how does shadowsocks work?

**Comment by madeye** [comment]
If you do not care the issue mentioned above. Long press the notification and check "Never show notification from this app".

**Comment by Kai-Zhang** [comment]
Mmmm...Yet I'm still confused about the relationship between notification and background service. So if I mute the notification the service may not be running even the VPN is still on? And so is it in old version and I just didn't notice?

**Comment by Lavande** [comment]
记得之前显示的是VPN图标，最近显示的是圆圈1，即有一条通知，于是老想去看看……然后发现不是新消息，不知道是因为我root的原因还是新版的改动，请问这个可以设置成VPN图标而不要提示1条消息吗？
