### ISSUE TITLE
Any way to know whether connected to server or not

### ISSUE THREAD

**Issue by coolxll** [shadowsocks/shadowsocks-android#401]
Right now, there is no way to know whether **the connection to shadowsocks server** is successful or not, the only way to test is to open a chrome browser and type some web site like google.com/youtube.com etc...

Is it possible to add a feature to let user know whether current network is connected or not..Just for easy test the connectivity to the ss server, which is quite useful.

**Comment by madeye** [comment]
No plan for this.
