### ISSUE TITLE
Question about mapping tcp flows

### ISSUE THREAD

**Issue by anikravesh** [shadowsocks/shadowsocks-android#402]
Hi @madeye , I am running tcpdump on my Android device while forwarding the traffic to a shadowsocks proxy. I am able to see 4 different tcp connections (4-tuples)  in wireshark for a single tcp connection (downloading a file using HTTP get):

1. proxy server <-->  wifi private addr
2. localhost <--> localhost(socks)
3. webserver -->  wifi private addr
4. wifi private addr <-- localhost

3 and 4 are actually a single tcp connection with different src/dst ips. What I want to do is to map (1) and (2) to its corresponding (3,4) connection. So, assuming that I open  more than one tcp connection on my phone, for each (3,4), I want to find its corresponding (1) and (2) connections. It would be great if I log the port mapping (what local port is being used for 1,2,3,4) for each connection in run time. I would appreciate it if you could tell my what part of code I could log these mappings when a tcp connection is being established.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/jni/badvpn/tun2socks/tun2socks.c#L88

**Comment by anikravesh** [comment]
Thanks for your prompt reply. I put Android log (__android_log_print) messages in different parts (insert_connection, main, etc) of the file (tun2socks). But it seems they never get called after building, installing and running the app. I verified that by running ps command and it turns out tun2socks is not running (although socks proxy was  running properly).

Basically, when a tcp connection is being established, I want to log **following port address A and B**:
*Connection1*:
```
      proxy server <--> wifi private addr (**port address A**)
```
and
*Connection2*:
```
      webserver --> wifi private addr (**port address B**)
      wifi private addr (**port address B**) <-- localhost
```

Another solution might be to decrypt the payload of *Connection1*  and map it to un-encrypted payload of *Connection2*. I am using TABLE encryption method.

Thanks!

**Comment by madeye** [comment]
It seems you're using a rooted device with shadowsocks running in NAT mode. Then just run `conntrack -L` to dump all NAT sessions from netfilter. You may need to cross compile `conntrack` to Android
