### ISSUE TITLE
绕过大陆地址的BUG

### ISSUE THREAD

**Issue by piscesmk2013** [shadowsocks/shadowsocks-android#404]
设备是nexus5 系统是android 6.0
shadowsocks已经勾选了绕过中国大陆地址，但是chrome打开百度IP还是我服务器的地址，然后我试过在分应用代理里勾选了chrome，让chrome不代理，但是结果依旧如此。
我还重新刷过系统和卸载重装过shadowsocks，并没有用，望修复
而且我在多次开关SS之后发现会突然变好了，但是没过多久又会这样
![screenshot_20151028-154723](https://cloud.githubusercontent.com/assets/4004730/10782558/43249f30-7d8c-11e5-90dc-af38be9d28dc.png)
![screenshot_20151028-154735](https://cloud.githubusercontent.com/assets/4004730/10782559/43286250-7d8c-11e5-8e3c-5ba55ed441b2.png)

**Comment by madeye** [comment]
Use VPN mode instead.

**Comment by a2232189** [comment]
同样问题。然而我本来就是VPN MODE

**Comment by a2232189** [comment]
@madeye

**Comment by a2232189** [comment]
@piscesmk2013 @madeye 已解决。
@piscesmk2013 请关闭chrome的“节省流量”功能

**Comment by falseen** [comment]
我一直都开着节省流量，没发现问题。

**Comment by a2232189** [comment]
@falseen 我开节省流量，用百度搜索“ip”二字会出现vps的地址，关闭节省流量后，出现的是国内我的ip地址。ss已设置为绕开局域网及中国大陆ip。

**Comment by piscesmk2013** [comment]
@a2232189 可是我没开过chrome的流量节省。。这问题是时有时无

**Comment by Mygod** [comment]
@a2232189 使用流量节省不代表会隐藏你的 IP。

**Comment by a2232189** [comment]
@Mygod 有道理

**Comment by akiori** [comment]
我遇到了类似的问题但我好像从没有正常过....上不去学校内网网站, 上taobao自动变成了国际版..
