### ISSUE TITLE
开发者你好，我反映一个问题：2.8.3版本在我红米手机上会突然失效的现象。

### ISSUE THREAD

**Issue by ruleroller** [shadowsocks/shadowsocks-android#407]
2.8.3版本会突然失效，连上之后，钥匙的图标也出现了，但其实所有网络都已被断开，重新启动手机，才能够暂时正常使用，用一段时间之后，如果我关掉客户端，下次再次想连上时，又有很大的几率会出现网络被接管后无法使用的情况，只得重启解决。我尝试过清理缓存，删除客户端，重新安装，重新添加ss服务器信息，依旧会出现这个情况。

一直一路更新使用下来，到目前只发现在使用2.8.3版本时存在这个问题。

我的手机时很古老的红米一代，系统是 4.2.1 HM2013022

现在已暂时用回2.7.7。

**Comment by falseen** [comment]
有没有给root权限？我的也是红米，只要给了root权限就会出现这种问题。你试试不给root权限，让它以vpn模式运行。

**Comment by ruleroller** [comment]
@falseen 我一直是在没root的情况下以VPN模式运行的，全局代理勾勾也是默认勾着的，你也试试不给root权限，在你手机上会不会发生这情况吧，😄。

其它配置信息修改部分：


加密方式：aes-256-cfb
路由：绕过局域网及中国大陆地址

其它都是默认的：
UDP转发：未勾选
自动连接：未勾选

**Comment by falseen** [comment]
我一直都是以vpn模式运行的，很少出问题，只是偶尔会出现无法访问网络的问题，这时只要重置+刷新dns缓存就可以解决。

我的是红米2，系统是miui开发版。

**Comment by madeye** [comment]
MIUI is not officially supported by shadowsocks.

**Comment by DuanYu-of-CHn** [comment]
thank you.
