### ISSUE TITLE
关闭shadowsocks后手机没信号

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-android#409]
索尼Z2，5.1系统。
从某一个版本起，一旦关闭shadowsocks后手机信号就没了，wifi还能正常使用，必须重启手机才能恢复正常，我稍后再仔细测试一下看能否提供更详细的信息。

**Comment by madeye** [comment]
Shadowsocks has nothing to do with the cellular network. It'd be a bug of your device or ROM, or any third party apps (e.g. firewall) on your phone. Try:

1. Make sure you are using VPN mode, not NAT mode.
2. Factory reset your phone.
3. Flash other ROMs.
