### ISSUE TITLE
[Xiaomi Redmi Note2] cannot use it normally

### ISSUE THREAD

**Issue by DuanYu-of-CHn** [shadowsocks/shadowsocks-android#421]
i'm a Chn boy.and i use shadowsocks about one years.but,since the build 2.8.2(may be),i cannot use it normally.oh,i used personal servers and i used it normally on winodws.therefor,i borrow my friend's htc d816.then,it cannot work ,too.in a way,i do not know the reason.please help me.
PS:i'm so sorroy that my english is so poor i cannot discrib the issue.and i guess you can not use chinese.

**Comment by madeye** [comment]
Duplicate with #407
