### ISSUE TITLE
Add a wiki

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#423]
It would be helpful to add a wiki including content like:

* https://github.com/shadowsocks/shadowsocks-android/issues/347#issuecomment-132835956
* https://github.com/shadowsocks/shadowsocks-android/issues/405
* https://github.com/shadowsocks/shadowsocks-android/pull/414#issuecomment-154915710

**Comment by madeye** [comment]
Added https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ

**Comment by Mygod** [comment]
A Chinese version will be great so that we can add a link to the page in the app. :stuck_out_tongue:
