### ISSUE TITLE
Use more intelligent bypass strategy

### ISSUE THREAD

**Issue by Kai-Zhang** [shadowsocks/shadowsocks-android#426]
I found when use Weibo official app or just connect to Github on my mobile, it will be much slower if I turn ss on. I suppose the "bypass China" strategy may not be intelligent enough because this barely happens on PC ss client using PAC...Maybe ss can support PAC? Maybe also update and edit?

**Comment by Kai-Zhang** [comment]
I'm sorry. I can't find which issue mine duplicates with...

**Comment by madeye** [comment]
#49 and #212

**Comment by Kai-Zhang** [comment]
Thx

**Comment by Kai-Zhang** [comment]
Thx
