### ISSUE TITLE
想问下能在windows下编译么

### ISSUE THREAD

**Issue by xieqiyou** [shadowsocks/shadowsocks-android#428]
或者sbt-idea后可不可导入android studio

**Comment by madeye** [comment]
不能

**Comment by ageback** [comment]
能哦！

**Comment by xieqiyou** [comment]
@ageback 请问下怎么编译？能说下编译环境么？

**Comment by ageback** [comment]
http://xhmikosr.1f0.de/tools/msys/MSYS_MinGW-w64_GCC_492_x86-x64.7z
用这个编译C++部分。然后下载 sbt 编译环境，按说明执行命令。

**Comment by AndlsH** [comment]
@ageback 
The link is dead. I have git bash installed on my Win7 PC, which includes the MINGW64. 
I would greatly appreciate it if you could give more detailed directions.
