### ISSUE TITLE
UI Problems on Android 4.x

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-android#430]
![screen shot 2015-11-18 at 3 33 29 pm](https://cloud.githubusercontent.com/assets/627917/11235163/ecde2d60-8e09-11e5-8b33-9c20448e2aac.png)

@Mygod Is there a overlay on the main UI?

**Comment by Mygod** [comment]
Yes. I haven't found the solution to that yet. :(

I suspect it's a support lib bug.

**Comment by madeye** [comment]
Oops, so should we drop the support of Android 4.x :)

**Comment by Mygod** [comment]
Totally. :)

P.S. Just kidding.

**Comment by madeye** [comment]
A quick search shows http://stackoverflow.com/questions/29608126/dialog-skinning-with-appcompat-v7-22-results-in-ugly-shadows-on-api-21

**Comment by Mygod** [comment]
Research* shows that making UI ugly on 4.x encourages people to upgrade their system.

**Comment by Mygod** [comment]
Oh thanks. Didn't find that.

**Comment by madeye** [comment]
What about this one? https://github.com/afollestad/material-dialogs

**Comment by madeye** [comment]
https://github.com/afollestad/material-dialogs should also help to refine the dialog of our settings

**Comment by Mygod** [comment]
Doesn't look necessary. The one in support lib looks good enough.

**Comment by madeye** [comment]
It seems that there are no ProgressDialogCompat.We may need to implement it ourself.

**Comment by Mygod** [comment]
We can use native ProgressDialog. I wouldn't bother to make material design available to 4.x if design lib didn't include it automatically. ProgressDialogCompat seems to be a large chunk of code that needs to be chopped off one day. Also including another library will increase the binary size significantly.

**Comment by madeye** [comment]
Sounds good.

**Comment by Mygod** [comment]
Okthx.

**Comment by Mygod** [comment]
I just filed an issue about this and hopefully it will get fixed: https://code.google.com/p/android/issues/detail?id=194475
