### ISSUE TITLE
小米1+Android4.4.2版本无法联网

### ISSUE THREAD

**Issue by lixiuna0908** [shadowsocks/shadowsocks-android#435]
1、debug发现，在执行到builder.establish(); 后出现大量ip route add 128.0.0.0/1 dev tun0 ret2, errno:3及ip route add 0.0.0.0/1 dev tun0 ret2, errno:3；的log打印；
2、另外通过netstat –an查看网络连接情况，当打开ShadowSocks后，网络连接数增加非常多；
3、log中还会出现 ：PushService: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
4、log中最后显示：
    E shadowsocks: socket: Too many open files
    E shadowsocks: invalid remote addr
    D OpenGLRenderer: prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x632e26c8>
    E shadowsocks: remote_recv_cb_recv: Connection reset by peer
    D OpenGLRenderer: finish <0x632e26c8>
    D tun2socks: ERROR(BConnection): recv failed
5、另外，钥匙图标正常显示，而且点开显示发送接收都有数据。

**Comment by madeye** [comment]
MIUI is not officially supported.

**Comment by lixiuna0908** [comment]
能说一下具体原因么？我的是红米1移动版，不带“神隐模式”
