### ISSUE TITLE
Debugging on an HTC device

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#437]
I reinstalled the latest version of the app on this device (Android 5.0.2) and as soon as I click connect, it disconnects itself. And it turned out both `VpnService.prepare` and `builder.establish` returned null at the same time which isn't supposed to happen according to the documentation.

I figured that out with this commit: https://github.com/Mygod/shadowsocks-android/commit/408e74384ed6f96ec98b4f3fcb78d46a9d3fd723#diff-16f734052343e423687545d52579f1b2R445

Apparently this line was hit and an exception was thrown. According to the owner, 2.8.3 worked fine and he was never shown a VPN connect request dialog.

Do you have any idea what might be causing this?

**Comment by madeye** [comment]
It's a bug of Android 5.0 (not only HTC, but all Android 5.0), which is supposed to be fixed on 5.1 and above.

You have to reboot your device sometimes after reinstalling apps using.VPN related permission.

**Comment by Mygod** [comment]
Okay. In that case I suppose we can add a friendly notice to ask user to reboot the device.

**Comment by madeye** [comment]
LGTM
