### ISSUE TITLE
Show traffic stats in notification bar

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#440]
Now's a good time to add back this feature.

P.S. It seems I've removed `service_status` in this commit because it wasn't used: https://github.com/shadowsocks/shadowsocks-android/commit/51e155c940b2c35bb1d68910af3bc65d19d63183#diff-787c9f20c9297db53ee0a28a2f1cfab5L57

**Comment by madeye** [comment]
This feature introduced too many issues, like system UI crashing. Unless we find a better way to show traffic stat on notification, I prefer to not adding this.

**Comment by Mygod** [comment]
I assume this is what's causing the crashes: https://github.com/shadowsocks/shadowsocks-android/blob/v2.2.2/src/main/res/drawable/ic_stat_speed.xml

We can just display the rate in the notification text, and add display rate in notification bar with [this new API in API level 23](http://developer.android.com/reference/android/app/Notification.Builder.html#setSmallIcon(android.graphics.drawable.Icon)).

**Comment by madeye** [comment]
The new API seems promising, which enables us creating icon from bitmap dynamically.

BTW, there already exists a helper function `Utils.getBitmap` to generate bitmap of a string.

**Comment by Mygod** [comment]
Actually I think the design in #447 looks quite fine. Closing this.
