### ISSUE TITLE
我的ss账号在刚配置之后能使用一段时间，过一阵后就不管用了

### ISSUE THREAD

**Issue by BlinkoWang** [shadowsocks/shadowsocks-android#448]
我的ss账号在刚配置之后能正常使用一段时间，过一阵后就不管用了。
ss账号没有问题，在PC端试了一切正常。
手机端用chrome打开google会提示DNS_PROBE_FINISHED_NXDOMAIN
尝试重置和刷新DNS缓存都不管用。
机型Nexus 6P

**Comment by kdanfly** [comment]
@BlinkoWang 问题解决了吗? 同样是Nexus 6P, 同样的问题, 各种搜没找到解决办法. 
Android 6.0.1,  shadowsocks 2.9.7/2.8.3 默认配置, 都有DNS问题.

**Comment by eastmalon** [comment]
如果开了UDP转发，关闭试试

**Comment by kdanfly** [comment]
配置项都试过了，各种无效。唉…
btw：感谢回复
Eastmalon D. <notifications@github.com>于2016年2月16日 周二22:49写道：
