### ISSUE TITLE
源码如何运行？

### ISSUE THREAD

**Issue by wllw** [shadowsocks/shadowsocks-android#450]
首先按照README.md文件来编译项目，没有问题；之后执行到"sbt clean android:package-release",发现一些依赖包无法下载，我的网络是可以翻墙的；接着我使用android studio导入该项目，还是出现问题：依赖包无法下载，当我修复这个问题后，继续make andorid-shadowsocks，发现混淆出现问题。由此我推断，sbt.build中“"com.android.support" % "design" % "23.1.1",
  "com.github.jorgecastilloprz" % "fabprogresscircle" % "1.01",”，以及“proguardOptions in Android ++= Seq("-”部分有问题。不知道是不是我使用方式有问题。

**Comment by Mygod** [comment]
用终端编译。

**Comment by fishg** [comment]
@wllw 不要偷懒，这两行要先确保运行成功：
android update sdk --filter tools,platform-tools,build-tools-21.0.1,android-21,extra-google-m2repository --no-ui --no-https -a

android update sdk --filter extra-android-m2repository --no-ui --no-https -a

**Comment by wllw** [comment]
@fishg 我是在centos上面，最新的sdk，ndk执行了git submodule update --init没有问题，然后执行了./build.sh.之后也成功了。最后执行“ sbt clean android:package-release“，出现了warn信息。最后我将源码移动到windows下的android studio导入。还是报错，warn。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/travis-ci/setup.sh

**Comment by wllw** [comment]
@madeye  难道是握IP有问题。
[root@HK shadowsocks-android]# sbt clean android:package-release
[info] Loading project definition from /root/shadowsocks-android/project
[info] Set current project to shadowsocks (in build file:/root/shadowsocks-android/)
[success] Total time: 65 s, completed Nov 26, 2015 9:07:16 PM
[info] Updating {file:/root/shadowsocks-android/}shadowsocks-android...
[info] Resolving com.android.support#design;23.1.1 ...
[warn]  module not found: com.android.support#design;23.1.1
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.android.support/design/23.1.1/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/android/support/design/23.1.1/design-23.1.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/android/support/design/23.1.1/design-23.1.1.pom
[warn] ==== google libraries: tried
[warn]   file:/root/android-sdk-linux/extras/google/m2repository/com/android/support/design/23.1.1/design-23.1.1.pom
[warn] ==== android libraries: tried
[warn]   file:/root/android-sdk-linux/extras/android/m2repository/com/android/support/design/23.1.1/design-23.1.1.pom
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/android/support/design/23.1.1/design-23.1.1.pom
[warn] ==== JRAF: tried
[warn]   http://JRAF.org/static/maven/2/com/android/support/design/23.1.1/design-23.1.1.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.android.support#design;23.1.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.android.support:design:23.1.1 (/root/shadowsocks-android/build.sbt#L29-43)
[warn]            +- shadowsocks:shadowsocks_2.11:0.1-SNAPSHOT

**Comment by Mygod** [comment]
You need to install Android Support Repository in SDK Manager.

**Comment by wllw** [comment]
@madeye “echo "y" | android update sdk --filter tools,platform-tools,build-tools-23.0.2,android-23,extra-google-m2repository --no-ui -a
echo "y" | android update sdk --filter extra-android-m2repository --no-ui -a”,我是执行过了，并且成功了。然后执行的“sbt clean android:package-release”.然后出现了上面的报错。why?我的心好累。求帮助。

**Comment by wllw** [comment]
@madeye 我重新开始弄了一遍，最后编译完成没有报错误。您是用什么开发工具开发的呢?

**Comment by madeye** [comment]
@wllw vim

**Comment by wllw** [comment]
@madeye  厉害！！！我使用android studio 导入编译好的，报错了，哎。我也决定也用VIM了，但是怎么生成apk文件呢；

**Comment by lxxgreat** [comment]
@wllw android studio 能编译成功? 我是在终端生成apk的.

**Comment by 1107470624** [comment]
请教下各位 目前我也在编译运行这个项目 但发现在Android studio运行不了 终端用那个工具编译，之前没有了解过终端编译

**Comment by 1107470624** [comment]
@lxxgreat 终端编译怎么进行编译？导入Android studio编译不了

**Comment by monakatyking** [comment]
@wllw 我最近也在研究这个，不过在执行./build.sh后出现
$ ./build.sh
/e/shadowsocks/shadowsocks-android/src/main /e/shadowsocks/shadowsocks-android
/e/shadowsocks/shadowsocks-android
/e/shadowsocks/shadowsocks-android/kcptun /e/shadowsocks/shadowsocks-android
Make standalone toolchain for ARM arch
/usr/bin/env: ‘python’: No such file or directory
Make standalone toolchain for X86 arch
/usr/bin/env: ‘python’: No such file or directory
Build the custom go
/e/shadowsocks/shadowsocks-android/kcptun/go/src /e/shadowsocks/shadowsocks-android/kcptun
ERROR: Do not use make.bash to build on Windows.
Use make.bat instead.
不知道该怎么办，请问你遇到过吗？

**Comment by ageback** [comment]
install python2 and golang

**Comment by monakatyking** [comment]
@ageback 
看文档并没有说要安装python2 and golang
只要有
JDK 1.8
SBT 0.13.0+
Go 1.4+
Android SDK
Build Tools 25+
Android Support Repository and Google Repository (see build.sbt for version)
Android NDK r12b+
这几个就行吗？

**Comment by Mygod** [comment]
You can try beta branch if you don't want to install golang and Python.

**Comment by ziqianzi** [comment]
@wllw 亲，你现在会编译这个软件了吗？教教我吧，付费

**Comment by ziqianzi** [comment]
@fishg 亲，你会编译这个软件吗？教教我，付费
