### ISSUE TITLE
在centos中编译完成的源码，导入android studio中报错。怎么在android studio中配置该项目，求知道。万分感谢。

### ISSUE THREAD

**Issue by wllw** [shadowsocks/shadowsocks-android#451]
我试着导入android studio后，会出现无法解析design包，support包等情况，sdk的android google库都是最新的。求给点意见。

**Comment by madeye** [comment]
You cannot import this project to Android Studio. As mentioned in README, it's written in Scala, not Java.

**Comment by wllw** [comment]
http://scala-on-android.taig.io/editor/android-studio/我照着这个做的。

**Comment by wllw** [comment]
@madeye  http://scala-on-android.taig.io/editor/android-studio/
我照着这个做的。

**Comment by madeye** [comment]
The exact explanation on the page you provided:

![image](https://cloud.githubusercontent.com/assets/627917/11432895/9fdb0364-94f1-11e5-8406-69fb5376cfb1.png)

**Comment by wllw** [comment]
@madeye  谢谢。

**Comment by wllw** [comment]
@madeye 还是打扰了，我想问下在vim中怎么开发，比如log怎么打印，bug调试方面怎么处理哦？

**Comment by wllw** [comment]
@madeye 我认为，我应该将这个项目翻译成java，这样更适合广大的android开发者学习。

**Comment by falseen** [comment]
@wllw 已经有人这么做了，不过目前还不是很完美。 项目地址：https://github.com/KagayamaKaede/ShadowsocksRDroid

**Comment by wllw** [comment]
@madeye 你们写android，不是用scala就是用kt，我算是服了。你们是强行打广告（=。    =），我觉得是这样。嘻嘻。

**Comment by wllw** [comment]
@madeye  请教下，System.sendfd(fd)=-1,可能是什么原因哦？
