### ISSUE TITLE
trusted networks feature

### ISSUE THREAD

**Issue by ib54003** [shadowsocks/shadowsocks-android#452]
Hey,
a feature for trusted networks would be great, so trusted networks (for example your own wi-fi) are not routed to remote.

**Comment by madeye** [comment]
Choose `Bypass LAN`.

**Comment by ib54003** [comment]
Sorry that not what i mean. For example if you are connected with a trusted wi-fi, you might not want to route all your internet traffic to the remote. If you do so you can save traffic on the remote.
