### ISSUE TITLE
运行项目，经调试发现System.sendfd(fd)始终为-1.为什么呢？

### ISSUE THREAD

**Issue by wllw** [shadowsocks/shadowsocks-android#458]
ShadowsocksVpnService类中handleConnect()方法里面，运行到 if (System.sendfd(fd) != -1) {
                    return true;
                }。打印发现System.sendfd(fd)始终为-1.求你们帮我看看

**Comment by madeye** [comment]
Run "./build.sh" before building the scala project.

Refer to https://github.com/shadowsocks/shadowsocks-android/blob/master/.travis.yml for more details.

**Comment by wllw** [comment]
@madeye  我已经将这个项目编译好了。你说的那个步骤我早已经弄过了。现在调试功能。另外System.cpp中，“/data/data/com.github.shadowsocks/sock_path”是在哪里产生的呢？

**Comment by madeye** [comment]
Double check and make sure you build the project successfully.

**Comment by wllw** [comment]
yes.我已经可以打包成apk，并且可以运行。但是现在我对源码有些部分进行了修改，我只是想问下：另外System.cpp中，“/data/data/com.github.shadowsocks/sock_path”是在哪里产生的呢？

**Comment by wllw** [comment]
@madeye yes.我已经可以打包成apk，并且可以运行。但是现在我对源码有些部分进行了修改，我只是想问下：另外System.cpp中，“/data/data/com.github.shadowsocks/sock_path”是在哪里产生的呢？

**Comment by wllw** [comment]
“/data/data/com.github.shadowsocks/sock_path”,产生于./src/main/jni/badvpn/tun2socks/tun2socks.c中的“ char *path = "/data/data/com.github.shadowsocks/sock_path";”
