### ISSUE TITLE
allow inputting port number by hand

### ISSUE THREAD

**Issue by CecilHarvey** [shadowsocks/shadowsocks-android#460]
the nightly release uses a selector for port numbers, which is VERY inconvenient (if not unusable at all) for ports like 12345 (which I am using on my server).

**Comment by Mygod** [comment]
Duplicate with #445.

**Comment by CzBiX** [comment]
@Mygod 太快了，我正要点 Comment，你的评论就刷出来了。

**Comment by fishg** [comment]
@CecilHarvey  点击数字可以调出键盘输入

**Comment by madeye** [comment]
@Mygod What about active input keyboard when the port dialog shows up?

**Comment by Mygod** [comment]
@madeye Ok.
