### ISSUE TITLE
关于主界面右上角的这个开关

### ISSUE THREAD

**Issue by zhangnew** [shadowsocks/shadowsocks-android#471]
您好，为什么在打开程序的时候不能立即进行开关的操作，而是先转一圈，然后才能操作呢

**Comment by madeye** [comment]
By design.

**Comment by zhangnew** [comment]
Fine. thank you.

**Comment by Mygod** [comment]
Actually I also prefer to remove that delay.

**Comment by madeye** [comment]
It's necessary as we need to present the "disabled" state of the switch button.

**Comment by Mygod** [comment]
However disabling the switch in onResume every time seems unnecessary to me
and is quite annoying.

**Comment by madeye** [comment]
This is a workaround for the progress circle, of which the animation start and stop everytime when resume.

Unless we find a solution to this issue, we have to keep the delay...

**Comment by zhangnew** [comment]
既然这个问题解决了，有没有计划在启动 App 的时候自动连接呢？
