### ISSUE TITLE
长时间跑 android-shadowsocks, 有断流情况

### ISSUE THREAD

**Issue by txchen** [shadowsocks/shadowsocks-android#473]
4.4, root 模式. 加密模式 RC4-MD5

经常遇到几个小时以后, 不能上任何网站, 打开 ss, turn off -> turn on, 就能恢复.
不知道是不是 Known issue?

**Comment by madeye** [comment]
Make sure you are using a AOSP system without any background service killer app installed.

**Comment by txchen** [comment]
没有任何此类程序. 请问有什么 investigate 的方式?

**Comment by FoxCyy** [comment]
我也是这种情况，ss版本2.9.1，需要关闭重新打开才行

**Comment by dongqisheng520** [comment]
我也一直有这个问题，Android 5.0 -Android 6.0 Moto X机器和索尼Z2 都有出现，每次都用shadowsocks最新版，一直没解决。

**Comment by Yee2** [comment]
三年过去了，这个问题还是有，在lineageOS14.1上面，还是经常断流，使用adb可以查看到进程并没有被系统杀死，但是得重新开关一次才能使用。
