### ISSUE TITLE
如何强制使用非 root 模式

### ISSUE THREAD

**Issue by txchen** [shadowsocks/shadowsocks-android#474]
4.4, 已 root. 但是没装 SuperSU, 请问有没有方法强制使用 VPN 模式? 谢谢!

**Comment by madeye** [comment]
Disable shadowsocks in SuperSU.

**Comment by txchen** [comment]
问题是: 没装 supersu 的情况.

**Comment by madeye** [comment]
Then, install SuperSU first.

**Comment by Mygod** [comment]
To disable NAT mode, just simply turn off the NAT mode switch.
