### ISSUE TITLE
Cannot bypass China mainland IPs.

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-android#476]
Tested on version 2.9.2. When I access IP138 it shows my proxy server IP. It's a mainland website and I suppose that this feature is not working correctly.

**Comment by t123yh** [comment]
Yes you can. Are U in China? Just access ip138.

**Comment by Mygod** [comment]
Make sure you turn off Chrome's data saver.

**Comment by t123yh** [comment]
@Mygod Oh my god, you are absolutely right.
