### ISSUE TITLE
2.9.2打开分应用代理后无法关闭

### ISSUE THREAD

**Issue by ueinohakono** [shadowsocks/shadowsocks-android#478]
打开了就关闭掉，想点击分应用代理的那个按钮，但是一点就跳进去根本没法关
android 4.4

**Comment by madeye** [comment]
Try to uninstall and install the app.

**Comment by Mygod** [comment]
进去后点击开关。

**Comment by madeye** [comment]
@Mygod Verified as a bug on Android 4.4:

E/WindowManager( 1218):
E/WindowManager( 1218): android.view.WindowLeaked: Activity com.github.shadowsocks.AppManager has leaked window android.support.v7.widget.AppCompatTextView{528b228c I.ED.... ......I. 0,0-80,113} that was originally added here
E/WindowManager( 1218): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager( 1218): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager( 1218): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager( 1218): 	at com.github.shadowsocks.AppManager.onCreate(AppManager.scala:214)
E/WindowManager( 1218): 	at android.app.Activity.performCreate(Activity.java:5231)
E/WindowManager( 1218): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/WindowManager( 1218): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/WindowManager( 1218): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/WindowManager( 1218): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/WindowManager( 1218): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/WindowManager( 1218): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager( 1218): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager( 1218): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager( 1218): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager( 1218): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager( 1218): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager( 1218): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager( 1218): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by madeye** [comment]
@Mygod Also reproduced on Android 5.1.1.

Steps to reproduce:

1. Click "Per-proxy".
2. Click the "ON/OFF" switch.
3. Crash.

**Comment by Mygod** [comment]
@madeye So it only works on 6.0? That's strangely interesting.
