### ISSUE TITLE
HTTP client test

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#479]
There's a feature called HTTP client test in Phone info (you can access it via entering `*#*#4636#*#*` in dialer) which makes a simple HTTP request (to `www.google.com` I suppose) to test the connection. Is it acceptable if I add an item in Shadowsocks under (or above?) the traffic stats to do the similar thing to see whether a profile is usable, i.e. has Internet access?

**Comment by madeye** [comment]
LGTM. I think we can directly show this connection status in the traffic stat.
