### ISSUE TITLE
能否添加aarch64支持

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-android#480]
目前的64位的典型平台为Nexus 6P，估计以后64位的CPU越来越多，建议添加支持
uname -m显示aarch64
APP_ABI为arm64-v8a
CPU family为ANDROID_CPU_FAMILY_ARM64
基本上要改的是：
build.sh
src/main/jni/Application.mk
src/main/jni/system.cpp
不过libevent现在编译不过
**UPDATE**: nexus 5x 是808,同样是64位CPU

**Comment by madeye** [comment]
No plan for this.

According to a local test before, there is no obvious performance improvement from aarch64. Also, it will enlarge the APK a lot.

**Comment by madeye** [comment]
Note, the test is only valid for shadowsocks, as it's a typical I/O bound application on modern mobile device.

**Comment by wongsyrone** [comment]
为什么不每个架构打包一个apk呢，或者将64位的独立出来。性能方面可能编译器，程序代码本身都有关系吧，另外在我日常使用中，开启ss不定期屏幕定住，然后自动重启或者甚至需要手动强制重启，不知道是否和架构相关，原来在Nexus 6上并没有遇见过这种问题。
最后我依然保留我的建议。

**Comment by Mygod** [comment]
Shadowsocks 的性能瓶颈在 I/O 操作，与需要大量计算操作的应用不同，因此和系统架构关系不大。

至于不定期屏幕定住是另外的问题，不能确定就和架构有关。

**Comment by wongsyrone** [comment]
感谢解答，但愿只有我遇到屏幕定住的问题，这样我就可以找其他方面的问题了

**Comment by wongsyrone** [comment]
经过研究，成功弄出aarch64的，如果有人想尝试可以用https://github.com/wongsyrone/shadowsocks-android/releases/tag/mod-01-arm64 ，是travis ci编译的
