### ISSUE TITLE
Doesn't work in non-latin locales

### ISSUE THREAD

**Issue by danialbehzadi** [shadowsocks/shadowsocks-android#483]
The app Doesn't work in non-latin locale at all. When you click on the connect button for example in the Persian locale, it tries for a second, but refuse to connect.
I think this may be because of the different unicode characters for the port numbers. In my case it tries to connect to the port ۸۳۸۸ instead of 8388 and obviously there is no such a port number on the server.

**Comment by madeye** [comment]
This is a known bug fixed years ago. Please make sure you're using the latest version of shadowsocks.

The latest stable version of shadowsocks is 2.8.3 and 2.9.3. Both are well tested in Persian locale.

**Comment by danialbehzadi** [comment]
I am using 2.9.3. Works perfectly in English, but the button doesn't go green in Persian.

**Comment by madeye** [comment]
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/627917/11916715/5e19d66e-a71e-11e5-8ef0-95d81cc8498a.png)

**Comment by danialbehzadi** [comment]
So there should be something related to the Android version. My phone is on Android 4.3.
As a workaround, how can I get the previous version (2.8.3?), cause there was no problem before today's upgrade via Google play store.

**Comment by madeye** [comment]
Try to uninstall and reinstall the app first.

The previous versions can be found here https://github.com/shadowsocks/shadowsocks-android/releases
