### ISSUE TITLE
Bypass LAN and China 模式下 Reuters 无法连接

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#487]
Reuters 无法在 bypass lan and China 的模式下连接，各个国家的版本都不能连。
是因为 Reutes 连接的是国内的 CDN？那不应该连不上，如果是连接的国外，那不应该被 bypassed 啊
切换为 ALL 模式，Reutes 可以连了，各个国家版本都可以。
此处 Retures 指 https://play.google.com/store/apps/details?id=com.thomsonreuters.reuters
SS 版本 2.9.3
OS 版本 6.0.1

另外，发现有人从 Play上收到 2.9.3 的推送，但是我 NEXUS 5 MUSHROOM 6.0.1 只看到 2.8.3 版本，前述的 2.9.3 是从 GITHUB上下的。

**Comment by madeye** [comment]
Cannot reproduce the issue. Make sure you're not using NAT mode.

Also, try to flush the DNS cache or/and switch on/off airplane mode.

**Comment by GitatHub** [comment]
前几次打开 reuters 没问题，几个小时后，就打不开了。需要 ALL 模式下或者 UDP FORWARDING 模式下才能打开
没有使用 NAT，因为没有 ROOT
重启也没用，检查了上级路由器，一切正常，PC 端同样的 DNS 没问题

从 PLAY 上重新安装了 2.8.3 ，同样是不能打开路透，因此可能不是新版的原因
不知道 REUTERS 使用了什么 域名和 IP 才导致出现这种诡异状况
因为其他 APP 一切正常 包括  GOOGLE 系所有应用
