### ISSUE TITLE
2.9.3 怎么删除一个 PROFILE ？

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#488]
只能通过编辑替换吗？但是如果有些 PROFILE 就是没用了，多余的，怎么删除？
系统是 6.0.1
设备是 NEXUS5

Play 没有推送 2.9.3 上面显示 2.8.3
这个 2.9.3 是从 GITHUB 上下载的

**Comment by madeye** [comment]
Slide to right.
