### ISSUE TITLE
Connect test function is not working in 2.9.4 if NOT proxy it self.

### ISSUE THREAD

**Issue by chenshaoju** [shadowsocks/shadowsocks-android#489]
Android系统版本：5.1.1
Shadowsocks版本：2.9.4
Shadowsocks模式：VPN模式
ROOT权限：有，已授权ROOT权限。
Shadowsocks路由：绕过局域网及中国大陆网络
Shadowsocks IPv6路由：关闭
分应用代理：开启
UDP转发：关闭
自动连接：启用

现象：在没有代理Shadowsocks自身的情况下，启动Shadowsocks并以VPN模式连接上以后，点击网络流量，等待５秒后，提示失败。但是Shadowsocks已经可以正常使用，并且可以通过Shadowsocks代理的App访问网络。

Logcat：
http://pastebin.com/3LAbcKHc
（可能没有有效信息）

期望：测试连通性的功能应该是直接连接本地端口进行代理访问测试，而不需要刻意去代理自己再进行连通性测试。

截图：
![screenshot_2015-12-25-14-22-57](https://cloud.githubusercontent.com/assets/515763/12000643/327e904e-ab15-11e5-91eb-5c894ca7afe7.png)

**Comment by Mygod** [comment]
Expected behavior. Why not proxy this app?

**Comment by madeye** [comment]
It's a expected behavior. BTW, this feature also doesn't work in NAT mode, as we bypass all the traffic from shadowsocks itself.

**Comment by chenshaoju** [comment]
My English is poor...

我的理解是这样的，所谓测试功能，即使没有代理自己（或者没有连接）的情况下，就是测试当前或选择的连接是否能够正常工作的。

常见的代理软件，比如Proxifier，在没有代理自己的时候也可以测试所选中的代理。

![unnamed qq screenshot20151225145905](https://cloud.githubusercontent.com/assets/515763/12000798/2354f902-ab18-11e5-919f-e81a339684e1.png)

**Comment by chenshaoju** [comment]
@madeye Ok....如果设计初衷就是这样的话。。。只是建议。
