### ISSUE TITLE
How do I delete default profile?

### ISSUE THREAD

**Issue by KwToPA** [shadowsocks/shadowsocks-android#493]
I updated from ver 2.8.3 then I found the app didn't work and the Pre-App proxy's button was gray. I can't delete default profile. So how do I use the Pre-App proxy and delete default profile.
OS: Android 4.1.2
mobile: Galaxy Win I8552

Thanks :)

**Comment by Mygod** [comment]
1. Enable NAT mode.
2. Swipe to remove a profile.

**Comment by KwToPA** [comment]
Hi Mygod
I use the NAT mode.Then I can see the data sent and received. But I still can't open any site. 

Best.
KwToPA

**Comment by KwToPA** [comment]
Forgot to say when I update all the data in this app were lost.

**Comment by KwToPA** [comment]
Hi Mygod
I reinstall it again and use the NAT mode. Now it works . Thanks  a lot.
Best,
KwToPA

**Comment by Mygod** [comment]
Sounds like database upgrade has failed.
