### ISSUE TITLE
Dynamic traffic stat in profile selector is broken

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#495]
https://github.com/shadowsocks/shadowsocks-android/commit/fcb368d2f8b80207a06bacdf872b42252aca2639

This commit has broken that feature.

**Comment by madeye** [comment]
Yes, this feature is removed for less database accesses.

Until the service stopped, the total traffic won't update.

**Comment by Mygod** [comment]
We can use callbacks to fix that feature.

**Comment by madeye** [comment]
What about just adding the real time traffic number and the number in the database?

**Comment by Mygod** [comment]
What do you mean by that?
