### ISSUE TITLE
NAT switch sometimes stop working

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#496]
Here's one way I've found to reproduce it:

* Start the service;
* Press home button; (to keep activity alive, but in the background)
* Stop the service using the notification;
* Bring back the activity;
* Try the switch now.

**Comment by madeye** [comment]
I cannot reproduce this on Android 5.1.1. Which version are you using?

**Comment by Mygod** [comment]
Latest version (compiled from source). Reproduced it on Android 6.0.1 and 5.1.1.

**Comment by madeye** [comment]
How do you bring back your activity? From recent task or click the icon? Tried both, no issue observed.

**Comment by Mygod** [comment]
By broken, I mean switching it doesn't have any effect until the activity is destroyed and created again.

**Comment by madeye** [comment]
https://dl.dropboxusercontent.com/u/4356689/issue-496.mp4
