### ISSUE TITLE
MiUI7开发版12.10后台内存清理自动结束tun2socks、ss-local

### ISSUE THREAD

**Issue by msdx321** [shadowsocks/shadowsocks-android#499]
在MiUI上后台管理界面上滑锁住应用防止自动清理后，MiUI自带清理依然会结束tun2socks及ss-local导致无法继续使用。明前尚不明确是针对SS进行的定点清除还是MiUI逻辑问题（因为只有tun2socks及ss-local被杀掉）

**Comment by madeye** [comment]
MIUI is not supported.

**Comment by dna1982** [comment]
我也发现这个问题了，估计是专门针对SS的。
打算放弃MIUI，刷原生的Rom了……

**Comment by xieranmaya** [comment]
各位试试在神隐模式里把ss加到白名单里。虽然这样最终还是会被杀进程，但能用的久一点，大概两个多小时。。

**Comment by ReVanTis** [comment]
我个人倾向于认为是miui的逻辑有问题，我自己也经历过别的应用有锁住以后被杀的情况。。。

**Comment by frihed** [comment]
不是miui 问题，是神隐模式设置问题，（设置——其他高级设置——电量和性能——神隐模式）
关闭神隐模式，或者采用自定义配置，保持联网即可。
