### ISSUE TITLE
请问是重新开始维护了吗

### ISSUE THREAD

**Issue by JohnsonChany** [shadowsocks/shadowsocks-android#501]
请问是重新开始维护了吗？如果是，那真是恭喜了。

在用2.9.3版本时遇到一个问题，安装后迅雷就无法下载了，我开了绕行模式将迅雷选中也无法下载，我的设备是nexus9，系统是android6.0.1。

换了之前的版本，迅雷就可以正常下载了。

**Comment by JohnsonChany** [comment]
更新到2.9.4的版本也是同样的问题

**Comment by madeye** [comment]
Bypass Xunlei and try again.

**Comment by JohnsonChany** [comment]
不好意思，我又试了下，应该是网络和资源的问题，不是shadowsocks的bug
