### ISSUE TITLE
ver 2.9.* FC on HTC M9 

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#504]
RT, this problem is not appear in 2.8.x . The runtime is 5.1
Is that caused by arm64 soc?
Please fix that, thx.

**Comment by madeye** [comment]
Try to clear the app data.

**Comment by simonsmh** [comment]
Does not work.

**Comment by madeye** [comment]
Try some other AOSP based ROMs instead.

**Comment by Mygod** [comment]
If you download from Play Store, submit the crash report. Otherwise, paste a logcat here.
