### ISSUE TITLE
Unable to resolve host "www.google.com":No address associated with hostname

### ISSUE THREAD

**Issue by mailsuhua** [shadowsocks/shadowsocks-android#505]
三星G9008v  android 5.0  未root
ss号在电脑上正常使用

**Comment by madeye** [comment]
Double check your config.

**Comment by flashbarry** [comment]
我遇到同样的问题，昨天还好上的，今天早上连上ss后，检测网络，报这个错：Unable to resolve host "www.google.com":No address associated with hostname。我换了远程dns，还是不行，求教。华为mate9
