### ISSUE TITLE
VPN模式到底怎么用？

### ISSUE THREAD

**Issue by laxtiz** [shadowsocks/shadowsocks-android#507]
之前一直好好的，今天Play 更新2.9.5，配置丢失重新填写都是小事，直接扫描Windows上的二维码好了
默认VPN模式完全无法使用：
服务端从python-shadowsocks 2.8.2 切换到 shadowsocks-libev 2.4.1 依然不行
服务端开启 verbose mode 看不到任何连接信息，PC连接就能看到服务端的信息。
NAT模式没问题，但是括号仅限调试有点莫名其妙，Google Play 回复 全是"NAT mode has been deprecated." 
请问VPN模式到底怎么用？需要服务端做调整吗？

**Comment by madeye** [comment]
Try to uninstall and reinstall the app.
