### ISSUE TITLE
Proposal for the new UI polishment

### ISSUE THREAD

**Issue by nulled666** [shadowsocks/shadowsocks-android#508]
The new material design style UI is great.
Might be it could be polished a little like below:
![ss](https://cloud.githubusercontent.com/assets/2113745/12078239/bbc2a6ca-b244-11e5-957c-36fde1dc673a.png)

* The switch button will be much easier to reach.
* Info structure is cleaner
* While scroll down, the Nework Trafiic part will be hidden.

**Comment by Mygod** [comment]
Sure. A pull request?

Btw, what's the overflow menu for?

**Comment by madeye** [comment]
Looks great. Submit a pull request if possible.

**Comment by nulled666** [comment]
Sorry, it's just a mockup design.
I don't have Android develop environment installed.

**Comment by DickYue** [comment]
我想为下一个版本的shadowsocks提供UI及交互设计，请问联系谁？如何提交？

**Comment by Mygod** [comment]
If you meant a pull request, you can create one whenever you like at your own repo.

**Comment by DickYue** [comment]
thx. i got.

**Comment by CraneJen** [comment]
2.10.1版本，在by pass Lan & China下，Google search没法用了，全局模式可以
