### ISSUE TITLE
Replace the placeholder icons

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#511]
The cloud icons were initially designed to be placeholder icons but I didn't replace those due to laziness. (drawing icons are annoying to me) :stuck_out_tongue: 

We should probably replace it with corresponding modified product icons like those in #508.

**Comment by Mygod** [comment]
Yeah I have also mentioned this issue in #412.

**Comment by Mygod** [comment]
Here's the draft. What do you think?
![ic_start_busy](https://cloud.githubusercontent.com/assets/3511321/12814553/ce1538f2-cb7a-11e5-8da3-92f83efd26b9.png)
![ic_start_connected](https://cloud.githubusercontent.com/assets/3511321/12814552/ce0fe0a0-cb7a-11e5-87a7-d3d34779746d.png)
![ic_start_idle](https://cloud.githubusercontent.com/assets/3511321/12814554/ce1600ac-cb7a-11e5-9ed4-f92f935e338e.png)

Attached: [Full source](https://mygod.tk/resources/userscloud/4koc8xsfuuof).

P.S. Apparently you can't see them because of the white background.

**Comment by madeye** [comment]
LGTM.
