### ISSUE TITLE
something wrong with the notification

### ISSUE THREAD

**Issue by Dylan1984** [shadowsocks/shadowsocks-android#513]
![screenshot_2016-01-04-18-50-55](https://cloud.githubusercontent.com/assets/16444143/12116856/c12728fc-b3f7-11e5-97b6-4b066bfa2ab5.jpg)

是优先级的问题吗？像shadowsocks这样的常驻而且非重要的通知是否应该像图中的termux后台一样处在分割线的下方？在通知较多的时候shadowsocks的通知会和其他混在一起使得其它通知不好操作。

**Comment by Mygod** [comment]
NAT mode has been deprecated.
