### ISSUE TITLE
NAT / VPN 两种模式下的 DNS 疑问

### ISSUE THREAD

**Issue by Itianxia** [shadowsocks/shadowsocks-android#514]
好：
    有个情况，反馈一下。
    NAT下，绕过大陆和局域网，分应用代理，绕行，未开启udp转发。
    这个时候，已经绕行的应用，查询 music.126.com 的dns信息，显示服务器是119.29.29.29 （我wifi的dns），端口53，但是结果IP是日本amazon的，就是走了代理后获取的IP（我服务器日本的）。
    关闭影梭后，获取的IP是本地电信。
    NAT模式下，自动处理UDP包么？

**Comment by madeye** [comment]
NAT mode is no longer supported.

**Comment by Itianxia** [comment]
重新试了下，切换VPN模式，获取的IP正常是本地电信的IP。

**Comment by Itianxia** [comment]
好哒，明白，开始改用VPN模式。
感谢。
