### ISSUE TITLE
一次性认证会被开启

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#516]
操作步骤：
Android 4.4.4
一次性认证都是关闭的，点击 按钮 启动服务。
预期：
正常连接服务器。
实际情况：
有一定概率，一次性认证会自己打开，导致无法连接。

**Comment by madeye** [comment]
Try to uninstall/reinstall the app.

**Comment by vipsbpig** [comment]
现在这个最新的版本,这个问题在安卓4.4.4上面会频繁出现...
