### ISSUE TITLE
Tasker插件不能正常工作

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#518]
@CzBiX   使用tasker调用ss的插件，1.选择配置文件后，无法通过tasker启动ss；2. 不能正常选择”关闭“操作。
我上传了一个视频 https://www.youtube.com/watch?v=C85VvO7ACQg
觉得描述不清楚。

**Comment by CzBiX** [comment]
1. 可以看下 logcat 中是否有相关错误日志，是否被各种卫士拦截。
2. 正确步骤：切换 Switch 到关闭服务状态之后，点击使用当前配置。属于 UE 问题。

希望能引起 @Mygod 的重视，优化 UI/UE。

**Comment by wyzegob** [comment]
@CzBiX 
针对第一个问题，现在我测试了几次，并抓取了log
[log.zip](https://github.com/shadowsocks/shadowsocks-android/files/79867/log.zip)

**Comment by CzBiX** [comment]
日志中多次出现 Xiaomi firewall/PowerKeeper 相关字样，估计是被 MIUI 给拦截了。
另外请参考 [FAQ](https://github.com/shadowsocks/shadowsocks) 。

**Comment by wyzegob** [comment]
防火墙和电量控制的例外我都是设置例外的。
通过tasker发送intent和service的方式是可以启动ss的。
另外 插件提供的关闭ss功能是正常的。
