### ISSUE TITLE
如何保持连接在空闲时不自动断开（关闭）

### ISSUE THREAD

**Issue by QiQiBiBi** [shadowsocks/shadowsocks-android#519]
通俗描述就是，连接时会问你要不要建立VPN，确定后会在状态栏产生小钥匙图标表示连接已建立。
但如果放着不管它一阵子，钥匙就消失了，还得手工再去连接一次才能用。
如果是看网页就无所谓了，但是像一些后台推送对话的IM比如Line，断了后就根本收不到话，很容易错过。
不知道是不是我漏了什么设置。

**Comment by CzBiX** [comment]
请确认使用的不是国内各种魔改 ROM，以及没有被各种卫士杀死。

**Comment by QiQiBiBi** [comment]
原生Android 4.4，NEXUS 5。装的工具是LBE，但之前的版本似乎没有出现这个问题，更新到2.9.5后才出现的。

**Comment by QiQiBiBi** [comment]
原生Android 4.4，NEXUS 5。装的工具是LBE，但之前的版本似乎没有出现这个问题，更新到2.9.5后才出现的。

**Comment by zabio** [comment]
华为mate 8 android 6.0 也是这样的 同问

**Comment by hanxiaoliang** [comment]
小米手机MIUI8也有这个问题

**Comment by wojiaoluyuan** [comment]
到底有没有解决啊？

**Comment by PINK-FL0YD** [comment]
主要是后天被清理了，各种rom应该有保持后台运行的白名单，把影梭添加进去

**Comment by Sherlock-Holo** [comment]
这是那些ROM的问题，并不关ss-android的事

**Comment by swors** [comment]
华为 emui5 加入白名单也没用

**Comment by beyondkmp** [comment]
@swors  华为直接用自带的手机管家->电池->锁屏清理应用，设置不清理ss,就可以了

**Comment by fs94007** [comment]
仍然有这个问题，怀疑是rom针对ss做了定期关闭

**Comment by zpengcom** [comment]
找下省电的应用程序   锁屏后不结束应用就行了

**Comment by leopark999** [comment]
我的vivo x9也有这个现象，在哪里加白名单
还有我的并不是锁屏才断开，我在看facebook，用着用着就给断了

**Comment by zuqiu2024** [comment]
有解决嘛
