### ISSUE TITLE
从2.9.0版本开始无法开机自动连接

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#520]
2.8.3版本可以正常开机启动。
同一手机(android 4.4.4)，从2.9.0版本开始一直到当前的2.9.5都无法开机启动自动连接。
结合之前的https://github.com/shadowsocks/shadowsocks-android/issues/518
应当与 ShadowsocksReceiver 有关，可能是下面的2个不能正确获取到值吧
ShadowsocksApplication.settings.getBoolean(Key.isAutoConnect, false)
ShadowsocksApplication.settings.getBoolean(ShadowsocksApplication.getVersionName, false)
@CzBiX   可能与https://github.com/shadowsocks/shadowsocks-android/issues/518 有关
@Mygod

**Comment by madeye** [comment]
Some app on your device has intercepted the `BOOT_COMPLETED` broadcast to shadowsocks.

Double check that there is no LBE, 360 Security or similar tools installed on your device.

**Comment by wyzegob** [comment]
我刚刚测试了，手机没有这个什么卫士的。安装了2.8.3 ，正常。卸了再装2.9.0就不行。同样的操作步骤。

**Comment by madeye** [comment]
If you are using EMUI, MIUI or similar ROMs, that kind of tools are pre-installed. So, try some other AOSP based ROMs, like CyanogenMod.

**Comment by NkSabre** [comment]
三星港版Galaxy S6 9200，2.9.5版本自动启动也失效

**Comment by NkSabre** [comment]
三星港版Galaxy S6 9200，2.9.6版本自动启动也失效

**Comment by bimzcy** [comment]
LG V10国行，2.9.x版本同样无法自启动。

**Comment by ageback** [comment]
国行 S5 SM-G9008V，刷了 Resurrection Remix 5.6.2，ss是下载最新源代码编译的版本 2.9.7，开机自启没问题。
