### ISSUE TITLE
nexus6 6.0.1 cannot connect

### ISSUE THREAD

**Issue by shaohao** [shadowsocks/shadowsocks-android#521]
install from play store v2.9.5
nexus6 android6.0.1
can connect to a remote ss server, but no web site can be accessed.
If i click "tap to check internet connection availability", it told me that "unable to resolve host "www.google.com": no address associated with hostname"

**Comment by shaohao** [comment]
Sorry, my fault. I input the wrong password of the remote ss server.
It works great now.

**Comment by Sheng0** [comment]
@shaohao i have the same issues,bu my password is true,
it works great before ,and oneday it told me that "unable to resolve host "www.google.com": no address associated with hostname"

**Comment by soryer** [comment]
The same issue occured at SHL23

**Comment by onizukaspm** [comment]
The same issue occured at my Nexus 6P, but it works great before. If anyone knows how fix it, please tell me~

**Comment by JeffinBao** [comment]
same issue also occurred at Smartisan T2, it all worked fine till yesterday, but suddenly couldn't work, and the indication is the same with @shaohao "unable to resolve host "www.google.com": no address associated with hostname"

I haven't changed any of my settings on my phone, and shadowsocks for Mac works fine.
Plz advice some clues that may lead to this issue
thanks in advance!!!

**Comment by MARGI3** [comment]
i got this problem too, i scan the QRcode to generate the username and password .  two days ago it works, but these days it does not work

**Comment by liangchaob** [comment]
same problem in Mi 3  MIUI8, just work well in morning, after lunch report  "unable to resolve host "www.google.com": no address associated with hostname".
Nothing update, password is right, WiFi and 3G they all get the same problem.

**Comment by tangzhiyi11** [comment]
i got the same problem , who fixed it?

**Comment by tade0726** [comment]
@tangzhiyi11 

Base on my research, some of the settings should been closed, my network is fine once I close them..
More detail, please check the link below.
https://www.ssorz.com/?p=490

**Comment by baijifeilong** [comment]
I opened two ports on my server. On my mac, both of them worked. By on my android phone, only one worked, no matter wifi or 4G. If you are the server owner, you can try another port such as 65535. Maybe a bigger port may work for you :)

**Comment by luckyfish0826** [comment]
I solve it by clear application data... maybe need to look into the code and debug to see what's the problem.
