### ISSUE TITLE
我使用的是之前的版本，之前shadowsocks.scala中有copToSystem()方法；但是现在发现最新版本没有了，我想问下是从哪个版本开始改的。

### ISSUE THREAD

**Issue by wllw** [shadowsocks/shadowsocks-android#522]
我使用的是之前的版本，之前shadowsocks.scala中有copToSystem()方法；但是现在发现最新版本没有了，我想问下是从哪个版本开始改的。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/commits/master/src/main/scala/com/github/shadowsocks/Shadowsocks.scala
