### ISSUE TITLE
现在SS的服务端应该用哪个版本？

### ISSUE THREAD

**Issue by dna1982** [shadowsocks/shadowsocks-android#526]
Python版的停更了，但是Android客户端还在不断加新功能（“一次性认证”之类的）。这些新功能Python服务端支持吗？
如果不支持的话，应该用哪个版本的服务端？Libev？

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks/tree/feature-ota

**Comment by v3aqb** [comment]
404

**Comment by mengskysama** [comment]
https://github.com/shadowsocks/shadowsocks/tree/master
