### ISSUE TITLE
SSL handsake timeout on Android6 with Nexus6

### ISSUE THREAD

**Issue by myth2loki** [shadowsocks/shadowsocks-android#527]
I installed SS on my nexus6 with Android6. I can connect to server, But got no data.  I got the issue when I pressed check connection(the second item).
![ss failed](https://cloud.githubusercontent.com/assets/10988990/12226492/d13ea4ae-b857-11e5-946e-6124e83740a3.jpg)

**Comment by madeye** [comment]
Double check your config.

**Comment by myth2loki** [comment]
I am sure that the config file is correct, because the same config used in android5 and PC can work. I checked the differences of Android6 from official website and I found that the OpenSSL is abandoned and uses BoringSSL as official library.
Message from developer.android.com below:
BoringSSL
Android is moving away from OpenSSL to the BoringSSL library. If you’re using the Android NDK in your app, don't link against cryptographic libraries that are not a part of the NDK API, such as libcrypto.so and libssl.so. These libraries are not public APIs, and may change or break without notice across releases and devices. In addition, you may expose yourself to security vulnerabilities. Instead, modify your native code to call the Java cryptography APIs via JNI or to statically link against a cryptography library of your choice.

**Comment by Mygod** [comment]
Triple check your config. And check again on other devices.

**Comment by myth2loki** [comment]
I have checked so many times, I am sure that more than 5 times. Using the app in Android5 with XiaoMi 2s, Nexus6 and HTC m7 is good. Using the app in Android6.0 with Nexus6 is not working.
Please don't let check my config the fourth time. I will be crashed.

**Comment by lanxichan** [comment]
I got this issue too, my devices is NEXUS 5X - HongKong, And i'm sure the config is correct. Did someone got some ideas?

**Comment by myth2loki** [comment]
Hi, The issue is gone When I installed Android6.0.1. Please do it as I did

**Comment by lanxichan** [comment]
@myth2loki  Greate! It works NOW! Thank you!
