### ISSUE TITLE
There should be a root check after press "重置" .

### ISSUE THREAD

**Issue by uuip** [shadowsocks/shadowsocks-android#529]
1. install the apk and run ss .
2. press to enable Mode.Nat
Note:At this time ,there is no root permission  assigned to ss.
3. press "重置" .
The screen always displays "重置中" .I should force stop the app.
There should be a root check after press "重置" .

**Comment by Mygod** [comment]
Check if your root is broken.

**Comment by uuip** [comment]
def recovery() {
 //no root check .There should be a root check.
    serviceStop()
    val h = showProgress(R.string.recovering)
    ThrowableFuture {
      reset()
      h.sendEmptyMessage(0)
    }
  }
