### ISSUE TITLE
The Main Activity UI not update after autostart.

### ISSUE THREAD

**Issue by uuip** [shadowsocks/shadowsocks-android#530]
**https://github.com/shadowsocks/shadowsocks-android/commit/0018a7ca9e204ac27d623eeb490284fd96b613ea cause  a new bug.
The ss app autostart after reboot the phone.
The Notification  apperas,but the Main Activity UI not update.like pic1.**
![1](https://cloud.githubusercontent.com/assets/16631174/12238963/6d978ae6-b8c1-11e5-88ce-22730ea67ad0.png)

  - **The right case like pic2 after press the conection button**
![2](https://cloud.githubusercontent.com/assets/16631174/12238968/725bf2ec-b8c1-11e5-92a7-08a97132ee86.png)

  - **I compile the apk after  undo  the code, it works well.**
![3](https://cloud.githubusercontent.com/assets/16631174/12238923/342ea442-b8c1-11e5-90b2-411c55821e4c.png)

**Comment by madeye** [comment]
Try to reopen the activity.

**Comment by Mygod** [comment]
How about this: https://github.com/Mygod/shadowsocks-android/commit/1b43b5a05c2b4b24fc0329189253ce9700eb4c90

**Comment by VampireSH** [comment]
对啊现在最新版本通知栏经常不见了

Mygod <notifications@github.com>于2016年7月8日周五 23:27写道：

**Comment by madeye** [comment]
@Mygod What about to use this one: https://github.com/shadowsocks/shadowsocks-android/commit/292f22cc86f6b9d93694575cd8385f486ba781ac

**Comment by madeye** [comment]
Observe this issue again after https://github.com/shadowsocks/shadowsocks-android/commit/84ac2b06fae97318594a6884d2fcddc38dcfe7d8
