### ISSUE TITLE
使用ss中遇到的界面相关问题

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#531]
- nat模式，服务正在运行点击重置，任务栏通知可能不会消失。
- 重置并强制关闭app，下次启动app一次性认证可能处于启用状态。
- 运行时界面被锁定--正常，但一段时间后界面可编辑，通知栏也解除锁定，经测试此时ss仍在提供服务。

上述3个问题均有一定概率出现，但还没弄清具体重现步骤。

**Comment by madeye** [comment]
Keep NAT mode disabled.

**Comment by 476210180** [comment]
第3个情况我也遇到过，在Android 5.1下，如果在没有停止服务时就重新启动设备且影梭设置了开机自动连接，就可能出现该问题。
