### ISSUE TITLE
client2.9.5 for android can't connect

### ISSUE THREAD

**Issue by flankcheung** [shadowsocks/shadowsocks-android#532]
I use the client for windows can be connected, but the client for android didn't work when it update to 2.9.5,even I clear the servers of background.
Please help!!!

**Comment by madeye** [comment]
Try to uninstall and reinstall the app.

**Comment by flankcheung** [comment]
Thank you for your advice.I uninstall and reinstall the app,It's work when
the frist time run,but the second time it can't connect.What's wrong with
the app,have somebody like this?

Max Lv <notifications@github.com>于2016-1-12 11:52 星期二写道：

**Comment by flankcheung** [comment]
Somebody help me!!!
