### ISSUE TITLE
hexadecimal format IP not supported.

### ISSUE THREAD

**Issue by lotc** [shadowsocks/shadowsocks-android#536]
IPv4 addresses can be represented in any notation expressing a 32-bit integer value. [[1]](https://en.wikipedia.org/wiki/IPv4#Address_representations)
Take a sample, all the links below point to the same IPv4 address.
1. http://192.0.2.235
2. [http://3221226219](http://3221226219)
3. [http://0xC00002EB](http://0xC00002EB)

On Windows version, you can insert any formats of IPv4.
But on Android version, only dot-decimal notation is supported.

Considering this is not even a bug, I don't think it should be "fixed".
But sending a qrcode or ss address with decimal or hexadecimal format IP can be immune from some text-base malicious sniffers. 
It would be better if the client can support this.

**Comment by madeye** [comment]
Sorry, no plan for this. But of course, pull request is always welcome.
