### ISSUE TITLE
使用Tasker切换配置文件后，打开app连接中断。

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#537]
@CzBiX 
步骤1：手动或者tasker启动配置a；
步骤2：配置tasker，使用配置b，并启动任务
步骤3（可选）：测试一下配置b是否连接正常，到此应当都是正常的。
步骤4：打开ss App，App界面变为可编辑状态，配置b的连接也断开。

**Comment by madeye** [comment]
Unfortunately, It's an expected behavior. I choose not to fix this.

**Comment by wyzegob** [comment]
if (ShadowsocksApplication.profileId != currentProfile.id) reloadProfile()  
原本是检测从 配置列表中选择item后返回，进行检查，如果选择不是同一个就更新界面。
但现在tasker直接从后台进行了更新~~再打开界面时进行检查就会出问题。

**Comment by wyzegob** [comment]
应当是当ShadowsocksApplication.profileId != 当前正在运行的服务id 时，停止服务。

**Comment by wyzegob** [comment]
@CzBiX
希望你能看到
TaskerReceiver.scala 中        
case Some(p) =>
        Utils.stopSsService(context) 
后面加上暂停1秒，解决了1楼的问题。
不知道原因，但这样确实解决了问题。

**Comment by CzBiX** [comment]
@wyzegob 可能是你测试的时候没有在步骤 2 之前打开 app 的界面，并选择了非 b 的配置文件，才让你误以为解决了问题？

另外我认为这个不是问题。打开 ss 的时候意味着你要对 ss 做某些管理操作，然而任何一种管理操作都会停止服务。

**Comment by wyzegob** [comment]
@CzBiX 
前提是app之前没启动过。
用tasker启动配置a，再用tasker启动配置b，预期情况是配置b正常工作，此时打开app界面应当是锁定的。
实际情况不是，配置b不工作。

或者注释掉stopSelf后也解决1楼的问题。
BaseService.scala
def stopRunner() { 
...
stopSelf()}。
当时测试时我加了日志的。
不加延时时，步骤1， ShadowsocksNatService.scala ，先 onCreate ，后startRunner，配置a正常。
执行步骤2， ShadowsocksNatService.scala ，先 startRunner ，后onCreate，不正常。
加延时后步骤2 先onCreate 再 startRunner ，正常。
我估计在刚开始执行第二步时ShadowsocksNatService实例还是存在的，所以没再实例化，但后续被某个操作销毁了。
