### ISSUE TITLE
why is nolonger NAT mode supported 

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-android#539]
i think NAT mode is great. what is the disadvantage?

**Comment by VampireSH** [comment]
我觉得NAT模式很好用啊。为什么准备取消NAT模式？如果使用VPN模式的话那个网络的叹号就不能取消了

**Comment by CzBiX** [comment]
请看 [FAQ](https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ)

建议修改 portal server 为 g.cn 而让网络检测机制能正常工作。
