### ISSUE TITLE
请教编译问题

### ISSUE THREAD

**Issue by ggwolfking** [shadowsocks/shadowsocks-android#540]
[error] (*:update) sbt.ResolveException: unresolved dependency: com.google.android.gms#play-services-base;8.4.0: not found
[error] unresolved dependency: com.google.android.gms#play-services-ads;8.4.0: not found
[error] unresolved dependency: com.google.android.gms#play-services-analytics;8.4.0: not found
[error] unresolved dependency: com.android.support#design;23.1.1: not found
[error] unresolved dependency: com.android.support#support-v4;22.2.0: not found
[error] unresolved dependency: com.android.support#support-annotations;(19,): not found
[error] Total time: 22 s, completed 2016-1-16 22:32:05
前面都是正常，最后几个报错。请问是什么原因呢？

**Comment by ggwolfking** [comment]
是缺少这几个库，已经解决了。谢谢。

**Comment by Linger50** [comment]
@ggwolfking 怎么解决的？android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-19,extra-google-m2repository,extra-android-m2repository --no-ui --no-https -a
之后

**Comment by Linger50** [comment]
@ggwolfking 怎么解决的？
android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-19,extra-google-m2repository,extra-android-m2repository --no-ui --no-https -a
之后还是报一样的错

**Comment by sfetome** [comment]
@ggwolfking 对啊，你这种不给结论和方案关问题看着好气人。求以后注意一下。


我是最后的参考链接所说，Google Play Services 和 Google Repository 都要更新到最新，
另外还把 Google Play Licensing Library,   Google Play Billing Library 也都更新了
(可能不需要，请自行确认，我是打开 gui 的 SDK manager 更新的)
解决了下面两个依赖
[error] unresolved dependency: com.google.android.gms#play-services-ads
[error] unresolved dependency: com.google.android.gms#play-services-analytics

参考链接
http://stackoverflow.com/a/29808207
