### ISSUE TITLE
有时候点击，连接按钮连接上后 ，然后再点击，vpn管理的通知没有关闭，请问是怎么回事？

### ISSUE THREAD

**Issue by MissJohn** [shadowsocks/shadowsocks-android#543]

**Comment by wyzegob** [comment]
@MissJohn 
只能呵呵了，你有兴趣的话，看看我提的所有bug。
开发者不认为是bug，只能呵呵了。

**Comment by CzBiX** [comment]
@MissJohn 请描述清楚你使用的版本，用最新版本测试一下。
@wyzegob 你之前提过类似 issue #517，不是有修复么。

**Comment by wyzegob** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/537
第二步后~~ 此问题必出。

抽空录个屏吧，1楼的

**Comment by CzBiX** [comment]
@wyzegob 请弄清楚 cannot reproduce 和 expected behavior 的意思和区别。

**Comment by wyzegob** [comment]
抽空录个屏，看看。
难道预期行为就是通知栏取消锁定后一直挂在那里？

**Comment by wyzegob** [comment]
1楼抽空录个屏，看看。

@CzBiX 
是你们不能复现罢了，不单是一人给提问题。
我提的一些bug，之前一直不被认为是bug ，直到https://github.com/shadowsocks/shadowsocks-android/issues/530 指出。如果他不指出的话，是不是一直都不认为是bug？

如果已经从界面启动了服务，再用tasker切换配置并启动，bgservice的状态是正确的么？

**Comment by wyzegob** [comment]
如果已经从界面启动了服务，再用tasker切换配置并启动服务，打开app， 服务会停掉。

如果之前没有启动过app，直接用tasker启动服务，打开app，服务则不会停掉；继续，在ss-android app界面，返回或者home键，再用tasker切换配置并启动服务，打开app， 服务会停掉。

@CzBiX  ~~
