### ISSUE TITLE
2.8 一切正常，2.9.x 之后无法连接

### ISSUE THREAD

**Issue by pizzamx** [shadowsocks/shadowsocks-android#546]
不知道是什么问题，全网搜过去感觉也没人遇到过这问题，不知道自己哪里做错了……
现在用的 2.8.3，一切正常，VPN、NAT 模式军可用
自从 2.9 推送后，我就没连上过，不得已又回退了。虽然用着没问题，但心里总觉得膈应。
我现在运行之后是会在任务栏有纸飞机图标而不是 VPN 那种锁，升级到 2.9.x 之后不管哪种模式就都是锁了，我感觉跟这个应该有关系。是不是跟 root 有关系呢？感觉又不是
没辙了，android 版本怎么可以看到日志吗？求助……谢谢！

**Comment by madeye** [comment]
Try to uninstall and reinstall the app.

**Comment by pizzamx** [comment]
tried just now and no it doesnt work...
