### ISSUE TITLE
使用Tasker启动服务后的3种状态

### ISSUE THREAD

**Issue by wyzegob** [shadowsocks/shadowsocks-android#547]
![2016-01-21_091054](https://cloud.githubusercontent.com/assets/16571857/12468461/ef76e78c-c01e-11e5-8fb0-6e6ae1255b68.png)

日志
[log.zip](https://github.com/shadowsocks/shadowsocks-android/files/98502/log.zip)

不用tasker也会触发部分情况，只是概率不高吧。
不知道哪种是预期行为。

**Comment by madeye** [comment]
@CzBiX When switching the profiles in TaskerReceiver, I suggest to delay more than 5 seconds to avoid any potential race condition, like start the service when connecting or disconnecting.
