### ISSUE TITLE
关于dns解析的问题

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-android#548]
在udp转发开启的情况下，dns查询是否走的是udp，如果是能否修改成总是走tcp？

因为发现一个问题，在公共WIFI网络情况下大多udp端口都是被封的，导致开启udp转发不能解析DNS（ss的udp端口不能访问）。

**Comment by madeye** [comment]
No, you can't do that.

**Comment by dutonttie** [comment]
好吧！看来只有每次修改一下配置了。
