### ISSUE TITLE
Have you considered "proxy auto config" feature yet? 

### ISSUE THREAD

**Issue by boytm** [shadowsocks/shadowsocks-android#551]
Have you considered "proxy auto config" feature yet? 
If we use this feature in android system. This app just need to worked as a HTTP proxy and supply a proxy.pac file. So the DNS and socket to SOCKS5 related function can be moved to server side or even removed. This approach can simplify app. By the way, I think domain name based system is more accurate than IP based.

And I have already finished a prototype, a shadowsocks client but is HTTP proxy instead of SOCKS5 proxy.
https://github.com/boytm/mproxy

**Comment by madeye** [comment]
Nope, it's not going to work.

I suggest you try it yourself and then you will realize why we keep doing transparent proxy from the beginning.
