### ISSUE TITLE
Shall we use the ss-redir instead of redsocks+ss-local ?

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-android#552]
Shall we use the ss-redir instead of redsocks+ss-local ?

**Comment by madeye** [comment]
Nope, NAT mode is not supported anymore. In the future, we will only provide VPN mode, which is ss-local + tun2socks.

**Comment by ccaapton** [comment]
@madeye Transproxy mode need redsocks/ss-redir as well, could you re-evaluate the possibility?
