### ISSUE TITLE
分应用代理内的应用列表应该是全局的而不是per服务器配置的

### ISSUE THREAD

**Issue by kraml** [shadowsocks/shadowsocks-android#554]
我相信大多数用户的使用场景应该是哪些应用需要开启影梭代理基本上是固定的，经常需要变的是影梭服务器地址以应对网络状况的变化。

现在客户端的情况是每个配置文件的分应用代理配置是独立的。一开始我还以为客户端有bug造成我的选择没有正确保存，后来才发现是随着切换服务器配置而变的。

**Comment by madeye** [comment]
#353
