### ISSUE TITLE
更新到2.9后，越来越耗电了

### ISSUE THREAD

**Issue by bitweng** [shadowsocks/shadowsocks-android#555]
2.8 是很正常的，怎么到了 2.9 特别是 2.9.3 和 2.9.5，耗电特别多

![photo_2016-01-25_18-08-56](https://cloud.githubusercontent.com/assets/1287611/12548115/209eec10-c38f-11e5-96aa-b82e812c1adc.jpg)

![photo_2016-01-25_18-11-44](https://cloud.githubusercontent.com/assets/1287611/12548125/29c1fb84-c38f-11e5-9023-2749f03c9c63.jpg)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ
