### ISSUE TITLE
切换网络连接时工作不正常

### ISSUE THREAD

**Issue by mengyyy** [shadowsocks/shadowsocks-android#558]
切换网络后（wifi之间切换或者移动网络切换至wifi） 状态栏图标不见 此时网络连接不通 
 shadowsocks开关为正在运行状态（绿色）但是点击无反应无法停止  重置后台依旧无反应  
强行停止运行再启动恢复正常  
另 ：  偶尔启动时正常 （绿色 出现打勾）但上传下载为零 
nexus5  安卓6.0  已root    shadowsocks版本2.9.6

**Comment by madeye** [comment]
Make sure you are not using any background service killer or something else.
