### ISSUE TITLE
Not working with mobile network 

### ISSUE THREAD

**Issue by rexdf** [shadowsocks/shadowsocks-android#560]
It works quite well with WiFi but does not with mobile network. If I share mobile network as WiFi to my computer, pc client works too.

My configure is global and VPN mode. I grant the shadowsocks-android mobile network permission.  In mobile network , there is no Received and Sent data or speed .  

Is this a ROM issue?

**Comment by madeye** [comment]
Yes, I believe it's a ROM issue.

Double check you're not limiting background data usage of shadowsocks.
