### ISSUE TITLE
Some Requests May Incorrectly Treated as Mainland China Address

### ISSUE THREAD

**Issue by hFrNa** [shadowsocks/shadowsocks-android#562]
Hello,
I've noticed that shadowsocks-android doesn't support custom rules. This may cause some problems when using apps such as Apple Music for Android. When I log in with a US Apple ID and try playing my songs, shadowsocks-android transmitted its network traffic DIRECTLY instead of routing them to proxy. This leads to a very slow loading speed. Even though using "ALL" route mode can solve the problem, it is not a perfect solution. Note that even though I check the Apple Music app in Per-App Proxy with Bypass Mode disabled, it still doesn't route it to proxy as long as Bypass LAN & China selected.

I think if there's an option allows user to specify some domains or ip addresses to use proxy or not, this problem will be solved. I would really appreciate it if this problem solved in the future.
Thank you for your great work.

**Comment by madeye** [comment]
Unfortunately, it won't be supported.

Also, shadowsocks works correctly in your scenario, as Apple has CDN service in China.

**Comment by JunnanZ** [comment]
@madeye I have the exact same issue as OP. Apple's servers in China are very unstable and slow.
