### ISSUE TITLE
支付宝依然会走代理

### ISSUE THREAD

**Issue by ufo22940268** [shadowsocks/shadowsocks-android#564]
虽然在分应用代理中关闭了，但是貌似支付宝还是会走代理。
判断的依据是是开着shadowsocks，支付宝就会请求时间过长，甚至超时。

已经尝试过并且无效的解决方法如下：
- 重装shadowsocks-android
- 各种姿势设置代理
- 开关飞行模式

环境
- shadowsocks-android 2.9.3
- 支付宝 最新版本
- android 6.0.1

**Comment by madeye** [comment]
Do not use NAT mode.

**Comment by ufo22940268** [comment]
I didn't use NAT mode.

**Comment by madeye** [comment]
Uninstall and reinstall the latest version of shadowsocks.

**Comment by ufo22940268** [comment]
Ok, thanks.

**Comment by ufo22940268** [comment]
Seems fix this problem.
