### ISSUE TITLE
New option: bypass China only

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#569]
Some people need to connect to LAN addresses while bypassing China addresses. Do you think it's necessary to add this feature?

**Comment by madeye** [comment]
I'm always OK to add route options, as it's almost free in our current design.

You can add a new entry here: https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/values/arrays.xml#L45, then handle the logic in the service.
