### ISSUE TITLE
2.9.8在6.0.1上闪退

### ISSUE THREAD

**Issue by mrken2004** [shadowsocks/shadowsocks-android#575]
您好！刚才发现2.9.8在Nexus 6P和Nexus 9上闪退，两个设备都是Android 6.0.1。换回2.9.7则正常。

**Comment by eastmalon** [comment]
+1

**Comment by madeye** [comment]
Post your adb log here.

**Comment by jemyzhang** [comment]
下拉到功能设置，FC毕现。清除数据后没有问题。。。有没有简单的办法可以导入配置啊？

02-18 16:54:31.868 16101 16101 E InputEventReceiver: Exception dispatching input event.
02-18 16:54:31.869 16101 16101 D AndroidRuntime: Shutting down VM
02-18 16:54:31.891 16101 16101 E AndroidRuntime: FATAL EXCEPTION: main
02-18 16:54:31.891 16101 16101 E AndroidRuntime: Process: com.github.shadowsocks, PID: 16101
02-18 16:54:31.891 16101 16101 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.getEntry(DropDownPreference.scala:138)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.getSummaryValue(DropDownPreference.scala:46)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.getSummaryValue(DropDownPreference.scala:19)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.SummaryPreference$class.getSummary(SummaryPreference.scala:20)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.getSummary(DropDownPreference.scala:19)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.getSummary(DropDownPreference.scala:19)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.preference.Preference.onBindView(Preference.java:558)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.github.shadowsocks.preferences.DropDownPreference.onBindView(DropDownPreference.scala:169)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.preference.Preference.getView(Preference.java:495)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:1876)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:702)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.ListView.fillGap(ListView.java:666)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3448)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.AbsListView.onTouchMove(AbsListView.java:3844)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3675)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9300)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9520)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
02-18 16:54:31.891 16101 16101 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl
02-18 16:54:31.895   956  2558 W ActivityManager:   Force finishing activity com.github.shadowsocks/.Shadowsocks

**Comment by mrken2004** [comment]
02-18 16:58:51.576  8904  8904 D AndroidRuntime: Shutting down VM
02-18 16:58:51.594  8904  8904 E AndroidRuntime: FATAL EXCEPTION: main
02-18 16:58:51.594  8904  8904 E AndroidRuntime: Process: com.github.shadowsocks, PID: 8904
02-18 16:58:51.594  8904  8904 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.getEntry(DropDownPreference.scala:138)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.getSummaryValue(DropDownPreference.scala:46)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.getSummaryValue(DropDownPreference.scala:19)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.SummaryPreference$class.getSummary(SummaryPreference.scala:20)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.getSummary(DropDownPreference.scala:19)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.getSummary(DropDownPreference.scala:19)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.preference.Preference.onBindView(Preference.java:558)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.github.shadowsocks.preferences.DropDownPreference.onBindView(DropDownPreference.scala:169)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.preference.Preference.getView(Preference.java:495)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.AbsListView.obtainView(AbsListView.java:2346)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.ListView.makeAndAddView(ListView.java:1876)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.ListView.fillDown(ListView.java:702)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.ListView.fillGap(ListView.java:666)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3448)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.AbsListView.onTouchMove(AbsListView.java:3844)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3675)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:9300)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:9520)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
02-18 16:58:51.594  8904  8904 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.
02-18 16:58:51.598  1226  5738 W ActivityManager:   Force finishing activity com.github.shadowsocks/.Shadowsock

是这个不？

**Comment by madeye** [comment]
It seems related to https://github.com/shadowsocks/shadowsocks-android/pull/571

@Mygod Do you have any idea?

**Comment by Mygod** [comment]
I did realize that I forgot to update `shared_pref` in #571 but I don't think it will cause the crash though. Still looking...

**Comment by Mygod** [comment]
Oh that's why. XD *facepalm*

**Comment by madeye** [comment]
I always forget to test a Chinese environment...
