### ISSUE TITLE
Bypass Lan & China not working, it only bypasses Lan

### ISSUE THREAD

**Issue by hrzhu** [shadowsocks/shadowsocks-android#577]
Latest release. Bypass China is working fine but I need to access my router occasionally.

**Comment by zmrui** [comment]
I think Bypass china not work well,it also bypass lan.
Because with bypass-China on,I can login to my router on 192.168.1.1

**Comment by hrzhu** [comment]
Bypass China byasses Lan in VPN mode not in legacy mode. Currently I'm
using bypass China with VPN mode, it doesn't agree with the description but
that's what I want.

**Comment by hrzhu** [comment]
ef77019 has fixed bypass China in VPN mode. Bypass Lan & China in VPN mode still doesn't work. It bypasses Lan only. And these two options don't work in NAT mode.
