### ISSUE TITLE
Fail to access to the internet connection with the release 2.9.7~2.9.9

### ISSUE THREAD

**Issue by Balanky** [shadowsocks/shadowsocks-android#578]
After updated to the release 2.97~2.99, two of my android devices neither Galaxy S4 (android version 4.4.2 rooted) or Nexus 7 (2012 wifi android version 6.0.1 rooted) occur the same fault: falied to access the internet connection after rebooting the devices. Release 2.9.6 works fine.

**Comment by xufan6** [comment]
更新到play中最新版2.9.10之后 vpn模式无法连接，回退到2.9.4恢复，没找到别的版本的备份所以也无法测试。
