### ISSUE TITLE
Shadowsocks VPN mode makes some app fails with DNS error on Android 6

### ISSUE THREAD

**Issue by adam900710** [shadowsocks/shadowsocks-android#579]
After updated to Android 6.0, shadowsocks with Route mode (system VPN interface), is not working for some apps (gReader and feedly).

gReader will give error of "Unable to resikve host 'feedly.com': No address asociated with hostname".

However most apps work just normal, including G+, Chrome, Telegram(registration), Google maps, Weather channel.

NAT mode makes all apps happy though.

Other info:
OS: CyanogenMode 13
Shadowsocks config:
  Onetime authentication: No
  Route: Bypass LAN & China (Other mode all tryied, not working though)
  IPv6 Route: No
  Per-App Proxy: No
  UDP Forwarding: No (If set to yes, no app works)
  NAT mode: No

Thanks

**Comment by madeye** [comment]
Tried these apps, everything works well.

**Comment by adam900710** [comment]
Strange, will logcat help?

**Comment by madeye** [comment]
Try:

1. Empty `/system/etc/hosts` if you've modified it.
2. Switch airplane mode on and off.
3. Uninstall / reinstall feedly.

**Comment by adam900710** [comment]
Still same problem. With both wifi and LTE network.

Hosts is not modified though.

But with UDP forwarding enabled, affected apps (gReader) is OK to sync feeds.

BTW, for better locating the problem, I hope I understand the arch of SS on Android correctly.
(As I'm not familiar with Android though)
Does it follow the following workflow?
Like:
```
App --HTTP request --> <Android VPN interface> ---> SS App proxy --socks5 request--> sslocal ---> ssserver
```

As for normal Linux usage, my overall setup is quite different with android:
```
Firefox/Chromium -----------Socks 5 request ------\
                                                   ---> sslocal -----------> ssserver
wget --http request--> Privoxy --Socks5 request---/
```

**Comment by madeye** [comment]
It seems a ROM specific issue, properly caused by a broken VPNService implementation of your ROM. I suggest to try other ROMs instead, maybe a stable version of CM.

**Comment by adam900710** [comment]
Thanks, I'll try to update or use another ROM if possible.
Although there is no stable CM13 yet...

**Comment by fishinbox** [comment]
works fine under WLAN
However, cannot bypass the firewall under 3G/LTE.
Was able to get shadowsocks connection to server, but DNS lookup for application request failed.
UDP forwarding cannot help.

under CMCC/China Mobile

**Comment by vkings1** [comment]
Me too the same problem.
