### ISSUE TITLE
黑白名单内的应用在卸载后重新安装就失效了

### ISSUE THREAD

**Issue by LarkinZero** [shadowsocks/shadowsocks-android#58]
能不能记住黑白名单内的应用代理状态，使得即使应用卸载了，再下次安装该应用后，还能使用之前的代理设置。

**Comment by ffts** [comment]
我也希望能有个记住应用的黑白名单状态的功能
可能对一般用户没什么，主要是我使用绕行模式的时候，自己开发的应用需要连公司的调试环境，有的时候要卸载装其他版本，就得再把这个应用加到白名单里一次
如果卸载之后应用也依然在白名单里就方便了，不知道会不会考虑加上这么个功能呀

**Comment by Mygod** [comment]
+1，感觉还是记录 package id 比较好，这样刷机以后恢复了应用不用重新配置一遍。
