### ISSUE TITLE
影梭已有的配置文件如何删除？貌似只能添加不能删除，应该如何操作？

### ISSUE THREAD

**Issue by yuan78** [shadowsocks/shadowsocks-android#581]
如题

**Comment by madeye** [comment]
Swipe to right.

**Comment by Mygod** [comment]
Reopening this because it seems sometimes the tip dialog in profiles selector doesn't show at all.

**Comment by Mygod** [comment]
Oh wait it actually is working. Never mind.

**Comment by LNDDYL** [comment]
`<string name="profile_manager_dialog_content">&#8226; 点击选择配置文件；\n&#8226; 滑动删除；\n&#8226;
    长按拖动改变顺序。</string>`
[https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/values-zh/strings.xml](url) 裡面有寫啊。

**Comment by l123456789jy** [comment]
Swipe to right. 左划删除

**Comment by lya0** [comment]
滑动删除，不分左右

**Comment by L-cw** [comment]
nice！

**Comment by yuluoxk** [comment]
nice

**Comment by shawn1207** [comment]
umm...，mac can't slide
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/51145062/182123151-13baebbf-34dd-4478-bfb4-db59012421d5.png">

**Comment by xavier72bit** [comment]
> umm...，mac can't slide
> <img alt="image" width="1218" src="https://user-images.githubusercontent.com/51145062/182123151-13baebbf-34dd-4478-bfb4-db59012421d5.png">

将光标移动到待删除的配置文件，然后使用触控板双指向右侧划就可以了

**Comment by shawn1207** [comment]
> > umm...，mac can't slide
> > <img alt="image" width="1218" src="https://user-images.githubusercontent.com/51145062/182123151-13baebbf-34dd-4478-bfb4-db59012421d5.png">
> 
> 将光标移动到待删除的配置文件，然后使用触控板双指向右侧划就可以了

谢谢您，已经知道了
