### ISSUE TITLE
一个功能设想：增加自定义hosts文件

### ISSUE THREAD

**Issue by wang20150419** [shadowsocks/shadowsocks-android#582]
对一些没有root的安卓手机，是无法修改hosts文件的。

实际上，还是有未封的Google IP地址可用的。
我用shadowsocks, 更多的是同步 google 联系人、日历和邮件，
以及上twitter（也有未封IP）。

能不能加一个功能，就是支持 自定义 hosts 文件（支持通配符），
对自定义的hosts文件，只解析其IP地址，数据不走代理。

这样相当于通过 VPN，修改了未root的安卓手机的hosts文件。
我觉得这个功能很有用，代码量也不大。

**Comment by madeye** [comment]
Duplicate with #544
