### ISSUE TITLE
感谢各位开发者

### ISSUE THREAD

**Issue by johnhuo** [shadowsocks/shadowsocks-android#589]
今天看了一天的Twitter上某$99元工具，真心觉着作者太LOW。作为不明真相的路边吃瓜Android用户 ，平日用的最多的翻WALL工具是影梭，感谢你们花费精力和时间维护项目，还没有实际的回报。特地上来感谢各位开发者。(看到后关了此issues)

**Comment by madeye** [comment]
Locked as off topic.
