### ISSUE TITLE
Bypass China / Lan&China 有问题

### ISSUE THREAD

**Issue by iamty7** [shadowsocks/shadowsocks-android#593]
Phone: Oneplus One
Android: 5.1.1
Shadowsocks: 2.9.11以及之前的版本

不论是Bypass China还是Bypass Lan&China，使用国内的一些app的下载（比如豌豆荚或者荔枝FM），速度基本只有翻墙下载速度200k以下，但是断开ss即可跑满带宽。

另外开启ss时，微信、有信等语音无法连通，且访问微信公众号的推送内容、有些国内网页的速度也较慢。

**Comment by madeye** [comment]
Try per-app proxy instead.

**Comment by GH-JY** [comment]
你可以设置绕过局域网地址和内地地址的，不用全局代理就行了，就可以解决这个问题了，至于网速方面的问题，由于SS的DNS等原因，清下DNS缓存看下有没有改进，导致网速慢的原因，有一定可能性是服务端的网络不稳定导致的。

**Comment by nuzar** [comment]
仍然存在此问题

**Comment by wyzegob** [comment]
不要用nat模式。
nat模式必然引起 语音视频失败。
使用Bypass Lan&China 并且 vpn模式，per App。

**Comment by weipingli** [comment]
ok

**Comment by weipingli** [comment]
ok

**Comment by zackzeng00** [comment]
这个问题我也遇见了 
6.0系统
版本2.10
访问微信公众号，网易新闻 拉取图片都特别慢。
慢不是拉取速度慢而是响应速度慢

**Comment by kyze8439690** [comment]
WeChat videp/audio chat can not work because udp packet is dropped.

**Comment by hudson6666** [comment]
我有个问题 我是VPN模式 如果开着 Shadowsocks，QQ电话不能接听，接听的时候会一直“连接中”，但是可以打，打没问题。如果两个人都开着 Shadowsocks，就没办法了。这个在QQ还显得不那么重要，用 telegram 语音也不通，telegram 必须翻墙，就没办法语音通话了

注：开启了UDP转发依然存在此问题

可否帮忙解释一下这是为什么 以及可能的解决方案

十分感谢

**Comment by kyze8439690** [comment]
@hudson6666 因为ss现在命中规则的udp才会转发，其余udp都丢掉了
