### ISSUE TITLE
Shadowsocks cuases reboot on Redmi2 running Android 6

### ISSUE THREAD

**Issue by jimzhong** [shadowsocks/shadowsocks-android#595]
Hi, I am using a Redmi 2 flashed with third-party Android 6 rom. Occasionally when I click on the connect button for connecting or disconnecting, the whole Android UI freezes and the phone reboots in a second. It is very strange. But till now, I haven't been able to get any logs or dumps. I appreciate it if anyone can look into this problem.

**Comment by madeye** [comment]
It's a bug of your ROM, not shadowsocks.

**Comment by jimzhong** [comment]
Yes, I confirmed. Thank you.

**Comment by GH-JY** [comment]
try to root the phone @jimzhong

**Comment by palysoysauce** [comment]
@jimzhong 这个bug解决了吗在CM13里面？

**Comment by jimzhong** [comment]
@palysoysauce 我用nexus experience 10.3.3，问题依然存在。

**Comment by palysoysauce** [comment]
@jimzhong 你去反馈了吗？他们怎么说？

**Comment by jimzhong** [comment]
@palysoysauce 并没有，我开logcat的时候始终没能重现故障

**Comment by palysoysauce** [comment]
@jimzhong 我现在在log，发现，崩溃重启期间哪一段，不会在日记文件里面。

**Comment by jimzhong** [comment]
@palysoysauce 那如何debug呢？我发现这个现象在连接WLAN时不会出现。

**Comment by palysoysauce** [comment]
@jimzhong 我发现，更新0611nightly版本，和刷了Xposed的一个叫NoVpnMonitor的插件，没有有出现这种情况了。但是手机发热比MIUI严重，电池下降快，Xda论坛好像有教程但没看。最新CMROM下载地址：
[https://download.cyanogenmod.org/?device=wt88047](url)
更新日志以及未来开发日志：
[https://www.cmxlog.com/13/wt88047/](url)

**Comment by jimzhong** [comment]
@palysoysauce CM竟然支持红米2了，我去试试。不过我目前使用的这个ROM即使没有连VPN也会出现屏幕卡死两秒后重启。因此我觉得bug不在VPN。
