### ISSUE TITLE
发表每一个版本时，求附上md5和sha1

### ISSUE THREAD

**Issue by Sky1ine** [shadowsocks/shadowsocks-android#599]
发表每一个版本时，求附上md5和sha1

**Comment by madeye** [comment]
It's totally unnecessary. Every APK is signed with my private key, you can verify it easily with Google Play.

**Comment by johnhuo** [comment]
Some one has no Google play ,they always download the APK file from GitHub

Closed #599 <https://github.com/shadowsocks/shadowsocks-android/issues/599>.

—
Reply to this email directly or view it on GitHub
<https://github.com/shadowsocks/shadowsocks-android/issues/599#event-587100708>
.
