### ISSUE TITLE
Shadowsocks "Per-App Proxy" no longer works 

### ISSUE THREAD

**Issue by kydan** [shadowsocks/shadowsocks-android#606]
Just moved to a Xiaomi Mi5 (MIUI 7.0.2.6.0, android version 6.0 MRA58K) and the latest build of shadowsocks does not seem to work any longer when using the "per-app proxy" mode, both with routing=all || china || lan & china. I have also briefly tested on a Meizu MX5 (FlymeOS 5.1.2.0A android version 5.1) I have tested against the same server, but on two different IPs. I have also tested connectivity to this server on both IP's with the windows client. 

Running Shadowsocks version 2.9.11 on both. While I have not downgraded and tested with the previous release yet, I know that at least on my Meizu, it was working fine.

Please let me know how I can be of further help in debugging this.

**Comment by madeye** [comment]
It's a bug of MIUI. Please report it to MIUI team.

**Comment by kydan** [comment]
@madeye tested on seperate devices running different ROMs. Please read the full report. I'll test on my nexus 5 as well.

**Comment by madeye** [comment]
If so, also report it to Flyme team.

**Comment by kydan** [comment]
~~seems odd it would not work across two separate devices, on different versions of android. I can confirm that "per-app proxy" in 2.9.11 works fine on Nexus 5, and that 2.9.10 works on Mx5.~~

upgraded to 2.9.11 again to do a dump for the MIUI bug report and it was working. Very strange as I had tested multiple times and it always would connect when using the app without per-app proxy. Perhaps this is a network issue? I constantly get timeouts to my shadowsocks host. I am unclear on how shadowsocks authentication works. Anyone have advice for getting proper network logs on android?

**Comment by ilikecola** [comment]
The function works well on both L39t(Cyanogenmod12.1) and e6883(Android 6.0).
