### ISSUE TITLE
Fail to connect to SS server sometimes when switch from WLAN to Mobile Data

### ISSUE THREAD

**Issue by Jedliu** [shadowsocks/shadowsocks-android#608]
Hi there,

Thanks for this great APP. 

Sometimes it fail to connect to SS server when switch from WLAN to Mobile Data mode. It doesn't happen always. I noticed this when I found I can't get any messages from QQ. Although it looks like connected, but when I click the 'Check Connectivity' button it failed to visit Google.com. I chose the route 'Bypass LAN & China', when this occurs I can't visit any sites in China either. Disconnect and reconnect, it'll be normal again.

So is it possible to have a background checking service, when it lose internet connection just disconnect and reconnect again? 

Thank you very much.

**Comment by madeye** [comment]
It has nothing to do with network switch. You ROM killed the background processes of shadowsocks, causing connectivity issues here.

So, try some other ROMs instead, e.g CyanogenMod or any AOSP based ROM. Keep away from MIUI, Flyme and EMUI, especially unstable versions of MIUI.

**Comment by Jedliu** [comment]
Thanks for your fast reply. I've put 'Shadowsocks' in system Protected Apps. Is there any background service which should be protected as well?
