### ISSUE TITLE
Bypass China mode not working with chrome?

### ISSUE THREAD

**Issue by JunnanZ** [shadowsocks/shadowsocks-android#613]
First I want to make sure, can bypass mode and per-app proxy work together? If so, the bypass China mode seems not working properly on chrome (bypass Lan works well). Browsing Chinese websites is very slow and I'm sure it's using shadowsocks. Any suggestions?

**Comment by madeye** [comment]
Make sure:

1. Use VPN mode.
2. Bandwidth saver is not enabled in Chrome.

**Comment by JunnanZ** [comment]
Yes, I'm using data saver! Turning it off solves the problem. Thank you!
