### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by liaoran** [shadowsocks/shadowsocks-android#620]
远程端口能否设置成可以手动输入，有些远程端口设置的过万，要是这样的话，还不找半天，不方便，请下个版本修改下，谢谢

**Comment by v3aqb** [comment]
可是手动输入的

liaoran <notifications@github.com>于2016年3月24日周四 15:46写道：

**Comment by v3aqb** [comment]
可以手动输入的

江超 <sgzz.cj@gmail.com>于2016年3月24日周四 15:47写道：

**Comment by liaoran** [comment]
sorry，没仔细研究
