### ISSUE TITLE
能将OCR功能直接集成到APP内吗？

### ISSUE THREAD

**Issue by ssc19940105** [shadowsocks/shadowsocks-android#623]
能将OCR功能直接集成到APP内吗？这样就不需要多安装一个不怎么用的着的APP。

**Comment by AnyOfYou** [comment]
ORC 功能并不需要外部的 App，除非你需要写入到 NFC 标签中。仅仅两台设备之间通过 Android Beam 分享，或者一台设备扫描 NFC 标签添加，App 自身就可以完成。

**Comment by LNDDYL** [comment]
什麼App？

**Comment by LNDDYL** [comment]
ss似乎不需要文字辨識功能吧？
