### ISSUE TITLE
Update OpenSSL to 1.02f/1.01r or higher

### ISSUE THREAD

**Issue by LvWind** [shadowsocks/shadowsocks-android#627]
Hi, i've been noticed in my own project on google play console that Google Play will block publishing older versions of OpenSSL soon.
Seems shadowsocks-android is still using [1.0.1c](https://github.com/shadowsocks/openssl-android) or 1.0.1j.

refer:[https://support.google.com/faqs/answer/6376725](https://support.google.com/faqs/answer/6376725)

**Comment by madeye** [comment]
Good point! I've updated the header files of OpenSSL.

**Comment by Mygod** [comment]
This is just hacking the version codes. Shouldn't we do a real update?

**Comment by madeye** [comment]
Yes, we should be. But, I didn't see any changes of OpenSSL affecting shadowsocks yet, as we're using only several crypto functions from OpenSSL.

Maybe we can switch to mbedtls in the future releases to avoid these issues from Google.

**Comment by wongsyrone** [comment]
FYI, I found an [issue](https://github.com/ARMmbed/mbedtls/issues/229) talked about building via NDK for Android. I have not found any information indicated the situation has changed.
BTW, you may want to switch to 1.0.2 if the migration failed for some reasons.

Please refer to https://mta.openssl.org/pipermail/openssl-announce/2016-February/000063.html for more info.

**Comment by Mygod** [comment]
Wait, if we need only a few crypto functions, why do we need to include a whole SSL/TLS library? Sounds like an overkill.

I'm not familiar with the crypto libraries but how does `libgcrypt`, `Crypto++`, etc. sound?

**Comment by madeye** [comment]
That's why we only need to link `libcrypto.a` statically.

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/jni/Android.mk#L399

**Comment by wongsyrone** [comment]
If all needed are statically linked in, you can try CFLAGS="-ffunction-sections -fdata-sections" LDFLAGS="-Wl,--gc-sections" to reduce binary size.

**Comment by Mygod** [comment]
I meant if we are going to migrate to another library, why not try something more lightweight?

Also there are also some security updates for crypto libraries (I remember reading about one recently) so it's always safe to keep them updated.

**Comment by madeye** [comment]
In other words, it has nothing to do with `SSL` and we are safe to ignore SSL related vulnerabilities.

@wongsyrone I think we already `strip` the binary.

**Comment by madeye** [comment]
@Mygod Yes, so there is plan to switch to mbedtls which only consists of several source files.

**Comment by Mygod** [comment]
I still prefer to using libraries dedicated to cryptography functions like `libgcrypt`. Correct me if I'm wrong but these feel safer to use.

**Comment by wongsyrone** [comment]
redsocks depends on libevent and the library depends on openssl heavily, there is an existing issue talking about [implementing in another TLS library](https://github.com/libevent/libevent/issues/290). 
Otherwise you can drop redsocks and implement UDP relay in another way which can make use of mbedtls.
