### ISSUE TITLE
Unable to setup proxy when installed as system app

### ISSUE THREAD

**Issue by perqin** [shadowsocks/shadowsocks-android#629]
I copy the apk file to /system/app/Shadowsocks/ and set corrent permission(rw-r--r--), but when I reboot and clean data and press Start VPN button it is just loading ever and ever. Why can't it be installed as system app?

**Comment by madeye** [comment]
No plan to support this.

**Comment by xcjiang** [comment]
system app不是这么简单，不是把apk copy过去 就行了，还需要把apk里的lib放到/system/lib 下面。

**Comment by perqin** [comment]
@xcjiang 刚刚尝试了，不管放到哪里都不行……
