### ISSUE TITLE
How can I use it as a normal http proxy?

### ISSUE THREAD

**Issue by yanxurui** [shadowsocks/shadowsocks-android#633]
I got **message bad request syntax** on the server command line when I try to connect to a normal http server.
How can I use it as a normal http proxy or is there a better proxy?
By the way, it works well when I use a previous version  2.1.3.

Thx!
![1](https://cloud.githubusercontent.com/assets/12461110/14377205/2ebcf764-fda1-11e5-9619-2b3a2801a6a5.jpg)

**Comment by madeye** [comment]
Nope.
