### ISSUE TITLE
How about input port number rather than scroll?

### ISSUE THREAD

**Issue by ilikecola** [shadowsocks/shadowsocks-android#634]
Sometimes servers' remote port is so big that entering servers' remote port is extremely inconvenient.How about input a number rather than scroll?

**Comment by AnyOfYou** [comment]
You can tap the number to input.

**Comment by xcjiang** [comment]
建议界面修改一下，输入大数字明显不适合滚动输入，多少人都迷惘了，这个设计欠考虑。

**Comment by x-ji** [comment]
Well I still think the selection wheel is redundant and potentially misleading, not to mention a keyboard will be displayed even if the user doesn't tap, however this keyboard doesn't actually modify the number. Just my two cents.
