### ISSUE TITLE
solve youtube problem

### ISSUE THREAD

**Issue by iamsurfing** [shadowsocks/shadowsocks-android#636]
people can surf the internet in youtube app but they can not watch youtube video, because /system/bin/mediaserver connect failed

please add a option named "mediaserver" in per app agent list , and this option can add user "media"  in NAT mode.

**Comment by madeye** [comment]
Use bypass mode

**Comment by huangyg11** [comment]
bypass mode是指 “功能设置->路由->绕过中国大陆地址” 吗？ 我试了还是不能看youtube视频。

**Comment by iamsurfing** [comment]
不是，是指绕行模式
我说的是谷歌商店和油管的视频是需要一个二进制文件mediaserver传输，而mediaserver是属于media用户组的，要把media用户组也设置成nat模式才可以正常看视频。
实在不行你用chrome的html5版油管也可以正常看视频。

**Comment by huangyg11** [comment]
用的不是nat模式，是vpn模式，要怎么设置呢
