### ISSUE TITLE
关于热点共享的问题

### ISSUE THREAD

**Issue by zy2688** [shadowsocks/shadowsocks-android#639]
假设有个3ds或者ipad，用wifi连到了开启热点共享的android手机上
手机开启了ss客户端
那么这个3ds或者ipad如何使用到手机的ss？

**Comment by madeye** [comment]
It won't work.

**Comment by xiaobuu** [comment]
+1 求此功能

**Comment by Mygod** [comment]
Some quick googling finds this: https://forum.xda-developers.com/general/networking/guide-how-to-wifi-tether-vpn-droidvpn-t2990751

**Comment by xiaobuu** [comment]
@Mygod Thanks! It works for me!

**Comment by Mygod** [comment]
There are also plenty of apps out there that does this.

This one works for me but its ads is too annoying: https://play.google.com/store/apps/details?id=com.ardadem.tethervpn

**Comment by oras903** [comment]
做个android    ss-redir 的程序行不？

**Comment by Mygod** [comment]
I think I will make a separate app that works for any system wide VPN AND sucks less.

**Comment by Mygod** [comment]
Consider it done: https://github.com/Mygod/VPNHotspot/releases

Please help test.

**Comment by vexetron** [comment]
@Mygod Thank you so much. I need not consider it done, for it's done authentically.
