### ISSUE TITLE
Question:配置切换失效(自编译)

### ISSUE THREAD

**Issue by myplane** [shadowsocks/shadowsocks-android#640]
按照说明进行:
1. git clone (试了 'master' 和 'tag-v2.10.1'分支)
2. -init(同步 jni库 )
3. build jni库
4. build
不曾修改任何文件，但编译完成安装使用时，切换配置操作后没有任何变化，只能使用单个配置。而当前的'master'主分支编译运行时，一旦点击左上角的名称"shadowsocks"就会"停止运行"。
不知是系统(Ubuntu-64 15.10)原因还是哪里的配置不当，有时间帮我分析分析。

**Comment by Mygod** [comment]
Check if your build succeeded. Try a manual reset and/or wiping app data.

**Comment by myplane** [comment]
编译过程没看到错误(说是有些特性并不支持当前的api 16)，有几个warn(和"string.xml"文件的翻译不全有关)，签名证书是自用的，其它的就没什么了

**Comment by AnyOfYou** [comment]
Try to sbt clean before build.
