### ISSUE TITLE
在bypass China的情况下，是所有域名的解析都经过服务器吗？

### ISSUE THREAD

**Issue by withlqs** [shadowsocks/shadowsocks-android#641]
这种情况下，国内域名的解析延迟会不会过大，导致体验下降或者解析不到最快的cdn？

**Comment by madeye** [comment]
Nope.

**Comment by withlqs** [comment]
因为ss-android没有gfwlist，那么判断是否from China，都要根据ip规则。

如果不经过远程服务器解析域名的话，可能会导致dns污染，继而影响bypass的判断。那么域名的解析就需要通过远程服务器进行。

如果在bypass China的情况下，所有域名都经过远程服务器来解析。显然会影响解析速度和国内网站cdn的准确性。

不知可否增加gfwlist来规避这个问题？

**Comment by xcjiang** [comment]
我的理解域名解析应该是在本地完成的，域名解析也需要通过ss？

**Comment by withlqs** [comment]
你使用nslookup www.facebook.com，在打开和关闭ss-android的情况下，是不同的返回ip

**Comment by xcjiang** [comment]
我看了一下代码，在vpn服务里指定了８.８.８.８作为ｄｎｓ，而８.８.８.８是通过ｓｓ中转的。所以你说的是对的，确实有这个问题，不过你提出的那个gfwlist的解决方法应该不行，实现不了的，要解决这个问题还需要另外的思路。

**Comment by withlqs** [comment]
我目前的解决方法是，让某些app不走ss。看上去效果会好很多
