### ISSUE TITLE
Compatibility problem

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-android#642]
I'm running multiple Shadowsocks servers onto linux (shadowsocks-libev).
I'm using shadowsocks-libev client onto linux
I'm using shadowsocks-android client onto android
Now I'm running Shadowsocks-server (go) onto Windows server

(shadowsocks-libev server) <-> (shadowsocks-libev client) works fine
(shadowsocks-libev server) <-> (shadowsocks-android client) works fine

(shadowsocks-go server onto windows) <-> (shadowsocks-libev client) works fine 
(shadowsocks-go server onto windows) <-> (shadowsocks-android client) tells NO INTERNET CONNECTIVITY

**Comment by madeye** [comment]
Double check your config. Make sure UDP and Onetime Auth are not enabled.

**Comment by dimzon** [comment]
this is my shadowsocks-libev client config (works fine)
```
cat /etc/shadowsocks-libev/config.json
{
 	"server":"LOL",
	"server_port":8998,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"LOL",
    "timeout":600,
    "method":"aes-256-cfb"
}
```
UDP and Onetime Auth are not enabled (!).

**Comment by dimzon** [comment]
I can PM you server IP && PASS so you can check it yourself. Libev client works fine. Android tells no connectivity...

**Comment by dimzon** [comment]
OMG. This was a wrong password! 
Isn't it possible to detect wrong password during initial handshake attempt and show some diagnostic message?

**Comment by Mygod** [comment]
No.
