### ISSUE TITLE
华为荣耀5X 5.11 EMUI3.1最新版本的ss无法使用

### ISSUE THREAD

**Issue by sonic32** [shadowsocks/shadowsocks-android#643]
连接成功，但是无法翻出去。
是否不支持此ROM？或者后续版本会解决这个问题？

**Comment by madeye** [comment]
Report this issue to EMUI team instead.

https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ

**Comment by yujiaolong** [comment]
大家好，请问shadowssocks用什么工具做开发，目前我编译出来了，然后想学习下里面代码，不知道用什么开发工具做，指点我一下

发自我的 iPhone
