### ISSUE TITLE
关于二维码扫描的建议

### ISSUE THREAD

**Issue by andronoob** [shadowsocks/shadowsocks-android#645]
尝试用二维码导入配置时会提示安装Barcode Scanner，但实际上用其他二维码扫描器也可以扫描ss的二维码，甚至可以把ss配置做成链接，但貌似ss界面上并没有说明？
反正我的第一感觉是：必须安装那个“御用”的条码扫描器才可以导入配置。
虽然实际上可以更灵活：可以用其他扫描器，也可以直接做成链接，点击即可导入，但这些都是我后来的偶然发现。

关于条码扫描器……我记得那个扫描器（com.google.zxing.client.android）需要从Google Play上安装——这把用户带入了窘境：没翻墙怎么能访问Google Play？
而且此扫描器貌似缺少扫描本地图片的功能，要是好友传来一张二维码，用户可能直接就抓瞎了……
现在FAQ里推荐了一个条码扫描器，但仍然有不少人不知道FAQ页面在哪里，甚至连GitHub是什么都不知道……而且FAQ上贴的是Google Play 的链接，仍然会碰到“没翻墙上不了Google Play”的窘境。

希望开发者为中国国情多妥协一点，哪怕只是在软件界面上多几句文字说明，谢谢。

**Comment by madeye** [comment]
No plan for this.
