### ISSUE TITLE
The ss floating window always appear in gear VR

### ISSUE THREAD

**Issue by jack2007** [shadowsocks/shadowsocks-android#647]
Hi,

When I use ss-android for gear vr with SAM-SUNG Note5, everything works fine except the floating window. It always shows on the VR screen.

**Comment by Mygod** [comment]
Which floating window?

**Comment by madeye** [comment]
There's no floating window from shadowsocks. Upload a screenshot if you could.

**Comment by jack2007** [comment]
Floating window which displays the network input/output bytes per second.
It only shows when using with gear VR device.
If my phone is not plugged with VR device, there is no floating window.

I'll try to capture a screeshot.

**Comment by Mygod** [comment]
I assume you are talking about the notification. In that case it's probably Samsung VR's bug. Check your notification settings to turn it off.

**Comment by jack2007** [comment]
Yes, it's the notification windows; After I turn off the ss notification, it's OK now. Thanks
