### ISSUE TITLE
增加导出/导入配置文件的功能。

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#648]
希望能加入这个功能。原因是，我在编译新版本安装后，程序会FC，需要清理数据才能正常运行。但是这样配置文件就没了，重新添加麻烦。

**Comment by madeye** [comment]
No plan for this.

**Comment by PerFect-i-SM** [comment]
That's a good idea

**Comment by AnyOfYou** [comment]
Actually this feature (export/import to clipboard) already exist in current release version.

**Comment by Mygod** [comment]
Not yet.

Speaking of that, isn't it time for another release? @madeye

**Comment by madeye** [comment]
I'll schedule a release recently.

**Comment by GH-JY** [comment]
这个没什么用吧。。安卓版。。

**Comment by eproall** [comment]
I want to know where to export the file? Not even a hint
