### ISSUE TITLE
android shadowsocks 无法使用

### ISSUE THREAD

**Issue by nikki70** [shadowsocks/shadowsocks-android#651]
系统是5.0.2
连接后，访问谷歌提示
DNS_PROBE_FINISHED_NO_INTERNET
刷新dsn缓存，依然不行，全局模式／分应用代理 都不行。
同ip ，端口 mac端可以正常使用。
用的是 python ss ，其他版本试过go，也不行。
要如何设置安卓手机 才能正常访问？

还有校园网，window／osx 都无法正常使用ss
检查提示：
检测如下：
[2016-04-20 01:57:21] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
在 System.Net.Sockets.Socket.get_RemoteEndPoint()
在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
————————————
校园网好像不支持ipv6
还是我vps设置问题， 用的是python一键安装ss。。
求指点 谢谢！

**Comment by madeye** [comment]
You have to diagnose network issues yourself.

**Comment by nikki70** [comment]
如何诊断。。

**Comment by nikki70** [comment]
VPN可以使用
ss 不行

**Comment by nikki70** [comment]
dns检查 设置allowed 重启后依然不行
飞行模式下 刷新dns  不行
开启nat模式 不行
。。。。
why , i don't understand..

**Comment by xcjiang** [comment]
不要开启udp转发
