### ISSUE TITLE
Please consider supporting Android for Work

### ISSUE THREAD

**Issue by oasisfeng** [shadowsocks/shadowsocks-android#659]
ShadowSocks works in the multi-user mode on Android, but not the managed profile mode, which shares the same nature of classic multi-user with some differences in parallel running.

I guess there's just some minor adaption work to be done to support Android for Work.

FYI: http://android-developers.blogspot.com/2015/11/testing-your-app-for-android-for-work.html

**Comment by madeye** [comment]
Assigned to myself for triage.

**Comment by madeye** [comment]
I tried shadowsocks 2.10.3 with Android for Work and it works surprisingly well.

The only trick I found is when you enable shadowsocks through Android for Work, it will set up a profile only VPN connection, which means only the apps in the same Android for Work profile would go through this connection. Or in the other words, shadowsocks becomes a per-profile proxy, not a global proxy.

If you still have any other question, please let me know.

**Comment by oasisfeng** [comment]
Sorry, my fault. With another Nexus device for comparison, I've found the cause. The system app "com.android.vpndialogs" is not correctly enabled on the previous test environment. After enabling it, ShadowSocks works well now.

Thanks for your quick reply and apologize for my false report.
