### ISSUE TITLE
Can you please publish shadowsocks to F-Droid?

### ISSUE THREAD

**Issue by rnons** [shadowsocks/shadowsocks-android#66]
China mainland users are suggested to download shadowsocks from coolapk.com. However, for reasons we all know, coolapk is not very "cool".

> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. 

Shadowsocks should be included in [F-Droid](https://f-droid.org/) repository.

**Comment by bsdhsr** [comment]
Why was this closed without reply? It makes a lot of sense to have to have this available on f-droid!
