### ISSUE TITLE
Bug: VPN dialog notification remains when disconnected from ipv6 hosts

### ISSUE THREAD

**Issue by nicedayever** [shadowsocks/shadowsocks-android#660]
DEVICE: ANDROID 5.1
SS-VERSION: 2.10.3

When SS disconnected from the IPv6 Shadowsocks Server, The VPN dialog notification bar DID NOT disappear, it still remained in the notification bar even the SS program was killed.

When SS disconnected from IPv4 SS server, everything was fine.

**Comment by madeye** [comment]
I believe it's a bug of your device or Android system. VPN icon is managed by system and disappears when VPN connection is lost.
