### ISSUE TITLE
与酷安冲突?

### ISSUE THREAD

**Issue by uniquepengpeng** [shadowsocks/shadowsocks-android#662]
环境:MX3,android5.0,最近版本的ss android(NAT模式)和酷安安卓市场,在酷安apk里面下载更新apk时,ss android 有很大的几率进程被杀.(已经设置了后台常驻进程和给了ROOT权限).不知道是什么情况.

**Comment by madeye** [comment]
I should be a bug of Flyme. Please report this issue to Meizu instead.
