### ISSUE TITLE
状态切换里能不能加个无代理的状态？

### ISSUE THREAD

**Issue by chitanda** [shadowsocks/shadowsocks-android#665]
RT。有时候有些网站必须关闭代理才可以访问（web 端局域网认证页面等），但是停止了后状态栏不能常驻通知栏，然后要重新找到app 开启，比较麻烦。
所以希望在切换那里加个无代理的状态（或者希望通知栏里停止可以改成暂停

**Comment by Mygod** [comment]
Add a profile with per-app proxy enabled for Shadowsocks only, bypass mode off.

**Comment by madeye** [comment]
As mentioned above, you can setup a profile to only proxy shadowsocks itself.

**Comment by chitanda** [comment]
@maydeye @Mygod thanks a lot. I got it
