### ISSUE TITLE
Android N Quick Setting Tile support

### ISSUE THREAD

**Issue by 109021017** [shadowsocks/shadowsocks-android#671]
A quick setting toggle for shadowsocks in the new notification panel would be much convenient.
[Android N Tile api](http://developer.android.com/preview/api-overview.html#tile_api)

**Comment by AnyOfYou** [comment]
I'm tried to implement this feature a few days ago, but it's seems this feature don't have any detailed API for now.

**Comment by Mygod** [comment]
That sure sounds convenient. I know CyanogenMod has support for custom tiles as well. I'll look into both when I've got time. :-)

**Comment by Mygod** [comment]
After digging around for a while, I implemented a draft of quick settings tile for N preview. It can now display service status and open main activity on click. I didn't find anything to provide a custom user interface though. I expect to see this improvement in the official N release. :-)

See the commit above for more details.

**Comment by Mygod** [comment]
For some reasons, I can't seem to add custom tiles to my device (CM13). I've also tried another app and it didn't work. Postponing supporting CM APIs as well. For anyone that's interested, I've also pushed a commit into my fork. (see above)

**Comment by madeye** [comment]
Awesome! Let's keep this issue open and wait until the Android N API becomes stable.

**Comment by Mygod** [comment]
Just checked Android N preview 3 docs. Nothing was added for quicksettings Tile API. I have submitted an issue at Android's issue tracker. Hopefully something will happen soon. :-)

**Comment by 109021017** [comment]
The Android N APIs are now final.

**Comment by Mygod** [comment]
Apparently [nothing has changed](https://developer.android.com/reference/android/service/quicksettings/package-summary.html). Merging after doing some final test.

**Comment by Mygod** [comment]
The quick settings tile has been changed to a quick switch button. It costs only ~4MB RAM when Shadowsocks isn't running.

**Comment by madeye** [comment]
@Mygod :thumbsup:

**Comment by 109021017** [comment]
👍
So is this update gonna be released any time soon?
I'm really looking forward to it.
