### ISSUE TITLE
UDP forwarding not working and one specific issue

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#672]
Issue 1
remote (server) side:
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled)
   Active: active (running) since $TIME
 Main PID: 201 (ss-server)
   CGroup: /system.slice/shadowsocks-libev.service
           └─201 /usr/bin/ss-server -a root -c /etc/shadowsocks-libev/config.json -u

local (client) side:
Android shadowsocks 2.10.3 in Android 6.0.1 on device nexus 5
BYPASS LAN+CHINA
if UDP forwarding enabled, all apps will lose internet access, and the browser returns DNS error.

Issue 2
in bypass mode (bypass LAN+CHINA)
the Reuters App is unable to connect, switching to the global mode solves the problem. other app work well.
The Reuters app is from Google play.
https://play.google.com/store/apps/details?id=com.thomsonreuters.reuters

**Comment by madeye** [comment]
Double check your server's firewall settings. Make sure outgoing DNS packets are allowed.

**Comment by GitatHub** [comment]
You mean that I have to enable PORT 53 on the server? Does not Shadowsocks client use the shadowsocks port to relay DNS inquiries? I see shadowsocks-libev opened a port 53813. Is this for UDP forwarding?
netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:44              0.0.0.0:*               LISTEN      201/ss-server   
tcp6       0      0 :::44                   :::*                    LISTEN      201/ss-server   
udp        0      0 0.0.0.0:53813           0.0.0.0:*                           201/ss-server   
udp        0      0 0.0.0.0:44              0.0.0.0:*                           201/ss-server   
udp6       0      0 :::44                   :::*                                201/ss-server

**Comment by GitatHub** [comment]
Could you please tell me what else to deal with the iptables?
