### ISSUE TITLE
The connection is intermittent for some apps.

### ISSUE THREAD

**Issue by Umit-** [shadowsocks/shadowsocks-android#677]
When the problem happens, `Spotify` and all `Google apps` on my Android device couldn't connect to the server, and I also cannot access to https://www.google.com/. But other apps like `Dropbox` works fine at the same time.

During this time, it's OK to access to those websites through changing your Internet environment. **Notice that all Internet environment may encounter this problem, but they don't encounter it *at the same time*.** The problem will last few hours and nobody knows when it will happen again.

I first encountered the problem when I was using a KitKat device few years ago, and I changed a lot of Shadowsocks server but the problem still exists.

I also tried different Route options, the NAT mode, and clear the DNS cache. But it's all useless.

I'm sure the problem is not cause by my Shadowsocks server, because other devices (such as my Mac and iOS devices using `Surge` , my PC using `Shadowsocks C#` and my Ubuntu laptop using `Shadowsocks-Qt5`) didn't meet this problem.

**Comment by madeye** [comment]
To me, it looks like a DNS cache poisoning issue. If you are using devices with Android 4.4 or below, try to switch off/on airplane mode.

To solve this issue, please keep using VPN mode on Android 5.0 or above.

**Comment by Umit-** [comment]
I am now using a Marshmallow device. The problem happens on all my Android devices from KitKat to Marshmallow (I didn't try Android N yet). And it will happen both in VPN mode and NAT mode.
