### ISSUE TITLE
Include config name and ota in ss scheme

### ISSUE THREAD

**Issue by humiaozuzu** [shadowsocks/shadowsocks-android#678]
Such as `ss://xxx?ota=false&remark=foobar` used by [shadowrocket](https://itunes.apple.com/us/app/shadowrocket/id932747118)

It will be much convenient when imported config also have a name :P

**Comment by madeye** [comment]
https://shadowsocks.org/en/config/quick-guide.html
https://github.com/shadowsocks/shadowsocks-org/issues/16

**Comment by Mygod** [comment]
OTA has been supported with #644.

**Comment by humiaozuzu** [comment]
@Mygod @madeye Thanks. How about the configuration name?
