### ISSUE TITLE
Battery drain on android 6.0

### ISSUE THREAD

**Issue by xubin990510** [shadowsocks/shadowsocks-android#679]
If i turn battery optimization on for shadowsocks i wont be able to tunnel through shadowsocks in battery saver mode, while disabling optimizations makes shadowsocks the biggest power consumer on my phone, (used 37% as mesuared by system, while screen is 27%)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#why-does-shadowsocks-consume-so-much-battery-on-android-50

**Comment by xubin990510** [comment]
No, that's not the case. If I turn battery optimization on (NEW feature for Marshmallow) that item for Shadowsocks will be gone; what I don't understand is just why I can't use Shadowsocks in Battery Saver Mode (if I keep the battery optimizations on for Shadowsocks)

**Comment by xubin990510** [comment]
![screenshot_20160513-052041](https://cloud.githubusercontent.com/assets/7804730/15230876/8912fe76-185d-11e6-8676-06f524d29267.png)
![screenshot_20160511-140805](https://cloud.githubusercontent.com/assets/7804730/15230875/8912befc-185d-11e6-8967-da43590fa755.png)
@madeye as you can see, this is the difference between enabling Battery Optimization for Shadowsocks and not enabling it.
By the way, Battery Optimization Settings for Shadowsocks is here:
![screenshot_20160513-052639](https://cloud.githubusercontent.com/assets/7804730/15231013/63632e2a-185e-11e6-9b8e-bc25511fa13e.png)

**Comment by xubin990510** [comment]
Oh, and the detail page in battery settings shown for Shadowsocks is a service called `tun2socks`, if that helps. Please reopen this.

**Comment by xubin990510** [comment]
@madeye

**Comment by madeye** [comment]
As mentioned in that link, shadowsocks will be reported as the top battery consumer on Android 5.0 or above, even though you put it in the optimization list.

In terms of battery saver, if you enable daze mode (battery optimization) for shadowsocks, Android system will limit the background traffic of shadowsocks' background service, causing the issue you mentioned.
