### ISSUE TITLE
切换到NAT模式再切换回VPN模式导致DNS解析失败

### ISSUE THREAD

**Issue by bydeath** [shadowsocks/shadowsocks-android#681]
我想试试NAT模式下的分应用代理。之后点了刷新DNS和重置所有后台服务。之后切换到VPN模式下，访问网络就出现DNS解析失败的问题，就连访问baidu也出现DNS解析失败。关闭该应用后，访问内网一切正常。清除数据，卸载后重装还是同样的问题。后来我不得不重新刷新固件，再装该应用之后好了。再也不敢切换至NAT模式了。或许是我点击了刷新DNS按钮导致的。

**Comment by madeye** [comment]
NAT mode is already deprecated.

**Comment by bydeath** [comment]
那为什么我在最新版的界面还能看到这个选项并且进行切换。

**Comment by zif68** [comment]
搞得要刷固件那么严重，，，，

**Comment by HougeLangley** [comment]
Only deprecated on Android 5.0 and before, 6.0 and after work great. I think NAT Mode is nice.
