### ISSUE TITLE
NAT mode iptables rule modification

### ISSUE THREAD

**Issue by x5ERZzk** [shadowsocks/shadowsocks-android#683]
Hi, I believe in NAT mode there should be a correction to the rule allowing Shadowsocks connect to remote server. When some app uses some service on the same server (on different port however) it will not be connected via the proxy but it will communicate with the server directly (it gets bypassed by the mentioned rule). Therefore I suggest to also match the port specified for Shadowsocks server. I believe it is the line:
init_sb.append(cmd_bypass.replace("-p tcp -d 0.0.0.0", "-d " + config.proxy))
that might be good to change to something like this:
init_sb.append(cmd_bypass.replace("-d 0.0.0.0", "-d " + config.proxy + " --dport " + config.remotePort))
in the ShadowsocksNatService.scala file.

Thanks for amazing work!

**Comment by madeye** [comment]
NAT mode is already deprecated

**Comment by madeye** [comment]
Also the correct line you're looking for is:

```
  init_sb.append(cmd_bypass.replace("-p tcp -d 0.0.0.0", "-m owner --uid-owner " + myUid))
```

**Comment by x5ERZzk** [comment]
Yes, you are right, I should have done more thorough analysis. However, since it blocks my use-case scenario, may I ask what is the
init_sb.append(cmd_bypass.replace("-p tcp -d 0.0.0.0", "-d " + config.proxy))
line for?
Sincere apologies for bothering you further.
