### ISSUE TITLE
bypass china is invalid when server is a IPv6 address

### ISSUE THREAD

**Issue by eastmalon** [shadowsocks/shadowsocks-android#684]

**Comment by wongsyrone** [comment]
说的是访问网站的服务器地址是v6吧，可以试试加上v6的中国路由表条目

**Comment by eastmalon** [comment]
不是访问ipv6网站。我的shadowsock服务端只能通过ipv6连接，配置里的server就是填的ipv6地址。此时路由选择bypass china失效，只有选择all才能访问Google。
同样的配置使用PC端的ss能正常使用。
