### ISSUE TITLE
Scanning on mobile does not accept  QRcode created by url with 'REMARKS'

### ISSUE THREAD

**Issue by Jamieezhou** [shadowsocks/shadowsocks-android#685]
QR code created in below format can be recognized and accepted by computer client, but not by android client.  
$ssurl =  $method.":".$pass."@".$server.":".$port."#".$remarks;

However if the remarks part is removed (which is  ."#".$remarks), both clients work.  Can android client get enhanced to support the remarks tag?

**Comment by madeye** [comment]
No plan for this.
