### ISSUE TITLE
certpathvalidatorexception trust anchor for certification path not found

### ISSUE THREAD

**Issue by kcschan** [shadowsocks/shadowsocks-android#688]
This issue happens on
Android N Developer Preview 3 (NPD35K)

Shadowsocks-android can successfully establish the connection, how ever actual payload transfer is not available. 

The logcat shows:

> 
03-21 00:42:58.032: W/Babel_NetConnCheckSvc(6887): IO exceptions, probably not a captive portal 
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(SourceFile:337)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.Connection.connectTls(Connection.java:235)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.Connection.connect(Connection.java:172)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.apps.hangouts.service.NetworkConnectionCheckingService.a(SourceFile:134)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.apps.hangouts.service.NetworkConnectionCheckingService.onHandleIntent(SourceFile:1105)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.os.Looper.loop(Looper.java:154)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:531)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:490)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:490)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:386)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:272)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:87)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:116)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(SourceFile:169)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(SourceFile:565)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(SourceFile:333)
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	... 18 more
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
03-21 00:42:58.035: W/Babel_NetConnCheckSvc(6887): 	... 30 more

**Comment by madeye** [comment]
Double check your config. According to your log, the error has nothing to do with shadowsocks.

Also tried the latest Android N, everything works well.

**Comment by kcschan** [comment]
Sorry this seems to be a local config/server side error just as what you said.
Thank you for the reply.
