### ISSUE TITLE
我想确认一下软件上是否有广告

### ISSUE THREAD

**Issue by yylzcom** [shadowsocks/shadowsocks-android#689]
非常感谢作者提供这么好的软件。

最近我有一个疑惑，本人手机上一直都没有广告（google play安装版本），朋友的国行手机没有google play，从我手机上下载一个用qq上传过去了，结果他手机上在软件底部出现了一个广告，如图：
http://ww2.sinaimg.cn/large/3fd49500gw1f41vggcv7zj20u01hc0w4.jpg

另外有两位推友说本来就是带有广告的，请问是这样的吗？

**Comment by madeye** [comment]
Duplicate with #669.

Yes, you would see a AD if you are using the default profile
To remove the AD, please remove the default one and use your own profile .
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#ui-tips
