### ISSUE TITLE
Need a faster way to import multiple profiles at one time

### ISSUE THREAD

**Issue by a359566926** [shadowsocks/shadowsocks-android#694]
Although the client supports many ways to import profiles, they're still a little inconvient, especially when I need to import multiple profiles at one time.

I found that the "Import from Clipboard" can import multiple profiles at one time now, but I must generate the URIs first.

I think we can make use of the "gui-config.json" which is used in shadowsocks-windows. Copy the text of it or just pick it by a FileSelector, and then all the profiles in it are imported, I think it will make android users feel cool!

**Comment by madeye** [comment]
No plan for this.

**Comment by madeye** [comment]
The best way to import multiple profiles is enabling Android's built-in backup and restore feature.

**Comment by a359566926** [comment]
I'm not restoring my profiles... It's because my shadowsocks service provider always change the profiles, and I have to update my profiles...

**Comment by bimzcy** [comment]
So do I, no json import is boring.
