### ISSUE TITLE
梭梭的安卓版这几天死了吗？PC端没问题

### ISSUE THREAD

**Issue by YoungPix** [shadowsocks/shadowsocks-android#695]
这几天没有用手机梭梭，今早链接了几次，只有上行流量，但没有下行流量，一个bytes都没有。

在瓦工那边换了服务器和密码还是不行。版本是梭梭安卓的 2.10.3，加密方式aes-256-cfb。（换了几种情况还是如上）

PC端相同设置无问题，连接顺畅，难道安卓端被定点清除了？

PS.用lan灯能上，go也没问题
瓦工那边还有一周快到期了，大神们有什么好点的serv能建议一下。自己用，性价比高点的。谢谢

@madeye

**Comment by madeye** [comment]
Please check the FAQ before submitting new issues.
