### ISSUE TITLE
In file "shadowsocks.scala", line 241-244, fab.isEnabled is always true. 

### ISSUE THREAD

**Issue by hophacker** [shadowsocks/shadowsocks-android#697]
In file "shadowsocks.scala", line 241-244, fab.isEnabled is always true. 
Either the `if` clause is meaningless or there's something missing here.
```scala
    if (fab.isEnabled) {
      fab.setEnabled(false)
      handler.postDelayed(() => fab.setEnabled(true), 1000)
    }

```

**Comment by madeye** [comment]
Makr sure you understand how handler works in Android.
