### ISSUE TITLE
WhatsApp calls ring but do not connect

### ISSUE THREAD

**Issue by ridium** [shadowsocks/shadowsocks-android#698]
WhatsApp calls ring but do not connect when answered. Sending WhatsApp messages, photos, and videos works. The log sees the connection but provides no additional information about timeouts, blocked connections, etc.

**Comment by madeye** [comment]
Enable UDP relay or bypass WhatsApp.

**Comment by ridium** [comment]
Enabling UDP worked. Thanks, apologies for not checking that sooner.

**Comment by Elmouu** [comment]
@madeye  but please how to do that i have seem issue

**Comment by chweto** [comment]
by pass whatsapp, then can passthrough video or voice call sometimes, and then cannot download photo or voice message. (Cancel by pass mode, then can download photo or voice message, but video or voice calls cannot get through)

**Comment by Elmouu** [comment]
I have Forget all of That anyway thanks

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Tony CHAN <notifications@github.com>
Envoyé : Monday, May 28, 2018 3:56:47 AM
À : shadowsocks/shadowsocks-android
Cc : Elmouu; Comment
Objet : Re: [shadowsocks/shadowsocks-android] WhatsApp calls ring but do not connect (#698)


by pass whatsapp, then can passthrough video or voice call sometimes, and then cannot download photo or voice message. (Cancel by pass mode, then can download photo or voice message, but video or voice calls cannot get through)

**Comment by IdioticMadman** [comment]
How to enable UDP relay in version 4.7.0? Because this happened again

**Comment by chweto** [comment]
> Enable UDP relay or bypass WhatsApp.

bypass WhatsApp NOT working, same other apps: Telegram, Viber, Messenger, etc...
