### ISSUE TITLE
有自动断线的情况

### ISSUE THREAD

**Issue by hezma** [shadowsocks/shadowsocks-android#699]
设备:努比亚Z5S  Android4.4.2  nubia UI2.0
root状态:已root
问题:在使用本软件时，发现存在自动断线的情况，不过频率不高。断线时状态栏图标与正常连接一致，进入软件可手动关闭，需清除后台内存（软件本身的）才能正常重启。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#why-are-miui-emui-and-other-aosps-in-china-not-officially-supported
