### ISSUE TITLE
运行一段时间之后分应用代理失效

### ISSUE THREAD

**Issue by yangyaofei** [shadowsocks/shadowsocks-android#700]
lg g3 官方rom

一段时间之后分应用代理的app无法正常连接网络，测试的app有qq和微信

重置后台服务无效，重启ss无效，切换服务器无效，最终利用系统自带的vpn断开连接解决

可能导致的原因可能是ss的切换应用导致，可能是句柄获取的问题，也可能是每次断开的时候句柄没有清除干净导致。
也可能是ss server不稳定和上述问题一起导致的

不知道我还能提供什么信息，比如log

**Comment by madeye** [comment]
It should be a bug of your ROM. Make sure no background process killer app is installed.
