### ISSUE TITLE
Need to add manual bypass settings

### ISSUE THREAD

**Issue by PRIHLOP** [shadowsocks/shadowsocks-android#702]
Please, add settings for manual adding bypass domains and IP ranges.
It demand for example in ISP networks, when ISP provide local services or when sites availible only in internal country network.

**Comment by madeye** [comment]
Sorry, no plan for this. If you really need this feature, my suggestion is to modify https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/values/chnroute.xml and build your own APK.

**Comment by PRIHLOP** [comment]
Ok, thanks for answer.
It is a pity that it is not planned.
