### ISSUE TITLE
[discuss] A better implement for shadowsocks client. (privoxy+ss-local+whitelist)

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-android#703]
Hi, I hope discuss a better implement for shadowsocks client.

following is a working process for me. it worked very well in my 
android phone and linux laptop for a while.

I think it is better than official shadowsocks-android, in fact,
I almost not use ss android client for now. though, some linux
binary command is extract from this app.

### 2. config [privoxy](http://www.silvester.org.uk/privoxy/)

privoxy have very stable window/android/linux implement.

basically, add following config:

```sh
# forward http request to socks (notice dot at line end)
forward-socks5   /               127.0.0.1:1081 .

# add a ss action, we will create this action file later.
actionsfile shadowsocks.action

# intercepted requests be treated as valid.
# we  should configure packet filter to redirect 
# outgoing HTTP connections into Privoxy.
accept-intercepted-requests 1
```

### 3.  config shadowsocks.action, content is following:
```sh
{+forward-override{forward .}} 
# white list pattern here, one pattern one line.
localhost
[0-9].[0-9].[0-9].[0-9]
0.0.
10.0.
127.0
169.254.
172.16.
192.168.
224.0
240.0
.6.com
.gold.net
.00.net
.0000738.com
.0001688.com

... 

.zzyzphoto.com
.zzzmode.com
.zzzyb.com
.zzzyit.com
```
[here](https://github.com/R0uter/gfw_domain_whitelist/blob/master/whitelist.pac) is a whitelist can be extract from.

### 4. start privoxy. listening at 8118 port. 
we can use this proxy for all request.
if domain name is in white list, privoxy willskip socks forward
otherwise, will forwoard to ss-local.

### 5.  iptables settings.
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8118

this work well for my linux terminal and firefox.  but not chrome.
in android, this is not worked too, i have to manually set WiFi proxy 
settings to make my phone work.  , i wonder how proxydroid  is implement
global http proxy.

## Pros
1. filter by domain name, ChinaDNS is not need.
2. white list is more easy to maintain. 
3. all site could be access, even white list is not involve.
3. less complexity. 

## Cons
1. maybe some not blocked site is access from socks server.
    which use more proxy bandwidth.  (this is not a big things currently)

**Comment by madeye** [comment]
First of all, you should understand the difference between a nomal HTTP proxy and a transparent proxy.

Then, you may need to read through shadowsocks-android's source code to figure out how shadowsocks-android works and why it adopted the transparent proxy approach from the very beginning.

Also, if you're interested, you can do some research on this project (https://github.com/madeye/BaoLianDeng), which is doing something similar to your proposal, except it is black list based and has its own limitations.

**Comment by zw963** [comment]
Fine.
Anywhy, I think it is the time to use whitelist instead of blacklist mechanism.

**Comment by zw963** [comment]
>> iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8118

this work well for my linux laptop, when use firefox and working in terminal,
I could access blocked site directly without any extra settings.
(though, I don't know why chrome not worked for me. i have to use
google-chrome --proxy-server=127.0.0.1:8118 to make it effect.)

privoxy can accept intercepted requests, this is worked somelike similar 
transparent proxy ?

**Comment by zw963** [comment]
I think there should a way to make ```iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8118``` worked well in android phone.

I am reading your another project (proxydroid).
i read following shell scripts,
```cl
$DIR/redsocks -p $DIR/redsocks.pid -c $DIR/redsocks.conf
 iptables -A INPUT -i ap+ -p tcp --dport 8123 -j ACCEPT
 iptables -A INPUT -i ap+ -p tcp --dport 8124 -j ACCEPT
 iptables -A INPUT -i lo -p tcp --dport 8123 -j ACCEPT
 iptables -A INPUT -i lo -p tcp --dport 8124 -j ACCEPT
 iptables -A INPUT -p tcp --dport 8123 -j DROP
 iptables -A INPUT -p tcp --dport 8124 -j DROP
 iptables -t nat -A PREROUTING -i ap+ -p tcp -d 192.168.43.1/24 -j RETURN
iptables -t nat -A PREROUTING -i ap+ -p tcp -j REDIRECT --to $proxy_port
 ```
Why your solution is worked? 
```iptables -t nat -A PREROUTING -i ap+ -p tcp -j REDIRECT --to $proxy_port```
just because there exist a virtual interface ap+ ?
