### ISSUE TITLE
Try to rewrite this app by Java. But keep getting connect() failed: Connection refused (socket fd = %d) bug

### ISSUE THREAD

**Issue by zhgqthomas** [shadowsocks/shadowsocks-android#704]
I know this was issued before. But I delete all the UNIX socket file like you told on issued #382 . I get connection refused bug even when I first try to start the VPN. I can't fine where is the problem. Please help me.

**Comment by madeye** [comment]
1. You have to debug your own code by yourself.
2. It makes no sense to rewrite this project to Java.
