### ISSUE TITLE
Why i can't build ss-android project?

### ISSUE THREAD

**Issue by ferrywon** [shadowsocks/shadowsocks-android#706]
I use git bash to build the project. BUT it appear a error :

[error] (*:nativeBuild) java.io.IOException: Cannot run program "./build.sh": CreateProcess error=193, %1 ??????▒▒?? Win32 ??▒▒
[error] Total time: 0 s, completed 2016-6-3 16:43:54

I setuped the sbt already , what else i missed ?

What should i do?

**Comment by ferrywon** [comment]
My system is windows

**Comment by madeye** [comment]
You need a Linux or Mac OS to build this project.
