### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#707]
It's been more than a month since last release and I just pushed two UI-related bugfixes:

* https://github.com/shadowsocks/shadowsocks-android/commit/07798c7e5638619fb78cf1b921b38ecffb338034
* https://github.com/shadowsocks/shadowsocks-android/commit/5afb8b9cd443bfaf5468c2dbb939c07825e113d3

**Comment by madeye** [comment]
I'm testing latest shadowsocks-libev. When it's ready, there will be a new release.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/releases/tag/v2.10.4
