### ISSUE TITLE
why is file size on google play smaller than github

### ISSUE THREAD

**Issue by dzzzm** [shadowsocks/shadowsocks-android#709]
Although it is described as 4.3mb on google play ,when downloading, it shows a size of 3.6mb?

**Comment by madeye** [comment]
Double check the size on the download page.

**Comment by dzzzm** [comment]
@madeye the size description on google play is 4.34mb ,and the file size on Github is also 4.34mb. But why when I click the download button on Google Play, it shows a size of 3.6mb? I have double checked it. It quite confuses me

**Comment by madeye** [comment]
Try to install the APK on your device. If it's corrupted, your Android device will refuse to install it.

**Comment by Mygod** [comment]
Ask Google.
