### ISSUE TITLE
标题shadowsocsk后的倒三角字符显示不出来

### ISSUE THREAD

**Issue by maoyuanrun** [shadowsocks/shadowsocks-android#714]
> ```<string name="screen_name" translatable="false">shadowsocks ▾</string> ```

字库缺少“▾”，结果显示为口

![screenshot.png](https://ooo.0o0.ooo/2016/06/13/575e8443aa751.png)

**Comment by madeye** [comment]
@Mygod What about using an icon instead?

**Comment by Mygod** [comment]
Okfine.
