### ISSUE TITLE
Can we have a SUSPEND button in the notification view?

### ISSUE THREAD

**Issue by qwert42** [shadowsocks/shadowsocks-android#715]
For example, between the STOP button and SWITCH button. I really want this SUSPEND button so that I can quickly turn on/off shadowsocks with just a swipe and a click.

Or maybe you could provide me some hints and I'll implement this myself and create a PR: I see that I need to add an action in `ShadowsocksNotification.scala` and pass a SUSPEND intent, and that I probably need to modify the `closeReceiver` value in `BaseService.scala`. But I'm not sure how to restart shadowsocks. Where can I get the `config` argument?

Thank you guys for making this wonderful app!

**Comment by madeye** [comment]
Sorry, no plan for this. VPN setup is not a trivial task. Quick on/off will introduce other issues.

**Comment by Mygod** [comment]
For an alternate approach, see #665.
