### ISSUE TITLE
Cannot access reuters news with UDP forwarding off

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#716]
If turn UDP forwarding off and use PDNSD, App (com.thomsonreuters.reuters) will not be able to connect to its server. However, with UDP forwarding on, it's resolved.
I see that *.reuters.com is included in the GFWlist. Why did the BYPASS LAN/CHINA mode cannot handle this domain?
Settings:
Bypass LAN/CHINA; ANDROID 6.0.1; NOT rooted
Thanks.

**Comment by madeye** [comment]
It works for me. Reboot your phone and try again.

**Comment by GitatHub** [comment]
rebooting cannot solve this.
this issue occurred several months ago.

**Comment by madeye** [comment]
Still, I suggest you to try again. It looks like a DNS poisoning issue of your phone.

**Comment by GitatHub** [comment]
It's normal to see a DNS poisoning on my network, but what do you mean DNS poisoning on my phone? It's not rooted.
is it possible that an normal app in android can affect the DNS of the phone.
I checked the DNS 114.114.114.114
it return cn.reuters.com an invalid IP 37.61.54.158
one of the real IP should be server-54-192-141-105.sfo5.r.cloudfront.net (54.192.141.105) with cloudfront protection.
