### ISSUE TITLE
Need disable SPDY for android

### ISSUE THREAD

**Issue by pandorla1984** [shadowsocks/shadowsocks-android#722]
need exact function IOS have to compatiable with facebook app

**Comment by madeye** [comment]
Facebook works well with shadowsocks-android.

**Comment by pandorla1984** [comment]
I'm not talking about facebook, the website works well, but the app doesn't. the app use SPDY which shadowsocket doesn't support. the app will report network issue when connected. that's exactly why IOS version has the function to disable SPDY, Please make a work-around or add the same function.
