### ISSUE TITLE
Need disable SPDY for android

### ISSUE THREAD

**Issue by pandorla1984** [shadowsocks/shadowsocks-android#723]
The facebook android app can't connect through shadowsocket. I'm not talking about facebook website, the website works well, but the app doesn't. the app use SPDY which shadowsocket doesn't support. the app will report network issue when connected. that's exactly why IOS version has the function to disable SPDY, Please make a work-around or add the same function.

**Comment by madeye** [comment]
Facebook app works well with shadowsocks-android. Make sure you're using VPN mode.

**Comment by pandorla1984** [comment]
I'm in VPN mode and I can use facebook app with other VPN solution. I
attached my environment, may anything related with the server end?









Max Lv <notifications@github.com>于2016年6月18日周六 17:29写道：

**Comment by pandorla1984** [comment]
Shadowsocket version 2.10.4
Android 6.0
Fb version 81.0.0.22.70
