### ISSUE TITLE
Tunnel OpenVPN over android shadowsocks (launched from .sh script or NAT mode )

### ISSUE THREAD

**Issue by tonsimple** [shadowsocks/shadowsocks-android#726]
Hi!
Long story short, I've read about desktop shadowsocks being used to tunnel openvpn traffic

Now, I've found out that ics-openvpn OpenVpn android client supports socks-proxy directive.

Also, as far as I can tell, android-shadowsocks supports UDP relay.

So, if I launch shadowsocks from command line (or use the deprecated NAT mode), I should be theoretically able to tunnel OpenVPN over shadowsocks on android?

Any particular "gotchas" that would keep me from using it this way?

**Comment by madeye** [comment]
Nope, you can't. Shadowsocks-android works as a transparent proxy, not socks5 proxy.

**Comment by tonsimple** [comment]
So, the "local port" it listens on is pretty much moot ?

**Comment by madeye** [comment]
Shadowsocks-android will listen on this "local port" for transparent proxy. Make sure there is no conflict of this port with other apps, e.g. file sharing, video streaming, and other proxy apps.

**Comment by tonsimple** [comment]
That's no problem, nothing interesting besides shadowsocks and openvpn intended my question was basically whether directing openvpn(udp) to that port will result in anything but failure
