### ISSUE TITLE
联通流量网络 DNS失效

### ISSUE THREAD

**Issue by badegglei** [shadowsocks/shadowsocks-android#730]
Sony X Performance (F8132) 6.0.1 未root
shadowsocks 2.10.4
在聊天流量网络 2/3/4G下 国内外网络都不能访问 错误是DNS无法解析
wifi 下无问题
(可能是双卡的缘故吗?)

**Comment by badegglei** [comment]
恩是双卡 我把卡换到SIM 1就好了 @madeye

**Comment by badegglei** [comment]
你没计划支持双卡吧 @madeye

**Comment by madeye** [comment]
It's a bug of your device. Report it to Sony instead.

**Comment by badegglei** [comment]
k ty 4 ur work @madeye
