### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-android#732]
Move frequently used options above the server settings
In the UI, I think the following order of options will be more user-friendly
(the topper the options are frequently used in my phone condition)

[Network Traffic]
-[contents omitted] ; (I recommend to display the profile name in this dark banner)

[Reset] ; this is the most frequently used.

[Feature settings]
-UDP forwarding ; usually used because sometimes you have to turn it on for preventing being DNS-poisoned.
-Route ; sometimes used, sometimes 'by pass LAN' does not work for LAN FTPserver. 
-[order for the rest options are not cared]

[Misc] ; the current order is OK

[Server settings]
- One-time authentication; sometimes used for testing
- (others omitted)

[Flush DNS cache] ; never used on unrooted devices

[about]

**Comment by madeye** [comment]
Don't use 'reset' frequently. It has side effects.

**Comment by GitatHub** [comment]
sometimes have to reset, otherwise the phone will lose the connection.
