### ISSUE TITLE
[report for wiki] turns out it IS possible to tunnel OpenVPN over shadowsocks on android

### ISSUE THREAD

**Issue by tonsimple** [shadowsocks/shadowsocks-android#733]
Hi!
Just reporting it in a separate issue because it might be of interest and might warrant being put on a wiki.

Long story short, you can run openvpn over shadowsocks on android

Prerequisites 
Root
Busybox
Shadowsocks (specifically the ss-local binary)

First, create a custom folder (let's say /data/custom) in /data/ and move ss-local there 
create a config for shadowsocks there 

NB! Disable "normal" shadowsocks VPN (of course)

shadowsocks must be launched as root 

su -c sh nohup /data/custom/ss-local -u -A -f /data/custom/custompid.pid -c /data/custom/shadowsocksconfig.conf&

Let's say our config specifies port 2090 as the listening one for our manually launched, root-user shadowsocks (to ensure it doesn't conflict with anything)
Let's say our shadowsocks server is 107.183.14.53

Now configure ics-openvpn (only android openvpn client to support socks-proxy directive)

Create a normal openvpn config

Now enable custom options under server
Add socks-proxy 127.0.0.1:2090 

Now go to routing tab and add 107.183.14.53/32 under Excluded Networks

Attempt connection.

Surprisingly enough, connection is established and ipleak.net shows the openvpn server's IP

N.B.
It does not work if ss-local is not run as root.

**Comment by madeye** [comment]
Thanks for the input. But I don't think it's necessary.
