### ISSUE TITLE
Profile name missing problem

### ISSUE THREAD

**Issue by humiaozuzu** [shadowsocks/shadowsocks-android#734]
When I click export in profiles page and import again using 'import from clipboard'.
The newly imported profile's names are missing and replaced with the profile's server address.

Any way to fix it?

**Comment by Mygod** [comment]
Copy and paste.

**Comment by humiaozuzu** [comment]
@Mygod If I have multiple profiles, copy and paste one by one is not convenient. Anyway to automate this?

**Comment by Mygod** [comment]
@humiaozuzu Why would you have multiple profiles with the same name? How could you distinguish one from another?
