### ISSUE TITLE
在 android 6.0 中使用扫码功能时，没有自动请求相机权限。

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#735]
导致扫码功能不能用。
我现在是手工给它开了相机权限。

**Comment by Mygod** [comment]
This app uses other apps to scan QR codes so permissions aren't required.

**Comment by madeye** [comment]
@Mygod It's added in a537a7fc0a0ca339e53936f49e49088eddd8762d 😳
