### ISSUE TITLE
开启绕开中国大陆和局域网地址后，访问国内的某些网站还会走代理

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#740]
比如有时候访问 baidu.com 输入 ip 查询当前 ip 地址，有时显示的 ip 是 vps 的 ip

**Comment by madeye** [comment]
Make sure you didn't enable UDP relay.

**Comment by pexcn** [comment]
服务端打开udp relay，但是客户端没有开

**Comment by wongsyrone** [comment]
可能是中国路由表更新了，你可以看看 https://github.com/wongsyrone/shadowsocks-android/commit/bfdbd4a128138ff06e3e86ee0fa5a0f52d7ec5be#diff-0a1a0cd47a081dee70f77b350248068e 这里有没有对应的ip

**Comment by pexcn** [comment]
Ok~

**Comment by Mattosx** [comment]
@pexcn  请问下，不管我是否开ss，我用联通4g访问 ipip.net 和 ip138.com 怎么显示的ip 是国外的，但是不是vps ip。我用baidu.com 搜索ip 是北京联通的。难道联通对访问国外的线路做了nat吗？

**Comment by Mattosx** [comment]
@madeye 请问下，是不是对于在 gfwlist 里面的污染域名 才做 dns tcp 查询啊？我是指未开启 ss-android 里面 udp 转发的情况。

**Comment by madeye** [comment]
Right.

**Comment by pexcn** [comment]
@Mattosx 不清楚...我广东联通4G访问ipip.net 和 ip138.com都是显示广东的ip...

**Comment by Mattosx** [comment]
@madeye 明白了。感谢。
