### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by cc9014** [shadowsocks/shadowsocks-android#75]
新手一枚，目前只编译过四次元。
./build-ndk 阶段就报错。

...
[armeabi] Compile thumb  : ext6 <= gen_libip6t_rt.c
[armeabi] Compile thumb  : ext6 <= gen_libip6t_hbh.c
[armeabi] Compile thumb  : ext6 <= gen_libip6t_frag.c
[armeabi] StaticLibrary  : libext6.a
[armeabi] Compile thumb  : ip6tc <= libip6tc.c
[armeabi] StaticLibrary  : libip6tc.a
[armeabi] Compile thumb  : xtables <= xtables.c
In file included from jni/iptables/iptables/xtables.c:35:0:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/magic.                     h:16:0: warning: "AFFS_SUPER_MAGIC" redefined [enabled by default]
 #define AFFS_SUPER_MAGIC 0xadff
 ^
In file included from C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/us                     r/include/sys/statfs.h:1:0,
                 from jni/iptables/iptables/xtables.c:31:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/vfs.h:75                     :0: note: this is the location of the previous definition
 #define  AFFS_SUPER_MAGIC      0xADFF
 ^
In file included from jni/iptables/iptables/xtables.c:35:0:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/magic.                     h:20:0: warning: "EFS_SUPER_MAGIC" redefined [enabled by default]
 #define EFS_SUPER_MAGIC 0x414A53
 ^
In file included from C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/us                     r/include/sys/statfs.h:1:0,
                 from jni/iptables/iptables/xtables.c:31:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/vfs.h:83                     :0: note: this is the location of the previous definition
 #define  EFS_SUPER_MAGIC       0x00414A53
 ^
In file included from jni/iptables/iptables/xtables.c:35:0:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/magic.                     h:24:0: warning: "HPFS_SUPER_MAGIC" redefined [enabled by default]
 #define HPFS_SUPER_MAGIC 0xf995e849
 ^
In file included from C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/us                     r/include/sys/statfs.h:1:0,
                 from jni/iptables/iptables/xtables.c:31:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/vfs.h:89                     :0: note: this is the location of the previous definition
 #define  HPFS_SUPER_MAGIC      0xF995E849
 ^
jni/iptables/iptables/xtables.c: In function 'ipaddr_to_host':
jni/iptables/iptables/xtables.c:1094:43: warning: passing argument 1 of 'gethost                     byaddr' from incompatible pointer type [enabled by default]
  host = gethostbyaddr(addr, sizeof(struct in_addr), AF_INET);
                                           ^
In file included from jni/iptables/iptables/xtables.c:22:0:
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/netdb.h:204:                     17: note: expected 'const char _' but argument is of type 'const struct in_addr                      *'
 struct hostent *gethostbyaddr(const char *, int, int);
                 ^
[armeabi] Compile thumb  : xtables <= xtoptions.c
[armeabi] StaticLibrary  : libxtables.a
[armeabi] Executable     : ip6tables
[armeabi] Install        : ip6tables => libs/armeabi/ip6tables
[armeabi] Compile thumb  : iptables <= iptables-standalone.c
[armeabi] Compile thumb  : iptables <= iptables.c
....
[armeabi] Install        : iptables => libs/armeabi/iptables
[armeabi] Executable     : pdnsd
C:/Android/android-ndk-r9d/platforms/android-9/arch-arm/usr/lib/crtbegin_dynamic                     .o:crtbrand.c:function _start: error: undefined reference to 'main'
collect2.exe: error: ld returned 1 exit status
/cygdrive/c/Android/android-ndk-r9d/build/core/build-binary.mk:601: recipe for t                     arget 'obj/local/armeabi/pdnsd' failed
make: *_\* [obj/local/armeabi/pdnsd] Error 1
mv: 无法获取"libs/armeabi-v7a/iptables" 的文件状态(stat): No such file or direct                     ory
mv: 无法获取"libs/x86/iptables" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi/pdnsd" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi-v7a/pdnsd" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/x86/pdnsd" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi/redsocks" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi-v7a/redsocks" 的文件状态(stat): No such file or direct                     ory
mv: 无法获取"libs/x86/redsocks" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi/ss-local" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi-v7a/ss-local" 的文件状态(stat): No such file or direct                     ory
mv: 无法获取"libs/x86/ss-local" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi/ss-tunnel" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi-v7a/ss-tunnel" 的文件状态(stat): No such file or direc                     tory
mv: 无法获取"libs/x86/ss-tunnel" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi/tun2socks" 的文件状态(stat): No such file or directory
mv: 无法获取"libs/armeabi-v7a/tun2socks" 的文件状态(stat): No such file or direc                     tory
mv: 无法获取"libs/x86/tun2socks" 的文件状态(stat): No such file or directory

大概就是这样，不知道怎么办，大神求解答。

**Comment by bygreencn** [comment]
@ageback 给点你目前编译的状态，编译环境的构建信息吧，我想把minSdkVersion改到15编译给自己用。
