### ISSUE TITLE
编译出错，大神能给看看啥原因吗？

### ISSUE THREAD

**Issue by PsjJourney** [shadowsocks/shadowsocks-android#756]
[**erro**r] Unable to locate SDK proguard config: /home/.android/sbt/sdktools/proguard/proguard-android.txt
[**error**] (android:proguardConfig) Unable to locate SDK proguard config: /home/psj/.android/sbt/sdktools/proguard/proguard-android.txt

**Comment by kaneawk** [comment]
It does not have this problem.

**Comment by PsjJourney** [comment]
I want to know how to solve this problems,thanks

**Comment by madeye** [comment]
Try to update or reinstall your SDK.

**Comment by pfn** [comment]
Sorry, was a bug in sbt-android, it is fixed in scala-android/sbt-android@b34aa3a

**Comment by pfn** [comment]
Oh, and in the mean time, you can work around this by `export ANDROID_HOME=$HOME/.android/sbt/sdk` in your shell
