### ISSUE TITLE
[Pull Request] Use Shell.Interactive interactively and removes iptables submodule

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#757]
https://github.com/Mygod/shadowsocks-android/tree/interactive
https://github.com/Mygod/shadowsocks-android/commit/4d8125da3c9a3fdb6a6f86ceb9c762eba5534e41

The following action will take only one SU request with this commit:

* Start service in NAT mode;
* Reset in NAT mode;
* Flush DNS.

And stopping service in NAT mode doesn't need SU request any more.

GitHub doesn't let me create a PR since I removed a submodule.

**Comment by madeye** [comment]
Merged. Thanks!
