### ISSUE TITLE
unable to start vpn service

### ISSUE THREAD

**Issue by kiruto** [shadowsocks/shadowsocks-android#758]
os: android 6.0.1, device: nexus 6
NAT mode can run correctly, but VPN mode cannot run.
here is the logcat:

W/AppOps: Bad call: specified package com.github.shadowsocks under uid 10035 but it is really 10310
E/Shadowsocks: Failed to start VpnService

i tried several times, uninstall, edit uid, manifest and rebuild, are not affected.

**Comment by kiruto** [comment]
selinux mode change is not affected too.

**Comment by madeye** [comment]
Make sure you're using the official ROM from Google.

**Comment by kiruto** [comment]
ofcourse official ROM

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#troubleshooting

**Comment by kiruto** [comment]
thanks for replay.
i tried all of solution but wipping app data.

the logcat says "Bad call: specified package com.github.shadowsocks under uid 10035 but it is really 10310" & "E/Shadowsocks: Failed to start VpnService".
i find the "10035" is the user of vpndialogs.

root@shamu:/ # ps | grep 10035                                                 
11653 10035      0:00 {roid.vpndialogs} com.android.vpndialogs
root@shamu:/ # ps | grep shadowsocks
 1421 10310      1:01 {hub.shadowsocks} com.github.shadowsocks

is there something wrong?

**Comment by madeye** [comment]
Try to restart your phone.

**Comment by kiruto** [comment]
still not work.
on my nexus4 device, when i connect, it shows a vpn dialog. but on my nexus 6, it doesn`t show any dialog.
thanks for answer.

**Comment by Mygod** [comment]
Try reinstalling.

**Comment by kiruto** [comment]
@Mygod i tried for times, but still not work. thanks
