### ISSUE TITLE
分应用代理中点击“应用设置到所有配置文件”会导致分应用代理设置失效

### ISSUE THREAD

**Issue by aenerv7** [shadowsocks/shadowsocks-android#759]
版本：2.10.6

在我选择好需要代理的应用后，点击那个“应用到所有配置文件”按钮会导致之前选择好的应用列表被清空，并且也未能将之前的选择好的列表应用到其他配置文件中

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#troubleshooting

**Comment by aenerv7** [comment]
和 [issue 760](https://github.com/shadowsocks/shadowsocks-android/issues/760) 一样，我在删除后重新安装 2.10.6 版本和删除后重新安装 2.10.5 版本两种操作之后，还是发现问题存在。

我的猜测是可能这个功能就是把当前配置文件中的应用设置执行“导出至剪切板”再对其他配置文件执行"从剪切板导入"，由于 [issue 760](https://github.com/shadowsocks/shadowsocks-android/issues/760) 的存在所以导致这个功能也失效了？

由于这是个新功能所以我没办法在早于 2.10.5 的版本上测试了，请问能否麻烦再测试检查一下呢？谢谢！
