### ISSUE TITLE
分代理应用中“导出至剪切板”功能失效

### ISSUE THREAD

**Issue by aenerv7** [shadowsocks/shadowsocks-android#760]
版本：2.10.6

在选择好需要代理的应用后，点击“导出至剪切板”，然后再进入别的配置文件选择“从剪切板导入”并不会有效果。之后我尝试在可编辑的区域里将导出的内容粘贴出来但无法粘贴，因为其实点击那个按钮并未导出任何内容，自然也就无法粘贴了

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#troubleshooting

**Comment by aenerv7** [comment]
在删除后重新安装 2.10.6 版本和删除后重新安装 2.10.5 版本两种操作之后，还是发现问题存在，这次发现粘贴到剪切板中的内容如下

> false
> (无论勾选了多少个 app，此处均为一行空白)

后来我又安装了 2.10.4 版本测试了一下，随意勾选了两个 app 导出后，剪切板里为下列内容

> false
> 
> com.google.android.configupdater
> com.google.android.gm

看起来似乎是出现在 2.10.5 和 2.10.6 版本上的问题，请问能否麻烦再测试检查一下？

另：虽然我的手机系统是 MIUI，但是根据之前的使用经验和导出的内容来看，这个导出功能应该是和本身手机系统关系不大的。

**Comment by Mygod** [comment]
Clear app data.

**Comment by aenerv7** [comment]
尝试了一下清除应用数据，包括彻底删了重装，都还是有这个问题

**Comment by aenerv7** [comment]
刚才尝试了一下清除应用数据，仍然有这个问题，又试了一下删除重装，还是有这个问题...

**Comment by aenerv7** [comment]
我刚才看了眼代码，似乎是把各种设置写到了 SQLite 里，由于我手里头机器 MIUI 的 Android 版本还是 5.1.1，会不会和不同 Android 版本上的 SQLite 有关？
