### ISSUE TITLE
Redesign Android TV interface

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#762]
(so that Google Play can stop rejecting this app)
# Redesign mobile UI
- [x] Switch to preference lib in Android Support lib. (wow we even switched to a third-party support lib fix lib now)
- [x] Redesign mobile interface with drawers.
- [x] Make profiles page the main UI.
# Redesign TV UI
- [x] Create submodules for TV, mobile and core. (did it in the beta branch)
- [ ] Split functionalities.
- [ ] Redesign TV interface with LeanbackPreferenceFragment.

**Comment by Mygod** [comment]
Btw I'm considering redesigning this app, but I don't have the time to do it. (oh and also I'm lazy)

**Comment by madeye** [comment]
Don't worry, We can mark it as long-term-plan. 😄

**Comment by Mygod** [comment]
![screenshot_1481899927](https://cloud.githubusercontent.com/assets/3511321/21266750/5d1447fe-c3e2-11e6-96af-5dc6a6715aa1.png)
Hmm how does this look? @madeye

**Comment by madeye** [comment]
Haha, drawer comes back? It looks awesome!

**Comment by Mygod** [comment]
We need drawer for additional features, including ACL (#1009). It also helps distinguish per-profile settings and global settings.

There are around 1.6k lines changed (`git diff --stat`) and there are still plenty of bugs to fix. *sigh*

**Comment by madeye** [comment]
You may push it to a dev branch. I can help to fix issues.

**Comment by Mygod** [comment]
Done. Pull drawer branch to play around with it TODAY!

And what bothers me most is where to put Network Traffic because clearly it's bothering to put it in every fragment.

Meanwhile I'll go ~~procrastinating for a while~~ design a banner for the drawer. :stuck_out_tongue:

**Comment by madeye** [comment]
Some feedbacks from my side:

1. Maybe we still put network traffic on the top? And let the switch button on the bottom.
2. Should we move profiles to the drawer, or just list them in the drawer? Currently, we have a very "clean" drawer. Not sure what we can put in it.

**Comment by madeye** [comment]
What about the following layout? It's from my favorite app Transdrone. I thought we could steal some ideas from it:

![image](https://cloud.githubusercontent.com/assets/627917/21285566/1e13b6c6-c477-11e6-8269-3912bd7babfb.png)

**Comment by Mygod** [comment]
1. Putting network traffic on the top would require putting it in every fragment layout (and probably move related code to `ToolbarFragment`). Also that kind of design doesn't make a lot of sense.
2. We shouldn't put profiles in the drawer. Most user switch profiles more often than configuring them. Putting profile list as the main layout makes more sense.  I'm planning to move reset in the drawer (and also add a banner and ACL).

Hmm that looks exactly like our current design. :laughing:

**Comment by Mygod** [comment]
1. Putting network traffic on the top would require putting it in every fragment layout (and probably move related code to `ToolbarFragment`). Also that kind of design doesn't make a lot of sense.
2. We shouldn't put profiles in the drawer. Most user switch profiles more often than configuring them. Putting profile list as the main layout makes more sense.  I'm planning to move reset in the drawer (and also add a banner and ACL).

Hmm that looks exactly like our current design. :laughing:

**Comment by pexcn** [comment]
Awesome! 🍦

**Comment by Mygod** [comment]
Marking redesigning mobile UI as complete as there are only bugfixes left to do. :raised_hands:

**Comment by madeye** [comment]
It looks really hard to find a good header background. @Mygod any suggestion?

**Comment by Mygod** [comment]
The current one looks really cool and great (much better than the one in [Root Explorer](https://play.google.com/store/apps/details?id=com.speedsoftware.rootexplorer)). I originally thought we would use plain color background but the current one looks better. Oh and where does that image come from and do we need license to use it?

**Comment by madeye** [comment]
Hmm, license is another problem. I got this image from google search: http://androidwalls.net/wp-content/uploads/2015/04/Mountains%20Night%20Silhouette%20Stars%20Sky%20Android%20Wallpaper.jpg

**Comment by madeye** [comment]
Another option is to search images in Flickr with CC 3.0+.

https://www.flickr.com/search/?license=2%2C3%2C4%2C5%2C6%2C9&text=mountains%20silhouette&advanced=1

**Comment by Mygod** [comment]
Great. I prefer to minimalist and tranquil ones. I'll leave this to you then.

**Comment by yuhuakukude** [comment]
can you teach me how to create a sbt android project?

**Comment by 967018** [comment]
不谋而合的issue。
重设计了Android影梭目前支持(也许)的所有平台的界面。附件为中英预览图。

欢迎联系合作。

![shadowsocks](https://user-images.githubusercontent.com/8299251/34076277-93ef27ea-e31b-11e7-8b00-aa0563fbed8c.png)
![default](https://user-images.githubusercontent.com/8299251/34076279-9e944dd8-e31b-11e7-828f-7ce17c4152ed.png)

**Comment by Mygod** [comment]
@967018 Looks good. Only if someone would implement all these stuff...

**Comment by 967018** [comment]
@Mygod 所以我的方案是被采纳了吗？如果是的话我下周可以出个正式的设计文档和过渡阶段的降级设计。

原来手表也可以用影梭啊……我会再适配这个设备的。会不会有能将手机/平板上的应用数据同步到手表的功能呢？

**Comment by Mygod** [comment]
Well you know, it would be great if someone would open a PR with all those changes instead of ME IMPLEMENTING ALL THESE STUFF. I honestly don't want to spend a lot of effort into designing this app (except in 2015 because it looked not material at all back then) and I believe @madeye doesn't either. In fact, I'd like this app to mostly depend on Android support libraries and third-party design libraries (for example see #1471) to minimize the effort for maintaining this project (given that they're good). I don't get paid at all working for this project just in case you're wondering.

For Android wear, see #664. This app will not come to Android wear as long as there's no VpnService support on Android wear. Also I would probably not want to implement something that I will not use (for example see #1457). So make sure to buy me a Chrome OS tablet and/or an Android tablet (preferably with a stylus), an Android watch and an Android TV (and whatever Android things is) so that I will work on those things.

**Comment by 967018** [comment]
哈哈，原来如此，做独立开发者不容易，辛苦了。
那我就把目标局限为手机/平板做一些细节修改吧（基于 Android support libraries或第三方库 / 在xml用几个变量就可以改善平板的布局了）。

**Comment by Mygod** [comment]
I just got a TV box. You can expect TV version coming this year.
