### ISSUE TITLE
设置为绕过中国地址后Google Apps工作不正常

### ISSUE THREAD

**Issue by ryans233** [shadowsocks/shadowsocks-android#764]
版本号：2.10.7
设置为"绕过中国大陆地址"后，Google App可以接收到卡片，但无法搜索（长时间等待后提示"Check your connection and try again"）。设为全局代理则可正常搜索。
最近还发现Google Play Service会产生长时间的NlpCollectorWakelock导致手机无法进入休眠，怀疑也是因为路由表模式失效导致某些Google服务地址无法连接，从而产生这种情况。

**Comment by madeye** [comment]
Try other service providers.
