### ISSUE TITLE
google.nl域名无法正确解析的问题

### ISSUE THREAD

**Issue by hanakisou4869** [shadowsocks/shadowsocks-android#770]
机型Nexus 5，软件版本2.10.7，其他服务均正常使用，但google搜索和youtube都无法载入，尝试使用google.com/ncr进行访问发现可以进入，但google.nl无法访问。全局模式亦无效，可能是路由出现错误。

在4.1系统上复现，两者均使用了NAT模式，VPN模式未有异常。

以上问题不存在于联通4G环境，仅wifi下出现，且与wifi的提供者无关，移动4G的热点和教育网均出现此现象。

**Comment by hanakisou4869** [comment]
提供一个临时的解决方案：（来自http://blog.csdn.net/leos_blog/article/details/43025265）

1   登录谷歌账号

2  默认搜索语言为英文

3  默认搜索引擎为： https://www.google.com/search?hl=en-US&source=hp&q=%s&aq=f&aqi=&aql=&oq=&gs_rfai=

4  使用一次 https://www.google.com/ncr  搜索

**Comment by madeye** [comment]
Try to uninstall and reinstall shadowsocks.

**Comment by hanakisou4869** [comment]
not working, wipeing cache.
