### ISSUE TITLE
2.10.7 googleplay edition can not scan qrcode on MIUI & SMARTISAN T1

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-android#771]
2.10.7 googleplay edition **can not scan qrcode** on MIUI & SMARTISAN T1
SMARTISAN OS:2.6.3
MIUI:5.8.6 (Android4.4.4.)

**Comment by madeye** [comment]
Duplicate with #748.

**Comment by madeye** [comment]
Double check your permission settings. Make sure you allowed camera permission of shadowsocks

**Comment by s7lx** [comment]
I'm very sure allowing camero permission of shadowsocks. It can scan qrcode but cannot load setting into shadowsocks
![image](https://cloud.githubusercontent.com/assets/3221213/16918402/bfb4d814-4d37-11e6-9d31-f43dc16a3882.png)

**Comment by s7lx** [comment]
I haven't see any **Permission Confirm Box** On MIUI.

**Comment by pjrobertson** [comment]
You can remove 'device bug' from #748 as well ;-)
And just if someone reports an issue on MIUI, it doesn't mean the issue *is* MIUI. Most likely it's not, since MIUI is a pretty standard Android skin
