### ISSUE TITLE
How to use GooglePlay in MIUI through shadowsocks for Android

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-android#772]
I've found how to use GooglePlay through shadowsocks for Android in MIUI OS

1. stop "迅雷加速" in `setting` of `Downloads`
2. stop "云加速" in `settting` ->`advanced` of `Browser` ; stop `极速模式` in `setting` of `Browser`

you can add them to FAQ

**Comment by Mygod** [comment]
Added. Thanks.

**Comment by JunhinAu** [comment]
1
