### ISSUE TITLE
connect kcptun not usable

### ISSUE THREAD

**Issue by shutup** [shadowsocks/shadowsocks-android#774]
i am trying to add an warper for kcptun, and first  i try to run the kcptun from android terminal,and then i use my laptop's shadowsocks to use the phone's kcptun server, and it works. then i am trying to use the shadowsocks on my phone to connect the kcptun server which is on my phone too ,but it did not work.is there something missing?
i grab some log from adb 
<pre>
07-19 16:55:13.117  2106  4455 W WhetstonePackageState: Permission denied by Whetstone, cannot start service from com.google.android.gms, third-party caller: com.github.shadowsocks, UserId: 0
07-19 16:55:13.507  2106  2318 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3f311c6 u0 com.github.shadowsocks/.Shadowsocks t1413} time:344730400
07-19 16:55:27.315 19459 30830 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -u, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf)
07-19 16:55:27.358 19459 30832 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/pdnsd, -c, /data/user/0/com.github.shadowsocks/pdnsd-vpn.conf)
07-19 16:55:27.393 19459 30844 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-tunnel, -V, -u, -t, 10, -b, 127.0.0.1, -l, 8163, -L, 8.8.8.8:53, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-tunnel-vpn.conf)
07-19 16:55:27.435  2106  4185 I Vpn     : Established by com.github.shadowsocks on tun0
07-19 16:55:27.436  5284  5284 D PowerKeeper.Vpn: add vpn: user = com.github.shadowsocks, uid = 10108, userId = 0
07-19 16:55:27.460 19459 30852 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 67, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:8153)
07-19 16:55:27.495  5284  5384 D PowerKeeperConfigureManager: 	pkg: com.github.shadowsocks	uid: 10108	bgDataEnable: false	bgDataDelayMinutes: 3	bgDataDelayCount: 20	bgDataMinDataKb: 100bgDataMaxInactiveCount: -1	bgLocationEnable: false	add2DeviceIdleWhiteList: false	bgLocationDelayMinutes: 1	bgKillDelayMinutes: -2	bgSDelayMinutes: 1	bgMusicCheck: false	scenario: 0
07-19 16:55:27.742  3855  3992 D IconCustomizer: Generate customized icon for com.github.shadowsocks.ShadowsocksApplication.png
07-19 16:55:27.809  3855  3992 I themeservice: add pending job /data/user/0/com.android.systemui/cache/com.github.shadowsocks.ShadowsocksApplication.png
07-19 16:55:27.853  3855 30860 I themeservice: saving icon for /data/user/0/com.android.systemui/cache/com.github.shadowsocks.ShadowsocksApplication.png
07-19 16:55:27.873 20733 20754 I themeservice: saving icon remotely(3855) for /data/user/0/com.android.systemui/cache/com.github.shadowsocks.ShadowsocksApplication.png ALLOW: true
07-19 16:55:27.902   336   733 E ShellService: move /data/user/0/com.android.systemui/cache/com.github.shadowsocks.ShadowsocksApplication.png /data/system/theme_magic/customized_icons/com.github.shadowsocks.ShadowsocksApplication.png failed: Permission denied
07-19 16:55:28.557  3855  3855 D PhoneStatusBar: addNotification pkg=com.github.shadowsocks;basepkg=com.github.shadowsocks;id=1
07-19 16:55:28.636  3855  3855 D PhoneStatusBar: updateNotification pkg=com.github.shadowsocks;id=1
07-19 16:56:27.637  5284  5383 D PowerCalculator: updatePowerForPackage: packageName: com.github.shadowsocks packageForeground: false
07-19 16:56:37.653  4594  4594 D WtProcessController: set foreground process size 2 pid:19459pacakgeName:com.github.shadowsocks
07-19 16:56:37.653  4594  4594 W WtProcessStrategy: {WhetstonePackageInfo#PacakgeName:com.github.shadowsocks uiMemoryThresold:0 nonUiMemoryThresold:0 Flag:5184,0x1440 [,TRIMHEAPS,SOFT_RESET,FLAG_DEAL_SCHEDULE] Type:0[] }not support ZRAM
07-19 16:59:34.676  3855  3855 D PhoneStatusBar: updateNotification pkg=com.github.shadowsocks;id=1
07-19 17:00:02.726  4594  4594 D WtProcessController: set foreground process size 2 pid:19459pacakgeName:com.github.shadowsocks
07-19 17:00:02.727  4594  4594 W WtProcessStrategy: {WhetstonePackageInfo#PacakgeName:com.github.shadowsocks uiMemoryThresold:0 nonUiMemoryThresold:0 Flag:5184,0x1440 [,TRIMHEAPS,SOFT_RESET,FLAG_DEAL_SCHEDULE] Type:0[] }not support ZRAM
07-19 17:00:27.026  3855  3855 D PhoneStatusBar: updateNotification pkg=com.github.shadowsocks;id=1
07-19 17:00:30.781  5284  5383 D PowerKeeperEventLogManager: notifyForegroundCompomentChanged ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}
07-19 17:00:30.787  5284  5383 D PowerCalculator: computePackageForeground: packageName = com.github.shadowsocks
07-19 17:00:30.788  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: true
07-19 17:00:30.788  5284  5383 D PowerCalculator: updatePowerForPackage: packageName: com.github.shadowsocks packageForeground: true
07-19 17:00:38.573  4594  4811 D WtProcessController: packageMoveToBackground packageName:com.github.shadowsocks
07-19 17:00:38.590  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: true packageForeground: false
07-19 17:00:38.590  5284  5383 D PowerCalculator: updatePowerForPackage: packageName: com.github.shadowsocks packageForeground: false
07-19 17:00:40.890  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:00:41.264  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:03:26.039  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:03:28.915  2106  4087 W AppOps  : Bad call: specified package com.github.shadowsocks under uid 10030 but it is really 10108
07-19 17:03:28.930  2106  4087 I Vpn     : Switched from com.github.shadowsocks to [Legacy VPN]
07-19 17:03:28.971  3855  3855 D PhoneStatusBar: removeNotification key=android.os.Binder@317c77 keyCode=3243127 old=StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null score=-20 key=0|com.github.shadowsocks|1|null|10108: Notification(pri=-2 contentView=com.github.shadowsocks/0x1090090 vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b actions=2 vis=PRIVATE))
07-19 17:03:29.003  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:03:29.084 19459 30830 I GuardedProcess: thread interrupt, destroy process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -u, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf)
07-19 17:03:29.085 19459 30844 I GuardedProcess: thread interrupt, destroy process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-tunnel, -V, -u, -t, 10, -b, 127.0.0.1, -l, 8163, -L, 8.8.8.8:53, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-tunnel-vpn.conf)
07-19 17:03:29.085 19459 30852 I GuardedProcess: thread interrupt, destroy process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 67, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:8153)
07-19 17:03:29.104 19459 30832 I GuardedProcess: thread interrupt, destroy process: WrappedArray(/data/user/0/com.github.shadowsocks/pdnsd, -c, /data/user/0/com.github.shadowsocks/pdnsd-vpn.conf)
07-19 17:03:29.248  5284  5384 D PowerKeeperConfigureManager: 	pkg: com.github.shadowsocks	uid: 10108	bgDataEnable: false	bgDataDelayMinutes: 3	bgDataDelayCount: 20	bgDataMinDataKb: 100	bgDataMaxInactiveCount: -1	bgLocationEnable: false	add2DeviceIdleWhiteList: false	bgLocationDelayMinutes: 1	bgKillDelayMinutes: -2	bgSDelayMinutes: 1	bgMusicCheck: false	scenario: 2
07-19 17:05:41.408  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:21:52.363  5284  5383 D PowerCalculator: computePackageForegroundLocked, packageName: com.github.shadowsocks oldPackageForeground: false packageForeground: false
07-19 17:26:15.561  5284  5382 D PowerCalculator: key = com.github.shadowsocks value = 56778 time = 638919
</pre>
and here are some settings
<pre>
root@virgo:/data/data # cat /data/user/0/com.github.shadowsocks/ss-local-vpn.conf
at /data/user/0/com.github.shadowsocks/ss-local-vpn.conf                      <
{"server": "192.168.0.199", "server_port": 1755, "local_port": 1080, "password": "MjdhNTVkNj", "method":"rc4-md5", "timeout": 600}
root@virgo:/data/data # cat /data/user/0/com.github.shadowsocks/pdnsd-vpn.conf
at /data/user/0/com.github.shadowsocks/pdnsd-vpn.conf                         <

global {
 perm_cache = 2048;
 cache_dir = "/data/user/0/com.github.shadowsocks";
 server_ip = 0.0.0.0;
 server_port = 8153;
 query_method = tcp_only;
 run_ipv4 = on;
 min_ttl = 15m;
 max_ttl = 1w;
 timeout = 10;
 daemon = off;
}

server {
 label = "local";
 ip = 127.0.0.1;
 port = 8163;
 reject = ::/0;
 reject_policy = negate;
 reject_recursively = on;
 timeout = 5;
}

rr {
 name=localhost;
 reverse=on;
 a=127.0.0.1;
 owner=localhost;
 soa=localhost,root.localhost,42,86400,900,86400,86400;
}

root@virgo:/data/data # cat /data/user/0/com.github.shadowsocks/ss-tunnel-vpn.conf
at /data/user/0/com.github.shadowsocks/ss-tunnel-vpn.conf                     <
{"server": "192.168.0.199", "server_port": 1755, "local_port": 8163, "password": "MjdhNTVkNj", "method":"rc4-md5", "timeout": 10}
root@virgo:/data/data #
</pre>

**Comment by madeye** [comment]
It won't work if you're using VPN mode with kcptun.

You may try NAT mode instead. Remember to run kcptun under shadowsocks' user id.
