### ISSUE TITLE
安卓客户端的dns查询的一个问题，导致路由器ipset失效，希望有解决方案。

### ISSUE THREAD

**Issue by yebr** [shadowsocks/shadowsocks-android#775]
ss客户端dns访问一个目标网站时，安卓版会解析成IP去连接，电脑版是以域名去连接。
例如，当我使用电脑版的ss客户端，我要访问www.cn.wsj.com，在SS服务器的日志上会显示：connect to: www.cn.wsj.com:80。
当我使用的是安卓版的ss客户端，在SS服务器的日志上会显示：connect to:111.108.54.9:80，就是相当于安卓客户端已经对www.cn.wsj.com先进行解析，再把连接请求发到ss服务器。
因为SS服务器端所在的环境并不是一个无墙环境，而是通过vpn方式连到被屏蔽的网站，被屏蔽的网站的ip是用dnsmasq根据访问域名时放进ipset的，在ipset列表中的ip通过vpn方式访问外网。
如果是像电脑那种基于域名的话，路由器就能解析该域名放到ipset列表中，但用安卓客户端的话，因为本来已经是ip，无法放进ipset的列表中，这导致了该ip无法通过vpn访问外网。
希望在日后的安卓新版中，能定义设置为不先解析域名为ip，而是直接把域名扔到ss服务器端进行解析处理，谢谢！

**Comment by madeye** [comment]
Shadowsocks-android works as a transparent proxy (or called "user-mode TCP/UDP NAT"). So you won't have remote dns resolve.

**Comment by yebr** [comment]
好的，我能看懂英文，但我英文语法不好，请允许我用中文输入。
请问有方法输出每个连接的ip吗？这样我就能把ip添加到ipset中，或者有没其它识别方法可以让iptables识别到安卓客户端的流量，让这些流量走vpn？

thanks for responding,my english is not good,I typed in chinese,and with simple english :).
is there any way to export the "connect to “ ip addresses to ipset?
or is there any way to match the shadowsocks flows from iptables? if matched i can set the shadowsocks flows pass throght the  vpn network.

**Comment by andronoob** [comment]
@yebr 你可以在ss服务器上使用类似iptables -m owner的办法匹配ss服务器产生的流量。

**Comment by yebr** [comment]
iptables -t filter -m owner --uid-owner ssu -I OUTPUT -p tcp --dport 80 -j  MARK --set-mark 3
 iptables -t filter -m owner --uid-owner ssu -I OUTPUT -p tcp --dport 443 -j  MARK --set-mark 3

iptables -t filter -L -nv | grep 1000
 1628  167K MARK       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1000 tcp dpt:80 MARK set 0x3

是的，我正在使用这种方法，电脑端好像是成功了，全部显ip网站都显示为了vpn的网站，
但手机端还是不行，不是什么原因，好郁闷。

**Comment by yebr** [comment]
@andronoob 依然是不行，我的思路是用-a ssu以ssu用户运行ssr-server，然后通过iptables匹配所有用户ssu访问80和443端口的流量标上mark3，然后所有带mark3标记的从vpn出网。
在iptables上看到是成功标记上了mark3，但是流量从没vpn出去。

**Comment by yebr** [comment]
主要的命令如下：
iptables -t filter -m owner --uid-owner ssu -I OUTPUT -p tcp --dport 80 -j MARK --set-mark 3
iptables -t filter -m owner --uid-owner ssu -I OUTPUT -p tcp --dport 443 -j MARK --set-mark 3
iptables -t filter -m owner --uid-owner ssu -I OUTPUT -p udp -j MARK --set-mark 3
iptables -t nat -A POSTROUTING -o pptp-vpn -j MASQUERADE
ip route add default dev pptp-vpn table 3
ip rule add fwmark 3 table 3 pref 253
/usr/bin/ssr-server -c /etc/shadowsocksr-server.json -u -a ssu -v >> /tmp/shadowsocks.log &

**Comment by yebr** [comment]
已解决，当弄清楚了android ss客户端的通信方式后，其实解决方法好简单，客户端打开udp转发，然后路由器把8.8.8.8 DNAT到本地DNS地址，这样就能触发本地DNS设置的ipset规则。

**Comment by junweigu** [comment]
@yebr 你服务端用的什么？怎么让安卓端转发udp到服务端的？使用iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to-destination 192.168.1.1吗？我在服务端（ss-rm-mu）将 192.168.1.1改成服务端的dns内部ip久直接无法上网了，你怎么解决的呢？

**Comment by yebr** [comment]
@junweigu 服务器端是shadowsocksr-server，改ip与服务器端的ss软件无关，是在路由器里增加一个环回ip，是增加，不是修改。

**Comment by junweigu** [comment]
感谢回复，我不是路由器版本，我是服务器后端，可能不一样

2016年8月29日 09:49，"yebr" <notifications@github.com>写道：

**Comment by yebr** [comment]
服务器版打开udp转发，只需要加一个参数-u，具体参数如下：
root@OpenWrt:~# /usr/bin/ssr-redir --help

shadowsocks-libev 2.4.5

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-redir

       -s <server_host>           Host name or ip address of your remote server.
       -p <server_port>           Port number of your remote server.
       -l <local_port>            Port number of your local server.
       -k <password>              Password of your remote server.
       -m <encrypt_method>        Encrypt method: table, rc4, rc4-md5,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  bf-cfb, camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, cast5-cfb, des-cfb, idea-cfb,
                                  rc2-cfb, seed-cfb, salsa20 and chacha20.

       [-a <user>]                Run as another user.
       [-f <pid_file>]            The file path to store pid.
       [-t <timeout>]             Socket timeout in seconds.
       [-c <config_file>]         The path to config file.
       [-n <number>]              Max number of open files.
       [-b <local_address>]       Local address to bind.

       [-u]                       Enable UDP relay,
                                  TPROXY is required in redir mode.
       [-U]                       Enable UDP relay and disable TCP relay.
       [-A]                       Enable onetime authentication.


       [-v]                       Verbose mode
