### ISSUE TITLE
Doesn't work shadowshoks in Turkmenistan

### ISSUE THREAD

**Issue by al305ev** [shadowsocks/shadowsocks-android#776]
Doesn't work in Turkmenistan, due to block of government Shadowshoks not working in our country, please fix it

**Comment by madeye** [comment]
Try to set up your own servers.

**Comment by al305ev** [comment]
Sorry but i do not understand about it.

Best regards,

Adyl ORAZOV

  22.07.2016, 8:49:58 пользователь Max Lv (notifications@github.com) написал:


  Try to set up your own servers.

**Comment by s7lx** [comment]
@al305ev shadowsocks is not a simple software to due the block of government.
It need a `ss-server` as a proxy.
Default `ss-server` is for chinese user, not for other country.

Sooooooooo, you should setup a `ss-server` in other server of 3rd country
