### ISSUE TITLE
android客户端解析服务器IP地址的问题，不知是否为bug？

### ISSUE THREAD

**Issue by yebr** [shadowsocks/shadowsocks-android#777]
我的服务器使用的是动态IP，因此需要用到DDNS动态域名解析服务。
例如我的域名是yebr.3322.org，公网IP为219.0.0.1，并且我在服务器的路由器自带的dns解析为192.168.168.168（通过dnsmasq的设置address=/yebr.3322.org/192.168.168.168，或通过hosts方式192.168.168.168 yebr.3322.org）。
在正常情况下，并通过手机IP工具软件已验证成功：使用手机的移动网络时，解析到yebr.3322.org的IP为219.0.0.1；手机使用路由器的WIFI时，解析到yebr.3322.org的IP为192.168.168.168
但使用shadowsocks android客户端时就有bug了，在使用手机的移动网络时，解析到yebr.3322.org的IP为219.0.0.1，但当手机使用路由器的WIFI时，解析到的IP依然是219.0.0.1（通过路由器tcpdump抓包确认），而不是192.168.168.168。
我使用几台手机测试情况都一样，即使清除后台服务和dns缓存，情况也一样，请问这个是否为bug？
如果不是，请是否有解决方法？谢谢！

**Comment by madeye** [comment]
It's expected.

Shadowsocks-android always resolves the server's domain through remote DNS server.

**Comment by yebr** [comment]
请问remote DNS server指的是一个由ss android客户端预先设定好的dns地址吗？
还是指使用的是server端dns解析服务？

**Comment by madeye** [comment]
OpenDNS and Google DNS.

**Comment by yebr** [comment]
Thank you very much，每次出现疑问找不出原因，都是你解决了，非常感谢！

**Comment by yebr** [comment]
知道原因后几分钟就解决了，路由器使用命令iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to 192.168.1.1，把dns解析转到本地解析就可以了。
