### ISSUE TITLE
可否公开下代码的设计文档，或者写一个类似这样的源码分析文章？以便更多的Android开发基础薄弱的developer们学习？ https://0x01.io/2016/02/28/shadowsocks-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB/

### ISSUE THREAD

**Issue by winer632** [shadowsocks/shadowsocks-android#781]
可否公开下代码的设计文档，或者写一个类似这样的源码分析文章？以便更多的Android开发基础薄弱的developer们学习？
https://0x01.io/2016/02/28/shadowsocks-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB/

**Comment by madeye** [comment]
Read the source code.

Some references:

http://ct2wj.com/2016/02/28/shadowsocks-android-source-code-analysis/
http://fqrouter.tumblr.com/post/51474945203/socks代理转vpn
