### ISSUE TITLE
Facebook Android App 不能连接

### ISSUE THREAD

**Issue by Easeman** [shadowsocks/shadowsocks-android#782]
系统环境 Nexus 6P Android 6.0.1
Shadowsocks Android 2.10.8
Facebook 87

Shadowsocks是VPN模式，其他所有网页和app都正常能用，唯独Facebook app不能通过shadowsocks连接。使用系统的VPN连接VPN服务器，Facebook app则可以正常使用。Facebook网页一直都正常访问。

**Comment by Easeman** [comment]
经过测试，如果关闭Shadowsocks客户端中的代理IPv6选项，Facebook app则可以正常使用，请问这是为什么呢？

**Comment by madeye** [comment]
Two possible reasons:

1. Your server doesn't support IPv6.
2. Your server's IPv6 address is blocked by Facebook.

If you're using Digital Ocean or Linode, you should be facing the second issue.
