### ISSUE TITLE
最新版的git拉下来的，编译失败

### ISSUE THREAD

**Issue by PsjJourney** [shadowsocks/shadowsocks-android#783]
aa@aa-virtual-machine:~/github/shadowsocks-android-2.10.8$ ./build.sh 
~/github/shadowsocks-android-2.10.8/src/main ~/github/shadowsocks-android-2.10.8
jni/Android.mk:554: jni/openssl/crypto/Android.mk: 没有那个文件或目录
jni/Android.mk:554: jni/openssl/ssl/Android.mk: 没有那个文件或目录

**Comment by PsjJourney** [comment]
发现git拉下来的openssl目录里面是空的

**Comment by ageback** [comment]
git submodule update --init --recursive

**Comment by PsjJourney** [comment]
好的，我试试，谢谢
