### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by daliands** [shadowsocks/shadowsocks-android#784]
some of erros are as below:
[warn]   It is recommended that the compiler be upgraded.
[warn] /home/ubuntu/work/shadowsocks-android/target/android/generated/source/com/github/shadowsocks/aidl/IShadowsocksService.java:  major version 52 is newer than 51, the highest major version supported by this compiler.
[warn]   It is recommended that the compiler be upgraded.
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] Error reading API from class file : java.lang.UnsupportedClassVersionError: android/os/IInterface : Unsupported major.minor version 52.0
[warn] there were three deprecation warnings; re-run with -deprecation for details
[warn] there were two feature warnings; re-run with -feature for details
[warn] two warnings found
[error] [NewApi] target/android/intermediates/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 16): android.net.VpnService.Builder#addAllowedApplication
[error] [NewApi] target/android/intermediates/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 16): android.net.VpnService.Builder#addDisallowedApplication
[error] [NewApi] src/main/res/drawable/ic_arrow_drop_down.xml:1:<vector> requires API level 21 (current min is 16) or building with Android Gradle plugin 1.4 or higher

I built with android-ndk-12b and android-sdk-25.1.7

**Comment by madeye** [comment]
Update your JDK to 1.8.
