### ISSUE TITLE
build  [error] jni/Android.mk:554

### ISSUE THREAD

**Issue by ssxz** [shadowsocks/shadowsocks-android#785]
According to the instructions, the installed files have been installed, 
When executing ‘sbt native-build clean android:package-release’ in the terminal
......
[info] Done updating.
[info] Set current project to shadowsocks (in build file:/root/Download/shadowsocks-android-master/)
[info] ~/Download/shadowsocks-android-master/src/main  ~/Download/shadowsocks-android-master
**[error]**  jni /Android.mk:554:   jni/openssl/crypto/Android.mk: No such file or directory
**[error]**  jni /Android.mk:554:   jni/openssl/ssl/Android.mk: No such file or directory
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium
......
Ask for help, thanks.

**Comment by madeye** [comment]
git submodule update --init
