### ISSUE TITLE
通知栏里不显示线路切换和停止按钮。

### ISSUE THREAD

**Issue by renjie45** [shadowsocks/shadowsocks-android#786]
用的miui最新开发版，低包是安卓6.0.1。百分之99.9都不显示线路和停止按钮如图1
![1](https://cloud.githubusercontent.com/assets/9068568/17283751/a1aae08e-57e6-11e6-9e0d-6bb985c80226.png)
，只有很小的机率一次会显示出来（手机上没做其他设置，就是随机出现能显示），如图2.
![2](https://cloud.githubusercontent.com/assets/9068568/17283753/a4e82482-57e6-11e6-9a7d-d4fe9307fb32.png)

**Comment by eastmalon** [comment]
轻按通知并下滑一小段距离，将会显示额外选项

**Comment by Mygod** [comment]
Update to Android 7.0 or learn how to expand notifications on Android 6.0.

**Comment by VampireSH** [comment]
miui的通知栏是有问题的，很多这些设置都不能打开

Mygod <notifications@github.com>于2016年8月1日周一 13:04写道：

**Comment by kfbb** [comment]
在miui下请双指下滑这个通知，能显示出这些项目。
