### ISSUE TITLE
编译报错 Premature end of file

### ISSUE THREAD

**Issue by haobug** [shadowsocks/shadowsocks-android#789]
```
$  sbt -verbose -debug clean android:package-release
[error] (android:processManifest) com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
```

 Google Play services ， Google Repository 我已经更新到当前最新，sbt 工具插件也安装正常，只剩下这一个错误，完全找不到原因，
- [AndroidManifest.xml](https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/AndroidManifest.xml)文件加不加 xml 声明都会报一样的错误。
- 这两步都正常通过
    - ``git submodule update --init``
    - ``./build.sh``
    - 报错--> `` sbt -verbose -debug clean android:package-release ``

完整的 log:
http://dpaste.com/1SNDSHP

**Comment by madeye** [comment]
Double check your environment setup:

https://travis-ci.org/shadowsocks/shadowsocks-android
https://github.com/shadowsocks/shadowsocks-android/blob/master/travis-ci/setup.sh
