### ISSUE TITLE
kcptun的体积过大

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#790]
最新版加了kcptun，体积大了不少，请问有计划用C重写或者重新实现一个“kcptun”吗？

**Comment by madeye** [comment]
Nope.

**Comment by Mygod** [comment]
I'm also wondering whether it's a good idea.

**Comment by VampireSH** [comment]
可以这样吗？kcp作为一个模块，默认程序不包含。这样可以减少体积

Mygod <notifications@github.com>于2016年8月6日周六 21:16写道：

**Comment by madeye** [comment]
Do you really think a 6.7 MB apk is too large?

I think It's smaller than most of the apps on the Google Play Top 100 list.

**Comment by Mygod** [comment]
Considering we're not supporting Android 2.x, storage isn't a problem.

I'm more concerned with its impact on battery life.

**Comment by VampireSH** [comment]
是的的确不大只是对比原来的大了而已😝。我一直好奇耗电那里真的就没有办法区分是谁耗的电吗？？

Mygod <notifications@github.com>于2016年8月6日周六 23:25写道：

**Comment by madeye** [comment]
1. I'm doing battery life test in my daily usage. So far so good, no additional battery usage can be observed. It makes sense as very few traffic would go through kcptun.
2. IMO, kcptun should run as a plugin server of shadowsocks. In your normal usage, just use shadowsocks over TCP. When you are with a poor connection, enable KCP to improve the performance.
