### ISSUE TITLE
影梭3.0.2的 KCP还是无法工作

### ISSUE THREAD

**Issue by wang20150419** [shadowsocks/shadowsocks-android#796]
影梭3.0.2的 KCP还是无法工作。

配置情况：

    客户端：
    ubuntu 16.04.1 LTS 64bit
    ss-server -c /etc/shadowsocks-7777.json -a root -u
    server_linux_amd64 -l :37777 -t 127.0.0.1:7777 --crypt xor --key xxxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2 
     (ss-server 版本：2.4.8 )

    手机：
     基于android 6.0的 emui 4.0 (华为mate8),  影梭 3.0.2
     功能设置：
         路由：绕过局域网及中国大陆地址
         分应用代理：enable (包括谷歌服务，浏览器等)
        UDP转发：enable
        KCP: enable
        KCP 端口： 37777
        KCP参数：--crypt xor --key xxxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2 

现象：

     手机关闭KCP，一切正常，开通KCP，则浏览器无法上任何网络，只有发送包，无接收包。
     电脑上用同样配置的shadowsocks和kcptun，都能正常使用。

**Comment by madeye** [comment]
1. Try smaller MTU, e.g. 1024.
2. Post the output of `adb logcat -s GuardedProcess`

**Comment by madeye** [comment]
Also, try to uninstall and reinstall the latest shadowsocks.

**Comment by wang20150419** [comment]
卸载后，重新安装，现在KCP可以正常使用了，看youtube比以前强太多了，720p不卡顿。非常感谢！

**Comment by sosmygirl** [comment]
同样的配置，昨天可以用，早上起床就不行了，重装也不行，不知道哪出问题了，把配置改成实例一样的也不行
