### ISSUE TITLE
Maybe we can have a donation version?

### ISSUE THREAD

**Issue by u3shadow** [shadowsocks/shadowsocks-android#800]
Maybe we can have a donation version without ad?

I think it's better to customer and your dev, you can feel we respect for your work and we can have a no ad version to use.

**Comment by brownursidaeR** [comment]
there is no ad

**Comment by u3shadow** [comment]
but the version i download from google play can show ad at the main page sometime

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#ui-tips

**Comment by brownursidaeR** [comment]
Remove the default profile to remove ads
