### ISSUE TITLE
Frequent connection loss with KCP enabled

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#801]
After keeping it running for a while, it always loses connection until the background service is restarted.

Reproduced on: bacon, Android 6.0.1, 20160518-VM13-bacon.
Also seen reports from: bullhead, Android 6.0.*.

**Comment by kmahyyg** [comment]
something wrong with kcptun is discovered in my server.I also always loss connection on my bandwagonhost vps with debian8_x64.Then I found the problem,Greatwall Boardband network multiQoS made kcptun useless.

**Comment by kmahyyg** [comment]
BTW keep updating with official kcptun client is needed!

**Comment by madeye** [comment]
Looks like a QoS issue. Try small `mtu`, `sndwnd`, and `rcvwnd`. Also remember to add `dscp` option and change your kcptun port to `21` or `4000`.

Here is an example:

`--crypt none --mode normal --mtu 1200 --nocomp --dscp 46 --datashard 10 --parityshard 0 --rcvwnd 64 --sndwnd 32`

**Comment by Mygod** [comment]
That doesn't seem to explain why the connection initially works fine. :confused:

**Comment by madeye** [comment]
Some broken NAT devices would also cause this kind of issue. Currently, we have a `10s` NAT `keepalive` to avoid being flushed from NAT cache. I think it's small enough for most of NAT devices.

https://github.com/xtaci/kcptun/blob/master/client/main.go#L195

However, when the Android device goes to sleep with a Wi-Fi. I think the `keepalive` trick here may not work.

**Comment by Mygod** [comment]
So report this to kcp-go perhaps? @xtaci

**Comment by madeye** [comment]
Yes, it should be an issue of upstream.

I'm thinking of re-dial UDP occasionally, e.g. re-dial UDP every 5 minutes, force to re-establish the connection.

**Comment by xtaci** [comment]
kcptun works 7x24 on my router, but NAT keepalive is a PROBLEM for mobile devices when it's switched to background.

**Comment by kmahyyg** [comment]
@madeye why must dscp set to 46? thanks a lot.
@xtaci @Mygod If you're in android 6.0+ , please follow these steps , that worked on my redmi 2 ( Resurrection Remix OS based on CM13).

Sorry, i have to use chinese now.
系统设置 -  应用管理 - 右上角三点。。。 - 电池使用（还是电池优化） -  找到shadowsocks app - 把优化电池使用改为不优化即可

also , greenify or other process manager may cause this problem.

**Comment by Mygod** [comment]
@kmahyyg That didn't seem to do the trick for me.

**Comment by KarlM256** [comment]
Hi...

I turned off battery optimization for shadowsocks Android and I am now running with the following kcptun options
--crypt none --mtu 1024 --sndwnd 64 --rcvwnd 64 --nocomp
and things seem more stable. I'm not sure what was most important, but I suspect turning off the battery optimization.

@madeye Instead of restarting KCP brute force, can you detect when traffic is not flowing? You mentioned keepalives...Do they pass in both directions? If you ran them through KCP, and you ACKed them in some way like ping pong back and forth from client to server and back to client with an incrementing counter, you would have a reliable way to detect a hang and then reset the KCP connection.

The client side seems like where to do that because you have control and easier bookkeeping on the client side because all of the traffic is for one "connection".

...Karl

**Comment by Mygod** [comment]
> I'm not sure what was most important, but I suspect turning off the battery optimization.

Turning off battery optimization only doesn't work for me. I guess there's only one way to find out.

**Comment by kmahyyg** [comment]
@xtaci I think that kcptun should add a feature that if the connection is lost too much or resend too much,it can find a better argument for itself, and also notice the user and the server administrator.

**Comment by xtaci** [comment]
@kmahyyg I've thought about that before

By periodically exchanging SNMP information to each other, and find out the best argument (some one call it : learning based algorithm). But the hardest part is : you never know which arguments are best, the internet, as a matter of fact, is totally unpredictable; learning is based on the assumption that -- it's predictable and the curve is derivable.

Based on the fact that the internet is unpredictable, it's easily to conclude that :
> For a given parameters set P1,  SNMP information set - S1 , there does not exists a function F, which could transform P1 & S1  into P2 & S2(the better one), i.e:

> non-existent  ：      P2, S2 := F(P1, S1) 

Even if the internet is predictable for a some limited space & time.  function F can easily be taken advantage of by ISP, they know you algorithm, they know how to defeat your algorithm by providing the worst set of S1.

**Comment by madeye** [comment]
@xtaci Now, it becomes an optimization problem. 

The heuristic approach you mentioned seems promising. It will help to detect the local best parameters, within a time interval, says 5 minutes. 

Also, I don't think we need to figure out the global best parameters,. Actually, it's impossible for a unstable system like the internet or evil ISPs.

I think we may use a greedy approach to tune the parameters on-line. Then, when the traffic efficiency becomes low (or after fixed time interval) , we reset all the parameters and perform the tuning again.

Other re-tuning points like network switching can be performed explicitly through our client implementation, e.g. shadowsocks.

**Comment by xtaci** [comment]
@madeye How about ISP intentionally lowers your traffic efficiency and trigger your tuning algorithm, at meanwhile providing you with the worst QoS.

**Comment by madeye** [comment]
@xtaci Right, it's a problem that may be unable to be solved by an algorithm. 😭

Still, we want to try something to improve kcptun, especially the efficiency.

Any ideas for anti-QoS purpose? For example, something like KCP over fake TCP?

**Comment by xtaci** [comment]
A TCP-RST packet kills the NAT mapping on the router. TCP is friendly to QoS, but TCP-RST is lethal to the connection.

**Comment by SilverBut** [comment]
My Sony Z2 is not using KCP but the connection is also not stable as the previous version. Might not a problem with KCP?

**Comment by madeye** [comment]
Closing as an upstream issue.
