### ISSUE TITLE
请问有ios代码吗？

### ISSUE THREAD

**Issue by louisyoung** [shadowsocks/shadowsocks-android#802]
谢谢

**Comment by Mygod** [comment]
Unfortunately iOS is closed-source. Ask Apple for their source code.

**Comment by s7lx** [comment]
@louisyoung you means shadowsocks for iOS ? https://github.com/shadowsocks/Potatso

**Comment by louisyoung** [comment]
thanks😀

2016-08-12 14:39 GMT+08:00 Mygod <notifications@github.com>:
