### ISSUE TITLE
Kcp Seems not working on 4.x

### ISSUE THREAD

**Issue by powerofchaos** [shadowsocks/shadowsocks-android#804]
客户端版本3.0.3 Kcp参数: --crypt xor --mtu 1300 --sndwnd 256 --rcvwnd 1024 --mode fast2 --nocomp
在android 4.1.2 和android 4.4.4上启用kcp无法上网，关闭kcp正常，相同网络环境相同配置参数在android 5.1.1和win7x32上可以正常使用kcp

**Comment by madeye** [comment]
I don't have any 4.x device anymore. I believe the best way to solve your issue is upgrading your device to Android 5.x or later.

**Comment by Mygod** [comment]
@madeye How about using emulator? Emulators in Android SDK runs pretty smooth now for me but it uses a lot of RAM.

I have an Android 4.1 device, however its screen is barely usable because I accidentally dropped it. So I prefer not to use that one.

Also btw when do you plan to end support for Android Jelly Bean 4.1 (API level 16)? Currently its market share is kind of small now.

**Comment by madeye** [comment]
I tried several emulators. But no one of them is able to establish a VPN connection. I suspect it's an issue of Google's emulator.

I also tried some android-x86 based virtual machines, like genymotion, still no luck.

If you find any emulator works for shadowsocks, please let me know.

**Comment by Mygod** [comment]
Google's emulator is able to establish a VPN connection. See #646 where I established a VPN connection on Android TV emulator.

**Comment by madeye** [comment]
Yes, I'm also able to get VPNService working on Android 5.0+ emulator. But I don't konw why Android 4.x just doesn't work.

**Comment by madeye** [comment]
Here is what I got on Android 4.4.2 emulator x86:

```
E/Shadowsocks( 2238): Error to start VPN service: command '34 interface fwmark rule add tun0' failed with '400 34 Failed to add fwmark rule (File exists)'
E/Shadowsocks( 2238): Error to start VPN service: Failed to connect the remote server
```

**Comment by madeye** [comment]
Try this apk: https://drive.google.com/file/d/0B3YSrCJtFxYicXptYm9uS3RsR2c/view
