### ISSUE TITLE
Proxy-only mode should be added to work with adblockers and Orbot.

### ISSUE THREAD

**Issue by edsgerlin** [shadowsocks/shadowsocks-android#805]
Adblockers like Adguard[2] or AdClear Plus for Android use VPN API to filter ads, which is incompatible with current Shadowsocks-Android. Luckily they have a option to set an upstream SOCKS proxy, we just need an option to run Shadowsocks-Android as a SOCKS proxy listening on localhost to make them compatible, and Adblockers will do the tunneling.

Also Orbot[1](Tor for Android) supports upstream SOCKS proxy, proxy chaining with Shadowsocks can improve performance of Tor greatly as I tested with Shadowsocks client running on my laptop.

Reference:
[1] https://play.google.com/store/apps/details?id=org.torproject.android
[2] https://adguard.com/

**Comment by madeye** [comment]
No plan for that.

**Comment by madeye** [comment]
Actually, you can emulate this  by enabling NAT mode without ROOT permission or just not proxing any app in per-app mode.

**Comment by edsgerlin** [comment]
However, VPN mode is exclusive even with "not proxing any app in per-app mode" set, and Shadowsocks-Android refuse to start NAT mode without ROOT permission.

**Comment by madeye** [comment]
Then try NAT mode with ROOT permission and no app selected in per-app settings.
