### ISSUE TITLE
Could you please tell me the local port number of kcptun?

### ISSUE THREAD

**Issue by hbxntsxw** [shadowsocks/shadowsocks-android#807]
Hi, the kcptun tunnel is very cool. Could you tell me the local port number of kcptun? I want to use the kcptun tunnel on another device. Thanks!

**Comment by madeye** [comment]
Nope, you can't. The embedded kcptun only listens on local host.

**Comment by hbxntsxw** [comment]
So, that also means I can't replace the kcptun file by an updated one?
