### ISSUE TITLE
Hardcoded DNS resolver in client?

### ISSUE THREAD

**Issue by shounak-de** [shadowsocks/shadowsocks-android#812]
The android client [always uses Google DNS servers](https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L311), and not the DNS resolvers configured on the ss-server. Can the DNS resolvers be an user input on the client? 

Also, is this something I can force redirect on my machine running ss-server with iptables? I am not very conversant with iptables, can you help me out (if this can be done on the server)

**Comment by madeye** [comment]
iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to-destination 192.168.1.1

**Comment by shounak-de** [comment]
:+1:

**Comment by junweigu** [comment]
@madeye   ，这个192.168.1.1 可以改成服务端的ss的dns内部ip吗？从而实现转发安卓端的dns请求到服务端的dns？
