### ISSUE TITLE
Implement per-app proxy for VPN mode on Android 4.4

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#813]
[Netfits](http://netfits.net/) supports per-app proxy on Android 4.x. After decompiling this app for a while, I found out it sends `Acc {uid} {allowed}` to its native code's stdin to do so and I'm lazy to decompile its native code. :stuck_out_tongue: 

So it's definitely possible to do so. [You can retrieve the uid of the socket](http://stackoverflow.com/a/18946355/2245107) and bypass the socket with `VpnService.protect` or something like that. Do you plan to support this?

**Comment by madeye** [comment]
Yes, it's possible. But I'm too lazy to add this feature.

http://stackoverflow.com/questions/9898961/is-there-a-way-to-get-the-uid-of-the-other-end-of-a-unix-socket-connection

**Comment by Mygod** [comment]
Yeah me too. Let's wait for someone to make a PR. :joy:

**Comment by madeye** [comment]
OK, close for now.

**Comment by Mygod** [comment]
Let's add a "contributions welcome" label as well.

**Comment by xiaoxiaogogo** [comment]
Ask a question. How to get the socket from VPNService?

**Comment by xiaoxiaogogo** [comment]
@Mygod

**Comment by xiaoxiaogogo** [comment]
How to get the socket which need to bypass from VPNService? @Mygod @madeye
