### ISSUE TITLE
Faster recovery from kcptun errors

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#814]
Hi...

I have noticed that sometimes the kcptun server hangs and I can never reconnect.

More commonly, breaking and restarting the shadowsocks/kcptun connection usually fixes it.

I noticed that shadowsocks-android now detects a failed connection and recovers, but it can take a long time. I assume that the test connection option results in a message from the client to the server and back to the client. Could this test be automatically sent when the input from the server is idle for a short time and the client is sending to the server, or has data queued up, and perform a fast restart of the connection if it is stalled? If we are not sending packets to the server, then a longer idle time could be used.

When shadowsocks-android now recovers, it takes a long time. I can test 2 or 3 times and have them time-out and fail before it restarts the connection.

Also, would you consider bypassing kcptun if it fails and can't be restarted?

Thanks,

...Karl

**Comment by madeye** [comment]
It's an upstream "bug". For loss of connection, the timeout of upstream is 30s.

Shadowsocks will only restart kcptun when the network switching.
