### ISSUE TITLE
Possible cause for kcptun issues

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#815]
Hi...

I did some experiments today, running the kcptun server on win10 pro 64 from a console so I could watch the log results on the screen. At the same time I ran shadowsocks on my Nexus 6 and experimented until I had problems.

So I observed that the memory used by the kcptun server that was normally around 5 to 10 MB would go up to 27 or 28 MB when there was a problem as seen on my phone. If I stopped using my Nexus 6 (turned off shadowsocks android), the memory would come back down after a while, so it wasn't leaking but backing up.

Every time that the performance of shadowsocks got bad on my phone, the kcptun server was using lots of memory.

When I was looking at the kcptun repository, I saw that it used yamux for multiplexing streams. But in this application, there should only be one stream. kcptun just needs to provide a point to point link between the shadowsocks client and the shadowsocks server. I don't know how you handle UDP packets when using kcptun. If forwarding UDP packets, perhaps UDP should bypass kcptun and go directly to the shadowsocks server. Without the UDP forwarding, then perhaps they should go through kcptun.

So I don't think that kcptun should be doing all of this multiplexing of streams. I don't think that it needs to know about the multiplexing that shadowsocks is doing. kcptun seems to keep some streams open for a long time before closing them and that plugs things up.

One time when the memory usage was high on the kcptun server, the shadowsocks server crashed.

The command line settings for kcptun in the shadowsocks-android settings didn't seem to matter much. Smaller send and receive windows helped a little. I always used a mtu of 1024, crypt none, mode normal, and nocomp. I experimented with datashard and parityshard with no effect that I could see, I currently have them set at 8 and 4 respectively.

Thanks,

...Karl

**Comment by madeye** [comment]
It's an issue that has been well discussed before. Without efficient keep-alive approach on mobile devices, the UDP NAT rules would be flushed by routers occasionally.

**Comment by KarlM256** [comment]
But kcptun could be used as a point to point link. That still gives you keep alives. We just avoid making kcptun track all of the streams that it does not need to know about.

**Comment by KarlM256** [comment]
To clarify, when forwarding UDP packets is not enabled, everything from shadowsocks android can go through one tcptun stream, and it maintains keepalives for itself. Having shadowsocks android and kcptun both keep track of the streams duplicates effort.

**Comment by madeye** [comment]
UDP forwarding goes to shadowsocks server. Nothing related to kcptun.

**Comment by KarlM256** [comment]
ok, so only TCP connections go through kcptun?

**Comment by madeye** [comment]
Also, please make sure your shadowsocks server and kcptun server are not listening on the same port.

**Comment by madeye** [comment]
Right.

**Comment by KarlM256** [comment]
Ok, so for the TCP connections, shadowsocks can handle multiplexing them through a single stream to/from the shadowsocks (python in my case) server.

**Comment by KarlM256** [comment]
My point is that because shadowsocks can handle the multiplexing, kcptun does not need to. kcptun only needs to see a single TCP stream. This would eliminate duplicated effort.

**Comment by madeye** [comment]
Shadowsocks never handles multiplexing. Make sure you understand the protocol of shadowsocks correctly.

**Comment by KarlM256** [comment]
It does handle multiplexing because it is carrying the SOCKS protocol. So multiple connections (streams to kcptun) go through a single path from the client to the server and then branch out again to the Internet at large. That is effectively multiplexing. Do you use a distinct port number for each connection to make them unique?

**Comment by madeye** [comment]
Again, please read the documents of shadowsocks.

**Comment by KarlM256** [comment]
ok. I am only trying to help. I will go study the shadowsocks documents more.

What I thought I observed was a problem where kcptun is ending up with many streams open at the same time and that seems to be the source of the hanging problem.

**Comment by KarlM256** [comment]
Do you create a new tcp connection between the ss client and server for each socks connection to the ss client? The documentation does not show how the packets are placed into tcp frames for transport from the client to the server.
