### ISSUE TITLE
kcp is not working in xiaomi 4 android 6.0

### ISSUE THREAD

**Issue by alexliyu** [shadowsocks/shadowsocks-android#816]
08-18 16:47:19.114 10997  2056 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 61, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
08-18 16:47:20.145 10997  2168 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/kcptun, -r, 65.223.15.169:21, -l, 127.0.0.1:1170, --path, /data/user/0/com.github.shadowsocks/protect_path, --crypt, none, --mtu, , 1200, --nocomp, , --mode, normal, --dscp, 46)
08-18 16:47:20.165 10997  2176 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf, -A)
08-18 16:47:20.187 10997  2178 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
08-18 16:47:20.227 10997  2168 W GuardedProcess: process exit too fast, stop guard: WrappedArray(/data/user/0/com.github.shadowsocks/kcptun, -r, 65.223.15.169:21, -l, 127.0.0.1:1170, --path, /data/user/0/com.github.shadowsocks/protect_path, --crypt, none, --mtu, , 1200, --nocomp, , --mode, normal, --dscp, 46)
08-18 16:49:07.418 10997  2176 I GuardedProcess: thread interrupt, destroy process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf, -A)

turn on the udp forward or turn off the udp, also not working with kcp, only work without kcp.

**Comment by braveguywallce** [comment]
could be problem of ROM , suggest changing your phone.

**Comment by csho** [comment]
Not working on either Nexus 6P or Moto G 2014 with cm13. PC version works well.

**Comment by braveguywallce** [comment]
works well on both Nexus 6p & Nexus 5X, with stock ROM by google.

**Comment by alexliyu** [comment]
ok, i known the where is issues, it seems in config the kcp, which did not strip the blank string of param.
eg. --mtu 1024 --l 127.0.0.1:1770
this one is right, but this is error:
--mtu 1024   --l 127.0.0.1:1770

because more than one black string after 1024.

so, please check the param, strip the wrong blank string.

**Comment by alexliyu** [comment]
the new q, 
what is the version of kcp?
i do not know which version of kcp i can use in the server.

**Comment by alexliyu** [comment]
i mean 3.04. which version of kcp in it.

**Comment by alexliyu** [comment]
2016/08/18 17:31:55 [ERR] yamux: Invalid protocol version: 255
2016/08/18 17:31:55 invalid protocol version
