### ISSUE TITLE
Can't bypass China

### ISSUE THREAD

**Issue by hrzhu** [shadowsocks/shadowsocks-android#819]
Steps to reproduce:
1. Select `Bypass China` or `Bypass Lan & China` and then connect to a working server.
2. Open baidu.com on browser and then seach IP, I expect it to show me my ISP's info, namely Shanghai Telecom， but, instead, it shows me my shadowsocks service provider's info.

The bug affects both NAT and VPN mode. I've cherry-picked the release commits, the last working version is v2.9.11

**Comment by madeye** [comment]
Make sure you didn't enable UDP forwarding.

**Comment by madeye** [comment]
Also, if you're using Chrome, please refer to https://github.com/shadowsocks/shadowsocks-android/issues/404#issuecomment-164135927

**Comment by hrzhu** [comment]
Disabling UDP forwarding fixes this.

**Comment by madeye** [comment]
If UDP forwarding is enabled, all the DNS requests would be forwarded to the remote server. It means you would get an IP near your server, not your device.
