### ISSUE TITLE
Shadowsocks Android hang with kcptun

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#820]
Hi...

I noticed that when I experience the hang situation, I always have many streams open (number of opens - number of closes) on the server. I have seen numbers well over 150 streams open, by random sampling, so I don't know what the true max value is.

But the yamux configuration for kcptun has a max of 256 open streams. Could you build an experimental version of Shadowsocks Android and kcptun for windows (64 bit) with a value of say 1024 maximum open streams. I think we can limit the maximum window send and receive window sizes to 16 or 64 if there are memory issues on your Android build.

I was shocked to see how many streams were open when visiting some web pages.

Thanks,

...Karl

**Comment by madeye** [comment]
256 is large enough for client. If you want to increase the limit, plese file a bug to https://github.com/xtaci/kcptun
