### ISSUE TITLE
No connection when kcptun key contains blank space, the key example is "f**k gfw"

### ISSUE THREAD

**Issue by GangZhuo** [shadowsocks/shadowsocks-android#821]

**Comment by madeye** [comment]
It seems we may need to parse the command line before passing to kcptun.

BTW, please disable encryption of kcptun. It's useless for shadowsocks over kcp.

**Comment by Mygod** [comment]
Already fixed in 25bd5347ebaf5647584e8a1dbf8aa70199e4f6e7.

**Comment by madeye** [comment]
@Mygod You're awesome!

**Comment by GangZhuo** [comment]
Thanks

Max Lv <notifications@github.com>于2016年8月19日周五 下午5:48写道：
