### ISSUE TITLE
Need to update inner kcptun client

### ISSUE THREAD

**Issue by kmahyyg** [shadowsocks/shadowsocks-android#824]
RT, important update in xtaci/kcptun repo.
Also I Donnot want to disable kcptun's encryption,because it may lead gfw to detect the header and protocol of packet.

**Comment by kmahyyg** [comment]
i update my kcpserver to 20160820,
and ss cannot connect to internet after updating.

**Comment by Snrat** [comment]
You and I think the same. But I personally think that there is no need to use KCP, which lead to the emergence of network congestion.

**Comment by Snrat** [comment]
I think that the SS will update in these days.
