### ISSUE TITLE
Internet Unavailable on Android 6.0.1

### ISSUE THREAD

**Issue by dsh0416** [shadowsocks/shadowsocks-android#825]
I've received Internet Unavailable on Android 6.0.1 with v3.0.4 and v3.0.5 releases.
Actually it works properly at v3.0.4 for hours, then it comes to be unavailable even if I cleared up the user data and cache. Of course, I also tried to reboot.
I've found similar issue like #192 , so that I reverted the version to v2.5.7 and it works fine.
Any log file should I uploade for reproducing?

**Comment by madeye** [comment]
Double check your config. It's been well tested on Android 6.0+.

**Comment by dsh0416** [comment]
I've done a series of checks to reproduce the bug.

My configuration is copied from my Mac through QR code, so that no problem of configs.
When I disconnected my Wifi and connect through LTE network, shadowsocks-android then works properly even if the UDP forwarding is off.

When I reconnect my Wifi, then all network traffics come to 0 Bytes and the Internet becomes unavailable.

My iOS device connects to the same Wifi works fine through shadowrocket and my PC and Mac all works fine with shadowsocks-windows and shadowsocksX.

So it more strictly shows that it only presents on Android devices, not the problem of server nor the configurations. Then I tried to use an CM13.1 and Android N device to run it. All received the same Internet unavailable issue when connecting to my Wifi. So still not the problem of android version.

Then it more likely to come to be a compatibility problem between my Wifi router and shadowsocks-android, because shadowsocksX, shadowrocket and shadowsocks-windows connected to the same router all works fine.

First thing I considered is that it may be a problem of DNS. I then directly set an additional DHCP option as `6,114.114.114.114,8.8.8.8`, so that it would never use the DNS service of the router. Unfortunately, it still doesn't work.

Then I statically set the IP and DNS, to remove the effect of DHCP, but still doesn't work. It should also not a problem of Firewall settings in the router, otherwise other devices should not connect successfully either.

I believe that it could be a better way to sniffer the exact problem if there could be some logs. I've gonna build the project, and I would comment here later if any valuable message found.

**Comment by madeye** [comment]
Try a different local port, e.g. 1984.

**Comment by dsh0416** [comment]
I've tried different local ports pretty early before. It doesn't help and I'm sure that default port 1080 is not occupied in all my three devices, and does not need su permission to occupy it.

**Comment by madeye** [comment]
You'd better post all your configs and settings (except your server ip and password)

**Comment by madeye** [comment]
Also make sure no pac or proxy settings in your wifi config.

**Comment by dsh0416** [comment]
I've finally found what caused the problem.

My shadowsocks server runs on both IPv4 and IPv6 mode, and I've set both A and AAAA resolve in DNS settings. So that when using the domain, the device could automatically choose the IPv4 way or IPv6 way to connect the server.

I've made an IPv6 DHCP on my router, but my ISP does not actually make an IPv6 distribution to my GPON. So that the IPv6 connection is unavailable to Internet. Even if I've overrided the IP settings when connecting to Wifi, Android still gets its IPv6 address from DHCP, which made the shadowsocks-android connect through IPv6 which is unavailable.

shadowsocks-windows, shadowsocksX and shadowrocket looks like all use the IPv4 way to connect to my server. Only shadowsocks-android does it in IPv6. When I directly input the IP instead of domain as my server address, it gets connected correctly. 

It's pretty tricky and caused by multiple and really seldom seen reasons. But it's not a "bug" of shadowsocks-android. I'm very sorry for disturbing you, and appreciate for your awesome work.

**Comment by madeye** [comment]
If you enabled IPv6 on your router, your android device would get a valid IPV6 address. Then, shadowsocks-android would resolve an IPv6 address first.

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/utils/Utils.scala#L245

**Comment by dsh0416** [comment]
Yes, that's the point. The IPv6 address is valid but unable to bypass to Internet because my ISP issues. Thanks for your time.
