### ISSUE TITLE
remount /system failed due to the fast-open can not be opened.

### ISSUE THREAD

**Issue by GhostFlying** [shadowsocks/shadowsocks-android#826]
On Nexus 6 running Android 7.0 preview 5 with Root permission.

The client (v3.0.5) try to enable the tcp fast open but failed. 

I checked out the log from supersu and find the mount command failed like below:

mount -o remount,rw /system
mount: '/dev/block/platform/msm_sdcc.1/by-name/system'->'/system': Device or resource busy

**Comment by madeye** [comment]
@Mygod We may ignore this failure, as some device has read-only system partition.

**Comment by Mygod** [comment]
OK I'll go and see what I can do.

**Comment by Mygod** [comment]
Could you please see if other apps are able to remount your system partition, e.g. Root Explorer?

**Comment by GhostFlying** [comment]
I tested with Solid Explorer, it can remount /system as rw, and I checked out the log, it did this by a little difference.

`mount -o rw,remount /dev/block/platform/msm_sdcc.1/by-name/system /system`

I tried it with adb and it works well.

**Comment by GhostFlying** [comment]
And as I see, what the client need is two things.

1. echo 3 > /proc/sys/net/ipv4/tcp_fastopen

2. create a script in /etc/init.d/ to run at device booted

It seems that echo something to tcp_fastopen do not need to remount the /system as rw and it can be done after device booted just by BOOT_COMPLETED Broadcast.

**Comment by Mygod** [comment]
Thanks.

For boot scripts vs broadcast receiver, this is a design decision that I'm not currently considering changing unless it doesn't work well.
