### ISSUE TITLE
Kcp 加密参数的选择

### ISSUE THREAD

**Issue by channingbox** [shadowsocks/shadowsocks-android#827]
已经为 Shadowsocks 选择加密了 还有必要为kcptun 选择加密吗 还是 none 就可以了

**Comment by bubbless** [comment]
安全 🍭

无论你上层如何加密，如果-crypt none，那么协议头部都是明文的，建议至少采用-crypt aes-128加密。

注意: -crypt xor 也是不安全的，除非你知道你在做什么。
[https://github.com/xtaci/kcptun#安全-lollipop](https://github.com/xtaci/kcptun#安全-lollipop)
