### ISSUE TITLE
Warning user before modify system partition.

### ISSUE THREAD

**Issue by CzBiX** [shadowsocks/shadowsocks-android#828]
It will break the OTA update.

**Comment by Mygod** [comment]
If you have root, OTA update is already broken.

**Comment by CzBiX** [comment]
@Mygod 
Systemless Root with FlashFire can direct flash OTA package without issue.

**Comment by eastmalon** [comment]
Not only root by Flashfire, *.zip of Supersu will be flashed in with Systemless mode default under recovery. And system can update with OTA after executing "full unroot".
