### ISSUE TITLE
如何添加自定义Bypass设备？

### ISSUE THREAD

**Issue by kamiyeye** [shadowsocks/shadowsocks-android#830]
"Bypass Lan&China“无法识别Lan里面有名字的设备，例如把一台机器命名development，访问http://development/的结果是dns找不到。原理上可以理解，但一般成熟的LAN环境里每台机器都是用名字访问的，一开SS就都没法访问，实在很不方便，是否能考虑增加一个选项来添加bypass的主机名/域名？

**Comment by madeye** [comment]
No plan for this. Try  per-app proxy.
