### ISSUE TITLE
启用 kcp 协议的 bug

### ISSUE THREAD

**Issue by daya-prac** [shadowsocks/shadowsocks-android#831]
在 shadowsocks-android 3.0.4 版本中，使用在 Linux 下可以正常工作的参数，无法连接到 kcptun 服务器。换用 3.0.5 版本后，同样的参数设置，可以连接至 kcptun 服务器，可正常浏览网页，但是使用 Google play 下载应用，或者使用 youtube 客户端浏览视频的时候，手机上的网络跑满了带宽，但是，经过 shadowsocks 的网络流量非常少，Google play 下载提示等待网络连接，youtube 播放视频卡顿。此时（使用 3.0.5 版本）关闭 shadowsocks-android 的代理，发现手机的网络依然是跑满带宽的状态，重新开启 ss 代理再关闭，或者直接杀进程，依然是这个结果，只有重启手机才能结束这种带宽跑满的状态。

**Comment by madeye** [comment]
Wait for next releases of kcptun. It's still a experimental feature.

**Comment by bubbless** [comment]
3.0.5版本默认 TCP Fast open 是开启的，对于openvz的用户是无法使用的，用了3.0.5后页面很多时候打不开，看视频10KBps,回退到3.0.4后正常，看视频1MBps.
