### ISSUE TITLE
Can I open the proxy on port 1080 without opening mode vpn?

### ISSUE THREAD

**Issue by burnegg** [shadowsocks/shadowsocks-android#832]
I want to connect my openvpn server with shadowsocks as a socks5 proxy.But while opening my openvpn client,the shadowsocks stop working in VPN mode(the port 1080 was not in listening,too).
I didn't get a root privilege. Can NAT mode work out the problem?
Thanks.

**Comment by madeye** [comment]
Yes, root your device and use NAT mode.
