### ISSUE TITLE
遇到一个比较奇怪的问题

### ISSUE THREAD

**Issue by weir008** [shadowsocks/shadowsocks-android#835]
当使用推荐的VPN模式的时候，会引起android 系统产生大量的alarm。通过Wakelock Detector,可以看到在“Androd系统”下面有一个“alarm”的项目，待机一天，累计唤醒时间能达到一小时以上；
但是，如果使用nat模式的时候，则一切正常，在同样的待机时间内，“Androd系统”下面*alarm*的项目唤醒只有10多秒。
以上经过了多次AB对比，都是同样的结果。
shadowsocks版本是2.10.8，使用的都是分应用代理，绕行模式。除了模式不同其它设置完全一样。
手机型号是moto xt1097，android 6.0。

**Comment by madeye** [comment]
In the `battery/shadowsocks`, you can see the number of CPU total cycles consumed by shadowsocks. Please refer to that number instead of any other metrics.
