### ISSUE TITLE
"autoexpire" does not seem to help solve the connection loss problem of kcptun

### ISSUE THREAD

**Issue by AndlsH** [shadowsocks/shadowsocks-android#837]
When the kcptun is disabled, everything is OK. Different from issue #801, connections will lose only if the device is put into sleep for a while. The client parameter is `-key XXX -autoexpire 60`. Logs on server are as follows:
```
[ERR] yamux: keepalive failed: i/o deadline reached
[ERR] yamux: Failed to read header: broken pipe
keepalive timeout
```
Simply push the `Reset` button in the app will solve the problem. Meanwhile, it works fine on windows client. So I believe there is nothing to do with the server. 
Here is a table to better describes the issue:

Setup|When the device is inuse|After wakeup from sleep|On Windows
:---------:|:---------------------------:|:---------------------------:|:--------:
shadowsock|OK|OK|OK
shadowsock + kcptun|OK|lose connection|OK

Device info.: Samsung Galaxy Note 3, Android 5.0 root. Shadowsocks works in VPN mode.

**Comment by madeye** [comment]
It's expected that yamux would report timeout. When the connection loss happen, could you visit any sites on your device?

**Comment by madeye** [comment]
Also, please try smaller numbers of autoexpire, e.g 5.

**Comment by madeye** [comment]
It won't cause any battery drain. Actually, it may help to solve some battery drain related issues.

If you still see conntion loss after setting that number smaller than 5, then it's nothing to do with kcptun. Double check that the kcptun process isn't killed by any background service killer. This process is likely being killed by some agressive process managers, as it sends keep-alive packets frequently.

**Comment by Mygod** [comment]
I've been testing this feature for 1 hr and no connection loss observed so far. :-)

**Comment by Mygod** [comment]
Update: It turns out that I forgot to turn on kcp last time. Just experienced connection loss and it didn't reconnect in 60s.

**Comment by madeye** [comment]
When the connection lost, what's the CPU% of kcptun? Is it 100%?

**Comment by madeye** [comment]
As I've enabled log for kcptun, could you try again and capture your log when connection lost.

`adb logcat -s kcptun`

**Comment by Mygod** [comment]
OK. Reopen?

**Comment by Mygod** [comment]
Forgot to do a manual reset. So no log dump.

However here's an interesting find: kcptun process is killed. Trying to run again...

**Comment by madeye** [comment]
I think this issue may be caused by a stupid bug that the stdout/stderr buffer becomes full for kcptun...

After redirect the log to logcat, I cannot detect connection loss any more. 😅

**Comment by Mygod** [comment]
Hmm if that turns out to be the case, maybe we should just let kcptun flood logcat?

**Comment by madeye** [comment]
Already fixed here: https://github.com/shadowsocks/kcptun/commit/c4054b07a6b493f48d4e9c35c6c1a4a047462325

**Comment by Mygod** [comment]
Ok. Just then my connection is super unstable (frequent mobile data switching). I wonder if that's causing kcptun not running. I'll test it again later.

**Comment by Mygod** [comment]
I just pulled the latest commit (updated submodules, did a reset) and I'm not seeing anything on my logcat except GuardedProcess. Is this normal?

**Comment by madeye** [comment]
Could you see stream open/close with tag kcptun?

**Comment by Mygod** [comment]
No. :confused:

**Comment by Mygod** [comment]
Oh, did a clean and build again and it worked. Never mind...

**Comment by Mygod** [comment]
Ok I experienced a connection loss twice just now and it reconnected after a while. From logcat I noticed that the session actually auto expire after 2 ~ 3 mins instead of the default 60 seconds. (network active during this time) Is this normal?

**Comment by madeye** [comment]
60s is the minimum time to expire a yamux session. So, it could be 2 or 3 mins, which depends on if there are new tcp connections created for shadowsocks.

Could you try a smaller number of autoexpire? For example, 10 seconds?

**Comment by madeye** [comment]
After 24 hours testing, no more diconnections can be detected from my side. Everything works well now.

**Comment by Mygod** [comment]
[I just fixed a crashing bug](https://github.com/shadowsocks/shadowsocks-android/commit/b8c593b110d45acbb85cfe7f4fbb842c920189b7) that has been preventing me from testing it. After that, so far so good.

**Comment by Mygod** [comment]
I guess it's safe to say that this has been fixed for now.
