### ISSUE TITLE
3.0.6点击Tcp Fast Open程序闪退

### ISSUE THREAD

**Issue by bubbless** [shadowsocks/shadowsocks-android#838]
设备Android6.0.1 ，设备未获取root权限，每次点击都会闪退，VPN连接建立完成后再点击Tcp Fast Open选项，程序闪退但是VPN连接还在，还可正常使用。

**Comment by madeye** [comment]
As said in the description, you need ROOT permission to enable TFO.

**Comment by bubbless** [comment]
3.0.4和3.0.5并没有出现此问题。
