### ISSUE TITLE
快捷切换列表UI的bug

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#844]
最新release
Bug表现为当你添加了足够多的配置，然后选择最后一个配置，连接上去，然后下拉状态栏，快捷切换配置，然后弹出配置列表了，你滑动到列表的最后才能看到你当前的配置项，但是当前的配置项不是选中状态，而且列表中没有一项是选中的，然后你把列表往上滑直到你当前配置项消失，然后再滑动到你当前配置项，才显示成选中状态

**Comment by Mygod** [comment]
I think this is a bug of RecyclerView. Could you try to reproduce it?

**Comment by madeye** [comment]
Verified on Android 6.0.1.

To reproduce this issue, just add enough profiles and select the last one. If the selected one doesn't show on the screen when the switch activity created, it cannot be selected properly.

**Comment by madeye** [comment]
By fixing the height of RecyclerView, this issue disappears. I suspect it's a bug of RecyclerView itself.

**Comment by Mygod** [comment]
Oops. Forgot to change that when copy-pasting.
