### ISSUE TITLE
Shadowsocks Android and Google Play Store

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#845]
Hi...

I'm using a Nexus 6 running Marchmallow 6.0.1 August patch level, with the server running in python 2.7.12 on Winfows 10 64 Pro and the current Android Shadowsocks client..

Recently I noticed that the Google Play Store stopped checking for installed apps correctly with Shadowsocks. Sometimes it will just hang and not display my installed apps. The waiting animation just continues on.

I then noticed that pings do not work under shadowsocks. I use connectbot with a local shell and ping an external publicly addressable host. I can start a ping and then turn Shadowsocks on and off repeatedly and the ping responses stop when shadowsocks is active and resume whan shadowsocks is off.

I have reverted to the pip version of shadowsocks and the problem persists. I am not using KCP.

Thanks,

...Karl

**Comment by madeye** [comment]
ICMP is not supported.

**Comment by KarlM256** [comment]
Ok. But Google Play Services used to work with Shadowsocks and now it doesn't. That seems fairly important as a use case in blocked countries.

**Comment by KarlM256** [comment]
Ok. Cleared memory and cache on google play store. Now works. Seems strange everything worked fine but google play store on shadowsocks. And with shadowsocks turned off, the play store worked fine. Check for system update also had the same problem.

Any chance of supporting ping in the future?

**Comment by KarlM256** [comment]
So clearing memory and cache did not fix it. Or at least, it was not a lasting fix. I just rolled my shadowsocks python back to the version from pip and things are working. I was running the git version from 20160801 because it had OTA support.

I run this for a while and report back.

**Comment by KarlM256** [comment]
I can get checking for a system update in settings about phone and checking installed apps in the play store to work with either the pip version of shadowsocks python or the snapshot I downloaded on August 1, 2016. The pip version does not support OTA. With the August 1 version, I must have OTA disabled for things to work. If I turn on OTA, the problem occurs.

Also, once I turn on OTA on the Android client, it will not work with it off. It appears that this is a server issue, OTA sticks on after used once.

**Comment by KarlM256** [comment]
By the way, I want to say again... SMTP/IMAP email and web browsing work fine even when checking for system updates and the play store do not.

**Comment by KarlM256** [comment]
Reopen?

**Comment by KarlM256** [comment]
It appears to be a problem with the shadowsocks python server. The shadowsocks-go server does does not show the same problem.

Thanks for all of your work on this android software.
