### ISSUE TITLE
307在安卓N下开启tcp fast open依然重启

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#847]
Nexus 6P，安卓N正式版 7.0.0 (NRD90M)
root方式为supersu 2.77 systemless
切换tcp fast open为开，再启动ss，手机直接重启

不过这不知道是不是安卓N对/system 分区的写入限制？因为某些软件也不兼容，例如adaway无法对/system/etc/写入hosts

**Comment by madeye** [comment]
The latest version won't write anything to `/system'. If the restart still exists, I believe it's a kernel related bug.

**Comment by baraja** [comment]
确实是安卓7.0的问题，因为另一台手机在6.0下没有问题

**Comment by baraja** [comment]
http://www.the247tech.com/android/fix-android-n-preview-root-surviving-your-trip-to-mount-doom/

请开发者看下这个链接能否解决安卓N的mount问题？貌似是安卓N新引入的toybox，而toolbox被弃用造成的

**Comment by Sherlock-Holo** [comment]
所以有没有什么解决方案，那篇文章只是说出了原因，咱已经安装过busybox了，需要卸掉还是怎么样？？？

**Comment by madeye** [comment]
It's a bug of Google or Qualcomm. You have to wait for a fix from them.

**Comment by Sherlock-Holo** [comment]
咱觉得应该是google的锅，毕竟有人提到是换了toybox才出现的问题，而且咱装了busybox也不行，可能是系统某个东西改了？

**Comment by Mygod** [comment]
AOSP emulator works fine. `mount` and therefore toybox/busybox is no longer used in the latest version. Reboot is most likely caused by buggy-implemented kernel or erroneous root.

**Comment by Sherlock-Holo** [comment]
所以咱就需要等待google去修复这个问题咯？？

Mygod <notifications@github.com>于2016年11月24日周四 下午4:46写道：

**Comment by wongsyrone** [comment]
nexus 6p NBD91K正常

**Comment by Sherlock-Holo** [comment]
使用了什么box？？

Syrone Wong <notifications@github.com>于2016年11月27日周日 17:15写道：

**Comment by wongsyrone** [comment]
没用任何box，就是原厂镜像+franco kernel+phh superuser+自己的修改版
