### ISSUE TITLE
开启热点时有影响

### ISSUE THREAD

**Issue by zhengyiZ** [shadowsocks/shadowsocks-android#849]
你好，最近需要使用手机给电脑热点，发现手机上shadowsocks开启时，电脑无法上网或是很慢，关闭后，网络正常，请问如何解决。

**Comment by madeye** [comment]
Try per-app mode.

**Comment by zhengyiZ** [comment]
Thanks.  It worked.
But there is another problem , when I use per-app mode . I can't download app with google play store.  I'm sure my setting is right . I add  all the apps witch need agent. like Chrome ,YouTube ,google play store,etc. And Chrome ,YouTube and others are OK. only google play store can't be used. 

More question: when I use  the per-app mode, what should do for the route mode?

**Comment by Mygod** [comment]
Use bypass mode/make sure you let download manager go through proxy.

**Comment by zhengyiZ** [comment]
Thanks,it worked. I ignore the download manager before.

**Comment by kumkee** [comment]
如果我使用绕行模式的话，哪些apps需要绕行才可以分享热点？
