### ISSUE TITLE
ss二级代理不能上外网

### ISSUE THREAD

**Issue by DragonCat1** [shadowsocks/shadowsocks-android#850]
我在国内vps上同时开了ss-server,ss-redir,按照shadowsocks-libev的README把非大陆网段的流量都转ss-redir到国外vps，搭配ss-tunnel和dnsmasq来根据gfwlist路由域名解析。
这个方案在shadowsocks-windows，shadowrocket，Potatso下都能正常使用。唯独安卓版打不开国外网站，国内正常。

**Comment by madeye** [comment]
`iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to-destination 127.0.0.1`

**Comment by DragonCat1** [comment]
解决了，谢谢。
