### ISSUE TITLE
3.0.8 和 3.0.7 都不能装在我4.2系统的红米手机上。

### ISSUE THREAD

**Issue by ruleroller** [shadowsocks/shadowsocks-android#851]
一点击安装就提示“解析错误”、“解析包时出现问题”。

3.0.4 可以正常安装。

我下载的3.0.8的sha1值：c0ed21f2c747f8e4cf02daef0665816f0e2c6c26

**Comment by madeye** [comment]
It's expected. Update your Android system or buy a new one.

**Comment by UISAHF** [comment]
建议去MIUI论坛找一下Android 5.0版本以上的原生包 应该有人做 刷上去就好
会比你4.2好用很多的
