### ISSUE TITLE
Play store 版本 3.0.8 更新后会造成设备重启

### ISSUE THREAD

**Issue by icodex** [shadowsocks/shadowsocks-android#853]
在3.0.8 新增了一个功能，添加了 TCP Fast open，但在我的 Nexus6p 开启，赋予 root 权限后，打开就会造成手机死机并重启。
如果我取消 supersu 对 shadowsocks 的授权，并在下次启用时拒绝提供 root 权限，手机就不会重启。

**Comment by madeye** [comment]
It's a buy of Android 7.0. Wait for Google's update.
