### ISSUE TITLE
Help:: Build problem

### ISSUE THREAD

**Issue by zhouzhou3516** [shadowsocks/shadowsocks-android#854]
Got errors: Call requires API level 21 (current min is 19): 

I am using openjdk version 1.8
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

what need to be upgraded?
====error log===================================================
[info] Compiling 40 Scala sources and 14 Java sources to /home/xxxx/mypro/shadowsocks-android/target/android/intermediates/classes...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] there was one feature warning; re-run with -feature for details
[warn] two warnings found
**[error] [NewApi] target/android/intermediates/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19):android.net.VpnService.Builder#addAllowedApplication
[error] [NewApi] target/android/intermediates/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19): android.net.VpnService.Builder#addDisallowedApplication
[error] [NewApi] src/main/res/drawable/ic_arrow_drop_down.xml:1:<vector> requires API level 21 (current min is 19) or building with Android Gradle plugin 1.4 or higher
[error] <vector xmlns:android="http://schemas.android.com/apk/res/android"
[error] ^
[error]
....
[error] lint found 15 errors, 6 warnings**
[info] Packaging resources: resources-release.ap_
[info] Packaging /home/xxxxxx/mypro/shadowsocks-android/target/android/intermediates/classes.jar ...
[info] Done packaging.
**[error] Unable to locate SDK proguard config: /home/xxxxxx/mypro/android/android-sdk/tools/proguard/proguard-android.txt**
[error] (android:proguardConfig) Unable to locate SDK proguard config: /home/xxxxxx/mypro/android/android-sdk/tools/proguard/proguard-android.txt
[error] Total time: 91 s, completed 2016-9-4 2:03:43

**Comment by madeye** [comment]
Double check your SDK.

**Comment by zhouzhou3516** [comment]
@madeye build successfully passed  by modify src/main/AndroidManifest.xml  minSdkVersion
change  android:minSdkVersion="**21**"  to android:minSdkVersion="**19**" 
 I am currently using android 7.0( API 24).
Altough the build got workaround, still not sure what is the root cause.
what should be the standard fix, do you have any comments?
