### ISSUE TITLE
Testing version 3.0.8

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#855]
Hi...

Could you make a release of kcptun-shadowsocks (Windows 64 is what I use.) that corresponds to the version you used in shadowsocks-android 3.0.8? I would like to test the latest version.

Is shadowsocks-libev 2.5.0 still current with shadowsocks-android 3.0.8?

In the shadowsocks-android "Read More" section in the play store, you suggest parameters for a kcptun server. Can you give the corresponding parameters for the command line in shadowsocks-android?

In particular, should sndwnd and rcvwnd be the same in the android client or the opposite? I understand the other parameters should match, but I don't know if client sndwnd should match server rcvwnd or server sndwnd.

Thanks,

...Karl

**Comment by KarlM256** [comment]
Hi...

Comparing the defaults for the kcptun client with your suggested server configuration, I believe that sndwnd on the server should match rcvwnd on the client, and rcvwnd on the server should match sndwnd on the client.

...Karl

**Comment by madeye** [comment]
You have to figure out them yourself. This feature is for advanced users.

**Comment by KarlM256** [comment]
Could you make a release of kcptun-shadowsocks (Windows 64 is what I use.) that corresponds to the version you used in shadowsocks-android 3.0.8? I would like to test the latest version.

Is shadowsocks-libev 2.5.0 still current with shadowsocks-android 3.0.8?
