### ISSUE TITLE
after 3.0.4, i can't install new version on android 4.1.2

### ISSUE THREAD

**Issue by cat2000** [shadowsocks/shadowsocks-android#856]
after 3.0.4, i can't install new version on android 4.1.2 with samsung galaxy n7105

**Comment by madeye** [comment]
It's expected.

**Comment by cat2000** [comment]
why, can it be possible to support 4.1.2

**Comment by Mygod** [comment]
Yes you can make this app support Android 1.0 if you want.

**Comment by pexcn** [comment]
请问不兼容低版本是为了代码好维护吗？

**Comment by madeye** [comment]
If you're using Google Play to install shadowsocks, it supports all the devices above Android 2.3.

The only difference is that if you're with an old Android device, you cannot use the new features of shadowsocks. Actually it's quite reasonable.

For old versions, please refer to https://github.com/shadowsocks/shadowsocks-android/releases.
