### ISSUE TITLE
config a domain as ssserver address, the domain got hijacked!

### ISSUE THREAD

**Issue by yeweishuai** [shadowsocks/shadowsocks-android#857]
Hi guys, I configured a domain name as my ss client server address, it works fine for a few months, but recently, I found the domain was hijacked!
I ping my domain, and got a strange ip 8.7.198.45, which is different from the ip I set in my domain provider!

So, please help, I was wondering, if ssclinet should resolve the configured server domain address on ssserver!!!!

After I reconfigure the ssserver address with my correct ip instead of the domain name, it worked fine.

**Comment by madeye** [comment]
I don think it's an issue of shadowsocks.

**Comment by yeweishuai** [comment]
Hi, madeye. Thanks for your answer.
I believe if ssclient resolve the domain format server address, It would be perfect!
