### ISSUE TITLE
YouTube Android客户端 无法被代理

### ISSUE THREAD

**Issue by Easeman** [shadowsocks/shadowsocks-android#861]
Shadowsocks Android 3.0.8
Nexus 6P Android 6.0.1
Shadowsocks连接的服务器不支持 IPv6
当前连接的Wi-Fi（教育网）支持 IPv6，而且可以访问IPv6网站

Shadowsocks客户端中
IPv6转发选项关闭
UDP转发打开

在这种情况下，IPv4网站访问正常，IPv6网站不能访问
问题是：YouTube客户端可以加载评论和视频说明，视频本身无法缓冲或者缓冲个几秒后就不能继续加载了，看起来YouTube客户端没有被代理。

当使用不支持IPv6的Wi-Fi时，一切正常。

请问哪里出了问题？

**Comment by Easeman** [comment]
在这种情况下，使用YouTube加载视频，即使能加载几秒，Shadowsocks统计数据中也没有任何数据统计。个人推测是YouTube视频缓冲根本没通过代理而是走了其他的路径，比如IPv6，而IPv6通道又不通畅或被干扰，因此出现缓冲几秒后中断的问题。会是这样吗？

**Comment by madeye** [comment]
Have you enabled per-app proxy?

**Comment by madeye** [comment]
Also, try to disable UDP forwarding.

**Comment by Easeman** [comment]
感谢您的回复。
我的per-app proxy已开启，是bypass mode
经过测试
关闭UDP Forwarding后问题得到解决。
但是关闭UDP Forwarding的后果是
一些网站
比如
tw.mobi.yahoo.com
不能访问
这也是我不愿意关闭UDP Forwarding的原因。
请问为什么会这样呢？
能否从技术上的角度解释一下呢？
谢谢！

**Comment by madeye** [comment]
When UDP forwarding enabled. all DNS (UDP) traffic would be redirected to the remote server. DNS requests become totally transparent for shadowsocks.

If not, DNS requests would be resolved locally, which is handled by pdnsd. And if you also disabled IPv6 forwarding, the local pdnsd would refuse to resolve IPv6 address, which solved the issue you met.

In your situation, you have IPv6 connections locally but IPv4 only network on your server. By enabling UDP forwarding and disabling IPv6 forwarding, Youtube client chooses to connect IPv6 address, but failed without IPv6 forwarding.

**Comment by madeye** [comment]
My suggestion is to set up shadowsocks server on IPv6 enabled VPS. Then, you can even connect to your shadowsocks via IPv6.

**Comment by Easeman** [comment]
非常感谢。
请问在关闭UDP转发时
网站
tw.mobi.yahoo.com
无法访问
（应该是判断网站的规则中漏了这个网站，目前我只发现了这一个网站，也许还有更多）
这个问题应该向那里反馈并加入网站判断规则呢？

**Comment by madeye** [comment]
`.yahoo.com` is not in the GFWList. That's why you cannot visit that site with 'Bypass CHN' route.

Also, see https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/res/values/configs.xml#L3

**Comment by madeye** [comment]
I've added your domain to the online list. You may wait for couple of hours before the new config goes into effect.

**Comment by Easeman** [comment]
Thank you.
You are a great developer.

**Comment by Mygod** [comment]
Wait. Last time I checked, [Android doesn't support DHCPv6 yet](https://code.google.com/p/android/issues/detail?id=32621). How did you manage to connect to an IPv6 network?

**Comment by madeye** [comment]
@Mygod Some university have [rfc6106](https://tools.ietf.org/html/rfc6106) enabled wireless connection.

**Comment by Easeman** [comment]
After my phone had connected to the Wi-Fi provided by our school(教育网), two IP addresses, including IPv4 and IPv6 was assigned to it.
I can visit
http://bt.byr.cn/
[2001:da8:215:4078:250:56ff:fe97:654d]

directly via Google Chrome Android.

**Comment by Mygod** [comment]
That one is related to DNS configuration. Perhaps you meant [neighbor discovery](https://tools.ietf.org/html/rfc4861)?

**Comment by dolphinpaopao** [comment]
android ss 3.1.2 
Moto X 2013 android 5.1
ss设置为绕过局域网和大陆地址，开启分应用代理，udp转发和KCP，本地和服务器均为ipv4连接，同样遇到了类似的问题，YouTube Android可以加载评论以及视频描述，但是播放视频的时候缓冲通道没有经过ss+kcp，而是直接通过的ss，导致速度不理想，ss本身的数据统计那里也没有显示任何流量。关闭udp转发，问题解决。
请问一下，我这种纯ipv4的使用环境可否开启udp转发的同时解决视频缓冲通道不经过ss+kcp的问题呢？谢谢。

**Comment by kobel8** [comment]
clash for android ，在EMUI10系统中也出现这个情况。不打开分应用功能就没事。

**Comment by wangfeng35** [comment]
> clash for android ，在EMUI10系统中也出现这个情况。不打开分应用功能就没事。

原来如此
