### ISSUE TITLE
我想问怎么运行呀

### ISSUE THREAD

**Issue by yundequanshi** [shadowsocks/shadowsocks-android#862]
这个东西怎么运行呀，都运行不起来，能给些建议指导吗？scala小白

**Comment by madeye** [comment]
It's an issue tracker. Please don't post general questions here.

**Comment by pexcn** [comment]
@madeye 请问这种问题如果看了README都解决不了，应该怎么解决？StackOverflow ?

**Comment by Mygod** [comment]
RTFSC.

**Comment by madeye** [comment]
@pexcn If you're a developer, you should learn Scala by yourself. If you're a normal user, I don't think you need to build the project from source code.

Also, StackOverflow is really a better place to ask general questions.

**Comment by pexcn** [comment]
学习Android没多久，不会Scala，但是这种项目不支持Android Studio。是不是也需要学一构建系统用的语言？比如Groovy之类？
