### ISSUE TITLE
Play Store  3.0.8版本很耗电

### ISSUE THREAD

**Issue by c1024** [shadowsocks/shadowsocks-android#863]
你好，我更新了Play Store 上的 3.0.8版本，发现很耗电。
昨晚睡前我的Nexus 5 和Nexus 6p有将近90%的电量，开着Shadowsocks  , 有启用kcptun。早上起来，发现低于15%了。以前版本电量消耗没这么大。两台手机是6.0.1系统。kcptun配置参数是-crypt salsa20  --mtu 1200 --nocomp --mode normal --dscp 46  -autoexpire 60 .

**Comment by madeye** [comment]
1. Please follow the template to open an issue.
2. You need to post a screenshot of your battery usage.
3. Try 3.1.0.
4. Try adding `--keepalive 0` to your kcptun command line.
5. It's expected that KCPTUN would consume much more battery.
