### ISSUE TITLE
shadowsocks-android 3.1.0

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#864]
Hi...

Shadowsocks-android-3.1.0, shadowsocks-libev-2.5.0 64 (on windows) and the latest kcptun 64 you referenced (on windows) are all working nicely together. Stable for one full day.

"Broken Pipe" usually shows before a new connection, but nothing strange in the kcptun log.

Thanks,

...Karl

**Comment by madeye** [comment]
Please follow the template to open an issue.
