### ISSUE TITLE
3.0.4以上的小bug

### ISSUE THREAD

**Issue by LuttyYang** [shadowsocks/shadowsocks-android#865]
我测试了ss 3.0.4到3.0.10
我测试的安卓版本是6.0和7.0
英语不是很好……还是写中文吧

从play商店上下载了3.0.8版本后，发现链接不上服务器，仔细研究了下，链接几十次，有1，2次可以连接服务器，其余时间显示远程服务器rest或者不能解析google的域名，因为我开始配置的服务器地址是域名，我就怀疑是域名解析的问题，然后我就把配置项改成了ip，结果测试了几十次连接都没问题……

那个域名有A记录和AAAA记录，怀疑是我运营商并不支持ip v6，结果ss使用了ip v6的原因？

其他：
我的路由器有为手机分配ip v6，但是并不可用的
这里是手机的ifconfig信息：

wlan0     Link encap:UNSPEC
          inet addr:10.89.79.176  Bcast:10.89.79.255  Mask:255.255.255.0
          inet6 addr: fd20:6d46:8f49:0:8e3a:e3ff:fe4a:573c/64 Scope: Global
          inet6 addr: fe80::8e3a:e3ff:fe4a:573c/64 Scope: Link
          inet6 addr: fd20:6d46:8f49:0:7c4e:141b:b84c:2ef6/64 Scope: Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7601 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9124 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3355318 TX bytes:2041264

**Comment by madeye** [comment]
It's exactly the same issue as https://github.com/shadowsocks/shadowsocks-android/issues/825

https://github.com/shadowsocks/shadowsocks-android/issues/825#issuecomment-241631763

> If you enabled IPv6 on your router, your android device would get a valid IPV6 address. Then, shadowsocks-android would resolve an IPv6 address first.
> 
> https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/utils/Utils.scala#L245

**Comment by madeye** [comment]
My suggestion is to use an IPv4 only domain or make sure your have a valid IPv6 connection.

**Comment by LuttyYang** [comment]
那可不可以在连接前先判断下ip v6可不可用呢？就像windows8以上那样

**Comment by madeye** [comment]
There is no reliable method to detect this. Shadowsocks is designed to be without handshake. So, you can never take a timeout of ping or TCP reset as the result of invalid IPv6 connection.
