### ISSUE TITLE
Sometimes don't work

### ISSUE THREAD

**Issue by tankririri** [shadowsocks/shadowsocks-android#869]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?

3.1.0
### What Android OS version and device are you using?
nexus 5X 6.0.1
ROM:Mokee MK60.1-bullhead-160829-RELEASE.zip

### What did you do?
Normal use

### What did you expect to see?
As usual

### What did you see instead?
As usual

### What is your config in detail (with all sensitive info masked)?
server  : IP
remote port: 1021
local port: 1080
password: something
encrypt: chacha20
Route: Bypass LAN & China
Per-app Proxy: On
UDP Forwarding: On
KCP: On
KCP port:1022
KCP Parameters:--key "something" --crypt salsa20 --nocomp --mtu 1200 --dscp 46 --mode fast

Issues:
Connection after a period of time, the status bar displays all normal, but when used to over the wall, statistics show that no data transmission by Shadowsocks. Re connect or switch to the server and can be used normally, but after a period of failure.
连接上以后过一段时间，状态栏显示一切正常，但是使用应用的时候无法翻墙，统计数据显示没有数据经过Shadowsocks传输。重新连接或者切换服务器之后又能正常使用，但过一段时间又失效。使用之前的3.0.8版本没有出现过此问题。

**Comment by madeye** [comment]
It'd be an upstream issue of kcptun.

Try adding `--autoexpire 10` to your KCP parameters and updating your kcptun server to the latest.

**Comment by tankririri** [comment]
Try adding `--autoexpire 10`
It's working. 
It is recommended to set it as the default parameter.
