### ISSUE TITLE
3.0.8 版本无法添加配置

### ISSUE THREAD

**Issue by free4537** [shadowsocks/shadowsocks-android#870]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.0.8

### What Android OS version and device are you using?
Android OS version：6.0
device：KNT-AL20（荣耀 V8 全网通高配版）

### What did you expect to see?
3.0.7 版本无此问题，期待修复此问题。. 

### What is your config in detail (with all sensitive info masked)?
安装后无法添加配置，不论是手动输入或是扫码

**Comment by madeye** [comment]
Try to uninstall and reinstall the APK. It'd be a database corruption.
