### ISSUE TITLE
Android client 3.1.0 disconnect after two days

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#872]
Please answer these questions before submitting your issue. Thanks!

### What did you see instead? After about 48 hours, error* each time I tested the conection. From the client, I disconnected and reconnected to the server and all was fine again.
*Fail to detect internet connection: Connection closed by peer. see screenshot

**Comment by KarlM256** [comment]
![screenshot_20160909-093211](https://cloud.githubusercontent.com/assets/13839705/18397776/863ddcfa-767e-11e6-8e74-66df6666e0af.png)

**Comment by madeye** [comment]
Try the latest version.

**Comment by KarlM256** [comment]
Versions 3.1.1 and 3.1.2 give the same error immediately upon trying to connect. With 3.1.1 and 3.1.2, the problem occurs immediately both with kcptun and without kcptun.
