### ISSUE TITLE
Can't get shadowsocks to work on android with my router

### ISSUE THREAD

**Issue by hillz1** [shadowsocks/shadowsocks-android#874]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
v2.3.3

### What Android OS version and device are you using?
Lollipop

### What did you do?
Trying to set global socks5 proxy on my device

### What did you expect to see?
A working internet connection

### What did you see instead?
Error, internet isn't working

### What is your config in detail (with all sensitive info masked)?
See the screenshot below

Hi, I have an openwrt router with SOCKS5 at 192.168.1.1:1080 and I'm trying to route all my internet connection on my android device to that SOCKS5 proxy with shadowsocks but unfortunately it isn't working, here's the screenshot of my configuration: 

https://s3.postimg.org/xdg8agvv7/Screenshot_2016_09_11_13_43_10_com_github_shadow.png
https://s11.postimg.org/8542vd2tv/Screenshot_2016_09_11_13_43_17_com_github_shadow.png

I put in my router's password in the password field of the app. Can you help me how to get it to work ?

**Comment by madeye** [comment]
You need to input your shadowsocks server's info in the app.
