### ISSUE TITLE
Can't turn off the One-time Authentication in 3.0.4

### ISSUE THREAD

**Issue by catscarlet** [shadowsocks/shadowsocks-android#875]
### What version of Shadowsocks are you using?

shadowsocks-android 3.0.4

### What Android OS version and device are you using?

Android 4.2.2

### What did you do?

I tried to turn off the switch of One-time Authentication.

### What did you expect to see?

Turn off the switch of One-time Authentication.

### What did you see instead?

After a drag the menu, the switch of One-time Authentication turn itself on.

### What is your config in detail (with all sensitive info masked)?

As the GIF(8.84 MB). May need a click to watch it.

![gif](https://cloud.githubusercontent.com/assets/10594035/18422765/4ccbbed8-78d1-11e6-8442-66e539fc7587.gif)

I tried turn off the switch of One-time Authentication and turn on the main switch immediately without dragging the menu to enable shadowsocks-android, and the One-time Authentication may be off.

**Comment by madeye** [comment]
It's a known bug. Please upgrade your OS to Android 4.4 or above to use the latest version.

**Comment by leviathangirl** [comment]
OK.
Sadly my old mobile phone's hardware doesn't support Android 4.4. Reinstall shadowsocks-android 2.10.4 instead.

Before I post this issue, I searched 'One-time Authentication' as keyword to check if it was a known bug, and I found nothing but 'Minor bug fixes' in every release note, that is a pretty sad story.

**Comment by catscarlet** [comment]
OK.
Sadly my old mobile phone's hardware doesn't support Android 4.4. Reinstall shadowsocks-android 2.10.4 instead.

Before I post this issue, I searched 'One-time Authentication' as keyword to check if it was a known bug, and I found nothing but 'Minor bug fixes' in every release note, that is a pretty sad story.

**Comment by Mygod** [comment]
Confirmed on 4.4 (which is DEFINITELY Google's fault). For now, press back immediately after changing the switch.

Btw I have something which is a part of the redesign which might solve this issue. See #762.
