### ISSUE TITLE
UI改进

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#878]
点击KCP参数对话框那个问号按钮的时候，最好能把输入法隐藏

![screenshot_2016-09-14-16-56-44](https://cloud.githubusercontent.com/assets/4590439/18505991/7c049b3e-7a2f-11e6-96bf-155466de2cdc.png)

**Comment by madeye** [comment]
I don't see any issue from your screenshot. The help dialog is not covered by the input keyboard.

**Comment by pexcn** [comment]
@madeye 但是输入法还是弹出的状态，虽然没有遮挡这个对话框
