### ISSUE TITLE
I can't connect successfully with the release 3.1.4, but with 3.1.0, it works.

### ISSUE THREAD

**Issue by keytouch** [shadowsocks/shadowsocks-android#879]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.4

### What Android OS version and device are you using?
6.0.1(miui8)

### What did you do?
normal usage

### What did you expect to see?
use smoothly

### What did you see instead?
ssl handshake timed out

### What is your config in detail (with all sensitive info masked)?
normal settings, for testing this, i turn off some sections like kcp which may cause trouble.
And with the same configuration, i connected smoothly on the ssr-android or an earlier ss-android client with original protocol.
I believe that there is something to do with the new ss-android  version.

**Comment by madeye** [comment]
You need to post the detailed configuration.

**Comment by keytouch** [comment]
uh, configuration on the client?

**Comment by madeye** [comment]
Right.

**Comment by keytouch** [comment]
I can't give you the screenshot as I'm using cellphone.
configurations are like this:
basic address and port num, with aes-256-cfb encryption. No ota.

**Comment by madeye** [comment]
And other configuration?

**Comment by keytouch** [comment]
uh, normally, I will turn on ipv6, but not this time for the issue. And  the rest below such as udp,kcp are off because of it.

**Comment by madeye** [comment]
As I mentioned above, you need to post all the configurations, including specific numbers, settings, etc.

**Comment by keytouch** [comment]
remote port is above 20000, i don't want to give it out so clearly, local port:1080(default)

**Comment by keytouch** [comment]
with 3.1.0 and the same settings, it works.

**Comment by Mygod** [comment]
> What is your config in detail (with all sensitive info masked)?

Btw have you read FAQ before posting this issue?

**Comment by keytouch** [comment]
I'm now using web-based page to post this issue, sorry for that

**Comment by madeye** [comment]
If so, I cannot reproduce your issue with your provided configurations. I tried the exactly same config on my side, everything works fine.

If you're using shadowsocks-libev as the server, make sure the DNS config is correct.

**Comment by keytouch** [comment]
let me test again. Because I knew that,miui is a little different.

**Comment by keytouch** [comment]
It didn't work, still showing"ssl handshake timed out"
Is there any other way to feed you the screenshot?

**Comment by madeye** [comment]
You don't need to post screenshots, but post every detailed config of your client (without hostname and password).

Also, what's your server version? Could you also post your server's log here?

**Comment by keytouch** [comment]
I use breakwa11's ssr-python, and I ensure that there is nothing wrong with my server configuration. There exist two reasons, 
1. I can use  it fine with 3.1.0 with the same server and configuration. 
2. I used a third part provided ss account on 3.1.4 just now, it goes wrong, and after I remove 3.1.4 and reinstall 3.1.0, it worked.

For the configuration, just A minute.

**Comment by keytouch** [comment]
name: omitted
hostname: *
remote port: 20020
local port: 1080
passwd: *

**Comment by keytouch** [comment]
slip of hand just now. I will feed the configuration to u immediately

**Comment by keytouch** [comment]
encyption: aes-256-cfb
ota: no
strategy(?I can't tell that exactly): go through ss except lan addresses and mainland addresses.
ipv6: on(it's also on on the server)
udp: off
kcp: off

**Comment by madeye** [comment]
shadowsocks-android only works with the server of original protocol. If you're connecting to a "compatible" server like ssr, no guarantee here.

The known working servers with your config include:

github.com/shadowsocks/shadowsocks
github.com/shadowsocks/shadowsocks-go
github.com/shadowsocks/shadowsocks-libev

I suggest you switch to the above servers and try again.

**Comment by Mygod** [comment]
Btw have you tried resetting, etc?

**Comment by keytouch** [comment]
yep

**Comment by keytouch** [comment]
I have tried original ss, I tried gyteng's free one.

**Comment by keytouch** [comment]
I cleaned the app data for several times.

**Comment by keytouch** [comment]
reseting ,also

**Comment by Mygod** [comment]
Tip: You can edit your previous post.

If so, could you post logcat and/or the log on your server as well?

**Comment by keytouch** [comment]
2016-09-14 14:11:06 ERROR    tcprelay.py:825 [Errno 104] Connection reset by peer
2016-09-14 14:11:06 ERROR    tcprelay.py:826 exception from ::ffff:101.90.126.170:54708
2016-09-14 14:13:15 ERROR    tcprelay.py:825 [Errno 110] Connection timed out
2016-09-14 14:13:15 ERROR    tcprelay.py:826 exception from ::ffff:101.90.126.170:54713
2016-09-14 14:13:20 ERROR    tcprelay.py:825 [Errno 110] Connection timed out
2016-09-14 14:13:20 ERROR    tcprelay.py:826 exception from ::ffff:101.90.126.170:54718
2016-09-14 14:13:25 ERROR    tcprelay.py:825 [Errno 110] Connection timed out
2016-09-14 14:13:25 ERROR    tcprelay.py:826 exception from ::ffff:101.90.126.170:54724
2016-09-14 14:13:31 ERROR    tcprelay.py:825 [Errno 110] Connection timed out
2016-09-14 14:13:31 ERROR    tcprelay.py:826 exception from ::ffff:101.90.126.170:54726

**Comment by keytouch** [comment]
this is the stderr, for I used supervisor

**Comment by keytouch** [comment]
stdout is empty. (just A little confused, maybe the info are treated as stderr,)(of course it's unnecessary to the issue.)

**Comment by keytouch** [comment]
these errors seems not to be abnormal.

**Comment by keytouch** [comment]
above these are the initiating info, so omitted.

**Comment by madeye** [comment]
Please try this server https://github.com/shadowsocks/shadowsocks/archive/master.zip and post all the logs from the command line.

**Comment by keytouch** [comment]
ok, hold on

**Comment by madeye** [comment]
The command line for this server is:

`python shadowsocks/server.py -s 0.0.0.0 -p 20020 -k test -m aes-256-cfb`

**Comment by madeye** [comment]
![image](https://cloud.githubusercontent.com/assets/627917/18517916/a2859046-7ad0-11e6-8306-1f3330cde1d5.png)

From other user's feedbacks, 3.1.4 works well on Xiaomi Mi 5 with Android 6.0 (MIUI 8).

**Comment by keytouch** [comment]
ok, it works. I will turn to the ssr side. thanks. And sorry for disturbing you.
