### ISSUE TITLE
Connection fail when Per-App Proxy is switch on

### ISSUE THREAD

**Issue by perqin** [shadowsocks/shadowsocks-android#881]
It works well when Per-App Proxy is turned off. When turned on, VPN can be established but connection is unavailable.

### What version of Shadowsocks are you using?
3.1.4

### What Android OS version and device are you using?
Xiaomi Mi3W cancro Android 7.0

### What did you do?
Switch on `Per-App proxy` option. All the other options are correct. Then click `Check connectivity` on the statistic panel of the app.

### What did you expect to see?
Successful connection.

### What did you see instead?
A snack bar shows up which reads `Fail to detect internet connection: connect timed out`. Also, the device is still blocked and sites like google.com are unreachable.

### What is your config in detail (with all sensitive info masked)?
Local Port: 1080
Encrypt Method: AES-256-CFB
One-time Authentication: Off
Route: GFWList
IPv6 Route: Off
Per-App Proxy: On
UDP Forwarding: Off
KCP: Off
Auto Connect: On
TCP Fast Open: Disabled because of unsupported kernel version
NAT mode: Off

**Comment by madeye** [comment]
It'd be a bug of your ROM. Please try again with official ROMs of your device.

**Comment by Mygod** [comment]
Check if Shadowsocks is going through proxy in per-app proxy settings.

**Comment by perqin** [comment]
@Myhod Shadowsocks is off in per-app proxy settings, with bypass mode option off.

**Comment by Mygod** [comment]
Turn it on.

**Comment by perqin** [comment]
@Mygod Thanks! Everything works now, but I just wonder why Shadowsocks itself has to be used under proxy.
