### ISSUE TITLE
Cna't add server

### ISSUE THREAD

**Issue by Tynamding** [shadowsocks/shadowsocks-android#882]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.3

### What Android OS version and device are you using?
Android 6.0.1 . My device is Nexus 6p

### What did you do?
When I was trying to add a server,it crashed.this issue doesn't exist in previous version.

**Comment by madeye** [comment]
It's a known issue of database corruption. Uninstall the app and reinstall the latest version.
