### ISSUE TITLE
更新kcptun和libsodium到新版

### ISSUE THREAD

**Issue by dolphinpaopao** [shadowsocks/shadowsocks-android#883]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.4

### What Android OS version and device are you using?

5.1
### What did you do?
normal

### What did you expect to see?
https://github.com/jedisct1/libsodium/releases
https://github.com/xtaci/kcptun/releases
https://github.com/jedisct1/libsodium/issues/363
更新kcptun和libsodium到新版
偶然看到libsodium的新版增加了对AES-GCM的支持，这对ARM新平台友好。

**Comment by madeye** [comment]
1. KCPTUN is already the latest.
2. AES of shadowsocks is from mbedtls, not libsodium.
