### ISSUE TITLE
3.1开始，到beta班3.1.4升级后，无法配置

### ISSUE THREAD

**Issue by nuoxixi** [shadowsocks/shadowsocks-android#884]
Please answer these questions before submitting your issue. Thanks!

**Comment by nuoxixi** [comment]
安卓5.1系统，已root。SS从3.1开始，到beta版3.1.4升级后，无法配置，手动也无法输入配置。貌似SS自动调用系统摄像头，但没有任何信息读取出来

**Comment by qieaaa** [comment]
进设置清下数据就好吧
