### ISSUE TITLE
android 6下多用户网速统计的问题

### ISSUE THREAD

**Issue by wsdslm** [shadowsocks/shadowsocks-android#885]
Shadowsocks 3.1.4
Android 6.0.1
Nexus 6P

多用户下，只有第一个启动shadowsocks的用户有统计信息

第二个启用shadowsocks的用户的统计状态
https://ooo.0o0.ooo/2016/09/18/57de173d1e37c.png

**Comment by madeye** [comment]
Try different local ports for different users.

**Comment by wsdslm** [comment]
ok
都有统计信息了
