### ISSUE TITLE
Add "China Only" routes

### ISSUE THREAD

**Issue by Artoria2e5** [shadowsocks/shadowsocks-android#886]
A "China Only" route mode can be very useful for people outside of China trying to access Chinese services. Reasons to use a back-into-the-wall proxy include:

 * Avoid accidental RSTs on HTTP browsing
 * Improve connection quality (ironic, but yes)
 * Bypass regional limits (e.g. bilibili animes)

Other complements of current sets, e.g. "LAN Only" can be useful for constructing VPN-like networks.

**Comment by Artoria2e5** [comment]
Closing without a reason is a great way to … meh

**Comment by madeye** [comment]
Look into the above commit for details.

**Comment by Artoria2e5** [comment]
Oops sorry I didn't see that.
