### ISSUE TITLE
选择仅代理国内无法访问的网址有问题

### ISSUE THREAD

**Issue by zhuscat** [shadowsocks/shadowsocks-android#887]
### What version of Shadowsocks are you using?
3.1.4

### What Android OS version and device are you using?
6.0 OnePlus 3

### What did you do?
选择了仅代理中国大陆不能访问网站。但出现了一些国内网站加载缓慢的问题，如segmentfault 无法加载图片，知乎加载图片缓慢（失败）等。使用的是4G。

### What did you expect to see?
正常地加载这些网站。

### What did you see instead?
网站加载不正常。

**Comment by madeye** [comment]
Have you enabled UDP forwarding?

**Comment by zhuscat** [comment]
@madeye No.

**Comment by madeye** [comment]
I tried Segmentfault and Zhihu on China Unicom 4G, both of them loaded correctly.

Since it looks like a DNS issue, I updated the configs via 28339ce. You may try the next version.

**Comment by zhuscat** [comment]
I find it can not load images(load text successfully). When I trun off the shadowsocks client, the images download immediately.
