### ISSUE TITLE
It doesn't work on EMUI 4.0 （base on Android 6.0）

### ISSUE THREAD

**Issue by shouyu16** [shadowsocks/shadowsocks-android#888]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.4

### What Android OS version and device are you using?
HUAWEI Honor 6 plus device, EMUI 4.0.1 OS (base on android 6.0)

### What did you do?
I had modify it's config value (name,ip,por, etc.), but it never saved.

### What did you see instead?
I had modify it's config value (name,ip,por, etc.), but it never saved.

**Comment by madeye** [comment]
Try to uninstall and reinstall the app.

**Comment by shouyu16** [comment]
OK,it works.
