### ISSUE TITLE
sendFd failed while connecting to remote server

### ISSUE THREAD

**Issue by sherrysakura** [shadowsocks/shadowsocks-android#889]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?

3.1.4, came along from 3.0.0

### What Android OS version and device are you using?

Motorola X Pro (XT1115, shamu_t), CM 13 (Android 6.0)

### What did you do?

tried full unintall, rolled back to 2.10.8 and still doesn't work well.

But the remote server worked smoothly on Windows version Shadowsocks.

### What did you expect to see?

Successful connection

### What did you see instead?

Connecting to remote server failed: sendFd failed

### What is your config in detail (with all sensitive info masked)?

Server Details: ---

Encrypt Method: AED-256-CFB

Remote Port: 5683

Local Port: 65509

KCP: Off

Route: Bypass LAN and China

IPv6 Route: Off

Per-App Proxy: Off

UDP Forwarding: Off

Auto Connect: On

TCP Fast Open: Off

NAT Mode: Off

**Comment by madeye** [comment]
Try rebooting your phone.

**Comment by sherrysakura** [comment]
Still the same problem.
In fact, I reboot everytime after full uninstallation, and reboot again after installing a new stable version. And what's more confusing, when I rolled back to 2.10.8, the routes used to be working on this phone does not work any more, but still works on Windows. So I have to use another route on my phone.

**Comment by madeye** [comment]
The error you got means there are something wrong with your device's VPN service. My suggestion is to try other ROMs instead. It'd be a ROM issue.

Actually, if your issue is unable to be reproduced by others, no one can help you.

**Comment by farforest** [comment]
Hi,

I was getting this same error message.  It resolved when I changed the local port to 1080.

**Comment by zzzfinal** [comment]
thanks to farforest , it works again!
