### ISSUE TITLE
新版提示“服务器名无效”

### ISSUE THREAD

**Issue by choicky** [shadowsocks/shadowsocks-android#891]
最新的版本中，可能改变了host地址的约束。

之前可以使用域名表示服务器地址的，现在只能用ip了。

建议允许使用域名表示服务器地址。

**Comment by madeye** [comment]
Double check that you have a valid connection.

**Comment by choicky** [comment]
I've set up several profiles before.  All of the hosts are defined by domain.

All of the profiles works until the latest upgrading.

After the latest upgrading, it says "服务名无效".  If I change the host from domain to IP address, it works again.

**Comment by madeye** [comment]
I suggest to try again after rebooting your phone.
