### ISSUE TITLE
android7.0下不能开启SS

### ISSUE THREAD

**Issue by xcjiang** [shadowsocks/shadowsocks-android#892]
点击右上角图标启动就会报错:
![screenshot_20160921-153921](https://cloud.githubusercontent.com/assets/1203809/18701962/1934c766-8012-11e6-8406-c08becbc3882.png)

我shell进到/data/user/0/com.github.shadowsocks下面看了，确实没有tun2socks.

版本是3.1.4， playstore上装的。手机是N6P.

**Comment by Mygod** [comment]
Try pressing reset.

**Comment by xcjiang** [comment]
@Mygod  真的可以了，谢谢。为啥reset之前那些文件全都没有，reset之后就都冒出来了。
