### ISSUE TITLE
重启动手机, Shadowsocks 3.1.5 有后台进程,  但是没有创建VPN.

### ISSUE THREAD

**Issue by lyfires** [shadowsocks/shadowsocks-android#894]
Samsung Galaxy Note4 SM-N9100 With Android 5.1.1

旧版Shadowsocks 3.1.4, 则没有该问题.可以开机启动VPN.

**Comment by lyfires** [comment]
另外当使用 "分应用代理"(非绕行模式), 却没有选择任何app时, "断开连接"以后,   VPN服务依旧处于激活状态.
如果使用 "分应用代理"(非绕行模式), 同时选择有app, 则"断开连接"以后,   VPN服务会正常退出.
此问题存在于3.1.4和3.1.5版本中, 其他版本未测试.

**Comment by wansen** [comment]
另外＂Refine local DNS resolver＂后，在不开启转发DNS时，仍会强制劫持DNS到本地转发端口，导致不能联网。此问题和上面反映的问题在Nexus6p最新7.0原版映像上都存在。

**Comment by wansen** [comment]
已将软件清理数据和缓存，全新安装，问题依旧，只好回滚到3.14版
