### ISSUE TITLE
Shadowsocks 无法自启

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-android#895]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.5

### What Android OS version and device are you using?
6.0.1 Bacon

### What did you do?
nothing

### What is your config in detail (with all sensitive info masked)?

3.1.5版本的ss Android，开机并不能自启，表现为没有VPN钥匙，而且确认了ss没有起作用

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-android/issues/894
