### ISSUE TITLE
auto change switch bar if touch text beside

### ISSUE THREAD

**Issue by WanderMax** [shadowsocks/shadowsocks-android#896]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.14
### What Android OS version and device are you using?
4.44
### What is your config in detail (with all sensitive info masked)?

In the configuration process, when I touch the text beside the switch bar, the switch will change to opposite set.
I just update it from old version, not test if clean install.
Thanks.

**Comment by madeye** [comment]
Sorry, all UI related issues on Android 4.x are not supported.

**Comment by WanderMax** [comment]
OK, I will keep old version for my old device.
thanks

**Comment by Mygod** [comment]
Isn't this the expected behavior?

**Comment by WanderMax** [comment]
No, I just want to swipe up or down, but the touch will triger the switch change.

**Comment by Mygod** [comment]
Could you check if this problem persists in 3.1.6 or higher?

**Comment by WanderMax** [comment]
@Mygod tested 3.23 version, it seems fixed mostly except the Misc option: auto connect/NAT mode/TCP fast open. These will auto change switch bar if I touch the strings beside. I hope it can help you.

**Comment by Mygod** [comment]
Unable to reproduce. I believe it's a bug of your ROM.

**Comment by WanderMax** [comment]
![1](https://cloud.githubusercontent.com/assets/15909056/19210211/4f891f44-8d4e-11e6-823f-799a4262d301.png)

@Mygod you can see the snapshot, when I touch the message "Auto Connect", not the switch, then the  switch bar will turn ON from OFF state

**Comment by WanderMax** [comment]
@Mygod I am not sure whether this is the new feature of version 3. I think it is not that good as it will make misoperation. Thanks.

**Comment by WanderMax** [comment]
@Mygod sorry that I try old version, and find that same feature too, it may be my improper operation that matters.  Thanks again.
