### ISSUE TITLE
how to handle tcp dnsquery + domain

### ISSUE THREAD

**Issue by FlowerWrong** [shadowsocks/shadowsocks-android#897]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?

shadowsocks-android-3.1.5 pre-release

### What Android OS version and device are you using?

6.0.1

### What did you do?

I write a shadowsocks server in ruby. But there is packet `dns query + domain`, like this

`"\x01\b\b\b\b\x005\x00\"\x14\x11\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x03wap\x01n\x06shifen\x03com\x00\x00\x1C\x00\x01"`

It is `8.8.8.8:53 + wap.shifen.com:80`. In python version, it is just write `wap.shifen.com:80` as data to 8.8.8.8 server. see [line of python version](https://github.com/shadowsocks/shadowsocks/blob/master/shadowsocks/tcprelay.py#L374). How can I handle this packet?

### What did you expect to see?

Ignore it? But it's atype is 1. May be it is a ipv4 connection.

**Comment by madeye** [comment]
Of course you cannot ignore it. Just follow the python version.

**Comment by FlowerWrong** [comment]
Do not handle it!! So what is this dns packet for?

**Comment by FlowerWrong** [comment]
Or you can sperate it into two packets.

**Comment by madeye** [comment]
You don't need to "handle" it. Treat it as normal TCP traffic.
