### ISSUE TITLE
路由设置问题

### ISSUE THREAD

**Issue by wang20150419** [shadowsocks/shadowsocks-android#898]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.6

### What Android OS version and device are you using?
android 6.0 

### What is your config in detail (with all sensitive info masked)?

路由设置为全局才能访问 google play, 设置为绕过内网和中国大陆地址，就无法访问。

**Comment by VampireSH** [comment]
重置后台试试？？

Max Lv <notifications@github.com>于2016年9月24日周六 17:37写道：
