### ISSUE TITLE
安卓7.0的vpn设置，Always on VPN是否需要开启？？

### ISSUE THREAD

**Issue by one360** [shadowsocks/shadowsocks-android#899]
开发者，您好！安卓7.0的vpn设置里，对于每个vpn连接，有个Always on VPN选项，请问是否需要开启shadowsocks的Always on VPN选项？？开启和不开启有什么区别吗？shadowsocks的Always on VPN选项默认并没有开启。

**Comment by madeye** [comment]
Nope.

**Comment by schemacs** [comment]
'The option to enable Always on VPN from Settings is available only if VPN client targets API level 24.' at [Always on VPN](https://developer.android.com/about/versions/nougat/android-7.0.html#android_for_work) , code at [AndroidManifest.xml]( https://github.com/shadowsocks/shadowsocks-android/blob/c21bd74302cece0670bd14270d03d0f975e6d487/mobile/src/main/AndroidManifest.xml#L17)
