### ISSUE TITLE
Start on boot issue

### ISSUE THREAD

**Issue by iKirby** [shadowsocks/shadowsocks-android#900]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.1.6 (Play Store beta)

### What Android OS version and device are you using?
7.0 Build NRD90U, Nexus 5

### What did you do?
Enabled Auto connect and NAT mode.

### What did you expect to see?
Service starts automatically on boot with notification.

### What did you see instead?
Service starts but no notification. Then I open the app, it doesn't show service running, I have to reset service and start it again.

### What is your config in detail (with all sensitive info masked)?
Server enabled One-time Authentication.
Route: Bypass LAN & China.
Per-App proxy enabled.

**Comment by madeye** [comment]
Again, it's an issue related to service's state. By addding `startService` in `attachService()` can solve this.

Any thoughts? @Mygod

**Comment by Mygod** [comment]
Can you reproduce this bug?

**Comment by madeye** [comment]
Yes, I can reproduce it 100% with the following steps on Android 6.0 (Oneplus 2):

1. Force close shadowsocks.
2. Execute `adb shell am broadcast -a android.intent.action.BOOT_COMPLETED -n com.github.shadowsocks/.BootReceiver`.

By forcing `ShadowsocksRunnerService` waiting 10 seconds before `stopSelf()` can also fix this issue.

**Comment by Mygod** [comment]
Great. Let's use the later fix for now.
