### ISSUE TITLE
新版3.1.6访问百度网页异常。

### ISSUE THREAD

**Issue by lyfires** [shadowsocks/shadowsocks-android#901]
从3.1.4覆盖升级3.1.6，“仅代理中国大陆无法访问的地址”模式，打开m.baidu.com 、tieba.baidu.com、image.baidu.com异常，很多图片及CSS无法加载。
改成“绕过局域网及中国大陆地址”则正常。
3.1.4版本 “仅代理中国大陆无法访问的地址”模式能正常访问以上网页。

使用配置：
版本3.1.6
非KCP协议；
仅代理中国大陆无法访问的地址；
开启分应用代理

**Comment by madeye** [comment]
Try uninstall and reinstall.

**Comment by lyfires** [comment]
@madeye 卸载重装以后，“仅代理中国大陆无法访问的地址”模式，问题依旧。
只能暂用“绕过局域网及中国大陆地址”模式，但是这个模式，不少国内网址会解析到国外ip，以致速度较慢。。。

附设备信息：三星 note4 android 5.1.1

**Comment by lyfires** [comment]
更新网友用源码编译的3.1.7问题依旧，已回滚3.1.4。

推测是DNS问题。

看源码3.1.4的是
`label = "china-servers";
      | ip = 114.114.114.114, 112.124.47.27;`

而新版是：
` | label = "china-servers";
       | ip = 1.2.4.8, 208.67.222.222, 114.114.114.114;`

**Comment by lyfires** [comment]
补充网络环境是：鹏博士宽带，有的地方又叫长城宽带，电讯通什么的。
国内不同检测ip网站获得的ip一般不同，基本上是个大局域网。
另外shadowsocks服务器端DNS是：114.114.114.114,  PC使用正常。

**Comment by madeye** [comment]
Could you also try 3G/4G?

**Comment by lyfires** [comment]
3.1.6 试用移动4g，中国电信宽带。
m.baidu.com 、image.baidu.com加载正常，但是tieba.baidu.com下，列表页及讨论帖子。
3.1.4版本则全部正常。

**Comment by cool168** [comment]
3.1.6版本kcp模式也不正常，访问youtube缓慢，访问国内网站连接不上。kcp模式不如3.1.0流畅。

**Comment by madeye** [comment]
Are you using NAT mode?

**Comment by lyfires** [comment]
未启用NAT。
建议：能否考虑添加自定义DNS功能？
理由：国内不同运营商的网络环境差异非常大，很难1个DNS服务器兼容全部用户。
