### ISSUE TITLE
Can't update since version 3.0.4

### ISSUE THREAD

**Issue by Kris123123** [shadowsocks/shadowsocks-android#902]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.0.4

### What Android OS version and device are you using?

Android 4.2.2
### What did you do?

I tried most of the update version above 3.0.4 but they don't show the installation page. I can't open the package of the app.
### What did you expect to see?

I want to update my shadowsocks.
### What did you see instead?

I can't even open the apk package. I downloaded from github and they don't work as the version before 3.0.4.

### What is your config in detail (with all sensitive info masked)?

Android 4.2.2 Jellybean.

Please help. Is my android too old to update? I can't update my phone in China as they won't provide they update packages and installing Roms from the internet is too dangerous and not under the copyright.

**Comment by Mygod** [comment]
You are under risk by using an extremely outdated system as well.
