### ISSUE TITLE
建议Notification添加暂停按钮

### ISSUE THREAD

**Issue by kuoruan** [shadowsocks/shadowsocks-android#904]
Notification 添加暂停按键以暂时停用代理，或者点击关闭按钮的时候不要去除 Notification

**Comment by Mygod** [comment]
Read FAQ before posting issues.

**Comment by wongsyrone** [comment]
I suggest adding 

> Read FAQ before posting issues.

 to GitHub issue template with a link to FAQ page.

**Comment by Mygod** [comment]
We have [CONTRIBUTING.md](https://github.com/shadowsocks/shadowsocks-android/blob/master/CONTRIBUTING.md).

**Comment by wongsyrone** [comment]
It seems they are too lazy to click it.

**Comment by Mygod** [comment]
In that case, it wouldn't matter what we write.
