### ISSUE TITLE
无法连接远程服务器: Bad LinkAddress params /224.0.0.0/3

### ISSUE THREAD

**Issue by yangyaofei** [shadowsocks/shadowsocks-android#907]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.2.0

### What Android OS version and device are you using?
LG g3 5.0.1  nexus7 5.1.1正常

### What did you do?
从play商店升级到此版本后,就会显示此问题.刚开始以为是database文件损坏,重置后再次使用
全局,绕过中国大陆地址可用,剩下的集中模式都不可用,会出现标题中出现的错误

### What did you expect to see?
我想可能是某个参数传输出问题了

### What did you see instead?
NO

### What is your config in detail (with all sensitive info masked)?
catlog:
 https://gist.github.com/yangyaofei/51719eaaad04d63d3536c59e32c92ef9

**Comment by yangyaofei** [comment]
已证实,三星S5 9008v 5.0.1同样出现此问题

**Comment by madeye** [comment]
Duplicate with https://github.com/shadowsocks/shadowsocks-android/issues/905
