### ISSUE TITLE
Allow specifying local IP address

### ISSUE THREAD

**Issue by xiaq** [shadowsocks/shadowsocks-android#908]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?

3.1.4

### What Android OS version and device are you using?

Android 6.0.1, Asus Chromebook Flip (should be irrelevant)

### What did you do?

I launched the app.

### What did you expect to see?

I want to make the client listen on all addresses and wish to see an option for that.

### What did you see instead?

There is no such option.

### What is your config in detail (with all sensitive info masked)?

Irrevelant.

Allowing the client to listen on addresses other than 127.0.0.1 will allow other devices on the local network to make use of the proxy.

In Chrome OS, the network of the Android subsystem is behind a virtual bridge, so after launching Shadowsocks for Android, I can only use the proxy in Android apps but not in Chrome OS apps. If I can make the Android client listen on 0.0.0.0, I will be able to use it from Chrome OS apps.

**Comment by madeye** [comment]
Sorry, no plan for this. Shadowsocks-android would only listen on the local address.
