### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by xieqiyou** [shadowsocks/shadowsocks-android#909]
[armeabi-v7a] Compile thumb  : pcre <= pcre_chartables.c
[armeabi-v7a] Compile thumb  : pcre <= pcre_dfa_exec.c
[armeabi-v7a] Compile thumb  : pcre <= pcre_exec.c
jni/pcre/pcre_chartables.c:1:1: error: unknown type name 'dist'
dist/pcre_chartables.c.dist
^
jni/pcre/pcre_chartables.c:1:5: error: expected identifier or '('
dist/pcre_chartables.c.dist
    ^
[armeabi-v7a] Compile thumb  : pcre <= pcre_fullinfo.c
2 errors generated.
[armeabi-v7a] Compile thumb  : pcre <= pcre_get.c
/home/xie/ndk/build/core/build-binary.mk:472: recipe for target 'obj/local/armeabi-v7a/objs/pcre/pcre/pcre_chartables.o' failed
make: *** [obj/local/armeabi-v7a/objs/pcre/pcre/pcre_chartables.o] Error 1
make: *** Waiting for unfinished jobs....
这是缺少啥包么？

**Comment by madeye** [comment]
Double check you are using the latest NDK.

**Comment by xieqiyou** [comment]
@madeye 是的用的是r12b的ndk，谷歌官方的下载也是r12b的

**Comment by madeye** [comment]
Try 
```
git submodule update --init
```

**Comment by xieqiyou** [comment]
@madeye 找到原因了，我把代码放在和windows共享的NTFS的磁盘里，完全在Linux下操作正常
