### ISSUE TITLE
UI改进

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-android#910]
### What version of Shadowsocks are you using?

3.2.1

### What Android OS version and device are you using?

Nexus 5, CyanogenMod 13.0

### What did you do?

Not.

### What did you expect to see?

在 320dpi 的设备上显示没问题。

希望端口选择有关选项的字体能在 480dpi 的设备上显示得大一点。

### What did you see instead?

端口号字体太小

![screenshot_20160930-160553](https://cloud.githubusercontent.com/assets/4590439/18984999/5c9a5368-86bb-11e6-8e2f-6635f79d6c26.png)

### What is your config in detail (with all sensitive info masked)?

Not.

**Comment by madeye** [comment]
@Mygod Any suggestion?
