### ISSUE TITLE
关闭手机数据，再打开数据，ss会失效

### ISSUE THREAD

**Issue by one360** [shadowsocks/shadowsocks-android#911]
### What version of Shadowsocks are you using?
3.14   
只开了分应用代理，kcp；其余都是关闭
### What Android OS version and device are you using?
nexus6    android 7.0
### What did you do?
开启ss后，如果关闭手机数据，再打开数据，ss就需要关闭后再打开才能使用。
ps：手机流量不够用，会时不时的关闭手机数据。

**Comment by madeye** [comment]
Try 3.2.1

**Comment by one360** [comment]
3.2.1暂时没发现问题。之前刚升到3.14的时候也没问题，但我使用一段时间后就时不时的存在这个问题。3.2.1发现此问题再反馈给您。
