### ISSUE TITLE
hide the status bar logo

### ISSUE THREAD

**Issue by alexzhang2015** [shadowsocks/shadowsocks-android#912]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
V3.1.4

### What Android OS version and device are you using?
Android

### What did you see instead?
![file_transfer](https://cloud.githubusercontent.com/assets/859624/18991597/25541b0a-874c-11e6-8537-2df903725d7b.jpg)

### What is your config in detail (with all sensitive info masked)?

Simple needs, if we can hide the shadowsocks status bar logo?

**Comment by madeye** [comment]
Nope, you can't. It's enforced by system.
