### ISSUE TITLE
VPN 模式 IPv6 转发失效

### ISSUE THREAD

**Issue by eastmalon** [shadowsocks/shadowsocks-android#913]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.2.1

### What Android OS version and device are you using?
6.0.1(cm 13), g9006w(galaxy s5)

### What did you do?
访问Google

### What did you expect to see?
通过shadowsocks访问

### What did you see instead?
未经shadowsocks直接访问Google

### What is your config in detail (with all sensitive info masked)?
VPN模式/NAT模式；IPv6转发，开/关；远程服务器地址，IPv4/IPv6；UDP转发，开/关；一次性认证，关；kcp，关；TCP fast open，关。

判断方式是Google的重定向。

**Comment by madeye** [comment]
Try this link and post the results.

https://ipv6.google.com/search?site=&source=hp&ei=zgTvV9bUM4uOjwPR8o_gDw&q=ip&oq=ip&gs_l=mobile-gws-hp.12...779.779.0.1558.1.1.0.0.0.0.0.0..0.0....0...1c.1j4.64.mobile-gws-hp..1.0.0.rYQ1dcCnc7c

**Comment by eastmalon** [comment]
VPN模式/NAT模式；IPv6转发，开/关；远程服务器地址，IPv4/IPv6；UDP转发，开/关。
打开链接，网页底部底部依然建议使用Google.cn。

在无ipv6的网络(WLAN/4G)中。VPN模式/NAT模式；IPv6转发，开/关；UDP转发，开/关。
无法找到dns服务器地址。

**Comment by madeye** [comment]
Which device are you using?

**Comment by eastmalon** [comment]
抱歉，没填上设备名称，已经添加修改到issue中。

**Comment by madeye** [comment]
According to your report, your device may have a broken IPv6 support of VPNService, which is unable to redirect IPv6 traffic to run device.

My suggestion is to try some other AOSP roms or Nexus phones.
