### ISSUE TITLE
How to fix this build error? Thanks!

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#914]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
Latest

### What Android OS version and device are you using?
6.0.1

### What did you do?
build shadows-android

### What did you expect to see?
build with no error.

### What did you see instead?
[armeabi-v7a] Executable     : pdnsd
[armeabi-v7a] Executable     : redsocks
[armeabi-v7a] Executable     : ss-local
[armeabi-v7a] Install        : libsystem.so => libs/armeabi-v7a/libsystem.so
[armeabi-v7a] Executable     : ss-tunnel
[armeabi-v7a] Install        : tun2socks => libs/armeabi-v7a/tun2socks
jni/shadowsocks-libev/src/utils.c:108: error: undefined reference to 'getpwnam_r
'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make.exe: *** [obj/local/armeabi-v7a/ss-local] Error 1
make.exe: *** Waiting for unfinished jobs....
jni/shadowsocks-libev/src/utils.c:108: error: undefined reference to 'getpwnam_r
'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make.exe: *** [obj/local/armeabi-v7a/ss-tunnel] Error 1

### What is your config in detail (with all sensitive info masked)?
build with latest android-ndk.

**Comment by madeye** [comment]
You cannot build shadowsocks on Windows.

**Comment by ageback** [comment]
Yes I can, on Windows. I've did it on other 2 PCs.

**Comment by ageback** [comment]
Well, maybe my fault. I specified ANDROID_NDK_HOME to the old NDK path.
