### ISSUE TITLE
怎么设置DNS？

### ISSUE THREAD

**Issue by shellus** [shadowsocks/shadowsocks-android#915]
我从国外翻回国内，在国内的vps上面搭建的shadowsocks服务器。

看服务器log发现，这个安卓客户端默认使用了8.8.8.8:53的dns。但是这个vps访问不了8.8.8.8:53，所以就dns解析错误了。

我想改成国内的dns，请问怎么操作？

**Comment by madeye** [comment]
1. Update to the latest version (3.2.1) and choose the "China list: route mode.
2. Redirect the DNS on your VPS like this https://github.com/shadowsocks/shadowsocks-android/issues/812#issuecomment-240276657.

**Comment by shellus** [comment]
# sudo iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to-destination 10.0.0.10
iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
#

**Comment by shellus** [comment]
i use docker...
