### ISSUE TITLE
ss仅代理中国无法访问地址还有一些问题

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-android#916]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.2.2

### What Android OS version and device are you using?
Android 6.0.1 Bacon

### What did you do?
在仅代理中国无法访问地址时在github下载东西时，没有代理这个链接，但是绕过中国就会代理github的连接

**Comment by Mygod** [comment]
Answer all the questions please.

**Comment by VampireSH** [comment]
What did you expect to see?
这个模式能够像电脑上的PAC那样完善
What is your config in detail (with all sensitive info masked)?
配置没问题，可以连得上，就是这个模式有时候没有代理应该代理的地址

**Comment by VampireSH** [comment]
例如如果用ADM下载github上的ss-Android的话，速度很慢，用这个模式根本没有走ss，因为切换去绕过中国的话很快，明显速度上去了

**Comment by madeye** [comment]
It's expected. Amazonaws (CDN for GitHub's download site) is not blocked by GFW, as a result, it won't be in the GFW List.

You may face low speed when downloading files from AWS with some ISPs. So, switch to Bypass CHN mode instead.

**Comment by VampireSH** [comment]
好哒，那以后再github下载东西时只能切换去那里了😂😂😂

Max Lv <notifications@github.com>于2016年10月3日周一 11:18写道：
