### ISSUE TITLE
Where to place the "Download Manager"

### ISSUE THREAD

**Issue by HankWangCHN** [shadowsocks/shadowsocks-android#918]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.2.3 Beta

### What Android OS version and device are you using?
Nexus 6p, Android N

### What did you do?
即使开启 "Bypass Lan & China“ , 下载国内软件时的速度=Shadowsocks 体现的速度

### What did you expect to see?
Download Manager 是否需要设置分应用代理？是否能区分下载源来自于墙内外？

此外，请问Route中的GFW 和 Bypass Lan & China 区别在哪里？

### What is your config in detail (with all sensitive info masked)?
Bypass Lan & China

请指教！谢谢。

**Comment by madeye** [comment]
Try GFW List mode.

**Comment by HankWangCHN** [comment]
Any difference between "GFW List Mode" & "Bypass Lan & China Mode"? I think many Chinese users will have the same question.

**Comment by madeye** [comment]
literally, proxy only sites in the GFW List or bypass any IP of China and LAN.
