### ISSUE TITLE
希望能与Tasker兼容

### ISSUE THREAD

**Issue by nopcall** [shadowsocks/shadowsocks-android#92]
我使用Tasker在连接wifi的时候 或者打开某应用的同时打开shadowsocks 
但是我不能让shadowsocks自动连接我的vps 并在后台工作。
是否能向shadowsock发送哪些参数实现这一功能呢？

**Comment by shangdawei** [comment]
v2.9.2 Add Tasker/Locale support by @CzBiX.

https://github.com/shadowsocks/shadowsocks-android/releases/download/v2.9.2/shadowsocks-nightly-2.9.2.apk
