### ISSUE TITLE
 Disconnect Often

### ISSUE THREAD

**Issue by rinaldizulfikar** [shadowsocks/shadowsocks-android#921]
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?
3.2.3

### What did you do?
Disconnected every less than a minute and needed to reconnect manually to continue..

### What did you expect to see?
Stable connection

### What did you see instead?
Automatic disconnect

### What is your config in detail (with all sensitive info masked)?
I turn off the battery saver mode but still disconnected..

**Comment by madeye** [comment]
It's not a bug of shadowsocks, but caused by incorrect settings or bug of your ROM. Double check that you're not kill shadowsocks' background services through battery saver, background service killer or security module like "knox" from samsung.
