### ISSUE TITLE
Others cannot connect to my hotspot if shadowsocks is turned on

### ISSUE THREAD

**Issue by was4444** [shadowsocks/shadowsocks-android#925]
### Environment

* Android version:  "6.0.1"
* Device/Device model: "Mi4/CyanogenMod Mi Cancro"
* Shadowsocks version: "3.2.3"

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Turn on hotspot with shadowsocks enabled.

### What did you expect to see?

Others can connect to my hotspot.

### What did you see instead?

* Others cannot connect to my hotspot;
* Others can connect to my hotspot if I turn off shadowsocks;

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/849

**Comment by iamsad3508** [comment]
虽然分应用代理能解决，但Nexus 6p NBD90X 就算建立PPTP都会导致其他机不能连上热点，一直停在验证身份或者获取IP上面，之前连上的不会有问题，所以这是谷歌的bug？
