### ISSUE TITLE
Android N Quick Setting Tile 无法开启ss

### ISSUE THREAD

**Issue by NLMartian** [shadowsocks/shadowsocks-android#926]
如题，google nexus 5x ，Quick setting tile 开启 shadowsocks 不能，可以关闭。非必现，还没找到规律。

**Comment by Mygod** [comment]
Please follow the issue template.

Cannot reproduce on bacon cm14.

**Comment by BlinkoWang** [comment]
reproduced on Google Nexus 6p NBD90X, always reproduced

**Comment by Mygod** [comment]
Have you tried resetting, clearing app data, etc.? Some report that after upgrading system this issue is gone.

**Comment by iamsad3508** [comment]
Nexus 6p NBD90X和它的上一个版本号都是这样好久了…只能关闭，都是10次有差不多10次不能开启，试过卸载重安装。刚试了一下(卸载再安装)ss3.0.3至3.0.6都可以，3.0.7和3.0.8就开始不行了。

**Comment by Mygod** [comment]
@iamsad3508 Thanks for that information. However I'm afraid that's not possible since [as you can see that there are absolutely 0 changes to quick switch functionality in 3.0.7 and 3.0.8](https://github.com/shadowsocks/shadowsocks-android/compare/v3.0.6...v3.0.8). Did you remember to do a reset?

**Comment by dfdragon** [comment]
nexus 5x NBD90W 没有任何问题，Quick Setting Tray能够正常的停止及启动ss 3.2.4，设置Quick Setting Tray时没有使用第三方工具软件，例如Custom Quick Settings等

**Comment by iamsad3508** [comment]
重启手机后，甚至3.2.4都可以正常开关了，所以还是没找到规律。但新安装或更新影梭的时候(影梭保持运行)，会造成快捷图标只能关不能开的问题，暂时重启能解决

**Comment by dfdragon** [comment]
你描述的这个现象像是第三方APP驻留内存引起的。我是不定期清理内存的，只有我允许的几个APP驻留。

**Comment by lijun0326** [comment]
nexus 6p NBD90X亲测没问题

**Comment by Mygod** [comment]
@iamsad3508 I tried these steps:

1. Toggle off with QS tile;
2. Toggle on with QS tile;
3. Build the latest commit 97d31cb and push it to my phone;
4. Toggle on with QS tile.

And the issue didn't happen.

By the way if you are installing Shadowsocks with a different version, it's expected since you need to start the app to let it do the initialization. But after that it should work (both on and off).

**Comment by Mygod** [comment]
@madeye What about moving initialization to BaseService then since it seems not everyone wants to launch the app after they installed an update?

**Comment by madeye** [comment]
LGTM. The initializing was put in the main activity because some very old versions require Root permission when initializing.

**Comment by c1024** [comment]
@madeye 我是用Nexus 6p Android N,这个问题我之前也遇到。出现情况是快速设置有两页，如果shadowsocks 是在第二页，就只能关，不能开。把shadowsocks放到第一页就正常了

**Comment by Mygod** [comment]
@c1024 Provide complete steps to reproduce your issue please. I'm unable to reproduce this.

**Comment by c1024** [comment]
@Mygod  安装最新google play 版本后，把shadowsocks开关放到快速设置第二页，然后想从那边打开shadowsocks，打开不了。如果移到第一页就正常了
