### ISSUE TITLE
Advice: About default translations for zh_SG

### ISSUE THREAD

**Issue by kaneawk** [shadowsocks/shadowsocks-android#927]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Singapore's officical default chinese language is Simplified Chinese, NOT Traditional Chinese, as same as China mainland. But app's set the language to TC as default, I think this is not the proper way.

**Comment by Mygod** [comment]
I don't think [`zh-rSG` is officially supported by AOSP](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res). There are only `zh-rCN`, `zh-rHK`, `zh-rTW`. There is `en-rSG` however. Searching `zh-rSG` in Android source returns nothing. Are you sure your ROM is using `zh-rSG`?

**Comment by Mygod** [comment]
Just checked again and it seems [Android actually supports a lot of locales](https://android.googlesource.com/platform/external/icu4c/+/master/data/lang/). I'll see how to fix this.

For now if you are using Nougat, you can add Chinese Simplified (China) to your language preferences.
