### ISSUE TITLE
Test operation slow

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#928]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment
Nexus 6, Marshmallow 6.0.1 with September update. Shadowsocks Android 3.2.4 and perhaps 3.2.3.

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [x ] Client IPv6 availability
* Local port: 1080
* Encrypt method: default
* [x ] One-time authentication (makes no difference)
* Route: Bypass LAN
* [x ] IPv6 route (makes no difference)
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x ] UDP Forwarding (makes no difference)
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Make a connection to my shadowsocks libev server

### What did you expect to see?
With the same server 2.5.3, I expected to response time consistently about 80 to 110 ms.

The first test after doing nothing with the phone for  2 or 3 minutes is always 500+ ms, after that, repeated test response times are in the 80 to 110 ms range.

### What did you see instead?

Now it varies from 80 to 700 ms, occasionally over 1000 ms.
I see this just tapping test each time the previous test completes.
Upgrading to the 2.5.4 ss libev server made no change.

After disconnecting and reconnecting, the client, I don't see the problem for a while.

I know this is not much to go on, so I will keep looking for patterns to the behavior.

Thanks,

...Karl

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-android. When you see unstable latency numbers, the first thing you need to check is your network.

If your network to your VPS is stable. My suggestion is to change the DNS of your shadowsocks-libev. You may try to set up a local caching DNS server like unbound. And point your DNS to the local one.

**Comment by madeye** [comment]
Closed as inactive.
