### ISSUE TITLE
Ping服务器无丢包，但连接SS后网络时断时续

### ISSUE THREAD

**Issue by Easeman** [shadowsocks/shadowsocks-android#929]
### Environment

Android 6.0.1
Google Nexus 6P
Shadowsocks 3.2.4

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [  ] IPv6 server address
* [x ] Client IPv4 availability
* [  ] Client IPv6 availability
* Local port: 1080
* Encrypt method:chacha20
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [ x] Per-App Proxy
  * [ x] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

无论是用中国联通，中国移动，中国电信的网络，用工具Ping我的美国西海岸服务器的IP V4地址，能Ping通而且几乎无丢包。
我当前用的是大学提供的教育网，网络IP是山东移动。
在这个网络环境下Ping我的美国西海岸服务器，IP V4地址，能Ping通而且几乎无丢包。
在使用Shadowsocks建立连接后，使用客户端的Check Connectivity，要不是超时，要不是高延迟，时断时续。在这种情况下上网也是断断续续，甚至长时间打不开网页，感觉丢包率超高的感觉，更换很多端口都是一样的状况。
在使用中国联通时，一切正常，没有任何超时现象，速度非常快，所以排除服务器端故障。

现在的问题是，在校园网的状况下，我的服务器能Ping通，而且无丢包，而当Shadowsocks客户端建立连接后，就给人丢包率很大的感觉，我不知道哪问题出在哪里。

### What did you expect to see?

如果Ping我的服务器延迟稳定无丢包，那么在Shadowsocks客户端内部的测试工具中也不应该出现大量超时的状况。

### What did you see instead?

中国联通，Ping我的服务器
未建立Shadowsocks连接时：
延迟稳定，无丢包
建立Shadowsocks连接后：
延迟稳定，无丢包

校园教育网（中国移动外网IP），Ping我的服务器
未建立Shadowsocks连接时：
延迟稳定，无丢包
建立Shadowsocks连接后：
延迟不稳定，大量丢包，几乎不能用

感谢您的解答！

**Comment by Easeman** [comment]
甚至有的时候客户端内Check Connectivity能持续测出延迟，但是网页就是打不开或者要等很久很久

**Comment by madeye** [comment]
It's a typical QoS issue. You can try:

1. Use common ports like 443, 80.
2. Try Shadowsocks over KCP.

**Comment by Easeman** [comment]
感谢您的解答 :)
