### ISSUE TITLE
version 3.2.4 affect the android bluetooth and wifi thethering

### ISSUE THREAD

**Issue by skt041959** [shadowsocks/shadowsocks-android#930]
### Environment

* Android version: 5.0.2
* Device: Moto X Pro
* Shadowsocks version: 3.2.4

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-256-CFB
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
1.open shadowsocks-android app like the above settings.
2.open the android bluetooth tethering switch
3.try to connect the bluetooth tethering from a laptop(running ArchLinux) and another Android Phone

### What did you expect to see?
The bluetooth and WiFi tethering can work at previous version.

### What did you see instead?

But after I update the shadowsocks-android app, I found that the clients cannot get IP address.
When I closed the shadowsocks-android app, the tethering worked normally.

The above appearanced when I tried to use WiFi tethering too.

**Comment by skt041959** [comment]
I have Route bypass LAN and China.
Whould you please provide the previous version? Then I can use it waiting the issue fixed

**Comment by madeye** [comment]
You can find all releases here: https://github.com/shadowsocks/shadowsocks-android/releases

And with which release, you can tether with shadowsocks connected?

**Comment by skt041959** [comment]
@madeye Thank you! I downgrade to the previous release v3.1.4. It works perfectly.

**Comment by skt041959** [comment]
The v3.1.5 works, v3.2.3 doesn't work with this issue.
And v3.2.0 has another bug, so I can't try.
