### ISSUE TITLE
Question：why to "System.jniclose(fd)"?

### ISSUE THREAD

**Issue by waitray** [shadowsocks/shadowsocks-android#931]
when ss-local send fd and VPNService had protected it succeed, the code
```
 // Trick to close file decriptor
  System.jniclose(fd);
```

i think it do some black magic,but i dont know ,can anyone tell me?

**Comment by madeye** [comment]
Because no `close(int socket)` API in Java.

**Comment by waitray** [comment]
but why close it ? ss-local use it to send data to remote-server?

**Comment by madeye** [comment]
Nope, sockets are closed to avoid socket leak.
