### ISSUE TITLE
编译方式

### ISSUE THREAD

**Issue by Honsec** [shadowsocks/shadowsocks-android#933]
这是非官方吗？
写的这么乱起八糟的。
到底要下载多少个语言环境和插件。

不是每个人都像你一样使用同一样的编程环境，至少提供一下环境和Tip不行吗？真装逼

**Comment by Sherlock-Holo** [comment]
不爽就自己重造轮子咯

Max Lv <notifications@github.com>于2016年10月11日周二 17:48写道：

**Comment by Sherlock-Holo** [comment]
不爽就自己重造轮子咯
Honsec <notifications@github.com>于2016年10月11日周二 17:46写道：

**Comment by pexcn** [comment]
人蠢怪社会系列

**Comment by IronXiao** [comment]
唉  我这是maven那几个插件下不动，挂代理在浏览器输插件地址直接就403了，不挂代理倒是死都下不动，忧伤的一笔，你们谁能下指导一下... ...

**Comment by gaotong2055** [comment]
用Scala确实很奇葩
