### ISSUE TITLE
how to bypass China when enable the per-app proxy？

### ISSUE THREAD

**Issue by jeremiesun** [shadowsocks/shadowsocks-android#934]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.01
* Device: nexus6p
* Shadowsocks version: 3.24

分应用代理模式勾选以后 绕过大陆网址那个选项还有用吗？
我应该怎么设置能让chrome 浏览Google时候代理 浏览国内网站时不代理呢？
应该不开绕行 把chrom勾选 ，还是开绕行 不勾选chrome呢 
我试了不管哪种方法 浏览国内网页的时候也在走代理

I select bypass lan&china in the route. and I enable the per-app proxy.Then I found I couldn't baypass china when browse the webq in chrome.No matter I  enable bypass mod and select chrome or disable bypass mod and not select chrome.
it means when i visit the chinese website in chrome, it isn't fast enough.

**Comment by madeye** [comment]
First of all, make sure you're not enabling "Data Saver" function of Chrome.

**Comment by jeremiesun** [comment]
thanks to madeye,,much better!

**Comment by Honsec** [comment]
@jeremiesun  能告诉我build 方法吗? 我无法编译。。。好苦逼
