### ISSUE TITLE
Could you provide detail build command?

### ISSUE THREAD

**Issue by Honsec** [shadowsocks/shadowsocks-android#935]
fucking document

**Comment by madeye** [comment]
Build of shadowsocks-android is very straightforward.

* First of all, make sure your building environment meets the (prerequisites)[https://github.com/shadowsocks/shadowsocks-android#prerequisites]
* Then, setup the environment variables and run "sbt native-build clean android:package-release"

For step-by-step building instructions, please refer to our travis-ci scripts: https://github.com/shadowsocks/shadowsocks-android/blob/master/.travis.yml

An example of the full building process can be found here: https://travis-ci.org/shadowsocks/shadowsocks-android/builds/165554883
