### ISSUE TITLE
YouTube全屏会使SS关闭

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-android#937]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: Android 6.0
* Device: mate8移动版
* Shadowsocks version: v 3.2.5

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [x ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:chacha20
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ x] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: --mode normal --autoexpire 30
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

watching YouTube

### What did you see instead?

问题：只要打开YouTube全屏，ss就自动关闭。系统已设为可后台运行，前面版本都没这问题。

**Comment by ageback** [comment]
Confirmed. With COC game.

**Comment by wongsyrone** [comment]
You'd better attach logcat
