### ISSUE TITLE
Still can't bypass China when enable the per-app proxy

### ISSUE THREAD

**Issue by jeremiesun** [shadowsocks/shadowsocks-android#938]
Environment

Android version: 6.01
Device: nexus6p
Shadowsocks version: 3.24
分应用代理模式勾选以后 绕过大陆网址那个选项还有用吗？
我应该怎么设置能让chrome 浏览Google时候代理 浏览国内网站时不代理呢？
应该不开绕行 把chrom勾选 ，还是开绕行 不勾选chrome呢 
我试了不管哪种方法 浏览国内网页的时候也在走代理 
我已经关掉了chrome的节省数据功能 我试了其他浏览器也是这样的

I select bypass Lan&china in the route. and I enable the per-app proxy.Then I found I couldn't baypass china when browse the web in chrome.No matter I enable bypass mod and select chrome or disable bypass mod and not select chrome.
**I am  disable the data saver in chrome already. And I tried the other browse, it is still the same.**

**Comment by madeye** [comment]
When "Bypass CHN" enabled, your chrome will connect to china IPs directly, no matter you enable or disable "per-app proxy".

When you say "you can't bypass china", how did you reproduce or verify this?

**Comment by jeremiesun** [comment]
@madeye   OK...I see...I Think that's a little inconvenient. Because if I disable "per-app proxy"and only enable "Bypass CHN",some chinese apps such as Taobao still slow, it still use the agent. 
When I enable the per-app mod, it's much better, but only the browse can't decide which website should bypass.
About reproduce this, when the website or the app is bypass ,the ''sent''and''received'' in the notification bar is 0kb/s.
Or use the taobao website，if bypass，the web language is simplified Chinese .If not ,it is  traditional Chinese. Such as this site :https://item.taobao.com/item.htm?spm=686.1000925.0.0.A6ynPV&id=538444472516

**Comment by madeye** [comment]
You should not rely on the status in the notification to identify China IPs are correctly bypassed.

To verify the "Bypass CHN" feature, you may try these sites:

1. https://www.baidu.com/s?wd=ip
2. http://ip.cn

Also, you could try "GFW List" mode.
