### ISSUE TITLE
shadowsocks can't connect with kcptun enable

### ISSUE THREAD

**Issue by markyzq** [shadowsocks/shadowsocks-android#939]
Environment

Android version: 5.1
Device: 华为5x
Shadowsocks version: 3.24

没有使能kcptun前，Shadowsocks能够上网，开启kcptun后，无法上网。

已经反复对照过服务器和客户端的配置，确认kcptun的配置都是一致的。

在android logcat中看到：
I/kcptun  (10598): main.go:365: listening on: 127.0.0.1:1170

为什么这边的监听端口写死成了1170?
kcp cmdline上面配上-t 127.0.0.1:8989, shadowsocks kcp功能打开就失败。

**Comment by madeye** [comment]
You should follow the template and post all your parameters here.
