### ISSUE TITLE
切换配置文件后，通知栏的“关闭”按钮不见了

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#940]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: nexus 6p NBD90X
* Shadowsocks version: 3.2.6

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [ x] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
连接成功之后在通知栏或者软件内切换配置文件

### What did you expect to see?
“切换”和“关闭”按钮都在

### What did you see instead?
只剩下“切换”可以按，“关闭不见了”

**Comment by Mygod** [comment]
You can shut it down with QS tile.

**Comment by iamsad3508** [comment]
yes. but it's curious it disappeared.
