### ISSUE TITLE
Network connection slow when gfwlist enabled

### ISSUE THREAD

**Issue by fanthos** [shadowsocks/shadowsocks-android#941]
### Environment

* Android version: 6.0.1
* Device: Honor 8
* Shadowsocks version: v3.2.6

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: RC4-MD5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Open some Android apps with lots of image should be loaded from Internet, and the host is not in gfwlist.

### What did you expect to see?
The images should be loaded in short time, like VPN disabled.

### What did you see instead?
The images have been loaded much more slow than VPN disabled.

**Comment by fanthos** [comment]
I can't reproduce this every time, sometimes it works but sometimes not.
It may happen several minutes after I started the VPN.

When I change route to Bypass LAN & China, it works great.

**Comment by madeye** [comment]
If you're visiting a site outside China and not in the GFWList, the random slow speed is expected.

**Comment by fanthos** [comment]
I was using Taobao for Android, and the images loading slow.

**Comment by madeye** [comment]
For apps like Taobao, it'd be a CDN related issue. My suggestion is to bypass them in the per-app proxy mode.

**Comment by fanthos** [comment]
Thanks. I am trying more apps about this issue.

**Comment by madeye** [comment]
I suggest to try web pages like sina.com and huaban.com that with many images and not in the GFWList.

**Comment by fanthos** [comment]
Taobao for Android works great just after I start VPN, but it becomes slow after several minutes, and Zhihu has same problem.
When I browsing items on Taobao app, data usage on shadowsocks did not increase, so I think this means the connections have been bypassed.
sina.cn and huaban.com seems good.

**Comment by fanthos** [comment]
I am checking the gfwlist.acl, maybe there need dot`.` at left?
I think
`.*youtube\.com`
should be written like
`(.*\.)?youtube\.com`
Also,
`google.cn` is not GFWed.

**Comment by madeye** [comment]
1. So it's definitely a CDN related issue. Bypass these two apps in the per-app mode.
2. `.*youtube\.com` means matching any sites with the suffix `youtube.com`.
3. `google.cn` is located at China, not in the GFW list.

**Comment by fanthos** [comment]
1. google.cn is in the gfwlist.acl file found in shadowsocks apk.
2. thisisnotyoutube.com matchs .*youtube\.com but not match (.*\.)?youtube.com

**Comment by fanthos** [comment]
Maybe I should enable verbose mode for ss-local to find out how it happened.
