### ISSUE TITLE
无法绕过中国大陆地址 Cannot bypass China

### ISSUE THREAD

**Issue by Monsieurs** [shadowsocks/shadowsocks-android#942]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1
* Device: Nexus 5
* Shadowsocks version: v3.2.4
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: --crypt "salsa20"
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

访问 ip.cn 检测IP地址

### What did you expect to see?

显示我的运营商IP

### What did you see instead?

显示了我的代理服务器IP

**Comment by madeye** [comment]
Uninstall and reinstall, then try again.

**Comment by Monsieurs** [comment]
http://www.baidu.com/s?word=ip This remains showing my proxy IP. However, after turning UDP Forwarding off, it shows my ISP IP.

**Comment by Monsieurs** [comment]
ip.cn sometimes shows my ISP IP, sometimes shows my proxy IP.

**Comment by madeye** [comment]
It's a CDN related issue. UDP forwarding means to forward all UDP requests to the remote server, including DNS queries. As a result, you would observe some sites are resolved outside China.

Also, you may try GFWLIST mode.

**Comment by Monsieurs** [comment]
@madeye UDP转发转发的流量包括分应用代理绕行模式中勾选的应用吗？

**Comment by madeye** [comment]
Nope.

**Comment by pieceist** [comment]
@madeye 还有一个问题，既然shadowsocks默认支持远程DNS解析，那UDP转发关闭状态下DNS解析是由ISP完成还是代理服务器完成？
