### ISSUE TITLE
如果有仅在wifi下启用KCP的选项就更好了

### ISSUE THREAD

**Issue by rchunping** [shadowsocks/shadowsocks-android#944]
首先，谢谢开发者！

发现新版增加了KCP支持，因为KCP的冗余发包，有选项能够只在wifi下使用会更好。

**Comment by Mygod** [comment]
Use Tasker integration.

**Comment by rchunping** [comment]
好主意！

**Comment by aihornmac** [comment]
+1 Wondering if this feature is shipped

**Comment by Mygod** [comment]
Tasker integration is available since 2.9.2.

**Comment by aihornmac** [comment]
@Mygod Thx for guidance
