### ISSUE TITLE
does ss-android 3.2.4 support kcptun's manual mode?

### ISSUE THREAD

**Issue by peakvision** [shadowsocks/shadowsocks-android#946]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment
android 5.1
samsung gt-n7100(t03g)
ss-android 3.2.4 gplay
* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes256
* [x ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
--conn 1 --autoexpire 10  --key KCPKEY --crypt aes --mtu 1350 --sndwnd 128 --rcvwnd 1024 --datashard 70 --parityshard 30 --dscp 0 --nocomp --mode manual --nodelay 0 --resend 0 --interval 50 --nc 1
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
old settings:
server(160922): --key KCPKEY --crypt aes --mode normal --mtu 1350 --sndwnd 1024 --rcvwnd 1024 --datashard 10 --parityshard 3 --dscp 0
ss-android-3.2.4:  --key KCPKEY --crypt aes --mode normal --conn 1 --autoexpire 10 --mtu 1350 --sndwnd 128 --rcvwnd 1024 --datashard 10 --parityshard 3 --dscp 0
result: ss-android and ss-winclinet+kcptunclient(160922) are both ok.

new settings:
server(160922): --key KCPKEY --crypt aes --mtu 1350 --sndwnd 1024 --rcvwnd 1024 --datashard 70 --parityshard 30 --dscp 0 --nocomp  --mode manual --nodelay 0 --resend 0 --interval 50 --nc 1
ss-android-3.2.4: --conn 1 --autoexpire 10  --key KCPKEY --crypt aes --mtu 1350 --sndwnd 128 --rcvwnd 1024 --datashard 70 --parityshard 30 --dscp 0 --nocomp --mode manual --nodelay 0 --resend 0 --interval 50 --nc 1
result: ss-android=cannot connect to internet, ss-winclient+kcptunclient(160922)=ok.

**Comment by madeye** [comment]
I tried your config line, everything works well.

You may submit the adb log here, with the command line `adb logcat -s GuardedProcess`

**Comment by peakvision** [comment]
chcp 65001
Active code page: 65001

F:\Google\Android>adb logcat -s GuardedProcess
--------- beginning of system
--------- beginning of main
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --key, KCPKEY, --crypt, aes, --mode, normal, --conn, 1, --autoexpire, 10, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 10, --parityshard, 3, --dscp, 0)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 71, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 75, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:1133)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6ffffffe arg 0xdb8
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): start process: WrappedArray(/data/data/com.github.shadowsocks/pdnsd, -c, /data/data/com.github.shadowsocks/pdnsd-vpn.conf)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/pdnsd: unused DT entry: type 0x6ffffffe arg 0x14dc
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/pdnsd: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-tunnel, -V, -t, 10, -b, 127.0.0.1, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-tunnel-vpn.conf, -L, 8.8.8.8:53, -A)

I/GuardedProcess( 8415): * 10/22 04:18:46| pdnsd: info: pdnsd-1.2.9a-par starting.
I/GuardedProcess( 8415): * 10/22 04:18:46| pdnsd: warning: Could not open disk cache file /data/data/com.github.shadowsocks/pdnsd.cache: No such file or directory
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-tunnel: unused DT entry: type 0x6ffffffe arg 0x1480
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-tunnel: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-tunnel, -V, -t, 10, -b, 127.0.0.1, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-tunnel-vpn.conf, -L, 8.8.8.8:53, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 75, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:1133)
I/GuardedProcess( 8415): thread interrupt, destroy process: WrappedArray(/data/data/com.github.shadowsocks/pdnsd, -c, /data/data/com.github.shadowsocks/pdnsd-vpn.conf)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 78, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:1133)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6ffffffe arg 0xdb8
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): start process: WrappedArray(/data/data/com.github.shadowsocks/pdnsd, -c, /data/data/com.github.shadowsocks/pdnsd-vpn.conf)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-tunnel, -V, -t, 10, -b, 127.0.0.1, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-tunnel-vpn.conf, -L, 8.8.8.8:53, -A)

I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/pdnsd: unused DT entry: type 0x6ffffffe arg 0x14dc
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/pdnsd: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): * 10/22 05:24:40| pdnsd: info: pdnsd-1.2.9a-par starting.
I/GuardedProcess( 8415): * 10/22 05:24:40| pdnsd: warning: Could not open disk cache file /data/data/com.github.shadowsocks/pdnsd.cache: No such file or directory
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-tunnel: unused DT entry: type 0x6ffffffe arg 0x1480
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-tunnel: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-tunnel, -V, -t, 10, -b, 127.0.0.1, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-tunnel-vpn.conf, -L, 8.8.8.8:53, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 78, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:1133)
I/GuardedProcess( 8415): thread interrupt, destroy process: WrappedArray(/data/data/com.github.shadowsocks/pdnsd, -c, /data/data/com.github.shadowsocks/pdnsd-vpn.conf)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 82, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6ffffffe arg 0xdb8
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6ffffffe arg 0xf04
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): Incorrect Usage.
I/GuardedProcess( 8415): NAME:
I/GuardedProcess( 8415):    kcptun - client(with SMUX)
I/GuardedProcess( 8415): USAGE:
I/GuardedProcess( 8415):    kcptun [global options] command [command options] [arguments...]
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): VERSION:
I/GuardedProcess( 8415):    SELFBUILD
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): COMMANDS:
I/GuardedProcess( 8415):      help, h  Shows a list of commands or help for one command
I/GuardedProcess( 8415): GLOBAL OPTIONS:
I/GuardedProcess( 8415):    --localaddr value, -l value   local listen address (default: ":12948")
I/GuardedProcess( 8415):    --remoteaddr value, -r value  kcp server address (default: "vps:29900")
I/GuardedProcess( 8415):    --key value                   pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
I/GuardedProcess( 8415):    --crypt value                 aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, none (default: "aes")
I/GuardedProcess( 8415):    --mode value                  profiles: fast3, fast2, fast, normal (default: "fast")
I/GuardedProcess( 8415):    --path value                  path to shadowsocks data dir (default: "/data/data/com.github.shadowsocks/protect_path")
I/GuardedProcess( 8415):    --conn value                  set num of UDP connections to server (default: 1)
I/GuardedProcess( 8415):    --autoexpire value            set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 60)
I/GuardedProcess( 8415):    --mtu value                   set maximum transmission unit for UDP packets (default: 1350) I/GuardedProcess( 8415):    --sndwnd value                set send window size(num of packets) (default: 128)
I/GuardedProcess( 8415):    --rcvwnd value                set receive window size(num of packets) (default: 1024)
I/GuardedProcess( 8415):    --datashard value             set reed-solomon erasure coding - datashard (default: 10)
I/GuardedProcess( 8415):    --parityshard value           set reed-solomon erasure coding - parityshard (default: 3)
I/GuardedProcess( 8415):    --dscp value                  set DSCP(6bit) (default: 0)
I/GuardedProcess( 8415):    --nocomp                      disable compression
I/GuardedProcess( 8415):    --log value                   specify a log file to output, default goes to stderr
I/GuardedProcess( 8415):    -c value                      config from json file, which will override the command from shell
I/GuardedProcess( 8415):    --help, -h                    show help
I/GuardedProcess( 8415):    --version, -v                 print the version
I/GuardedProcess( 8415):
W/GuardedProcess( 8415): process exit too fast, stop guard: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 82, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 87, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6ffffffe arg 0xdb8
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6ffffffe arg 0xf04
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): Incorrect Usage.
I/GuardedProcess( 8415): NAME:
I/GuardedProcess( 8415):    kcptun - client(with SMUX)
I/GuardedProcess( 8415): USAGE:
I/GuardedProcess( 8415):    kcptun [global options] command [command options] [arguments...]
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): VERSION:
I/GuardedProcess( 8415):    SELFBUILD
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): COMMANDS:
I/GuardedProcess( 8415):      help, h  Shows a list of commands or help for one command
I/GuardedProcess( 8415): GLOBAL OPTIONS:
I/GuardedProcess( 8415):    --localaddr value, -l value   local listen address (default: ":12948")
I/GuardedProcess( 8415):    --remoteaddr value, -r value  kcp server address (default: "vps:29900")
I/GuardedProcess( 8415):    --key value                   pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
I/GuardedProcess( 8415):    --crypt value                 aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, none (default: "aes")
I/GuardedProcess( 8415):    --mode value                  profiles: fast3, fast2, fast, normal (default: "fast")
I/GuardedProcess( 8415):    --path value                  path to shadowsocks data dir (default: "/data/data/com.github.shadowsocks/protect_path")
I/GuardedProcess( 8415):    --conn value                  set num of UDP connections to server (default: 1)
I/GuardedProcess( 8415):    --autoexpire value            set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 60)
I/GuardedProcess( 8415):    --mtu value                   set maximum transmission unit for UDP packets (default: 1350) I/GuardedProcess( 8415):    --sndwnd value                set send window size(num of packets) (default: 128)
I/GuardedProcess( 8415):    --rcvwnd value                set receive window size(num of packets) (default: 1024)
I/GuardedProcess( 8415):    --datashard value             set reed-solomon erasure coding - datashard (default: 10)
I/GuardedProcess( 8415):    --parityshard value           set reed-solomon erasure coding - parityshard (default: 3)
I/GuardedProcess( 8415):    --dscp value                  set DSCP(6bit) (default: 0)
I/GuardedProcess( 8415):    --nocomp                      disable compression
I/GuardedProcess( 8415):    --log value                   specify a log file to output, default goes to stderr
I/GuardedProcess( 8415):    -c value                      config from json file, which will override the command from shell
I/GuardedProcess( 8415):    --help, -h                    show help
I/GuardedProcess( 8415):    --version, -v                 print the version
I/GuardedProcess( 8415):
W/GuardedProcess( 8415): process exit too fast, stop guard: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 87, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 90, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6ffffffe arg 0xdb8
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/tun2socks: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6ffffffe arg 0xf04
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/kcptun: unused DT entry: type 0x6fffffff arg 0x1
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): start process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6ffffffe arg 0x151c
I/GuardedProcess( 8415): WARNING: linker: /data/data/com.github.shadowsocks/ss-local: unused DT entry: type 0x6fffffff arg 0x2
I/GuardedProcess( 8415): Incorrect Usage.
I/GuardedProcess( 8415): NAME:
I/GuardedProcess( 8415):    kcptun - client(with SMUX)
I/GuardedProcess( 8415): USAGE:
I/GuardedProcess( 8415):    kcptun [global options] command [command options] [arguments...]
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): VERSION:
I/GuardedProcess( 8415):    SELFBUILD
I/GuardedProcess( 8415):
I/GuardedProcess( 8415): COMMANDS:
I/GuardedProcess( 8415):      help, h  Shows a list of commands or help for one command
I/GuardedProcess( 8415): GLOBAL OPTIONS:
I/GuardedProcess( 8415):    --localaddr value, -l value   local listen address (default: ":12948")
I/GuardedProcess( 8415):    --remoteaddr value, -r value  kcp server address (default: "vps:29900")
I/GuardedProcess( 8415):    --key value                   pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
I/GuardedProcess( 8415):    --crypt value                 aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, none (default: "aes")
I/GuardedProcess( 8415):    --mode value                  profiles: fast3, fast2, fast, normal (default: "fast")
I/GuardedProcess( 8415):    --path value                  path to shadowsocks data dir (default: "/data/data/com.github.shadowsocks/protect_path")
I/GuardedProcess( 8415):    --conn value                  set num of UDP connections to server (default: 1)
I/GuardedProcess( 8415):    --autoexpire value            set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 60)
I/GuardedProcess( 8415):    --mtu value                   set maximum transmission unit for UDP packets (default: 1350) I/GuardedProcess( 8415):    --sndwnd value                set send window size(num of packets) (default: 128)
I/GuardedProcess( 8415):    --rcvwnd value                set receive window size(num of packets) (default: 1024)
I/GuardedProcess( 8415):    --datashard value             set reed-solomon erasure coding - datashard (default: 10)
I/GuardedProcess( 8415):    --parityshard value           set reed-solomon erasure coding - parityshard (default: 3)
I/GuardedProcess( 8415):    --dscp value                  set DSCP(6bit) (default: 0)
I/GuardedProcess( 8415):    --nocomp                      disable compression
I/GuardedProcess( 8415):    --log value                   specify a log file to output, default goes to stderr
I/GuardedProcess( 8415):    -c value                      config from json file, which will override the command from shell
I/GuardedProcess( 8415):    --help, -h                    show help
I/GuardedProcess( 8415):    --version, -v                 print the version
I/GuardedProcess( 8415):
W/GuardedProcess( 8415): process exit too fast, stop guard: ArrayBuffer(/data/data/com.github.shadowsocks/kcptun, -r, VPS-SS-LIBEV-SERVER_IP_PORT, -l, 127.0.0.1:1170, --path, /data/data/com.github.shadowsocks/protect_path, --conn, 1, --autoexpire, 10 , --key, KCPKEY, --crypt, aes, --mtu, 1350, --sndwnd, 128, --rcvwnd, 1024, --datashard, 70, --parityshard, 30, --dscp, 0, --nocomp, --mode, manual, --nodelay, 0, --resend, 0, --interval, 50, --nc, 1)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/data/com.github.shadowsocks, -c, /data/data/com.github.shadowsocks/ss-local-udp-vpn.conf, -A)
I/GuardedProcess( 8415): thread interrupt, destroy process: ArrayBuffer(/data/data/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 90, --tunmtu, 1500, --sock-path, /data/data/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)

**Comment by madeye** [comment]
Is there any special character in your KCPKEY?

**Comment by peakvision** [comment]
No, pure upper and lower case letters with numbers.

**Comment by madeye** [comment]
There is a special character after --autoexpire 10.

https://www.diffchecker.com/EZlCc7Ay

**Comment by peakvision** [comment]
AH, thanks. Changing to chcp 437, a character "┬á" is shown.
I check the original .bat file which the parameters are copied from, after "10" are two spaces(u+0020 u+0020). Maybe it's involved with email html formats.
