### ISSUE TITLE
kcptun is not working

### ISSUE THREAD

**Issue by Diaboli** [shadowsocks/shadowsocks-android#952]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "5.0.2"
* Device: HTC M7
* Shadowsocks version: *version code "v3.2.4"
* Last version that did not exhibit the issue (if applicable):

### Configuration

server-kcptun:
     "nocomp": false

client-kcptun:
     --nocomp false

server-kcptun.log:
    2016/10/23 09:23:01 remote address: XX.XX.XX.XX:36040
    2016/10/23 09:23:01 broken pipe

At this point shadowsocks can not connection to the network.
But delete "--nocomp false" in the client-kcptun configuration, shadowsocks is working.

**Comment by madeye** [comment]
It should be just '--nocomp'.

**Comment by Diaboli** [comment]
I tried, but the result remains the same.

**Comment by wang20150419** [comment]
I encountered the same problem. version: 3.2.7, delete "--nocomp", it works fine.

**Comment by madeye** [comment]
When you set 'nocomp: false' on the server, it means "enable compression".

When you add '--nocomp' to the client, is means "disable compression".

The confusion is caused by upstream, you may open an issue there.
