### ISSUE TITLE
Auto connect on start-up not working

### ISSUE THREAD

**Issue by guibog** [shadowsocks/shadowsocks-android#953]
### Environment

* Android version: Android 4.4.4 - CyanogenMod 11-20141112-SNAPSHOT-M12-hlte
* Device: Galaxy Note 3
* Shadowsocks version: *version code "v3.2.4"
* Last version that did not exhibit the issue (if applicable):

### Configuration

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-256-CFB
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [x ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Check "auto-connect" setting, boot the phone. Tried 3 times.

### What did you expect to see?

After reboot, I expect a VPN key logo in top bar, and shadowsocks connected, or at least the security pop-up "do you trust shadowsock".

### What did you see instead?

No VPN key logo in top bar, shadowsocks not auto connected, had to connect manually.

Note: my phone is rooted, I have Xposed, so maybe this is a problem with the security pop-up, which I could bypass using Xposed? (But if auto-connect is not possible, maybe the option in settings should be grayed)

**Comment by madeye** [comment]
This feature doesn't work on Android 4.4. Try Android 5.0 or above.

**Comment by guibog** [comment]
Ok thanks. Would there be a way to disable this setting for Android < 5.0?

**Comment by madeye** [comment]
My suggestion is to ignore this setting. Actually, the support of Android 4.x would be completely dropped in the near future.

**Comment by Mygod** [comment]
> Actually, the support of Android 4.x would be completely dropped in the near future.

Perhaps not so soon. 22.47% of the sessions now still uses Android 4.4 while only 3.56% uses 4.3. :angry:
