### ISSUE TITLE
安卓端老是断流，是不是配置不对？

### ISSUE THREAD

**Issue by 6656i** [shadowsocks/shadowsocks-android#954]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "5.1.1", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.2.3" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ x] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1312
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [x ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: enabled
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

KCP服务端配置
{
    "listen": ":YYYY",
    "target": "127.0.0.1:XXXX",
    "key": "**********.",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/var/log/kcptun/server.log"
}

客户端参数
--key "**********" --crypt salsa20 --mode fast2 --mtu 1350 --dscp 0 --parityshard 3

连接以后安卓经常断流，PC端则正常，是不是安卓端的参数我没设置对？

**Comment by 6656i** [comment]
检测网络连接时，报错误：SSL handshake time out.

**Comment by madeye** [comment]
Try `--autoexpire 10` in the client command line.

**Comment by 6656i** [comment]
客户端调小 --mtu 512 --sndwnd 256 --rcvwnd 256 ,似乎出现频率没那么高，但是不知道参数调小以后，有啥不良影响，比如会不会影响速度？

**Comment by madeye** [comment]
Smaller parameters mean smaller peak bandwidth. For some specific ISP, it may also influence QoS policy. Still, you'd try `--autoexpire 10`, it will help to solve NAT related connection loss.

**Comment by 6656i** [comment]
试过添加 --autoexpire 10，无明显效果，所以才调小上面的参数。可能是ISP原因，用4g流量就不怎么断流。

**Comment by madeye** [comment]
If so, you may try even smaller number, e.g. `--autoexpire 3`.

**Comment by 6656i** [comment]
应该是ISP问题，同样的配置拿给别人用了一天都没断流。
