### ISSUE TITLE
Guide to create configurations for Android shadowsocks

### ISSUE THREAD

**Issue by SirMiguelMr** [shadowsocks/shadowsocks-android#955]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

Android versión: Android lollipop 5.1.1,  "LinuxRom " custom Rom, Rom cooked by "juanpirulo"
Device: Sony Xperia Z1 C6903 
Shadowsocks version: 3.2.7 
Greetings, the reason for my contact with you is to ask them to please explain clearly how to create configurations for shadowsocks on Android.
I understand a VPS (Virtual Private Server) is required for this purpose, but my question lies in what the configuration that you have to perform to the VPS to function as shadowsocks server connection.
Thanks in advance
Note: excuse my bad English, my native language is Spanish, so I use the Google translator
### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by Mygod** [comment]
Shadowsocks is a general protocol so you just need to configure a normal Shadowsocks server. See [shadowsocks.org](https://shadowsocks.org) for more info.
