### ISSUE TITLE
Conflict with WiFi hotspot

### ISSUE THREAD

**Issue by kensenjiha** [shadowsocks/shadowsocks-android#956]
### Environment

* Android version: 6.0.1 (CM13.0)
* Device: xiaomi redmi 3
* Shadowsocks version: 3.2.7
* Last version that did not exhibit the issue (if applicable): 3.2.4 or so, not exactly

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
enable WiFi hotspot

### What did you expect to see?

WiFi hotspot and shadowsocks both work.

### What did you see instead?

1. WiFi hotspot clients suffers  from 
* unable to obtain ip address
* unable to access internet

2. after disabling shadowsocks, or doing a stop-and-start, WiFi hotspot clients may resume Internet access.

**Comment by madeye** [comment]
1. Update to the latest version.
2. Disable UDP forwarding.
3. Enable Per-app proxy, and use bypass mode.

**Comment by madeye** [comment]
Closed as inactive.

**Comment by kensenjiha** [comment]
sorry, but that doesn't resolve it. 
1. And 3.2.7 is the latest version. 
2. UDP Settings don't change anything
3. No luck either

**Comment by xiaoken** [comment]
well for me unchecking UDP settings would let me use the hotspot
but network connections from my PC didn't go through the ss server, but i guess that's normal.

**Comment by kensenjiha** [comment]
I finally got this solved. no need to disable UDP forwarding. steps:

1. enable NAT mode
1. connect then disconnect (very important, this refresh settings), 
1. disable NAT mode
1. connect.

**Comment by hydrandt** [comment]
2018: Use the "Apps VPN mode". Either you can select which apps' traffic will go through the vpn, or you can use the "Bypass Mode", where you select which apps' traffic will not go through the vpn. In both cases tethering will work.
