### ISSUE TITLE
北京移动4g经常无法访问外网

### ISSUE THREAD

**Issue by lostsnow** [shadowsocks/shadowsocks-android#957]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Device: Google Nexus 6P (没有root)
* Shadowsocks version: v3.2.7/v3.2.4
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [x] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: 
  * `-key xxx -crypt aes-128 -nocomp -datashard 70 -parityshard 30 -mtu 1400 -dscp 46 -mode manual -nodelay 0 -interval 40 -resend 0 -nc 1`
  * `-key xxx -crypt aes-128 -mode fast2 --nocomp`
  * disable
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you see instead?

在移动 4g 网络下 连接以后测试经常会提示 `unable to resolve host "www.google.com"` 无法上外网, 有时候会提示 `ssl handshake timed out`, 上述3种 kcp 设置都是如此

偶尔有时候打开飞行模式再关闭又好了, 有时候并不管用

使用 kcp 时尝试添加 `-autoexpire 10` 以及更改服务端端口到 21 等问题依然存在

同样的 server 同样的配置在另外一个联通手机(手机型号及系统/APP版本都一致)上使用正常, 使用 wifi 的时候也正常

**Comment by lostsnow** [comment]
我感觉好像是移动劣化了 udp, 不使用 kcp 不开启 udp 转发的时候 连通率会比较高, 但是不转发 udp 的话又会被 dns 污染, 感觉无解了...

**Comment by madeye** [comment]
I don't think you need to enable UDP forwarding. Without it, DNS should still work correctly.

**Comment by lostsnow** [comment]
ok, thx. but can not use kcp :(

**Comment by zinian** [comment]
我的好像移动限速了，基本就是几十K/S .....
