### ISSUE TITLE
Android client Per App access control not preventing apps

### ISSUE THREAD

**Issue by ipswitch8** [shadowsocks/shadowsocks-android#959]
* Android version: 6.0.1
* Device: BlackBerry Priv
* Shadowsocks version: 3.0.4 (Android client)

### Configuration

_Put an `x` inside the [ ] that applies._

* [X] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-256-CBP
* [X] One-time authentication
* Route
  * [X] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [X] IPv6 route
* [X] Per-App Proxy
  * [ ] Bypass mode
* [X] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Have two browser apps, one enabled for proxy, one not enabled

### What did you expect to see?
Enabled browser should get out through proxy (it does)
Other browser should have no network access

### What did you see instead?
Enabled browser gets out through proxy (good)
Other browser bypasses proxy and gets out directly (bad)

**Comment by Mygod** [comment]
I'm afraid this is the expected behavior.

**Comment by ipswitch8** [comment]
Then what is the "Bypass Proxy" switch used for?

**Comment by madeye** [comment]
Bypass proxy means connecting to the destination server directly, not through proxy.
