### ISSUE TITLE
能否提供一个自定义设置远端dns ip的功能？

### ISSUE THREAD

**Issue by leonliu315** [shadowsocks/shadowsocks-android#96]
我有几个vps连接8.8.8.8需要200ms，而连接opendns，或者4.2.2.2却只要10ms，还有就是udp能提供直接使用tun2socks里的udpgw的功能么？

**Comment by yebr** [comment]
2年前的请求，真心需要这个功能，应该是技术不可实现。

**Comment by codexss** [comment]
@yebr 
你试试在服务器上转发一下8888
```
iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to 158.69.209.100
iptables -t nat -A PREROUTING -d 8.8.8.8 -j DNAT --to 158.69.209.10
```
我这里看起来工作正常，DNS被成功的转发走了。

**Comment by yebr** [comment]
@codexss 谢谢，是的，我也是用了这个方法，应该用OUTPUT就可以，不需要PREROUTING：
https://github.com/shadowsocks/shadowsocks-android/issues/777#issuecomment-234708103

iptables -t nat -D OUTPUT -d 8.8.8.8 -j DNAT --to-destination 192.168.1.1

**Comment by shellus** [comment]
@yebr 你好，我在docker部署shadowsocks server。docker的linux内核不支持iptables -t nat。

请问你的新建lo接口是如何操作的？

**Comment by shellus** [comment]
好吧，我试过了。
route add -host 8.8.8.8 dev lo                              
SIOCADDRT: Operation not permitted
# 

一样是不行。该死的安卓客户端，为什么要写死8.8.8.8啊。真变态

**Comment by codexss** [comment]
ssr可以解决这个问题

娃娃脾气 <notifications@github.com>于2016年10月2日周日 20:36写道：

**Comment by shellus** [comment]
@codexss 你是说使用ssr的服务端和客户端吗？

还是只使用ssr的客户端就行？

我看过ssr的客户端，上面并没有dns设置的选项。

**Comment by codexss** [comment]
是粉色图标的那个吗？
zeronet打开shadowsocksr.bit下载客户端

娃娃脾气 <notifications@github.com>于2016年10月2日周日 20:44写道：

**Comment by shellus** [comment]
@codexss ok,搞定了，thanks。
因为我开始直接在github下载的版本低，所以没有dns设置选项。在shadowsocksr.bit下了新版就有了

但是可惜路由规则没有https://github.com/shadowsocks/shadowsocks-android的这样有“仅代理国内流量”的规则。

不过已经能用了就好，谢谢你。
