### ISSUE TITLE
关于DNS解析

### ISSUE THREAD

**Issue by 6656i** [shadowsocks/shadowsocks-android#960]
听说shadowsocks现在都是使用远程DNS解释。
于是我有个疑问：是全部路由（“全局”，“绕行中国大陆”等）都使用服务器的DNS，还是根据路由不同使用DNS？

因为同一个vps有几个人一起用。
我用全局代理，所以想用google dns。
而另外人大多用“绕行局域网及中国大陆”，114 dns会比较好。

如果程序是根据路由设置来选择dns，那就省事了。
如果是统一远程dns，是否可以在服务器安装dnsmasq来实现上面的目的？

**Comment by madeye** [comment]
You can simply assume only domains in GFWList is resolved remotely, otherwise resolved locally with local DNS.

If UDP relay enabled, all DNS requests would be forwarded to remote.

**Comment by 6656i** [comment]
@madeye 但是服务器端resolv.conf配置成8.8.8.8时，用“绕行局域网及中国大陆”模式，访问m.taobao.com会跳转国际版；而配置成114.114.114.114时，则不会跳转国际版。

**Comment by madeye** [comment]
Make sure you didn't enable UDP forwarding.

**Comment by madeye** [comment]
For Chrome, also make sure compression is not enabled.

**Comment by ajaxhe** [comment]
> For Chrome, also make sure compression is not enabled.

@madeye May I ask how make sure compression config in chrome? 

I also user shadowsocks-andriod client, the route configure as GFW list, disable UDP forwarding, remote DNS Server is my DNS Server which build as dnsmasq in centos vps.
but when use tcpdump tool in SS Server, and visite a fake domain such as www.not-exist-domain.com in Android Chrome, then I find SS Server try to send a DNS resolve request to my DNS Server.
My question is, www.not-exist-domain.com doesn't in GFW list, and UDP forwarding disabled, why the ss try to use remote DNS?

Thinks~
