### ISSUE TITLE
Inconsistent behavior (different behavior between two devices, elephone p7000 and xiaomi redmi note 2)

### ISSUE THREAD

**Issue by hironik** [shadowsocks/shadowsocks-android#962]
### Environment

* Android version: Android 5.0, Android 5.1 (cyanogen) (inconsistent behavior between two, which is subject of this report/question, see below)

* Device: Elephone P7000, Xiaomi Redmi 2

* Shadowsocks version: consistent across many versions (tested one by one from 2.10.8 to 3.2.7

* Last version that did not exhibit the issue (if applicable): Not found (tried)

### Configuration
 
* [x ] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ x] Client IPv6 availability
* Local port: 1080
* Encrypt method: CHACHA20 (does not affect behavior, several tried)
* [x ] One-time authentication
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ x] IPv6 route
* [ x] Per-App Proxy
  * [x ] Bypass mode (tried w/out per app proxy, no change)
* [x ] UDP Forwarding (tried without, no change)
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Okay, so I have two phones before me.

Elephone P 7000 with Android 5.0 based ROM 

Xiaomi Redmi Note 2 with the following ROMs

-  MIUI 7 6.5.27
- Cyanogenmod (5.1 Based, "Resurrection Remix")
- AOSP-based (Android 5.0, vova.vafin ROM)

Rooted
Installed Shadowsocks

Had the bright idea to lock down a specific app early on so it doesn't send anything before Shadowsocks start or in case shadowsocks has some issue.

Added the following iptables rule 

_iptables -t filter -A OUTPUT ! -o tun0 -p all -m owner --uid-owner [uid of an app] -j REJECT_

### What did you expect to see?

At least, I expected same behavior on both devices irrespective of ROM (whatever that might be)

Which did not happen.

### What did you see instead?

1)
On Elephone P7000 and RedmiNote2+Cyanogen the following behavior happens

app works when VPN connected, fails when VPN disconnects
(this is awesome and exactly what I want)

2)
On RedmiNote2+MIUI7 and on RedmiNote2+AOSP the following happens

app stops working. Completely.
(not good)

So
Questions:

a) which behavior is the "normal and expected" shadowsocks behavior?

b) is there a way to make it so it always behaves like described under 1)? (some ip rule trick or a switch somewhere) ?

**Comment by madeye** [comment]
a) Both of the behaviors are not expected. You should not add additional rules to iptables, which would cause compatibility issues.

b) Maybe you can try only blocking TCP traffic to avoid blocking the system wide DNS caching mechanism on Android 5.0 (or try 6.0 and above). But again, this kind of usage is not officially supported.

**Comment by madeye** [comment]
Closed as inactive.
