### ISSUE TITLE
这锅是该度娘背，还是。。。

### ISSUE THREAD

**Issue by 6656i** [shadowsocks/shadowsocks-android#963]
* Android version: 5.1.1
* Device: not4 n9100
* Shadowsocks version: 3.2.7

百度贴吧类似这些图片，开全局代理以后都无法显示。https://imgsa.baidu.com/forum/whfpf%3D106%2C106%2C40%3Bq%3D100%3Bg%3D0/sign=0cf61bc49125bc312b0852d838e2bc81/2946f21fbe096b63d727905a04338744ebf8acfa.jpg

是度娘屏蔽了海外ip，还是什么原因？
由于没有其他VPN，所以不能确定是不是SS的问题。

**Comment by madeye** [comment]
Tried your link on some servers outside China. No one can access the image. So, it'd be an issue of Baidu.

**Comment by xiaoken** [comment]
same here, should be link problem
