### ISSUE TITLE
How can i add values-ca , values-es,... and how work Pre-App proxy?

### ISSUE THREAD

**Issue by dhpark21** [shadowsocks/shadowsocks-android#966]
Hi.

Test version 3.2.7

1. I was testing multi language, but did not work(not translate) local language, i was make ~/res/values-ca/strings.xml

2. what is Pre-App Proxy function?
 and, how can Shawodsocks "Default" profile connect/disconnect request form external app?

Thanks.

**Comment by Mygod** [comment]
1. It should work that way. Create `src/main/res/values-ca/strings.xml` as well as `src/main/res/values-ca-v21/strings.xml` like other language does (it should still work without v21). Rebuild and deploy it on your device. Check your system language (it has to be Catalan).
2. Per-App proxy decide which app can go through proxy or connect directly.

**Comment by Mygod** [comment]
Oh sorry I just realized that if you want to test out the translation, you need to tweak [this line](https://github.com/shadowsocks/shadowsocks-android/blob/f70e905/build.sbt#L30) as well. See [this page I just added](https://github.com/shadowsocks/shadowsocks-android/wiki/Guidelines-for-translation-contributors) for further instructions.
