### ISSUE TITLE
Abnormal received bandwidth when watching YouTube

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#968]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.1 (NDE63P) [ROM](http://forum.xda-developers.com/oneplus-one/development/cm14-unoffical-nrd90m-t3461228)
* Device: OnePlus One (A0001)
* Shadowsocks version: f3a45816
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [x] IPv6 server address
* [ ] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method: chacha20
* [x] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [x] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

Note: DHCPv6 + NAT6 with OpenWrt.

### What did you do?

Stream 1080p YouTube video (a vlog).

### What did you expect to see?

After 1min, I should see at least 75MB received according to the fact that YouTube 1080p bitrate = 10-12Mbps.

### What did you see instead?

Only <400KB received. (the buffer has grown at least 0.5min)

**Comment by Mygod** [comment]
Seems like the issue only appears when route is set to all.

**Comment by madeye** [comment]
Hmm.. It's really hard for me to find a pure IPv6 environment.

Can we confirm that all traffic go through shadowsocks? If so, it would be an issue with shadowsocks-libev.

**Comment by Mygod** [comment]
Perhaps by manually disable IPv4 network with iptables, etc? I'm in an environment where IPv6 network is for free. 🍻🙃

I'm not sure. Let me check.

**Comment by madeye** [comment]
What about disabling UDP forwarding? I didn't count the traffic through UDP and YouTube may go through UDP with QUIC protocol.

**Comment by Mygod** [comment]
Yeah that works too. Why would changing route affect QUIC though?

Should we count UDP traffic as well?

**Comment by madeye** [comment]
Yes. I will push a fix later.

**Comment by Mygod** [comment]
Great. It's working properly now.
