### ISSUE TITLE
"Internet Unavailable" on Kindle fire 

### ISSUE THREAD

**Issue by nvl2val** [shadowsocks/shadowsocks-android#969]
Have read FAQ and I'm using CyanogenMod ROM, I don't know if my condition is [this](https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ#why-are-miui-emui-and-other-aosps-in-china-not-officially-supported). If not, below is my issure.

### Environment

* Android version: CyanogenMod 4.4 and 5.1.1
* Device: Kindle Fire HD 7(2nd gen)
* Shadowsocks version: 2.10.1 and 3.2.7
* Last version that did not exhibit the issue (if applicable):

### Configuration

* Local port: 1080
* Encrypt method: AES-256-CFB

I only configure "Server", "Remote Port", "Local Port", "Password" and "Encrypt Method", and the other settings are default. The same setting profile works fine on my RedMi 3s, but doesn't work on my kindle fire tablet.

### What did you do?
After having installed this app and configured it with the above settings, I checked the connectivity.

### What did you expect to see?
Valid network connection.

### What did you see instead?
Internet Unavailable and a Toast with text——"Failed to detect internet connection: failed to connect to www.google.com..."

**Comment by madeye** [comment]
It looks an issue of your device. For example, broken VPN service implementation.

Maybe you can try other ROMs.

**Comment by nvl2val** [comment]
Thank you for your quick response. 

I have tried three ROMs, and they all don't work. By the way, what may result in "broken VPN service implementation"? Is there any way to check that(I know some android development)? Can I fix that?

**Comment by madeye** [comment]
It mean the ROM you're using has bugs. But no one knows what the bug is.

**Comment by nvl2val** [comment]
Okay, that's a shame.

**Comment by nvl2val** [comment]
Okay, that's a shame.

**Comment by user-e** [comment]
Had a very similar problem on Kindle Fire HDX (standard ROM, not rooted/customized).
