### ISSUE TITLE
如何贡献翻译

### ISSUE THREAD

**Issue by yyxida** [shadowsocks/shadowsocks-android#971]
想写下日语的翻译，但是我不会编程，只能翻译文本，请该怎样贡献翻译

**Comment by Mygod** [comment]
Add src/main/values-ja/strings.xml and src/main/values-ja-v21/strings.xml.

**Comment by yyxida** [comment]
ありがとうございます。

**Comment by sunsysjp** [comment]
yyxida，你好
目前的日文翻译有一些不是日文的使用习惯，以及功能说明里还存在中文。
如果需要的话，我可以帮你完善日文翻译。大家一起把ss让更多的人用起来。

**Comment by yyxida** [comment]
当然可以，感谢你的帮助。可以的话，请留下你的qq联系方式吗？我也可以交流学习一下。

**Comment by sunsysjp** [comment]
嗯嗯，好啊。
你加我微信或者LINE吧。
微信 ID（QQ ID）：178495495
LINE ID：sunsysjp
我是日籍华裔，几年前在日本富士通上过班，所以对网络这块我也一直在大陆的时候用SS，在日本也有自己的服务器。
比较支持作者，这次看到你给作者提供翻译，觉得我应该也可以协助你一起完善，所以给了作者邮件后他让我在贴里面回复的。

2016-12-03 17:30 GMT+07:00 yyxida <notifications@github.com>:
