### ISSUE TITLE
[feature_request]在解析中国境内域名时希望能使用Chinadns

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-android#972]
在解析中国境内域名时希望能使用Chinadns：
类似抱怨DNS解析问题的ticket有很多，我注意到glzjin尝试使用了chinadns作为上游dns，解析国内网址时不会再出现错误解析到国外cdn节点等情况，自然链接速度也有很大改观，希望这个feature能够加入，在全局模式时可以禁用，bypass国内流量时启用，参数可以让使用者调节。
相关ticket
#960
相关项目
https://github.com/glzjin/shadowsocksr-android
最后感谢您对此项目的开发。

**Comment by madeye** [comment]
From the very beginning, shadowsocks-android resolves all the "Chinese sites" locally as you said. The details of how it works can also be found in the issue you listed.

**Comment by simonsmh** [comment]
在使用过程中，我没有启用UDP转发和chrome的流量节省，使用时我也没有经历过那么多的DNS解析问题。然而，我想咨询一下使用chinadns对其他用户出现的问题作为解决方法解决的可能性，毕竟chinadns在路由器上的表现有目共睹。

**Comment by madeye** [comment]
You didn't have DNS related issues, because shadowsocks-android already did the "China DNS" you called automatically in the background.

**Comment by simonsmh** [comment]
回去找了一下commit，果然是我会错意了QWQ
感谢您的解答。

**Comment by pexcn** [comment]
希望在开启了 UDP 转发的时候，UDP 的流量能按照「绕过局域网及中国大陆地址」这样。
现在的情况是当我选择「绕过局域网及中国大陆地址」并且开启了「UDP 转发」访问 baidu.com 搜索 ip 查询自己的 ip, 显示的 ip 是 server 的 ip.
