### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by phengchen** [shadowsocks/shadowsocks-android#974]
make: *** No rule to make target `jni/libancillary/fd_recv.c', needed by `obj/local/armeabi-v7a/objs/ancillary/libancillary/fd_recv.o'.  Stop.

**Comment by madeye** [comment]
`git submodule update --init`

**Comment by aeroxy** [comment]
I ran into the same issue and `git submodule update --init` doesn't solve it.

**Comment by aeroxy** [comment]
I think this is due to the fact some of the submodule are updating, making the older commits become unadvertised, and therefore cannot be fetched. As a result the new submodule would be used after git reset --hard, of which causes the error.

**Comment by kimw** [comment]
@aeroxy Nope. See #1482
