### ISSUE TITLE
shadowsocks-android开着的情况下会拦截其它程序的UDP包吗

### ISSUE THREAD

**Issue by itian** [shadowsocks/shadowsocks-android#975]
我有一个程序 网络模块使用了enet(也是一个可靠UDP)  在shadowsocks-android开着的情况下(使用绕过局域网和中国大陆地址) enet连接我在国内的阿里云地址 永远连接失败 如果关了shadowsocks-android就一切正常

**Comment by madeye** [comment]
Make sure your server supports UDP and enable "UDP forwarding" in your client.

**Comment by itian** [comment]
哦 研究了一下 好了 ss要开着udp转发 服务器也要iptables -A INPUT -p udp --dport 监听的端口号 -j ACCEPT
