### ISSUE TITLE
UDP转发问题

### ISSUE THREAD

**Issue by itian** [shadowsocks/shadowsocks-android#976]
UDP转发 使用绕过局域网和中国大陆地址选项后 UDP还是通过软件内设置的代理服务器转发的 这种情况正常吗

**Comment by madeye** [comment]
It's expected.

**Comment by Mygod** [comment]
Off-topic question: It's been 1 month since last release. Time to push out a new one? (CM14.1 is already in the air)

**Comment by madeye** [comment]
@Mygod Let me schedule a release this weekend.
