### ISSUE TITLE
Abnormal battery comsuption

### ISSUE THREAD

**Issue by chenming1986** [shadowsocks/shadowsocks-android#985]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 6.0.1 with Google services (stock Taiwan ROM)
* Device: Samsung Galaxy S6 edge
* Shadowsocks version: reproduced on all recent versions from Play Storesince several months ago
* Last version that did not exhibit the issue (if applicable): Unknown

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [x] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [x] TCP Fast Open
* [ ] NAT mode

### What did you do?
1, keep WIFI connection to my home router that has ss + kcptun enabled, so my cell phone always has connrctivity to google services even when the ss on it is turn off
2, enable ss one the phone, leave it in idle overnight（~8 hours), check the battery consumption
3, disable ss on the phone, leave it in idle for the same duration as step 2, check the battery comsuption again

### What did you expect to see?
battery comsuption in step 2 and 3 should be similiar

### What did you see instead?
battery consumption is step 2 is dramatically higher than in step 3. With ss on, the battery dropped ~30% in 8 hours, while without ss it only dropped 5%. Google services should not be the problem since my home wifi always has connectivity to Google.
Switching to cellular network didn't make things better. This issue has been around for ~2 months but I can't remember the exact date since I thought the battery was dead in the first place

**Comment by Mygod** [comment]
kcptun is expected to drain battery faster. Could you do an experiment with kcptun disabled?

Btw does this indicates that kcptun prevents the device going to doze? @madeye

**Comment by chenming1986** [comment]
Tried with kcptun disabled, the issue persists. Any logs that I can capture? Is this issue specific to my device?

**Comment by Mygod** [comment]
Could you [dump battery logs](https://developer.android.com/studio/profile/battery-historian.html)?

```
adb shell dumpsys batterystats > batterystats.txt
```

**Comment by chenming1986** [comment]
I tried with the latest 3.2.8 release. Seems the issue is gone... Closing
