### ISSUE TITLE
Drop database schema of pre-release versions (17 <= oldVersion < 20)

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-android#987]
@Mygod 

Recently, I have received many feedbacks that the users upgrading their app from quite old versions would get the local database corrupted.

I'm thinking about just dropping the schema of all the pre-release (17 <= oldVersion < 19) in the next version. Any suggestion?

**Comment by madeye** [comment]
Also, this won't cause any issue for users upgrading from 2.x versions.

**Comment by Mygod** [comment]
Can you reproduce that issue? Maybe we don't have to drop support for those.

**Comment by madeye** [comment]
Nope, but I didn't get a chance to test every combination.

I think it may be also related to our database backup mechanism, which backup and restore the sqlite file directly.

**Comment by Mygod** [comment]
Hmm but why do you think removing support for those versions would fix the issue? (and even if it does, I still prefer not to removing them)

What database backup mechanism?

**Comment by madeye** [comment]
Another assumption is about the conflict of the default value of a column.

In ormlite, we should define default value in the annotation, but we don't. However, when upgrading the database, we alter the database by adding some columns with default value. I'm not sure if it would cause any conflict of schema.

**Comment by madeye** [comment]
The backup agent backups and restores the whole database as a file. If one user downgrade to a previous version with the new database file already in the cloud, we may get errors.

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ShadowsocksBackupAgent.scala

**Comment by Mygod** [comment]
We shouldn't support downgrading. If a user decide to downgrade, he/she should manually clear app data.

Yes that conflict is there but it shouldn't cause error for upgrading from a really old version (and skipping multiple versions) since my database is also upgraded from old versions.

**Comment by madeye** [comment]
Another issue is introduced from third-party forks. If someone installed [this app](https://github.com/glzjin/shadowsocksr-android/blob/nokcp/src/main/scala/com/github/shadowsocks/ShadowsocksBackupAgent.scala), we would get our database corrupted when restoring.

**Comment by madeye** [comment]
What about adding a hint for users that have corrupted database? Guide them to clear the app data?

**Comment by Mygod** [comment]
That fork has a different package name so its app data will never corrupt ours. But it's very likely that somebody made an unofficial fork and distributed it (without user's knowledge) that's incompatible with our upgrades.

I'm currently waiting for someone who can reproduce this issue to report it.

Yes. That's a good idea. Let's do that if that's possible.

**Comment by Mygod** [comment]
Actually we could show a dialog on start up if database corruption is detected. And if user decides that he/she doesn't want to keep the data, we can destroy the database and recreate a new one.

**Comment by madeye** [comment]
Yes, that's what I mean.

**Comment by madeye** [comment]
I saw a lot of `SQLiteCantOpenDatabaseException` in the Analytics when `getProfile()`, which seems the problem.

**Comment by madeye** [comment]
Another exception is `SQLiteException (@DBHelper:onUpgrade:131) {main}`, which happens more than 100k times a day. it seems caused by failure of database upgrading command on some devices.

**Comment by Mygod** [comment]
Hmm... So should we close this for now?

**Comment by madeye** [comment]
OK. Let me release a new version and see what will happen.
