### ISSUE TITLE
Nexus 6p 7.1.1 NPF26F

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-android#988]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [*] IPv4 server address
* [ ] IPv6 server address
* [*] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:aes-256-cfb
* [*] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [*] GFW List
  * [ ] China List
* [*] IPv6 route
* [ ] Per-App Proxy
  * [*] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [*] Auto Connect
* [*] TCP Fast Open
* [ ] NAT mode

### What did you do?
打开了TFO，supersu日记显示success

### What did you expect to see?
android 7.1.1 能够正常开启TFO

### What did you see instead?
说是success了，但是过几秒立即卡死重启，重启后日记还是success，但是过1分钟左右还是重启了，关了TFO后这种问题没有了

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/847
