### ISSUE TITLE
二维码备注

### ISSUE THREAD

**Issue by pyrrhudite** [shadowsocks/shadowsocks-android#989]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!
### What did you expect to see?
你好，未来的版本会支持remarks吗？每次都要自己重新写备注真的是很麻烦

**Comment by Mygod** [comment]
Could we use # for remark perhaps?

**Comment by madeye** [comment]
I'm OK with that. Let's open an issue in shadowsocks-org and update the spec on the official site.
