### ISSUE TITLE
Could you please change option "KCP port" from wheel to textbox

### ISSUE THREAD

**Issue by Kuroko-Komeiji** [shadowsocks/shadowsocks-android#990]
I use port in 1024 and its default value is 8399. I tried to slide for more than 5 minutes to reach value in 1000.
I think it better to be a textbox and check if value is valid ( is integer between 1 and 65535 ) 
Same for all option for ports. Thank you very much.

**Comment by Mygod** [comment]
https://memegenerator.net/instance/25885886
