### ISSUE TITLE
如何禁用China DNS

### ISSUE THREAD

**Issue by jiuxiaxixi** [shadowsocks/shadowsocks-android#991]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you see instead?
因为代理的服务器无法访问国外网站 总是会弹出校园网认证

**Comment by madeye** [comment]
Enable UDP forwarding.

**Comment by jiuxiaxixi** [comment]
感谢 我试试

**Comment by jiuxiaxixi** [comment]
服务器端用ss-server 也Enable UDP forwarding.

**Comment by jiuxiaxixi** [comment]
加上之后无法联通服务器了 
网络环境：校园网 未认证 Dr.com 可以直连校园内某台服务器 服务器可以访问外网

**Comment by madeye** [comment]
Double check the configs of your ss-server and your server's firewall rules. Make sure UDP forwading is enabled and UDP traffic is allowed.

**Comment by jiuxiaxixi** [comment]
如果 配置为仅代理中国大陆地址 就可以上网 不开UDP转发

**Comment by jiuxiaxixi** [comment]
iOS shadowsrockt没有问题

**Comment by madeye** [comment]
Try this on your server:

```
iptables -t nat -A OUTPUT -d 8.8.8.8 -j DNAT --to-destination 114.114.114.114
```
