### ISSUE TITLE
请问“绕开中国地址”和“仅代理中国无法访问的地址”有什么区别？

### ISSUE THREAD

**Issue by yebr** [shadowsocks/shadowsocks-android#992]
"绕开中国地址"我理解的是，给系统路由表添加上除中国以外的路由，访问这些路由就通过ss。
“仅代理中国无法访问的地址”我理解的是，首先使用本地访问，无法访问后（如何判定？gfwlist？）使用ss访问。
请问是这样吗？

哪一种访问速度更快？
哪一种消耗流量更低？

谢谢！

**Comment by ljl024** [comment]
根据我个人的理解
##绕开中国地址## 会根据是否为中国IP来决定数据包的转发(直接发出/发至代理端口)，但并非修改系统路由表，而是通过调用VPN接口，由shadowsocks-android来处理大部分数据包，根据特定规则将数据包发往不同的接口。

##仅代理中国无法访问的地址## 则是由解析过的gfwlist来决定转发数据包的方式(直接发出/发至代理端口)。

在实际使用中，并不能确定那一种方式访问更快，##仅代理中国无法访问的地址##理论上会消耗更少的服务器流量，但这与你实际访问的网站/服务有关。直接访问的地址越多，消耗的服务器流量就越少。两种模式对于移动数据流量的消耗都是接近的，shadowsocks采用的加密技术并不会显著增加传输流量，但网络情况不佳时重发数据包会消耗额外的流量。
使用kcptun功能会显著增加数据流量和耗电量。
如果你使用的服务器足够快且流量充裕，我建议你使用##绕开中国地址##模式，这会为你访问国际互联网带来更好的体验。
当服务器负载过重/服务器的链路质量不佳时，采用##仅代理中国无法访问的地址##模式有时会有更好的表现。

**Comment by yebr** [comment]
@ljl024 很详细，非常感谢！
