### ISSUE TITLE
请问如何查看已经配置过的密码？想导出给pc用

### ISSUE THREAD

**Issue by W-quan** [shadowsocks/shadowsocks-android#995]

**Comment by Mygod** [comment]
You can't and you shouldn't be able to. If you have root, see
databases/profiles.db in this app's data dir.

**Comment by ljl024** [comment]
You can't get the password in shadowsocks-android directly.
But you can get a QR code of the server with share function, have a screenshot and use shadowsocks-windows to decode it (open the screenshot file on your PC and scan the QR code on your screen with shadowsocks-windows).
You can also copy the url(in share function) and use base64 decode tool to decode the string after ss://  to get raw string which include password , server address and port.

**Comment by W-quan** [comment]
thank you.
