### ISSUE TITLE
Try to make "Restrict background data" work with Shadowsocks

### ISSUE THREAD

**Issue by m13253** [shadowsocks/shadowsocks-android#996]
* Android version: Android 6.0.1, CyanogenMod 13.0

In Settings → Data → Top-right menu, we can apply background data restrictions, which will be useful if you accidentally run out of your monthly data plan.

However this option does not work with Shadowsocks because the VPN always runs in the background, causing *all* other apps to be offline.

I am wondering if we can manage to make it work. I am not sure if there are any API to bypass the restriction for a single app. But I think it would be possible if we implement a similar feature in Shadowsocks. Here is my idea:

First the user turn on a switch in Shadowsocks app. Whenever an activity switch happens, allow all network requests from the app of the new activity, then (optionally after some timeout), drop all network requests from the old app, if the old app is not opened during the timeout.

I wonder if you are interested in this feature. I am happy to discuss about it.

Anyway, thanks for this piece of wonderful software!

**Comment by Mygod** [comment]
Shadowsocks works fine with system data saver. Tested on cm14.1.
