### ISSUE TITLE
coolapk.com 解析出来的IP被识别成非国内IP段而走了代理服务器

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-android#997]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
6.0
* Device: *e.g. Google Pixel XL*
Nexus 5
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
3.2.7

* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [X] IPv4 server address
* [ ] IPv6 server address
* [X] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [X] Bypass LAN & China
  * [X ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

访问coolapk.com，解析出来的IP是 118.178.34.76，已经勾选了Bypass LAN & China或者GFW List

### What did you expect to see?

不通过SS服务器访问，而是直连

### What did you see instead?

通过代理访问

**Comment by madeye** [comment]
1. 118.178.34.76 is an IP of Aliyun located at Shenzheng.
2. I cannot reproduce the issue with both Bypass CHN and GFW LIST modes.

**Comment by myliyifei** [comment]
1 确实是阿里云的，所以正常应该是直连而不走代理。
2 在服务器上设置是无法访问CN的IP段，所以服务器的iptables的日志正好反馈处阻止该IP的118.178.34.76访问。这是按照规则产生的阻止日志，理论上如果该目标IP不走代理，根本不会产生该日志。
Dec  6 09:57:53 kernel: [4179314.457942] IPT REJ CN ADDR IN= OUT=eth0 SRC=xxx.xxx.xxx.xxx DST=118.178.34.76 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=58047 DF PROTO=TCP SPT=43907 DPT=80 WINDOW=42340 RES=0x00 SYN URGP=0 

客户端是3.2.7，之前几个版本也有同样问题，已经清空数据并完全重装了一遍，当前/data/data/com.github.shadowsocks/目录下面的文件可以看到的是bypass-lan-china.acl 和 gfwlist.acl等。

**Comment by pexcn** [comment]
有时候访问 baidu.com 也会有这个问题。

**Comment by fanthos** [comment]
I think its better to replace `^(.*\.)?` with `^(.*\.)*` in ACL file, because someone may use `aa.bb.blocked.com` as domain name.

**Comment by Mygod** [comment]
FYI . matches . as well.

**Comment by fanthos** [comment]
Sorry I didnt notice that
