### ISSUE TITLE
Add DNS server port configuration

### ISSUE THREAD

**Issue by changyp6** [shadowsocks/shadowsocks-android#998]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Set DNS address to 8.8.8.8 in the DNS config input

### What did you expect to see?
google address can be resolved correctly.

The GFW will respond to your DNS query before the real server if it detects you are query google address on port 53

If you query the address on an alternative port, the DNS query will not be alterred.

For example

dig @208.67.222.222 www.google.com
Will get an invalid address
dig @208.67.222.222 -p 5353 www.google.com
Will get a correct address

If the DNS configuration can add a port config, we can always get correct address.

### What did you see instead?
www.google.com is still resolved to an invalid address.

**Comment by madeye** [comment]
No plan for this.

DNS option is only for remote DNS resolution, which means you need to make sure no DNS poisoning on your remote server. Actually, if you have DNS poisoning issue on your server, you still cannot access blocked sites.

**Comment by changyp6** [comment]
Thanks for your quick reply!

What does "Remote DNS" mean?
Does it mean that the DNS server is used by the server?

Max Lv <notifications@github.com>于2016年12月7日 周三 20:58写道：

**Comment by madeye** [comment]
Right.
